import ResearchLean.AG.ObstructionDiagnosticBridge.SpecifiedAffineObstruction
import Formal.AG.Cohomology.GluingMismatch
import Mathlib.Algebra.FreeAbelianGroup.Finsupp
import Mathlib.RingTheory.MvPolynomial.Basic
import Formal.Util.AssertStandardAxioms

/-!
# Existing obstruction-class provenance for the affine local data

This module connects the selected affine local data to the existing
`Cohomology.GluingMismatchData`, `descentCocycle`, and
`descentObstructionClass` construction.  The chart state determines an integer
point of the polynomial law ring whose relation ideal is generated by the
primitive presentation relations.  The overlap comparison is the affine
transition plus the difference of the two chart states, so its existing gluing
mismatch cochain is exactly `actualMismatch`.
-/

noncomputable section

namespace AAT.AG.ObstructionDiagnosticBridge

open CanonicalResolution Cohomology ResolutionInvariance TwoPhase

universe u

namespace GeneratorPresentation

variable {Source : Type u} [Fintype Source]
variable {q : Reading Source} {laws : FiniteLawFamily Source}
variable {U : AtomCarrier.{u}} {A : ArchitectureObject U}
variable {S : Site.AATSite A}
variable {D : TargetSupportedNerve q} {G : ContextOpenSupport S}
variable [IsEmpty D.nerve.FaceComponent]
variable {P : GeneratorPresentation laws} {C : FaceEmptyAATCechCover D G}

/-- Polynomial ring whose variables are the primitive presentation generators. -/
abbrev AffineLawRing (laws : FiniteLawFamily Source) :=
  MvPolynomial (PrimitiveGenerator laws) ℤ

/-- Relation ideal generated by `X_left - X_right` for every primitive relation. -/
def affineLawIdeal (P : GeneratorPresentation laws) : Ideal (AffineLawRing laws) :=
  Ideal.span {f | ∃ left right, P.relation left right ∧
    f = MvPolynomial.X left - MvPolynomial.X right}

namespace ActualCechAffineLocalData

/-- The presentation-valued chart state read as integral coordinates on relation blocks. -/
def chartBlockState (x : ActualCechAffineLocalData P C)
    (chart : D.nerve.Chart) : P.Block → ℤ :=
  letI := C.chartSupportNonempty chart
  letI := C.chartSupportPreconnected chart
  fun block =>
    FreeAbelianGroup.coeff block
      (P.presentationToBlocks
        (P.aatLocallyConstantObstructionSectionEquiv G (C.chartContext chart)
          (x.localState chart)))

/-- Evaluation of the affine law ring at the integral state of one chart. -/
def chartLawEvaluation (x : ActualCechAffineLocalData P C)
    (chart : D.nerve.Chart) : AffineLawRing laws →+* ℤ :=
  MvPolynomial.eval₂Hom (RingHom.id ℤ)
    (fun generator => x.chartBlockState chart (P.blockOf generator))

/-- Existing lawful-section data represented by one selected chart state. -/
def chartLawfulSection (x : ActualCechAffineLocalData P C)
    (chart : D.nerve.Chart) :
    LawAlgebra.LawfulLocus.LawfulSectionData (AffineLawRing laws) P.affineLawIdeal where
  SectionRing := ℤ
  commRing := inferInstance
  pullback := x.chartLawEvaluation chart

omit [Fintype Source] in
/-- Primitive presentation relations make every selected chart state lawful. -/
theorem chartLawfulSection_lawful (x : ActualCechAffineLocalData P C)
    (chart : D.nerve.Chart) : (x.chartLawfulSection chart).Lawful := by
  rw [LawAlgebra.LawfulLocus.LawfulSectionData.Lawful,
    LawAlgebra.LawfulLocus.LawfulSectionData.pulledObstructionIdeal,
    Ideal.map_eq_bot_iff_le_ker]
  change P.affineLawIdeal ≤ RingHom.ker (x.chartLawEvaluation chart)
  rw [affineLawIdeal, Ideal.span_le]
  rintro f ⟨left, right, hrelation, rfl⟩
  change x.chartLawEvaluation chart
      (MvPolynomial.X left - MvPolynomial.X right) = 0
  rw [map_sub, sub_eq_zero]
  change
    (MvPolynomial.eval₂Hom (RingHom.id ℤ)
        (fun generator => x.chartBlockState chart (P.blockOf generator)))
          (MvPolynomial.X left) =
      (MvPolynomial.eval₂Hom (RingHom.id ℤ)
        (fun generator => x.chartBlockState chart (P.blockOf generator)))
          (MvPolynomial.X right)
  rw [MvPolynomial.eval₂Hom_X', MvPolynomial.eval₂Hom_X']
  apply congrArg (x.chartBlockState chart)
  apply Quotient.sound
  exact Relation.EqvGen.rel left right hrelation

/-- Existing local-flatness package carried by the chart states. -/
def localFlatnessData (x : ActualCechAffineLocalData P C) :
    LocalFlatnessData C.toCoverRelativeCechCover (AffineLawRing laws) P.affineLawIdeal where
  localSection := x.chartLawfulSection
  lawful := x.chartLawfulSection_lawful

/-- Restriction witness for a selected chart state on one overlap. -/
def restrictedLawfulSection (x : ActualCechAffineLocalData P C)
    (edge : D.nerve.EdgeComponent) (chart : D.nerve.Chart) :
    RestrictedLocalLawfulSection x.localFlatnessData edge chart where
  restrictedSection := x.chartLawfulSection chart
  restrictsLocalSection :=
    x.chartLawfulSection chart = x.localFlatnessData.localSection chart
  restriction_holds := rfl
  restrictedLawful := x.chartLawfulSection_lawful chart

/--
The existing gluing-mismatch input whose affine comparison value is equation (1).
The restrictions are the lawful chart states above; the mismatch value is the
selected primitive transition plus the actual sheaf restriction difference.
-/
def gluingMismatchData (x : ActualCechAffineLocalData P C) :
    GluingMismatchData (P.aatLocallyConstantObstructionSheaf G)
      x.localFlatnessData where
  leftIndex := D.nerve.edgeLeft
  rightIndex := D.nerve.edgeRight
  leftRestriction := fun edge =>
    x.restrictedLawfulSection edge (D.nerve.edgeLeft edge)
  rightRestriction := fun edge =>
    x.restrictedLawfulSection edge (D.nerve.edgeRight edge)
  mismatch := fun edge _left _right => x.actualMismatch edge

omit [Fintype Source] in
/-- The existing gluing mismatch cochain is the affine actual mismatch. -/
theorem gluingMismatchCochain_eq_actualMismatch
    (x : ActualCechAffineLocalData P C) :
    x.gluingMismatchData.gluingMismatchCochain = x.actualMismatch :=
  rfl

/-- Existing descent cocycle attached to the affine lawful local data. -/
def existingDescentCocycle (x : ActualCechAffineLocalData P C) :
    (P.faceEmptyCechComplex C).CechCocycle 1 :=
  descentCocycle x.gluingMismatchData (P.faceEmptyCechComplex C)
    (by
      rw [x.gluingMismatchCochain_eq_actualMismatch,
        P.faceEmptyCech_d1_eq_zero C]
      rfl)

omit [Fintype Source] in
/-- The existing descent cocycle and the specified actual cocycle coincide. -/
theorem existingDescentCocycle_eq_actualCocycle
    (x : ActualCechAffineLocalData P C) :
    x.existingDescentCocycle = x.actualCocycle := by
  apply Subtype.ext
  exact x.gluingMismatchCochain_eq_actualMismatch

/-- Existing legacy descent-obstruction class for the selected lawful local data. -/
def existingDescentObstructionClass (x : ActualCechAffineLocalData P C) :
    (P.faceEmptyCechComplex C).CoverRelativeHn 1 :=
  descentObstructionClass x.gluingMismatchData (P.faceEmptyCechComplex C)
    (by
      rw [x.gluingMismatchCochain_eq_actualMismatch,
        P.faceEmptyCech_d1_eq_zero C]
      rfl)

/-- Additive reading of the existing descent-obstruction class. -/
def existingDescentAdditiveClass (x : ActualCechAffineLocalData P C) :
    (P.faceEmptyCechComplex C).AdditiveCechH1 :=
  (P.faceEmptyCechComplex C).additiveH1Class x.existingDescentCocycle

omit [Fintype Source] in
/-- The class used by B1--C2 is exactly the existing descent obstruction class. -/
theorem existingDescentAdditiveClass_eq_actualClass
    (x : ActualCechAffineLocalData P C) :
    x.existingDescentAdditiveClass = x.actualClass := by
  rw [existingDescentAdditiveClass, actualClass,
    x.existingDescentCocycle_eq_actualCocycle]

omit [Fintype Source] in
/-- Equality of existing obstruction classes is exactly equality of the additive classes used below. -/
theorem existingDescentObstructionClass_eq_iff_actualClass_eq
    (x y : ActualCechAffineLocalData P C) :
    x.existingDescentObstructionClass = y.existingDescentObstructionClass ↔
      x.actualClass = y.actualClass := by
  change
    (P.faceEmptyCechComplex C).cohomologyClassSucc 0 x.existingDescentCocycle =
        (P.faceEmptyCechComplex C).cohomologyClassSucc 0 y.existingDescentCocycle ↔
      x.actualClass = y.actualClass
  rw [(P.faceEmptyCechComplex C).cohomologyClassSucc_eq_iff_additiveH1Class_eq]
  change x.existingDescentAdditiveClass = y.existingDescentAdditiveClass ↔
    x.actualClass = y.actualClass
  rw [x.existingDescentAdditiveClass_eq_actualClass,
    y.existingDescentAdditiveClass_eq_actualClass]

#assert_standard_axioms_only
  AAT.AG.ObstructionDiagnosticBridge.GeneratorPresentation.ActualCechAffineLocalData

end ActualCechAffineLocalData
end GeneratorPresentation
end AAT.AG.ObstructionDiagnosticBridge
