import ResearchLean.AG.ResolutionInvariance.LawValueBlockDecomposition
import Mathlib.Logic.Relation
import Formal.Util.AssertStandardAxioms

/-!
# Generator relations for the obstruction--diagnostic bridge

This module begins the construction required by G-125(A--B).  The primitive
generators are the source occurrences of declared laws.  A presentation gives
relations between those generators, and the quotient by the equivalence
closure of the relations is the component set used for obstruction
coefficients.  Every primitive relation must preserve the actual
source-generated law-value label from `LawValueBlockDecomposition`.

The reflection condition is deliberately separate from the presentation data:
it says that generators with the same law-value label are connected by the
declared relations.  From this structural condition we derive, rather than
assume, the equivalence between relation components and law-value labels.

Implementation notes: `Relation.EqvGen` is used instead of accepting a setoid
as input, so the component relation is generated by the declared primitive
relations.  The law-value side reuses the existing `LawValueLabel`; an
independent copy of the diagnostic coordinate type would leave G-125(A)
unconnected from the existing generated diagnostic complex.
-/

noncomputable section

namespace AAT.AG.ObstructionDiagnosticBridge

open CanonicalResolution ResolutionInvariance

universe u

variable {Source : Type u}

/-- A primitive generator is one occurrence of one declared law on the source. -/
abbrev PrimitiveGenerator (laws : FiniteLawFamily Source) :=
  laws.Law × Source

/-- The existing source-generated diagnostic label of a primitive generator. -/
def PrimitiveGenerator.label (laws : FiniteLawFamily Source)
    (generator : PrimitiveGenerator laws) : LawValueLabel laws :=
  LawValueLabel.ofSource laws generator.1 generator.2

/--
G-125(A) presentation data: primitive generator relations that preserve the
actual law-value label.  Connectivity and reflection are not fields.
-/
structure GeneratorPresentation (laws : FiniteLawFamily Source) where
  /-- Primitive relation generating the obstruction coefficient components. -/
  relation : PrimitiveGenerator laws → PrimitiveGenerator laws → Prop
  /-- Every declared relation stays inside one source-generated law-value label. -/
  relation_preserves_label :
    ∀ ⦃left right⦄, relation left right →
      left.label laws = right.label laws

namespace GeneratorPresentation

variable {laws : FiniteLawFamily Source}

/-- Connectivity generated by the primitive relation. -/
def Related (P : GeneratorPresentation laws) :
    PrimitiveGenerator laws → PrimitiveGenerator laws → Prop :=
  Relation.EqvGen P.relation

/-- The relation-component set `B = π₀(R)` from the G-125 paper design. -/
abbrev Block (P : GeneratorPresentation laws) :=
  Quotient (Relation.EqvGen.setoid P.relation)

/-- The relation component containing one primitive generator. -/
def blockOf (P : GeneratorPresentation laws)
    (generator : PrimitiveGenerator laws) : P.Block :=
  Quotient.mk (Relation.EqvGen.setoid P.relation) generator

/-- Generated connectivity preserves the existing source-generated label. -/
theorem related_preserves_label (P : GeneratorPresentation laws)
    {left right : PrimitiveGenerator laws} (h : P.Related left right) :
    left.label laws = right.label laws := by
  induction h with
  | rel left right hrel => exact P.relation_preserves_label hrel
  | refl _ => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ihLeft ihRight => exact ihLeft.trans ihRight

/-- The law-value label induced on relation components. -/
def blockLabel (P : GeneratorPresentation laws) : P.Block → LawValueLabel laws :=
  Quotient.lift (fun generator => generator.label laws)
    (fun _ _ h => P.related_preserves_label h)

/-- Evaluation of the component label on a primitive generator. -/
@[simp]
theorem blockLabel_blockOf (P : GeneratorPresentation laws)
    (generator : PrimitiveGenerator laws) :
    P.blockLabel (P.blockOf generator) = generator.label laws :=
  rfl

/-- Every existing law-value label is represented by a primitive generator. -/
theorem primitiveGenerator_label_surjective (laws : FiniteLawFamily Source) :
    Function.Surjective (PrimitiveGenerator.label laws) := by
  intro label
  obtain ⟨source, hsource⟩ := label.generated
  refine ⟨⟨label.law, source⟩, ?_⟩
  apply LawValueLabel.ext laws
  · rfl
  · exact heq_of_eq hsource

/-- The component-label map is surjective before imposing reflection. -/
theorem blockLabel_surjective (P : GeneratorPresentation laws) :
    Function.Surjective P.blockLabel := by
  intro label
  obtain ⟨generator, hgenerator⟩ :=
    primitiveGenerator_label_surjective laws label
  exact ⟨P.blockOf generator, hgenerator⟩

/--
G-125(B) structural reflection condition `R_q`: equal law-value labels must be
connected by the declared primitive relations.  It contains no cohomology or
injectivity conclusion.
-/
def ReflectionCondition (P : GeneratorPresentation laws) : Prop :=
  ∀ left right,
    left.label laws = right.label laws → P.Related left right

/-- Under `R_q`, the generated component-label map is injective. -/
theorem blockLabel_injective (P : GeneratorPresentation laws)
    (hReflection : P.ReflectionCondition) :
    Function.Injective P.blockLabel := by
  intro left right hlabel
  refine Quotient.inductionOn₂ left right ?_ hlabel
  intro leftGenerator rightGenerator hgeneratorLabel
  apply Quotient.sound
  exact hReflection leftGenerator rightGenerator hgeneratorLabel

/--
G-125(A--B) presentation theorem: the structural reflection condition derives
the equivalence `π₀(R) ≃ Λ` between obstruction components and the existing
source-generated law-value labels.
-/
def blockLabelEquiv (P : GeneratorPresentation laws)
    (hReflection : P.ReflectionCondition) : P.Block ≃ LawValueLabel laws :=
  Equiv.ofBijective P.blockLabel
    ⟨P.blockLabel_injective hReflection, P.blockLabel_surjective⟩

/-- The derived equivalence evaluates a primitive component by its law value. -/
@[simp]
theorem blockLabelEquiv_blockOf (P : GeneratorPresentation laws)
    (hReflection : P.ReflectionCondition)
    (generator : PrimitiveGenerator laws) :
    P.blockLabelEquiv hReflection (P.blockOf generator) =
      generator.label laws :=
  rfl

end GeneratorPresentation

/-! ## Nonvacuity fixtures for the reflection condition -/

namespace ReflectionConditionFixtures

/-- A two-point source with one constant law, used only to test `R_q`. -/
abbrev FixtureSource := Bool

/-- The fixture law family has one law and one reached value. -/
def laws : FiniteLawFamily FixtureSource where
  Law := PUnit
  lawFintype := inferInstance
  Value := fun _ => PUnit
  valueDecidableEq := fun _ => inferInstance
  eval := fun _ _ => PUnit.unit

/-- Positive fixture: primitive relations are generated exactly by label equality. -/
def connected : GeneratorPresentation laws where
  relation := fun left right => left.label laws = right.label laws
  relation_preserves_label := by
    intro left right h
    exact h

/-- The positive fixture satisfies the structural reflection condition. -/
theorem connected_reflectionCondition : connected.ReflectionCondition := by
  intro left right hlabel
  exact Relation.EqvGen.rel left right hlabel

/-- The positive fixture relates two distinct primitive generators. -/
theorem connected_has_distinct_related_generators :
    ∃ left right : PrimitiveGenerator laws,
      left ≠ right ∧ connected.Related left right := by
  let left : PrimitiveGenerator laws := ⟨PUnit.unit, false⟩
  let right : PrimitiveGenerator laws := ⟨PUnit.unit, true⟩
  refine ⟨left, right, ?_, ?_⟩
  · intro h
    exact Bool.noConfusion (congrArg Prod.snd h)
  · apply Relation.EqvGen.rel
    apply LawValueLabel.ext laws
    · rfl
    · exact HEq.rfl

/-- Negative fixture: no primitive relation is declared. -/
def disconnected : GeneratorPresentation laws where
  relation := fun _ _ => False
  relation_preserves_label := by
    intro left right h
    exact False.elim h

/-- The equivalence closure of the empty relation identifies only equal values. -/
theorem eq_of_empty_related {α : Type u} {left right : α}
    (h : Relation.EqvGen (fun _ _ : α => False) left right) : left = right := by
  induction h with
  | rel _ _ hrel => exact False.elim hrel
  | refl _ => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ihLeft ihRight => exact ihLeft.trans ihRight

/-- The negative fixture does not satisfy the structural reflection condition. -/
theorem disconnected_not_reflectionCondition :
    ¬ disconnected.ReflectionCondition := by
  intro hReflection
  let left : PrimitiveGenerator laws := ⟨PUnit.unit, false⟩
  let right : PrimitiveGenerator laws := ⟨PUnit.unit, true⟩
  have hlabel : left.label laws = right.label laws := by
    apply LawValueLabel.ext laws
    · rfl
    · exact HEq.rfl
  have hrelated := hReflection left right hlabel
  have heq : left = right := eq_of_empty_related hrelated
  exact Bool.noConfusion (congrArg Prod.snd heq)

end ReflectionConditionFixtures

end AAT.AG.ObstructionDiagnosticBridge

#assert_standard_axioms_only AAT.AG.ObstructionDiagnosticBridge
