import ResearchLean.AG.ObstructionDiagnosticBridge.PointAtomContextSupport
import ResearchLean.AG.ObstructionDiagnosticBridge.AATLocallyConstantObstruction
import Mathlib.Topology.Sheaves.SheafCondition.Sites
import Formal.Util.AssertStandardAxioms

/-!
# Continuity of the point-Atom support functor

The point-support coverage is not declared stable under base change: its
requirements ask for all point Atoms independently of the base context.
Instead, this module proves continuity directly against the Grothendieck
topology generated by that precoverage.

The proof uses the general sheaf criterion for a generated topology.  A
pullback of an admissible family along an arbitrary context morphism is sent
by the support functor to intersections with the new base support.  Those
opens cover the new base because the original admissible family covers every
point Atom.  No precoverage base-change instance is introduced.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits Set TopologicalSpace

namespace AAT.AG.ObstructionDiagnosticBridge
namespace PointAtomContextSupport

open SelectedFiniteGeometry

/-- Product contexts form pullbacks in the canonical thin context category. -/
def contextPullbackCone {X Y Z : site.category} (f : X ⟶ Z) (g : Y ⟶ Z) :
    PullbackCone f g :=
  PullbackCone.mk
    (homOfLE (Site.productContextFiniteMeet.meet_le_left X.ctx Y.ctx))
    (homOfLE (Site.productContextFiniteMeet.meet_le_right X.ctx Y.ctx))
    (Subsingleton.elim _ _)

/-- The product-context pullback cone has the universal property. -/
def contextPullbackConeIsLimit {X Y Z : site.category} (f : X ⟶ Z) (g : Y ⟶ Z) :
    IsLimit (contextPullbackCone f g) :=
  PullbackCone.IsLimit.mk _
    (fun s => homOfLE
      (Site.productContextFiniteMeet.le_meet (leOfHom s.fst) (leOfHom s.snd)))
    (fun _ => Subsingleton.elim _ _)
    (fun _ => Subsingleton.elim _ _)
    (fun _ _ _ _ => Subsingleton.elim _ _)

/-- Supply the product-context limit witness locally for pairwise pullback APIs. -/
noncomputable local instance contextHasPullback
    {X Y Z : site.category} (f : X ⟶ Z) (g : Y ⟶ Z) : HasPullback f g :=
  ⟨⟨⟨contextPullbackCone f g, contextPullbackConeIsLimit f g⟩⟩⟩

/-- The image of the selected product-context pullback is an open intersection pullback. -/
def supportMapPullbackConeIsLimit {X Y Z : site.category} (f : X ⟶ Z) (g : Y ⟶ Z) :
    IsLimit
      (PullbackCone.mk
        (supportFunctor.map (contextPullbackCone f g).fst)
        (supportFunctor.map (contextPullbackCone f g).snd)
        (Subsingleton.elim _ _) :
        PullbackCone (supportFunctor.map f) (supportFunctor.map g)) :=
  PullbackCone.IsLimit.mk _
    (fun s => homOfLE (by
      rw [show supportFunctor.obj (contextPullbackCone f g).pt =
          supportFunctor.obj X ⊓ supportFunctor.obj Y by
        exact contextSupport_product X.ctx Y.ctx]
      exact le_inf (leOfHom s.fst) (leOfHom s.snd)))
    (fun _ => Subsingleton.elim _ _)
    (fun _ => Subsingleton.elim _ _)
    (fun _ _ _ _ => Subsingleton.elim _ _)

/-- The support functor preserves each pullback in the context category. -/
theorem supportFunctor_preservesPullback
    {X Y Z : site.category} (f : X ⟶ Z) (g : Y ⟶ Z) :
    PreservesLimit (cospan f g) supportFunctor :=
  preservesLimit_of_preserves_limit_cone
    (contextPullbackConeIsLimit f g)
    ((PullbackCone.isLimitMapConeEquiv
      (contextPullbackCone f g) supportFunctor).symm
      (supportMapPullbackConeIsLimit f g))

/-- Pulling an admissible family back and applying support gives an open cover. -/
theorem mapped_pullback_mem_open_topology
    {X Y : site.category} (f : Y ⟶ X)
    (F : Site.AATCoverageFamily coverageRequirements overlap X) :
    Sieve.generate
        (((Sieve.generate F.presieve).pullback f).arrows.map supportFunctor) ∈
      Opens.grothendieckTopology Space (supportFunctor.obj Y) := by
  intro x hx
  obtain ⟨i, hi⟩ := F.admissible.atomSupportCoverage x trivial
  let patchObject := Site.ContextCategoryObject.of contextPreorder (F.patch i)
  let Q := Site.ContextCategoryObject.of contextPreorder
    (Site.productContext Y.ctx (F.patch i))
  let q : Q ⟶ Y :=
    homOfLE (Site.productContextFiniteMeet.meet_le_left Y.ctx (F.patch i))
  let qpatch : Q ⟶ patchObject :=
    homOfLE (Site.productContextFiniteMeet.meet_le_right Y.ctx (F.patch i))
  have hq : (Sieve.generate F.presieve).pullback f q := by
    change Sieve.generate F.presieve (q ≫ f)
    have hinclusion : Sieve.generate F.presieve
        (homOfLE (F.inclusion i)) :=
      Sieve.le_generate F.presieve _ (Presieve.ofArrows.mk i)
    have hcomp := (Sieve.generate F.presieve).downward_closed hinclusion qpatch
    convert hcomp using 1
  refine ⟨supportFunctor.obj Q, supportFunctor.map q, ?_, ?_⟩
  · exact Sieve.le_generate _ _ (Presieve.map.of hq)
  · change x ∈ contextSupport (Site.productContext Y.ctx (F.patch i))
    rw [contextSupport_product]
    exact ⟨hx, hi⟩

/-- The point-Atom support functor is continuous for the generated AAT topology. -/
theorem supportFunctor_isContinuous :
    Functor.IsContinuous.{u} supportFunctor site.topology
      (Opens.grothendieckTopology Space) where
  op_comp_isSheaf_of_types := by
    rintro ⟨G, hG⟩
    rw [isSheaf_iff_isSheaf_of_type] at hG
    rw [Site.AATSite.topology, Site.AATGrothendieckTopology]
    rw [Precoverage.isSheaf_toGrothendieck_iff]
    intro X Y f R hR
    rcases hR with ⟨F, rfl⟩
    letI : supportFunctor.PreservesPairwisePullbacks
        ((Sieve.generate F.presieve).pullback f).arrows := {
      preservesLimit := by
        intro R Y left right hleft hright
        exact supportFunctor_preservesPullback left right
    }
    letI : ((Sieve.generate F.presieve).pullback f).arrows.HasPairwisePullbacks :=
      ⟨by
        intro Y Z left hleft right hright
        exact contextHasPullback left right⟩
    rw [Presieve.IsSheafFor.comp_iff_of_preservesPairwisePullbacks]
    apply (Presieve.isSheafFor_iff_generate _).mpr
    exact hG _ (mapped_pullback_mem_open_topology f F)

/-- The selected point-Atom support data satisfies the generic G-125 input contract. -/
def contextOpenSupport : ContextOpenSupport site where
  space := TopCat.of Space
  support := supportFunctor
  continuous := supportFunctor_isContinuous

#assert_standard_axioms_only
  AAT.AG.ObstructionDiagnosticBridge.PointAtomContextSupport

end PointAtomContextSupport
end AAT.AG.ObstructionDiagnosticBridge
