import ResearchLean.AG.ObstructionDiagnosticBridge.GeneratorPresentation
import Mathlib.GroupTheory.Congruence.Hom
import Formal.Util.AssertStandardAxioms

/-!
# The integral presentation group

This module constructs the group from G-125's paper design directly from the
primitive generator relations.  It first forms the free abelian group on law
occurrences, then quotients by the additive congruence generated by each
declared relation between basis generators.

The main theorem derives
`M_R ≃+ FreeAbelianGroup B`, where `B = π₀(R)`.  Thus the expected free
integer coefficient group on relation components is a consequence of the
presentation, not an input certificate.  The later coefficient comparison may
compose this equivalence with the `B ≃ LawValueLabel` equivalence derived from
the reflection condition.
-/

noncomputable section

namespace AAT.AG.ObstructionDiagnosticBridge

open CanonicalResolution ResolutionInvariance

universe u

namespace GeneratorPresentation

variable {Source : Type u} {laws : FiniteLawFamily Source}

/-- The generating pairs of the additive presentation congruence. -/
def presentationRelation (P : GeneratorPresentation laws) :
    FreeAbelianGroup (PrimitiveGenerator laws) →
      FreeAbelianGroup (PrimitiveGenerator laws) → Prop :=
  fun x y => ∃ left right, P.relation left right ∧
    x = FreeAbelianGroup.of left ∧ y = FreeAbelianGroup.of right

/-- The least additive congruence identifying every declared pair of generators. -/
def presentationCongruence (P : GeneratorPresentation laws) :
    AddCon (FreeAbelianGroup (PrimitiveGenerator laws)) :=
  addConGen P.presentationRelation

/-- G-125(A)'s integral presentation group `M_R`. -/
abbrev PresentationGroup (P : GeneratorPresentation laws) :=
  P.presentationCongruence.Quotient

/-- The class in `M_R` of one primitive generator. -/
def generatorClass (P : GeneratorPresentation laws)
    (generator : PrimitiveGenerator laws) : P.PresentationGroup :=
  P.presentationCongruence.mk' (FreeAbelianGroup.of generator)

/-- Relation-connected primitive generators determine the same class in `M_R`. -/
theorem generatorClass_eq_of_related (P : GeneratorPresentation laws)
    {left right : PrimitiveGenerator laws} (h : P.Related left right) :
    P.generatorClass left = P.generatorClass right := by
  induction h with
  | rel left right hrel =>
      apply (P.presentationCongruence.eq).2
      exact AddConGen.Rel.of _ _ ⟨left, right, hrel, rfl, rfl⟩
  | refl _ => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ihLeft ihRight => exact ihLeft.trans ihRight

/-- The class of a relation component in `M_R`, well-defined by connectivity. -/
def blockGenerator (P : GeneratorPresentation laws) :
    P.Block → P.PresentationGroup :=
  Quotient.lift P.generatorClass (fun _ _ h => P.generatorClass_eq_of_related h)

/-- Computing the component class at a primitive generator recovers its presentation class. -/
@[simp]
theorem blockGenerator_blockOf (P : GeneratorPresentation laws)
    (generator : PrimitiveGenerator laws) :
    P.blockGenerator (P.blockOf generator) = P.generatorClass generator :=
  rfl

/-- Extend component classes to a homomorphism from the free group on `B`. -/
def blocksToPresentation (P : GeneratorPresentation laws) :
    FreeAbelianGroup P.Block →+ P.PresentationGroup :=
  FreeAbelianGroup.lift P.blockGenerator

/-- Computation of `blocksToPresentation` on a component basis generator. -/
@[simp]
theorem blocksToPresentation_of_blockOf (P : GeneratorPresentation laws)
    (generator : PrimitiveGenerator laws) :
    P.blocksToPresentation (FreeAbelianGroup.of (P.blockOf generator)) =
      P.generatorClass generator := by
  simp [blocksToPresentation]

/-- Map every primitive basis generator to the basis generator of its relation component. -/
def generatorToBlock (P : GeneratorPresentation laws) :
    FreeAbelianGroup (PrimitiveGenerator laws) →+ FreeAbelianGroup P.Block :=
  FreeAbelianGroup.map P.blockOf

/-- The component map identifies every pair in the generated presentation congruence. -/
theorem presentationCongruence_le_ker_generatorToBlock
    (P : GeneratorPresentation laws) :
    P.presentationCongruence ≤ AddCon.ker P.generatorToBlock := by
  intro x y h
  induction h with
  | of x y hrel =>
      obtain ⟨left, right, hprimitive, rfl, rfl⟩ := hrel
      change FreeAbelianGroup.of (P.blockOf left) =
        FreeAbelianGroup.of (P.blockOf right)
      congr 1
      apply Quotient.sound
      exact Relation.EqvGen.rel left right hprimitive
  | refl _ => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ ihLeft ihRight => exact ihLeft.trans ihRight
  | add _ _ ihLeft ihRight =>
      change P.generatorToBlock (_ + _) = P.generatorToBlock (_ + _)
      rw [map_add, map_add]
      exact congrArg₂ (· + ·) ihLeft ihRight

/-- Descend the component map through the presentation quotient. -/
def presentationToBlocks (P : GeneratorPresentation laws) :
    P.PresentationGroup →+ FreeAbelianGroup P.Block :=
  P.presentationCongruence.lift P.generatorToBlock
    P.presentationCongruence_le_ker_generatorToBlock

/-- Computation of the descended map on a primitive generator class. -/
@[simp]
theorem presentationToBlocks_generatorClass (P : GeneratorPresentation laws)
    (generator : PrimitiveGenerator laws) :
    P.presentationToBlocks (P.generatorClass generator) =
      FreeAbelianGroup.of (P.blockOf generator) := by
  rfl

/-- Component expansion followed by the presentation map is the identity on `M_R`. -/
theorem blocksToPresentation_comp_presentationToBlocks
    (P : GeneratorPresentation laws) :
    P.blocksToPresentation.comp P.presentationToBlocks = AddMonoidHom.id _ := by
  apply AddCon.hom_ext
  apply FreeAbelianGroup.lift_ext
  intro generator
  change P.generatorClass generator = P.generatorClass generator
  rfl

/-- The presentation map followed by component expansion is the identity on `ℤ^B`. -/
theorem presentationToBlocks_comp_blocksToPresentation
    (P : GeneratorPresentation laws) :
    P.presentationToBlocks.comp P.blocksToPresentation = AddMonoidHom.id _ := by
  apply FreeAbelianGroup.lift_ext
  intro block
  refine Quotient.inductionOn block ?_
  intro generator
  change FreeAbelianGroup.of (P.blockOf generator) =
    FreeAbelianGroup.of (P.blockOf generator)
  rfl

/--
G-125(A)'s normal-form theorem: the relation presentation group is the free
abelian group on the relation components `B = π₀(R)`.
-/
def presentationGroupEquivBlocks (P : GeneratorPresentation laws) :
    P.PresentationGroup ≃+ FreeAbelianGroup P.Block :=
  { toFun := P.presentationToBlocks
    invFun := P.blocksToPresentation
    left_inv := fun x => congrArg (fun f => f x)
      P.blocksToPresentation_comp_presentationToBlocks
    right_inv := fun x => congrArg (fun f => f x)
      P.presentationToBlocks_comp_blocksToPresentation
    map_add' := P.presentationToBlocks.map_add }

end GeneratorPresentation

/-! ## Nonvacuity fixture -/

namespace PresentationGroupFixtures

open GeneratorPresentation ReflectionConditionFixtures

/--
The connected two-source fixture has distinct primitive generators that become
equal in the presentation group, so the generated congruence is used
nontrivially rather than collapsing to equality by definition.
-/
theorem connected_distinct_generator_classes_equal :
    ∃ left right : PrimitiveGenerator ReflectionConditionFixtures.laws,
      left ≠ right ∧
        ReflectionConditionFixtures.connected.generatorClass left =
          ReflectionConditionFixtures.connected.generatorClass right := by
  obtain ⟨left, right, hne, hrelated⟩ :=
    ReflectionConditionFixtures.connected_has_distinct_related_generators
  exact ⟨left, right, hne,
    ReflectionConditionFixtures.connected.generatorClass_eq_of_related hrelated⟩

end PresentationGroupFixtures

#assert_standard_axioms_only AAT.AG.ObstructionDiagnosticBridge

end AAT.AG.ObstructionDiagnosticBridge
