import ResearchLean.AG.TransportCoherence.CanonicalCoherence
import Mathlib.CategoryTheory.Endomorphism

/-!
# Finite presentations and raw transport-coherence defects

This module supplies the G-106/J1 coefficient system.  A finite presentation
has finitely many vertices, edge generators, declared parallel-path 2-cells,
and declared oriented 3-cell pastings.  An admissible interpretation assigns a
package to every vertex, a strongly cocartesian lift to every edge, a base
equality to every declared 2-cell, and an external fiber-isomorphism comparator.

The raw defect is unconditional: for every edge reselection it compares the
authored comparator with the canonical comparator generated by the G-101
universal property.  Edge reselection changes path evaluation and never edits a
2-cell comparator directly.  The resulting image defines the obstruction
orbit independently of coherentizability.  A 3-cell cocycle equation is stated
only under the separate `SyzygyCompatible` direction hypothesis.
-/

namespace AAT.AG.TransportCoherence

universe u

open CategoryTheory
open AtomFoundation

/-! ## Finite presentation geometry -/

/-- A finite path in a directed family of edge generators. -/
inductive PresentedPath {V : Type u} (Edge : V → V → Type u) : V → V → Type u
  | nil (v : V) : PresentedPath Edge v v
  | cons {i j k : V} (edge : Edge i j) (tail : PresentedPath Edge j k) :
      PresentedPath Edge i k

namespace PresentedPath

/-- Concatenate two finite presented paths. -/
def append {V : Type u} {Edge : V → V → Type u} {i j k : V}
    (first : PresentedPath Edge i j) (second : PresentedPath Edge j k) :
    PresentedPath Edge i k :=
  match first with
  | .nil _ => second
  | .cons edge tail => .cons edge (append tail second)

/-- Appending an identity path on the right changes no presented path. -/
@[simp]
theorem append_nil {V : Type u} {Edge : V → V → Type u} {i j : V}
    (path : PresentedPath Edge i j) :
    path.append (.nil j) = path := by
  induction path with
  | nil vertex => rfl
  | cons edge tail inductionHypothesis =>
      simp only [append, inductionHypothesis]

/-- Concatenation of presented paths is associative. -/
@[simp]
theorem append_assoc {V : Type u} {Edge : V → V → Type u}
    {i j k l : V} (first : PresentedPath Edge i j)
    (second : PresentedPath Edge j k) (third : PresentedPath Edge k l) :
    (first.append second).append third = first.append (second.append third) := by
  induction first with
  | nil vertex => rfl
  | cons edge tail inductionHypothesis =>
      simp only [append, inductionHypothesis]

end PresentedPath

/-- Orientation of a declared 2-cell face inside a 3-cell pasting. -/
inductive FaceOrientation
  | forward
  | backward
  deriving DecidableEq

/-- The finite 0/1/2-cell skeleton underlying a G-106 presentation. -/
structure FiniteTransportTwoPresentation where
  /-- Finite family of 0-cell labels. -/
  Vertex : Type u
  /-- Explicit finiteness witness for the 0-cells. -/
  vertexFintype : Fintype Vertex
  /-- Finite family of directed 1-cell generators between each pair. -/
  Edge : Vertex → Vertex → Type u
  /-- Explicit finiteness witness for every edge-generator family. -/
  edgeFintype : ∀ i j, Fintype (Edge i j)
  /-- Finite family of declared parallel-path 2-cells. -/
  TwoCell : Type u
  /-- Explicit finiteness witness for the 2-cells. -/
  twoCellFintype : Fintype TwoCell
  /-- Source vertex of a declared 2-cell. -/
  twoSource : TwoCell → Vertex
  /-- Target vertex of a declared 2-cell. -/
  twoTarget : TwoCell → Vertex
  /-- First path in a declared parallel-path relation. -/
  twoLeft : (cell : TwoCell) → PresentedPath Edge (twoSource cell) (twoTarget cell)
  /-- Second path in a declared parallel-path relation. -/
  twoRight : (cell : TwoCell) → PresentedPath Edge (twoSource cell) (twoTarget cell)

namespace FiniteTransportTwoPresentation

/-- Paths in a finite 0/1/2-cell presentation skeleton. -/
abbrev Path (G : FiniteTransportTwoPresentation.{u}) := PresentedPath G.Edge

end FiniteTransportTwoPresentation

/--
One oriented 2-cell rewrite placed inside a common source-to-target path.

The incoming prefix and outgoing suffix determine the complete path before and
after the rewrite; they are geometry, not a cocycle equation or certificate.
-/
structure WhiskeredFace (G : FiniteTransportTwoPresentation.{u})
    (source target : G.Vertex) where
  /-- The local declared 2-cell being rewritten. -/
  cell : G.TwoCell
  /-- Prefix from the outer source to the local 2-cell source. -/
  incoming : G.Path source (G.twoSource cell)
  /-- Suffix from the local 2-cell target to the outer target. -/
  outgoing : G.Path (G.twoTarget cell) target
  /-- Whether the local relation is used left-to-right or right-to-left. -/
  orientation : FaceOrientation

namespace WhiskeredFace

/-- Local path before applying an oriented whiskered face. -/
def localBefore {G : FiniteTransportTwoPresentation.{u}}
    {source target : G.Vertex} (face : WhiskeredFace G source target) :
    G.Path (G.twoSource face.cell) (G.twoTarget face.cell) :=
  match face.orientation with
  | .forward => G.twoLeft face.cell
  | .backward => G.twoRight face.cell

/-- Local path after applying an oriented whiskered face. -/
def localAfter {G : FiniteTransportTwoPresentation.{u}}
    {source target : G.Vertex} (face : WhiskeredFace G source target) :
    G.Path (G.twoSource face.cell) (G.twoTarget face.cell) :=
  match face.orientation with
  | .forward => G.twoRight face.cell
  | .backward => G.twoLeft face.cell

/-- Complete outer path before applying a whiskered face. -/
def before {G : FiniteTransportTwoPresentation.{u}}
    {source target : G.Vertex} (face : WhiskeredFace G source target) :
    G.Path source target :=
  face.incoming.append (face.localBefore.append face.outgoing)

/-- Complete outer path after applying a whiskered face. -/
def after {G : FiniteTransportTwoPresentation.{u}}
    {source target : G.Vertex} (face : WhiskeredFace G source target) :
    G.Path source target :=
  face.incoming.append (face.localAfter.append face.outgoing)

end WhiskeredFace

/--
A typed rewrite step between two complete paths.  The equality fields force the
step indices to be exactly the oriented whiskered face's before and after paths.
-/
structure RewriteStep (G : FiniteTransportTwoPresentation.{u})
    {source target : G.Vertex} (before after : G.Path source target) where
  /-- Oriented local face placed inside the two complete paths. -/
  face : WhiskeredFace G source target
  /-- The indexed input path is the face's complete pre-rewrite path. -/
  before_eq : before = face.before
  /-- The indexed output path is the face's complete post-rewrite path. -/
  after_eq : after = face.after

namespace WhiskeredFace

/-- Every whiskered face gives its tautological typed rewrite step. -/
def asStep {G : FiniteTransportTwoPresentation.{u}}
    {source target : G.Vertex} (face : WhiskeredFace G source target) :
    RewriteStep G face.before face.after where
  face := face
  before_eq := rfl
  after_eq := rfl

end WhiskeredFace

/--
A finite vertical pasting of oriented 2-cell rewrites.  The shared middle-path
index in `cons` makes adjacent rewrites composable by construction.
-/
inductive RewritePasting (G : FiniteTransportTwoPresentation.{u})
    {source target : G.Vertex} :
    G.Path source target → G.Path source target → Type u
  | nil (path : G.Path source target) : RewritePasting G path path
  | cons {before middle finish : G.Path source target}
      (step : RewriteStep G before middle)
      (tail : RewritePasting G middle finish) :
      RewritePasting G before finish

/--
The finite G-106 presentation geometry.

The inherited skeleton stores finite 0/1/2-cell generators.  Every 3-cell is a
pair of finite typed rewrite pastings with the same complete start and finish
paths.  Thus face incidence, adjacency, the common outer paths, and orientation
are input geometry; no syzygy equation is stored.
-/
structure FiniteTransportPresentation extends FiniteTransportTwoPresentation.{u} where
  /-- Finite family of declared 3-cell syzygies. -/
  ThreeCell : Type u
  /-- Explicit finiteness witness for the 3-cells. -/
  threeCellFintype : Fintype ThreeCell
  /-- Common initial vertex of the two declared 3-cell pastings. -/
  threeSource : ThreeCell → Vertex
  /-- Common terminal vertex at which a 3-cell pasting is evaluated. -/
  threeTarget : ThreeCell → Vertex
  /-- Complete starting path shared by both declared 3-cell pastings. -/
  threeStart : (cell : ThreeCell) →
    PresentedPath Edge (threeSource cell) (threeTarget cell)
  /-- Complete finishing path shared by both declared 3-cell pastings. -/
  threeFinish : (cell : ThreeCell) →
    PresentedPath Edge (threeSource cell) (threeTarget cell)
  /-- First typed oriented 2-cell rewrite pasting. -/
  threeLeft : (cell : ThreeCell) →
    RewritePasting toFiniteTransportTwoPresentation
      (threeStart cell) (threeFinish cell)
  /-- Second typed oriented 2-cell rewrite pasting with the same outer paths. -/
  threeRight : (cell : ThreeCell) →
    RewritePasting toFiniteTransportTwoPresentation
      (threeStart cell) (threeFinish cell)

namespace FiniteTransportPresentation

/-- Paths in a fixed finite presentation. -/
abbrev Path (G : FiniteTransportPresentation.{u}) := PresentedPath G.Edge

instance (G : FiniteTransportPresentation.{u}) : Fintype G.Vertex :=
  G.vertexFintype

instance (G : FiniteTransportPresentation.{u}) (i j : G.Vertex) :
    Fintype (G.Edge i j) :=
  G.edgeFintype i j

instance (G : FiniteTransportPresentation.{u}) : Fintype G.TwoCell :=
  G.twoCellFintype

instance (G : FiniteTransportPresentation.{u}) : Fintype G.ThreeCell :=
  G.threeCellFintype

end FiniteTransportPresentation

/-! ## Fiber automorphism groups -/

/--
The subgroup of package automorphisms lying over identity in one G-101 fiber.
The complete upper Atom equivalence is then identity by the package morphism
compatibility law; no separate automorphism certificate is supplied.
-/
def packageFiberAutSubgroup {U : AtomCarrier.{u}} (P : AATCorePackage U) :
    Subgroup (Aut P) where
  carrier automorphism := automorphism.hom.base = 𝟙 (packagePoint P)
  one_mem' := by
    rfl
  mul_mem' := by
    intro left right hleft hright
    change (right.hom.comp left.hom).base = 𝟙 (packagePoint P)
    change right.hom.base.comp left.hom.base = 𝟙 (packagePoint P)
    rw [hright, hleft]
    exact (@Category.id_comp
      (ExtractionInstance U) (ExtInstHom.extractionInstanceCategory U)
      (packagePoint P) (packagePoint P) (𝟙 (packagePoint P)))
  inv_mem' := by
    intro automorphism homBase
    have mappedIso : (packageProjection U).mapIso automorphism =
        Iso.refl (packagePoint P) := by
      apply Iso.ext
      exact homBase
    have invBase := congrArg
      (fun iso : Aut (packagePoint P) => iso.inv) mappedIso
    simpa using invBase

/-- The noncommutative group of package automorphisms in one G-101 fiber. -/
abbrev PackageFiberAut {U : AtomCarrier.{u}} (P : AATCorePackage U) :=
  packageFiberAutSubgroup P

namespace PackageFiberAut

/-- The total-category forward morphism of a fiber automorphism. -/
def hom {U : AtomCarrier.{u}} {P : AATCorePackage U}
    (automorphism : PackageFiberAut P) : PackageTotalHom P P :=
  automorphism.1.hom

/-- The total-category inverse morphism of a fiber automorphism. -/
def inv {U : AtomCarrier.{u}} {P : AATCorePackage U}
    (automorphism : PackageFiberAut P) : PackageTotalHom P P :=
  automorphism.1.inv

/-- Every fiber automorphism's forward morphism lies over identity. -/
theorem hom_base_eq {U : AtomCarrier.{u}} {P : AATCorePackage U}
    (automorphism : PackageFiberAut P) :
    (PackageFiberAut.hom automorphism).base = 𝟙 (packagePoint P) :=
  automorphism.2

/-- Every fiber automorphism's inverse morphism lies over identity. -/
theorem inv_base_eq {U : AtomCarrier.{u}} {P : AATCorePackage U}
    (automorphism : PackageFiberAut P) :
    (PackageFiberAut.inv automorphism).base = 𝟙 (packagePoint P) := by
  exact (packageFiberAutSubgroup P).inv_mem automorphism.2

/-- The complete forward upper hom of a fiber automorphism fixes every Atom. -/
theorem hom_atomEquiv_eq {U : AtomCarrier.{u}} {P : AATCorePackage U}
    (automorphism : PackageFiberAut P) :
    (PackageFiberAut.hom automorphism).upper.atomEquiv = Equiv.refl U.Atom := by
  rw [(PackageFiberAut.hom automorphism).atomEquiv_eq,
    PackageFiberAut.hom_base_eq]
  rfl

/-- The complete inverse upper hom of a fiber automorphism fixes every Atom. -/
theorem inv_atomEquiv_eq {U : AtomCarrier.{u}} {P : AATCorePackage U}
    (automorphism : PackageFiberAut P) :
    (PackageFiberAut.inv automorphism).upper.atomEquiv = Equiv.refl U.Atom := by
  rw [(PackageFiberAut.inv automorphism).atomEquiv_eq,
    PackageFiberAut.inv_base_eq]
  rfl

/--
Two endpoint-fiber automorphisms are equal when they have the same composite
after one strongly cocartesian lift.
-/
theorem ext_of_strong_fac {U : AtomCarrier.{u}} {P Q : AATCorePackage U}
    (lift : PackageTotalHom P Q)
    [(packageProjection U).IsStronglyCocartesian lift.base lift]
    (left right : PackageFiberAut Q)
    (fac : lift.comp (PackageFiberAut.hom left) =
      lift.comp (PackageFiberAut.hom right)) :
    left = right := by
  letI : (packageProjection U).IsHomLift
      (𝟙 (packagePoint Q)) left.1.hom := by
    rw [← PackageFiberAut.hom_base_eq]
    change (packageProjection U).IsHomLift
      ((packageProjection U).map (PackageFiberAut.hom left))
      (PackageFiberAut.hom left)
    infer_instance
  letI : (packageProjection U).IsHomLift
      (𝟙 (packagePoint Q)) right.1.hom := by
    rw [← PackageFiberAut.hom_base_eq]
    change (packageProjection U).IsHomLift
      ((packageProjection U).map (PackageFiberAut.hom right))
      (PackageFiberAut.hom right)
    infer_instance
  apply Subtype.ext
  apply Iso.ext
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) lift.base lift (𝟙 (packagePoint Q))
  exact fac

end PackageFiberAut

/-! ## Admissible edge lifts and path evaluation -/

/--
G-106/J1 admissible edge-lift data for a finite presentation.

Each vertex is interpreted by a package, hence by its underlying doctrine.
Each edge is interpreted by a total morphism and must be strongly cocartesian.
The qualification is the fixed local direction hypothesis; it neither mentions
2-cell comparators nor any global coherence or vanishing conclusion.
-/
structure AdmissibleLiftData (G : FiniteTransportPresentation.{u})
    (U : AtomCarrier.{u}) where
  /-- Package, and therefore doctrine, interpreting every 0-cell. -/
  package : G.Vertex → AATCorePackage U
  /-- Selected total lift interpreting every edge generator. -/
  edgeLift : {i j : G.Vertex} → G.Edge i j → PackageTotalHom (package i) (package j)
  /-- Every selected edge lift has the required local opcartesian qualification. -/
  edgeStrong : ∀ {i j : G.Vertex} (edge : G.Edge i j),
    (packageProjection U).IsStronglyCocartesian
      (edgeLift edge).base (edgeLift edge)

namespace AdmissibleLiftData

/-- Evaluate a finite presented path by composing its selected edge lifts. -/
def pathLift {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U) :
    {i j : G.Vertex} → G.Path i j → PackageTotalHom (data.package i) (data.package j)
  | _, _, .nil vertex => PackageTotalHom.id (data.package vertex)
  | _, _, .cons edge tail => (data.edgeLift edge).comp (data.pathLift tail)

/-- Path evaluation sends concatenation to composition of total lifts. -/
theorem pathLift_append
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U) {i j k : G.Vertex}
    (first : G.Path i j) (second : G.Path j k) :
    data.pathLift (first.append second) =
      (data.pathLift first).comp (data.pathLift second) := by
  induction first with
  | nil vertex =>
      change data.pathLift second =
        (PackageTotalHom.id (data.package vertex)).comp (data.pathLift second)
      exact (@Category.id_comp
        (AATCorePackage U) (PackageTotalHom.packageTotalCategory U)
        (data.package vertex) (data.package k) (data.pathLift second)).symm
  | cons edge tail inductionHypothesis =>
      simp only [PresentedPath.append, pathLift]
      rw [inductionHypothesis]
      exact (@Category.assoc
        (AATCorePackage U) (PackageTotalHom.packageTotalCategory U)
        _ _ _ _ (data.edgeLift edge) (data.pathLift tail)
        (data.pathLift second)).symm

/--
Every selected path lift is strongly cocartesian.  The proof uses only the
admissible edge qualifications and closure under identity and composition.
-/
theorem pathLift_isStronglyCocartesian
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U) {i j : G.Vertex}
    (path : G.Path i j) :
    (packageProjection U).IsStronglyCocartesian
      (data.pathLift path).base (data.pathLift path) := by
  induction path with
  | nil vertex =>
      letI : (packageProjection U).IsHomLift
          (𝟙 (packagePoint (data.package vertex)))
          (Iso.refl (data.package vertex)).hom := by
        change (packageProjection U).IsHomLift
          (𝟙 (packagePoint (data.package vertex)))
          (𝟙 (data.package vertex))
        exact CategoryTheory.IsHomLift.id
          (p := packageProjection U) rfl
      simpa only [pathLift] using
        (CategoryTheory.Functor.IsStronglyCocartesian.of_iso
          (packageProjection U) (𝟙 (packagePoint (data.package vertex)))
          (Iso.refl (data.package vertex)))
  | cons edge tail inductionHypothesis =>
      letI : (packageProjection U).IsStronglyCocartesian
          (data.edgeLift edge).base (data.edgeLift edge) :=
        data.edgeStrong edge
      letI : (packageProjection U).IsStronglyCocartesian
          (data.pathLift tail).base (data.pathLift tail) :=
        inductionHypothesis
      simpa only [pathLift] using
        (CategoryTheory.Functor.IsStronglyCocartesian.comp
          (packageProjection U) :
          (packageProjection U).IsStronglyCocartesian
            ((data.edgeLift edge).base.comp (data.pathLift tail).base)
            ((data.edgeLift edge).comp (data.pathLift tail)))

end AdmissibleLiftData

/--
The complete G-106/J1 admissible comparison data.

`twoCellBase` interprets each declared parallel-path relation in the base.
`comparator` is the explicitly authored invertible translation at the common
endpoint.  It is local input data and is not required to equal the canonical
comparison; no coherence, cocycle, orbit-vanishing, or coherentizability field
is stored.
-/
structure AdmissibleTransportData (G : FiniteTransportPresentation.{u})
    (U : AtomCarrier.{u}) where
  /-- Locally qualified packages and edge lifts. -/
  lift : AdmissibleLiftData G U
  /-- Declared parallel paths have the same composite exact base morphism. -/
  twoCellBase : ∀ cell : G.TwoCell,
    (lift.pathLift (G.twoLeft cell)).base =
      (lift.pathLift (G.twoRight cell)).base
  /-- Authored invertible translation attached to every declared 2-cell. -/
  comparator : (cell : G.TwoCell) →
    PackageFiberAut (lift.package (G.twoTarget cell))

/-! ## Edge reselection and its action on path evaluation -/

/--
An admissible G-106/J1 edge reselection assigns one fiber automorphism to every
1-cell.  There is deliberately no 2-cell component, so an authored comparator
cannot be replaced directly by the canonical one.
-/
abbrev EdgeReselection {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U) :=
  (i j : G.Vertex) → (edge : G.Edge i j) → PackageFiberAut (data.package j)

/-- Reselect an edge lift by postcomposing its target-fiber trivialization. -/
def reselectedEdgeLift {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (edge : G.Edge i j) : PackageTotalHom (data.package i) (data.package j) :=
  (data.edgeLift edge).comp (PackageFiberAut.hom (reselection i j edge))

/-- Edge reselection preserves the exact base morphism. -/
theorem reselectedEdgeLift_base_eq {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (edge : G.Edge i j) :
    (reselectedEdgeLift data reselection edge).base =
      (data.edgeLift edge).base := by
  change (data.edgeLift edge).base.comp
    (PackageFiberAut.hom (reselection i j edge)).base =
      (data.edgeLift edge).base
  rw [PackageFiberAut.hom_base_eq]
  exact (@Category.comp_id
    (ExtractionInstance U) (ExtInstHom.extractionInstanceCategory U)
    (packagePoint (data.package i)) (packagePoint (data.package j))
    (data.edgeLift edge).base)

/-- Edge reselection preserves strong cocartesianness. -/
theorem reselectedEdgeLift_isStronglyCocartesian
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (edge : G.Edge i j) :
    (packageProjection U).IsStronglyCocartesian
      (reselectedEdgeLift data reselection edge).base
      (reselectedEdgeLift data reselection edge) := by
  letI : (packageProjection U).IsStronglyCocartesian
      (data.edgeLift edge).base (data.edgeLift edge) :=
    data.edgeStrong edge
  letI : (packageProjection U).IsHomLift
      (reselection i j edge).1.hom.base
      (reselection i j edge).1.hom := by
    change (packageProjection U).IsHomLift
      ((packageProjection U).map (reselection i j edge).1.hom)
      (reselection i j edge).1.hom
    infer_instance
  letI : (packageProjection U).IsStronglyCocartesian
      (PackageFiberAut.hom (reselection i j edge)).base
      (PackageFiberAut.hom (reselection i j edge)) := by
    change (packageProjection U).IsStronglyCocartesian
      (reselection i j edge).1.hom.base (reselection i j edge).1.hom
    exact CategoryTheory.Functor.IsStronglyCocartesian.of_iso
      (packageProjection U) (reselection i j edge).1.hom.base
      (reselection i j edge).1
  change (packageProjection U).IsStronglyCocartesian
    ((data.edgeLift edge).base.comp
      (PackageFiberAut.hom (reselection i j edge)).base)
    ((data.edgeLift edge).comp
      (PackageFiberAut.hom (reselection i j edge)))
  exact CategoryTheory.Functor.IsStronglyCocartesian.comp (packageProjection U)

/-- The admissible edge-lift interpretation after one edge reselection. -/
def reselectLiftData {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) : AdmissibleLiftData G U where
  package := data.package
  edgeLift := reselectedEdgeLift data reselection
  edgeStrong := reselectedEdgeLift_isStronglyCocartesian data reselection

/-- Evaluate a path after changing only its edge trivializations. -/
def reselectedPathLift {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (path : G.Path i j) : PackageTotalHom (data.package i) (data.package j) :=
  (reselectLiftData data reselection).pathLift path

/-- Reselected path evaluation also preserves finite concatenation. -/
theorem reselectedPathLift_append
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j k : G.Vertex}
    (first : G.Path i j) (second : G.Path j k) :
    reselectedPathLift data reselection (first.append second) =
      (reselectedPathLift data reselection first).comp
        (reselectedPathLift data reselection second) :=
  (reselectLiftData data reselection).pathLift_append first second

/-- Reselection preserves the composite exact base of every finite path. -/
theorem reselectedPathLift_base_eq {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (path : G.Path i j) :
    (reselectedPathLift data reselection path).base =
      (data.pathLift path).base := by
  induction path with
  | nil vertex =>
      simp only [reselectedPathLift, reselectLiftData,
        AdmissibleLiftData.pathLift]
  | cons edge tail inductionHypothesis =>
      simp only [reselectedPathLift, reselectLiftData,
        AdmissibleLiftData.pathLift]
      change
        (reselectedEdgeLift data reselection edge).base.comp
            (reselectedPathLift data reselection tail).base =
          (data.edgeLift edge).base.comp (data.pathLift tail).base
      rw [reselectedEdgeLift_base_eq, inductionHypothesis]

/-- Every reselected path remains strongly cocartesian. -/
theorem reselectedPathLift_isStronglyCocartesian
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (path : G.Path i j) :
    (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data reselection path).base
      (reselectedPathLift data reselection path) :=
  (reselectLiftData data reselection).pathLift_isStronglyCocartesian path

/-- Identity edge reselection leaves every edge lift unchanged. -/
@[simp]
theorem reselectedEdgeLift_one {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U)
    {i j : G.Vertex} (edge : G.Edge i j) :
    reselectedEdgeLift data (1 : EdgeReselection data) edge =
      data.edgeLift edge := by
  change (data.edgeLift edge).comp (𝟙 (data.package j)) = data.edgeLift edge
  exact (@Category.comp_id
    (AATCorePackage U) (PackageTotalHom.packageTotalCategory U)
    (data.package i) (data.package j) (data.edgeLift edge))

/--
Pointwise multiplication of edge reselections acts by successive
re-trivialization.  The order follows mathlib's noncommutative `Aut` convention.
-/
theorem reselectedEdgeLift_mul {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U)
    (left right : EdgeReselection data) {i j : G.Vertex}
    (edge : G.Edge i j) :
    reselectedEdgeLift data (left * right) edge =
      (reselectedEdgeLift data right edge).comp
        (PackageFiberAut.hom (left i j edge)) := by
  change (data.edgeLift edge).comp
      ((right i j edge).1.hom.comp (left i j edge).1.hom) =
    ((data.edgeLift edge).comp (right i j edge).1.hom).comp
      (left i j edge).1.hom
  exact (@Category.assoc
    (AATCorePackage U) (PackageTotalHom.packageTotalCategory U)
    (data.package i) (data.package j) (data.package j) (data.package j)
    (data.edgeLift edge) (right i j edge).1.hom
    (left i j edge).1.hom).symm

/-- Identity reselection leaves every finite path evaluation unchanged. -/
@[simp]
theorem reselectedPathLift_one {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U)
    {i j : G.Vertex} (path : G.Path i j) :
    reselectedPathLift data (1 : EdgeReselection data) path =
      data.pathLift path := by
  induction path with
  | nil vertex =>
      rfl
  | cons edge tail inductionHypothesis =>
      simp only [reselectedPathLift, reselectLiftData,
        AdmissibleLiftData.pathLift]
      change
        (reselectedEdgeLift data (1 : EdgeReselection data) edge).comp
            (reselectedPathLift data (1 : EdgeReselection data) tail) =
          (data.edgeLift edge).comp (data.pathLift tail)
      rw [reselectedEdgeLift_one, inductionHypothesis]

/--
Pointwise multiplication acts on every finite path by successive edge
reselection.  This is the path-evaluation form of the G-106 coboundary action.
-/
theorem reselectedPathLift_mul {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleLiftData G U)
    (left right : EdgeReselection data) {i j : G.Vertex}
    (path : G.Path i j) :
    reselectedPathLift data (left * right) path =
      reselectedPathLift (reselectLiftData data right) left path := by
  induction path with
  | nil vertex =>
      rfl
  | cons edge tail inductionHypothesis =>
      simp only [reselectedPathLift, reselectLiftData,
        AdmissibleLiftData.pathLift]
      change
        (reselectedEdgeLift data (left * right) edge).comp
            (reselectedPathLift data (left * right) tail) =
          (reselectedEdgeLift (reselectLiftData data right) left edge).comp
            (reselectedPathLift (reselectLiftData data right) left tail)
      rw [reselectedEdgeLift_mul, inductionHypothesis]
      rfl

/-! ## Canonical comparison of strongly cocartesian lifts -/

/--
The canonical endpoint-fiber comparator between two strongly cocartesian lifts
with the same source, target, and exact base.  It is generated by the G-101
universal property through mathlib's codomain-isomorphism construction.
-/
noncomputable def canonicalFiberComparator
    {U : AtomCarrier.{u}} {P Q : AATCorePackage U}
    (left right : PackageTotalHom P Q)
    (baseEq : left.base = right.base)
    [(packageProjection U).IsStronglyCocartesian left.base left]
    [(packageProjection U).IsStronglyCocartesian right.base right] :
    PackageFiberAut Q := by
  have rightBase : right.base = left.base ≫ (Iso.refl (packagePoint Q)).hom := by
    simpa using baseEq.symm
  let comparison : Q ≅ Q :=
    CategoryTheory.Functor.IsStronglyCocartesian.codomainIsoOfBaseIso
      (p := packageProjection U)
      (f := left.base) (f' := right.base)
      (g := Iso.refl (packagePoint Q)) rightBase left right
  have homLift : (packageProjection U).IsHomLift
      (𝟙 (packagePoint Q)) comparison.hom := by
    change (packageProjection U).IsHomLift
      (Iso.refl (packagePoint Q)).hom
      (CategoryTheory.Functor.IsStronglyCocartesian.map
        (packageProjection U) left.base left rightBase right)
    infer_instance
  have homBase : comparison.hom.base = 𝟙 (packagePoint Q) := by
    exact (CategoryTheory.IsHomLift.eq_of_isHomLift
      (packageProjection U) _ comparison.hom).symm
  exact ⟨comparison, homBase⟩

/-- The G-101-generated comparator is characterized by its lift factorization. -/
@[simp]
theorem canonicalFiberComparator_fac
    {U : AtomCarrier.{u}} {P Q : AATCorePackage U}
    (left right : PackageTotalHom P Q)
    (baseEq : left.base = right.base)
    [(packageProjection U).IsStronglyCocartesian left.base left]
    [(packageProjection U).IsStronglyCocartesian right.base right] :
    left.comp
        (PackageFiberAut.hom (canonicalFiberComparator left right baseEq)) =
      right := by
  have rightBase : right.base = left.base ≫ (Iso.refl (packagePoint Q)).hom := by
    simpa using baseEq.symm
  unfold canonicalFiberComparator
  dsimp only
  simpa only using (CategoryTheory.Functor.IsStronglyCocartesian.fac
    (p := packageProjection U) (f := left.base) (φ := left)
    (g := (Iso.refl (packagePoint Q)).hom)
    (f' := right.base) (hf' := rightBase) (φ' := right))

/-! ## Endpoint gauges induced by successive edge reselection -/

/--
The endpoint gauge from the path evaluated in `current` coordinates to the
same path after one further `increment`.  It is generated by G-101 uniqueness,
not supplied as reselection data.
-/
noncomputable def pathReselectionTransition
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (current increment : EdgeReselection data) {i j : G.Vertex}
    (path : G.Path i j) : PackageFiberAut (data.package j) := by
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data current path).base
      (reselectedPathLift data current path) :=
    reselectedPathLift_isStronglyCocartesian data current path
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data (increment * current) path).base
      (reselectedPathLift data (increment * current) path) :=
    reselectedPathLift_isStronglyCocartesian data (increment * current) path
  exact canonicalFiberComparator
    (reselectedPathLift data current path)
    (reselectedPathLift data (increment * current) path)
    ((reselectedPathLift_base_eq data current path).trans
      (reselectedPathLift_base_eq data (increment * current) path).symm)

/-- The induced endpoint gauge factors one path evaluation into the next. -/
@[simp]
theorem pathReselectionTransition_fac
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (current increment : EdgeReselection data) {i j : G.Vertex}
    (path : G.Path i j) :
    (reselectedPathLift data current path).comp
        (PackageFiberAut.hom
          (pathReselectionTransition data current increment path)) =
      reselectedPathLift data (increment * current) path := by
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data current path).base
      (reselectedPathLift data current path) :=
    reselectedPathLift_isStronglyCocartesian data current path
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data (increment * current) path).base
      (reselectedPathLift data (increment * current) path) :=
    reselectedPathLift_isStronglyCocartesian data (increment * current) path
  exact canonicalFiberComparator_fac
    (reselectedPathLift data current path)
    (reselectedPathLift data (increment * current) path)
    ((reselectedPathLift_base_eq data current path).trans
      (reselectedPathLift_base_eq data (increment * current) path).symm)

/-- Identity increment induces the identity endpoint gauge. -/
@[simp]
theorem pathReselectionTransition_one
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (current : EdgeReselection data) {i j : G.Vertex}
    (path : G.Path i j) :
    pathReselectionTransition data current 1 path = 1 := by
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data current path).base
      (reselectedPathLift data current path) :=
    reselectedPathLift_isStronglyCocartesian data current path
  apply PackageFiberAut.ext_of_strong_fac
    (reselectedPathLift data current path)
  rw [pathReselectionTransition_fac]
  rw [one_mul]
  change reselectedPathLift data current path =
    (reselectedPathLift data current path).comp (𝟙 (data.package j))
  exact (@Category.comp_id
    (AATCorePackage U) (PackageTotalHom.packageTotalCategory U)
    (data.package i) (data.package j)
    (reselectedPathLift data current path)).symm

/--
Endpoint gauges compose in the same order as successive edge reselections.
The product order follows mathlib's reverse-hom convention for `Aut`.
-/
theorem pathReselectionTransition_mul
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (current increment middle : EdgeReselection data)
    {i j : G.Vertex} (path : G.Path i j) :
    pathReselectionTransition data current (middle * increment) path =
      pathReselectionTransition data (increment * current) middle path *
        pathReselectionTransition data current increment path := by
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data current path).base
      (reselectedPathLift data current path) :=
    reselectedPathLift_isStronglyCocartesian data current path
  apply PackageFiberAut.ext_of_strong_fac
    (reselectedPathLift data current path)
  rw [pathReselectionTransition_fac]
  change reselectedPathLift data ((middle * increment) * current) path =
    (reselectedPathLift data current path).comp
      ((pathReselectionTransition data current increment path).1.hom.comp
        (pathReselectionTransition data (increment * current) middle path).1.hom)
  calc
    reselectedPathLift data ((middle * increment) * current) path =
        reselectedPathLift data (middle * (increment * current)) path := by
      rw [mul_assoc]
    _ = (reselectedPathLift data (increment * current) path).comp
          (PackageFiberAut.hom
            (pathReselectionTransition data (increment * current) middle path)) :=
      (pathReselectionTransition_fac data (increment * current) middle path).symm
    _ = ((reselectedPathLift data current path).comp
          (PackageFiberAut.hom
            (pathReselectionTransition data current increment path))).comp
          (PackageFiberAut.hom
            (pathReselectionTransition data (increment * current) middle path)) := by
      exact congrArg
        (fun lift : PackageTotalHom (data.package i) (data.package j) =>
          lift.comp (PackageFiberAut.hom
            (pathReselectionTransition data (increment * current) middle path)))
        (pathReselectionTransition_fac data current increment path).symm
    _ = (reselectedPathLift data current path).comp
          ((pathReselectionTransition data current increment path).1.hom.comp
            (pathReselectionTransition data (increment * current) middle path).1.hom) :=
      (@Category.assoc
        (AATCorePackage U) (PackageTotalHom.packageTotalCategory U)
        (data.package i) (data.package j) (data.package j) (data.package j)
        (reselectedPathLift data current path)
        (PackageFiberAut.hom
          (pathReselectionTransition data current increment path))
        (PackageFiberAut.hom
          (pathReselectionTransition data (increment * current) middle path)))

/--
The selected base relation of every 2-cell survives arbitrary edge
reselection.  This is the path-level coboundary action's base compatibility.
-/
theorem reselectedTwoCellBase {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) (cell : G.TwoCell) :
    (reselectedPathLift data.lift reselection (G.twoLeft cell)).base =
      (reselectedPathLift data.lift reselection (G.twoRight cell)).base := by
  rw [reselectedPathLift_base_eq, reselectedPathLift_base_eq]
  exact data.twoCellBase cell

/-! ## Canonical 2-cell comparisons and raw defects -/

/--
The canonical G-106/J1 comparison between the two reselected lifts of a
declared 2-cell.  Both strong-lift instances and their base equality are derived
from admissible local data.
-/
noncomputable def canonicalTwoCellComparator
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) (cell : G.TwoCell) :
    PackageFiberAut (data.lift.package (G.twoTarget cell)) := by
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data.lift reselection (G.twoLeft cell)).base
      (reselectedPathLift data.lift reselection (G.twoLeft cell)) :=
    reselectedPathLift_isStronglyCocartesian
      data.lift reselection (G.twoLeft cell)
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data.lift reselection (G.twoRight cell)).base
      (reselectedPathLift data.lift reselection (G.twoRight cell)) :=
    reselectedPathLift_isStronglyCocartesian
      data.lift reselection (G.twoRight cell)
  exact canonicalFiberComparator
    (reselectedPathLift data.lift reselection (G.twoLeft cell))
    (reselectedPathLift data.lift reselection (G.twoRight cell))
    (reselectedTwoCellBase data reselection cell)

/-- The canonical 2-cell comparator identifies the two reselected path lifts. -/
theorem canonicalTwoCellComparator_fac
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) (cell : G.TwoCell) :
    (reselectedPathLift data.lift reselection (G.twoLeft cell)).comp
        (PackageFiberAut.hom
          (canonicalTwoCellComparator data reselection cell)) =
      reselectedPathLift data.lift reselection (G.twoRight cell) := by
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data.lift reselection (G.twoLeft cell)).base
      (reselectedPathLift data.lift reselection (G.twoLeft cell)) :=
    reselectedPathLift_isStronglyCocartesian
      data.lift reselection (G.twoLeft cell)
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data.lift reselection (G.twoRight cell)).base
      (reselectedPathLift data.lift reselection (G.twoRight cell)) :=
    reselectedPathLift_isStronglyCocartesian
      data.lift reselection (G.twoRight cell)
  exact canonicalFiberComparator_fac
    (reselectedPathLift data.lift reselection (G.twoLeft cell))
    (reselectedPathLift data.lift reselection (G.twoRight cell))
    (reselectedTwoCellBase data reselection cell)

/--
The two path endpoint gauges give the noncommutative transformation square for
the canonical 2-cell comparator under successive edge reselection.
-/
theorem canonicalTwoCellComparator_transition_fac
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (current increment : EdgeReselection data.lift) (cell : G.TwoCell) :
    canonicalTwoCellComparator data (increment * current) cell *
        pathReselectionTransition data.lift current increment (G.twoLeft cell) =
      pathReselectionTransition data.lift current increment (G.twoRight cell) *
        canonicalTwoCellComparator data current cell := by
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data.lift current (G.twoLeft cell)).base
      (reselectedPathLift data.lift current (G.twoLeft cell)) :=
    reselectedPathLift_isStronglyCocartesian
      data.lift current (G.twoLeft cell)
  apply PackageFiberAut.ext_of_strong_fac
    (reselectedPathLift data.lift current (G.twoLeft cell))
  change
    (reselectedPathLift data.lift current (G.twoLeft cell)).comp
        ((pathReselectionTransition data.lift current increment
            (G.twoLeft cell)).1.hom.comp
          (canonicalTwoCellComparator data (increment * current) cell).1.hom) =
      (reselectedPathLift data.lift current (G.twoLeft cell)).comp
        ((canonicalTwoCellComparator data current cell).1.hom.comp
          (pathReselectionTransition data.lift current increment
            (G.twoRight cell)).1.hom)
  calc
    (reselectedPathLift data.lift current (G.twoLeft cell)).comp
        ((pathReselectionTransition data.lift current increment
            (G.twoLeft cell)).1.hom.comp
          (canonicalTwoCellComparator data (increment * current) cell).1.hom) =
      ((reselectedPathLift data.lift current (G.twoLeft cell)).comp
        (PackageFiberAut.hom
          (pathReselectionTransition data.lift current increment
            (G.twoLeft cell)))).comp
        (PackageFiberAut.hom
          (canonicalTwoCellComparator data (increment * current) cell)) :=
      (@Category.assoc
        (AATCorePackage U) (PackageTotalHom.packageTotalCategory U)
        _ _ _ _ _ _ _).symm
    _ = (reselectedPathLift data.lift (increment * current)
          (G.twoLeft cell)).comp
        (PackageFiberAut.hom
          (canonicalTwoCellComparator data (increment * current) cell)) := by
      rw [pathReselectionTransition_fac]
    _ = reselectedPathLift data.lift (increment * current)
          (G.twoRight cell) :=
      canonicalTwoCellComparator_fac data (increment * current) cell
    _ = (reselectedPathLift data.lift current (G.twoRight cell)).comp
          (PackageFiberAut.hom
            (pathReselectionTransition data.lift current increment
              (G.twoRight cell))) :=
      (pathReselectionTransition_fac data.lift current increment
        (G.twoRight cell)).symm
    _ = ((reselectedPathLift data.lift current (G.twoLeft cell)).comp
          (PackageFiberAut.hom
            (canonicalTwoCellComparator data current cell))).comp
          (PackageFiberAut.hom
            (pathReselectionTransition data.lift current increment
              (G.twoRight cell))) := by
      rw [canonicalTwoCellComparator_fac]
    _ = (reselectedPathLift data.lift current (G.twoLeft cell)).comp
        ((canonicalTwoCellComparator data current cell).1.hom.comp
          (pathReselectionTransition data.lift current increment
            (G.twoRight cell)).1.hom) :=
      (@Category.assoc
        (AATCorePackage U) (PackageTotalHom.packageTotalCategory U)
        _ _ _ _ _ _ _)

/--
Solved form of the canonical-comparator transformation: the right-path gauge
acts on the left and the inverse left-path gauge acts on the right.
-/
theorem canonicalTwoCellComparator_transition
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (current increment : EdgeReselection data.lift) (cell : G.TwoCell) :
    canonicalTwoCellComparator data (increment * current) cell =
      pathReselectionTransition data.lift current increment (G.twoRight cell) *
        canonicalTwoCellComparator data current cell *
          (pathReselectionTransition data.lift current increment
            (G.twoLeft cell))⁻¹ := by
  apply mul_right_cancel
    (b := pathReselectionTransition data.lift current increment
      (G.twoLeft cell))
  rw [canonicalTwoCellComparator_transition_fac]
  simp [mul_assoc]

/--
The unconditional raw G-106/J1 defect on one declared 2-cell:
`delta = u * phi⁻¹`, whose underlying categorical composite is
`phi.inv ≫ u.hom` in mathlib's `Aut` multiplication convention.
-/
noncomputable def rawTwoCellDefect
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) (cell : G.TwoCell) :
    PackageFiberAut (data.lift.package (G.twoTarget cell)) :=
  data.comparator cell * (canonicalTwoCellComparator data reselection cell)⁻¹

/--
The raw defect has the fixed noncommutative order `phi.inv ≫ u.hom`, exactly
representing `u ∘ phi⁻¹`; it is not an abelianized or commuted surrogate.
-/
theorem rawTwoCellDefect_hom
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) (cell : G.TwoCell) :
    PackageFiberAut.hom (rawTwoCellDefect data reselection cell) =
      (canonicalTwoCellComparator data reselection cell).1.inv.comp
        (PackageFiberAut.hom (data.comparator cell)) :=
  rfl

/--
Explicit noncommutative coboundary formula for the raw defect.  Since the
authored comparator is fixed rather than gauge-rewritten, its conjugate of the
left-path endpoint gauge appears on the left.
-/
theorem rawTwoCellDefect_transition
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (current increment : EdgeReselection data.lift) (cell : G.TwoCell) :
    rawTwoCellDefect data (increment * current) cell =
      (data.comparator cell *
          pathReselectionTransition data.lift current increment
            (G.twoLeft cell) *
          (data.comparator cell)⁻¹) *
        rawTwoCellDefect data current cell *
          (pathReselectionTransition data.lift current increment
            (G.twoRight cell))⁻¹ := by
  rw [rawTwoCellDefect, rawTwoCellDefect,
    canonicalTwoCellComparator_transition]
  simp only [mul_inv_rev, inv_inv]
  simp [mul_assoc]

/-- The raw 2-cochain over all declared 2-cells after one edge reselection. -/
abbrev DefectCochain {G : FiniteTransportPresentation.{u}}
    {U : AtomCarrier.{u}} (data : AdmissibleTransportData G U) :=
  (cell : G.TwoCell) → PackageFiberAut (data.lift.package (G.twoTarget cell))

/-- Evaluate the unconditional raw 2-cochain after an edge reselection. -/
noncomputable def rawDefectCochain
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) : DefectCochain data :=
  fun cell => rawTwoCellDefect data reselection cell

/-- The baseline raw 2-cochain before any edge is reselected. -/
noncomputable def initialRawDefectCochain
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U) : DefectCochain data :=
  rawDefectCochain data 1

/--
Coordinate-dependent action of one additional edge reselection on a raw
2-cochain.  Both parallel paths contribute their generated endpoint gauges;
the authored comparator itself remains fixed.
-/
noncomputable def reselectionTranslate
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (current increment : EdgeReselection data.lift)
    (cochain : DefectCochain data) : DefectCochain data :=
  fun cell =>
    (data.comparator cell *
        pathReselectionTransition data.lift current increment
          (G.twoLeft cell) *
        (data.comparator cell)⁻¹) *
      cochain cell *
        (pathReselectionTransition data.lift current increment
          (G.twoRight cell))⁻¹

/-- Identity edge reselection acts trivially on every 2-cochain. -/
@[simp]
theorem reselectionTranslate_one
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (current : EdgeReselection data.lift) (cochain : DefectCochain data) :
    reselectionTranslate data current 1 cochain = cochain := by
  funext cell
  simp [reselectionTranslate]

/--
The coordinate-dependent cochain translation respects successive edge
reselection.  This is the genuine noncommutative coboundary action law.
-/
theorem reselectionTranslate_mul
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (current increment middle : EdgeReselection data.lift)
    (cochain : DefectCochain data) :
    reselectionTranslate data (increment * current) middle
        (reselectionTranslate data current increment cochain) =
      reselectionTranslate data current (middle * increment) cochain := by
  funext cell
  simp only [reselectionTranslate, pathReselectionTransition_mul]
  simp [mul_assoc]

/-- The raw cochain transforms by the explicit coboundary action. -/
theorem rawDefectCochain_transition
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (current increment : EdgeReselection data.lift) :
    rawDefectCochain data (increment * current) =
      reselectionTranslate data current increment
        (rawDefectCochain data current) := by
  funext cell
  exact rawTwoCellDefect_transition data current increment cell

/-- State space on which edge reselections act with their current coordinate. -/
structure ReselectionCochainState
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U) where
  /-- Current edge-trivialization coordinate. -/
  coordinate : EdgeReselection data.lift
  /-- Raw-cochain coordinate carried by the state. -/
  cochain : DefectCochain data

/-- Apply one incremental edge reselection to a cochain state. -/
noncomputable def reselectionStep
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (increment : EdgeReselection data.lift)
    (state : ReselectionCochainState data) : ReselectionCochainState data where
  coordinate := increment * state.coordinate
  cochain := reselectionTranslate data state.coordinate increment state.cochain

/-- Identity reselection is the identity state transformation. -/
@[simp]
theorem reselectionStep_one
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (state : ReselectionCochainState data) :
    reselectionStep data 1 state = state := by
  cases state
  simp [reselectionStep]

/-- Successive state transformations multiply in execution order. -/
theorem reselectionStep_mul
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (increment middle : EdgeReselection data.lift)
    (state : ReselectionCochainState data) :
    reselectionStep data middle (reselectionStep data increment state) =
      reselectionStep data (middle * increment) state := by
  cases state
  simp [reselectionStep, reselectionTranslate_mul, mul_assoc]

/-- Initial action state before any edge is reselected. -/
noncomputable def initialReselectionState
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U) : ReselectionCochainState data where
  coordinate := 1
  cochain := initialRawDefectCochain data

/-- Acting on the initial state computes the raw cochain at that reselection. -/
theorem reselectionStep_initial_cochain
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) :
    (reselectionStep data reselection
      (initialReselectionState data)).cochain =
        rawDefectCochain data reselection := by
  change reselectionTranslate data 1 reselection
      (rawDefectCochain data 1) = rawDefectCochain data reselection
  simpa only [mul_one] using
    (rawDefectCochain_transition data 1 reselection).symm

/-- The identity 2-cochain, defined without reference to coherentizability. -/
def identityDefectCochain
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U) : DefectCochain data :=
  fun _ => 1

/--
Membership in the edge-reselection orbit of the raw 2-cochain.  Only 1-cell
reselection varies; the authored comparator family remains fixed.
-/
def InReselectionOrbit
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U) (cochain : DefectCochain data) : Prop :=
  ∃ reselection : EdgeReselection data.lift,
    rawDefectCochain data reselection = cochain

/--
The image definition of `InReselectionOrbit` is exactly the cochain projection
of the genuine reselection action orbit of the initial state.
-/
theorem inReselectionOrbit_iff_action
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U) (cochain : DefectCochain data) :
    InReselectionOrbit data cochain ↔
      ∃ reselection : EdgeReselection data.lift,
        (reselectionStep data reselection
          (initialReselectionState data)).cochain = cochain := by
  constructor
  · rintro ⟨reselection, equality⟩
    exact ⟨reselection,
      (reselectionStep_initial_cochain data reselection).trans equality⟩
  · rintro ⟨reselection, equality⟩
    exact ⟨reselection,
      (reselectionStep_initial_cochain data reselection).symm.trans equality⟩

/-- The baseline raw cochain belongs to its edge-reselection orbit. -/
theorem initialRawDefectCochain_mem_orbit
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U) :
    InReselectionOrbit data (initialRawDefectCochain data) := by
  exact ⟨1, rfl⟩

/--
Vanishing of the G-106/J1 obstruction: the raw cochain's edge-reselection orbit
contains the identity cochain.  This definition does not mention a coherence
equation or coherentizability witness.
-/
def TransportObstructionVanishes
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U) : Prop :=
  InReselectionOrbit data (identityDefectCochain data)

/-! ## Whiskered 3-cell pasting and the syzygy direction hypothesis -/

/-- Compose a fiber automorphism with a reselected path lift. -/
def fiberAutThenPath
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (automorphism : PackageFiberAut (data.package i))
    (path : G.Path i j) : PackageTotalHom (data.package i) (data.package j) :=
  (PackageFiberAut.hom automorphism).comp
    (reselectedPathLift data reselection path)

/-- The upper path used to whisker a fiber automorphism is strongly cocartesian. -/
theorem fiberAutThenPath_isStronglyCocartesian
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (automorphism : PackageFiberAut (data.package i))
    (path : G.Path i j) :
    (packageProjection U).IsStronglyCocartesian
      (fiberAutThenPath data reselection automorphism path).base
      (fiberAutThenPath data reselection automorphism path) := by
  letI : (packageProjection U).IsHomLift
      automorphism.1.hom.base automorphism.1.hom := by
    change (packageProjection U).IsHomLift
      ((packageProjection U).map automorphism.1.hom) automorphism.1.hom
    infer_instance
  letI : (packageProjection U).IsStronglyCocartesian
      (PackageFiberAut.hom automorphism).base
      (PackageFiberAut.hom automorphism) := by
    change (packageProjection U).IsStronglyCocartesian
      automorphism.1.hom.base automorphism.1.hom
    exact CategoryTheory.Functor.IsStronglyCocartesian.of_iso
      (packageProjection U) automorphism.1.hom.base automorphism.1
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data reselection path).base
      (reselectedPathLift data reselection path) :=
    reselectedPathLift_isStronglyCocartesian data reselection path
  change (packageProjection U).IsStronglyCocartesian
    ((PackageFiberAut.hom automorphism).base.comp
      (reselectedPathLift data reselection path).base)
    ((PackageFiberAut.hom automorphism).comp
      (reselectedPathLift data reselection path))
  exact CategoryTheory.Functor.IsStronglyCocartesian.comp (packageProjection U)

/-- Whiskering preserves the path's exact base morphism. -/
theorem fiberAutThenPath_base_eq
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (automorphism : PackageFiberAut (data.package i))
    (path : G.Path i j) :
    (fiberAutThenPath data reselection automorphism path).base =
      (reselectedPathLift data reselection path).base := by
  change (PackageFiberAut.hom automorphism).base.comp
      (reselectedPathLift data reselection path).base = _
  rw [PackageFiberAut.hom_base_eq]
  exact (@Category.id_comp
    (ExtractionInstance U) (ExtInstHom.extractionInstanceCategory U)
    (packagePoint (data.package i)) (packagePoint (data.package j))
    (reselectedPathLift data reselection path).base)

/--
Transport a fiber automorphism along a reselected path by factoring its upper
path through the strongly cocartesian path lift.  This is generated by the same
G-101 uniqueness mechanism as canonical binary transport coherence.
-/
noncomputable def whiskerFiberAut
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (automorphism : PackageFiberAut (data.package i))
    (path : G.Path i j) : PackageFiberAut (data.package j) := by
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data reselection path).base
      (reselectedPathLift data reselection path) :=
    reselectedPathLift_isStronglyCocartesian data reselection path
  letI : (packageProjection U).IsStronglyCocartesian
      (fiberAutThenPath data reselection automorphism path).base
      (fiberAutThenPath data reselection automorphism path) :=
    fiberAutThenPath_isStronglyCocartesian data reselection automorphism path
  exact canonicalFiberComparator
    (reselectedPathLift data reselection path)
    (fiberAutThenPath data reselection automorphism path)
    (fiberAutThenPath_base_eq data reselection automorphism path).symm

/-- The whiskered automorphism is characterized by its opcartesian square. -/
theorem whiskerFiberAut_fac
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleLiftData G U)
    (reselection : EdgeReselection data) {i j : G.Vertex}
    (automorphism : PackageFiberAut (data.package i))
    (path : G.Path i j) :
    (reselectedPathLift data reselection path).comp
        (PackageFiberAut.hom
          (whiskerFiberAut data reselection automorphism path)) =
      fiberAutThenPath data reselection automorphism path := by
  letI : (packageProjection U).IsStronglyCocartesian
      (reselectedPathLift data reselection path).base
      (reselectedPathLift data reselection path) :=
    reselectedPathLift_isStronglyCocartesian data reselection path
  letI : (packageProjection U).IsStronglyCocartesian
      (fiberAutThenPath data reselection automorphism path).base
      (fiberAutThenPath data reselection automorphism path) :=
    fiberAutThenPath_isStronglyCocartesian data reselection automorphism path
  exact canonicalFiberComparator_fac
    (reselectedPathLift data reselection path)
    (fiberAutThenPath data reselection automorphism path)
    (fiberAutThenPath_base_eq data reselection automorphism path).symm

/-- Evaluate one oriented, whiskered raw-defect face at a 3-cell target. -/
noncomputable def orientedFaceDefect
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) {source target : G.Vertex}
    (face : WhiskeredFace G.toFiniteTransportTwoPresentation source target) :
    PackageFiberAut (data.lift.package target) :=
  let transported := whiskerFiberAut data.lift reselection
    (rawTwoCellDefect data reselection face.cell) face.outgoing
  match face.orientation with
  | .forward => transported
  | .backward => transported⁻¹

/--
Ordered product of a typed oriented 2-cell pasting at its common target.

The incoming prefix is used by the pasting indices to validate each complete
rewrite.  The coefficient value already lives at the local face target, so only
the outgoing suffix transports it to the common terminal fiber.
-/
noncomputable def defectPastingProduct
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) {source target : G.Vertex}
    {before finish : G.Path source target}
    (pasting : RewritePasting G.toFiniteTransportTwoPresentation before finish) :
    PackageFiberAut (data.lift.package target) :=
  match pasting with
  | .nil _ => 1
  | .cons step tail =>
      orientedFaceDefect data reselection step.face *
        defectPastingProduct data reselection tail

/--
The explicit G-106 syzygy direction hypothesis.  It consists only of the local
3-cell boundary equations declared by the finite presentation and does not
mention global orbit vanishing or coherentizability.
-/
def SyzygyCompatible
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift) : Prop :=
  ∀ cell : G.ThreeCell,
    defectPastingProduct data reselection (G.threeLeft cell) =
      defectPastingProduct data reselection (G.threeRight cell)

/--
Under the declared syzygy direction hypothesis, the unconditional raw defect
satisfies the corresponding 3-cell cocycle equation.  No cocycle claim is made
from admissibility alone.
-/
theorem rawDefect_cocycle_of_syzygy
    {G : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : AdmissibleTransportData G U)
    (reselection : EdgeReselection data.lift)
    (compatible : SyzygyCompatible data reselection)
    (cell : G.ThreeCell) :
    defectPastingProduct data reselection (G.threeLeft cell) =
      defectPastingProduct data reselection (G.threeRight cell) :=
  compatible cell

end AAT.AG.TransportCoherence

#assert_standard_axioms_only AAT.AG.TransportCoherence
