import ResearchLean.AG.SFT.ConwayOwnerUniformSelectorQuotientBridge

/-!
Cycle 20 evidence for `G-sft-conway-01`.

Cycle 17 recorded the owner-uniform local/global gap as a selected
quotient-style receiver, and Cycle 19 compared the quotient-style and selector
presentations.  This file makes the finite receiver an explicit quotient
carrier: the selected owner-uniform Conway class is the image of the family
defect in `OwnerUniformFamilyZ2` modulo the boundary subgroup generated by
explicit owner-uniform boundary generators.

This is a selected finite quotient carrier.  It does not claim a universal
quotient theorem, arbitrary-cover naturality, a canonical selector, or a sheaf
`H^1` theorem.
-/

namespace ResearchLean.AG
namespace SFT
namespace ConwayTwoTopology

/-! ## Selected finite quotient carrier -/

/--
The selected finite quotient carrier for the owner-uniform Conway obstruction
of a support-fork family.
-/
abbrev OwnerUniformConwayQuotient {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) :=
  OwnerUniformFamilyZ2 ⧸ OwnerUniformFamilyBoundarySubgroup family

/-- The selected owner-uniform Conway class of a support-fork family. -/
def OwnerUniformConwayClass {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) :
    OwnerUniformConwayQuotient family :=
  QuotientAddGroup.mk (OwnerUniformFamilyDefect family)

/-! ## Presentation comparisons -/

/--
The selected Conway class is zero exactly when the Cycle 17 boundary-membership
presentation vanishes.
-/
theorem ownerUniformConwayClass_eq_zero_iff_familyClassVanishes
    {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) :
    OwnerUniformConwayClass family = 0 ↔
      OwnerUniformFamilyClassVanishes family := by
  exact QuotientAddGroup.eq_zero_iff (OwnerUniformFamilyDefect family)

/--
The selected Conway class is zero exactly when an owner-uniform span selector
exists.
-/
theorem ownerUniformConwayClass_eq_zero_iff_spanSelector
    {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) :
    OwnerUniformConwayClass family = 0 ↔
      Nonempty (OwnerUniformSpanSelector family) := by
  rw [ownerUniformConwayClass_eq_zero_iff_familyClassVanishes]
  exact (ownerUniformSpanSelector_nonempty_iff_familyClassVanishes family).symm

/--
Nonzero of the selected Conway class is the same as the Cycle 18
span-selector obstruction, provided the family is forkwise selectable.
-/
theorem ownerUniformConwayClass_ne_zero_iff_selectorObstruction
    {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas)
    (hforkwise : ForkwiseCommonRefinementSpanSelectable family) :
    OwnerUniformConwayClass family ≠ 0 ↔
      OwnerUniformSpanSelectorObstruction family := by
  constructor
  · intro hnonzero
    exact
      ownerUniformSpanSelectorObstruction_of_forkwiseSelectable_nonzeroClass
        hforkwise
        (by
          intro hvanish
          exact hnonzero
            ((ownerUniformConwayClass_eq_zero_iff_familyClassVanishes
              family).2 hvanish))
  · intro hobstruction hzero
    have hvanish :
        OwnerUniformFamilyClassVanishes family :=
      (ownerUniformConwayClass_eq_zero_iff_familyClassVanishes family).1 hzero
    have hnonzero :
        OwnerUniformFamilyNonzeroClass family :=
      ownerUniformFamilyNonzeroClass_of_spanSelectorObstruction hobstruction
    exact hnonzero hvanish

/--
The selected Conway class is nonzero exactly when the Cycle 17 nonzero class
predicate holds.
-/
theorem ownerUniformConwayClass_ne_zero_iff_familyNonzeroClass
    {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) :
    OwnerUniformConwayClass family ≠ 0 ↔
      OwnerUniformFamilyNonzeroClass family := by
  constructor
  · intro hnonzero hvanish
    exact hnonzero
      ((ownerUniformConwayClass_eq_zero_iff_familyClassVanishes family).2
        hvanish)
  · intro hnonzero hzero
    exact hnonzero
      ((ownerUniformConwayClass_eq_zero_iff_familyClassVanishes family).1
        hzero)

/-! ## Restricted singleton/full-family witness -/

/-- Every selected singleton subfamily has zero selected Conway class. -/
theorem restrictedSingletonSubfamilies_ownerUniformConwayClass_zero
    (sub : RestrictedSingletonSubfamilyIdx) :
    OwnerUniformConwayClass (restrictedSingletonSubfamily sub) = 0 := by
  exact
    (ownerUniformConwayClass_eq_zero_iff_familyClassVanishes
      (restrictedSingletonSubfamily sub)).2
        (restrictedSingletonSubfamilies_ownerUniformFamilyClass_vanishes sub)

/-- The full restricted two-fork family has nonzero selected Conway class. -/
theorem restrictedTwoForkFamily_ownerUniformConwayClass_nonzero :
    OwnerUniformConwayClass restrictedTwoForkFamily ≠ 0 := by
  exact
    (ownerUniformConwayClass_ne_zero_iff_familyNonzeroClass
      restrictedTwoForkFamily).2
        restrictedTwoForkFamily_ownerUniformFamilyClass_nonzero

/--
For the restricted two-fork witness, nonzero of the selected Conway class is
equivalent to the owner-uniform span-selector obstruction.
-/
theorem restrictedTwoForkFamily_conwayClass_nonzero_iff_selectorObstruction :
    OwnerUniformConwayClass restrictedTwoForkFamily ≠ 0 ↔
      OwnerUniformSpanSelectorObstruction restrictedTwoForkFamily :=
  ownerUniformConwayClass_ne_zero_iff_selectorObstruction
    restrictedTwoForkFamily
    restrictedTwoForkFamily_forkwiseSpanSelectable

/--
The selected Cycle 20 package: the owner-uniform obstruction now has an explicit
finite quotient carrier; zero of its class is the boundary-generator/selector
presentation; singleton subfamilies are zero; and the full restricted two-fork
family is nonzero.
-/
theorem selectedOwnerUniformTrueQuotientPackage :
    (forall {atlas : TwoCoverAtlas}
      (family : SupportForkFamily atlas),
        OwnerUniformConwayClass family = 0 ↔
          OwnerUniformFamilyClassVanishes family) /\
      (forall {atlas : TwoCoverAtlas}
        (family : SupportForkFamily atlas),
          OwnerUniformConwayClass family = 0 ↔
            Nonempty (OwnerUniformSpanSelector family)) /\
      (forall sub : RestrictedSingletonSubfamilyIdx,
        OwnerUniformConwayClass
          (restrictedSingletonSubfamily sub) = 0) /\
      OwnerUniformConwayClass restrictedTwoForkFamily ≠ 0 /\
      (OwnerUniformConwayClass restrictedTwoForkFamily ≠ 0 ↔
        OwnerUniformSpanSelectorObstruction restrictedTwoForkFamily) := by
  exact
    ⟨(by
        intro atlas family
        exact
          ownerUniformConwayClass_eq_zero_iff_familyClassVanishes family),
      (by
        intro atlas family
        exact ownerUniformConwayClass_eq_zero_iff_spanSelector family),
      restrictedSingletonSubfamilies_ownerUniformConwayClass_zero,
      restrictedTwoForkFamily_ownerUniformConwayClass_nonzero,
      restrictedTwoForkFamily_conwayClass_nonzero_iff_selectorObstruction⟩

end ConwayTwoTopology
end SFT
end ResearchLean.AG
