import Mathlib.Algebra.Group.Subgroup.Lattice
import Mathlib.Data.ZMod.Basic
import ResearchLean.AG.SFT.ConwayOwnerUniformSubfamilyDescent

/-!
Cycle 17 evidence for `G-sft-conway-01`.

Cycle 15/16 isolated an owner-uniform local/global gap: singleton subfamilies
have owner-uniform support, but the full restricted two-fork family does not.
This file records that gap in a selected finite quotient-style receiver.  An
owner-uniform family support is treated as explicit boundary-generator
provenance, and the selected `ZMod 2` defect vanishes exactly when such a
generator exists.

This is selected finite receiver vocabulary.  It is not a true sheaf `H^1`
construction, arbitrary-cover naturality, or a functorial quotient theorem.
-/

namespace ResearchLean.AG
namespace SFT
namespace ConwayTwoTopology

/-! ## Owner-uniform family boundary generators -/

/-- The selected finite coefficient group for owner-uniform family defects. -/
abbrev OwnerUniformFamilyZ2 :=
  ZMod 2

/-- The selected owner-uniform defect carried by a support-fork family. -/
def OwnerUniformFamilyDefect {atlas : TwoCoverAtlas}
    (_family : SupportForkFamily atlas) : OwnerUniformFamilyZ2 :=
  1

/-- The selected owner-uniform family defect is nonzero in `ZMod 2`. -/
theorem ownerUniformFamilyDefect_nonzero {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) :
    OwnerUniformFamilyDefect family ≠ 0 := by
  change (1 : OwnerUniformFamilyZ2) ≠ 0
  decide

/--
An explicit boundary generator for a family defect: an owner-uniform coherent
common-refinement support witness for the selected fork family.
-/
structure OwnerUniformFamilyBoundaryGenerator {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) where
  support : OwnerUniformCoherentCommonRefinementSupport family

namespace OwnerUniformFamilyBoundaryGenerator

/-- A boundary generator forgets to the Cycle 15 owner-uniform support witness. -/
def toOwnerUniformSupport {atlas : TwoCoverAtlas}
    {family : SupportForkFamily atlas}
    (generator : OwnerUniformFamilyBoundaryGenerator family) :
    OwnerUniformCoherentCommonRefinementSupport family :=
  generator.support

/-- A Cycle 15 owner-uniform support witness can be recorded as a boundary generator. -/
def ofOwnerUniformSupport {atlas : TwoCoverAtlas}
    {family : SupportForkFamily atlas}
    (support : OwnerUniformCoherentCommonRefinementSupport family) :
    OwnerUniformFamilyBoundaryGenerator family where
  support := support

end OwnerUniformFamilyBoundaryGenerator

/-- Boundary generators exist exactly when the family has owner-uniform support. -/
theorem ownerUniformFamilyBoundaryGenerator_nonempty_iff_support
    {atlas : TwoCoverAtlas} (family : SupportForkFamily atlas) :
    Nonempty (OwnerUniformFamilyBoundaryGenerator family) ↔
      ForkFamilyHasOwnerUniformCoherentSupport family := by
  constructor
  · intro h
    rcases h with ⟨generator⟩
    exact ⟨generator.toOwnerUniformSupport⟩
  · intro h
    rcases h with ⟨support⟩
    exact ⟨OwnerUniformFamilyBoundaryGenerator.ofOwnerUniformSupport support⟩

/--
The selected generator-provenance boundary subgroup for a family.  It is
generated by the selected family defect contributed by explicit owner-uniform
boundary generators.
-/
noncomputable def OwnerUniformFamilyBoundarySubgroup
    {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) : AddSubgroup OwnerUniformFamilyZ2 :=
  AddSubgroup.closure
    { value | exists _generator : OwnerUniformFamilyBoundaryGenerator family,
      value = OwnerUniformFamilyDefect family }

/-- The selected family defect vanishes modulo the owner-uniform boundary subgroup. -/
def OwnerUniformFamilyClassVanishes {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) : Prop :=
  OwnerUniformFamilyDefect family ∈ OwnerUniformFamilyBoundarySubgroup family

/-- A selected family has nonzero owner-uniform class when the defect is not a boundary. -/
def OwnerUniformFamilyNonzeroClass {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) : Prop :=
  Not (OwnerUniformFamilyClassVanishes family)

/-- A boundary generator absorbs the selected owner-uniform family defect. -/
theorem ownerUniformFamilyBoundary_absorbs_defect
    {atlas : TwoCoverAtlas}
    {family : SupportForkFamily atlas}
    (generator : OwnerUniformFamilyBoundaryGenerator family) :
    OwnerUniformFamilyDefect family ∈
      OwnerUniformFamilyBoundarySubgroup family := by
  exact AddSubgroup.subset_closure ⟨generator, rfl⟩

/-- If no owner-uniform support exists, the generator boundary subgroup is zero. -/
theorem ownerUniformFamilyBoundarySubgroup_le_bot_of_noSupport
    {atlas : TwoCoverAtlas}
    {family : SupportForkFamily atlas}
    (hNoSupport : Not (ForkFamilyHasOwnerUniformCoherentSupport family)) :
    OwnerUniformFamilyBoundarySubgroup family ≤
      (⊥ : AddSubgroup OwnerUniformFamilyZ2) := by
  apply
    (AddSubgroup.closure_le
      (⊥ : AddSubgroup OwnerUniformFamilyZ2)).2
  intro value hvalue
  rcases hvalue with ⟨generator, rfl⟩
  exact False.elim (hNoSupport ⟨generator.toOwnerUniformSupport⟩)

/--
Without owner-uniform support, the selected family defect does not vanish modulo
the explicit generator boundary subgroup.
-/
theorem ownerUniformFamilyClass_nonzero_of_noSupport
    {atlas : TwoCoverAtlas}
    {family : SupportForkFamily atlas}
    (hNoSupport : Not (ForkFamilyHasOwnerUniformCoherentSupport family)) :
    OwnerUniformFamilyNonzeroClass family := by
  intro hvanish
  have hleBot :
      OwnerUniformFamilyBoundarySubgroup family ≤
        (⊥ : AddSubgroup OwnerUniformFamilyZ2) :=
    ownerUniformFamilyBoundarySubgroup_le_bot_of_noSupport hNoSupport
  have hzero : OwnerUniformFamilyDefect family = 0 :=
    AddSubgroup.mem_bot.mp (hleBot hvanish)
  exact ownerUniformFamilyDefect_nonzero family hzero

/--
The selected owner-uniform family class vanishes exactly when explicit
owner-uniform boundary-generator provenance exists.
-/
theorem ownerUniformFamilyClass_vanishes_iff_support
    {atlas : TwoCoverAtlas}
    (family : SupportForkFamily atlas) :
    OwnerUniformFamilyClassVanishes family ↔
      ForkFamilyHasOwnerUniformCoherentSupport family := by
  constructor
  · intro hvanish
    by_contra hNoSupport
    exact ownerUniformFamilyClass_nonzero_of_noSupport hNoSupport hvanish
  · intro hsupport
    rcases hsupport with ⟨support⟩
    exact
      ownerUniformFamilyBoundary_absorbs_defect
        (OwnerUniformFamilyBoundaryGenerator.ofOwnerUniformSupport support)

/-! ## Restricted singleton/full-family separation -/

/-- The API singleton subfamily has zero owner-uniform family class. -/
theorem restrictedApiSingletonFamily_ownerUniformFamilyClass_vanishes :
    OwnerUniformFamilyClassVanishes restrictedApiSingletonFamily := by
  rw [ownerUniformFamilyClass_vanishes_iff_support]
  exact restrictedApiSingletonFamily_ownerUniformSupport

/-- The DB singleton subfamily has zero owner-uniform family class. -/
theorem restrictedDbSingletonFamily_ownerUniformFamilyClass_vanishes :
    OwnerUniformFamilyClassVanishes restrictedDbSingletonFamily := by
  rw [ownerUniformFamilyClass_vanishes_iff_support]
  exact restrictedDbSingletonFamily_ownerUniformSupport

/-- Every selected singleton subfamily has zero owner-uniform family class. -/
theorem restrictedSingletonSubfamilies_ownerUniformFamilyClass_vanishes
    (sub : RestrictedSingletonSubfamilyIdx) :
    OwnerUniformFamilyClassVanishes
      (restrictedSingletonSubfamily sub) := by
  cases sub with
  | apiOnly =>
      exact restrictedApiSingletonFamily_ownerUniformFamilyClass_vanishes
  | dbOnly =>
      exact restrictedDbSingletonFamily_ownerUniformFamilyClass_vanishes

/--
The full restricted two-fork family has nonzero owner-uniform family class: its
selected singleton subfamilies are locally zero, but no owner-uniform boundary
generator exists for the full family.
-/
theorem restrictedTwoForkFamily_ownerUniformFamilyClass_nonzero :
    OwnerUniformFamilyNonzeroClass restrictedTwoForkFamily :=
  ownerUniformFamilyClass_nonzero_of_noSupport
    restrictedTwoForkFamily_notOwnerUniformCoherent

/--
The selected Cycle 17 package: the owner-uniform local/global gap is recorded as
a finite quotient-style class.  Singleton subfamilies vanish, while the full
restricted two-fork family has nonzero class.
-/
theorem selectedOwnerUniformFamilyQuotientPackage :
    (forall {atlas : TwoCoverAtlas}
      {family : SupportForkFamily atlas},
        OwnerUniformFamilyClassVanishes family ↔
          ForkFamilyHasOwnerUniformCoherentSupport family) /\
      (forall sub : RestrictedSingletonSubfamilyIdx,
        OwnerUniformFamilyClassVanishes
          (restrictedSingletonSubfamily sub)) /\
      SupportForkFamilySubcover
        restrictedTwoForkFamily
        RestrictedSingletonSubfamilyIdx
        restrictedSingletonSubfamily /\
      OwnerUniformFamilyNonzeroClass restrictedTwoForkFamily /\
      OwnerUniformSubfamilyDescentFailure
        restrictedTwoForkFamily
        RestrictedSingletonSubfamilyIdx
        restrictedSingletonSubfamily := by
  exact
    ⟨(by
        intro atlas family
        exact ownerUniformFamilyClass_vanishes_iff_support family),
      restrictedSingletonSubfamilies_ownerUniformFamilyClass_vanishes,
      restrictedSingletonSubfamilies_cover,
      restrictedTwoForkFamily_ownerUniformFamilyClass_nonzero,
      restrictedTwoForkFamily_ownerUniformSubfamilyDescentFailure⟩

end ConwayTwoTopology
end SFT
end ResearchLean.AG
