import ResearchLean.AG.CrossStageCoherence.ComparisonDescent
import ResearchLean.AG.CrossStageCoherence.SectionDecomposition

/-!
# Core pushforward of cell-chain comparison descent

This module implements the first part of fixed G-109 theorem (G).  It reuses
the reviewed core oriented-face and pasting evaluators, and proves that the
group homomorphism `compositeFiberPushforward` commutes with authored and
canonical cell factors, twisted affine steps, complete route transport, and
closed-chain holonomy.  A normalized upper comparison section therefore
pushes pointwise to a normalized core comparison section, and upper
cell-chain coherence preserves every closed core route.

## Implementation notes

The core factors are defined through the existing
`orientedFaceAuthoredComparator` and
`orientedFaceCanonicalComparator`; no second orientation or product
convention is introduced.  Defining them merely as names for the image of the
upper factors was rejected: the comparison theorems below instead prove that
the existing core evaluator is the image.  The ambient input is exactly the
fixed two-layer transport datum.  No coherence, section, factorization, or
kernel-membership certificate is added to it.
-/

namespace AAT.AG.CrossStageCoherence

universe u v

open CategoryTheory
open AtomFoundation
open GeometryTransport
open TransportCoherence

set_option maxHeartbeats 3000000

/-- The authored factor of one typed step, evaluated by the reviewed core oriented-face API. -/
noncomputable def coreCellAuthoredFactor
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {before after : CellChainNode P source target}
    (step : CellChainStep P before after) :
    PackageFiberAut (data.coreData.lift.package target) :=
  orientedFaceAuthoredComparator data.coreData 1
    step.toRewriteStep.face

/-- The canonical factor of one typed step, generated by the reviewed core evaluator. -/
noncomputable def coreCellCanonicalFactor
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {before after : CellChainNode P source target}
    (step : CellChainStep P before after) :
    PackageFiberAut (data.coreData.lift.package target) :=
  orientedFaceCanonicalComparator data.coreData 1
    step.toRewriteStep.face

/-- Projection sends each upper authored factor to the existing core authored factor. -/
theorem pushforward_cellAuthoredFactor
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {before after : CellChainNode P source target}
    (step : CellChainStep P before after) :
    compositeFiberPushforward (data.lift.geometry target)
        (cellAuthoredFactor data step) =
      coreCellAuthoredFactor data step := by
  rw [cellAuthoredFactor_eq_upperOrientedFaceAuthoredComparator]
  unfold upperOrientedFaceAuthoredComparator coreCellAuthoredFactor
  rw [pushforward_upperOrientedFaceComparator,
    pushforwardEdgeReselection_one]
  rfl

/-- Projection sends each generated upper canonical factor to the existing core one. -/
theorem pushforward_cellCanonicalFactor
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {before after : CellChainNode P source target}
    (step : CellChainStep P before after) :
    compositeFiberPushforward (data.lift.geometry target)
        (cellCanonicalFactor data 1 step) =
      coreCellCanonicalFactor data step := by
  rw [cellCanonicalFactor_eq_upperOrientedFaceCanonicalComparator]
  unfold upperOrientedFaceCanonicalComparator coreCellCanonicalFactor
  rw [pushforward_upperOrientedFaceComparator,
    pushforwardEdgeReselection_one]
  apply congrArg (fun family =>
    orientedFaceComparator data.coreData 1 family
      step.toRewriteStep.face)
  funext cell
  exact pushforward_upperCanonicalTwoCellComparator data 1 cell

/-- On a declared forward cell, the core authored factor is the projected input comparator. -/
theorem coreCellAuthoredFactor_forward
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U) (cell : P.TwoCell) :
    coreCellAuthoredFactor data (CellChainStep.forward cell) =
      data.coreData.comparator cell := by
  simp [coreCellAuthoredFactor, CellChainStep.toRewriteStep,
    CellChainStep.forward,
    orientedFaceAuthoredComparator, orientedFaceComparator,
    authoredComparatorFamily]

/-- On a declared forward cell, the core canonical factor is the G-106 comparator. -/
theorem coreCellCanonicalFactor_forward
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U) (cell : P.TwoCell) :
    coreCellCanonicalFactor data (CellChainStep.forward cell) =
      canonicalTwoCellComparator data.coreData 1 cell := by
  simp [coreCellCanonicalFactor, CellChainStep.toRewriteStep,
    CellChainStep.forward,
    orientedFaceCanonicalComparator, orientedFaceComparator,
    canonicalComparatorFamily]

/-- The fixed core affine action `x ↦ p(u) * x * p(φ₀)⁻¹` of one typed step. -/
noncomputable def CoreCellAffineStep
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {before after : CellChainNode P source target}
    (step : CellChainStep P before after) :
    PackageFiberAut (data.coreData.lift.package target) ≃
      PackageFiberAut (data.coreData.lift.package target) :=
  cellGaugeAffineEquiv (coreCellAuthoredFactor data step)
    (coreCellCanonicalFactor data step)

/-- Expose the core affine formula without unfolding its equivalence record. -/
theorem coreCellAffineStep_apply
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {before after : CellChainNode P source target}
    (step : CellChainStep P before after)
    (coordinate : PackageFiberAut (data.coreData.lift.package target)) :
    CoreCellAffineStep data step coordinate =
      coreCellAuthoredFactor data step * coordinate *
        (coreCellCanonicalFactor data step)⁻¹ :=
  rfl

/-- A forward core affine step uses the projected authored and canonical cell data. -/
theorem coreCellAffineStep_forward_apply
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U) (cell : P.TwoCell)
    (coordinate :
      PackageFiberAut (data.coreData.lift.package (P.twoTarget cell))) :
    CoreCellAffineStep data (CellChainStep.forward cell) coordinate =
      data.coreData.comparator cell * coordinate *
        (canonicalTwoCellComparator data.coreData 1 cell)⁻¹ := by
  rw [coreCellAffineStep_apply, coreCellAuthoredFactor_forward,
    coreCellCanonicalFactor_forward]

/-- The group projection intertwines every upper affine step with its core step. -/
theorem pushforward_cellAffineStep
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {before after : CellChainNode P source target}
    (step : CellChainStep P before after)
    (coordinate : CompositeFiberAut (data.lift.geometry target)) :
    compositeFiberPushforward (data.lift.geometry target)
        (CellAffineStep data step coordinate) =
      CoreCellAffineStep data step
        (compositeFiberPushforward (data.lift.geometry target) coordinate) := by
  rw [cellAffineStep_apply, coreCellAffineStep_apply, map_mul, map_mul, map_inv,
    pushforward_cellAuthoredFactor, pushforward_cellCanonicalFactor]

/-- Compose the reviewed core affine steps along one endpoint-indexed cell chain. -/
noncomputable def CoreCellRouteTransport
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {first last : CellChainNode P source target}
    (chain : CellChain P first last) :
    PackageFiberAut (data.coreData.lift.package target) ≃
      PackageFiberAut (data.coreData.lift.package target) :=
  match chain with
  | .nil _ => Equiv.refl _
  | .cons step tail =>
      (CoreCellAffineStep data step).trans (CoreCellRouteTransport data tail)

/-- Projection commutes pointwise with complete cell-route transport. -/
theorem pushforward_cellRouteTransport
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {first last : CellChainNode P source target}
    (chain : CellChain P first last)
    (coordinate : CompositeFiberAut (data.lift.geometry target)) :
    compositeFiberPushforward (data.lift.geometry target)
        (CellRouteTransport data chain coordinate) =
      CoreCellRouteTransport data chain
        (compositeFiberPushforward (data.lift.geometry target) coordinate) := by
  induction chain generalizing coordinate with
  | nil node => rfl
  | cons step tail inductionHypothesis =>
      change compositeFiberPushforward (data.lift.geometry target)
          (CellRouteTransport data tail (CellAffineStep data step coordinate)) =
        CoreCellRouteTransport data tail
          (CoreCellAffineStep data step
            (compositeFiberPushforward (data.lift.geometry target) coordinate))
      rw [inductionHypothesis, pushforward_cellAffineStep]

/-- The authored core word accumulated in the reviewed route-composition order. -/
noncomputable def coreCellAuthoredWord
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {first last : CellChainNode P source target}
    (chain : CellChain P first last) :
    PackageFiberAut (data.coreData.lift.package target) :=
  match chain with
  | .nil _ => 1
  | .cons step tail =>
      coreCellAuthoredWord data tail * coreCellAuthoredFactor data step

/-- The generated canonical core word accumulated in route-composition order. -/
noncomputable def coreCellCanonicalWord
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {first last : CellChainNode P source target}
    (chain : CellChain P first last) :
    PackageFiberAut (data.coreData.lift.package target) :=
  match chain with
  | .nil _ => 1
  | .cons step tail =>
      coreCellCanonicalWord data tail * coreCellCanonicalFactor data step

/-- The core authored word is exactly the existing authored pasting evaluator. -/
theorem coreCellAuthoredWord_eq_authoredPastingComparator
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {first last : CellChainNode P source target}
    (chain : CellChain P first last) :
    coreCellAuthoredWord data chain =
      authoredPastingComparator data.coreData 1
        chain.toRewritePasting := by
  induction chain with
  | nil node => rfl
  | cons step tail inductionHypothesis =>
      simp only [coreCellAuthoredWord, CellChain.toRewritePasting,
        authoredPastingComparator, pastingComparator]
      rw [inductionHypothesis]
      rfl

/-- The core canonical word is exactly the existing canonical pasting evaluator. -/
theorem coreCellCanonicalWord_eq_canonicalPastingComparator
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {first last : CellChainNode P source target}
    (chain : CellChain P first last) :
    coreCellCanonicalWord data chain =
      canonicalPastingComparator data.coreData 1
        chain.toRewritePasting := by
  induction chain with
  | nil node => rfl
  | cons step tail inductionHypothesis =>
      simp only [coreCellCanonicalWord, CellChain.toRewritePasting,
        canonicalPastingComparator, pastingComparator]
      rw [inductionHypothesis]
      rfl

/-- Projection sends the complete upper authored word to the complete core word. -/
theorem pushforward_cellAuthoredWord
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {first last : CellChainNode P source target}
    (chain : CellChain P first last) :
    compositeFiberPushforward (data.lift.geometry target)
        (cellAuthoredWord data chain) =
      coreCellAuthoredWord data chain := by
  induction chain with
  | nil node => exact map_one _
  | cons step tail inductionHypothesis =>
      simp only [cellAuthoredWord, coreCellAuthoredWord, map_mul]
      rw [inductionHypothesis, pushforward_cellAuthoredFactor]

/-- Projection sends the complete upper canonical word to the complete core word. -/
theorem pushforward_cellCanonicalWord
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {first last : CellChainNode P source target}
    (chain : CellChain P first last) :
    compositeFiberPushforward (data.lift.geometry target)
        (cellCanonicalWord data 1 chain) =
      coreCellCanonicalWord data chain := by
  induction chain with
  | nil node => exact map_one _
  | cons step tail inductionHypothesis =>
      simp only [cellCanonicalWord, coreCellCanonicalWord, map_mul]
      rw [inductionHypothesis, pushforward_cellCanonicalFactor]

/-- Core route transport has the two-sided authored/canonical word normal form. -/
theorem coreCellRouteTransport_apply
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {first last : CellChainNode P source target}
    (chain : CellChain P first last)
    (coordinate : PackageFiberAut (data.coreData.lift.package target)) :
    CoreCellRouteTransport data chain coordinate =
      coreCellAuthoredWord data chain * coordinate *
        (coreCellCanonicalWord data chain)⁻¹ := by
  induction chain generalizing coordinate with
  | nil node =>
      simp [CoreCellRouteTransport, coreCellAuthoredWord,
        coreCellCanonicalWord]
  | cons step tail inductionHypothesis =>
      simp only [CoreCellRouteTransport, Equiv.trans_apply,
        CoreCellAffineStep, cellGaugeAffineEquiv, coreCellAuthoredWord,
        coreCellCanonicalWord]
      change CoreCellRouteTransport data tail
          (coreCellAuthoredFactor data step * coordinate *
            (coreCellCanonicalFactor data step)⁻¹) = _
      rw [inductionHypothesis]
      group

/-- Every closed core canonical word is identity, by projected canonical thinness. -/
theorem coreCellCanonicalWord_closed_eq_one
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {node : CellChainNode P source target}
    (chain : CellChain P node node) :
    coreCellCanonicalWord data chain = 1 := by
  have projected := congrArg
    (compositeFiberPushforward (data.lift.geometry target))
    (cellCanonicalWord_closed_eq_one data 1 chain)
  rw [pushforward_cellCanonicalWord, map_one] at projected
  exact projected

/-- Core holonomy is core route transport evaluated at the identity coordinate. -/
noncomputable def CoreCellChainHolonomy
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {node : CellChainNode P source target}
    (chain : CellChain P node node) :
    PackageFiberAut (data.coreData.lift.package target) :=
  CoreCellRouteTransport data chain 1

/-- Projection preserves closed cell-chain holonomy. -/
theorem pushforward_cellChainHolonomy
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {node : CellChainNode P source target}
    (chain : CellChain P node node) :
    compositeFiberPushforward (data.lift.geometry target)
        (CellChainHolonomy data chain) =
      CoreCellChainHolonomy data chain := by
  unfold CellChainHolonomy CoreCellChainHolonomy
  rw [pushforward_cellRouteTransport, map_one]

/-- A closed core route is left multiplication by its pushed holonomy. -/
theorem coreCellRouteTransport_closed_apply
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {node : CellChainNode P source target}
    (chain : CellChain P node node)
    (coordinate : PackageFiberAut (data.coreData.lift.package target)) :
    CoreCellRouteTransport data chain coordinate =
      CoreCellChainHolonomy data chain * coordinate := by
  rw [coreCellRouteTransport_apply,
    coreCellCanonicalWord_closed_eq_one data chain]
  simp only [inv_one, mul_one]
  unfold CoreCellChainHolonomy
  rw [coreCellRouteTransport_apply,
    coreCellCanonicalWord_closed_eq_one data chain]
  simp

/-- Fixed theorem (G), coherence part: upper coherence makes every closed core route identity. -/
theorem cellChainCoherent_core
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    (coherent : CellChainCoherent data) :
    ∀ (source target : P.Vertex) (node : CellChainNode P source target)
      (chain : CellChain P node node),
      CoreCellRouteTransport data chain = Equiv.refl _ := by
  intro source target node chain
  have upperIdentity :=
    (cellChainCoherent_iff_holonomy_eq_one data).1 coherent
      source target node chain
  have coreIdentity := congrArg
    (compositeFiberPushforward (data.lift.geometry target)) upperIdentity
  rw [pushforward_cellChainHolonomy, map_one] at coreIdentity
  apply Equiv.ext
  intro coordinate
  rw [coreCellRouteTransport_closed_apply, coreIdentity, one_mul]
  rfl

/-- The projected descent datum: core node coordinates, nil normalization, and the forward core equation. -/
structure CoreCellComparisonSection
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U) where
  value : ∀ {source target : P.Vertex},
    CellChainNode P source target →
      PackageFiberAut (data.coreData.lift.package target)
  nil_normalization : ∀ vertex : P.Vertex,
    value (CellChainNode.nil P vertex) = 1
  naturality : ∀ cell : P.TwoCell,
    value (CellChainNode.right P cell) =
      data.coreData.comparator cell * value (CellChainNode.left P cell) *
        (canonicalTwoCellComparator data.coreData 1 cell)⁻¹

namespace CoreCellComparisonSection

/-- The forward core equation generates naturality for every dependent oriented step. -/
theorem naturality_affine
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    {data : TwoLayerTransportData.{u, v} P U}
    (comparison : CoreCellComparisonSection data)
    {source target : P.Vertex}
    {before after : CellChainNode P source target}
    (step : CellChainStep P before after) :
    comparison.value after =
      CoreCellAffineStep data step (comparison.value before) := by
  rcases step with
    ⟨cell, source_eq, target_eq, orientation, before_eq, after_eq⟩
  subst source
  subst target
  cases orientation
  · have before_node : before = CellChainNode.left P cell :=
      CellChainNode.ext (by
        simpa [orientedCellBeforePath, castPresentedPath] using before_eq)
    have after_node : after = CellChainNode.right P cell :=
      CellChainNode.ext (by
        simpa [orientedCellAfterPath, castPresentedPath] using after_eq)
    subst before
    subst after
    rw [coreCellAffineStep_apply]
    simpa [coreCellAuthoredFactor, coreCellCanonicalFactor,
      CellChainStep.toRewriteStep, CellChainStep.forward,
      orientedFaceAuthoredComparator, orientedFaceCanonicalComparator,
      orientedFaceComparator, authoredComparatorFamily,
      canonicalComparatorFamily] using comparison.naturality cell
  · have before_node : before = CellChainNode.right P cell :=
      CellChainNode.ext (by
        simpa [orientedCellBeforePath, castPresentedPath] using before_eq)
    have after_node : after = CellChainNode.left P cell :=
      CellChainNode.ext (by
        simpa [orientedCellAfterPath, castPresentedPath] using after_eq)
    subst before
    subst after
    rw [coreCellAffineStep_apply]
    have forward := comparison.naturality cell
    simp only [coreCellAuthoredFactor, coreCellCanonicalFactor,
      CellChainStep.toRewriteStep, orientedFaceAuthoredComparator,
      orientedFaceCanonicalComparator, orientedFaceComparator,
      authoredComparatorFamily, canonicalComparatorFamily,
      whiskerFiberAut_nil]
    rw [forward]
    group

/-- Reverse-step core naturality is derived from the generated affine equation. -/
theorem naturality_backward
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    {data : TwoLayerTransportData.{u, v} P U}
    (comparison : CoreCellComparisonSection data)
    {source target : P.Vertex}
    {before after : CellChainNode P source target}
    (step : CellChainStep P before after) :
    comparison.value before =
      (coreCellAuthoredFactor data step)⁻¹ * comparison.value after *
        coreCellCanonicalFactor data step := by
  rw [comparison.naturality_affine step, coreCellAffineStep_apply]
  group

end CoreCellComparisonSection

/-- Fixed theorem (G), section part: push an upper comparison section pointwise to core. -/
noncomputable def CellComparisonSection.pushforwardCore
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    {data : TwoLayerTransportData.{u, v} P U}
    (comparison : CellComparisonSection data) :
    CoreCellComparisonSection data where
  value := fun {_ _} node =>
    compositeFiberPushforward (data.lift.geometry _) (comparison.value node)
  nil_normalization := by
    intro vertex
    rw [comparison.nil_normalization]
    exact map_one _
  naturality := by
    intro cell
    have mapped := congrArg
      (compositeFiberPushforward
        (data.lift.geometry (P.twoTarget cell)))
      (comparison.naturality cell)
    rw [map_mul, map_mul, map_inv,
      pushforward_upperCanonicalTwoCellComparator,
      pushforwardEdgeReselection_one] at mapped
    exact mapped

/-- Pointwise evaluation of the pushed section is exactly `compositeFiberPushforward`. -/
theorem CellComparisonSection.pushforwardCore_value
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    {data : TwoLayerTransportData.{u, v} P U}
    (comparison : CellComparisonSection data)
    {source target : P.Vertex}
    (node : CellChainNode P source target) :
    comparison.pushforwardCore.value node =
      compositeFiberPushforward (data.lift.geometry target)
        (comparison.value node) :=
  rfl

/-- Parallel typed arrows have the same core canonical factor by upper strong cancellation. -/
theorem coreCellCanonicalFactor_eq_of_parallel
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {left right : CellChainNode P source target}
    (first second : CellChainStep P left right) :
    coreCellCanonicalFactor data first =
      coreCellCanonicalFactor data second := by
  rw [← pushforward_cellCanonicalFactor data first,
    ← pushforward_cellCanonicalFactor data second,
    cellCanonicalFactor_eq_of_parallel data 1 first second]

/-- Fixed theorem (G), kernel part: equal core projections force parallel holonomy into `H_G = ker p`. -/
theorem parallelCellTwoChain_holonomy_mem_innerFiberAutSubgroup_of_pushforward_eq
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    {source target : P.Vertex}
    {left right : CellChainNode P source target}
    (first second : CellChainStep P left right)
    (sameCore :
      compositeFiberPushforward (data.lift.geometry target)
          (cellAuthoredFactor data first) =
        compositeFiberPushforward (data.lift.geometry target)
          (cellAuthoredFactor data second)) :
    CellChainHolonomy data (parallelCellTwoChain first second) ∈
      innerFiberAutSubgroup (data.lift.geometry target) := by
  rw [innerFiberAutSubgroup_eq_ker]
  change compositeFiberPushforward (data.lift.geometry target)
      (CellChainHolonomy data (parallelCellTwoChain first second)) = 1
  rw [parallelCellTwoChain_holonomy, map_mul, map_inv,
    sameCore, mul_inv_cancel]

end AAT.AG.CrossStageCoherence

#assert_standard_axioms_only AAT.AG.CrossStageCoherence
