import ResearchLean.AG.CrossStageCoherence.Pseudofunctor

/-!
# Core-fiber transport over pointed doctrine morphisms

This module constructs the lower, core-stage transport pseudofunctor over the
same `ExtractionInstance` base used by the geometry stage.  Object transport
is the G-101 canonical package transport; the vertical action, compositor, and
unitor are generated by its strong cocartesian universal property.
-/

namespace AAT.AG.CrossStageCoherence

universe u

open CategoryTheory
open AtomFoundation

set_option maxHeartbeats 2000000

/-- The core-package fiber over a pointed extraction doctrine. -/
abbrev CoreFiber {U : AtomCarrier.{u}} (X : ExtractionInstance U) :=
  (packageProjection U).Fiber X

/-- The actual pointed base arrow used by core-fiber transport. -/
noncomputable def coreFiberBaseHom {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) (P : CoreFiber X) :
    (packageProjection U).obj P.1 ⟶ Y :=
  eqToHom P.2 ≫ σ

/-- The underlying core package transported along a pointed arrow. -/
noncomputable def coreFiberTransportObject {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) (P : CoreFiber X) :
    AATCorePackage U :=
  transportAlong P.1 (coreFiberBaseHom σ P).doctrineHom

/-- Canonical core transport lands over the selected pointed target. -/
theorem coreFiberTransportObject_point {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) (P : CoreFiber X) :
    (packageProjection U).obj (coreFiberTransportObject σ P) = Y := by
  apply ExtractionInstance.ext
  · rfl
  · apply heq_of_eq
    exact (coreFiberBaseHom σ P).source_eq

/-- The transported core package as an object of the target fiber. -/
noncomputable def coreFiberTransportObj {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) (P : CoreFiber X) :
    CoreFiber Y :=
  ⟨coreFiberTransportObject σ P, coreFiberTransportObject_point σ P⟩

/-- The canonical core lift over a pointed arrow. -/
noncomputable def coreFiberLift {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) (P : CoreFiber X) :
    P.1 ⟶ (coreFiberTransportObj σ P).1 :=
  transportAlongHom P.1 (coreFiberBaseHom σ P).doctrineHom

/-- The core lift projects to the authored pointed arrow, including fiber casts. -/
theorem coreFiberLift_projection {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) (P : CoreFiber X) :
    (packageProjection U).map (coreFiberLift σ P) ≫
        eqToHom (coreFiberTransportObj σ P).2 =
      eqToHom P.2 ≫ σ := by
  apply ExtInstHom.ext
  change (extInstToDoctrine U).map
      ((packageProjection U).map (coreFiberLift σ P) ≫
        eqToHom (coreFiberTransportObj σ P).2) =
    (extInstToDoctrine U).map (eqToHom P.2 ≫ σ)
  rw [Functor.map_comp, Functor.map_comp, eqToHom_map, eqToHom_map]
  simp [coreFiberLift, coreFiberTransportObj, coreFiberTransportObject,
    coreFiberBaseHom, extInstToDoctrine]
  have hlift :
      (transportAlongHom P.1
        (eqToHom P.2 ≫ σ).doctrineHom).base.doctrineHom =
        (eqToHom P.2 ≫ σ).doctrineHom := rfl
  rw [hlift]
  rw [← eqToHom_map (extInstToDoctrine U) P.2]
  rfl

/-- The canonical core lift is a lift of the authored pointed arrow. -/
theorem coreFiberLift_isHomLift {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) (P : CoreFiber X) :
    (packageProjection U).IsHomLift σ (coreFiberLift σ P) :=
  CategoryTheory.IsHomLift.of_commsq
    (packageProjection U) σ (coreFiberLift σ P)
    P.2 (coreFiberTransportObj σ P).2 (coreFiberLift_projection σ P)

/-- The canonical core lift is strongly cocartesian over the authored arrow. -/
theorem coreFiberLift_isStronglyCocartesian {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) (P : CoreFiber X) :
    (packageProjection U).IsStronglyCocartesian σ (coreFiberLift σ P) := by
  letI : (packageProjection U).IsStronglyCocartesian
      ((packageProjection U).map (coreFiberLift σ P))
      (coreFiberLift σ P) := by
    simpa only [coreFiberLift, packageProjection_map] using
      transportAlongHom_isStronglyCocartesian P.1
        (coreFiberBaseHom σ P).doctrineHom
  letI : (packageProjection U).IsHomLift σ (coreFiberLift σ P) :=
    coreFiberLift_isHomLift σ P
  exact stronglyCocartesian_of_isHomLift
    (packageProjection U) σ (coreFiberLift σ P)

/-- Transport a vertical core morphism by the canonical universal property. -/
noncomputable def coreFiberTransportMap {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    {P Q : CoreFiber X} (f : P ⟶ Q) :
    coreFiberTransportObj σ P ⟶ coreFiberTransportObj σ Q := by
  letI : (packageProjection U).IsStronglyCocartesian σ (coreFiberLift σ P) :=
    coreFiberLift_isStronglyCocartesian σ P
  letI : (packageProjection U).IsHomLift (𝟙 X) f.1 := f.2
  letI : (packageProjection U).IsHomLift σ (coreFiberLift σ Q) :=
    coreFiberLift_isHomLift σ Q
  letI : (packageProjection U).IsHomLift σ
      (f.1 ≫ coreFiberLift σ Q) := by
    simpa using inferInstanceAs
      ((packageProjection U).IsHomLift
        ((𝟙 X) ≫ σ) (f.1 ≫ coreFiberLift σ Q))
  exact ⟨CategoryTheory.Functor.IsStronglyCocartesian.map
      (packageProjection U) σ (coreFiberLift σ P)
      (g := 𝟙 Y) (f' := σ) (Category.comp_id σ).symm
      (f.1 ≫ coreFiberLift σ Q), inferInstance⟩

/-- Defining factorization equation of transported vertical core morphisms. -/
theorem coreFiberTransportMap_fac {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    {P Q : CoreFiber X} (f : P ⟶ Q) :
    coreFiberLift σ P ≫ (coreFiberTransportMap σ f).1 =
      f.1 ≫ coreFiberLift σ Q := by
  letI : (packageProjection U).IsStronglyCocartesian σ (coreFiberLift σ P) :=
    coreFiberLift_isStronglyCocartesian σ P
  letI : (packageProjection U).IsHomLift (𝟙 X) f.1 := f.2
  letI : (packageProjection U).IsHomLift σ (coreFiberLift σ Q) :=
    coreFiberLift_isHomLift σ Q
  letI : (packageProjection U).IsHomLift σ
      (f.1 ≫ coreFiberLift σ Q) := by
    simpa using inferInstanceAs
      ((packageProjection U).IsHomLift
        ((𝟙 X) ≫ σ) (f.1 ≫ coreFiberLift σ Q))
  exact CategoryTheory.Functor.IsStronglyCocartesian.fac
    (packageProjection U) σ (coreFiberLift σ P)
    (Category.comp_id σ).symm (f.1 ≫ coreFiberLift σ Q)

/-- Core vertical transport preserves identities. -/
theorem coreFiberTransportMap_id {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) (P : CoreFiber X) :
    coreFiberTransportMap σ (𝟙 P) = 𝟙 (coreFiberTransportObj σ P) := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  letI : (packageProjection U).IsStronglyCocartesian σ (coreFiberLift σ P) :=
    coreFiberLift_isStronglyCocartesian σ P
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) σ (coreFiberLift σ P) (𝟙 Y)
  simpa using coreFiberTransportMap_fac σ (𝟙 P)

/-- Core vertical transport preserves composition. -/
theorem coreFiberTransportMap_comp {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    {P Q R : CoreFiber X} (f : P ⟶ Q) (g : Q ⟶ R) :
    coreFiberTransportMap σ (f ≫ g) =
      coreFiberTransportMap σ f ≫ coreFiberTransportMap σ g := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  letI : (packageProjection U).IsStronglyCocartesian σ (coreFiberLift σ P) :=
    coreFiberLift_isStronglyCocartesian σ P
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) σ (coreFiberLift σ P) (𝟙 Y)
  change coreFiberLift σ P ≫ (coreFiberTransportMap σ (f ≫ g)).1 =
    coreFiberLift σ P ≫
      ((coreFiberTransportMap σ f).1 ≫ (coreFiberTransportMap σ g).1)
  calc
    _ = (f ≫ g).1 ≫ coreFiberLift σ R :=
      coreFiberTransportMap_fac σ (f ≫ g)
    _ = f.1 ≫ (g.1 ≫ coreFiberLift σ R) := Category.assoc _ _ _
    _ = f.1 ≫ (coreFiberLift σ Q ≫ (coreFiberTransportMap σ g).1) :=
      congrArg (fun h => f.1 ≫ h) (coreFiberTransportMap_fac σ g).symm
    _ = (f.1 ≫ coreFiberLift σ Q) ≫ (coreFiberTransportMap σ g).1 :=
      (Category.assoc _ _ _).symm
    _ = (coreFiberLift σ P ≫ (coreFiberTransportMap σ f).1) ≫
        (coreFiberTransportMap σ g).1 :=
      congrArg (fun h => h ≫ (coreFiberTransportMap σ g).1)
        (coreFiberTransportMap_fac σ f).symm
    _ = _ := Category.assoc _ _ _

/-- The core-fiber transport functor over an `ExtInstHom`. -/
noncomputable def coreFiberTransportFunctor {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y) :
    CoreFiber X ⥤ CoreFiber Y where
  obj := coreFiberTransportObj σ
  map := coreFiberTransportMap σ
  map_id := coreFiberTransportMap_id σ
  map_comp := coreFiberTransportMap_comp σ

/-- The iterated core lift for two composable pointed arrows. -/
noncomputable def coreFiberIteratedLift {U : AtomCarrier.{u}}
    {X Y Z : ExtractionInstance U} (σ : X ⟶ Y) (τ : Y ⟶ Z)
    (P : CoreFiber X) :
    P.1 ⟶ ((coreFiberTransportFunctor τ).obj
      ((coreFiberTransportFunctor σ).obj P)).1 :=
  coreFiberLift σ P ≫
    coreFiberLift τ ((coreFiberTransportFunctor σ).obj P)

/-- The iterated core lift is strong over the composite arrow. -/
theorem coreFiberIteratedLift_isStronglyCocartesian {U : AtomCarrier.{u}}
    {X Y Z : ExtractionInstance U} (σ : X ⟶ Y) (τ : Y ⟶ Z)
    (P : CoreFiber X) :
    (packageProjection U).IsStronglyCocartesian
      (σ ≫ τ) (coreFiberIteratedLift σ τ P) := by
  letI : (packageProjection U).IsStronglyCocartesian σ (coreFiberLift σ P) :=
    coreFiberLift_isStronglyCocartesian σ P
  letI : (packageProjection U).IsStronglyCocartesian τ
      (coreFiberLift τ ((coreFiberTransportFunctor σ).obj P)) :=
    coreFiberLift_isStronglyCocartesian τ
      ((coreFiberTransportFunctor σ).obj P)
  exact CategoryTheory.Functor.IsStronglyCocartesian.comp (packageProjection U)

/-- The core compositor component generated by lift uniqueness. -/
noncomputable def coreFiberCompositorApp {U : AtomCarrier.{u}}
    {X Y Z : ExtractionInstance U} (σ : X ⟶ Y) (τ : Y ⟶ Z)
    (P : CoreFiber X) :
    (coreFiberTransportFunctor (σ ≫ τ)).obj P ≅
      (coreFiberTransportFunctor τ).obj
        ((coreFiberTransportFunctor σ).obj P) := by
  letI : (packageProjection U).IsStronglyCocartesian (σ ≫ τ)
      (coreFiberLift (σ ≫ τ) P) :=
    coreFiberLift_isStronglyCocartesian (σ ≫ τ) P
  letI : (packageProjection U).IsStronglyCocartesian (σ ≫ τ)
      (coreFiberIteratedLift σ τ P) :=
    coreFiberIteratedLift_isStronglyCocartesian σ τ P
  exact strongLiftComparisonIso (packageProjection U) (σ ≫ τ)
    (coreFiberLift (σ ≫ τ) P) (coreFiberIteratedLift σ τ P)

/-- Factorization equation of the core compositor. -/
theorem coreFiberCompositorApp_hom_fac {U : AtomCarrier.{u}}
    {X Y Z : ExtractionInstance U} (σ : X ⟶ Y) (τ : Y ⟶ Z)
    (P : CoreFiber X) :
    coreFiberLift (σ ≫ τ) P ≫ (coreFiberCompositorApp σ τ P).hom.1 =
      coreFiberIteratedLift σ τ P := by
  letI : (packageProjection U).IsStronglyCocartesian (σ ≫ τ)
      (coreFiberLift (σ ≫ τ) P) :=
    coreFiberLift_isStronglyCocartesian (σ ≫ τ) P
  letI : (packageProjection U).IsStronglyCocartesian (σ ≫ τ)
      (coreFiberIteratedLift σ τ P) :=
    coreFiberIteratedLift_isStronglyCocartesian σ τ P
  exact strongLiftComparisonHom_fac (packageProjection U) (σ ≫ τ)
    (coreFiberLift (σ ≫ τ) P) (coreFiberIteratedLift σ τ P)

/-- The iterated core lift transports a vertical map to its authored composite. -/
theorem coreFiberIteratedMap_fac {U : AtomCarrier.{u}}
    {X Y Z : ExtractionInstance U} (σ : X ⟶ Y) (τ : Y ⟶ Z)
    {P Q : CoreFiber X} (f : P ⟶ Q) :
    coreFiberIteratedLift σ τ P ≫
        ((coreFiberTransportFunctor σ ⋙ coreFiberTransportFunctor τ).map f).1 =
      f.1 ≫ coreFiberIteratedLift σ τ Q := by
  change (coreFiberLift σ P ≫
      coreFiberLift τ ((coreFiberTransportFunctor σ).obj P)) ≫
        (coreFiberTransportMap τ (coreFiberTransportMap σ f)).1 =
    f.1 ≫ (coreFiberLift σ Q ≫
      coreFiberLift τ ((coreFiberTransportFunctor σ).obj Q))
  calc
    _ = coreFiberLift σ P ≫
        (coreFiberLift τ ((coreFiberTransportFunctor σ).obj P) ≫
          (coreFiberTransportMap τ (coreFiberTransportMap σ f)).1) :=
      Category.assoc _ _ _
    _ = coreFiberLift σ P ≫
        ((coreFiberTransportMap σ f).1 ≫
          coreFiberLift τ ((coreFiberTransportFunctor σ).obj Q)) := by
      rw [show coreFiberLift τ ((coreFiberTransportFunctor σ).obj P) ≫
          (coreFiberTransportMap τ (coreFiberTransportMap σ f)).1 =
        (coreFiberTransportMap σ f).1 ≫
          coreFiberLift τ ((coreFiberTransportFunctor σ).obj Q) by
        simpa only [coreFiberTransportFunctor] using
          coreFiberTransportMap_fac τ (coreFiberTransportMap σ f)]
    _ = (coreFiberLift σ P ≫ (coreFiberTransportMap σ f).1) ≫
        coreFiberLift τ ((coreFiberTransportFunctor σ).obj Q) :=
      (Category.assoc _ _ _).symm
    _ = (f.1 ≫ coreFiberLift σ Q) ≫
        coreFiberLift τ ((coreFiberTransportFunctor σ).obj Q) := by
      rw [coreFiberTransportMap_fac]
    _ = _ := Category.assoc _ _ _

/-- The core compositor is natural on all vertical morphisms. -/
theorem coreFiberCompositor_naturality {U : AtomCarrier.{u}}
    {X Y Z : ExtractionInstance U} (σ : X ⟶ Y) (τ : Y ⟶ Z)
    {P Q : CoreFiber X} (f : P ⟶ Q) :
    (coreFiberTransportFunctor (σ ≫ τ)).map f ≫
        (coreFiberCompositorApp σ τ Q).hom =
      (coreFiberCompositorApp σ τ P).hom ≫
        (coreFiberTransportFunctor σ ⋙ coreFiberTransportFunctor τ).map f := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  letI : (packageProjection U).IsStronglyCocartesian (σ ≫ τ)
      (coreFiberLift (σ ≫ τ) P) :=
    coreFiberLift_isStronglyCocartesian (σ ≫ τ) P
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) (σ ≫ τ) (coreFiberLift (σ ≫ τ) P) (𝟙 Z)
  change coreFiberLift (σ ≫ τ) P ≫
      ((coreFiberTransportMap (σ ≫ τ) f).1 ≫
        (coreFiberCompositorApp σ τ Q).hom.1) =
    coreFiberLift (σ ≫ τ) P ≫
      ((coreFiberCompositorApp σ τ P).hom.1 ≫
        (coreFiberTransportMap τ (coreFiberTransportMap σ f)).1)
  calc
    _ = (coreFiberLift (σ ≫ τ) P ≫
        (coreFiberTransportMap (σ ≫ τ) f).1) ≫
          (coreFiberCompositorApp σ τ Q).hom.1 :=
      (Category.assoc _ _ _).symm
    _ = (f.1 ≫ coreFiberLift (σ ≫ τ) Q) ≫
          (coreFiberCompositorApp σ τ Q).hom.1 := by
      rw [coreFiberTransportMap_fac]
    _ = f.1 ≫ (coreFiberLift (σ ≫ τ) Q ≫
          (coreFiberCompositorApp σ τ Q).hom.1) := Category.assoc _ _ _
    _ = f.1 ≫ coreFiberIteratedLift σ τ Q := by
      rw [coreFiberCompositorApp_hom_fac]
    _ = coreFiberIteratedLift σ τ P ≫
        (coreFiberTransportMap τ (coreFiberTransportMap σ f)).1 :=
      (coreFiberIteratedMap_fac σ τ f).symm
    _ = (coreFiberLift (σ ≫ τ) P ≫
        (coreFiberCompositorApp σ τ P).hom.1) ≫
          (coreFiberTransportMap τ (coreFiberTransportMap σ f)).1 := by
      rw [coreFiberCompositorApp_hom_fac]
    _ = _ := Category.assoc _ _ _

/-- The natural compositor of core-fiber transport. -/
noncomputable def coreFiberCompositor {U : AtomCarrier.{u}}
    {X Y Z : ExtractionInstance U} (σ : X ⟶ Y) (τ : Y ⟶ Z) :
    coreFiberTransportFunctor (σ ≫ τ) ≅
      coreFiberTransportFunctor σ ⋙ coreFiberTransportFunctor τ :=
  NatIso.ofComponents (coreFiberCompositorApp σ τ)
    (fun f => coreFiberCompositor_naturality σ τ f)

/-- The identity core lift. -/
noncomputable def coreFiberIdentityLift {U : AtomCarrier.{u}}
    (X : ExtractionInstance U) (P : CoreFiber X) : P.1 ⟶ P.1 :=
  𝟙 P.1

/-- The identity core lift is strongly cocartesian. -/
theorem coreFiberIdentityLift_isStronglyCocartesian {U : AtomCarrier.{u}}
    (X : ExtractionInstance U) (P : CoreFiber X) :
    (packageProjection U).IsStronglyCocartesian
      (𝟙 X) (coreFiberIdentityLift X P) := by
  letI : (packageProjection U).IsHomLift
      (𝟙 X) (coreFiberIdentityLift X P) := CategoryTheory.IsHomLift.id P.2
  letI : IsIso (coreFiberIdentityLift X P) := by
    change IsIso (𝟙 P.1)
    infer_instance
  exact CategoryTheory.Functor.IsStronglyCocartesian.of_isIso
    (packageProjection U) (𝟙 X) (coreFiberIdentityLift X P)

/-- The core unitor component generated by lift uniqueness. -/
noncomputable def coreFiberUnitorApp {U : AtomCarrier.{u}}
    (X : ExtractionInstance U) (P : CoreFiber X) :
    (coreFiberTransportFunctor (𝟙 X)).obj P ≅ P := by
  letI : (packageProjection U).IsStronglyCocartesian (𝟙 X)
      (coreFiberLift (𝟙 X) P) := coreFiberLift_isStronglyCocartesian (𝟙 X) P
  letI : (packageProjection U).IsStronglyCocartesian (𝟙 X)
      (coreFiberIdentityLift X P) :=
    coreFiberIdentityLift_isStronglyCocartesian X P
  exact strongLiftComparisonIso (packageProjection U) (𝟙 X)
    (coreFiberLift (𝟙 X) P) (coreFiberIdentityLift X P)

/-- Factorization equation of the core unitor. -/
theorem coreFiberUnitorApp_hom_fac {U : AtomCarrier.{u}}
    (X : ExtractionInstance U) (P : CoreFiber X) :
    coreFiberLift (𝟙 X) P ≫ (coreFiberUnitorApp X P).hom.1 = 𝟙 P.1 := by
  letI : (packageProjection U).IsStronglyCocartesian (𝟙 X)
      (coreFiberLift (𝟙 X) P) := coreFiberLift_isStronglyCocartesian (𝟙 X) P
  letI : (packageProjection U).IsStronglyCocartesian (𝟙 X)
      (coreFiberIdentityLift X P) :=
    coreFiberIdentityLift_isStronglyCocartesian X P
  exact strongLiftComparisonHom_fac (packageProjection U) (𝟙 X)
    (coreFiberLift (𝟙 X) P) (coreFiberIdentityLift X P)

/-- The core unitor is natural on every vertical morphism. -/
theorem coreFiberUnitor_naturality {U : AtomCarrier.{u}}
    (X : ExtractionInstance U) {P Q : CoreFiber X} (f : P ⟶ Q) :
    (coreFiberTransportFunctor (𝟙 X)).map f ≫
        (coreFiberUnitorApp X Q).hom =
      (coreFiberUnitorApp X P).hom ≫ f := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  letI : (packageProjection U).IsStronglyCocartesian (𝟙 X)
      (coreFiberLift (𝟙 X) P) := coreFiberLift_isStronglyCocartesian (𝟙 X) P
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) (𝟙 X) (coreFiberLift (𝟙 X) P) (𝟙 X)
  change coreFiberLift (𝟙 X) P ≫
      ((coreFiberTransportMap (𝟙 X) f).1 ≫
        (coreFiberUnitorApp X Q).hom.1) =
    coreFiberLift (𝟙 X) P ≫ ((coreFiberUnitorApp X P).hom.1 ≫ f.1)
  calc
    _ = (coreFiberLift (𝟙 X) P ≫
        (coreFiberTransportMap (𝟙 X) f).1) ≫
          (coreFiberUnitorApp X Q).hom.1 :=
      (Category.assoc _ _ _).symm
    _ = (f.1 ≫ coreFiberLift (𝟙 X) Q) ≫
          (coreFiberUnitorApp X Q).hom.1 := by
      rw [coreFiberTransportMap_fac]
    _ = f.1 ≫ (coreFiberLift (𝟙 X) Q ≫
          (coreFiberUnitorApp X Q).hom.1) := Category.assoc _ _ _
    _ = f.1 := by rw [coreFiberUnitorApp_hom_fac, Category.comp_id]
    _ = (coreFiberLift (𝟙 X) P ≫
          (coreFiberUnitorApp X P).hom.1) ≫ f.1 := by
      rw [coreFiberUnitorApp_hom_fac, Category.id_comp]
    _ = _ := Category.assoc _ _ _

/-- The natural unitor of core-fiber transport. -/
noncomputable def coreFiberUnitor {U : AtomCarrier.{u}}
    (X : ExtractionInstance U) :
    coreFiberTransportFunctor (𝟙 X) ≅ 𝟭 (CoreFiber X) :=
  NatIso.ofComponents (coreFiberUnitorApp X)
    (fun f => coreFiberUnitor_naturality X f)

/-- Transport-object cast induced by equality of two pointed base arrows. -/
noncomputable def coreFiberTransportEqCast {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} {σ τ : X ⟶ Y} (h : σ = τ)
    (G : CoreFiber X) :
    (coreFiberTransportFunctor σ).obj G ⟶
      (coreFiberTransportFunctor τ).obj G :=
  eqToHom (congrArg (fun k => (coreFiberTransportFunctor k).obj G) h)

/-- Equality transport of the base arrow carries its canonical lift to the other lift. -/
theorem coreFiberLift_eqCast_fac {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} {σ τ : X ⟶ Y} (h : σ = τ)
    (G : CoreFiber X) :
    coreFiberLift σ G ≫ (coreFiberTransportEqCast h G).1 =
      coreFiberLift τ G := by
  cases h
  change coreFiberLift σ G ≫ 𝟙 _ = coreFiberLift σ G
  exact Category.comp_id _

/-- The fully iterated right-associated three-arrow canonical lift. -/
noncomputable def coreFiberTripleIteratedLift {U : AtomCarrier.{u}}
    {W X Y Z : ExtractionInstance U}
    (σ : W ⟶ X) (τ : X ⟶ Y) (υ : Y ⟶ Z)
    (G : CoreFiber W) :
    G.1 ⟶ ((coreFiberTransportFunctor υ).obj
      ((coreFiberTransportFunctor τ).obj
        ((coreFiberTransportFunctor σ).obj G))).1 :=
  coreFiberLift σ G ≫
    coreFiberIteratedLift τ υ ((coreFiberTransportFunctor σ).obj G)

/-- The object cast from left- to right-associated base composition. -/
noncomputable def coreFiberAssociatorCast {U : AtomCarrier.{u}}
    {W X Y Z : ExtractionInstance U}
    (σ : W ⟶ X) (τ : X ⟶ Y) (υ : Y ⟶ Z)
    (G : CoreFiber W) :
    (coreFiberTransportFunctor ((σ ≫ τ) ≫ υ)).obj G ⟶
      (coreFiberTransportFunctor (σ ≫ (τ ≫ υ))).obj G :=
  coreFiberTransportEqCast (Category.assoc σ τ υ) G

/-- The left-associated compositor route in the three-arrow pentagon. -/
noncomputable def coreFiberPentagonLeftRoute {U : AtomCarrier.{u}}
    {W X Y Z : ExtractionInstance U}
    (σ : W ⟶ X) (τ : X ⟶ Y) (υ : Y ⟶ Z)
    (G : CoreFiber W) :
    (coreFiberTransportFunctor ((σ ≫ τ) ≫ υ)).obj G ⟶
      (coreFiberTransportFunctor υ).obj
        ((coreFiberTransportFunctor τ).obj
          ((coreFiberTransportFunctor σ).obj G)) :=
  (coreFiberCompositorApp (σ ≫ τ) υ G).hom ≫
    (coreFiberTransportFunctor υ).map (coreFiberCompositorApp σ τ G).hom

/-- The right-associated compositor route in the three-arrow pentagon. -/
noncomputable def coreFiberPentagonRightRoute {U : AtomCarrier.{u}}
    {W X Y Z : ExtractionInstance U}
    (σ : W ⟶ X) (τ : X ⟶ Y) (υ : Y ⟶ Z)
    (G : CoreFiber W) :
    (coreFiberTransportFunctor ((σ ≫ τ) ≫ υ)).obj G ⟶
      (coreFiberTransportFunctor υ).obj
        ((coreFiberTransportFunctor τ).obj
          ((coreFiberTransportFunctor σ).obj G)) :=
  coreFiberAssociatorCast σ τ υ G ≫
    ((coreFiberCompositorApp σ (τ ≫ υ) G).hom ≫
      (coreFiberCompositorApp τ υ
        ((coreFiberTransportFunctor σ).obj G)).hom)

/-- The left compositor route factors the direct lift as full iteration. -/
theorem coreFiberPentagonLeftRoute_fac {U : AtomCarrier.{u}}
    {W X Y Z : ExtractionInstance U}
    (σ : W ⟶ X) (τ : X ⟶ Y) (υ : Y ⟶ Z)
    (G : CoreFiber W) :
    coreFiberLift ((σ ≫ τ) ≫ υ) G ≫
        (coreFiberPentagonLeftRoute σ τ υ G).1 =
      coreFiberTripleIteratedLift σ τ υ G := by
  change coreFiberLift ((σ ≫ τ) ≫ υ) G ≫
      ((coreFiberCompositorApp (σ ≫ τ) υ G).hom.1 ≫
        (coreFiberTransportMap υ
          (coreFiberCompositorApp σ τ G).hom).1) =
    coreFiberLift σ G ≫
      coreFiberIteratedLift τ υ ((coreFiberTransportFunctor σ).obj G)
  calc
    _ = (coreFiberLift ((σ ≫ τ) ≫ υ) G ≫
        (coreFiberCompositorApp (σ ≫ τ) υ G).hom.1) ≫
          (coreFiberTransportMap υ
            (coreFiberCompositorApp σ τ G).hom).1 :=
      (Category.assoc _ _ _).symm
    _ = coreFiberIteratedLift (σ ≫ τ) υ G ≫
          (coreFiberTransportMap υ
            (coreFiberCompositorApp σ τ G).hom).1 := by
      rw [coreFiberCompositorApp_hom_fac]
    _ = (coreFiberLift (σ ≫ τ) G ≫
          coreFiberLift υ ((coreFiberTransportFunctor (σ ≫ τ)).obj G)) ≫
          (coreFiberTransportMap υ
            (coreFiberCompositorApp σ τ G).hom).1 := rfl
    _ = coreFiberLift (σ ≫ τ) G ≫
        (coreFiberLift υ ((coreFiberTransportFunctor (σ ≫ τ)).obj G) ≫
          (coreFiberTransportMap υ
            (coreFiberCompositorApp σ τ G).hom).1) :=
      Category.assoc _ _ _
    _ = coreFiberLift (σ ≫ τ) G ≫
        ((coreFiberCompositorApp σ τ G).hom.1 ≫
          coreFiberLift υ
            ((coreFiberTransportFunctor τ).obj
              ((coreFiberTransportFunctor σ).obj G))) := by
      rw [show coreFiberLift υ ((coreFiberTransportFunctor (σ ≫ τ)).obj G) ≫
          (coreFiberTransportMap υ
            (coreFiberCompositorApp σ τ G).hom).1 =
        (coreFiberCompositorApp σ τ G).hom.1 ≫
          coreFiberLift υ
            ((coreFiberTransportFunctor τ).obj
              ((coreFiberTransportFunctor σ).obj G)) by
        simpa only [coreFiberTransportFunctor] using
          coreFiberTransportMap_fac υ
            (coreFiberCompositorApp σ τ G).hom]
    _ = (coreFiberLift (σ ≫ τ) G ≫
          (coreFiberCompositorApp σ τ G).hom.1) ≫
        coreFiberLift υ
          ((coreFiberTransportFunctor τ).obj
            ((coreFiberTransportFunctor σ).obj G)) :=
      (Category.assoc _ _ _).symm
    _ = coreFiberIteratedLift σ τ G ≫
        coreFiberLift υ
          ((coreFiberTransportFunctor τ).obj
            ((coreFiberTransportFunctor σ).obj G)) := by
      rw [coreFiberCompositorApp_hom_fac]
    _ = _ := by
      simp only [coreFiberIteratedLift, Category.assoc]

/-- The right compositor route factors the direct lift as full iteration. -/
theorem coreFiberPentagonRightRoute_fac {U : AtomCarrier.{u}}
    {W X Y Z : ExtractionInstance U}
    (σ : W ⟶ X) (τ : X ⟶ Y) (υ : Y ⟶ Z)
    (G : CoreFiber W) :
    coreFiberLift ((σ ≫ τ) ≫ υ) G ≫
        (coreFiberPentagonRightRoute σ τ υ G).1 =
      coreFiberTripleIteratedLift σ τ υ G := by
  change coreFiberLift ((σ ≫ τ) ≫ υ) G ≫
      ((coreFiberAssociatorCast σ τ υ G).1 ≫
        ((coreFiberCompositorApp σ (τ ≫ υ) G).hom.1 ≫
          (coreFiberCompositorApp τ υ
            ((coreFiberTransportFunctor σ).obj G)).hom.1)) =
    coreFiberLift σ G ≫
      coreFiberIteratedLift τ υ ((coreFiberTransportFunctor σ).obj G)
  calc
    _ = (coreFiberLift ((σ ≫ τ) ≫ υ) G ≫
        (coreFiberAssociatorCast σ τ υ G).1) ≫
          ((coreFiberCompositorApp σ (τ ≫ υ) G).hom.1 ≫
            (coreFiberCompositorApp τ υ
              ((coreFiberTransportFunctor σ).obj G)).hom.1) :=
      (Category.assoc _ _ _).symm
    _ = coreFiberLift (σ ≫ (τ ≫ υ)) G ≫
          ((coreFiberCompositorApp σ (τ ≫ υ) G).hom.1 ≫
            (coreFiberCompositorApp τ υ
              ((coreFiberTransportFunctor σ).obj G)).hom.1) := by
      rw [coreFiberAssociatorCast, coreFiberLift_eqCast_fac]
    _ = (coreFiberLift (σ ≫ (τ ≫ υ)) G ≫
          (coreFiberCompositorApp σ (τ ≫ υ) G).hom.1) ≫
        (coreFiberCompositorApp τ υ
          ((coreFiberTransportFunctor σ).obj G)).hom.1 :=
      (Category.assoc _ _ _).symm
    _ = coreFiberIteratedLift σ (τ ≫ υ) G ≫
        (coreFiberCompositorApp τ υ
          ((coreFiberTransportFunctor σ).obj G)).hom.1 := by
      rw [coreFiberCompositorApp_hom_fac]
    _ = (coreFiberLift σ G ≫
          coreFiberLift (τ ≫ υ) ((coreFiberTransportFunctor σ).obj G)) ≫
        (coreFiberCompositorApp τ υ
          ((coreFiberTransportFunctor σ).obj G)).hom.1 := rfl
    _ = coreFiberLift σ G ≫
        (coreFiberLift (τ ≫ υ) ((coreFiberTransportFunctor σ).obj G) ≫
          (coreFiberCompositorApp τ υ
            ((coreFiberTransportFunctor σ).obj G)).hom.1) :=
      Category.assoc _ _ _
    _ = _ := by rw [coreFiberCompositorApp_hom_fac]

/-- Three-arrow associativity: the two actual compositor routes coincide. -/
theorem coreFiberCompositor_assoc {U : AtomCarrier.{u}}
    {W X Y Z : ExtractionInstance U}
    (σ : W ⟶ X) (τ : X ⟶ Y) (υ : Y ⟶ Z)
    (G : CoreFiber W) :
    coreFiberPentagonLeftRoute σ τ υ G =
      coreFiberPentagonRightRoute σ τ υ G := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  letI : (packageProjection U).IsStronglyCocartesian
      ((σ ≫ τ) ≫ υ) (coreFiberLift ((σ ≫ τ) ≫ υ) G) :=
    coreFiberLift_isStronglyCocartesian ((σ ≫ τ) ≫ υ) G
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) ((σ ≫ τ) ≫ υ)
    (coreFiberLift ((σ ≫ τ) ≫ υ) G) (𝟙 Z)
  change coreFiberLift ((σ ≫ τ) ≫ υ) G ≫
      (coreFiberPentagonLeftRoute σ τ υ G).1 =
    coreFiberLift ((σ ≫ τ) ≫ υ) G ≫
      (coreFiberPentagonRightRoute σ τ υ G).1
  rw [coreFiberPentagonLeftRoute_fac, coreFiberPentagonRightRoute_fac]

/-- Equality cast for the right unit equation. -/
noncomputable def coreFiberRightUnitCast {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    (G : CoreFiber X) :
    (coreFiberTransportFunctor (σ ≫ 𝟙 Y)).obj G ⟶
      (coreFiberTransportFunctor σ).obj G :=
  coreFiberTransportEqCast (Category.comp_id σ) G

/-- Compositor followed by the target unitor, the right unit route. -/
noncomputable def coreFiberRightUnitRoute {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    (G : CoreFiber X) :
    (coreFiberTransportFunctor (σ ≫ 𝟙 Y)).obj G ⟶
      (coreFiberTransportFunctor σ).obj G :=
  (coreFiberCompositorApp σ (𝟙 Y) G).hom ≫
    (coreFiberUnitorApp Y ((coreFiberTransportFunctor σ).obj G)).hom

/-- The right unit route factors to the original canonical lift. -/
theorem coreFiberRightUnitRoute_fac {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    (G : CoreFiber X) :
    coreFiberLift (σ ≫ 𝟙 Y) G ≫
        (coreFiberRightUnitRoute σ G).1 = coreFiberLift σ G := by
  change coreFiberLift (σ ≫ 𝟙 Y) G ≫
      ((coreFiberCompositorApp σ (𝟙 Y) G).hom.1 ≫
        (coreFiberUnitorApp Y
          ((coreFiberTransportFunctor σ).obj G)).hom.1) =
    coreFiberLift σ G
  calc
    _ = (coreFiberLift (σ ≫ 𝟙 Y) G ≫
        (coreFiberCompositorApp σ (𝟙 Y) G).hom.1) ≫
          (coreFiberUnitorApp Y
            ((coreFiberTransportFunctor σ).obj G)).hom.1 :=
      (Category.assoc _ _ _).symm
    _ = coreFiberIteratedLift σ (𝟙 Y) G ≫
          (coreFiberUnitorApp Y
            ((coreFiberTransportFunctor σ).obj G)).hom.1 := by
      rw [coreFiberCompositorApp_hom_fac]
    _ = (coreFiberLift σ G ≫
          coreFiberLift (𝟙 Y) ((coreFiberTransportFunctor σ).obj G)) ≫
        (coreFiberUnitorApp Y
          ((coreFiberTransportFunctor σ).obj G)).hom.1 := rfl
    _ = coreFiberLift σ G ≫
        (coreFiberLift (𝟙 Y) ((coreFiberTransportFunctor σ).obj G) ≫
          (coreFiberUnitorApp Y
            ((coreFiberTransportFunctor σ).obj G)).hom.1) :=
      Category.assoc _ _ _
    _ = _ := by
      rw [coreFiberUnitorApp_hom_fac]
      exact Category.comp_id _

/-- The right unit triangle compares the actual route with the base equality cast. -/
theorem coreFiberCompositor_right_unit {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    (G : CoreFiber X) :
    coreFiberRightUnitRoute σ G = coreFiberRightUnitCast σ G := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  letI : (packageProjection U).IsStronglyCocartesian
      (σ ≫ 𝟙 Y) (coreFiberLift (σ ≫ 𝟙 Y) G) :=
    coreFiberLift_isStronglyCocartesian (σ ≫ 𝟙 Y) G
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) (σ ≫ 𝟙 Y)
    (coreFiberLift (σ ≫ 𝟙 Y) G) (𝟙 Y)
  change coreFiberLift (σ ≫ 𝟙 Y) G ≫
      (coreFiberRightUnitRoute σ G).1 =
    coreFiberLift (σ ≫ 𝟙 Y) G ≫
      (coreFiberRightUnitCast σ G).1
  rw [coreFiberRightUnitRoute_fac]
  exact (coreFiberLift_eqCast_fac (Category.comp_id σ) G).symm

/-- Equality cast for the left unit equation. -/
noncomputable def coreFiberLeftUnitCast {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    (G : CoreFiber X) :
    (coreFiberTransportFunctor (𝟙 X ≫ σ)).obj G ⟶
      (coreFiberTransportFunctor σ).obj G :=
  coreFiberTransportEqCast (Category.id_comp σ) G

/-- Source unitor transported along `σ`, the left unit route. -/
noncomputable def coreFiberLeftUnitRoute {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    (G : CoreFiber X) :
    (coreFiberTransportFunctor (𝟙 X ≫ σ)).obj G ⟶
      (coreFiberTransportFunctor σ).obj G :=
  (coreFiberCompositorApp (𝟙 X) σ G).hom ≫
    (coreFiberTransportFunctor σ).map (coreFiberUnitorApp X G).hom

/-- The left unit route factors to the original canonical lift. -/
theorem coreFiberLeftUnitRoute_fac {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    (G : CoreFiber X) :
    coreFiberLift (𝟙 X ≫ σ) G ≫
        (coreFiberLeftUnitRoute σ G).1 = coreFiberLift σ G := by
  change coreFiberLift (𝟙 X ≫ σ) G ≫
      ((coreFiberCompositorApp (𝟙 X) σ G).hom.1 ≫
        (coreFiberTransportMap σ (coreFiberUnitorApp X G).hom).1) =
    coreFiberLift σ G
  calc
    _ = (coreFiberLift (𝟙 X ≫ σ) G ≫
        (coreFiberCompositorApp (𝟙 X) σ G).hom.1) ≫
          (coreFiberTransportMap σ (coreFiberUnitorApp X G).hom).1 :=
      (Category.assoc _ _ _).symm
    _ = coreFiberIteratedLift (𝟙 X) σ G ≫
          (coreFiberTransportMap σ (coreFiberUnitorApp X G).hom).1 := by
      rw [coreFiberCompositorApp_hom_fac]
    _ = (coreFiberLift (𝟙 X) G ≫
          coreFiberLift σ ((coreFiberTransportFunctor (𝟙 X)).obj G)) ≫
        (coreFiberTransportMap σ (coreFiberUnitorApp X G).hom).1 := rfl
    _ = coreFiberLift (𝟙 X) G ≫
        (coreFiberLift σ ((coreFiberTransportFunctor (𝟙 X)).obj G) ≫
          (coreFiberTransportMap σ (coreFiberUnitorApp X G).hom).1) :=
      Category.assoc _ _ _
    _ = coreFiberLift (𝟙 X) G ≫
        ((coreFiberUnitorApp X G).hom.1 ≫ coreFiberLift σ G) := by
      rw [show coreFiberLift σ ((coreFiberTransportFunctor (𝟙 X)).obj G) ≫
          (coreFiberTransportMap σ (coreFiberUnitorApp X G).hom).1 =
        (coreFiberUnitorApp X G).hom.1 ≫ coreFiberLift σ G by
        simpa only [coreFiberTransportFunctor] using
          coreFiberTransportMap_fac σ (coreFiberUnitorApp X G).hom]
    _ = (coreFiberLift (𝟙 X) G ≫
          (coreFiberUnitorApp X G).hom.1) ≫ coreFiberLift σ G :=
      (Category.assoc _ _ _).symm
    _ = _ := by rw [coreFiberUnitorApp_hom_fac, Category.id_comp]

/-- The left unit triangle compares the actual route with the base equality cast. -/
theorem coreFiberCompositor_left_unit {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (σ : X ⟶ Y)
    (G : CoreFiber X) :
    coreFiberLeftUnitRoute σ G = coreFiberLeftUnitCast σ G := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  letI : (packageProjection U).IsStronglyCocartesian
      (𝟙 X ≫ σ) (coreFiberLift (𝟙 X ≫ σ) G) :=
    coreFiberLift_isStronglyCocartesian (𝟙 X ≫ σ) G
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) (𝟙 X ≫ σ)
    (coreFiberLift (𝟙 X ≫ σ) G) (𝟙 Y)
  change coreFiberLift (𝟙 X ≫ σ) G ≫
      (coreFiberLeftUnitRoute σ G).1 =
    coreFiberLift (𝟙 X ≫ σ) G ≫
      (coreFiberLeftUnitCast σ G).1
  rw [coreFiberLeftUnitRoute_fac]
  exact (coreFiberLift_eqCast_fac (Category.id_comp σ) G).symm

end AAT.AG.CrossStageCoherence

#assert_standard_axioms_only AAT.AG.CrossStageCoherence
