import ResearchLean.AG.CrossStageCoherence.EdgeEffectivity
import ResearchLean.AG.CrossStageCoherence.ComparisonDescentInstances
import ResearchLean.AG.CrossStageCoherence.FiniteWitnesses

/-!
# Finite acceptance instances for edge-level effectivity

The reviewed noncentral-twist presentation is edge-level and therefore
path-gauge effective.  Its canonical comparator is generated by a nonidentity
edge lift and is both nonidentity and noncentral.

For the negative side, the reviewed root-obstruction fixture contains a
repeated active edge.  It has an explicit formal comparison section, but no
edge gauge can realize that section because realizability would imply the
already refuted joint-vanishing statement.  This is an acceptance instance for
`PathGaugeEffective`; the stronger fixed witness (w4), which additionally
requires compatible-pairwise vanishing on the same fixture, remains separate.

## Implementation notes

A negative fixture without any formal comparison section was rejected: it
would not witness failure of a universal effectivity statement.  The chosen
root-obstruction fixture first constructs `witnessComparisonSection` and only
then proves that no edge gauge realizes it.  Its repeated edge also gives the
required negative `EdgeLevelPresentation` instance.  This fixture has empty
`CompatiblePairs`, so it is deliberately not presented as the stronger w4
witness.
-/

namespace AAT.AG.CrossStageCoherence

open CategoryTheory
open AtomFoundation
open GeometryTransport
open TransportCoherence
open FiniteCrossStageWitness

set_option maxHeartbeats 3000000

namespace EdgeEffectivityInstances

/-- The reviewed noncentral-twist presentation is genuinely edge-level. -/
theorem noncentralTwist_edgeLevel :
    EdgeLevelPresentation NoncentralTwistWitness.presentation := by
  intro cell
  cases cell
  constructor <;>
    simp [NoncentralTwistWitness.presentation,
      NoncentralTwistWitness.nilPath, NoncentralTwistWitness.twistPath,
      PresentedPath.length]

/-- The repeated active edge places the root-obstruction fixture outside the
edge-level class. -/
theorem witness_not_edgeLevel :
    ¬ EdgeLevelPresentation witnessPresentation := by
  intro edgeLevel
  have tooLong := (edgeLevel WitnessTwoCell.activeFirst).2
  change PresentedPath.length witnessActiveDoublePath ≤ 1 at tooLong
  norm_num [witnessActiveDoublePath, witnessNilPath,
    PresentedPath.length] at tooLong

/-- On the identity-lift root fixture, every baseline canonical cell comparator
is the identity. -/
theorem witness_upperCanonical_eq_one (cell : WitnessTwoCell) :
    upperCanonicalTwoCellComparator witnessData 1 cell = 1 := by
  let leftLift := upperReselectedPathLift witnessData.lift 1
    (witnessPresentation.twoLeft cell)
  letI : (crossStageProjection.{0, 0} FiniteModel.carrier).IsStronglyCocartesian
      leftLift.base.base leftLift :=
    (upperReselectLiftData witnessData.lift 1).pathLift_compositeStrong
      (witnessPresentation.twoLeft cell)
  apply CompositeFiberAut.ext_of_strong_fac leftLift
  calc
    leftLift.comp (CompositeFiberAut.hom
        (upperCanonicalTwoCellComparator witnessData 1 cell)) =
        upperReselectedPathLift witnessData.lift 1
          (witnessPresentation.twoRight cell) :=
      upperCanonicalTwoCellComparator_fac witnessData 1 cell
    _ = GeometryTotalHom.id package := by
      rw [upperReselectedPathLift_one]
      change witnessLiftData.pathLift
        (witnessPresentation.twoRight cell) = GeometryTotalHom.id package
      exact witnessPathLift_eq_id _
    _ = leftLift.comp
        (CompositeFiberAut.hom (1 : CompositeFiberAut package)) := by
      dsimp only [leftLift]
      rw [upperReselectedPathLift_one]
      change GeometryTotalHom.id package =
        (witnessLiftData.pathLift
          (witnessPresentation.twoLeft cell)).comp
            (CompositeFiberAut.hom (1 : CompositeFiberAut package))
      rw [witnessPathLift_eq_id]
      exact (@Category.id_comp
        (GeomReadCategory.{0, 0} FiniteModel.carrier)
        (geometryTotalCategory FiniteModel.carrier)
        package package (GeometryTotalHom.id package)).symm

/-- The formal coordinate requested by the root fixture: identity at the empty
path, the visible comparator on the repeated active path, and the inner
comparator on the strict path. -/
noncomputable def witnessNodeValue
    {source target : witnessPresentation.Vertex}
    (node : CellChainNode witnessPresentation source target) :
    CompositeFiberAut (witnessData.lift.geometry target) := by
  cases source
  cases target
  exact match node.path with
    | .nil _ => 1
    | .cons edge _ =>
        match edge with
        | .active => visibleComposite
        | .strict => innerFiberInclusion package innerSwap

/-- The root fixture has genuine formal comparison descent even though no
actual upper edge gauge realizes it. -/
noncomputable def witnessComparisonSection :
    CellComparisonSection witnessData where
  value := witnessNodeValue
  nil_normalization := by
    intro vertex
    cases vertex
    rfl
  naturality := by
    intro cell
    cases cell
    all_goals rw [witness_upperCanonical_eq_one]
    all_goals
      simp [witnessNodeValue, CellChainNode.right, CellChainNode.left,
        witnessPresentation, witnessTwoPresentation, witnessNilPath,
        witnessActiveDoublePath, witnessStrictPath, witnessData]

/-- The formal root comparison section is concretely inhabited. -/
theorem witnessComparisonSection_nonempty :
    Nonempty (CellComparisonSection witnessData) :=
  ⟨witnessComparisonSection⟩

/-- No edge-realizable comparison section exists on the root fixture. -/
theorem witness_no_edgeRealizableSection :
    ¬ Nonempty (EdgeRealizableCellComparisonSection witnessData) := by
  intro realizable
  exact witness_not_joint
    ((jointVanishes_iff_nonempty_edgeRealizableSection witnessData).2
      realizable)

/-- In particular, its explicit formal section cannot be effectivized by one
upper edge gauge. -/
theorem witness_not_pathGaugeEffective :
    ¬ PathGaugeEffective witnessData := by
  intro effective
  obtain ⟨gauge, realizes⟩ := effective witnessComparisonSection
  apply witness_no_edgeRealizableSection
  exact ⟨{ comparison := witnessComparisonSection
           gauge := gauge
           realizes := realizes }⟩

/-- The edge-level class has direct positive and negative finite instances. -/
theorem edgeLevelPresentation_instances :
    EdgeLevelPresentation NoncentralTwistWitness.presentation ∧
      ¬ EdgeLevelPresentation witnessPresentation :=
  ⟨noncentralTwist_edgeLevel, witness_not_edgeLevel⟩

/-- Path-gauge effectivity has direct positive and negative finite instances;
the positive datum has a nonidentity, noncentral canonical comparator. -/
theorem pathGaugeEffective_instances :
    PathGaugeEffective NoncentralTwistWitness.data ∧
      ¬ PathGaugeEffective witnessData :=
  ⟨edgeLevelPresentation_pathGaugeEffective NoncentralTwistWitness.data
      noncentralTwist_edgeLevel,
    witness_not_pathGaugeEffective⟩

end EdgeEffectivityInstances

end AAT.AG.CrossStageCoherence

#assert_standard_axioms_only AAT.AG.CrossStageCoherence
