import ResearchLean.AG.CrossStageCoherence.Unification
import ResearchLean.AG.TransportCoherence.FiniteWitnesses
import ResearchLean.AG.GeometryTransport.FiniteWitnesses

/-!
# Finite cross-stage witnesses

The fixture is built over `FiniteModel.carrier`.  Its core has four symmetric
signature axes.  The selected geometry distinguishes the pair `{0, 1}`.  The
block swap `(0 1)(2 3)` lifts, while either of its four-cycle square roots must
leave that selected pair and therefore cannot lift.  Independently, a diagonal
`Int × Int` coefficient system is invariant under coefficient swap and supplies
a nonidentity element of the strict inner group.
-/

namespace AAT.AG.CrossStageCoherence

open CategoryTheory
open AtomFoundation
open GeometryTransport
open TransportCoherence

namespace FiniteCrossStageWitness

/-! ## A nondegenerate geometry package with a selected axis pair -/

/-- Four symmetric signature axes, with coordinates recording their axes. -/
def signature : ArchitectureSignature FiniteModel.carrier where
  Axis := Fin 4
  Coordinate _ := Fin 4
  selected _ := True
  coordinate _ axis := axis

/-- The finite reading with the four-axis signature used by the cross-stage witness. -/
noncomputable def reading : CoreReading FiniteModel.carrier :=
  { FiniteModel.coreReading with signatureReading := signature }

/-- The finite four-axis core generated by the existing finite AAT axioms. -/
noncomputable def core : AATCorePackage FiniteModel.carrier :=
  AATCorePackage.generate FiniteModel.axiomSystem reading

/-- Coverage selects exactly axes `0` and `1`. -/
def requirements : Site.CoverageRequirements core.object
    core.equationSystem core.algebra.signatureReading where
  requiredSupport := fun _ => False
  requiredEquationCoordinate := fun _ => False
  selectedViolationWitness := fun _ => False
  requiredAxis := fun axis => axis = (0 : Fin 4) ∨ axis = (1 : Fin 4)
  supportVisibleOn := fun _ _ => True
  equationCoordinateVisibleOn := fun _ _ => True
  violationWitnessVisibleOn := fun _ _ => True
  axisReadableOn := fun _ axis => axis = (0 : Fin 4) ∨ axis = (1 : Fin 4)
  boundaryVisibleOn := fun _ _ => True

/-- Selected finite geometry on the unchanged finite context preorder. -/
noncomputable def selectedGeometry : Site.SelectedGeometryReading core where
  requirements := requirements
  overlap := Site.meetOverlapPullback core.contextPreorder
    Site.productContextFiniteMeet

/-- One explicit context witnessing that the selected site is inhabited. -/
def baseContext : Site.ArchCtx core.object where
  minimal := {
    Support := PUnit
    Axis := PUnit
    Observable := PUnit
    supportReads := fun _ _ => False
    supportReads_objectFamily := fun h => False.elim h
    axisReads := fun _ => True
    observableReads := fun _ => True
  }
  Extension := PUnit
  extension := PUnit.unit

/-- Diagonal coefficient map into the symmetric pair ring. -/
def diagonalCoefficient : Int →+*
    GeometryTransport.NegativeGeometryWitness.PairCoefficient :=
  Int.castRingHom _

/-- Swapping the pair factors fixes the diagonal coefficient map. -/
theorem pairSwap_comp_diagonal :
    GeometryTransport.NegativeGeometryWitness.pairSwap.comp diagonalCoefficient =
      diagonalCoefficient := by
  ext value <;> rfl

/-- One semantic coordinate on every selected context. -/
def coordFamily (W : selectedGeometry.toAATSite.category) :
    LawAlgebra.CoordinateFamily W.ctx where
  Coord := Unit
  label := fun _ => LawAlgebra.CoordinateLabel.semantic
  LocalData := fun _ => Unit

/-- The nonzero integral relation used before diagonal coefficient extension. -/
noncomputable def relationFamily (W : selectedGeometry.toAATSite.category) :
    LawAlgebra.StructuralRelationFamily (coordFamily W) Int where
  Relation := Unit
  polynomial := fun _ => MvPolynomial.X () ^ 2 - MvPolynomial.X ()

/-- Every context restriction fixes the selected coordinate. -/
noncomputable def coordinateRestriction
    {X Y : selectedGeometry.toAATSite.category} (w : X ⟶ Y) :
    LawAlgebra.TypedCoordinateRestriction (coordFamily X) (coordFamily Y) Int
      (selectedGeometry.toAATSite.contextPreorder.morphism (leOfHom w)) where
  variableImage := fun _ => MvPolynomial.X ()

theorem coordinateRestriction_polynomialMap
    {X Y : selectedGeometry.toAATSite.category} (w : X ⟶ Y) :
    (coordinateRestriction w).polynomialMap =
      RingHom.id (LawAlgebra.FreeTypedCommAlg (coordFamily X) Int) := by
  apply MvPolynomial.ringHom_ext
  · intro value
    change (coordinateRestriction w).polynomialMap (MvPolynomial.C value) =
      MvPolynomial.C value
    exact LawAlgebra.TypedCoordinateRestriction.polynomialMap_C _ _
  · intro coordinate
    cases coordinate
    rw [LawAlgebra.TypedCoordinateRestriction.polynomialMap_X]
    rfl

/-- The relation is stable under the identity coordinate restriction. -/
noncomputable def restrictionStable
    {X Y : selectedGeometry.toAATSite.category} (w : X ⟶ Y) :
    LawAlgebra.RestrictionStableStructuralRelations
      (relationFamily X) (relationFamily Y)
      (selectedGeometry.toAATSite.contextPreorder.morphism (leOfHom w)) where
  restriction := coordinateRestriction w
  maps_JStruct := by
    intro polynomial hpolynomial
    have identity : (coordinateRestriction w).polynomialMap polynomial =
        polynomial := by
      rw [coordinateRestriction_polynomialMap]
      rfl
    rw [identity]
    exact hpolynomial

/-- Coherent integral raw system on the selected site. -/
noncomputable def integralRaw :
    LawAlgebra.RawAmbientRestrictionSystem selectedGeometry.toAATSite Int where
  coordFamily := coordFamily
  relationFamily := relationFamily
  restrictionStable := restrictionStable
  identity_polynomialMap W := coordinateRestriction_polynomialMap (𝟙 W)
  composition_polynomialMap f g := by
    change (coordinateRestriction (f ≫ g)).polynomialMap =
      ((coordinateRestriction f).polynomialMap).comp
        ((coordinateRestriction g).polynomialMap)
    rw [coordinateRestriction_polynomialMap,
      coordinateRestriction_polynomialMap,
      coordinateRestriction_polynomialMap]
    exact (RingHom.id_comp _).symm

/-- The actual finite raw system after diagonal coefficient extension. -/
noncomputable def symmetricRaw :
    LawAlgebra.RawAmbientRestrictionSystem selectedGeometry.toAATSite
      GeometryTransport.NegativeGeometryWitness.PairCoefficient :=
  integralRaw.baseChange diagonalCoefficient

/-- The raw system is fixed by the nonidentity coefficient swap. -/
theorem symmetricRaw_swap :
    symmetricRaw.baseChange
        GeometryTransport.NegativeGeometryWitness.pairSwap = symmetricRaw := by
  unfold symmetricRaw
  rw [← LawAlgebra.RawAmbientRestrictionSystem.baseChange_comp]
  rw [pairSwap_comp_diagonal]

/-- The finite geometry package used by both witness directions. -/
noncomputable def package :
    GeometryPackage.{0, 0} FiniteModel.carrier where
  core := core
  geometry := selectedGeometry
  Coefficient := GeometryTransport.NegativeGeometryWitness.PairCoefficient
  coefficientCommRing := inferInstance
  raw := symmetricRaw

/-- The fixture has an actual selected finite context. -/
theorem site_nonempty : Nonempty package.site.category :=
  ⟨⟨baseContext⟩⟩

/-- The top sieve is an actual cover in the selected generated topology. -/
theorem has_actual_cover :
    (⊤ : Sieve (⟨baseContext⟩ : package.site.category)) ∈
      package.site.topology ⟨baseContext⟩ :=
  package.site.top_mem _

/-- The pair coefficient ring is nonzero. -/
theorem coefficient_nontrivial :
    (((2 : Int), (2 : Int)) : package.Coefficient) ≠ 0 := by
  norm_num

/-- The inherited finite raw relation remains genuinely nonzero. -/
theorem raw_relation_nonzero :
    ((package.raw.relationFamily
      (⟨baseContext⟩ : package.site.category)).polynomial ()) ≠ 0 := by
  intro equality
  change MvPolynomial.map diagonalCoefficient
      (MvPolynomial.X () ^ 2 - MvPolynomial.X ()) = 0 at equality
  have evaluated := congrArg
    (MvPolynomial.eval₂Hom (RingHom.fst Int Int)
      (fun _ : Unit => (2 : Int))) equality
  norm_num [diagonalCoefficient] at evaluated

/-! ## Core-fiber permutations and the selected-pair lift test -/

/-- A four-axis permutation as a self-map of the fixed source core. -/
noncomputable def corePermutationTotal (permutation : Equiv.Perm (Fin 4)) :
    PackageTotalHom core core where
  base := ExtInstHom.id (packagePoint core)
  upper :=
    { SignedExactCoreReadingHom.refl core with
      axisMap := permutation
      coordinateEquiv := fun _ => permutation
      axis_selected_iff := fun _ => Iff.rfl
      coordinate_eq := by intro object axis; rfl }
  atomEquiv_eq := rfl

/-- Core permutation composition follows permutation composition. -/
theorem corePermutationTotal_comp (first second : Equiv.Perm (Fin 4)) :
    (corePermutationTotal first).comp (corePermutationTotal second) =
      corePermutationTotal (first.trans second) := by
  apply PackageTotalHom.ext
  · apply ExtInstHom.ext
    apply ExactDoctrineHom.ext
    · rfl
    · apply Equiv.ext
      intro atom
      rfl
  · apply SignedExactCoreReadingHom.ext
    · apply Equiv.ext
      intro atom
      rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl

/-- The reflexive permutation is the total identity. -/
theorem corePermutationTotal_refl :
    corePermutationTotal (Equiv.refl (Fin 4)) = PackageTotalHom.id core := by
  apply PackageTotalHom.ext
  · apply ExtInstHom.ext
    apply ExactDoctrineHom.ext
    · rfl
    · apply Equiv.ext
      intro atom
      rfl
  · apply SignedExactCoreReadingHom.ext
    · apply Equiv.ext
      intro atom
      rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl

/-- Core-fiber automorphism associated to a four-axis permutation. -/
noncomputable def coreFiberPermutation (permutation : Equiv.Perm (Fin 4)) :
    PackageFiberAut core := by
  let iso : Aut core :=
    { hom := corePermutationTotal permutation
      inv := corePermutationTotal permutation.symm
      hom_inv_id := by
        change (corePermutationTotal permutation).comp
          (corePermutationTotal permutation.symm) = PackageTotalHom.id core
        rw [corePermutationTotal_comp]
        rw [show permutation.trans permutation.symm = Equiv.refl (Fin 4) by
          apply Equiv.ext
          intro axis
          exact permutation.symm_apply_apply axis]
        exact corePermutationTotal_refl
      inv_hom_id := by
        change (corePermutationTotal permutation.symm).comp
          (corePermutationTotal permutation) = PackageTotalHom.id core
        rw [corePermutationTotal_comp]
        rw [show permutation.symm.trans permutation = Equiv.refl (Fin 4) by
          apply Equiv.ext
          intro axis
          exact permutation.apply_symm_apply axis]
        exact corePermutationTotal_refl }
  exact ⟨iso, rfl⟩

theorem coreFiberPermutation_mul (first second : Equiv.Perm (Fin 4)) :
    coreFiberPermutation first * coreFiberPermutation second =
      coreFiberPermutation (second.trans first) := by
  apply Subtype.ext
  apply Iso.ext
  change (corePermutationTotal second).comp (corePermutationTotal first) =
    corePermutationTotal (second.trans first)
  exact corePermutationTotal_comp second first

/-- The visible involution swapping within each selected-status block. -/
def blockPermutation : Equiv.Perm (Fin 4) :=
  (Equiv.swap (0 : Fin 4) 1).trans (Equiv.swap (2 : Fin 4) 3)

/-- One four-cycle square root of `blockPermutation`. -/
def squareRootPermutation : Equiv.Perm (Fin 4) :=
  ((Equiv.swap (0 : Fin 4) 2).trans (Equiv.swap (0 : Fin 4) 1)).trans
    (Equiv.swap (0 : Fin 4) 3)

theorem squareRootPermutation_square :
    squareRootPermutation.trans squareRootPermutation = blockPermutation := by
  apply Equiv.ext
  intro axis
  fin_cases axis <;> rfl

/-- The concrete square root leaves the selected pair and cannot lift. -/
noncomputable def blockedCore : PackageFiberAut core :=
  coreFiberPermutation squareRootPermutation

/-- A nonidentity block-preserving core element that can lift. -/
noncomputable def visibleCore : PackageFiberAut core :=
  coreFiberPermutation blockPermutation

theorem blockedCore_mul_self : blockedCore * blockedCore = visibleCore := by
  rw [blockedCore, visibleCore, coreFiberPermutation_mul,
    squareRootPermutation_square]

/-! ## Liftable and blocked core automorphisms -/

/-- Raw reindexing cannot see a pure signature-axis permutation. -/
theorem rawReindex_corePermutation
    (permutation : Equiv.Perm (Fin 4))
    (raw : LawAlgebra.RawAmbientRestrictionSystem package.site
      package.Coefficient) :
    rawReindex (G := package) (H := package)
      (corePermutationTotal permutation) raw = raw := by
  apply LawAlgebra.RawAmbientRestrictionSystem.ext
  · rfl
  · rfl
  · rfl

/-- Local transport equality for the dependent base index of a geometry hom. -/
theorem castBase_heq
    {f g : PackageTotalHom package.core package.core} (equality : f = g)
    (hom : GeomReadHom package package f) :
    HEq (GeomReadHom.castBase equality hom) hom := by
  cases equality
  rfl

/-- Compare geometry homs after identifying their dependent base indices. -/
theorem geometryHom_heq_of_base_eq
    {f g : PackageTotalHom package.core package.core}
    (F : GeomReadHom package package f)
    (T : GeomReadHom package package g)
    (baseEquality : f = g)
    (coefficientEquality : F.coefficientHom = T.coefficientHom)
    (supportEquality : HEq F.supportComp T.supportComp)
    (axisEquality : HEq F.axisComp T.axisComp)
    (observableEquality : HEq F.observableComp T.observableComp) :
    HEq F T := by
  cases baseEquality
  exact heq_of_eq (GeomReadHom.ext coefficientEquality supportEquality
    axisEquality observableEquality)

/-- Predicate defining the selected axis pair. -/
def SelectedAxis (axis : Fin 4) : Prop :=
  axis = (0 : Fin 4) ∨ axis = (1 : Fin 4)

/-- A core permutation preserving the selected pair preserves the geometry. -/
noncomputable def geometryPermutationHom
    (permutation : Equiv.Perm (Fin 4))
    (preservesSelected : ∀ axis, SelectedAxis axis →
      SelectedAxis (permutation axis)) :
    GeomReadHom package package (corePermutationTotal permutation) where
  coverage := {
    requiredSupport := fun _ h => False.elim h
    requiredEquationCoordinate := fun _ h => False.elim h
    selectedViolationWitness := fun _ h => False.elim h
    requiredAxis := by
      intro axis selected
      exact preservesSelected axis selected
    supportVisibleOn := fun _ _ _ => trivial
    equationCoordinateVisibleOn := fun _ _ _ => trivial
    violationWitnessVisibleOn := fun _ _ _ => trivial
    axisReadableOn := by
      intro W axis readable
      exact preservesSelected axis readable
    boundaryVisibleOn := fun _ _ _ => trivial
  }
  overlap := { overlapIso := fun _ _ _ => Iso.refl _ }
  coefficientHom := RingHom.id package.Coefficient
  raw_eq := by
    unfold rawTransport
    rw [LawAlgebra.RawAmbientRestrictionSystem.baseChange_id]
    exact (rawReindex_corePermutation permutation package.raw).symm
  supportComp _ := _root_.id
  axisComp _ := _root_.id
  observableComp _ := _root_.id
  supportReads _ _ _ h := h
  axisReads _ _ h := h
  observableReads _ _ h := h
  support_naturality _ _ := rfl
  axis_naturality _ _ := rfl
  observable_naturality _ _ := rfl

/-- The block involution preserves the selected pair. -/
theorem blockPermutation_preserves_selected :
    ∀ axis, SelectedAxis axis → SelectedAxis (blockPermutation axis) := by
  intro axis selected
  fin_cases axis <;> simp_all [SelectedAxis] <;> decide

theorem blockPermutation_square :
    blockPermutation.trans blockPermutation = Equiv.refl (Fin 4) := by
  apply Equiv.ext
  intro axis
  fin_cases axis <;> rfl

/-- Geometry self-map over the visible nonidentity core permutation. -/
noncomputable def visibleGeometryTotal : GeometryTotalHom package package where
  base := corePermutationTotal blockPermutation
  geometry := geometryPermutationHom
    blockPermutation blockPermutation_preserves_selected

/-- Applying the visible geometry permutation twice is identity. -/
theorem visibleGeometryTotal_square :
    visibleGeometryTotal.comp visibleGeometryTotal = GeometryTotalHom.id package := by
  have baseSquare :
      (visibleGeometryTotal.comp visibleGeometryTotal).base =
        (GeometryTotalHom.id package).base := by
    change (corePermutationTotal blockPermutation).comp
      (corePermutationTotal blockPermutation) =
        PackageTotalHom.id core
    rw [corePermutationTotal_comp]
    rw [blockPermutation_square]
    exact corePermutationTotal_refl
  apply GeometryTotalHom.ext
  · exact baseSquare
  · apply geometryHom_heq_of_base_eq _ _ baseSquare
    · exact RingHom.id_comp _
    · rfl
    · rfl
    · rfl

/-- The liftable geometry self-map as a categorical automorphism. -/
noncomputable def visibleGeometryIso : Aut package where
  hom := visibleGeometryTotal
  inv := visibleGeometryTotal
  hom_inv_id := visibleGeometryTotal_square
  inv_hom_id := visibleGeometryTotal_square

/-- A `C_G` element with nonidentity pushforward. -/
noncomputable def visibleComposite : CompositeFiberAut package :=
  ⟨visibleGeometryIso, rfl⟩

theorem visibleComposite_pushforward :
    compositeFiberPushforward package visibleComposite = visibleCore := by
  apply Subtype.ext
  apply Iso.ext
  rfl

theorem visibleCore_ne_one : visibleCore ≠ 1 := by
  intro equality
  have axisEquality := congrArg
    (fun automorphism : PackageFiberAut core =>
      (PackageFiberAut.hom automorphism).upper.axisMap (0 : Fin 4)) equality
  change (1 : Fin 4) = 0 at axisEquality
  exact (by decide : (1 : Fin 4) ≠ 0) axisEquality

/-- The fixture pushforward is genuinely nonconstant. -/
theorem compositeFiberPushforward_nontrivial :
    compositeFiberPushforward package visibleComposite ≠ 1 := by
  rw [visibleComposite_pushforward]
  exact visibleCore_ne_one

/-- No geometry automorphism projects to the selected-axis-breaking core swap. -/
theorem blockedCore_has_no_composite_lift :
    ∀ automorphism : CompositeFiberAut package,
      compositeFiberPushforward package automorphism ≠ blockedCore := by
  intro automorphism equality
  have baseEquality := congrArg PackageFiberAut.hom equality
  change automorphism.1.hom.base =
    corePermutationTotal squareRootPermutation at baseEquality
  have preservesSelected :=
    automorphism.1.hom.geometry.coverage.requiredAxis (0 : Fin 4) (Or.inl rfl)
  have axisEquality := congrArg
    (fun hom : PackageTotalHom core core => hom.upper.axisMap (0 : Fin 4))
    baseEquality
  change automorphism.1.hom.base.upper.axisMap (0 : Fin 4) = (0 : Fin 4) ∨
    automorphism.1.hom.base.upper.axisMap (0 : Fin 4) = (1 : Fin 4)
      at preservesSelected
  change automorphism.1.hom.base.upper.axisMap (0 : Fin 4) =
    squareRootPermutation (0 : Fin 4) at axisEquality
  rw [axisEquality] at preservesSelected
  have rootZero : squareRootPermutation (0 : Fin 4) = (2 : Fin 4) := rfl
  rw [rootZero] at preservesSelected
  rcases preservesSelected with selected | selected
  · exact (by decide : (2 : Fin 4) ≠ 0) selected
  · exact (by decide : (2 : Fin 4) ≠ 1) selected

/-! ## A nonidentity strict inner coefficient automorphism -/

/-- Coefficient swap is a geometry self-map over the identity core morphism. -/
noncomputable def coefficientSwapGeometryHom :
    GeomReadHom package package (PackageTotalHom.id core) where
  coverage := CoverageTransport.id package
  overlap := OverlapTransport.id package
  coefficientHom := GeometryTransport.NegativeGeometryWitness.pairSwap
  raw_eq := by
    unfold rawTransport
    calc
      package.raw = package.raw.baseChange
          GeometryTransport.NegativeGeometryWitness.pairSwap :=
        symmetricRaw_swap.symm
      _ = rawReindex (G := package) (H := package)
          (PackageTotalHom.id package.core)
          (package.raw.baseChange
            GeometryTransport.NegativeGeometryWitness.pairSwap) :=
        (rawReindex_id package _).symm
  supportComp _ := _root_.id
  axisComp _ := _root_.id
  observableComp _ := _root_.id
  supportReads _ _ _ := _root_.id
  axisReads _ _ := _root_.id
  observableReads _ _ := _root_.id
  support_naturality _ _ := rfl
  axis_naturality _ _ := rfl
  observable_naturality _ _ := rfl

noncomputable def coefficientSwapTotal : GeometryTotalHom package package where
  base := PackageTotalHom.id core
  geometry := coefficientSwapGeometryHom

theorem coefficientSwapTotal_square :
    coefficientSwapTotal.comp coefficientSwapTotal = GeometryTotalHom.id package := by
  have baseSquare :
      (coefficientSwapTotal.comp coefficientSwapTotal).base =
        (GeometryTotalHom.id package).base := by
    change (PackageTotalHom.id core).comp (PackageTotalHom.id core) =
      PackageTotalHom.id core
    exact Category.comp_id
      (self := AAT.AG.AtomFoundation.PackageTotalHom.packageTotalCategory
        FiniteModel.carrier)
      (PackageTotalHom.id core)
  apply GeometryTotalHom.ext
  · exact baseSquare
  · apply geometryHom_heq_of_base_eq _ _ baseSquare
    · exact GeometryTransport.NegativeGeometryWitness.pairSwap_comp
    · rfl
    · rfl
    · rfl

noncomputable def coefficientSwapIso : Aut package where
  hom := coefficientSwapTotal
  inv := coefficientSwapTotal
  hom_inv_id := coefficientSwapTotal_square
  inv_hom_id := coefficientSwapTotal_square

/-- The concrete nonidentity element of the strict subgroup `H_G`. -/
noncomputable def innerSwap : InnerFiberAut package :=
  ⟨⟨coefficientSwapIso, rfl⟩, rfl⟩

theorem innerSwap_ne_one : innerSwap ≠ 1 := by
  intro equality
  have coefficientEquality := congrArg
    (fun automorphism : InnerFiberAut package =>
      automorphism.1.1.hom.geometry.coefficientHom
        (((1 : Int), (0 : Int)) : package.Coefficient)) equality
  change (((0 : Int), (1 : Int)) : package.Coefficient) = ((1, 0) : package.Coefficient)
    at coefficientEquality
  norm_num at coefficientEquality

/-! ## One closed presentation coupling the two stages -/

/-- The repeated active loop carries the interstage obstruction; the strict loop
carries the independent inner obstruction. -/
inductive WitnessEdge : Type
  | active
  | strict
  deriving DecidableEq

instance witnessEdgeFintype : Fintype WitnessEdge where
  elems := {.active, .strict}
  complete edge := by cases edge <;> simp

/-- Two equal active faces support a genuine syzygy; the third face is strict. -/
inductive WitnessTwoCell : Type
  | activeFirst
  | activeSecond
  | strict
  deriving DecidableEq

instance witnessTwoCellFintype : Fintype WitnessTwoCell where
  elems := {.activeFirst, .activeSecond, .strict}
  complete cell := by cases cell <;> simp

/-- The unique 3-cell compares the two distinct active faces. -/
inductive WitnessThreeCell : Type
  | comparison
  deriving DecidableEq

instance witnessThreeCellFintype : Fintype WitnessThreeCell where
  elems := {.comparison}
  complete cell := by cases cell; simp

abbrev WitnessVertex := PUnit

abbrev WitnessEdgeFamily (_ _ : WitnessVertex) := WitnessEdge

def witnessNilPath : PresentedPath WitnessEdgeFamily PUnit.unit PUnit.unit :=
  .nil PUnit.unit

/-- Reusing the same active edge twice forces a square-root equation on its gauge. -/
def witnessActiveDoublePath :
    PresentedPath WitnessEdgeFamily PUnit.unit PUnit.unit :=
  @PresentedPath.cons WitnessVertex WitnessEdgeFamily PUnit.unit PUnit.unit
    PUnit.unit .active
    (@PresentedPath.cons WitnessVertex WitnessEdgeFamily PUnit.unit PUnit.unit
      PUnit.unit .active witnessNilPath)

def witnessStrictPath :
    PresentedPath WitnessEdgeFamily PUnit.unit PUnit.unit :=
  .cons .strict witnessNilPath

/-- The finite 2-skeleton of the coupled witness. -/
noncomputable def witnessTwoPresentation : FiniteTransportTwoPresentation where
  Vertex := WitnessVertex
  vertexFintype := inferInstance
  Edge := WitnessEdgeFamily
  edgeFintype := fun _ _ => witnessEdgeFintype
  TwoCell := WitnessTwoCell
  twoCellFintype := witnessTwoCellFintype
  twoSource := fun _ => PUnit.unit
  twoTarget := fun _ => PUnit.unit
  twoLeft := fun _ => witnessNilPath
  twoRight
    | .activeFirst => witnessActiveDoublePath
    | .activeSecond => witnessActiveDoublePath
    | .strict => witnessStrictPath

def witnessFace (cell : WitnessTwoCell) :
    WhiskeredFace witnessTwoPresentation PUnit.unit PUnit.unit where
  cell := cell
  incoming := witnessNilPath
  outgoing := witnessNilPath
  orientation := .forward

def witnessStep (cell : WitnessTwoCell) :
    RewriteStep witnessTwoPresentation witnessNilPath
      (witnessTwoPresentation.twoRight cell) where
  face := witnessFace cell
  before_eq := by
    simp [witnessFace, WhiskeredFace.before, WhiskeredFace.localBefore,
      witnessTwoPresentation, witnessNilPath]
  after_eq := by
    simp [witnessFace, WhiskeredFace.after, WhiskeredFace.localAfter,
      witnessTwoPresentation, PresentedPath.append, witnessNilPath]

noncomputable def witnessPasting (cell : WitnessTwoCell) :
    RewritePasting witnessTwoPresentation witnessNilPath
      (witnessTwoPresentation.twoRight cell) :=
  .cons (witnessStep cell)
    (@RewritePasting.nil witnessTwoPresentation PUnit.unit PUnit.unit
      (witnessTwoPresentation.twoRight cell))

/-- Closed fixture with two distinct nonempty fillings of the active relation. -/
noncomputable def witnessPresentation : FiniteTransportPresentation where
  toFiniteTransportTwoPresentation := witnessTwoPresentation
  ThreeCell := WitnessThreeCell
  threeCellFintype := witnessThreeCellFintype
  threeSource := fun _ => PUnit.unit
  threeTarget := fun _ => PUnit.unit
  threeStart := fun _ => witnessNilPath
  threeFinish := fun _ => witnessActiveDoublePath
  threeLeft := fun _ => witnessPasting .activeFirst
  threeRight := fun _ => witnessPasting .activeSecond

/-- Identity is a strongly cocartesian geometry lift. -/
theorem geometryIdentityStrong :
    (geometryProjection FiniteModel.carrier).IsStronglyCocartesian
      (GeometryTotalHom.id package).base (GeometryTotalHom.id package) := by
  letI : (geometryProjection FiniteModel.carrier).IsHomLift
      (𝟙 package.core) (Iso.refl package).hom :=
    CategoryTheory.IsHomLift.id rfl
  simpa using
    (CategoryTheory.Functor.IsStronglyCocartesian.of_iso
      (geometryProjection FiniteModel.carrier) (𝟙 package.core)
      (Iso.refl package))

/-- Its core identity is independently strongly cocartesian. -/
theorem coreIdentityStrong :
    (packageProjection FiniteModel.carrier).IsStronglyCocartesian
      (PackageTotalHom.id core).base (PackageTotalHom.id core) := by
  letI : (packageProjection FiniteModel.carrier).IsHomLift
      (𝟙 (packagePoint core)) (Iso.refl core).hom :=
    CategoryTheory.IsHomLift.id rfl
  simpa using
    (CategoryTheory.Functor.IsStronglyCocartesian.of_iso
      (packageProjection FiniteModel.carrier) (𝟙 (packagePoint core))
      (Iso.refl core))

/-- Both loops use the same identity lift; their qualifications remain two-layered. -/
noncomputable def witnessLiftData :
    TwoLayerLiftData witnessPresentation FiniteModel.carrier where
  geometry _ := package
  edgeLift _ := GeometryTotalHom.id package
  edgeGeometryStrong _ := geometryIdentityStrong
  edgeCoreStrong _ := coreIdentityStrong

theorem witnessPathLift_eq_id
    {i j : witnessPresentation.Vertex}
    (path : witnessPresentation.Path i j) :
    witnessLiftData.pathLift path = GeometryTotalHom.id package := by
  induction path with
  | nil => rfl
  | cons edge tail inductionHypothesis =>
      change (GeometryTotalHom.id package).comp
          (witnessLiftData.pathLift tail) = GeometryTotalHom.id package
      rw [inductionHypothesis]
      exact Category.comp_id
        (self := geometryTotalCategory FiniteModel.carrier)
        (GeometryTotalHom.id package)

/-- Active faces carry the block involution, while the strict face carries the
nonidentity coefficient swap in `H_G`. -/
noncomputable def witnessData :
    TwoLayerTransportData witnessPresentation FiniteModel.carrier where
  lift := witnessLiftData
  twoCellBase := by
    intro cell
    rw [witnessPathLift_eq_id, witnessPathLift_eq_id]
  comparator
    | .activeFirst => visibleComposite
    | .activeSecond => visibleComposite
    | .strict => innerFiberInclusion package innerSwap

/-! ## Pairwise local trivializers -/

/-- The core coordinate uses the nonliftable four-cycle square root. -/
noncomputable def witnessCoreReselection :
    EdgeReselection witnessData.coreData.lift :=
  fun _ _ edge =>
    match edge with
    | .active => blockedCore
    | .strict => 1

theorem witnessCoreReselection_coherent :
    CoherentAt witnessData.coreData witnessCoreReselection := by
  intro cell
  cases cell <;>
    simp only [witnessPresentation, witnessTwoPresentation,
      witnessNilPath, witnessActiveDoublePath, witnessStrictPath,
      reselectedPathLift, reselectLiftData, AdmissibleLiftData.pathLift,
      reselectedEdgeLift, witnessData, TwoLayerTransportData.coreData,
      TwoLayerLiftData.coreLiftData, witnessLiftData,
      witnessCoreReselection, visibleComposite_pushforward]
  · simpa only [Category.id_comp, Category.comp_id] using
      congrArg PackageFiberAut.hom blockedCore_mul_self |>.symm
  · simpa only [Category.id_comp, Category.comp_id] using
      congrArg PackageFiberAut.hom blockedCore_mul_self |>.symm
  · exact Category.comp_id
      (self := PackageTotalHom.packageTotalCategory FiniteModel.carrier)
      (PackageTotalHom.id core)

noncomputable def witnessCoreTrivializer : CoreTrivializer witnessData where
  reselection := witnessCoreReselection
  coherent := witnessCoreReselection_coherent

/-- The strict coordinate changes only the strict loop by the coefficient swap. -/
noncomputable def witnessStrictReselection :
    StrictEdgeReselection witnessData.lift :=
  fun _ _ edge =>
    match edge with
    | .active => 1
    | .strict => innerSwap

theorem witnessStrict_qualified : StrictCellQualified witnessData .strict := by
  constructor
  · have pathEquality := (witnessPathLift_eq_id
        (witnessPresentation.twoLeft WitnessTwoCell.strict)).trans
      (witnessPathLift_eq_id
        (witnessPresentation.twoRight WitnessTwoCell.strict)).symm
    exact congrArg GeometryTotalHom.base pathEquality
  · change compositeFiberPushforward package
      (innerFiberInclusion package innerSwap) = 1
    exact (compositeFiberPushforward_eq_one_iff innerSwap.1).2 innerSwap.2

theorem witnessActiveFirst_not_qualified :
    ¬ StrictCellQualified witnessData .activeFirst := by
  intro qualified
  have pushed := qualified.2
  change compositeFiberPushforward package visibleComposite = 1 at pushed
  rw [visibleComposite_pushforward] at pushed
  apply visibleCore_ne_one
  exact pushed

theorem witnessActiveSecond_not_qualified :
    ¬ StrictCellQualified witnessData .activeSecond := by
  intro qualified
  have pushed := qualified.2
  change compositeFiberPushforward package visibleComposite = 1 at pushed
  rw [visibleComposite_pushforward] at pushed
  apply visibleCore_ne_one
  exact pushed

/-- The maximal strict sector contains exactly the intended strict face. -/
theorem witnessStrictTwoCell_eq_strict (cell : StrictTwoCell witnessData) :
    cell.1 = .strict := by
  rcases cell with ⟨cell, qualified⟩
  cases cell
  · exact False.elim (witnessActiveFirst_not_qualified qualified)
  · exact False.elim (witnessActiveSecond_not_qualified qualified)
  · rfl

theorem witnessStrictAuthored_eq_innerSwap
    (qualified : StrictCellQualified witnessData .strict) :
    strictAuthoredComparator witnessData ⟨.strict, qualified⟩ = innerSwap := by
  apply Subtype.ext
  rfl

theorem witnessStrictReselection_coherent :
    StrictCoherentAt witnessData witnessStrictReselection := by
  intro cell
  rcases cell with ⟨cell, qualified⟩
  cases cell
  · exact False.elim (witnessActiveFirst_not_qualified qualified)
  · exact False.elim (witnessActiveSecond_not_qualified qualified)
  · rw [witnessStrictAuthored_eq_innerSwap qualified]
    simp only [witnessPresentation, witnessTwoPresentation, witnessNilPath,
      witnessStrictPath, upperReselectedPathLift, upperReselectLiftData,
      TwoLayerLiftData.pathLift, upperReselectedEdgeLift,
      strictToUpperReselection, witnessData, witnessLiftData,
      witnessStrictReselection]
    exact Category.comp_id
      (self := geometryTotalCategory FiniteModel.carrier)
      (CompositeFiberAut.hom (innerFiberInclusion package innerSwap))

noncomputable def witnessStrictTrivializer : StrictTrivializer witnessData where
  reselection := witnessStrictReselection
  coherent := witnessStrictReselection_coherent

theorem witness_local_pairwise_vanishes : LocalPairwiseVanishes witnessData :=
  ⟨⟨witnessCoreTrivializer⟩, ⟨witnessStrictTrivializer⟩⟩

theorem witness_core_vanishes : CoreVanishes witnessData :=
  (coreVanishes_iff_nonempty_trivializer witnessData).2
    ⟨witnessCoreTrivializer⟩

theorem witness_strict_vanishes :
    StrictTransportObstructionVanishes witnessData :=
  (strictVanishes_iff_nonempty_trivializer witnessData).2
    ⟨witnessStrictTrivializer⟩

/-! ## Every core trivializer requires a nonliftable active coordinate -/

theorem witnessCoreTrivializer_active_square (trivializer :
    CoreTrivializer witnessData) :
    PackageFiberAut.hom visibleCore =
      (PackageFiberAut.hom
        (trivializer.reselection PUnit.unit PUnit.unit .active)).comp
      (PackageFiberAut.hom
        (trivializer.reselection PUnit.unit PUnit.unit .active)) := by
  simpa only [witnessPresentation, witnessTwoPresentation,
    witnessNilPath, witnessActiveDoublePath, reselectedPathLift,
    reselectLiftData, AdmissibleLiftData.pathLift, reselectedEdgeLift,
    witnessData, TwoLayerTransportData.coreData,
    TwoLayerLiftData.coreLiftData, witnessLiftData,
    visibleComposite_pushforward, Category.id_comp, Category.comp_id] using
    trivializer.coherent WitnessTwoCell.activeFirst

theorem packageFiberAxisMap_injective (automorphism : PackageFiberAut core) :
    Function.Injective (PackageFiberAut.hom automorphism).upper.axisMap := by
  intro first second equality
  have leftInverse (axis : Fin 4) :
      automorphism.1.inv.upper.axisMap
          (automorphism.1.hom.upper.axisMap axis) = axis := by
    have identity := congrArg
      (fun hom : PackageTotalHom core core => hom.upper.axisMap axis)
      automorphism.1.hom_inv_id
    exact identity
  calc
    first = automorphism.1.inv.upper.axisMap
        (automorphism.1.hom.upper.axisMap first) := (leftInverse first).symm
    _ = automorphism.1.inv.upper.axisMap
        (automorphism.1.hom.upper.axisMap second) := congrArg _ equality
    _ = second := leftInverse second

theorem selectedPair_square_zero
    (map : Fin 4 → Fin 4) (injective : Function.Injective map)
    (selectedZero : SelectedAxis (map 0))
    (selectedOne : SelectedAxis (map 1)) :
    map (map 0) = 0 := by
  rcases selectedZero with zeroFixed | zeroToOne
  · rw [zeroFixed]
    exact zeroFixed
  · rw [zeroToOne]
    rcases selectedOne with oneToZero | oneFixed
    · exact oneToZero
    · have impossible : (0 : Fin 4) = 1 :=
        injective (zeroToOne.trans oneFixed.symm)
      exact False.elim ((by decide : (0 : Fin 4) ≠ 1) impossible)

/-- No edgewise geometry section can lift the core coordinate of any trivializer. -/
theorem witnessCoreTrivializer_has_no_edgeSection
    (trivializer : CoreTrivializer witnessData) :
    ¬ ∃ edgeSection : EdgeSectionFamily witnessData,
      edgeSection.core = trivializer.reselection := by
  rintro ⟨edgeSection, coreEquality⟩
  let upper := edgeSection.lift PUnit.unit PUnit.unit WitnessEdge.active
  let coreGauge := trivializer.reselection PUnit.unit PUnit.unit WitnessEdge.active
  have projects := edgeSection.projects
    PUnit.unit PUnit.unit WitnessEdge.active
  rw [coreEquality] at projects
  have homEquality := congrArg PackageFiberAut.hom projects
  change upper.1.hom.base = PackageFiberAut.hom coreGauge at homEquality
  have axisZeroEquality := congrArg
    (fun hom : PackageTotalHom core core => hom.upper.axisMap (0 : Fin 4))
    homEquality
  have axisOneEquality := congrArg
    (fun hom : PackageTotalHom core core => hom.upper.axisMap (1 : Fin 4))
    homEquality
  change upper.1.hom.base.upper.axisMap (0 : Fin 4) =
    (PackageFiberAut.hom coreGauge).upper.axisMap (0 : Fin 4)
      at axisZeroEquality
  change upper.1.hom.base.upper.axisMap (1 : Fin 4) =
    (PackageFiberAut.hom coreGauge).upper.axisMap (1 : Fin 4)
      at axisOneEquality
  have upperSelectedZero :=
    upper.1.hom.geometry.coverage.requiredAxis (0 : Fin 4) (Or.inl rfl)
  have upperSelectedOne :=
    upper.1.hom.geometry.coverage.requiredAxis (1 : Fin 4) (Or.inr rfl)
  change SelectedAxis (upper.1.hom.base.upper.axisMap (0 : Fin 4))
    at upperSelectedZero
  change SelectedAxis (upper.1.hom.base.upper.axisMap (1 : Fin 4))
    at upperSelectedOne
  rw [axisZeroEquality] at upperSelectedZero
  rw [axisOneEquality] at upperSelectedOne
  have squareZero := selectedPair_square_zero
    (PackageFiberAut.hom coreGauge).upper.axisMap
    (packageFiberAxisMap_injective coreGauge)
    upperSelectedZero upperSelectedOne
  have activeSquare := congrArg
    (fun hom : PackageTotalHom core core => hom.upper.axisMap (0 : Fin 4))
    (witnessCoreTrivializer_active_square trivializer)
  change blockPermutation (0 : Fin 4) =
      (PackageFiberAut.hom coreGauge).upper.axisMap
        ((PackageFiberAut.hom coreGauge).upper.axisMap (0 : Fin 4))
    at activeSquare
  rw [squareZero] at activeSquare
  exact (by decide : blockPermutation (0 : Fin 4) ≠ 0) activeSquare

/-- In particular, no core trivializer admits an aligned section. -/
theorem witness_all_coreTrivializers_have_no_alignedSection :
    ∀ trivializer : CoreTrivializer witnessData,
      ¬ ∃ edgeSection : EdgeSectionFamily witnessData,
        edgeSection.core = trivializer.reselection ∧
          CoreAlignmentAt witnessData edgeSection := by
  intro trivializer
  rintro ⟨edgeSection, coreEquality, _alignment⟩
  exact witnessCoreTrivializer_has_no_edgeSection trivializer
    ⟨edgeSection, coreEquality⟩

theorem witness_compatiblePairs_empty : IsEmpty (CompatiblePairs witnessData) :=
  ⟨fun pair => witnessCoreTrivializer_has_no_edgeSection pair.coreTrivializer
    ⟨pair.edgeSection, rfl⟩⟩

/-- The orbit-to-compatible-pair theorem turns nonliftability into joint failure. -/
theorem witness_not_joint : ¬ JointVanishes witnessData := by
  intro joint
  obtain ⟨pair⟩ :=
    (jointVanishes_iff_compatiblePairwiseVanishes witnessData).1 joint
  exact witness_compatiblePairs_empty.false pair

theorem witnessCorePathLift_eq_id
    {i j : witnessPresentation.Vertex}
    (path : witnessPresentation.Path i j) :
    witnessData.coreData.lift.pathLift path = PackageTotalHom.id core := by
  have upperIdentity := witnessPathLift_eq_id path
  change witnessLiftData.coreLiftData.pathLift path = PackageTotalHom.id core
  rw [← witnessLiftData.pathLift_base path]
  exact congrArg GeometryTotalHom.base upperIdentity

theorem witness_identity_core_active_not_coherent :
    ¬ ((reselectedPathLift witnessData.coreData.lift 1
          (witnessPresentation.twoLeft WitnessTwoCell.activeFirst)).comp
        (PackageFiberAut.hom
          (witnessData.coreData.comparator WitnessTwoCell.activeFirst)) =
      reselectedPathLift witnessData.coreData.lift 1
        (witnessPresentation.twoRight WitnessTwoCell.activeFirst)) := by
  intro equation
  change (reselectedPathLift witnessData.coreData.lift 1
      (witnessPresentation.twoLeft WitnessTwoCell.activeFirst)).comp
      (PackageFiberAut.hom visibleCore) =
    reselectedPathLift witnessData.coreData.lift 1
      (witnessPresentation.twoRight WitnessTwoCell.activeFirst) at equation
  rw [reselectedPathLift_one, reselectedPathLift_one,
    witnessCorePathLift_eq_id, witnessCorePathLift_eq_id] at equation
  have homIdentity : PackageFiberAut.hom visibleCore =
      PackageTotalHom.id core := by
    calc
      PackageFiberAut.hom visibleCore =
          (PackageTotalHom.id core).comp
            (PackageFiberAut.hom visibleCore) :=
        (Category.id_comp
          (self := PackageTotalHom.packageTotalCategory FiniteModel.carrier)
          (PackageFiberAut.hom visibleCore)).symm
      _ = PackageTotalHom.id core := equation
  apply visibleCore_ne_one
  apply Subtype.ext
  apply Iso.ext
  exact homIdentity

/-- The active interstage defect is nonidentity at the baseline coordinate. -/
theorem witness_interstage_obstruction_ne_one :
    interstageObstruction witnessData WitnessTwoCell.activeFirst ≠ 1 := by
  intro identity
  have authoredEqCanonical :=
    (rawTwoCellDefect_eq_one_iff witnessData.coreData 1
      WitnessTwoCell.activeFirst).1 identity
  have factor := canonicalTwoCellComparator_fac witnessData.coreData 1
    WitnessTwoCell.activeFirst
  rw [← authoredEqCanonical] at factor
  exact witness_identity_core_active_not_coherent factor

/-- The corresponding total raw face is also nonidentity, by the projection formula. -/
theorem witness_upper_raw_active_ne_one :
    upperRawTwoCellDefect witnessData 1 WitnessTwoCell.activeFirst ≠ 1 := by
  intro identity
  have projection := totalObstruction_projection witnessData
    WitnessTwoCell.activeFirst
  rw [totalObstruction_eq_upperRaw, identity, map_one] at projection
  exact witness_interstage_obstruction_ne_one projection.symm

noncomputable def witnessStrictCell : StrictTwoCell witnessData :=
  ⟨.strict, witnessStrict_qualified⟩

theorem strictToUpperReselection_one :
    strictToUpperReselection witnessData.lift
      (1 : StrictEdgeReselection witnessData.lift) = 1 := by
  funext i j edge
  exact map_one _

theorem witnessUpperPathLift_one
    {i j : witnessPresentation.Vertex}
    (path : witnessPresentation.Path i j) :
    upperReselectedPathLift witnessData.lift 1 path =
      GeometryTotalHom.id package := by
  induction path with
  | nil => rfl
  | cons edge tail inductionHypothesis =>
      simp only [upperReselectedPathLift, upperReselectLiftData,
        TwoLayerLiftData.pathLift]
      change ((GeometryTotalHom.id package).comp
          (CompositeFiberAut.hom (1 : CompositeFiberAut package))).comp
          (upperReselectedPathLift witnessData.lift 1 tail) =
        GeometryTotalHom.id package
      rw [show CompositeFiberAut.hom (1 : CompositeFiberAut package) =
          GeometryTotalHom.id package by rfl]
      have identitySquared :
          (GeometryTotalHom.id package).comp (GeometryTotalHom.id package) =
            GeometryTotalHom.id package :=
        Category.comp_id
          (self := geometryTotalCategory FiniteModel.carrier)
          (GeometryTotalHom.id package)
      rw [identitySquared, inductionHypothesis]
      exact Category.comp_id
        (self := geometryTotalCategory FiniteModel.carrier)
        (GeometryTotalHom.id package)

/-- The strict raw face is genuinely nonidentity before applying its killer. -/
theorem witness_strict_raw_ne_one :
    strictRawTwoCellDefect witnessData 1 witnessStrictCell ≠ 1 := by
  intro identity
  have authoredEqCanonical :=
    (strictRawTwoCellDefect_eq_one_iff witnessData 1 witnessStrictCell).1
      identity
  have factor := strictCanonicalTwoCellComparator_fac witnessData 1
    witnessStrictCell
  rw [← authoredEqCanonical] at factor
  change (upperReselectedPathLift witnessData.lift
      (strictToUpperReselection witnessData.lift 1)
      (witnessPresentation.twoLeft WitnessTwoCell.strict)).comp
      (CompositeFiberAut.hom
        (innerFiberInclusion package innerSwap)) =
    upperReselectedPathLift witnessData.lift
      (strictToUpperReselection witnessData.lift 1)
      (witnessPresentation.twoRight WitnessTwoCell.strict) at factor
  rw [strictToUpperReselection_one, witnessUpperPathLift_one,
    witnessUpperPathLift_one] at factor
  have homIdentity :
      CompositeFiberAut.hom (innerFiberInclusion package innerSwap) =
        GeometryTotalHom.id package := by
    calc
      CompositeFiberAut.hom (innerFiberInclusion package innerSwap) =
          (GeometryTotalHom.id package).comp
            (CompositeFiberAut.hom
              (innerFiberInclusion package innerSwap)) :=
        (Category.id_comp
          (self := geometryTotalCategory FiniteModel.carrier)
          (CompositeFiberAut.hom
            (innerFiberInclusion package innerSwap))).symm
      _ = GeometryTotalHom.id package := factor
  apply innerSwap_ne_one
  apply Subtype.ext
  apply Subtype.ext
  apply Iso.ext
  exact homIdentity

/-! ## Nondegenerate closed syzygy -/

theorem witness_nontrivial_syzygy :
    NontrivialSyzygyAt (P := witnessPresentation)
      WitnessThreeCell.comparison := by
  simp [NontrivialSyzygyAt, witnessPresentation, witnessPasting,
    witnessStep, witnessFace, RewritePastingHasFace,
    RewritePastingUsesCell]

theorem witness_syzygy_support_has_nonidentity_raw :
    SyzygySupportHasNonidentityRaw witnessData 1
      WitnessThreeCell.comparison := by
  refine ⟨WitnessTwoCell.activeFirst, ?_, witness_upper_raw_active_ne_one⟩
  left
  simp [witnessPresentation, witnessPasting, witnessStep, witnessFace,
    RewritePastingUsesCell]

theorem witness_upper_syzygyCompatible :
    UpperSyzygyCompatible witnessData 1 := by
  intro cell
  cases cell
  rfl

/-- The conditional cocycle theorem fires on the actual nonempty syzygy. -/
theorem witness_upper_cocycle_fires :
    upperDefectPastingProduct witnessData 1
        (witnessPresentation.threeLeft WitnessThreeCell.comparison) =
      upperDefectPastingProduct witnessData 1
        (witnessPresentation.threeRight WitnessThreeCell.comparison) :=
  upperRawDefect_cocycle_of_syzygy witnessData 1
    witness_upper_syzygyCompatible WitnessThreeCell.comparison

/-- Its projected cocycle equation fires on the same support. -/
theorem witness_core_cocycle_fires :
    defectPastingProduct witnessData.coreData
        (pushforwardEdgeReselection witnessData.lift 1)
        (witnessPresentation.threeLeft WitnessThreeCell.comparison) =
      defectPastingProduct witnessData.coreData
        (pushforwardEdgeReselection witnessData.lift 1)
        (witnessPresentation.threeRight WitnessThreeCell.comparison) :=
  pushforward_upperRawDefect_cocycle_of_syzygy witnessData 1
    witness_upper_syzygyCompatible WitnessThreeCell.comparison

/-! ## Canonical positive diagram on the same finite geometry -/

/-- The positive diagram authors only identity comparisons on the same nonempty
presentation and the same two-layer lift data. -/
noncomputable def canonicalWitnessData :
    TwoLayerTransportData witnessPresentation FiniteModel.carrier where
  lift := witnessLiftData
  twoCellBase := by
    intro cell
    rw [witnessPathLift_eq_id, witnessPathLift_eq_id]
  comparator _ := 1

theorem canonicalWitness_coherentAt_identity :
    CrossStageCoherentAt canonicalWitnessData 1 := by
  intro cell
  change (upperReselectedPathLift witnessData.lift 1
      (witnessPresentation.twoLeft cell)).comp
      (CompositeFiberAut.hom (1 : CompositeFiberAut package)) =
    upperReselectedPathLift witnessData.lift 1
      (witnessPresentation.twoRight cell)
  rw [witnessUpperPathLift_one, witnessUpperPathLift_one]
  exact Category.comp_id
    (self := geometryTotalCategory FiniteModel.carrier)
    (GeometryTotalHom.id package)

theorem canonicalWitness_joint_vanishes :
    JointVanishes canonicalWitnessData :=
  (jointVanishes_iff_crossStageCoherentizable canonicalWitnessData).2
    ⟨1, canonicalWitness_coherentAt_identity⟩

/-- Concrete fixed-endpoint section supplied by the canonical joint gauge. -/
noncomputable def canonicalWitnessEdgeSection :
    EdgeSectionFamily canonicalWitnessData :=
  edgeSectionOfUpperReselection canonicalWitnessData 1

theorem canonicalWitness_alignment :
    CoreAlignmentAt canonicalWitnessData canonicalWitnessEdgeSection :=
  edgeSectionOfUpperReselection_alignment canonicalWitnessData 1
    canonicalWitness_coherentAt_identity

/-- The supplied section makes the three-term kernel decomposition fire. -/
theorem canonicalWitness_kernel_decomposition_fires (cell : WitnessTwoCell) :
    totalObstruction canonicalWitnessData cell =
      innerFiberInclusion
          (canonicalWitnessData.lift.geometry
            (witnessPresentation.twoTarget cell))
          (sectionInnerObstruction canonicalWitnessData
            canonicalWitnessEdgeSection canonicalWitness_alignment cell) *
        sectionLiftTerm canonicalWitnessData canonicalWitnessEdgeSection cell :=
  totalObstruction_kernel_decomposition canonicalWitnessData
    canonicalWitnessEdgeSection canonicalWitness_alignment cell

noncomputable def canonicalWitnessCompatiblePair :
    CompatiblePairs canonicalWitnessData :=
  jointGaugeToCompatiblePairs canonicalWitnessData 1
    canonicalWitness_coherentAt_identity

theorem canonicalWitness_compatible_pairwise_vanishes :
    CompatiblePairwiseVanishes canonicalWitnessData :=
  ⟨canonicalWitnessCompatiblePair⟩

/-- Both nonempty sides of the positive gluing theorem fire on this diagram. -/
theorem canonicalWitness_positive_gluing_fires :
    JointVanishes canonicalWitnessData ∧
      CompatiblePairwiseVanishes canonicalWitnessData :=
  ⟨canonicalWitness_joint_vanishes,
    canonicalWitness_compatible_pairwise_vanishes⟩

theorem canonicalWitness_joint_iff_compatible :
    JointVanishes canonicalWitnessData ↔
      CompatiblePairwiseVanishes canonicalWitnessData :=
  jointVanishes_iff_compatiblePairwiseVanishes canonicalWitnessData

/-- The positive fixture passes through the independently reconstructed
pseudofunctor obstruction orbit. -/
theorem canonicalWitness_pseudofunctor_obstruction_vanishes :
    PseudofunctorObstructionVanishes canonicalWitnessData :=
  (pseudofunctorObstructionVanishes_iff_joint canonicalWitnessData).2
    canonicalWitness_joint_vanishes

theorem canonicalWitness_pseudofunctor_raw_is_general :
    pseudofunctorRawDefectCochain canonicalWitnessData 1 =
      upperRawDefectCochain canonicalWitnessData 1 :=
  pseudofunctorRawDefectCochain_eq_upper canonicalWitnessData 1

theorem canonicalWitness_categorical_anchor_fires :
    CrossStageCoherentizable canonicalWitnessData :=
  (jointVanishes_iff_crossStageCoherentizable canonicalWitnessData).1
    canonicalWitness_joint_vanishes

/-- The negative fixture passes through the same unification and categorical
anchor; failure is therefore not introduced by a second obstruction notion. -/
theorem witness_pseudofunctor_obstruction_does_not_vanish :
    ¬ PseudofunctorObstructionVanishes witnessData := by
  intro vanishes
  exact witness_not_joint
    ((pseudofunctorObstructionVanishes_iff_joint witnessData).1 vanishes)

theorem witness_pseudofunctor_raw_is_general :
    pseudofunctorRawDefectCochain witnessData 1 =
      upperRawDefectCochain witnessData 1 :=
  pseudofunctorRawDefectCochain_eq_upper witnessData 1

theorem witness_categorical_anchor_does_not_fire :
    ¬ CrossStageCoherentizable witnessData := by
  intro coherentizable
  exact witness_not_joint
    ((jointVanishes_iff_crossStageCoherentizable witnessData).2 coherentizable)

/-! ## Combined fixture qualifications -/

theorem witness_strict_sector_nonempty :
    Nonempty (StrictTwoCell witnessData) := ⟨witnessStrictCell⟩

theorem witness_strict_inclusion_not_surjective :
    ¬ Function.Surjective (strictTwoCellEmbedding witnessData) := by
  intro surjective
  obtain ⟨cell, equality⟩ := surjective WitnessTwoCell.activeFirst
  change cell.1 = WitnessTwoCell.activeFirst at equality
  have qualified := cell.property
  rw [equality] at qualified
  exact witnessActiveFirst_not_qualified qualified

theorem witness_core_active_cell_exists :
    ∃ cell : WitnessTwoCell,
      ¬ StrictCellQualified witnessData cell ∧
        interstageObstruction witnessData cell ≠ 1 :=
  ⟨.activeFirst, witnessActiveFirst_not_qualified,
    witness_interstage_obstruction_ne_one⟩

/-- The independent local killers disagree on their shared one-vertex boundary. -/
theorem witness_shared_boundary_incompatible :
    LocalPairwiseVanishes witnessData ∧ IsEmpty (CompatiblePairs witnessData) :=
  ⟨witness_local_pairwise_vanishes, witness_compatiblePairs_empty⟩

/-- All negative obligations are joined on the single closed `witnessData` fixture. -/
theorem finite_cross_stage_negative_witness :
    compositeFiberPushforward package visibleComposite ≠ 1 ∧
      LocalPairwiseVanishes witnessData ∧
      ¬ JointVanishes witnessData ∧
      (∀ trivializer : CoreTrivializer witnessData,
        ¬ ∃ edgeSection : EdgeSectionFamily witnessData,
          edgeSection.core = trivializer.reselection ∧
            CoreAlignmentAt witnessData edgeSection) ∧
      interstageObstruction witnessData WitnessTwoCell.activeFirst ≠ 1 ∧
      strictRawTwoCellDefect witnessData 1 witnessStrictCell ≠ 1 ∧
      NontrivialSyzygyAt (P := witnessPresentation)
        WitnessThreeCell.comparison ∧
      SyzygySupportHasNonidentityRaw witnessData 1
        WitnessThreeCell.comparison ∧
      UpperSyzygyCompatible witnessData 1 := by
  refine ⟨compositeFiberPushforward_nontrivial,
    witness_local_pairwise_vanishes, witness_not_joint,
    witness_all_coreTrivializers_have_no_alignedSection,
    witness_interstage_obstruction_ne_one, witness_strict_raw_ne_one,
    witness_nontrivial_syzygy, witness_syzygy_support_has_nonidentity_raw,
    witness_upper_syzygyCompatible⟩

end FiniteCrossStageWitness

end AAT.AG.CrossStageCoherence

#assert_standard_axioms_only AAT.AG.CrossStageCoherence
