import ResearchLean.AG.CrossStageCoherence.ComparisonDescent

/-!
# Path-gauge coordinates and realizable comparison descent

This module implements theorem (D) of the fixed G-109 target.  An upper edge
gauge generates a canonical endpoint coordinate on every presented path by
strong-cocartesian uniqueness.  These coordinates are identity on empty paths,
equal the assigned gauge on one-edge paths, and obey the noncommutative
canonical-comparator transition square.

A realizable comparison section consists of an ordinary descent section and
one actual upper edge gauge whose generated path coordinates are exactly the
section values.  The independent total obstruction orbit vanishes if and only
if such a realizable section exists.

## Implementation notes

`PathGaugeCoordinate` is constructed from the reviewed
`canonicalCompositeFiberComparator`; it is not supplied as a field and is not
defined from a comparison section.  Realizability is kept in a separate
structure, so `CellComparisonSection` and `CellChainCoherent` remain unchanged.
-/

namespace AAT.AG.CrossStageCoherence

universe u v

open CategoryTheory
open AtomFoundation
open GeometryTransport
open TransportCoherence

set_option maxHeartbeats 3000000

/-! ## Canonical path coordinates -/

/-- Identity upper reselection recovers the original selected path lift. -/
@[simp]
theorem upperReselectedPathLift_one
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    {source target : P.Vertex} (path : P.Path source target) :
    upperReselectedPathLift data 1 path = data.pathLift path := by
  induction path with
  | nil vertex => rfl
  | cons edge tail inductionHypothesis =>
      change ((data.edgeLift edge).comp
          (CompositeFiberAut.hom (1 : CompositeFiberAut _))).comp
            (upperReselectedPathLift data 1 tail) =
        (data.edgeLift edge).comp (data.pathLift tail)
      have edgeOne : (data.edgeLift edge).comp
          (𝟙 (data.geometry _)) = data.edgeLift edge :=
        @Category.comp_id
          (GeomReadCategory.{u, v} U) (geometryTotalCategory U)
          _ _ (data.edgeLift edge)
      rw [compositeFiberAut_hom_one, edgeOne, inductionHypothesis]

/-- A one-edge path evaluates to the selected two-layer edge lift. -/
@[simp]
theorem twoLayerPathLift_singleEdge
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    {source target : P.Vertex} (edge : P.Edge source target) :
    data.pathLift (.cons edge (.nil target)) = data.edgeLift edge := by
  change (data.edgeLift edge).comp (𝟙 (data.geometry target)) =
    data.edgeLift edge
  exact @Category.comp_id
    (GeomReadCategory.{u, v} U) (geometryTotalCategory U)
    _ _ (data.edgeLift edge)

/-- A reselected one-edge path evaluates to the reselected upper edge lift. -/
@[simp]
theorem upperReselectedPathLift_singleEdge
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    (gauge : UpperEdgeReselection data)
    {source target : P.Vertex} (edge : P.Edge source target) :
    upperReselectedPathLift data gauge (.cons edge (.nil target)) =
      upperReselectedEdgeLift data gauge edge := by
  change (upperReselectedEdgeLift data gauge edge).comp
      (𝟙 (data.geometry target)) = upperReselectedEdgeLift data gauge edge
  exact @Category.comp_id
    (GeomReadCategory.{u, v} U) (geometryTotalCategory U)
    _ _ (upperReselectedEdgeLift data gauge edge)

/--
The canonical endpoint coordinate from the original path lift to the lift
generated by an upper edge gauge.
-/
noncomputable def PathGaugeCoordinate
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    (gauge : UpperEdgeReselection data)
    {source target : P.Vertex} (path : P.Path source target) :
    CompositeFiberAut (data.geometry target) := by
  letI : (geometryProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data 1 path).base
      (upperReselectedPathLift data 1 path) :=
    (upperReselectLiftData data 1).pathLift_geometryStrong path
  letI : (geometryProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data gauge path).base
      (upperReselectedPathLift data gauge path) :=
    (upperReselectLiftData data gauge).pathLift_geometryStrong path
  letI : (packageProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data 1 path).base.base
      (upperReselectedPathLift data 1 path).base :=
    (upperReselectLiftData data 1).pathLift_coreStrong path
  letI : (packageProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data gauge path).base.base
      (upperReselectedPathLift data gauge path).base :=
    (upperReselectLiftData data gauge).pathLift_coreStrong path
  exact canonicalCompositeFiberComparator
    (upperReselectedPathLift data 1 path)
    (upperReselectedPathLift data gauge path)
    ((upperReselectedPathLift_base_base data 1 path).trans
      (upperReselectedPathLift_base_base data gauge path).symm)

/-- The generated coordinate factors the baseline path lift into its reselection. -/
@[simp]
theorem pathGaugeCoordinate_fac
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    (gauge : UpperEdgeReselection data)
    {source target : P.Vertex} (path : P.Path source target) :
    (upperReselectedPathLift data 1 path).comp
        (CompositeFiberAut.hom (PathGaugeCoordinate data gauge path)) =
      upperReselectedPathLift data gauge path := by
  letI : (geometryProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data 1 path).base
      (upperReselectedPathLift data 1 path) :=
    (upperReselectLiftData data 1).pathLift_geometryStrong path
  letI : (geometryProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data gauge path).base
      (upperReselectedPathLift data gauge path) :=
    (upperReselectLiftData data gauge).pathLift_geometryStrong path
  letI : (packageProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data 1 path).base.base
      (upperReselectedPathLift data 1 path).base :=
    (upperReselectLiftData data 1).pathLift_coreStrong path
  letI : (packageProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data gauge path).base.base
      (upperReselectedPathLift data gauge path).base :=
    (upperReselectLiftData data gauge).pathLift_coreStrong path
  exact canonicalCompositeFiberComparator_fac
    (upperReselectedPathLift data 1 path)
    (upperReselectedPathLift data gauge path)
    ((upperReselectedPathLift_base_base data 1 path).trans
      (upperReselectedPathLift_base_base data gauge path).symm)

/-- The fixed factorization equation stated with the original `pathLift`. -/
theorem pathGaugeCoordinate_fac_pathLift
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    (gauge : UpperEdgeReselection data)
    {source target : P.Vertex} (path : P.Path source target) :
    (data.pathLift path).comp
        (CompositeFiberAut.hom (PathGaugeCoordinate data gauge path)) =
      upperReselectedPathLift data gauge path := by
  rw [← upperReselectedPathLift_one data path]
  exact pathGaugeCoordinate_fac data gauge path

/-- Strong cancellation makes the path-gauge coordinate unique. -/
theorem pathGaugeCoordinate_unique
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    (gauge : UpperEdgeReselection data)
    {source target : P.Vertex} (path : P.Path source target)
    (coordinate : CompositeFiberAut (data.geometry target))
    (realizes : (data.pathLift path).comp
        (CompositeFiberAut.hom coordinate) =
      upperReselectedPathLift data gauge path) :
    coordinate = PathGaugeCoordinate data gauge path := by
  let lift := data.pathLift path
  letI : (crossStageProjection.{u, v} U).IsStronglyCocartesian
      lift.base.base lift := data.pathLift_compositeStrong path
  apply CompositeFiberAut.ext_of_strong_fac lift
  exact realizes.trans (pathGaugeCoordinate_fac_pathLift data gauge path).symm

/-- Existence and uniqueness of the coordinate are consequences, not input fields. -/
theorem existsUnique_pathGaugeCoordinate
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    (gauge : UpperEdgeReselection data)
    {source target : P.Vertex} (path : P.Path source target) :
    ∃! coordinate : CompositeFiberAut (data.geometry target),
      (data.pathLift path).comp (CompositeFiberAut.hom coordinate) =
        upperReselectedPathLift data gauge path := by
  refine ⟨PathGaugeCoordinate data gauge path,
    pathGaugeCoordinate_fac_pathLift data gauge path, ?_⟩
  intro coordinate realizes
  exact pathGaugeCoordinate_unique data gauge path coordinate realizes

/-- Empty paths carry the identity path-gauge coordinate. -/
@[simp]
theorem pathGaugeCoordinate_nil
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    (gauge : UpperEdgeReselection data) (vertex : P.Vertex) :
    PathGaugeCoordinate data gauge (.nil vertex) = 1 := by
  symm
  apply pathGaugeCoordinate_unique data gauge (.nil vertex) 1
  change (GeometryTotalHom.id (data.geometry vertex)).comp
      (𝟙 (data.geometry vertex)) = GeometryTotalHom.id (data.geometry vertex)
  exact @Category.comp_id
    (GeomReadCategory.{u, v} U) (geometryTotalCategory U)
    _ _ (GeometryTotalHom.id (data.geometry vertex))

/-- On a single edge the generated path coordinate is the assigned edge gauge. -/
@[simp]
theorem pathGaugeCoordinate_singleEdge
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    (gauge : UpperEdgeReselection data)
    {source target : P.Vertex} (edge : P.Edge source target) :
    PathGaugeCoordinate data gauge (.cons edge (.nil target)) =
      gauge source target edge := by
  symm
  apply pathGaugeCoordinate_unique data gauge
    (.cons edge (.nil target)) (gauge source target edge)
  rw [twoLayerPathLift_singleEdge, upperReselectedPathLift_singleEdge]
  rfl

/-! ## The noncommutative transition square -/

/-- The two path coordinates form the canonical-comparator transition square. -/
theorem pathGaugeCoordinate_upperCanonical_transition_fac
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    (gauge : UpperEdgeReselection data.lift) (cell : P.TwoCell) :
    upperCanonicalTwoCellComparator data gauge cell *
        PathGaugeCoordinate data.lift gauge (P.twoLeft cell) =
      PathGaugeCoordinate data.lift gauge (P.twoRight cell) *
        upperCanonicalTwoCellComparator data 1 cell := by
  let baselineLeft := upperReselectedPathLift data.lift 1 (P.twoLeft cell)
  letI : (crossStageProjection.{u, v} U).IsStronglyCocartesian
      baselineLeft.base.base baselineLeft :=
    (upperReselectLiftData data.lift 1).pathLift_compositeStrong
      (P.twoLeft cell)
  apply CompositeFiberAut.ext_of_strong_fac baselineLeft
  change baselineLeft.comp
      ((CompositeFiberAut.hom
        (PathGaugeCoordinate data.lift gauge (P.twoLeft cell))).comp
        (CompositeFiberAut.hom
          (upperCanonicalTwoCellComparator data gauge cell))) =
    baselineLeft.comp
      ((CompositeFiberAut.hom
        (upperCanonicalTwoCellComparator data 1 cell)).comp
        (CompositeFiberAut.hom
          (PathGaugeCoordinate data.lift gauge (P.twoRight cell))))
  calc
    baselineLeft.comp
        ((CompositeFiberAut.hom
          (PathGaugeCoordinate data.lift gauge (P.twoLeft cell))).comp
          (CompositeFiberAut.hom
            (upperCanonicalTwoCellComparator data gauge cell))) =
      (baselineLeft.comp
        (CompositeFiberAut.hom
          (PathGaugeCoordinate data.lift gauge (P.twoLeft cell)))).comp
        (CompositeFiberAut.hom
          (upperCanonicalTwoCellComparator data gauge cell)) :=
      (@Category.assoc
        (GeomReadCategory.{u, v} U) (geometryTotalCategory U)
        _ _ _ _ _ _ _).symm
    _ = (upperReselectedPathLift data.lift gauge
          (P.twoLeft cell)).comp
        (CompositeFiberAut.hom
          (upperCanonicalTwoCellComparator data gauge cell)) := by
      rw [pathGaugeCoordinate_fac]
    _ = upperReselectedPathLift data.lift gauge (P.twoRight cell) :=
      upperCanonicalTwoCellComparator_fac data gauge cell
    _ = (upperReselectedPathLift data.lift 1
          (P.twoRight cell)).comp
        (CompositeFiberAut.hom
          (PathGaugeCoordinate data.lift gauge (P.twoRight cell))) :=
      (pathGaugeCoordinate_fac data.lift gauge (P.twoRight cell)).symm
    _ = ((upperReselectedPathLift data.lift 1
          (P.twoLeft cell)).comp
        (CompositeFiberAut.hom
          (upperCanonicalTwoCellComparator data 1 cell))).comp
        (CompositeFiberAut.hom
          (PathGaugeCoordinate data.lift gauge (P.twoRight cell))) := by
      rw [upperCanonicalTwoCellComparator_fac]
    _ = baselineLeft.comp
        ((CompositeFiberAut.hom
          (upperCanonicalTwoCellComparator data 1 cell)).comp
          (CompositeFiberAut.hom
            (PathGaugeCoordinate data.lift gauge (P.twoRight cell)))) :=
      @Category.assoc
        (GeomReadCategory.{u, v} U) (geometryTotalCategory U)
        _ _ _ _ _ _ _

/-- Solved transition: the right-path gauge acts on the left. -/
theorem pathGaugeCoordinate_upperCanonical_transition
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    (gauge : UpperEdgeReselection data.lift) (cell : P.TwoCell) :
    upperCanonicalTwoCellComparator data gauge cell =
      PathGaugeCoordinate data.lift gauge (P.twoRight cell) *
        upperCanonicalTwoCellComparator data 1 cell *
          (PathGaugeCoordinate data.lift gauge (P.twoLeft cell))⁻¹ := by
  apply mul_right_cancel
    (b := PathGaugeCoordinate data.lift gauge (P.twoLeft cell))
  rw [pathGaugeCoordinate_upperCanonical_transition_fac]
  simp [mul_assoc]

/-! ## Realizable comparison sections and theorem (D) -/

/-- A formal comparison section realized by one actual upper edge gauge. -/
structure EdgeRealizableCellComparisonSection
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U) where
  comparison : CellComparisonSection data
  gauge : UpperEdgeReselection data.lift
  realizes : ∀ {source target : P.Vertex}
    (node : CellChainNode P source target),
    PathGaugeCoordinate data.lift gauge node.path = comparison.value node

/-- A coherent upper edge gauge generates its own realizable comparison section. -/
noncomputable def edgeRealizableSectionOfCoherentAt
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U)
    (gauge : UpperEdgeReselection data.lift)
    (coherent : CrossStageCoherentAt data gauge) :
    EdgeRealizableCellComparisonSection data where
  gauge := gauge
  comparison :=
    { value := fun {_ _} node =>
        PathGaugeCoordinate data.lift gauge node.path
      nil_normalization := pathGaugeCoordinate_nil data.lift gauge
      naturality := by
        intro cell
        change PathGaugeCoordinate data.lift gauge (P.twoRight cell) =
          data.comparator cell *
            PathGaugeCoordinate data.lift gauge (P.twoLeft cell) *
              (upperCanonicalTwoCellComparator data 1 cell)⁻¹
        have rawIdentity :=
          (crossStageCoherentAt_iff_rawCochain_identity data gauge).1 coherent
        have authoredEqCanonical :=
          (upperRawTwoCellDefect_eq_one_iff data gauge cell).1
            (congrFun rawIdentity cell)
        rw [authoredEqCanonical,
          pathGaugeCoordinate_upperCanonical_transition]
        group }
  realizes := by
    intro source target node
    rfl

namespace EdgeRealizableCellComparisonSection

/-- A realizable section recovers the categorical all-cell equations. -/
theorem crossStageCoherentAt
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    {data : TwoLayerTransportData.{u, v} P U}
    (realizable : EdgeRealizableCellComparisonSection data) :
    CrossStageCoherentAt data realizable.gauge := by
  apply (crossStageCoherentAt_iff_rawCochain_identity
    data realizable.gauge).2
  funext cell
  change upperRawTwoCellDefect data realizable.gauge cell = 1
  apply (upperRawTwoCellDefect_eq_one_iff data realizable.gauge cell).2
  have naturality := realizable.comparison.naturality cell
  rw [← realizable.realizes (CellChainNode.right P cell),
    ← realizable.realizes (CellChainNode.left P cell)] at naturality
  change PathGaugeCoordinate data.lift realizable.gauge (P.twoRight cell) =
    data.comparator cell *
      PathGaugeCoordinate data.lift realizable.gauge (P.twoLeft cell) *
        (upperCanonicalTwoCellComparator data 1 cell)⁻¹ at naturality
  calc
    data.comparator cell =
        PathGaugeCoordinate data.lift realizable.gauge (P.twoRight cell) *
          upperCanonicalTwoCellComparator data 1 cell *
            (PathGaugeCoordinate data.lift realizable.gauge
              (P.twoLeft cell))⁻¹ := by
      rw [naturality]
      group
    _ = upperCanonicalTwoCellComparator data realizable.gauge cell :=
      (pathGaugeCoordinate_upperCanonical_transition
        data realizable.gauge cell).symm

end EdgeRealizableCellComparisonSection

/--
Fixed theorem (D): total orbit vanishing is equivalent to comparison descent
that is effective at one actual edge gauge.
-/
theorem jointVanishes_iff_nonempty_edgeRealizableSection
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U) :
    JointVanishes data ↔
      Nonempty (EdgeRealizableCellComparisonSection data) := by
  constructor
  · intro vanishes
    rcases (jointVanishes_iff_crossStageCoherentizable data).1 vanishes with
      ⟨gauge, coherent⟩
    exact ⟨edgeRealizableSectionOfCoherentAt data gauge coherent⟩
  · rintro ⟨realizable⟩
    apply (jointVanishes_iff_crossStageCoherentizable data).2
    exact ⟨realizable.gauge, realizable.crossStageCoherentAt⟩

end AAT.AG.CrossStageCoherence

#assert_standard_axioms_only AAT.AG.CrossStageCoherence
