import ResearchLean.AG.CrossStageCoherence.PathGaugeEffectivity
import ResearchLean.AG.CrossStageCoherence.CorePushforward

/-!
# Core pushforward of path-gauge realizability

This module completes the realizable-section clause of fixed G-109 theorem
(G).  Projection sends the canonical upper path-gauge coordinate to the
existing G-106 path-reselection transition.  Consequently an upper
edge-realizable comparison section pushes pointwise to a core comparison
section realized by the projected edge gauge.

The core coordinate is the existing `pathReselectionTransition`; no
effectivity-preservation or reflection statement is asserted.  Those
base-change questions remain the fixed G-110 frontier.

## Implementation notes

`CoreEdgeRealizableCellComparisonSection` mirrors the upper realizability
certificate: it keeps one actual core edge gauge together with the pointwise
equation saying that this gauge realizes every typed path node.  Keeping the
gauge is essential because a bare `CoreCellComparisonSection` records formal
descent but forgets the realization datum used by theorem (G).

We deliberately reject storing effectivity preservation, reflection, or a
prepackaged projected conclusion as fields.  Those choices would either cross
the fixed G-110 frontier or hide theorem (G)'s pointwise pushforward claim in
the certificate.  Reusing the G-106 `pathReselectionTransition` also avoids a
second core path-coordinate evaluator.
-/

namespace AAT.AG.CrossStageCoherence

universe u v

open CategoryTheory
open AtomFoundation
open GeometryTransport
open TransportCoherence

set_option maxHeartbeats 3000000

/-! ## Projection of canonical path coordinates -/

/--
Projection sends an upper path-gauge coordinate to the G-106 endpoint
transition generated by the projected edge gauge.
-/
theorem pushforward_pathGaugeCoordinate
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerLiftData.{u, v} P U)
    (gauge : UpperEdgeReselection data)
    {source target : P.Vertex} (path : P.Path source target) :
    compositeFiberPushforward (data.geometry target)
        (PathGaugeCoordinate data gauge path) =
      pathReselectionTransition data.coreLiftData 1
        (pushforwardEdgeReselection data gauge) path := by
  letI : (geometryProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data 1 path).base
      (upperReselectedPathLift data 1 path) :=
    (upperReselectLiftData data 1).pathLift_geometryStrong path
  letI : (geometryProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data gauge path).base
      (upperReselectedPathLift data gauge path) :=
    (upperReselectLiftData data gauge).pathLift_geometryStrong path
  letI : (packageProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data 1 path).base.base
      (upperReselectedPathLift data 1 path).base :=
    (upperReselectLiftData data 1).pathLift_coreStrong path
  letI : (packageProjection U).IsStronglyCocartesian
      (upperReselectedPathLift data gauge path).base.base
      (upperReselectedPathLift data gauge path).base :=
    (upperReselectLiftData data gauge).pathLift_coreStrong path
  unfold PathGaugeCoordinate pathReselectionTransition
  simpa only [upperReselectedPathLift_base,
    pushforwardEdgeReselection_one] using
    compositeFiberPushforward_canonicalComparator
      (upperReselectedPathLift data 1 path)
      (upperReselectedPathLift data gauge path)
      ((upperReselectedPathLift_base_base data 1 path).trans
        (upperReselectedPathLift_base_base data gauge path).symm)

/-! ## Core realizable comparison sections -/

/-- A core comparison section realized by one actual core edge gauge. -/
structure CoreEdgeRealizableCellComparisonSection
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    (data : TwoLayerTransportData.{u, v} P U) where
  comparison : CoreCellComparisonSection data
  gauge : EdgeReselection data.coreData.lift
  realizes : ∀ {source target : P.Vertex}
    (node : CellChainNode P source target),
    pathReselectionTransition data.coreData.lift 1 gauge node.path =
      comparison.value node

/--
Fixed theorem (G), realizability part: projection sends an upper realizable
section pointwise to a core realizable section.
-/
noncomputable def EdgeRealizableCellComparisonSection.pushforwardCore
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    {data : TwoLayerTransportData.{u, v} P U}
    (realizable : EdgeRealizableCellComparisonSection data) :
    CoreEdgeRealizableCellComparisonSection data where
  comparison := realizable.comparison.pushforwardCore
  gauge := pushforwardEdgeReselection data.lift realizable.gauge
  realizes := by
    intro source target node
    change pathReselectionTransition data.lift.coreLiftData 1
        (pushforwardEdgeReselection data.lift realizable.gauge) node.path =
      realizable.comparison.pushforwardCore.value node
    rw [← pushforward_pathGaugeCoordinate data.lift realizable.gauge node.path,
      realizable.realizes node]
    rfl

/-- Pointwise core realization is exactly the projection of upper realization. -/
theorem EdgeRealizableCellComparisonSection.pushforwardCore_value
    {P : FiniteTransportPresentation.{u}} {U : AtomCarrier.{u}}
    {data : TwoLayerTransportData.{u, v} P U}
    (realizable : EdgeRealizableCellComparisonSection data)
    {source target : P.Vertex} (node : CellChainNode P source target) :
    realizable.pushforwardCore.comparison.value node =
      compositeFiberPushforward (data.lift.geometry target)
        (realizable.comparison.value node) :=
  rfl

end AAT.AG.CrossStageCoherence

#assert_standard_axioms_only AAT.AG.CrossStageCoherence
