import ResearchLean.AG.TwoPhase.DependencyProfile
import Formal.AG.Cohomology.CoverNerve
import Formal.Util.AssertStandardAxioms
import Mathlib.Algebra.Exact
import Mathlib.LinearAlgebra.Quotient.Basic

/-!
# Atom-indexed two-phase coefficient complexes

This module discharges stage E1 of
`G-102-aat-two-phase-obstruction`.  It attaches the E0 source--Atom dependency
profile to finite chart, edge, and face Atom bases.  Their declared restriction
correspondences first generate an expanded nerve; the coefficient complex is the
reviewed `FiniteNerveCochainComplex` on that generated nerve.  The structural
coordinate subspaces are generated by the basis coordinates whose attached
pairs are structural.  Condition E says only that the two incidence
differentials preserve those subspaces.

Under Condition E, the structural restriction and semantic quotient are
constructed canonically.  Inclusion and quotient are cochain maps, and their
degreewise short exactness is proved from Mathlib's subtype/quotient exactness;
exactness is not a field of the coefficient data or of Condition E.

## Implementation notes

The underlying differential is the reviewed nerve-incidence differential of
`FiniteNerveCochainComplex`; it is not supplied independently of its incidence
formula.  The six support-correspondence maps generate the nerve endpoint and
face maps, hence determine which Atom coordinates enter each differential.
The three pair maps record the doctrine-derived provenance of those coordinates.
Condition E then audits whether the generated formulas preserve phase support.

The coordinate support subspace is presented by a zero-off-support predicate for
usable membership API.  `coordinateSupport_eq_span` proves that this is exactly
the span of the corresponding standard basis vectors, rather than an opaque
selected submodule.
-/

noncomputable section

namespace AAT.AG.TwoPhase

open Cohomology

universe u n v w

/-- A finite three-term linear cochain complex in degrees zero through two. -/
structure ThreeCochainComplex (k : Type v) [Field k] where
  C0 : Type w
  C1 : Type w
  C2 : Type w
  [add_C0 : AddCommGroup C0]
  [add_C1 : AddCommGroup C1]
  [add_C2 : AddCommGroup C2]
  [module_C0 : Module k C0]
  [module_C1 : Module k C1]
  [module_C2 : Module k C2]
  [finiteDimensional_C0 : FiniteDimensional k C0]
  [finiteDimensional_C1 : FiniteDimensional k C1]
  [finiteDimensional_C2 : FiniteDimensional k C2]
  d0 : C0 →ₗ[k] C1
  d1 : C1 →ₗ[k] C2
  d1_comp_d0 : ∀ c, d1 (d0 c) = 0

namespace ThreeCochainComplex

attribute [instance] add_C0 add_C1 add_C2
attribute [instance] module_C0 module_C1 module_C2
attribute [instance] finiteDimensional_C0 finiteDimensional_C1 finiteDimensional_C2

/-- A morphism of finite three-term cochain complexes. -/
structure Hom {k : Type v} [Field k]
    (source target : ThreeCochainComplex k) where
  f0 : source.C0 →ₗ[k] target.C0
  f1 : source.C1 →ₗ[k] target.C1
  f2 : source.C2 →ₗ[k] target.C2
  comm0 : ∀ c, f1 (source.d0 c) = target.d0 (f0 c)
  comm1 : ∀ c, f2 (source.d1 c) = target.d1 (f1 c)

end ThreeCochainComplex

/-- The standard coordinate vector supported at one finite basis index. -/
noncomputable def coordinateVector {k : Type v} [Field k] {ι : Type*}
    (i : ι) : ι → k := by
  classical
  exact Pi.single i 1

/-- Coordinate functions supported only where `phase` holds. -/
def coordinateSupport (k : Type v) [Field k] {ι : Type*}
    (phase : ι → Prop) : Submodule k (ι → k) where
  carrier := {f | ∀ i, ¬ phase i → f i = 0}
  zero_mem' := by simp
  add_mem' := by
    intro f g hf hg i hi
    simp [hf i hi, hg i hi]
  smul_mem' := by
    intro scalar f hf i hi
    simp [hf i hi]

/-- Membership in a coordinate-support subspace is pointwise vanishing off support. -/
theorem mem_coordinateSupport_iff
    {k : Type v} [Field k] {ι : Type*} (phase : ι → Prop) (f : ι → k) :
    f ∈ coordinateSupport k phase ↔ ∀ i, ¬ phase i → f i = 0 :=
  Iff.rfl

/--
For a finite basis, the support subspace is exactly the span of supported
standard coordinate vectors.
-/
theorem coordinateSupport_eq_span
    {k : Type v} [Field k] {ι : Type*} [Fintype ι]
    (phase : ι → Prop) :
    coordinateSupport k phase =
      Submodule.span k {f | ∃ i, phase i ∧ f = coordinateVector i} := by
  classical
  apply le_antisymm
  · intro f hf
    have hdecomp : f = ∑ i, f i • coordinateVector i := by
      funext j
      simp [coordinateVector, Pi.single_apply]
    rw [hdecomp]
    apply Submodule.sum_mem
    intro i _hi
    by_cases hphase : phase i
    · exact Submodule.smul_mem _ _
        (Submodule.subset_span ⟨i, hphase, rfl⟩)
    · rw [hf i hphase]
      simp
  · apply Submodule.span_le.2
    rintro f ⟨i, hi, rfl⟩
    intro j hj
    have hne : i ≠ j := by
      intro hij
      exact hj (hij ▸ hi)
    simp [coordinateVector, hne]

/--
Finite source--Atom supports on a base nerve, with all incidence
correspondences declared before the coefficient differential is constructed.

Each chart, edge, and face has its own finite basis.  The six index maps specify
how an edge basis element lands in the two endpoint chart supports and how a
face basis element lands in its three boundary-edge supports.  These maps, not
an annotation added to an existing scalar complex, construct the expanded nerve
whose incidence formulas define the coefficient differential.
-/
structure AtomIndexedNerveData
    {U : AtomCarrier.{u}} (D : ExtractionDoctrine U)
    (N : CoverNerve.{n}) where
  [fintypeChart : Fintype N.Chart]
  [fintypeEdge : Fintype N.EdgeComponent]
  [fintypeFace : Fintype N.FaceComponent]
  /-- Finite Atom basis over each chart component. -/
  ChartBasis : N.Chart → Type u
  /-- Finite Atom basis over each edge component. -/
  EdgeBasis : N.EdgeComponent → Type u
  /-- Finite Atom basis over each face component. -/
  FaceBasis : N.FaceComponent → Type u
  chartBasisFintype : ∀ chart, Fintype (ChartBasis chart)
  edgeBasisFintype : ∀ edge, Fintype (EdgeBasis edge)
  faceBasisFintype : ∀ face, Fintype (FaceBasis face)
  /-- Doctrine-derived pair represented by a chart-basis coordinate. -/
  chartPair : ∀ chart, ChartBasis chart → ExtractionPair D
  /-- Doctrine-derived pair represented by an edge-basis coordinate. -/
  edgePair : ∀ edge, EdgeBasis edge → ExtractionPair D
  /-- Doctrine-derived pair represented by a face-basis coordinate. -/
  facePair : ∀ face, FaceBasis face → ExtractionPair D
  /-- Edge-to-left-chart Atom correspondence. -/
  edgeLeftIndex : ∀ edge, EdgeBasis edge → ChartBasis (N.edgeLeft edge)
  /-- Edge-to-right-chart Atom correspondence. -/
  edgeRightIndex : ∀ edge, EdgeBasis edge → ChartBasis (N.edgeRight edge)
  /-- First face-boundary Atom correspondence. -/
  faceEdge0Index : ∀ face, FaceBasis face → EdgeBasis (N.faceEdge0 face)
  /-- Second face-boundary Atom correspondence. -/
  faceEdge1Index : ∀ face, FaceBasis face → EdgeBasis (N.faceEdge1 face)
  /-- Third face-boundary Atom correspondence. -/
  faceEdge2Index : ∀ face, FaceBasis face → EdgeBasis (N.faceEdge2 face)

namespace AtomIndexedNerveData

variable {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
variable {N : CoverNerve.{n}}

/--
The Atom-indexed nerve generated by the finite supports and their declared
incidence correspondences.
-/
def expandedNerve (I : AtomIndexedNerveData D N) : CoverNerve.{max n u} where
  Chart := Σ chart, I.ChartBasis chart
  EdgeComponent := Σ edge, I.EdgeBasis edge
  FaceComponent := Σ face, I.FaceBasis face
  edgeLeft := fun edge =>
    ⟨N.edgeLeft edge.1, I.edgeLeftIndex edge.1 edge.2⟩
  edgeRight := fun edge =>
    ⟨N.edgeRight edge.1, I.edgeRightIndex edge.1 edge.2⟩
  faceEdge0 := fun face =>
    ⟨N.faceEdge0 face.1, I.faceEdge0Index face.1 face.2⟩
  faceEdge1 := fun face =>
    ⟨N.faceEdge1 face.1, I.faceEdge1Index face.1 face.2⟩
  faceEdge2 := fun face =>
    ⟨N.faceEdge2 face.1, I.faceEdge2Index face.1 face.2⟩
  edgeOverlapComponent := fun edge => N.edgeOverlapComponent edge.1
  faceTripleOverlapComponent := fun face =>
    N.faceTripleOverlapComponent face.1
  edgeOverlapComponent_holds := fun edge =>
    N.edgeOverlapComponent_holds edge.1
  faceTripleOverlapComponent_holds := fun face =>
    N.faceTripleOverlapComponent_holds face.1

/-- Pair provenance of an expanded chart coordinate. -/
def chartPairAt (I : AtomIndexedNerveData D N)
    (chart : I.expandedNerve.Chart) : ExtractionPair D :=
  I.chartPair chart.1 chart.2

/-- Pair provenance of an expanded edge coordinate. -/
def edgePairAt (I : AtomIndexedNerveData D N)
    (edge : I.expandedNerve.EdgeComponent) : ExtractionPair D :=
  I.edgePair edge.1 edge.2

/-- Pair provenance of an expanded face coordinate. -/
def facePairAt (I : AtomIndexedNerveData D N)
    (face : I.expandedNerve.FaceComponent) : ExtractionPair D :=
  I.facePair face.1 face.2

/-- The expanded left endpoint is definitionally induced by `edgeLeftIndex`. -/
theorem edgeLeft_eq (I : AtomIndexedNerveData D N)
    (edge : I.expandedNerve.EdgeComponent) :
    I.expandedNerve.edgeLeft edge =
      ⟨N.edgeLeft edge.1, I.edgeLeftIndex edge.1 edge.2⟩ :=
  rfl

/-- The expanded right endpoint is definitionally induced by `edgeRightIndex`. -/
theorem edgeRight_eq (I : AtomIndexedNerveData D N)
    (edge : I.expandedNerve.EdgeComponent) :
    I.expandedNerve.edgeRight edge =
      ⟨N.edgeRight edge.1, I.edgeRightIndex edge.1 edge.2⟩ :=
  rfl

/-- Pair provenance at the expanded left endpoint is generated by `edgeLeftIndex`. -/
theorem edgeLeftPair_eq (I : AtomIndexedNerveData D N)
    (edge : I.expandedNerve.EdgeComponent) :
    I.chartPairAt (I.expandedNerve.edgeLeft edge) =
      I.chartPair (N.edgeLeft edge.1) (I.edgeLeftIndex edge.1 edge.2) :=
  rfl

/-- Pair provenance at the expanded right endpoint is generated by `edgeRightIndex`. -/
theorem edgeRightPair_eq (I : AtomIndexedNerveData D N)
    (edge : I.expandedNerve.EdgeComponent) :
    I.chartPairAt (I.expandedNerve.edgeRight edge) =
      I.chartPair (N.edgeRight edge.1) (I.edgeRightIndex edge.1 edge.2) :=
  rfl

/-- The first expanded face boundary is induced by `faceEdge0Index`. -/
theorem faceEdge0_eq (I : AtomIndexedNerveData D N)
    (face : I.expandedNerve.FaceComponent) :
    I.expandedNerve.faceEdge0 face =
      ⟨N.faceEdge0 face.1, I.faceEdge0Index face.1 face.2⟩ :=
  rfl

/-- The second expanded face boundary is induced by `faceEdge1Index`. -/
theorem faceEdge1_eq (I : AtomIndexedNerveData D N)
    (face : I.expandedNerve.FaceComponent) :
    I.expandedNerve.faceEdge1 face =
      ⟨N.faceEdge1 face.1, I.faceEdge1Index face.1 face.2⟩ :=
  rfl

/-- The third expanded face boundary is induced by `faceEdge2Index`. -/
theorem faceEdge2_eq (I : AtomIndexedNerveData D N)
    (face : I.expandedNerve.FaceComponent) :
    I.expandedNerve.faceEdge2 face =
      ⟨N.faceEdge2 face.1, I.faceEdge2Index face.1 face.2⟩ :=
  rfl

/-- Pair provenance on the first face boundary is generated by `faceEdge0Index`. -/
theorem faceEdge0Pair_eq (I : AtomIndexedNerveData D N)
    (face : I.expandedNerve.FaceComponent) :
    I.edgePairAt (I.expandedNerve.faceEdge0 face) =
      I.edgePair (N.faceEdge0 face.1) (I.faceEdge0Index face.1 face.2) :=
  rfl

/-- Pair provenance on the second face boundary is generated by `faceEdge1Index`. -/
theorem faceEdge1Pair_eq (I : AtomIndexedNerveData D N)
    (face : I.expandedNerve.FaceComponent) :
    I.edgePairAt (I.expandedNerve.faceEdge1 face) =
      I.edgePair (N.faceEdge1 face.1) (I.faceEdge1Index face.1 face.2) :=
  rfl

/-- Pair provenance on the third face boundary is generated by `faceEdge2Index`. -/
theorem faceEdge2Pair_eq (I : AtomIndexedNerveData D N)
    (face : I.expandedNerve.FaceComponent) :
    I.edgePairAt (I.expandedNerve.faceEdge2 face) =
      I.edgePair (N.faceEdge2 face.1) (I.faceEdge2Index face.1 face.2) :=
  rfl

/-- The expanded chart support is finite by construction. -/
noncomputable def chartFintype (I : AtomIndexedNerveData D N) :
    Fintype I.expandedNerve.Chart := by
  change Fintype (Σ chart : N.Chart, I.ChartBasis chart)
  letI : Fintype N.Chart := I.fintypeChart
  letI (chart : N.Chart) : Fintype (I.ChartBasis chart) :=
    I.chartBasisFintype chart
  infer_instance

/-- The expanded edge support is finite by construction. -/
noncomputable def edgeFintype (I : AtomIndexedNerveData D N) :
    Fintype I.expandedNerve.EdgeComponent := by
  change Fintype (Σ edge : N.EdgeComponent, I.EdgeBasis edge)
  letI : Fintype N.EdgeComponent := I.fintypeEdge
  letI (edge : N.EdgeComponent) : Fintype (I.EdgeBasis edge) :=
    I.edgeBasisFintype edge
  infer_instance

/-- The expanded face support is finite by construction. -/
noncomputable def faceFintype (I : AtomIndexedNerveData D N) :
    Fintype I.expandedNerve.FaceComponent := by
  change Fintype (Σ face : N.FaceComponent, I.FaceBasis face)
  letI : Fintype N.FaceComponent := I.fintypeFace
  letI (face : N.FaceComponent) : Fintype (I.FaceBasis face) :=
    I.faceBasisFintype face
  infer_instance

end AtomIndexedNerveData

/--
The coefficient complex on the Atom-indexed nerve generated by `indexing`.

Unlike the rejected annotation presentation, the domain of `all` is already the
expanded nerve, so its incidence differential is definitionally induced by the
declared Atom-support correspondences.
-/
structure AtomIndexedCoefficientComplex
    {U : AtomCarrier.{u}} (D : ExtractionDoctrine U)
    (family : DeclaredSemanticFamily D)
    (N : CoverNerve.{n}) (k : Type v) [Field k] where
  /-- Finite Atom supports and the maps that generate the expanded nerve. -/
  indexing : AtomIndexedNerveData D N
  /-- Reviewed incidence complex on that generated Atom-indexed nerve. -/
  all : FiniteNerveCochainComplex indexing.expandedNerve k

namespace AtomIndexedCoefficientComplex

variable {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
variable {family : DeclaredSemanticFamily D}
variable {N : CoverNerve.{n}} {k : Type v} [Field k]

/-- The chart-coordinate subspace generated by structurally classified pairs. -/
def structural0 (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k) :
    Submodule k P.all.C0 :=
  (coordinateSupport k fun chart =>
    family.Structural (P.indexing.chartPairAt chart)).comap
    P.all.zeroCochainCoordinates.toLinearMap

/-- The edge-coordinate subspace generated by structurally classified pairs. -/
def structural1 (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k) :
    Submodule k P.all.C1 :=
  (coordinateSupport k fun edge =>
    family.Structural (P.indexing.edgePairAt edge)).comap
    P.all.oneCochainCoordinates.toLinearMap

/-- The face-coordinate subspace generated by structurally classified pairs. -/
def structural2 (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k) :
    Submodule k P.all.C2 :=
  (coordinateSupport k fun face =>
    family.Structural (P.indexing.facePairAt face)).comap
    P.all.twoCochainCoordinates.toLinearMap

/-- Chart membership is concrete vanishing away from structural pair coordinates. -/
theorem mem_structural0_iff
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (c : P.all.C0) :
    c ∈ P.structural0 ↔
      ∀ chart, ¬ family.Structural (P.indexing.chartPairAt chart) →
        P.all.zeroCochainCoordinates c chart = 0 :=
  Iff.rfl

/-- Edge membership is concrete vanishing away from structural pair coordinates. -/
theorem mem_structural1_iff
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (c : P.all.C1) :
    c ∈ P.structural1 ↔
      ∀ edge, ¬ family.Structural (P.indexing.edgePairAt edge) →
        P.all.oneCochainCoordinates c edge = 0 :=
  Iff.rfl

/-- Face membership is concrete vanishing away from structural pair coordinates. -/
theorem mem_structural2_iff
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (c : P.all.C2) :
    c ∈ P.structural2 ↔
      ∀ face, ¬ family.Structural (P.indexing.facePairAt face) →
        P.all.twoCochainCoordinates c face = 0 :=
  Iff.rfl

/-- The chart structural subspace is the pullback of the span of structural basis vectors. -/
theorem structural0_eq_comap_span
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k) :
    P.structural0 =
      (Submodule.span k {f | ∃ chart,
        family.Structural (P.indexing.chartPairAt chart) ∧
          f = coordinateVector chart}).comap
        P.all.zeroCochainCoordinates.toLinearMap := by
  letI := P.indexing.chartFintype
  classical
  rw [structural0, coordinateSupport_eq_span]

/-- The edge structural subspace is the pullback of the span of structural basis vectors. -/
theorem structural1_eq_comap_span
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k) :
    P.structural1 =
      (Submodule.span k {f | ∃ edge,
        family.Structural (P.indexing.edgePairAt edge) ∧
          f = coordinateVector edge}).comap
        P.all.oneCochainCoordinates.toLinearMap := by
  letI := P.indexing.edgeFintype
  classical
  rw [structural1, coordinateSupport_eq_span]

/-- The face structural subspace is the pullback of the span of structural basis vectors. -/
theorem structural2_eq_comap_span
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k) :
    P.structural2 =
      (Submodule.span k {f | ∃ face,
        family.Structural (P.indexing.facePairAt face) ∧
          f = coordinateVector face}).comap
        P.all.twoCochainCoordinates.toLinearMap := by
  letI := P.indexing.faceFintype
  classical
  rw [structural2, coordinateSupport_eq_span]

/-- The underlying degree-zero differential remains the reviewed edge-incidence map. -/
theorem d0_coordinate
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (c : P.all.C0) (edge : P.indexing.expandedNerve.EdgeComponent) :
    P.all.oneCochainCoordinates (P.all.d0 c) edge =
      P.all.zeroCochainCoordinates c
          (P.indexing.expandedNerve.edgeRight edge) -
        P.all.zeroCochainCoordinates c
          (P.indexing.expandedNerve.edgeLeft edge) :=
  P.all.d0_eq_edgeIncidence c edge

/-- The underlying degree-one differential remains the reviewed face-incidence map. -/
theorem d1_coordinate
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (c : P.all.C1) (face : P.indexing.expandedNerve.FaceComponent) :
    P.all.twoCochainCoordinates (P.all.d1 c) face =
      P.all.oneCochainCoordinates c
          (P.indexing.expandedNerve.faceEdge0 face) -
        P.all.oneCochainCoordinates c
          (P.indexing.expandedNerve.faceEdge1 face) +
          P.all.oneCochainCoordinates c
            (P.indexing.expandedNerve.faceEdge2 face) :=
  P.all.d1_eq_faceIncidence c face

/--
The degree-zero differential uses exactly the two Atom-support correspondences
declared before construction of the expanded nerve.
-/
theorem d0_coordinate_from_atom_correspondence
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (c : P.all.C0) (edge : P.indexing.expandedNerve.EdgeComponent) :
    P.all.oneCochainCoordinates (P.all.d0 c) edge =
      P.all.zeroCochainCoordinates c
          ⟨N.edgeRight edge.1,
            P.indexing.edgeRightIndex edge.1 edge.2⟩ -
        P.all.zeroCochainCoordinates c
          ⟨N.edgeLeft edge.1,
            P.indexing.edgeLeftIndex edge.1 edge.2⟩ := by
  simpa [AtomIndexedNerveData.expandedNerve] using
    P.all.d0_eq_edgeIncidence c edge

/--
The degree-one differential uses exactly the three Atom-support
correspondences declared before construction of the expanded nerve.
-/
theorem d1_coordinate_from_atom_correspondence
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (c : P.all.C1) (face : P.indexing.expandedNerve.FaceComponent) :
    P.all.twoCochainCoordinates (P.all.d1 c) face =
      P.all.oneCochainCoordinates c
          ⟨N.faceEdge0 face.1,
            P.indexing.faceEdge0Index face.1 face.2⟩ -
        P.all.oneCochainCoordinates c
          ⟨N.faceEdge1 face.1,
            P.indexing.faceEdge1Index face.1 face.2⟩ +
          P.all.oneCochainCoordinates c
            ⟨N.faceEdge2 face.1,
              P.indexing.faceEdge2Index face.1 face.2⟩ := by
  simpa [AtomIndexedNerveData.expandedNerve] using
    P.all.d1_eq_faceIncidence c face

/--
Condition E: the actual incidence differentials preserve structural support.

It contains no exactness, vanishing, cohomology, or injectivity assertion.
-/
def ConditionE
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k) : Prop :=
  P.structural0 ≤ P.structural1.comap P.all.d0 ∧
    P.structural1 ≤ P.structural2.comap P.all.d1

/-- Condition E is exactly the two differential-closure statements. -/
theorem conditionE_iff
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k) :
    P.ConditionE ↔
      (∀ c ∈ P.structural0, P.all.d0 c ∈ P.structural1) ∧
        (∀ c ∈ P.structural1, P.all.d1 c ∈ P.structural2) :=
  Iff.rfl

/-- The reviewed all-phase nerve complex, exposed through the common three-term API. -/
def allComplex
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k) :
    ThreeCochainComplex k where
  C0 := P.all.C0
  C1 := P.all.C1
  C2 := P.all.C2
  d0 := P.all.d0
  d1 := P.all.d1
  d1_comp_d0 := P.all.d1_comp_d0

/-- Degree-zero structural differential obtained from Condition E. -/
def structuralD0
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE) : P.structural0 →ₗ[k] P.structural1 where
  toFun c := ⟨P.all.d0 c.1, hE.1 c.2⟩
  map_add' x y := by ext; simp
  map_smul' scalar x := by ext; simp

/-- Degree-one structural differential obtained from Condition E. -/
def structuralD1
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE) : P.structural1 →ₗ[k] P.structural2 where
  toFun c := ⟨P.all.d1 c.1, hE.2 c.2⟩
  map_add' x y := by ext; simp
  map_smul' scalar x := by ext; simp

/-- The canonical structural subcomplex cut out by the derived phase support. -/
def structuralComplex
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE) : ThreeCochainComplex k where
  C0 := P.structural0
  C1 := P.structural1
  C2 := P.structural2
  d0 := P.structuralD0 hE
  d1 := P.structuralD1 hE
  d1_comp_d0 := by
    intro c
    apply Subtype.ext
    exact P.all.d1_comp_d0 c.1

/-- Degree-zero differential induced on the semantic quotient. -/
def semanticD0
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE) :
    (P.all.C0 ⧸ P.structural0) →ₗ[k] (P.all.C1 ⧸ P.structural1) :=
  Submodule.mapQ P.structural0 P.structural1 P.all.d0 hE.1

/-- Degree-one differential induced on the semantic quotient. -/
def semanticD1
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE) :
    (P.all.C1 ⧸ P.structural1) →ₗ[k] (P.all.C2 ⧸ P.structural2) :=
  Submodule.mapQ P.structural1 P.structural2 P.all.d1 hE.2

/-- The canonical quotient complex `F_sem = F_all / F_struct`. -/
def semanticComplex
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE) : ThreeCochainComplex k where
  C0 := P.all.C0 ⧸ P.structural0
  C1 := P.all.C1 ⧸ P.structural1
  C2 := P.all.C2 ⧸ P.structural2
  d0 := P.semanticD0 hE
  d1 := P.semanticD1 hE
  d1_comp_d0 := by
    intro c
    obtain ⟨c, rfl⟩ := P.structural0.mkQ_surjective c
    change P.structural2.mkQ (P.all.d1 (P.all.d0 c)) = 0
    rw [P.all.d1_comp_d0]
    exact map_zero P.structural2.mkQ

/-- Canonical inclusion of the structural subcomplex into the all-phase complex. -/
def inclusion
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE) :
    ThreeCochainComplex.Hom (P.structuralComplex hE) P.allComplex where
  f0 := P.structural0.subtype
  f1 := P.structural1.subtype
  f2 := P.structural2.subtype
  comm0 _ := rfl
  comm1 _ := rfl

/-- Canonical projection from the all-phase complex to the semantic quotient. -/
def projection
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE) :
    ThreeCochainComplex.Hom P.allComplex (P.semanticComplex hE) where
  f0 := P.structural0.mkQ
  f1 := P.structural1.mkQ
  f2 := P.structural2.mkQ
  comm0 _ := rfl
  comm1 _ := rfl

/-- The canonical inclusion followed by projection is zero in degree zero. -/
theorem projection_inclusion_zero0
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE)
    (c : (P.structuralComplex hE).C0) :
    (P.projection hE).f0 ((P.inclusion hE).f0 c) = 0 := by
  change P.structural0.mkQ c.1 = 0
  exact (Submodule.Quotient.mk_eq_zero P.structural0).2 c.2

/-- The canonical inclusion followed by projection is zero in degree one. -/
theorem projection_inclusion_zero1
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE)
    (c : (P.structuralComplex hE).C1) :
    (P.projection hE).f1 ((P.inclusion hE).f1 c) = 0 := by
  change P.structural1.mkQ c.1 = 0
  exact (Submodule.Quotient.mk_eq_zero P.structural1).2 c.2

/-- The canonical inclusion followed by projection is zero in degree two. -/
theorem projection_inclusion_zero2
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE)
    (c : (P.structuralComplex hE).C2) :
    (P.projection hE).f2 ((P.inclusion hE).f2 c) = 0 := by
  change P.structural2.mkQ c.1 = 0
  exact (Submodule.Quotient.mk_eq_zero P.structural2).2 c.2

/--
The canonical structural inclusion and semantic quotient form a short exact
sequence in every degree.

Condition E is used to construct both endpoint complexes and both cochain maps;
the injectivity, exactness, and surjectivity clauses are then derived.
-/
theorem degreewise_shortExact
    (P : AtomIndexedCoefficientComplex.{u, n, v, w} D family N k)
    (hE : P.ConditionE) :
    (Function.Injective (P.inclusion hE).f0 ∧
      Function.Exact (P.inclusion hE).f0 (P.projection hE).f0 ∧
      Function.Surjective (P.projection hE).f0) ∧
    (Function.Injective (P.inclusion hE).f1 ∧
      Function.Exact (P.inclusion hE).f1 (P.projection hE).f1 ∧
      Function.Surjective (P.projection hE).f1) ∧
    (Function.Injective (P.inclusion hE).f2 ∧
      Function.Exact (P.inclusion hE).f2 (P.projection hE).f2 ∧
      Function.Surjective (P.projection hE).f2) := by
  constructor
  · constructor
    · change Function.Injective P.structural0.subtype
      exact P.structural0.injective_subtype
    constructor
    · change Function.Exact P.structural0.subtype P.structural0.mkQ
      exact LinearMap.exact_subtype_mkQ P.structural0
    · change Function.Surjective P.structural0.mkQ
      exact P.structural0.mkQ_surjective
  constructor
  · constructor
    · change Function.Injective P.structural1.subtype
      exact P.structural1.injective_subtype
    constructor
    · change Function.Exact P.structural1.subtype P.structural1.mkQ
      exact LinearMap.exact_subtype_mkQ P.structural1
    · change Function.Surjective P.structural1.mkQ
      exact P.structural1.mkQ_surjective
  · constructor
    · change Function.Injective P.structural2.subtype
      exact P.structural2.injective_subtype
    constructor
    · change Function.Exact P.structural2.subtype P.structural2.mkQ
      exact LinearMap.exact_subtype_mkQ P.structural2
    · change Function.Surjective P.structural2.mkQ
      exact P.structural2.mkQ_surjective

end AtomIndexedCoefficientComplex

end AAT.AG.TwoPhase

#assert_standard_axioms_only AAT.AG.TwoPhase
