import Formal.AG.Site.Coverage
import Mathlib.CategoryTheory.Category.Preorder
import Mathlib.CategoryTheory.Sites.Coverage

namespace AAT.AG
namespace Site

universe u

open CategoryTheory

/--
II.定義7.1: Mathlib-facing object wrapper for the thin category attached to
the selected context preorder.

The wrapper keeps the AAT context preorder as explicit data while allowing
Mathlib's preorder category instance to supply morphisms, sieves, coverages,
and Grothendieck topologies.
-/
structure ContextCategoryObject {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    (C : ContextPreorderCategory A) where
  ctx : ArchCtx A

namespace ContextCategoryObject

instance {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    (C : ContextPreorderCategory A) : Preorder (ContextCategoryObject C) where
  le X Y := C.le X.ctx Y.ctx
  le_refl X := C.refl X.ctx
  le_trans _X _Y _Z hXY hYZ := C.trans hXY hYZ

/-- II.定義7.1: wrap an AAT context as an object of the Mathlib thin category. -/
def of {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    (C : ContextPreorderCategory A) (W : ArchCtx A) :
    ContextCategoryObject C where
  ctx := W

end ContextCategoryObject

/--
II.定義7.1: a Mathlib-facing admissible family over a fixed base object.

This is the same data as `CoverageFamily`, but indexed by the wrapped base
object so it can be converted directly to a `Presieve` on the thin category.
-/
structure AATCoverageFamily {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} (R : CoverageRequirements A LU Sig)
    (P : ContextOverlapPullback C) (base : ContextCategoryObject C) where
  Index : Type u
  patch : Index -> ArchCtx A
  inclusion : ∀ i : Index, C.Hom (patch i) base.ctx
  admissible :
    AdmissibleCover R P
      { base := base.ctx
        Index := Index
        patch := patch
        inclusion := inclusion }

namespace AATCoverageFamily

/-- II.定義7.1: recover the AAT-native coverage family. -/
def toCoverageFamily {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} {R : CoverageRequirements A LU Sig}
    {P : ContextOverlapPullback C} {base : ContextCategoryObject C}
    (F : AATCoverageFamily R P base) : CoverageFamily C where
  base := base.ctx
  Index := F.Index
  patch := F.patch
  inclusion := F.inclusion

/-- II.定義7.1: convert an admissible AAT family to a Mathlib presieve. -/
def presieve {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} {R : CoverageRequirements A LU Sig}
    {P : ContextOverlapPullback C} {base : ContextCategoryObject C}
    (F : AATCoverageFamily R P base) : Presieve base :=
  Presieve.ofArrows
    (fun i : F.Index => ContextCategoryObject.of C (F.patch i))
    (fun i : F.Index => homOfLE (F.inclusion i))

/-- II.定義7.1: the presieve remembers the underlying admissible cover. -/
theorem admissibleCover {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} {R : CoverageRequirements A LU Sig}
    {P : ContextOverlapPullback C} {base : ContextCategoryObject C}
    (F : AATCoverageFamily R P base) :
    AdmissibleCover R P F.toCoverageFamily :=
  F.admissible

end AATCoverageFamily

/--
II.定義7.1: AAT admissible precoverage generated by admissible cover families.

This is the AAT-primary coverage layer. The generated Grothendieck topology is
obtained from this precoverage; the Mathlib `Coverage` bridge below records the
extra pullback/base-change hypotheses needed by `CategoryTheory.Coverage`.
-/
def admissiblePrecoverage {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} (R : CoverageRequirements A LU Sig)
    (P : ContextOverlapPullback C) :
    Precoverage (ContextCategoryObject C) where
  coverings base := { S | ∃ F : AATCoverageFamily R P base, S = F.presieve }

/--
II.定義7.1: `J_U`, the Grothendieck topology generated by AAT admissible
cover families.
-/
def AATGrothendieckTopology {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} (R : CoverageRequirements A LU Sig)
    (P : ContextOverlapPullback C) :
    GrothendieckTopology (ContextCategoryObject C) :=
  (admissiblePrecoverage R P).toGrothendieck

namespace AATGrothendieckTopology

/-- II.定義7.1: identity/top covers are in `J_U`. -/
theorem top_mem {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} (R : CoverageRequirements A LU Sig)
    (P : ContextOverlapPullback C) (base : ContextCategoryObject C) :
    (⊤ : Sieve base) ∈ AATGrothendieckTopology R P base :=
  (AATGrothendieckTopology R P).top_mem base

/-- II.定義7.1: `J_U` is stable under base change. -/
theorem pullback_stable {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} (R : CoverageRequirements A LU Sig)
    (P : ContextOverlapPullback C) {base loc : ContextCategoryObject C}
    (f : loc ⟶ base) {S : Sieve base}
    (hS : S ∈ AATGrothendieckTopology R P base) :
    S.pullback f ∈ AATGrothendieckTopology R P loc :=
  (AATGrothendieckTopology R P).pullback_stable f hS

/-- II.定義7.1: `J_U` satisfies local character / transitivity. -/
theorem transitive {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} (R : CoverageRequirements A LU Sig)
    (P : ContextOverlapPullback C) {base : ContextCategoryObject C}
    {S T : Sieve base} (hS : S ∈ AATGrothendieckTopology R P base)
    (hT : ∀ ⦃loc : ContextCategoryObject C⦄ ⦃f : loc ⟶ base⦄,
      S f -> T.pullback f ∈ AATGrothendieckTopology R P loc) :
    T ∈ AATGrothendieckTopology R P base :=
  (AATGrothendieckTopology R P).transitive hS T hT

/-- II.定義7.1: generated admissible families are covers in `J_U`. -/
theorem generate_mem {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} {R : CoverageRequirements A LU Sig}
    {P : ContextOverlapPullback C} {base : ContextCategoryObject C}
    (F : AATCoverageFamily R P base) :
    Sieve.generate F.presieve ∈ AATGrothendieckTopology R P base :=
  Precoverage.generate_mem_toGrothendieck ⟨F, rfl⟩

/--
II.定義7.1 / R4 Mathlib bridge: when the AAT admissible precoverage has the
pullbacks and base-change stability required by Mathlib, the generated `J_U`
agrees with `Coverage.toGrothendieck`.
-/
theorem eq_coverage_toGrothendieck {U : AtomCarrier.{u}} {A : ArchitectureObject U}
    {C : ContextPreorderCategory A} {LU : LawUniverse U}
    {Sig : ArchitectureSignature U} (R : CoverageRequirements A LU Sig)
    (P : ContextOverlapPullback C)
    [Precoverage.HasPullbacks (admissiblePrecoverage R P)]
    [Precoverage.IsStableUnderBaseChange (admissiblePrecoverage R P)] :
    AATGrothendieckTopology R P =
      (admissiblePrecoverage R P).toCoverage.toGrothendieck := by
  rw [AATGrothendieckTopology, Precoverage.toGrothendieck_toCoverage]

end AATGrothendieckTopology

end Site
end AAT.AG
