import Formal.Arch.Finite
import Formal.Arch.Operation

namespace Formal.Arch

universe u

/-- Two architecture graphs have the same dependency edge relation. -/
def EdgeEquivalent {C : Type u} (G H : ArchGraph C) : Prop :=
  ∀ c d : C, G.edge c d ↔ H.edge c d

namespace EdgeEquivalent

/-- Edge equivalence is reflexive. -/
theorem refl {C : Type u} (G : ArchGraph C) : EdgeEquivalent G G :=
  fun _ _ => Iff.rfl

/-- Edge equivalence is symmetric. -/
theorem symm {C : Type u} {G H : ArchGraph C}
    (h : EdgeEquivalent G H) : EdgeEquivalent H G :=
  fun c d => (h c d).symm

/-- Edge equivalence is transitive. -/
theorem trans {C : Type u} {G H K : ArchGraph C}
    (hGH : EdgeEquivalent G H) (hHK : EdgeEquivalent H K) :
    EdgeEquivalent G K :=
  fun c d => Iff.trans (hGH c d) (hHK c d)

end EdgeEquivalent

/--
Concrete graph-level transformation kernel for Architecture Calculus operations.

This kernel is deliberately finite: every source and target is a
`FiniteArchGraph`, so graph transformations stay inside the proof-carrying
measurement universe used by executable metrics.
-/
structure ConcreteGraphOperation (C : Type u) where
  kind : ArchitectureOperationKind
  source : FiniteArchGraph C
  target : FiniteArchGraph C
  precondition : Prop
  nonConclusion : Prop

namespace ConcreteGraphOperation

/-- The proof-obligation package generated by a concrete graph operation. -/
def generatedProofObligation {C : Type u}
    (op : ConcreteGraphOperation C) :
    OperationProofObligation (FiniteArchGraph C) PUnit :=
  OperationProofObligation.ofKind op.kind
    { formalUniverse := True
      requiredLaws := True
      invariantFamily := fun _ => True
      witnessUniverse := fun _ => True
      coverageAssumptions := True
      exactnessAssumptions := True
      operationPreconditions := op.precondition
      conclusion := True
      nonConclusions := op.nonConclusion }
    op.precondition
    op.nonConclusion

/--
Connect a concrete graph operation to the existing `ArchitectureOperation`
schema.

The witness family is intentionally trivial here: graph-level preservation
theorems are proved separately on the concrete source and target graphs.
-/
def toArchitectureOperation {C : Type u}
    (op : ConcreteGraphOperation C) :
    ArchitectureOperation (FiniteArchGraph C) PUnit PUnit where
  kind := op.kind
  source := op.source
  target := op.target
  precondition := op.precondition
  generatedProofObligation := op.generatedProofObligation
  generatedProofObligationKind := rfl
  sourceWitness := fun _ => True
  targetWitness := fun _ => True
  witnessMap := id
  witnessMappingSound := by
    intro _ _h
    trivial
  nonConclusion := op.nonConclusion

/-- Concrete operations preserve their operation tag when embedded in the schema. -/
theorem toArchitectureOperation_kind {C : Type u}
    (op : ConcreteGraphOperation C) :
    op.toArchitectureOperation.kind = op.kind :=
  rfl

/-- Concrete operations preserve their source when embedded in the schema. -/
theorem toArchitectureOperation_source {C : Type u}
    (op : ConcreteGraphOperation C) :
    op.toArchitectureOperation.source = op.source :=
  rfl

/-- Concrete operations preserve their target when embedded in the schema. -/
theorem toArchitectureOperation_target {C : Type u}
    (op : ConcreteGraphOperation C) :
    op.toArchitectureOperation.target = op.target :=
  rfl

end ConcreteGraphOperation

namespace ArchGraph

/-- Reverse every dependency edge in a graph. -/
def reverse {C : Type u} (G : ArchGraph C) : ArchGraph C where
  edge c d := G.edge d c

/-- Membership in a reversed graph is exactly the opposite edge of the source graph. -/
theorem reverse_edge_iff {C : Type u} (G : ArchGraph C) {c d : C} :
    (G.reverse).edge c d ↔ G.edge d c :=
  Iff.rfl

/-- Reversing twice restores the original edge relation. -/
theorem reverse_reverse_edge_iff {C : Type u} (G : ArchGraph C) {c d : C} :
    (G.reverse.reverse).edge c d ↔ G.edge c d :=
  Iff.rfl

/-- Compose two graphs on the same component type by taking edge union. -/
def compose {C : Type u} (G H : ArchGraph C) : ArchGraph C where
  edge c d := G.edge c d ∨ H.edge c d

/-- Edges of a composed graph are exactly edges from either input graph. -/
theorem compose_edge_iff {C : Type u} (G H : ArchGraph C) {c d : C} :
    (G.compose H).edge c d ↔ G.edge c d ∨ H.edge c d :=
  Iff.rfl

/-- The left operand embeds into graph-level composition. -/
theorem left_edgeSubset_compose {C : Type u} (G H : ArchGraph C) :
    EdgeSubset G (G.compose H) :=
  fun hEdge => Or.inl hEdge

/-- The right operand embeds into graph-level composition. -/
theorem right_edgeSubset_compose {C : Type u} (G H : ArchGraph C) :
    EdgeSubset H (G.compose H) :=
  fun hEdge => Or.inr hEdge

/-- Graph-level edge-union composition is associative up to edge equivalence. -/
theorem compose_assoc_edgeEquivalent {C : Type u} (G H K : ArchGraph C) :
    EdgeEquivalent ((G.compose H).compose K) (G.compose (H.compose K)) := by
  intro c d
  constructor
  · intro hEdge
    rcases hEdge with hLeft | hK
    · rcases hLeft with hG | hH
      · exact Or.inl hG
      · exact Or.inr (Or.inl hH)
    · exact Or.inr (Or.inr hK)
  · intro hEdge
    rcases hEdge with hG | hRight
    · exact Or.inl (Or.inl hG)
    · rcases hRight with hH | hK
      · exact Or.inl (Or.inr hH)
      · exact Or.inr hK

/--
Graph-level replacement chooses the replacement graph.

Preservation claims are kept separate and must be proved from an explicit
`EdgeEquivalent` precondition.
-/
def replace {C : Type u} (_G H : ArchGraph C) : ArchGraph C :=
  H

/-- Edges of a replacement graph are exactly the replacement target edges. -/
theorem replace_edge_iff {C : Type u} (G H : ArchGraph C) {c d : C} :
    (G.replace H).edge c d ↔ H.edge c d :=
  Iff.rfl

/-- Edge-equivalent replacement preserves the source edge relation. -/
theorem replace_preserves_edges_of_edgeEquivalent {C : Type u}
    (G H : ArchGraph C) (hEquiv : EdgeEquivalent G H) {c d : C} :
    (G.replace H).edge c d ↔ G.edge c d :=
  (hEquiv c d).symm

end ArchGraph

namespace FiniteArchGraph

/-- Reverse every dependency edge while keeping the same finite component universe. -/
def reverse {C : Type u} (FG : FiniteArchGraph C) : FiniteArchGraph C where
  graph := FG.graph.reverse
  componentUniverse :=
    { components := FG.components
      nodup := FG.nodup_components
      covers := FG.covers_components
      edgeClosed := by
        intro c d hEdge
        have hClosed := FG.edgeClosed_components hEdge
        exact ⟨hClosed.2, hClosed.1⟩ }

/-- Edges of the reversed finite graph are exactly source edges in the opposite direction. -/
theorem reverse_edge_iff {C : Type u} (FG : FiniteArchGraph C) {c d : C} :
    FG.reverse.graph.edge c d ↔ FG.graph.edge d c :=
  Iff.rfl

/-- Reversing a finite graph twice restores the original edge relation. -/
theorem reverse_reverse_edge_iff {C : Type u} (FG : FiniteArchGraph C) {c d : C} :
    FG.reverse.reverse.graph.edge c d ↔ FG.graph.edge c d :=
  Iff.rfl

/--
Protect is the graph-level identity transform at this kernel layer.

Runtime protection parameters such as fallback, queue, or circuit breaker labels
belong to later runtime-semantic packages; the finite static graph is preserved.
-/
def protect {C : Type u} (FG : FiniteArchGraph C) : FiniteArchGraph C :=
  FG

/-- The graph-level protect kernel preserves exactly the source edge relation. -/
theorem protect_edge_iff {C : Type u} (FG : FiniteArchGraph C) {c d : C} :
    FG.protect.graph.edge c d ↔ FG.graph.edge c d :=
  Iff.rfl

/--
Compose finite graphs by edge union while retaining the source graph's finite
measurement universe.

The retained universe is full over the component type, so it also covers edges
introduced by the right operand.
-/
def compose {C : Type u} (FG FH : FiniteArchGraph C) : FiniteArchGraph C where
  graph := FG.graph.compose FH.graph
  componentUniverse :=
    { components := FG.components
      nodup := FG.nodup_components
      covers := FG.covers_components
      edgeClosed := ComponentUniverse.edgeClosed_of_covers FG.covers_components }

/-- Edges of a composed finite graph are exactly edges from either input graph. -/
theorem compose_edge_iff {C : Type u} (FG FH : FiniteArchGraph C) {c d : C} :
    (FG.compose FH).graph.edge c d ↔
      FG.graph.edge c d ∨ FH.graph.edge c d :=
  Iff.rfl

/-- The source finite graph embeds into graph-level finite composition. -/
theorem left_edgeSubset_compose {C : Type u} (FG FH : FiniteArchGraph C) :
    EdgeSubset FG.graph (FG.compose FH).graph :=
  ArchGraph.left_edgeSubset_compose FG.graph FH.graph

/-- The right finite graph embeds into graph-level finite composition. -/
theorem right_edgeSubset_compose {C : Type u} (FG FH : FiniteArchGraph C) :
    EdgeSubset FH.graph (FG.compose FH).graph :=
  ArchGraph.right_edgeSubset_compose FG.graph FH.graph

/-- Finite edge-union composition is associative up to edge equivalence. -/
theorem compose_assoc_edgeEquivalent {C : Type u}
    (FG FH FK : FiniteArchGraph C) :
    EdgeEquivalent ((FG.compose FH).compose FK).graph
      (FG.compose (FH.compose FK)).graph :=
  ArchGraph.compose_assoc_edgeEquivalent FG.graph FH.graph FK.graph

/--
Replace a finite graph by another finite graph over the same component type.

Preservation is intentionally relative to explicit equivalence assumptions.
-/
def replace {C : Type u} (_FG FH : FiniteArchGraph C) : FiniteArchGraph C :=
  FH

/-- Edges of a finite replacement are exactly the replacement target edges. -/
theorem replace_edge_iff {C : Type u} (FG FH : FiniteArchGraph C) {c d : C} :
    (FG.replace FH).graph.edge c d ↔ FH.graph.edge c d :=
  Iff.rfl

/-- Edge-equivalent finite replacement preserves the source edge relation. -/
theorem replace_preserves_edges_of_edgeEquivalent {C : Type u}
    (FG FH : FiniteArchGraph C) (hEquiv : EdgeEquivalent FG.graph FH.graph)
    {c d : C} :
    (FG.replace FH).graph.edge c d ↔ FG.graph.edge c d :=
  (hEquiv c d).symm

end FiniteArchGraph

namespace ConcreteGraphOperation

/-- Concrete `reverse` graph operation on a finite architecture graph. -/
def reverse {C : Type u} (FG : FiniteArchGraph C) :
    ConcreteGraphOperation C where
  kind := ArchitectureOperationKind.reverse
  source := FG
  target := FG.reverse
  precondition := True
  nonConclusion := True

/-- Concrete `protect` graph operation on a finite architecture graph. -/
def protect {C : Type u} (FG : FiniteArchGraph C) :
    ConcreteGraphOperation C where
  kind := ArchitectureOperationKind.protect
  source := FG
  target := FG.protect
  precondition := True
  nonConclusion := True

/-- Concrete `compose` graph operation using finite edge union. -/
def compose {C : Type u} (FG FH : FiniteArchGraph C) :
    ConcreteGraphOperation C where
  kind := ArchitectureOperationKind.compose
  source := FG
  target := FG.compose FH
  precondition := True
  nonConclusion := True

/--
Concrete `replace` graph operation with edge equivalence as an explicit
precondition.
-/
def replace {C : Type u} (FG FH : FiniteArchGraph C) :
    ConcreteGraphOperation C where
  kind := ArchitectureOperationKind.replace
  source := FG
  target := FG.replace FH
  precondition := EdgeEquivalent FG.graph FH.graph
  nonConclusion := True

/-- The concrete reverse operation is connected to the `reverse` operation kind. -/
theorem reverse_kind {C : Type u} (FG : FiniteArchGraph C) :
    (reverse FG).kind = ArchitectureOperationKind.reverse :=
  rfl

/-- The concrete protect operation is connected to the `protect` operation kind. -/
theorem protect_kind {C : Type u} (FG : FiniteArchGraph C) :
    (protect FG).kind = ArchitectureOperationKind.protect :=
  rfl

/-- The concrete compose operation is connected to the `compose` operation kind. -/
theorem compose_kind {C : Type u} (FG FH : FiniteArchGraph C) :
    (compose FG FH).kind = ArchitectureOperationKind.compose :=
  rfl

/-- The concrete replace operation is connected to the `replace` operation kind. -/
theorem replace_kind {C : Type u} (FG FH : FiniteArchGraph C) :
    (replace FG FH).kind = ArchitectureOperationKind.replace :=
  rfl

/-- The schema embedding of concrete reverse keeps the `reverse` operation kind. -/
theorem reverse_schema_kind {C : Type u} (FG : FiniteArchGraph C) :
    (reverse FG).toArchitectureOperation.kind =
      ArchitectureOperationKind.reverse :=
  rfl

/-- The schema embedding of concrete protect keeps the `protect` operation kind. -/
theorem protect_schema_kind {C : Type u} (FG : FiniteArchGraph C) :
    (protect FG).toArchitectureOperation.kind =
      ArchitectureOperationKind.protect :=
  rfl

/-- The schema embedding of concrete compose keeps the `compose` operation kind. -/
theorem compose_schema_kind {C : Type u} (FG FH : FiniteArchGraph C) :
    (compose FG FH).toArchitectureOperation.kind =
      ArchitectureOperationKind.compose :=
  rfl

/-- The schema embedding of concrete replace keeps the `replace` operation kind. -/
theorem replace_schema_kind {C : Type u} (FG FH : FiniteArchGraph C) :
    (replace FG FH).toArchitectureOperation.kind =
      ArchitectureOperationKind.replace :=
  rfl

end ConcreteGraphOperation

end Formal.Arch
