namespace Formal.Arch

universe u v w

/--
The Chapter 3 operation catalog stabilized for the Architecture Calculus core.

These tags classify theorem packages; they do not by themselves assert that an
operation preserves, improves, or removes any obstruction.
-/
inductive ArchitectureOperationKind where
  | compose
  | refine
  | abstract
  | replace
  | split
  | merge
  | isolate
  | protect
  | migrate
  | reverse
  | contract
  | repair
  | synthesize
  deriving DecidableEq, Repr

namespace ArchitectureOperationKind

/-- Human-readable operation tag used by documentation-facing theorem packages. -/
def label : ArchitectureOperationKind -> String
  | compose => "compose"
  | refine => "refine"
  | abstract => "abstract"
  | replace => "replace"
  | split => "split"
  | merge => "merge"
  | isolate => "isolate"
  | protect => "protect"
  | migrate => "migrate"
  | reverse => "reverse"
  | contract => "contract"
  | repair => "repair"
  | synthesize => "synthesize"

end ArchitectureOperationKind

/--
Minimal proof-obligation schema for an architecture operation theorem package.

`nonConclusions` is an explicit field: a theorem package must record what it
does not claim, such as runtime or semantic flatness outside the selected
universe.
-/
structure ProofObligation (State : Type u) (Witness : Type v) where
  formalUniverse : Prop
  requiredLaws : Prop
  invariantFamily : State -> Prop
  witnessUniverse : Witness -> Prop
  coverageAssumptions : Prop
  exactnessAssumptions : Prop
  operationPreconditions : Prop
  conclusion : Prop
  nonConclusions : Prop

namespace ProofObligation

variable {State : Type u} {Witness : Type v}

/-- The assumptions that must be visible before the obligation conclusion is used. -/
def AssumptionsHold (P : ProofObligation State Witness) : Prop :=
  P.formalUniverse ∧
  P.requiredLaws ∧
  P.coverageAssumptions ∧
  P.exactnessAssumptions ∧
  P.operationPreconditions

/-- An obligation is discharged when its visible assumptions imply its conclusion. -/
def Discharged (P : ProofObligation State Witness) : Prop :=
  AssumptionsHold P -> P.conclusion

/-- The theorem package explicitly records claims it does not make. -/
def RecordsNonConclusions (P : ProofObligation State Witness) : Prop :=
  P.nonConclusions

/-- A direct conclusion proof discharges the proof obligation. -/
theorem discharged_of_conclusion (P : ProofObligation State Witness)
    (h : P.conclusion) : P.Discharged := by
  intro _hAssumptions
  exact h

end ProofObligation

/--
Operation-specific proof-obligation package.

This records the operation family together with the precondition and
non-conclusion clauses that are generated for that operation.
-/
structure OperationProofObligation (State : Type u) (Witness : Type v) where
  kind : ArchitectureOperationKind
  obligation : ProofObligation State Witness
  precondition : Prop
  nonConclusion : Prop

namespace OperationProofObligation

variable {State : Type u} {Witness : Type v}

/-- Build an operation proof-obligation package for a selected operation kind. -/
def ofKind (kind : ArchitectureOperationKind)
    (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  { kind
    obligation
    precondition
    nonConclusion }

/-- Proof-obligation package generated by a `compose` operation. -/
def compose (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.compose obligation precondition nonConclusion

/-- Proof-obligation package generated by a `refine` operation. -/
def refine (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.refine obligation precondition nonConclusion

/-- Proof-obligation package generated by an `abstract` operation. -/
def abstract (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.abstract obligation precondition nonConclusion

/-- Proof-obligation package generated by a `replace` operation. -/
def replace (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.replace obligation precondition nonConclusion

/-- Proof-obligation package generated by a `split` operation. -/
def split (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.split obligation precondition nonConclusion

/-- Proof-obligation package generated by a `merge` operation. -/
def merge (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.merge obligation precondition nonConclusion

/-- Proof-obligation package generated by an `isolate` operation. -/
def isolate (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.isolate obligation precondition nonConclusion

/-- Proof-obligation package generated by a `protect` operation. -/
def protect (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.protect obligation precondition nonConclusion

/-- Proof-obligation package generated by a `migrate` operation. -/
def migrate (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.migrate obligation precondition nonConclusion

/-- Proof-obligation package generated by a `reverse` operation. -/
def reverse (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.reverse obligation precondition nonConclusion

/-- Proof-obligation package generated by a `contract` operation. -/
def contract (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.contract obligation precondition nonConclusion

/-- Proof-obligation package generated by a `repair` operation. -/
def repair (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.repair obligation precondition nonConclusion

/-- Proof-obligation package generated by a `synthesize` operation. -/
def synthesize (obligation : ProofObligation State Witness)
    (precondition nonConclusion : Prop) :
    OperationProofObligation State Witness :=
  ofKind ArchitectureOperationKind.synthesize obligation precondition nonConclusion

end OperationProofObligation

/--
Minimal architecture operation schema with one-way witness mapping.

The direction is reflective: if an obstruction witness is observed after the
operation, `witnessMap` transports it back to a pre-operation witness family.
-/
structure ArchitectureOperation
    (State : Type u) (BeforeWitness : Type v) (AfterWitness : Type w) where
  kind : ArchitectureOperationKind
  source : State
  target : State
  precondition : Prop
  generatedProofObligation : OperationProofObligation State AfterWitness
  generatedProofObligationKind : generatedProofObligation.kind = kind
  sourceWitness : BeforeWitness -> Prop
  targetWitness : AfterWitness -> Prop
  witnessMap : AfterWitness -> BeforeWitness
  witnessMappingSound :
    ∀ w, targetWitness w -> sourceWitness (witnessMap w)
  nonConclusion : Prop

namespace ArchitectureOperation

variable {State : Type u} {BeforeWitness : Type v} {AfterWitness : Type w}

/-- The generated obligation associated with an operation. -/
def GeneratedObligation
    (op : ArchitectureOperation State BeforeWitness AfterWitness) :
    OperationProofObligation State AfterWitness :=
  op.generatedProofObligation

/-- The generated proof obligation is tagged with the operation kind. -/
theorem generatedObligation_kind
    (op : ArchitectureOperation State BeforeWitness AfterWitness) :
    op.generatedProofObligation.kind = op.kind :=
  op.generatedProofObligationKind

/-- Visible preconditions from the operation and its generated obligation. -/
def PreconditionsHold
    (op : ArchitectureOperation State BeforeWitness AfterWitness) : Prop :=
  op.precondition ∧ op.generatedProofObligation.precondition

/--
One-way witness mapping soundness.

If a selected post-operation witness is present, the operation maps it to a
selected pre-operation witness.
-/
theorem witnessMapping_sound
    (op : ArchitectureOperation State BeforeWitness AfterWitness)
    {w : AfterWitness} (h : op.targetWitness w) :
    op.sourceWitness (op.witnessMap w) :=
  op.witnessMappingSound w h

/-- A post-operation witness reflects to the existence of a pre-operation witness. -/
theorem exists_sourceWitness_of_targetWitness
    (op : ArchitectureOperation State BeforeWitness AfterWitness)
    {w : AfterWitness} (h : op.targetWitness w) :
    ∃ v : BeforeWitness, op.sourceWitness v :=
  ⟨op.witnessMap w, op.witnessMapping_sound h⟩

end ArchitectureOperation

end Formal.Arch
