import ResearchLean.AG.RelativeRepairComposition.C13RangeInput

/-! # Positive and negative all-S actual inputs on the same nonzero original face -/
namespace AAT.AG.RelativeRepairComposition.C13ActualRangeRegression
set_option synthInstance.maxHeartbeats 100000
open CategoryTheory TransportCoherence TransportCoherence.Arbitrary AbelianLiftingObstruction
open C13RangeInput
/-- The field with two elements used for the full native kernel coordinates. -/
abbrev k := ZMod 2
/-- The full coefficient family generated by the original translation tower. -/
noncomputable abbrev M := tower.toTower.localCoefficients
/-- Decide equality on the original two named loop indices. -/
instance originalEdgeEquality : DecidableEq (EdgeName (K := geometry)) :=
  inferInstanceAs (DecidableEq (Σ _ : Unit, Σ _ : Unit, Bool))
/-- Decide the original candidate predicate using the named loop index. -/
instance candidatesDecidable : DecidablePred (· ∈ candidates) :=
  fun e => inferInstanceAs (Decidable (e.2.2 = true))
/-- Decide membership in the physically fixed original edge set. -/
instance fixedEdgesDecidable : DecidablePred (· ∈ fixed.edges) :=
  fun e => inferInstanceAs (Decidable (e.2.2 = false))
/-- Decide membership in the physically fixed original face set. -/
instance fixedFacesDecidable : DecidablePred (· ∈ fixed.faces) :=
  fun f => inferInstanceAs (Decidable (f ∈ (∅ : Set Unit)))

/-- The full native coefficient map is linear for the transferred original module. -/
noncomputable def linearCoefficient (v : geometry.Vertex) : M.A v ≃ₗ[k] k where
  toAddEquiv := coefficient v
  map_smul' t x := (coefficient v).apply_symm_apply (t • coefficient v x)

/-- One complete coordinate represents the entire one-dimensional original kernel. -/
def scalarCoordinate : k ≃ₗ[k] (Fin 1 → k) where
  toFun x := fun _ => x
  invFun x := x 0
  left_inv _ := rfl
  right_inv x := by funext j; exact congrArg x (Subsingleton.elim _ _)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- Complete bases of the actual full kernels, with no proper subgroup selected. -/
noncomputable def basis : FiniteFamily.Bases (k := k) M.A :=
  ⟨fun _ => 1,fun v => (linearCoefficient v).trans scalarCoordinate⟩

/-- The actual full solution keeps translation one at both original loops. -/
def groupSolution : GroupExtension.GroupSolution geometry projection core where
  edge _ := Multiplicative.ofAdd 1
  projects _ := rfl
  face _ := rfl

/-- The categorical solution is generated by the original edge-preserving group correspondence. -/
noncomputable def solution : Solution tower :=
  (GroupExtension.solutionEquiv geometry projection kernel_comm core reference projects relations).symm groupSolution

/-- The same named original candidate range is used by every independent actual predicate. -/
abbrev Repair (S : Set candidates) :=
  SupportedRepair tower (fixedEdgesForRange fixed.edges candidates (OriginalRanges.allowed candidates S))

/-- Allowing the original true loop permits the concrete actual translation-one repair. -/
noncomputable def allRepair : Repair Set.univ := ⟨solution,by
  intro e he
  rcases he with hp | hc
  · change (Multiplicative.ofAdd (1 : k) : E) * 1 = reference e.2.2 * 1
    have hf : e.2.2 = false := hp
    have hn : e.2.2 ≠ true :=
      fun ht => (by decide : (false : Bool) ≠ true) (hf.symm.trans ht)
    rw [reference,if_neg hn]
  · exact (hc.2 ⟨hc.1,trivial⟩).elim⟩

/-- Fixing both original loops forces two different original translation values across the authored face. -/
theorem empty_no_repair : ¬ Nonempty (Repair ∅) := by
  rintro ⟨R⟩
  let G := GroupExtension.solutionEquiv geometry projection kernel_comm core reference projects relations R.1
  have hf := G.face ()
  have ha := R.2 ⟨(),(),false⟩ (Or.inl rfl)
  have hb := R.2 ⟨(),(),true⟩ (Or.inr ⟨rfl,by rintro ⟨_,h⟩; exact h⟩)
  change G.edge false * 1 = Multiplicative.ofAdd 1 * 1 at ha
  change G.edge true * 1 = 1 * 1 at hb
  simp only [mul_one] at ha hb
  change 1 * G.edge false = 1 * G.edge true at hf
  rw [one_mul,one_mul,ha,hb] at hf
  have h : (1 : k) = 0 := congrArg Multiplicative.toAdd hf
  exact (by decide : (1 : k) ≠ 0) h

local notation "D0" => OriginalColumns.D (k := k) M fixed candidates linear
local notation "Bcol" => OriginalRanges.column (k := k) M fixed candidates outside linear
local notation "obs" => OriginalRangeClassification.obstruction (k := k) tower fixed candidates linear fixed_coherent

/-- The same actual always quotient obstruction is nonzero; otherwise the empty actual range would repair. -/
theorem obstruction_nonzero : obs ≠ 0 := by
  intro hz
  apply empty_no_repair
  apply (OriginalRangeClassification.repair_nonempty_iff_range (k := k)
    tower fixed candidates outside linear fixed_coherent ∅).mpr
  change obs ∈ NamedDual.ranges Bcol ∅
  rw [hz]; exact Submodule.zero_mem _

/-- The original actual successful range is accepted by the independent full-column predicate. -/
theorem all_range_member : obs ∈ NamedDual.ranges Bcol Set.univ :=
  (OriginalRangeClassification.repair_nonempty_iff_range (k := k)
    tower fixed candidates outside linear fixed_coherent Set.univ).mp ⟨allRepair⟩

/-- The same actual nonzero rhs is rejected for the empty range by the full-column predicate. -/
theorem empty_range_reject : obs ∉ NamedDual.ranges Bcol ∅ :=
  fun h => empty_no_repair ((OriginalRangeClassification.repair_nonempty_iff_range (k := k)
    tower fixed candidates outside linear fixed_coherent ∅).mpr h)

/-- The successful actual range hits every dual support nonzero on its own original obstruction. -/
theorem all_hits : NamedDual.Hits Bcol obs Set.univ :=
  (NamedDual.mem_ranges_iff_hits Bcol obs Set.univ).mp all_range_member

/-- The empty actual range fails that same independently defined dual-support condition. -/
theorem empty_hits_reject : ¬ NamedDual.Hits Bcol obs ∅ :=
  fun h => empty_range_reject ((NamedDual.mem_ranges_iff_hits Bcol obs ∅).mpr h)

/-- A second closed physical input fixes every original loop but no original face. -/
def allFixed : ClosedRegion geometry where
  vertices := Set.univ
  edges := Set.univ
  faces := ∅
  triples := ∅
  edge_closed _ _ := ⟨trivial,trivial⟩
  face_closed _ h := False.elim h
  triple_closed t _ := Empty.elim t

/-- The original empty named candidate input. -/
def noCandidates : Set (EdgeName (K := geometry)) := ∅
/-- Decide membership in the empty original candidate family. -/
instance noCandidatesDecidable : DecidablePred (· ∈ noCandidates) :=
  fun e => inferInstanceAs (Decidable (e ∈ (∅ : Set (EdgeName (K := geometry)))))

/-- Every candidate of the original empty input is outside the fixed part. -/
theorem noCandidates_outside (e : EdgeName (K := geometry)) (he : e ∈ noCandidates) :
    e ∉ allFixed.edges := False.elim he

/-- The original empty fixed-face condition follows from the closed input itself. -/
theorem allFixed_coherent (f : geometry.TwoCell) (hf : f ∈ allFixed.faces) :
    tower.toTower.upper.pathLift (geometry.twoLeft f) ≫ FiberAut.hom (tower.comparator f) =
      tower.toTower.upper.pathLift (geometry.twoRight f) := False.elim hf

/-- Even allowing every member of the empty candidate family cannot repair this independent actual input. -/
theorem allFixed_no_repair : ¬ Nonempty (SupportedRepair tower
    (fixedEdgesForRange allFixed.edges noCandidates (OriginalRanges.allowed noCandidates Set.univ))) := by
  rintro ⟨R⟩
  let G := GroupExtension.solutionEquiv geometry projection kernel_comm core reference projects relations R.1
  have hf := G.face ()
  have ha := R.2 ⟨(),(),false⟩ (Or.inl trivial)
  have hb := R.2 ⟨(),(),true⟩ (Or.inl trivial)
  change G.edge false * 1 = Multiplicative.ofAdd 1 * 1 at ha
  change G.edge true * 1 = 1 * 1 at hb
  simp only [mul_one] at ha hb
  change 1 * G.edge false = 1 * G.edge true at hf
  rw [one_mul,one_mul,ha,hb] at hf
  exact (by decide : (1 : k) ≠ 0) (congrArg Multiplicative.toAdd hf)

/-- The same actual all-candidate impossibility produces a nonzero dual with empty original named support. -/
theorem impossible_empty_support :
    ∃ phi : Module.Dual k (OriginalRanges.ObstructionSpace (k := k) M allFixed noCandidates linear),
      phi (OriginalRangeClassification.obstruction (k := k) tower allFixed noCandidates linear allFixed_coherent) ≠ 0 ∧
        NamedDual.support (OriginalRanges.column (k := k) M allFixed noCandidates noCandidates_outside linear) phi = ∅ :=
  OriginalRangeClassification.impossible_dual_empty (k := k) tower allFixed noCandidates
    noCandidates_outside linear allFixed_coherent allFixed_no_repair

end AAT.AG.RelativeRepairComposition.C13ActualRangeRegression
#assert_standard_axioms_only AAT.AG.RelativeRepairComposition.C13ActualRangeRegression
