import ResearchLean.AG.RelativeRepairComposition.SubdivisionObstruction
import ResearchLean.AG.RelativeRepairComposition.SubdivisionZeroCohomology
import ResearchLean.AG.RelativeRepairComposition.NativeAffineSubdivision
import ResearchLean.AG.RelativeRepairComposition.C17SubdivisionCoordinates
import ResearchLean.AG.RelativeRepairComposition.NativeAffineEvaluation

/-!
# The same specified W4 uses the full native complex decomposition

The supplemental full kernel contains a nonzero element with coordinate one.
Actual permitted vertex labels produce it under the original first differential;
the native contraction retains it. The same actual defect has coordinate minus
one on the original and rewritten full face.

## Implementation notes

These are applications of the general decomposition to the previously specified
W4 actual tower and factors. Independent actual repair coordinates remain those
of C17. Its empty three-cell carrier is used only for this specified example,
not for the general full-route d2 comparison.
-/
namespace AAT.AG.RelativeRepairComposition.C18SubdivisionRegression
open CategoryTheory Limits TransportCoherence TransportCoherence.Arbitrary AbelianLiftingObstruction
open NativeAffine C17SubdivisionInput

/-- The chosen always edge remains outside the full original candidate set. -/
theorem chosen_not_candidate : chosen ∉ ({candidate} : Set (EdgeName (K := geometry))) := by
  intro h
  have he : chosen = candidate := h
  have hb := congrArg (fun e : EdgeName (K := geometry) => e.2.2) he
  change (false : Bool) = true at hb
  cases hb

/-- The already specified actual W4 factors are generated by the same arbitrary whole-affine factory. -/
theorem factors_generated :
    NativeAffine.subdivisionFactors geometry reference reference comparison linear_faces chosen first second
      (by simpa [reference,chosen] using factor_product) = factors := rfl

/-- A coefficient with coordinate one belongs to the entire actual fresh kernel. -/
noncomputable def freshOne : splitTower.toTower.localCoefficients.A (.inr ()) := middleCoefficient.symm 1

/-- The full fresh coefficient used by the contraction is nonzero in the actual kernel. -/
theorem freshOne_ne_zero : freshOne ≠ 0 := by
  intro h
  have hv := congrArg middleCoefficient h
  change middleCoefficient (middleCoefficient.symm 1) = middleCoefficient 0 at hv
  rw [AddEquiv.apply_symm_apply,map_zero] at hv
  exact one_ne_zero hv

/-- The actual full-kernel supplement differential sends its nonzero element to exactly itself. -/
theorem fresh_identity_value :
    (Subdivision.freshComplex originalTower chosen factors).d 0 1 (ULift.up freshOne) =
      ULift.up freshOne := by
  have hd : (Subdivision.freshComplex originalTower chosen factors).d 0 1 = 𝟙 _ :=
    NativeIdentityComplex.d_zero_one _
  rw [hd]
  rfl

/-- The native contraction retains the entire nonzero element with its actual value. -/
theorem fresh_contraction_value :
    (Subdivision.freshContraction originalTower chosen factors).hom 1 0 (ULift.up freshOne) =
      ULift.up freshOne := rfl

/-- A complete permitted actual label with old value zero and arbitrary fresh displacement. -/
noncomputable def freshLabel (a : splitTower.toTower.localCoefficients.A (.inr ())) :
    RelativeComplex.C0Group splitTower.toTower.localCoefficients
      (Subdivision.oldRegion geometry chosen fixedRegion (by exact not_false))
      (Subdivision.oldEdgeSet geometry chosen {candidate})
      (Subdivision.oldEdgeSet geometry chosen {candidate}) :=
  (Subdivision.relative0Equiv originalTower chosen factors fixedRegion {candidate} {candidate}
    (by exact not_false) chosen_not_candidate).symm (0,a)

/-- The original supported differential sends every fresh displacement to that same entire first value. -/
theorem fresh_label_d0 (a : splitTower.toTower.localCoefficients.A (.inr ())) :
    d0 splitTower.toTower.localCoefficients (freshLabel a).1
      (Subdivision.firstEdgeName geometry chosen) = a := by
  rw [Subdivision.d0_first]
  change (Subdivision.relative0Equiv originalTower chosen factors fixedRegion {candidate} {candidate}
    (by exact not_false) chosen_not_candidate (freshLabel a)).2 = a
  rw [freshLabel,AddEquiv.apply_symm_apply]

/-- The actual original differential has a nonzero first value at the full permitted label. -/
theorem fresh_label_d0_nonzero :
    d0 splitTower.toTower.localCoefficients (freshLabel freshOne).1
      (Subdivision.firstEdgeName geometry chosen) ≠ 0 := by
  rw [fresh_label_d0]
  exact freshOne_ne_zero

/-- The full original reference word has actual affine value identity. -/
theorem reference_face_word : GroupExtension.pathValue geometry reference (geometry.twoLeft ()) = (1 : Op) := by
  have hh : C17SubdivisionInput.flip * C17SubdivisionInput.flip = (1 : Op) := by
    ext x
    change -(-x) = x
    exact neg_neg x
  simp only [geometry,GroupExtension.pathValue,reference,if_pos,if_neg,
    Bool.false_eq_true,not_false_eq_true,one_mul,mul_one,hh]

/-- The full actual original obstruction representative has the specified nonzero coordinate minus one. -/
theorem old_defect_coordinate : middleCoefficient (originalTower.toTower.defect ()) = (-1 : ZMod 3) := by
  have hv := defect_value geometry reference reference comparison linear_faces ()
  rw [reference_face_word] at hv
  simpa only [geometry,GroupExtension.pathValue,comparison,inv_one,mul_one,translation_apply,add_zero]
    using hv

/-- The same actual split tower retains that entire original obstruction representative and comparison value. -/
theorem new_defect_coordinate : middleCoefficient (splitTower.toTower.defect ()) = (-1 : ZMod 3) := by
  rw [Subdivision.defect_substitute]
  exact old_defect_coordinate

/-- The same full native decomposition applies to W4 with its candidate allowed. -/
noncomputable def relativeComplexIso :=
  Subdivision.relativeBiprodIso originalTower chosen factors fixedRegion {candidate} {candidate}
    (by exact not_false) chosen_not_candidate

/-- The same actual collapse preserves every native cohomology degree of the specified W4. -/
noncomputable def allHomologyIso (n : ℕ) :=
  Subdivision.relativeHomologyIso originalTower chosen factors fixedRegion {candidate} {candidate}
    (by exact not_false) chosen_not_candidate n

/-- The native degree-one collapse on every independent supported correction keeps exactly the actual W4 value v-u. -/
theorem native_collapse_coordinate (h : RelativeComplex.C1Group splitTower.toTower.localCoefficients
    (Subdivision.oldRegion geometry chosen fixedRegion (by exact not_false))
    (Subdivision.oldEdgeSet geometry chosen {candidate})
    (Subdivision.oldEdgeSet geometry chosen {candidate})) :
    middleCoefficient (((Subdivision.relativeCollapse originalTower chosen factors fixedRegion
      {candidate} {candidate} (by exact not_false) chosen_not_candidate).f 1 h).1 chosen) =
      middleCoefficient (h.1 (Subdivision.secondEdgeName geometry chosen)) -
        middleCoefficient (h.1 (Subdivision.firstEdgeName geometry chosen)) := by
  rw [Subdivision.relativeCollapse_one]
  exact C17SubdivisionInput.collapse_coordinate h.1

/-- The same native section restores zero first correction on every original supported correction. -/
theorem native_section_first (h : RelativeComplex.C1Group originalTower.toTower.localCoefficients
    fixedRegion {candidate} {candidate}) :
    ((Subdivision.relativeSection originalTower chosen factors fixedRegion {candidate} {candidate}
      (by exact not_false) chosen_not_candidate).f 1 h).1
      (Subdivision.firstEdgeName geometry chosen) = 0 := by
  rw [Subdivision.relativeSection_one,Subdivision.expandCorrection_first]

end AAT.AG.RelativeRepairComposition.C18SubdivisionRegression
#assert_standard_axioms_only AAT.AG.RelativeRepairComposition.C18SubdivisionRegression
