import ResearchLean.AG.RelativeRepairComposition.CoverEquation

/-!
# Transport of native comma objects and all arrows through coordinates.
## Implementation notes

G-130 B changes coordinates in the entire native comma category. The inverse
functors and their counits restore the two local objects and conjugate the full
overlap arrow. A bijection of isomorphism classes would omit this arrow and its
compatible morphisms, so the comparison uses native category equivalences.
-/

namespace AAT.AG.RelativeRepairComposition
open CategoryTheory CategoryTheory.Functor CategoryTheory.NatIso
namespace CommaCoordinates
universe uC uD uW uX uY uZ vC vD vW vX vY vZ
variable {C : Type uC} {D : Type uD} {W : Type uW}
variable {X : Type uX} {Y : Type uY} {Z : Type uZ}
variable [Category.{vC} C] [Category.{vD} D] [Category.{vW} W]
variable [Category.{vX} X] [Category.{vY} Y] [Category.{vZ} Z]
variable (eC : C ≌ X) (eD : D ≌ Y) (eW : W ≌ Z)
variable (L : X ⥤ Z) (R : Y ⥤ Z)

/-- Restriction on independent objects is restored through full coordinate functors. -/
def leftRestriction : C ⥤ W := eC.functor ⋙ L ⋙ eW.inverse

/-- Restriction on the other independent objects retains their full coordinates. -/
def rightRestriction : D ⥤ W := eD.functor ⋙ R ⋙ eW.inverse

/-- The left coordinate comparison is generated by the existing inverse counit. -/
def leftComparison : eC.inverse ⋙ leftRestriction eC eW L ≅ L ⋙ eW.inverse :=
  isoWhiskerRight eC.counitIso (L ⋙ eW.inverse) ≪≫ leftUnitor (L ⋙ eW.inverse)

/-- The right coordinate comparison is generated by the existing inverse counit. -/
def rightComparison : R ⋙ eW.inverse ≅ eD.inverse ⋙ rightRestriction eD eW R :=
  (isoWhiskerRight eD.counitIso (R ⋙ eW.inverse) ≪≫ leftUnitor (R ⋙ eW.inverse)).symm

/-- The left comparison is the full mapped counit followed by identity transport. -/
theorem left_comparison_hom (x : X) :
    (leftComparison eC eW L).hom.app x =
      eW.inverse.map (L.map (eC.counitIso.hom.app x)) ≫ 𝟙 _ := rfl

/-- The right comparison is identity transport followed by the full mapped inverse counit. -/
theorem right_comparison_hom (y : Y) :
    (rightComparison eD eW R).hom.app y =
      𝟙 _ ≫ eW.inverse.map (R.map (eD.counitIso.inv.app y)) := rfl

/-- Every comma object and compatible arrow is restored through the same equivalences. -/
def restoreFunctor : Comma L R ⥤
    Comma (leftRestriction eC eW L) (rightRestriction eD eW R) :=
  Comma.map (leftComparison eC eW L).hom (rightComparison eD eW R).hom

/-- Restoration keeps the entire overlap arrow between the coordinate comparisons. -/
theorem restore_seam (d : Comma L R) :
    ((restoreFunctor eC eD eW L R).obj d).hom =
      (leftComparison eC eW L).hom.app d.left ≫ eW.inverse.map d.hom ≫
        (rightComparison eD eW R).hom.app d.right := rfl

/-- Restoration of the left object uses the specified full inverse functor. -/
theorem restore_left_obj (d : Comma L R) :
    ((restoreFunctor eC eD eW L R).obj d).left = eC.inverse.obj d.left := rfl

/-- Restoration of the right object uses the specified full inverse functor. -/
theorem restore_right_obj (d : Comma L R) :
    ((restoreFunctor eC eD eW L R).obj d).right = eD.inverse.obj d.right := rfl

/-- Restoration keeps the entire left arrow through the specified inverse functor. -/
theorem restore_left_map {d e : Comma L R} (f : d ⟶ e) :
    ((restoreFunctor eC eD eW L R).map f).left = eC.inverse.map f.left := rfl

/-- Restoration keeps the entire right arrow through the specified inverse functor. -/
theorem restore_right_map {d e : Comma L R} (f : d ⟶ e) :
    ((restoreFunctor eC eD eW L R).map f).right = eD.inverse.map f.right := rfl

/-- The comma restoration is full, faithful and essentially surjective. -/
theorem restore_is_equivalence : (restoreFunctor eC eD eW L R).IsEquivalence := by
  unfold restoreFunctor
  infer_instance

/-- The native comma comparison is an equivalence on all objects and arrows. -/
noncomputable def equivalence : Comma L R ≌
    Comma (leftRestriction eC eW L) (rightRestriction eD eW R) := by
  letI := restore_is_equivalence eC eD eW L R
  exact (restoreFunctor eC eD eW L R).asEquivalence

/-- Every arrow of the native comma of groupoids is an isomorphism. -/
theorem comma_is_groupoid [IsGroupoid C] [IsGroupoid D]
    (L : C ⥤ W) (R : D ⥤ W) : IsGroupoid (Comma L R) where
  all_isIso f := by
    let e := Comma.isoMk (asIso f.left) (asIso f.right) f.w
    have h : e.hom = f := Comma.hom_ext _ _ rfl rfl
    rw [← h]
    infer_instance

end CommaCoordinates
end AAT.AG.RelativeRepairComposition

#assert_standard_axioms_only AAT.AG.RelativeRepairComposition
