import ResearchLean.AG.RelativeRepairComposition.GeneratedStrictCover

/-!
# Candidate zero followed by projection to the shared original coordinates

The relation is generated by the same native private matrix and section. All
candidate conditions are imposed before the shared projection. Thus internal
candidate coordinates are existentially eliminated, while shared ones remain.
-/
namespace AAT.AG.RelativeRepairComposition
open TransportCoherence AbelianLiftingObstruction FiniteCoefficients
universe uk uG uA
namespace FiniteNative
variable {k : Type uk} [Field k] [Fintype k] [DecidableEq k]
variable {K : FiniteTransportPresentation.{uG}} (M : LocalCoefficients.{uG,uA} K)
variable [∀ v, Module k (M.A v)]
variable (B : FiniteFamily.Bases (k := k) M.A) (U P : ClosedRegion K)
variable [DecidablePred (· ∈ P.vertices)] [DecidablePred (· ∈ P.edges)]
variable [DecidablePred (· ∈ P.faces)] [DecidablePred (· ∈ U.vertices)]
variable [DecidablePred (· ∈ U.edges)] [DecidablePred (· ∈ U.faces)]
variable (internalEdges : Set (EdgeName (K := K))) [DecidablePred (· ∈ internalEdges)]
variable (hlinear : ∀ {i j : K.Vertex} (e : K.Edge i j) (t : k) (x : M.A i),
  M.edge e (t • x) = t • M.edge e x)
variable (δ : RelativeCover.C2 M ClosedRegion.all P)
variable [Fintype (EdgeName (K := K))] [DecidableEq (EdgeName (K := K))]
variable [Fintype K.TwoCell] [DecidableEq K.TwoCell]
variable (ek : FiniteElimination.Enumeration k)
variable (ee : FiniteElimination.Enumeration (EdgeName (K := K)))
variable (ef : FiniteElimination.Enumeration K.TwoCell)
local notation "E" => generatedSolutionEquiv M B U P internalEdges hlinear δ ek ee ef
local notation "Generated" => GeneratedObjects M B U P internalEdges hlinear δ ek ee ef

/-- Read all old edge values exposed by a public coordinate, without private choices. -/
def boundaryPublicValue (z : ZIndex M B U P internalEdges → k) (e : U.edges) : M.A e.1.2.1 :=
  ((edgeSplit M B U P internalEdges).symm (0,z)).1 e

omit [DecidablePred (· ∈ P.vertices)] in
/-- The inverse generated solution has the same exposed edge value for every private kernel. -/
theorem restored_boundary_value (y : Generated) (e : U.edges) (he : e.1 ∉ internalEdges) :
    ((E).symm y).1.1 e = boundaryPublicValue M B U P internalEdges y.1.1 e := by
  let h := ((E).symm y).1
  have hz := generated_solution_inverse_public M B U P internalEdges hlinear δ ek ee ef y
  have hh : h = (edgeSplit M B U P internalEdges).symm
      ((edgeSplit M B U P internalEdges h).1,y.1.1) := by
    rw [← hz]
    exact (LinearEquiv.symm_apply_apply _ h).symm
  change h.1 e = _
  rw [hh]
  by_cases hp : e.1 ∈ P.edges
  · exact (((edgeSplit M B U P internalEdges).symm _).2 e hp).trans
      (((edgeSplit M B U P internalEdges).symm (0,y.1.1)).2 e hp).symm
  · exact public_edge_private_independent M B U P internalEdges _ 0 y.1.1 e hp he

/-- Candidate zero conditions are imposed on all original candidates, including internal candidates. -/
def BoundaryPublicZero (candidates allowed : Set (EdgeName (K := K)))
    (z : ZIndex M B U P internalEdges → k) : Prop :=
  ∀ e : U.edges, e.1 ∈ candidates \ allowed → boundaryPublicValue M B U P internalEdges z e = 0

/-- C is the image of the same generated relation after candidate zero and internal-candidate elimination. -/
def BoundaryRelation (W : ClosedRegion K) (inc : ClosedRegion.Inclusion W U)
    (candidates allowed : Set (EdgeName (K := K))) : Set (∀ e : W.edges, M.A e.1.2.1) :=
  {t | ∃ z : LinearInterface.Relation (D M B U P internalEdges hlinear)
      (F M B U P internalEdges hlinear) (generatedSection M B U P internalEdges hlinear ek ee ef)
      (rhs M B U P δ),
    BoundaryPublicZero M B U P internalEdges candidates allowed z.1 ∧
      publicRestriction M B U P internalEdges W inc z.1 = t}

/-- The independent supported local solution supplies its literal shared original edge values. -/
def supportedBoundary (W : ClosedRegion K) (inc : ClosedRegion.Inclusion W U)
    (candidates allowed : Set (EdgeName (K := K)))
    (h : SupportedEquation.Objects M P U candidates allowed δ) : ∀ e : W.edges, M.A e.1.2.1 :=
  fun e => h.1.1.1 ⟨e.1,inc.edges e.2⟩

omit [DecidablePred (· ∈ P.vertices)] in
/-- The projected generated C is exactly the range of independent supported original repairs. -/
theorem boundary_relation_range (W : ClosedRegion K) (inc : ClosedRegion.Inclusion W U)
    (hw : ∀ e ∈ W.edges, e ∉ internalEdges)
    (candidates allowed : Set (EdgeName (K := K)))
    (hc : ∀ e ∈ candidates, e ∉ internalEdges) :
    BoundaryRelation M B U P internalEdges hlinear δ ek ee ef W inc candidates allowed =
      Set.range (supportedBoundary M U P δ W inc candidates allowed) := by
  ext t
  constructor
  · rintro ⟨z, hz, ht⟩
    let y : Generated := (z,0)
    let h := (E).symm y
    have hs : ∀ e : U.edges, e.1 ∈ candidates \ allowed → h.1.1 e = 0 := by
      intro e he
      exact (restored_boundary_value M B U P internalEdges hlinear δ ek ee ef y e
        (hc e.1 he.1)).trans (hz e he)
    refine ⟨⟨h,hs⟩, ?_⟩
    change (fun e : W.edges => h.1.1 ⟨e.1,inc.edges e.2⟩) = t
    calc
      _ = publicRestriction M B U P internalEdges W inc z.1 := by
        funext e
        exact restored_boundary_value M B U P internalEdges hlinear δ ek ee ef y
          ⟨e.1,inc.edges e.2⟩ (hw e.1 e.2)
      _ = t := ht
  · rintro ⟨h, rfl⟩
    let y := (E) h.1
    have hy : (E).symm y = h.1 := (E).symm_apply_apply h.1
    refine ⟨y.1, ?_, ?_⟩
    · intro e he
      have hv := restored_boundary_value M B U P internalEdges hlinear δ ek ee ef y e
        (hc e.1 he.1)
      rw [hy] at hv
      exact hv.symm.trans (h.2 e he)
    · funext e
      have hv := restored_boundary_value M B U P internalEdges hlinear δ ek ee ef y
        ⟨e.1,inc.edges e.2⟩ (hw e.1 e.2)
      rw [hy] at hv
      exact hv.symm

end FiniteNative
end AAT.AG.RelativeRepairComposition
#assert_standard_axioms_only AAT.AG.RelativeRepairComposition.FiniteNative
