import Formal.Util.AssertStandardAxioms
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.Order.Minimal

/-!
# All named candidate ranges and dual obstruction supports

The coefficient space at each candidate may differ. The range is generated by
the original full columns, while dual supports are independently defined by
nonzero column composites. Separation uses the field dual of the actual quotient.
-/
namespace AAT.AG.RelativeRepairComposition
universe uk ue uy uo
namespace NamedDual
variable {k : Type uk} [Field k] {E : Type ue} {Y : E → Type uy}
variable [∀ e, AddCommGroup (Y e)] [∀ e, Module k (Y e)]
variable {O : Type uo} [AddCommGroup O] [Module k O]
variable (B : ∀ e, Y e →ₗ[k] O)

/-- The full sum of the selected original named column ranges. -/
def ranges (S : Set E) : Submodule k O := ⨆ e ∈ S, LinearMap.range (B e)

/-- A dual support retains exactly the names with nonzero whole column composite. -/
def support (phi : Module.Dual k O) : Set E := {e | phi.comp (B e) ≠ 0}

/-- A named candidate belongs to the dual support exactly when its full column composite is nonzero. -/
theorem mem_support (phi : Module.Dual k O) (e : E) :
    e ∈ support B phi ↔ phi.comp (B e) ≠ 0 := Iff.rfl

/-- Every selected full column is contained in the selected sum. -/
theorem range_le (S : Set E) (e : E) (he : e ∈ S) :
    LinearMap.range (B e) ≤ ranges B S :=
  le_iSup_of_le e (le_iSup_of_le he le_rfl)

/-- The range sum is annihilated exactly when all selected column composites vanish. -/
theorem annihilates_iff (S : Set E) (phi : Module.Dual k O) :
    phi ∈ (ranges B S).dualAnnihilator ↔ ∀ e ∈ S, phi.comp (B e) = 0 := by
  rw [Submodule.mem_dualAnnihilator]
  constructor
  · intro h e he
    ext y
    exact h (B e y) (range_le B S e he ⟨y,rfl⟩)
  · intro h x hx
    have hle : ranges B S ≤ LinearMap.ker phi := by
      apply iSup_le
      intro e
      apply iSup_le
      intro he y hy
      rcases hy with ⟨z,rfl⟩
      change phi (B e z) = 0
      exact LinearMap.congr_fun (h e he) z
    exact hle hx

/-- A nonzero value on the obstruction must meet its independently named dual support. -/
def Hits (o : O) (S : Set E) : Prop :=
  ∀ phi : Module.Dual k O, phi o ≠ 0 → (S ∩ support B phi).Nonempty

/-- Field dual separation gives the complete all-range hitting criterion. -/
theorem mem_ranges_iff_hits (o : O) (S : Set E) : o ∈ ranges B S ↔ Hits B o S := by
  classical
  constructor
  · intro ho phi hphi
    by_contra hn
    have hc : ∀ e ∈ S, phi.comp (B e) = 0 := by
      intro e he
      by_contra hne
      exact hn ⟨e,he,hne⟩
    exact hphi ((Submodule.mem_dualAnnihilator phi).mp ((annihilates_iff B S phi).mpr hc) o ho)
  · intro hh
    apply (Subspace.forall_mem_dualAnnihilator_apply_eq_zero_iff (ranges B S) o).mp
    intro phi hphi
    by_contra hn
    obtain ⟨e,he,hs⟩ := hh phi hn
    exact hs ((annihilates_iff B S phi).mp hphi e he)

/-- A failed range has a separating quotient dual avoiding every selected name. -/
theorem failure_witness (o : O) (S : Set E) (h : o ∉ ranges B S) :
    ∃ phi : Module.Dual k O, phi o ≠ 0 ∧ ∀ e ∈ S, phi.comp (B e) = 0 := by
  classical
  have hn : ¬ Hits B o S := fun hh => h ((mem_ranges_iff_hits B o S).mpr hh)
  simp only [Hits,not_forall] at hn
  obtain ⟨phi,hphi,hs⟩ := hn
  refine ⟨phi,hphi,?_⟩
  intro e he
  by_contra hne
  exact hs ⟨e,he,hne⟩

/-- Inclusion-minimal feasible ranges are precisely minimal dual transversals. -/
theorem minimal_iff (o : O) (S : Set E) :
    Minimal (fun T => o ∈ ranges B T) S ↔ Minimal (Hits B o) S := by
  constructor
  · rintro ⟨hs,hm⟩
    exact ⟨(mem_ranges_iff_hits B o S).mp hs,
      fun T ht hts => hm ((mem_ranges_iff_hits B o T).mpr ht) hts⟩
  · rintro ⟨hs,hm⟩
    exact ⟨(mem_ranges_iff_hits B o S).mpr hs,
      fun T ht hts => hm ((mem_ranges_iff_hits B o T).mp ht) hts⟩

/-- At zero obstruction the empty set is the unique inclusion-minimal feasible range. -/
theorem minimal_zero_iff (S : Set E) :
    Minimal (fun T => (0 : O) ∈ ranges B T) S ↔ S = ∅ := by
  constructor
  · intro h
    apply Set.eq_empty_iff_forall_notMem.mpr
    intro e he
    exact h.2 (Submodule.zero_mem _) (Set.empty_subset S) he
  · rintro rfl
    exact ⟨Submodule.zero_mem _,fun _ _ _ => Set.empty_subset _⟩

/-- If all candidates fail, a nonzero obstruction dual has empty named support. -/
theorem impossible_empty_support (o : O) (h : o ∉ ranges B Set.univ) :
    ∃ phi : Module.Dual k O, phi o ≠ 0 ∧ support B phi = ∅ := by
  obtain ⟨phi,hphi,hc⟩ := failure_witness B o Set.univ h
  refine ⟨phi,hphi,Set.eq_empty_iff_forall_notMem.mpr ?_⟩
  intro e he
  exact he (hc e (Set.mem_univ e))

/-- An empty obstruction support excludes every transversal, including empty candidate input. -/
theorem no_transversal_of_empty_support (o : O) (phi : Module.Dual k O)
    (hphi : phi o ≠ 0) (hs : support B phi = ∅) : ∀ S, ¬ Hits B o S := by
  intro S hh
  obtain ⟨e,_,he⟩ := hh phi hphi
  rw [hs] at he
  exact he

end NamedDual
end AAT.AG.RelativeRepairComposition
#assert_standard_axioms_only AAT.AG.RelativeRepairComposition
