import ResearchLean.AG.RelativeRepairComposition.SubdivisionSupportedSolutions

/-!
# Full coefficient transport at retained edges and both actual factors

The coefficient types are the same actual projection kernels. Equality of the
actual selected edge transports proves the retained and factor formulas.
-/
namespace AAT.AG.RelativeRepairComposition.Subdivision
open CategoryTheory TransportCoherence TransportCoherence.Arbitrary AbelianLiftingObstruction
universe uG uE uB uD vE vB vD
variable {K : FiniteTransportPresentation.{uG}}
variable {E : Type uE} {B : Type uB} {D : Type uD}
variable [Category.{vE} E] [Category.{vB} B] [Category.{vD} D]
variable {p : E ⥤ B} {q : B ⥤ D}
variable (T : OriginalTowerPresentation K p q) (chosen : EdgeName (K := K))
variable (F : Factorization T chosen)

/-- The additive equivalence generated by the entire actual first-factor kernel transport. -/
noncomputable def rho1AddEquiv : T.toTower.localCoefficients.A chosen.1 ≃+
    (originalTower T chosen F).toTower.localCoefficients.A (.inr ()) :=
  kernelTransportAddEquiv p q F.first F.firstStrong F.firstLowerStrong F.firstBijective

/-- The additive equivalence generated by the entire actual second-factor kernel transport. -/
noncomputable def rho2AddEquiv : (originalTower T chosen F).toTower.localCoefficients.A (.inr ()) ≃+
    T.toTower.localCoefficients.A chosen.2.1 :=
  kernelTransportAddEquiv p q F.second F.secondStrong F.secondLowerStrong F.secondBijective

/-- The full second-factor additive equivalence has exactly the earlier generated full additive hom value. -/
theorem rho2AddEquiv_value
    (a : (originalTower T chosen F).toTower.localCoefficients.A (.inr ())) :
    rho2AddEquiv T chosen F a = rho2Add T chosen F a := rfl

/-- Every retained original edge has exactly its same original full coefficient equivalence. -/
theorem coefficient_edge_old (e : EdgeName (K := K)) (he : e ≠ chosen) :
    (originalTower T chosen F).toTower.localCoefficients.edge (oldEdge K chosen e he) =
      T.toTower.localCoefficients.edge e.2.2 := by
  apply AddEquiv.ext
  intro a
  have h := selected_edge_transport T chosen F (oldEdge K chosen e he)
  have hv := congrArg (fun rho => Additive.ofMul (rho (Additive.toMul a))) h
  simpa only [referenceLiftData,liftData,edgeAssignment_old] using hv

/-- The first named factor uses the generated whole actual first-factor equivalence. -/
theorem coefficient_edge_first :
    (originalTower T chosen F).toTower.localCoefficients.edge (firstEdge K chosen) =
      rho1AddEquiv T chosen F := by
  apply AddEquiv.ext
  intro a
  have h := selected_edge_transport T chosen F (firstEdge K chosen)
  have hv := congrArg (fun rho => Additive.ofMul (rho (Additive.toMul a))) h
  simpa only [referenceLiftData,liftData,edgeAssignment_first] using hv

/-- The second named factor uses the generated whole actual second-factor equivalence. -/
theorem coefficient_edge_second :
    (originalTower T chosen F).toTower.localCoefficients.edge (secondEdge K chosen) =
      rho2AddEquiv T chosen F := by
  apply AddEquiv.ext
  intro a
  have h := selected_edge_transport T chosen F (secondEdge K chosen)
  have hv := congrArg (fun rho => Additive.ofMul (rho (Additive.toMul a))) h
  simpa only [referenceLiftData,liftData,edgeAssignment_second] using hv

/-- Full original selected-edge transport is exactly the actual first-factor then second-factor transport. -/
theorem coefficient_transport_comp (a : T.toTower.localCoefficients.A chosen.1) :
    T.toTower.localCoefficients.edge chosen.2.2 a =
      rho2AddEquiv T chosen F (rho1AddEquiv T chosen F a) := by
  change Additive.ofMul
    ((kernelTransportHom p q (T.toTower.upper.edgeLift chosen.2.2)
      (T.toTower.upper.edgeStrong chosen.2.2) (T.toTower.lowerStrong chosen.2.2))
      (Additive.toMul a)) =
    Additive.ofMul ((rho2 T chosen F) ((rho1 T chosen F) (Additive.toMul a)))
  rw [transport_comp]
  rfl

end AAT.AG.RelativeRepairComposition.Subdivision
#assert_standard_axioms_only AAT.AG.RelativeRepairComposition.Subdivision
