import ResearchLean.AG.RelativeRepairComposition.SubdivisionRegionIncidence
import ResearchLean.AG.RelativeRepairComposition.IndexedClosedCovers

/-!
# Transport of complete closed covers through actual edge substitution

## Implementation notes

Every member is generated by expandedRegion, including the member containing
the chosen edge. Coverage follows by reading edgeOrigin and by placing the fresh
vertex in any member covering the chosen edge. Intersections retain that vertex
only when both members contain the edge, so a private chosen edge creates no
new overlap cells. A supplied new cover or overlap certificate is unnecessary.
-/
namespace AAT.AG.RelativeRepairComposition.Subdivision
open TransportCoherence
universe uG uI
variable (K : FiniteTransportPresentation.{uG}) (chosen : EdgeName (K := K))

/-- Equality of all four cell sets determines the entire closed region. -/
theorem closedRegion_eq {H : FiniteTransportPresentation.{uG}} (U V : ClosedRegion H)
    (hv : U.vertices = V.vertices) (he : U.edges = V.edges)
    (hf : U.faces = V.faces) (ht : U.triples = V.triples) : U = V := by
  cases U; cases V; cases hv; cases he; cases hf; cases ht; rfl

/-- Avoiding the chosen name makes full edge substitution exactly retained-name substitution. -/
theorem expanded_set_avoiding (S : Set (EdgeName (K := K))) (hs : chosen ∉ S) :
    expandedEdgeSet K chosen S = oldEdgeSet K chosen S := by
  ext a
  constructor
  · intro ha
    have hn : edgeOrigin K chosen a ≠ chosen := fun h => hs (h ▸ ha)
    exact ⟨⟨edgeOrigin K chosen a,hn⟩,ha,
      ((edgeOrigin_eq_old K chosen a _ hn).mp rfl).symm⟩
  · rintro ⟨e,he,rfl⟩
    exact he

/-- Full region generation agrees with the accepted retained region when the chosen edge is absent. -/
theorem expanded_region_avoiding (U : ClosedRegion K) (hu : chosen ∉ U.edges) :
    expandedRegion K chosen U = oldRegion K chosen U hu := by
  apply closedRegion_eq
  · ext v
    cases v with
    | inl a =>
      change a ∈ U.vertices ↔ ∃ x ∈ U.vertices, Sum.inl x = (Sum.inl a : Vertex K)
      constructor
      · intro h; exact ⟨a,h,rfl⟩
      · rintro ⟨x,h,hx⟩
        exact (Sum.inl.inj hx) ▸ h
    | inr b => simp [expandedRegion,expandedVertexSet,oldRegion,hu]
  · exact expanded_set_avoiding K chosen U.edges hu
  · rfl
  · rfl

/-- All four sets of an original inclusion transport through the same substitution. -/
theorem expanded_inclusion {U V : ClosedRegion K} (h : ClosedRegion.Inclusion U V) :
    ClosedRegion.Inclusion (expandedRegion K chosen U) (expandedRegion K chosen V) := by
  refine ⟨?_,expanded_set_mono K chosen h.edges,h.faces,h.triples⟩
  intro v hv
  cases v with
  | inl a => exact h.vertices hv
  | inr b => exact h.edges hv

/-- Intersections preserve every original cell and the exact fresh membership. -/
theorem expanded_inter (U V : ClosedRegion K) :
    expandedRegion K chosen (ClosedRegion.inter U V) =
      ClosedRegion.inter (expandedRegion K chosen U) (expandedRegion K chosen V) := by
  apply closedRegion_eq
  · ext v; cases v <;> rfl
  · rfl
  · rfl
  · rfl

/-- Unions transport without changing any authored face or complete route. -/
theorem expanded_union (U V : ClosedRegion K) :
    expandedRegion K chosen (ClosedRegion.union U V) =
      ClosedRegion.union (expandedRegion K chosen U) (expandedRegion K chosen V) := by
  apply closedRegion_eq
  · ext v; cases v <;> rfl
  · rfl
  · rfl
  · rfl

/-- Indexed assembly retains the same family index and every substituted cell. -/
theorem expanded_indexed_union {I : Type uI} (U : I → ClosedRegion K) :
    expandedRegion K chosen (ClosedRegion.indexedUnion U) =
      ClosedRegion.indexedUnion (fun i => expandedRegion K chosen (U i)) := by
  apply closedRegion_eq
  · ext v; cases v <;> rfl
  · rfl
  · rfl
  · rfl

/-- The original complete region generates the entire new presentation. -/
theorem expanded_all : expandedRegion K chosen ClosedRegion.all = ClosedRegion.all := by
  apply closedRegion_eq
  · ext v; cases v <;> rfl
  · rfl
  · rfl
  · rfl

/-- Every original indexed 0–3 cover generates a complete indexed cover of the new presentation. -/
theorem expanded_indexed_cover {I : Type uI} (U : I → ClosedRegion K)
    (hc : ClosedRegion.IndexedCover U) :
    ClosedRegion.IndexedCover (fun i => expandedRegion K chosen (U i)) := by
  refine ⟨?_,?_,hc.faces,hc.triples⟩
  · intro v
    cases v with
    | inl a => exact hc.vertices a
    | inr b => exact hc.edges chosen
  · intro e
    exact hc.edges (edgeOrigin K chosen e)

/-- A chosen edge occurring in at most one member occurs in no overlap of distinct members. -/
theorem chosen_not_overlap {I : Type uI} (U : I → ClosedRegion K)
    (hu : ∀ i j, chosen ∈ (U i).edges → chosen ∈ (U j).edges → i = j)
    (i j : I) (hij : i ≠ j) : chosen ∉ (ClosedRegion.inter (U i) (U j)).edges := by
  intro h
  exact hij (hu i j h.1 h.2)

/-- Distinct overlaps of a private chosen edge retain precisely their old region, with no new vertex or factor. -/
theorem expanded_overlap_retained {I : Type uI} (U : I → ClosedRegion K)
    (hu : ∀ i j, chosen ∈ (U i).edges → chosen ∈ (U j).edges → i = j)
    (i j : I) (hij : i ≠ j) :
    ClosedRegion.inter (expandedRegion K chosen (U i)) (expandedRegion K chosen (U j)) =
      oldRegion K chosen (ClosedRegion.inter (U i) (U j))
        (chosen_not_overlap K chosen U hu i j hij) := by
  rw [← expanded_inter]
  exact expanded_region_avoiding K chosen _ _

end AAT.AG.RelativeRepairComposition.Subdivision
#assert_standard_axioms_only AAT.AG.RelativeRepairComposition.Subdivision
