import ResearchLean.AG.RelativeRepairComposition.SymbolicInterface
import ResearchLean.AG.RelativeRepairComposition.NativeLocalInterface

/-!
# Symbolic fibres use the original one-time finite generator

## Implementation notes

The defect parameter map is restricted and written in the existing full original
face coordinates. The private matrix, elimination and section are those of the
same fixed local system and original private set. Each fibre evaluates to the
existing generated objects, then reconstructs the independent original equation.
-/
namespace AAT.AG.RelativeRepairComposition
open CategoryTheory TransportCoherence AbelianLiftingObstruction FiniteCoefficients
universe uk uG uA uV
namespace SymbolicNativeLocal
variable {k : Type uk} [Field k] {V : Type uV} [AddCommGroup V] [Module k V]
variable {K : FiniteTransportPresentation.{uG}} (M : LocalCoefficients.{uG,uA} K)
variable [∀ v, Module k (M.A v)]
variable (bases : FiniteFamily.Bases (k := k) M.A) (U P : ClosedRegion K)
variable [DecidablePred (· ∈ P.vertices)] [DecidablePred (· ∈ P.edges)] [DecidablePred (· ∈ P.faces)]
variable [DecidablePred (· ∈ U.vertices)] [DecidablePred (· ∈ U.edges)]
variable (δ₀ : RelativeCover.C2 M ClosedRegion.all P)
variable (Δ : V →ₗ[k] RelativeCover.C2 M ClosedRegion.all P)

/-- The original full defect family is evaluated on the same native relative face space. -/
def defectFamily (v : V) : RelativeCover.C2 M ClosedRegion.all P := δ₀ + Δ v

/-- The entire local right-hand side is generated by original restriction and full coordinates. -/
def rhsMap : RelativeCover.C2 M ClosedRegion.all P →ₗ[k] (FiniteNative.Index2 M bases U P → k) where
  toFun δ := FiniteNative.rhs M bases U P δ
  map_add' δ ε := by
    unfold FiniteNative.rhs CoverEquation.defect
    rw [map_add, neg_add, map_add]
  map_smul' t δ := by
    unfold FiniteNative.rhs CoverEquation.defect
    have hr : RelativeCover.r2 M P (ClosedRegion.to_all U) (t • δ) =
        t • RelativeCover.r2 M P (ClosedRegion.to_all U) δ := Subtype.ext rfl
    rw [hr, ← smul_neg, map_smul]
    rfl

/-- The parameter linear term is generated from the same original local restriction and full coordinates. -/
def rhsLinear : V →ₗ[k] (FiniteNative.Index2 M bases U P → k) := (rhsMap M bases U P).comp Δ

omit [DecidablePred (· ∈ P.vertices)] [DecidablePred (· ∈ P.edges)]
  [DecidablePred (· ∈ U.vertices)] [DecidablePred (· ∈ U.edges)] in
/-- Every evaluated local right-hand side is exactly the base term plus its generated parameter term. -/
theorem rhs_affine (v : V) :
    FiniteNative.rhs M bases U P (defectFamily M P δ₀ Δ v) =
      SymbolicInterface.rhs (rhsLinear M bases U P Δ) (FiniteNative.rhs M bases U P δ₀) v := by
  exact (rhsMap M bases U P).map_add δ₀ (Δ v)

variable (internalEdges : Set (EdgeName (K := K))) [DecidablePred (· ∈ internalEdges)]
variable (hlinear : ∀ {i j : K.Vertex} (e : K.Edge i j) (t : k) (x : M.A i),
  M.edge e (t • x) = t • M.edge e x)
variable [Fintype k] [DecidableEq k]
variable [Fintype (EdgeName (K := K))] [DecidableEq (EdgeName (K := K))]
variable [Fintype K.TwoCell] [DecidableEq K.TwoCell] [DecidablePred (· ∈ U.faces)]
variable (ek : FiniteElimination.Enumeration k)
variable (ee : FiniteElimination.Enumeration (EdgeName (K := K)))
variable (ef : FiniteElimination.Enumeration K.TwoCell)
local notation "D" => FiniteNative.D M bases U P internalEdges hlinear
local notation "F" => FiniteNative.F M bases U P internalEdges hlinear
local notation "σ" => FiniteNative.generatedSection M bases U P internalEdges hlinear ek ee ef
local notation "r₀" => FiniteNative.rhs M bases U P δ₀
local notation "B" => rhsLinear M bases U P Δ

/-- The single symbolic local relation is constructed before any parameter value or allowed range. -/
abbrev Fiber (v : V) := SymbolicInterface.RelationFiber D F σ B r₀ v × LinearMap.ker D

/-- Both directions of evaluation preserve the same public values and the full original private kernel. -/
def fiberEquiv (v : V) : Fiber M bases U P δ₀ Δ internalEdges hlinear ek ee ef v ≃
    FiniteNative.GeneratedObjects M bases U P internalEdges hlinear (defectFamily M P δ₀ Δ v) ek ee ef where
  toFun y := (⟨y.1.1,by
    change LinearInterface.projection D σ (F y.1.1) =
      LinearInterface.projection D σ (FiniteNative.rhs M bases U P (defectFamily M P δ₀ Δ v))
    rw [rhs_affine]
    exact (SymbolicInterface.relation_evaluation D F σ B r₀ v y.1.1).mp y.1.2⟩,y.2)
  invFun y := (⟨y.1.1,by
    apply (SymbolicInterface.relation_evaluation D F σ B r₀ v y.1.1).mpr
    rw [← rhs_affine]
    exact y.1.2⟩,y.2)
  left_inv _ := rfl
  right_inv _ := rfl

/-- Symbolic evaluation followed by full generation restores the independently defined original local equation. -/
def originalEquationEquiv (v : V) : Fiber M bases U P δ₀ Δ internalEdges hlinear ek ee ef v ≃
    CoverEquation.Solution M P (defectFamily M P δ₀ Δ v) U :=
  (fiberEquiv M bases U P δ₀ Δ internalEdges hlinear ek ee ef v).trans
    (FiniteNative.generatedSolutionEquiv M bases U P internalEdges hlinear
      (defectFamily M P δ₀ Δ v) ek ee ef).symm

omit [DecidablePred (· ∈ P.vertices)] in
/-- Every public coordinate is identical after symbolic evaluation. -/
theorem fiber_public (v : V) (y : Fiber M bases U P δ₀ Δ internalEdges hlinear ek ee ef v) :
    (fiberEquiv M bases U P δ₀ Δ internalEdges hlinear ek ee ef v y).1.1 = y.1.1 := rfl

omit [DecidablePred (· ∈ P.vertices)] in
/-- Every internal kernel coordinate is identical after symbolic evaluation. -/
theorem fiber_private (v : V) (y : Fiber M bases U P δ₀ Δ internalEdges hlinear ek ee ef v) :
    (fiberEquiv M bases U P δ₀ Δ internalEdges hlinear ek ee ef v y).2 = y.2 := rfl

end SymbolicNativeLocal
end AAT.AG.RelativeRepairComposition
#assert_standard_axioms_only AAT.AG.RelativeRepairComposition
