import ResearchLean.AG.RelativeRepairComposition.W5AuthoredOperations
import ResearchLean.AG.RelativeRepairComposition.NativeAffineDifferentials

/-!
# W5's complete original kernels, transport, differential and actual defect

The full categorical kernel coordinates come from the original whole affine
projection. Original words derive d1(u,a,b)=(u-a,u-b) before imposing P.
The actual reference words, including the two input translations, derive the
signed defect without an externally supplied cocycle or vanishing condition.
-/
namespace AAT.AG.RelativeRepairComposition.W5OriginalDifferentials
open CategoryTheory TransportCoherence TransportCoherence.Arbitrary AbelianLiftingObstruction
open NativeAffine W5AffineInput W5AuthoredOperations
variable (b₁ b₂ : ZMod 2)
local notation "T" => originalTower b₁ b₂
local notation "M" => TowerPresentation.localCoefficients (OriginalTowerPresentation.toTower T)

/-- Each complete original categorical kernel is linearly equivalent to the whole F2 space. -/
noncomputable def kernelCoordinate (v : geometry.Vertex) : (M).A v ≃ₗ[ZMod 2] ZMod 2 :=
  NativeAffine.linearCoefficient geometry (reference b₁ b₂) (reference b₁ b₂)
    comparison (linear_faces b₁ b₂) v
/-- Every full coordinate inverse includes as its actual original affine translation. -/
theorem kernel_inverse_value (v : geometry.Vertex) (a : ZMod 2) :
    FiberAut.hom (kernelInclusion
      (GroupExtension.projection (projection (k := ZMod 2) (A := ZMod 2)))
      (GroupExtension.terminal (ZMod 2 ≃ₗ[ZMod 2] ZMod 2)) ((T).original.object v)
      (Additive.toMul ((kernelCoordinate b₁ b₂ v).symm a))) = translation (k := ZMod 2) a :=
  NativeAffine.coefficient_inverse_value geometry (reference b₁ b₂) (reference b₁ b₂)
    comparison (linear_faces b₁ b₂) v a
/-- All original complete-kernel transports are linear, generated by the actual reference maps. -/
theorem original_linear {i j : geometry.Vertex} (e : geometry.Edge i j)
    (t : ZMod 2) (a : (M).A i) : (M).edge e (t • a) = t • (M).edge e a :=
  NativeAffine.edge_linear geometry (reference b₁ b₂) (reference b₁ b₂)
    comparison (linear_faces b₁ b₂) e t a
/-- The whole original kernel transport is identity in these full coordinates. -/
theorem original_transport {i j : geometry.Vertex} (e : geometry.Edge i j) (a : (M).A i) :
    kernelCoordinate b₁ b₂ j ((M).edge e a) = kernelCoordinate b₁ b₂ i a := by
  change NativeAffine.coefficient geometry (reference b₁ b₂) (reference b₁ b₂)
      comparison (linear_faces b₁ b₂) j ((M).edge e a) = _
  rw [NativeAffine.edge_coefficient,reference_linear]
  rfl
/-- Every original degree-zero differential retains the actual target-minus-source values. -/
theorem d0_value (a : C0 M) (e : EdgeName (K := geometry)) :
    kernelCoordinate b₁ b₂ e.2.1 (d0 M a e) =
      kernelCoordinate b₁ b₂ e.2.1 (a e.2.1) - kernelCoordinate b₁ b₂ e.1 (a e.1) := by
  change NativeAffine.coefficient geometry (reference b₁ b₂) (reference b₁ b₂)
      comparison (linear_faces b₁ b₂) e.2.1 (d0 M a e) = _
  rw [NativeAffine.d0_value,reference_linear]
  rfl
/-- The complete original face differential is u minus the corresponding physical-edge correction. -/
theorem d1_value (a : C1 M) (f : Bool) :
    kernelCoordinate b₁ b₂ vertexT (d1 M a f) =
      kernelCoordinate b₁ b₂ vertexT (a (name edgeE)) -
        kernelCoordinate b₁ b₂ vertexT (a (name (if f then edgeB else edgeA))) := by
  refine (NativeAffine.d1_value geometry (reference b₁ b₂) (reference b₁ b₂)
    comparison (linear_faces b₁ b₂) a f).trans ?_
  cases f <;> simp [geometry,vectorPath,GroupExtension.pathValue,name] <;> rfl
/-- The same original degree-two differential vanishes on the specified empty three-cell family. -/
theorem d2_zero (a : C2 M) : d2 M a = 0 := by
  funext s
  exact s.elim
/-- The inverse whole input translation evaluates at the same negative input value. -/
theorem translation_inverse_apply (a x : ZMod 2) :
    ((translation (k := ZMod 2) a)⁻¹ : Op) x = -a + x := by
  change (AffineEquiv.constVAdd (ZMod 2) (ZMod 2) a).symm x = _
  rw [AffineEquiv.constVAdd_symm]
  rfl
/-- The full original actual defect is (-b1,-b2), derived from the real ordered words. -/
theorem defect_coordinate (f : Bool) :
    kernelCoordinate b₁ b₂ vertexT ((T).toTower.defect f) = -inputValue b₁ b₂ f := by
  have hv := NativeAffine.defect_value geometry (reference b₁ b₂) (reference b₁ b₂)
    comparison (linear_faces b₁ b₂) f
  rw [reference_left_path,reference_right_path,comparison,zero_translation,one_mul,one_mul] at hv
  exact hv.trans (by rw [translation_inverse_apply,add_zero]; cases f <;> rfl)

end AAT.AG.RelativeRepairComposition.W5OriginalDifferentials
#assert_standard_axioms_only AAT.AG.RelativeRepairComposition.W5OriginalDifferentials
