import Mathlib.AlgebraicGeometry.Modules.Tilde
import ResearchLean.AG.QualitySurface.IntrinsicLawResponseCircuitDescent.SemanticOperationDerivation

/-!
# Ambient-to-quotient derivation coefficient sheaf

This file constructs the J3a coefficient sheaf from the single ambient module
`Der_k(A₀, A₀/I₀)`.  Its `tilde` sheaf on `Spec(A₀/I₀)` is restricted to the
open union generated by the selected chart denominators.  Every operation
label gives a section on that union, and localization readout maps recover the
J2 chart and overlap quotient-valued derivations.

## Implementation notes

The coefficient object is the module sheaf obtained from the ambient
quotient derivation module by `tilde` and open restriction.  It is not
identified with a sheaf of all local derivations.  In particular, no
base-change equivalence
`Bᵢ ⊗[B₀] Der_k(A₀,B₀) ≃ Der_k(Aᵢ,Bᵢ)` is asserted.  The comparison
maps instead use the universal property of localized modules and localized
Kähler differentials.  Their selected-operation recovery theorems connect
directly to J2, including its left and right restriction naturality.
-/

open CategoryTheory
open TopologicalSpace
open scoped AlgebraicGeometry

namespace ResearchLean.AG.QualitySurface.IntrinsicLawResponseCircuitDescent

universe uk uA uOp uChart uState uBefore uAfter

namespace TypedLocalizationGeometry

variable {k : Type uk} {A0 : Type uA} {Chart : Type uChart}
variable [Field k] [CommRing A0] [Algebra k A0] [Fintype Chart]

namespace DerivationLocalization

variable {S : Type*} [CommRing S] [Algebra k S] [Algebra A0 S]
variable [IsScalarTower k A0 S]

/-- Extend a derivation with already-local coefficients across a localization. -/
noncomputable def extend
    (M : Submonoid A0) [IsLocalization M S]
    (T : Type*) [CommRing T] [Algebra k T] [Algebra A0 T] [Algebra S T]
    [IsScalarTower k A0 T] [IsScalarTower k S T] [IsScalarTower A0 S T]
    (d : Derivation k A0 T) : Derivation k S T :=
  let omegaMap : KaehlerDifferential k A0 →ₗ[A0] KaehlerDifferential k S :=
    KaehlerDifferential.map k k A0 S
  let localized : KaehlerDifferential k S →ₗ[A0] T :=
    IsLocalizedModule.lift M omegaMap d.liftKaehlerDifferential (fun m ↦ by
      rw [← (Algebra.lsmul A0 (A := S) A0 T).commutes]
      exact (IsLocalization.map_units S m).map _)
  (localized.extendScalarsOfIsLocalization M S).compDer
    (KaehlerDifferential.D k S)

@[simp] theorem extend_algebraMap
    (M : Submonoid A0) [IsLocalization M S]
    (T : Type*) [CommRing T] [Algebra k T] [Algebra A0 T] [Algebra S T]
    [IsScalarTower k A0 T] [IsScalarTower k S T] [IsScalarTower A0 S T]
    (d : Derivation k A0 T) (a : A0) :
    extend (k := k) M T d (algebraMap A0 S a) = d a := by
  dsimp [extend]
  rw [← KaehlerDifferential.map_D k k A0 S a]
  rw [IsLocalizedModule.lift_apply]
  simp

end DerivationLocalization

/-- The lawful ambient coordinate ring. -/
abbrev ambientLawQuotient (I0 : Ideal A0) := A0 ⧸ I0

/-- The affine lawful ambient scheme. -/
noncomputable abbrev ambientLawSpec (I0 : Ideal A0) : AlgebraicGeometry.Scheme :=
  AlgebraicGeometry.Spec (.of (ambientLawQuotient I0))

/-- The principal open selected by one chart denominator after quotienting. -/
noncomputable def lawfulChartOpen
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart) :
    (ambientLawSpec I0).Opens :=
  PrimeSpectrum.basicOpen (R := ambientLawQuotient I0)
    (Ideal.Quotient.mk I0 (G.denominator i))

/-- The principal open selected by a pair of chart denominators after quotienting. -/
noncomputable def lawfulOverlapOpen
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    (ambientLawSpec I0).Opens :=
  PrimeSpectrum.basicOpen (R := ambientLawQuotient I0)
    (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j))

/-- The canonical coefficient map from the ambient law quotient to one chart quotient. -/
noncomputable def chartLawQuotientMap
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart) :
    ambientLawQuotient I0 →ₐ[k] G.chartLawQuotient I0 i :=
  Ideal.quotientMapₐ (G.chartLawIdeal I0 i)
    ((Algebra.ofId A0 (G.chartRing i)).restrictScalars k)
    (Ideal.le_comap_map)

/-- The canonical coefficient map from the ambient law quotient to one overlap quotient. -/
noncomputable def overlapLawQuotientMap
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    ambientLawQuotient I0 →ₐ[k] G.overlapLawQuotient I0 i j :=
  Ideal.quotientMapₐ (G.overlapLawIdeal I0 i j)
    ((Algebra.ofId A0 (G.overlapRing i j)).restrictScalars k)
    (Ideal.le_comap_map)

theorem isUnit_chartLawQuotientMap_denominator
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart) :
    IsUnit (G.chartLawQuotientMap I0 i
      (Ideal.Quotient.mk I0 (G.denominator i))) := by
  have h : IsUnit
      (algebraMap A0 (G.chartRing i) (G.denominator i)) :=
    IsLocalization.Away.algebraMap_isUnit (G.denominator i)
  exact h.map (Ideal.Quotient.mk (G.chartLawIdeal I0 i))

theorem isUnit_overlapLawQuotientMap_denominator
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    IsUnit (G.overlapLawQuotientMap I0 i j
      (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j))) := by
  have h : IsUnit
      (algebraMap A0 (G.overlapRing i j)
        (G.denominator i * G.denominator j)) :=
    IsLocalization.Away.algebraMap_isUnit
      (G.denominator i * G.denominator j)
  exact h.map (Ideal.Quotient.mk (G.overlapLawIdeal I0 i j))

/-- Localize one ambient quotient-valued derivation to a selected chart. -/
noncomputable def chartAmbientComparison
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart)
    (d : Derivation k A0 (ambientLawQuotient I0)) :
    Derivation k (G.chartRing i) (G.chartLawQuotient I0 i) := by
  let φ := G.chartLawQuotientMap I0 i
  letI : Algebra (ambientLawQuotient I0) (G.chartLawQuotient I0 i) :=
    φ.toRingHom.toAlgebra
  letI : IsScalarTower A0 (ambientLawQuotient I0) (G.chartLawQuotient I0 i) :=
    .of_algebraMap_eq fun a ↦ by rfl
  let d' : Derivation k A0 (G.chartLawQuotient I0 i) :=
    ((Algebra.linearMap (ambientLawQuotient I0)
      (G.chartLawQuotient I0 i)).restrictScalars A0).compDer d
  exact DerivationLocalization.extend (Submonoid.powers (G.denominator i))
    (G.chartLawQuotient I0 i) d'

@[simp] theorem chartAmbientComparison_algebraMap
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart)
    (d : Derivation k A0 (ambientLawQuotient I0)) (a : A0) :
    G.chartAmbientComparison I0 i d (algebraMap A0 (G.chartRing i) a) =
      G.chartLawQuotientMap I0 i (d a) := by
  simp [chartAmbientComparison, DerivationLocalization.extend_algebraMap]
  rfl

/-- Localize one ambient quotient-valued derivation to a selected overlap. -/
noncomputable def overlapAmbientComparison
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart)
    (d : Derivation k A0 (ambientLawQuotient I0)) :
    Derivation k (G.overlapRing i j) (G.overlapLawQuotient I0 i j) := by
  let φ := G.overlapLawQuotientMap I0 i j
  letI : Algebra (ambientLawQuotient I0) (G.overlapLawQuotient I0 i j) :=
    φ.toRingHom.toAlgebra
  letI : IsScalarTower A0 (ambientLawQuotient I0) (G.overlapLawQuotient I0 i j) :=
    .of_algebraMap_eq fun a ↦ by rfl
  let d' : Derivation k A0 (G.overlapLawQuotient I0 i j) :=
    ((Algebra.linearMap (ambientLawQuotient I0)
      (G.overlapLawQuotient I0 i j)).restrictScalars A0).compDer d
  exact DerivationLocalization.extend
    (Submonoid.powers (G.denominator i * G.denominator j))
    (G.overlapLawQuotient I0 i j) d'

@[simp] theorem overlapAmbientComparison_algebraMap
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart)
    (d : Derivation k A0 (ambientLawQuotient I0)) (a : A0) :
    G.overlapAmbientComparison I0 i j d
        (algebraMap A0 (G.overlapRing i j) a) =
      G.overlapLawQuotientMap I0 i j (d a) := by
  simp [overlapAmbientComparison, DerivationLocalization.extend_algebraMap]
  rfl

/-- The chart comparison, linear over the ambient lawful quotient. -/
noncomputable def chartAmbientComparisonLinear
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart) :
    letI : Algebra (ambientLawQuotient I0) (G.chartLawQuotient I0 i) :=
      (G.chartLawQuotientMap I0 i).toRingHom.toAlgebra
    Derivation k A0 (ambientLawQuotient I0) →ₗ[ambientLawQuotient I0]
      Derivation k (G.chartRing i) (G.chartLawQuotient I0 i) := by
  letI : Algebra (ambientLawQuotient I0) (G.chartLawQuotient I0 i) :=
    (G.chartLawQuotientMap I0 i).toRingHom.toAlgebra
  exact
    { toFun := G.chartAmbientComparison I0 i
      map_add' := fun d e ↦ by
        apply AmbientOperationLocalization.derivation_ext_of_isLocalization
          (G.chartRing i) (Submonoid.powers (G.denominator i))
        intro a
        simp
      map_smul' := fun r d ↦ by
        apply AmbientOperationLocalization.derivation_ext_of_isLocalization
          (G.chartRing i) (Submonoid.powers (G.denominator i))
        intro a
        simp
        rfl }

/-- The overlap comparison, linear over the ambient lawful quotient. -/
noncomputable def overlapAmbientComparisonLinear
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    letI : Algebra (ambientLawQuotient I0) (G.overlapLawQuotient I0 i j) :=
      (G.overlapLawQuotientMap I0 i j).toRingHom.toAlgebra
    Derivation k A0 (ambientLawQuotient I0) →ₗ[ambientLawQuotient I0]
      Derivation k (G.overlapRing i j) (G.overlapLawQuotient I0 i j) := by
  letI : Algebra (ambientLawQuotient I0) (G.overlapLawQuotient I0 i j) :=
    (G.overlapLawQuotientMap I0 i j).toRingHom.toAlgebra
  exact
    { toFun := G.overlapAmbientComparison I0 i j
      map_add' := fun d e ↦ by
        apply AmbientOperationLocalization.derivation_ext_of_isLocalization
          (G.overlapRing i j)
          (Submonoid.powers (G.denominator i * G.denominator j))
        intro a
        simp
      map_smul' := fun r d ↦ by
        apply AmbientOperationLocalization.derivation_ext_of_isLocalization
          (G.overlapRing i j)
          (Submonoid.powers (G.denominator i * G.denominator j))
        intro a
        simp
        rfl }

/-- The open union generated by the selected chart denominators. -/
noncomputable def lawfulOpen
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) :
    (ambientLawSpec I0).Opens :=
  ⨆ i, G.lawfulChartOpen I0 i

theorem lawfulChartOpen_le_lawfulOpen
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart) :
    G.lawfulChartOpen I0 i ≤ G.lawfulOpen I0 :=
  le_iSup (fun j ↦ G.lawfulChartOpen I0 j) i

theorem lawfulOverlapOpen_eq_inf
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    G.lawfulOverlapOpen I0 i j =
      G.lawfulChartOpen I0 i ⊓ G.lawfulChartOpen I0 j := by
  simp [lawfulOverlapOpen, lawfulChartOpen, PrimeSpectrum.basicOpen_mul]

theorem lawfulOverlapOpen_le_lawfulOpen
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    G.lawfulOverlapOpen I0 i j ≤ G.lawfulOpen I0 := by
  rw [G.lawfulOverlapOpen_eq_inf I0 i j]
  exact inf_le_left.trans (G.lawfulChartOpen_le_lawfulOpen I0 i)

/-- The lawful locally affine space generated by the selected charts. -/
noncomputable abbrev lawfulSpace
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) :
    AlgebraicGeometry.Scheme :=
  (G.lawfulOpen I0).toScheme

/-- A selected chart as an open of the generated lawful space. -/
noncomputable def lawfulChartOpenOnSpace
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart) :
    (G.lawfulSpace I0).Opens :=
  (G.lawfulOpen I0).ι ⁻¹ᵁ G.lawfulChartOpen I0 i

/-- A selected overlap as an open of the generated lawful space. -/
noncomputable def lawfulOverlapOpenOnSpace
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    (G.lawfulSpace I0).Opens :=
  (G.lawfulOpen I0).ι ⁻¹ᵁ G.lawfulOverlapOpen I0 i j

theorem image_lawfulChartOpenOnSpace
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart) :
    (G.lawfulOpen I0).ι ''ᵁ G.lawfulChartOpenOnSpace I0 i =
      G.lawfulChartOpen I0 i := by
  rw [lawfulChartOpenOnSpace,
    AlgebraicGeometry.Scheme.Hom.image_preimage_eq_opensRange_inf,
    AlgebraicGeometry.Scheme.Opens.opensRange_ι, inf_eq_right]
  exact G.lawfulChartOpen_le_lawfulOpen I0 i

theorem image_lawfulOverlapOpenOnSpace
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    (G.lawfulOpen I0).ι ''ᵁ G.lawfulOverlapOpenOnSpace I0 i j =
      G.lawfulOverlapOpen I0 i j := by
  rw [lawfulOverlapOpenOnSpace,
    AlgebraicGeometry.Scheme.Hom.image_preimage_eq_opensRange_inf,
    AlgebraicGeometry.Scheme.Opens.opensRange_ι, inf_eq_right]
  exact G.lawfulOverlapOpen_le_lawfulOpen I0 i j

/-- The ambient-to-quotient derivation module. -/
abbrev ambientDerivationModule (I0 : Ideal A0) :=
  ModuleCat.of (ambientLawQuotient I0)
    (Derivation k A0 (ambientLawQuotient I0))

/-- The single ambient-to-quotient derivation sheaf on the affine lawful ambient scheme. -/
noncomputable def ambientDerivationSheaf (I0 : Ideal A0) :
    (ambientLawSpec I0).Modules :=
  AlgebraicGeometry.tilde (ambientDerivationModule (k := k) I0)

/-- The tilde section map on a selected chart is the corresponding module localization. -/
noncomputable def chartToOpenIsLocalized
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart) :
    IsLocalizedModule
      (Submonoid.powers (Ideal.Quotient.mk I0 (G.denominator i)))
      (AlgebraicGeometry.tilde.toOpen
        (ambientDerivationModule (k := k) I0) (G.lawfulChartOpen I0 i)).hom := by
  letI : IsLocalizedModule
      (Submonoid.powers (Ideal.Quotient.mk I0 (G.denominator i)))
      (AlgebraicGeometry.StructureSheaf.toOpenₗ (ambientLawQuotient I0)
        (ambientDerivationModule (k := k) I0) (G.lawfulChartOpen I0 i)) := by
    change IsLocalizedModule
      (Submonoid.powers (Ideal.Quotient.mk I0 (G.denominator i)))
      (AlgebraicGeometry.StructureSheaf.toOpenₗ (ambientLawQuotient I0)
        (ambientDerivationModule (k := k) I0)
        (PrimeSpectrum.basicOpen (Ideal.Quotient.mk I0 (G.denominator i))))
    infer_instance
  exact IsLocalizedModule.of_linearEquiv
    (Submonoid.powers (Ideal.Quotient.mk I0 (G.denominator i)))
    (AlgebraicGeometry.StructureSheaf.toOpenₗ (ambientLawQuotient I0)
      (ambientDerivationModule (k := k) I0) (G.lawfulChartOpen I0 i))
    ((AlgebraicGeometry.tilde.modulesSpecToSheafIso
      (R := .of (ambientLawQuotient I0))
      (ambientDerivationModule (k := k) I0)).app _).toLinearEquiv.symm

/-- The tilde section map on a selected overlap is the corresponding module localization. -/
noncomputable def overlapToOpenIsLocalized
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    IsLocalizedModule
      (Submonoid.powers
        (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j)))
      (AlgebraicGeometry.tilde.toOpen
        (ambientDerivationModule (k := k) I0)
        (G.lawfulOverlapOpen I0 i j)).hom := by
  let overlapOpen : (ambientLawSpec I0).Opens := G.lawfulOverlapOpen I0 i j
  letI : IsLocalizedModule
      (Submonoid.powers
        (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j)))
      (AlgebraicGeometry.StructureSheaf.toOpenₗ (ambientLawQuotient I0)
        (ambientDerivationModule (k := k) I0) overlapOpen) := by
    change IsLocalizedModule
      (Submonoid.powers
        (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j)))
      (AlgebraicGeometry.StructureSheaf.toOpenₗ (ambientLawQuotient I0)
        (ambientDerivationModule (k := k) I0)
        (PrimeSpectrum.basicOpen
          (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j))))
    infer_instance
  exact IsLocalizedModule.of_linearEquiv
    (Submonoid.powers
      (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j)))
    (AlgebraicGeometry.StructureSheaf.toOpenₗ (ambientLawQuotient I0)
      (ambientDerivationModule (k := k) I0) overlapOpen)
    ((AlgebraicGeometry.tilde.modulesSpecToSheafIso
      (R := .of (ambientLawQuotient I0))
      (ambientDerivationModule (k := k) I0)).app _).toLinearEquiv.symm

/-- Read a section on a selected basic open as a chart derivation. -/
noncomputable def chartSectionToDerivation
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart) :
    letI : Algebra (ambientLawQuotient I0) (G.chartLawQuotient I0 i) :=
      (G.chartLawQuotientMap I0 i).toRingHom.toAlgebra
    (AlgebraicGeometry.modulesSpecToSheaf.obj
        (ambientDerivationSheaf (k := k) I0)).presheaf.obj
          (.op (G.lawfulChartOpen I0 i)) →ₗ[ambientLawQuotient I0]
      Derivation k (G.chartRing i) (G.chartLawQuotient I0 i) := by
  letI : Algebra (ambientLawQuotient I0) (G.chartLawQuotient I0 i) :=
    (G.chartLawQuotientMap I0 i).toRingHom.toAlgebra
  let source := AlgebraicGeometry.tilde.toOpen
    (ambientDerivationModule (k := k) I0) (G.lawfulChartOpen I0 i)
  letI : IsLocalizedModule
      (Submonoid.powers (Ideal.Quotient.mk I0 (G.denominator i))) source.hom :=
    G.chartToOpenIsLocalized I0 i
  apply IsLocalizedModule.lift
    (Submonoid.powers (Ideal.Quotient.mk I0 (G.denominator i))) source.hom
    (G.chartAmbientComparisonLinear I0 i)
  intro s
  rw [← (Algebra.lsmul (ambientLawQuotient I0)
    (A := G.chartLawQuotient I0 i) (ambientLawQuotient I0)
    (Derivation k (G.chartRing i) (G.chartLawQuotient I0 i))).commutes]
  rcases s.2 with ⟨n, hn⟩
  rw [← hn, map_pow]
  exact (G.isUnit_chartLawQuotientMap_denominator I0 i).pow n |>.map _

@[simp] theorem chartSectionToDerivation_toOpen
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart)
    (d : Derivation k A0 (ambientLawQuotient I0)) :
    G.chartSectionToDerivation I0 i
        ((AlgebraicGeometry.tilde.toOpen
          (ambientDerivationModule (k := k) I0) (G.lawfulChartOpen I0 i)) d) =
      G.chartAmbientComparison I0 i d := by
  letI : Algebra (ambientLawQuotient I0) (G.chartLawQuotient I0 i) :=
    (G.chartLawQuotientMap I0 i).toRingHom.toAlgebra
  letI : IsLocalizedModule
      (Submonoid.powers (Ideal.Quotient.mk I0 (G.denominator i)))
      (AlgebraicGeometry.tilde.toOpen
        (ambientDerivationModule (k := k) I0) (G.lawfulChartOpen I0 i)).hom :=
    G.chartToOpenIsLocalized I0 i
  unfold chartSectionToDerivation
  apply IsLocalizedModule.lift_apply

/-- Read a section on a selected overlap basic open as an overlap derivation. -/
noncomputable def overlapSectionToDerivation
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart) :
    letI : Algebra (ambientLawQuotient I0) (G.overlapLawQuotient I0 i j) :=
      (G.overlapLawQuotientMap I0 i j).toRingHom.toAlgebra
    (AlgebraicGeometry.modulesSpecToSheaf.obj
        (ambientDerivationSheaf (k := k) I0)).presheaf.obj
          (.op (G.lawfulOverlapOpen I0 i j))
        →ₗ[ambientLawQuotient I0]
      Derivation k (G.overlapRing i j) (G.overlapLawQuotient I0 i j) := by
  letI : Algebra (ambientLawQuotient I0) (G.overlapLawQuotient I0 i j) :=
    (G.overlapLawQuotientMap I0 i j).toRingHom.toAlgebra
  let overlapOpen : (ambientLawSpec I0).Opens := G.lawfulOverlapOpen I0 i j
  let source := AlgebraicGeometry.tilde.toOpen
    (ambientDerivationModule (k := k) I0) overlapOpen
  letI : IsLocalizedModule
      (Submonoid.powers
        (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j))) source.hom :=
    G.overlapToOpenIsLocalized I0 i j
  apply IsLocalizedModule.lift
    (Submonoid.powers
      (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j))) source.hom
    (G.overlapAmbientComparisonLinear I0 i j)
  intro s
  rw [← (Algebra.lsmul (ambientLawQuotient I0)
    (A := G.overlapLawQuotient I0 i j) (ambientLawQuotient I0)
    (Derivation k (G.overlapRing i j) (G.overlapLawQuotient I0 i j))).commutes]
  rcases s.2 with ⟨n, hn⟩
  rw [← hn, map_pow]
  exact (G.isUnit_overlapLawQuotientMap_denominator I0 i j).pow n |>.map _

@[simp] theorem overlapSectionToDerivation_toOpen
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart)
    (d : Derivation k A0 (ambientLawQuotient I0)) :
    G.overlapSectionToDerivation I0 i j
        ((AlgebraicGeometry.tilde.toOpen
          (ambientDerivationModule (k := k) I0)
          (G.lawfulOverlapOpen I0 i j)) d) =
      G.overlapAmbientComparison I0 i j d := by
  letI : Algebra (ambientLawQuotient I0) (G.overlapLawQuotient I0 i j) :=
    (G.overlapLawQuotientMap I0 i j).toRingHom.toAlgebra
  letI : IsLocalizedModule
      (Submonoid.powers
        (Ideal.Quotient.mk I0 (G.denominator i * G.denominator j)))
      (AlgebraicGeometry.tilde.toOpen
        (ambientDerivationModule (k := k) I0)
        (G.lawfulOverlapOpen I0 i j)).hom :=
    G.overlapToOpenIsLocalized I0 i j
  unfold overlapSectionToDerivation
  apply IsLocalizedModule.lift_apply

/-- The derivation coefficient sheaf on the generated lawful space. -/
noncomputable def derivationCoefficientSheaf
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) :
    (G.lawfulSpace I0).Modules :=
  (ambientDerivationSheaf (k := k) I0).restrict (G.lawfulOpen I0).ι

theorem derivationCoefficientSheaf_isSheaf
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) :
    (AlgebraicGeometry.Scheme.Modules.presheaf
      (G.derivationCoefficientSheaf I0)).IsSheaf :=
  AlgebraicGeometry.Scheme.Modules.isSheaf _

/-- Read a coefficient-sheaf section on a lawful-space chart as a chart derivation. -/
noncomputable def chartSectionToDerivationOnSpace
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i : Chart)
    (s : (AlgebraicGeometry.Scheme.Modules.presheaf
      (G.derivationCoefficientSheaf I0)).obj (.op (G.lawfulChartOpenOnSpace I0 i))) :
    Derivation k (G.chartRing i) (G.chartLawQuotient I0 i) :=
  G.chartSectionToDerivation I0 i
    ((ambientDerivationSheaf (k := k) I0).presheaf.map
      (eqToHom (G.image_lawfulChartOpenOnSpace I0 i).symm).op s)

/-- Read a coefficient-sheaf section on a lawful-space overlap as an overlap derivation. -/
noncomputable def overlapSectionToDerivationOnSpace
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (i j : Chart)
    (s : (AlgebraicGeometry.Scheme.Modules.presheaf
      (G.derivationCoefficientSheaf I0)).obj (.op (G.lawfulOverlapOpenOnSpace I0 i j))) :
    Derivation k (G.overlapRing i j) (G.overlapLawQuotient I0 i j) :=
  G.overlapSectionToDerivation I0 i j
    ((ambientDerivationSheaf (k := k) I0).presheaf.map
      (eqToHom (G.image_lawfulOverlapOpenOnSpace I0 i j).symm).op s)

end TypedLocalizationGeometry

namespace ArchitectureOperationPresentation

variable {k : Type uk} {A0 : Type uA} {Op : Type uOp} {Chart : Type uChart}
variable {State : Type uState} {BeforeWitness : Type uBefore}
variable {AfterWitness : Type uAfter}
variable [Field k] [CommRing A0] [Algebra k A0]
variable [Fintype Op] [Fintype Chart]

/-- The selected ambient derivation with coefficients pushed to the lawful quotient. -/
noncomputable def ambientQuotientDerivation
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (I0 : Ideal A0) (op : Op) : Derivation k A0 (A0 ⧸ I0) :=
  QuotientValuedDerivation.quotientDerivation I0 (P.ambientDerivation op)

theorem chartAmbientComparison_selected
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i : Chart) :
    G.chartAmbientComparison I0 i (P.ambientQuotientDerivation I0 op) =
      P.chartQuotientDerivation G I0 op i := by
  apply AmbientOperationLocalization.derivation_ext_of_isLocalization
    (G.chartRing i) (Submonoid.powers (G.denominator i))
  intro a
  simp [ambientQuotientDerivation, QuotientValuedDerivation.quotientDerivation_apply]
  rfl

theorem overlapAmbientComparison_selected
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) :
    G.overlapAmbientComparison I0 i j (P.ambientQuotientDerivation I0 op) =
      P.overlapQuotientDerivation G I0 op i j := by
  apply AmbientOperationLocalization.derivation_ext_of_isLocalization
    (G.overlapRing i j)
    (Submonoid.powers (G.denominator i * G.denominator j))
  intro a
  simp [ambientQuotientDerivation, QuotientValuedDerivation.quotientDerivation_apply]
  rfl

/-- The section generated by an operation label on an ambient lawful open. -/
noncomputable def ambientOperationSection
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (I0 : Ideal A0) (op : Op) (U : (TypedLocalizationGeometry.ambientLawSpec I0).Opens) :
    (AlgebraicGeometry.modulesSpecToSheaf.obj
      (TypedLocalizationGeometry.ambientDerivationSheaf (k := k) I0)).presheaf.obj (.op U) :=
  AlgebraicGeometry.tilde.toOpen
    (TypedLocalizationGeometry.ambientDerivationModule (k := k) I0) U
    (P.ambientQuotientDerivation I0 op)

theorem ambientOperationSection_res
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (I0 : Ideal A0) (op : Op)
    (U V : (TypedLocalizationGeometry.ambientLawSpec I0).Opens) (h : V ≤ U) :
    (TypedLocalizationGeometry.ambientDerivationSheaf (k := k) I0).presheaf.map
        (homOfLE h).op (P.ambientOperationSection I0 op U) =
      P.ambientOperationSection I0 op V := by
  rfl

/-- The selected operation section on one chart. -/
noncomputable def chartOperationSection
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i : Chart) :=
  P.ambientOperationSection I0 op (G.lawfulChartOpen I0 i)

/-- The selected operation section on one overlap. -/
noncomputable def overlapOperationSection
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) :=
  P.ambientOperationSection I0 op
    (G.lawfulOverlapOpen I0 i j)

theorem operationSection_restrict_chart
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i : Chart) :
    (TypedLocalizationGeometry.ambientDerivationSheaf (k := k) I0).presheaf.map
        (homOfLE (G.lawfulChartOpen_le_lawfulOpen I0 i)).op
        (P.ambientOperationSection I0 op (G.lawfulOpen I0)) =
      P.chartOperationSection G I0 op i :=
  P.ambientOperationSection_res I0 op _ _ _

theorem operationSection_restrict_overlap
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) :
    (TypedLocalizationGeometry.ambientDerivationSheaf (k := k) I0).presheaf.map
        (homOfLE (G.lawfulOverlapOpen_le_lawfulOpen I0 i j)).op
        (P.ambientOperationSection I0 op (G.lawfulOpen I0)) =
      P.overlapOperationSection G I0 op i j :=
  P.ambientOperationSection_res I0 op _ _ _

theorem chartOperationSection_recovers
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i : Chart) :
    G.chartSectionToDerivation I0 i (P.chartOperationSection G I0 op i) =
      P.chartQuotientDerivation G I0 op i := by
  rw [show P.chartOperationSection G I0 op i =
    (AlgebraicGeometry.tilde.toOpen
      (TypedLocalizationGeometry.ambientDerivationModule (k := k) I0)
      (G.lawfulChartOpen I0 i)) (P.ambientQuotientDerivation I0 op) from rfl,
    G.chartSectionToDerivation_toOpen]
  exact P.chartAmbientComparison_selected G I0 op i

theorem overlapOperationSection_recovers
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) :
    G.overlapSectionToDerivation I0 i j (P.overlapOperationSection G I0 op i j) =
      P.overlapQuotientDerivation G I0 op i j := by
  rw [show P.overlapOperationSection G I0 op i j =
    (AlgebraicGeometry.tilde.toOpen
      (TypedLocalizationGeometry.ambientDerivationModule (k := k) I0)
      (G.lawfulOverlapOpen I0 i j))
      (P.ambientQuotientDerivation I0 op) from rfl]
  rw [G.overlapSectionToDerivation_toOpen]
  exact P.overlapAmbientComparison_selected G I0 op i j

theorem left_operationSection_natural
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) (x : G.chartRing i) :
    (G.overlapSectionToDerivation I0 i j
        (P.overlapOperationSection G I0 op i j)) (G.leftChartToOverlap i j x) =
      G.leftLawQuotientRestriction I0 i j
        ((G.chartSectionToDerivation I0 i
          (P.chartOperationSection G I0 op i)) x) := by
  rw [P.overlapOperationSection_recovers G I0 op i j,
    P.chartOperationSection_recovers G I0 op i]
  exact P.leftQuotientDerivation_natural G I0 op i j x

theorem right_operationSection_natural
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) (x : G.chartRing j) :
    (G.overlapSectionToDerivation I0 i j
        (P.overlapOperationSection G I0 op i j)) (G.rightChartToOverlap i j x) =
      G.rightLawQuotientRestriction I0 i j
        ((G.chartSectionToDerivation I0 j
          (P.chartOperationSection G I0 op j)) x) := by
  rw [P.overlapOperationSection_recovers G I0 op i j,
    P.chartOperationSection_recovers G I0 op j]
  exact P.rightQuotientDerivation_natural G I0 op i j x

/-- The section of the coefficient sheaf generated by an operation label. -/
noncomputable def operationDerivationSection
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (op : Op) :
    (AlgebraicGeometry.Scheme.Modules.presheaf
      (G.derivationCoefficientSheaf I0)).obj (.op ⊤) :=
  by
    exact
      (TypedLocalizationGeometry.ambientDerivationSheaf (k := k) I0).presheaf.map
        (eqToHom (G.lawfulOpen I0).ι_image_top).op
        (AlgebraicGeometry.tilde.toOpen
          (TypedLocalizationGeometry.ambientDerivationModule (k := k) I0)
          (G.lawfulOpen I0) (P.ambientQuotientDerivation I0 op))

@[simp] theorem operationDerivationSection_eq
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0) (op : Op) :
    P.operationDerivationSection G I0 op =
      (TypedLocalizationGeometry.ambientDerivationSheaf (k := k) I0).presheaf.map
        (eqToHom (G.lawfulOpen I0).ι_image_top).op
        (P.ambientOperationSection I0 op (G.lawfulOpen I0)) := rfl

/-- Restriction of the global coefficient-sheaf section to a lawful-space chart. -/
noncomputable def operationDerivationSectionOnChart
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i : Chart) :
    (AlgebraicGeometry.Scheme.Modules.presheaf
      (G.derivationCoefficientSheaf I0)).obj (.op (G.lawfulChartOpenOnSpace I0 i)) :=
  (G.derivationCoefficientSheaf I0).presheaf.map
    (homOfLE le_top).op (P.operationDerivationSection G I0 op)

/-- Restriction of the global coefficient-sheaf section to a lawful-space overlap. -/
noncomputable def operationDerivationSectionOnOverlap
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) :
    (AlgebraicGeometry.Scheme.Modules.presheaf
      (G.derivationCoefficientSheaf I0)).obj (.op (G.lawfulOverlapOpenOnSpace I0 i j)) :=
  (G.derivationCoefficientSheaf I0).presheaf.map
    (homOfLE le_top).op (P.operationDerivationSection G I0 op)

theorem operationDerivationSection_restrict_chart
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i : Chart) :
    G.chartSectionToDerivationOnSpace I0 i
        (P.operationDerivationSectionOnChart G I0 op i) =
      P.chartQuotientDerivation G I0 op i := by
  change G.chartSectionToDerivation I0 i (P.chartOperationSection G I0 op i) = _
  exact P.chartOperationSection_recovers G I0 op i

theorem operationDerivationSection_restrict_overlap
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) :
    G.overlapSectionToDerivationOnSpace I0 i j
        (P.operationDerivationSectionOnOverlap G I0 op i j) =
      P.overlapQuotientDerivation G I0 op i j := by
  change G.overlapSectionToDerivation I0 i j
    (P.overlapOperationSection G I0 op i j) = _
  exact P.overlapOperationSection_recovers G I0 op i j

theorem left_operationDerivationSection_natural
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) (x : G.chartRing i) :
    (G.overlapSectionToDerivationOnSpace I0 i j
        (P.operationDerivationSectionOnOverlap G I0 op i j))
          (G.leftChartToOverlap i j x) =
      G.leftLawQuotientRestriction I0 i j
        ((G.chartSectionToDerivationOnSpace I0 i
          (P.operationDerivationSectionOnChart G I0 op i)) x) := by
  rw [P.operationDerivationSection_restrict_overlap G I0 op i j,
    P.operationDerivationSection_restrict_chart G I0 op i]
  exact P.leftQuotientDerivation_natural G I0 op i j x

theorem right_operationDerivationSection_natural
    (P : ArchitectureOperationPresentation k A0 Op State BeforeWitness AfterWitness)
    (G : TypedLocalizationGeometry k A0 Chart) (I0 : Ideal A0)
    (op : Op) (i j : Chart) (x : G.chartRing j) :
    (G.overlapSectionToDerivationOnSpace I0 i j
        (P.operationDerivationSectionOnOverlap G I0 op i j))
          (G.rightChartToOverlap i j x) =
      G.rightLawQuotientRestriction I0 i j
        ((G.chartSectionToDerivationOnSpace I0 j
          (P.operationDerivationSectionOnChart G I0 op j)) x) := by
  rw [P.operationDerivationSection_restrict_overlap G I0 op i j,
    P.operationDerivationSection_restrict_chart G I0 op j]
  exact P.rightQuotientDerivation_natural G I0 op i j x

end ArchitectureOperationPresentation

end ResearchLean.AG.QualitySurface.IntrinsicLawResponseCircuitDescent

#assert_standard_axioms_only
  ResearchLean.AG.QualitySurface.IntrinsicLawResponseCircuitDescent.TypedLocalizationGeometry.DerivationLocalization

#assert_standard_axioms_only
  ResearchLean.AG.QualitySurface.IntrinsicLawResponseCircuitDescent.TypedLocalizationGeometry

#assert_standard_axioms_only
  ResearchLean.AG.QualitySurface.IntrinsicLawResponseCircuitDescent.ArchitectureOperationPresentation
