import Formal.Util.AssertStandardAxioms
import Mathlib.Data.Set.Finite.Powerset
import Mathlib.LinearAlgebra.Dual.Lemmas
import Mathlib.LinearAlgebra.LinearIndependent.Lemmas
import Mathlib.Order.Preorder.Finite

/-!
# Finite linear repair and support-minimal dependence

This file isolates the fiberwise linear-algebra theorem used by G-08.  A
normalized repair is a dual vector that annihilates all protected responses
and evaluates the target response to `1`.  Failure is witnessed by a finite
support-minimal dependence containing the target.  The singleton loop case is
kept separate from the nonloop circuit case.
-/

namespace ResearchLean.AG.QualitySurface
namespace IntrinsicLawResponseCircuitDescent
namespace LinearRepair

open Submodule

universe uK uL uV

variable {K : Type uK} {L : Type uL} {V : Type uV}
variable [Field K] [AddCommGroup V] [Module K V]

/-- The subspace generated by the protected response labels. -/
def protectedSpan (response : L → V) (P : Set L) : Submodule K V :=
  Submodule.span K (response '' P)

/-- A normalized dual separator annihilates the protected vectors and evaluates
the target vector to `1`. -/
def IsNormalizedSeparator (response : L → V) (P : Set L) (target : L)
    (separator : Module.Dual K V) : Prop :=
  (∀ p ∈ P, separator (response p) = 0) ∧ separator (response target) = 1

/-- Normalized repair exists exactly when the target response is outside the
protected response span. -/
theorem exists_normalizedSeparator_iff_not_mem_protectedSpan
    (response : L → V) (P : Set L) (target : L) :
    (∃ separator : Module.Dual K V,
      IsNormalizedSeparator response P target separator) ↔
      response target ∉ protectedSpan (K := K) response P := by
  constructor
  · rintro ⟨repair, hprotected, htarget⟩ hmem
    have hle : protectedSpan (K := K) response P ≤ LinearMap.ker repair := by
      rw [protectedSpan, Submodule.span_le]
      rintro x ⟨p, hp, rfl⟩
      exact LinearMap.mem_ker.mpr (hprotected p hp)
    have hzero := LinearMap.mem_ker.mp (hle hmem)
    rw [htarget] at hzero
    exact one_ne_zero hzero
  · intro hmem
    obtain ⟨repair, htarget, hmap⟩ :=
      (protectedSpan (K := K) response P).exists_dual_map_eq_bot_of_notMem hmem inferInstance
    refine ⟨(repair (response target))⁻¹ • repair, ?_, ?_⟩
    · intro p hp
      have hspan : response p ∈ protectedSpan (K := K) response P :=
        Submodule.subset_span ⟨p, hp, rfl⟩
      have hmapped : repair (response p) ∈
          (protectedSpan (K := K) response P).map repair :=
        ⟨response p, hspan, rfl⟩
      rw [hmap] at hmapped
      have hzero : repair (response p) = 0 := by simpa using hmapped
      simp [hzero]
    · simp [htarget]

theorem not_exists_normalizedSeparator_iff_mem_protectedSpan
    (response : L → V) (P : Set L) (target : L) :
    (¬ ∃ separator : Module.Dual K V,
      IsNormalizedSeparator response P target separator) ↔
      response target ∈ protectedSpan (K := K) response P := by
  rw [exists_normalizedSeparator_iff_not_mem_protectedSpan]
  simp

section ResponseFunctionals

variable {E : Type*} [AddCommGroup E] [Module K E]

/-- The span of a finite protected family of response functionals. -/
def protectedResponseSpan (response : L → Module.Dual K E) (P : Finset L) :
    Submodule K (Module.Dual K E) :=
  Submodule.span K (Set.range fun p : P ↦ response p.1)

/-- A normalized repair vector annihilates all protected response functionals
and evaluates the target response to `1`. -/
def IsNormalizedRepair (response : L → Module.Dual K E) (P : Finset L)
    (target : L) (repair : E) : Prop :=
  (∀ p : P, response p.1 repair = 0) ∧ response target repair = 1

/-- The actual fiber repair alternative: a normalized repair vector exists
exactly when the target response functional is outside the protected span. -/
theorem exists_normalizedRepair_iff_not_mem_protectedResponseSpan
    (response : L → Module.Dual K E) (P : Finset L) (target : L) :
    (∃ repair : E, IsNormalizedRepair response P target repair) ↔
      response target ∉ protectedResponseSpan (K := K) response P := by
  constructor
  · rintro ⟨repair, hprotected, htarget⟩ hmem
    have hle : protectedResponseSpan (K := K) response P ≤
        LinearMap.ker (Module.Dual.eval K E repair) := by
      rw [protectedResponseSpan, Submodule.span_le]
      rintro f ⟨p, rfl⟩
      exact LinearMap.mem_ker.mpr (hprotected p)
    have hzero := LinearMap.mem_ker.mp (hle hmem)
    change response target repair = 0 at hzero
    rw [htarget] at hzero
    exact one_ne_zero hzero
  · intro hnotMem
    by_contra hnoRepair
    push_neg at hnoRepair
    have hker : (⨅ p : P, LinearMap.ker (response p.1)) ≤
        LinearMap.ker (response target) := by
      intro repair hprotected
      apply LinearMap.mem_ker.mpr
      by_contra htargetZero
      let normalized : E := (response target repair)⁻¹ • repair
      have hprotectedNormalized : ∀ p : P, response p.1 normalized = 0 := by
        intro p
        rw [map_smul, LinearMap.mem_ker.mp
          ((Submodule.mem_iInf _).mp hprotected p), smul_zero]
      have htargetNormalized : response target normalized = 1 := by
        simp [normalized, htargetZero]
      exact hnoRepair normalized ⟨hprotectedNormalized, htargetNormalized⟩
    exact hnotMem (mem_span_of_iInf_ker_le_ker hker)

theorem not_exists_normalizedRepair_iff_mem_protectedResponseSpan
    (response : L → Module.Dual K E) (P : Finset L) (target : L) :
    (¬ ∃ repair : E, IsNormalizedRepair response P target repair) ↔
      response target ∈ protectedResponseSpan (K := K) response P := by
  rw [exists_normalizedRepair_iff_not_mem_protectedResponseSpan]
  simp

theorem protectedResponseSpan_eq_protectedSpan
    (response : L → Module.Dual K E) (P : Finset L) :
    protectedResponseSpan (K := K) response P =
      protectedSpan (K := K) response (P : Set L) := by
  rw [protectedResponseSpan, protectedSpan]
  congr 1
  ext f
  constructor
  · rintro ⟨p, rfl⟩
    exact ⟨p.1, p.2, rfl⟩
  · rintro ⟨p, hp, rfl⟩
    exact ⟨⟨p, hp⟩, rfl⟩

end ResponseFunctionals

/-- A finite response circuit is an inclusion-minimal linearly dependent
label set. -/
def IsSupportMinimalDependence (response : L → V) (C : Set L) : Prop :=
  C.Finite ∧ Minimal (fun S : Set L ↦ ¬ LinearIndepOn K response S) C

theorem isSupportMinimalDependence_iff
    (response : L → V) (C : Set L) :
    IsSupportMinimalDependence (K := K) response C ↔
      C.Finite ∧ ¬ LinearIndepOn K response C ∧
        ∀ ⦃D : Set L⦄, D ⊂ C → LinearIndepOn K response D := by
  rw [IsSupportMinimalDependence, Set.minimal_iff_forall_ssubset]
  aesop

/-- Failure of normalized repair is equivalent to a finite support-minimal
dependence containing the target and using only protected labels besides it. -/
theorem mem_protectedSpan_iff_exists_supportMinimalDependence
    (response : L → V) (P : Set L) (hP : P.Finite) (target : L)
    (htarget : target ∉ P) :
    response target ∈ protectedSpan (K := K) response P ↔
      ∃ C : Set L,
        IsSupportMinimalDependence (K := K) response C ∧
        target ∈ C ∧ C ⊆ insert target P := by
  constructor
  · intro hspanTarget
    obtain ⟨I, hIP, -, hspanPI, hI⟩ :=
      exists_linearIndepOn_extension
        (linearIndepOn_empty K response) (Set.empty_subset P)
    have hspan_le : protectedSpan (K := K) response P ≤
        Submodule.span K (response '' I) := by
      rw [protectedSpan, Submodule.span_le]
      exact hspanPI
    have htargetSpan : response target ∈ Submodule.span K (response '' I) :=
      hspan_le hspanTarget
    have htargetI : target ∉ I := fun h ↦ htarget (hIP h)
    have hdepInsert : ¬ LinearIndepOn K response (insert target I) := by
      rw [linearIndepOn_insert htargetI]
      simp [hI, htargetSpan]
    let dependentSubsets : Set (Set L) :=
      {C | C ⊆ insert target I ∧ ¬ LinearIndepOn K response C}
    have hInsertFinite : (insert target I).Finite := (hP.subset hIP).insert target
    have hFamilyFinite : dependentSubsets.Finite :=
      hInsertFinite.finite_subsets.subset (by
        intro C hC
        exact hC.1)
    have hInsertMem : insert target I ∈ dependentSubsets :=
      ⟨Set.Subset.rfl, hdepInsert⟩
    obtain ⟨C, hCsub, hCminimal⟩ :=
      hFamilyFinite.exists_le_minimal hInsertMem
    have hCfamily : C ∈ dependentSubsets := hCminimal.prop
    have hCtarget : target ∈ C := by
      by_contra hnot
      have hCI : C ⊆ I := by
        intro x hx
        rcases hCfamily.1 hx with rfl | hxI
        · exact (hnot hx).elim
        · exact hxI
      exact hCfamily.2 (hI.mono hCI)
    have hCminimalDep : Minimal
        (fun S : Set L ↦ ¬ LinearIndepOn K response S) C := by
      refine ⟨hCfamily.2, ?_⟩
      intro D hDdep hDC
      have hDfamily : D ∈ dependentSubsets :=
        ⟨hDC.trans hCfamily.1, hDdep⟩
      exact (hCminimal.eq_of_le hDfamily hDC).symm.subset
    refine ⟨C, ⟨hInsertFinite.subset hCfamily.1, hCminimalDep⟩,
      hCtarget, ?_⟩
    exact hCfamily.1.trans (Set.insert_subset_insert hIP)
  · rintro ⟨C, hC, htargetC, hCsubset⟩
    have hdiffProper : C \ {target} ⊂ C := by
      refine ⟨Set.diff_subset, ?_⟩
      intro hsub
      exact (hsub htargetC).2 rfl
    have hdiffIndep : LinearIndepOn K response (C \ {target}) := by
      have hproper :=
        (Set.minimal_iff_forall_ssubset.mp hC.2).2 hdiffProper
      simpa using hproper
    have htargetNotDiff : target ∉ C \ {target} := by simp
    have hdepInsert : ¬ LinearIndepOn K response
        (insert target (C \ {target})) := by
      simpa [Set.insert_diff_singleton, Set.insert_eq_of_mem htargetC] using hC.2.prop
    have htargetSpan : response target ∈
        Submodule.span K (response '' (C \ {target})) := by
      by_contra hnot
      exact hdepInsert ((linearIndepOn_insert htargetNotDiff).2 ⟨hdiffIndep, hnot⟩)
    have hdiffP : C \ {target} ⊆ P := by
      intro x hx
      rcases hCsubset hx.1 with hxt | hxP
      · exact (hx.2 hxt).elim
      · exact hxP
    exact (Submodule.span_mono (Set.image_mono hdiffP)) htargetSpan

@[simp] theorem supportMinimalDependence_singleton_iff
    (response : L → V) (target : L) :
    IsSupportMinimalDependence (K := K) response ({target} : Set L) ↔
      response target = 0 := by
  simp [IsSupportMinimalDependence, Set.minimal_iff_forall_ssubset,
    linearIndepOn_singleton_iff, Set.ssubset_singleton_iff]

/-- In the nonloop case, a target-containing circuit also contains a protected
label. -/
theorem exists_protected_mem_supportMinimalDependence_of_ne_zero
    (response : L → V) (P : Set L) (hP : P.Finite) (target : L)
    (htarget : target ∉ P) (htargetZero : response target ≠ 0)
    (hspan : response target ∈ protectedSpan (K := K) response P) :
    ∃ C : Set L,
      IsSupportMinimalDependence (K := K) response C ∧ target ∈ C ∧
      C ⊆ insert target P ∧ ∃ p ∈ C, p ∈ P := by
  obtain ⟨C, hC, htC, hCsub⟩ :=
    (mem_protectedSpan_iff_exists_supportMinimalDependence
      response P hP target htarget).mp hspan
  have hex : ∃ p ∈ C, p ∈ P := by
    by_contra hnone
    push_neg at hnone
    have hCsingleton : C = {target} := by
      apply Set.Subset.antisymm
      · intro x hx
        rcases hCsub hx with rfl | hxP
        · simp
        · exact (hnone x hx hxP).elim
      · exact Set.singleton_subset_iff.mpr htC
    have hzero : response target = 0 :=
      (supportMinimalDependence_singleton_iff response target).mp
        (hCsingleton ▸ hC)
    exact htargetZero hzero
  exact ⟨C, hC, htC, hCsub, hex⟩

section ResponseCircuitAlternative

variable {E : Type*} [AddCommGroup E] [Module K E]

/-- A zero target response is the separate loop branch: no normalized repair
exists and the singleton target set is a circuit. -/
theorem no_normalizedRepair_and_singleton_circuit_of_target_eq_zero
    (response : L → Module.Dual K E) (P : Finset L) (target : L)
    (htargetZero : response target = 0) :
    (¬ ∃ repair : E, IsNormalizedRepair response P target repair) ∧
      IsSupportMinimalDependence (K := K) response ({target} : Set L) := by
  constructor
  · rw [not_exists_normalizedRepair_iff_mem_protectedResponseSpan]
    rw [htargetZero]
    exact Submodule.zero_mem _
  · rw [supportMinimalDependence_singleton_iff]
    exact htargetZero

/-- In the nonloop failure branch, the generated circuit contains the target
and at least one protected label. -/
theorem exists_supportMinimalCircuit_of_no_normalizedRepair_of_target_ne_zero
    (response : L → Module.Dual K E) (P : Finset L) (target : L)
    (htargetP : target ∉ P) (htargetZero : response target ≠ 0)
    (hfail : ¬ ∃ repair : E, IsNormalizedRepair response P target repair) :
    ∃ C : Set L,
      IsSupportMinimalDependence (K := K) response C ∧
      target ∈ C ∧ C ⊆ insert target (P : Set L) ∧
      ∃ p ∈ C, p ∈ (P : Set L) := by
  have hspan : response target ∈
      protectedResponseSpan (K := K) response P :=
    (not_exists_normalizedRepair_iff_mem_protectedResponseSpan
      response P target).mp hfail
  rw [protectedResponseSpan_eq_protectedSpan] at hspan
  exact exists_protected_mem_supportMinimalDependence_of_ne_zero
    response (P : Set L) P.finite_toSet target htargetP htargetZero hspan

end ResponseCircuitAlternative

#assert_standard_axioms_only
  ResearchLean.AG.QualitySurface.IntrinsicLawResponseCircuitDescent.LinearRepair

end LinearRepair
end IntrinsicLawResponseCircuitDescent
end ResearchLean.AG.QualitySurface
