import Formal.AG.Measurement.Computability
import Formal.AG.Measurement.LawConflict

noncomputable section

namespace AAT.AG
namespace Measurement

universe u v

/-!
Part VIII theorem 4.2 connection from the computed finite support relation to
the existing relation-valued `LawConflictMeasurement` API.

The common ambient in this module is generated from the finite regime itself:
its selected site context, coefficient ring, module-valued obstruction sheaf,
and two equation-coordinate ideals are not imported from an unrelated ambient
template.
-/

/-- Domain selections for the two equation-generated lawful loci.

The geometric ambient, structure coefficient ring, law ideals, witness
families, comparison profile, and support carrier are derived from `R` and `D`
by `commonAmbient`; this structure contains no ambient or ideal certificate.
-/
structure FiniteAATConflictRealization
    {M : MeasurementProfile.{u, v}}
    {R : FiniteMeasurementRegime M}
    (_D : FiniteAATComputationData M R) where
  /-- Measurement-domain element read by the selected left equation. -/
  leftDomain : M.Domain
  /-- Measurement-domain element read by the selected right equation. -/
  rightDomain : M.Domain

namespace FiniteAATConflictRealization

variable {M : MeasurementProfile.{u, v}}
variable {R : FiniteMeasurementRegime M}
variable {D : FiniteAATComputationData M R}

/-- Canonical affine common ambient generated by the finite regime.

The selected ambient is the profile site object that generates the actual
equation context, and its selected structure sheaf is the finite regime's
module-valued obstruction sheaf.  Both law ideals inhabit the shared witness
polynomial chart and are proved to be the spans of the selected equation
coordinates.
-/
def commonAmbient (C : FiniteAATConflictRealization D) :
    CommonAmbientPair M := by
  letI := R.geometry.coeffCommRing
  exact {
    AmbientSpace := M.SiteObj
    StructureSheaf := Site.AATSheaf M.equationGeometry.site
    LawIdeal := Ideal (MvPolynomial M.WitnessVariables M.Coeff)
    CoefficientObject := M.Coeff
    WitnessPair :=
      Finset (Finset M.WitnessVariables) ×
        Finset (Finset M.WitnessVariables)
    ComparisonProfile :=
      M.equationGeometry.site.equationSystem.RequiredIndex ×
        M.equationGeometry.site.equationSystem.RequiredIndex
    SupportCarrier := Finset M.WitnessVariables
    leftDomain := C.leftDomain
    rightDomain := C.rightDomain
    selectedAmbient := D.profileRealization.equationSite
    selectedStructureSheaf := R.geometry.obstructionSheaf.carrier
    leftLawIdeal := D.leftIdeal
    rightLawIdeal := D.rightIdeal
    leftCoefficient := 1
    rightCoefficient := 1
    selectedWitnessPair :=
      (D.leftSquareFree.forbiddenSupports,
        D.rightSquareFree.forbiddenSupports)
    selectedComparisonProfile :=
      (D.profileRealization.selectedLeftEquation,
        D.profileRealization.selectedRightEquation)
    commonRingedSite :=
      Site.AATSheafCondition M.equationGeometry.site
        R.geometry.obstructionSheaf.carrier.toPresheaf
    commonRingedSite_cert :=
      R.geometry.obstructionSheaf.carrier.isSheaf
    lawIdealsInCommonAmbient :=
      D.leftIdeal =
          Ideal.span
            (Set.range
              (D.profileRealization.equationCoordinate
                D.profileRealization.selectedLeftEquation.1)) ∧
        D.rightIdeal =
          Ideal.span
            (Set.range
              (D.profileRealization.equationCoordinate
                D.profileRealization.selectedRightEquation.1))
    lawIdealsInCommonAmbient_cert :=
      ⟨D.profileRealization.leftIdeal_eq_span_range,
        D.profileRealization.rightIdeal_eq_span_range⟩
    coefficientsCompatible := (1 : M.Coeff) = 1
    coefficientsCompatible_cert := rfl
    witnessesComparable :=
      (D.leftSquareFree.forbiddenSupports,
        D.rightSquareFree.forbiddenSupports) =
      (D.leftSquareFree.forbiddenSupports,
        D.rightSquareFree.forbiddenSupports)
    witnessesComparable_cert := rfl
    comparisonProfileFixed :=
      (D.profileRealization.selectedLeftEquation,
        D.profileRealization.selectedRightEquation) =
      (D.profileRealization.selectedLeftEquation,
        D.profileRealization.selectedRightEquation)
    comparisonProfileFixed_cert := rfl
    noComparisonWithoutCommonAmbient :=
      Site.AATSheafCondition M.equationGeometry.site
          R.geometry.obstructionSheaf.carrier.toPresheaf ∧
        (D.leftIdeal =
            Ideal.span
              (Set.range
                (D.profileRealization.equationCoordinate
                  D.profileRealization.selectedLeftEquation.1)) ∧
          D.rightIdeal =
            Ideal.span
              (Set.range
                (D.profileRealization.equationCoordinate
                  D.profileRealization.selectedRightEquation.1)))
    noComparisonWithoutCommonAmbient_cert :=
      ⟨R.geometry.obstructionSheaf.carrier.isSheaf,
        D.profileRealization.leftIdeal_eq_span_range,
        D.profileRealization.rightIdeal_eq_span_range⟩
  }

/-- The selected ambient is the actual profile site object whose finite
geometry generates the equation context. -/
theorem commonAmbient_selectedAmbient
    (C : FiniteAATConflictRealization D) :
    C.commonAmbient.selectedAmbient =
      D.profileRealization.equationSite :=
  rfl

/-- The structure-sheaf carrier is the actual sheaf type on the generated AAT
site. -/
theorem commonAmbient_structureSheaf
    (C : FiniteAATConflictRealization D) :
    C.commonAmbient.StructureSheaf =
      Site.AATSheaf M.equationGeometry.site :=
  rfl

/-- The selected structure sheaf is the finite regime's actual
module-valued obstruction sheaf carrier. -/
theorem commonAmbient_selectedStructureSheaf
    (C : FiniteAATConflictRealization D) :
    C.commonAmbient.selectedStructureSheaf =
      R.geometry.obstructionSheaf.carrier :=
  rfl

/-- The law-ideal carrier is the ideal lattice of the witness polynomial
chart generated over the structure sheaf's coefficient ring. -/
theorem commonAmbient_lawIdeal
    (C : FiniteAATConflictRealization D) :
    letI := R.geometry.coeffCommRing
    C.commonAmbient.LawIdeal =
      Ideal (MvPolynomial M.WitnessVariables M.Coeff) :=
  rfl

/-- The common-ringed-site obligation is the sheaf condition of the finite
regime's actual obstruction sheaf. -/
theorem commonAmbient_commonRingedSite
    (C : FiniteAATConflictRealization D) :
    C.commonAmbient.commonRingedSite =
      Site.AATSheafCondition M.equationGeometry.site
        R.geometry.obstructionSheaf.carrier.toPresheaf :=
  rfl

/-- The selected ambient left ideal is fixed by construction to the actual
left equation ideal. -/
theorem commonAmbient_leftLawIdeal
    (C : FiniteAATConflictRealization D) :
    letI := R.geometry.coeffCommRing
    C.commonAmbient.leftLawIdeal = D.leftIdeal :=
  rfl

/-- The selected ambient right ideal is fixed by construction to the actual
right equation ideal. -/
theorem commonAmbient_rightLawIdeal
    (C : FiniteAATConflictRealization D) :
    letI := R.geometry.coeffCommRing
    C.commonAmbient.rightLawIdeal = D.rightIdeal :=
  rfl

/-- Both actual Tor ideals are generated by their selected equation
coordinates in the shared witness polynomial ring. -/
theorem commonAmbient_ideals_eq_span_range
    (C : FiniteAATConflictRealization D) :
    letI := R.geometry.coeffCommRing
    D.leftIdeal =
          Ideal.span
            (Set.range
              (D.profileRealization.equationCoordinate
                D.profileRealization.selectedLeftEquation.1)) ∧
      D.rightIdeal =
          Ideal.span
            (Set.range
              (D.profileRealization.equationCoordinate
                D.profileRealization.selectedRightEquation.1)) :=
  C.commonAmbient.lawIdealsInCommonAmbient_cert

/-- Relation-valued support semantics on the canonical finite witness
carrier. -/
def supportRelation (C : FiniteAATConflictRealization D) :
    letI := R.geometry.coeffCommRing
    D.ActualConflictClass -> C.commonAmbient.SupportCarrier -> Prop := by
  letI := R.geometry.coeffCommRing
  exact fun conflictClass support =>
    D.ComputedConflictSupport conflictClass support

/-- Selected support in the common ambient carrier. -/
def selectedSupport (C : FiniteAATConflictRealization D) :
    C.commonAmbient.SupportCarrier :=
  D.selectedClassSupport

/-- The selected actual conflict class and selected support satisfy the
computed relation. -/
theorem selectedSupport_holds (C : FiniteAATConflictRealization D) :
    letI := R.geometry.coeffCommRing
    C.supportRelation D.selectedConflictClass C.selectedSupport := by
  letI := R.geometry.coeffCommRing
  exact D.computedConflictSupport_selected

/-- The computed support relation assigns only the empty finite support to
the zero actual conflict class. -/
theorem supportRelation_zero
    (C : FiniteAATConflictRealization D)
    {support : C.commonAmbient.SupportCarrier}
    (h : C.supportRelation (0 : D.ActualConflictClass) support) :
    support = (∅ : Finset M.WitnessVariables) := by
  letI := R.geometry.coeffCommRing
  exact D.computedConflictSupport_zero h

/-- Existing `LawConflictMeasurement` constructed from the same selected Tor
bridge, actual class, and computed relation-valued support. -/
def lawConflictMeasurement (C : FiniteAATConflictRealization D) :
    LawConflictMeasurement C.commonAmbient := by
  letI := R.geometry.coeffCommRing
  let B := Derived.Intersection.canonicalSelectedTorBridge
    (MvPolynomial M.WitnessVariables M.Coeff) D.leftIdeal D.rightIdeal
  let selectedClass : B.LawConflict D.torDegree := D.selectedConflictClass
  let relation : B.LawConflict D.torDegree ->
      C.commonAmbient.SupportCarrier -> Prop := C.supportRelation
  have hselected : relation selectedClass C.selectedSupport := by
    exact C.selectedSupport_holds
  exact {
    Degree := ULift.{u} Nat
    selectedDegree := ULift.up D.torDegree
    LeftQuotient :=
      MvPolynomial M.WitnessVariables M.Coeff ⧸ D.leftIdeal
    RightQuotient :=
      MvPolynomial M.WitnessVariables M.Coeff ⧸ D.rightIdeal
    TorObject := B.LawConflict D.torDegree
    ConflictClass := B.LawConflict D.torDegree
    selectedConflictClass := selectedClass
    conflictSupport := relation
    selectedSupport := C.selectedSupport
    ZeroConflict := fun x => x = 0
    NontrivialConflict := fun x => x ≠ 0
    lawConflictTorReading :=
      Nonempty
        (B.LawConflict D.torDegree ≃ₗ[
          MvPolynomial M.WitnessVariables M.Coeff]
          Derived.Intersection.mathlibTor
            (MvPolynomial M.WitnessVariables M.Coeff)
            D.leftIdeal D.rightIdeal D.torDegree)
    lawConflictTorReading_cert :=
      ⟨B.lawConflictLinearEquivMathlibTor D.torDegree⟩
    selectedClassSupportReading :=
      relation selectedClass C.selectedSupport
    selectedClassSupportReading_cert := hselected
    commonAmbientRequired :=
      C.commonAmbient.commonRingedSite ∧
        C.commonAmbient.lawIdealsInCommonAmbient
    commonAmbientRequired_cert :=
      ⟨C.commonAmbient.commonRingedSite_cert,
        C.commonAmbient.lawIdealsInCommonAmbient_cert⟩
    coefficientCompatibilityUsed :=
      C.commonAmbient.coefficientsCompatible
    coefficientCompatibilityUsed_cert :=
      C.commonAmbient.coefficientsCompatible_cert
    topologyAndCoefficientBoundary :=
      C.commonAmbient.noComparisonWithoutCommonAmbient
    topologyAndCoefficientBoundary_cert :=
      C.commonAmbient.noComparisonWithoutCommonAmbient_cert
  }

/-- The final measurement's common-ambient obligation contains the actual
equation-generated ideals used by its selected Tor bridge. -/
theorem lawConflictMeasurement_commonAmbientRequired_shape
    (C : FiniteAATConflictRealization D) :
    letI := R.geometry.coeffCommRing
    C.lawConflictMeasurement.commonAmbientRequired =
      (C.commonAmbient.commonRingedSite ∧
        C.commonAmbient.lawIdealsInCommonAmbient) :=
  rfl

/-- The final measurement exposes the selected computed-support reading. -/
theorem selectedClassSupportReading_holds
    (C : FiniteAATConflictRealization D) :
    C.lawConflictMeasurement.selectedClassSupportReading :=
  C.lawConflictMeasurement.selectedClassSupportReading_holds

end FiniteAATConflictRealization

/-- Final theorem 4.2 package after a selected common ambient has been
realized.  The base computation and relation-valued `LawConflictMeasurement`
are both conclusions; the caller supplies no class-specific support
certificate. -/
structure FiniteAATConflictComputability
    {M : MeasurementProfile.{u, v}}
    (R : FiniteMeasurementRegime M)
    (D : FiniteAATComputationData M R)
    (C : FiniteAATConflictRealization D) :
    Type (max (u + 1) (v + 1)) where
  /-- The complete finite Čech, square-free, and Tor computation package. -/
  computation : FiniteAATComputability R D
  /-- Existing measurement semantics instantiated by the computed support
  relation and the actual transported conflict class. -/
  lawConflictMeasurement :
    LawConflictMeasurement.{u, v, max u v} C.commonAmbient
  /-- The exposed measurement is exactly the one constructed from the
  canonical selected Tor bridge and `ComputedConflictSupport`. -/
  lawConflictMeasurement_eq_computed :
    lawConflictMeasurement = C.lawConflictMeasurement
  /-- The final package exposes the selected class/support reading. -/
  selectedClassSupportReading :
    lawConflictMeasurement.selectedClassSupportReading

/-- Construct the final common-ambient theorem 4.2 package without accepting
any selected support correctness proof. -/
def finiteAATConflictComputabilityPackage
    {M : MeasurementProfile.{u, v}}
    (R : FiniteMeasurementRegime M)
    (D : FiniteAATComputationData M R)
    (C : FiniteAATConflictRealization D) :
    FiniteAATConflictComputability R D C where
  computation := finiteAATComputabilityPackage R D
  lawConflictMeasurement := C.lawConflictMeasurement
  lawConflictMeasurement_eq_computed := rfl
  selectedClassSupportReading := C.selectedClassSupportReading_holds

/-- A finite regime, selected computation data, and local common-ambient
realization determine the final relation-valued conflict computation. -/
theorem finiteAATConflictComputability
    {M : MeasurementProfile.{u, v}}
    (R : FiniteMeasurementRegime M)
    (D : FiniteAATComputationData M R)
    (C : FiniteAATConflictRealization D) :
    Nonempty (FiniteAATConflictComputability R D C) :=
  ⟨finiteAATConflictComputabilityPackage R D C⟩

end Measurement
end AAT.AG
