import Formal.AG.Cohomology.CochainComparison
import Formal.AG.Measurement.Stability

noncomputable section

namespace AAT.AG
namespace Measurement

universe u v w

/-!
Part VIII R5 / AC11-AC12 refactor functoriality and class transport.

The selected ringed ambient, coefficient, and law-ideal comparisons are
realized as the degree `0`, `1`, and `2` maps of an actual three-term cochain
comparison.  The map on `H^1` is generated by quotient descent; it is not a
caller-supplied cohomology isomorphism.
-/

/--
VIII.Definition 7.1: selected maps of a finite-profile refactor.

These are the maps whose invertibility and cochain realization are supplied
by `RefactorEquivalenceAssumptions`.
-/
structure RefactorMorphism (M_X M_Y : MeasurementProfile.{u, v}) where
  sourceSiteFintype : Fintype M_X.SiteObj
  targetSiteFintype : Fintype M_Y.SiteObj
  selectedSiteMap : M_X.SiteObj → M_Y.SiteObj
  selectedRingedAmbientComparison :
    M_Y.ObstructionObject → M_X.ObstructionObject
  selectedCoefficientComparison : M_Y.Coeff → M_X.Coeff
  selectedLawIdealPullback : M_Y.ObstructionIdeal → M_X.ObstructionIdeal
  selectedWitnessComparison : M_Y.WitnessVariables → M_X.WitnessVariables
  selectedAxisComparison :
    M_Y.RepresentationFamily → M_X.RepresentationFamily

/--
VIII.Definition 7.2: actual source and target three-term obstruction complexes.

Each degree is realized by the corresponding profile object.  The profile
zero readings are connected to zero classes of the quotient
`H^1 = ker d¹ / im d⁰`.
-/
structure PullbackObstructionClass {M_X M_Y : MeasurementProfile.{u, v}}
    (ρ : RefactorMorphism M_X M_Y) where
  SourceC0 : Type w
  SourceC1 : Type w
  SourceC2 : Type w
  TargetC0 : Type w
  TargetC1 : Type w
  TargetC2 : Type w
  [sourceC0AddCommGroup : AddCommGroup SourceC0]
  [sourceC1AddCommGroup : AddCommGroup SourceC1]
  [sourceC2AddCommGroup : AddCommGroup SourceC2]
  [targetC0AddCommGroup : AddCommGroup TargetC0]
  [targetC1AddCommGroup : AddCommGroup TargetC1]
  [targetC2AddCommGroup : AddCommGroup TargetC2]
  sourceComplex : Cohomology.AdditiveThreeTermComplex SourceC0 SourceC1 SourceC2
  targetComplex : Cohomology.AdditiveThreeTermComplex TargetC0 TargetC1 TargetC2
  sourceAmbientRealization : SourceC0 ≃ M_X.ObstructionObject
  targetAmbientRealization : TargetC0 ≃ M_Y.ObstructionObject
  sourceCoefficientRealization : SourceC1 ≃ M_X.Coeff
  targetCoefficientRealization : TargetC1 ≃ M_Y.Coeff
  sourceLawIdealRealization : SourceC2 ≃ M_X.ObstructionIdeal
  targetLawIdealRealization : TargetC2 ≃ M_Y.ObstructionIdeal
  sourceDomain : sourceComplex.H1 → M_X.Domain
  targetDomain : targetComplex.H1 → M_Y.Domain
  sourceZero_iff_h1Zero :
    ∀ sourceClass : sourceComplex.H1,
      M_X.Zero (sourceDomain sourceClass) ↔ sourceComplex.H1IsZero sourceClass
  targetZero_iff_h1Zero :
    ∀ targetClass : targetComplex.H1,
      M_Y.Zero (targetDomain targetClass) ↔ targetComplex.H1IsZero targetClass

attribute [instance] PullbackObstructionClass.sourceC0AddCommGroup
attribute [instance] PullbackObstructionClass.sourceC1AddCommGroup
attribute [instance] PullbackObstructionClass.sourceC2AddCommGroup
attribute [instance] PullbackObstructionClass.targetC0AddCommGroup
attribute [instance] PullbackObstructionClass.targetC1AddCommGroup
attribute [instance] PullbackObstructionClass.targetC2AddCommGroup

/--
VIII.Theorem 7.3 assumptions: every selected profile map is an actual
equivalence.  The ambient, coefficient, and law-ideal isomorphisms are
realized degreewise and commute with both differentials.
-/
structure RefactorEquivalenceAssumptions {M_X M_Y : MeasurementProfile.{u, v}}
    (ρ : RefactorMorphism M_X M_Y) (P : PullbackObstructionClass.{u, v, w} ρ) where
  selectedFiniteSiteEquivalence : M_X.SiteObj ≃ M_Y.SiteObj
  selectedFiniteSiteEquivalence_apply :
    ∀ x, selectedFiniteSiteEquivalence x = ρ.selectedSiteMap x
  ringedAmbientIso : M_Y.ObstructionObject ≃ M_X.ObstructionObject
  ringedAmbientIso_apply :
    ∀ x, ringedAmbientIso x = ρ.selectedRingedAmbientComparison x
  coefficientIso : M_Y.Coeff ≃ M_X.Coeff
  coefficientIso_apply :
    ∀ x, coefficientIso x = ρ.selectedCoefficientComparison x
  lawIdealPullbackIso : M_Y.ObstructionIdeal ≃ M_X.ObstructionIdeal
  lawIdealPullbackIso_apply :
    ∀ x, lawIdealPullbackIso x = ρ.selectedLawIdealPullback x
  witnessReadingIso : M_Y.WitnessVariables ≃ M_X.WitnessVariables
  witnessReadingIso_apply :
    ∀ x, witnessReadingIso x = ρ.selectedWitnessComparison x
  axisReadingIso : M_Y.RepresentationFamily ≃ M_X.RepresentationFamily
  axisReadingIso_apply :
    ∀ x, axisReadingIso x = ρ.selectedAxisComparison x
  ambientCochainIso : P.TargetC0 ≃+ P.SourceC0
  coefficientCochainIso : P.TargetC1 ≃+ P.SourceC1
  lawIdealCochainIso : P.TargetC2 ≃+ P.SourceC2
  ambientCochainIso_realizes : ∀ c,
    P.sourceAmbientRealization (ambientCochainIso c) =
      ringedAmbientIso (P.targetAmbientRealization c)
  coefficientCochainIso_realizes : ∀ c,
    P.sourceCoefficientRealization (coefficientCochainIso c) =
      coefficientIso (P.targetCoefficientRealization c)
  lawIdealCochainIso_realizes : ∀ c,
    P.sourceLawIdealRealization (lawIdealCochainIso c) =
      lawIdealPullbackIso (P.targetLawIdealRealization c)
  from_d0 : ∀ c : P.TargetC0,
    coefficientCochainIso (P.targetComplex.d0 c) =
      P.sourceComplex.d0 (ambientCochainIso c)
  from_d1 : ∀ c : P.TargetC1,
    lawIdealCochainIso (P.targetComplex.d1 c) =
      P.sourceComplex.d1 (coefficientCochainIso c)

namespace RefactorEquivalenceAssumptions

/--
The cochain equivalence constructed from the selected realized degreewise
isomorphisms and their differential compatibility.
-/
def cochainEquivalence {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    {P : PullbackObstructionClass.{u, v, w} ρ}
    (E : RefactorEquivalenceAssumptions ρ P) :
    Cohomology.AdditiveThreeTermComplex.Equivalence
      P.sourceComplex P.targetComplex where
  to0 := E.ambientCochainIso.symm.toAddMonoidHom
  to1 := E.coefficientCochainIso.symm.toAddMonoidHom
  to2 := E.lawIdealCochainIso.symm.toAddMonoidHom
  from0 := E.ambientCochainIso.toAddMonoidHom
  from1 := E.coefficientCochainIso.toAddMonoidHom
  from2 := E.lawIdealCochainIso.toAddMonoidHom
  to0_from0 := by intro c; simp
  from0_to0 := by intro c; simp
  to1_from1 := by intro c; simp
  from1_to1 := by intro c; simp
  to2_from2 := by intro c; simp
  from2_to2 := by intro c; simp
  to_d0 := by
    intro c
    apply E.coefficientCochainIso.injective
    simpa using (E.from_d0 (E.ambientCochainIso.symm c)).symm
  to_d1 := by
    intro c
    apply E.lawIdealCochainIso.injective
    simpa using (E.from_d1 (E.coefficientCochainIso.symm c)).symm
  from_d0 := E.from_d0
  from_d1 := E.from_d1

end RefactorEquivalenceAssumptions

namespace PullbackObstructionClass

/--
VIII.Definition 7.2: pullback on actual quotient classes, generated from the
cochain-level refactor equivalence.
-/
def pullback {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    (P : PullbackObstructionClass.{u, v, w} ρ)
    (E : RefactorEquivalenceAssumptions ρ P) :
    P.targetComplex.H1 → P.sourceComplex.H1 :=
  E.cochainEquivalence.fromH1

/-- The generated pullback sends the actual target zero class to source zero. -/
theorem pullback_zero {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    (P : PullbackObstructionClass.{u, v, w} ρ)
    (E : RefactorEquivalenceAssumptions ρ P) :
    P.pullback E P.targetComplex.H1ZeroClass =
      P.sourceComplex.H1ZeroClass :=
  E.cochainEquivalence.fromH1_zero

/-- The generated quotient pullback reflects and preserves the zero class. -/
theorem pullback_h1Zero_iff {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    (P : PullbackObstructionClass.{u, v, w} ρ)
    (E : RefactorEquivalenceAssumptions ρ P)
    (targetClass : P.targetComplex.H1) :
    P.sourceComplex.H1IsZero (P.pullback E targetClass) ↔
      P.targetComplex.H1IsZero targetClass :=
  E.cochainEquivalence.fromH1_zero_iff targetClass

end PullbackObstructionClass

/-- VIII.Theorem 7.3 package for one selected target obstruction class. -/
structure RefactorInvarianceUnderEquivalence {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y} (P : PullbackObstructionClass.{u, v, w} ρ)
    (E : RefactorEquivalenceAssumptions ρ P) where
  targetClass : P.targetComplex.H1
  targetInScope : M_Y.InScope (P.targetDomain targetClass)
  sourceInScope : M_X.InScope (P.sourceDomain (P.pullback E targetClass))

namespace RefactorInvarianceUnderEquivalence

/-- VIII.Theorem 7.3: selected zero is preserved and reflected by pullback. -/
theorem zero_iff_pullback_zero {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    {P : PullbackObstructionClass.{u, v, w} ρ}
    {E : RefactorEquivalenceAssumptions ρ P}
    (T : RefactorInvarianceUnderEquivalence P E) :
    M_Y.Zero (P.targetDomain T.targetClass) ↔
      M_X.Zero (P.sourceDomain (P.pullback E T.targetClass)) := by
  rw [P.targetZero_iff_h1Zero, P.sourceZero_iff_h1Zero]
  exact (P.pullback_h1Zero_iff E T.targetClass).symm

/-- A target-zero reading transports to source zero. -/
theorem source_zero_of_target_zero {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    {P : PullbackObstructionClass.{u, v, w} ρ}
    {E : RefactorEquivalenceAssumptions ρ P}
    (T : RefactorInvarianceUnderEquivalence P E)
    (hzero : M_Y.Zero (P.targetDomain T.targetClass)) :
    M_X.Zero (P.sourceDomain (P.pullback E T.targetClass)) :=
  T.zero_iff_pullback_zero.mp hzero

/-- A source-zero pullback reflects target zero. -/
theorem target_zero_of_source_zero {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    {P : PullbackObstructionClass.{u, v, w} ρ}
    {E : RefactorEquivalenceAssumptions ρ P}
    (T : RefactorInvarianceUnderEquivalence P E)
    (hzero : M_X.Zero (P.sourceDomain (P.pullback E T.targetClass))) :
    M_Y.Zero (P.targetDomain T.targetClass) :=
  T.zero_iff_pullback_zero.mpr hzero

end RefactorInvarianceUnderEquivalence

/-- Construct the theorem package for one selected class. -/
def refactorInvarianceUnderEquivalencePackage {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    {P : PullbackObstructionClass.{u, v, w} ρ}
    (E : RefactorEquivalenceAssumptions ρ P)
    (targetClass : P.targetComplex.H1)
    (targetInScope : M_Y.InScope (P.targetDomain targetClass))
    (sourceInScope : M_X.InScope (P.sourceDomain (P.pullback E targetClass))) :
    RefactorInvarianceUnderEquivalence P E where
  targetClass := targetClass
  targetInScope := targetInScope
  sourceInScope := sourceInScope

/--
VIII.Theorem 7.3: selected refactor equivalence preserves and reflects zero
for every obstruction class transported by the generated quotient map.
-/
theorem refactorZero_iff_pullbackZero {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    {P : PullbackObstructionClass.{u, v, w} ρ}
    (E : RefactorEquivalenceAssumptions ρ P)
    (targetClass : P.targetComplex.H1) :
    M_Y.Zero (P.targetDomain targetClass) ↔
      M_X.Zero (P.sourceDomain (P.pullback E targetClass)) := by
  rw [P.targetZero_iff_h1Zero, P.sourceZero_iff_h1Zero]
  exact (P.pullback_h1Zero_iff E targetClass).symm

/-- The selected class and scope evidence determine a theorem package. -/
theorem refactorInvarianceUnderEquivalence {M_X M_Y : MeasurementProfile.{u, v}}
    {ρ : RefactorMorphism M_X M_Y}
    {P : PullbackObstructionClass.{u, v, w} ρ}
    (E : RefactorEquivalenceAssumptions ρ P)
    (targetClass : P.targetComplex.H1)
    (targetInScope : M_Y.InScope (P.targetDomain targetClass))
    (sourceInScope : M_X.InScope (P.sourceDomain (P.pullback E targetClass))) :
    Nonempty (RefactorInvarianceUnderEquivalence P E) :=
  ⟨refactorInvarianceUnderEquivalencePackage E targetClass targetInScope sourceInScope⟩

end Measurement
end AAT.AG
