import ResearchLean.AG.TwoPhase.DependencyProfile
import Formal.AG.Cohomology.CoverNerve
import Formal.Util.AssertStandardAxioms

/-!
# Canonical support-generated nerves for structural-cover invariance

This module discharges the I0 construction obligation of
`G-105-aat-structural-cover-invariance`.  A support predicate determines its
charts, pairwise intersections, triple intersections, endpoints, and face
boundaries.  No preselected `CoverNerve` or incidence map is an input.

## Implementation notes

The generated cells are subtypes carrying existence proofs for one, two, or
three simultaneous support memberships.  The proofs make the incidence maps
total but do not add mathematical data: every endpoint and face boundary is a
projection from the supporting tuple.  A presentation starting from
`AtomIndexedNerveData.expandedNerve` was rejected here because that API starts
from a supplied base nerve and six supplied incidence maps; downstream G-105
coefficient data will instead use `nerveOf` as that base.

Ordered tuples are used, as in a Čech nerve: repeated vertices and both
orientations are retained.  This makes the alternating cochain differential a
later construction on the canonical tuple incidence rather than an additional
choice made in I0.
-/

noncomputable section

namespace AAT.AG.StructuralCover

open Cohomology
open TwoPhase

universe u

/-- An atom whose support is nonempty. -/
abbrev SupportChart {U : AtomCarrier.{u}} (D : ExtractionDoctrine U)
    (support : D.Source → U.Atom → Prop) :=
  {atom : U.Atom // ∃ source, support source atom}

/-- An ordered atom pair whose two supports meet. -/
abbrev SupportEdge {U : AtomCarrier.{u}} (D : ExtractionDoctrine U)
    (support : D.Source → U.Atom → Prop) :=
  {pair : SupportChart D support × SupportChart D support //
    ∃ source, support source pair.1.1 ∧ support source pair.2.1}

/-- An ordered atom triple whose three supports meet. -/
abbrev SupportFace {U : AtomCarrier.{u}} (D : ExtractionDoctrine U)
    (support : D.Source → U.Atom → Prop) :=
  {triple : SupportChart D support ×
      SupportChart D support × SupportChart D support //
    ∃ source, support source triple.1.1 ∧
      support source triple.2.1.1 ∧ support source triple.2.2.1}

/--
The canonical Čech nerve generated by a source--Atom support predicate.

The support predicate constructs all cell types and incidence maps; it is not
stored as an annotation on an independently selected nerve.
-/
def nerveOf {U : AtomCarrier.{u}} (D : ExtractionDoctrine U)
    (support : D.Source → U.Atom → Prop) : CoverNerve.{u} where
  Chart := SupportChart D support
  EdgeComponent := SupportEdge D support
  FaceComponent := SupportFace D support
  edgeLeft := fun edge => edge.1.1
  edgeRight := fun edge => edge.1.2
  faceEdge0 := fun face =>
    ⟨(face.1.2.1, face.1.2.2), by
      rcases face.2 with ⟨source, hfirst, hsecond, hthird⟩
      exact ⟨source, hsecond, hthird⟩⟩
  faceEdge1 := fun face =>
    ⟨(face.1.1, face.1.2.2), by
      rcases face.2 with ⟨source, hfirst, hsecond, hthird⟩
      exact ⟨source, hfirst, hthird⟩⟩
  faceEdge2 := fun face =>
    ⟨(face.1.1, face.1.2.1), by
      rcases face.2 with ⟨source, hfirst, hsecond, hthird⟩
      exact ⟨source, hfirst, hsecond⟩⟩
  edgeOverlapComponent := fun edge =>
    ∃ source, support source edge.1.1.1 ∧ support source edge.1.2.1
  faceTripleOverlapComponent := fun face =>
    ∃ source, support source face.1.1.1 ∧
      support source face.1.2.1.1 ∧ support source face.1.2.2.1
  edgeOverlapComponent_holds := fun edge => edge.2
  faceTripleOverlapComponent_holds := fun face => face.2

/-- A support proof canonically produces a generated chart. -/
def chartOfSupport {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    {support : D.Source → U.Atom → Prop} {source : D.Source} {atom : U.Atom}
    (h : support source atom) : (nerveOf D support).Chart :=
  ⟨atom, source, h⟩

/-- Every generated chart exposes the support point that generated it. -/
theorem chart_has_support {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    {support : D.Source → U.Atom → Prop}
    (chart : (nerveOf D support).Chart) :
    ∃ source, support source chart.1 :=
  chart.2

/-- A common support point canonically produces an ordered generated edge. -/
def edgeOfCommonSupport {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    {support : D.Source → U.Atom → Prop}
    (left right : (nerveOf D support).Chart) (source : D.Source)
    (hleft : support source left.1) (hright : support source right.1) :
    (nerveOf D support).EdgeComponent :=
  ⟨(left, right), source, hleft, hright⟩

/-- Every generated edge exposes an actual common support point. -/
theorem edge_has_common_support
    {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    {support : D.Source → U.Atom → Prop}
    (edge : (nerveOf D support).EdgeComponent) :
    ∃ source, support source edge.1.1.1 ∧ support source edge.1.2.1 :=
  edge.2

/-- A triple support point canonically produces an ordered generated face. -/
def faceOfCommonSupport {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    {support : D.Source → U.Atom → Prop}
    (first second third : (nerveOf D support).Chart) (source : D.Source)
    (hfirst : support source first.1) (hsecond : support source second.1)
    (hthird : support source third.1) :
    (nerveOf D support).FaceComponent :=
  ⟨(first, second, third), source, hfirst, hsecond, hthird⟩

/-- Every generated face exposes an actual triple support point. -/
theorem face_has_common_support
    {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    {support : D.Source → U.Atom → Prop}
    (face : (nerveOf D support).FaceComponent) :
    ∃ source, support source face.1.1.1 ∧
      support source face.1.2.1.1 ∧ support source face.1.2.2.1 :=
  face.2

/-- Pointwise equal supports generate equal nerves, not merely isomorphic ones. -/
theorem nerveOf_congr {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    {support support' : D.Source → U.Atom → Prop}
    (h : ∀ source atom, support source atom ↔ support' source atom) :
    nerveOf D support = nerveOf D support' := by
  have hsupport : support = support' := by
    funext source atom
    exact propext (h source atom)
  subst support'
  rfl

/-- Generated charts are finite whenever the Atom carrier is finite. -/
noncomputable def chartFintype {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    (support : D.Source → U.Atom → Prop) [Fintype U.Atom] :
    Fintype (nerveOf D support).Chart :=
  by
    change Fintype (SupportChart D support)
    exact Fintype.ofFinite _

/-- Generated pairwise intersections are finite in the finite-Atom regime. -/
noncomputable def edgeFintype {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    (support : D.Source → U.Atom → Prop) [Fintype U.Atom] :
    Fintype (nerveOf D support).EdgeComponent :=
  by
    change Fintype (SupportEdge D support)
    letI : Fintype (SupportChart D support) := chartFintype support
    exact Fintype.ofFinite _

/-- Generated triple intersections are finite in the finite-Atom regime. -/
noncomputable def faceFintype {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    (support : D.Source → U.Atom → Prop) [Fintype U.Atom] :
    Fintype (nerveOf D support).FaceComponent :=
  by
    change Fintype (SupportFace D support)
    letI : Fintype (SupportChart D support) := chartFintype support
    exact Fintype.ofFinite _

/-- The full support extracted by a doctrine. -/
def allSupport {U : AtomCarrier.{u}} (D : ExtractionDoctrine U) :
    D.Source → U.Atom → Prop :=
  D.extracts

/-- The base-classified structural support extracted by a doctrine. -/
def structuralSupport {U : AtomCarrier.{u}} (D : ExtractionDoctrine U)
    (family : DeclaredSemanticFamily D) : D.Source → U.Atom → Prop :=
  fun source atom => D.extracts source atom ∧ family.Structural (source, atom)

/-- The full canonical nerve of one doctrine. -/
def nerveOfAll {U : AtomCarrier.{u}} (D : ExtractionDoctrine U) :
    CoverNerve.{u} :=
  nerveOf D (allSupport D)

/-- The canonical structural-support nerve, classified once at the base doctrine. -/
def nerveOfStructural {U : AtomCarrier.{u}} (D : ExtractionDoctrine U)
    (family : DeclaredSemanticFamily D) : CoverNerve.{u} :=
  nerveOf D (structuralSupport D family)

/-- A variant's full support, with the original Source and Atom types retained. -/
def variantAllSupport {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    (variant : SemanticVariant D) : D.Source → U.Atom → Prop :=
  variant.replaceSemantic.extracts

/--
A variant's support restricted by the phase classification fixed at the base.
-/
def variantStructuralSupport {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    (family : DeclaredSemanticFamily D) (variant : SemanticVariant D) :
    D.Source → U.Atom → Prop :=
  fun source atom =>
    variant.replaceSemantic.extracts source atom ∧
      family.Structural (source, atom)

/-- The full generated nerve after one declared semantic replacement. -/
def nerveOfVariantAll {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    (variant : SemanticVariant D) : CoverNerve.{u} :=
  nerveOf D (variantAllSupport variant)

/-- The generated structural nerve after replacement, using the base phase. -/
def nerveOfVariantStructural
    {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    (family : DeclaredSemanticFamily D) (variant : SemanticVariant D) :
    CoverNerve.{u} :=
  nerveOf D (variantStructuralSupport family variant)

/--
For a declared family member, the base-classified structural support is
pointwise unchanged by semantic replacement.

Family membership is the material premise used to specialize the derived
`Structural` predicate; no invariance certificate is an input.
-/
theorem variantStructuralSupport_iff
    {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    (family : DeclaredSemanticFamily D) (variant : SemanticVariant D)
    (hvariant : variant ∈ family.members) (source : D.Source) (atom : U.Atom) :
    variantStructuralSupport family variant source atom ↔
      structuralSupport D family source atom := by
  constructor
  · rintro ⟨hvariantExtracts, hstructural⟩
    exact ⟨(hstructural variant hvariant).1 hvariantExtracts, hstructural⟩
  · rintro ⟨hbaseExtracts, hstructural⟩
    exact ⟨(hstructural variant hvariant).2 hbaseExtracts, hstructural⟩

/--
Claim (i): every declared semantic replacement has exactly the base structural
Čech nerve.

This is equality of the generated `CoverNerve` values, not a selected
isomorphism or an equality of cardinalities.
-/
theorem nerveOfVariantStructural_eq_nerveOfStructural
    {U : AtomCarrier.{u}} {D : ExtractionDoctrine U}
    (family : DeclaredSemanticFamily D) (variant : SemanticVariant D)
    (hvariant : variant ∈ family.members) :
    nerveOfVariantStructural family variant = nerveOfStructural D family :=
  nerveOf_congr (variantStructuralSupport_iff family variant hvariant)

/-! ## Finite nonconstancy witness -/

namespace NerveGenerationWitness

open FiniteModel

/-- The one-point source used to test whether support changes the generated nerve. -/
abbrev Source := PUnit

/--
A finite doctrine extracting exactly `componentA` from its sole source.

All nonsemantic doctrine fields are fixed and permissive; extraction therefore
reads the selected semantic support rather than a supplied incidence relation.
-/
def doctrine : ExtractionDoctrine FiniteModel.carrier where
  Source := Source
  Vocabulary := PUnit
  SemanticReading := PUnit
  Resolution := PUnit
  vocabulary := PUnit.unit
  semanticReading := PUnit.unit
  resolution := PUnit.unit
  vocabularyAllows := fun _ _ => True
  semanticAllows := fun _ _ atom => atom = FiniteAtom.componentA
  resolutionAllows := fun _ _ _ => True
  sourceSemantics := fun _ _ => True
  normalize := id

/-- A genuine replacement that adds `componentC` to the extracted support. -/
def expandedVariant : SemanticVariant doctrine where
  semanticReading := PUnit.unit
  semanticAllows := fun _ _ atom =>
    atom = FiniteAtom.componentA ∨ atom = FiniteAtom.componentC

/-- The non-singleton declared family used by the I0 adequacy witness. -/
def family : DeclaredSemanticFamily doctrine where
  members := {SemanticVariant.original doctrine, expandedVariant}
  original_mem := by simp

/-- Base extraction is exactly the singleton support chosen before nerve construction. -/
theorem doctrine_extracts_iff (source : doctrine.Source)
    (atom : FiniteModel.carrier.Atom) :
    doctrine.extracts source atom ↔ atom = FiniteAtom.componentA := by
  simp [doctrine, ExtractionDoctrine.extracts]

/-- Replacement extraction is exactly the two-atom enlarged support. -/
theorem expandedVariant_extracts_iff (source : doctrine.Source)
    (atom : FiniteModel.carrier.Atom) :
    expandedVariant.replaceSemantic.extracts source atom ↔
      atom = FiniteAtom.componentA ∨ atom = FiniteAtom.componentC := by
  simp [expandedVariant, SemanticVariant.replaceSemantic, doctrine,
    ExtractionDoctrine.extracts]

/-- The enlarged semantic component is not the original component. -/
theorem expandedVariant_ne_original :
    expandedVariant ≠ SemanticVariant.original doctrine := by
  intro h
  have hexpanded :
      expandedVariant.replaceSemantic.extracts PUnit.unit
        FiniteAtom.componentC :=
    (expandedVariant_extracts_iff PUnit.unit FiniteAtom.componentC).2
      (Or.inr rfl)
  rw [h] at hexpanded
  have hbase : doctrine.extracts PUnit.unit FiniteAtom.componentC := by
    simpa using hexpanded
  have heq := (doctrine_extracts_iff PUnit.unit FiniteAtom.componentC).1 hbase
  exact FiniteAtom.noConfusion heq

/-- The retained atom gives an actual structural pair in the nontrivial family. -/
theorem componentA_structural :
    family.Structural (PUnit.unit, FiniteAtom.componentA) := by
  intro variant hvariant
  simp only [family, Set.mem_insert_iff, Set.mem_singleton_iff] at hvariant
  rcases hvariant with rfl | rfl
  · exact Iff.rfl
  · rw [expandedVariant_extracts_iff, doctrine_extracts_iff]
    simp

/-- The added atom gives an actual semantic pair in the same family. -/
theorem componentC_semantic :
    family.Semantic (PUnit.unit, FiniteAtom.componentC) := by
  apply (family.semantic_iff_exists_variant
    (PUnit.unit, FiniteAtom.componentC)).2
  refine ⟨expandedVariant, by simp [family], ?_⟩
  rw [expandedVariant_extracts_iff, doctrine_extracts_iff]
  simp

/-- Both derived phases occur before either nerve is compared. -/
theorem both_phases_nonempty :
    (∃ pair : ExtractionPair doctrine, family.Structural pair) ∧
      (∃ pair : ExtractionPair doctrine, family.Semantic pair) :=
  ⟨⟨(PUnit.unit, FiniteAtom.componentA), componentA_structural⟩,
    ⟨(PUnit.unit, FiniteAtom.componentC), componentC_semantic⟩⟩

/-- The generated full nerve before semantic replacement. -/
def baseNerve : CoverNerve :=
  nerveOfAll doctrine

/-- The generated full nerve after semantic replacement. -/
def expandedNerve : CoverNerve :=
  nerveOfVariantAll expandedVariant

/-- Every base chart is the uniquely supported `componentA` chart. -/
theorem base_chart_atom_eq (chart : baseNerve.Chart) :
    chart.1 = FiniteAtom.componentA := by
  rcases chart.2 with ⟨source, hsource⟩
  exact (doctrine_extracts_iff source chart.1).1 hsource

/-- The base generated chart type is a singleton. -/
theorem base_chart_subsingleton : Subsingleton baseNerve.Chart := by
  constructor
  intro left right
  apply Subtype.ext
  exact (base_chart_atom_eq left).trans (base_chart_atom_eq right).symm

/-- The retained atom is a chart after replacement. -/
def expandedChartA : expandedNerve.Chart :=
  ⟨FiniteAtom.componentA, PUnit.unit,
    (expandedVariant_extracts_iff PUnit.unit FiniteAtom.componentA).2
      (Or.inl rfl)⟩

/-- The newly admitted atom is a second chart after replacement. -/
def expandedChartC : expandedNerve.Chart :=
  ⟨FiniteAtom.componentC, PUnit.unit,
    (expandedVariant_extracts_iff PUnit.unit FiniteAtom.componentC).2
      (Or.inr rfl)⟩

/-- The two replacement charts are genuinely distinct. -/
theorem expandedChartA_ne_expandedChartC : expandedChartA ≠ expandedChartC := by
  intro h
  exact FiniteAtom.noConfusion (congrArg (fun chart => chart.1) h)

/-- The generated all-Atom nerve changes when its extracted support changes. -/
theorem baseNerve_ne_expandedNerve : baseNerve ≠ expandedNerve := by
  intro hnerve
  have hChart : baseNerve.Chart = expandedNerve.Chart :=
    congrArg (fun nerve : CoverNerve => nerve.Chart) hnerve
  have hexpandedSubsingleton : Subsingleton expandedNerve.Chart := by
    rw [← hChart]
    exact base_chart_subsingleton
  exact expandedChartA_ne_expandedChartC
    (hexpandedSubsingleton.elim expandedChartA expandedChartC)

/--
Finite I0 adequacy: a nonidentity member, both phases, and actual generated
nerve variation occur in one doctrine-derived fixture.
-/
theorem nerve_generation_nonconstant :
    expandedVariant ≠ SemanticVariant.original doctrine ∧
      (∃ pair : ExtractionPair doctrine, family.Structural pair) ∧
      (∃ pair : ExtractionPair doctrine, family.Semantic pair) ∧
      baseNerve ≠ expandedNerve :=
  ⟨expandedVariant_ne_original, both_phases_nonempty.1,
    both_phases_nonempty.2, baseNerve_ne_expandedNerve⟩

/--
Claim (ii): a member of one finite declared family genuinely changes the
generated all-Atom nerve while both derived phases occur.

The same existential witness supplies family membership, nonidentity, phase
nonvacuity, and the `CoverNerve` inequality; none of these facts is stored in
the variant.
-/
theorem allAtomNerve_variability :
    ∃ variant : SemanticVariant doctrine,
      variant ∈ family.members ∧
      variant ≠ SemanticVariant.original doctrine ∧
      (∃ pair : ExtractionPair doctrine, family.Structural pair) ∧
      (∃ pair : ExtractionPair doctrine, family.Semantic pair) ∧
      nerveOfAll doctrine ≠ nerveOfVariantAll variant := by
  refine ⟨expandedVariant, by simp [family], expandedVariant_ne_original,
    both_phases_nonempty.1, both_phases_nonempty.2, ?_⟩
  simpa [baseNerve, expandedNerve] using baseNerve_ne_expandedNerve

end NerveGenerationWitness

end AAT.AG.StructuralCover

#assert_standard_axioms_only AAT.AG.StructuralCover
