import ResearchLean.AG.RealizationReconstruction.AATFiniteReferenceSyntax
import ResearchLean.AG.RealizationReconstruction.G122OriginalInput
import ResearchLean.AG.RealizationReconstruction.LensSemantics
import ResearchLean.AG.RealizationReconstruction.ProtocolSemantics
import ResearchLean.AG.DoctrineFiberProduct.LaxDiagnosticProjectorModificationCounterexample
import Formal.Util.AssertStandardAxioms

/-!
# A closed family signature for realization reconstruction

This module starts the source-provenance part of G-123(A).  The single
parameter type is a closed tagged union of the two required AAT branches and
the two independently specified CS families.  Lens parameters contain only a
view type and reference view; protocol parameters contain only the finite
schema and observation functor fixed in n1015.  Semantic objects remain
quantified *after* the parameter.

The primitive sorts below are generated by role-specific constructors.  In
particular there is no constructor accepting a completed core map, geometry
map, decoder, extension, comparison-group element, splitting, or retract.
The G-122 branch carries the original arbitrary family input and its semantic
objects are the arbitrary cell/cochain/geometry inputs constructed in Cycle 7.
The primitive sorts below expose source-derived roles but do not yet give an
interpretation, `D_Theta`, or the final finite presentation `Sigma`.
-/

namespace AAT.AG.RealizationReconstruction

open CategoryTheory TransportCoherence
open AtomFoundation DoctrineFiberProduct

universe u v

/-- The independently fixed parameter data for the lens branch of G-123(E).

It contains no lens state carrier, lens laws, presentation, or semantic map. -/
structure LensFamilyInput where
  View : Type u
  reference : View

/-- The independently fixed parameter data for the protocol branch of
G-123(E).  State functors and adapters are deliberately absent. -/
structure ProtocolFamilyInput where
  schema : ProtocolSchema.{u}
  observation : CategoryTheory.Functor schema.ExecutionCategory (Type u)

/-- The closed union of mandatory G-123 input families.

The G-117 tag and general G-122 input occur in the same parameter declaration
as the two CS models.  The G-122 payload is exactly the original family input;
generated transports and comparisons are absent. -/
inductive ClosedFamilyParameter : Type (max (u + 1) (v + 1))
  | taggedOperation
  | g122 (input : G122FamilyInput.{u, v})
  | lens (input : LensFamilyInput.{u})
  | protocol (input : ProtocolFamilyInput.{u})

/-- Semantic objects are selected by the closed parameter and remain
quantified after it.  The constructors only inject the independently defined
semantic object types into one universe-uniform index; they add no data or
property.  In particular the G-122 branch contains the arbitrary original
cell input, not a decoder image. -/
inductive FamilyRealization : ClosedFamilyParameter.{u, v} →
    Type (max (u + 1) (v + 1))
  | taggedOperation : FamilyRealization .taggedOperation
  | g122 {input : G122FamilyInput.{u, v}} (object : G122CellInput input) :
      FamilyRealization (.g122 input)
  | lens {input : LensFamilyInput.{u}}
      (object : LensRealization input.View input.reference) :
      FamilyRealization (.lens input)
  | protocol {input : ProtocolFamilyInput.{u}}
      (object : ProtocolRealization input.schema input.observation) :
      FamilyRealization (.protocol input)

/-- Primitive Atom names generated for each family.  The tagged example uses
its fixed finite Atom family; the G-122 branch uses its arbitrary source Atom
family.  CS constructors are role tags and do not accept arbitrary AAT
values. -/
inductive PrimitiveAtom :
    (θ : ClosedFamilyParameter.{u, v}) → FamilyRealization θ →
      Type (max (u + 1) (v + 1))
  | taggedOperation (atom : FiniteModel.FiniteAtom) :
      PrimitiveAtom .taggedOperation .taggedOperation
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (atom : input.Carrier.Atom) :
      PrimitiveAtom (.g122 input) (.g122 X)
  | lensState {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference} :
      PrimitiveAtom (.lens input) (.lens X)
  | lensView {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference} :
      PrimitiveAtom (.lens input) (.lens X)
  | protocolState {input : ProtocolFamilyInput.{u}}
      {X : ProtocolRealization input.schema input.observation}
      (vertex : input.schema.Vertex) :
      PrimitiveAtom (.protocol input) (.protocol X)
  | protocolOperation {input : ProtocolFamilyInput.{u}}
      {X : ProtocolRealization input.schema input.observation}
      {source target : input.schema.Vertex}
      (edge : input.schema.Edge source target) :
      PrimitiveAtom (.protocol input) (.protocol X)

/-- Primitive source occurrences.  Values from arbitrary CS parameter types
are accepted only in their declared source roles.  No eliminator in this
module can consume such a value as an AAT map. -/
inductive PrimitiveSource :
    (θ : ClosedFamilyParameter.{u, v}) → FamilyRealization θ →
      Type (max (u + 1) (v + 1))
  | taggedOperation (source : FiniteModel.ExtractionSource) :
      PrimitiveSource .taggedOperation .taggedOperation
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (source : let _ := input.atomDecidableEq
        (input.authored.context.supportPackage X.cell.as).reading.doctrine.Source) :
      PrimitiveSource (.g122 input) (.g122 X)
  | lensPoint {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference} :
      PrimitiveSource (.lens input) (.lens X)
  | lensState {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference} (state : X.Carrier) :
      PrimitiveSource (.lens input) (.lens X)
  | lensView {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference} (view : input.View) :
      PrimitiveSource (.lens input) (.lens X)
  | lensUpdate {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference}
      (state : X.Carrier) (view : input.View) :
      PrimitiveSource (.lens input) (.lens X)
  | protocolPoint {input : ProtocolFamilyInput.{u}}
      {X : ProtocolRealization input.schema input.observation} :
      PrimitiveSource (.protocol input) (.protocol X)
  | protocolState {input : ProtocolFamilyInput.{u}}
      {X : ProtocolRealization input.schema input.observation}
      (vertex : input.schema.Vertex) (state : X.State vertex) :
      PrimitiveSource (.protocol input) (.protocol X)
  | protocolOperation {input : ProtocolFamilyInput.{u}}
      {X : ProtocolRealization input.schema input.observation}
      {source target : input.schema.Vertex}
      (edge : input.schema.Edge source target) (state : X.State source) :
      PrimitiveSource (.protocol input) (.protocol X)

/-- Protocol observations are evaluations of generating states, not an
additional source summand.  This generated-source decomposition implements
`1 + Sigma_v X(v) + Sigma_e X(s(e))` without admitting unattached `O(v)`
values as source terms. -/
def protocolObservationValue {input : ProtocolFamilyInput.{u}}
    {X : ProtocolRealization input.schema input.observation}
    (vertex : input.schema.Vertex) (state : X.State vertex) :
    input.observation.obj (input.schema.vertexObject vertex) :=
  X.observe vertex state

/-- Generated object names.  Their dependence on the semantic object is
explicit.  The G-117 branch ranges over every name in the object family rather
than selecting endpoints after seeing a morphism. -/
inductive LensPrimitiveObject (input : LensFamilyInput.{u})
    (X : LensRealization input.View input.reference)
  | state
  | view
  | read
  | write

namespace LensPrimitiveObject

/-- The closed interpretation of each lens object role.  In particular Read
is the very same carrier `C` as State, while Write is definitionally `C x V`;
these domains cannot be chosen independently by a later interpreter. -/
def Carrier {input : LensFamilyInput.{u}}
    {X : LensRealization input.View input.reference} :
    LensPrimitiveObject input X → Type u
  | .state => X.Carrier
  | .view => input.View
  | .read => X.Carrier
  | .write => X.Carrier × input.View

end LensPrimitiveObject

/-- Generated object names.  Lens roles carry the closed carrier
interpretation above; other branches retain their source-specific owners. -/
inductive PrimitiveObject :
    (θ : ClosedFamilyParameter.{u, v}) → FamilyRealization θ →
      Type (max (u + 1) (v + 1))
  | tagged (object : ArchitectureObject FiniteModel.carrier) :
      PrimitiveObject .taggedOperation .taggedOperation
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (object : ArchitectureObject input.Carrier) :
      PrimitiveObject (.g122 input) (.g122 X)
  | lens {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference}
      (role : LensPrimitiveObject input X) :
      PrimitiveObject (.lens input) (.lens X)
  | protocolState {input : ProtocolFamilyInput.{u}}
      {X : ProtocolRealization input.schema input.observation}
      (vertex : input.schema.Vertex) :
      PrimitiveObject (.protocol input) (.protocol X)
  | protocolObservation {input : ProtocolFamilyInput.{u}}
      {X : ProtocolRealization input.schema input.observation}
      (vertex : input.schema.Vertex) :
      PrimitiveObject (.protocol input) (.protocol X)

/-- Endpoint-indexed primitive operation names.

The tagged constructor contains an actual operation of the fixed G-117
package, retaining both endpoints and the pre-existing operation identity.
The G-122 reference constructor likewise contains one operation from the
original authored support package at its actual endpoints.  Protocol edges
retain their original typed endpoints.  These constructors are individual
operation names/values, not completed operation-map families. -/
inductive PrimitiveOperation :
    (θ : ClosedFamilyParameter.{u, v}) → (X : FamilyRealization θ) →
      PrimitiveObject θ X → PrimitiveObject θ X →
        Type (max (u + 1) (v + 1))
  | tagged {source target : ArchitectureObject FiniteModel.carrier}
      (operation : taggedOperationPackage.reading.operationReading.Op source target) :
      PrimitiveOperation .taggedOperation .taggedOperation (.tagged source) (.tagged target)
  | g122Ref {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      {source target : ArchitectureObject input.Carrier}
      (operation : let _ := input.atomDecidableEq
        (input.authored.context.supportPackage X.cell.as).reading.operationReading.Op
          source target) :
      PrimitiveOperation (.g122 input) (.g122 X) (.g122 source) (.g122 target)
  | lensGet {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference} :
      PrimitiveOperation (.lens input) (.lens X)
        (PrimitiveObject.lens (.read : LensPrimitiveObject input X))
        (PrimitiveObject.lens (.view : LensPrimitiveObject input X))
  | lensPut {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference} :
      PrimitiveOperation (.lens input) (.lens X)
        (PrimitiveObject.lens (.write : LensPrimitiveObject input X))
        (PrimitiveObject.lens (.state : LensPrimitiveObject input X))
  | protocolEdge {input : ProtocolFamilyInput.{u}}
      {X : ProtocolRealization input.schema input.observation}
      {source target : input.schema.Vertex}
      (edge : input.schema.Edge source target) :
      PrimitiveOperation (.protocol input) (.protocol X) (PrimitiveObject.protocolState source)
        (PrimitiveObject.protocolState target)

namespace PrimitiveOperation

/-- Read back the exact source operation identity stored by a G-122 primitive
reference.  The fixed indices rule out every non-G-122 constructor. -/
def g122Value {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
    {source target : ArchitectureObject input.Carrier}
    (operation : PrimitiveOperation (.g122 input) (.g122 X)
      (.g122 source) (.g122 target)) :
    let _ := input.atomDecidableEq
    (input.authored.context.supportPackage X.cell.as).reading.operationReading.Op
      source target := by
  cases operation with
  | g122Ref value => exact value

/-- Evaluate the configuration action of a G-122 primitive reference through
the original operation reading.  Operation identity is retained separately by
`g122Value`; no injectivity of `configurationMap` is assumed. -/
def g122ConfigurationMap {input : G122FamilyInput.{u, v}}
    {X : G122CellInput input}
    {source target : ArchitectureObject input.Carrier}
    (operation : PrimitiveOperation (.g122 input) (.g122 X)
      (.g122 source) (.g122 target)) :
    ConfigurationHom source.configuration target.configuration := by
  letI := input.atomDecidableEq
  exact
    (input.authored.context.supportPackage X.cell.as).reading.operationReading.configurationMap
      operation.g122Value

@[simp] theorem g122Value_ref {input : G122FamilyInput.{u, v}}
    {X : G122CellInput input}
    {source target : ArchitectureObject input.Carrier}
    (operation : let _ := input.atomDecidableEq
      (input.authored.context.supportPackage X.cell.as).reading.operationReading.Op
        source target) :
    g122Value (g122Ref operation) = operation :=
  rfl

@[simp] theorem g122ConfigurationMap_ref
    {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
    {source target : ArchitectureObject input.Carrier}
    (operation : let _ := input.atomDecidableEq
      (input.authored.context.supportPackage X.cell.as).reading.operationReading.Op
        source target) :
    g122ConfigurationMap (g122Ref operation) =
      let _ := input.atomDecidableEq
      (input.authored.context.supportPackage X.cell.as).reading.operationReading.configurationMap
        operation :=
  rfl

end PrimitiveOperation

/-- Context names are generated independently of completed geometry maps. -/
inductive PrimitiveContext :
    (θ : ClosedFamilyParameter.{u, v}) → (X : FamilyRealization θ) →
      PrimitiveObject θ X → Type (max (u + 1) (v + 1))
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      {object : ArchitectureObject input.Carrier}
      (context : Site.ArchCtx object) :
      PrimitiveContext (.g122 input) (.g122 X) (.g122 object)
  | lensState {input : LensFamilyInput.{u}}
      {X : LensRealization input.View input.reference} :
      PrimitiveContext (.lens input) (.lens X) (.lens .state)
  | protocolVertex {input : ProtocolFamilyInput.{u}}
      {X : ProtocolRealization input.schema input.observation}
      (vertex : input.schema.Vertex) :
      PrimitiveContext (.protocol input) (.protocol X) (.protocolState vertex)

/-- The source G-122 diagnostic-cell family is a combinatorial role, not the
AAT complete-geometry context family. -/
inductive PrimitiveDiagnosticCell :
    (θ : ClosedFamilyParameter.{u, v}) → FamilyRealization θ →
      Type (max (u + 1) (v + 1))
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (cell : let _ := input.atomDecidableEq
        input.authored.context.square.semantic.diagnostic.TwoCell) :
      PrimitiveDiagnosticCell (.g122 input) (.g122 X)

/-- The fixed G-122 family is a value of the general common branch. -/
noncomputable def finiteAxisFoldParameter : ClosedFamilyParameter.{0, 0} :=
  .g122 finiteAxisFoldG122FamilyInput

/-- The card-mandated fixed cell input is an object under that same general
G-122 parameter. -/
noncomputable def finiteAxisFoldRealization :
    FamilyRealization finiteAxisFoldParameter :=
  .g122 finiteAxisFoldG122CellInput

/-- The actual fixed G-122 finite Atom family is present by specialization of
the general branch. -/
noncomputable def finiteAxisFoldAtom (atom : FiniteModel.FiniteAtom) :
    PrimitiveAtom finiteAxisFoldParameter finiteAxisFoldRealization :=
  .g122 atom

/-- Every operation of the mandated finite axis-fold support package is
represented at the same endpoints through the general G-122 reference
constructor. -/
noncomputable def finiteAxisFoldOperationReference
    {source target : ArchitectureObject FiniteModel.carrier}
    (operation : finiteAxisFoldSupportPackage.reading.operationReading.Op source target) :
    PrimitiveOperation finiteAxisFoldParameter finiteAxisFoldRealization
      (.g122 source) (.g122 target) :=
  .g122Ref operation

/-- The fixed specialization reads back the identical operation value; it is
not reconstructed from its configuration map. -/
@[simp] theorem finiteAxisFoldOperationReference_value
    {source target : ArchitectureObject FiniteModel.carrier}
    (operation : finiteAxisFoldSupportPackage.reading.operationReading.Op source target) :
    PrimitiveOperation.g122Value (finiteAxisFoldOperationReference operation) = operation :=
  rfl

/-- The fixed G-117 operation family is represented at every pair of its
actual architecture-object endpoints. -/
def taggedOperation {source target : ArchitectureObject FiniteModel.carrier}
    (operation : taggedOperationPackage.reading.operationReading.Op source target) :
    PrimitiveOperation .taggedOperation .taggedOperation
      (PrimitiveObject.tagged source)
      (PrimitiveObject.tagged target) :=
  .tagged operation

/-- The single G-123(C) candidate action flips the Boolean tag uniformly on
every operation at every pair of endpoints. -/
def taggedUniformFlipAction
    {source target : ArchitectureObject FiniteModel.carrier}
    (operation : taggedOperationPackage.reading.operationReading.Op source target) :
    taggedOperationPackage.reading.operationReading.Op source target :=
  (operation.1, !operation.2)

/-- The uniform action is involutive on every operation, independently of its
endpoints. -/
theorem taggedUniformFlipAction_involutive
    {source target : ArchitectureObject FiniteModel.carrier}
    (operation : taggedOperationPackage.reading.operationReading.Op source target) :
    taggedUniformFlipAction (taggedUniformFlipAction operation) = operation := by
  rcases operation with ⟨operation, tag⟩
  cases tag <;> rfl

/-- The uniform operation action extends to one actual endomorphism of the
fixed G-117 package; exactness is constructed because configuration reading
forgets the Boolean tag. -/
noncomputable def taggedUniformFlipUpper :
    SignedExactCoreReadingHom taggedOperationPackage taggedOperationPackage :=
  { SignedExactCoreReadingHom.refl taggedOperationPackage with
    operationMap := taggedUniformFlipAction
    operation_naturality := by
      intro first second operation
      change ConfigurationHom.comp
          (finiteAxisFoldSupportPackage.reading.operationReading.configurationMap
            operation.1)
          (ConfigurationHom.id first.configuration) =
        ConfigurationHom.comp
          (ConfigurationHom.id second.configuration)
          (finiteAxisFoldSupportPackage.reading.operationReading.configurationMap
            operation.1)
      apply ConfigurationHom.ext
      rfl }

/-- The G-123(C) uniform flip as one actual package self-map. -/
noncomputable def taggedUniformFlipTotal :
    PackageTotalHom taggedOperationPackage taggedOperationPackage where
  base := ExtInstHom.id (packagePoint taggedOperationPackage)
  upper := taggedUniformFlipUpper
  atomEquiv_eq := rfl

/-- No-unfold evaluation of the uniform package self-map at every endpoint. -/
@[simp] theorem taggedUniformFlipTotal_operationMap
    {source target : ArchitectureObject FiniteModel.carrier}
    (operation : taggedOperationPackage.reading.operationReading.Op source target) :
    taggedUniformFlipTotal.upper.operationMap operation =
      taggedUniformFlipAction operation :=
  rfl

/-- Composition of the uniform flip evaluates by applying its same action
twice; no endpoint-dependent choice enters the composite. -/
theorem taggedUniformFlipSquare_operationMap
    {source target : ArchitectureObject FiniteModel.carrier}
    (operation : taggedOperationPackage.reading.operationReading.Op source target) :
    (taggedUniformFlipTotal.comp taggedUniformFlipTotal).upper.operationMap operation =
      operation := by
  change taggedUniformFlipAction (taggedUniformFlipAction operation) = operation
  exact taggedUniformFlipAction_involutive operation

/-- Every named protocol edge occurs with its original endpoints. -/
def protocolEdge {input : ProtocolFamilyInput.{u}}
    {X : ProtocolRealization input.schema input.observation}
    {source target : input.schema.Vertex} (edge : input.schema.Edge source target) :
    PrimitiveOperation (.protocol input) (.protocol X)
      (PrimitiveObject.protocolState source : PrimitiveObject (.protocol input) (.protocol X))
      (PrimitiveObject.protocolState target : PrimitiveObject (.protocol input) (.protocol X)) :=
  .protocolEdge edge

/-- Role-indexed access to the actual source G-122 signature axis. -/
inductive PrimitiveSignatureAxis :
    (θ : ClosedFamilyParameter.{u, v}) → FamilyRealization θ →
      Type (max (u + 1) (v + 1))
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (axis : let _ := input.atomDecidableEq
        (input.authored.context.supportPackage X.cell.as).reading.signatureReading.Axis) :
      PrimitiveSignatureAxis (.g122 input) (.g122 X)

/-- Role-indexed access to the actual source G-122 signature-coordinate
family, kept distinct from the axis role. -/
inductive PrimitiveSignatureCoordinate :
    (θ : ClosedFamilyParameter.{u, v}) → (X : FamilyRealization θ) →
      PrimitiveSignatureAxis θ X → Type (max (u + 1) (v + 1))
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (axis : let _ := input.atomDecidableEq
        (input.authored.context.supportPackage X.cell.as).reading.signatureReading.Axis)
      (coordinate : let _ := input.atomDecidableEq
        (input.authored.context.supportPackage X.cell.as).reading.signatureReading.Coordinate axis) :
      PrimitiveSignatureCoordinate (.g122 input) (.g122 X) (.g122 axis)

/-- Role-indexed access to the actual source G-122 equation family. -/
inductive PrimitiveEquationIndex :
    (θ : ClosedFamilyParameter.{u, v}) → FamilyRealization θ →
      Type (max (u + 1) (v + 1))
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (index : let _ := input.atomDecidableEq
        (input.authored.context.supportPackage X.cell.as).reading.equationReading.equationSystem.Index) :
      PrimitiveEquationIndex (.g122 input) (.g122 X)

/-- Role-indexed access to the actual source G-122 invariant family. -/
inductive PrimitiveInvariantIndex :
    (θ : ClosedFamilyParameter.{u, v}) → FamilyRealization θ →
      Type (max (u + 1) (v + 1))
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (index : let _ := input.atomDecidableEq
        (input.authored.context.supportPackage X.cell.as).reading.invariantReading.Index) :
      PrimitiveInvariantIndex (.g122 input) (.g122 X)

/-- Role-indexed access to the actual source G-122 raw-coordinate family. -/
inductive PrimitiveCoordinateIndex :
    (θ : ClosedFamilyParameter.{u, v}) → FamilyRealization θ →
      Type (max (u + 1) (v + 1))
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (context : let _ := input.atomDecidableEq
        X.selectedGeometry.toAATSite.category)
      (index : let _ := input.atomDecidableEq
        let _ := input.coefficientCommRing
        (X.raw.coordFamily context).Coord) :
      PrimitiveCoordinateIndex (.g122 input) (.g122 X)

/-- Role-indexed access to the actual source G-122 raw-relation family. -/
inductive PrimitiveRelationIndex :
    (θ : ClosedFamilyParameter.{u, v}) → FamilyRealization θ →
      Type (max (u + 1) (v + 1))
  | g122 {input : G122FamilyInput.{u, v}} {X : G122CellInput input}
      (context : let _ := input.atomDecidableEq
        X.selectedGeometry.toAATSite.category)
      (index : let _ := input.atomDecidableEq
        let _ := input.coefficientCommRing
        (X.raw.relationFamily context).Relation) :
      PrimitiveRelationIndex (.g122 input) (.g122 X)

#assert_standard_axioms_only AAT.AG.RealizationReconstruction

end AAT.AG.RealizationReconstruction
