import ResearchLean.AG.RealizationReconstruction.CSAATSignedExactCoreIso
import Formal.Util.AssertStandardAxioms

/-!
# Total package morphisms for genuine CS isomorphisms

The lower pointed-doctrine morphism is generated from the actual lens or
protocol semantic hom and its distinguished-point equation.  The upper
morphism is the complete signed exact core constructed previously.  Their Atom
equivalences are definitionally the same identity equivalence, so the complete
`PackageTotalHom` is constructed without accepting a lower morphism, upper
morphism, or compatibility certificate as an input.
-/

namespace AAT.AG.RealizationReconstruction

open CategoryTheory
open AtomFoundation

universe u

/-- Lower pointed-doctrine morphism generated by a genuine lens isomorphism. -/
def lensIsoExtInstHom
    {input : LensFamilyInput.{u}}
    {X Y : LensRealization input.View input.reference} (e : X ≅ Y) :
    ExtInstHom (packagePoint (lensAATCorePackage input X))
      (packagePoint (lensAATCorePackage input Y)) where
  doctrineHom := lensAATExactDoctrineHom e.hom
  source_eq := lensAATSourceMap_point e.hom

/-- Complete package morphism generated by the same genuine lens
isomorphism. -/
noncomputable def lensIsoPackageTotalHom
    {input : LensFamilyInput.{u}}
    {X Y : LensRealization input.View input.reference} (e : X ≅ Y) :
    PackageTotalHom (lensAATCorePackage input X)
      (lensAATCorePackage input Y) where
  base := lensIsoExtInstHom e
  upper := lensIsoSignedExactCoreReadingHom e
  atomEquiv_eq := rfl

/-- Lower pointed-doctrine morphism generated by a genuine protocol
isomorphism. -/
def protocolIsoExtInstHom
    {input : ProtocolFamilyInput.{u}}
    {X Y : ProtocolRealization input.schema input.observation} (e : X ≅ Y) :
    ExtInstHom (packagePoint (protocolAATCorePackage input X))
      (packagePoint (protocolAATCorePackage input Y)) where
  doctrineHom := protocolAATExactDoctrineHom e.hom
  source_eq := protocolAATSourceMap_point e.hom

/-- Complete package morphism generated by the same genuine protocol
isomorphism. -/
noncomputable def protocolIsoPackageTotalHom
    {input : ProtocolFamilyInput.{u}}
    {X Y : ProtocolRealization input.schema input.observation} (e : X ≅ Y) :
    PackageTotalHom (protocolAATCorePackage input X)
      (protocolAATCorePackage input Y) where
  base := protocolIsoExtInstHom e
  upper := protocolIsoSignedExactCoreReadingHom e
  atomEquiv_eq := rfl

#assert_standard_axioms_only AAT.AG.RealizationReconstruction

end AAT.AG.RealizationReconstruction
