import ResearchLean.AG.RealizationReconstruction.FiniteAxisFoldNormalizedAxisSwap
import Formal.Util.AssertStandardAxioms

/-!
# A source presentation for the fixed finite-axis-fold axis swap

The fixed adjacent axis permutation starts from `Equiv.swap (0 : Fin 3) 1`,
is lifted through the original complete geometry, and is transported along
the fixed pull-push route.  This file adds a primitive source leaf whose
evaluator spells out that route, together with a general syntax operator that
normalizes and applies the constructed geometry section to a direct-endpoint
term.  Neither constructor accepts a completed automorphism, comparison
element, or family of semantic maps as input.

The new congruence is generated by the retained source laws, the category
laws, and the independently proved involution law.  Semantic equality is not
a congruence constructor.  The quotient therefore supplies a displayed axis
automorphism whose decoder is exactly the transported swap.  Conjugation by
the displayed `barAlpha` gives a source comparison element, and restricting
its decoded raw comparison gives exactly the nonidentity normalized
comparison constructed from the original swap.

This is a source preimage for one fixed normalized comparison element.  It
does not prove coverage of arbitrary endpoint automorphisms, comparison-group
elements, sections, kernels, or lift fibers.
-/

namespace AAT.AG.RealizationReconstruction

open CategoryTheory AtomFoundation DoctrineFiberProduct GeometryTransport
open CrossStageCoherence TransportCoherence FullGeometryNormalization

noncomputable section

/-- Decidable atom equality for the fixed finite-axis-fold input. -/
local instance finiteAxisFoldAxisSwapPresentationAtomDecidableEq :
    DecidableEq FiniteModel.carrier.Atom := by
  change DecidableEq FiniteModel.FiniteAtom
  infer_instance

/-- Fixed source syntax with a primitive axis recipe and a general
normalization-section operator on direct-endpoint source terms. -/
inductive FiniteAxisFoldAxisSwapSyntax :
    G122GeneratedGeometryObject finiteAxisFoldG122FamilyInput →
      G122GeneratedGeometryObject finiteAxisFoldG122FamilyInput → Type 2
  | base {X Y} (term : FiniteAxisFoldKernelExtendedSyntax X Y) :
      FiniteAxisFoldAxisSwapSyntax X Y
  | axisDirect : FiniteAxisFoldAxisSwapSyntax
      (.direct finiteAxisFoldG122CellInput)
      (.direct finiteAxisFoldG122CellInput)
  | normalizeSectionDirect
      (term : FiniteAxisFoldAxisSwapSyntax
        (.direct finiteAxisFoldG122CellInput)
        (.direct finiteAxisFoldG122CellInput)) : FiniteAxisFoldAxisSwapSyntax
      (.direct finiteAxisFoldG122CellInput)
      (.direct finiteAxisFoldG122CellInput)
  | compose {X Y Z} (first : FiniteAxisFoldAxisSwapSyntax X Y)
      (second : FiniteAxisFoldAxisSwapSyntax Y Z) :
      FiniteAxisFoldAxisSwapSyntax X Z

namespace FiniteAxisFoldAxisSwapSyntax

/-- Evaluate the new primitive by the fixed construction from the original
axis permutation, and retain the old evaluator on all old source recipes. -/
noncomputable def evaluate {X Y} : FiniteAxisFoldAxisSwapSyntax X Y →
    G122GeneratedGeometryObject.Hom finiteAxisFoldG122FamilyInput X Y
  | .base term => term.evaluate
  | .axisDirect =>
      ((geomFiberTransportFunctor
          finiteAxisFoldBCDatumSquare.context.square.semantic.square.top).map
        ((exactGeometryPullFunctor
            (authoredExactLeftInput finiteAxisFoldBCDatumSquare)).map
          finiteAxisFoldSouthwestSwapHom)).1
  | .normalizeSectionDirect term =>
      canonicalNormalizationGeometrySection
        finiteAxisFoldActualDirectAdmissibleGeometry.obj
        finiteAxisFoldActualDirectAdmissibleGeometry.property
        (((geometryNormalizationFunctor.{0, 0} FiniteModel.carrier).map
          (ObjectProperty.homMk term.evaluate)).f.hom)
  | .compose first second => G122GeneratedGeometryObject.comp
      finiteAxisFoldG122FamilyInput first.evaluate second.evaluate

/-- Node count for the extended finite syntax tree. -/
def size {X Y} : FiniteAxisFoldAxisSwapSyntax X Y → Nat
  | .base term => term.size + 1
  | .axisDirect => 1
  | .normalizeSectionDirect term => term.size + 1
  | .compose first second => first.size + second.size + 1

/-- Every axis-swap syntax term has a node. -/
theorem size_pos {X Y} (term : FiniteAxisFoldAxisSwapSyntax X Y) :
    0 < term.size := by
  induction term with
  | base term => simp [size]
  | axisDirect => simp [size]
  | normalizeSectionDirect term termPositive => simp [size]
  | compose first second firstPositive secondPositive =>
      simp only [size]
      omega

/-- Source-generated congruence.  In particular, equality after evaluation
is deliberately absent from the constructors. -/
inductive Congruent : {X Y :
    G122GeneratedGeometryObject finiteAxisFoldG122FamilyInput} →
    FiniteAxisFoldAxisSwapSyntax X Y →
    FiniteAxisFoldAxisSwapSyntax X Y → Prop
  | refl {X Y} (term : FiniteAxisFoldAxisSwapSyntax X Y) : Congruent term term
  | symm {X Y} {first second : FiniteAxisFoldAxisSwapSyntax X Y} :
      Congruent first second → Congruent second first
  | trans {X Y} {first second third : FiniteAxisFoldAxisSwapSyntax X Y} :
      Congruent first second → Congruent second third → Congruent first third
  | comp {W X Y} {first first' : FiniteAxisFoldAxisSwapSyntax W X}
      {second second' : FiniteAxisFoldAxisSwapSyntax X Y} :
      Congruent first first' → Congruent second second' →
        Congruent (.compose first second) (.compose first' second')
  | base {X Y} {first second : FiniteAxisFoldKernelExtendedSyntax X Y} :
      FiniteAxisFoldKernelExtendedSyntax.Congruent first second →
        Congruent (.base first) (.base second)
  | base_comp {X Y Z} (first : FiniteAxisFoldKernelExtendedSyntax X Y)
      (second : FiniteAxisFoldKernelExtendedSyntax Y Z) :
      Congruent (.compose (.base first) (.base second))
        (.base (.compose first second))
  | normalizeSectionDirect {first second : FiniteAxisFoldAxisSwapSyntax
      (.direct finiteAxisFoldG122CellInput)
      (.direct finiteAxisFoldG122CellInput)} :
      Congruent first second →
        Congruent (.normalizeSectionDirect first)
          (.normalizeSectionDirect second)
  | id_comp {X Y} (term : FiniteAxisFoldAxisSwapSyntax X Y) :
      Congruent (.compose (.base (.base (.identity X))) term) term
  | comp_id {X Y} (term : FiniteAxisFoldAxisSwapSyntax X Y) :
      Congruent (.compose term (.base (.base (.identity Y)))) term
  | assoc {W X Y Z} (first : FiniteAxisFoldAxisSwapSyntax W X)
      (second : FiniteAxisFoldAxisSwapSyntax X Y)
      (third : FiniteAxisFoldAxisSwapSyntax Y Z) :
      Congruent (.compose (.compose first second) third)
        (.compose first (.compose second third))
  | axisDirect_sq : Congruent (.compose .axisDirect .axisDirect)
      (.base (.base (.identity (.direct finiteAxisFoldG122CellInput))))
  | normalizedAxisDirect_sq :
      Congruent
        (.compose (.normalizeSectionDirect .axisDirect)
          (.normalizeSectionDirect .axisDirect))
        (.base (.base (.identity (.direct finiteAxisFoldG122CellInput))))

/-- The transported swap is still an involution as a complete-geometry
morphism at the actual direct endpoint. -/
theorem axisDirect_evaluate_comp_self :
    G122GeneratedGeometryObject.comp finiteAxisFoldG122FamilyInput
        (evaluate .axisDirect) (evaluate .axisDirect) =
      G122GeneratedGeometryObject.id finiteAxisFoldG122FamilyInput
        (.direct finiteAxisFoldG122CellInput) := by
  change finiteAxisFoldActualDirectSwapFiberAut.hom.1 ≫
      finiteAxisFoldActualDirectSwapFiberAut.hom.1 = 𝟙 _
  simpa [finiteAxisFoldActualDirectSwapFiberAut,
    finiteAxisFoldLeftPulledSwapFiberAut,
    finiteAxisFoldSouthwestSwapAut]
    using congrArg Subtype.val finiteAxisFoldActualDirectSwapFiberAut.hom_inv_id

/-- The sectioned fixed recipe and its inverse satisfy the first inverse law
because both are evaluated from one constructed canonical-section isomorphism. -/
theorem normalizedAxisDirect_evaluate_comp_self :
    G122GeneratedGeometryObject.comp finiteAxisFoldG122FamilyInput
        (evaluate (.normalizeSectionDirect .axisDirect))
        (evaluate (.normalizeSectionDirect .axisDirect)) =
      G122GeneratedGeometryObject.id finiteAxisFoldG122FamilyInput
        (.direct finiteAxisFoldG122CellInput) := by
  change (canonicalNormalizationAutomorphismSectionHom
      finiteAxisFoldActualDirectAdmissibleGeometry
      finiteAxisFoldNormalizedDirectSwapAut).hom.hom ≫
    (canonicalNormalizationAutomorphismSectionHom
      finiteAxisFoldActualDirectAdmissibleGeometry
      finiteAxisFoldNormalizedDirectSwapAut).inv.hom = 𝟙 _
  have equality := congrArg
    (fun f : finiteAxisFoldActualDirectAdmissibleGeometry ⟶
        finiteAxisFoldActualDirectAdmissibleGeometry => f.hom)
    (canonicalNormalizationAutomorphismSectionHom
      finiteAxisFoldActualDirectAdmissibleGeometry
      finiteAxisFoldNormalizedDirectSwapAut).hom_inv_id
  exact equality

/-- Every generated congruence is sound for the independently defined
evaluator. -/
theorem evaluate_eq_of_congruent {X Y}
    {first second : FiniteAxisFoldAxisSwapSyntax X Y}
    (relation : Congruent first second) : first.evaluate = second.evaluate := by
  induction relation with
  | refl => rfl
  | symm _ ih => exact ih.symm
  | trans _ _ firstIH secondIH => exact firstIH.trans secondIH
  | comp _ _ firstIH secondIH => simp only [evaluate]; rw [firstIH, secondIH]
  | base relation =>
      exact FiniteAxisFoldKernelExtendedSyntax.evaluate_eq_of_congruent relation
  | base_comp first second => rfl
  | normalizeSectionDirect relation ih =>
      simp only [evaluate]
      rw [ih]
  | id_comp term => exact G122GeneratedGeometryObject.id_comp _ term.evaluate
  | comp_id term => exact G122GeneratedGeometryObject.comp_id _ term.evaluate
  | assoc first second third =>
      exact G122GeneratedGeometryObject.comp_assoc _ first.evaluate
        second.evaluate third.evaluate
  | axisDirect_sq => exact axisDirect_evaluate_comp_self
  | normalizedAxisDirect_sq => exact normalizedAxisDirect_evaluate_comp_self

/-- The new primitive is not identified with the source identity by the
generated laws. -/
theorem axisDirect_not_congruent_identity :
    ¬ Congruent (.axisDirect)
      (.base (.base (.identity (.direct finiteAxisFoldG122CellInput)))) := by
  intro relation
  apply finiteAxisFoldActualDirectSwapFiberAut_ne_one
  apply Iso.ext
  apply Subtype.ext
  simpa [evaluate, G122GeneratedGeometryObject.id] using
    evaluate_eq_of_congruent relation

end FiniteAxisFoldAxisSwapSyntax

/-- Objects retain the fixed G-122 generated objects; only source arrows are
extended. -/
structure FiniteAxisFoldAxisSwapPresentation where
  /-- Original generated object represented by this presentation object. -/
  object : G122GeneratedGeometryObject finiteAxisFoldG122FamilyInput

namespace FiniteAxisFoldAxisSwapPresentation

/-- Embed an original generated object. -/
def ofObject (X : G122GeneratedGeometryObject finiteAxisFoldG122FamilyInput) :
    FiniteAxisFoldAxisSwapPresentation := ⟨X⟩

/-- Setoid generated by the source congruence. -/
def congruentSetoid (X Y :
    G122GeneratedGeometryObject finiteAxisFoldG122FamilyInput) :
    Setoid (FiniteAxisFoldAxisSwapSyntax X Y) where
  r := FiniteAxisFoldAxisSwapSyntax.Congruent
  iseqv :=
    { refl := FiniteAxisFoldAxisSwapSyntax.Congruent.refl
      symm := FiniteAxisFoldAxisSwapSyntax.Congruent.symm
      trans := FiniteAxisFoldAxisSwapSyntax.Congruent.trans }

/-- Quotient morphisms of the axis-swap presentation. -/
abbrev Hom (P Q : FiniteAxisFoldAxisSwapPresentation) :=
  Quotient (congruentSetoid P.object Q.object)

/-- Insert a finite term into the quotient. -/
def classOf {X Y} (term : FiniteAxisFoldAxisSwapSyntax X Y) :
    Hom (ofObject X) (ofObject Y) := Quotient.mk _ term

/-- Compose quotient morphisms using syntax composition. -/
def comp {P Q R : FiniteAxisFoldAxisSwapPresentation}
    (first : Hom P Q) (second : Hom Q R) : Hom P R :=
  Quotient.liftOn₂ first second
    (fun firstTerm secondTerm => Quotient.mk _ (.compose firstTerm secondTerm))
    (by
      intro first first' second second' firstRelation secondRelation
      exact Quotient.sound (FiniteAxisFoldAxisSwapSyntax.Congruent.comp
        firstRelation secondRelation))

/-- Category generated by the explicit source and category laws. -/
instance : Category FiniteAxisFoldAxisSwapPresentation where
  Hom := Hom
  id P := classOf (.base (.base (.identity P.object)))
  comp := comp
  id_comp := by
    intro P Q f
    induction f using Quotient.inductionOn with
    | _ term =>
        exact Quotient.sound
          (FiniteAxisFoldAxisSwapSyntax.Congruent.id_comp term)
  comp_id := by
    intro P Q f
    induction f using Quotient.inductionOn with
    | _ term =>
        exact Quotient.sound
          (FiniteAxisFoldAxisSwapSyntax.Congruent.comp_id term)
  assoc := by
    intro P Q R S f g h
    induction f using Quotient.inductionOn with
    | _ first =>
      induction g using Quotient.inductionOn with
      | _ second =>
        induction h using Quotient.inductionOn with
        | _ third =>
            exact Quotient.sound
              (FiniteAxisFoldAxisSwapSyntax.Congruent.assoc first second third)

/-- Sound decoder into all complete-geometry morphisms of the fixed generated
objects. -/
noncomputable def decoder : FiniteAxisFoldAxisSwapPresentation ⥤
    G122GeneratedGeometryObject finiteAxisFoldG122FamilyInput where
  obj P := P.object
  map f := Quotient.liftOn f FiniteAxisFoldAxisSwapSyntax.evaluate
    (fun _ _ relation =>
      FiniteAxisFoldAxisSwapSyntax.evaluate_eq_of_congruent relation)
  map_id _ := rfl
  map_comp f g := by
    induction f using Quotient.inductionOn with
    | _ first =>
      induction g using Quotient.inductionOn with
      | _ second => rfl

/-- Retained source-law `barAlpha` is an isomorphism in the new quotient. -/
noncomputable def barAlphaIso :
    ofObject (.direct finiteAxisFoldG122CellInput) ≅
      ofObject (.viaBase finiteAxisFoldG122CellInput) where
  hom := classOf (.base (.base (.barAlpha finiteAxisFoldG122CellInput)))
  inv := classOf (.base (.base (.barAlphaInv finiteAxisFoldG122CellInput)))
  hom_inv_id := Quotient.sound (FiniteAxisFoldAxisSwapSyntax.Congruent.trans
    (FiniteAxisFoldAxisSwapSyntax.Congruent.base_comp _ _)
    (FiniteAxisFoldAxisSwapSyntax.Congruent.base
      (FiniteAxisFoldKernelExtendedSyntax.Congruent.trans
        (FiniteAxisFoldKernelExtendedSyntax.Congruent.base_comp _ _)
        (FiniteAxisFoldKernelExtendedSyntax.Congruent.base
          (G122GeneratedComparisonSyntax.Congruent.barAlpha_hom_inv _)))))
  inv_hom_id := Quotient.sound (FiniteAxisFoldAxisSwapSyntax.Congruent.trans
    (FiniteAxisFoldAxisSwapSyntax.Congruent.base_comp _ _)
    (FiniteAxisFoldAxisSwapSyntax.Congruent.base
      (FiniteAxisFoldKernelExtendedSyntax.Congruent.trans
        (FiniteAxisFoldKernelExtendedSyntax.Congruent.base_comp _ _)
        (FiniteAxisFoldKernelExtendedSyntax.Congruent.base
          (G122GeneratedComparisonSyntax.Congruent.barAlpha_inv_hom _)))))

/-- Displayed automorphism represented by the nullary axis-swap recipe. -/
noncomputable def directAxisSwapAut :
    Aut (ofObject (.direct finiteAxisFoldG122CellInput)) where
  hom := classOf .axisDirect
  inv := classOf .axisDirect
  hom_inv_id := Quotient.sound FiniteAxisFoldAxisSwapSyntax.Congruent.axisDirect_sq
  inv_hom_id := Quotient.sound FiniteAxisFoldAxisSwapSyntax.Congruent.axisDirect_sq

/-- Displayed source automorphism for the full fixed recipe "construct the
swap, normalize it, then apply the canonical geometry section". -/
noncomputable def sectionedDirectAxisSwapAut :
    Aut (ofObject (.direct finiteAxisFoldG122CellInput)) where
  hom := classOf (.normalizeSectionDirect .axisDirect)
  inv := classOf (.normalizeSectionDirect .axisDirect)
  hom_inv_id := Quotient.sound
    FiniteAxisFoldAxisSwapSyntax.Congruent.normalizedAxisDirect_sq
  inv_hom_id := Quotient.sound
    FiniteAxisFoldAxisSwapSyntax.Congruent.normalizedAxisDirect_sq

/-- Decoding the displayed source automorphism is exactly the swap obtained
from the original axis permutation by the fixed pull-push construction. -/
theorem decoder_map_directAxisSwapAut_hom :
    decoder.map directAxisSwapAut.hom =
      finiteAxisFoldActualDirectSwapFiberAut.hom.1 := rfl

/-- The sectioned displayed recipe decodes to the complete canonical section,
not merely to an arrow with the same normalization. -/
theorem decoder_map_sectionedDirectAxisSwapAut_hom :
    decoder.map sectionedDirectAxisSwapAut.hom =
      (canonicalNormalizationAutomorphismSectionHom
        finiteAxisFoldActualDirectAdmissibleGeometry
        finiteAxisFoldNormalizedDirectSwapAut).hom.hom := rfl

/-- The displayed source automorphism is nonidentity. -/
theorem directAxisSwapAut_ne_one : directAxisSwapAut ≠ 1 := by
  intro equality
  apply finiteAxisFoldActualDirectSwapFiberAut_ne_one
  apply Iso.ext
  apply Subtype.ext
  simpa [directAxisSwapAut, decoder, G122GeneratedGeometryObject.id] using
    congrArg (fun f => decoder.map f) (congrArg Iso.hom equality)

/-- Displayed comparison group for retained `barAlpha`. -/
noncomputable abbrev ComparisonSubgroup :=
  GeneratedArrowComparisonSubgroup barAlphaIso.hom

/-- Source comparison term obtained by conjugating the displayed swap across
the displayed source-law `barAlpha`. -/
noncomputable def axisSwapComparisonElement : ComparisonSubgroup :=
  generatedArrowComparisonSectionHom barAlphaIso directAxisSwapAut

/-- Evaluate every displayed direct automorphism at the independently defined
actual admissible direct endpoint. -/
noncomputable def directAutomorphismEvaluationHom :
    Aut (ofObject (.direct finiteAxisFoldG122CellInput)) →*
      Aut finiteAxisFoldActualDirectAdmissibleGeometry where
  toFun a :=
    { hom := ObjectProperty.homMk (decoder.map a.hom)
      inv := ObjectProperty.homMk (decoder.map a.inv)
      hom_inv_id := by
        apply ObjectProperty.hom_ext
        exact (decoder.mapIso a).hom_inv_id
      inv_hom_id := by
        apply ObjectProperty.hom_ext
        exact (decoder.mapIso a).inv_hom_id }
  map_one' := by
    apply Iso.ext
    apply ObjectProperty.hom_ext
    exact decoder.map_id _
  map_mul' a b := by
    apply Iso.ext
    apply ObjectProperty.hom_ext
    exact decoder.map_comp b.hom a.hom

/-- Evaluate every displayed via-base automorphism at the independently
defined actual admissible via-base endpoint. -/
noncomputable def viaBaseAutomorphismEvaluationHom :
    Aut (ofObject (.viaBase finiteAxisFoldG122CellInput)) →*
      Aut (authoredExactViaBaseAdmissibleGeometryAt
        finiteAxisFoldBCDatumSquare
        (Discrete.mk DoubleDiamondTwoCell.second)
        Int
        (finiteAxisFoldFixedCoefficientGeometryFamily
          (Discrete.mk DoubleDiamondTwoCell.second))
        finiteCanonicalObjectNormalization_admissible) where
  toFun a :=
    { hom := ObjectProperty.homMk (decoder.map a.hom)
      inv := ObjectProperty.homMk (decoder.map a.inv)
      hom_inv_id := by
        apply ObjectProperty.hom_ext
        exact (decoder.mapIso a).hom_inv_id
      inv_hom_id := by
        apply ObjectProperty.hom_ext
        exact (decoder.mapIso a).inv_hom_id }
  map_one' := by
    apply Iso.ext
    apply ObjectProperty.hom_ext
    exact decoder.map_id _
  map_mul' a b := by
    apply Iso.ext
    apply ObjectProperty.hom_ext
    exact decoder.map_comp b.hom a.hom

/-- Decoding a displayed commuting square proves preservation of the actual
fixed `barAlpha`; preservation is not stored in a syntax constructor. -/
theorem endpointAutomorphisms_preserve_actualBarAlpha
    (pair : Aut (ofObject (.direct finiteAxisFoldG122CellInput)) ×
      Aut (ofObject (.viaBase finiteAxisFoldG122CellInput)))
    (preserves : pair ∈ ComparisonSubgroup) :
    (directAutomorphismEvaluationHom pair.1,
        viaBaseAutomorphismEvaluationHom pair.2) ∈
      FiniteAxisFoldComparisonRestrictionKernel.RawComparison := by
  change (directAutomorphismEvaluationHom pair.1).hom ≫ _ =
    _ ≫ (viaBaseAutomorphismEvaluationHom pair.2).hom
  apply ObjectProperty.hom_ext
  have mapped := congrArg (fun f => decoder.map f) preserves
  simpa [directAutomorphismEvaluationHom,
    viaBaseAutomorphismEvaluationHom] using mapped

/-- Evaluate the entire new displayed comparison group in the actual raw
comparison group. -/
noncomputable def comparisonEvaluationHom : ComparisonSubgroup →*
    FiniteAxisFoldComparisonRestrictionKernel.RawComparison where
  toFun pair :=
    ⟨(directAutomorphismEvaluationHom pair.1.1,
        viaBaseAutomorphismEvaluationHom pair.1.2),
      endpointAutomorphisms_preserve_actualBarAlpha pair.1 pair.2⟩
  map_one' := by
    apply Subtype.ext
    apply Prod.ext
    · exact map_one directAutomorphismEvaluationHom
    · exact map_one viaBaseAutomorphismEvaluationHom
  map_mul' a b := by
    apply Subtype.ext
    apply Prod.ext
    · exact map_mul directAutomorphismEvaluationHom a.1.1 b.1.1
    · exact map_mul viaBaseAutomorphismEvaluationHom a.1.2 b.1.2

/-- The decoded source of the displayed comparison is exactly the fixed
transported axis swap at the admissible direct endpoint. -/
theorem axisSwapComparisonElement_evaluation_source :
    (comparisonEvaluationHom axisSwapComparisonElement).1.1 =
      finiteAxisFoldActualDirectSwapAdmissibleAut := by
  apply Iso.ext
  apply ObjectProperty.hom_ext
  rfl

/-- Evaluation commutes with source conjugation for every displayed direct
automorphism in the new presentation. -/
theorem comparisonEvaluation_section
    (a : Aut (ofObject (.direct finiteAxisFoldG122CellInput))) :
    comparisonEvaluationHom
        (generatedArrowComparisonSectionHom barAlphaIso a) =
      generatedArrowComparisonSectionHom
        (authoredExactBarAlphaAdmissibleIsoAt
          finiteAxisFoldBCDatumSquare
          (Discrete.mk DoubleDiamondTwoCell.second)
          Int
          (finiteAxisFoldFixedCoefficientGeometryFamily
            (Discrete.mk DoubleDiamondTwoCell.second))
          finiteCanonicalObjectNormalization_admissible)
        (directAutomorphismEvaluationHom a) := by
  apply Subtype.ext
  apply Prod.ext
  · rfl
  · apply Iso.ext
    apply ObjectProperty.hom_ext
    dsimp [comparisonEvaluationHom, viaBaseAutomorphismEvaluationHom,
      generatedArrowComparisonSectionHom,
      presentationIsoConjugationAutomorphismHom,
      directAutomorphismEvaluationHom]
    rw [Functor.map_comp, Functor.map_comp]
    rfl

/-- The sectioned displayed direct recipe evaluates to the exact canonical
normalization section of the fixed normalized axis swap. -/
theorem sectionedDirectAxisSwapAut_evaluation :
    directAutomorphismEvaluationHom sectionedDirectAxisSwapAut =
      canonicalNormalizationAutomorphismSectionHom
        finiteAxisFoldActualDirectAdmissibleGeometry
        finiteAxisFoldNormalizedDirectSwapAut := by
  apply Iso.ext
  apply ObjectProperty.hom_ext
  rfl

/-- The canonical-section recipe remains nonidentity, because normalizing it
recovers the already nonidentity normalized axis swap. -/
theorem sectionedDirectAxisSwapAut_evaluation_ne_one :
    directAutomorphismEvaluationHom sectionedDirectAxisSwapAut ≠ 1 := by
  intro equality
  apply finiteAxisFoldNormalizedDirectSwapAut_ne_one
  calc
    finiteAxisFoldNormalizedDirectSwapAut =
        RealizationComparisonIdempotents.functorAutomorphismHom
          (geometryNormalizationFunctor.{0, 0} FiniteModel.carrier)
          finiteAxisFoldActualDirectAdmissibleGeometry
          (canonicalNormalizationAutomorphismSectionHom
            finiteAxisFoldActualDirectAdmissibleGeometry
            finiteAxisFoldNormalizedDirectSwapAut) :=
      (canonicalNormalizationAutomorphismSection_rightInverse
        finiteAxisFoldActualDirectAdmissibleGeometry
        finiteAxisFoldNormalizedDirectSwapAut).symm
    _ = RealizationComparisonIdempotents.functorAutomorphismHom
          (geometryNormalizationFunctor.{0, 0} FiniteModel.carrier)
          finiteAxisFoldActualDirectAdmissibleGeometry
          (directAutomorphismEvaluationHom sectionedDirectAxisSwapAut) := by
      rw [sectionedDirectAxisSwapAut_evaluation]
    _ = RealizationComparisonIdempotents.functorAutomorphismHom
          (geometryNormalizationFunctor.{0, 0} FiniteModel.carrier)
          finiteAxisFoldActualDirectAdmissibleGeometry 1 := by rw [equality]
    _ = 1 := map_one _

/-- The sectioned source term itself is nonidentity in the generated quotient. -/
theorem sectionedDirectAxisSwapAut_ne_one : sectionedDirectAxisSwapAut ≠ 1 := by
  intro equality
  apply sectionedDirectAxisSwapAut_evaluation_ne_one
  have mapped := congrArg
    (fun a => directAutomorphismEvaluationHom a) equality
  simpa using mapped

/-- Displayed comparison element whose decoder is the full actual canonical
comparison section at the fixed normalized swap. -/
noncomputable def sectionedAxisSwapComparisonElement : ComparisonSubgroup :=
  generatedArrowComparisonSectionHom barAlphaIso sectionedDirectAxisSwapAut

/-- The fixed normalized swap's canonical raw lift is represented exactly by
the source presentation, including both endpoint components. -/
theorem sectionedAxisSwapComparisonElement_evaluation :
    comparisonEvaluationHom sectionedAxisSwapComparisonElement =
      authoredExactCanonicalComparisonSectionHom
        finiteAxisFoldBCDatumSquare
        (Discrete.mk DoubleDiamondTwoCell.second)
        Int
        (finiteAxisFoldFixedCoefficientGeometryFamily
          (Discrete.mk DoubleDiamondTwoCell.second))
        finiteCanonicalObjectNormalization_admissible
        finiteAxisFoldNormalizedComparisonSwap := by
  rw [sectionedAxisSwapComparisonElement, comparisonEvaluation_section,
    sectionedDirectAxisSwapAut_evaluation]
  rfl

/-- The exact represented canonical comparison lift is nonidentity at its
source endpoint. -/
theorem sectionedAxisSwapComparisonElement_evaluation_ne_one :
    comparisonEvaluationHom sectionedAxisSwapComparisonElement ≠ 1 := by
  intro equality
  apply sectionedDirectAxisSwapAut_evaluation_ne_one
  have sourceEquality := congrArg
    (fun pair : FiniteAxisFoldComparisonRestrictionKernel.RawComparison =>
      pair.1.1) equality
  simpa [sectionedAxisSwapComparisonElement, comparisonEvaluationHom] using
    sourceEquality

/-- Exact existential source preimage of the canonical comparison section at
the fixed nonidentity normalized swap. -/
theorem finiteAxisFoldNormalizedComparisonSwap_canonicalSection_has_source_preimage :
    ∃ displayed : ComparisonSubgroup,
      comparisonEvaluationHom displayed =
        authoredExactCanonicalComparisonSectionHom
          finiteAxisFoldBCDatumSquare
          (Discrete.mk DoubleDiamondTwoCell.second)
          Int
          (finiteAxisFoldFixedCoefficientGeometryFamily
            (Discrete.mk DoubleDiamondTwoCell.second))
          finiteCanonicalObjectNormalization_admissible
          finiteAxisFoldNormalizedComparisonSwap :=
  ⟨sectionedAxisSwapComparisonElement,
    sectionedAxisSwapComparisonElement_evaluation⟩

/-- Normalize only after decoding the source presentation into the actual raw
comparison group. -/
noncomputable def normalizedEvaluationHom : ComparisonSubgroup →*
    FiniteAxisFoldComparisonRestrictionKernel.NormalizedComparison :=
  FiniteAxisFoldComparisonRestrictionKernel.restrictionHom.comp
    comparisonEvaluationHom

/-- The source endpoint of the normalized evaluation is exactly the canonical
normalization of the original transported axis swap. -/
theorem axisSwapComparisonElement_normalized_source :
    (normalizedEvaluationHom axisSwapComparisonElement).1.1 =
      finiteAxisFoldNormalizedDirectSwapAut := by
  change (geometryNormalizationFunctor.{0, 0}
      finiteAxisFoldG122FamilyInput.Carrier).mapIso
      (comparisonEvaluationHom axisSwapComparisonElement).1.1 = _
  rw [axisSwapComparisonElement_evaluation_source]
  rfl

/-- The fixed nonidentity normalized comparison has an exact source-syntax
preimage under decoder evaluation followed by canonical restriction. -/
theorem axisSwapComparisonElement_normalized_evaluation :
    normalizedEvaluationHom axisSwapComparisonElement =
      finiteAxisFoldNormalizedComparisonSwap := by
  let evaluated := normalizedEvaluationHom axisSwapComparisonElement
  calc
    normalizedEvaluationHom axisSwapComparisonElement =
        generatedArrowComparisonSectionHom finiteAxisFoldNormalizedBarAlphaIso
          (generatedArrowComparisonSourceHom
            finiteAxisFoldNormalizedBarAlphaIso.hom evaluated) := by
      exact (generatedArrowComparisonSection_source_rightInverse
        finiteAxisFoldNormalizedBarAlphaIso evaluated).symm
    _ = finiteAxisFoldNormalizedComparisonSwap := by
      change generatedArrowComparisonSectionHom
          finiteAxisFoldNormalizedBarAlphaIso evaluated.1.1 = _
      rw [show evaluated.1.1 = finiteAxisFoldNormalizedDirectSwapAut by
        exact axisSwapComparisonElement_normalized_source]
      rfl

/-- Explicit existential form of the fixed normalized comparison preimage. -/
theorem finiteAxisFoldNormalizedComparisonSwap_has_source_preimage :
    ∃ displayed : ComparisonSubgroup,
      normalizedEvaluationHom displayed =
        finiteAxisFoldNormalizedComparisonSwap :=
  ⟨axisSwapComparisonElement,
    axisSwapComparisonElement_normalized_evaluation⟩

end FiniteAxisFoldAxisSwapPresentation

end

end AAT.AG.RealizationReconstruction

#assert_standard_axioms_only AAT.AG.RealizationReconstruction
