import ResearchLean.AG.RealizationReconstruction.FiniteAxisFoldLocalKernelBackwardFaithfulness
import Formal.Util.AssertStandardAxioms

/-!
# Independent two-symbol syntax for the backward-toggle fragment

The source-owned backward toggle is an involution because its original
complete-geometry automorphism is self-inverse and every subsequent step is
functorial transport.  This file retains that provenance through the actual
normalized local-fiber-kernel element.

Independently of the semantic residual group, `FiniteAxisFoldBackwardToggleSyntax`
is the two-symbol source syntax generated by `identity` and `toggle`, with the
single multiplication rule `toggle * toggle = identity`.  Its evaluation into
the actual local-fiber kernel is injective because the constructed toggle is
nonidentity.

This is only the explicitly displayed two-element fragment.  It neither
defines syntax as a semantic range nor claims that the fragment covers the
full residual local-fiber kernel.
-/

namespace AAT.AG.RealizationReconstruction

open CategoryTheory AtomFoundation DoctrineFiberProduct GeometryTransport
open CrossStageCoherence FullGeometryNormalization

noncomputable section

set_option synthInstance.maxHeartbeats 200000
set_option maxHeartbeats 1000000

local instance finiteAxisFoldBackwardToggleSyntaxAtomDecidableEq :
    DecidableEq FiniteModel.carrier.Atom :=
  finiteAxisFoldBackwardToggleAtomDecidableEq

private theorem finiteAxisFoldExtensionBackwardGeometryFiberAut_mul_self :
    finiteAxisFoldExtensionBackwardGeometryFiberAut *
        finiteAxisFoldExtensionBackwardGeometryFiberAut = 1 := by
  apply Iso.ext
  exact finiteAxisFoldExtensionBackwardGeometryFiberAut.hom_inv_id

private theorem finiteAxisFoldTransportedExtensionBackwardAut_mul_self :
    finiteAxisFoldTransportedExtensionBackwardAut *
        finiteAxisFoldTransportedExtensionBackwardAut = 1 := by
  change
    (geomFiberTransportFunctor
        finiteAxisFoldSourceToSouthwestExtInstHom).mapAut _
          finiteAxisFoldExtensionBackwardGeometryFiberAut *
      (geomFiberTransportFunctor
        finiteAxisFoldSourceToSouthwestExtInstHom).mapAut _
          finiteAxisFoldExtensionBackwardGeometryFiberAut = 1
  rw [← map_mul,
    finiteAxisFoldExtensionBackwardGeometryFiberAut_mul_self, map_one]

private theorem finiteAxisFoldSouthwestExtensionBackwardAut_mul_self :
    finiteAxisFoldSouthwestExtensionBackwardAut *
        finiteAxisFoldSouthwestExtensionBackwardAut = 1 := by
  apply Iso.ext
  simpa [finiteAxisFoldSouthwestExtensionBackwardAut] using
    congrArg Iso.hom finiteAxisFoldTransportedExtensionBackwardAut_mul_self

private theorem finiteAxisFoldActualDirectExtensionBackwardAut_mul_self :
    finiteAxisFoldActualDirectExtensionBackwardAut *
        finiteAxisFoldActualDirectExtensionBackwardAut = 1 := by
  change
    (geomFiberTransportFunctor
        finiteAxisFoldBCDatumSquare.context.square.semantic.square.top).mapAut _
      ((exactGeometryPullFunctor
          (authoredExactLeftInput finiteAxisFoldBCDatumSquare)).mapAut _
        finiteAxisFoldSouthwestExtensionBackwardAut) *
    (geomFiberTransportFunctor
        finiteAxisFoldBCDatumSquare.context.square.semantic.square.top).mapAut _
      ((exactGeometryPullFunctor
          (authoredExactLeftInput finiteAxisFoldBCDatumSquare)).mapAut _
        finiteAxisFoldSouthwestExtensionBackwardAut) = 1
  rw [← map_mul, ← map_mul,
    finiteAxisFoldSouthwestExtensionBackwardAut_mul_self, map_one, map_one]

private theorem
    finiteAxisFoldActualDirectExtensionBackwardAdmissibleAut_mul_self :
    finiteAxisFoldActualDirectExtensionBackwardAdmissibleAut *
        finiteAxisFoldActualDirectExtensionBackwardAdmissibleAut = 1 := by
  have actualHom :
      finiteAxisFoldActualDirectExtensionBackwardAut.hom ≫
          finiteAxisFoldActualDirectExtensionBackwardAut.hom =
        𝟙 _ := by
    have equality := congrArg Iso.hom
      finiteAxisFoldActualDirectExtensionBackwardAut_mul_self
    simpa [CategoryTheory.Aut.Aut_mul_def] using equality
  apply Iso.ext
  apply ObjectProperty.hom_ext
  exact congrArg Subtype.val actualHom

/-- Functorial transport and normalization preserve the source-owned
involution equation. -/
theorem finiteAxisFoldNormalizedExtensionBackwardAut_mul_self :
    finiteAxisFoldNormalizedExtensionBackwardAut *
        finiteAxisFoldNormalizedExtensionBackwardAut = 1 := by
  change
    (geometryNormalizationFunctor FiniteModel.carrier).mapAut _
        finiteAxisFoldActualDirectExtensionBackwardAdmissibleAut *
      (geometryNormalizationFunctor FiniteModel.carrier).mapAut _
        finiteAxisFoldActualDirectExtensionBackwardAdmissibleAut = 1
  rw [← map_mul,
    finiteAxisFoldActualDirectExtensionBackwardAdmissibleAut_mul_self,
    map_one]

/-- The same involution equation inside the full residual local-fiber kernel.
All four subtype layers retain the already constructed kernel evidence. -/
theorem finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel_mul_self :
    finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel *
        finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel = 1 := by
  apply Subtype.ext
  apply Subtype.ext
  apply Subtype.ext
  apply Subtype.ext
  exact finiteAxisFoldNormalizedExtensionBackwardAut_mul_self

/-- Independent finite source syntax for the displayed backward-toggle
fragment.  In particular, it is not defined from a semantic subgroup, image,
or range. -/
inductive FiniteAxisFoldBackwardToggleSyntax
  | identity
  | toggle
  deriving DecidableEq, Fintype

namespace FiniteAxisFoldBackwardToggleSyntax

/-- Explicit multiplication on the independent two-symbol syntax. -/
def mul : FiniteAxisFoldBackwardToggleSyntax →
    FiniteAxisFoldBackwardToggleSyntax →
    FiniteAxisFoldBackwardToggleSyntax
  | identity, code => code
  | toggle, identity => toggle
  | toggle, toggle => identity

instance : One FiniteAxisFoldBackwardToggleSyntax :=
  ⟨identity⟩

instance : Mul FiniteAxisFoldBackwardToggleSyntax :=
  ⟨mul⟩

/-- Each source code is its own inverse. -/
instance : Inv FiniteAxisFoldBackwardToggleSyntax :=
  ⟨fun code => code⟩

/-- The explicit source multiplication makes the two-symbol syntax a group. -/
instance : Group FiniteAxisFoldBackwardToggleSyntax where
  mul_assoc := by
    intro first second third
    cases first <;> cases second <;> cases third <;> rfl
  one_mul := by
    intro code
    cases code <;> rfl
  mul_one := by
    intro code
    cases code <;> rfl
  inv_mul_cancel := by
    intro code
    cases code <;> rfl

@[simp] theorem identity_mul (code : FiniteAxisFoldBackwardToggleSyntax) :
    identity * code = code := by
  cases code <;> rfl

@[simp] theorem mul_identity (code : FiniteAxisFoldBackwardToggleSyntax) :
    code * identity = code := by
  cases code <;> rfl

@[simp] theorem toggle_mul_toggle :
    toggle * toggle = identity :=
  rfl

/-- Evaluate the independent source syntax in the actual normalized
local-fiber kernel.  Its only nonidentity generator is the source-owned
backward toggle constructed before this syntax was introduced. -/
noncomputable def evaluate :
    FiniteAxisFoldBackwardToggleSyntax →*
      FiniteAxisFoldResidualLocalFiberKernel where
  toFun
    | identity => 1
    | toggle => finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel
  map_one' := rfl
  map_mul' first second := by
    cases first <;> cases second
    · exact (one_mul 1).symm
    · exact
        (one_mul
          finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel).symm
    · exact
        (mul_one
          finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel).symm
    · exact
        finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel_mul_self.symm

@[simp] theorem evaluate_identity :
    evaluate identity = 1 :=
  rfl

@[simp] theorem evaluate_toggle :
    evaluate toggle =
      finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel :=
  rfl

/-- The two source codes remain distinct after evaluation.  This proves
faithfulness of this finite fragment only, not surjectivity onto the full
residual local-fiber kernel. -/
theorem evaluate_injective : Function.Injective evaluate := by
  intro first second equality
  cases first <;> cases second
  · rfl
  · exfalso
    exact finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel_ne_one
      equality.symm
  · exfalso
    exact finiteAxisFoldNormalizedExtensionBackwardLocalFiberKernel_ne_one
      equality
  · rfl

end FiniteAxisFoldBackwardToggleSyntax

#assert_standard_axioms_only AAT.AG.RealizationReconstruction

end

end AAT.AG.RealizationReconstruction
