import ResearchLean.AG.RealizationReconstruction.FiniteAxisFoldBottomKernelInvolution
import Formal.Util.AssertStandardAxioms

/-!
# The displayed involution has exactly the constructed two-point orbit

Cycle 62 proved that the source-displayed bottom restriction-kernel element
is a nontrivial involution and constructed two distinct points in every fixed
bottom-qualified lift fiber.  This file closes the formal orbit gap identified
in that cycle's adversarial review.

It constructs the two-element subgroup consisting of the identity and the
same displayed involution.  Its action orbit on the canonical lift is proved
equal to the previously constructed canonical/shifted pair, hence has
cardinality two for every bottom-normalized comparison element.  This is the
orbit of the displayed subgroup only; it does not classify the full
restriction kernel or the full lift fiber.

## Implementation notes

The subgroup carrier contains only `1` and the Cycle 61 kernel element.  Its
closure laws use the Cycle 62 source-proved square equation.  The orbit proof
unpacks subgroup membership and the standard action orbit definition; it does
not receive an orbit, a full kernel enumeration, or a completed family of
lifts as input.
-/

namespace AAT.AG.RealizationReconstruction

open CategoryTheory AtomFoundation DoctrineFiberProduct GeometryTransport
open TransportCoherence FullGeometryNormalization

noncomputable section

set_option synthInstance.maxHeartbeats 100000
set_option maxHeartbeats 500000

/-- Decidable atom equality for the fixed finite-axis-fold input. -/
local instance finiteAxisFoldBottomKernelOrbitAtomDecidableEq :
    DecidableEq FiniteModel.carrier.Atom := by
  change DecidableEq FiniteModel.FiniteAtom
  infer_instance

namespace FiniteAxisFoldBottomKernelOrbit

open FiniteAxisFoldBottomRestrictionKernel
open FiniteAxisFoldBottomKernelInvolution

/-- The opposite kernel generator also squares to identity, in the group that
acts on bottom-qualified lift fibers. -/
theorem oppositeElement_mul_self :
    MulOpposite.op element * MulOpposite.op element = 1 := by
  apply MulOpposite.unop_injective
  simpa using element_mul_self

/-- The exact two-element subgroup generated by the displayed involution. -/
noncomputable def displayedInvolutionSubgroup :
    Subgroup bottomRestrictionHom.kerᵐᵒᵖ where
  carrier := {g | g = 1 ∨ g = MulOpposite.op element}
  one_mem' := Or.inl rfl
  mul_mem' := by
    intro a b ha hb
    rcases ha with rfl | rfl <;> rcases hb with rfl | rfl
    · exact Or.inl (one_mul 1)
    · exact Or.inr (one_mul _)
    · exact Or.inr (mul_one _)
    · exact Or.inl oppositeElement_mul_self
  inv_mem' := by
    intro a ha
    rcases ha with rfl | rfl
    · exact Or.inl inv_one
    · exact Or.inr (inv_eq_of_mul_eq_one_right oppositeElement_mul_self)

/-- Both and only the identity and displayed involution belong to the
constructed subgroup. -/
theorem mem_displayedInvolutionSubgroup_iff
    (g : bottomRestrictionHom.kerᵐᵒᵖ) :
    g ∈ displayedInvolutionSubgroup ↔
      g = 1 ∨ g = MulOpposite.op element :=
  Iff.rfl

/-- The actual subgroup orbit of the canonical lift is exactly the two-point
set constructed in Cycle 62. -/
theorem orbit_canonicalLift_eq_pair (t : NormalizedBottomComparison) :
    MulAction.orbit displayedInvolutionSubgroup (canonicalLift t) =
      (canonicalShiftedPair t : Set
        (AuthoredExactCanonicalBottomComparisonLiftFiber
          finiteAxisFoldBCDatumSquare
          (Discrete.mk DoubleDiamondTwoCell.second)
          Int
          (finiteAxisFoldFixedCoefficientGeometryFamily
            (Discrete.mk DoubleDiamondTwoCell.second))
          finiteCanonicalObjectNormalization_admissible t)) := by
  ext lift
  constructor
  · intro membership
    rcases (MulAction.mem_orbit_iff.mp membership) with ⟨g, action⟩
    rcases g.property with identity | generator
    · have g_eq_one : g = 1 := Subtype.ext identity
      subst g
      have lift_eq : lift = canonicalLift t := by
        simpa using action.symm
      simp [canonicalShiftedPair, lift_eq]
    · let displayedGenerator : displayedInvolutionSubgroup :=
        ⟨MulOpposite.op element, Or.inr rfl⟩
      have g_eq_generator : g = displayedGenerator := Subtype.ext generator
      subst g
      have lift_eq : lift = shiftedLift t := by
        simpa [displayedGenerator, shiftedLift] using action.symm
      simp [canonicalShiftedPair, lift_eq]
  · intro membership
    simp only [canonicalShiftedPair, Finset.coe_insert,
      Finset.coe_singleton, Set.mem_insert_iff, Set.mem_singleton_iff] at membership
    rcases membership with rfl | rfl
    · apply MulAction.mem_orbit_iff.mpr
      refine ⟨1, ?_⟩
      exact one_smul _ _
    · let displayedGenerator : displayedInvolutionSubgroup :=
        ⟨MulOpposite.op element, Or.inr rfl⟩
      apply MulAction.mem_orbit_iff.mpr
      refine ⟨displayedGenerator, ?_⟩
      rfl

/-- The formally defined displayed-subgroup orbit has cardinality two in
every bottom-qualified lift fiber. -/
theorem orbit_canonicalLift_ncard (t : NormalizedBottomComparison) :
    (MulAction.orbit displayedInvolutionSubgroup (canonicalLift t)).ncard = 2 := by
  rw [orbit_canonicalLift_eq_pair]
  simpa using canonical_shifted_pair_card t

end FiniteAxisFoldBottomKernelOrbit

end

end AAT.AG.RealizationReconstruction

#assert_standard_axioms_only AAT.AG.RealizationReconstruction
