import ResearchLean.AG.RealizationReconstruction.MandatoryCAdmissibleCategoryObstruction
import Formal.Util.AssertStandardAxioms

/-!
# The full tagged-branch primitive reference alphabet

Cycle 13's conditional obstruction used only finite lists of architecture
objects.  This module replaces that candidate with one explicit disjoint
alphabet containing every primitive role that the closed family signature has
on the mandatory tagged branch: Atom, extraction source, architecture object,
and endpoint-indexed operation references.

The encoding below never stores a completed object map or operation-map
family.  It encodes one primitive occurrence at a time into a finite list of
architecture objects.  Consequently finite lists over the whole tagged
primitive alphabet still embed into the architecture-object type.  This is a
cardinal/provenance statement about the existing primitive declaration; it
does not yet construct the final presentation category or prove that its
endomorphisms are generated by these references.

## Implementation notes

`typeValueArchitectureObject` uses the authored `StructureMaps` type/value
pair because `ArchitectureObject` already exposes that dependent pair and its
literal projection gives the left inverse needed below.  This is used for one
primitive value at a time; using a completed source predicate or a whole
operation-map family here would violate the primitive provenance requirement.

The four constructors are encoded by lists of lengths one through four.  The
length first separates the primitive role, after which literal object equality
or the type/value left inverse recovers its payload.  A single untagged payload
encoding was rejected because it would not distinguish roles, and encoding an
operation payload without its source and target was rejected because dependent
operation identity could not then be recovered.
-/

namespace AAT.AG.RealizationReconstruction

open CategoryTheory AtomFoundation DoctrineFiberProduct
open RealizationComparisonIdempotents

universe uP vP

/-- A universal value witness for small types, encoded as an architecture
object by placing its type and value in the authored `StructureMaps` fields.
This Cycle 14 API stores one primitive value, not a completed semantic map. -/
noncomputable def typeValueArchitectureObject
    (value : Σ ValueType : Type, ValueType) :
    ArchitectureObject FiniteModel.carrier where
  configuration := FiniteModel.object.configuration
  StructureMaps := value.1
  SelectedQuantities := PUnit
  structureMaps := value.2
  selectedQuantities := PUnit.unit

/-- Read the small type and value placed in an architecture object's
`StructureMaps` fields.  This is the left-inverse API used to prove that the
Cycle 14 primitive-value encoding loses no information. -/
def readTypeValueArchitectureObject
    (object : ArchitectureObject FiniteModel.carrier) :
    Σ ValueType : Type, ValueType :=
  ⟨object.StructureMaps, object.structureMaps⟩

/-- The universal small-value encoder is a literal section of the readback;
its premise is an arbitrary small type-value pair and its conclusion is used
only for primitive-reference injectivity. -/
@[simp] theorem readTypeValueArchitectureObject_typeValueArchitectureObject
    (value : Σ ValueType : Type, ValueType) :
    readTypeValueArchitectureObject (typeValueArchitectureObject value) = value := by
  rcases value with ⟨ValueType, value⟩
  rfl

/-- Cycle 14 injectivity of the small primitive-value encoder, derived from
the constructed readback rather than assumed as a reference certificate. -/
theorem typeValueArchitectureObject_injective :
    Function.Injective typeValueArchitectureObject :=
  (Function.LeftInverse.injective
    readTypeValueArchitectureObject_typeValueArchitectureObject)

/-- The complete primitive-reference sum for the mandatory tagged branch of
`AATClosedFamilySignature`.  Its four constructors correspond exactly to the
branch's Atom, Source, Object, and endpoint-indexed Operation constructors;
the other closed-signature primitive families have no tagged constructor. -/
inductive TaggedPrimitiveReference where
  | atom (atom : FiniteModel.FiniteAtom)
  | source (source : FiniteModel.ExtractionSource)
  | object (object : ArchitectureObject FiniteModel.carrier)
  | operation {source target : ArchitectureObject FiniteModel.carrier}
      (operation : taggedOperationPackage.reading.operationReading.Op source target)

/-- Translate every actual tagged-branch `PrimitiveAtom` occurrence from the
closed family signature into the Cycle 14 sum; dependent pattern matching
shows that no other Atom constructor inhabits this branch. -/
def taggedPrimitiveAtomReference
    (atom : PrimitiveAtom (.taggedOperation : ClosedFamilyParameter)
      (.taggedOperation : FamilyRealization .taggedOperation)) :
    TaggedPrimitiveReference := by
  cases atom with
  | taggedOperation value => exact .atom value

/-- Translate every actual tagged-branch `PrimitiveSource` occurrence from
the closed signature into the Cycle 14 sum; the fixed branch has exactly the
pre-existing extraction-source constructor. -/
def taggedPrimitiveSourceReference
    (source : PrimitiveSource (.taggedOperation : ClosedFamilyParameter)
      (.taggedOperation : FamilyRealization .taggedOperation)) :
    TaggedPrimitiveReference := by
  cases source with
  | taggedOperation value => exact .source value

/-- Translate every actual tagged-branch `PrimitiveObject` occurrence into
the Cycle 14 sum while retaining the complete architecture object, not a
selected endpoint subset. -/
def taggedPrimitiveObjectReference
    (object : PrimitiveObject (.taggedOperation : ClosedFamilyParameter)
      (.taggedOperation : FamilyRealization .taggedOperation)) :
    TaggedPrimitiveReference := by
  cases object with
  | tagged value => exact .object value

/-- Translate every endpoint-indexed tagged-branch `PrimitiveOperation`
occurrence into the Cycle 14 sum.  Both endpoints and the exact existing
operation value are retained by dependent pattern matching. -/
def taggedPrimitiveOperationReference
    {source target : ArchitectureObject FiniteModel.carrier}
    (operation : PrimitiveOperation
      (.taggedOperation : ClosedFamilyParameter)
      (.taggedOperation : FamilyRealization .taggedOperation)
      (.tagged source) (.tagged target)) : TaggedPrimitiveReference := by
  cases operation with
  | tagged value => exact .operation value

/-- Encode one tagged primitive occurrence by a finite architecture-object
list.  List lengths separate the four primitive roles; operation references
retain both endpoints and encode the single dependent operation value. -/
noncomputable def taggedPrimitiveReferenceObjects :
    TaggedPrimitiveReference → List (ArchitectureObject FiniteModel.carrier)
  | .atom atom =>
      [typeValueArchitectureObject ⟨FiniteModel.FiniteAtom, atom⟩]
  | .source source =>
      let encoded := typeValueArchitectureObject ⟨FiniteModel.ExtractionSource, source⟩
      [encoded, encoded]
  | .object object => [object, object, object]
  | @TaggedPrimitiveReference.operation source target operation =>
      let encoded := typeValueArchitectureObject
        ⟨taggedOperationPackage.reading.operationReading.Op source target, operation⟩
      [source, target, encoded, encoded]

/-- The finite-list encoding of the full tagged primitive alphabet is
injective.  Equal lengths first preserve the primitive role; the universal
value readback then recovers Atom, Source, or the dependent operation after
the operation endpoints have been recovered. -/
theorem taggedPrimitiveReferenceObjects_injective :
    Function.Injective taggedPrimitiveReferenceObjects := by
  intro first second equality
  cases first with
  | atom first =>
      cases second with
      | atom second =>
          simp only [taggedPrimitiveReferenceObjects, List.cons.injEq,
            and_true] at equality
          have valueEquality := typeValueArchitectureObject_injective equality
          cases valueEquality
          rfl
      | source second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
      | object second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
      | operation second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
  | source first =>
      cases second with
      | atom second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
      | source second =>
          simp only [taggedPrimitiveReferenceObjects, List.cons.injEq,
            and_true] at equality
          have valueEquality := typeValueArchitectureObject_injective equality.1
          cases valueEquality
          rfl
      | object second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
      | operation second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
  | object first =>
      cases second with
      | atom second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
      | source second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
      | object second =>
          simp only [taggedPrimitiveReferenceObjects, List.cons.injEq,
            and_true] at equality
          cases equality.1
          rfl
      | operation second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
  | @operation firstSource firstTarget firstOperation =>
      cases second with
      | atom second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
      | source second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
      | object second =>
          have lengthEquality := congrArg List.length equality
          simp [taggedPrimitiveReferenceObjects] at lengthEquality
      | @operation secondSource secondTarget secondOperation =>
          simp only [taggedPrimitiveReferenceObjects, List.cons.injEq,
            and_true] at equality
          rcases equality with ⟨sourceEquality, targetEquality, valueEquality, _⟩
          cases sourceEquality
          cases targetEquality
          have operationEquality := typeValueArchitectureObject_injective valueEquality
          cases operationEquality
          rfl

/-- Embed every occurrence in the complete tagged primitive alphabet into the
architecture-object type by composing its finite-list encoding with Cycle
11's list embedding. -/
noncomputable def taggedPrimitiveReferenceEmbedding :
    TaggedPrimitiveReference ↪ ArchitectureObject FiniteModel.carrier :=
  (⟨taggedPrimitiveReferenceObjects,
      taggedPrimitiveReferenceObjects_injective⟩ :
    TaggedPrimitiveReference ↪ List (ArchitectureObject FiniteModel.carrier)).trans
      listArchitectureObjectEmbedding

/-- Mapping a finite list along the primitive-reference embedding is itself
injective; this is the API bridge from finite syntax over the whole alphabet
to finite architecture-object lists. -/
noncomputable def listTaggedPrimitiveReferenceMapEmbedding :
    List TaggedPrimitiveReference ↪
      List (ArchitectureObject FiniteModel.carrier) where
  toFun := List.map taggedPrimitiveReferenceEmbedding
  inj' := List.map_injective_iff.mpr taggedPrimitiveReferenceEmbedding.injective

/-- Cycle 14 cardinal/provenance conclusion: finite lists over every primitive
role available on the mandatory tagged branch embed into the full
architecture-object type.  This bounds the explicit alphabet without adding
source predicates, completed endpoint maps, or semantic endomorphisms as
primitive references. -/
noncomputable def listTaggedPrimitiveReferenceEmbedding :
    List TaggedPrimitiveReference ↪ ArchitectureObject FiniteModel.carrier :=
  listTaggedPrimitiveReferenceMapEmbedding.trans listArchitectureObjectEmbedding

/-- Enumerate every finite list over the complete tagged primitive alphabet
by architecture objects, using the inverse of the constructed embedding.  It
is an auxiliary cardinal reindexing, not a syntax decoder. -/
noncomputable def taggedPrimitiveReferenceListEnumeration :
    ArchitectureObject FiniteModel.carrier → List TaggedPrimitiveReference :=
  Function.invFun listTaggedPrimitiveReferenceEmbedding

/-- The auxiliary architecture-object enumeration covers every finite tagged
primitive-reference list because it is the inverse of the Cycle 14 embedding. -/
theorem taggedPrimitiveReferenceListEnumeration_surjective :
    Function.Surjective taggedPrimitiveReferenceListEnumeration :=
  (Function.leftInverse_invFun
    listTaggedPrimitiveReferenceEmbedding.injective).surjective

/-- Finite lists over the full tagged primitive alphabet cannot enumerate all
Boolean predicates on mandatory-C source objects.  This upgrades Cycle 11's
object-only cardinal lemma to the Atom/Source/Object/Operation alphabet. -/
theorem listTaggedPrimitiveReferences_not_surjective_choices
    (decode : List TaggedPrimitiveReference →
      (ArchitectureObject FiniteModel.carrier → Bool)) :
    ¬ Function.Surjective decode := by
  intro decodeSurjective
  exact objects_not_surjective_choices
    (decode ∘ taggedPrimitiveReferenceListEnumeration)
    (decodeSurjective.comp taggedPrimitiveReferenceListEnumeration_surjective)

/-- No decoder from finite lists over the complete tagged primitive alphabet
reaches every endomorphism of the mandatory object in the independent
admissible-package category.  Readback transfers any hypothetical surjection
to the preceding full-alphabet predicate contradiction. -/
theorem taggedSourceChoiceAdmissibleEndomorphisms_not_listPrimitiveEnumerable
    (decode : List TaggedPrimitiveReference →
      (taggedUniformFlipPackage ⟶ taggedUniformFlipPackage)) :
    ¬ Function.Surjective decode := by
  intro decodeSurjective
  have choiceSurjective : Function.Surjective
      (readTaggedSourceChoiceAdmissible ∘ decode) := by
    intro choice
    obtain ⟨code, equality⟩ :=
      decodeSurjective (taggedSourceChoiceAdmissibleMorphism choice)
    exact ⟨code, by simp [equality]⟩
  exact listTaggedPrimitiveReferences_not_surjective_choices _ choiceSurjective

/-- Cycle 14 combined obstruction for the full existing tagged primitive
alphabet.  If every presentation endomorphism is generated by a finite list
of those Atom/Source/Object/Operation references, a decoder into the
independent admissible-package category cannot be both full and
retract-generating.  The premise still has to be derived from the final
presentation syntax. -/
theorem not_full_and_retractGenerated_of_listPrimitiveGeneratedEndomorphisms
    {P : Type uP} [Category.{vP} P]
    (F : P ⥤ CanonicalNormalizationAdmissiblePackage FiniteModel.carrier)
    (listGenerated : ∀ p : P,
      ∃ decode : List TaggedPrimitiveReference → (p ⟶ p),
        Function.Surjective decode) :
    ¬ (F.Full ∧ RetractGeneratedBy F) := by
  rintro ⟨hfull, hgen⟩
  obtain ⟨p, i, r, _hir, endomorphismSurjective⟩ :=
    exists_retractEndomorphismMap_surjective F hfull hgen taggedUniformFlipPackage
  obtain ⟨decode, decodeSurjective⟩ := listGenerated p
  exact taggedSourceChoiceAdmissibleEndomorphisms_not_listPrimitiveEnumerable
    (retractEndomorphismMap F i r ∘ decode)
    (endomorphismSurjective.comp decodeSurjective)

#assert_standard_axioms_only AAT.AG.RealizationReconstruction

end AAT.AG.RealizationReconstruction
