import ResearchLean.AG.RealizationReconstruction.MandatoryCFiniteReferenceObstruction
import ResearchLean.AG.RealizationReconstruction.RetractEndomorphismLift
import ResearchLean.AG.RealizationReconstruction.AATUniformFlipKaroubi
import Formal.Util.AssertStandardAxioms

/-!
# Mandatory-C obstruction inside an independent AAT package category

The admissible-package category was defined independently in G-119 as the full
subcategory of AAT core packages satisfying canonical-normalization
admissibility.  Its morphisms are all package total morphisms; no decoder image
or presentation-membership condition is imposed on them.

This module places every mandatory-C source-choice endomorphism in that actual
category and combines the Cycle 11 cardinal obstruction with Cycle 12's
fullness/retract transfer.  It rules out decoders into this category when every
presentation endomorphism is separately proved to be generated by finite lists
of architecture-object references.  The result remains conditional on that
candidate syntax bound and does not identify this category with the still
unconstructed final `R_Theta`.
-/

namespace AAT.AG.RealizationReconstruction

open CategoryTheory AtomFoundation DoctrineFiberProduct
open RealizationComparisonIdempotents

universe uP vP

/-- Cycle 13 semantic-membership constructor: every Cycle 11 source-choice
map is an actual endomorphism of the fixed mandatory-C object in the
independently defined admissible-package category.  Full-subcategory
membership comes only from the fixed object's G-119 admissibility; the
morphism carries no decoder or comparison certificate. -/
noncomputable def taggedSourceChoiceAdmissibleMorphism
    (choice : ArchitectureObject FiniteModel.carrier → Bool) :
    taggedUniformFlipPackage ⟶ taggedUniformFlipPackage :=
  ObjectProperty.homMk (taggedSourceChoiceTotal choice)

/-- Cycle 13 readback API on the independent category hom-set.  It forgets the
full-subcategory wrapper and uses the Cycle 11 operation-level readback; no
normalization sandwich or future `R_Theta` interpretation is assumed. -/
noncomputable def readTaggedSourceChoiceAdmissible
    (f : taggedUniformFlipPackage ⟶ taggedUniformFlipPackage) :
    ArchitectureObject FiniteModel.carrier → Bool :=
  readTaggedSourceChoice f.hom

/-- The admissible-category constructor/readback pair is a literal left
inverse for every full source predicate.  This transfers Cycle 11
nonvacuity into the independently defined category rather than a toy external
function space. -/
@[simp] theorem readTaggedSourceChoiceAdmissible_taggedSourceChoiceAdmissibleMorphism
    (choice : ArchitectureObject FiniteModel.carrier → Bool) :
    readTaggedSourceChoiceAdmissible
      (taggedSourceChoiceAdmissibleMorphism choice) = choice :=
  readTaggedSourceChoice_taggedSourceChoiceTotal choice

/-- Cycle 13 semantic-family embedding theorem in the admissible-package
category, derived from the constructed readback left inverse and not from a
chosen decoder image. -/
theorem taggedSourceChoiceAdmissibleMorphism_injective :
    Function.Injective taggedSourceChoiceAdmissibleMorphism := by
  intro first second equality
  have readEquality := congrArg readTaggedSourceChoiceAdmissible equality
  simpa using readEquality

/-- Cycle 13 category-level form of the Cycle 11 obstruction: finite lists of
mandatory-C source-object references cannot enumerate every endomorphism of
the fixed object in the independent admissible-package category. -/
theorem taggedSourceChoiceAdmissibleEndomorphisms_not_listObjectEnumerable
    (decode : List (ArchitectureObject FiniteModel.carrier) →
      (taggedUniformFlipPackage ⟶ taggedUniformFlipPackage)) :
    ¬ Function.Surjective decode := by
  intro decodeSurjective
  have choiceSurjective : Function.Surjective
      (readTaggedSourceChoiceAdmissible ∘ decode) := by
    intro choice
    obtain ⟨code, equality⟩ :=
      decodeSurjective (taggedSourceChoiceAdmissibleMorphism choice)
    exact ⟨code, by simp [equality]⟩
  exact listArchitectureObjects_not_surjective_choices _ choiceSurjective

/-- Combined Cycle 11--13 obstruction for one explicit candidate grammar.
If every presentation endomorphism is separately a surjective image of finite
mandatory-C source-object reference lists, no decoder into the independent
admissible-package category can be both full and retract-generating.  The list
generation premise must be proved for an actual syntax; this theorem neither
assumes nor concludes anything about richer source-provenanced alphabets. -/
theorem not_full_and_retractGenerated_of_listObjectGeneratedEndomorphisms
    {P : Type uP} [Category.{vP} P]
    (F : P ⥤ CanonicalNormalizationAdmissiblePackage FiniteModel.carrier)
    (listGenerated : ∀ p : P,
      ∃ decode : List (ArchitectureObject FiniteModel.carrier) → (p ⟶ p),
        Function.Surjective decode) :
    ¬ (F.Full ∧ RetractGeneratedBy F) := by
  rintro ⟨hfull, hgen⟩
  obtain ⟨p, i, r, _hir, endomorphismSurjective⟩ :=
    exists_retractEndomorphismMap_surjective F hfull hgen taggedUniformFlipPackage
  obtain ⟨decode, decodeSurjective⟩ := listGenerated p
  exact taggedSourceChoiceAdmissibleEndomorphisms_not_listObjectEnumerable
    (retractEndomorphismMap F i r ∘ decode)
    (endomorphismSurjective.comp decodeSurjective)

#assert_standard_axioms_only AAT.AG.RealizationReconstruction

end AAT.AG.RealizationReconstruction
