import Formal.Arch.AAT.GeneratedGraph
import Formal.Arch.AAT.ZeroCurvature
import Formal.Arch.Core.Finite
import Formal.Arch.Signature.SignatureLawfulness

namespace Formal.Arch
namespace AAT

universe u v

namespace GeneratedArchitectureObject

/-- Identity projection generated from the carrier of a generated object. -/
def generatedProjection {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    (object : GeneratedArchitectureObject presentation) :
    InterfaceProjection (GeneratedCarrier object) (GeneratedCarrier object) where
  expose := id

/-- Generated abstract graph for the identity projection. -/
def generatedAbstractGraph {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    (object : GeneratedArchitectureObject presentation) :
    AbstractGraph (GeneratedCarrier object) :=
  GeneratedArchGraph object

/-- Boundary policy generated from the relation surface. -/
def generatedBoundaryAllowed {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    (object : GeneratedArchitectureObject presentation)
    (source target : GeneratedCarrier object) : Prop :=
  GeneratedRelation object source target

/-- Abstraction policy generated from the same relation surface. -/
def generatedAbstractionAllowed {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    (object : GeneratedArchitectureObject presentation)
    (source target : GeneratedCarrier object) : Prop :=
  GeneratedRelation object source target

/-- Finite component universe generated by the object's carrier list. -/
def generatedComponentUniverse {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    (object : GeneratedArchitectureObject presentation) :
    ComponentUniverse (GeneratedArchGraph object) where
  components := object.carrierList
  nodup := object.carrierListNodup
  covers := object.carrierListCovers
  edgeClosed := by
    intro source target _hEdge
    exact ⟨object.carrierListCovers source,
      object.carrierListCovers target⟩

end GeneratedArchitectureObject

/--
Generated law model over a generated architecture object.

The representation model is constructed by `toArchitectureLawModel`; it is not
stored as a hand-authored field.
-/
structure GeneratedArchitectureLawModel {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    (object : GeneratedArchitectureObject presentation) where
  generatedWalkAcyclic : WalkAcyclic (GeneratedArchGraph object)
  lawModelBoundary : Prop

namespace GeneratedArchitectureLawModel

/-- Construct the existing Signature law model from generated object surfaces. -/
def toArchitectureLawModel {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (_model : GeneratedArchitectureLawModel object) :
    ArchitectureSignature.ArchitectureLawModel
      (GeneratedCarrier object)
      (GeneratedCarrier object)
      GeneratedObservationCoordinate where
  G := GeneratedArchGraph object
  π := object.generatedProjection
  GA := object.generatedAbstractGraph
  O := object.generatedObservation
  U := object.generatedComponentUniverse
  boundaryAllowed := object.generatedBoundaryAllowed
  abstractionAllowed := object.generatedAbstractionAllowed
  lspPairClosed := by
    intro x y _hSame
    exact ⟨object.carrierListCovers x, object.carrierListCovers y⟩

/-- Projection soundness follows because the generated projection is identity. -/
theorem generated_projection_sound
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (_model : GeneratedArchitectureLawModel object) :
    ProjectionSound
      (GeneratedArchGraph object)
      object.generatedProjection
      object.generatedAbstractGraph := by
  intro _source _target hEdge
  exact hEdge

/-- Generated observation is LSP-compatible under the identity projection. -/
theorem generated_lsp_compatible
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (_model : GeneratedArchitectureLawModel object) :
    LSPCompatible object.generatedProjection object.generatedObservation := by
  intro x y hSame
  cases hSame
  rfl

/-- Generated boundary policy is sound for generated graph edges. -/
theorem generated_boundary_policy_sound
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (_model : GeneratedArchitectureLawModel object) :
    ArchitectureSignature.PolicySound
      (GeneratedArchGraph object)
      object.generatedBoundaryAllowed := by
  intro _source _target hEdge
  exact hEdge

/-- Generated abstraction policy is sound for generated graph edges. -/
theorem generated_abstraction_policy_sound
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (_model : GeneratedArchitectureLawModel object) :
    ArchitectureSignature.PolicySound
      (GeneratedArchGraph object)
      object.generatedAbstractionAllowed := by
  intro _source _target hEdge
  exact hEdge

/-- Generated law models satisfy the existing architecture lawfulness predicate. -/
theorem generatedArchitectureLawful
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (model : GeneratedArchitectureLawModel object) :
    ArchitectureSignature.ArchitectureLawful model.toArchitectureLawModel := by
  exact
    ⟨model.generatedWalkAcyclic,
      model.generated_projection_sound,
      model.generated_lsp_compatible,
      model.generated_boundary_policy_sound,
      model.generated_abstraction_policy_sound⟩

/--
Generated objects produce generated law models once the generated graph
acyclicity premise is supplied.

The existing `ArchitectureLawModel` is constructed by `toArchitectureLawModel`;
it is not a caller-supplied representation field.
-/
theorem generated_law_model_from_generated_object
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (hWalkAcyclic : WalkAcyclic (GeneratedArchGraph object))
    (lawModelBoundary : Prop) :
    ∃ model : GeneratedArchitectureLawModel object,
      ArchitectureSignature.ArchitectureLawful model.toArchitectureLawModel := by
  let model : GeneratedArchitectureLawModel object :=
    { generatedWalkAcyclic := hWalkAcyclic
      lawModelBoundary := lawModelBoundary }
  exact ⟨model, model.generatedArchitectureLawful⟩

/-- Signature required axes are zero for generated law models. -/
def generatedSignatureOf
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    [DecidableEq system.Atom]
    [hRelation : DecidableRel (GeneratedRelation object)]
    (model : GeneratedArchitectureLawModel object) :
    ArchitectureSignature.ArchitectureSignatureV1 := by
  letI : DecidableRel model.toArchitectureLawModel.G.edge := by
    intro source target
    change Decidable (GeneratedRelation object source target)
    exact hRelation source target
  letI : DecidableRel model.toArchitectureLawModel.GA.edge := by
    intro source target
    change Decidable (GeneratedRelation object source target)
    exact hRelation source target
  letI : DecidableRel model.toArchitectureLawModel.boundaryAllowed := by
    intro source target
    change Decidable (GeneratedRelation object source target)
    exact hRelation source target
  letI : DecidableRel model.toArchitectureLawModel.abstractionAllowed := by
    intro source target
    change Decidable (GeneratedRelation object source target)
    exact hRelation source target
  exact ArchitectureSignature.ArchitectureLawModel.signatureOf
    model.toArchitectureLawModel

/-- Signature required axes are zero for generated law models. -/
theorem generated_requiredSignatureAxesZero
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    [DecidableEq system.Atom]
    [hRelation : DecidableRel (GeneratedRelation object)]
    (model : GeneratedArchitectureLawModel object) :
    ArchitectureSignature.RequiredSignatureAxesZero
      (model.generatedSignatureOf) := by
  letI : DecidableRel model.toArchitectureLawModel.G.edge := by
    intro source target
    change Decidable (GeneratedRelation object source target)
    exact hRelation source target
  letI : DecidableRel model.toArchitectureLawModel.GA.edge := by
    intro source target
    change Decidable (GeneratedRelation object source target)
    exact hRelation source target
  letI : DecidableRel model.toArchitectureLawModel.boundaryAllowed := by
    intro source target
    change Decidable (GeneratedRelation object source target)
    exact hRelation source target
  letI : DecidableRel model.toArchitectureLawModel.abstractionAllowed := by
    intro source target
    change Decidable (GeneratedRelation object source target)
    exact hRelation source target
  exact
    (ArchitectureSignature.architectureLawful_iff_requiredSignatureAxesZero
      model.toArchitectureLawModel).mp
      model.generatedArchitectureLawful

/-- The selected pure molecule generated by an architecture object. -/
def requiredGeneratedMolecule
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (_model : GeneratedArchitectureLawModel object)
    (molecule : Molecule system) : Prop :=
  molecule = object.molecule.toMolecule

/--
Pure AAT design law generated from a generated law model.

The selected generated molecule is bad only when the generated Signature
lawfulness theorem fails.  Since generated lawfulness is proved by
`generatedArchitectureLawful`, this law has no required obstruction circuit on
the generated molecule.
-/
def generatedDesignLaw
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (model : GeneratedArchitectureLawModel object) :
    DesignLaw system where
  Bad := fun molecule =>
    model.requiredGeneratedMolecule molecule ∧
      ¬ ArchitectureSignature.ArchitectureLawful model.toArchitectureLawModel
  evaluationBoundary := model.lawModelBoundary
  nonConclusions := True

/-- Pure AAT core generated from the selected generated object and law model. -/
def generatedAATCore
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (model : GeneratedArchitectureLawModel object) :
    AATCore system where
  molecules := model.requiredGeneratedMolecule
  moleculeAtomsPrimitive := by
    intro molecule hMolecule atom hAtom
    subst molecule
    exact object.molecule.atoms_primitive hAtom
  laws := fun law => law = model.generatedDesignLaw
  circuits := fun _hLaw _hMolecule _hCircuit => True
  circuitEvidence := by
    intro _law _molecule _hLaw _hMolecule _hCircuit
    trivial
  noObservationDependency := True
  noObservationDependencyEvidence := trivial
  noLawCreatesAtomsEvidence := system.law_does_not_create_atoms
  moleculeBoundary := object.objectBoundary
  lawBoundary := model.lawModelBoundary
  circuitBoundary := True
  nonConclusions := True

/-- The generated design law is selected in its generated AAT core. -/
theorem generated_law_on_core
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (model : GeneratedArchitectureLawModel object) :
    model.generatedAATCore.laws model.generatedDesignLaw := by
  rfl

/-- The generated molecule is selected in its generated AAT core. -/
theorem generated_molecule_on_core
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (model : GeneratedArchitectureLawModel object) :
    model.generatedAATCore.molecules object.molecule.toMolecule := by
  rfl

/-- Generated law models have no required pure AAT obstruction circuit. -/
theorem generated_noRequiredObstructionCircuit
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (model : GeneratedArchitectureLawModel object) :
    NoRequiredObstructionCircuit
      model.generatedDesignLaw
      model.requiredGeneratedMolecule := by
  intro molecule _hRequired hCircuit
  exact (obstructionCircuit_bad hCircuit).2 model.generatedArchitectureLawful

/-- Generated lawfulness supplies the pure AAT lawfulness bridge. -/
def generatedLawfulnessBridge
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (model : GeneratedArchitectureLawModel object) :
    LawfulnessBridge
      model.generatedDesignLaw
      model.requiredGeneratedMolecule where
  badWitnessComplete := by
    intro _molecule _hRequired hBad
    exact False.elim (hBad.2 model.generatedArchitectureLawful)
  circuitBad := by
    intro _molecule _hRequired hCircuit
    exact obstructionCircuit_bad hCircuit
  coverageBoundary := model.lawModelBoundary
  exactnessBoundary := model.lawModelBoundary
  nonConclusions := True

/--
Generated law models produce the existing pure AAT zero-curvature theorem
package without an `architectureLawfulFromAAT` bridge field.
-/
def generatedZeroCurvaturePackage
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (model : GeneratedArchitectureLawModel object) :
    ZeroCurvaturePackage model.generatedAATCore where
  law := model.generatedDesignLaw
  requiredMolecule := model.requiredGeneratedMolecule
  lawOnCore := model.generated_law_on_core
  requiredMoleculesOnCore := by
    intro molecule hRequired
    exact hRequired
  requiredCircuitsOnCore := by
    intro _molecule _hRequired _hCircuit
    trivial
  lawfulnessBridge := model.generatedLawfulnessBridge
  zeroCurvature :=
    zeroCurvature_iff_noRequiredObstructionCircuit.mpr
      model.generated_noRequiredObstructionCircuit
  coverageBoundary := model.lawModelBoundary
  exactnessBoundary := model.lawModelBoundary
  theoremPackageBoundary := model.lawModelBoundary
  nonConclusions := True

/-- Generated law models are lawful within the pure AAT molecule configuration. -/
theorem generated_lawfulWithinMoleculeConfiguration
    {system : AtomAxiomSystem.{u, v}}
    {presentation : AtomShapePresentation system}
    {object : GeneratedArchitectureObject presentation}
    (model : GeneratedArchitectureLawModel object) :
    LawfulWithinMoleculeConfiguration
      model.generatedDesignLaw
      model.requiredGeneratedMolecule :=
  model.generatedZeroCurvaturePackage.lawfulWithinMoleculeConfiguration

end GeneratedArchitectureLawModel

end AAT
end Formal.Arch
