import ResearchLean.AG.QualitySurface.LawGeneratedBooleanCirclePrimitiveAtlas
import ResearchLean.AG.QualitySurface.LawGeneratedLargeCoefficientH0
import Formal.Util.AssertStandardAxioms
import Mathlib.Tactic

/-!
# Law-generated conormal first-order descent package

This file closes the G-07 theorem package on the fixed Boolean-circle
law-generated example.  It transports the kernel-section torsor through the
canonical `H⁰` comparison and through both first-order repair
representations, records choice independence and the primary effectivity
equivalence, and states the universal `H¹`-vanishing consequence.
-/

noncomputable section

namespace ResearchLean.AG.QualitySurface
namespace LawGeneratedConormalFirstOrderDescentPackage

open CategoryTheory Opposite
open AAT.AG
open AAT.AG.LawAlgebra
open LawGeneratedLargeCoefficientCech
open LawGeneratedLargeCoefficientH0
open LawGeneratedLargeConormalDescent
open LawGeneratedIdealPowerLiftedSheafification
open LawGeneratedSemanticFirstOrderRepair
open LawGeneratedBooleanCircleSite
open LawGeneratedBooleanCircleLawCore
open LawGeneratedBooleanCircleConormalH1Pair
open LawGeneratedBooleanCirclePrimitiveAtlas

/-- The concrete local-lift problem generated by the primitive square-zero atlas. -/
abbrev SquareZeroLocalLiftData :=
  toLocalLiftData squareZeroCore squareZeroLawfulReadingRepresentation

/-- The canonical short exactness proof for the concrete square-zero sequence. -/
abbrev squareZeroShortExact :=
  sheafifiedShortComplex_shortExact squareZeroCore

/-- Cover-relative degree-zero conormal cohomology for the fixed square-zero core. -/
abbrev SquareZeroH0 :=
  H0 geometry (AdditiveSequence squareZeroCore).X₁.val

/-- The `H⁰` action on actual global first-order lifts. -/
def squareZeroH0Action (c : SquareZeroH0)
    (lift : SquareZeroLocalLiftData.GlobalLift) :
    SquareZeroLocalLiftData.GlobalLift :=
  SquareZeroLocalLiftData.kernelAction squareZeroShortExact
    ((lawGeneratedConormalSectionsEquivH0 (geometry := geometry)
      squareZeroCore).symm c) lift

/-- The `H⁰` action on a nonempty global-lift fiber is simply transitive. -/
theorem squareZeroGlobalLift_h0_simplyTransitive
    (left right : SquareZeroLocalLiftData.GlobalLift) :
    ∃! c : SquareZeroH0, squareZeroH0Action c left = right := by
  let e := lawGeneratedConormalSectionsEquivH0 (geometry := geometry) squareZeroCore
  letI : Nonempty SquareZeroLocalLiftData.GlobalLift := ⟨left⟩
  obtain ⟨n, hn, hunique⟩ :=
    SquareZeroLocalLiftData.globalLiftFiber_simplyTransitive
      squareZeroShortExact left right
  refine ⟨e n, ?_, ?_⟩
  · simpa [squareZeroH0Action, e] using hn
  · intro c hc
    have hc' : SquareZeroLocalLiftData.kernelAction squareZeroShortExact
        (e.symm c) left = right := by
      simpa [squareZeroH0Action, e] using hc
    have heq : e.symm c = n := hunique (e.symm c) hc'
    calc
      c = e (e.symm c) := (e.apply_symm_apply c).symm
      _ = e n := congrArg e heq

/-- Internal first-order lifts and semantic correction primitives are equivalent. -/
noncomputable def squareZeroInternalFirstOrderLiftSemanticRepairEquiv :
    InternalFirstOrderLift squareZeroCore squareZeroLawfulReadingRepresentation ≃
      SemanticFirstOrderRepair squareZeroCore squareZeroLawfulReadingRepresentation :=
  (internalFirstOrderLiftEquiv squareZeroCore squareZeroLawfulReadingRepresentation).trans
    (SemanticFirstOrderRepairEquiv squareZeroCore
      squareZeroLawfulReadingRepresentation).symm

/-- The transported `H⁰` action on internal first-order lifts. -/
def squareZeroInternalH0Action (c : SquareZeroH0)
    (repair : InternalFirstOrderLift squareZeroCore
      squareZeroLawfulReadingRepresentation) :
    InternalFirstOrderLift squareZeroCore squareZeroLawfulReadingRepresentation :=
  (internalFirstOrderLiftEquiv squareZeroCore
      squareZeroLawfulReadingRepresentation).symm
    (squareZeroH0Action c
      (internalFirstOrderLiftEquiv squareZeroCore
        squareZeroLawfulReadingRepresentation repair))

/-- The transported `H⁰` action on semantic first-order repairs. -/
def squareZeroSemanticH0Action (c : SquareZeroH0)
    (repair : SemanticFirstOrderRepair squareZeroCore
      squareZeroLawfulReadingRepresentation) :
    SemanticFirstOrderRepair squareZeroCore squareZeroLawfulReadingRepresentation :=
  (SemanticFirstOrderRepairEquiv squareZeroCore
      squareZeroLawfulReadingRepresentation).symm
    (squareZeroH0Action c
      (SemanticFirstOrderRepairEquiv squareZeroCore
        squareZeroLawfulReadingRepresentation repair))

/-- The `H⁰` action on a nonempty internal-repair fiber is simply transitive. -/
theorem squareZeroInternalRepair_h0_simplyTransitive
    (left right : InternalFirstOrderLift squareZeroCore
      squareZeroLawfulReadingRepresentation) :
    ∃! c : SquareZeroH0, squareZeroInternalH0Action c left = right := by
  let e := internalFirstOrderLiftEquiv squareZeroCore
    squareZeroLawfulReadingRepresentation
  letI : Nonempty SquareZeroLocalLiftData.GlobalLift := ⟨e left⟩
  obtain ⟨c, hc, hunique⟩ :=
    squareZeroGlobalLift_h0_simplyTransitive (e left) (e right)
  refine ⟨c, ?_, ?_⟩
  · apply e.injective
    simpa [squareZeroInternalH0Action, e] using hc
  · intro d hd
    apply hunique d
    have := congrArg e hd
    simpa [squareZeroInternalH0Action, e] using this

/-- The `H⁰` action on a nonempty semantic-repair fiber is simply transitive. -/
theorem squareZeroSemanticRepair_h0_simplyTransitive
    (left right : SemanticFirstOrderRepair squareZeroCore
      squareZeroLawfulReadingRepresentation) :
    ∃! c : SquareZeroH0, squareZeroSemanticH0Action c left = right := by
  let e := SemanticFirstOrderRepairEquiv squareZeroCore
    squareZeroLawfulReadingRepresentation
  letI : Nonempty SquareZeroLocalLiftData.GlobalLift := ⟨e left⟩
  obtain ⟨c, hc, hunique⟩ :=
    squareZeroGlobalLift_h0_simplyTransitive (e left) (e right)
  refine ⟨c, ?_, ?_⟩
  · apply e.injective
    simpa [squareZeroSemanticH0Action, e] using hc
  · intro d hd
    apply hunique d
    have := congrArg e hd
    simpa [squareZeroSemanticH0Action, e] using this

/-! ## Generic law-generated package API -/

universe u

variable {U : AtomCarrier.{u}} {A : ArchitectureObject U}
variable {S : Site.AATSite A}
variable {geometry' : Site.FinitePosetCoverGeometry S}

/-- Cover-relative conormal `H⁰` for an architectural equation system. -/
abbrev LawGeneratedH0
    (G : ArchitecturalEquationSystem S.contextPreorder) :=
  H0 geometry' (AdditiveSequence G).X₁.val

/-- The canonical `H⁰` action on a law-generated global-lift fiber. -/
def globalLiftH0Action
    (G : ArchitecturalEquationSystem S.contextPreorder)
    (atlas : ExplicitLawGeneratedReadingAtlas (geometry := geometry') G)
    (c : LawGeneratedH0 (geometry' := geometry') G)
    (lift : (toLocalLiftData G atlas).GlobalLift) :
    (toLocalLiftData G atlas).GlobalLift :=
  (toLocalLiftData G atlas).kernelAction
    (sheafifiedShortComplex_shortExact G)
    ((lawGeneratedConormalSectionsEquivH0 (geometry := geometry') G).symm c) lift

/-- The generic global-lift fiber is simply transitive under conormal `H⁰`. -/
theorem globalLiftH0Action_simplyTransitive
    (G : ArchitecturalEquationSystem S.contextPreorder)
    (atlas : ExplicitLawGeneratedReadingAtlas (geometry := geometry') G)
    (left right : (toLocalLiftData G atlas).GlobalLift) :
    ∃! c : LawGeneratedH0 (geometry' := geometry') G,
      globalLiftH0Action G atlas c left = right := by
  let P := toLocalLiftData G atlas
  let hK := sheafifiedShortComplex_shortExact G
  let e := lawGeneratedConormalSectionsEquivH0 (geometry := geometry') G
  letI : Nonempty P.GlobalLift := ⟨left⟩
  obtain ⟨n, hn, hunique⟩ := P.globalLiftFiber_simplyTransitive hK left right
  refine ⟨e n, ?_, ?_⟩
  · simpa [globalLiftH0Action, P, hK, e] using hn
  · intro c hc
    apply e.symm.injective
    rw [e.symm_apply_apply]
    exact hunique (e.symm c) (by
      simpa [globalLiftH0Action, P, hK, e] using hc)

/-- The canonical `H⁰` action transported to semantic correction primitives. -/
def semanticRepairH0Action
    (G : ArchitecturalEquationSystem S.contextPreorder)
    (atlas : ExplicitLawGeneratedReadingAtlas (geometry := geometry') G)
    (c : LawGeneratedH0 (geometry' := geometry') G)
    (repair : SemanticFirstOrderRepair G atlas) :
    SemanticFirstOrderRepair G atlas :=
  (SemanticFirstOrderRepairEquiv G atlas).symm
    (globalLiftH0Action G atlas c (SemanticFirstOrderRepairEquiv G atlas repair))

/-- The semantic-repair fiber is simply transitive under conormal `H⁰`. -/
theorem semanticRepairH0Action_simplyTransitive
    (G : ArchitecturalEquationSystem S.contextPreorder)
    (atlas : ExplicitLawGeneratedReadingAtlas (geometry := geometry') G)
    (left right : SemanticFirstOrderRepair G atlas) :
    ∃! c : LawGeneratedH0 (geometry' := geometry') G,
      semanticRepairH0Action G atlas c left = right := by
  let e := SemanticFirstOrderRepairEquiv G atlas
  obtain ⟨c, hc, hunique⟩ :=
    globalLiftH0Action_simplyTransitive G atlas (e left) (e right)
  refine ⟨c, ?_, ?_⟩
  · apply e.injective
    simpa [semanticRepairH0Action, e] using hc
  · intro d hd
    apply hunique d
    have := congrArg e hd
    simpa [semanticRepairH0Action, e] using this

/-- Internal first-order lifts and semantic repairs are generically equivalent. -/
noncomputable def internalFirstOrderLiftSemanticRepairEquiv
    (G : ArchitecturalEquationSystem S.contextPreorder)
    (atlas : ExplicitLawGeneratedReadingAtlas (geometry := geometry') G) :
    InternalFirstOrderLift G atlas ≃ SemanticFirstOrderRepair G atlas :=
  (internalFirstOrderLiftEquiv G atlas).trans
    (SemanticFirstOrderRepairEquiv G atlas).symm

/-- Universal `H¹` vanishing globalizes every explicit locally liftable atlas. -/
theorem allGlobalLifts_nonempty_of_H1_isZero
    (G : ArchitecturalEquationSystem S.contextPreorder)
    (hzero : ∀ x : H1 geometry' (AdditiveSequence G).X₁.val,
      (threeTermComplex geometry' (AdditiveSequence G).X₁.val).H1IsZero x)
    (atlas : ExplicitLawGeneratedReadingAtlas (geometry := geometry') G) :
    Nonempty (toLocalLiftData G atlas).GlobalLift := by
  let P := toLocalLiftData G atlas
  let hK := sheafifiedShortComplex_shortExact G
  apply (P.connectingClassFor_isZero_iff_nonempty_globalLift
    hK P.chosenGeneratorLocalLiftFamily).mp
  exact hzero _

/--
The complete law-generated conormal first-order descent package: choice
independence, actual effectivity, both repair representations, the conormal
`H⁰` torsor action, the universal `H¹` consequence, and the fixed nonvacuity
witnesses.
-/
theorem lawGeneratedConormalFirstOrderDescent_package
    (G : ArchitecturalEquationSystem S.contextPreorder)
    (atlas : ExplicitLawGeneratedReadingAtlas (geometry := geometry') G) :
    let P := toLocalLiftData G atlas
    let hK := sheafifiedShortComplex_shortExact G
    let C := threeTermComplex geometry' (AdditiveSequence G).X₁.val
    let H0G := H0 geometry' (AdditiveSequence G).X₁.val
    (∀ left right : P.GeneratorLocalLiftFamily,
      P.connectingClassFor hK left = P.connectingClassFor hK right) ∧
    (C.H1IsZero (P.connectingClass hK) ↔ Nonempty P.GlobalLift) ∧
    (C.H1IsZero (P.connectingClass hK) ↔
      Nonempty (InternalFirstOrderLift G atlas)) ∧
    Nonempty
      ((AdditiveSequence G).X₁.val.obj (op geometry'.base) ≃+ H0G) ∧
    Nonempty (SemanticFirstOrderRepair G atlas ≃ P.GlobalLift) ∧
    Nonempty (InternalFirstOrderLift G atlas ≃
      SemanticFirstOrderRepair G atlas) ∧
    (∀ left right : P.GlobalLift,
      ∃! c : H0G, globalLiftH0Action G atlas c left = right) ∧
    (∀ left right : SemanticFirstOrderRepair G atlas,
      ∃! c : H0G, semanticRepairH0Action G atlas c left = right) ∧
    ((∀ x : H1 geometry' (AdditiveSequence G).X₁.val, C.H1IsZero x) →
      ∀ atlas' : ExplicitLawGeneratedReadingAtlas (geometry := geometry') G,
        Nonempty (toLocalLiftData G atlas').GlobalLift) ∧
    additiveAtlasQ0Reading squareZeroCore squareZeroLawfulReadingRepresentation ≠ 0 ∧
    ((∀ x : H1 LawGeneratedBooleanCircleSite.geometry
        LawGeneratedBooleanCircleConormalH1Pair.IdempotentX1,
      (threeTermComplex LawGeneratedBooleanCircleSite.geometry
        LawGeneratedBooleanCircleConormalH1Pair.IdempotentX1).H1IsZero x) ∧
      ¬ (threeTermComplex LawGeneratedBooleanCircleSite.geometry
          LawGeneratedBooleanCircleSquareZeroH1.SquareZeroX1).H1IsZero
        (h1Class LawGeneratedBooleanCircleSite.geometry
          LawGeneratedBooleanCircleSquareZeroH1.SquareZeroX1
          LawGeneratedBooleanCircleSquareZeroH1.squareZeroOmegaCocycle)) := by
  dsimp only
  let P := toLocalLiftData G atlas
  let hK := sheafifiedShortComplex_shortExact G
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro left right
    exact P.connectingClass_choice_independent hK left right
  · change
      (threeTermComplex geometry' (AdditiveSequence G).X₁.val).H1IsZero
          (P.connectingClassFor hK P.chosenGeneratorLocalLiftFamily) ↔
        Nonempty P.GlobalLift
    exact P.connectingClassFor_isZero_iff_nonempty_globalLift
      hK P.chosenGeneratorLocalLiftFamily
  · exact connectingClass_isZero_iff_nonempty_internalFirstOrderLift G atlas
  · exact ⟨lawGeneratedConormalSectionsEquivH0 (geometry := geometry') G⟩
  · exact ⟨SemanticFirstOrderRepairEquiv G atlas⟩
  · exact ⟨internalFirstOrderLiftSemanticRepairEquiv G atlas⟩
  · exact globalLiftH0Action_simplyTransitive G atlas
  · exact semanticRepairH0Action_simplyTransitive G atlas
  · intro hzero atlas'
    exact allGlobalLifts_nonempty_of_H1_isZero G hzero atlas'
  · simpa [squareZeroLawfulReadingRepresentation] using
      squareZeroAdditiveAtlasQ0Reading_ne_zero
  · exact conormalH1_zero_nonzero_pair

end LawGeneratedConormalFirstOrderDescentPackage
end ResearchLean.AG.QualitySurface

#assert_standard_axioms_only ResearchLean.AG.QualitySurface.LawGeneratedConormalFirstOrderDescentPackage
