import ResearchLean.AG.QualitySurface.LawGeneratedLargeCoefficientCech
import ResearchLean.AG.QualitySurface.LawGeneratedIdealPowerLiftedSheafification
import Formal.Util.AssertStandardAxioms
import Mathlib.Algebra.AddTorsor.Defs
import Mathlib.Algebra.Category.Grp.Limits
import Mathlib.Algebra.Homology.ShortComplex.ShortExact
import Mathlib.CategoryTheory.Sites.Abelian
import Mathlib.CategoryTheory.Sites.Limits
import Mathlib.Tactic

/-!
# Large-coefficient additive lift descent

For a selected finite-poset cover and a short exact complex of bundled
`AddCommGrpCat`-valued sheaves, this file constructs the connecting Cech class
of an explicitly locally liftable section and proves independence from the
chosen generator-local lifts.  The equivalence between class vanishing and an
actual global lift, selected-cover gluing, and the lift-fiber torsor remain the
next proof obligations.

The kernel comparison is derived from `ShortComplex.ShortExact`: evaluation at
each site object preserves the kernel limit.  No exactness, effectivity, class
vanishing, compatible family, global lift, or torsor conclusion is stored in
the local-lift input data.
-/

noncomputable section

namespace ResearchLean.AG.QualitySurface
namespace LawGeneratedLargeConormalDescent

universe u

open CategoryTheory Limits Opposite
open AAT.AG

variable {U : AtomCarrier.{u}} {A : ArchitectureObject U}
variable {S : Site.AATSite A}
variable {geometry : Site.FinitePosetCoverGeometry S}

/-! ## Sectionwise kernel generated by categorical short exactness -/

/-- Evaluation of a bundled sheaf at one site object. -/
abbrev sectionFunctor (W : S.categoryᵒᵖ) :=
  (sheafSections S.topology AddCommGrpCat.{u + 1}).obj W

set_option synthInstance.maxHeartbeats 100000 in
/-- Evaluation carries the sheaf-level kernel fork to a limiting section fork. -/
noncomputable def sectionKernelIsLimit
    (K : ShortComplex (Sheaf S.topology AddCommGrpCat.{u + 1}))
    (hK : K.ShortExact) (W : S.categoryᵒᵖ) :
    IsLimit (KernelFork.ofι (K.f.val.app W) (by
      change (K.f ≫ K.g).val.app W = (0 : K.X₁ ⟶ K.X₃).val.app W
      exact congrArg (fun eta ↦ eta.val.app W) K.zero)) := by
  let hPresheaf := KernelFork.mapIsLimit _ hK.fIsKernel
    (sheafToPresheaf S.topology AddCommGrpCat.{u + 1})
  let hSection := KernelFork.mapIsLimit _ hPresheaf
    ((evaluation S.categoryᵒᵖ AddCommGrpCat.{u + 1}).obj W)
  simpa [sectionFunctor] using hSection

/-- The first term of a short exact sheaf complex is the concrete sectionwise kernel. -/
noncomputable def sectionKernelIso
    (K : ShortComplex (Sheaf S.topology AddCommGrpCat.{u + 1}))
    (hK : K.ShortExact) (W : S.categoryᵒᵖ) :
    K.X₁.val.obj W ≅ AddCommGrpCat.of (K.g.val.app W).hom.ker :=
  (sectionKernelIsLimit K hK W).conePointUniqueUpToIso
      (kernelIsKernel (K.g.val.app W)) ≪≫
    AddCommGrpCat.kernelIsoKer (K.g.val.app W)

/-- Concrete additive equivalence generated from the sectionwise kernel limit. -/
noncomputable def sectionKernelEquiv
    (K : ShortComplex (Sheaf S.topology AddCommGrpCat.{u + 1}))
    (hK : K.ShortExact) (W : S.categoryᵒᵖ) :
    K.X₁.val.obj W ≃+ AddMonoidHom.ker (K.g.val.app W).hom where
  toFun := (sectionKernelIso K hK W).hom.hom
  invFun := (sectionKernelIso K hK W).inv.hom
  left_inv x := by
    exact ConcreteCategory.congr_hom (sectionKernelIso K hK W).hom_inv_id x
  right_inv x := by
    exact ConcreteCategory.congr_hom (sectionKernelIso K hK W).inv_hom_id x
  map_add' x y := map_add (sectionKernelIso K hK W).hom.hom x y

/-- The generated kernel equivalence is carried by the first map of the short complex. -/
theorem sectionKernelEquiv_apply
    (K : ShortComplex (Sheaf S.topology AddCommGrpCat.{u + 1}))
    (hK : K.ShortExact) (W : S.categoryᵒᵖ) (n : K.X₁.val.obj W) :
    ((sectionKernelEquiv K hK W n).1 : K.X₂.val.obj W) = K.f.val.app W n := by
  have hh : (sectionKernelIso K hK W).hom ≫
      AddCommGrpCat.ofHom (AddSubgroup.subtype (K.g.val.app W).hom.ker) =
        K.f.val.app W := by
    dsimp [sectionKernelIso]
    rw [Category.assoc, AddCommGrpCat.kernelIsoKer_hom_comp_subtype]
    simpa using IsLimit.conePointUniqueUpToIso_hom_comp
      (sectionKernelIsLimit K hK W) (kernelIsKernel (K.g.val.app W))
      WalkingParallelPair.zero
  exact ConcreteCategory.congr_hom hh n

/-! ## Local lift input and cochain functoriality -/

/-- Only the locally solvable section data supplied to additive lift descent. -/
structure LocalLiftData
    (geometry : Site.FinitePosetCoverGeometry S)
    (K : ShortComplex (Sheaf S.topology AddCommGrpCat.{u + 1})) where
  baseSection : K.X₃.val.obj (op geometry.base)
  localLifts : ∀ i : geometry.cover.Index,
    K.X₂.val.obj (op
      (Site.ContextCategoryObject.of S.contextPreorder (geometry.cover.patch i)))
  localLifts_project : ∀ i : geometry.cover.Index,
    K.g.val.app _ (localLifts i) =
      K.X₃.val.map (homOfLE (geometry.cover.inclusion i)).op baseSection

namespace LocalLiftData

variable {K : ShortComplex (Sheaf S.topology AddCommGrpCat.{u + 1})}
variable (P : LocalLiftData geometry K)

/-- A natural transformation acts pointwise on generated large cochains. -/
def mapCochain
    {F G : S.categoryᵒᵖ ⥤ AddCommGrpCat.{u + 1}} (eta : F ⟶ G) (n : Nat)
    (c : LawGeneratedLargeCoefficientCech.Cochain geometry F n) : LawGeneratedLargeCoefficientCech.Cochain geometry G n :=
  fun sigma ↦ eta.app _ (c sigma)

/-- Naturality transports pointwise cochain maps through every generated differential. -/
theorem map_differential
    {F G : S.categoryᵒᵖ ⥤ AddCommGrpCat.{u + 1}} (eta : F ⟶ G) (n : Nat)
    (c : LawGeneratedLargeCoefficientCech.Cochain geometry F n) :
    mapCochain eta (n + 1) (LawGeneratedLargeCoefficientCech.differential geometry F n c) =
      LawGeneratedLargeCoefficientCech.differential geometry G n (mapCochain eta n c) := by
  funext sigma
  classical
  dsimp [mapCochain, LawGeneratedLargeCoefficientCech.differential]
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro i _hi
  by_cases hi : Even i.val
  · simp only [hi, ↓reduceIte]
    exact eta.naturality_apply _ _
  · simp only [hi, ↓reduceIte, map_neg]
    exact congrArg Neg.neg (eta.naturality_apply _ _)

/-- The degree-zero restriction cochain of a section over the selected base. -/
def restrictionCochain (F : S.categoryᵒᵖ ⥤ AddCommGrpCat.{u + 1})
    (x : F.obj (op geometry.base)) : LawGeneratedLargeCoefficientCech.Cochain geometry F 0 :=
  fun sigma ↦ F.map (homOfLE (geometry.cover.inclusion (sigma 0))).op x

/-- Restrictions of one base section agree on every canonical pair overlap. -/
theorem restrictionCochain_cocycle
    (F : S.categoryᵒᵖ ⥤ AddCommGrpCat.{u + 1}) (x : F.obj (op geometry.base)) :
    LawGeneratedLargeCoefficientCech.d0 geometry F
      (restrictionCochain (geometry := geometry) F x) = 0 := by
  funext sigma
  dsimp [LawGeneratedLargeCoefficientCech.d0, LawGeneratedLargeCoefficientCech.differential]
  rw [Fin.sum_univ_two]
  simp only [Fin.val_zero, Fin.val_one,
    if_pos (by decide : Even 0), if_neg (by decide : ¬ Even 1)]
  dsimp [LawGeneratedLargeCoefficientCech.faceRestriction, restrictionCochain]
  change (F ⋙ forget AddCommGrpCat).map _ ((F ⋙ forget AddCommGrpCat).map _ x) +
      -((F ⋙ forget AddCommGrpCat).map _ ((F ⋙ forget AddCommGrpCat).map _ x)) = 0
  rw [← FunctorToTypes.map_comp_apply, ← FunctorToTypes.map_comp_apply]
  let m₀ :=
    (homOfLE (geometry.cover.inclusion
      ((LawGeneratedLargeCoefficientCech.face geometry 0 sigma (0 : Fin 2)) 0))).op ≫
      (LawGeneratedLargeCoefficientCech.faceHom geometry 0 sigma (0 : Fin 2)).op
  let m₁ :=
    (homOfLE (geometry.cover.inclusion
      ((LawGeneratedLargeCoefficientCech.face geometry 0 sigma (1 : Fin 2)) 0))).op ≫
      (LawGeneratedLargeCoefficientCech.faceHom geometry 0 sigma (1 : Fin 2)).op
  change (F ⋙ forget AddCommGrpCat).map m₀ x +
    -(F ⋙ forget AddCommGrpCat).map m₁ x = 0
  rw [show m₀ = m₁ from Subsingleton.elim _ _, add_neg_cancel]

/-- The short-exact kernel inclusion has zero composite with the projection. -/
theorem projection_kernel (W : S.categoryᵒᵖ) (n : K.X₁.val.obj W) :
    K.g.val.app W (K.f.val.app W n) = 0 := by
  have hz : K.f.val.app W ≫ K.g.val.app W = 0 := by
    change (K.f ≫ K.g).val.app W = (0 : K.X₁ ⟶ K.X₃).val.app W
    exact congrArg (fun eta ↦ eta.val.app W) K.zero
  exact ConcreteCategory.congr_hom hz n

/-- The locally chosen middle sections as a degree-zero cochain. -/
def localLiftCochain : LawGeneratedLargeCoefficientCech.Cochain geometry K.X₂.val 0 :=
  fun sigma ↦ P.localLifts (sigma 0)

/-- The fixed quotient section restricted to all selected generators. -/
def baseSectionCochain : LawGeneratedLargeCoefficientCech.Cochain geometry K.X₃.val 0 :=
  restrictionCochain (geometry := geometry) K.X₃.val P.baseSection

theorem projection_localLiftCochain
    (sigma : LawGeneratedLargeCoefficientCech.Tuple geometry 0) :
    K.g.val.app _ (P.localLiftCochain sigma) = P.baseSectionCochain sigma :=
  P.localLifts_project (sigma 0)

theorem baseSectionCochain_cocycle :
    LawGeneratedLargeCoefficientCech.d0 geometry K.X₃.val P.baseSectionCochain = 0 :=
  restrictionCochain_cocycle (geometry := geometry) K.X₃.val P.baseSection

/-! ## Connecting class and independence of local choices -/

/-- Explicit local lifts of the fixed quotient section. -/
def GeneratorLocalLiftFamily : Type (u + 1) :=
  { lifts : ∀ i : geometry.cover.Index,
      K.X₂.val.obj (op
        (Site.ContextCategoryObject.of S.contextPreorder (geometry.cover.patch i))) //
    ∀ i, K.g.val.app _ (lifts i) =
      K.X₃.val.map (homOfLE (geometry.cover.inclusion i)).op P.baseSection }

def chosenGeneratorLocalLiftFamily : P.GeneratorLocalLiftFamily :=
  ⟨P.localLifts, P.localLifts_project⟩

def localLiftCochainFor (L : P.GeneratorLocalLiftFamily) :
    LawGeneratedLargeCoefficientCech.Cochain geometry K.X₂.val 0 :=
  fun sigma ↦ L.1 (sigma 0)

theorem projection_localLiftCochainFor (L : P.GeneratorLocalLiftFamily)
    (sigma : LawGeneratedLargeCoefficientCech.Tuple geometry 0) :
    K.g.val.app _ (P.localLiftCochainFor L sigma) = P.baseSectionCochain sigma :=
  L.2 (sigma 0)

theorem projection_localLiftDifferentialFor_eq_zero
    (L : P.GeneratorLocalLiftFamily) (sigma : LawGeneratedLargeCoefficientCech.Tuple geometry 1) :
    K.g.val.app _ (LawGeneratedLargeCoefficientCech.d0 geometry K.X₂.val (P.localLiftCochainFor L) sigma) = 0 := by
  have hmap := congrFun
    (map_differential (geometry := geometry) K.g.val 0 (P.localLiftCochainFor L)) sigma
  calc
    _ = LawGeneratedLargeCoefficientCech.d0 geometry K.X₃.val
        (mapCochain K.g.val 0 (P.localLiftCochainFor L)) sigma := hmap
    _ = LawGeneratedLargeCoefficientCech.d0 geometry K.X₃.val P.baseSectionCochain sigma := by
      exact congrArg
        (fun z ↦ LawGeneratedLargeCoefficientCech.d0 geometry K.X₃.val z sigma)
        (funext fun tau ↦ P.projection_localLiftCochainFor L tau)
    _ = 0 := congrFun P.baseSectionCochain_cocycle sigma

/-- Kernel-valued overlap difference generated from one local-lift choice. -/
def localLiftDifferenceFor (hK : K.ShortExact) (L : P.GeneratorLocalLiftFamily) :
    LawGeneratedLargeCoefficientCech.Cochain geometry K.X₁.val 1 :=
  fun sigma ↦
    (sectionKernelEquiv K hK _).symm
      ⟨LawGeneratedLargeCoefficientCech.d0 geometry K.X₂.val (P.localLiftCochainFor L) sigma,
        P.projection_localLiftDifferentialFor_eq_zero L sigma⟩

theorem kernel_localLiftDifferenceFor (hK : K.ShortExact)
    (L : P.GeneratorLocalLiftFamily) (sigma : LawGeneratedLargeCoefficientCech.Tuple geometry 1) :
    K.f.val.app _ (P.localLiftDifferenceFor hK L sigma) =
      LawGeneratedLargeCoefficientCech.d0 geometry K.X₂.val (P.localLiftCochainFor L) sigma := by
  rw [← sectionKernelEquiv_apply K hK]
  change ((sectionKernelEquiv K hK _) ((sectionKernelEquiv K hK _).symm _)).1 = _
  rw [AddEquiv.apply_symm_apply]

theorem localLiftDifferenceFor_cocycle (hK : K.ShortExact)
    (L : P.GeneratorLocalLiftFamily) :
    LawGeneratedLargeCoefficientCech.d1 geometry K.X₁.val (P.localLiftDifferenceFor hK L) = 0 := by
  funext sigma
  apply (sectionKernelEquiv K hK _).injective
  apply Subtype.ext
  rw [sectionKernelEquiv_apply K hK]
  have hmap := congrFun
    (map_differential (geometry := geometry) K.f.val 1 (P.localLiftDifferenceFor hK L)) sigma
  calc
    _ = LawGeneratedLargeCoefficientCech.d1 geometry K.X₂.val
        (mapCochain K.f.val 1 (P.localLiftDifferenceFor hK L)) sigma := hmap
    _ = LawGeneratedLargeCoefficientCech.d1 geometry K.X₂.val
        (LawGeneratedLargeCoefficientCech.d0 geometry K.X₂.val (P.localLiftCochainFor L)) sigma := by
      exact congrArg
        (fun z ↦ LawGeneratedLargeCoefficientCech.d1 geometry K.X₂.val z sigma)
        (funext fun tau ↦ P.kernel_localLiftDifferenceFor hK L tau)
    _ = 0 := congrFun (LawGeneratedLargeCoefficientCech.d1_d0 geometry K.X₂.val (P.localLiftCochainFor L)) sigma
    _ = ((sectionKernelEquiv K hK _) (0 : K.X₁.val.obj _)).1 := by simp

def connectingCocycleFor (hK : K.ShortExact) (L : P.GeneratorLocalLiftFamily) :
    (LawGeneratedLargeCoefficientCech.threeTermComplex geometry K.X₁.val).H1Cocycle :=
  ⟨P.localLiftDifferenceFor hK L, P.localLiftDifferenceFor_cocycle hK L⟩

def connectingClassFor (hK : K.ShortExact) (L : P.GeneratorLocalLiftFamily) :
    LawGeneratedLargeCoefficientCech.H1 geometry K.X₁.val :=
  LawGeneratedLargeCoefficientCech.h1Class geometry K.X₁.val (P.connectingCocycleFor hK L)

def changePrimitive (hK : K.ShortExact)
    (left right : P.GeneratorLocalLiftFamily) :
    LawGeneratedLargeCoefficientCech.Cochain geometry K.X₁.val 0 :=
  fun sigma ↦
    (sectionKernelEquiv K hK _).symm
      ⟨P.localLiftCochainFor left sigma - P.localLiftCochainFor right sigma, by
        change K.g.val.app _
          (P.localLiftCochainFor left sigma - P.localLiftCochainFor right sigma) = 0
        rw [map_sub, P.projection_localLiftCochainFor,
          P.projection_localLiftCochainFor, sub_self]⟩

theorem kernel_changePrimitive (hK : K.ShortExact)
    (left right : P.GeneratorLocalLiftFamily) (sigma : LawGeneratedLargeCoefficientCech.Tuple geometry 0) :
    K.f.val.app _ (P.changePrimitive hK left right sigma) =
      P.localLiftCochainFor left sigma - P.localLiftCochainFor right sigma := by
  rw [← sectionKernelEquiv_apply K hK]
  change ((sectionKernelEquiv K hK _) ((sectionKernelEquiv K hK _).symm _)).1 = _
  rw [AddEquiv.apply_symm_apply]

theorem localLiftDifferenceFor_sub (hK : K.ShortExact)
    (left right : P.GeneratorLocalLiftFamily) :
    P.localLiftDifferenceFor hK left - P.localLiftDifferenceFor hK right =
      LawGeneratedLargeCoefficientCech.d0 geometry K.X₁.val (P.changePrimitive hK left right) := by
  funext sigma
  apply (sectionKernelEquiv K hK _).injective
  apply Subtype.ext
  rw [sectionKernelEquiv_apply K hK]
  change K.f.val.app _
      (P.localLiftDifferenceFor hK left sigma - P.localLiftDifferenceFor hK right sigma) = _
  rw [map_sub, P.kernel_localLiftDifferenceFor, P.kernel_localLiftDifferenceFor]
  rw [sectionKernelEquiv_apply K hK]
  have hmap := congrFun
    (map_differential (geometry := geometry) K.f.val 0 (P.changePrimitive hK left right)) sigma
  have hmap' : mapCochain K.f.val 1
      (LawGeneratedLargeCoefficientCech.d0 geometry K.X₁.val
        (P.changePrimitive hK left right)) sigma =
      LawGeneratedLargeCoefficientCech.d0 geometry K.X₂.val
        (mapCochain K.f.val 0 (P.changePrimitive hK left right)) sigma := by
    simpa only [LawGeneratedLargeCoefficientCech.d0] using hmap
  change _ = mapCochain K.f.val 1
    (LawGeneratedLargeCoefficientCech.d0 geometry K.X₁.val
      (P.changePrimitive hK left right)) sigma
  rw [hmap']
  calc
    _ = LawGeneratedLargeCoefficientCech.d0 geometry K.X₂.val
        (P.localLiftCochainFor left - P.localLiftCochainFor right) sigma := by
      simpa only [Pi.sub_apply] using
        (congrFun (map_sub (LawGeneratedLargeCoefficientCech.d0 geometry K.X₂.val)
          (P.localLiftCochainFor left) (P.localLiftCochainFor right)) sigma).symm
    _ = _ := congrArg
      (fun z ↦ LawGeneratedLargeCoefficientCech.d0 geometry K.X₂.val z sigma)
      (funext fun tau ↦ (P.kernel_changePrimitive hK left right tau).symm)

theorem connectingClass_choice_independent (hK : K.ShortExact)
    (left right : P.GeneratorLocalLiftFamily) :
    P.connectingClassFor hK left = P.connectingClassFor hK right := by
  apply Quotient.sound
  exact ⟨P.changePrimitive hK left right, P.localLiftDifferenceFor_sub hK left right⟩

def connectingCocycle (hK : K.ShortExact) :=
  P.connectingCocycleFor hK P.chosenGeneratorLocalLiftFamily

def connectingClass (hK : K.ShortExact) :=
  P.connectingClassFor hK P.chosenGeneratorLocalLiftFamily

end LocalLiftData

end LawGeneratedLargeConormalDescent
end ResearchLean.AG.QualitySurface

#assert_standard_axioms_only ResearchLean.AG.QualitySurface.LawGeneratedLargeConormalDescent
