import ResearchLean.AG.QualitySurface.SemanticRepairFiniteQueryExtensionality

/-!
Cycle 22 evidence for `G-aat-quality-surface-04`.

This file packages finite query-generated observations as an explicit class.
The package stores a finite query, a visible support condition, and a post-map;
the observation is generated from these data rather than accepted as an
arbitrary hidden field.
-/

namespace ResearchLean.AG
namespace QualitySurface
namespace SemanticRepairFiniteQueryObservation

open SemanticRepairObstructionTower
open SemanticRepairUniversalShadow
open SemanticRepairTraceProbeShadow
open SemanticRepairFiniteTraceSupport
open SemanticRepairFiniteSupportCompleteness
open SemanticRepairFiniteQueryAdmissibility
open SemanticRepairFiniteQueryExtensionality

universe u v w x y z

/-! ## Finite query-generated observation package -/

/--
A finite query-generated observation relative to a fixed support list.

The package does not contain an arbitrary observation or an extensionality
claim.  The observation is generated from the current four-bit layer, the
finite query trace vector, and the post-map.
-/
structure FiniteTraceQueryObservation
    {Atom : Type u}
    (support : List Atom)
    (Out : Type z) where
  query : List Atom
  query_supported : QuerySupportedBy support query
  post : FiniteTowerLayerShadow -> List Bool -> Out

/-- The observation generated by a finite query package. -/
def FiniteTraceQueryObservation.observe
    {Atom : Type u}
    {support : List Atom}
    {Out : Type z}
    (obs : FiniteTraceQueryObservation support Out)
    (T : FiniteSemanticRepairObstructionTower.{u, v, w, x, y} Atom) :
    Out :=
  obs.post (canonicalTowerLayerShadow T)
    (supportTraceVector obs.query T.sourceTraceToken)

/--
Every finite query-generated observation factors through the support trace
shadow.
-/
theorem finiteTraceQueryObservation_factors_through_supportTraceShadow
    {Atom : Type u}
    {support : List Atom}
    {Out : Type z}
    (obs : FiniteTraceQueryObservation support Out) :
    ∃ factor : TraceProbeFiniteTowerLayerShadow -> Out,
      ∀ T : FiniteSemanticRepairObstructionTower.{u, v, w, x, y} Atom,
        obs.observe T =
          factor (canonicalSupportTraceProbeTowerLayerShadow support T) := by
  exact
    queryTraceGeneratedObservation_factors_through_supportTraceShadow
      obs.query obs.query_supported obs.post

/--
Every finite query-generated observation is extensional for the support trace
shadow.
-/
theorem finiteTraceQueryObservation_supportTraceShadowExtensional
    {Atom : Type u}
    {support : List Atom}
    {Out : Type z}
    (obs : FiniteTraceQueryObservation support Out) :
    SupportTraceShadowExtensional
      (Atom := Atom)
      support
      (fun T : FiniteSemanticRepairObstructionTower.{u, v, w, x, y} Atom =>
        obs.observe T) := by
  exact
    queryTraceGeneratedObservation_supportTraceShadowExtensional
      obs.query_supported obs.post

/--
Same support trace shadow gives the same finite query-generated observation.
-/
theorem finiteTraceQueryObservation_same_of_same_supportTraceShadow
    {Atom : Type u}
    {support : List Atom}
    {Out : Type z}
    (obs : FiniteTraceQueryObservation support Out)
    {left right :
      FiniteSemanticRepairObstructionTower.{u, v, w, x, y} Atom}
    (hshadow :
      canonicalSupportTraceProbeTowerLayerShadow support left =
        canonicalSupportTraceProbeTowerLayerShadow support right) :
    obs.observe left = obs.observe right := by
  exact
    finiteTraceQueryObservation_supportTraceShadowExtensional
      (Atom := Atom) obs left right hshadow

/-! ## Concrete complete Bool support query package -/

/-- The Cycle 20 `[true]` query packaged as a finite query observation. -/
def boolTrueFiniteTraceQueryObservation
    {Out : Type z}
    (post : FiniteTowerLayerShadow -> List Bool -> Out) :
    FiniteTraceQueryObservation
      SemanticRepairFiniteSupportCompleteness.boolCompleteTraceSupport Out where
  query := SemanticRepairFiniteQueryAdmissibility.boolTrueTraceQuery
  query_supported :=
    boolTrueTraceQuery_supportedBy_completeBoolSupport
  post := post

/-- The packaged Bool query observation factors through complete Bool support. -/
theorem boolTrueFiniteTraceQueryObservation_factors
    {Out : Type z}
    (post : FiniteTowerLayerShadow -> List Bool -> Out) :
    ∃ factor : TraceProbeFiniteTowerLayerShadow -> Out,
      ∀ T : FiniteSemanticRepairObstructionTower.{0, 0, 0, 0, 0} Bool,
        (boolTrueFiniteTraceQueryObservation post).observe T =
          factor
            (canonicalSupportTraceProbeTowerLayerShadow
              SemanticRepairFiniteSupportCompleteness.boolCompleteTraceSupport T) := by
  exact
    finiteTraceQueryObservation_factors_through_supportTraceShadow
      (boolTrueFiniteTraceQueryObservation post)

/--
The packaged Bool query observation is extensional for the complete Bool
support shadow.
-/
theorem boolTrueFiniteTraceQueryObservation_supportTraceShadowExtensional
    {Out : Type z}
    (post : FiniteTowerLayerShadow -> List Bool -> Out) :
    SupportTraceShadowExtensional
      (Atom := Bool)
      SemanticRepairFiniteSupportCompleteness.boolCompleteTraceSupport
      (fun T : FiniteSemanticRepairObstructionTower.{0, 0, 0, 0, 0} Bool =>
        (boolTrueFiniteTraceQueryObservation post).observe T) := by
  exact
    finiteTraceQueryObservation_supportTraceShadowExtensional
      (boolTrueFiniteTraceQueryObservation post)

end SemanticRepairFiniteQueryObservation
end QualitySurface
end ResearchLean.AG
