import ResearchLean.AG.QualitySurface.SemanticRepairCechGrounding
import Formal.AG.LawAlgebra.LawEquation
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
G-06 law-equation realization layer.

This file adds the reviewed input-vocabulary extension approved for G-06: laws
are realized through the native `ArchitecturalEquationSystem`.  Its
atom-indexed violation coordinates generate the witness ideal of each equation,
and the local obstruction ideal and quotient coefficient are the canonical
constructions from `Formal.AG.LawAlgebra.LawEquation`.

The obstruction coefficient object is then *generated* as the ideal-quotient
presheaf `Observable / I_Ob`.  Its restriction maps are induced by
`Ideal.quotientMap` along the LawAlgebra `RestrictionCompatible` theorem, so
additive restriction functoriality is constructed, not supplied.

On this generated coefficient realization, the support-only `interpret` map is
no longer a free field: it is the obstruction-quotient class of an explicit
defect observable.  The law-as-equation semantic tie says only that a required
equation holding on the displayed local reading places that reading's defect
inside the equation's own atom-generated witness ideal.  The tie is pointwise and
chart-local: it contains no overlap equality, no `arrowCompatibilityLaw`, no
`sourceC0CechZero`, no residual-zero, and no `H1` zero.  The cross-chart
restriction equality demanded by G-06 is *derived* from the quotient
realization: lawful defects vanish in the quotient, and the zero section is a
common base-restriction realization, which routes through the Cycle 346 and
Cycle 311 theorems to the displayed required-law restriction evaluator and the
generated-Cech `sourceC0CechZero`.

The Cycle 347 no-go boundary is untouched: nothing here constructs a
base-restriction source for an arbitrary support-only source.  The positive
construction fires only for sources whose interpretation is generated by the
law-equation realization itself.
-/

noncomputable section

universe u v w x y z r a b

namespace ResearchLean.AG
namespace QualitySurface
namespace SemanticRepairCechGrounding

open CategoryTheory
open Opposite
open SemanticRepairSheafH1
open SemanticRepairTrueSheafH1
open SemanticRepairObstructionTower

namespace SemanticRepairCoverRelativeCochainRealization
namespace CoverRelativeCechGeneratedSemanticCoefficient

/-! ## Law-equation geometry and the generated coefficient realization -/

/--
G-06 law-equation input geometry.

This bundles the native equation system with displayed semantic provenance and
the sheaf condition of its generated obstruction-quotient presheaf.  The sheaf
condition is input geometry in the
same ambient position as the existing
`SemanticAtomLawAdditiveCoefficientGeometry.isSheaf` field; it asserts nothing
about interpretation maps, overlap equality of any source, `sourceC0CechZero`,
residual zero, `H1` zero, or global coherence.
-/
structure SemanticLawEquationWitnessIdealGeometry
    {U : AAT.AG.AtomCarrier.{r}} {A : AAT.AG.ArchitectureObject U}
    (semanticSite : SemanticRepairSite.{r, v} U.Atom)
    (S : AAT.AG.Site.AATSite A) where
  equationSystem : AAT.AG.ArchitecturalEquationSystem S.contextPreorder
  supportAtom : U.Atom
  supportAtom_traceVisible :
    semanticSite.sourceTraceToken supportAtom = true
  provenanceLawIndex : S.equationSystem.toLegacyLawUniverse.Index
  provenanceLawIndex_required :
    S.equationSystem.toLegacyLawUniverse.Required provenanceLawIndex
  quotientIsSheaf :
    AAT.AG.Site.AATSheafCondition S
      equationSystem.obstructionQuotientPresheaf

namespace SemanticLawEquationWitnessIdealGeometry

variable {U : AAT.AG.AtomCarrier.{r}} {A : AAT.AG.ArchitectureObject U}
variable {semanticSite : SemanticRepairSite.{r, v} U.Atom}
variable {S : AAT.AG.Site.AATSite A}

/--
The law-equation geometry generates the Cycle 247 semantic atom/law additive
coefficient geometry.  The coefficient functor is the generated
obstruction-quotient presheaf, so additive restriction laws are constructed by
`obstructionQuotientCoefficient` rather than supplied; the support fields are
the designated trace-visible atom and required law index.
-/
def toSemanticAtomLawAdditiveCoefficientGeometry
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S) :
    SemanticAtomLawAdditiveCoefficientGeometry semanticSite S where
  coefficient :=
    G.equationSystem.obstructionQuotientCoefficient
  isSheaf := G.quotientIsSheaf
  atomSupport := fun _ _ => [G.supportAtom]
  atomSupport_traceVisible := fun _ _ =>
    ⟨G.supportAtom, List.mem_singleton_self G.supportAtom,
      G.supportAtom_traceVisible⟩
  lawSupport := fun _ _ => [G.provenanceLawIndex]
  lawSupport_nonempty := fun _ _ =>
    ⟨G.provenanceLawIndex, List.mem_singleton_self G.provenanceLawIndex⟩
  lawSupport_required := fun _ _ lawIndex hmem => by
    have heq : lawIndex = G.provenanceLawIndex := List.eq_of_mem_singleton hmem
    exact heq ▸ G.provenanceLawIndex_required

/--
The generated obstruction sheaf of the law-equation realization: the
obstruction-quotient coefficient read through the Cycle 246/247 additive
restriction route.  Its carrier presheaf is the generated quotient; nothing is
supplied beyond the geometry itself.
-/
abbrev lawEquationObstructionSheaf
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S) :
    AAT.AG.Cohomology.ObstructionSheaf S :=
  G.toSemanticAtomLawAdditiveCoefficientGeometry.toAdditiveRestrictionLaw.toObstructionSheaf

/--
Sections of the generated obstruction sheaf at a context are the obstruction
quotient at that context.  This is a construction-unfolding bridge, proved by
definitional equality alone.
-/
def toObstructionSection
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S)
    (W : S.category)
    (x : G.equationSystem.ObstructionQuotient W) :
    G.lawEquationObstructionSheaf.carrier.toPresheaf.obj (op W) :=
  x

end SemanticLawEquationWitnessIdealGeometry

end CoverRelativeCechGeneratedSemanticCoefficient

/-! ## Law-equation defect source and the generated positive constructions -/

namespace CoverRelativeCechFinitePosetChartProjectionPointwiseAtomLawInputBoundaryBasis

open CoverRelativeCechGeneratedSemanticCoefficient

variable {U : AAT.AG.AtomCarrier.{r}} {A : AAT.AG.ArchitectureObject U}
variable {semanticSite : SemanticRepairSite.{r, v} U.Atom}
variable {S : AAT.AG.Site.AATSite A}

/-- The generated finite-poset regime of the law-equation realization. -/
abbrev lawEquationRegime
    (coverGeometry : FinitePosetAtomLawCoverGeometry S)
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S) :=
  (coverGeometry.canonicalTupleOverlapGeometryFromOverlap.toCanonicalTupleCoverGeometry).toObstructionCoefficientRegime
    G.lawEquationObstructionSheaf

/-- The generated standard finite-poset Cech complex of the realization. -/
abbrev lawEquationStandardComplex
    (coverGeometry : FinitePosetAtomLawCoverGeometry S)
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S) :=
  atomLawOverlapStandardFinitePosetCechComplex coverGeometry
    G.lawEquationObstructionSheaf

/-- The generated cover-relative Cech complex of the realization. -/
abbrev lawEquationCechComplex
    (coverGeometry : FinitePosetAtomLawCoverGeometry S)
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S) :=
  atomLawOverlapCoverRelativeCechComplex coverGeometry
    G.lawEquationObstructionSheaf

/-- The displayed atom/law chart of the generated realization cover. -/
abbrev lawEquationChart
    (coverGeometry : FinitePosetAtomLawCoverGeometry S)
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S)
    (i : (lawEquationRegime coverGeometry G).cover.Index) :
    S.category :=
  (AAT.AG.Cohomology.finitePosetCoverRelativeCover
    (lawEquationStandardComplex coverGeometry G)).chart i

/--
G-06 law-equation defect source.

This is the input-boundary source for the generated realization: local inputs,
atom/law support, a displayed architecture-object reading, and a defect
observable for each local input.  The single semantic tie `holds_defect_mem`
is the law-as-equation semantics: a displayed required equation holding on the
displayed local reading places the displayed defect inside that equation's own
atom-generated witness ideal on the same chart.

The tie is pointwise and chart-local.  The structure has no `interpret` field:
the interpretation is generated below as the obstruction-quotient class of the
defect.  No overlap equality, `arrowCompatibilityLaw`,
`commonRestrictionRealization`, evaluator, `sourceC0CechZero`, residual-zero,
or `H1` zero appears as a field.
-/
structure LawEquationDefectSemanticAtomLawInputBoundarySource
    (coverGeometry : FinitePosetAtomLawCoverGeometry S)
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S)
    (skeleton :
      SourceSectionFreeSkeleton
        (semanticSite := semanticSite) (S := S)
        (regime := lawEquationRegime coverGeometry G)
        (C := lawEquationStandardComplex coverGeometry G)
        (Ob := G.lawEquationObstructionSheaf)
        (K := lawEquationCechComplex coverGeometry G)) where
  LocalInput : (lawEquationRegime coverGeometry G).cover.Index -> Type r
  input : (i : (lawEquationRegime coverGeometry G).cover.Index) -> LocalInput i
  atomSupport :
    (i : (lawEquationRegime coverGeometry G).cover.Index) ->
      LocalInput i -> List U.Atom
  atomSupport_traceVisible :
    forall (i : (lawEquationRegime coverGeometry G).cover.Index)
      (localInput : LocalInput i),
      exists atom : U.Atom,
        atom ∈ atomSupport i localInput ∧
          semanticSite.sourceTraceToken atom = true
  lawSupport :
    (i : (lawEquationRegime coverGeometry G).cover.Index) ->
      LocalInput i -> List G.equationSystem.Index
  lawSupport_nonempty :
    forall (i : (lawEquationRegime coverGeometry G).cover.Index)
      (localInput : LocalInput i),
      exists lawIndex : G.equationSystem.Index,
        lawIndex ∈ lawSupport i localInput
  lawSupport_required :
    forall (i : (lawEquationRegime coverGeometry G).cover.Index)
      (localInput : LocalInput i) (lawIndex : G.equationSystem.Index),
      lawIndex ∈ lawSupport i localInput -> G.equationSystem.Required lawIndex
  objectOfLocalInput :
    (i : (lawEquationRegime coverGeometry G).cover.Index) ->
      LocalInput i -> AAT.AG.ArchitectureObject U
  defect :
    (i : (lawEquationRegime coverGeometry G).cover.Index) ->
      LocalInput i ->
        G.equationSystem.Observable (lawEquationChart coverGeometry G i)
  holds_defect_mem :
    forall (i : (lawEquationRegime coverGeometry G).cover.Index)
      (lawIndex : G.equationSystem.Index),
      lawIndex ∈ lawSupport i (input i) ->
        G.equationSystem.Required lawIndex ->
          G.equationSystem.EquationHolds lawIndex
              (objectOfLocalInput i (input i)) ->
            defect i (input i) ∈
              G.equationSystem.witnessIdeal
                (lawEquationChart coverGeometry G i) lawIndex

namespace LawEquationDefectSemanticAtomLawInputBoundarySource

variable {coverGeometry : FinitePosetAtomLawCoverGeometry S}
variable {G : SemanticLawEquationWitnessIdealGeometry semanticSite S}
variable {skeleton :
  SourceSectionFreeSkeleton
    (semanticSite := semanticSite) (S := S)
    (regime := lawEquationRegime coverGeometry G)
    (C := lawEquationStandardComplex coverGeometry G)
    (Ob := G.lawEquationObstructionSheaf)
    (K := lawEquationCechComplex coverGeometry G)}

/--
Generate the Cycle 295 support-only source from the law-equation defect
source.  The `interpret` map is not a free field: it is the
obstruction-quotient class of the displayed defect observable.
-/
def toSupportOnlySemanticAtomLawInputBoundarySource
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton) :
    SourceSectionFreeSkeleton.GeneratedFinitePosetSelectedCoverPresieveSupportOnlySemanticAtomLawInputBoundarySource
      skeleton where
  LocalInput := D.LocalInput
  input := D.input
  atomSupport := D.atomSupport
  atomSupport_traceVisible := D.atomSupport_traceVisible
  lawSupport := fun _ _ => [G.provenanceLawIndex]
  lawSupport_nonempty := fun _ _ =>
    ⟨G.provenanceLawIndex, List.mem_singleton_self G.provenanceLawIndex⟩
  lawSupport_required := fun _ _ lawIndex hmem => by
    have heq : lawIndex = G.provenanceLawIndex := List.eq_of_mem_singleton hmem
    exact heq ▸ G.provenanceLawIndex_required
  interpret := fun i localInput =>
    G.toObstructionSection (lawEquationChart coverGeometry G i)
      (Ideal.Quotient.mk
        (G.equationSystem.obstructionIdeal
          (lawEquationChart coverGeometry G i))
        (D.defect i localInput))

/-- Native displayed-equation fulfillment on all selected local readings. -/
def DisplayedRequiredEquationsHoldOn
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton) : Prop :=
  forall i (equationIndex : G.equationSystem.Index),
    equationIndex ∈ D.lawSupport i (D.input i) ->
      G.equationSystem.Required equationIndex ->
        G.equationSystem.EquationHolds equationIndex
          (D.objectOfLocalInput i (D.input i))

/--
Law-equation vanishing theorem: if the displayed required equations hold on the
displayed local readings, then every generated interpretation is the zero
class of the obstruction quotient.

The proof consumes `holds` through the law-as-equation tie and the LawAlgebra
containment `I_L ≤ I_Ob`; it does not consume any overlap equality,
compatibility law, or Cech-side premise.
-/
theorem displayedRequiredLawsHoldOn_constructs_interpret_eq_zero
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (hholds : D.DisplayedRequiredEquationsHoldOn) :
    forall i : (lawEquationRegime coverGeometry G).cover.Index,
      D.toSupportOnlySemanticAtomLawInputBoundarySource.interpret i
          (D.toSupportOnlySemanticAtomLawInputBoundarySource.input i) = 0 := by
  intro i
  obtain ⟨lawIndex, hmem⟩ := D.lawSupport_nonempty i (D.input i)
  have hrequired : G.equationSystem.Required lawIndex :=
    D.lawSupport_required i (D.input i) lawIndex hmem
  have hholdsLaw :
      G.equationSystem.EquationHolds lawIndex
        (D.objectOfLocalInput i (D.input i)) :=
    hholds i lawIndex hmem hrequired
  have hdefect :
      D.defect i (D.input i) ∈
        G.equationSystem.witnessIdeal
          (lawEquationChart coverGeometry G i) lawIndex :=
    D.holds_defect_mem i lawIndex hmem hrequired hholdsLaw
  have hobstruction :
      D.defect i (D.input i) ∈
        G.equationSystem.obstructionIdeal
          (lawEquationChart coverGeometry G i) :=
    G.equationSystem.witnessIdeal_le_obstructionIdeal
      (lawEquationChart coverGeometry G i) hrequired hdefect
  exact Ideal.Quotient.eq_zero_iff_mem.mpr hobstruction

/--
Construction-faithfulness reading: the generated interpretation vanishes
exactly when the displayed defect lies in the atom-generated local obstruction
ideal.  Vanishing is therefore ideal membership, not a definitional collapse.
-/
theorem interpret_eq_zero_iff_defect_mem_obstructionIdeal
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (i : (lawEquationRegime coverGeometry G).cover.Index) :
    D.toSupportOnlySemanticAtomLawInputBoundarySource.interpret i
        (D.toSupportOnlySemanticAtomLawInputBoundarySource.input i) = 0 <->
      D.defect i (D.input i) ∈
        G.equationSystem.obstructionIdeal
          (lawEquationChart coverGeometry G i) :=
  Ideal.Quotient.eq_zero_iff_mem

/--
Nondegeneracy reading: a displayed defect outside the local obstruction ideal
has a nonzero generated interpretation.  The quotient realization is faithful:
it does not collapse every reading to zero.
-/
theorem interpret_ne_zero_of_defect_notMem_obstructionIdeal
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (i : (lawEquationRegime coverGeometry G).cover.Index)
    (hnot :
      D.defect i (D.input i) ∉
        G.equationSystem.obstructionIdeal
          (lawEquationChart coverGeometry G i)) :
    D.toSupportOnlySemanticAtomLawInputBoundarySource.interpret i
        (D.toSupportOnlySemanticAtomLawInputBoundarySource.input i) ≠ 0 :=
  fun h => hnot ((D.interpret_eq_zero_iff_defect_mem_obstructionIdeal i).mp h)

/--
Detector soundness: a nonzero generated interpretation certifies that every
displayed required equation fails on the displayed local reading.  This is the
AAT reading of the obstruction class: nonzero class means equation failure,
traced through the displayed equation support.
-/
theorem interpret_ne_zero_detects_displayed_required_law_failure
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (i : (lawEquationRegime coverGeometry G).cover.Index)
    (hne :
      D.toSupportOnlySemanticAtomLawInputBoundarySource.interpret i
          (D.toSupportOnlySemanticAtomLawInputBoundarySource.input i) ≠ 0) :
    forall lawIndex : G.equationSystem.Index,
      lawIndex ∈ D.lawSupport i (D.input i) ->
        G.equationSystem.Required lawIndex ->
          ¬ G.equationSystem.EquationHolds lawIndex
              (D.objectOfLocalInput i (D.input i)) := by
  intro lawIndex hmem hrequired hholdsLaw
  refine hne ?_
  have hdefect :=
    D.holds_defect_mem i lawIndex hmem hrequired hholdsLaw
  exact
    Ideal.Quotient.eq_zero_iff_mem.mpr
      (G.equationSystem.witnessIdeal_le_obstructionIdeal
        (lawEquationChart coverGeometry G i) hrequired hdefect)

/--
G-06 positive lower construction, common-section form: on the law-equation
realization, displayed required-equation fulfillment constructs the common
restriction realization with the zero base section.

This is the layer Cycle 346/347 left open, now constructed from atom/law
restriction geometry: the equality per chart is the vanishing theorem, and the
zero section restricts to zero because the generated quotient restriction maps
are additive.  No `arrowCompatibilityLaw`, raw overlap equality, evaluator,
`sourceC0CechZero`, residual-zero, or `H1` zero is consumed.
-/
theorem displayedRequiredLawsHoldOn_constructs_commonRestrictionRealization
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (hholds : D.DisplayedRequiredEquationsHoldOn) :
    D.toSupportOnlySemanticAtomLawInputBoundarySource.commonRestrictionRealization := by
  refine ⟨0, fun i => ?_⟩
  rw [D.displayedRequiredLawsHoldOn_constructs_interpret_eq_zero hholds i]
  exact (G.lawEquationObstructionSheaf.map_zero _).symm

/--
G-06 positive lower construction, base-restriction form: the zero base section
packages the law-equation realization as a base-restriction source.
-/
def toBaseRestrictionSource
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton) :
    SourceSectionFreeSkeleton.GeneratedFinitePosetSelectedCoverPresieveBaseRestrictionSemanticAtomLawInputBoundarySource
      skeleton where
  sourceSection := 0
  LocalInput := D.LocalInput
  input := D.input
  atomSupport := D.atomSupport
  atomSupport_traceVisible := D.atomSupport_traceVisible
  lawSupport := fun _ _ => [G.provenanceLawIndex]
  lawSupport_nonempty := fun _ _ =>
    ⟨G.provenanceLawIndex, List.mem_singleton_self G.provenanceLawIndex⟩
  lawSupport_required := fun _ _ lawIndex hmem => by
    have heq : lawIndex = G.provenanceLawIndex := List.eq_of_mem_singleton hmem
    exact heq ▸ G.provenanceLawIndex_required

/--
G-06 positive lower construction, display-preserving form: under displayed
required-equation fulfillment, the generated base-restriction source preserves the
displayed interpretations of the law-equation support-only source.

Together with `toBaseRestrictionSource` this discharges, on the law-equation
realization, the open obligation recorded by Cycle 346/347: a same-source
display-preserving base-restriction source generated from lower semantic
atom/law restriction geometry.  The Cycle 347 no-go is untouched because this
construction requires the law-equation defect source, not support-only data.
-/
theorem displayedRequiredLawsHoldOn_constructs_baseRestrictionSource_preservingDisplayedInterpretation
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (hholds : D.DisplayedRequiredEquationsHoldOn) :
    D.toSupportOnlySemanticAtomLawInputBoundarySource.baseRestrictionSourcePreservesDisplayedInterpretation
      D.toBaseRestrictionSource := by
  intro i
  rw [D.displayedRequiredLawsHoldOn_constructs_interpret_eq_zero hholds i]
  exact G.lawEquationObstructionSheaf.map_zero _

/--
G-06 evaluator theorem: on the law-equation realization, the displayed
required-law restriction evaluator is a theorem, not an external premise.

The proof routes the vanishing theorem through the Cycle 346 common-section
evaluator constructor.  The law premises are genuinely consumed: they enter
through the law-as-equation tie inside the vanishing theorem.
-/
theorem displayedRequiredLawsHoldOn_constructs_displayedRequiredLawRestrictionEvaluator
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (hholds : D.DisplayedRequiredEquationsHoldOn) :
    D.toSupportOnlySemanticAtomLawInputBoundarySource.displayedRequiredLawRestrictionEvaluator
      D.objectOfLocalInput :=
  D.toSupportOnlySemanticAtomLawInputBoundarySource.commonRestrictionRealization_constructs_displayedRequiredLawRestrictionEvaluator
    D.objectOfLocalInput
    (D.displayedRequiredLawsHoldOn_constructs_commonRestrictionRealization hholds)

/--
G-06 generated-Cech proof-use: on the law-equation realization, displayed
required-equation fulfillment constructs the generated `sourceC0CechZero` through
the Cycle 296 descent bridge and the Cycle 311 generated-complex route.

The new lower geometry is therefore routed through the semantic coefficient
Cech complex rather than recorded as a standalone certificate.
-/
theorem displayedRequiredLawsHoldOn_constructs_sourceC0CechZero
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (hholds : D.DisplayedRequiredEquationsHoldOn) :
    atomLawOverlap_sourceSectionFreeSkeleton_sourceC0CechZero coverGeometry
      G.toSemanticAtomLawAdditiveCoefficientGeometry skeleton
      D.toSupportOnlySemanticAtomLawInputBoundarySource :=
  atomLawOverlap_sourceSectionFreeSkeleton_arrowCompatibilityLaw_constructs_sourceC0CechZero
    coverGeometry G.toSemanticAtomLawAdditiveCoefficientGeometry skeleton
    D.toSupportOnlySemanticAtomLawInputBoundarySource
    (D.toSupportOnlySemanticAtomLawInputBoundarySource.commonRestrictionRealization_constructs_arrowCompatibilityLaw
      (D.displayedRequiredLawsHoldOn_constructs_commonRestrictionRealization
        hholds))

/--
G-06 law-equation grounding packet.

On the law-equation realization, displayed required-equation fulfillment
simultaneously constructs: interpretation vanishing, the common restriction
realization, a display-preserving base-restriction source, the displayed
required-law restriction evaluator, the isolated arrow compatibility law, and
the generated-Cech `sourceC0CechZero`.  Every component is generated from the
atom/law input boundary and the lower restriction geometry of the realization;
none is accepted as an input premise.
-/
theorem lawEquation_grounding_packet
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (hholds : D.DisplayedRequiredEquationsHoldOn) :
    (forall i : (lawEquationRegime coverGeometry G).cover.Index,
      D.toSupportOnlySemanticAtomLawInputBoundarySource.interpret i
          (D.toSupportOnlySemanticAtomLawInputBoundarySource.input i) = 0) /\
      D.toSupportOnlySemanticAtomLawInputBoundarySource.commonRestrictionRealization /\
      D.toSupportOnlySemanticAtomLawInputBoundarySource.baseRestrictionSourcePreservesDisplayedInterpretation
        D.toBaseRestrictionSource /\
      D.toSupportOnlySemanticAtomLawInputBoundarySource.displayedRequiredLawRestrictionEvaluator
        D.objectOfLocalInput /\
      D.toSupportOnlySemanticAtomLawInputBoundarySource.arrowCompatibilityLaw /\
      atomLawOverlap_sourceSectionFreeSkeleton_sourceC0CechZero coverGeometry
        G.toSemanticAtomLawAdditiveCoefficientGeometry skeleton
        D.toSupportOnlySemanticAtomLawInputBoundarySource :=
  ⟨D.displayedRequiredLawsHoldOn_constructs_interpret_eq_zero hholds,
    D.displayedRequiredLawsHoldOn_constructs_commonRestrictionRealization hholds,
    D.displayedRequiredLawsHoldOn_constructs_baseRestrictionSource_preservingDisplayedInterpretation
      hholds,
    D.displayedRequiredLawsHoldOn_constructs_displayedRequiredLawRestrictionEvaluator
      hholds,
    D.toSupportOnlySemanticAtomLawInputBoundarySource.commonRestrictionRealization_constructs_arrowCompatibilityLaw
      (D.displayedRequiredLawsHoldOn_constructs_commonRestrictionRealization
        hholds),
    D.displayedRequiredLawsHoldOn_constructs_sourceC0CechZero hholds⟩

end LawEquationDefectSemanticAtomLawInputBoundarySource

end CoverRelativeCechFinitePosetChartProjectionPointwiseAtomLawInputBoundaryBasis

end SemanticRepairCoverRelativeCochainRealization

end SemanticRepairCechGrounding
end QualitySurface
end ResearchLean.AG
