import ResearchLean.AG.QualitySurface.SemanticRepairNonabelianTorsor

/-!
Cycle 82 evidence for `G-aat-quality-surface-04`.

Cycle 81 added the object-level quotient surface for the first sheaf `H1`
layer.  This file adds the analogous finite/small object-level surface for the
pointed nonabelian repair torsor layer.

The current torsor envelope intentionally does not store gauge-action laws.
Therefore the same-class relation and the selected/neutral class comparison
are supplied as visible relation data.  The universal property factors only
observations that explicitly respect that relation.  No global coherence,
tower vanishing, representation adequacy, stack effectiveness, or target
completion is hidden in the torsor or in theorem premises.
-/

namespace ResearchLean.AG
namespace QualitySurface
namespace SemanticRepairNonabelianH1Universality

open SemanticRepairNonabelianTorsor

universe z r s

/-! ## Object-level nonabelian `H1` classes -/

/-- Actual nonabelian `H1` cocycles in a finite pointed repair torsor. -/
def NonabelianRepairH1Cocycle
    {Choice : Type z}
    {Repair : Type r}
    (torsor : FinitePointedRepairTorsor Choice Repair) :
    Type z :=
  { choice : Choice // NonabelianCechZ1 torsor choice }

/--
Visible nonabelian `H1` class relation data.

The relation is external theorem data because the finite pointed torsor does
not store gauge-action laws.  The selected/neutral comparison is also explicit:
it identifies the selected-transition class with the neutral class exactly
when the pointed torsor is trivial.
-/
structure NonabelianRepairH1ClassRelation
    {Choice : Type z}
    {Repair : Type r}
    (torsor : FinitePointedRepairTorsor Choice Repair) where
  neutral_cocycle : NonabelianCechZ1 torsor torsor.neutral
  sameClass :
    NonabelianRepairH1Cocycle torsor ->
      NonabelianRepairH1Cocycle torsor ->
        Prop
  sameClass_refl :
    ∀ cocycle : NonabelianRepairH1Cocycle torsor,
      sameClass cocycle cocycle
  sameClass_symm :
    ∀ left right : NonabelianRepairH1Cocycle torsor,
      sameClass left right -> sameClass right left
  sameClass_trans :
    ∀ left middle right : NonabelianRepairH1Cocycle torsor,
      sameClass left middle ->
        sameClass middle right ->
          sameClass left right
  selected_neutral_iff_trivial :
    sameClass
        ⟨torsor.selectedTransition, torsor.selected_cocycle⟩
        ⟨torsor.neutral, neutral_cocycle⟩ <->
      PointedTorsorTrivial torsor

/-- The visible nonabelian same-class relation on cocycles. -/
def NonabelianRepairH1SameClass
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor)
    (left right : NonabelianRepairH1Cocycle torsor) : Prop :=
  relation.sameClass left right

/-- The quotient setoid generated by the visible nonabelian same-class data. -/
def nonabelianRepairH1CocycleSetoid
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor) :
    Setoid (NonabelianRepairH1Cocycle torsor) where
  r left right := NonabelianRepairH1SameClass relation left right
  iseqv := by
    constructor
    · intro cocycle
      exact relation.sameClass_refl cocycle
    · intro left right hsame
      exact relation.sameClass_symm left right hsame
    · intro left middle right hleft hright
      exact relation.sameClass_trans left middle right hleft hright

/-- The object-level pointed nonabelian repair `H1` class quotient. -/
def NonabelianRepairH1Class
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor) :
    Type z :=
  Quot (nonabelianRepairH1CocycleSetoid relation)

/-- Build a nonabelian repair `H1` class from a visible cocycle. -/
def nonabelianRepairH1Class_mk
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor)
    (choice : Choice)
    (hclosed : NonabelianCechZ1 torsor choice) :
    NonabelianRepairH1Class relation :=
  Quot.mk (nonabelianRepairH1CocycleSetoid relation)
    ⟨choice, hclosed⟩

/-- Same-class cocycles have equal nonabelian repair `H1` quotient classes. -/
theorem nonabelianRepairH1Class_eq_of_sameClass
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor)
    {left right : NonabelianRepairH1Cocycle torsor}
    (hsame : NonabelianRepairH1SameClass relation left right) :
    Quot.mk (nonabelianRepairH1CocycleSetoid relation) left =
      Quot.mk (nonabelianRepairH1CocycleSetoid relation) right := by
  exact Quot.sound hsame

/-- The selected transition as a nonabelian repair `H1` class. -/
def nonabelianRepairH1_selectedTransitionClass
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor) :
    NonabelianRepairH1Class relation :=
  nonabelianRepairH1Class_mk relation
    torsor.selectedTransition torsor.selected_cocycle

/-- The neutral point as a nonabelian repair `H1` class. -/
def nonabelianRepairH1_neutralClass
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor) :
    NonabelianRepairH1Class relation :=
  nonabelianRepairH1Class_mk relation
    torsor.neutral relation.neutral_cocycle

/-! ## Universal factorization and visible effectivity comparison -/

/--
Lift a cocycle observation to nonabelian `H1` classes when it visibly respects
the supplied same-class relation.
-/
def nonabelianRepairH1_lift
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor)
    {Out : Type s}
    (observe : NonabelianRepairH1Cocycle torsor -> Out)
    (respect :
      ∀ left right : NonabelianRepairH1Cocycle torsor,
        NonabelianRepairH1SameClass relation left right ->
          observe left = observe right) :
    NonabelianRepairH1Class relation -> Out :=
  Quot.lift observe (by
    intro left right hsame
    exact respect left right hsame)

/-- The lifted observation agrees with the original observation on cocycles. -/
theorem nonabelianRepairH1_lift_mk
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor)
    {Out : Type s}
    (observe : NonabelianRepairH1Cocycle torsor -> Out)
    (respect :
      ∀ left right : NonabelianRepairH1Cocycle torsor,
        NonabelianRepairH1SameClass relation left right ->
          observe left = observe right)
    (choice : Choice)
    (hclosed : NonabelianCechZ1 torsor choice) :
    nonabelianRepairH1_lift relation observe respect
        (nonabelianRepairH1Class_mk relation choice hclosed) =
      observe ⟨choice, hclosed⟩ := by
  rfl

/--
Universal factorization through the nonabelian repair `H1` quotient class.

Only observations that respect the visible same-class relation factor.
-/
theorem nonabelianRepairH1_universalFactorization
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor)
    {Out : Type s}
    (observe : NonabelianRepairH1Cocycle torsor -> Out)
    (respect :
      ∀ left right : NonabelianRepairH1Cocycle torsor,
        NonabelianRepairH1SameClass relation left right ->
          observe left = observe right) :
    (∀ cocycle : NonabelianRepairH1Cocycle torsor,
      nonabelianRepairH1_lift relation observe respect
          (Quot.mk (nonabelianRepairH1CocycleSetoid relation) cocycle) =
        observe cocycle) ∧
      (∀ factor : NonabelianRepairH1Class relation -> Out,
        (∀ cocycle : NonabelianRepairH1Cocycle torsor,
          factor (Quot.mk (nonabelianRepairH1CocycleSetoid relation) cocycle) =
            observe cocycle) ->
          ∀ cls : NonabelianRepairH1Class relation,
            factor cls =
              nonabelianRepairH1_lift relation observe respect cls) := by
  constructor
  · intro cocycle
    rfl
  · intro factor hfactor cls
    refine Quot.inductionOn cls ?_
    intro cocycle
    simpa [nonabelianRepairH1_lift] using hfactor cocycle

/--
Effective nonabelian repair descent identifies the selected transition class
with the neutral class through the visible same-class relation.
-/
theorem nonabelianRepairH1_selectedClass_eq_neutral_of_effectiveDescent
    {Choice : Type z}
    {Repair : Type r}
    {torsor : FinitePointedRepairTorsor Choice Repair}
    (relation : NonabelianRepairH1ClassRelation torsor)
    (heffective : EffectiveNonabelianRepairDescent torsor) :
    nonabelianRepairH1_selectedTransitionClass relation =
      nonabelianRepairH1_neutralClass relation := by
  rcases heffective with ⟨repair, _heffective, hgauge⟩
  have htrivial : PointedTorsorTrivial torsor := ⟨repair, hgauge⟩
  have hsame :
      NonabelianRepairH1SameClass relation
        ⟨torsor.selectedTransition, torsor.selected_cocycle⟩
        ⟨torsor.neutral, relation.neutral_cocycle⟩ :=
    relation.selected_neutral_iff_trivial.2 htrivial
  exact Quot.sound hsame

end SemanticRepairNonabelianH1Universality
end QualitySurface
end ResearchLean.AG
