import ResearchLean.AG.QualitySurface.SemanticRepairLawEquationRealization

/-!
G-06 end-to-end grounded comparison packet on the law-equation realization.

Cycle 348/349 generated the displayed required-law restriction evaluator and
the generated-Cech `sourceC0CechZero` from law-as-equation geometry, and fixed
a concrete nondegenerate instance.  This file composes that route with the
Cycle 332 canonical-argument-free grounded-packet route, producing a single
end-to-end theorem from the law-equation defect source to the selected
comparison packet: gate realization layer, degree-wise carrier data and
explicit face-restriction equations, cover-relative cochain realization, the
semantic-additive-`H1`-to-cover-relative-`H1` comparison package, residual
boundary, and the semantic / additive `H1` zero readings.

The composition is honest about where the law semantics enters: the displayed
interpretation realization conjunct consumes `displayedRequiredLawsHoldOn`
through the Cycle 348 vanishing theorem, so the base-restricted primitive of
the packet source provably realizes the law-equation source's own displayed
interpretations.  The current-G06 input surface built here carries the
ambient `G.quotientIsSheaf` (discharged for the concrete finite-model
instance, discharge-required in general) and a descent field derived from it;
no conclusion-shaped field is introduced.
-/

noncomputable section

universe u v w x y z r a b

namespace ResearchLean.AG
namespace QualitySurface
namespace SemanticRepairCechGrounding

open CategoryTheory
open Opposite
open SemanticRepairSheafH1
open SemanticRepairTrueSheafH1
open SemanticRepairObstructionTower

namespace SemanticRepairCoverRelativeCochainRealization
namespace CoverRelativeCechFinitePosetChartProjectionPointwiseAtomLawInputBoundaryBasis

open CoverRelativeCechGeneratedSemanticCoefficient

variable {U : AAT.AG.AtomCarrier.{r}} {A : AAT.AG.ArchitectureObject U}
variable {semanticSite : SemanticRepairSite.{r, v} U.Atom}
variable {S : AAT.AG.Site.AATSite A}

/--
Selected cover bridge landing exactly on the generated law-equation
cover-relative cover.  The provenance maps from semantic cover components into
selected simplices are input geometry, exactly as in the general bridge.
-/
def lawEquationCoverBridge
    (coverGeometry : FinitePosetAtomLawCoverGeometry S)
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S)
    (semanticCover : SemanticRepairCover.{r, v, w} semanticSite)
    (chartSimplex :
      semanticCover.CoverChart ->
        (AAT.AG.Cohomology.finitePosetCoverRelativeCover
          (lawEquationStandardComplex coverGeometry G)).simplex 0)
    (overlapSimplex :
      (Sigma fun pair : semanticCover.CoverChart × semanticCover.CoverChart =>
        semanticCover.Overlap pair.1 pair.2) ->
          (AAT.AG.Cohomology.finitePosetCoverRelativeCover
            (lawEquationStandardComplex coverGeometry G)).simplex 1)
    (tripleSimplex :
      (Sigma fun triple :
        semanticCover.CoverChart × semanticCover.CoverChart ×
          semanticCover.CoverChart =>
        semanticCover.TripleOverlap triple.1 triple.2.1 triple.2.2) ->
          (AAT.AG.Cohomology.finitePosetCoverRelativeCover
            (lawEquationStandardComplex coverGeometry G)).simplex 2) :
    SemanticRepairCoverRelativeCoverBridge semanticCover S where
  coverRelative :=
    AAT.AG.Cohomology.finitePosetCoverRelativeCover
      (lawEquationStandardComplex coverGeometry G)
  chartSimplex := chartSimplex
  overlapSimplex := overlapSimplex
  tripleSimplex := tripleSimplex

/--
The current G-06 input surface generated by the law-equation realization.

The general Cech complex is the generated law-equation complex, the presheaf
is the generated obstruction-quotient carrier, the selected cover is the sieve
generated by the displayed atom/law coverage family, the sheaf condition is
the ambient `G.quotientIsSheaf` (discharged on the concrete finite-model
instance, discharge-required in general), and the descent field is derived
from that sheaf condition through the selected cover membership.  No field
stores an overlap equality, `H1` zero, comparison equivalence, or global
coherence.
-/
def lawEquationCurrentG06InputSurface
    (coverGeometry : FinitePosetAtomLawCoverGeometry S)
    (G : SemanticLawEquationWitnessIdealGeometry semanticSite S)
    (semanticCover : SemanticRepairCover.{r, v, w} semanticSite)
    (chartSimplex :
      semanticCover.CoverChart ->
        (AAT.AG.Cohomology.finitePosetCoverRelativeCover
          (lawEquationStandardComplex coverGeometry G)).simplex 0)
    (overlapSimplex :
      (Sigma fun pair : semanticCover.CoverChart × semanticCover.CoverChart =>
        semanticCover.Overlap pair.1 pair.2) ->
          (AAT.AG.Cohomology.finitePosetCoverRelativeCover
            (lawEquationStandardComplex coverGeometry G)).simplex 1)
    (tripleSimplex :
      (Sigma fun triple :
        semanticCover.CoverChart × semanticCover.CoverChart ×
          semanticCover.CoverChart =>
        semanticCover.TripleOverlap triple.1 triple.2.1 triple.2.2) ->
          (AAT.AG.Cohomology.finitePosetCoverRelativeCover
            (lawEquationStandardComplex coverGeometry G)).simplex 2) :
    SemanticRepairCarrierSpecificComparisonProvenance.CurrentG06InputSurface
      (semanticCover := semanticCover) (S := S)
      (Ob := G.lawEquationObstructionSheaf) where
  coverBridge :=
    lawEquationCoverBridge coverGeometry G semanticCover chartSimplex
      overlapSimplex tripleSimplex
  K := lawEquationCechComplex coverGeometry G
  presheaf := G.lawEquationObstructionSheaf.carrier.toPresheaf
  coverBase := coverGeometry.base
  selectedCover := Sieve.generate coverGeometry.cover.presieve
  selectedCover_mem :=
    AAT.AG.Site.AATGrothendieckTopology.generate_mem coverGeometry.cover
  sheafCondition := G.quotientIsSheaf
  descent :=
    AAT.AG.Site.AATSheafConditionFor.descent
      (AAT.AG.Site.AATSheafCondition.cover G.quotientIsSheaf
        (Sieve.generate coverGeometry.cover.presieve)
        (AAT.AG.Site.AATGrothendieckTopology.generate_mem coverGeometry.cover))

namespace LawEquationDefectSemanticAtomLawInputBoundarySource

variable {coverGeometry : FinitePosetAtomLawCoverGeometry S}
variable {G : SemanticLawEquationWitnessIdealGeometry semanticSite S}
variable {skeleton :
  SourceSectionFreeSkeleton
    (semanticSite := semanticSite) (S := S)
    (regime := lawEquationRegime coverGeometry G)
    (C := lawEquationStandardComplex coverGeometry G)
    (Ob := G.lawEquationObstructionSheaf)
    (K := lawEquationCechComplex coverGeometry G)}

/--
Read the law-equation defect source as a Cycle 236 base-restriction
boundary-primitive source over the generated cover, with the zero base section
and the generated overlap-to-base maps.

The zero base section is not an arbitrary choice: the displayed-interpretation
realization theorem below proves, from displayed required-law fulfillment,
that the primitive generated by this base section realizes exactly the
law-equation source's own displayed interpretations.
-/
def toCoverRelativeBaseRestrictionSource
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton) :
    CoverRelativeCechBaseRestrictionBoundaryPrimitiveFreeSemanticAtomLawInputBoundarySource
      semanticSite S
      (AAT.AG.Cohomology.finitePosetCoverRelativeCover
        (lawEquationStandardComplex coverGeometry G))
      G.lawEquationObstructionSheaf
      (lawEquationCechComplex coverGeometry G) where
  c0Order := []
  c1Order := []
  sourceSection := 0
  zeroSimplexToBase := fun sigma =>
    homOfLE
        ((lawEquationRegime coverGeometry G).simplexOverlap_le_patch 0 sigma 0) ≫
      (AAT.AG.Cohomology.finitePosetCoverRelativeCover
        (lawEquationStandardComplex coverGeometry G)).inclusion
        ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0)
  LocalInput := fun sigma =>
    D.LocalInput ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0)
  input := fun sigma =>
    D.input ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0)
  atomSupport := fun sigma =>
    D.atomSupport ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0)
  atomSupport_traceVisible := fun sigma =>
    D.atomSupport_traceVisible
      ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0)
  lawSupport := fun _ _ => [G.provenanceLawIndex]
  lawSupport_nonempty := fun _ _ =>
    ⟨G.provenanceLawIndex, List.mem_singleton_self G.provenanceLawIndex⟩
  lawSupport_required := fun _ _ lawIndex hmem => by
    have heq : lawIndex = G.provenanceLawIndex := List.eq_of_mem_singleton hmem
    exact heq ▸ G.provenanceLawIndex_required

/--
Displayed-interpretation realization: under displayed required-law
fulfillment, the base-restricted degree-`0` primitive of the generated packet
source realizes exactly the law-equation source's displayed interpretations,
restricted to each selected `0`-simplex overlap.

This conjunct is where the law semantics is consumed: both sides are proved
zero through the Cycle 348 vanishing theorem and the additive restriction
maps.  Without `hholds` there is no such realization claim.
-/
theorem displayedRequiredLawsHoldOn_constructs_primitive_realizes_displayedInterpretations
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (hholds : D.DisplayedRequiredEquationsHoldOn) :
    forall sigma :
      (AAT.AG.Cohomology.finitePosetCoverRelativeCover
        (lawEquationStandardComplex coverGeometry G)).simplex 0,
      D.toCoverRelativeBaseRestrictionSource.toPrimitive sigma =
        G.lawEquationObstructionSheaf.carrier.toPresheaf.map
          (homOfLE
            ((lawEquationRegime coverGeometry G).simplexOverlap_le_patch 0
              sigma 0)).op
          (D.toSupportOnlySemanticAtomLawInputBoundarySource.interpret
            ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0)
            (D.toSupportOnlySemanticAtomLawInputBoundarySource.input
              ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0))) := by
  intro sigma
  rw [D.displayedRequiredLawsHoldOn_constructs_interpret_eq_zero hholds
      ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0)]
  show
    G.lawEquationObstructionSheaf.carrier.toPresheaf.map
        (D.toCoverRelativeBaseRestrictionSource.zeroSimplexToBase sigma).op
        (0 :
          G.lawEquationObstructionSheaf.carrier.toPresheaf.obj
            (op
              (AAT.AG.Cohomology.finitePosetCoverRelativeCover
                (lawEquationStandardComplex coverGeometry G)).base)) =
      G.lawEquationObstructionSheaf.carrier.toPresheaf.map
        (homOfLE
          ((lawEquationRegime coverGeometry G).simplexOverlap_le_patch 0
            sigma 0)).op
        0
  rw [G.lawEquationObstructionSheaf.map_zero, G.lawEquationObstructionSheaf.map_zero]

/--
G-06 end-to-end law-equation grounded comparison packet composition.

Per-conjunct dependence on the law premise is as follows and is part of the
claim.  Conjuncts 1-3 (displayed-interpretation realization, displayed
required-law restriction evaluator, generated-Cech `sourceC0CechZero`) consume
`hholds` through the Cycle 348 vanishing theorem; they are where the law
semantics enters, and it enters at cochain degree `0`.  Conjuncts 4-10 (gate
layer, degree-wise carrier data and face-restriction equations, cochain
realization, comparison package, residual boundary, semantic / additive `H1`
zero) come from the reviewed Cycle 332 route applied to the zero-base-section
packet source; they hold for the generated boundary coefficient by
construction (`residual := K.d 0 primitive`) and do NOT depend on `hholds`.
In particular the `H1` zero conjuncts must not be cited as law-grounded
descent content; the law-grounded content of this composition is exactly
conjuncts 1-3.

The input surface's `sheafCondition` field is the ambient
`G.quotientIsSheaf`; it is proved for the concrete finite-model instance in
`SemanticRepairLawEquationWitnessInstance.lean` and remains the
discharge-required `AATSheafCondition` ledger item at the general level.

No evaluator, arrow compatibility law, overlap equality, `sourceC0CechZero`,
residual-zero, `H1` zero, `c0Equiv`, or comparison certificate is accepted as
an input premise; each appears only in the conclusion.
-/
theorem lawEquation_constructs_groundedComparisonPacket
    (D :
      LawEquationDefectSemanticAtomLawInputBoundarySource coverGeometry G
        skeleton)
    (semanticCover : SemanticRepairCover.{r, v, w} semanticSite)
    (chartSimplex :
      semanticCover.CoverChart ->
        (AAT.AG.Cohomology.finitePosetCoverRelativeCover
          (lawEquationStandardComplex coverGeometry G)).simplex 0)
    (overlapSimplex :
      (Sigma fun pair : semanticCover.CoverChart × semanticCover.CoverChart =>
        semanticCover.Overlap pair.1 pair.2) ->
          (AAT.AG.Cohomology.finitePosetCoverRelativeCover
            (lawEquationStandardComplex coverGeometry G)).simplex 1)
    (tripleSimplex :
      (Sigma fun triple :
        semanticCover.CoverChart × semanticCover.CoverChart ×
          semanticCover.CoverChart =>
        semanticCover.TripleOverlap triple.1 triple.2.1 triple.2.2) ->
          (AAT.AG.Cohomology.finitePosetCoverRelativeCover
            (lawEquationStandardComplex coverGeometry G)).simplex 2)
    (hholds : D.DisplayedRequiredEquationsHoldOn) :
    let surface :=
      lawEquationCurrentG06InputSurface coverGeometry G semanticCover
        chartSimplex overlapSimplex tripleSimplex
    let source := D.toCoverRelativeBaseRestrictionSource
    let restrictionSource :=
      source.toRestrictionRealizedBoundaryPrimitiveFreeSemanticAtomLawInputBoundarySource
    let boundarySource :=
      restrictionSource.toBoundaryPrimitiveFreeSemanticAtomLawInputBoundarySource
    let freeSource := boundarySource.toFreeSemanticAtomLawInputBoundarySource
    let geometry :=
      CoverRelativeCechSemanticAtomLawInputBoundaryGeometry.ofFreeSemanticAtomLawInputBoundarySource
        freeSource
    let boundary :=
      geometry.toBoundaryGeneratedCoefficient
        (K := surface.K) source.c0Order source.c1Order
    let generated := boundary.toGeneratedCoefficient
    let canonical :=
      CoverRelativeCechGeneratedCanonicalH1Envelope.defaultObservationEnvelope
        (site := semanticSite) generated
    let envelope := canonical.toGeneratedEnvelope
    let realization := envelope.toCochainRealization
    (forall sigma :
      (AAT.AG.Cohomology.finitePosetCoverRelativeCover
        (lawEquationStandardComplex coverGeometry G)).simplex 0,
      source.toPrimitive sigma =
        G.lawEquationObstructionSheaf.carrier.toPresheaf.map
          (homOfLE
            ((lawEquationRegime coverGeometry G).simplexOverlap_le_patch 0
              sigma 0)).op
          (D.toSupportOnlySemanticAtomLawInputBoundarySource.interpret
            ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0)
            (D.toSupportOnlySemanticAtomLawInputBoundarySource.input
              ((lawEquationRegime coverGeometry G).simplexIndices 0 sigma 0)))) /\
      D.toSupportOnlySemanticAtomLawInputBoundarySource.displayedRequiredLawRestrictionEvaluator
        D.objectOfLocalInput /\
      atomLawOverlap_sourceSectionFreeSkeleton_sourceC0CechZero coverGeometry
        G.toSemanticAtomLawAdditiveCoefficientGeometry skeleton
        D.toSupportOnlySemanticAtomLawInputBoundarySource /\
      Nonempty
        (SelectedSemanticCoefficientDirectRealizationLayer
          (E := envelope.toEnvelope)
          (additive := envelope.toAdditiveCechH1Data) surface) /\
      DegreewiseCarrierDataAndExplicitFaceRestrictionEquations
        (E := envelope.toEnvelope)
        (additive := envelope.toAdditiveCechH1Data)
        (coverBridge := surface.coverBridge)
        (K := surface.K) /\
      Nonempty
        (SemanticRepairCoverRelativeCochainRealization
          envelope.toAdditiveCechH1Data surface.K) /\
      Nonempty
        (SemanticRepairCoverRelativeH1Comparison.SemanticRepairAdditiveH1CoverRelativeH1ComparisonPackage
          realization.toH1Comparison) /\
      canonical.residualBoundary /\
      SemanticRepairH1Zero envelope.toEnvelope /\
      SemanticRepairAdditiveH1Zero envelope.toAdditiveCechH1Data := by
  dsimp
  have hroute :=
    CoverRelativeCechBaseRestrictionBoundaryPrimitiveFreeSemanticAtomLawInputBoundarySource.baseRestriction_constructs_identityC0ReplacementRoute_and_additiveCechBoundaryRoute_withoutCanonicalArgument
      (surface :=
        lawEquationCurrentG06InputSurface coverGeometry G semanticCover
          chartSimplex overlapSimplex tripleSimplex)
      coverGeometry.cover rfl
      D.toCoverRelativeBaseRestrictionSource
  rcases hroute with
    ⟨_hsection, _hsectionToLocal, _hprimitive, _hboundaryPrimitive, _hresidual,
      _hvisible, _hcontinuation, _hsource, hlayer, hface, hrealization,
      _hc0Carrier, hcomparison, _hprimitiveBoundary, hboundary, hsemanticH1,
      hadditiveH1⟩
  exact
    ⟨D.displayedRequiredLawsHoldOn_constructs_primitive_realizes_displayedInterpretations
        hholds,
      D.displayedRequiredLawsHoldOn_constructs_displayedRequiredLawRestrictionEvaluator
        hholds,
      D.displayedRequiredLawsHoldOn_constructs_sourceC0CechZero hholds,
      hlayer,
      hface,
      hrealization,
      hcomparison,
      hboundary,
      hsemanticH1,
      hadditiveH1⟩

end LawEquationDefectSemanticAtomLawInputBoundarySource

end CoverRelativeCechFinitePosetChartProjectionPointwiseAtomLawInputBoundaryBasis
end SemanticRepairCoverRelativeCochainRealization

end SemanticRepairCechGrounding
end QualitySurface
end ResearchLean.AG
