import Formal.AG.Cohomology.FinitePosetComparison
import Formal.AG.Site.FinitePosetGeometry
import Mathlib.Algebra.BigOperators.Fin

noncomputable section

namespace AAT.AG

universe u

open CategoryTheory
open Opposite

namespace Site.FinitePosetCoverGeometry

variable {U : AtomCarrier.{u}} {A : ArchitectureObject U}
variable {S : Site.AATSite A}

/--
X.R1(b): generate the finite-poset regime whose coefficient is the selected
obstruction sheaf carrier.
-/
def toObstructionCoefficientRegime
    (geometry : Site.FinitePosetCoverGeometry S)
    (Ob : Cohomology.ObstructionSheaf S) :
    Site.FinitePosetAATSiteRegime S :=
  geometry.toRegime Ob.carrier.toPresheaf

/-- X.R1(b): generated coefficients are definitionally obstruction sections. -/
theorem toObstructionCoefficientRegime_coefficient_obj
    (geometry : Site.FinitePosetCoverGeometry S)
    (Ob : Cohomology.ObstructionSheaf S) (W : S.category) :
    (geometry.toObstructionCoefficientRegime Ob).coefficient.obj (op W) =
      Ob.carrier.toPresheaf.obj (op W) :=
  rfl

/-- X.R1(b): the generated obstruction regime keeps the coefficient-free cover. -/
theorem toObstructionCoefficientRegime_cover
    (geometry : Site.FinitePosetCoverGeometry S)
    (Ob : Cohomology.ObstructionSheaf S) :
    (geometry.toObstructionCoefficientRegime Ob).cover = geometry.cover :=
  rfl

end Site.FinitePosetCoverGeometry

namespace Cohomology

namespace StandardFinitePosetCech

variable {U : AtomCarrier.{u}} {A : ArchitectureObject U}
variable {S : Site.AATSite A}

/-- X.R1(a): obstruction-coefficient finite-poset sections inherit abelian groups. -/
instance obstructionFinitePosetCechSectionAddCommGroup
    (geometry : Site.FinitePosetCoverGeometry S)
    (Ob : ObstructionSheaf S) (n : Nat)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) n) :
    AddCommGroup
      (Site.FinitePosetCechSection
        (geometry.toObstructionCoefficientRegime Ob) n simplex) := by
  change
    AddCommGroup
      (Ob.carrier.toPresheaf.obj
        (op
          (Site.FinitePosetCechOverlapObject
            (geometry.toObstructionCoefficientRegime Ob) n simplex)))
  infer_instance

/--
X.R1(a): standard alternating sum in an obstruction sheaf section group.

The sign convention is the finite alternating sum over `Fin m`: even indices
are added and odd indices are subtracted.
-/
def obstructionSheafStandardAlternatingCombination
    (Ob : ObstructionSheaf S) (W : S.category) (m : Nat)
    (terms : Fin m -> Ob.carrier.toPresheaf.obj (op W)) :
    Ob.carrier.toPresheaf.obj (op W) :=
  letI := Ob.addCommGroup W
  Finset.univ.sum
    (fun i : Fin m => if Even i.val then terms i else -terms i)

/-- X.R1(a): the standard alternating sum of zero terms is zero. -/
theorem obstructionSheafStandardAlternatingCombination_zero
    (Ob : ObstructionSheaf S) (W : S.category) (m : Nat) :
    obstructionSheafStandardAlternatingCombination Ob W m (fun _ => 0) = 0 := by
  classical
  letI := Ob.addCommGroup W
  simp [obstructionSheafStandardAlternatingCombination]

/--
X.R1(a): obstruction-sheaf restrictions commute with the standard alternating
sum.
-/
theorem obstructionSheafStandardAlternatingCombination_map
    (Ob : ObstructionSheaf S)
    {source target : S.category} (f : source ⟶ target)
    (m : Nat)
    (terms : Fin m -> Ob.carrier.toPresheaf.obj (op target)) :
    Ob.carrier.toPresheaf.map f.op
        (obstructionSheafStandardAlternatingCombination Ob target m terms) =
      obstructionSheafStandardAlternatingCombination Ob source m
        (fun i => Ob.carrier.toPresheaf.map f.op (terms i)) := by
  classical
  letI := Ob.addCommGroup target
  letI := Ob.addCommGroup source
  let restrictionHom :
      Ob.carrier.toPresheaf.obj (op target) →+
        Ob.carrier.toPresheaf.obj (op source) := {
    toFun := Ob.carrier.toPresheaf.map f.op
    map_zero' := Ob.map_zero f
    map_add' := by
      intro x y
      exact Ob.map_add f x y }
  dsimp [obstructionSheafStandardAlternatingCombination]
  change
    restrictionHom
        (Finset.univ.sum
          (fun i : Fin m => if Even i.val then terms i else -terms i)) =
      Finset.univ.sum
        (fun i : Fin m =>
          if Even i.val then restrictionHom (terms i) else -restrictionHom (terms i))
  rw [map_sum restrictionHom]
  refine Finset.sum_congr rfl ?_
  intro i _hi
  by_cases h : Even i.val
  · simp [h]
  · simp [h, map_neg restrictionHom (terms i)]

/--
X.R1(a): standard additive data for the obstruction-coefficient finite-poset
regime generated by a coefficient-free cover geometry.
-/
def standardAdditiveData
    (geometry : Site.FinitePosetCoverGeometry S)
    (Ob : ObstructionSheaf S) :
    Site.FinitePosetCechAdditiveData
      (geometry.toObstructionCoefficientRegime Ob) where
  zeroSection := by
    intro n simplex
    letI :=
      Ob.addCommGroup
        (Site.FinitePosetCechOverlapObject
          (geometry.toObstructionCoefficientRegime Ob) n simplex)
    exact
      (0 :
        Ob.carrier.toPresheaf.obj
          (op
            (Site.FinitePosetCechOverlapObject
              (geometry.toObstructionCoefficientRegime Ob) n simplex)))
  combineFaces := by
    intro n simplex terms
    exact
      obstructionSheafStandardAlternatingCombination Ob
        (Site.FinitePosetCechOverlapObject
          (geometry.toObstructionCoefficientRegime Ob) (n + 1) simplex)
        (n + 2) terms
  combineFaces_zero := by
    intro n simplex
    exact
      obstructionSheafStandardAlternatingCombination_zero Ob
        (Site.FinitePosetCechOverlapObject
          (geometry.toObstructionCoefficientRegime Ob) (n + 1) simplex)
        (n + 2)

/-- X.R1(a): standard face-restriction differential. -/
def standardDifferential
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat) :
    Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n ->
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) (n + 1) :=
  fun cochain simplex =>
    (standardAdditiveData geometry Ob).combineFaces n simplex
      (fun i => Site.FinitePosetCechFaceRestriction faces cochain simplex i)

/-- X.R1(a): the standard differential sends zero to zero. -/
theorem standardDifferential_zero
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat) :
    standardDifferential faces n
        (Site.FinitePosetCechZeroCochain
          (standardAdditiveData geometry Ob) n) =
      Site.FinitePosetCechZeroCochain
        (standardAdditiveData geometry Ob) (n + 1) := by
  funext simplex
  classical
  let W :=
    Site.FinitePosetCechOverlapObject
      (geometry.toObstructionCoefficientRegime Ob) (n + 1) simplex
  letI := Ob.addCommGroup W
  change
    obstructionSheafStandardAlternatingCombination Ob W (n + 2)
        (fun i =>
          Ob.carrier.toPresheaf.map
            (homOfLE (faces.faceOverlap_le n simplex i)).op 0) =
      0
  rw [show
      (fun i =>
          Ob.carrier.toPresheaf.map
            (homOfLE (faces.faceOverlap_le n simplex i)).op 0) =
        (fun _ : Fin (n + 2) => 0) by
        funext i
        exact Ob.map_zero (homOfLE (faces.faceOverlap_le n simplex i))]
  exact obstructionSheafStandardAlternatingCombination_zero Ob W (n + 2)

/--
X.R1(a): restrict a degree-`n` cochain along an inner face of an outer face,
then back to the original selected `(n+3)`-fold overlap.
-/
def standardDoubleFaceRestriction
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (outer : Fin (n + 3)) (inner : Fin (n + 2)) :
    Site.FinitePosetCechSection
      (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex :=
  Ob.carrier.toPresheaf.map
      (homOfLE (faces.faceOverlap_le (n + 1) simplex outer)).op
    (Site.FinitePosetCechFaceRestriction faces cochain
      (faces.face (n + 1) simplex outer) inner)

/-- X.R1(a): route-level composite restriction map for one double-face term. -/
def standardDoubleFaceRestrictionMap
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (outer : Fin (n + 3)) (inner : Fin (n + 2)) :
    Ob.carrier.toPresheaf.obj
        (op
          (Site.FinitePosetCechOverlapObject
            (geometry.toObstructionCoefficientRegime Ob) n
            (faces.face n (faces.face (n + 1) simplex outer) inner))) ->
      Site.FinitePosetCechSection
        (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex :=
  Ob.carrier.toPresheaf.map
    (homOfLE
      (S.contextPreorder.trans
        (faces.faceOverlap_le (n + 1) simplex outer)
        (faces.faceOverlap_le n
          (faces.face (n + 1) simplex outer) inner))).op

/-- X.R1(a): double-face restriction is the route map applied to the cochain. -/
theorem standardDoubleFaceRestriction_eq_restrictionMap_apply
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (outer : Fin (n + 3)) (inner : Fin (n + 2)) :
    standardDoubleFaceRestriction faces n cochain simplex outer inner =
      standardDoubleFaceRestrictionMap faces n simplex outer inner
        (cochain (faces.face n (faces.face (n + 1) simplex outer) inner)) := by
  dsimp [standardDoubleFaceRestriction,
    Site.FinitePosetCechFaceRestriction,
    standardDoubleFaceRestrictionMap,
    Site.FinitePosetCoverGeometry.toRegime,
    Site.FinitePosetCoverGeometry.toObstructionCoefficientRegime]
  rw [← CategoryTheory.FunctorToTypes.map_comp_apply]
  congr

/--
X.R1(a): transport the left two-face restriction map along a lower simplex
identity.
-/
def standardDoubleFaceRestrictionMapTransported
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (i j : Fin (n + 2))
    (hface :
      faces.face n (faces.face (n + 1) simplex j.succ) i =
        faces.face n (faces.face (n + 1) simplex i.castSucc) j) :
    Ob.carrier.toPresheaf.obj
        (op
          (Site.FinitePosetCechOverlapObject
            (geometry.toObstructionCoefficientRegime Ob) n
            (faces.face n (faces.face (n + 1) simplex i.castSucc) j))) ->
      Site.FinitePosetCechSection
        (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex :=
  Ob.carrier.toPresheaf.map
    (homOfLE
      (S.contextPreorder.trans
        (faces.faceOverlap_le (n + 1) simplex j.succ)
        (by
          simpa [hface] using
            faces.faceOverlap_le n
              (faces.face (n + 1) simplex j.succ) i))).op

/-- X.R1(a): transported and right double-face route maps agree by thinness. -/
theorem standardDoubleFaceRestrictionMapTransported_eq_of_twoFaceSimplexIdentity
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (i j : Fin (n + 2))
    (hface :
      faces.face n (faces.face (n + 1) simplex j.succ) i =
        faces.face n (faces.face (n + 1) simplex i.castSucc) j) :
    standardDoubleFaceRestrictionMapTransported
        faces n simplex i j hface =
      standardDoubleFaceRestrictionMap faces n simplex i.castSucc j := by
  funext x
  dsimp [standardDoubleFaceRestrictionMapTransported,
    standardDoubleFaceRestrictionMap,
    Site.FinitePosetCoverGeometry.toRegime,
    Site.FinitePosetCoverGeometry.toObstructionCoefficientRegime]

/-- X.R1(a): composite restriction is invariant under transport of equal faces. -/
theorem standardCompositeRestrictionMap_apply_eq_of_lowSimplex_eq
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (n : Nat)
    (top :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (lowLeft lowRight :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) n)
    (h : lowLeft = lowRight)
    (hleLeft :
      S.contextPreorder.le
        ((geometry.toObstructionCoefficientRegime Ob).simplexOverlap (n + 2) top)
        ((geometry.toObstructionCoefficientRegime Ob).simplexOverlap n lowLeft))
    (hleRight :
      S.contextPreorder.le
        ((geometry.toObstructionCoefficientRegime Ob).simplexOverlap (n + 2) top)
        ((geometry.toObstructionCoefficientRegime Ob).simplexOverlap n lowRight))
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n) :
    Ob.carrier.toPresheaf.map (homOfLE hleLeft).op (cochain lowLeft) =
      Ob.carrier.toPresheaf.map (homOfLE hleRight).op (cochain lowRight) := by
  cases h
  congr

/-- X.R1(a): the left double-face route transports to the right lower face. -/
theorem standardDoubleFaceRestrictionMap_apply_transport
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (i j : Fin (n + 2))
    (hface :
      faces.face n (faces.face (n + 1) simplex j.succ) i =
        faces.face n (faces.face (n + 1) simplex i.castSucc) j) :
    standardDoubleFaceRestrictionMap faces n simplex j.succ i
        (cochain (faces.face n (faces.face (n + 1) simplex j.succ) i)) =
      standardDoubleFaceRestrictionMapTransported faces n simplex i j hface
        (cochain (faces.face n (faces.face (n + 1) simplex i.castSucc) j)) := by
  dsimp [standardDoubleFaceRestrictionMap,
    standardDoubleFaceRestrictionMapTransported,
    Site.FinitePosetCoverGeometry.toRegime,
    Site.FinitePosetCoverGeometry.toObstructionCoefficientRegime]
  exact
    standardCompositeRestrictionMap_apply_eq_of_lowSimplex_eq
      (geometry := geometry) (Ob := Ob) n simplex
      (faces.face n (faces.face (n + 1) simplex j.succ) i)
      (faces.face n (faces.face (n + 1) simplex i.castSucc) j)
      hface
      (S.contextPreorder.trans
        (faces.faceOverlap_le (n + 1) simplex j.succ)
        (faces.faceOverlap_le n (faces.face (n + 1) simplex j.succ) i))
      (S.contextPreorder.trans
        (faces.faceOverlap_le (n + 1) simplex j.succ)
        (by
          simpa [hface] using
            faces.faceOverlap_le n (faces.face (n + 1) simplex j.succ) i))
      cochain

/-- X.R1(a): the explicit second standard differential double alternating sum. -/
def standardDoubleAlternatingFaceCombination
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2)) :
    Site.FinitePosetCechSection
      (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex :=
  obstructionSheafStandardAlternatingCombination Ob
    (Site.FinitePosetCechOverlapObject
      (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
    (n + 3)
    (fun outer =>
      obstructionSheafStandardAlternatingCombination Ob
        (Site.FinitePosetCechOverlapObject
          (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
        (n + 2)
        (fun inner =>
          standardDoubleFaceRestriction faces n cochain simplex outer inner))

/-- X.R1(a): one signed double-face term in the Cech `d²` rectangle. -/
def standardSignedDoubleFaceTerm
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (outer : Fin (n + 3)) (inner : Fin (n + 2)) :
    Site.FinitePosetCechSection
      (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex := by
  letI :=
    Ob.addCommGroup
      (Site.FinitePosetCechOverlapObject
        (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
  let term := standardDoubleFaceRestriction faces n cochain simplex outer inner
  let innerSigned := if Even inner.val then term else -term
  exact if Even outer.val then innerSigned else -innerSigned

/-- X.R1(a): pure finite Cech rectangle sum. -/
def finiteCechRectangleSum (M : Type*) [AddCommMonoid M] (N : Nat)
    (f : Fin (N + 1) -> Fin N -> M) : M :=
  Finset.univ.sum
    (fun outer : Fin (N + 1) =>
      Finset.univ.sum (fun inner : Fin N => f outer inner))

/-- X.R1(a): pure finite triangular paired sum. -/
def finiteCechTriangularPairSum (M : Type*) [AddCommMonoid M] (N : Nat)
    (f : Fin (N + 1) -> Fin N -> M) : M :=
  Finset.univ.sum
    (fun i : Fin N =>
      (Finset.univ.filter (fun j : Fin N => i ≤ j)).sum
        (fun j => f j.succ i + f i.castSucc j))

theorem finiteCech_sum_filter_castSucc_le
    {M : Type*} [AddCommMonoid M] {N : Nat}
    (i : Fin N) (g : Fin (N + 1) -> M) :
    (Finset.univ.filter (fun j : Fin (N + 1) => i.castSucc ≤ j)).sum g =
      (Finset.univ.filter (fun j : Fin N => i ≤ j)).sum (fun j => g j.castSucc) +
        g (Fin.last N) := by
  rw [Finset.sum_filter, Fin.sum_univ_castSucc, ← Finset.sum_filter]
  simp [Fin.castSucc_le_castSucc_iff, Fin.le_last]

theorem finiteCech_sum_filter_last_le
    {M : Type*} [AddCommMonoid M] {N : Nat}
    (g : Fin (N + 1) -> M) :
    (Finset.univ.filter (fun j : Fin (N + 1) => Fin.last N ≤ j)).sum g =
      g (Fin.last N) := by
  rw [Finset.sum_filter, Fin.sum_univ_castSucc]
  simp [Fin.last_le_iff, Fin.castSucc_ne_last]

theorem finiteCechRectangleSum_succ
    {M : Type*} [AddCommMonoid M] (N : Nat)
    (f : Fin (N + 1 + 1) -> Fin (N + 1) -> M) :
    finiteCechRectangleSum M (N + 1) f =
      finiteCechRectangleSum M N (fun outer inner => f outer.castSucc inner.castSucc) +
        Finset.univ.sum (fun outer : Fin (N + 1) => f outer.castSucc (Fin.last N)) +
          Finset.univ.sum (fun inner : Fin (N + 1) =>
            f (Fin.last (N + 1)) inner) := by
  unfold finiteCechRectangleSum
  simp_rw [Fin.sum_univ_castSucc]
  rw [Finset.sum_add_distrib]
  simp [add_assoc, add_comm, add_left_comm]

theorem finiteCechTriangularPairSum_succ
    {M : Type*} [AddCommMonoid M] (N : Nat)
    (f : Fin (N + 1 + 1) -> Fin (N + 1) -> M) :
    finiteCechTriangularPairSum M (N + 1) f =
      finiteCechTriangularPairSum M N
        (fun outer inner => f outer.castSucc inner.castSucc) +
        Finset.univ.sum (fun inner : Fin (N + 1) =>
          f (Fin.last (N + 1)) inner) +
          Finset.univ.sum (fun outer : Fin (N + 1) =>
            f outer.castSucc (Fin.last N)) := by
  unfold finiteCechTriangularPairSum
  simp_rw [Fin.sum_univ_castSucc]
  simp_rw [finiteCech_sum_filter_castSucc_le]
  rw [finiteCech_sum_filter_last_le]
  simp [Finset.sum_add_distrib, add_assoc, add_comm, add_left_comm]

/-- X.R1(a): rectangle double-face indices reindex to triangular Cech pairs. -/
theorem finiteCechRectangleSum_eq_triangularPairSum
    {M : Type*} [AddCommMonoid M] (N : Nat)
    (f : Fin (N + 1) -> Fin N -> M) :
    finiteCechRectangleSum M N f = finiteCechTriangularPairSum M N f := by
  induction N with
  | zero =>
      simp [finiteCechRectangleSum, finiteCechTriangularPairSum]
  | succ N ih =>
      rw [finiteCechRectangleSum_succ, finiteCechTriangularPairSum_succ, ih]
      simp [add_comm, add_left_comm]

/-- X.R1(a): nested alternating sums expand to signed double-face terms. -/
theorem standardDoubleAlternatingFaceCombination_eq_signedTermSum
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2)) :
    standardDoubleAlternatingFaceCombination faces n cochain simplex =
      letI :=
        Ob.addCommGroup
          (Site.FinitePosetCechOverlapObject
            (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
      Finset.univ.sum
        (fun outer : Fin (n + 3) =>
          Finset.univ.sum
            (fun inner : Fin (n + 2) =>
              standardSignedDoubleFaceTerm faces n cochain simplex outer inner)) := by
  classical
  letI :=
    Ob.addCommGroup
      (Site.FinitePosetCechOverlapObject
        (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
  dsimp [standardDoubleAlternatingFaceCombination,
    obstructionSheafStandardAlternatingCombination,
    standardSignedDoubleFaceTerm]
  refine Finset.sum_congr rfl ?_
  intro outer _houter_mem
  by_cases houter : Even outer.val
  · simp [houter]
  · simp [houter, Finset.sum_neg_distrib]

/-- X.R1(a): triangular surface of paired signed double-face terms. -/
def standardTriangularDoubleFacePairSum
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2)) :
    Site.FinitePosetCechSection
      (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex := by
  classical
  letI :=
    Ob.addCommGroup
      (Site.FinitePosetCechOverlapObject
        (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
  exact
    Finset.univ.sum
      (fun i : Fin (n + 2) =>
        (Finset.univ.filter (fun j : Fin (n + 2) => i ≤ j)).sum
          (fun j =>
            standardSignedDoubleFaceTerm faces n cochain simplex j.succ i +
              standardSignedDoubleFaceTerm faces n cochain simplex i.castSucc j))

/-- X.R1(a): signed double-face rectangle reindexes to triangular pairs. -/
theorem standardSignedDoubleFaceTermSum_eq_triangularPairSum
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2)) :
    letI :=
      Ob.addCommGroup
        (Site.FinitePosetCechOverlapObject
          (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
    Finset.univ.sum
        (fun outer : Fin (n + 3) =>
          Finset.univ.sum
            (fun inner : Fin (n + 2) =>
              standardSignedDoubleFaceTerm faces n cochain simplex outer inner)) =
      standardTriangularDoubleFacePairSum faces n cochain simplex := by
  classical
  letI :=
    Ob.addCommGroup
      (Site.FinitePosetCechOverlapObject
        (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
  change
    finiteCechRectangleSum
        (Site.FinitePosetCechSection
          (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
        (n + 2)
        (fun outer inner =>
          standardSignedDoubleFaceTerm faces n cochain simplex outer inner) =
      finiteCechTriangularPairSum
        (Site.FinitePosetCechSection
          (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
        (n + 2)
        (fun outer inner =>
          standardSignedDoubleFaceTerm faces n cochain simplex outer inner)
  exact
    finiteCechRectangleSum_eq_triangularPairSum (n + 2)
      (fun outer inner =>
        standardSignedDoubleFaceTerm faces n cochain simplex outer inner)

/-- X.R1(a): the double alternating combination equals the triangular pair sum. -/
theorem standardDoubleAlternatingFaceCombination_eq_triangularPairSum
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2)) :
    standardDoubleAlternatingFaceCombination faces n cochain simplex =
      standardTriangularDoubleFacePairSum faces n cochain simplex := by
  rw [standardDoubleAlternatingFaceCombination_eq_signedTermSum]
  exact standardSignedDoubleFaceTermSum_eq_triangularPairSum faces n cochain simplex

/-- X.R1(a): local equality of the two paired double-face restriction terms. -/
def TwoFaceTermEquality
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (i j : Fin (n + 2)) : Prop :=
  standardDoubleFaceRestriction faces n cochain simplex j.succ i =
    standardDoubleFaceRestriction faces n cochain simplex i.castSucc j

namespace TwoFaceTermEquality

/-- X.R1(a): a two-face simplex identity generates local term equality. -/
theorem of_twoFaceSimplexIdentity
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (i j : Fin (n + 2))
    (hface :
      faces.face n (faces.face (n + 1) simplex j.succ) i =
        faces.face n (faces.face (n + 1) simplex i.castSucc) j) :
    TwoFaceTermEquality faces n cochain simplex i j := by
  dsimp [TwoFaceTermEquality]
  rw [standardDoubleFaceRestriction_eq_restrictionMap_apply]
  rw [standardDoubleFaceRestrictionMap_apply_transport
    faces n cochain simplex i j hface]
  rw [standardDoubleFaceRestrictionMapTransported_eq_of_twoFaceSimplexIdentity
    faces n simplex i j hface]
  rw [standardDoubleFaceRestriction_eq_restrictionMap_apply]

end TwoFaceTermEquality

/--
X.R1(a): lower two-face law. It stores only the triangular simplex identity,
not cancellation, `d ∘ d = 0`, or cohomology data.
-/
structure TwoFaceRestrictionMapLaw
    (geometry : Site.FinitePosetCoverGeometry S)
    (Ob : ObstructionSheaf S)
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)) where
  twoFace_simplex_eq :
    ∀ (n : Nat)
      (simplex :
        Site.FinitePosetCechSimplex
          (geometry.toObstructionCoefficientRegime Ob) (n + 2))
      (i j : Fin (n + 2)),
      i ≤ j ->
      faces.face n (faces.face (n + 1) simplex j.succ) i =
        faces.face n (faces.face (n + 1) simplex i.castSucc) j

namespace TwoFaceRestrictionMapLaw

/-- X.R1(a): lower two-face law generates local term equality. -/
theorem toTwoFaceTermEquality
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : TwoFaceRestrictionMapLaw geometry Ob faces)
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (i j : Fin (n + 2)) (hle : i ≤ j) :
    TwoFaceTermEquality faces n cochain simplex i j :=
  TwoFaceTermEquality.of_twoFaceSimplexIdentity
    faces n cochain simplex i j (law.twoFace_simplex_eq n simplex i j hle)

end TwoFaceRestrictionMapLaw

/-- X.R1(a): a simplicial face action generates the lower two-face law. -/
def twoFaceRestrictionMapLawOfSimplicialFaceAction
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (action :
      Site.FinitePosetCechSimplicialFaceAction
        (geometry.toObstructionCoefficientRegime Ob)) :
    TwoFaceRestrictionMapLaw geometry Ob action.toFaceData where
  twoFace_simplex_eq := by
    intro n simplex i j hle
    exact action.twoFace_simplex_eq n simplex i j hle

/-- X.R1(a): paired signed double-face terms cancel. -/
theorem standardSignedDoubleFaceTerm_pair_cancel
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (i j : Fin (n + 2))
    (hterm : TwoFaceTermEquality faces n cochain simplex i j) :
    standardSignedDoubleFaceTerm faces n cochain simplex j.succ i +
        standardSignedDoubleFaceTerm faces n cochain simplex i.castSucc j =
      (standardAdditiveData geometry Ob).zeroSection (n + 2) simplex := by
  letI :=
    Ob.addCommGroup
      (Site.FinitePosetCechOverlapObject
        (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
  change
    standardSignedDoubleFaceTerm faces n cochain simplex j.succ i +
        standardSignedDoubleFaceTerm faces n cochain simplex i.castSucc j = 0
  dsimp [TwoFaceTermEquality] at hterm
  dsimp [standardSignedDoubleFaceTerm]
  rw [hterm]
  by_cases hi : Even i.val
  · by_cases hj : Even j.val
    · simp [hi, hj, Nat.even_add_one]
    · simp [hi, hj, Nat.even_add_one]
  · by_cases hj : Even j.val
    · simp [hi, hj, Nat.even_add_one]
    · simp [hi, hj, Nat.even_add_one]

/-- X.R1(a): lower two-face law generates signed-pair cancellation. -/
theorem standardSignedDoubleFaceTerm_pair_cancel_of_twoFaceRestrictionMapLaw
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : TwoFaceRestrictionMapLaw geometry Ob faces)
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (i j : Fin (n + 2)) (hle : i ≤ j) :
    standardSignedDoubleFaceTerm faces n cochain simplex j.succ i +
        standardSignedDoubleFaceTerm faces n cochain simplex i.castSucc j =
      (standardAdditiveData geometry Ob).zeroSection (n + 2) simplex :=
  standardSignedDoubleFaceTerm_pair_cancel
    faces n cochain simplex i j
    (law.toTwoFaceTermEquality n cochain simplex i j hle)

/-- X.R1(a): simplicial face action generates signed-pair cancellation. -/
theorem standardSignedDoubleFaceTerm_pair_cancel_of_simplicialFaceAction
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (action :
      Site.FinitePosetCechSimplicialFaceAction
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (i j : Fin (n + 2)) (hle : i ≤ j) :
    standardSignedDoubleFaceTerm action.toFaceData n cochain simplex j.succ i +
        standardSignedDoubleFaceTerm action.toFaceData n cochain simplex i.castSucc j =
      (standardAdditiveData geometry Ob).zeroSection (n + 2) simplex :=
  standardSignedDoubleFaceTerm_pair_cancel_of_twoFaceRestrictionMapLaw
    (twoFaceRestrictionMapLawOfSimplicialFaceAction
      (geometry := geometry) (Ob := Ob) action)
    n cochain simplex i j hle

/-- X.R1(a): triangular pair sum cancels for a generated simplicial action. -/
theorem standardTriangularDoubleFacePairSum_eq_zero_of_simplicialFaceAction
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (action :
      Site.FinitePosetCechSimplicialFaceAction
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2)) :
    standardTriangularDoubleFacePairSum
        action.toFaceData n cochain simplex =
      (standardAdditiveData geometry Ob).zeroSection (n + 2) simplex := by
  letI :=
    Ob.addCommGroup
      (Site.FinitePosetCechOverlapObject
        (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
  change standardTriangularDoubleFacePairSum action.toFaceData n cochain simplex = 0
  dsimp [standardTriangularDoubleFacePairSum]
  refine Finset.sum_eq_zero ?_
  intro i _hi_mem
  refine Finset.sum_eq_zero ?_
  intro j hj_mem
  have hle : i ≤ j := (Finset.mem_filter.mp hj_mem).2
  exact
    standardSignedDoubleFaceTerm_pair_cancel_of_simplicialFaceAction
      action n cochain simplex i j hle

/--
X.R1(a): one outer face restriction of the standard differential expands to the
inner double alternating sum.
-/
theorem faceRestriction_standardDifferential_eq_innerDoubleAlternating
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2))
    (outer : Fin (n + 3)) :
    Site.FinitePosetCechFaceRestriction faces
        (standardDifferential faces n cochain) simplex outer =
      obstructionSheafStandardAlternatingCombination Ob
        (Site.FinitePosetCechOverlapObject
          (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
        (n + 2)
        (fun inner =>
          standardDoubleFaceRestriction faces n cochain simplex outer inner) := by
  let outerSimplex := faces.face (n + 1) simplex outer
  change
    Ob.carrier.toPresheaf.map
        (homOfLE (faces.faceOverlap_le (n + 1) simplex outer)).op
      (standardDifferential faces n cochain outerSimplex) =
      obstructionSheafStandardAlternatingCombination Ob
        (Site.FinitePosetCechOverlapObject
          (geometry.toObstructionCoefficientRegime Ob) (n + 2) simplex)
        (n + 2)
        (fun inner =>
          standardDoubleFaceRestriction faces n cochain simplex outer inner)
  dsimp [standardDifferential, standardAdditiveData]
  exact
    obstructionSheafStandardAlternatingCombination_map Ob
      (homOfLE (faces.faceOverlap_le (n + 1) simplex outer)) (n + 2)
      (fun inner =>
        Site.FinitePosetCechFaceRestriction faces cochain outerSimplex inner)

/-- X.R1(a): the second generated differential is the double alternating sum. -/
theorem secondDifferential_eq_doubleAlternatingFaceCombination
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob))
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 2)) :
    standardDifferential faces (n + 1)
        (standardDifferential faces n cochain) simplex =
      standardDoubleAlternatingFaceCombination faces n cochain simplex := by
  dsimp [standardDifferential, standardDoubleAlternatingFaceCombination,
    standardAdditiveData]
  congr
  funext outer
  exact
    faceRestriction_standardDifferential_eq_innerDoubleAlternating
      faces n cochain simplex outer

/--
X.R1(a): standard `d ∘ d = 0` law for a generated or selected face action.

This law is consumed by the existing `FinitePosetCechComplex` signature. The
canonical tuple route below generates it from double-face cancellation rather
than taking it as the final completion certificate.
-/
structure StandardDifferentialCompLaw
    (geometry : Site.FinitePosetCoverGeometry S)
    (Ob : ObstructionSheaf S)
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)) where
  differential_comp_zero :
    ∀ (n : Nat)
      (cochain :
        Site.FinitePosetCechCochain
          (geometry.toObstructionCoefficientRegime Ob) n),
      standardDifferential faces (n + 1)
          (standardDifferential faces n cochain) =
        Site.FinitePosetCechZeroCochain
          (standardAdditiveData geometry Ob) (n + 2)

/-- X.R1(a): explicit double-face cancellation law below `d ∘ d = 0`. -/
structure DoubleFaceCancellationLaw
    (geometry : Site.FinitePosetCoverGeometry S)
    (Ob : ObstructionSheaf S)
    (faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)) where
  doubleFace_cancellation :
    ∀ (n : Nat)
      (cochain :
        Site.FinitePosetCechCochain
          (geometry.toObstructionCoefficientRegime Ob) n)
      (simplex :
        Site.FinitePosetCechSimplex
          (geometry.toObstructionCoefficientRegime Ob) (n + 2)),
      standardDoubleAlternatingFaceCombination faces n cochain simplex =
        (standardAdditiveData geometry Ob).zeroSection (n + 2) simplex

namespace DoubleFaceCancellationLaw

/-- X.R1(a): double-face cancellation generates the standard `d ∘ d = 0` law. -/
def toStandardDifferentialCompLaw
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : DoubleFaceCancellationLaw geometry Ob faces) :
    StandardDifferentialCompLaw geometry Ob faces where
  differential_comp_zero := by
    intro n cochain
    funext simplex
    rw [secondDifferential_eq_doubleAlternatingFaceCombination]
    exact law.doubleFace_cancellation n cochain simplex

end DoubleFaceCancellationLaw

/-- X.R1(a): a simplicial face action generates double-face cancellation. -/
def doubleFaceCancellationLawOfSimplicialFaceAction
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    (action :
      Site.FinitePosetCechSimplicialFaceAction
        (geometry.toObstructionCoefficientRegime Ob)) :
    DoubleFaceCancellationLaw geometry Ob action.toFaceData where
  doubleFace_cancellation := by
    intro n cochain simplex
    rw [standardDoubleAlternatingFaceCombination_eq_triangularPairSum]
    exact
      standardTriangularDoubleFacePairSum_eq_zero_of_simplicialFaceAction
        action n cochain simplex

/--
X.R1(a): build the selected finite-poset Cech complex from the standard
additive data, standard face-restriction differential, and the standard
`d ∘ d = 0` proof object.
-/
def standardFinitePosetCechComplex
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : StandardDifferentialCompLaw geometry Ob faces) :
    Site.FinitePosetCechComplex
      (geometry.toObstructionCoefficientRegime Ob) where
  additive := standardAdditiveData geometry Ob
  faces := faces
  differential := standardDifferential faces
  differential_eq_restrictions := by
    intro n cochain simplex
    rfl
  differential_zero := standardDifferential_zero faces
  differential_comp_zero := law.differential_comp_zero

/-- X.R1(a): the standard complex uses the generated standard additive data. -/
theorem standardFinitePosetCechComplex_additive
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : StandardDifferentialCompLaw geometry Ob faces) :
    (standardFinitePosetCechComplex law).additive =
      standardAdditiveData geometry Ob :=
  rfl

/-- X.R1(a): the standard complex differential is the standard differential. -/
theorem standardFinitePosetCechComplex_differential
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : StandardDifferentialCompLaw geometry Ob faces)
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n) :
    (standardFinitePosetCechComplex law).differential n cochain =
      standardDifferential faces n cochain :=
  rfl

/--
X.R1(a) / II.命題7.2C: the standard complex satisfies the existing
face-restriction presentation used by the finite-poset Cech surface.
-/
theorem standardFinitePosetCechComplex_differential_from_restrictions
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : StandardDifferentialCompLaw geometry Ob faces)
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (geometry.toObstructionCoefficientRegime Ob) (n + 1)) :
    (standardFinitePosetCechComplex law).differential n cochain simplex =
      (standardFinitePosetCechComplex law).additive.combineFaces n simplex
        (fun i =>
          Site.FinitePosetCechFaceRestriction
            (standardFinitePosetCechComplex law).faces cochain simplex i) :=
  Site.FinitePosetCechComplex.differential_from_restrictions
    (standardFinitePosetCechComplex law) n cochain simplex

/--
X.R1(a) / II.命題7.2C: the standard complex has `d ∘ d = 0` through
the generated standard differential law, not through a free final theorem.
-/
theorem standardFinitePosetCechComplex_differential_comp
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : StandardDifferentialCompLaw geometry Ob faces)
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (geometry.toObstructionCoefficientRegime Ob) n) :
    (standardFinitePosetCechComplex law).differential (n + 1)
        ((standardFinitePosetCechComplex law).differential n cochain) =
      Site.FinitePosetCechZeroCochain
        (standardFinitePosetCechComplex law).additive (n + 2) :=
  Site.FinitePosetCechComplex.differential_comp
    (standardFinitePosetCechComplex law) n cochain

/--
X.R1(a) / II.命題7.2C: the existing finite-poset high-degree vanishing theorem
applies to the standard complex route.
-/
theorem standardFinitePosetCechComplex_cohomology_vanishes_above_nerveDimension
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : StandardDifferentialCompLaw geometry Ob faces)
    {d n : Nat}
    (R :
      Site.FinitePosetCechCoboundaryRelation
        (standardFinitePosetCechComplex law) n)
    (hdim :
      Site.FinitePosetNerveDimension
        (geometry.toObstructionCoefficientRegime Ob) d)
    (hn : d < n) :
    Site.FinitePosetCechCohomologyVanishes
      (standardFinitePosetCechComplex law) n R :=
  Site.finitePosetCechCohomology_vanishes_above_nerveDimension
    (standardFinitePosetCechComplex law) R hdim hn

/--
X.R1(a): generated cover-relative cover from the standard finite-poset route.

The additive cover-relative complex requires the semantic-free cochain
comparison/H1 layer of R1(c), so this R1(a)(b) route stops at the selected
cover and the finite-poset complex.
-/
def standardCoverRelativeCechCover
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : StandardDifferentialCompLaw geometry Ob faces) :
    CoverRelativeCechCover S :=
  finitePosetCoverRelativeCover (standardFinitePosetCechComplex law)

/-- X.R1(a): the generated cover-relative cover has the original base. -/
theorem standardCoverRelativeCechCover_base
    {geometry : Site.FinitePosetCoverGeometry S}
    {Ob : ObstructionSheaf S}
    {faces :
      Site.FinitePosetCechFaceData
        (geometry.toObstructionCoefficientRegime Ob)}
    (law : StandardDifferentialCompLaw geometry Ob faces) :
    (standardCoverRelativeCechCover law).base = geometry.base :=
  rfl

/-! ## Canonical tuple generated standard complex -/

/--
X.R1(a): canonical tuple geometry generates the standard `d ∘ d = 0` law.

The input is the coefficient-free canonical tuple cover geometry and the
obstruction sheaf. No `d ∘ d = 0` proof object is supplied.
-/
def canonicalTupleStandardDifferentialCompLaw
    {geometry : Site.FinitePosetCoverGeometry S}
    (tupleGeometry : Site.FinitePosetCanonicalTupleCoverGeometry geometry)
    (Ob : ObstructionSheaf S) :
    StandardDifferentialCompLaw tupleGeometry.toCoverGeometry Ob
      ((tupleGeometry.toSimplicialFaceAction Ob.carrier.toPresheaf).toFaceData) :=
  (doubleFaceCancellationLawOfSimplicialFaceAction
    (geometry := tupleGeometry.toCoverGeometry) (Ob := Ob)
    (tupleGeometry.toSimplicialFaceAction Ob.carrier.toPresheaf)).toStandardDifferentialCompLaw

/--
X.R1(a): canonical tuple geometry generates the standard finite-poset Cech
complex end-to-end.

The selected face action, standard alternating differential, and `d ∘ d = 0`
law are generated from the tuple nerve route.
-/
def canonicalTupleStandardFinitePosetCechComplex
    {geometry : Site.FinitePosetCoverGeometry S}
    (tupleGeometry : Site.FinitePosetCanonicalTupleCoverGeometry geometry)
    (Ob : ObstructionSheaf S) :
    Site.FinitePosetCechComplex
      (tupleGeometry.toCoverGeometry.toObstructionCoefficientRegime Ob) :=
  standardFinitePosetCechComplex
    (canonicalTupleStandardDifferentialCompLaw tupleGeometry Ob)

/-- X.R1(a): the canonical tuple standard complex uses standard additive data. -/
theorem canonicalTupleStandardFinitePosetCechComplex_additive
    {geometry : Site.FinitePosetCoverGeometry S}
    (tupleGeometry : Site.FinitePosetCanonicalTupleCoverGeometry geometry)
    (Ob : ObstructionSheaf S) :
    (canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob).additive =
      standardAdditiveData tupleGeometry.toCoverGeometry Ob :=
  rfl

/--
X.R1(a) / II.命題7.2C: the canonical tuple route generates the existing
face-restriction presentation.
-/
theorem canonicalTupleStandardFinitePosetCechComplex_differential_from_restrictions
    {geometry : Site.FinitePosetCoverGeometry S}
    (tupleGeometry : Site.FinitePosetCanonicalTupleCoverGeometry geometry)
    (Ob : ObstructionSheaf S)
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (tupleGeometry.toCoverGeometry.toObstructionCoefficientRegime Ob) n)
    (simplex :
      Site.FinitePosetCechSimplex
        (tupleGeometry.toCoverGeometry.toObstructionCoefficientRegime Ob) (n + 1)) :
    (canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob).differential
        n cochain simplex =
      (canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob).additive.combineFaces
        n simplex
        (fun i =>
          Site.FinitePosetCechFaceRestriction
            (canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob).faces
            cochain simplex i) :=
  standardFinitePosetCechComplex_differential_from_restrictions
    (canonicalTupleStandardDifferentialCompLaw tupleGeometry Ob)
    n cochain simplex

/--
X.R1(a) / II.命題7.2C: the canonical tuple route proves `d ∘ d = 0` by
simplicial double-face cancellation.
-/
theorem canonicalTupleStandardFinitePosetCechComplex_differential_comp
    {geometry : Site.FinitePosetCoverGeometry S}
    (tupleGeometry : Site.FinitePosetCanonicalTupleCoverGeometry geometry)
    (Ob : ObstructionSheaf S)
    (n : Nat)
    (cochain :
      Site.FinitePosetCechCochain
        (tupleGeometry.toCoverGeometry.toObstructionCoefficientRegime Ob) n) :
    (canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob).differential
        (n + 1)
        ((canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob).differential
          n cochain) =
      Site.FinitePosetCechZeroCochain
        (canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob).additive
        (n + 2) :=
  standardFinitePosetCechComplex_differential_comp
    (canonicalTupleStandardDifferentialCompLaw tupleGeometry Ob) n cochain

/--
X.R1(a) / II.命題7.2C: when the generated tuple-regime has a finite nerve
dimension bound, the standard finite-poset cohomology quotient vanishes above
that bound.
-/
theorem canonicalTupleStandardFinitePosetCechComplex_cohomology_vanishes_above_nerveDimension
    {geometry : Site.FinitePosetCoverGeometry S}
    (tupleGeometry : Site.FinitePosetCanonicalTupleCoverGeometry geometry)
    (Ob : ObstructionSheaf S)
    {d n : Nat}
    (R :
      Site.FinitePosetCechCoboundaryRelation
        (canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob) n)
    (hdim :
      Site.FinitePosetNerveDimension
        (tupleGeometry.toCoverGeometry.toObstructionCoefficientRegime Ob) d)
    (hn : d < n) :
    Site.FinitePosetCechCohomologyVanishes
      (canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob) n R :=
  standardFinitePosetCechComplex_cohomology_vanishes_above_nerveDimension
    (canonicalTupleStandardDifferentialCompLaw tupleGeometry Ob) R hdim hn

/--
X.R1(a): canonical tuple geometry generates the corresponding cover-relative
Cech cover.
-/
def canonicalTupleStandardCoverRelativeCechCover
    {geometry : Site.FinitePosetCoverGeometry S}
    (tupleGeometry : Site.FinitePosetCanonicalTupleCoverGeometry geometry)
    (Ob : ObstructionSheaf S) :
    CoverRelativeCechCover S :=
  finitePosetCoverRelativeCover
    (canonicalTupleStandardFinitePosetCechComplex tupleGeometry Ob)

/-- X.R1(a): the generated cover-relative cover keeps the original base. -/
theorem canonicalTupleStandardCoverRelativeCechCover_base
    {geometry : Site.FinitePosetCoverGeometry S}
    (tupleGeometry : Site.FinitePosetCanonicalTupleCoverGeometry geometry)
    (Ob : ObstructionSheaf S) :
    (canonicalTupleStandardCoverRelativeCechCover tupleGeometry Ob).base =
      geometry.base :=
  rfl

end StandardFinitePosetCech

end Cohomology
end AAT.AG
