import ResearchLean.AG.ProtocolHolonomy.FiniteSelectedWalks
import Formal.Util.AssertStandardAxioms

/-!
# Terminating path search in the selected original named graph

Enumerate selected graph walks below the finite vertex count. A reachable
pair has a simple walk in that bound; the list head therefore gives a
concrete selected walk. Resolve its steps against the explicit original
edge table to return a named signed path with its selected-name proof.
-/

namespace AAT.AG.ProtocolHolonomy

open AAT.AG.RealizationReconstruction

universe u v

/-- Selected walks of exactly `n` steps, generated by finite vertex and
adjacency decisions. -/
def finiteSelectedWalksExact
    (Q : FixedFDirectedMultigraph.{u, v})
    [DecidableEq Q.Vertex] [DecidableEq Q.Edge]
    (vertices : ExplicitEnumeration Q.Vertex)
    (selected : Finset Q.Edge)
    (a b : Q.Vertex) : (n : Nat) →
    List ((selectedReachabilityGraph Q selected).Walk a b)
  | 0 => if h : a = b then [h ▸ SimpleGraph.Walk.nil] else []
  | n + 1 => by
      letI : DecidableRel (selectedReachabilityGraph Q selected).Adj :=
        selectedAdjDecidable Q selected
      exact vertices.values.flatMap fun y =>
        if h : (selectedReachabilityGraph Q selected).Adj a y then
          (finiteSelectedWalksExact Q vertices selected y b n).map
            (SimpleGraph.Walk.cons h)
        else []

/-- Every concrete selected walk appears at its own length. -/
theorem mem_finiteSelectedWalksExact
    (Q : FixedFDirectedMultigraph.{u, v})
    [DecidableEq Q.Vertex] [DecidableEq Q.Edge]
    (vertices : ExplicitEnumeration Q.Vertex)
    (selected : Finset Q.Edge)
    {a b : Q.Vertex}
    (p : (selectedReachabilityGraph Q selected).Walk a b) :
    p ∈ finiteSelectedWalksExact Q vertices selected a b p.length := by
  induction p with
  | nil => simp [finiteSelectedWalksExact]
  | cons h p ih =>
      rename_i x y z
      letI : DecidableRel (selectedReachabilityGraph Q selected).Adj :=
        selectedAdjDecidable Q selected
      simp only [SimpleGraph.Walk.length_cons]
      unfold finiteSelectedWalksExact
      apply List.mem_flatMap.mpr
      refine ⟨y, vertices.complete y, ?_⟩
      simp [h, ih]

/-- All selected walks shorter than the finite vertex count. -/
def finiteSelectedBoundedWalks
    (Q : FixedFDirectedMultigraph.{u, v})
    [DecidableEq Q.Vertex] [DecidableEq Q.Edge]
    (vertices : ExplicitEnumeration Q.Vertex)
    (selected : Finset Q.Edge)
    (a b : Q.Vertex) :
    List ((selectedReachabilityGraph Q selected).Walk a b) := by
  letI : Fintype Q.Vertex := vertices.toFintype
  exact (List.range (Fintype.card Q.Vertex)).flatMap
    (finiteSelectedWalksExact Q vertices selected a b)

/-- Given selected connectivity, compute an actual signed path using only
the selected original names. The proof eliminates an impossible empty list;
the returned value is the finite list head and explicit edge-table scan. -/
def finiteSelectedNamedPathOfReachable
    (Q : FixedFDirectedMultigraph.{u, v})
    [DecidableEq Q.Vertex] [DecidableEq Q.Edge]
    (vertices : ExplicitEnumeration Q.Vertex)
    (edges : ExplicitEnumeration Q.Edge)
    (selected : Finset Q.Edge)
    {a b : Q.Vertex} (h : SelectedNamedReachable Q selected a b) :
    {p : SignedPath Q a b // UsesNamedEdges (fun e => e ∈ selected) p} := by
  letI : Fintype Q.Vertex := vertices.toFintype
  letI : DecidableRel (selectedReachabilityGraph Q selected).Adj :=
    selectedAdjDecidable Q selected
  let G := selectedReachabilityGraph Q selected
  let paths : List (G.Walk a b) :=
    finiteSelectedBoundedWalks Q vertices selected a b
  have hne : paths ≠ [] := by
    intro hempty
    have hr : G.Reachable a b :=
      (selectedReachable_iff_named Q selected a b).mpr h
    have hp : Nonempty (G.Path a b) := hr.elim_path (fun p => ⟨p⟩)
    obtain ⟨p⟩ := hp
    have hmem : p.1 ∈ paths := by
      unfold paths finiteSelectedBoundedWalks
      apply List.mem_flatMap.mpr
      refine ⟨p.1.length, List.mem_range.mpr p.2.length_lt, ?_⟩
      exact mem_finiteSelectedWalksExact Q vertices selected p.1
    simp [hempty] at hmem
  exact selectedSignedPathOfWalk Q selected edges (paths.head hne)

end AAT.AG.ProtocolHolonomy

#print axioms AAT.AG.ProtocolHolonomy.finiteSelectedWalksExact
#print axioms AAT.AG.ProtocolHolonomy.mem_finiteSelectedWalksExact
#print axioms AAT.AG.ProtocolHolonomy.finiteSelectedBoundedWalks
#print axioms AAT.AG.ProtocolHolonomy.finiteSelectedNamedPathOfReachable

private def selectedPathSmokeQ :
    AAT.AG.RealizationReconstruction.FixedFDirectedMultigraph.{0, 0} where
  Vertex := Bool
  Edge := Bool
  source := fun _ => false
  target := fun _ => true

private def selectedPathSmokeVertices :
    AAT.AG.ProtocolHolonomy.ExplicitEnumeration selectedPathSmokeQ.Vertex where
  values := [false, true]
  complete := by intro x; cases x <;> simp

private def selectedPathSmokeEdges :
    AAT.AG.ProtocolHolonomy.ExplicitEnumeration selectedPathSmokeQ.Edge where
  values := [false, true]
  complete := by intro x; cases x <;> simp

#eval (letI : DecidableEq selectedPathSmokeQ.Vertex := inferInstanceAs (DecidableEq Bool)
  letI : DecidableEq selectedPathSmokeQ.Edge := inferInstanceAs (DecidableEq Bool)
  letI : Quiver selectedPathSmokeQ.Vertex :=
    AAT.AG.ProtocolHolonomy.typedQuiver selectedPathSmokeQ
  letI : Quiver (Quiver.Symmetrify selectedPathSmokeQ.Vertex) :=
    Quiver.symmetrifyQuiver selectedPathSmokeQ.Vertex
  let h : AAT.AG.ProtocolHolonomy.SelectedNamedReachable
      selectedPathSmokeQ {false} false true :=
    Relation.EqvGen.rel _ _ ⟨false, by simp, rfl, rfl⟩
  (AAT.AG.ProtocolHolonomy.finiteSelectedNamedPathOfReachable
    selectedPathSmokeQ selectedPathSmokeVertices selectedPathSmokeEdges
      {false} h).1.length)

#assert_standard_axioms_only AAT.AG.ProtocolHolonomy
