import ResearchLean.AG.ProtocolHolonomy.FiniteVerticalLifts
import ResearchLean.AG.ProtocolHolonomy.FiniteLiftableVisible
import ResearchLean.AG.ProtocolHolonomy.LiftFiberTorsor
import Formal.Util.AssertStandardAxioms

/-!
# All lifts over a finite visible change

One successful input-generated C1 search returns an original A1 lift.
Compose it on the right with every vertical lift generated by the finite
B2 centralizer tables. The resulting list exhausts the original lift fiber.
The right-composition code uses the original vertexwise maps and edge square;
the already-proved C3 torsor establishes completeness.
-/

namespace AAT.AG.ProtocolHolonomy

open AAT.AG.RealizationReconstruction

universe u v w

namespace ReversibleData

variable {Q : FixedFDirectedMultigraph.{u, v}}
    (D : ReversibleData.{u, v, w} Q)

/-- Computable pointwise right composition with a vertical A1 change. -/
def composeVertical (g : FixedFGraphAutomorphism Q)
    (a : D.Lift g) (α : D.Lift (1 : FixedFGraphAutomorphism Q)) : D.Lift g where
  fiber v := (α.fiber v).trans (a.fiber v)
  edge_naturality := by
    intro e x
    have hα := α.edge_naturality e x
    have ha := a.edge_naturality e (α.fiber (Q.source e) x)
    change (α.fiber (Q.target e)) (D.edgeEquiv e x) =
      D.edgeEquiv e (α.fiber (Q.source e) x) at hα
    change (a.fiber (Q.target e))
      (D.edgeEquiv e (α.fiber (Q.source e) x)) =
        D.renamedEdgeEquiv g e
          (a.fiber (Q.source e) (α.fiber (Q.source e) x)) at ha
    simpa only [Equiv.trans_apply] using
      (congrArg (a.fiber (Q.target e)) hα).trans ha

/-- The executable composition is the original C3 right torsor action. -/
theorem composeVertical_eq_rightAction
    (H : Subgroup (FixedFGraphAutomorphism Q))
    (g : D.LiftableVisible H) (a : D.Lift g.1.1)
    (α : D.Lift (1 : FixedFGraphAutomorphism Q)) :
    D.composeVertical g.1.1 a α = D.verticalRightAction H g a α := by
  apply Lift.ext
  intro v x
  exact (D.verticalRightAction_fiber_apply H g a α v x).symm

section Finite

variable [DecidableEq Q.Vertex] [DecidableEq Q.Edge]
    [∀ x : Q.Vertex, DecidableEq (D.Fiber x)]

/-- If the C1 search succeeds, produce the complete original A1 lift fiber
by acting with every finite B2 vertical lift. -/
def finiteAllLifts (g : FixedFGraphAutomorphism Q)
    (vertices : ExplicitEnumeration Q.Vertex)
    (edges : ExplicitEnumeration Q.Edge)
    (fibers : ∀ x, ExplicitEnumeration (D.Fiber x)) :
    List (D.Lift g) :=
  match D.findFiniteRootLift g vertices edges fibers with
  | none => []
  | some a =>
      (D.finiteVerticalLifts vertices edges fibers).values.map
        (D.composeVertical g a)

/-- The finite C1/B2 procedure lists every original lift in either branch. -/
theorem mem_finiteAllLifts (g : FixedFGraphAutomorphism Q)
    (vertices : ExplicitEnumeration Q.Vertex)
    (edges : ExplicitEnumeration Q.Edge)
    (fibers : ∀ x, ExplicitEnumeration (D.Fiber x))
    (b : D.Lift g) :
    b ∈ D.finiteAllLifts g vertices edges fibers := by
  have hsuccess := (D.findFiniteRootLift_isSome_iff g vertices edges fibers).mpr ⟨b⟩
  cases hfind : D.findFiniteRootLift g vertices edges fibers with
  | none => simp [hfind] at hsuccess
  | some a =>
      let H : Subgroup (FixedFGraphAutomorphism Q) := ⊤
      let g' : D.LiftableVisible H := ⟨⟨g, trivial⟩,
        (D.mem_liftableVisible_iff_lift H ⟨g, trivial⟩).mpr ⟨a⟩⟩
      obtain ⟨α, hα⟩ := D.verticalRightAction_transitive H g' a b
      have hcomp : D.composeVertical g a α = b := by
        rw [D.composeVertical_eq_rightAction H g' a α]
        exact hα
      unfold finiteAllLifts
      rw [hfind]
      apply List.mem_map.mpr
      exact ⟨α, (D.finiteVerticalLifts vertices edges fibers).complete α, hcomp⟩

/-- The output list is empty exactly when the original A1 lift fiber is
empty; a nonempty output contains every possible lift, not just one. -/
theorem finiteAllLifts_eq_nil_iff (g : FixedFGraphAutomorphism Q)
    (vertices : ExplicitEnumeration Q.Vertex)
    (edges : ExplicitEnumeration Q.Edge)
    (fibers : ∀ x, ExplicitEnumeration (D.Fiber x)) :
    D.finiteAllLifts g vertices edges fibers = [] ↔ IsEmpty (D.Lift g) := by
  constructor
  · intro h
    constructor
    intro a
    have hm := D.mem_finiteAllLifts g vertices edges fibers a
    simp [h] at hm
  · intro h
    cases hs : D.finiteAllLifts g vertices edges fibers with
    | nil => rfl
    | cons a rest => exact (h.false a).elim

end Finite
end ReversibleData
end AAT.AG.ProtocolHolonomy

#print axioms AAT.AG.ProtocolHolonomy.ReversibleData.composeVertical
#print axioms AAT.AG.ProtocolHolonomy.ReversibleData.composeVertical_eq_rightAction
#print axioms AAT.AG.ProtocolHolonomy.ReversibleData.finiteAllLifts
#print axioms AAT.AG.ProtocolHolonomy.ReversibleData.mem_finiteAllLifts
#print axioms AAT.AG.ProtocolHolonomy.ReversibleData.finiteAllLifts_eq_nil_iff
#assert_standard_axioms_only AAT.AG.ProtocolHolonomy
