import ResearchLean.AG.ProtocolHolonomy.PathEquations
import ResearchLean.AG.RealizationReconstruction.ProtocolSemantics
import Mathlib.Combinatorics.Quiver.Prefunctor
import Formal.Util.AssertStandardAxioms

/-!
# Original reversible input in the independent protocol schema

All three original universe levels are retained. `ULift` changes only the
coordinates needed by the existing single-universe execution category.
Original vertices, named edges, equations, and fiber values have explicit
down maps, so no extra operation or equation data is supplied.
-/

namespace AAT.AG.ProtocolHolonomy

open AAT.AG.RealizationReconstruction CategoryTheory

universe u v w

/-- Original typed named edges with only a universe change. -/
abbrev LiftedEdge (Q : FixedFDirectedMultigraph.{u, v})
    (a b : ULift.{max v w} Q.Vertex) :=
  ULift.{max u w} (TypedEdge Q a.down b.down)

instance liftedQuiver (Q : FixedFDirectedMultigraph.{u, v}) :
    Quiver (ULift.{max v w} Q.Vertex) where
  Hom := LiftedEdge Q

/-- Embed each original directed path, preserving every named edge. -/
def upPrefunctor (Q : FixedFDirectedMultigraph.{u, v}) :
    @Prefunctor Q.Vertex (typedQuiver Q)
      (ULift.{max v w} Q.Vertex) (liftedQuiver Q) := by
  letI : Quiver Q.Vertex := typedQuiver Q
  exact { obj x := ULift.up x
          map e := ULift.up e }

/-- Embed an original positive path in the universe-lifted schema. -/
def upPath (Q : FixedFDirectedMultigraph.{u, v})
    {s t : Q.Vertex} (p : PositivePath Q s t) :
    @Quiver.Path (ULift.{max v w} Q.Vertex) (liftedQuiver Q)
      (ULift.up s) (ULift.up t) := by
  letI : Quiver Q.Vertex := typedQuiver Q
  exact (upPrefunctor Q).mapPath p

/-- The original finite input as the independent finite protocol schema.
The relation family is exactly the original Π. -/
def FiniteProtocolInput.schema {Q : FixedFDirectedMultigraph.{u, v}}
    (P : FiniteProtocolInput.{u, v, w} Q) :
    ProtocolSchema.{max u v w} := by
  letI : Finite Q.Vertex := P.finiteVertex
  letI : Finite Q.Edge := P.finiteEdge
  letI : Quiver Q.Vertex := typedQuiver Q
  exact {
  Vertex := ULift.{max v w} Q.Vertex
  vertex_finite := inferInstance
  Edge := LiftedEdge Q
  edge_finite := fun _ _ => inferInstance
  RelationIndex := ULift.{w} P.equations.Index
  relation_finite := inferInstance
  relationSource r := ULift.up (P.equations.source r.down)
  relationTarget r := ULift.up (P.equations.target r.down)
  relationLeft r := upPath Q (P.equations.left r.down)
  relationRight r := upPath Q (P.equations.right r.down)
  }

namespace FiniteProtocolInput

variable {Q : FixedFDirectedMultigraph.{u, v}}
  (P : FiniteProtocolInput.{u, v, w} Q)

/-- The original fiber at each lifted vertex, with unchanged elements. -/
abbrev schemaFiber (a : P.schema.Vertex) :=
  ULift.{max u v} (P.data.Fiber a.down)

/-- Action of an original named edge, with its original forward table. -/
def schemaEdgeAction {a b : P.schema.Vertex} (e : P.schema.Edge a b) :
    P.schemaFiber a → P.schemaFiber b :=
  fun x => ULift.up (P.data.typedEdgeEquiv e.down x.down)

/-- The free-path semantics generated by the original edge equivalences. -/
def pathFunctor : Paths P.schema.Vertex ⥤ Type (max u v w) :=
  P.schema.pathFunctorOfEdgeAction P.schemaFiber (P.schemaEdgeAction)

/-- On a path of original named edges, the generated semantics evaluates
to the original composite of reversible operations, element by element. -/
theorem pathFunctor_map_up {s t : Q.Vertex}
    (p : PositivePath Q s t) (x : P.data.Fiber s) :
    ((P.pathFunctor.map (upPath Q p))
      (ULift.up x : P.schemaFiber (ULift.up s))).down =
        P.data.positiveTransport p x := by
  letI : Quiver Q.Vertex := typedQuiver Q
  induction p with
  | nil => rfl
  | cons p e ih =>
      change P.data.typedEdgeEquiv e
        (((P.pathFunctor.map (upPath Q p))
          (ULift.up x : P.schemaFiber (ULift.up s))).down) = _
      rw [ih]
      rfl

/-- Every authored original equation is respected by the generated
free-path semantics. This is the relation needed for quotient descent. -/
theorem pathFunctor_relation
    {a b : Paths P.schema.Vertex} (p q : a ⟶ b)
    (h : P.schema.pathRelation p q) :
    P.pathFunctor.map p = P.pathFunctor.map q := by
  obtain ⟨r, hs, ht, hp, hq⟩ := h
  cases hs
  cases ht
  subst p
  subst q
  funext x
  apply ULift.down_injective
  cases x with
  | up y =>
      change (P.pathFunctor.map (upPath Q (P.equations.left r.down))
        (ULift.up y)).down =
        (P.pathFunctor.map (upPath Q (P.equations.right r.down))
          (ULift.up y)).down
      rw [P.pathFunctor_map_up (P.equations.left r.down) y,
        P.pathFunctor_map_up (P.equations.right r.down) y]
      exact congrArg (fun e => e y) (P.satisfies r.down)

/-- The actual functor on the original path-equation quotient. -/
def executionFunctor : P.schema.ExecutionCategory ⥤ Type (max u v w) :=
  CategoryTheory.Quotient.lift P.schema.pathRelation P.pathFunctor
    (fun _ _ p q h => P.pathFunctor_relation p q h)

/-- The specified one-point observation over the execution category. -/
def singletonObservation : P.schema.ExecutionCategory ⥤ Type (max u v w) where
  obj _ := ULift.{max u v w} Unit
  map _ := fun _ => ULift.up ()
  map_id := by intros; rfl
  map_comp := by intros; rfl

/-- Every original state has the same one-point observation. -/
def executionObservation : P.executionFunctor ⟶ P.singletonObservation where
  app _ := fun _ => ULift.up ()
  naturality := by intros; rfl

/-- The independent protocol realization generated by the original
reversible edge operations and path equations. -/
def realization : ProtocolRealization P.schema P.singletonObservation where
  toFunctor := P.executionFunctor
  state_finite := by
    intro x
    change Finite (P.schemaFiber x)
    infer_instance
  observation := P.executionObservation

/-- Reading an original named edge from the independent realization gives
exactly the input edge equivalence on every original state. -/
theorem realization_edgeAction_down {s t : Q.Vertex}
    (e : TypedEdge Q s t) (x : P.data.Fiber s) :
    ((P.realization.edgeAction
      (ULift.up e : P.schema.Edge (ULift.up s) (ULift.up t)))
        (ULift.up x)).down = P.data.typedEdgeEquiv e x := by
  rfl

/-- Reading any original positive execution from the quotient realization
gives its original composite edge action. -/
theorem realization_pathAction_down {s t : Q.Vertex}
    (p : PositivePath Q s t) (x : P.data.Fiber s) :
    ((P.realization.pathAction (upPath Q p)) (ULift.up x)).down =
      P.data.positiveTransport p x := by
  exact P.pathFunctor_map_up p x

end FiniteProtocolInput

end AAT.AG.ProtocolHolonomy

#print axioms AAT.AG.ProtocolHolonomy.FiniteProtocolInput.schema
#print axioms AAT.AG.ProtocolHolonomy.FiniteProtocolInput.pathFunctor_map_up
#print axioms AAT.AG.ProtocolHolonomy.FiniteProtocolInput.pathFunctor_relation
#print axioms AAT.AG.ProtocolHolonomy.FiniteProtocolInput.executionFunctor
#print axioms AAT.AG.ProtocolHolonomy.FiniteProtocolInput.realization
#print axioms AAT.AG.ProtocolHolonomy.FiniteProtocolInput.realization_edgeAction_down
#print axioms AAT.AG.ProtocolHolonomy.FiniteProtocolInput.realization_pathAction_down
#assert_standard_axioms_only AAT.AG.ProtocolHolonomy
