import ResearchLean.AG.AtomFoundation.RefinementObstruction
import ResearchLean.AG.AtomFoundation.RefinementSupply

/-!
# Failure of refinement extension supply in the finite witness

The Cycle 10 target uses a nonempty but uniformly rejecting equation detector.
The source has a concrete positive, matching, accepted three-relation datum.
Any raw supply generating this fixed target would therefore produce a
canonical positive lift whose derived acceptance preservation forces
`false = true`.  The same strict refinement does have the different generated
target constructed in `RefinementSupplyWitness`.
-/

namespace AAT.AG.AtomFoundation

/-- The concrete source cycle datum has only positive polarities. -/
theorem refinementCycleQueryDatum_positive :
    FiniteModel.cycleQueryDatum.Positive := by
  intro query expected hmem
  simp [FiniteModel.cycleQueryDatum] at hmem
  rcases hmem with ⟨_, h⟩ | ⟨_, h⟩ | ⟨_, h⟩ <;> exact h

/-- The positive datum genuinely matches the nondegenerate source object. -/
theorem refinementCycleQueryDatum_matches_source :
    FiniteModel.cycleQueryDatum.Matches refinementSourcePackage.object := by
  simpa [refinementSourcePackage] using FiniteModel.cycleQueryDatum_matches_core

/-- The source detector genuinely accepts the selected positive datum. -/
theorem refinementCycleQueryDatum_accepted_source :
    refinementSourcePackage.algebra.circuits.accepts
      PUnit.unit FiniteModel.cycleQueryDatum = true := by
  simpa [refinementSourcePackage] using FiniteModel.cycleQueryDatum_accepted

/-- Every equation of the fixed refinement target uses the rejecting detector. -/
theorem refinementTargetPackage_circuit_code_reject
    (i : refinementTargetPackage.algebra.equationSystem.Index) :
    refinementTargetPackage.algebra.circuits.code i = .reject := by
  cases i
  rfl

/-- The fixed target rejects every finite datum, independently of its syntax. -/
theorem refinementTargetPackage_accepts_eq_false
    (i : refinementTargetPackage.algebra.equationSystem.Index)
    (datum : FiniteCircuitDatum FiniteModel.carrier) :
    refinementTargetPackage.algebra.circuits.accepts i datum = false :=
  EquationCircuitReading.accepts_eq_false_of_code_reject
    refinementTargetPackage.algebra.circuits i datum
    (refinementTargetPackage_circuit_code_reject i)

/--
The fixed all-reject target cannot be generated by refinement extension supply.

The contradiction uses `accepts_mono` derived on the canonical positive lift:
the source accepts its concrete positive cycle datum, whereas the fixed target
rejects every possible transported query at every equation index.
-/
theorem finiteExtractionRefinement_not_hasExtensionSupply :
    ¬ HasRefinementExtensionSupply refinementSourcePackage
      refinementTargetPackage finiteExtractionRefinement := by
  intro hSupply
  rcases HasRefinementExtensionSupply.lift refinementSourcePackage
      refinementTargetPackage finiteExtractionRefinement hSupply with ⟨F, _hatom⟩
  have haccepts := F.accepts_mono PUnit.unit FiniteModel.cycleQueryDatum
    refinementCycleQueryDatum_positive refinementCycleQueryDatum_accepted_source
  rw [refinementTargetPackage_accepts_eq_false] at haccepts
  contradiction

end AAT.AG.AtomFoundation

#assert_standard_axioms_only AAT.AG.AtomFoundation
