import Formal.AG.SemanticRepair.Projection

noncomputable section

namespace AAT.AG
namespace SemanticRepair

universe u v w x y

/--
X.定義3.1: finite semantic repair-gluing complex.

The projection and finite cover datum are inherited from §2.  `C0` is the
supplied type of local repair primitives, `C1` is the supplied type of residual
gluing cochains, and `delta0` is the supplied restriction-difference map.  The
generated theorem layer below reads the selected residual cochain through the
boundary predicate `B1`; this structure does not assert arbitrary sheaf
cohomology or a global repair certificate by itself.
-/
structure FiniteSemanticRepairGluingComplex where
  projection : SemanticAtomProjection.{u, v}
  cover : FiniteSemanticRepairCoverDatum.{v, w, x} projection.Component
  C0 : Type y
  C1 : Type x
  primitiveFinite : Fintype C0
  cochainFinite : Fintype C1
  supportOf : C0 -> projection.Support
  delta0 : C0 -> C1
  residual : C1

namespace FiniteSemanticRepairGluingComplex

attribute [instance] primitiveFinite cochainFinite

end FiniteSemanticRepairGluingComplex

/--
X.定義3.2: boundary membership `B¹`.

`B1 K cochain` means the cochain is generated by a local primitive through the
finite restriction-difference map `delta0`.
-/
def B1 (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y})
    (cochain : K.C1) : Prop :=
  exists primitive, K.delta0 primitive = cochain

/-- X.定義3.2: the selected finite obstruction class vanishes exactly when it lies in `B¹`. -/
def ObstructionClassVanishes
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y}) : Prop :=
  B1 K K.residual

/-- X.定義3.2: nonzero obstruction is failure of selected boundary membership. -/
def ObstructionClassNonzero
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y}) : Prop :=
  Not (ObstructionClassVanishes K)

/--
X.定義3.2: a primitive is semantically closed when its support closes every
§2 residual atom of the selected finite cover.
-/
def PrimitiveSemanticallyClosed
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y})
    (primitive : K.C0) : Prop :=
  SemanticRepairClosed K.projection K.cover (K.supportOf primitive)

/--
X.定義3.2: global semantic repair coherence.

The generated certificate is a primitive whose `delta0` equals the selected
residual and whose semantic support is closed.
-/
def GlobalSemanticRepairCoherent
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y}) : Prop :=
  exists primitive,
    K.delta0 primitive = K.residual /\
      PrimitiveSemanticallyClosed K primitive

/--
X.定義3.3: semantic faithfulness hypotheses.

These are the supplied semantic conditions required only for the sufficiency
direction: a boundary primitive must have residual-component coverage and
faithfulness back to the actual residual atom.  By X.補題2.5 these two facts
generate semantic closure.
-/
structure SemanticFaithfulnessHypotheses
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y}) where
  component_covered_of_boundary :
    forall primitive,
      K.delta0 primitive = K.residual ->
        ResidualComponentCoveredSupport
          K.projection K.cover (K.supportOf primitive)
  component_faithful_of_boundary :
    forall primitive,
      K.delta0 primitive = K.residual ->
        ResidualComponentFaithfulSupport
          K.projection K.cover (K.supportOf primitive)

/--
X.定理3.4 support lemma: semantic faithfulness turns a boundary primitive into
a closed semantic repair primitive.
-/
theorem primitive_semanticRepairClosed_of_faithful_delta0
    {K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y}}
    (hfaithful : SemanticFaithfulnessHypotheses K)
    {primitive : K.C0}
    (hboundary : K.delta0 primitive = K.residual) :
    PrimitiveSemanticallyClosed K primitive := by
  exact
    (semanticRepairClosed_iff_residualComponentCovered_and_faithful).mpr
      ⟨hfaithful.component_covered_of_boundary primitive hboundary,
        hfaithful.component_faithful_of_boundary primitive hboundary⟩

/-- X.定理3.4(i): global semantic coherence forces obstruction vanishing. -/
theorem globalRepairCoherent_forces_obstructionVanishes
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y}) :
    GlobalSemanticRepairCoherent K -> ObstructionClassVanishes K := by
  intro hglobal
  rcases hglobal with ⟨primitive, hboundary, _hclosed⟩
  exact ⟨primitive, hboundary⟩

/-- X.定理3.4(i), contrapositive: nonzero obstruction rules out global coherence. -/
theorem no_globalRepairCoherent_of_nonzero_obstruction
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y}) :
    ObstructionClassNonzero K -> Not (GlobalSemanticRepairCoherent K) := by
  intro hnonzero hglobal
  exact hnonzero (globalRepairCoherent_forces_obstructionVanishes K hglobal)

/-- X.定理3.4(ii): under semantic faithfulness, vanishing generates global coherence. -/
theorem globalRepairCoherent_of_obstructionVanishes
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y})
    (hfaithful : SemanticFaithfulnessHypotheses K) :
    ObstructionClassVanishes K -> GlobalSemanticRepairCoherent K := by
  intro hvanishes
  rcases hvanishes with ⟨primitive, hboundary⟩
  exact
    ⟨primitive, hboundary,
      primitive_semanticRepairClosed_of_faithful_delta0 hfaithful hboundary⟩

/--
X.定理3.4(iii): finite semantic repair-gluing descent equivalence under
semantic faithfulness hypotheses.
-/
theorem finiteSemanticRepairGluingDescent_iff
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y})
    (hfaithful : SemanticFaithfulnessHypotheses K) :
    GlobalSemanticRepairCoherent K <-> ObstructionClassVanishes K :=
  ⟨globalRepairCoherent_forces_obstructionVanishes K,
    globalRepairCoherent_of_obstructionVanishes K hfaithful⟩

/--
X.定理3.4 package: necessity and nonzero-obstruction exclusion are
unconditional; sufficiency and iff carry exactly the semantic faithfulness
hypotheses.
-/
theorem finiteSemanticRepairGluingDescent_package
    (K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y})
    (hfaithful : SemanticFaithfulnessHypotheses K) :
    (GlobalSemanticRepairCoherent K -> ObstructionClassVanishes K) /\
      (ObstructionClassNonzero K -> Not (GlobalSemanticRepairCoherent K)) /\
      (ObstructionClassVanishes K -> GlobalSemanticRepairCoherent K) /\
      (GlobalSemanticRepairCoherent K <-> ObstructionClassVanishes K) := by
  exact
    ⟨globalRepairCoherent_forces_obstructionVanishes K,
      no_globalRepairCoherent_of_nonzero_obstruction K,
      globalRepairCoherent_of_obstructionVanishes K hfaithful,
      finiteSemanticRepairGluingDescent_iff K hfaithful⟩

/--
X.定理3.5: complete-support boundary class.

Every primitive in the class uses the same complete support, and that complete
support is already semantically closed for the selected cover.  Therefore the
semantic faithfulness hypotheses are generated from X.補題2.5 rather than left
as material premises.
-/
structure CompleteSupportBoundaryComplex where
  K : FiniteSemanticRepairGluingComplex.{u, v, w, x, y}
  completeSupport : K.projection.Support
  support_eq : forall primitive, K.supportOf primitive = completeSupport
  complete_closed : SemanticRepairClosed K.projection K.cover completeSupport

/--
X.定理3.5: a complete-support boundary class discharges
`SemanticFaithfulnessHypotheses`.
-/
theorem completeSupportBoundary_semanticFaithfulnessHypotheses
    (L : CompleteSupportBoundaryComplex.{u, v, w, x, y}) :
    SemanticFaithfulnessHypotheses L.K := by
  have hdecomp :
      ResidualComponentCoveredSupport L.K.projection L.K.cover L.completeSupport /\
        ResidualComponentFaithfulSupport L.K.projection L.K.cover L.completeSupport :=
    (semanticRepairClosed_iff_residualComponentCovered_and_faithful).mp
      L.complete_closed
  constructor
  · intro primitive _hboundary
    simpa [L.support_eq primitive] using hdecomp.1
  · intro primitive _hboundary
    simpa [L.support_eq primitive] using hdecomp.2

/--
X.定理3.5: finite descent equivalence for a complete-support class, with
semantic faithfulness discharged by the class certificate.
-/
theorem finiteSemanticRepairGluingDescent_iff_of_completeSupportBoundary
    (L : CompleteSupportBoundaryComplex.{u, v, w, x, y}) :
    GlobalSemanticRepairCoherent L.K <-> ObstructionClassVanishes L.K :=
  finiteSemanticRepairGluingDescent_iff L.K
    (completeSupportBoundary_semanticFaithfulnessHypotheses L)

/-- X.定理3.5 package for complete-support families. -/
theorem completeSupportBoundary_descent_package
    (L : CompleteSupportBoundaryComplex.{u, v, w, x, y}) :
    SemanticFaithfulnessHypotheses L.K /\
      (GlobalSemanticRepairCoherent L.K -> ObstructionClassVanishes L.K) /\
      (ObstructionClassNonzero L.K -> Not (GlobalSemanticRepairCoherent L.K)) /\
      (ObstructionClassVanishes L.K -> GlobalSemanticRepairCoherent L.K) /\
      (GlobalSemanticRepairCoherent L.K <-> ObstructionClassVanishes L.K) := by
  let hfaithful := completeSupportBoundary_semanticFaithfulnessHypotheses L
  exact
    ⟨hfaithful,
      globalRepairCoherent_forces_obstructionVanishes L.K,
      no_globalRepairCoherent_of_nonzero_obstruction L.K,
      globalRepairCoherent_of_obstructionVanishes L.K hfaithful,
      finiteSemanticRepairGluingDescent_iff_of_completeSupportBoundary L⟩

end SemanticRepair
end AAT.AG
