import Formal.AG.LawAlgebra.LawEquation
import Formal.AG.SemanticRepair.AdditiveH1
import Formal.AG.SemanticRepair.H1Comparison

noncomputable section

namespace AAT.AG
namespace SemanticRepair

open CategoryTheory
open Opposite

universe u v w x y z r

/-! ## X.§7 theorem 7.3 and 7.5 SAGA comparison packages -/

/-! ## Degree-zero law-equation generated source package -/

/-- X.定理8.1: pointwise zero reading for the generated degree-zero cochain. -/
def GeneratedSourceC0PointwiseZero
    {U : AtomCarrier.{u}}
    {A : ArchitectureObject U}
    {S : Site.AATSite.{u} A}
    {G : ArchitecturalEquationSystem S.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G) : Prop :=
  forall i : D.Chart, D.interpret i = 0

/-- X.定理8.1 package: law fulfillment generates only degree-zero zero readings. -/
structure GeneratedSourceC0ZeroPackage
    {U : AtomCarrier.{u}}
    {A : ArchitectureObject U}
    {S : Site.AATSite.{u} A}
    {G : ArchitecturalEquationSystem S.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G) : Type (u + 1) where
  pointwiseZero : GeneratedSourceC0PointwiseZero D

/-- X.定理8.1: displayed law satisfaction gives pointwise zero. -/
theorem displayedRequiredLawsHoldOn_constructs_generatedSourceC0_pointwiseZero
    {U : AtomCarrier.{u}}
    {A : ArchitectureObject U}
    {S : Site.AATSite.{u} A}
    {G : ArchitecturalEquationSystem S.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G)
    (hholds : D.DisplayedRequiredLawsHoldOn) :
    GeneratedSourceC0PointwiseZero D :=
  D.displayedRequiredLawsHoldOn_constructs_interpret_eq_zero hholds

/-- X.定理8.1: degree-zero law-generated zero package. -/
theorem displayedRequiredLawsHoldOn_constructs_generatedSourceC0_zeroPackage
    {U : AtomCarrier.{u}}
    {A : ArchitectureObject U}
    {S : Site.AATSite.{u} A}
    {G : ArchitecturalEquationSystem S.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G)
    (hholds : D.DisplayedRequiredLawsHoldOn) :
    Nonempty (GeneratedSourceC0ZeroPackage D) :=
  ⟨{ pointwiseZero :=
        displayedRequiredLawsHoldOn_constructs_generatedSourceC0_pointwiseZero
          D hholds }⟩

namespace SemanticRepairCoverH1BoundaryRelationAdditiveData

/--
X.定理7.3 bridge: the bounded §4 additive cover data as the finite-free
semantic additive H1 surface required by theorem 7.2.
-/
def toAdditiveH1Surface
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P) :
    SemanticRepairAdditiveH1Surface where
  C0 := data.boundaryRelation.cech.C0
  C1 := data.boundaryRelation.cech.C1
  C2 := data.boundaryRelation.cech.C2
  zero1 := data.boundaryRelation.cech.zero1
  zero2 := data.boundaryRelation.cech.zero2
  delta0 := data.boundaryRelation.cech.delta0
  delta1 := data.boundaryRelation.cech.delta1
  residual := data.boundaryRelation.cech.residual
  c0AddCommGroup := data.toAdditiveCechH1Data.c0AddCommGroup
  c1AddCommGroup := data.toAdditiveCechH1Data.c1AddCommGroup
  zero1_eq_zero := data.toAdditiveCechH1Data.zero1_eq_zero
  delta0_zero := data.toAdditiveCechH1Data.delta0_zero
  delta0_add := data.toAdditiveCechH1Data.delta0_add
  delta0_neg := data.toAdditiveCechH1Data.delta0_neg
  zero1_cocycle := data.boundaryRelation.cech.zero1_cocycle
  delta1_delta0_eq_zero := data.boundaryRelation.cech.delta1_delta0_eq_zero
  residual_cocycle := data.boundaryRelation.cech.residual_cocycle

end SemanticRepairCoverH1BoundaryRelationAdditiveData

/--
X.定理7.3: additive H1 zero on the bounded §4 surface is equivalent to zero
on the theorem-7.2 finite-free surface generated from it.
-/
theorem boundedAdditiveH1Zero_iff_surfaceH1Zero
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P) :
    data.toAdditiveCechH1Data.H1Zero <->
      data.toAdditiveH1Surface.H1Zero := by
  constructor
  · intro hzero
    exact hzero
  · intro hzero
    exact hzero

/-- X.定理7.3 conclusion bundle generated by true-sheaf descent and H1 comparison. -/
structure SemanticRepairGroundedGlobalGluingPackage
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {U : AtomCarrier.{r}}
    {A : ArchitectureObject U}
    (S : Site.AATSite A)
    (F : Site.AATPresheaf S)
    {base : S.category}
    (cover : Sieve base)
    (gluingData : Site.AATGluingData S F cover)
    {coverRel : Cohomology.CoverRelativeCechCover S}
    {Ob : Cohomology.ObstructionSheaf S}
    {K : Cohomology.CoverRelativeCechComplex coverRel Ob}
    (comparison :
      SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K) :
    Type (max u v w x y z r) where
  sheafConditionFor : Site.AATSheafConditionFor S F cover
  descent : Site.AATDescent S F cover
  uniqueGlobalSection :
    ∃! globalSection : F.obj (op base),
      Site.AATGlobalSectionRealizes gluingData globalSection
  h1ComparisonPackage :
    Nonempty
      (SemanticRepairCoverRelativeH1Comparison.SemanticRepairAdditiveH1CoverRelativeH1ComparisonPackage
        comparison)
  globalCoherent_iff_coverRelativeH1Zero :
    GlobalSemanticRepairCoherent data.boundaryRelation.toFiniteGluingComplex <->
      comparison.CoverRelativeResidualH1Zero
  coverRelativeH1Zero_to_globalCoherent :
    comparison.CoverRelativeResidualH1Zero ->
      GlobalSemanticRepairCoherent data.boundaryRelation.toFiniteGluingComplex
  globalCoherent_to_coverRelativeH1Zero :
    GlobalSemanticRepairCoherent data.boundaryRelation.toFiniteGluingComplex ->
      comparison.CoverRelativeResidualH1Zero
  boundedAdditiveH1Zero_iff_coverRelativeH1Zero :
    data.toAdditiveCechH1Data.H1Zero <->
      comparison.CoverRelativeResidualH1Zero
  torsorTrivialization_of_h1Zero : data.AdditiveTorsorTrivial

/--
X.定理7.3: theorem 4.8 plus theorem 7.2 and supplied gluing data yield the
selected global-gluing conclusion bundle.
-/
theorem trueSheafBoundaryRelationAdditive_coverRelativeH1Zero_effectiveGluing_package
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {U : AtomCarrier.{r}}
    {A : ArchitectureObject U}
    (S : Site.AATSite A)
    (F : Site.AATPresheaf S)
    {base : S.category}
    (cover : Sieve base)
    (certificate : data.TrueSheafConditionCertificate S F cover)
    (gluingData : Site.AATGluingData S F cover)
    {coverRel : Cohomology.CoverRelativeCechCover S}
    {Ob : Cohomology.ObstructionSheaf S}
    {K : Cohomology.CoverRelativeCechComplex coverRel Ob}
    (comparison :
      SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K) :
    Nonempty
      (SemanticRepairGroundedGlobalGluingPackage
        data S F cover gluingData comparison) := by
  rcases
    aatSheafCondition_coverMembership_descent_effectiveGluing
      certificate.sheafCondition cover certificate.cover_mem gluingData with
    ⟨hSheafFor, hDescent, hEffectiveGluing⟩
  have hBoundedAdditive :
      GlobalSemanticRepairCoherent data.boundaryRelation.toFiniteGluingComplex <->
        data.toAdditiveCechH1Data.H1Zero :=
    data.globalRepairCoherent_iff_additiveH1Zero
  have hSurfaceCover :
      data.toAdditiveH1Surface.H1Zero <->
        comparison.CoverRelativeResidualH1Zero :=
    comparison.semanticRepairAdditiveH1Zero_iff_coverRelativeH1Zero
  have hBoundedCover :
      data.toAdditiveCechH1Data.H1Zero <->
        comparison.CoverRelativeResidualH1Zero :=
    (boundedAdditiveH1Zero_iff_surfaceH1Zero data).trans hSurfaceCover
  have hGlobalCover :
      GlobalSemanticRepairCoherent data.boundaryRelation.toFiniteGluingComplex <->
        comparison.CoverRelativeResidualH1Zero :=
    hBoundedAdditive.trans hBoundedCover
  refine ⟨?_⟩
  exact
    { sheafConditionFor := hSheafFor
      descent := hDescent
      uniqueGlobalSection := hEffectiveGluing
      h1ComparisonPackage :=
        comparison.semanticRepairAdditiveH1_coverRelativeH1_comparison_package
      globalCoherent_iff_coverRelativeH1Zero := hGlobalCover
      coverRelativeH1Zero_to_globalCoherent := hGlobalCover.2
      globalCoherent_to_coverRelativeH1Zero := hGlobalCover.1
      boundedAdditiveH1Zero_iff_coverRelativeH1Zero := hBoundedCover
      torsorTrivialization_of_h1Zero :=
        SemanticRepairCoverH1BoundaryRelationAdditiveData.additiveTorsorTrivial_of_additiveH1Zero
          data }

/--
X.定理7.5 conclusions 1--3: the law-grounded degree-zero generation layer.

This structure is deliberately the only theorem-7.5 conclusion group whose
fields mention `LawEquationDefectSource`.  Later descent and H1 conclusions are
generated from the theorem-7.3 package, not from law-equation hypotheses.
-/
structure SemanticRepairGeneratedLawDependentConclusions
    {U : AtomCarrier.{u}}
    {A : ArchitectureObject U}
    {S : Site.AATSite.{u} A}
    {G : ArchitecturalEquationSystem S.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G) : Type (u + 1) where
  /-- Generated source package, including the degree-zero Cech vanishing proof. -/
  generatedSourceC0ZeroPackage : GeneratedSourceC0ZeroPackage D
  generatedInterpretationZero : forall i : D.Chart, D.interpret i = 0
  generatedInterpretationPointwiseZero :
    D.GeneratedInterpretationPointwiseZero
  generatedInterpretationZero_iff_defect_mem_obstructionIdeal :
    forall i : D.Chart,
      D.interpret i = 0 <->
        D.defect i (D.input i) ∈ G.obstructionIdeal (D.chart i)
  nonzeroInterpretationDetectsDisplayedLawFailure :
    forall i : D.Chart,
      D.interpret i ≠ 0 ->
        forall lawIndex : G.Index,
          lawIndex ∈ D.lawSupport i (D.input i) ->
            G.Required lawIndex ->
              ¬ G.EquationHolds lawIndex
                (D.objectOfLocalInput i (D.input i))

/-- X.定理7.5 conclusions 4--10: law-independent SAGA descent/H1 layer. -/
structure SemanticRepairGeneratedLawIndependentConclusions
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {U : AtomCarrier.{r}}
    {A : ArchitectureObject U}
    (S : Site.AATSite A)
    (F : Site.AATPresheaf S)
    {base : S.category}
    (cover : Sieve base)
    (gluingData : Site.AATGluingData S F cover)
    {coverRel : Cohomology.CoverRelativeCechCover S}
    {Ob : Cohomology.ObstructionSheaf S}
    {K : Cohomology.CoverRelativeCechComplex coverRel Ob}
    (comparison :
      SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K) :
    Type (max (max u v) (max w (max x (max y (max z r))))) where
  groundedGlobalGluingPackage :
    Nonempty
      (SemanticRepairGroundedGlobalGluingPackage
        data S F cover gluingData comparison)
  sheafConditionFor : Site.AATSheafConditionFor S F cover
  descent : Site.AATDescent S F cover
  uniqueGlobalSection :
    ∃! globalSection : F.obj (op base),
      Site.AATGlobalSectionRealizes gluingData globalSection
  globalCoherent_iff_coverRelativeH1Zero :
    GlobalSemanticRepairCoherent data.boundaryRelation.toFiniteGluingComplex <->
      comparison.CoverRelativeResidualH1Zero
  boundedAdditiveH1Zero_iff_coverRelativeH1Zero :
    data.toAdditiveCechH1Data.H1Zero <->
      comparison.CoverRelativeResidualH1Zero
  torsorTrivialization : data.AdditiveTorsorTrivial

/--
X.定理7.5 packet: generated end-to-end SAGA realization.

The packet is split into law-dependent conclusions 1--3 and law-independent
conclusions 4--10.  This is the statement-level dependency boundary required
by AC14.
-/
structure SemanticRepairGeneratedEndToEndSAGAPacket
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {Ulaw : AtomCarrier.{u}}
    {Alaw : ArchitectureObject Ulaw}
    {Slaw : Site.AATSite.{u} Alaw}
    {G : ArchitecturalEquationSystem Slaw.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G)
    {U : AtomCarrier.{r}}
    {A : ArchitectureObject U}
    (S : Site.AATSite A)
    (F : Site.AATPresheaf S)
    {base : S.category}
    (cover : Sieve base)
    (gluingData : Site.AATGluingData S F cover)
    {coverRel : Cohomology.CoverRelativeCechCover S}
    {Ob : Cohomology.ObstructionSheaf S}
    {K : Cohomology.CoverRelativeCechComplex coverRel Ob}
    (comparison :
      SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K) :
    Type (max (u + 1) (max v (max w (max x (max y (max z r)))))) where
  lawDependentConclusions :
    SemanticRepairGeneratedLawDependentConclusions D
  lawIndependentConclusions :
    SemanticRepairGeneratedLawIndependentConclusions
      data S F cover gluingData comparison

/--
X.定理7.5 realized packet: the theorem-7.5 packet together with the concrete
cochain realization that generated its H1 comparison.

This body-side strengthening keeps the comparison provenance in the theorem
object: the comparison is no longer only a parameter with a packet attached,
but is tied to an explicit `SemanticRepairCoverRelativeCochainRealization` and
the theorem-7.2 comparison package derived from it.
-/
structure SemanticRepairGeneratedRealizedEndToEndSAGAPacket
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {Ulaw : AtomCarrier.{u}}
    {Alaw : ArchitectureObject Ulaw}
    {Slaw : Site.AATSite.{u} Alaw}
    {G : ArchitecturalEquationSystem Slaw.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G)
    {U : AtomCarrier.{r}}
    {A : ArchitectureObject U}
    (S : Site.AATSite A)
    (F : Site.AATPresheaf S)
    {base : S.category}
    (cover : Sieve base)
    (gluingData : Site.AATGluingData S F cover)
    {coverRel : Cohomology.CoverRelativeCechCover S}
    {Ob : Cohomology.ObstructionSheaf S}
    {K : Cohomology.CoverRelativeCechComplex coverRel Ob}
    (comparison :
      SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K) :
    Type (max (u + 1) (max v (max w (max x (max y (max z r)))))) where
  /-- End-to-end theorem-7.5 packet generated by the realization. -/
  packet :
    SemanticRepairGeneratedEndToEndSAGAPacket
      data D S F cover gluingData comparison
  /-- Cochain realization from which the comparison is constructed. -/
  cochainRealization :
    SemanticRepairCoverRelativeCochainRealization data.toAdditiveH1Surface K
  comparison_eq_realization :
    comparison = cochainRealization.toH1Comparison
  h1ComparisonPackage :
    Nonempty
      (SemanticRepairCoverRelativeH1Comparison.SemanticRepairAdditiveH1CoverRelativeH1ComparisonPackage
        comparison)

/--
X.定理7.5 native generated-input surface.

This stricter boundary fixes the downstream coefficient to the obstruction
quotient presheaf produced by the law-equation witness-ideal core itself. The
native theorem route can no longer be formed with an arbitrary coefficient
presheaf or obstruction sheaf: the cover-relative complex is typed over the
obstruction sheaf generated from `G.obstructionQuotientCoefficient` and the
selected sheaf certificate.
-/
structure SemanticRepairNativeGeneratedEndToEndInputs
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {Ulaw : AtomCarrier.{u}}
    {Alaw : ArchitectureObject Ulaw}
    {Slaw : Site.AATSite.{u} Alaw}
    {G : ArchitecturalEquationSystem Slaw.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G)
    {base : Slaw.category}
    (cover : Sieve base)
    (certificate :
      data.TrueSheafConditionCertificate Slaw G.obstructionQuotientPresheaf cover)
    {coverRel : Cohomology.CoverRelativeCechCover Slaw}
    (K : Cohomology.CoverRelativeCechComplex coverRel
      (Cohomology.ObstructionSheaf.ofAddCommGrpValued
        G.obstructionQuotientCoefficient certificate.sheafCondition)) :
    Type (max u v w x y z) where
  realization :
    SemanticRepairCoverRelativeCochainRealization data.toAdditiveH1Surface K

namespace SemanticRepairNativeGeneratedEndToEndInputs

variable {P : SemanticAtomProjection.{u, v}}
variable {data :
  SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P}
variable {Ulaw : AtomCarrier.{u}} {Alaw : ArchitectureObject Ulaw}
variable {Slaw : Site.AATSite.{u} Alaw}
variable {G : ArchitecturalEquationSystem Slaw.contextPreorder}
variable {D : LawAlgebra.LawEquationDefectSource.{u} G}
variable {base : Slaw.category} {cover : Sieve base}
variable {certificate :
  data.TrueSheafConditionCertificate Slaw G.obstructionQuotientPresheaf cover}
variable {coverRel : Cohomology.CoverRelativeCechCover Slaw}
variable {K : Cohomology.CoverRelativeCechComplex coverRel
  (Cohomology.ObstructionSheaf.ofAddCommGrpValued
    G.obstructionQuotientCoefficient certificate.sheafCondition)}

/-- X.定理7.5: native generated inputs construct the comparison used downstream. -/
def toH1Comparison
    (inputs : SemanticRepairNativeGeneratedEndToEndInputs data D cover certificate K) :
    SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K :=
  inputs.realization.toH1Comparison

end SemanticRepairNativeGeneratedEndToEndInputs

/--
X.定理7.5: generated law-equation grounding plus theorem 7.3 yields the
10-conclusion SAGA packet, with law dependency confined to conclusions 1--3.

Scaffolding: this route consumes the section-4 bounded Cech data, whose
`c0Finite` / `c1Finite` fields carry `Fintype` premises absent from theorem
7.5.  The canonical theorem-7.5 entry-point is the finite-free
`lawEquation_constructs_groundedComparisonPacket_finiteFree`.
-/
theorem lawEquation_constructs_groundedComparisonPacket
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {Ulaw : AtomCarrier.{u}}
    {Alaw : ArchitectureObject Ulaw}
    {Slaw : Site.AATSite.{u} Alaw}
    {G : ArchitecturalEquationSystem Slaw.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G)
    (hDisplayedRequiredLaws : D.DisplayedRequiredLawsHoldOn)
    {U : AtomCarrier.{r}}
    {A : ArchitectureObject U}
    (S : Site.AATSite A)
    (F : Site.AATPresheaf S)
    {base : S.category}
    (cover : Sieve base)
    (certificate : data.TrueSheafConditionCertificate S F cover)
    (gluingData : Site.AATGluingData S F cover)
    {coverRel : Cohomology.CoverRelativeCechCover S}
    {Ob : Cohomology.ObstructionSheaf S}
    {K : Cohomology.CoverRelativeCechComplex coverRel Ob}
    (comparison :
      SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K) :
    Nonempty
      (SemanticRepairGeneratedEndToEndSAGAPacket
        data D S F cover gluingData comparison) := by
  rcases
    LawAlgebra.LawEquationDefectSource.lawEquation_grounding_packet
      D hDisplayedRequiredLaws with
    ⟨hInterpretZero, hPointwiseZero, _hDefectIff, hFailureDetection⟩
  rcases
    displayedRequiredLawsHoldOn_constructs_generatedSourceC0_zeroPackage
      D hDisplayedRequiredLaws with
    ⟨hZeroPackage⟩
  rcases
    trueSheafBoundaryRelationAdditive_coverRelativeH1Zero_effectiveGluing_package
      data S F cover certificate gluingData comparison with
    ⟨package73⟩
  refine ⟨?_⟩
  exact
    { lawDependentConclusions :=
        { generatedSourceC0ZeroPackage := hZeroPackage
          generatedInterpretationZero := hInterpretZero
          generatedInterpretationPointwiseZero := hPointwiseZero
          generatedInterpretationZero_iff_defect_mem_obstructionIdeal := _hDefectIff
          nonzeroInterpretationDetectsDisplayedLawFailure := hFailureDetection }
      lawIndependentConclusions :=
        { groundedGlobalGluingPackage := ⟨package73⟩
          sheafConditionFor := package73.sheafConditionFor
          descent := package73.descent
          uniqueGlobalSection := package73.uniqueGlobalSection
          globalCoherent_iff_coverRelativeH1Zero :=
            package73.globalCoherent_iff_coverRelativeH1Zero
          boundedAdditiveH1Zero_iff_coverRelativeH1Zero :=
            package73.boundedAdditiveH1Zero_iff_coverRelativeH1Zero
          torsorTrivialization := package73.torsorTrivialization_of_h1Zero } }

/--
X.定理7.5 generated-comparison form: a cochain realization generates the
H1 comparison used by the end-to-end packet.

This keeps theorem 7.5 from taking `SemanticRepairCoverRelativeH1Comparison`
as a material premise.  The returned dependent pair exposes the generated
comparison together with the usual ten-conclusion packet.

Scaffolding: this route consumes the section-4 bounded Cech data, whose
`c0Finite` / `c1Finite` fields carry `Fintype` premises absent from theorem
7.5.  The canonical theorem-7.5 entry-point is the finite-free
`lawEquation_constructs_groundedComparisonPacket_finiteFree`.
-/
theorem lawEquation_constructs_groundedComparisonPacket_fromRealization
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {Ulaw : AtomCarrier.{u}}
    {Alaw : ArchitectureObject Ulaw}
    {Slaw : Site.AATSite.{u} Alaw}
    {G : ArchitecturalEquationSystem Slaw.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G)
    (hDisplayedRequiredLaws : D.DisplayedRequiredLawsHoldOn)
    {U : AtomCarrier.{r}}
    {A : ArchitectureObject U}
    (S : Site.AATSite A)
    (F : Site.AATPresheaf S)
    {base : S.category}
    (cover : Sieve base)
    (certificate : data.TrueSheafConditionCertificate S F cover)
    (gluingData : Site.AATGluingData S F cover)
    {coverRel : Cohomology.CoverRelativeCechCover S}
    {Ob : Cohomology.ObstructionSheaf S}
    {K : Cohomology.CoverRelativeCechComplex coverRel Ob}
    (realization :
      SemanticRepairCoverRelativeCochainRealization data.toAdditiveH1Surface K) :
    Nonempty
      (Sigma fun comparison :
        SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K =>
          SemanticRepairGeneratedEndToEndSAGAPacket
            data D S F cover gluingData comparison) := by
  let comparison := realization.toH1Comparison
  rcases
    lawEquation_constructs_groundedComparisonPacket
      data D hDisplayedRequiredLaws S F cover certificate gluingData comparison with
    ⟨packet⟩
  exact ⟨⟨comparison, packet⟩⟩

/--
X.定理7.5 realized generated-comparison form: the returned packet retains the
cochain realization that generated the comparison and the theorem-7.2
comparison package derived from it.

Scaffolding: this route consumes the section-4 bounded Cech data, whose
`c0Finite` / `c1Finite` fields carry `Fintype` premises absent from theorem
7.5.  The canonical theorem-7.5 entry-point is the finite-free
`lawEquation_constructs_groundedComparisonPacket_finiteFree`.
-/
theorem lawEquation_constructs_realizedGroundedComparisonPacket_fromRealization
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {Ulaw : AtomCarrier.{u}}
    {Alaw : ArchitectureObject Ulaw}
    {Slaw : Site.AATSite.{u} Alaw}
    {G : ArchitecturalEquationSystem Slaw.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G)
    (hDisplayedRequiredLaws : D.DisplayedRequiredLawsHoldOn)
    {U : AtomCarrier.{r}}
    {A : ArchitectureObject U}
    (S : Site.AATSite A)
    (F : Site.AATPresheaf S)
    {base : S.category}
    (cover : Sieve base)
    (certificate : data.TrueSheafConditionCertificate S F cover)
    (gluingData : Site.AATGluingData S F cover)
    {coverRel : Cohomology.CoverRelativeCechCover S}
    {Ob : Cohomology.ObstructionSheaf S}
    {K : Cohomology.CoverRelativeCechComplex coverRel Ob}
    (realization :
      SemanticRepairCoverRelativeCochainRealization data.toAdditiveH1Surface K) :
    Nonempty
      (Sigma fun comparison :
        SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K =>
          SemanticRepairGeneratedRealizedEndToEndSAGAPacket
            data D S F cover gluingData comparison) := by
  let comparison := realization.toH1Comparison
  rcases
    lawEquation_constructs_groundedComparisonPacket
      data D hDisplayedRequiredLaws S F cover certificate gluingData comparison with
    ⟨packet⟩
  exact
    ⟨⟨comparison,
      { packet := packet
        cochainRealization := realization
        comparison_eq_realization := rfl
        h1ComparisonPackage :=
          comparison.semanticRepairAdditiveH1_coverRelativeH1_comparison_package }⟩⟩

/--
X.定理7.5 native generated-input form: the theorem consumes cochain
realization data while the coefficient presheaf is definitionally the
law-equation-generated obstruction quotient `O/I_Ob`.

Scaffolding: this route consumes the section-4 bounded Cech data, whose
`c0Finite` / `c1Finite` fields carry `Fintype` premises absent from theorem
7.5.  The canonical theorem-7.5 entry-point is the finite-free
`lawEquation_constructs_groundedComparisonPacket_finiteFree`.
-/
theorem lawEquation_constructs_groundedComparisonPacket_fromNativeGeneratedInputs
    {P : SemanticAtomProjection.{u, v}}
    (data :
      SemanticRepairCoverH1BoundaryRelationAdditiveData.{u, v, w, x, y, z} P)
    {Ulaw : AtomCarrier.{u}}
    {Alaw : ArchitectureObject Ulaw}
    {Slaw : Site.AATSite.{u} Alaw}
    {G : ArchitecturalEquationSystem Slaw.contextPreorder}
    (D : LawAlgebra.LawEquationDefectSource.{u} G)
    (hDisplayedRequiredLaws : D.DisplayedRequiredLawsHoldOn)
    {base : Slaw.category}
    (cover : Sieve base)
    (certificate :
      data.TrueSheafConditionCertificate Slaw G.obstructionQuotientPresheaf cover)
    (gluingData :
      Site.AATGluingData Slaw G.obstructionQuotientPresheaf cover)
    {coverRel : Cohomology.CoverRelativeCechCover Slaw}
    {K : Cohomology.CoverRelativeCechComplex coverRel
      (Cohomology.ObstructionSheaf.ofAddCommGrpValued
        G.obstructionQuotientCoefficient certificate.sheafCondition)}
    (inputs :
      SemanticRepairNativeGeneratedEndToEndInputs data D cover certificate K) :
    Nonempty
      (Sigma fun comparison :
        SemanticRepairCoverRelativeH1Comparison data.toAdditiveH1Surface K =>
          SemanticRepairGeneratedEndToEndSAGAPacket
            data D Slaw G.obstructionQuotientPresheaf cover gluingData comparison) := by
  let comparison := inputs.toH1Comparison
  rcases
    lawEquation_constructs_groundedComparisonPacket
      data D hDisplayedRequiredLaws Slaw G.obstructionQuotientPresheaf
      cover certificate gluingData comparison with
    ⟨packet⟩
  exact ⟨⟨comparison, packet⟩⟩

end SemanticRepair
end AAT.AG
