import ResearchLean.AG.DiagnosticConservativity.TransportAlignment
import ResearchLean.AG.DoctrineFiberProduct.PackageProjectionBeckChevalleyExactness

/-!
# G-113 revision 2 semantic-global ambidextrous lift

This module discharges the G-110 bridge required by G-113(a).  The G-112
semantic-global selected cartesian lift is compared with the explicit G-110
arbitrary-target lift.  The comparison is generated by cartesian uniqueness,
and its composition with the reviewed cocartesian explicit lift makes the
selected lift cocartesian as well.

## Implementation notes

The selected lift is not assumed or claimed to be definitionally equal to the
explicit lift.  Their canonical domain isomorphism over the identity base arrow
is used in the proof.  The alternative of reusing the realized-arrow unit and
counit was rejected because G-113 quantifies over every indexed base hom.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation
open CrossStageCoherence

/--
Every G-112 semantic-global selected lift is strongly cocartesian, by the
canonical comparison with the reviewed G-110 explicit arbitrary-target lift.
-/
theorem exact_bottom_semantic_global_selected_lift_isStronglyCocartesian
    {U : AtomCarrier.{u}} {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    (packageProjection U).IsStronglyCocartesian hom
      (exact_bottom_semantic_global_selected_lift hom targetPackage).hom := by
  let explicit := strongCartesianLiftOfTarget
    (cartSemanticInputOfHom hom) targetPackage
  let selected := exact_bottom_semantic_global_selected_lift hom targetPackage
  letI : (packageProjection U).IsStronglyCartesian hom explicit.hom :=
    explicit.isStronglyCartesian
  letI : (packageProjection U).IsStronglyCartesian hom selected.hom :=
    selected.isStronglyCartesian
  have base_fac : hom = (Iso.refl source).hom ≫ hom := by simp
  let comparison : selected.domain ≅ explicit.domain :=
    CategoryTheory.Functor.IsStronglyCartesian.domainIsoOfBaseIso
      (p := packageProjection U)
      (g := Iso.refl source)
      (f := hom) (f' := hom)
      base_fac explicit.hom selected.hom
  have comparison_fac : comparison.hom ≫ explicit.hom = selected.hom := by
    exact CategoryTheory.Functor.IsStronglyCartesian.fac
      (packageProjection U) hom explicit.hom base_fac selected.hom
  letI : (packageProjection U).IsHomLift
      (𝟙 source) comparison.hom := by
    change (packageProjection U).IsHomLift
      (Iso.refl source).hom comparison.hom
    infer_instance
  letI : (packageProjection U).IsStronglyCocartesian
      (𝟙 source) comparison.hom :=
    CategoryTheory.Functor.IsStronglyCocartesian.of_iso
      (packageProjection U) (𝟙 source) comparison
  letI : (packageProjection U).IsStronglyCocartesian hom explicit.hom :=
    strongCartesianLiftOfTarget_isStronglyCocartesian
      (cartSemanticInputOfHom hom) targetPackage
  have composed : (packageProjection U).IsStronglyCocartesian
      ((𝟙 source) ≫ hom) (comparison.hom ≫ explicit.hom) :=
    CategoryTheory.Functor.IsStronglyCocartesian.comp (packageProjection U)
  simpa only [Category.id_comp, comparison_fac] using composed

/--
At each indexed diagnostic vertex, the G-112 reindexing lift over the same F0
base arrow is strongly cocartesian.
-/
theorem indexedDiagnosticTransportSelectedLift_isStronglyCocartesian
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (vertex : G.Vertex) (targetPackage : CoreFiber (E.vertex vertex)) :
    (packageProjection U).IsStronglyCocartesian (hom.app vertex)
      (exact_bottom_semantic_global_selected_lift
        (hom.app vertex) targetPackage).hom :=
  exact_bottom_semantic_global_selected_lift_isStronglyCocartesian
    (hom.app vertex) targetPackage

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
