import ResearchLean.AG.DiagnosticConservativity.PathSquareDownstreamCompatibility
import ResearchLean.AG.DoctrineFiberProduct.IndexedDiagnosticCovarianceWitnesses
import ResearchLean.AG.DoctrineFiberProduct.CartesianRegimeReindexingCleavageWitnesses

/-!
# G-113 revision 2 base-isomorphism independence and finite nondegeneracy

The diagnostic fiber transport equivalence is generated over every indexed
base component; no `IsIso` premise occurs in its construction.  The finite
witness below makes the independence concrete.  Its base component is the
selective-two arrow, which identifies two distinct source cells and is not an
isomorphism.  Its source package is the previously fixed finite cartesian
reindexing fixture, and its source swap is generated by that G-110 fixture's
actual reindexing factor graph from the pre-existing first-two-axis swap,
independently of the diagnostic equivalence.  Forward and inverse diagnostic
transport then preserve the same nonidentity reselection and raw defect through
both round trips.
-/

namespace AAT.AG.DoctrineFiberProduct

open CategoryTheory
open AtomFoundation
open CrossStageCoherence
open TransportCoherence

local instance finiteNonIsoDiagnosticAtomDecidableEq :
    DecidableEq FiniteModel.carrier.Atom := by
  change DecidableEq FiniteModel.FiniteAtom
  infer_instance

namespace IndexedBaseDiagramHom

/-- The explicit fiber equivalence exists without a base `IsIso` assumption. -/
theorem indexedDiagnosticTransport_isEquivalence_arbitraryBase
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (vertex : G.Vertex) :
    (indexedDiagnosticTransportPush hom vertex).IsEquivalence :=
  indexedDiagnosticTransportPush_isEquivalence hom vertex

/-- A base `IsIso` assumption gives the same generated fiber equivalence. -/
theorem indexedDiagnosticTransport_isEquivalence_of_baseIsIso
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (vertex : G.Vertex) [IsIso (hom.app vertex)] :
    (indexedDiagnosticTransportPush hom vertex).IsEquivalence :=
  hom.indexedDiagnosticTransport_isEquivalence_arbitraryBase vertex

end IndexedBaseDiagramHom

open IndexedBaseDiagramHom

/-! ## Finite non-isomorphic base witness -/

/-- The visible target four-axis package. -/
noncomputable abbrev finiteNonIsoDiagnosticTargetObject :
    CoreFiber finiteSelectiveTwoToSupportInput.semantic.target :=
  finiteReindexFourAxisTarget

/-- The target adjacent swap as a package-fiber automorphism. -/
noncomputable def finiteNonIsoDiagnosticTargetSwap :
    PackageFiberAut finiteNonIsoDiagnosticTargetObject.1 :=
  ⟨finiteCleavageAxisPermutationIso finiteReindexAxisSwap, rfl⟩

/-- The visible target adjacent swap is nonidentity. -/
theorem finiteNonIsoDiagnosticTargetSwap_ne_one :
    finiteNonIsoDiagnosticTargetSwap ≠ 1 := by
  intro equality
  have axisEquality := congrArg
    (fun automorphism : PackageFiberAut finiteNonIsoDiagnosticTargetObject.1 =>
      (PackageFiberAut.hom automorphism).upper.axisMap finiteReindexAxisZero)
    equality
  change (1 : Fin 4) = 0 at axisEquality
  exact finiteReindexAxisZero_ne_one axisEquality.symm

/-- The pre-existing finite cartesian-reindexing object in the source fiber. -/
noncomputable def finiteNonIsoDiagnosticSourceObject :
    CoreFiber finiteSelectiveTwoToSupportInput.semantic.source :=
  finiteSelectiveTwoReindexedFourAxisObject

/-- Reindex the fixed target swap through the pre-existing G-110 fixture. -/
noncomputable def finiteNonIsoDiagnosticSourceSwap :
    PackageFiberAut finiteNonIsoDiagnosticSourceObject.1 :=
  (packageFiberAutCoreFiberEquiv finiteNonIsoDiagnosticSourceObject).symm
    ((selectedCoreFiberReindexFunctor finiteSelectiveTwoToSupportInput).mapIso
      ((packageFiberAutCoreFiberEquiv finiteNonIsoDiagnosticTargetObject)
        finiteNonIsoDiagnosticTargetSwap))

/-- The endpoint-group equivalence retains the underlying total hom. -/
theorem packageFiberAutCoreFiberEquiv_hom_value
    {X : ExtractionInstance FiniteModel.carrier} (object : CoreFiber X)
    (automorphism : PackageFiberAut object.1) :
    PackageFiberAut.hom automorphism =
      ((packageFiberAutCoreFiberEquiv object) automorphism).hom.1 := by
  rcases object with ⟨object, rfl⟩
  rfl

/-- The source swap's total hom is the G-110 reindexing map. -/
theorem finiteNonIsoDiagnosticSourceSwap_hom_eq :
    PackageFiberAut.hom finiteNonIsoDiagnosticSourceSwap =
      ((selectedCoreFiberReindexFunctor finiteSelectiveTwoToSupportInput).map
        ((packageFiberAutCoreFiberEquiv finiteNonIsoDiagnosticTargetObject)
          finiteNonIsoDiagnosticTargetSwap).hom).1 := by
  have equality := (packageFiberAutCoreFiberEquiv
    finiteNonIsoDiagnosticSourceObject).apply_symm_apply
      ((selectedCoreFiberReindexFunctor finiteSelectiveTwoToSupportInput).mapIso
        ((packageFiberAutCoreFiberEquiv finiteNonIsoDiagnosticTargetObject)
          finiteNonIsoDiagnosticTargetSwap))
  rw [packageFiberAutCoreFiberEquiv_hom_value]
  exact congrArg (fun automorphism : Aut finiteNonIsoDiagnosticSourceObject =>
    automorphism.hom.1) equality

/-- The raw G-110 reindexing factor graph for the fixed source swap. -/
theorem finiteNonIsoDiagnosticSourceSwap_fac :
    (PackageFiberAut.hom finiteNonIsoDiagnosticSourceSwap) ≫
        (selectedCoreFiberCartesianLift finiteSelectiveTwoToSupportInput
          finiteNonIsoDiagnosticTargetObject).hom =
      (selectedCoreFiberCartesianLift finiteSelectiveTwoToSupportInput
          finiteNonIsoDiagnosticTargetObject).hom ≫
        PackageFiberAut.hom finiteNonIsoDiagnosticTargetSwap := by
  rw [finiteNonIsoDiagnosticSourceSwap_hom_eq]
  exact selectedCoreFiberReindexFunctor_map_fac
    finiteSelectiveTwoToSupportInput
      ((packageFiberAutCoreFiberEquiv finiteNonIsoDiagnosticTargetObject)
        finiteNonIsoDiagnosticTargetSwap).hom

/-- The G-110 source-fixture swap remains visibly nonidentity. -/
theorem finiteNonIsoDiagnosticSourceSwap_ne_one :
    finiteNonIsoDiagnosticSourceSwap ≠ 1 := by
  intro equality
  have sourceHomEquality := congrArg PackageFiberAut.hom equality
  have liftEquality :
      (selectedCoreFiberCartesianLift finiteSelectiveTwoToSupportInput
          finiteNonIsoDiagnosticTargetObject).hom =
        (selectedCoreFiberCartesianLift finiteSelectiveTwoToSupportInput
          finiteNonIsoDiagnosticTargetObject).hom ≫
          PackageFiberAut.hom finiteNonIsoDiagnosticTargetSwap := by
    calc
      _ = PackageFiberAut.hom finiteNonIsoDiagnosticSourceSwap ≫
          (selectedCoreFiberCartesianLift finiteSelectiveTwoToSupportInput
            finiteNonIsoDiagnosticTargetObject).hom := by
        rw [sourceHomEquality]
        change _ = (𝟙 finiteNonIsoDiagnosticSourceObject.1) ≫ _
        simp
      _ = _ := finiteNonIsoDiagnosticSourceSwap_fac
  apply finiteNonIsoDiagnosticTargetSwap_ne_one
  apply (packageFiberAutCoreFiberEquiv
    finiteNonIsoDiagnosticTargetObject).injective
  apply Iso.ext
  apply CategoryTheory.Functor.Fiber.hom_ext
  let lift := (selectedCoreFiberCartesianLift finiteSelectiveTwoToSupportInput
    finiteNonIsoDiagnosticTargetObject).hom
  letI : (packageProjection FiniteModel.carrier).IsStronglyCocartesian
      finiteSelectiveTwoToSupportInput.semantic.hom lift :=
    selectedCoreFiberCartesianLift_isStronglyCocartesian
      finiteSelectiveTwoToSupportInput finiteNonIsoDiagnosticTargetObject
  letI : (packageProjection FiniteModel.carrier).IsHomLift
      (𝟙 finiteSelectiveTwoToSupportInput.semantic.target)
      (PackageFiberAut.hom finiteNonIsoDiagnosticTargetSwap) := by
    exact (packageFiberAutCoreFiberEquiv
      finiteNonIsoDiagnosticTargetObject
      finiteNonIsoDiagnosticTargetSwap).hom.2
  letI : (packageProjection FiniteModel.carrier).IsHomLift
      (𝟙 finiteSelectiveTwoToSupportInput.semantic.target)
      (PackageFiberAut.hom (1 :
        PackageFiberAut finiteNonIsoDiagnosticTargetObject.1)) := by
    exact (packageFiberAutCoreFiberEquiv
      finiteNonIsoDiagnosticTargetObject 1).hom.2
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection FiniteModel.carrier)
    finiteSelectiveTwoToSupportInput.semantic.hom lift
    (𝟙 finiteSelectiveTwoToSupportInput.semantic.target)
  change lift ≫ PackageFiberAut.hom finiteNonIsoDiagnosticTargetSwap =
    lift ≫ PackageFiberAut.hom (1 :
      PackageFiberAut finiteNonIsoDiagnosticTargetObject.1)
  rw [← liftEquality]
  change lift = lift ≫ (𝟙 finiteNonIsoDiagnosticTargetObject.1)
  simp

/-- The constant source disk over the selective-two source. -/
noncomputable def finiteNonIsoDiagnosticSourceDiagram :
    IndexedBaseDiagram indexedCovarianceShape FiniteModel.carrier where
  vertex := fun _ => finiteSelectiveTwoToSupportInput.semantic.source
  edge := fun _ => 𝟙 _
  relation := by intro cell; cases cell; rfl

/-- The constant target disk over the selective-two target. -/
noncomputable def finiteNonIsoDiagnosticTargetDiagram :
    IndexedBaseDiagram indexedCovarianceShape FiniteModel.carrier where
  vertex := fun _ => finiteSelectiveTwoToSupportInput.semantic.target
  edge := fun _ => 𝟙 _
  relation := by intro cell; cases cell; rfl

/-- The disk hom whose every vertex component is the non-isomorphic base arrow. -/
noncomputable def finiteNonIsoDiagnosticDiagramHom :
    IndexedBaseDiagramHom finiteNonIsoDiagnosticSourceDiagram
      finiteNonIsoDiagnosticTargetDiagram where
  app := fun _ => finiteSelectiveTwoToSupportInput.semantic.hom
  naturality := by
    intro i j edge
    change finiteSelectiveTwoToSupportInput.semantic.hom ≫ 𝟙 _ =
      𝟙 _ ≫ finiteSelectiveTwoToSupportInput.semantic.hom
    simp

/-- Every witness vertex component is genuinely non-isomorphic. -/
theorem finiteNonIsoDiagnosticDiagramHom_not_isIso (vertex) :
    ¬ IsIso (finiteNonIsoDiagnosticDiagramHom.app vertex) := by
  simpa [finiteNonIsoDiagnosticDiagramHom] using
    finiteSelectiveTwoToSupportInput_not_isIso

/-- Its primitive source map visibly identifies two distinct finite cells. -/
theorem finiteNonIsoDiagnosticDiagramHom_identifies_distinct_cells (vertex) :
    finiteSelectiveTwoPoint ≠ finiteSelectiveTwoOther ∧
      (finiteNonIsoDiagnosticDiagramHom.app vertex).doctrineHom.sourceMap
          finiteSelectiveTwoPoint =
        (finiteNonIsoDiagnosticDiagramHom.app vertex).doctrineHom.sourceMap
          finiteSelectiveTwoOther := by
  exact ⟨finiteSelectiveTwoToSupport_source_points_ne,
    finiteSelectiveTwoToSupport_sourceMap_eq⟩

/-- Source interpretation with identity edges and the raw G-110 swap comparator. -/
noncomputable def finiteNonIsoDiagnosticSource :
    IndexedDiagnosticInterpretation finiteNonIsoDiagnosticSourceDiagram where
  package := fun _ => finiteNonIsoDiagnosticSourceObject.1
  vertexBase := fun _ => finiteNonIsoDiagnosticSourceObject.2
  edgeLift := fun _ => PackageTotalHom.id finiteNonIsoDiagnosticSourceObject.1
  edgeOver := by
    intro i j edge
    exact CategoryTheory.IsHomLift.id finiteNonIsoDiagnosticSourceObject.2
  edgeStrong := by
    intro i j edge
    letI : (packageProjection FiniteModel.carrier).IsHomLift
        (𝟙 finiteSelectiveTwoToSupportInput.semantic.source)
        (Iso.refl finiteNonIsoDiagnosticSourceObject.1).hom :=
      CategoryTheory.IsHomLift.id finiteNonIsoDiagnosticSourceObject.2
    simpa using CategoryTheory.Functor.IsStronglyCocartesian.of_iso
      (packageProjection FiniteModel.carrier)
      (𝟙 finiteSelectiveTwoToSupportInput.semantic.source)
      (Iso.refl finiteNonIsoDiagnosticSourceObject.1)
  comparator := fun _ => finiteNonIsoDiagnosticSourceSwap

/-- The same raw swap on both edges gives a nonidentity source reselection. -/
noncomputable def finiteNonIsoDiagnosticSourceReselection :
    IndexedEdgeReselection finiteNonIsoDiagnosticSource :=
  fun _ _ edge => match edge with
    | .left => finiteNonIsoDiagnosticSourceSwap
    | .right => finiteNonIsoDiagnosticSourceSwap

/-- The source reselection is nonidentity. -/
theorem finiteNonIsoDiagnosticSourceReselection_ne_one :
    finiteNonIsoDiagnosticSourceReselection ≠ 1 := by
  intro equality
  have rightEquality := congrFun
    (congrFun (congrFun equality indexedCovarianceSourceVertex)
      indexedCovarianceTargetVertex) indexedCovarianceRightEdge
  exact finiteNonIsoDiagnosticSourceSwap_ne_one rightEquality

@[simp]
theorem finiteNonIsoDiagnosticSourceReselection_left :
    finiteNonIsoDiagnosticSourceReselection indexedCovarianceSourceVertex
      indexedCovarianceTargetVertex indexedCovarianceLeftEdge =
        finiteNonIsoDiagnosticSourceSwap := by
  rfl

@[simp]
theorem finiteNonIsoDiagnosticSourceReselection_right :
    finiteNonIsoDiagnosticSourceReselection indexedCovarianceSourceVertex
      indexedCovarianceTargetVertex indexedCovarianceRightEdge =
        finiteNonIsoDiagnosticSourceSwap := by
  rfl

/-- The same-swap reselection has identity canonical comparator. -/
theorem finiteNonIsoDiagnostic_sourceReselectionCanonicalComparator_eq_one :
    canonicalTwoCellComparator
        finiteNonIsoDiagnosticSource.toAdmissibleTransportData
        finiteNonIsoDiagnosticSourceReselection
        indexedCovarianceFace = 1 := by
  let data := finiteNonIsoDiagnosticSource.toAdmissibleTransportData
  let left := TransportCoherence.reselectedPathLift data.lift
    finiteNonIsoDiagnosticSourceReselection
    indexedCovarianceLeftPath.toPresentedPath
  letI : (packageProjection FiniteModel.carrier).IsStronglyCocartesian
      left.base left :=
    TransportCoherence.reselectedPathLift_isStronglyCocartesian data.lift
      finiteNonIsoDiagnosticSourceReselection
        indexedCovarianceLeftPath.toPresentedPath
  apply PackageFiberAut.ext_of_strong_fac left
  calc
    left.comp (PackageFiberAut.hom
        (canonicalTwoCellComparator data
          finiteNonIsoDiagnosticSourceReselection indexedCovarianceFace)) =
      TransportCoherence.reselectedPathLift data.lift
        finiteNonIsoDiagnosticSourceReselection
        indexedCovarianceRightPath.toPresentedPath :=
      canonicalTwoCellComparator_fac data
        finiteNonIsoDiagnosticSourceReselection indexedCovarianceFace
    _ = left.comp (PackageFiberAut.hom 1) := by
      simp [data, left, finiteNonIsoDiagnosticSource,
        indexedCovarianceLeftPath, indexedCovarianceRightPath,
        indexedCovarianceSourceVertex, indexedCovarianceTargetVertex,
        indexedCovarianceLeftEdge, indexedCovarianceRightEdge,
        indexedCovarianceShape, IndexedBasePath.toPresentedPath,
        IndexedDiagnosticInterpretation.reselectedPathLift,
        IndexedDiagnosticInterpretation.reselectedEdgeLift,
        TransportCoherence.reselectedPathLift,
        TransportCoherence.reselectedEdgeLift,
        TransportCoherence.reselectLiftData, AdmissibleLiftData.pathLift,
        finiteNonIsoDiagnosticSourceReselection]
      rw [show PackageFiberAut.hom
          (1 : PackageFiberAut finiteNonIsoDiagnosticSourceObject.1) =
        PackageTotalHom.id finiteNonIsoDiagnosticSourceObject.1 by rfl]
      exact (@Category.comp_id
        (AATCorePackage FiniteModel.carrier)
        (PackageTotalHom.packageTotalCategory FiniteModel.carrier)
        finiteNonIsoDiagnosticSourceObject.1
        finiteNonIsoDiagnosticSourceObject.1
        (((PackageTotalHom.id finiteNonIsoDiagnosticSourceObject.1).comp
          (PackageFiberAut.hom finiteNonIsoDiagnosticSourceSwap)).comp
            (PackageTotalHom.id finiteNonIsoDiagnosticSourceObject.1))).symm

/-- The raw defect at the named nonidentity reselection is the source swap. -/
theorem finiteNonIsoDiagnostic_sourceReselectionRawDefect_eq_swap :
    rawDefectCochain
        finiteNonIsoDiagnosticSource.toAdmissibleTransportData
        finiteNonIsoDiagnosticSourceReselection
        indexedCovarianceFace = finiteNonIsoDiagnosticSourceSwap := by
  rw [rawDefectCochain, rawTwoCellDefect,
    finiteNonIsoDiagnostic_sourceReselectionCanonicalComparator_eq_one]
  simp [finiteNonIsoDiagnosticSource]

/-- The source raw defect at the named reselection is nonidentity. -/
theorem finiteNonIsoDiagnostic_sourceReselectionRawDefect_ne_one :
    rawDefectCochain
        finiteNonIsoDiagnosticSource.toAdmissibleTransportData
        finiteNonIsoDiagnosticSourceReselection
        indexedCovarianceFace ≠ 1 := by
  rw [finiteNonIsoDiagnostic_sourceReselectionRawDefect_eq_swap]
  exact finiteNonIsoDiagnosticSourceSwap_ne_one

/-- The nonidentity source reselection remains nonidentity after transport. -/
theorem finiteNonIsoDiagnostic_transportedReselection_ne_one :
    finiteNonIsoDiagnosticDiagramHom.transportedReselection
        finiteNonIsoDiagnosticSource finiteNonIsoDiagnosticSourceReselection ≠ 1 := by
  intro equality
  apply finiteNonIsoDiagnosticSourceReselection_ne_one
  apply (indexedDiagnosticReselectionEquivalence finiteNonIsoDiagnosticDiagramHom
    finiteNonIsoDiagnosticSource).injective
  rw [indexedDiagnosticReselectionEquivalence_apply]
  calc
    finiteNonIsoDiagnosticDiagramHom.transportedReselection
        finiteNonIsoDiagnosticSource finiteNonIsoDiagnosticSourceReselection = 1 :=
      equality
    _ = indexedDiagnosticReselectionEquivalence
        finiteNonIsoDiagnosticDiagramHom finiteNonIsoDiagnosticSource 1 :=
      (map_one (indexedDiagnosticReselectionEquivalence
        finiteNonIsoDiagnosticDiagramHom finiteNonIsoDiagnosticSource)).symm

/-- The source reselection is recovered after the forward-inverse round trip. -/
theorem finiteNonIsoDiagnostic_sourceReselection_roundTrip :
    finiteNonIsoDiagnosticDiagramHom.inverseTransportedReselection
        finiteNonIsoDiagnosticSource
        (finiteNonIsoDiagnosticDiagramHom.transportedReselection
          finiteNonIsoDiagnosticSource finiteNonIsoDiagnosticSourceReselection) =
      finiteNonIsoDiagnosticSourceReselection :=
  IndexedBaseDiagramHom.inverseTransportedReselection_transportedReselection
    finiteNonIsoDiagnosticDiagramHom finiteNonIsoDiagnosticSource
    finiteNonIsoDiagnosticSourceReselection

/-- The transported reselection is recovered after the inverse-forward round trip. -/
theorem finiteNonIsoDiagnostic_targetReselection_roundTrip :
    finiteNonIsoDiagnosticDiagramHom.transportedReselection
        finiteNonIsoDiagnosticSource
        (finiteNonIsoDiagnosticDiagramHom.inverseTransportedReselection
          finiteNonIsoDiagnosticSource
          (finiteNonIsoDiagnosticDiagramHom.transportedReselection
            finiteNonIsoDiagnosticSource finiteNonIsoDiagnosticSourceReselection)) =
      finiteNonIsoDiagnosticDiagramHom.transportedReselection
        finiteNonIsoDiagnosticSource finiteNonIsoDiagnosticSourceReselection :=
  IndexedBaseDiagramHom.transportedReselection_inverseTransportedReselection
    finiteNonIsoDiagnosticDiagramHom finiteNonIsoDiagnosticSource _

/-- The transported raw defect at the same reselection is nonidentity. -/
theorem finiteNonIsoDiagnostic_transportedSourceReselectionRawDefect_ne_one :
    rawDefectCochain
        (finiteNonIsoDiagnosticDiagramHom.transportedInterpretation
          finiteNonIsoDiagnosticSource).toAdmissibleTransportData
        (finiteNonIsoDiagnosticDiagramHom.transportedReselection
          finiteNonIsoDiagnosticSource
          finiteNonIsoDiagnosticSourceReselection) indexedCovarianceFace ≠ 1 := by
  intro equality
  apply finiteNonIsoDiagnostic_sourceReselectionRawDefect_ne_one
  have pointwise := congrFun
    (IndexedBaseDiagramHom.indexedDiagnosticDefectCochain_via_horizontalPasting
      finiteNonIsoDiagnosticDiagramHom finiteNonIsoDiagnosticSource
        finiteNonIsoDiagnosticSourceReselection)
      indexedCovarianceFace
  have mappedOne := map_one
    (indexedDiagnosticEndpointEquivalence finiteNonIsoDiagnosticDiagramHom
      finiteNonIsoDiagnosticSource indexedCovarianceTargetVertex)
  apply (indexedDiagnosticEndpointEquivalence finiteNonIsoDiagnosticDiagramHom
    finiteNonIsoDiagnosticSource indexedCovarianceTargetVertex).injective
  calc
    _ = rawDefectCochain
        (finiteNonIsoDiagnosticDiagramHom.transportedInterpretation
          finiteNonIsoDiagnosticSource).toAdmissibleTransportData
        (finiteNonIsoDiagnosticDiagramHom.transportedReselection
          finiteNonIsoDiagnosticSource
          finiteNonIsoDiagnosticSourceReselection) indexedCovarianceFace := by
      simpa [indexedDiagnosticDefectCochainEquivalence_apply,
        indexedCovarianceTargetVertex, indexedCovarianceFace,
        indexedCovarianceShape] using pointwise
    _ = 1 := equality
    _ = _ := mappedOne.symm

/-- The source raw cochain is recovered after its forward-inverse round trip. -/
theorem finiteNonIsoDiagnostic_sourceDefect_roundTrip :
    (indexedDiagnosticDefectCochainEquivalence finiteNonIsoDiagnosticDiagramHom
      finiteNonIsoDiagnosticSource).symm
        (indexedDiagnosticDefectCochainEquivalence finiteNonIsoDiagnosticDiagramHom
          finiteNonIsoDiagnosticSource
          (rawDefectCochain
            finiteNonIsoDiagnosticSource.toAdmissibleTransportData
              finiteNonIsoDiagnosticSourceReselection)) =
      rawDefectCochain
        finiteNonIsoDiagnosticSource.toAdmissibleTransportData
          finiteNonIsoDiagnosticSourceReselection :=
  (indexedDiagnosticDefectCochainEquivalence finiteNonIsoDiagnosticDiagramHom
    finiteNonIsoDiagnosticSource).symm_apply_apply _

/-- The transported raw cochain is recovered after its inverse-forward round trip. -/
theorem finiteNonIsoDiagnostic_targetDefect_roundTrip :
    indexedDiagnosticDefectCochainEquivalence finiteNonIsoDiagnosticDiagramHom
        finiteNonIsoDiagnosticSource
        ((indexedDiagnosticDefectCochainEquivalence
          finiteNonIsoDiagnosticDiagramHom finiteNonIsoDiagnosticSource).symm
          (rawDefectCochain
            (finiteNonIsoDiagnosticDiagramHom.transportedInterpretation
              finiteNonIsoDiagnosticSource).toAdmissibleTransportData
            (finiteNonIsoDiagnosticDiagramHom.transportedReselection
              finiteNonIsoDiagnosticSource
              finiteNonIsoDiagnosticSourceReselection))) =
      rawDefectCochain
        (finiteNonIsoDiagnosticDiagramHom.transportedInterpretation
          finiteNonIsoDiagnosticSource).toAdmissibleTransportData
        (finiteNonIsoDiagnosticDiagramHom.transportedReselection
          finiteNonIsoDiagnosticSource
          finiteNonIsoDiagnosticSourceReselection) :=
  (indexedDiagnosticDefectCochainEquivalence finiteNonIsoDiagnosticDiagramHom
    finiteNonIsoDiagnosticSource).apply_symm_apply _

/-- The finite base component refutes the converse from fiber equivalence. -/
theorem finiteNonIsoDiagnostic_converse_refutation :
    (¬ IsIso
      (finiteNonIsoDiagnosticDiagramHom.app indexedCovarianceTargetVertex)) ∧
      (indexedDiagnosticTransportPush finiteNonIsoDiagnosticDiagramHom
        indexedCovarianceTargetVertex).IsEquivalence :=
  ⟨finiteNonIsoDiagnosticDiagramHom_not_isIso _,
    IndexedBaseDiagramHom.indexedDiagnosticTransport_isEquivalence_arbitraryBase
      finiteNonIsoDiagnosticDiagramHom _⟩

/-- Defect and reselection nonidentity fire on the same named finite witness. -/
theorem finiteNonIsoDiagnostic_sameWitness_nondegeneracy :
    rawDefectCochain
          finiteNonIsoDiagnosticSource.toAdmissibleTransportData
          finiteNonIsoDiagnosticSourceReselection indexedCovarianceFace ≠ 1 ∧
      rawDefectCochain
          (finiteNonIsoDiagnosticDiagramHom.transportedInterpretation
            finiteNonIsoDiagnosticSource).toAdmissibleTransportData
          (finiteNonIsoDiagnosticDiagramHom.transportedReselection
            finiteNonIsoDiagnosticSource
            finiteNonIsoDiagnosticSourceReselection) indexedCovarianceFace ≠ 1 ∧
      finiteNonIsoDiagnosticSourceReselection ≠ 1 ∧
      finiteNonIsoDiagnosticDiagramHom.transportedReselection
          finiteNonIsoDiagnosticSource
          finiteNonIsoDiagnosticSourceReselection ≠ 1 :=
  ⟨finiteNonIsoDiagnostic_sourceReselectionRawDefect_ne_one,
    finiteNonIsoDiagnostic_transportedSourceReselectionRawDefect_ne_one,
    finiteNonIsoDiagnosticSourceReselection_ne_one,
    finiteNonIsoDiagnostic_transportedReselection_ne_one⟩

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
