import ResearchLean.AG.DiagnosticConservativity.PathSquareCompatibility

/-!
# G-113 revision 2 downstream path-square compatibility

Every authored two-cell has two finite paths. Their path squares are generated
recursively by horizontal pasting, so they form the two path faces of the
diagnostic transport cube. This module records those faces together with the
comparator and raw-defect faces, and then derives cochain, orbit, coherence,
and obstruction exactness from the cube.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation
open CrossStageCoherence
open TransportCoherence

namespace IndexedBaseDiagramHom

private theorem packageTotalHom_comp_assoc'
    {U : AtomCarrier.{u}} {P Q R S : AATCorePackage U}
    (first : PackageTotalHom P Q) (second : PackageTotalHom Q R)
    (third : PackageTotalHom R S) :
    first.comp (second.comp third) = (first.comp second).comp third := by
  let packageCategory : Category (AATCorePackage U) := inferInstance
  exact (@Category.assoc (AATCorePackage U) packageCategory
    P Q R S first second third).symm

/-- A nonempty indexed path is its first edge pasted horizontally with its tail. -/
theorem indexedDiagnosticPathSquare_via_horizontalRoute
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (reselection : IndexedEdgeReselection source) {i j : G.Vertex}
    (path : IndexedBasePath G.toIndexedBaseShape i j) :
    (hom.diagnosticVertexLift source i).comp
        ((hom.transportedInterpretation source).reselectedPathLift
          (indexedDiagnosticReselectionEquivalence hom source reselection) path) =
      (source.reselectedPathLift reselection path).comp
        (hom.diagnosticVertexLift source j) := by
  cases path with
  | nil _ =>
      exact hom.indexedDiagnosticPathSquare_commutes source reselection (.nil _)
  | @cons _ middle target edge tail =>
      simpa only [IndexedBasePath.append,
        IndexedDiagnosticInterpretation.reselectedPathLift] using
        hom.indexedDiagnosticHorizontalPathPasting_eq_pathSquare source reselection
          (.cons edge (.nil middle)) tail

/-- The inverse path square is generated by the same recursive horizontal route. -/
theorem indexedDiagnosticPathSquare_inverse_via_horizontalRoute
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (targetReselection : IndexedEdgeReselection
      (hom.transportedInterpretation source)) {i j : G.Vertex}
    (path : IndexedBasePath G.toIndexedBaseShape i j) :
    (hom.diagnosticVertexLift source i).comp
        ((hom.transportedInterpretation source).reselectedPathLift
          targetReselection path) =
      (source.reselectedPathLift
        (hom.inverseTransportedReselection source targetReselection) path).comp
          (hom.diagnosticVertexLift source j) := by
  cases path with
  | nil _ =>
      exact hom.indexedDiagnosticPathSquare_inverse_commutes source
        targetReselection (.nil _)
  | @cons _ middle target edge tail =>
      simpa only [IndexedBasePath.append,
        IndexedDiagnosticInterpretation.reselectedPathLift] using
        hom.indexedDiagnosticHorizontalPathPasting_inverse_eq_pathSquare source
          targetReselection (.cons edge (.nil middle)) tail

/-- Coherence preservation with both path faces supplied by horizontal pasting. -/
theorem indexedCoherentAt_transport_via_horizontalPasting
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (reselection : IndexedEdgeReselection source)
    (coherent : source.IndexedCoherentAt reselection) :
    (hom.transportedInterpretation source).IndexedCoherentAt
      (hom.transportedReselection source reselection) := by
  intro cell
  let vertexLift := hom.diagnosticVertexLift source (G.twoSource cell)
  let targetLeft :=
    ((hom.transportedInterpretation source).reselectedPathLift
      (hom.transportedReselection source reselection) (G.twoLeft cell)).comp
        (PackageFiberAut.hom
          ((hom.transportedInterpretation source).comparator cell))
  let targetRight :=
    (hom.transportedInterpretation source).reselectedPathLift
      (hom.transportedReselection source reselection) (G.twoRight cell)
  letI : (packageProjection U).IsStronglyCocartesian
      (hom.app (G.twoSource cell)) vertexLift :=
    hom.diagnosticVertexLift_isStronglyCocartesian source _
  letI : (packageProjection U).IsHomLift
      (E.path (G.twoLeft cell))
      ((hom.transportedInterpretation source).reselectedPathLift
        (hom.transportedReselection source reselection) (G.twoLeft cell)) :=
    (hom.transportedInterpretation source).reselectedPathLift_isHomLift _ _
  letI : (packageProjection U).IsHomLift
      (𝟙 (E.vertex (G.twoTarget cell)))
      (PackageFiberAut.hom
        ((hom.transportedInterpretation source).comparator cell)) := by
    apply CategoryTheory.IsHomLift.of_commsq
      (packageProjection U) (𝟙 (E.vertex (G.twoTarget cell)))
      (PackageFiberAut.hom
        ((hom.transportedInterpretation source).comparator cell))
      ((hom.transportedInterpretation source).vertexBase (G.twoTarget cell))
      ((hom.transportedInterpretation source).vertexBase (G.twoTarget cell))
    rw [packageProjection_map, PackageFiberAut.hom_base_eq, Category.comp_id]
    exact Category.id_comp _
  letI : (packageProjection U).IsHomLift
      (E.path (G.twoLeft cell)) targetLeft := by
    have composite : (packageProjection U).IsHomLift
        (E.path (G.twoLeft cell) ≫ 𝟙 (E.vertex (G.twoTarget cell)))
        targetLeft := CategoryTheory.IsHomLift.comp
          (packageProjection U) (E.path (G.twoLeft cell))
          (𝟙 (E.vertex (G.twoTarget cell)))
          ((hom.transportedInterpretation source).reselectedPathLift
            (hom.transportedReselection source reselection) (G.twoLeft cell))
          (PackageFiberAut.hom
            ((hom.transportedInterpretation source).comparator cell))
    simpa using composite
  letI : (packageProjection U).IsHomLift
      (E.path (G.twoLeft cell)) targetRight := by
    rw [E.relation_path cell]
    exact (hom.transportedInterpretation source).reselectedPathLift_isHomLift _ _
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) (hom.app (G.twoSource cell)) vertexLift
    (E.path (G.twoLeft cell))
  dsimp only [vertexLift, targetLeft, targetRight]
  calc
    _ = ((hom.diagnosticVertexLift source (G.twoSource cell)).comp
          ((hom.transportedInterpretation source).reselectedPathLift
            (hom.transportedReselection source reselection)
            (G.twoLeft cell))).comp
          (PackageFiberAut.hom
            ((hom.transportedInterpretation source).comparator cell)) :=
        packageTotalHom_comp_assoc' _ _ _
    _ = ((source.reselectedPathLift reselection (G.twoLeft cell)).comp
          (hom.diagnosticVertexLift source (G.twoTarget cell))).comp
          (PackageFiberAut.hom
            ((hom.transportedInterpretation source).comparator cell)) := by
        have face := hom.indexedDiagnosticPathSquare_via_horizontalRoute source
          reselection (G.twoLeft cell)
        rw [indexedDiagnosticReselectionEquivalence_apply] at face
        rw [face]
    _ = (source.reselectedPathLift reselection (G.twoLeft cell)).comp
          ((hom.diagnosticVertexLift source (G.twoTarget cell)).comp
            (PackageFiberAut.hom
              ((hom.transportedInterpretation source).comparator cell))) :=
        (packageTotalHom_comp_assoc' _ _ _).symm
    _ = (source.reselectedPathLift reselection (G.twoLeft cell)).comp
          ((PackageFiberAut.hom (source.comparator cell)).comp
            (hom.diagnosticVertexLift source (G.twoTarget cell))) := by
        rw [hom.diagnosticVertexLift_comparator_naturality source cell]
    _ = ((source.reselectedPathLift reselection (G.twoLeft cell)).comp
          (PackageFiberAut.hom (source.comparator cell))).comp
            (hom.diagnosticVertexLift source (G.twoTarget cell)) :=
        packageTotalHom_comp_assoc' _ _ _
    _ = (source.reselectedPathLift reselection (G.twoRight cell)).comp
          (hom.diagnosticVertexLift source (G.twoTarget cell)) := by
        rw [coherent cell]
    _ = _ := by
      have face := hom.indexedDiagnosticPathSquare_via_horizontalRoute source
        reselection (G.twoRight cell)
      rw [indexedDiagnosticReselectionEquivalence_apply] at face
      exact face.symm

/-- Canonical comparator transport obtained from the horizontal-pasting proof. -/
theorem endpointAction_canonicalTwoCellComparator_via_horizontalPasting
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (reselection : IndexedEdgeReselection source) (cell : G.TwoCell) :
    hom.endpointAction source (G.twoTarget cell)
        (canonicalTwoCellComparator source.toAdmissibleTransportData
          reselection cell) =
      canonicalTwoCellComparator
        (hom.transportedInterpretation source).toAdmissibleTransportData
        (hom.transportedReselection source reselection) cell := by
  let canonicalized := canonicalizedDiagnosticInterpretation source reselection
  let targetLeft :=
    TransportCoherence.reselectedPathLift
      (hom.transportedInterpretation source).toAdmissibleTransportData.lift
      (hom.transportedReselection source reselection)
      (G.twoLeft cell).toPresentedPath
  letI : (packageProjection U).IsStronglyCocartesian
      targetLeft.base targetLeft :=
    TransportCoherence.reselectedPathLift_isStronglyCocartesian
      (hom.transportedInterpretation source).toAdmissibleTransportData.lift
      (hom.transportedReselection source reselection)
      (G.twoLeft cell).toPresentedPath
  apply PackageFiberAut.ext_of_strong_fac targetLeft
  have transportedCoherent :=
    hom.indexedCoherentAt_transport_via_horizontalPasting canonicalized
      reselection (canonicalizedDiagnosticInterpretation_coherent source reselection)
  calc
    targetLeft.comp
        (PackageFiberAut.hom
          (hom.endpointAction source (G.twoTarget cell)
            (canonicalTwoCellComparator source.toAdmissibleTransportData
              reselection cell))) =
      (hom.transportedInterpretation source).reselectedPathLift
        (hom.transportedReselection source reselection)
        (G.twoRight cell) := by
          have mapped := transportedCoherent cell
          dsimp only [canonicalized] at mapped
          rw [transportedCanonicalized_reselectedPathLift,
            transportedCanonicalized_reselectedPathLift] at mapped
          dsimp only [targetLeft]
          rw [(hom.transportedInterpretation source).toAdmissibleTransportData_reselectedPathLift
            (hom.transportedReselection source reselection)]
          simpa only [transportedInterpretation_comparator,
            endpointAction_canonicalizedDiagnosticInterpretation,
            canonicalizedDiagnosticInterpretation_comparator] using mapped
    _ = targetLeft.comp
        (PackageFiberAut.hom
          (canonicalTwoCellComparator
            (hom.transportedInterpretation source).toAdmissibleTransportData
            (hom.transportedReselection source reselection) cell)) := by
      dsimp only [targetLeft]
      have fac := (canonicalTwoCellComparator_fac
        (hom.transportedInterpretation source).toAdmissibleTransportData
        (hom.transportedReselection source reselection) cell).symm
      rw [(hom.transportedInterpretation source).toAdmissibleTransportData_reselectedPathLift
        (hom.transportedReselection source reselection)] at fac
      exact fac

/--
The four commuting faces of diagnostic transport at one authored two-cell.
The two path faces use the actual horizontal-pasting theorem; the comparator
face then determines the raw-defect face.
-/
structure IndexedDiagnosticTwoCellPastingCube
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (reselection : IndexedEdgeReselection source) (cell : G.TwoCell) : Prop where
  leftRoute :
    (hom.pathSquare (G.twoLeft cell)).route = (G.twoLeft cell).squareRoute
  rightRoute :
    (hom.pathSquare (G.twoRight cell)).route = (G.twoRight cell).squareRoute
  leftFace :
    (hom.diagnosticVertexLift source (G.twoSource cell)).comp
        ((hom.transportedInterpretation source).reselectedPathLift
          (indexedDiagnosticReselectionEquivalence hom source reselection)
          (G.twoLeft cell)) =
      (source.reselectedPathLift reselection (G.twoLeft cell)).comp
        (hom.diagnosticVertexLift source (G.twoTarget cell))
  rightFace :
    (hom.diagnosticVertexLift source (G.twoSource cell)).comp
        ((hom.transportedInterpretation source).reselectedPathLift
          (indexedDiagnosticReselectionEquivalence hom source reselection)
          (G.twoRight cell)) =
      (source.reselectedPathLift reselection (G.twoRight cell)).comp
        (hom.diagnosticVertexLift source (G.twoTarget cell))
  comparatorFace :
    hom.endpointAction source (G.twoTarget cell)
        (canonicalTwoCellComparator source.toAdmissibleTransportData
          reselection cell) =
      canonicalTwoCellComparator
        (hom.transportedInterpretation source).toAdmissibleTransportData
        (hom.transportedReselection source reselection) cell
  defectFace :
    indexedDiagnosticEndpointEquivalence hom source (G.twoTarget cell)
        (rawTwoCellDefect source.toAdmissibleTransportData reselection cell) =
      rawTwoCellDefect
        (hom.transportedInterpretation source).toAdmissibleTransportData
        (hom.transportedReselection source reselection) cell

/-- Generate the complete forward two-cell cube from horizontal path pasting. -/
theorem indexedDiagnosticTwoCellPastingCube
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (reselection : IndexedEdgeReselection source) (cell : G.TwoCell) :
    IndexedDiagnosticTwoCellPastingCube hom source reselection cell where
  leftRoute := rfl
  rightRoute := rfl
  leftFace := hom.indexedDiagnosticPathSquare_via_horizontalRoute source
    reselection (G.twoLeft cell)
  rightFace := hom.indexedDiagnosticPathSquare_via_horizontalRoute source
    reselection (G.twoRight cell)
  comparatorFace :=
    hom.endpointAction_canonicalTwoCellComparator_via_horizontalPasting source
      reselection cell
  defectFace := by
    rw [indexedDiagnosticEndpointEquivalence_apply]
    unfold rawTwoCellDefect
    rw [map_mul, map_inv]
    rw [hom.endpointAction_canonicalTwoCellComparator_via_horizontalPasting
      source reselection cell]
    rfl

/-- Raw-defect cochain transport is derived cellwise from the pasting cubes. -/
theorem indexedDiagnosticDefectCochain_via_horizontalPasting
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (reselection : IndexedEdgeReselection source) :
    indexedDiagnosticDefectCochainEquivalence hom source
        (rawDefectCochain source.toAdmissibleTransportData reselection) =
      rawDefectCochain
        (hom.transportedInterpretation source).toAdmissibleTransportData
        (hom.transportedReselection source reselection) := by
  funext cell
  exact (hom.indexedDiagnosticTwoCellPastingCube source reselection cell).defectFace

/-- Inverse cochain transport follows from the forward cubes and the round trip. -/
theorem indexedDiagnosticDefectCochain_inverse_via_horizontalPasting
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (targetReselection : IndexedEdgeReselection
      (hom.transportedInterpretation source)) :
    (indexedDiagnosticDefectCochainEquivalence hom source).symm
        (rawDefectCochain
          (hom.transportedInterpretation source).toAdmissibleTransportData
          targetReselection) =
      rawDefectCochain source.toAdmissibleTransportData
        (hom.inverseTransportedReselection source targetReselection) := by
  apply (indexedDiagnosticDefectCochainEquivalence hom source).injective
  rw [(indexedDiagnosticDefectCochainEquivalence hom source).apply_symm_apply]
  rw [hom.indexedDiagnosticDefectCochain_via_horizontalPasting source]
  rw [hom.transportedReselection_inverseTransportedReselection]

/-- Orbit exactness factors through the horizontal-pasting cochain theorem. -/
theorem indexedDiagnosticOrbit_via_horizontalPasting
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (cochain : DefectCochain source.toAdmissibleTransportData) :
    InReselectionOrbit source.toAdmissibleTransportData cochain ↔
      InReselectionOrbit
        (hom.transportedInterpretation source).toAdmissibleTransportData
        (indexedDiagnosticDefectCochainEquivalence hom source cochain) := by
  constructor
  · rintro ⟨reselection, equality⟩
    refine ⟨hom.transportedReselection source reselection, ?_⟩
    rw [← hom.indexedDiagnosticDefectCochain_via_horizontalPasting source]
    exact congrArg (indexedDiagnosticDefectCochainEquivalence hom source) equality
  · rintro ⟨targetReselection, equality⟩
    refine ⟨hom.inverseTransportedReselection source targetReselection, ?_⟩
    rw [← hom.indexedDiagnosticDefectCochain_inverse_via_horizontalPasting source]
    rw [equality]
    exact (indexedDiagnosticDefectCochainEquivalence hom source).symm_apply_apply
      cochain

/-- Coherence exactness factors through raw-cochain identity and the cubes. -/
theorem indexedDiagnosticCoherence_via_horizontalPasting
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D)
    (reselection : IndexedEdgeReselection source) :
    source.IndexedCoherentAt reselection ↔
      (hom.transportedInterpretation source).IndexedCoherentAt
        (hom.transportedReselection source reselection) := by
  rw [source.indexedCoherentAt_iff_adaptedCoherentAt,
    (hom.transportedInterpretation source).indexedCoherentAt_iff_adaptedCoherentAt,
    coherentAt_iff_rawDefectCochain_eq_identity,
    coherentAt_iff_rawDefectCochain_eq_identity]
  have mapIdentity :
      indexedDiagnosticDefectCochainEquivalence hom source
          (identityDefectCochain source.toAdmissibleTransportData) =
        identityDefectCochain
          (hom.transportedInterpretation source).toAdmissibleTransportData := by
    funext cell
    exact map_one (indexedDiagnosticEndpointEquivalence hom source
      (G.twoTarget cell))
  constructor
  · intro equality
    have mapped := congrArg
      (indexedDiagnosticDefectCochainEquivalence hom source) equality
    rw [hom.indexedDiagnosticDefectCochain_via_horizontalPasting source] at mapped
    rw [mapIdentity] at mapped
    exact mapped
  · intro equality
    have mapped := congrArg
      (indexedDiagnosticDefectCochainEquivalence hom source).symm equality
    rw [hom.indexedDiagnosticDefectCochain_inverse_via_horizontalPasting source]
      at mapped
    have symmMapIdentity := congrArg
      (indexedDiagnosticDefectCochainEquivalence hom source).symm mapIdentity
    rw [(indexedDiagnosticDefectCochainEquivalence hom source).symm_apply_apply]
      at symmMapIdentity
    rw [← symmMapIdentity] at mapped
    simpa only [hom.inverseTransportedReselection_transportedReselection source]
      using mapped

/-- Obstruction exactness is the orbit theorem at the identity cochain. -/
theorem indexedDiagnosticObstruction_via_horizontalPasting
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D) :
    TransportObstructionVanishes source.toAdmissibleTransportData ↔
      TransportObstructionVanishes
        (hom.transportedInterpretation source).toAdmissibleTransportData := by
  unfold TransportObstructionVanishes
  have orbit := hom.indexedDiagnosticOrbit_via_horizontalPasting source
    (identityDefectCochain source.toAdmissibleTransportData)
  have mapIdentity :
      indexedDiagnosticDefectCochainEquivalence hom source
          (identityDefectCochain source.toAdmissibleTransportData) =
        identityDefectCochain
          (hom.transportedInterpretation source).toAdmissibleTransportData := by
    funext cell
    exact map_one (indexedDiagnosticEndpointEquivalence hom source
      (G.twoTarget cell))
  rw [mapIdentity] at orbit
  exact orbit

/-- The downstream part of G-113(h), with every field derived from the cube. -/
structure IndexedDiagnosticPastingDownstreamExactness
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D) : Prop where
  twoCellCube : ∀ reselection cell,
    IndexedDiagnosticTwoCellPastingCube hom source reselection cell
  cochain : ∀ reselection,
    indexedDiagnosticDefectCochainEquivalence hom source
        (rawDefectCochain source.toAdmissibleTransportData reselection) =
      rawDefectCochain
        (hom.transportedInterpretation source).toAdmissibleTransportData
        (hom.transportedReselection source reselection)
  orbit : ∀ cochain : DefectCochain source.toAdmissibleTransportData,
    InReselectionOrbit source.toAdmissibleTransportData cochain ↔
      InReselectionOrbit
        (hom.transportedInterpretation source).toAdmissibleTransportData
        (indexedDiagnosticDefectCochainEquivalence hom source cochain)
  coherence : ∀ reselection : IndexedEdgeReselection source,
    source.IndexedCoherentAt reselection ↔
      (hom.transportedInterpretation source).IndexedCoherentAt
        (hom.transportedReselection source reselection)
  obstruction :
    TransportObstructionVanishes source.toAdmissibleTransportData ↔
      TransportObstructionVanishes
        (hom.transportedInterpretation source).toAdmissibleTransportData

/-- Generate the downstream exactness package through the cellwise pasting route. -/
theorem indexedDiagnosticPastingDownstreamExactness
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E : IndexedBaseDiagram G U} (hom : IndexedBaseDiagramHom D E)
    (source : IndexedDiagnosticInterpretation D) :
    IndexedDiagnosticPastingDownstreamExactness hom source where
  twoCellCube := hom.indexedDiagnosticTwoCellPastingCube source
  cochain := hom.indexedDiagnosticDefectCochain_via_horizontalPasting source
  orbit := hom.indexedDiagnosticOrbit_via_horizontalPasting source
  coherence := hom.indexedDiagnosticCoherence_via_horizontalPasting source
  obstruction := hom.indexedDiagnosticObstruction_via_horizontalPasting source

end IndexedBaseDiagramHom

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
