import ResearchLean.AG.DiagnosticConservativity.PentagonCochainCompatibility
import ResearchLean.AG.DoctrineFiberProduct.BCDiagnosticNaturalIsoTransport

/-!
# G-113 revision 2 whole-pentagon orbit compatibility

The explicit whole-pentagon cochain comparison carries direct three-arrow
transport to successive transport.  This application equation is then used
to transport the complete existential witness defining `InReselectionOrbit`
for every cochain at the direct target.

## Implementation notes

The left route is used for the witness calculation because it is generated by
the two reviewed binary compositors without an associativity cast.  The right
route is connected through the proved whole-pentagon equality.  A proof from
cochain-map equality alone was rejected: orbit membership is instead moved
through the three generated source/target equivalences, so both directions
construct an actual reselection witness.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation
open CrossStageCoherence
open TransportCoherence

namespace IndexedBaseDiagramHom

/-- The left whole-pentagon cochain comparison sends direct three-arrow
transport of every source cochain to its successive three-step transport. -/
theorem indexedDiagnosticPentagonMateLeftDefectCochainEquivalence_transport_apply
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E F H : IndexedBaseDiagram G U}
    (first : IndexedBaseDiagramHom D E)
    (second : IndexedBaseDiagramHom E F)
    (third : IndexedBaseDiagramHom F H)
    (source : IndexedDiagnosticInterpretation D)
    (cochain : DefectCochain source.toAdmissibleTransportData) :
    indexedDiagnosticPentagonMateLeftDefectCochainEquivalence
        first second third source
        (indexedDiagnosticDefectCochainEquivalence
          ((first.comp second).comp third) source cochain) =
      indexedDiagnosticDefectCochainEquivalence third
        (second.transportedInterpretation
          (first.transportedInterpretation source))
        (indexedDiagnosticDefectCochainEquivalence second
          (first.transportedInterpretation source)
          (indexedDiagnosticDefectCochainEquivalence first source cochain)) := by
  funext cell
  rw [indexedDiagnosticPentagonMateLeftDefectCochainEquivalence_apply]
  rw [indexedDiagnosticPentagonMateLeftEndpointEquivalence_eq_g111]
  rw [indexedDiagnosticDefectCochainEquivalence_apply,
    indexedDiagnosticDefectCochainEquivalence_apply,
    indexedDiagnosticDefectCochainEquivalence_apply,
    indexedDiagnosticDefectCochainEquivalence_apply]
  rw [indexedDiagnosticEndpointEquivalence_apply,
    indexedDiagnosticEndpointEquivalence_apply,
    indexedDiagnosticEndpointEquivalence_apply,
    indexedDiagnosticEndpointEquivalence_apply]
  unfold indexedDiagnosticPentagonG111LeftEndpointEquivalence
  unfold coreFiberPentagonLeftRouteIso
  change packageFiberAutMulEquivOfCoreFiberIso
      ((coreFiberCompositor
          (first.app (G.twoTarget cell) ≫ second.app (G.twoTarget cell))
          (third.app (G.twoTarget cell))).app
            (source.fiberPackage (G.twoTarget cell)) ≪≫
        (CategoryTheory.Functor.isoWhiskerRight
          (coreFiberCompositor
            (first.app (G.twoTarget cell)) (second.app (G.twoTarget cell)))
          (coreFiberTransportFunctor
            (third.app (G.twoTarget cell)))).app
              (source.fiberPackage (G.twoTarget cell))) _ = _
  rw [packageFiberAutMulEquivOfCoreFiberIso_trans]
  have firstStage :=
    indexedDiagnosticCompositionMateEndpointCompositorEquivalence_apply
      (first.comp second) third source (G.twoTarget cell) (cochain cell)
  rw [indexedDiagnosticCompositionMateEndpointCompositorEquivalence_eq_g111]
    at firstStage
  rw [indexedDiagnosticEndpointEquivalence_apply,
    indexedDiagnosticEndpointEquivalence_apply,
    indexedDiagnosticEndpointEquivalence_apply] at firstStage
  unfold indexedDiagnosticCompositionEndpointCompositorEquivalence at firstStage
  simp only [IndexedBaseDiagramHom.comp_app] at firstStage
  have mappedFirstStage := congrArg
    (packageFiberAutMulEquivOfCoreFiberIso
      ((CategoryTheory.Functor.isoWhiskerRight
        (coreFiberCompositor
          (first.app (G.twoTarget cell)) (second.app (G.twoTarget cell)))
        (coreFiberTransportFunctor
          (third.app (G.twoTarget cell)))).app
            (source.fiberPackage (G.twoTarget cell)))) firstStage
  refine mappedFirstStage.trans ?_
  have whiskerNaturality := coreFiberFunctorPackageAutHom_iso_naturality
    (CategoryTheory.Functor.isoWhiskerRight
      (coreFiberCompositor
        (first.app (G.twoTarget cell)) (second.app (G.twoTarget cell)))
      (coreFiberTransportFunctor (third.app (G.twoTarget cell))))
    (source.fiberPackage (G.twoTarget cell))
    (cochain cell)
  have directComp := congrArg (fun action => action (cochain cell))
    (coreFiberFunctorPackageAutHom_comp
      (coreFiberTransportFunctor
        (first.app (G.twoTarget cell) ≫ second.app (G.twoTarget cell)))
      (coreFiberTransportFunctor (third.app (G.twoTarget cell)))
      (source.fiberPackage (G.twoTarget cell)))
  have successiveComp := congrArg (fun action => action (cochain cell))
    (coreFiberFunctorPackageAutHom_comp
      (coreFiberTransportFunctor (first.app (G.twoTarget cell)) ⋙
        coreFiberTransportFunctor (second.app (G.twoTarget cell)))
      (coreFiberTransportFunctor (third.app (G.twoTarget cell)))
      (source.fiberPackage (G.twoTarget cell)))
  have pairComp := congrArg (fun action => action (cochain cell))
    (coreFiberFunctorPackageAutHom_comp
      (coreFiberTransportFunctor (first.app (G.twoTarget cell)))
      (coreFiberTransportFunctor (second.app (G.twoTarget cell)))
      (source.fiberPackage (G.twoTarget cell)))
  change packageFiberAutMulEquivOfCoreFiberIso
      ((CategoryTheory.Functor.isoWhiskerRight
        (coreFiberCompositor
          (first.app (G.twoTarget cell)) (second.app (G.twoTarget cell)))
        (coreFiberTransportFunctor (third.app (G.twoTarget cell)))).app
          (source.fiberPackage (G.twoTarget cell)))
      (coreFiberFunctorPackageAutHom
        (coreFiberTransportFunctor (third.app (G.twoTarget cell)))
        ((coreFiberTransportFunctor
          (first.app (G.twoTarget cell) ≫ second.app (G.twoTarget cell))).obj
            (source.fiberPackage (G.twoTarget cell)))
        (coreFiberFunctorPackageAutHom
          (coreFiberTransportFunctor
            (first.app (G.twoTarget cell) ≫ second.app (G.twoTarget cell)))
          (source.fiberPackage (G.twoTarget cell)) (cochain cell))) =
    coreFiberFunctorPackageAutHom
      (coreFiberTransportFunctor (third.app (G.twoTarget cell)))
      ((coreFiberTransportFunctor (first.app (G.twoTarget cell)) ⋙
        coreFiberTransportFunctor (second.app (G.twoTarget cell))).obj
          (source.fiberPackage (G.twoTarget cell)))
      (coreFiberFunctorPackageAutHom
        (coreFiberTransportFunctor (second.app (G.twoTarget cell)))
        ((coreFiberTransportFunctor (first.app (G.twoTarget cell))).obj
          (source.fiberPackage (G.twoTarget cell)))
        (coreFiberFunctorPackageAutHom
          (coreFiberTransportFunctor (first.app (G.twoTarget cell)))
          (source.fiberPackage (G.twoTarget cell)) (cochain cell)))
  calc
    _ = packageFiberAutMulEquivOfCoreFiberIso
        ((CategoryTheory.Functor.isoWhiskerRight
          (coreFiberCompositor
            (first.app (G.twoTarget cell)) (second.app (G.twoTarget cell)))
          (coreFiberTransportFunctor (third.app (G.twoTarget cell)))).app
            (source.fiberPackage (G.twoTarget cell)))
        (coreFiberFunctorPackageAutHom
          (coreFiberTransportFunctor
              (first.app (G.twoTarget cell) ≫ second.app (G.twoTarget cell)) ⋙
            coreFiberTransportFunctor (third.app (G.twoTarget cell)))
          (source.fiberPackage (G.twoTarget cell)) (cochain cell)) :=
      congrArg
        (packageFiberAutMulEquivOfCoreFiberIso
          ((CategoryTheory.Functor.isoWhiskerRight
            (coreFiberCompositor
              (first.app (G.twoTarget cell)) (second.app (G.twoTarget cell)))
            (coreFiberTransportFunctor (third.app (G.twoTarget cell)))).app
              (source.fiberPackage (G.twoTarget cell)))) directComp.symm
    _ = coreFiberFunctorPackageAutHom
        ((coreFiberTransportFunctor (first.app (G.twoTarget cell)) ⋙
          coreFiberTransportFunctor (second.app (G.twoTarget cell))) ⋙
            coreFiberTransportFunctor (third.app (G.twoTarget cell)))
        (source.fiberPackage (G.twoTarget cell)) (cochain cell) :=
      whiskerNaturality
    _ = coreFiberFunctorPackageAutHom
        (coreFiberTransportFunctor (third.app (G.twoTarget cell)))
        ((coreFiberTransportFunctor (first.app (G.twoTarget cell)) ⋙
          coreFiberTransportFunctor (second.app (G.twoTarget cell))).obj
            (source.fiberPackage (G.twoTarget cell)))
        (coreFiberFunctorPackageAutHom
          (coreFiberTransportFunctor (first.app (G.twoTarget cell)) ⋙
            coreFiberTransportFunctor (second.app (G.twoTarget cell)))
          (source.fiberPackage (G.twoTarget cell)) (cochain cell)) :=
      successiveComp
    _ = _ := congrArg
      (coreFiberFunctorPackageAutHom
        (coreFiberTransportFunctor (third.app (G.twoTarget cell)))
        ((coreFiberTransportFunctor (first.app (G.twoTarget cell)) ⋙
          coreFiberTransportFunctor (second.app (G.twoTarget cell))).obj
            (source.fiberPackage (G.twoTarget cell)))) pairComp

/-- The right whole-pentagon cochain comparison has the same generated
three-step application equation. -/
theorem indexedDiagnosticPentagonMateRightDefectCochainEquivalence_transport_apply
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E F H : IndexedBaseDiagram G U}
    (first : IndexedBaseDiagramHom D E)
    (second : IndexedBaseDiagramHom E F)
    (third : IndexedBaseDiagramHom F H)
    (source : IndexedDiagnosticInterpretation D)
    (cochain : DefectCochain source.toAdmissibleTransportData) :
    indexedDiagnosticPentagonMateRightDefectCochainEquivalence
        first second third source
        (indexedDiagnosticDefectCochainEquivalence
          ((first.comp second).comp third) source cochain) =
      indexedDiagnosticDefectCochainEquivalence third
        (second.transportedInterpretation
          (first.transportedInterpretation source))
        (indexedDiagnosticDefectCochainEquivalence second
          (first.transportedInterpretation source)
          (indexedDiagnosticDefectCochainEquivalence first source cochain)) := by
  rw [← indexedDiagnosticPentagonMateDefectCochainEquivalence_eq
    first second third source]
  exact indexedDiagnosticPentagonMateLeftDefectCochainEquivalence_transport_apply
    first second third source cochain

/-- Arbitrary direct three-arrow target orbit membership is invariant under
the generated left whole-pentagon comparison to successive transport. -/
theorem indexedDiagnosticPentagonInReselectionOrbit_mate_left_iff
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E F H : IndexedBaseDiagram G U}
    (first : IndexedBaseDiagramHom D E)
    (second : IndexedBaseDiagramHom E F)
    (third : IndexedBaseDiagramHom F H)
    (source : IndexedDiagnosticInterpretation D)
    (directCochain : DefectCochain
      (((first.comp second).comp third).transportedInterpretation source).toAdmissibleTransportData) :
    InReselectionOrbit
        (((first.comp second).comp third).transportedInterpretation source).toAdmissibleTransportData
        directCochain ↔
      InReselectionOrbit
        (third.transportedInterpretation
          (second.transportedInterpretation
            (first.transportedInterpretation source))).toAdmissibleTransportData
        (indexedDiagnosticPentagonMateLeftDefectCochainEquivalence
          first second third source directCochain) := by
  let sourceCochain :=
    (indexedDiagnosticDefectCochainEquivalence
      ((first.comp second).comp third) source).symm directCochain
  have directRoundTrip :
      indexedDiagnosticDefectCochainEquivalence
          ((first.comp second).comp third) source sourceCochain = directCochain := by
    exact (indexedDiagnosticDefectCochainEquivalence
      ((first.comp second).comp third) source).apply_symm_apply directCochain
  have pentagonEquation :=
    indexedDiagnosticPentagonMateLeftDefectCochainEquivalence_transport_apply
      first second third source sourceCochain
  rw [directRoundTrip] at pentagonEquation
  calc
    _ ↔ InReselectionOrbit source.toAdmissibleTransportData sourceCochain :=
      indexedDiagnosticInReselectionOrbit_symm_iff
        ((first.comp second).comp third) source directCochain
    _ ↔ InReselectionOrbit
        (first.transportedInterpretation source).toAdmissibleTransportData
        (indexedDiagnosticDefectCochainEquivalence first source sourceCochain) :=
      indexedDiagnosticInReselectionOrbit_iff first source sourceCochain
    _ ↔ InReselectionOrbit
        (second.transportedInterpretation
          (first.transportedInterpretation source)).toAdmissibleTransportData
        (indexedDiagnosticDefectCochainEquivalence second
          (first.transportedInterpretation source)
          (indexedDiagnosticDefectCochainEquivalence first source sourceCochain)) :=
      indexedDiagnosticInReselectionOrbit_iff second
        (first.transportedInterpretation source)
        (indexedDiagnosticDefectCochainEquivalence first source sourceCochain)
    _ ↔ InReselectionOrbit
        (third.transportedInterpretation
          (second.transportedInterpretation
            (first.transportedInterpretation source))).toAdmissibleTransportData
        (indexedDiagnosticDefectCochainEquivalence third
          (second.transportedInterpretation
            (first.transportedInterpretation source))
          (indexedDiagnosticDefectCochainEquivalence second
            (first.transportedInterpretation source)
            (indexedDiagnosticDefectCochainEquivalence first source sourceCochain))) :=
      indexedDiagnosticInReselectionOrbit_iff third
        (second.transportedInterpretation
          (first.transportedInterpretation source))
        (indexedDiagnosticDefectCochainEquivalence second
          (first.transportedInterpretation source)
          (indexedDiagnosticDefectCochainEquivalence first source sourceCochain))
    _ ↔ _ := by rw [← pentagonEquation]

/-- The right whole-pentagon comparison transports the same arbitrary-target
orbit witnesses as the left route. -/
theorem indexedDiagnosticPentagonInReselectionOrbit_mate_right_iff
    {G : IndexedBaseTwoShape.{u}} {U : AtomCarrier.{u}}
    {D E F H : IndexedBaseDiagram G U}
    (first : IndexedBaseDiagramHom D E)
    (second : IndexedBaseDiagramHom E F)
    (third : IndexedBaseDiagramHom F H)
    (source : IndexedDiagnosticInterpretation D)
    (directCochain : DefectCochain
      (((first.comp second).comp third).transportedInterpretation source).toAdmissibleTransportData) :
    InReselectionOrbit
        (((first.comp second).comp third).transportedInterpretation source).toAdmissibleTransportData
        directCochain ↔
      InReselectionOrbit
        (third.transportedInterpretation
          (second.transportedInterpretation
            (first.transportedInterpretation source))).toAdmissibleTransportData
        (indexedDiagnosticPentagonMateRightDefectCochainEquivalence
          first second third source directCochain) := by
  rw [← indexedDiagnosticPentagonMateDefectCochainEquivalence_eq
    first second third source]
  exact indexedDiagnosticPentagonInReselectionOrbit_mate_left_iff
    first second third source directCochain

end IndexedBaseDiagramHom

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
