import Formal.AG.Examples.FiniteModel
import Formal.AG.LawAlgebra.Correspondence
import Formal.AG.LawAlgebra.Nullstellensatz
import Formal.AG.LawAlgebra.StanleyReisner

noncomputable section

namespace AAT.AG
namespace LawAlgebra

universe u

namespace FiniteExamples

open MvPolynomial
open scoped BigOperators

namespace StanleyReisnerChart

/-- III.例5.6E: selected coordinates `E_W = {x,y,z}`. -/
abbrev Coord := Fin 3

/-- III.例5.6E: the forbidden support `{x,y}`. -/
def xySupport : Finset Coord :=
  {0, 1}

/-- III.例5.6E: square-free regime with the single forbidden support `{x,y}`. -/
def regime : StanleyReisner.SquareFreeWitnessRegime Coord where
  Forb S := S = xySupport

/-- III.例5.6E: the selected support `{x,y}` is forbidden. -/
theorem xy_forbidden :
    regime.Forb xySupport :=
  rfl

/-- III.例5.6E: the selected obstruction ideal is generated by `xy`. -/
theorem obstructionIdeal_eq_span_xy (k : Type u) [CommRing k] :
    StanleyReisner.SquareFreeWitnessRegime.obstructionIdeal Coord k regime =
      Ideal.span ({StanleyReisner.squareFreeMonomial Coord k xySupport} :
        Set (MvPolynomial Coord k)) := by
  classical
  rw [StanleyReisner.SquareFreeWitnessRegime.obstructionIdeal,
    StanleyReisner.SquareFreeWitnessRegime.supportIdeal]
  apply le_antisymm
  · apply Ideal.span_le.mpr
    rintro f ⟨S, hS, rfl⟩
    rw [hS]
    exact Ideal.subset_span (by simp)
  · apply Ideal.span_le.mpr
    intro f hf
    rw [Set.mem_singleton_iff.mp hf]
    exact Ideal.subset_span ⟨xySupport, rfl, rfl⟩

/-- III.例5.6E: the obstruction ideal agrees with the Stanley-Reisner ideal. -/
theorem obstructionIdeal_eq_stanleyReisnerIdeal (k : Type u) [CommRing k] :
    StanleyReisner.SquareFreeWitnessRegime.obstructionIdeal Coord k regime =
      StanleyReisner.SquareFreeWitnessRegime.stanleyReisnerIdeal Coord k
        (StanleyReisner.SquareFreeWitnessRegime.delta Coord regime) :=
  StanleyReisner.SquareFreeWitnessRegime.obstructionIdeal_eq_stanleyReisnerIdeal
    Coord k regime

/-- III.例5.6E: `{z}` is a face of `Delta_U(W)`. -/
theorem z_face :
    ({2} : Finset Coord) ∈
      (StanleyReisner.SquareFreeWitnessRegime.delta Coord regime).faces := by
  intro S hS hSsubset
  rw [hS] at hSsubset
  have hzero : (0 : Coord) ∈ ({2} : Finset Coord) := hSsubset (by simp [xySupport])
  simp at hzero

/-- III.例5.6E: `{x,y}` is not a face of `Delta_U(W)`. -/
theorem xy_not_face :
    xySupport ∉
      (StanleyReisner.SquareFreeWitnessRegime.delta Coord regime).faces := by
  intro h
  exact h xySupport rfl (fun x hx => hx)

end StanleyReisnerChart

namespace NSdepthExample

/-- III.例7.2D: one Boolean coordinate. -/
abbrev Coord := Unit

/-- III.例7.2D: the ideal `<x>`. -/
def xIdeal (k : Type u) [CommRing k] : Ideal (MvPolynomial Coord k) :=
  Ideal.span ({X Unit.unit} : Set (MvPolynomial Coord k))

/-- III.例7.2D: the ideal `<x - 1>`. -/
def xMinusOneIdeal (k : Type u) [CommRing k] : Ideal (MvPolynomial Coord k) :=
  Ideal.span ({X Unit.unit - 1} : Set (MvPolynomial Coord k))

/-- III.例7.2D: `1 = x - (x - 1)`. -/
theorem one_eq_x_sub_x_minus_one (k : Type u) [CommRing k] :
    (1 : MvPolynomial Coord k) = X Unit.unit - (X Unit.unit - 1) := by
  ring

/-- III.例7.2D: `<x> + <x - 1>` contains `1`. -/
theorem one_mem_x_sup_xMinusOne (k : Type u) [CommRing k] :
    (1 : MvPolynomial Coord k) ∈ xIdeal k ⊔ xMinusOneIdeal k := by
  classical
  rw [one_eq_x_sub_x_minus_one k]
  have hx : X Unit.unit ∈ xIdeal k ⊔ xMinusOneIdeal k :=
    Ideal.mem_sup_left (Ideal.subset_span (by simp : X Unit.unit ∈
      ({X Unit.unit} : Set (MvPolynomial Coord k))))
  have hxm : X Unit.unit - 1 ∈ xIdeal k ⊔ xMinusOneIdeal k :=
    Ideal.mem_sup_right (Ideal.subset_span (by simp : X Unit.unit - 1 ∈
      ({X Unit.unit - 1} : Set (MvPolynomial Coord k))))
  exact Ideal.sub_mem (xIdeal k ⊔ xMinusOneIdeal k) hx hxm

/-- III.例7.2D: concrete certificate payload over `Int` for `1 ∈ <x> + <x - 1>`. -/
structure UnitCertificate where
  label : Unit := Unit.unit
  unit_mem : (1 : MvPolynomial Coord Int) ∈ xIdeal Int ⊔ xMinusOneIdeal Int

/-- III.例7.2D: the concrete unit certificate generated by `1 = x - (x - 1)`. -/
def unitCertificate : UnitCertificate where
  label := Unit.unit
  unit_mem := one_mem_x_sup_xMinusOne Int

/-- III.例7.2D: the concrete unit certificate has display degree `1`. -/
def unitCertificateDegree (_c : UnitCertificate) : ℕ :=
  1

/-- III.例7.2D: certificate availability is generated by the concrete unit certificate. -/
def hasUnitCertificateAt (d : ℕ) : Prop :=
  ∃ c : UnitCertificate, unitCertificateDegree c ≤ d

/-- III.例7.2D: the concrete unit certificate is available in display degree `1`. -/
theorem hasUnitCertificateAt_one :
    hasUnitCertificateAt 1 :=
  ⟨unitCertificate, le_rfl⟩

/-- III.例7.2D: selected NSdepth profile with depth `1`, generated by the concrete certificate. -/
def nsdepthOneProfile : Nullstellensatz.NSdepthProfile where
  HasCertificateAt := hasUnitCertificateAt
  depth := 1
  depth_hasCertificate := hasUnitCertificateAt_one
  depth_minimal := by
    intro d hd
    rcases hd with ⟨cert, hcert⟩
    exact hcert

/-- III.例7.2D: the selected certificate display has `NSdepth = 1`. -/
theorem nsdepth_eq_one :
    nsdepthOneProfile.NSdepth = 1 :=
  rfl

end NSdepthExample

namespace CycleCorrespondenceExample

/-- III.R13: one coordinate recording the selected finite cycle witness. -/
abbrev Coord := Unit

/-- III.R13: the coordinate ring for the selected cycle witness. -/
abbrev CycleRing := MvPolynomial Coord Int

/-- III.R13: the selected cycle witness coordinate `c_ABC`. -/
def cycleCoordinate : CycleRing :=
  X Unit.unit

/-- III.R13: the finite cycle witness ideal `I_cycle = <c_ABC>`. -/
def cycleIdeal : Ideal CycleRing :=
  Ideal.span ({cycleCoordinate} : Set CycleRing)

/-- III.R13: the cycle witness coordinate belongs to `I_cycle`. -/
theorem cycleCoordinate_mem_cycleIdeal :
    cycleCoordinate ∈ cycleIdeal :=
  Ideal.subset_span (by simp [cycleCoordinate])

/-- III.R13: singleton selected law family whose witness ideal is `I_cycle`. -/
def cycleWitnessIdealFamily :
    ObstructionIdeal.SelectedLawWitnessIdealFamily CycleRing where
  LawIndex := PUnit
  selected _ := True
  witnessIdeal _ := cycleIdeal

/-- III.R13: the local obstruction ideal generated by the selected cycle law is `I_cycle`. -/
theorem localObstructionIdeal_eq_cycleIdeal :
    cycleWitnessIdealFamily.localObstructionIdeal = cycleIdeal := by
  apply le_antisymm
  · rw [ObstructionIdeal.SelectedLawWitnessIdealFamily.localObstructionIdeal_le_iff]
    intro index _hselected
    cases index
    rfl
  · exact ObstructionIdeal.SelectedLawWitnessIdealFamily.witnessIdeal_le_localObstructionIdeal
      CycleRing cycleWitnessIdealFamily (L := PUnit.unit) trivial

/-- III.R13: section evaluation at `c_ABC = 0`. -/
def zeroEval : CycleRing →+* Int :=
  MvPolynomial.eval₂Hom (RingHom.id Int) (fun _ : Coord => (0 : Int))

/-- III.R13: section evaluation at `c_ABC = 1`. -/
def oneEval : CycleRing →+* Int :=
  MvPolynomial.eval₂Hom (RingHom.id Int) (fun _ : Coord => (1 : Int))

/-- III.R13: lawful section data for the acyclic finite cycle witness. -/
def acyclicSectionData : LawfulLocus.LawfulSectionData CycleRing cycleIdeal where
  SectionRing := Int
  commRing := inferInstance
  pullback := zeroEval

/-- III.R13: violating section data for the cyclic finite cycle witness. -/
def cyclicSectionData : LawfulLocus.LawfulSectionData CycleRing cycleIdeal where
  SectionRing := Int
  commRing := inferInstance
  pullback := oneEval

/-- III.R13: the acyclic section pulls `I_cycle` back to zero. -/
theorem acyclic_pulledObstructionIdeal_eq_bot :
    acyclicSectionData.pulledObstructionIdeal = ⊥ := by
  rw [LawfulLocus.LawfulSectionData.pulledObstructionIdeal, acyclicSectionData,
    cycleIdeal, Ideal.map_span]
  simp [cycleCoordinate, zeroEval]

/-- III.R13: the cyclic witness section pulls `I_cycle` back to the unit ideal. -/
theorem cyclic_pulledObstructionIdeal_eq_top :
    cyclicSectionData.pulledObstructionIdeal = ⊤ := by
  rw [LawfulLocus.LawfulSectionData.pulledObstructionIdeal, cyclicSectionData,
    cycleIdeal, Ideal.map_span]
  simp [cycleCoordinate, oneEval]

/-- III.R13: the acyclic pulled lawful locus has a point. -/
theorem acyclic_pulled_lawful_locus_has_point :
    ∃ p : PrimeSpectrum Int,
      p ∈ LawfulLocus.lawfulLocus Int acyclicSectionData.pulledObstructionIdeal := by
  rw [acyclic_pulledObstructionIdeal_eq_bot]
  exact ⟨⟨⊥, inferInstance⟩, by simp [LawfulLocus.lawfulLocus]⟩

/-- III.R13: the cyclic pulled lawful locus has no point. -/
theorem cyclic_pulled_lawful_locus_no_point :
    ¬ ∃ p : PrimeSpectrum Int,
      p ∈ LawfulLocus.lawfulLocus Int cyclicSectionData.pulledObstructionIdeal := by
  rw [cyclic_pulledObstructionIdeal_eq_top]
  simp [LawfulLocus.lawfulLocus]

/-- III.R13: selected acyclic configuration for the theorem 11.1 finite example. -/
def acyclicConfiguration : AtomConfiguration FiniteModel.carrier where
  family := FiniteModel.allFamily
  relation _ _ := False
  identification _ _ := False

/-- III.R13: finite object with no selected cycle witness. -/
def acyclicObject : ArchitectureObject FiniteModel.carrier :=
  FiniteModel.objectOfConfiguration acyclicConfiguration

/-- III.R13: finite object with the selected cycle witness. -/
def cyclicObject : ArchitectureObject FiniteModel.carrier :=
  FiniteModel.object

/-- III.R13: the acyclic finite object satisfies the selected NoCycle law. -/
theorem acyclic_noCycleLaw_holds :
    FiniteModel.noCycleLaw.holds acyclicObject := by
  intro hcycle
  exact hcycle.1

/-- III.R13: the cyclic finite object violates the selected NoCycle law. -/
theorem cyclic_noCycleLaw_fails :
    ¬ FiniteModel.noCycleLaw.holds cyclicObject :=
  FiniteModel.cycle_obstruction_law_failure

/-- III.R13: the acyclic finite object is lawful in the singleton NoCycle universe. -/
theorem acyclic_lawfulness :
    Lawfulness acyclicObject FiniteModel.lawUniverse := by
  intro index _hrequired
  cases index
  exact acyclic_noCycleLaw_holds

/-- III.R13: the cyclic finite object is not lawful in the singleton NoCycle universe. -/
theorem cyclic_lawfulness_fails :
    ¬ Lawfulness cyclicObject FiniteModel.lawUniverse := by
  intro h
  exact cyclic_noCycleLaw_fails (h PUnit.unit rfl)

/-- III.R13: the cyclic witness section is not locally lawful. -/
theorem cyclicSection_not_lawful :
    ¬ cyclicSectionData.Lawful := by
  intro h
  have hone : (1 : Int) ∈ (⊥ : Ideal Int) := by
    rw [← h, cyclic_pulledObstructionIdeal_eq_top]
    trivial
  simp at hone

/-- III.R13: selected signature axes for the finite NoCycle model. -/
def signatureAxes : SignatureAxes FiniteModel.carrier where
  Axis := PUnit
  selected _ := True
  zero A _ := FiniteModel.noCycleLaw.holds A

/-- III.R13: signature-axis exactness for the singleton NoCycle universe. -/
theorem lawfulness_iff_signatureAxesZero (A : ArchitectureObject FiniteModel.carrier) :
    Lawfulness A FiniteModel.lawUniverse ↔ RequiredSignatureAxesZero A signatureAxes := by
  constructor
  · intro h axis _hselected
    cases axis
    exact h PUnit.unit rfl
  · intro h index _hrequired
    cases index
    exact h PUnit.unit trivial

/-- III.R13: theorem 11.1 assumptions for the selected acyclic finite cycle example. -/
def acyclicCorrespondenceAssumptions :
    Correspondence.LawfulnessIdealCorrespondenceAssumptions
      acyclicSectionData acyclicObject FiniteModel.lawUniverse signatureAxes
        FiniteModel.noCycleValuation where
  obstructionSoundness := by
    intro index
    cases index with
    | mk index hrequired =>
        cases index
        exact FiniteModel.noCycleSound
  obstructionCompleteness := by
    intro index
    cases index with
    | mk index hrequired =>
        cases index
        exact FiniteModel.noCycleComplete
  axisExactness := lawfulness_iff_signatureAxesZero acyclicObject
  uAdequateCover := True
  obstructionSheafDescent := True
  ringRestrictionCompatibility := True
  witnessCoverage := by
    intro _hcover _hdescent _hring
    constructor
    · intro _hsection index _hrequired
      cases index
      exact acyclic_noCycleLaw_holds
    · intro _hsemantic
      exact acyclic_pulledObstructionIdeal_eq_bot
  uAdequateCover_holds := trivial
  obstructionSheafDescent_holds := trivial
  ringRestrictionCompatibility_holds := trivial

/-- III.R13: theorem 11.1 assumptions for the selected cyclic finite cycle example. -/
def cyclicCorrespondenceAssumptions :
    Correspondence.LawfulnessIdealCorrespondenceAssumptions
      cyclicSectionData cyclicObject FiniteModel.lawUniverse signatureAxes
        FiniteModel.noCycleValuation where
  obstructionSoundness := by
    intro index
    cases index with
    | mk index hrequired =>
        cases index
        exact FiniteModel.noCycleSound
  obstructionCompleteness := by
    intro index
    cases index with
    | mk index hrequired =>
        cases index
        exact FiniteModel.noCycleComplete
  axisExactness := lawfulness_iff_signatureAxesZero cyclicObject
  uAdequateCover := True
  obstructionSheafDescent := True
  ringRestrictionCompatibility := True
  witnessCoverage := by
    intro _hcover _hdescent _hring
    constructor
    · intro hsection
      exact False.elim (cyclicSection_not_lawful hsection)
    · intro hsemantic
      exact False.elim (cyclic_lawfulness_fails hsemantic)
  uAdequateCover_holds := trivial
  obstructionSheafDescent_holds := trivial
  ringRestrictionCompatibility_holds := trivial

/-- III.R13: theorem 11.1 finite example package for the selected acyclic cycle model. -/
def acyclicCorrespondencePackage :
    Correspondence.LawfulnessIdealCorrespondencePackage
      acyclicSectionData acyclicObject FiniteModel.lawUniverse signatureAxes
        FiniteModel.noCycleValuation FiniteModel.singletonRequiredAggregation
          acyclicCorrespondenceAssumptions :=
  Correspondence.lawfulnessIdealCorrespondence
    acyclicSectionData acyclicObject FiniteModel.lawUniverse signatureAxes
    FiniteModel.noCycleValuation FiniteModel.singletonRequiredAggregation
    acyclicCorrespondenceAssumptions

/-- III.R13: theorem 11.1 finite example package for the selected cyclic cycle model. -/
def cyclicCorrespondencePackage :
    Correspondence.LawfulnessIdealCorrespondencePackage
      cyclicSectionData cyclicObject FiniteModel.lawUniverse signatureAxes
        FiniteModel.noCycleValuation FiniteModel.singletonRequiredAggregation
          cyclicCorrespondenceAssumptions :=
  Correspondence.lawfulnessIdealCorrespondence
    cyclicSectionData cyclicObject FiniteModel.lawUniverse signatureAxes
    FiniteModel.noCycleValuation FiniteModel.singletonRequiredAggregation
    cyclicCorrespondenceAssumptions

end CycleCorrespondenceExample

end FiniteExamples

end LawAlgebra
end AAT.AG
