import Formal.AG.Examples.FiniteModel
import Formal.AG.LawAlgebra.LawfulLocus
import Formal.AG.LawAlgebra.Nullstellensatz
import Formal.AG.LawAlgebra.StanleyReisner

noncomputable section

namespace AAT.AG
namespace LawAlgebra

universe u

namespace FiniteExamples

open MvPolynomial
open scoped BigOperators

namespace StanleyReisnerChart

/-- III.例5.6E: selected coordinates `E_W = {x,y,z}`. -/
abbrev Coord := Fin 3

/-- III.例5.6E: the forbidden support `{x,y}`. -/
def xySupport : Finset Coord :=
  {0, 1}

/-- III.例5.6E: square-free regime with the single forbidden support `{x,y}`. -/
def regime : StanleyReisner.SquareFreeWitnessRegime Coord where
  Forb S := S = xySupport

/-- III.例5.6E: the selected support `{x,y}` is forbidden. -/
theorem xy_forbidden :
    regime.Forb xySupport :=
  rfl

/-- III.例5.6E: the selected obstruction ideal is generated by `xy`. -/
theorem obstructionIdeal_eq_span_xy (k : Type u) [CommRing k] :
    StanleyReisner.SquareFreeWitnessRegime.obstructionIdeal Coord k regime =
      Ideal.span ({StanleyReisner.squareFreeMonomial Coord k xySupport} :
        Set (MvPolynomial Coord k)) := by
  classical
  rw [StanleyReisner.SquareFreeWitnessRegime.obstructionIdeal,
    StanleyReisner.SquareFreeWitnessRegime.supportIdeal]
  apply le_antisymm
  · apply Ideal.span_le.mpr
    rintro f ⟨S, hS, rfl⟩
    rw [hS]
    exact Ideal.subset_span (by simp)
  · apply Ideal.span_le.mpr
    intro f hf
    rw [Set.mem_singleton_iff.mp hf]
    exact Ideal.subset_span ⟨xySupport, rfl, rfl⟩

/-- III.例5.6E: the obstruction ideal agrees with the Stanley-Reisner ideal. -/
theorem obstructionIdeal_eq_stanleyReisnerIdeal (k : Type u) [CommRing k] :
    StanleyReisner.SquareFreeWitnessRegime.obstructionIdeal Coord k regime =
      StanleyReisner.SquareFreeWitnessRegime.stanleyReisnerIdeal Coord k
        (StanleyReisner.SquareFreeWitnessRegime.delta Coord regime) :=
  StanleyReisner.SquareFreeWitnessRegime.obstructionIdeal_eq_stanleyReisnerIdeal
    Coord k regime

/-- III.例5.6E: `{z}` is a face of `Delta_U(W)`. -/
theorem z_face :
    ({2} : Finset Coord) ∈
      (StanleyReisner.SquareFreeWitnessRegime.delta Coord regime).faces := by
  intro S hS hSsubset
  rw [hS] at hSsubset
  have hzero : (0 : Coord) ∈ ({2} : Finset Coord) := hSsubset (by simp [xySupport])
  simp at hzero

/-- III.例5.6E: `{x,y}` is not a face of `Delta_U(W)`. -/
theorem xy_not_face :
    xySupport ∉
      (StanleyReisner.SquareFreeWitnessRegime.delta Coord regime).faces := by
  intro h
  exact h xySupport rfl (fun x hx => hx)

end StanleyReisnerChart

namespace NSdepthExample

/-- III.例7.2D: one Boolean coordinate. -/
abbrev Coord := Unit

/-- III.R4 / III-5: selected generators for the unit-certificate display. -/
inductive UnitGenerator where
  | x
  | xMinusOne
  deriving DecidableEq

/-- III.R4 / III-5: generator family `<x>, <x - 1>` used by the display. -/
def unitGenerator : UnitGenerator -> MvPolynomial Coord Int
  | UnitGenerator.x => X Unit.unit
  | UnitGenerator.xMinusOne => X Unit.unit - 1

/-- III.例7.2D: the ideal `<x>`. -/
def xIdeal (k : Type u) [CommRing k] : Ideal (MvPolynomial Coord k) :=
  Ideal.span ({X Unit.unit} : Set (MvPolynomial Coord k))

/-- III.例7.2D: the ideal `<x - 1>`. -/
def xMinusOneIdeal (k : Type u) [CommRing k] : Ideal (MvPolynomial Coord k) :=
  Ideal.span ({X Unit.unit - 1} : Set (MvPolynomial Coord k))

/-- III.例7.2D: `1 = x - (x - 1)`. -/
theorem one_eq_x_sub_x_minus_one (k : Type u) [CommRing k] :
    (1 : MvPolynomial Coord k) = X Unit.unit - (X Unit.unit - 1) := by
  ring

/-- III.例7.2D: `<x> + <x - 1>` contains `1`. -/
theorem one_mem_x_sup_xMinusOne (k : Type u) [CommRing k] :
    (1 : MvPolynomial Coord k) ∈ xIdeal k ⊔ xMinusOneIdeal k := by
  classical
  rw [one_eq_x_sub_x_minus_one k]
  have hx : X Unit.unit ∈ xIdeal k ⊔ xMinusOneIdeal k :=
    Ideal.mem_sup_left (Ideal.subset_span (by simp : X Unit.unit ∈
      ({X Unit.unit} : Set (MvPolynomial Coord k))))
  have hxm : X Unit.unit - 1 ∈ xIdeal k ⊔ xMinusOneIdeal k :=
    Ideal.mem_sup_right (Ideal.subset_span (by simp : X Unit.unit - 1 ∈
      ({X Unit.unit - 1} : Set (MvPolynomial Coord k))))
  exact Ideal.sub_mem (xIdeal k ⊔ xMinusOneIdeal k) hx hxm

/-- III.R4 / III-5: coefficient vector for `1 = x - (x - 1)`. -/
def unitCombinationCoeff : UnitGenerator →₀ MvPolynomial Coord Int :=
  Finsupp.single UnitGenerator.x 1 + Finsupp.single UnitGenerator.xMinusOne (-1)

/-- III.R4 / III-5: the selected generator combination displays `1`. -/
theorem unitCombinationCoeff_sum :
    unitCombinationCoeff.sum (fun i a => a * unitGenerator i) = 1 := by
  rw [unitCombinationCoeff]
  rw [Finsupp.sum_add_index]
  · rw [Finsupp.sum_single_index, Finsupp.sum_single_index]
    · simp [unitGenerator]
    · simp [unitGenerator]
    · simp [unitGenerator]
  · intro a _ha
    simp [unitGenerator]
  · intro a _ha b1 b2
    simp [add_mul]

/--
III.R4 / III-5: concrete generator certificate for `1 = x - (x - 1)`.

This is the data-backed source for the selected `NSdepth = 1` profile below.
-/
def concreteGeneratorUnitCertificate :
    Nullstellensatz.GeneratorUnitCertificate UnitGenerator unitGenerator where
  coeff := unitCombinationCoeff
  unit_eq_linearCombination := unitCombinationCoeff_sum
  displayDegree := 1
  displayDegree_bounds := by
    intro i
    cases i
    · simp [unitCombinationCoeff, unitGenerator]
    · have h : (1 - X Unit.unit : MvPolynomial Coord Int).totalDegree ≤ 1 := by
        calc
          (1 - X Unit.unit : MvPolynomial Coord Int).totalDegree
              ≤ max (1 : MvPolynomial Coord Int).totalDegree
                  (X Unit.unit : MvPolynomial Coord Int).totalDegree :=
            totalDegree_sub _ _
          _ ≤ 1 := by simp
      simpa [unitCombinationCoeff, unitGenerator] using h

/-- III.R4 / III-5: the concrete display proves `1 ∈ span {x, x - 1}`. -/
theorem concreteGeneratorUnitCertificate_one_mem_span :
    (1 : MvPolynomial Coord Int) ∈ Ideal.span (Set.range unitGenerator) :=
  Nullstellensatz.GeneratorUnitCertificate.one_mem_span
    concreteGeneratorUnitCertificate

/-- III.R4 / III-5: selected concrete generator certificate family. -/
inductive ConcreteGeneratorCertificate where
  | unit

/-- III.R4 / III-5: read the selected certificate family as generator displays. -/
def concreteGeneratorCertificate :
    ConcreteGeneratorCertificate ->
      Nullstellensatz.GeneratorUnitCertificate UnitGenerator unitGenerator
  | ConcreteGeneratorCertificate.unit => concreteGeneratorUnitCertificate

/-- III.例7.2D: concrete certificate payload over `Int` for `1 ∈ <x> + <x - 1>`. -/
structure UnitCertificate where
  label : Unit := Unit.unit
  unit_mem : (1 : MvPolynomial Coord Int) ∈ xIdeal Int ⊔ xMinusOneIdeal Int

/-- III.例7.2D: the concrete unit certificate generated by `1 = x - (x - 1)`. -/
def unitCertificate : UnitCertificate where
  label := Unit.unit
  unit_mem := one_mem_x_sup_xMinusOne Int

/-- III.例7.2D: the concrete unit certificate has display degree `1`. -/
def unitCertificateDegree (_c : UnitCertificate) : ℕ :=
  1

/-- III.例7.2D: certificate availability is generated by the concrete unit certificate. -/
def hasUnitCertificateAt (d : ℕ) : Prop :=
  ∃ c : UnitCertificate, unitCertificateDegree c ≤ d

/-- III.例7.2D: the concrete unit certificate is available in display degree `1`. -/
theorem hasUnitCertificateAt_one :
    hasUnitCertificateAt 1 :=
  ⟨unitCertificate, le_rfl⟩

/-- III.R4 / III-5: concrete generator-certificate availability in display degree `1`. -/
theorem hasConcreteGeneratorUnitCertificateAt_one :
    Nullstellensatz.HasSelectedGeneratorUnitCertificateAt unitGenerator
      ConcreteGeneratorCertificate concreteGeneratorCertificate 1 :=
  ⟨ConcreteGeneratorCertificate.unit, le_rfl⟩

/--
III.R4 / III-5: selected generator-backed NSdepth profile with depth `1`.

Unlike the legacy profile below, certificate availability is generated from an
actual finite linear-combination display over the selected generator family.
-/
def concreteGeneratorNSdepthProfile :
    Nullstellensatz.GeneratorNSdepthProfile UnitGenerator unitGenerator where
  Certificate := ConcreteGeneratorCertificate
  certificate := concreteGeneratorCertificate
  depth := 1
  depth_hasCertificate := hasConcreteGeneratorUnitCertificateAt_one
  depth_minimal := by
    intro d hd
    rcases hd with ⟨cert, hcert⟩
    cases cert
    exact hcert

/-- III.R4 / III-5: the concrete generator-backed profile has `NSdepth = 1`. -/
theorem concreteGeneratorNSdepth_eq_one :
    concreteGeneratorNSdepthProfile.toNSdepthProfile.NSdepth = 1 :=
  rfl

/-- III.例7.2D: selected NSdepth profile with depth `1`, generated by the concrete certificate. -/
def nsdepthOneProfile : Nullstellensatz.NSdepthProfile where
  HasCertificateAt := hasUnitCertificateAt
  depth := 1
  depth_hasCertificate := hasUnitCertificateAt_one
  depth_minimal := by
    intro d hd
    rcases hd with ⟨cert, hcert⟩
    exact hcert

/-- III.例7.2D: the selected certificate display has `NSdepth = 1`. -/
theorem nsdepth_eq_one :
    nsdepthOneProfile.NSdepth = 1 :=
  rfl

end NSdepthExample

namespace CycleCorrespondenceExample

/-- III.R13: one coordinate recording the selected finite cycle witness. -/
abbrev Coord := Unit

/-- III.R13: the coordinate ring for the selected cycle witness. -/
abbrev CycleRing := MvPolynomial Coord Int

/-- III.R13: the selected cycle witness coordinate `c_ABC`. -/
def cycleCoordinate : CycleRing :=
  X Unit.unit

/-- III.R13: the finite cycle witness ideal `I_cycle = <c_ABC>`. -/
def cycleIdeal : Ideal CycleRing :=
  Ideal.span ({cycleCoordinate} : Set CycleRing)

/-- III.R13: the cycle witness coordinate belongs to `I_cycle`. -/
theorem cycleCoordinate_mem_cycleIdeal :
    cycleCoordinate ∈ cycleIdeal :=
  Ideal.subset_span (by simp [cycleCoordinate])

/-- III.R13: singleton selected law family whose witness ideal is `I_cycle`. -/
def cycleWitnessIdealFamily :
    ObstructionIdeal.SelectedLawWitnessIdealFamily CycleRing where
  LawIndex := PUnit
  selected _ := True
  witnessIdeal _ := cycleIdeal

/-- III.R13: the local obstruction ideal generated by the selected cycle law is `I_cycle`. -/
theorem localObstructionIdeal_eq_cycleIdeal :
    cycleWitnessIdealFamily.localObstructionIdeal = cycleIdeal := by
  apply le_antisymm
  · rw [ObstructionIdeal.SelectedLawWitnessIdealFamily.localObstructionIdeal_le_iff]
    intro index _hselected
    cases index
    rfl
  · exact ObstructionIdeal.SelectedLawWitnessIdealFamily.witnessIdeal_le_localObstructionIdeal
      CycleRing cycleWitnessIdealFamily (L := PUnit.unit) trivial

/-- III.R13: section evaluation at `c_ABC = 0`. -/
def zeroEval : CycleRing →+* Int :=
  MvPolynomial.eval₂Hom (RingHom.id Int) (fun _ : Coord => (0 : Int))

/-- III.R13: section evaluation at `c_ABC = 1`. -/
def oneEval : CycleRing →+* Int :=
  MvPolynomial.eval₂Hom (RingHom.id Int) (fun _ : Coord => (1 : Int))

/-- III.R13: lawful section data for the acyclic finite cycle witness. -/
def acyclicSectionData : LawfulLocus.LawfulSectionData CycleRing cycleIdeal where
  SectionRing := Int
  commRing := inferInstance
  pullback := zeroEval

/-- III.R13: violating section data for the cyclic finite cycle witness. -/
def cyclicSectionData : LawfulLocus.LawfulSectionData CycleRing cycleIdeal where
  SectionRing := Int
  commRing := inferInstance
  pullback := oneEval

/-- III.R13: the acyclic section pulls `I_cycle` back to zero. -/
theorem acyclic_pulledObstructionIdeal_eq_bot :
    acyclicSectionData.pulledObstructionIdeal = ⊥ := by
  rw [LawfulLocus.LawfulSectionData.pulledObstructionIdeal, acyclicSectionData,
    cycleIdeal, Ideal.map_span]
  simp [cycleCoordinate, zeroEval]

/-- III.R4 / III-1: acyclic section data for the generated local obstruction ideal. -/
def acyclicLocalSectionData :
    LawfulLocus.LocalLawfulSectionData CycleRing cycleWitnessIdealFamily where
  SectionRing := Int
  commRing := inferInstance
  pullback := zeroEval

/-- III.R4 / III-1: the acyclic pullback kills the selected cycle witness ideal. -/
theorem acyclic_cycleWitnessIdeal_le_ker
    (index : cycleWitnessIdealFamily.LawIndex) :
    cycleWitnessIdealFamily.witnessIdeal index ≤ RingHom.ker zeroEval := by
  cases index
  change cycleIdeal ≤ RingHom.ker zeroEval
  exact (Ideal.map_eq_bot_iff_le_ker zeroEval).mp
    (by
      simpa [LawfulLocus.LawfulSectionData.pulledObstructionIdeal, acyclicSectionData]
        using acyclic_pulledObstructionIdeal_eq_bot)

/--
III.R4 / III-1: the finite acyclic cycle example fires the strengthened
Lawfulness-Ideal bridge through selected witness ideals and
`localObstructionIdeal`, not through the old `witnessCoverage` field.
-/
theorem acyclicLocalSection_lawful_from_witnessIdeals :
    acyclicLocalSectionData.Lawful := by
  rw [LawfulLocus.LawfulSectionData.Lawful,
    LawfulLocus.LawfulSectionData.pulledObstructionIdeal]
  apply (Ideal.map_eq_bot_iff_le_ker acyclicLocalSectionData.pullback).2
  rw [ObstructionIdeal.SelectedLawWitnessIdealFamily.localObstructionIdeal_le_iff]
  intro index _hselected
  exact acyclic_cycleWitnessIdeal_le_ker index

/--
III.R4 / III-2: the acyclic finite section's induced prime map lands in the
selected local lawful zero locus.
-/
theorem acyclic_sectionPrimeMap_mem_localLawfulLocus (p : PrimeSpectrum Int) :
    LawfulLocus.localSectionPrimeMap CycleRing cycleWitnessIdealFamily acyclicLocalSectionData p ∈
      LawfulLocus.localLawfulLocus CycleRing cycleWitnessIdealFamily :=
  LawfulLocus.localSectionPrimeMap_mem_localLawfulLocus_of_lawful
    CycleRing cycleWitnessIdealFamily acyclicLocalSectionData
    acyclicLocalSection_lawful_from_witnessIdeals p

/-- III.R13: the cyclic witness section pulls `I_cycle` back to the unit ideal. -/
theorem cyclic_pulledObstructionIdeal_eq_top :
    cyclicSectionData.pulledObstructionIdeal = ⊤ := by
  rw [LawfulLocus.LawfulSectionData.pulledObstructionIdeal, cyclicSectionData,
    cycleIdeal, Ideal.map_span]
  simp [cycleCoordinate, oneEval]

/-- III.R13: the acyclic pulled lawful locus has a point. -/
theorem acyclic_pulled_lawful_locus_has_point :
    ∃ p : PrimeSpectrum Int,
      p ∈ LawfulLocus.lawfulLocus Int acyclicSectionData.pulledObstructionIdeal := by
  rw [acyclic_pulledObstructionIdeal_eq_bot]
  exact ⟨⟨⊥, inferInstance⟩, by simp [LawfulLocus.lawfulLocus]⟩

/-- III.R13: the cyclic pulled lawful locus has no point. -/
theorem cyclic_pulled_lawful_locus_no_point :
    ¬ ∃ p : PrimeSpectrum Int,
      p ∈ LawfulLocus.lawfulLocus Int cyclicSectionData.pulledObstructionIdeal := by
  rw [cyclic_pulledObstructionIdeal_eq_top]
  simp [LawfulLocus.lawfulLocus]

/-- III.R13: selected acyclic configuration for the theorem 11.1 finite example. -/
def acyclicConfiguration : AtomConfiguration FiniteModel.carrier where
  family := FiniteModel.allFamily
  relation _ _ := False
  identification _ _ := False

/-- III.R13: finite object with no selected cycle witness. -/
def acyclicObject : ArchitectureObject FiniteModel.carrier :=
  FiniteModel.objectOfConfiguration acyclicConfiguration

/-- III.R13: finite object with the selected cycle witness. -/
def cyclicObject : ArchitectureObject FiniteModel.carrier :=
  FiniteModel.object

/-- III.R13: equation system selected for the finite NoCycle correspondence. -/
noncomputable def noCycleEquationSystem :=
  FiniteModel.equationSystem
    (Site.contextMorphismPreorderCategory FiniteModel.object)

/-- III.R13: the acyclic finite object fulfills the selected NoCycle equation. -/
theorem acyclic_noCycleEquationHolds :
    noCycleEquationSystem.EquationHolds PUnit.unit acyclicObject := by
  apply (FiniteModel.equationHolds_iff_noCycle _ acyclicObject).mpr
  intro hcycle
  exact hcycle.1

/-- III.R13: the cyclic finite object violates the selected NoCycle equation. -/
theorem cyclic_noCycleEquation_fails :
    ¬ noCycleEquationSystem.EquationHolds PUnit.unit cyclicObject := by
  intro hequation
  exact (FiniteModel.equationHolds_iff_noCycle _ cyclicObject).mp hequation
    (by
      simpa [cyclicObject, FiniteModel.hasCycleWitness,
        FiniteModel.hasDependencyCycle] using FiniteModel.object_hasCycleWitness)

/-- III.R13: the acyclic finite object fulfills every required equation. -/
theorem acyclic_equationLawful :
    noCycleEquationSystem.EquationLawful acyclicObject := by
  intro index _hrequired
  cases index
  exact acyclic_noCycleEquationHolds

/-- III.R13: the cyclic finite object fails required equation lawfulness. -/
theorem cyclic_equationLawful_fails :
    ¬ noCycleEquationSystem.EquationLawful cyclicObject := by
  intro h
  exact cyclic_noCycleEquation_fails (h PUnit.unit rfl)

/-- III.R13: the cyclic witness section is not locally lawful. -/
theorem cyclicSection_not_lawful :
    ¬ cyclicSectionData.Lawful := by
  intro h
  have hone : (1 : Int) ∈ (⊥ : Ideal Int) := by
    rw [← h, cyclic_pulledObstructionIdeal_eq_top]
    trivial
  simp at hone

/-- III.R13: selected equation-generated signature axes for the finite model. -/
def signatureAxes : SignatureAxes FiniteModel.carrier :=
  equationResidualSignatureAxes noCycleEquationSystem

/-- III.R13: equation lawfulness is exact on the generated signature axes. -/
theorem equationLawful_iff_signatureAxesZero
    (A : ArchitectureObject FiniteModel.carrier) :
    noCycleEquationSystem.EquationLawful A ↔
      RequiredSignatureAxesZero A signatureAxes :=
  equationLawful_iff_requiredSignatureAxesZero
    (equationResidualSignatureComparison noCycleEquationSystem) A

end CycleCorrespondenceExample

end FiniteExamples

end LawAlgebra
end AAT.AG
