import Formal.AG.LawAlgebra.IdempotentCollapse
import Mathlib.RingTheory.Spectrum.Prime.Basic

noncomputable section

namespace AAT.AG
namespace LawAlgebra

universe u v

open scoped BigOperators
open MvPolynomial

namespace StanleyReisner

set_option linter.unusedSectionVars false

variable (E : Type u) (k : Type v) [CommRing k]

/-- III.定義5.6B: the square-free monomial `x_S = ∏ e ∈ S, x_e`. -/
def squareFreeMonomial [DecidableEq E] (S : Finset E) : MvPolynomial E k :=
  ∏ e ∈ S, X e

/--
III.定義5.6B: square-free witness regime.

`Forb` is the selected family of forbidden witness supports. The obstruction
ideal generated from this regime lives in the deformation-side polynomial
algebra `k[E]`, not in the Boolean quotient of `IdempotentCollapse`.
-/
structure SquareFreeWitnessRegime where
  Forb : Set (Finset E)

namespace SquareFreeWitnessRegime

variable [DecidableEq E]

/-- III.定義5.6B: monomials selected by a support predicate. -/
def monomialSet (P : Set (Finset E)) : Set (MvPolynomial E k) :=
  {f | ∃ S, P S ∧ f = squareFreeMonomial E k S}

/-- III.定義5.6B: the monomial ideal generated by a support predicate. -/
def supportIdeal (P : Set (Finset E)) : Ideal (MvPolynomial E k) :=
  Ideal.span (monomialSet E k P)

/-- III.定義5.6B: local square-free obstruction ideal. -/
def obstructionIdeal (R : SquareFreeWitnessRegime E) : Ideal (MvPolynomial E k) :=
  supportIdeal E k R.Forb

/-- III.定義5.6B: supports containing no forbidden support. -/
def AdmissibleSupport (R : SquareFreeWitnessRegime E) (T : Finset E) : Prop :=
  ∀ S, R.Forb S -> ¬ S ⊆ T

/-- III.定理5.6C: an abstract simplicial complex on witness supports. -/
structure AbstractSimplicialComplex where
  faces : Set (Finset E)
  downward_closed : ∀ ⦃S T : Finset E⦄, T ∈ faces -> S ⊆ T -> S ∈ faces

/-- III.定理5.6C: `Δ_U(W)` consists of supports containing no forbidden support. -/
def delta (R : SquareFreeWitnessRegime E) : AbstractSimplicialComplex E where
  faces := {T | AdmissibleSupport E R T}
  downward_closed := by
    intro S T hT hST F hF hFS
    exact hT F hF (fun x hx => hST (hFS hx))

/-- III.定理5.6C: Stanley-Reisner ideal of a complex. -/
def stanleyReisnerIdeal (Δ : AbstractSimplicialComplex E) : Ideal (MvPolynomial E k) :=
  supportIdeal E k {S | S ∉ Δ.faces}

/-- III.定理5.6C: coordinate subspace arrangement reading `V(I_Δ)`. -/
def coordinateSubspaceArrangement (Δ : AbstractSimplicialComplex E) :
    Set (PrimeSpectrum (MvPolynomial E k)) :=
  PrimeSpectrum.zeroLocus (stanleyReisnerIdeal E k Δ)

/-- III.定理5.6C: the lawful-flat chart reading for a square-free regime. -/
def flatChart (R : SquareFreeWitnessRegime E) :
    Set (PrimeSpectrum (MvPolynomial E k)) :=
  coordinateSubspaceArrangement E k (delta E R)

theorem mem_delta_iff (R : SquareFreeWitnessRegime E) (T : Finset E) :
    T ∈ (delta E R).faces ↔ AdmissibleSupport E R T :=
  Iff.rfl

/-- III.系5.6D: faces are exactly admissible witness supports. -/
theorem face_iff_admissibleSupport (R : SquareFreeWitnessRegime E) (T : Finset E) :
    T ∈ (delta E R).faces ↔ AdmissibleSupport E R T :=
  Iff.rfl

lemma squareFreeMonomial_subset_mul {S T : Finset E} (hST : S ⊆ T) :
    squareFreeMonomial E k T =
      squareFreeMonomial E k (T \ S) * squareFreeMonomial E k S := by
  unfold squareFreeMonomial
  exact (Finset.prod_sdiff hST).symm

lemma squareFreeMonomial_mem_supportIdeal_of_subset {P : Set (Finset E)}
    {S T : Finset E} (hS : P S) (hST : S ⊆ T) :
    squareFreeMonomial E k T ∈ supportIdeal E k P := by
  rw [squareFreeMonomial_subset_mul E k hST]
  exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨S, hS, rfl⟩)

lemma obstructionIdeal_le_stanleyReisnerIdeal (R : SquareFreeWitnessRegime E) :
    obstructionIdeal E k R ≤ stanleyReisnerIdeal E k (delta E R) := by
  rw [obstructionIdeal, stanleyReisnerIdeal, supportIdeal]
  apply Ideal.span_le.mpr
  rintro f ⟨S, hS, rfl⟩
  have hSnot : S ∉ (delta E R).faces := by
    intro hface
    exact hface S hS (fun x hx => hx)
  exact Ideal.subset_span ⟨S, hSnot, rfl⟩

lemma stanleyReisnerIdeal_le_obstructionIdeal (R : SquareFreeWitnessRegime E) :
    stanleyReisnerIdeal E k (delta E R) ≤ obstructionIdeal E k R := by
  rw [stanleyReisnerIdeal, obstructionIdeal, supportIdeal]
  apply Ideal.span_le.mpr
  rintro f ⟨T, hT, rfl⟩
  have h_exists : ∃ S, R.Forb S ∧ S ⊆ T := by
    by_contra hnone
    apply hT
    exact (mem_delta_iff E R T).mpr (by
      intro S hS hST
      exact hnone ⟨S, hS, hST⟩)
  rcases h_exists with ⟨S, hS, hST⟩
  exact squareFreeMonomial_mem_supportIdeal_of_subset E k hS hST

/--
III.定理5.6C: the square-free obstruction ideal is the Stanley-Reisner ideal of
the complex cut out by forbidden supports.
-/
theorem obstructionIdeal_eq_stanleyReisnerIdeal (R : SquareFreeWitnessRegime E) :
    obstructionIdeal E k R = stanleyReisnerIdeal E k (delta E R) :=
  le_antisymm (obstructionIdeal_le_stanleyReisnerIdeal E k R)
    (stanleyReisnerIdeal_le_obstructionIdeal E k R)

/-- III.定理5.6C: inclusion-minimality predicate for forbidden supports. -/
def MinimalForbidden (R : SquareFreeWitnessRegime E) (S : Finset E) : Prop :=
  R.Forb S ∧ ∀ T, R.Forb T -> T ⊆ S -> S ⊆ T

/-- III.定理5.6C: all selected forbidden supports are inclusion-minimal. -/
def InclusionMinimalForbiddenFamily (R : SquareFreeWitnessRegime E) : Prop :=
  ∀ ⦃S T : Finset E⦄, R.Forb S -> R.Forb T -> T ⊆ S -> S ⊆ T

/--
III.定理5.6C: the theorem under the explicit inclusion-minimal hypothesis.

The equality above is actually stronger and does not need the hypothesis; this
wrapper records the textual minimal-family statement.
-/
theorem obstructionIdeal_eq_stanleyReisnerIdeal_of_minimal
    (R : SquareFreeWitnessRegime E) (_hmin : InclusionMinimalForbiddenFamily E R) :
    obstructionIdeal E k R = stanleyReisnerIdeal E k (delta E R) :=
  obstructionIdeal_eq_stanleyReisnerIdeal E k R

/-- III.定理5.6C: the minimal forbidden reduction of a regime. -/
def minimalReduction (R : SquareFreeWitnessRegime E) : SquareFreeWitnessRegime E where
  Forb := {S | MinimalForbidden E R S}

theorem exists_minimalForbidden_subset [Fintype E] (R : SquareFreeWitnessRegime E)
    {S : Finset E} (hS : R.Forb S) :
    ∃ T, MinimalForbidden E R T ∧ T ⊆ S := by
  classical
  let candidates : Set (Finset E) := {T | R.Forb T ∧ T ⊆ S}
  have hfinite : candidates.Finite := Set.finite_univ.subset (by intro T _; trivial)
  have hnonempty : candidates.Nonempty := ⟨S, hS, fun x hx => hx⟩
  rcases hfinite.exists_minimal hnonempty with ⟨T, hTmin⟩
  refine ⟨T, ?_, hTmin.1.2⟩
  refine ⟨hTmin.1.1, ?_⟩
  intro U hU hUT
  exact hTmin.2 ⟨hU, fun x hx => hTmin.1.2 (hUT hx)⟩ hUT

lemma obstructionIdeal_le_minimalReduction_obstructionIdeal [Fintype E]
    (R : SquareFreeWitnessRegime E) :
    obstructionIdeal E k R ≤ obstructionIdeal E k (minimalReduction E R) := by
  rw [obstructionIdeal, obstructionIdeal, supportIdeal]
  apply Ideal.span_le.mpr
  rintro f ⟨S, hS, rfl⟩
  rcases exists_minimalForbidden_subset E R hS with ⟨T, hTmin, hTS⟩
  exact squareFreeMonomial_mem_supportIdeal_of_subset E k hTmin hTS

lemma minimalReduction_obstructionIdeal_le_obstructionIdeal (R : SquareFreeWitnessRegime E) :
    obstructionIdeal E k (minimalReduction E R) ≤ obstructionIdeal E k R := by
  rw [obstructionIdeal, obstructionIdeal, supportIdeal]
  apply Ideal.span_le.mpr
  rintro f ⟨S, hS, rfl⟩
  exact Ideal.subset_span ⟨S, hS.1, rfl⟩

/--
III.定理5.6C: non-minimal forbidden families reduce to their inclusion-minimal
supports without changing the obstruction ideal, hence also without changing
its radical.
-/
theorem minimalReduction_obstructionIdeal_eq [Fintype E]
    (R : SquareFreeWitnessRegime E) :
    obstructionIdeal E k (minimalReduction E R) = obstructionIdeal E k R :=
  le_antisymm (minimalReduction_obstructionIdeal_le_obstructionIdeal E k R)
    (obstructionIdeal_le_minimalReduction_obstructionIdeal E k R)

theorem radical_minimalReduction_obstructionIdeal_eq [Fintype E]
    (R : SquareFreeWitnessRegime E) :
    (obstructionIdeal E k (minimalReduction E R)).radical =
      (obstructionIdeal E k R).radical := by
  rw [minimalReduction_obstructionIdeal_eq E k R]

/-- III.系5.6D: minimal monomial generator supports of `I_Δ`. -/
def MinimalStanleyReisnerGeneratorSupport
    (Δ : AbstractSimplicialComplex E) (S : Finset E) : Prop :=
  S ∉ Δ.faces ∧ ∀ T, T ∉ Δ.faces -> T ⊆ S -> S ⊆ T

/--
III.系5.6D: minimal Stanley-Reisner generator supports are exactly the minimal
forbidden supports.
-/
theorem minimalGeneratorSupport_iff_minimalForbidden
    (R : SquareFreeWitnessRegime E) (S : Finset E) :
    MinimalStanleyReisnerGeneratorSupport E (delta E R) S ↔ MinimalForbidden E R S := by
  constructor
  · intro h
    have h_exists : ∃ T, R.Forb T ∧ T ⊆ S := by
      by_contra hnone
      apply h.1
      exact (mem_delta_iff E R S).mpr (by
        intro T hT hTS
        exact hnone ⟨T, hT, hTS⟩)
    rcases h_exists with ⟨T, hT, hTS⟩
    have hTnonface : T ∉ (delta E R).faces :=
      fun hface => hface T hT (fun x hx => hx)
    have hST : S ⊆ T := h.2 T hTnonface hTS
    refine ⟨?_, ?_⟩
    · have hEq : T = S := Finset.Subset.antisymm hTS hST
      simpa [hEq] using hT
    · intro U hU hUS
      have hUnonface : U ∉ (delta E R).faces :=
        fun hface => hface U hU (fun x hx => hx)
      exact h.2 U hUnonface hUS
  · intro h
    refine ⟨?_, ?_⟩
    · exact fun hface => hface S h.1 (fun x hx => hx)
    · intro T hTnonface hTS
      have h_exists : ∃ U, R.Forb U ∧ U ⊆ T := by
        by_contra hnone
        apply hTnonface
        exact (mem_delta_iff E R T).mpr (by
          intro U hU hUT
          exact hnone ⟨U, hU, hUT⟩)
      rcases h_exists with ⟨U, hU, hUT⟩
      exact fun x hx => hUT (h.2 U hU (fun y hy => hTS (hUT hy)) hx)

end SquareFreeWitnessRegime

end StanleyReisner

end LawAlgebra
end AAT.AG
