import ResearchLean.AG.CrossStageCoherence.ArbitraryStrongLiftPseudofunctor
import ResearchLean.AG.TransportCoherence.ArbitraryFinitePresentation
import ResearchLean.AG.CrossStageCoherence.CompositeQualification
import ResearchLean.AG.CrossStageCoherence.CompatiblePairRefutation
import ResearchLean.AG.CrossStageCoherence.CellChain
import ResearchLean.AG.CrossStageCoherence.CellChainInstances
import ResearchLean.AG.CrossStageCoherence.ComparisonDescent
import ResearchLean.AG.CrossStageCoherence.ComparisonDescentInstances
import ResearchLean.AG.CrossStageCoherence.CorePushforward
import ResearchLean.AG.CrossStageCoherence.CorePushforwardInstances
import ResearchLean.AG.CrossStageCoherence.PathGaugeEffectivity
import ResearchLean.AG.CrossStageCoherence.PathGaugeEffectivityInstances
import ResearchLean.AG.CrossStageCoherence.EdgeEffectivity
import ResearchLean.AG.CrossStageCoherence.EdgeEffectivityInstances
import ResearchLean.AG.CrossStageCoherence.IdentityEdgeLiftSpecialization
import ResearchLean.AG.CrossStageCoherence.SharedEdgeTriangleWitness
import ResearchLean.AG.CrossStageCoherence.SimpleTriangleWitness
import ResearchLean.AG.CrossStageCoherence.RealizablePushforward
import ResearchLean.AG.CrossStageCoherence.RealizablePushforwardInstances
import ResearchLean.AG.CrossStageCoherence.RootEffectivityWitness

/-!
# Cross-stage transport coherence

Umbrella import for arbitrary selected-strong-lift and canonical G-109
pseudofunctors, obstruction-composition, vanishing, finite-witness,
compatible-pair refutation, comparison-descent, path-gauge effectivity,
identity-edge-lift specialization, simple/shared-edge triangle witnesses,
root-effectivity obstruction, and core-pushforward development.
-/
