import Formal.AG.Atom.Invariant
import Formal.AG.Atom.Obstruction

namespace AAT.AG

universe u

/--
A homomorphism of Atom configurations, transporting all selected configuration data.

Implementation notes: the atom map and three preservation laws are the actual
operation data of Part I Definition 10.2.  The previous endpoint-indexed
arbitrary propositions were rejected because they did not construct a map
between configurations.
-/
structure ConfigurationHom {U : AtomCarrier.{u}}
    (C D : AtomConfiguration U) where
  /-- The actual map on atoms. -/
  atomMap : U.Atom -> U.Atom
  maps_family : ∀ {a}, C.family.mem a -> D.family.mem (atomMap a)
  maps_relation : ∀ {a b}, C.relation a b ->
    D.relation (atomMap a) (atomMap b)
  maps_identification : ∀ {a b}, C.identification a b ->
    D.identification (atomMap a) (atomMap b)

namespace ConfigurationHom

/-- Configuration homomorphisms with the same atom map are equal. -/
@[ext]
theorem ext {U : AtomCarrier.{u}} {C D : AtomConfiguration U}
    {f g : ConfigurationHom C D} (hatomMap : f.atomMap = g.atomMap) : f = g := by
  cases f
  cases g
  cases hatomMap
  rfl

/-- The identity homomorphism of an Atom configuration. -/
def id {U : AtomCarrier.{u}} (C : AtomConfiguration U) :
    ConfigurationHom C C where
  atomMap := fun a => a
  maps_family := fun h => h
  maps_relation := fun h => h
  maps_identification := fun h => h

/-- Composition of Atom-configuration homomorphisms. -/
def comp {U : AtomCarrier.{u}} {C D E : AtomConfiguration U}
    (g : ConfigurationHom D E) (f : ConfigurationHom C D) :
    ConfigurationHom C E where
  atomMap := g.atomMap ∘ f.atomMap
  maps_family h := g.maps_family (f.maps_family h)
  maps_relation h := g.maps_relation (f.maps_relation h)
  maps_identification h := g.maps_identification (f.maps_identification h)

end ConfigurationHom

/-- I.定義10.2: an operation from one architecture object to another. -/
structure Operation (U : AtomCarrier.{u}) where
  source : ArchitectureObject U
  target : ArchitectureObject U
  configurationMap :
    ConfigurationHom source.configuration target.configuration

/--
Selected operations between architecture objects, read as configuration homomorphisms.

Implementation notes: `Op` is indexed by both endpoints so the source and
target cannot be selected independently of the operation.  A single global
operation carrier with separate endpoint functions was rejected because it
did not expose the object-pair-indexed family fixed by Part I Definition 10.1.
-/
structure OperationReading (U : AtomCarrier.{u}) where
  /-- The selected operation type for each source-target pair. -/
  Op : ArchitectureObject U -> ArchitectureObject U -> Type u
  /-- The configuration homomorphism realized by a selected operation. -/
  configurationMap : ∀ {A B}, Op A B ->
    ConfigurationHom A.configuration B.configuration

/--
I.定義10.3: a multi-axis signature reading of selected quantities on
architecture objects.
-/
structure ArchitectureSignature (U : AtomCarrier.{u}) where
  Axis : Type u
  Coordinate : Axis -> Type u
  selected : Axis -> Prop
  coordinate : (A : ArchitectureObject U) -> (axis : Axis) -> Coordinate axis

/--
I.定義10.1: the object algebra generated by the Part I ingredients.

Implementation notes: the distinguished generated object fixes the context
category, architectural equation system, and equation-indexed circuit family.
The old law reading is a derived display view below. Operations remain indexed
by object pairs; selected circuit and selected operation fields were rejected
because the algebra is a family of objects and morphisms rather than a package
containing one witness of each.
-/
structure ObjectAlgebra (U : AtomCarrier.{u}) where
  Obj : Type (u + 1)
  object : Obj -> ArchitectureObject U
  /-- The generated object whose context/equation reading anchors the algebra. -/
  base : Obj
  /-- Context, equation, and equation-indexed circuit reading generated at `base`. -/
  equationReading : EquationReading (object base)
  Op : Obj -> Obj -> Type u
  /-- The actual configuration homomorphism of an indexed operation. -/
  configurationMap : ∀ {A B}, Op A B ->
    ConfigurationHom (object A).configuration (object B).configuration
  /-- The invariant reading shared by the algebra. -/
  invariantReading : InvariantFamily U
  /-- The architecture signature reading. -/
  signatureReading : ArchitectureSignature U

/-- I.命題10.4: the six operation readings tracked in Part I. -/
inductive OperationRole where
  | preservation
  | reflection
  | repair
  | extension
  | synthesis
  | translation
  deriving DecidableEq

namespace Operation

/-- I.定義10.2: read an operation's Atom-configuration homomorphism. -/
def configurationMap_apply {U : AtomCarrier.{u}} (op : Operation U) :
    ConfigurationHom op.source.configuration op.target.configuration :=
  op.configurationMap

/-- I.命題10.4: preservation reading for a selected function invariant. -/
def PreservesFunctionInvariant {U : AtomCarrier.{u}} (op : Operation U)
    (I : FunctionInvariant U) : Prop :=
  Invariant.EqualityPreserved I op.source op.target

/-- I.命題10.4: preservation reading for a selected predicate invariant. -/
def PreservesPredicateInvariant {U : AtomCarrier.{u}} (op : Operation U)
    (P : PredicateInvariant U) : Prop :=
  Invariant.PredicatePreserved P op.source op.target

/-- I.命題10.4: reflection reading as target-side selected obstruction exposure. -/
def ReflectsObstruction {U : AtomCarrier.{u}} (op : Operation U)
    (W : LawWitnessFamily U) : Prop :=
  ∃ witness : W.Witness, W.badWitness op.target witness

/-- I.命題10.4: repair reading as a selected obstruction valuation decrease. -/
def RepairsObstruction {U : AtomCarrier.{u}} {Value : Type u}
    (op : Operation U) (valuation : ObstructionValuation U Value)
    (L : Law U) (decreases : Value -> Value -> Prop) : Prop :=
  decreases (valuation.omega L op.target) (valuation.omega L op.source)

/-- I.命題10.4: extension reading as growth of the underlying Atom family. -/
def ExtendsAtomFamily {U : AtomCarrier.{u}} (op : Operation U) : Prop :=
  op.source.configuration.family.Subset op.target.configuration.family

/-- I.命題10.4: synthesis reading as construction of a selected lawful target. -/
def SynthesizesLawfulObject {U : AtomCarrier.{u}} (op : Operation U)
    (LU : LawUniverse U) : Prop :=
  Lawfulness op.target LU

/-- I.命題10.4: translation reading as selected object equivalence evidence. -/
def TranslatesRepresentation {U : AtomCarrier.{u}} (op : Operation U) :
    Prop :=
  Nonempty (ArchitectureObject.ObjectEquivalence op.source op.target)

/-- I.命題10.4: function-invariant preservation exposes equality of values. -/
theorem preservesFunctionInvariant_apply {U : AtomCarrier.{u}}
    {op : Operation U} {I : FunctionInvariant U}
    (h : PreservesFunctionInvariant op I) :
    I.evaluate op.source = I.evaluate op.target :=
  h

/-- I.命題10.4: predicate-invariant preservation transports source witnesses. -/
theorem preservesPredicateInvariant_apply {U : AtomCarrier.{u}}
    {op : Operation U} {P : PredicateInvariant U}
    (h : PreservesPredicateInvariant op P) (hsource : P.holds op.source) :
    P.holds op.target :=
  h hsource

/-- I.命題10.4: reflection provides a target-side obstruction witness. -/
theorem reflectsObstruction_witness {U : AtomCarrier.{u}}
    {op : Operation U} {W : LawWitnessFamily U}
    (h : ReflectsObstruction op W) :
    ∃ witness : W.Witness, W.badWitness op.target witness :=
  h

/-- I.命題10.4: repair is exactly the selected decrease comparison. -/
theorem repairsObstruction_apply {U : AtomCarrier.{u}} {Value : Type u}
    {op : Operation U} {valuation : ObstructionValuation U Value}
    {L : Law U} {decreases : Value -> Value -> Prop}
    (h : RepairsObstruction op valuation L decreases) :
    decreases (valuation.omega L op.target) (valuation.omega L op.source) :=
  h

/-- I.命題10.4: extension exposes source-family inclusion in the target. -/
theorem extendsAtomFamily_apply {U : AtomCarrier.{u}}
    {op : Operation U} (h : ExtendsAtomFamily op) :
    op.source.configuration.family.Subset op.target.configuration.family :=
  h

/-- I.命題10.4: synthesis exposes lawfulness of the constructed target. -/
theorem synthesizesLawfulObject_apply {U : AtomCarrier.{u}}
    {op : Operation U} {LU : LawUniverse U}
    (h : SynthesizesLawfulObject op LU) :
    Lawfulness op.target LU :=
  h

/-- I.命題10.4: translation provides selected object-equivalence evidence. -/
theorem translatesRepresentation_witness {U : AtomCarrier.{u}}
    {op : Operation U} (h : TranslatesRepresentation op) :
    Nonempty (ArchitectureObject.ObjectEquivalence op.source op.target) :=
  h

end Operation

namespace OperationReading

/--
Operation readings are equal when their indexed operation families and their
dependent configuration-map functions agree.
-/
@[ext (iff := false)]
theorem ext {U : AtomCarrier.{u}} {R S : OperationReading U}
    (hOp : R.Op = S.Op)
    (hconfigurationMap :
      HEq (@OperationReading.configurationMap U R)
        (@OperationReading.configurationMap U S)) : R = S := by
  cases R
  cases S
  cases hOp
  cases hconfigurationMap
  rfl

/-- Package a selected operation as an architecture operation. -/
def operation {U : AtomCarrier.{u}} (R : OperationReading U)
    {A B : ArchitectureObject U} (op : R.Op A B) : Operation U where
  source := A
  target := B
  configurationMap := R.configurationMap op

/-- A packaged selected operation has its first index as source. -/
theorem operation_source {U : AtomCarrier.{u}} (R : OperationReading U)
    {A B : ArchitectureObject U} (op : R.Op A B) :
    (R.operation op).source = A :=
  rfl

/-- A packaged selected operation has its second index as target. -/
theorem operation_target {U : AtomCarrier.{u}} (R : OperationReading U)
    {A B : ArchitectureObject U} (op : R.Op A B) :
    (R.operation op).target = B :=
  rfl

/-- A packaged selected operation exposes the recorded configuration homomorphism. -/
theorem operation_configurationMap {U : AtomCarrier.{u}}
    (R : OperationReading U) {A B : ArchitectureObject U} (op : R.Op A B) :
    (R.operation op).configurationMap = R.configurationMap op :=
  rfl

/-- The least family of objects containing `base` and closed under selected operations. -/
inductive Reachable {U : AtomCarrier.{u}} (R : OperationReading U)
    (base : ArchitectureObject U) : ArchitectureObject U -> Prop
  | base : Reachable R base base
  | step {A B} : Reachable R base A -> R.Op A B -> Reachable R base B

end OperationReading

namespace ArchitectureSignature

/-- I.定義10.3: read a selected coordinate of an architecture object. -/
def read {U : AtomCarrier.{u}} (signature : ArchitectureSignature U)
    (A : ArchitectureObject U) (axis : signature.Axis) :
    signature.Coordinate axis :=
  signature.coordinate A axis

/-- I.定義10.3: `read` is the recorded coordinate reading. -/
theorem read_eq_coordinate {U : AtomCarrier.{u}}
    (signature : ArchitectureSignature U) (A : ArchitectureObject U)
    (axis : signature.Axis) :
    signature.read A axis = signature.coordinate A axis :=
  rfl

end ArchitectureSignature

namespace ObjectAlgebra

/--
Indexed object algebras are equal when their carrier and all dependent object,
operation, and configuration-map fields agree, together with their readings.
-/
@[ext (iff := false)]
theorem ext {U : AtomCarrier.{u}} {K L : ObjectAlgebra U}
    (hObj : K.Obj = L.Obj)
    (hobject : HEq (@ObjectAlgebra.object U K) (@ObjectAlgebra.object U L))
    (hbase : HEq K.base L.base)
    (hequationReading : HEq K.equationReading L.equationReading)
    (hOp : HEq (@ObjectAlgebra.Op U K) (@ObjectAlgebra.Op U L))
    (hconfigurationMap :
      HEq (@ObjectAlgebra.configurationMap U K)
        (@ObjectAlgebra.configurationMap U L))
    (hinvariantReading : K.invariantReading = L.invariantReading)
    (hsignatureReading : K.signatureReading = L.signatureReading) : K = L := by
  cases K
  cases L
  cases hObj
  cases hobject
  cases hbase
  cases hequationReading
  cases hOp
  cases hconfigurationMap
  cases hinvariantReading
  cases hsignatureReading
  rfl

/-- The context preorder selected by the equation reading. -/
def contextPreorder {U : AtomCarrier.{u}} (K : ObjectAlgebra U) :
    Site.ContextPreorderCategory (K.object K.base) :=
  K.equationReading.contextPreorder

/-- The architectural equation system that is the algebra's primary law input. -/
def equationSystem {U : AtomCarrier.{u}} (K : ObjectAlgebra U) :
    ArchitecturalEquationSystem K.contextPreorder :=
  K.equationReading.equationSystem

/-- The finite circuit reading indexed by the algebra's equation system. -/
def circuits {U : AtomCarrier.{u}} (K : ObjectAlgebra U) :
    EquationCircuitReading K.equationSystem :=
  K.equationReading.circuits

/-- The old law reading generated one-way from the primary equation reading. -/
def lawReading {U : AtomCarrier.{u}} (K : ObjectAlgebra U) : LawReading U :=
  K.equationReading.toLegacyLawReading

/-- I.定義10.1: read an object of the algebra. -/
def getObject {U : AtomCarrier.{u}} (algebra : ObjectAlgebra U)
    (object : algebra.Obj) : ArchitectureObject U :=
  algebra.object object

/-- The finite circuit fiber selected at an object and equation index. -/
def Circuit {U : AtomCarrier.{u}} (K : ObjectAlgebra U) (A : K.Obj)
    (i : K.equationSystem.Index) : Type u :=
  K.circuits.Circuit (K.object A) i

/-- Package an indexed algebra operation as an architecture operation. -/
def operation {U : AtomCarrier.{u}} (K : ObjectAlgebra U)
    {A B : K.Obj} (op : K.Op A B) : Operation U where
  source := K.object A
  target := K.object B
  configurationMap := K.configurationMap op

/-- I.定義10.1: the object accessor is the recorded object map. -/
theorem getObject_eq {U : AtomCarrier.{u}} (algebra : ObjectAlgebra U)
    (object : algebra.Obj) :
    algebra.getObject object = algebra.object object :=
  rfl

/-- An indexed algebra operation has the object at its first index as source. -/
theorem operation_source {U : AtomCarrier.{u}} (K : ObjectAlgebra U)
    {A B : K.Obj} (op : K.Op A B) :
    (K.operation op).source = K.object A :=
  rfl

/-- An indexed algebra operation has the object at its second index as target. -/
theorem operation_target {U : AtomCarrier.{u}} (K : ObjectAlgebra U)
    {A B : K.Obj} (op : K.Op A B) :
    (K.operation op).target = K.object B :=
  rfl

/-- An indexed algebra operation exposes its recorded configuration homomorphism. -/
theorem operation_configurationMap {U : AtomCarrier.{u}}
    (K : ObjectAlgebra U) {A B : K.Obj} (op : K.Op A B) :
    (K.operation op).configurationMap = K.configurationMap op :=
  rfl

/-- Every circuit in an indexed algebra refutes its selected equation. -/
theorem circuit_sound {U : AtomCarrier.{u}} (K : ObjectAlgebra U)
    (A : K.Obj) (i : K.equationSystem.Index)
    (c : K.Circuit A i) :
    ¬ K.equationSystem.EquationHolds i (K.object A) :=
  K.circuits.sound i (K.object A) c.1 c.2.1 c.2.2

/--
The indexed circuit fiber is inhabited exactly when a matching datum is
accepted by the corresponding detector.
-/
theorem circuit_nonempty_iff {U : AtomCarrier.{u}} (K : ObjectAlgebra U)
    (A : K.Obj) (i : K.equationSystem.Index) :
    Nonempty (K.Circuit A i) ↔
      ∃ Q : FiniteCircuitDatum U,
        Q.Matches (K.object A) ∧ K.circuits.accepts i Q = true := by
  constructor
  · rintro ⟨c⟩
    exact ⟨c.1, c.2⟩
  · rintro ⟨Q, hmatches, haccepts⟩
    exact ⟨⟨Q, hmatches, haccepts⟩⟩

end ObjectAlgebra

end AAT.AG
