import Formal.AG.Atom.Obstruction
import Formal.AG.Equation.Legacy

/-!
# One-way legacy circuit displays

This compatibility leaf converts equation-indexed circuit readings into the
older law-indexed display API.  Standard core and site modules depend only on
`EquationCircuitReading` and `EquationReading` from `Atom.Obstruction`.
-/

namespace AAT.AG

universe u

namespace EquationCircuitReading

variable {U : AtomCarrier.{u}} {A₀ : ArchitectureObject U}
variable {C : Site.ContextPreorderCategory A₀}
variable {E : ArchitecturalEquationSystem C}

/--
One-way compatibility conversion of an equation circuit reading, relative to
an explicitly supplied detector-soundness proof.
-/
def toLegacy (R : EquationCircuitReading E) (hSound : R.Sound) :
    CircuitReading E.toLegacyLawUniverse where
  code := R.code
  sound := by
    intro index object datum hmatches haccepts
    exact hSound index object datum hmatches haccepts

end EquationCircuitReading

namespace EquationReading

/--
The one-way legacy display generated by a core equation reading and its
explicit detector-soundness proof.
-/
def toLegacyLawReading {U : AtomCarrier.{u}} {object : ArchitectureObject U}
    (R : EquationReading object) (hSound : R.circuits.Sound) : LawReading U where
  lawUniverse := R.equationSystem.toLegacyLawUniverse
  circuits := R.circuits.toLegacy hSound

end EquationReading

end AAT.AG
