import ResearchLean.AG.AbelianLiftingObstruction.OriginalTowerPresentation
import ResearchLean.AG.AbelianLiftingObstruction.Cohomology
import ResearchLean.AG.TransportCoherence.ArbitraryObstruction

/-!
# The actual face defect of the selected tower

The defect is the difference between the authored and canonical comparisons
of the same selected paths. Core alignment proves that this difference lies
in the actual kernel of the first functor.
-/

namespace AAT.AG.AbelianLiftingObstruction

open CategoryTheory TransportCoherence TransportCoherence.Arbitrary

universe uG uE uB uD vE vB vD

/-- A two-step raw defect becomes a product when the later authored comparison
centralizes the earlier kernel defect. -/
private theorem rawProduct_of_central {G : Type*} [Group G]
    (ut uh mt mh dh dt : G)
    (hh : dh = uh * mh⁻¹) (ht : dt = ut * mt⁻¹)
    (hc : ut * dh = dh * ut) :
    (ut * uh) * (mt * mh)⁻¹ = dh * dt := by
  calc
    (ut * uh) * (mt * mh)⁻¹ = ut * (uh * mh⁻¹) * mt⁻¹ := by
      simp only [mul_inv_rev, mul_assoc]
    _ = ut * dh * mt⁻¹ := by rw [hh]
    _ = dh * ut * mt⁻¹ := by rw [hc]
    _ = dh * dt := by rw [ht]; exact mul_assoc _ _ _

namespace TowerPresentation

variable {K : FiniteTransportPresentation.{uG}}
variable {E : Type uE} {B : Type uB} {D : Type uD}
variable [Category.{vE} E] [Category.{vB} B] [Category.{vD} D]
variable {p : E ⥤ B} {q : B ⥤ D}
variable (T : TowerPresentation K p q)

/-- The original selected arrows and authored comparisons as arbitrary transport data. -/
abbrev toTransportData : TransportData K.toFiniteTransportTwoPresentation (p ⋙ q) where
  lift := T.upper
  faceBase := T.faceBase
  comparator := T.comparator

/-- The comparison generated by the same selected paths and their strong lifting property. -/
noncomputable def canonicalFace (f : K.TwoCell) :
    FiberAut (p ⋙ q) (T.upper.object (K.twoTarget f)) :=
  canonicalFiberComparator (p ⋙ q)
    (T.upper.pathBase (K.twoLeft f))
    (T.upper.pathLift (K.twoLeft f))
    (T.upper.pathLift (K.twoRight f))
    (T.upper.pathLift_isStronglyCocartesian (K.twoLeft f))
    (by rw [T.faceBase f]
        exact T.upper.pathLift_isStronglyCocartesian (K.twoRight f))

/-- G-129 B1: the same authored/canonical defect, restricted to the actual kernel. -/
noncomputable def faceDefect (f : K.TwoCell) :
    Kernel p q (T.upper.object (K.twoTarget f)) :=
  faceKernelDefect p q
    (T.upper.pathLift (K.twoLeft f))
    (T.upper.pathLift (K.twoRight f))
    (T.upper.pathLift_isStronglyCocartesian (K.twoLeft f))
    (by rw [T.faceBase f]
        exact T.upper.pathLift_isStronglyCocartesian (K.twoRight f))
    (T.pathLowerStrong (K.twoLeft f))
    (T.comparator f) (T.coreAlignment f)

/-- B1 preserves the original noncommutative order `u * m⁻¹`. -/
theorem faceDefect_inclusion (f : K.TwoCell) :
    kernelInclusion p q _ (T.faceDefect f) =
      T.comparator f * (T.canonicalFace f)⁻¹ := by
  unfold faceDefect canonicalFace
  exact faceKernelDefect_inclusion p q
    (T.upper.pathLift (K.twoLeft f))
    (T.upper.pathLift (K.twoRight f))
    (T.upper.pathLift_isStronglyCocartesian (K.twoLeft f))
    (by rw [T.faceBase f]
        exact T.upper.pathLift_isStronglyCocartesian (K.twoRight f))
    (T.pathLowerStrong (K.twoLeft f))
    (T.comparator f) (T.coreAlignment f)

/-- The same B1 value is the existing raw defect at the identity reselection. -/
theorem faceDefect_eq_raw (f : K.TwoCell) :
    kernelInclusion p q _ (T.faceDefect f) =
      rawFaceDefect T.toTransportData 1 f := by
  rw [faceDefect_inclusion T, rawFaceDefect_one]
  rfl

/-- The named canonical comparison is the existing initial comparison. -/
theorem canonicalFace_eq_initial (f : K.TwoCell) :
    T.canonicalFace f = initialCanonicalFaceComparator T.toTransportData f := rfl

/-- G-129 B: the actual face defect in the C² of the already constructed complex. -/
noncomputable def defect : C2 T.localCoefficients :=
  fun f => Additive.ofMul (T.faceDefect f)

/-- Projection of every defect coordinate is the identity core automorphism. -/
theorem defect_projection (f : K.TwoCell) :
    fiberPushforward p q _ (kernelInclusion p q _ (T.faceDefect f)) = 1 :=
  (T.faceDefect f).2

/-- Whiskering an actual kernel element is the already constructed path transport. -/
theorem whisker_kernel {i j : K.Vertex} (w : K.Path i j)
    (a : Kernel p q (T.upper.object i)) :
    whiskerFiberAut T.upper 1 (kernelInclusion p q _ a) w =
      kernelInclusion p q _ (T.pathKernelTransportHom w a) := by
  apply FiberAut.ext_of_strong_fac (T.upper.pathLift w)
    (T.upper.pathLift_isStronglyCocartesian w)
  calc
    T.upper.pathLift w ≫
        FiberAut.hom (whiskerFiberAut T.upper 1 (kernelInclusion p q _ a) w) =
      reselectedPathLift T.upper 1 w ≫
        FiberAut.hom (whiskerFiberAut T.upper 1 (kernelInclusion p q _ a) w) := by
          rw [Arbitrary.reselectedPathLift_one]
    _ = fiberAutThenPath T.upper 1 (kernelInclusion p q _ a) w :=
      whiskerFiberAut_fac T.upper 1 (kernelInclusion p q _ a) w
    _ = FiberAut.hom (kernelInclusion p q _ a) ≫ T.upper.pathLift w := by
      simp only [Arbitrary.fiberAutThenPath, Arbitrary.reselectedPathLift_one]
    _ = T.upper.pathLift w ≫
        FiberAut.hom (kernelInclusion p q _ (T.pathKernelTransportHom w a)) :=
      (kernelTransportHom_fac p q (T.upper.pathLift w)
        (T.upper.pathLift_isStronglyCocartesian w)
        (T.pathLowerStrong w) a).symm

/-- Centralization of the whole actual kernel survives transport along any path. -/
theorem whisker_centralizes {i j : K.Vertex} (w : K.Path i j)
    (u : FiberAut (p ⋙ q) (T.upper.object i))
    (hu : ∀ a : Kernel p q (T.upper.object i),
      u * kernelInclusion p q _ a = kernelInclusion p q _ a * u) :
    ∀ b : Kernel p q (T.upper.object j),
      whiskerFiberAut T.upper 1 u w * kernelInclusion p q _ b =
        kernelInclusion p q _ b * whiskerFiberAut T.upper 1 u w := by
  intro b
  obtain ⟨a, rfl⟩ := (T.pathKernelTransportBijective w).2 b
  rw [← T.whisker_kernel w a]
  have h := congrArg (whiskerFiberAutHom T.upper 1 w) (hu a)
  simpa only [MonoidHom.map_mul] using h

/-- Reversing an authored face changes its actual kernel defect to its inverse. -/
theorem reverseFaceDefect (f : K.TwoCell) :
    (T.comparator f)⁻¹ * (T.canonicalFace f) =
      (kernelInclusion p q _ (T.faceDefect f))⁻¹ := by
  let u := T.comparator f
  let m := T.canonicalFace f
  let d := kernelInclusion p q _ (T.faceDefect f)
  have hd : d = u * m⁻¹ := by
    exact T.faceDefect_inclusion f
  have hc : Commute u d := T.comparatorCentralizes f (T.faceDefect f)
  have hm : m = d⁻¹ * u := by
    rw [hd]
    simp [mul_inv_rev, mul_assoc]
  change u⁻¹ * m = d⁻¹
  calc
    u⁻¹ * m = u⁻¹ * (d⁻¹ * u) := by rw [hm]
    _ = (u⁻¹ * d⁻¹) * u := (mul_assoc _ _ _).symm
    _ = (d⁻¹ * u⁻¹) * u := by rw [hc.inv_inv.eq]
    _ = d⁻¹ := by simp [mul_assoc]

/-- A face defect carried through a suffix is exactly transported kernel data. -/
theorem whisker_faceDefect (f : K.TwoCell)
    {j : K.Vertex} (w : K.Path (K.twoTarget f) j) :
    whiskerFiberAut T.upper 1
      (T.comparator f * (T.canonicalFace f)⁻¹) w =
      kernelInclusion p q _ (T.pathKernelTransportHom w (T.faceDefect f)) := by
  rw [← T.faceDefect_inclusion f]
  exact T.whisker_kernel w (T.faceDefect f)

/-- Both orientations of a whiskered face give the signed C² value. -/
theorem orientedFaceDefect_inclusion {source target : K.Vertex}
    (f : WhiskeredFace K.toFiniteTransportTwoPresentation source target) :
    orientedFaceDefect T.toTransportData 1 f =
      kernelInclusion p q _
        (Additive.toMul (faceCorrection T.localCoefficients T.defect f)) := by
  rcases f with ⟨cell, incoming, outgoing, orientation⟩
  have winv (u : FiberAut (p ⋙ q) (T.upper.object (K.twoTarget cell))) :
      whiskerFiberAut T.upper 1 u⁻¹ outgoing =
        (whiskerFiberAut T.upper 1 u outgoing)⁻¹ :=
    map_inv (whiskerFiberAutHom T.upper 1 outgoing) u
  cases orientation with
  | forward =>
      simp only [Arbitrary.orientedFaceDefect, Arbitrary.orientedFaceAuthoredComparator,
        Arbitrary.orientedFaceCanonicalComparator, Arbitrary.orientedFaceComparator,
        Arbitrary.authoredComparatorFamily, Arbitrary.canonicalComparatorFamily]
      rw [canonicalFaceComparator_one, ← T.canonicalFace_eq_initial cell]
      change whiskerFiberAut T.upper 1 (T.comparator cell) outgoing *
        (whiskerFiberAut T.upper 1 (T.canonicalFace cell) outgoing)⁻¹ = _
      have h := T.whisker_faceDefect cell outgoing
      rw [whiskerFiberAut_mul, winv] at h
      have hco : Additive.toMul
          (faceCorrection T.localCoefficients T.defect
            { cell := cell, incoming := incoming, outgoing := outgoing,
              orientation := FaceOrientation.forward }) =
          T.pathKernelTransportHom outgoing (T.faceDefect cell) := by
        change Additive.toMul
          (T.edgeCoefficients.pathTransport outgoing
            (Additive.ofMul (T.faceDefect cell))) = _
        rw [T.edgeCoefficients_pathTransport]
        rfl
      exact h.trans (congrArg (kernelInclusion p q _) hco.symm)
  | backward =>
      simp only [Arbitrary.orientedFaceDefect, Arbitrary.orientedFaceAuthoredComparator,
        Arbitrary.orientedFaceCanonicalComparator, Arbitrary.orientedFaceComparator,
        Arbitrary.authoredComparatorFamily, Arbitrary.canonicalComparatorFamily]
      rw [canonicalFaceComparator_one, ← T.canonicalFace_eq_initial cell]
      change whiskerFiberAut T.upper 1 (T.comparator cell)⁻¹ outgoing *
        (whiskerFiberAut T.upper 1 (T.canonicalFace cell)⁻¹ outgoing)⁻¹ = _
      have h := T.reverseFaceDefect cell
      have hw := congrArg (fun u => whiskerFiberAut T.upper 1 u outgoing) h
      change whiskerFiberAut T.upper 1
          ((T.comparator cell)⁻¹ * T.canonicalFace cell) outgoing =
        whiskerFiberAut T.upper 1
          (kernelInclusion p q _ (T.faceDefect cell))⁻¹ outgoing at hw
      rw [whiskerFiberAut_mul, winv] at hw
      rw [winv (kernelInclusion p q _ (T.faceDefect cell)),
        T.whisker_kernel outgoing (T.faceDefect cell)] at hw
      have hco : Additive.toMul
          (faceCorrection T.localCoefficients T.defect
            { cell := cell, incoming := incoming, outgoing := outgoing,
              orientation := FaceOrientation.backward }) =
          (T.pathKernelTransportHom outgoing (T.faceDefect cell))⁻¹ := by
        change Additive.toMul
          (-T.edgeCoefficients.pathTransport outgoing
            (Additive.ofMul (T.faceDefect cell))) = _
        rw [T.edgeCoefficients_pathTransport]
        rfl
      rw [winv (T.comparator cell), winv (T.canonicalFace cell), inv_inv]
      exact hw.trans ((map_inv (kernelInclusion p q _) _).symm.trans
        (congrArg (kernelInclusion p q _) hco.symm))

/-- Authored oriented comparisons centralize the entire actual kernel at the outer endpoint. -/
theorem orientedAuthored_centralizes {source target : K.Vertex}
    (f : WhiskeredFace K.toFiniteTransportTwoPresentation source target) :
    ∀ b : Kernel p q (T.upper.object target),
      orientedFaceAuthoredComparator T.toTransportData 1 f *
        kernelInclusion p q _ b =
      kernelInclusion p q _ b *
        orientedFaceAuthoredComparator T.toTransportData 1 f := by
  rcases f with ⟨cell, incoming, outgoing, orientation⟩
  cases orientation with
  | forward =>
      simpa only [Arbitrary.orientedFaceAuthoredComparator,
        Arbitrary.orientedFaceComparator, Arbitrary.authoredComparatorFamily]
        using T.whisker_centralizes outgoing (T.comparator cell)
          (T.comparatorCentralizes cell)
  | backward =>
      have hsource : ∀ a : Kernel p q (T.upper.object (K.twoTarget cell)),
          (T.comparator cell)⁻¹ * kernelInclusion p q _ a =
            kernelInclusion p q _ a * (T.comparator cell)⁻¹ := by
        intro a
        exact (show Commute (T.comparator cell) (kernelInclusion p q _ a)
          from T.comparatorCentralizes cell a).inv_left.eq
      simpa only [Arbitrary.orientedFaceAuthoredComparator,
        Arbitrary.orientedFaceComparator, Arbitrary.authoredComparatorFamily]
        using T.whisker_centralizes outgoing (T.comparator cell)⁻¹ hsource

/-- The authored comparison of an entire typed pasting centralizes the actual kernel. -/
theorem pastingAuthored_centralizes {source target : K.Vertex}
    {before after : K.Path source target}
    (P : RewritePasting K.toFiniteTransportTwoPresentation before after) :
    ∀ b : Kernel p q (T.upper.object target),
      authoredPastingComparator T.toTransportData 1 P * kernelInclusion p q _ b =
        kernelInclusion p q _ b * authoredPastingComparator T.toTransportData 1 P := by
  induction P with
  | nil path =>
      intro b
      simp [Arbitrary.authoredPastingComparator, Arbitrary.pastingComparator]
  | cons step tail ih =>
      intro b
      rcases step with ⟨face, rfl, rfl⟩
      change
        (authoredPastingComparator T.toTransportData 1 tail *
            orientedFaceAuthoredComparator T.toTransportData 1 face) *
          kernelInclusion p q _ b =
        kernelInclusion p q _ b *
          (authoredPastingComparator T.toTransportData 1 tail *
            orientedFaceAuthoredComparator T.toTransportData 1 face)
      calc
        _ = authoredPastingComparator T.toTransportData 1 tail *
            (orientedFaceAuthoredComparator T.toTransportData 1 face *
              kernelInclusion p q _ b) := mul_assoc _ _ _
        _ = authoredPastingComparator T.toTransportData 1 tail *
            (kernelInclusion p q _ b *
              orientedFaceAuthoredComparator T.toTransportData 1 face) := by
                rw [T.orientedAuthored_centralizes face b]
        _ = (authoredPastingComparator T.toTransportData 1 tail *
              kernelInclusion p q _ b) *
            orientedFaceAuthoredComparator T.toTransportData 1 face :=
              (mul_assoc _ _ _).symm
        _ = (kernelInclusion p q _ b *
              authoredPastingComparator T.toTransportData 1 tail) *
            orientedFaceAuthoredComparator T.toTransportData 1 face := by rw [ih b]
        _ = _ := mul_assoc _ _ _

/-- The existing raw defect of any typed pasting is the inclusion of its signed C² sum. -/
theorem pastingRawDefect_inclusion {source target : K.Vertex}
    {before after : K.Path source target}
    (P : RewritePasting K.toFiniteTransportTwoPresentation before after) :
    pastingRawDefect T.toTransportData 1 P =
      kernelInclusion p q _
        (Additive.toMul (pastingCorrection T.localCoefficients T.defect P)) := by
  induction P with
  | nil path =>
      simp [Arbitrary.pastingRawDefect, Arbitrary.authoredPastingComparator,
        Arbitrary.canonicalPastingComparator, Arbitrary.pastingComparator,
        pastingCorrection]
  | cons step tail ih =>
      rcases step with ⟨face, rfl, rfl⟩
      let uh := orientedFaceAuthoredComparator T.toTransportData 1 face
      let mh := orientedFaceCanonicalComparator T.toTransportData 1 face
      let ut := authoredPastingComparator T.toTransportData 1 tail
      let mt := canonicalPastingComparator T.toTransportData 1 tail
      let dh := kernelInclusion p q _
        (Additive.toMul (faceCorrection T.localCoefficients T.defect face))
      let dt := kernelInclusion p q _
        (Additive.toMul (pastingCorrection T.localCoefficients T.defect tail))
      have hh : dh = uh * mh⁻¹ := (T.orientedFaceDefect_inclusion face).symm
      have ht : dt = ut * mt⁻¹ := ih.symm
      have hc : ut * dh = dh * ut := T.pastingAuthored_centralizes tail _
      have h := rawProduct_of_central ut uh mt mh dh dt hh ht hc
      change (ut * uh) * (mt * mh)⁻¹ =
        kernelInclusion p q _
          (Additive.toMul
            (faceCorrection T.localCoefficients T.defect face +
              pastingCorrection T.localCoefficients T.defect tail))
      calc
        (ut * uh) * (mt * mh)⁻¹ = dh * dt := h
        _ = _ := by
          change kernelInclusion p q _
              (Additive.toMul (faceCorrection T.localCoefficients T.defect face)) *
              kernelInclusion p q _
                (Additive.toMul (pastingCorrection T.localCoefficients T.defect tail)) = _
          exact (map_mul (kernelInclusion p q _) _ _).symm

/-- G-129 B: condition 4 makes the actual face defect a cocycle of the same complex. -/
theorem defect_cocycle
    (hsyzygy : ∀ s : K.ThreeCell,
      AuthoredSyzygy T.toTransportData 1 (K.threeLeft s) (K.threeRight s)) :
    d2 T.localCoefficients T.defect = 0 := by
  funext s
  have hraw := rawDefect_cocycle_of_authoredSyzygy T.toTransportData 1
    (K.threeLeft s) (K.threeRight s) (hsyzygy s)
  rw [T.pastingRawDefect_inclusion, T.pastingRawDefect_inclusion] at hraw
  have hkernel := (kernelInclusion_injective p q
    (T.upper.object (K.threeTarget s))) hraw
  have hsum := Additive.ext hkernel
  change pastingCorrection T.localCoefficients T.defect (K.threeLeft s) -
    pastingCorrection T.localCoefficients T.defect (K.threeRight s) = 0
  exact sub_eq_zero.mpr hsum

end TowerPresentation

end AAT.AG.AbelianLiftingObstruction

#assert_standard_axioms_only AAT.AG.AbelianLiftingObstruction
