import Mathlib.Algebra.Ring.Prod
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum
import Formal.Util.AssertStandardAxioms

/-!
# Automorphisms of the integral pair coefficient ring

G-129 completion condition 4 uses diagonal coefficients in `Int × Int`.
These API lemmas apply to arbitrary ring automorphisms, independently of any
geometry package. The two primitive idempotents determine the automorphism.
-/

namespace AAT.AG.AbelianLiftingObstruction.PairCoefficients

/-- The first primitive idempotent detects the two possible coefficient actions. -/
def first : Int × Int := (1, 0)

/-- API: every pair is generated by integer scalars and the first idempotent. -/
theorem decompose (z : Int × Int) :
    z = (z.1 : Int × Int) * first + (z.2 : Int × Int) * (1 - first) := by
  ext <;> simp [first]

/-- API: ring homomorphisms out of the pair ring are determined by one idempotent. -/
theorem hom_ext {R : Type*} [Ring R] {f g : (Int × Int) →+* R}
    (h : f first = g first) : f = g := by
  ext z
  rw [decompose z]
  simp only [map_add, map_mul, map_intCast, map_sub, map_one, h]

/-- Every automorphism permutes the two primitive idempotents. -/
theorem image_first (f : (Int × Int) ≃+* (Int × Int)) :
    f first = first ∨ f first = 1 - first := by
  have hn0 : f first ≠ 0 := by
    intro h
    have : first = 0 := f.injective (h.trans (map_zero f).symm)
    norm_num [first] at this
  have hn1 : f first ≠ 1 := by
    intro h
    have : first = 1 := f.injective (h.trans (map_one f).symm)
    norm_num [first] at this
  have hi : f first * f first = f first := by
    rw [← map_mul]
    congr 1
  rcases image : f first with ⟨x, y⟩
  have hx : x * x = x := by simpa [image] using congrArg Prod.fst hi
  have hy : y * y = y := by simpa [image] using congrArg Prod.snd hi
  have hc (a : Int) (ha : a * a = a) : a = 0 ∨ a = 1 := by
    have h : a * (a - 1) = 0 := by nlinarith
    rcases mul_eq_zero.mp h with h | h
    · exact Or.inl h
    · exact Or.inr (sub_eq_zero.mp h)
  rcases hc x hx with rfl | rfl <;> rcases hc y hy with rfl | rfl
  · exact False.elim (hn0 image)
  · exact Or.inr rfl
  · exact Or.inl rfl
  · exact False.elim (hn1 image)

/-- G-129 geometry kernel API: all pair coefficient automorphisms commute. -/
theorem comp_comm (f g : (Int × Int) ≃+* (Int × Int)) :
    f.toRingHom.comp g.toRingHom = g.toRingHom.comp f.toRingHom := by
  apply hom_ext
  change f (g first) = g (f first)
  rcases image_first f with hf | hf <;> rcases image_first g with hg | hg
  all_goals simp only [hf, hg, map_sub, map_one]

/-- G-129 geometry example API: every coefficient automorphism squares to identity. -/
theorem square (f : (Int × Int) ≃+* (Int × Int)) :
    f.toRingHom.comp f.toRingHom = RingHom.id _ := by
  apply hom_ext
  change f (f first) = first
  rcases image_first f with h | h
  · rw [h, h]
  · rw [h, map_sub, map_one, h]
    simp

end AAT.AG.AbelianLiftingObstruction.PairCoefficients

#assert_standard_axioms_only AAT.AG.AbelianLiftingObstruction.PairCoefficients
