import ResearchLean.AG.AbelianLiftingObstruction.PathKernelTransport

/-!
# The original tower on a finite transport presentation

G-129 A keeps the original objects, edge arrows, their two strong properties,
the authored face comparator, and core alignment in one typed input. The
kernel and edge transport are derived from the two functors; only abelianness,
bijectivity on that derived kernel, and centralization remain assumptions.

## Implementation notes

The upper `LiftData` is the existing arbitrary-functor realization. The lower
strong property is attached to its image under the actual first functor, so
there is no independent lower edge arrow that could drift from the input.
-/

namespace AAT.AG.AbelianLiftingObstruction

open CategoryTheory TransportCoherence TransportCoherence.Arbitrary

universe uG uE uB uD vE vB vD

/-- G-129 A: primitive tower data and precisely the four kinds of hypotheses used later. -/
structure TowerPresentation (K : FiniteTransportPresentation.{uG})
    {E : Type uE} {B : Type uB} {D : Type uD}
    [Category.{vE} E] [Category.{vB} B] [Category.{vD} D]
    (p : E ⥤ B) (q : B ⥤ D) where
  /-- Original objects and edge arrows, strong for the composite projection. -/
  upper : LiftData K.toFiniteTransportTwoPresentation (p ⋙ q)
  /-- The image of each same edge is strong for the second projection. -/
  lowerStrong : ∀ {i j : K.Vertex} (e : K.Edge i j),
    q.IsStronglyCocartesian (upper.edgeBase e) (p.map (upper.edgeLift e))
  /-- The two authored face paths agree in the bottom category. -/
  faceBase : ∀ f : K.TwoCell,
    upper.pathBase (K.twoLeft f) = upper.pathBase (K.twoRight f)
  /-- Authored terminal comparison, independent of the canonical comparison. -/
  comparator : ∀ f : K.TwoCell,
    FiberAut (p ⋙ q) (upper.object (K.twoTarget f))
  /-- Core coherence of the selected edge lifts, G-129 (A2). -/
  coreAlignment : ∀ f : K.TwoCell,
    p.map (upper.pathLift (K.twoLeft f)) ≫
      p.map (FiberAut.hom (comparator f)) =
      p.map (upper.pathLift (K.twoRight f))
  /-- G-129 condition 1 on the actual kernel at every vertex. -/
  kernelComm : ∀ v : K.Vertex, ∀ a b : Kernel p q (upper.object v),
    a * b = b * a
  /-- G-129 condition 2: the generated map on the actual kernel is bijective. -/
  edgeBijective : ∀ {i j : K.Vertex} (e : K.Edge i j),
    Function.Bijective (kernelTransportHom p q (upper.edgeLift e)
      (upper.edgeStrong e) (lowerStrong e))
  /-- G-129 condition 3: each authored comparator centralizes the entire actual kernel. -/
  comparatorCentralizes : ∀ f : K.TwoCell,
    ∀ a : Kernel p q (upper.object (K.twoTarget f)),
      comparator f * kernelInclusion p q _ a =
        kernelInclusion p q _ a * comparator f

namespace TowerPresentation

variable {K : FiniteTransportPresentation.{uG}}
variable {E : Type uE} {B : Type uB} {D : Type uD}
variable [Category.{vE} E] [Category.{vB} B] [Category.{vD} D]
variable {p : E ⥤ B} {q : B ⥤ D}
variable (T : TowerPresentation K p q)

/-- G-129 A: the same original path image is strong for the lower projection. -/
theorem pathLowerStrong {i j : K.Vertex} (w : K.Path i j) :
    q.IsStronglyCocartesian (T.upper.pathBase w)
      (p.map (T.upper.pathLift w)) := by
  induction w with
  | nil v =>
      simpa only [LiftData.pathBase, LiftData.pathLift, p.map_id] using
        identityStrong q (p.obj (T.upper.object v))
  | cons e tail ih =>
      letI : q.IsStronglyCocartesian (T.upper.edgeBase e)
          (p.map (T.upper.edgeLift e)) := T.lowerStrong e
      letI : q.IsStronglyCocartesian (T.upper.pathBase tail)
          (p.map (T.upper.pathLift tail)) := ih
      simpa only [LiftData.pathBase, LiftData.pathLift, p.map_comp] using
        (Functor.IsStronglyCocartesian.comp q :
          q.IsStronglyCocartesian
            (T.upper.edgeBase e ≫ T.upper.pathBase tail)
            (p.map (T.upper.edgeLift e) ≫ p.map (T.upper.pathLift tail)))

/-- The actual kernel map along an original path, generated by its composed arrow. -/
noncomputable def pathKernelTransportHom {i j : K.Vertex} (w : K.Path i j) :
    Kernel p q (T.upper.object i) →* Kernel p q (T.upper.object j) :=
  kernelTransportHom p q (T.upper.pathLift w)
    (T.upper.pathLift_isStronglyCocartesian w) (T.pathLowerStrong w)

/-- API: the empty path induces the identity of the actual kernel. -/
theorem pathKernelTransportHom_nil (v : K.Vertex) :
    T.pathKernelTransportHom (PresentedPath.nil v) =
      MonoidHom.id (Kernel p q (T.upper.object v)) := by
  simpa only [pathKernelTransportHom, LiftData.pathLift] using
    kernelTransport_identity p q (T.upper.object v)

/-- API: a cons path transports across its edge and then its tail. -/
theorem pathKernelTransportHom_cons {i j k : K.Vertex}
    (e : K.Edge i j) (w : K.Path j k) :
    T.pathKernelTransportHom (PresentedPath.cons e w) =
      (T.pathKernelTransportHom w).comp
        (kernelTransportHom p q (T.upper.edgeLift e)
          (T.upper.edgeStrong e) (T.lowerStrong e)) := by
  simpa only [pathKernelTransportHom, LiftData.pathLift] using
    kernelTransportHom_comp p q (T.upper.edgeLift e) (T.upper.pathLift w)
      (T.upper.edgeStrong e) (T.upper.pathLift_isStronglyCocartesian w)
      (T.lowerStrong e) (T.pathLowerStrong w)

/-- G-129 A condition 2 on edges implies bijectivity along every original path. -/
theorem pathKernelTransportBijective {i j : K.Vertex} (w : K.Path i j) :
    Function.Bijective (T.pathKernelTransportHom w) := by
  induction w with
  | nil v =>
      rw [T.pathKernelTransportHom_nil]
      exact Function.bijective_id
  | cons e tail ih =>
      rw [T.pathKernelTransportHom_cons]
      exact ih.comp (T.edgeBijective e)

/-- G-129 A: the vertex groups and edge equivalences use the actual projection kernel. -/
noncomputable def edgeCoefficients : EdgeCoefficients K where
  A v := KernelCoefficient p q (T.upper.object v)
  commGroup v := by
    letI : CommGroup (Kernel p q (T.upper.object v)) :=
      kernelCommGroup p q (T.upper.object v) (T.kernelComm v)
    infer_instance
  edge e := kernelTransportAddEquiv p q (T.upper.edgeLift e)
    (T.upper.edgeStrong e) (T.lowerStrong e) (T.edgeBijective e)

/-- API: recursive additive path transport is the original path's generated kernel map. -/
theorem edgeCoefficients_pathTransport {i j : K.Vertex}
    (w : K.Path i j) (a : Kernel p q (T.upper.object i)) :
    (T.edgeCoefficients.pathTransport w) (Additive.ofMul a) =
      Additive.ofMul (T.pathKernelTransportHom w a) := by
  induction w with
  | nil v =>
      rw [T.pathKernelTransportHom_nil]
      rfl
  | cons e tail ih =>
      rw [T.pathKernelTransportHom_cons]
      simp only [EdgeCoefficients.pathTransport, AddEquiv.trans_apply,
        MonoidHom.comp_apply]
      exact ih (kernelTransportHom p q (T.upper.edgeLift e)
        (T.upper.edgeStrong e) (T.lowerStrong e) a)

/-- G-129 A: core alignment and centralization discharge the authored face relation. -/
theorem edgeCoefficients_face (f : K.TwoCell) :
    T.edgeCoefficients.pathTransport (K.twoLeft f) =
      T.edgeCoefficients.pathTransport (K.twoRight f) := by
  let left := K.twoLeft f
  let right := K.twoRight f
  have hupperRight : (p ⋙ q).IsStronglyCocartesian
      (T.upper.pathBase left) (T.upper.pathLift right) := by
    rw [T.faceBase f]
    exact T.upper.pathLift_isStronglyCocartesian right
  have hlowerRight : q.IsStronglyCocartesian
      (T.upper.pathBase left) (p.map (T.upper.pathLift right)) := by
    rw [T.faceBase f]
    exact T.pathLowerStrong right
  have heq :=
    (centralizes_iff_kernelTransport_eq p q
      (T.upper.pathLift left) (T.upper.pathLift right)
      (T.upper.pathLift_isStronglyCocartesian left) hupperRight
      (T.pathLowerStrong left) hlowerRight
      (T.kernelComm (K.twoTarget f)) (T.comparator f)
      (T.coreAlignment f)
      (T.pathKernelTransportBijective left).2).mp
        (T.comparatorCentralizes f)
  change T.pathKernelTransportHom right = T.pathKernelTransportHom left at heq
  apply AddEquiv.ext
  intro a
  let b : Kernel p q (T.upper.object (K.twoSource f)) := Additive.toMul a
  calc
    (T.edgeCoefficients.pathTransport left) a =
        Additive.ofMul (T.pathKernelTransportHom left b) :=
          T.edgeCoefficients_pathTransport left b
    _ = Additive.ofMul (T.pathKernelTransportHom right b) := by rw [heq]
    _ = (T.edgeCoefficients.pathTransport right) a :=
          (T.edgeCoefficients_pathTransport right b).symm

/-- G-129 A: the same actual kernels and edge maps descend to local coefficients. -/
noncomputable def localCoefficients : LocalCoefficients K where
  toEdgeCoefficients := T.edgeCoefficients
  face_transport := T.edgeCoefficients_face

end TowerPresentation

end AAT.AG.AbelianLiftingObstruction

#assert_standard_axioms_only AAT.AG.AbelianLiftingObstruction
