pub const AAT_ATOM_VOCABULARY_V1_SCHEMA: &str = "aat-atom-vocabulary/v0.5.5";
pub const ARCHMAP_V2_SCHEMA: &str = "archmap/v0.5.4";
pub const ARCHMAP_VALIDATION_REPORT_SCHEMA_VERSION: &str = "archmap-validation-report/v0.5.4";
pub const LAW_POLICY_V1_SCHEMA: &str = "law-policy/v0.5.4";
pub const LAW_POLICY_VALIDATION_REPORT_SCHEMA_VERSION: &str = "law-policy-validation-report/v0.5.4";
pub const NORMALIZED_ARCHMAP_V2_SCHEMA: &str = "normalized-archmap/v0.5.4";
pub const MEASUREMENT_PROFILE_V1_SCHEMA: &str = "measurement-profile/v0.5.4";
pub const ARCHSIG_BOUNDARY_STATEMENT_V1_SCHEMA: &str = "archsig-boundary-statement/v0.5.4";
pub const ARCHSIG_MEASUREMENT_PACKET_V1_SCHEMA: &str = "archsig-measurement-packet/v0.5.4";
pub const ARCHSIG_GATE_POLICY_V1_SCHEMA: &str = "archsig-gate-policy/v0.5.4";
pub const ARCHSIG_GATE_REPORT_V1_SCHEMA: &str = "archsig-gate-report/v0.5.4";
pub const ARCHSIG_ARCHMAP_DIFF_V1_SCHEMA: &str = "archmap-diff/v0.5.4";
pub const ARCHSIG_COMPARISON_REPORT_V1_SCHEMA: &str = "archsig-comparison-report/v0.5.7";
pub const ARCHSIG_COMPARISON_NO_NEW_MEASURED_OBSTRUCTION_RECORDED: &str =
    "NO_NEW_MEASURED_OBSTRUCTION_RECORDED";
pub const ARCHSIG_COMPARISON_MEASURED_OBSTRUCTION_RECORDED_AFTER_CHANGE: &str =
    "MEASURED_OBSTRUCTION_RECORDED_AFTER_CHANGE";
pub const ARCHSIG_COMPARISON_MEASURED_OBSTRUCTION_NO_LONGER_RECORDED_AFTER_CHANGE: &str =
    "MEASURED_OBSTRUCTION_NO_LONGER_RECORDED_AFTER_CHANGE";
pub const ARCHSIG_COMPARISON_RUNS_NOT_COMPARABLE_WITHOUT_COMPARISON_DATA: &str =
    "RUNS_NOT_COMPARABLE_WITHOUT_COMPARISON_DATA";
// Generated evaluator contract IDs are owned by ArchSig's computation layer.
// Keep this registry as the single source of truth for the IDs emitted into
// assumption ledgers and comparison readings.
pub const ARCHSIG_CONTRACT_AG_RESTRICTION_COMPATIBILITY: &str =
    "archsig-contract:ag-restriction-compatibility";
pub const ARCHSIG_CONTRACT_AG_SECTION_FACTORIZATION: &str =
    "archsig-contract:ag-section-factorization";
pub const ARCHSIG_CONTRACT_LAW_SURFACE_QUOTIENT_SHEAF_CONDITION: &str =
    "archsig-contract:law-surface-quotient-sheaf-condition";
pub const ARCHSIG_CONTRACT_SAGA_DERIVED_FINITE_COMPLEX_ENUMERATION: &str =
    "archsig-contract:saga-derived-finite-complex-enumeration";
pub const ARCHSIG_CONTRACT_RESIDUAL_DIFFERENCE_READING: &str =
    "archsig-contract:residual-difference-reading";
pub const ARCHSIG_GENERATED_CONTRACT_IDS: [&str; 5] = [
    ARCHSIG_CONTRACT_AG_RESTRICTION_COMPATIBILITY,
    ARCHSIG_CONTRACT_AG_SECTION_FACTORIZATION,
    ARCHSIG_CONTRACT_LAW_SURFACE_QUOTIENT_SHEAF_CONDITION,
    ARCHSIG_CONTRACT_SAGA_DERIVED_FINITE_COMPLEX_ENUMERATION,
    ARCHSIG_CONTRACT_RESIDUAL_DIFFERENCE_READING,
];
pub const ARCHSIG_COMPARISON_CONCLUSION_CODES: [&str; 4] = [
    ARCHSIG_COMPARISON_NO_NEW_MEASURED_OBSTRUCTION_RECORDED,
    ARCHSIG_COMPARISON_MEASURED_OBSTRUCTION_RECORDED_AFTER_CHANGE,
    ARCHSIG_COMPARISON_MEASURED_OBSTRUCTION_NO_LONGER_RECORDED_AFTER_CHANGE,
    ARCHSIG_COMPARISON_RUNS_NOT_COMPARABLE_WITHOUT_COMPARISON_DATA,
];
pub const ARCHSIG_COMPARISON_CLASS_TRANSPORT_CONCLUSION_CODES: [&str; 1] =
    [ARCHSIG_CLASS_ZERO_TRANSPORTED_UNDER_CHECKED_REFINEMENT];
pub const ARCHSIG_GATE_BLOCKED_BY_GATE_POLICY: &str = "BLOCKED_BY_GATE_POLICY";
pub const ARCHSIG_GATE_PASS_WITHIN_GATE_POLICY: &str = "PASS_WITHIN_GATE_POLICY";
pub const ARCHSIG_GATE_NOT_EVALUABLE: &str = "NOT_EVALUABLE";
pub const ARCHSIG_GATE_REPORT_DECISIONS: [&str; 3] = [
    ARCHSIG_GATE_PASS_WITHIN_GATE_POLICY,
    ARCHSIG_GATE_BLOCKED_BY_GATE_POLICY,
    ARCHSIG_GATE_NOT_EVALUABLE,
];
pub const ARCHSIG_SAGA_REPAIR_GLUES_WITHIN_SELECTED_COMPLEX: &str =
    "REPAIR_GLUES_WITHIN_SELECTED_COMPLEX";
pub const ARCHSIG_SAGA_MEASURED_NONGLUING_RESIDUAL: &str = "MEASURED_NONGLUING_RESIDUAL";
pub const ARCHSIG_MEASURED_NONGLUING_RESIDUAL_CLASS: &str = "MEASURED_NONGLUING_RESIDUAL_CLASS";
pub const ARCHSIG_MEASURED_LAW_DEFECT_AT_CHART: &str = "MEASURED_LAW_DEFECT_AT_CHART";
pub const ARCHSIG_DISPLAYED_LAWS_HOLD_ON_SELECTED_CHARTS: &str =
    "DISPLAYED_LAWS_HOLD_ON_SELECTED_CHARTS";
pub const ARCHSIG_CLASS_ZERO_TRANSPORTED_UNDER_CHECKED_REFINEMENT: &str =
    "CLASS_ZERO_TRANSPORTED_UNDER_CHECKED_REFINEMENT";
pub const ARCHSIG_TWO_PROFILES_REPORTED_SEPARATELY: &str = "TWO_PROFILES_REPORTED_SEPARATELY";
pub const ARCHSIG_CECH_COVER_SHAPE_EXCLUDES_GLUING_OBSTRUCTION: &str =
    "COVER_SHAPE_EXCLUDES_GLUING_OBSTRUCTION";
pub const ARCHSIG_REPAIR_TARGETS_IDENTIFIED: &str = "REPAIR_TARGETS_IDENTIFIED";
pub const ARCHSIG_MEASURED_H1_OBSTRUCTION_UNDER_PROFILE: &str =
    "MEASURED_H1_OBSTRUCTION_UNDER_PROFILE";
pub const ARCHSIG_MEASURED_AG_OBSTRUCTION_UNDER_PROFILE: &str =
    "MEASURED_AG_OBSTRUCTION_UNDER_PROFILE";
pub const ARCHSIG_NO_MEASURED_H1_OBSTRUCTION_UNDER_PROFILE: &str =
    "NO_MEASURED_H1_OBSTRUCTION_UNDER_PROFILE";
pub const ARCHSIG_AG_MEASUREMENT_FOUNDATION_READY_UNDER_PROFILE: &str =
    "AG_MEASUREMENT_FOUNDATION_READY_UNDER_PROFILE";
pub const ARCHSIG_VALIDATION_FAILED_BEFORE_MEASUREMENT: &str =
    "VALIDATION_FAILED_BEFORE_MEASUREMENT";
pub const ARCHSIG_ANALYSIS_CONCLUSION_CODES: [&str; 10] = [
    ARCHSIG_SAGA_MEASURED_NONGLUING_RESIDUAL,
    ARCHSIG_MEASURED_NONGLUING_RESIDUAL_CLASS,
    ARCHSIG_SAGA_REPAIR_GLUES_WITHIN_SELECTED_COMPLEX,
    ARCHSIG_CECH_COVER_SHAPE_EXCLUDES_GLUING_OBSTRUCTION,
    ARCHSIG_MEASURED_H1_OBSTRUCTION_UNDER_PROFILE,
    ARCHSIG_REPAIR_TARGETS_IDENTIFIED,
    ARCHSIG_MEASURED_AG_OBSTRUCTION_UNDER_PROFILE,
    ARCHSIG_NO_MEASURED_H1_OBSTRUCTION_UNDER_PROFILE,
    ARCHSIG_AG_MEASUREMENT_FOUNDATION_READY_UNDER_PROFILE,
    ARCHSIG_VALIDATION_FAILED_BEFORE_MEASUREMENT,
];
pub const ARCHSIG_SAGA_CONCLUSION_CODES: [&str; 8] = [
    ARCHSIG_SAGA_REPAIR_GLUES_WITHIN_SELECTED_COMPLEX,
    ARCHSIG_SAGA_MEASURED_NONGLUING_RESIDUAL,
    ARCHSIG_MEASURED_NONGLUING_RESIDUAL_CLASS,
    ARCHSIG_CECH_COVER_SHAPE_EXCLUDES_GLUING_OBSTRUCTION,
    ARCHSIG_REPAIR_TARGETS_IDENTIFIED,
    ARCHSIG_MEASURED_LAW_DEFECT_AT_CHART,
    ARCHSIG_DISPLAYED_LAWS_HOLD_ON_SELECTED_CHARTS,
    ARCHSIG_TWO_PROFILES_REPORTED_SEPARATELY,
];
pub const ARCHSIG_RUN_MANIFEST_SCHEMA_VERSION: &str = "archsig-run-manifest/v0.5.4";
pub const ARCHSIG_ATOM_VIEWER_DATA_SCHEMA_VERSION: &str = "archsig-atom-viewer-data/v0.5.4";
pub const SCHEMA_VERSION_CATALOG_SCHEMA_VERSION: &str = "schema-version-catalog/v0.5.4";
pub const SCHEMA_COMPATIBILITY_POLICY_SCHEMA_VERSION: &str = "schema-compatibility-policy/v0.5.4";
