import ResearchLean.AG.DoctrineFiberProduct.ExactBottomGlobalLiftCoherence

/-!
# Arbitrary semantic cartesian cleavage coherence

A choice of strong cartesian lifts for every semantic base arrow and target
fiber object determines reindexing, natural unit and composition comparisons,
and coherent unit and triple-composition routes.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation
open CrossStageCoherence

set_option maxHeartbeats 3000000

/-! ## Semantic-global cleavage and reindexing -/

/-- The only supplied data: a strong cartesian lift for every semantic arrow and target object. -/
class SemanticCartesianCleavageFamily (U : AtomCarrier.{u}) where
  cleavage : ∀ {source target : ExtractionInstance U}
    (hom : source ⟶ target),
    CoreFiberCartesianCleavage (cartSemanticInputOfHom hom)

/-- The semantic-global construction supplies a cleavage family without further input. -/
noncomputable def canonicalSemanticCartesianCleavageFamily
    (U : AtomCarrier.{u}) : SemanticCartesianCleavageFamily U where
  cleavage := fun hom => exact_bottom_semantic_global_cartesian_cleavage hom

/-- The selected arbitrary cleavage at a semantic base arrow. -/
noncomputable def arbitrary_semantic_cartesian_cleavage
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source target : ExtractionInstance U} (hom : source ⟶ target) :
    CoreFiberCartesianCleavage (cartSemanticInputOfHom hom) :=
  SemanticCartesianCleavageFamily.cleavage hom

/-- The contravariant reindexing functor generated by the semantic-global cleavage. -/
noncomputable def arbitrary_semantic_reindex_functor
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) : CoreFiber target ⥤ CoreFiber source :=
  (arbitrary_semantic_cartesian_cleavage hom).reindexFunctor

/-- The selected lift used by semantic-global reindexing. -/
noncomputable def arbitrary_semantic_selected_lift
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    StrongCartesianLift (cartSemanticInputOfHom hom) targetPackage :=
  (arbitrary_semantic_cartesian_cleavage hom).lift targetPackage

/-- The selected reindexing map satisfies its cartesian factor graph. -/
theorem arbitrary_semantic_reindex_map_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) {first second : CoreFiber target}
    (vertical : first ⟶ second) :
    ((arbitrary_semantic_reindex_functor hom).map vertical).1 ≫
        (arbitrary_semantic_selected_lift hom second).hom =
      (arbitrary_semantic_selected_lift hom first).hom ≫ vertical.1 :=
  (arbitrary_semantic_cartesian_cleavage hom).reindexFunctor_map_fac
    vertical

/-! ## Composition compositor -/

/-- The literal two-step semantic-global cartesian lift. -/
noncomputable def arbitrary_semantic_iterated_lift
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source middle target : ExtractionInstance U}
    (first : source ⟶ middle) (second : middle ⟶ target)
    (targetPackage : CoreFiber target) :
    StrongCartesianLift (cartSemanticInputOfHom (first ≫ second))
      targetPackage where
  domain := (arbitrary_semantic_selected_lift first
    ((arbitrary_semantic_reindex_functor second).obj
      targetPackage)).domain
  hom := (arbitrary_semantic_selected_lift first
      ((arbitrary_semantic_reindex_functor second).obj
        targetPackage)).hom ≫
    (arbitrary_semantic_selected_lift second targetPackage).hom
  isStronglyCartesian := by
    letI : (packageProjection U).IsStronglyCartesian first
        (arbitrary_semantic_selected_lift first
      ((arbitrary_semantic_reindex_functor second).obj
        targetPackage)).hom :=
      (arbitrary_semantic_selected_lift first
        ((arbitrary_semantic_reindex_functor second).obj
          targetPackage)).isStronglyCartesian
    letI : (packageProjection U).IsStronglyCartesian second
        (arbitrary_semantic_selected_lift second targetPackage).hom :=
      (arbitrary_semantic_selected_lift second
        targetPackage).isStronglyCartesian
    exact CategoryTheory.Functor.IsStronglyCartesian.comp
      (packageProjection U)

/-- The cleavage whose lift is the actual two-step composite. -/
noncomputable def arbitrary_semantic_iterated_cleavage
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source middle target : ExtractionInstance U}
    (first : source ⟶ middle) (second : middle ⟶ target) :
    CoreFiberCartesianCleavage
      (cartSemanticInputOfHom (first ≫ second)) where
  lift := arbitrary_semantic_iterated_lift first second

/-- The compositor component from iterated reindexing to direct reindexing. -/
noncomputable def arbitrary_semantic_compositor_app
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source middle target : ExtractionInstance U}
    (first : source ⟶ middle) (second : middle ⟶ target)
    (targetPackage : CoreFiber target) :
    (arbitrary_semantic_reindex_functor second ⋙
      arbitrary_semantic_reindex_functor first).obj targetPackage ≅
      (arbitrary_semantic_reindex_functor
        (first ≫ second)).obj targetPackage := by
  simpa only [arbitrary_semantic_reindex_functor,
    CoreFiberCartesianCleavage.reindexFunctor_obj,
    arbitrary_semantic_iterated_cleavage,
    arbitrary_semantic_iterated_lift,
    arbitrary_semantic_selected_lift] using
    CoreFiberCartesianCleavage.comparisonApp
      (arbitrary_semantic_iterated_cleavage first second)
      (arbitrary_semantic_cartesian_cleavage (first ≫ second))
      targetPackage

/-- The compositor component has the literal two-step factor triangle. -/
theorem arbitrary_semantic_compositor_app_hom_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source middle target : ExtractionInstance U}
    (first : source ⟶ middle) (second : middle ⟶ target)
    (targetPackage : CoreFiber target) :
    (arbitrary_semantic_compositor_app first second
      targetPackage).hom.1 ≫
        (arbitrary_semantic_selected_lift
          (first ≫ second) targetPackage).hom =
      (arbitrary_semantic_iterated_lift first second
        targetPackage).hom := by
  simpa only [arbitrary_semantic_compositor_app,
    arbitrary_semantic_iterated_cleavage,
    arbitrary_semantic_selected_lift] using
    CoreFiberCartesianCleavage.comparisonApp_hom_fac
      (arbitrary_semantic_iterated_cleavage first second)
      (arbitrary_semantic_cartesian_cleavage (first ≫ second))
      targetPackage

/-- The iterated reindexing map has the literal two-step factor graph. -/
theorem arbitrary_semantic_iterated_map_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source middle target : ExtractionInstance U}
    (first : source ⟶ middle) (second : middle ⟶ target)
    {sourcePackage targetPackage : CoreFiber target}
    (vertical : sourcePackage ⟶ targetPackage) :
    ((arbitrary_semantic_reindex_functor second ⋙
      arbitrary_semantic_reindex_functor first).map vertical).1 ≫
        (arbitrary_semantic_iterated_lift first second
          targetPackage).hom =
      (arbitrary_semantic_iterated_lift first second
        sourcePackage).hom ≫ vertical.1 := by
  change
    ((arbitrary_semantic_reindex_functor first).map
      ((arbitrary_semantic_reindex_functor second).map vertical)).1 ≫
      ((arbitrary_semantic_selected_lift first
        ((arbitrary_semantic_reindex_functor second).obj
          targetPackage)).hom ≫
        (arbitrary_semantic_selected_lift second targetPackage).hom) =
    ((arbitrary_semantic_selected_lift first
      ((arbitrary_semantic_reindex_functor second).obj
        sourcePackage)).hom ≫
      (arbitrary_semantic_selected_lift second sourcePackage).hom) ≫
      vertical.1
  calc
    _ = (((arbitrary_semantic_reindex_functor first).map
          ((arbitrary_semantic_reindex_functor second).map
            vertical)).1 ≫
        (arbitrary_semantic_selected_lift first
          ((arbitrary_semantic_reindex_functor second).obj
            targetPackage)).hom) ≫
        (arbitrary_semantic_selected_lift second targetPackage).hom :=
      (Category.assoc _ _ _).symm
    _ = ((arbitrary_semantic_selected_lift first
          ((arbitrary_semantic_reindex_functor second).obj
            sourcePackage)).hom ≫
        ((arbitrary_semantic_reindex_functor second).map
          vertical).1) ≫
        (arbitrary_semantic_selected_lift second targetPackage).hom := by
      rw [arbitrary_semantic_reindex_map_fac]
    _ = (arbitrary_semantic_selected_lift first
          ((arbitrary_semantic_reindex_functor second).obj
            sourcePackage)).hom ≫
        (((arbitrary_semantic_reindex_functor second).map
          vertical).1 ≫
          (arbitrary_semantic_selected_lift second
            targetPackage).hom) := Category.assoc _ _ _
    _ = (arbitrary_semantic_selected_lift first
          ((arbitrary_semantic_reindex_functor second).obj
            sourcePackage)).hom ≫
        ((arbitrary_semantic_selected_lift second
          sourcePackage).hom ≫ vertical.1) := by
      rw [arbitrary_semantic_reindex_map_fac]
    _ = _ := (Category.assoc _ _ _).symm

/-- The compositor components are natural on every vertical map. -/
theorem arbitrary_semantic_compositor_naturality
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source middle target : ExtractionInstance U}
    (first : source ⟶ middle) (second : middle ⟶ target)
    {sourcePackage targetPackage : CoreFiber target}
    (vertical : sourcePackage ⟶ targetPackage) :
    (arbitrary_semantic_reindex_functor second ⋙
        arbitrary_semantic_reindex_functor first).map vertical ≫
      (arbitrary_semantic_compositor_app first second
        targetPackage).hom =
      (arbitrary_semantic_compositor_app first second
        sourcePackage).hom ≫
      (arbitrary_semantic_reindex_functor
        (first ≫ second)).map vertical := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let directTarget := arbitrary_semantic_selected_lift
    (first ≫ second) targetPackage
  letI : (packageProjection U).IsStronglyCartesian (first ≫ second)
      directTarget.hom := directTarget.isStronglyCartesian
  apply CategoryTheory.Functor.IsStronglyCartesian.ext
    (packageProjection U) (first ≫ second) directTarget.hom (𝟙 source)
  change
    (((arbitrary_semantic_reindex_functor second ⋙
      arbitrary_semantic_reindex_functor first).map vertical).1 ≫
      (arbitrary_semantic_compositor_app first second
        targetPackage).hom.1) ≫ directTarget.hom =
    ((arbitrary_semantic_compositor_app first second
      sourcePackage).hom.1 ≫
      ((arbitrary_semantic_reindex_functor
        (first ≫ second)).map vertical).1) ≫ directTarget.hom
  calc
    _ = ((arbitrary_semantic_reindex_functor second ⋙
          arbitrary_semantic_reindex_functor first).map vertical).1 ≫
        ((arbitrary_semantic_compositor_app first second
          targetPackage).hom.1 ≫ directTarget.hom) := Category.assoc _ _ _
    _ = ((arbitrary_semantic_reindex_functor second ⋙
          arbitrary_semantic_reindex_functor first).map vertical).1 ≫
        (arbitrary_semantic_iterated_lift first second
          targetPackage).hom := by
      rw [arbitrary_semantic_compositor_app_hom_fac]
    _ = (arbitrary_semantic_iterated_lift first second
          sourcePackage).hom ≫ vertical.1 :=
      arbitrary_semantic_iterated_map_fac first second vertical
    _ = ((arbitrary_semantic_compositor_app first second
          sourcePackage).hom.1 ≫
        (arbitrary_semantic_selected_lift
          (first ≫ second) sourcePackage).hom) ≫ vertical.1 := by
      rw [arbitrary_semantic_compositor_app_hom_fac]
    _ = (arbitrary_semantic_compositor_app first second
          sourcePackage).hom.1 ≫
        ((arbitrary_semantic_selected_lift
          (first ≫ second) sourcePackage).hom ≫ vertical.1) :=
      Category.assoc _ _ _
    _ = (arbitrary_semantic_compositor_app first second
          sourcePackage).hom.1 ≫
        (((arbitrary_semantic_reindex_functor
          (first ≫ second)).map vertical).1 ≫ directTarget.hom) := by
      rw [arbitrary_semantic_reindex_map_fac]
    _ = _ := (Category.assoc _ _ _).symm

/-- The natural semantic-global contravariant compositor. -/
noncomputable def arbitrary_semantic_compositor
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source middle target : ExtractionInstance U}
    (first : source ⟶ middle) (second : middle ⟶ target) :
    arbitrary_semantic_reindex_functor second ⋙
        arbitrary_semantic_reindex_functor first ≅
      arbitrary_semantic_reindex_functor (first ≫ second) :=
  NatIso.ofComponents
    (arbitrary_semantic_compositor_app first second)
    (fun vertical =>
      arbitrary_semantic_compositor_naturality
        first second vertical)

/-! ## Identity unitor -/

/-- The literal identity cartesian lift. -/
noncomputable def arbitrary_semantic_identity_lift
    {U : AtomCarrier.{u}} (object : ExtractionInstance U)
    (targetPackage : CoreFiber object) :
    StrongCartesianLift (cartSemanticInputOfHom (𝟙 object))
      targetPackage where
  domain := targetPackage.1
  hom := 𝟙 targetPackage.1
  isStronglyCartesian := by
    letI : (packageProjection U).IsHomLift
        (𝟙 object) (𝟙 targetPackage.1) :=
      CategoryTheory.IsHomLift.id targetPackage.2
    exact CategoryTheory.Functor.IsStronglyCartesian.of_isIso
      (packageProjection U) (𝟙 object) (𝟙 targetPackage.1)

/-- The literal identity lift family. -/
noncomputable def arbitrary_semantic_identity_cleavage
    {U : AtomCarrier.{u}} (object : ExtractionInstance U) :
    CoreFiberCartesianCleavage (cartSemanticInputOfHom (𝟙 object)) where
  lift := arbitrary_semantic_identity_lift object

/-- The unitor component from a fiber object to its selected identity reindexing. -/
noncomputable def arbitrary_semantic_unitor_app
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] (object : ExtractionInstance U)
    (targetPackage : CoreFiber object) :
    targetPackage ≅
      (arbitrary_semantic_reindex_functor
        (𝟙 object)).obj targetPackage := by
  simpa only [arbitrary_semantic_reindex_functor,
    CoreFiberCartesianCleavage.reindexFunctor_obj,
    arbitrary_semantic_identity_cleavage,
    arbitrary_semantic_identity_lift,
    arbitrary_semantic_selected_lift] using
    CoreFiberCartesianCleavage.comparisonApp
      (arbitrary_semantic_identity_cleavage object)
      (arbitrary_semantic_cartesian_cleavage (𝟙 object))
      targetPackage

/-- The unitor component followed by the selected identity lift is identity. -/
theorem arbitrary_semantic_unitor_app_hom_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] (object : ExtractionInstance U)
    (targetPackage : CoreFiber object) :
    (arbitrary_semantic_unitor_app object targetPackage).hom.1 ≫
        (arbitrary_semantic_selected_lift
          (𝟙 object) targetPackage).hom = 𝟙 targetPackage.1 := by
  simpa only [arbitrary_semantic_unitor_app,
    arbitrary_semantic_identity_cleavage,
    arbitrary_semantic_identity_lift,
    arbitrary_semantic_selected_lift] using
    CoreFiberCartesianCleavage.comparisonApp_hom_fac
      (arbitrary_semantic_identity_cleavage object)
      (arbitrary_semantic_cartesian_cleavage (𝟙 object))
      targetPackage

/-- The unitor components are natural on vertical maps. -/
theorem arbitrary_semantic_unitor_naturality
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] (object : ExtractionInstance U)
    {sourcePackage targetPackage : CoreFiber object}
    (vertical : sourcePackage ⟶ targetPackage) :
    vertical ≫
        (arbitrary_semantic_unitor_app object targetPackage).hom =
      (arbitrary_semantic_unitor_app object sourcePackage).hom ≫
        (arbitrary_semantic_reindex_functor
          (𝟙 object)).map vertical := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let targetLift := arbitrary_semantic_selected_lift
    (𝟙 object) targetPackage
  letI : (packageProjection U).IsStronglyCartesian (𝟙 object)
      targetLift.hom := targetLift.isStronglyCartesian
  apply CategoryTheory.Functor.IsStronglyCartesian.ext
    (packageProjection U) (𝟙 object) targetLift.hom (𝟙 object)
  change
    (vertical.1 ≫
      (arbitrary_semantic_unitor_app object targetPackage).hom.1) ≫
        targetLift.hom =
    ((arbitrary_semantic_unitor_app object sourcePackage).hom.1 ≫
      ((arbitrary_semantic_reindex_functor
        (𝟙 object)).map vertical).1) ≫ targetLift.hom
  calc
    _ = vertical.1 ≫
        ((arbitrary_semantic_unitor_app object
          targetPackage).hom.1 ≫ targetLift.hom) := Category.assoc _ _ _
    _ = vertical.1 ≫ 𝟙 targetPackage.1 := by
      rw [arbitrary_semantic_unitor_app_hom_fac]
    _ = vertical.1 := Category.comp_id _
    _ = 𝟙 sourcePackage.1 ≫ vertical.1 := (Category.id_comp _).symm
    _ = ((arbitrary_semantic_unitor_app object
          sourcePackage).hom.1 ≫
        (arbitrary_semantic_selected_lift
          (𝟙 object) sourcePackage).hom) ≫ vertical.1 := by
      rw [arbitrary_semantic_unitor_app_hom_fac]
    _ = (arbitrary_semantic_unitor_app object
          sourcePackage).hom.1 ≫
        ((arbitrary_semantic_selected_lift
          (𝟙 object) sourcePackage).hom ≫ vertical.1) :=
      Category.assoc _ _ _
    _ = (arbitrary_semantic_unitor_app object
          sourcePackage).hom.1 ≫
        (((arbitrary_semantic_reindex_functor
          (𝟙 object)).map vertical).1 ≫ targetLift.hom) := by
      rw [arbitrary_semantic_reindex_map_fac]
    _ = _ := (Category.assoc _ _ _).symm

/-- The natural semantic-global identity unitor. -/
noncomputable def arbitrary_semantic_unitor
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] (object : ExtractionInstance U) :
    𝟭 (CoreFiber object) ≅
      arbitrary_semantic_reindex_functor (𝟙 object) :=
  NatIso.ofComponents (arbitrary_semantic_unitor_app object)
    (fun vertical =>
      arbitrary_semantic_unitor_naturality object vertical)

/-! ## Equality transport -/

/-- Object transport induced by equality of semantic base arrows. -/
noncomputable def arbitrary_semantic_reindex_eq_cast
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    {first second : source ⟶ target} (equality : first = second)
    (targetPackage : CoreFiber target) :
    (arbitrary_semantic_reindex_functor first).obj targetPackage ⟶
      (arbitrary_semantic_reindex_functor second).obj targetPackage :=
  eqToHom (congrArg
    (fun hom =>
      (arbitrary_semantic_reindex_functor hom).obj targetPackage)
    equality)

/-- Equality transport carries the second selected lift back to the first. -/
theorem arbitrary_semantic_reindex_eq_cast_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    {first second : source ⟶ target} (equality : first = second)
    (targetPackage : CoreFiber target) :
    (arbitrary_semantic_reindex_eq_cast equality targetPackage).1 ≫
        (arbitrary_semantic_selected_lift second targetPackage).hom =
      (arbitrary_semantic_selected_lift first targetPackage).hom := by
  cases equality
  exact Category.id_comp _

/-! ## Pentagon coherence -/

/-- The literal three-step cartesian lift hom. -/
noncomputable def arbitrary_semantic_triple_lift
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {firstObject secondObject thirdObject fourthObject : ExtractionInstance U}
    (first : firstObject ⟶ secondObject)
    (second : secondObject ⟶ thirdObject)
    (third : thirdObject ⟶ fourthObject)
    (targetPackage : CoreFiber fourthObject) :
    ((arbitrary_semantic_reindex_functor first).obj
      ((arbitrary_semantic_reindex_functor second).obj
        ((arbitrary_semantic_reindex_functor third).obj
          targetPackage))).1 ⟶ targetPackage.1 :=
  (arbitrary_semantic_selected_lift first
      ((arbitrary_semantic_reindex_functor second).obj
        ((arbitrary_semantic_reindex_functor third).obj
          targetPackage))).hom ≫
    ((arbitrary_semantic_selected_lift second
      ((arbitrary_semantic_reindex_functor third).obj
        targetPackage)).hom ≫
      (arbitrary_semantic_selected_lift third targetPackage).hom)

/-- The left-associated compositor route. -/
noncomputable def arbitrary_semantic_pentagon_left_route
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {firstObject secondObject thirdObject fourthObject : ExtractionInstance U}
    (first : firstObject ⟶ secondObject)
    (second : secondObject ⟶ thirdObject)
    (third : thirdObject ⟶ fourthObject)
    (targetPackage : CoreFiber fourthObject) :
    (arbitrary_semantic_reindex_functor first).obj
      ((arbitrary_semantic_reindex_functor second).obj
        ((arbitrary_semantic_reindex_functor third).obj
          targetPackage)) ⟶
      (arbitrary_semantic_reindex_functor
        ((first ≫ second) ≫ third)).obj targetPackage :=
  (arbitrary_semantic_compositor_app first second
      ((arbitrary_semantic_reindex_functor third).obj
        targetPackage)).hom ≫
    (arbitrary_semantic_compositor_app
      (first ≫ second) third targetPackage).hom

/-- The right-associated compositor route, normalized to the left-associated base arrow. -/
noncomputable def arbitrary_semantic_pentagon_right_route
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {firstObject secondObject thirdObject fourthObject : ExtractionInstance U}
    (first : firstObject ⟶ secondObject)
    (second : secondObject ⟶ thirdObject)
    (third : thirdObject ⟶ fourthObject)
    (targetPackage : CoreFiber fourthObject) :
    (arbitrary_semantic_reindex_functor first).obj
      ((arbitrary_semantic_reindex_functor second).obj
        ((arbitrary_semantic_reindex_functor third).obj
          targetPackage)) ⟶
      (arbitrary_semantic_reindex_functor
        ((first ≫ second) ≫ third)).obj targetPackage :=
  (arbitrary_semantic_reindex_functor first).map
      (arbitrary_semantic_compositor_app second third
        targetPackage).hom ≫
    (arbitrary_semantic_compositor_app first (second ≫ third)
      targetPackage).hom ≫
    arbitrary_semantic_reindex_eq_cast
      (Category.assoc first second third).symm targetPackage

/-- The left pentagon route factors the direct lift as the triple lift. -/
theorem arbitrary_semantic_pentagon_left_route_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {firstObject secondObject thirdObject fourthObject : ExtractionInstance U}
    (first : firstObject ⟶ secondObject)
    (second : secondObject ⟶ thirdObject)
    (third : thirdObject ⟶ fourthObject)
    (targetPackage : CoreFiber fourthObject) :
    (arbitrary_semantic_pentagon_left_route first second third
      targetPackage).1 ≫
      (arbitrary_semantic_selected_lift
        ((first ≫ second) ≫ third) targetPackage).hom =
      arbitrary_semantic_triple_lift first second third
        targetPackage := by
  change
    ((arbitrary_semantic_compositor_app first second
        ((arbitrary_semantic_reindex_functor third).obj
          targetPackage)).hom.1 ≫
      (arbitrary_semantic_compositor_app
        (first ≫ second) third targetPackage).hom.1) ≫
      (arbitrary_semantic_selected_lift
        ((first ≫ second) ≫ third) targetPackage).hom = _
  calc
    _ = (arbitrary_semantic_compositor_app first second
          ((arbitrary_semantic_reindex_functor third).obj
            targetPackage)).hom.1 ≫
        ((arbitrary_semantic_compositor_app
          (first ≫ second) third targetPackage).hom.1 ≫
          (arbitrary_semantic_selected_lift
            ((first ≫ second) ≫ third) targetPackage).hom) :=
      Category.assoc _ _ _
    _ = (arbitrary_semantic_compositor_app first second
          ((arbitrary_semantic_reindex_functor third).obj
            targetPackage)).hom.1 ≫
        (arbitrary_semantic_iterated_lift
          (first ≫ second) third targetPackage).hom := by
      rw [arbitrary_semantic_compositor_app_hom_fac]
    _ = ((arbitrary_semantic_compositor_app first second
          ((arbitrary_semantic_reindex_functor third).obj
            targetPackage)).hom.1 ≫
        (arbitrary_semantic_selected_lift (first ≫ second)
          ((arbitrary_semantic_reindex_functor third).obj
            targetPackage)).hom) ≫
        (arbitrary_semantic_selected_lift third
          targetPackage).hom := (Category.assoc _ _ _).symm
    _ = (arbitrary_semantic_iterated_lift first second
          ((arbitrary_semantic_reindex_functor third).obj
            targetPackage)).hom ≫
        (arbitrary_semantic_selected_lift third
          targetPackage).hom := by
      rw [arbitrary_semantic_compositor_app_hom_fac]
    _ = _ := by
      simp only [arbitrary_semantic_iterated_lift,
        arbitrary_semantic_triple_lift, Category.assoc]

/-- The right pentagon route factors the same direct lift as the triple lift. -/
theorem arbitrary_semantic_pentagon_right_route_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {firstObject secondObject thirdObject fourthObject : ExtractionInstance U}
    (first : firstObject ⟶ secondObject)
    (second : secondObject ⟶ thirdObject)
    (third : thirdObject ⟶ fourthObject)
    (targetPackage : CoreFiber fourthObject) :
    (arbitrary_semantic_pentagon_right_route first second third
      targetPackage).1 ≫
      (arbitrary_semantic_selected_lift
        ((first ≫ second) ≫ third) targetPackage).hom =
      arbitrary_semantic_triple_lift first second third
        targetPackage := by
  change
    ((((arbitrary_semantic_reindex_functor first).map
        (arbitrary_semantic_compositor_app second third
          targetPackage).hom).1 ≫
      (arbitrary_semantic_compositor_app first (second ≫ third)
        targetPackage).hom.1) ≫
      (arbitrary_semantic_reindex_eq_cast
        (Category.assoc first second third).symm targetPackage).1) ≫
      (arbitrary_semantic_selected_lift
        ((first ≫ second) ≫ third) targetPackage).hom = _
  calc
    _ = (((arbitrary_semantic_reindex_functor first).map
          (arbitrary_semantic_compositor_app second third
            targetPackage).hom).1 ≫
        (arbitrary_semantic_compositor_app first (second ≫ third)
          targetPackage).hom.1) ≫
        ((arbitrary_semantic_reindex_eq_cast
          (Category.assoc first second third).symm targetPackage).1 ≫
          (arbitrary_semantic_selected_lift
            ((first ≫ second) ≫ third) targetPackage).hom) :=
      Category.assoc _ _ _
    _ = (((arbitrary_semantic_reindex_functor first).map
          (arbitrary_semantic_compositor_app second third
            targetPackage).hom).1 ≫
        (arbitrary_semantic_compositor_app first (second ≫ third)
          targetPackage).hom.1) ≫
        (arbitrary_semantic_selected_lift
          (first ≫ (second ≫ third)) targetPackage).hom := by
      rw [arbitrary_semantic_reindex_eq_cast_fac]
    _ = ((arbitrary_semantic_reindex_functor first).map
          (arbitrary_semantic_compositor_app second third
            targetPackage).hom).1 ≫
        ((arbitrary_semantic_compositor_app first (second ≫ third)
          targetPackage).hom.1 ≫
          (arbitrary_semantic_selected_lift
            (first ≫ (second ≫ third)) targetPackage).hom) :=
      Category.assoc _ _ _
    _ = ((arbitrary_semantic_reindex_functor first).map
          (arbitrary_semantic_compositor_app second third
            targetPackage).hom).1 ≫
        (arbitrary_semantic_iterated_lift first (second ≫ third)
          targetPackage).hom := by
      rw [arbitrary_semantic_compositor_app_hom_fac]
    _ = (((arbitrary_semantic_reindex_functor first).map
          (arbitrary_semantic_compositor_app second third
            targetPackage).hom).1 ≫
        (arbitrary_semantic_selected_lift first
          ((arbitrary_semantic_reindex_functor
            (second ≫ third)).obj targetPackage)).hom) ≫
        (arbitrary_semantic_selected_lift (second ≫ third)
          targetPackage).hom := (Category.assoc _ _ _).symm
    _ = ((arbitrary_semantic_selected_lift first
          ((arbitrary_semantic_reindex_functor third ⋙
            arbitrary_semantic_reindex_functor second).obj
            targetPackage)).hom ≫
        (arbitrary_semantic_compositor_app second third
          targetPackage).hom.1) ≫
        (arbitrary_semantic_selected_lift (second ≫ third)
          targetPackage).hom := by
      rw [arbitrary_semantic_reindex_map_fac]
    _ = (arbitrary_semantic_selected_lift first
          ((arbitrary_semantic_reindex_functor second).obj
            ((arbitrary_semantic_reindex_functor third).obj
              targetPackage))).hom ≫
        ((arbitrary_semantic_compositor_app second third
          targetPackage).hom.1 ≫
          (arbitrary_semantic_selected_lift (second ≫ third)
            targetPackage).hom) := Category.assoc _ _ _
    _ = (arbitrary_semantic_selected_lift first
          ((arbitrary_semantic_reindex_functor second).obj
            ((arbitrary_semantic_reindex_functor third).obj
              targetPackage))).hom ≫
        (arbitrary_semantic_iterated_lift second third
          targetPackage).hom := by
      rw [arbitrary_semantic_compositor_app_hom_fac]
    _ = _ := by
      simp only [arbitrary_semantic_iterated_lift,
        arbitrary_semantic_triple_lift]

/-- Pentagon coherence: the two actual compositor routes agree componentwise. -/
theorem arbitrary_semantic_pentagon
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {firstObject secondObject thirdObject fourthObject : ExtractionInstance U}
    (first : firstObject ⟶ secondObject)
    (second : secondObject ⟶ thirdObject)
    (third : thirdObject ⟶ fourthObject)
    (targetPackage : CoreFiber fourthObject) :
    arbitrary_semantic_pentagon_left_route first second third
        targetPackage =
      arbitrary_semantic_pentagon_right_route first second third
        targetPackage := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let directLift := arbitrary_semantic_selected_lift
    ((first ≫ second) ≫ third) targetPackage
  letI : (packageProjection U).IsStronglyCartesian
      ((first ≫ second) ≫ third) directLift.hom :=
    directLift.isStronglyCartesian
  apply CategoryTheory.Functor.IsStronglyCartesian.ext
    (packageProjection U) ((first ≫ second) ≫ third)
    directLift.hom (𝟙 firstObject)
  change
    (arbitrary_semantic_pentagon_left_route first second third
      targetPackage).1 ≫ directLift.hom =
    (arbitrary_semantic_pentagon_right_route first second third
      targetPackage).1 ≫ directLift.hom
  rw [arbitrary_semantic_pentagon_left_route_fac,
    arbitrary_semantic_pentagon_right_route_fac]

/-! ## Unit triangle coherence -/

/-- The source-identity route through unitor and compositor. -/
noncomputable def arbitrary_semantic_left_unit_route
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    (arbitrary_semantic_reindex_functor hom).obj targetPackage ⟶
      (arbitrary_semantic_reindex_functor
        (𝟙 source ≫ hom)).obj targetPackage :=
  (arbitrary_semantic_unitor_app source
      ((arbitrary_semantic_reindex_functor hom).obj
        targetPackage)).hom ≫
    (arbitrary_semantic_compositor_app
      (𝟙 source) hom targetPackage).hom

/-- The source-unit equality cast. -/
noncomputable def arbitrary_semantic_left_unit_cast
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    (arbitrary_semantic_reindex_functor hom).obj targetPackage ⟶
      (arbitrary_semantic_reindex_functor
        (𝟙 source ≫ hom)).obj targetPackage :=
  arbitrary_semantic_reindex_eq_cast
    (Category.id_comp hom).symm targetPackage

/-- The target-identity route through mapped unitor and compositor. -/
noncomputable def arbitrary_semantic_right_unit_route
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    (arbitrary_semantic_reindex_functor hom).obj targetPackage ⟶
      (arbitrary_semantic_reindex_functor
        (hom ≫ 𝟙 target)).obj targetPackage :=
  (arbitrary_semantic_reindex_functor hom).map
      (arbitrary_semantic_unitor_app target targetPackage).hom ≫
    (arbitrary_semantic_compositor_app
      hom (𝟙 target) targetPackage).hom

/-- The target-unit equality cast. -/
noncomputable def arbitrary_semantic_right_unit_cast
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    (arbitrary_semantic_reindex_functor hom).obj targetPackage ⟶
      (arbitrary_semantic_reindex_functor
        (hom ≫ 𝟙 target)).obj targetPackage :=
  arbitrary_semantic_reindex_eq_cast
    (Category.comp_id hom).symm targetPackage

/-- The source-unit route factors the composite lift as the original lift. -/
theorem arbitrary_semantic_left_unit_route_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    (arbitrary_semantic_left_unit_route hom targetPackage).1 ≫
        (arbitrary_semantic_selected_lift
          (𝟙 source ≫ hom) targetPackage).hom =
      (arbitrary_semantic_selected_lift hom targetPackage).hom := by
  change
    ((arbitrary_semantic_unitor_app source
      ((arbitrary_semantic_reindex_functor hom).obj
        targetPackage)).hom.1 ≫
      (arbitrary_semantic_compositor_app
        (𝟙 source) hom targetPackage).hom.1) ≫
      (arbitrary_semantic_selected_lift
        (𝟙 source ≫ hom) targetPackage).hom = _
  calc
    _ = (arbitrary_semantic_unitor_app source
          ((arbitrary_semantic_reindex_functor hom).obj
            targetPackage)).hom.1 ≫
        ((arbitrary_semantic_compositor_app
          (𝟙 source) hom targetPackage).hom.1 ≫
          (arbitrary_semantic_selected_lift
            (𝟙 source ≫ hom) targetPackage).hom) :=
      Category.assoc _ _ _
    _ = (arbitrary_semantic_unitor_app source
          ((arbitrary_semantic_reindex_functor hom).obj
            targetPackage)).hom.1 ≫
        (arbitrary_semantic_iterated_lift
          (𝟙 source) hom targetPackage).hom := by
      rw [arbitrary_semantic_compositor_app_hom_fac]
    _ = ((arbitrary_semantic_unitor_app source
          ((arbitrary_semantic_reindex_functor hom).obj
            targetPackage)).hom.1 ≫
        (arbitrary_semantic_selected_lift (𝟙 source)
          ((arbitrary_semantic_reindex_functor hom).obj
            targetPackage)).hom) ≫
        (arbitrary_semantic_selected_lift hom targetPackage).hom :=
      (Category.assoc _ _ _).symm
    _ = (arbitrary_semantic_selected_lift hom
          targetPackage).hom := by
      rw [arbitrary_semantic_unitor_app_hom_fac]
      exact Category.id_comp _

/-- The target-unit route factors the composite lift as the original lift. -/
theorem arbitrary_semantic_right_unit_route_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    (arbitrary_semantic_right_unit_route hom targetPackage).1 ≫
        (arbitrary_semantic_selected_lift
          (hom ≫ 𝟙 target) targetPackage).hom =
      (arbitrary_semantic_selected_lift hom targetPackage).hom := by
  change
    (((arbitrary_semantic_reindex_functor hom).map
      (arbitrary_semantic_unitor_app target
        targetPackage).hom).1 ≫
      (arbitrary_semantic_compositor_app
        hom (𝟙 target) targetPackage).hom.1) ≫
      (arbitrary_semantic_selected_lift
        (hom ≫ 𝟙 target) targetPackage).hom = _
  calc
    _ = ((arbitrary_semantic_reindex_functor hom).map
          (arbitrary_semantic_unitor_app target
            targetPackage).hom).1 ≫
        ((arbitrary_semantic_compositor_app
          hom (𝟙 target) targetPackage).hom.1 ≫
          (arbitrary_semantic_selected_lift
            (hom ≫ 𝟙 target) targetPackage).hom) :=
      Category.assoc _ _ _
    _ = ((arbitrary_semantic_reindex_functor hom).map
          (arbitrary_semantic_unitor_app target
            targetPackage).hom).1 ≫
        (arbitrary_semantic_iterated_lift
          hom (𝟙 target) targetPackage).hom := by
      rw [arbitrary_semantic_compositor_app_hom_fac]
    _ = (((arbitrary_semantic_reindex_functor hom).map
          (arbitrary_semantic_unitor_app target
            targetPackage).hom).1 ≫
        (arbitrary_semantic_selected_lift hom
          ((arbitrary_semantic_reindex_functor
            (𝟙 target)).obj targetPackage)).hom) ≫
        (arbitrary_semantic_selected_lift
          (𝟙 target) targetPackage).hom := (Category.assoc _ _ _).symm
    _ = ((arbitrary_semantic_selected_lift hom
          targetPackage).hom ≫
        (arbitrary_semantic_unitor_app target
          targetPackage).hom.1) ≫
        (arbitrary_semantic_selected_lift
          (𝟙 target) targetPackage).hom := by
      rw [arbitrary_semantic_reindex_map_fac]
    _ = (arbitrary_semantic_selected_lift hom
          targetPackage).hom ≫
        ((arbitrary_semantic_unitor_app target
          targetPackage).hom.1 ≫
          (arbitrary_semantic_selected_lift
            (𝟙 target) targetPackage).hom) := Category.assoc _ _ _
    _ = (arbitrary_semantic_selected_lift hom
          targetPackage).hom ≫ 𝟙 targetPackage.1 := by
      rw [arbitrary_semantic_unitor_app_hom_fac]
    _ = _ := Category.comp_id _

/-- Source-unit triangle coherence. -/
theorem arbitrary_semantic_left_unit_triangle
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    arbitrary_semantic_left_unit_route hom targetPackage =
      arbitrary_semantic_left_unit_cast hom targetPackage := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let directLift := arbitrary_semantic_selected_lift
    (𝟙 source ≫ hom) targetPackage
  letI : (packageProjection U).IsStronglyCartesian (𝟙 source ≫ hom)
      directLift.hom := directLift.isStronglyCartesian
  apply CategoryTheory.Functor.IsStronglyCartesian.ext
    (packageProjection U) (𝟙 source ≫ hom)
    directLift.hom (𝟙 source)
  change
    (arbitrary_semantic_left_unit_route hom targetPackage).1 ≫
      directLift.hom =
    (arbitrary_semantic_left_unit_cast hom targetPackage).1 ≫
      directLift.hom
  rw [arbitrary_semantic_left_unit_route_fac]
  exact (arbitrary_semantic_reindex_eq_cast_fac
    (Category.id_comp hom).symm targetPackage).symm

/-- Target-unit triangle coherence. -/
theorem arbitrary_semantic_right_unit_triangle
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    arbitrary_semantic_right_unit_route hom targetPackage =
      arbitrary_semantic_right_unit_cast hom targetPackage := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let directLift := arbitrary_semantic_selected_lift
    (hom ≫ 𝟙 target) targetPackage
  letI : (packageProjection U).IsStronglyCartesian (hom ≫ 𝟙 target)
      directLift.hom := directLift.isStronglyCartesian
  apply CategoryTheory.Functor.IsStronglyCartesian.ext
    (packageProjection U) (hom ≫ 𝟙 target)
    directLift.hom (𝟙 source)
  change
    (arbitrary_semantic_right_unit_route hom targetPackage).1 ≫
      directLift.hom =
    (arbitrary_semantic_right_unit_cast hom targetPackage).1 ≫
      directLift.hom
  rw [arbitrary_semantic_right_unit_route_fac]
  exact (arbitrary_semantic_reindex_eq_cast_fac
    (Category.comp_id hom).symm targetPackage).symm

/-- The two semantic-global unit triangles, packaged at one arbitrary arrow. -/
theorem arbitrary_semantic_triangle
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U] {source target : ExtractionInstance U}
    (hom : source ⟶ target) (targetPackage : CoreFiber target) :
    arbitrary_semantic_left_unit_route hom targetPackage =
        arbitrary_semantic_left_unit_cast hom targetPackage ∧
      arbitrary_semantic_right_unit_route hom targetPackage =
        arbitrary_semantic_right_unit_cast hom targetPackage :=
  ⟨arbitrary_semantic_left_unit_triangle hom targetPackage,
    arbitrary_semantic_right_unit_triangle hom targetPackage⟩

/-! ## Connection with the previously selected semantic-global API -/

/-- The arbitrary reindexing is naturally isomorphic to the existing selected reindexing. -/
noncomputable def arbitrary_semantic_to_canonical
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source target : ExtractionInstance U} (hom : source ⟶ target) :
    arbitrary_semantic_reindex_functor hom ≅
      exact_bottom_semantic_global_reindex_functor hom :=
  CoreFiberCartesianCleavage.comparison
    (arbitrary_semantic_cartesian_cleavage hom)
    (exact_bottom_semantic_global_cartesian_cleavage hom)

/-- The comparison maps the arbitrary lift to the previously selected lift. -/
theorem arbitrary_semantic_to_canonical_app_fac
    {U : AtomCarrier.{u}} [SemanticCartesianCleavageFamily U]
    {source target : ExtractionInstance U} (hom : source ⟶ target)
    (targetPackage : CoreFiber target) :
    ((arbitrary_semantic_to_canonical hom).hom.app targetPackage).1 ≫
        (exact_bottom_semantic_global_selected_lift hom targetPackage).hom =
      (arbitrary_semantic_selected_lift hom targetPackage).hom :=
  CoreFiberCartesianCleavage.comparisonApp_hom_fac
    (arbitrary_semantic_cartesian_cleavage hom)
    (exact_bottom_semantic_global_cartesian_cleavage hom)
    targetPackage

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
