import ResearchLean.AG.DoctrineFiberProduct.BCDiagnosticFiberwiseTransport

/-!
# Total-category transport of diagnostic data

This module removes the identity-base restriction from the same-combinatorial
transport engine.  A structural action on the package total category records
two laws: it preserves strongly cocartesian morphisms, and equal source base
morphisms have equal image base morphisms.  These laws generate every target
edge qualification, every target two-cell base equation, and the target
comparator table for arbitrary G-106 admissible source data.

No target package, lift, qualification, base equation, or comparator is an
input.  Constructing the particular total-category action generated by a
semantic Beck--Chevalley square remains a separate obligation.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation CrossStageCoherence TransportCoherence

/-- Structural action on the package total category sufficient to transport a
G-106 diagnostic interpretation.  The laws concern the action itself rather
than any chosen target diagnostic datum. -/
structure DiagnosticPackageTotalAction (U : AtomCarrier.{u}) where
  /-- Functorial action on packages and total morphisms. -/
  total : AATCorePackage U ⥤ AATCorePackage U
  /-- The action preserves the local G-106 qualification. -/
  map_stronglyCocartesian :
    ∀ {P Q : AATCorePackage U} (hom : PackageTotalHom P Q),
      (packageProjection U).IsStronglyCocartesian hom.base hom →
        (packageProjection U).IsStronglyCocartesian
          (total.map hom).base (total.map hom)
  /-- Image base morphisms depend only on the source base morphism. -/
  map_base_eq_of_base_eq :
    ∀ {P Q : AATCorePackage U} (left right : PackageTotalHom P Q),
      left.base = right.base →
        (total.map left).base = (total.map right).base

namespace DiagnosticPackageTotalAction

/-- Map a package-fiber automorphism through the total action.  Its target
fiber equation is derived by comparing its source base with the identity. -/
noncomputable def mapPackageFiberAut
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {P : AATCorePackage U} (automorphism : PackageFiberAut P) :
    PackageFiberAut (action.total.obj P) := by
  refine ⟨action.total.mapIso automorphism.1, ?_⟩
  have baseEq := action.map_base_eq_of_base_eq
    (PackageFiberAut.hom automorphism) (𝟙 P)
    (by simpa using PackageFiberAut.hom_base_eq automorphism)
  change (action.total.map (PackageFiberAut.hom automorphism)).base =
    𝟙 (packagePoint (action.total.obj P))
  calc
    _ = (action.total.map (𝟙 P)).base := baseEq
    _ = (𝟙 (action.total.obj P) :
        PackageTotalHom (action.total.obj P) (action.total.obj P)).base := by
      rw [action.total.map_id]
    _ = _ := rfl

/-- The total action sends the identity endpoint automorphism to identity. -/
@[simp]
theorem mapPackageFiberAut_one
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    (P : AATCorePackage U) :
    action.mapPackageFiberAut (1 : PackageFiberAut P) = 1 := by
  apply Subtype.ext
  apply Iso.ext
  exact action.total.map_id P

/-- The total action preserves endpoint-automorphism multiplication. -/
@[simp]
theorem mapPackageFiberAut_mul
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {P : AATCorePackage U} (left right : PackageFiberAut P) :
    action.mapPackageFiberAut (left * right) =
      action.mapPackageFiberAut left * action.mapPackageFiberAut right := by
  apply Subtype.ext
  apply Iso.ext
  change action.total.map (right.1.hom ≫ left.1.hom) =
    action.total.map right.1.hom ≫ action.total.map left.1.hom
  exact action.total.map_comp right.1.hom left.1.hom

/-- Packages obtained by applying the total action at every fixed vertex. -/
def transportedPackage
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U) (vertex : G.Vertex) :
    AATCorePackage U :=
  action.total.obj (data.lift.package vertex)

/-- Edge lifts obtained by functorially mapping the source edge lifts. -/
def transportedEdgeLift
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U)
    {i j : G.Vertex} (edge : G.Edge i j) :
    PackageTotalHom (action.transportedPackage data i)
      (action.transportedPackage data j) :=
  action.total.map (data.lift.edgeLift edge)

/-- Target edge qualification is derived from the action law and the source
G-106 qualification. -/
theorem transportedEdgeLift_isStronglyCocartesian
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U)
    {i j : G.Vertex} (edge : G.Edge i j) :
    (packageProjection U).IsStronglyCocartesian
      (action.transportedEdgeLift data edge).base
      (action.transportedEdgeLift data edge) :=
  action.map_stronglyCocartesian (data.lift.edgeLift edge)
    (data.lift.edgeStrong edge)

/-- The generated target edge-lift interpretation on the unchanged finite
presentation. -/
noncomputable def transportedLiftData
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U) : AdmissibleLiftData G U where
  package := action.transportedPackage data
  edgeLift := action.transportedEdgeLift data
  edgeStrong := action.transportedEdgeLift_isStronglyCocartesian data

/-- Target path evaluation is the functorial image of source path evaluation. -/
theorem transportedPathLift_eq_map
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U)
    {i j : G.Vertex} (path : G.Path i j) :
    (action.transportedLiftData data).pathLift path =
      action.total.map (data.lift.pathLift path) := by
  induction path with
  | nil vertex =>
      exact (action.total.map_id (data.lift.package vertex)).symm
  | cons edge tail inductionHypothesis =>
      simp only [AdmissibleLiftData.pathLift]
      rw [inductionHypothesis]
      exact (action.total.map_comp
        (data.lift.edgeLift edge) (data.lift.pathLift tail)).symm

/-- Every target two-cell base equation is derived by applying the structural
base-congruence law to the source G-106 equation. -/
theorem transportedTwoCellBase
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U) (cell : G.TwoCell) :
    ((action.transportedLiftData data).pathLift (G.twoLeft cell)).base =
      ((action.transportedLiftData data).pathLift (G.twoRight cell)).base := by
  rw [action.transportedPathLift_eq_map,
    action.transportedPathLift_eq_map]
  exact action.map_base_eq_of_base_eq
    (data.lift.pathLift (G.twoLeft cell))
    (data.lift.pathLift (G.twoRight cell)) (data.twoCellBase cell)

/-- Generate arbitrary-source G-106 target data without accepting any target
field. -/
noncomputable def transportedData
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U) : AdmissibleTransportData G U where
  lift := action.transportedLiftData data
  twoCellBase := action.transportedTwoCellBase data
  comparator cell := action.mapPackageFiberAut (data.comparator cell)

/-- The arbitrary-source target comparator satisfies the d3 generation
equation by construction. -/
@[simp]
theorem transportedData_comparator
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U) (cell : G.TwoCell) :
    (action.transportedData data).comparator cell =
      action.mapPackageFiberAut (data.comparator cell) := rfl

/-- The arbitrary-source target edge qualification is the generated action
law, exposed without unfolding the constructor. -/
theorem transportedData_edgeStrong
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U)
    {i j : G.Vertex} (edge : G.Edge i j) :
    (packageProjection U).IsStronglyCocartesian
      ((action.transportedData data).lift.edgeLift edge).base
      ((action.transportedData data).lift.edgeLift edge) :=
  action.transportedEdgeLift_isStronglyCocartesian data edge

/-- The arbitrary-source target two-cell equation is generated from the source
equation and the action's base congruence law. -/
theorem transportedData_twoCellBase
    {U : AtomCarrier.{u}} (action : DiagnosticPackageTotalAction U)
    {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U) (cell : G.TwoCell) :
    ((action.transportedData data).lift.pathLift (G.twoLeft cell)).base =
      ((action.transportedData data).lift.pathLift (G.twoRight cell)).base :=
  action.transportedTwoCellBase data cell

/-- Identity total action, witnessing that the structural action contract is
inhabited without target diagnostic fields. -/
noncomputable def identity (U : AtomCarrier.{u}) :
    DiagnosticPackageTotalAction U where
  total := 𝟭 _
  map_stronglyCocartesian hom qualification := by
    simpa using qualification
  map_base_eq_of_base_eq left right equality := by
    simpa using equality

end DiagnosticPackageTotalAction

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
