import ResearchLean.AG.DoctrineFiberProduct.BCDiagnosticAxisFold

/-!
# Beck--Chevalley comparison generated by a diagnostic axis fold

The G-106 initial raw defect is inspected for an object-fixing moved signature
axis.  Such an axis generates a noninvertible fold; absence of such an axis
generates identity.  The resulting southwest vertical morphism is passed
through selected reindexing and the cocartesian universal property before the
Beck--Chevalley component is assembled.

No comparison, endomorphism, fold witness, or expected equality is accepted
from a caller.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation CrossStageCoherence TransportCoherence

set_option maxHeartbeats 3000000

/-- The total southwest fold generated by the initial raw defect. -/
noncomputable def authoredDiagnosticAxisFoldTotal
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    input.context.supportPackage cell ⟶ input.context.supportPackage cell :=
  PackageFiberAut.generatedAxisFoldTotal
    (initialRawDefectCochain input.toTransportData cell)

/-- The generated fold lies over the southwest identity. -/
theorem authoredDiagnosticAxisFoldTotal_isHomLift
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    (packageProjection U).IsHomLift
      (𝟙 input.context.square.semantic.square.southwest)
      (authoredDiagnosticAxisFoldTotal input cell) := by
  apply CategoryTheory.IsHomLift.of_commsq
    (packageProjection U)
    (𝟙 input.context.square.semantic.square.southwest)
    (authoredDiagnosticAxisFoldTotal input cell)
    (input.context.endpoint_eq cell)
    (input.context.endpoint_eq cell)
  rw [packageProjection_map, authoredDiagnosticAxisFoldTotal,
    PackageFiberAut.generatedAxisFoldTotal_base]
  rw [Category.comp_id]
  exact Category.id_comp _

/-- The generated fold as a southwest-fiber morphism. -/
noncomputable def authoredDiagnosticAxisFoldComponent
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    input.context.supportObject cell ⟶ input.context.supportObject cell :=
  ⟨authoredDiagnosticAxisFoldTotal input cell,
    authoredDiagnosticAxisFoldTotal_isHomLift input cell⟩

/-- The generated fold retagged at the decoded southwest object. -/
noncomputable def authoredDiagnosticAxisFoldDecodedComponent
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    authoredSupportDecodedObject input.context (Discrete.mk cell) ⟶
      authoredSupportDecodedObject input.context (Discrete.mk cell) := by
  rcases input with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  exact authoredDiagnosticAxisFoldComponent
    ⟨⟨⟨toSemanticBC presentation, presentation, rfl⟩, lift, endpoint_eq⟩,
      twoCellBase, authored⟩ cell

/--
The underlying package morphism of the decoded component is the fold generated
from the initial raw defect.  `HEq` records the retagging across
`realization_eq`; concrete realized inputs can recover ordinary equality.
-/
theorem authoredDiagnosticAxisFoldDecodedComponent_val_heq
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    HEq (authoredDiagnosticAxisFoldDecodedComponent input cell).1
      (PackageFiberAut.generatedAxisFoldTotal
        (initialRawDefectCochain input.toTransportData cell)) := by
  rcases input with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  rfl

/--
Generate the left factor from the reindexed diagnostic fold by the package
cocartesian universal property.
-/
noncomputable def authoredDiagnosticAxisFoldLeftFactor
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    (coreFiberTransportFunctor
        (typedPresentationToSemantic
          (bcLeftPresentation input.context.square.presentation))).obj
        ((selectedCoreFiberReindexFunctor
          (typedRealizableHom
            (bcLeftPresentation input.context.square.presentation))).obj
          (authoredSupportDecodedObject input.context (Discrete.mk cell))) ⟶
      authoredSupportDecodedObject input.context (Discrete.mk cell) := by
  rcases input with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  let normalizedContext : AuthoredSupportContext U :=
    ⟨⟨toSemanticBC presentation, presentation, rfl⟩, lift, endpoint_eq⟩
  let normalizedInput : AuthoredBCDatumSquare U :=
    ⟨normalizedContext, twoCellBase, authored⟩
  let leftInput := typedRealizableHom (bcLeftPresentation presentation)
  let support := normalizedContext.supportObject cell
  exact reindexToCoreTransportHom leftInput
    ((selectedCoreFiberReindexFunctor leftInput).obj support)
    support
    ((selectedCoreFiberReindexFunctor leftInput).map
      (authoredDiagnosticAxisFoldComponent normalizedInput cell))

/-- The universal equation defining the generated fold factor. -/
theorem authoredDiagnosticAxisFoldLeftFactor_fac
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    coreFiberLift
        (typedPresentationToSemantic
          (bcLeftPresentation input.context.square.presentation))
        ((selectedCoreFiberReindexFunctor
          (typedRealizableHom
            (bcLeftPresentation input.context.square.presentation))).obj
          (authoredSupportDecodedObject input.context (Discrete.mk cell))) ≫
      (authoredDiagnosticAxisFoldLeftFactor input cell).1 =
        (((selectedCoreFiberReindexFunctor
          (typedRealizableHom
            (bcLeftPresentation input.context.square.presentation))).map
          (authoredDiagnosticAxisFoldDecodedComponent input cell)).1 ≫
        (selectedCoreFiberCartesianLift
          (typedRealizableHom
            (bcLeftPresentation input.context.square.presentation))
          (authoredSupportDecodedObject input.context
            (Discrete.mk cell))).hom) := by
  rcases input with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  exact reindexToCoreTransportHom_fac
    (typedRealizableHom (bcLeftPresentation presentation))
    ((selectedCoreFiberReindexFunctor
      (typedRealizableHom (bcLeftPresentation presentation))).obj
      (AuthoredSupportContext.supportObject
        ⟨⟨toSemanticBC presentation, presentation, rfl⟩, lift, endpoint_eq⟩ cell))
    (AuthoredSupportContext.supportObject
      ⟨⟨toSemanticBC presentation, presentation, rfl⟩, lift, endpoint_eq⟩ cell)
    ((selectedCoreFiberReindexFunctor
      (typedRealizableHom (bcLeftPresentation presentation))).map
      (authoredDiagnosticAxisFoldComponent
        ⟨⟨⟨toSemanticBC presentation, presentation, rfl⟩, lift, endpoint_eq⟩,
          twoCellBase, authored⟩ cell))

/-- Identity raw defect makes the decoded generated fold the identity. -/
theorem authoredDiagnosticAxisFoldDecodedComponent_eq_id
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (hdefect : initialRawDefectCochain input.toTransportData =
      identityDefectCochain input.toTransportData)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    authoredDiagnosticAxisFoldDecodedComponent input cell =
      𝟙 (authoredSupportDecodedObject input.context (Discrete.mk cell)) := by
  rcases input with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  apply CategoryTheory.Functor.Fiber.hom_ext
  change PackageFiberAut.generatedAxisFoldTotal
      (initialRawDefectCochain
        (AuthoredBCDatumSquare.toTransportData
          ⟨⟨⟨toSemanticBC presentation, presentation, rfl⟩,
            lift, endpoint_eq⟩, twoCellBase, authored⟩) cell) =
    PackageTotalHom.id
      (AuthoredSupportContext.supportPackage
        ⟨⟨toSemanticBC presentation, presentation, rfl⟩,
          lift, endpoint_eq⟩ cell)
  rw [congrFun hdefect cell]
  exact PackageFiberAut.generatedAxisFoldTotal_one

/-- Identity raw defect specializes the generated factor to the counit. -/
theorem authoredDiagnosticAxisFoldLeftFactor_eq_counit
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (hdefect : initialRawDefectCochain input.toTransportData =
      identityDefectCochain input.toTransportData)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    authoredDiagnosticAxisFoldLeftFactor input cell =
      (bcLeftAdjunction input.context.square.presentation).counit.app
        (authoredSupportDecodedObject input.context (Discrete.mk cell)) := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let leftInput := typedRealizableHom
    (bcLeftPresentation input.context.square.presentation)
  let support := authoredSupportDecodedObject input.context (Discrete.mk cell)
  let reindexed := (selectedCoreFiberReindexFunctor leftInput).obj support
  letI : (packageProjection U).IsStronglyCocartesian
      leftInput.semantic.hom (coreFiberLift leftInput.semantic.hom reindexed) :=
    coreFiberLift_isStronglyCocartesian leftInput.semantic.hom reindexed
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) leftInput.semantic.hom
    (coreFiberLift leftInput.semantic.hom reindexed)
    (𝟙 leftInput.semantic.target)
  dsimp only [leftInput, support, reindexed]
  change coreFiberLift
      (typedPresentationToSemantic
        (bcLeftPresentation input.context.square.presentation))
      ((selectedCoreFiberReindexFunctor
        (typedRealizableHom
          (bcLeftPresentation input.context.square.presentation))).obj
        (authoredSupportDecodedObject input.context (Discrete.mk cell))) ≫
      (authoredDiagnosticAxisFoldLeftFactor input cell).1 =
    coreFiberLift
      (typedPresentationToSemantic
        (bcLeftPresentation input.context.square.presentation))
      ((selectedCoreFiberReindexFunctor
        (typedRealizableHom
          (bcLeftPresentation input.context.square.presentation))).obj
        (authoredSupportDecodedObject input.context (Discrete.mk cell))) ≫
      ((bcLeftAdjunction input.context.square.presentation).counit.app
        (authoredSupportDecodedObject input.context (Discrete.mk cell))).1
  rw [authoredDiagnosticAxisFoldLeftFactor_fac]
  rw [show (bcLeftAdjunction input.context.square.presentation).counit =
      coreTransportReindexCounit leftInput by rfl]
  rw [authoredDiagnosticAxisFoldDecodedComponent_eq_id input hdefect cell]
  rw [CategoryTheory.Functor.map_id]
  simpa only [Category.id_comp] using
    (coreTransportReindexCounit_app_fac leftInput support).symm

/--
Universal uniqueness identifies the generated factor as the counit followed by
the independently generated diagnostic fold.
-/
theorem authoredDiagnosticAxisFoldLeftFactor_eq_counit_comp_fold
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.square.semantic.diagnostic.TwoCell) :
    authoredDiagnosticAxisFoldLeftFactor input cell =
      (bcLeftAdjunction input.context.square.presentation).counit.app
          (authoredSupportDecodedObject input.context (Discrete.mk cell)) ≫
        authoredDiagnosticAxisFoldDecodedComponent input cell := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let leftInput := typedRealizableHom
    (bcLeftPresentation input.context.square.presentation)
  let support := authoredSupportDecodedObject input.context (Discrete.mk cell)
  let reindexed := (selectedCoreFiberReindexFunctor leftInput).obj support
  letI : (packageProjection U).IsStronglyCocartesian
      leftInput.semantic.hom (coreFiberLift leftInput.semantic.hom reindexed) :=
    coreFiberLift_isStronglyCocartesian leftInput.semantic.hom reindexed
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (packageProjection U) leftInput.semantic.hom
    (coreFiberLift leftInput.semantic.hom reindexed)
    (𝟙 leftInput.semantic.target)
  dsimp only [leftInput, support, reindexed]
  change coreFiberLift
      (typedPresentationToSemantic
        (bcLeftPresentation input.context.square.presentation))
      ((selectedCoreFiberReindexFunctor
        (typedRealizableHom
          (bcLeftPresentation input.context.square.presentation))).obj
        (authoredSupportDecodedObject input.context (Discrete.mk cell))) ≫
      (authoredDiagnosticAxisFoldLeftFactor input cell).1 =
    coreFiberLift
      (typedPresentationToSemantic
        (bcLeftPresentation input.context.square.presentation))
      ((selectedCoreFiberReindexFunctor
        (typedRealizableHom
          (bcLeftPresentation input.context.square.presentation))).obj
        (authoredSupportDecodedObject input.context (Discrete.mk cell))) ≫
      (((bcLeftAdjunction input.context.square.presentation).counit.app
        (authoredSupportDecodedObject input.context (Discrete.mk cell))).1 ≫
        (authoredDiagnosticAxisFoldDecodedComponent input cell).1)
  rw [authoredDiagnosticAxisFoldLeftFactor_fac]
  rw [← Category.assoc]
  rw [show (bcLeftAdjunction input.context.square.presentation).counit =
      coreTransportReindexCounit leftInput by rfl]
  have hcounit :
      coreFiberLift
          (typedPresentationToSemantic
            (bcLeftPresentation input.context.square.presentation))
          ((selectedCoreFiberReindexFunctor
            (typedRealizableHom
              (bcLeftPresentation input.context.square.presentation))).obj
            (authoredSupportDecodedObject input.context (Discrete.mk cell))) ≫
        ((coreTransportReindexCounit
          (typedRealizableHom
            (bcLeftPresentation input.context.square.presentation))).app
          (authoredSupportDecodedObject input.context (Discrete.mk cell))).1 =
        (selectedCoreFiberCartesianLift
          (typedRealizableHom
            (bcLeftPresentation input.context.square.presentation))
          (authoredSupportDecodedObject input.context (Discrete.mk cell))).hom := by
    exact coreTransportReindexCounit_app_fac
      (typedRealizableHom
        (bcLeftPresentation input.context.square.presentation))
      (authoredSupportDecodedObject input.context (Discrete.mk cell))
  rw [hcounit]
  exact selectedCoreFiberReindexFunctor_map_fac
    (typedRealizableHom
      (bcLeftPresentation input.context.square.presentation))
    (authoredDiagnosticAxisFoldDecodedComponent input cell)

/-- The component assembled from the generated fold factor. -/
noncomputable def authoredDiagnosticAxisFoldComparisonComponent
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.Category) :
    (authoredSupportDirectRoute input.context).obj cell ⟶
      (authoredSupportViaBaseRoute input.context).obj cell := by
  rcases input with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  let normalizedContext : AuthoredSupportContext U :=
    ⟨⟨toSemanticBC presentation, presentation, rfl⟩, lift, endpoint_eq⟩
  let normalizedInput : AuthoredBCDatumSquare U :=
    ⟨normalizedContext, twoCellBase, authored⟩
  let support := normalizedContext.supportObject cell.as
  let leftReindexed :=
    (selectedCoreFiberReindexFunctor
      (typedRealizableHom (bcLeftPresentation presentation))).obj support
  exact
    (bcRightAdjunction presentation).unit.app
        ((coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcTopPresentation presentation))).obj leftReindexed) ≫
      (selectedCoreFiberReindexFunctor
        (typedRealizableHom (bcRightPresentation presentation))).map
          ((bcCoreTransportSquareIso presentation).hom.app leftReindexed) ≫
      (selectedCoreFiberReindexFunctor
        (typedRealizableHom (bcRightPresentation presentation))).map
          ((coreFiberTransportFunctor
            (typedPresentationToSemantic
              (bcBottomPresentation presentation))).map
            (authoredDiagnosticAxisFoldLeftFactor normalizedInput cell.as))

/-- The via-base image of the generated diagnostic fold. -/
noncomputable def authoredViaBaseDiagnosticAxisFoldComponent
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.Category) :
    (authoredSupportViaBaseRoute input.context).obj cell ⟶
      (authoredSupportViaBaseRoute input.context).obj cell := by
  rcases input with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  let normalizedContext : AuthoredSupportContext U :=
    ⟨⟨toSemanticBC presentation, presentation, rfl⟩, lift, endpoint_eq⟩
  let normalizedInput : AuthoredBCDatumSquare U :=
    ⟨normalizedContext, twoCellBase, authored⟩
  exact
    (selectedCoreFiberReindexFunctor
      (typedRealizableHom (bcRightPresentation presentation))).map
      ((coreFiberTransportFunctor
        (typedPresentationToSemantic
          (bcBottomPresentation presentation))).map
        (authoredDiagnosticAxisFoldComponent normalizedInput cell.as))

/-- The assembled component is canonical followed by the transported fold. -/
theorem authoredDiagnosticAxisFoldComparisonComponent_eq_canonical_comp_fold
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (cell : input.context.Category) :
    authoredDiagnosticAxisFoldComparisonComponent input cell =
      (authoredSupportCanonicalMate input.context).app cell ≫
        authoredViaBaseDiagnosticAxisFoldComponent input cell := by
  rcases input with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  let normalizedContext : AuthoredSupportContext U :=
    ⟨⟨toSemanticBC presentation, presentation, rfl⟩, lift, endpoint_eq⟩
  let normalizedInput : AuthoredBCDatumSquare U :=
    ⟨normalizedContext, twoCellBase, authored⟩
  let support := normalizedContext.supportObject cell.as
  let leftReindexed :=
    (selectedCoreFiberReindexFunctor
      (typedRealizableHom (bcLeftPresentation presentation))).obj support
  change
    (bcRightAdjunction presentation).unit.app
          ((coreFiberTransportFunctor
            (typedPresentationToSemantic
              (bcTopPresentation presentation))).obj leftReindexed) ≫
        (selectedCoreFiberReindexFunctor
          (typedRealizableHom (bcRightPresentation presentation))).map
            ((bcCoreTransportSquareIso presentation).hom.app leftReindexed) ≫
        (selectedCoreFiberReindexFunctor
          (typedRealizableHom (bcRightPresentation presentation))).map
            ((coreFiberTransportFunctor
              (typedPresentationToSemantic
                (bcBottomPresentation presentation))).map
              (authoredDiagnosticAxisFoldLeftFactor normalizedInput cell.as)) =
      (coreBeckChevalleyMate presentation).app support ≫
        (selectedCoreFiberReindexFunctor
          (typedRealizableHom (bcRightPresentation presentation))).map
          ((coreFiberTransportFunctor
            (typedPresentationToSemantic
              (bcBottomPresentation presentation))).map
            (authoredDiagnosticAxisFoldComponent normalizedInput cell.as))
  rw [authoredDiagnosticAxisFoldLeftFactor_eq_counit_comp_fold
    normalizedInput cell.as]
  rw [CategoryTheory.Functor.map_comp]
  rw [CategoryTheory.Functor.map_comp]
  rw [coreBeckChevalleyMate_app]
  simp only [Category.assoc]
  rfl

/-- The named K2 candidate producer generated from diagnostic axis data. -/
noncomputable def authoredDiagnosticAxisFoldComparison
    {U : AtomCarrier.{u}} [DecidableEq U.Atom] :
    AuthoredComparisonProducerSignature
      (authoredSupportDirectRouteFamily U)
      (authoredSupportViaBaseRouteFamily U) :=
  fun input => authoredComparisonOfComponents
    (fun cell => authoredDiagnosticAxisFoldComparisonComponent input cell)

/-- Identity raw defect makes every generated component canonical. -/
theorem authoredDiagnosticAxisFoldComparisonComponent_eq_canonical
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (hdefect : initialRawDefectCochain input.toTransportData =
      identityDefectCochain input.toTransportData)
    (cell : input.context.Category) :
    authoredDiagnosticAxisFoldComparisonComponent input cell =
      (authoredSupportCanonicalMate input.context).app cell := by
  rcases input with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  let normalizedContext : AuthoredSupportContext U :=
    ⟨⟨toSemanticBC presentation, presentation, rfl⟩, lift, endpoint_eq⟩
  let normalizedInput : AuthoredBCDatumSquare U :=
    ⟨normalizedContext, twoCellBase, authored⟩
  let support := normalizedContext.supportObject cell.as
  let leftReindexed :=
    (selectedCoreFiberReindexFunctor
      (typedRealizableHom (bcLeftPresentation presentation))).obj support
  change
    (bcRightAdjunction presentation).unit.app
          ((coreFiberTransportFunctor
            (typedPresentationToSemantic
              (bcTopPresentation presentation))).obj leftReindexed) ≫
        (selectedCoreFiberReindexFunctor
          (typedRealizableHom (bcRightPresentation presentation))).map
            ((bcCoreTransportSquareIso presentation).hom.app leftReindexed) ≫
        (selectedCoreFiberReindexFunctor
          (typedRealizableHom (bcRightPresentation presentation))).map
            ((coreFiberTransportFunctor
              (typedPresentationToSemantic
                (bcBottomPresentation presentation))).map
              (authoredDiagnosticAxisFoldLeftFactor normalizedInput cell.as)) =
      (coreBeckChevalleyMate presentation).app support
  rw [authoredDiagnosticAxisFoldLeftFactor_eq_counit
    normalizedInput hdefect cell.as]
  exact (coreBeckChevalleyMate_app presentation support).symm

/-- Identity raw defect makes the complete generated family canonical. -/
theorem authoredDiagnosticAxisFoldComparison_eq_canonical
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (hdefect : initialRawDefectCochain input.toTransportData =
      identityDefectCochain input.toTransportData) :
    authoredDiagnosticAxisFoldComparison input =
      authoredSupportCanonicalMate input.context := by
  apply CategoryTheory.NatTrans.ext
  apply funext
  intro cell
  exact authoredDiagnosticAxisFoldComparisonComponent_eq_canonical
    input hdefect cell

/-- The candidate public relation specialized to the two named producers. -/
def DiagnosticAxisFoldMateCoherentRel
    (U : AtomCarrier.{u}) [DecidableEq U.Atom] :
    MateCoherentRelSignature U :=
  mateCoherentRelEquation authoredDiagnosticAxisFoldComparison
    (authoredSupportCanonicalMateFamily U)

/-- Coherent initial data fires the generated fold relation. -/
theorem diagnosticAxisFoldMateCoherentRel_of_initialRawDefect_eq_identity
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : AuthoredBCDatumSquare U)
    (hdefect : initialRawDefectCochain input.toTransportData =
      identityDefectCochain input.toTransportData) :
    DiagnosticAxisFoldMateCoherentRel U input :=
  authoredDiagnosticAxisFoldComparison_eq_canonical input hdefect

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
