import ResearchLean.AG.DoctrineFiberProduct.BCPastingNormalizedMateAlignment
import ResearchLean.AG.DoctrineFiberProduct.CoreTransportReindexCompositorConjugacy

/-!
# Vertical pasted-mate alignment with the generated reindex compositor

The normalized vertical target route defines its right-adjoint comparison by
conjugating the inverse covariant right-edge compositor.  This module proves
that the resulting comparison is exactly the inverse generated selected-
reindex compositor and rewrites the complete target alignment in those terms.

## API position and assumptions

These declarations are G-110(E) predecessors for the vertical component-to-
outer mate commuting theorem.  Their only authored input is finite vertical
pasting data.  The covariant and contravariant compositors, adjunctions, and
normalized realization provenance are generated by the existing APIs.

## Implementation notes

The proof uses the finite-composition conjugacy theorem and reverses its
natural-isomorphism equality because the normalized outer target maps to the
literal lower-then-upper component reindex route.  Treating that inverse
orientation as definitional, or taking a right-adjoint alignment from the
caller, would erase the required mate-coherence obligation.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation CrossStageCoherence

/-- The normalized vertical right transport comparison is the generated typed
covariant compositor for the upper and lower right presentations. -/
theorem verticalNormalizedRightTransportIso_eq_typedCompositor
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    verticalNormalizedRightTransportIso data =
      typedCoreFiberTransportCompositor
        (bcRightPresentation data.upperPresentation)
        (bcRightPresentation data.lowerPresentation) := by
  rfl

/-- The normalized vertical right reindex alignment is the inverse generated
selected-reindex compositor.  This is the exact contravariant orientation
required from the normalized outer route to the literal component route. -/
theorem verticalNormalizedRightReindexAlignment_eq_selectedCompositor_inv
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    verticalNormalizedRightReindexAlignment data =
      (selectedCoreFiberReindexCompositor
        (bcRightPresentation data.upperPresentation)
        (bcRightPresentation data.lowerPresentation)).inv := by
  unfold verticalNormalizedRightReindexAlignment
  rw [verticalNormalizedRightTransportIso_eq_typedCompositor]
  have conjugacy := congrArg Iso.inv
    (coreTransportReindexCompositor_conjugateIsoEquiv
      (bcRightPresentation data.upperPresentation)
      (bcRightPresentation data.lowerPresentation))
  simpa [conjugateIsoEquiv] using conjugacy

/-- The complete normalized vertical mate-target alignment uses bottom-edge
equality transport followed by the inverse generated selected-reindex
compositor. -/
theorem verticalMateTargetAlignment_eq_selectedCompositor_inv
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    verticalMateTargetAlignment data =
      Functor.whiskerRight
          (coreFiberTransportEqIso (verticalNormalizedBottom_eq data)).hom
          (selectedCoreFiberReindexFunctor
            (bcPastingNormalizedProvenance
              (.vertical data)).rightProvenance.toRealizableHom) ≫
        Functor.whiskerLeft
          (coreFiberTransportFunctor
            (typedPresentationToSemantic
              (bcBottomPresentation data.lowerPresentation)))
          (selectedCoreFiberReindexCompositor
            (bcRightPresentation data.upperPresentation)
            (bcRightPresentation data.lowerPresentation)).inv := by
  unfold verticalMateTargetAlignment
  rw [verticalNormalizedRightReindexAlignment_eq_selectedCompositor_inv]

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
