import ResearchLean.AG.DoctrineFiberProduct.BCHorizontalTypedComponentSquareAlignment
import ResearchLean.AG.DoctrineFiberProduct.BCPastingOuterCanonicalMate

/-!
# Typed outer Beck--Chevalley comparison equalities

This module identifies the horizontal and vertical typed `TwoSquare` normal
forms with the independently generated normalized outer boundary comparisons.
The inputs are finite pasting data; every square, compositor, equality
transport, and comparison is generated by the existing G-110 pasting APIs.

## Implementation notes

The horizontal calculation first aligns the literal component square and then
uses a small `TwoSquare` interchange lemma.  The vertical calculation retains
the right-edge compositor naturality as a named lemma, avoiding reduction of
the complete pasted expression.  Caller-supplied comparison equalities and
whole-functor casts are not used.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation CrossStageCoherence
open CategoryTheory.NatTrans CategoryTheory.TwoSquare

set_option maxHeartbeats 2000000

/-- Whiskering a `TwoSquare` at the bottom by a composite is staged
associatively.  This is an API lemma for the horizontal outer equality. -/
theorem twoSquare_whiskerBottom_comp
    {C₁ C₂ C₃ C₄ : Type*}
    [Category C₁] [Category C₂] [Category C₃] [Category C₄]
    {T : C₁ ⥤ C₂} {L : C₁ ⥤ C₃} {R : C₂ ⥤ C₄}
    {B B' B'' : C₃ ⥤ C₄}
    (w : TwoSquare T L R B) (α : B ⟶ B') (β : B' ⟶ B'') :
    w.whiskerBottom (α ≫ β) =
      (w.whiskerBottom α).whiskerBottom β := by
  apply NatTrans.ext
  funext X
  simp

/-- Horizontal composition commutes with the generated external top and
bottom alignments used by the typed outer comparison. -/
theorem twoSquare_hComp_whiskerTopBottom
    {C₀ C₁ S C₂ C₃ : Type*}
    [Category C₀] [Category C₁] [Category S]
    [Category C₂] [Category C₃]
    {P : C₀ ⥤ C₁} {L : C₀ ⥤ S} {Q : C₁ ⥤ S}
    {ZT ZT₀ : C₁ ⥤ C₂} {R : C₂ ⥤ C₃}
    {ZB ZB₀ ZB₁ : S ⥤ C₃} {T : C₀ ⥤ C₂}
    (w : TwoSquare P L Q (𝟭 S))
    (z : TwoSquare ZT Q R ZB)
    (α : T ⟶ P ⋙ ZT₀) (β : ZT₀ ⟶ ZT)
    (δ : ZB ⟶ ZB₀) (ε : ZB₀ ⟶ ZB₁) :
    ((w ≫ₕ z).whiskerTop
        (α ≫ Functor.whiskerLeft P β)).whiskerBottom
      ((Functor.leftUnitor ZB).hom ≫ δ ≫ ε) =
    ((w ≫ₕ ((z.whiskerTop β).whiskerBottom δ)).whiskerTop
        α).whiskerBottom
      ((Functor.leftUnitor ZB₀).hom ≫ ε) := by
  apply NatTrans.ext
  funext X
  simp

/-- The reviewed horizontal outer normal form after replacing the typed
component square by its independently proved component comparison. -/
noncomputable def horizontalReviewedOuterComparisonNormalForm
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    TwoSquare
      (coreFiberTransportFunctor
        (normalizedNestedPasteSquare (.horizontal data)).top)
      (coreFiberTransportFunctor
        (normalizedNestedPasteSquare (.horizontal data)).left)
      (coreFiberTransportFunctor
        (normalizedNestedPasteSquare (.horizontal data)).right)
      (coreFiberTransportFunctor
        (normalizedNestedPasteSquare (.horizontal data)).bottom) :=
  (((horizontalNormalizedNorthwestLeftTransportSquare data) ≫ₕ
      horizontalCompositorAlignedComponentSquare data).whiskerTop
      (horizontalBCPastingNormalizedTopCompositor data).hom).whiskerBottom
    ((Functor.leftUnitor
      (coreFiberTransportFunctor
        ((toSemanticBC data.leftPresentation).square.bottom ≫
          (toSemanticBC data.rightPresentation).square.bottom))).hom ≫
      (coreFiberTransportEqIso
        (horizontalBCPastingNormalizedBottom_eq data).symm).hom)

/-- The normalized horizontal northwest square pasted with the reviewed
component comparison is the named normalized component comparison. -/
theorem horizontalNorthwestComponentComparison_eq_normalized
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    ((((horizontalNormalizedNorthwestLeftTransportSquare data) ≫ₕ
        TwoSquare.mk _ _ _ _
          (horizontalBCPastingComponentComparison data).hom).whiskerTop
        (horizontalBCPastingNormalizedTopCompositor data).hom).whiskerBottom
      (Functor.leftUnitor
        (coreFiberTransportFunctor
          ((toSemanticBC data.leftPresentation).square.bottom ≫
            (toSemanticBC data.rightPresentation).square.bottom))).hom) =
      TwoSquare.mk _ _ _ _
        (horizontalBCPastingNormalizedComponentComparison data).hom := by
  apply NatTrans.ext
  funext X
  simp [horizontalNormalizedNorthwestLeftTransportSquare,
    horizontalBCPastingNormalizedComponentComparison]

/-- The reviewed horizontal normal form is the independently generated outer
boundary comparison square. -/
theorem horizontalReviewedOuterComparisonNormalForm_eq_outer
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    horizontalReviewedOuterComparisonNormalForm data =
      TwoSquare.mk _ _ _ _
        (horizontalBCPastingOuterBoundaryComparison data).hom := by
  unfold horizontalReviewedOuterComparisonNormalForm
  rw [horizontalCompositorAlignedComponentSquare_eq_componentComparison]
  rw [twoSquare_whiskerBottom_comp]
  rw [horizontalNorthwestComponentComparison_eq_normalized]
  rfl

/-- The natural transformation carried by the generated horizontal typed
outer normal form. -/
noncomputable def horizontalTypedOuterComparisonNatTrans
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).top ⋙
        coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).right ⟶
      coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).left ⋙
        coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).bottom :=
  (horizontalTypedOuterComparisonNormalForm data).natTrans

/-- The natural transformation carried by the reviewed horizontal outer
normal form. -/
noncomputable def horizontalReviewedOuterComparisonNatTrans
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).top ⋙
        coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).right ⟶
      coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).left ⋙
        coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).bottom :=
  (horizontalReviewedOuterComparisonNormalForm data).natTrans

/-- The generated horizontal typed and reviewed outer normal forms carry the
same natural transformation. -/
theorem horizontalTypedOuterComparisonNatTrans_eq_reviewed
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    horizontalTypedOuterComparisonNatTrans data =
      horizontalReviewedOuterComparisonNatTrans data := by
  exact twoSquare_hComp_whiskerTopBottom
    (horizontalNormalizedNorthwestLeftTransportSquare data)
    (horizontalTypedComponentSquare data)
    (horizontalBCPastingNormalizedTopCompositor data).hom
    (coreFiberCompositor
      (typedPresentationToSemantic
        (bcTopPresentation data.leftPresentation))
      (typedPresentationToSemantic
        (bcTopPresentation data.rightPresentation))).hom
    (coreFiberCompositor
      (typedPresentationToSemantic
        (bcBottomPresentation data.leftPresentation))
      (typedPresentationToSemantic
        (bcBottomPresentation data.rightPresentation))).inv
    (coreFiberTransportEqIso
      (horizontalBCPastingNormalizedBottom_eq data).symm).hom

/-- The generated horizontal typed outer comparison equals the independently
generated horizontal outer boundary comparison. -/
theorem horizontalTypedOuterComparisonNatTrans_eq_outer
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    horizontalTypedOuterComparisonNatTrans data =
      (horizontalBCPastingOuterBoundaryComparison data).hom := by
  rw [horizontalTypedOuterComparisonNatTrans_eq_reviewed]
  exact congrArg TwoSquare.natTrans
    (horizontalReviewedOuterComparisonNormalForm_eq_outer data)

/-- The literal upper-then-lower vertical component square used for the
vertical outer equality. -/
noncomputable def verticalTypedComponentSquareForOuterEquality
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    TwoSquare
      (coreFiberTransportFunctor
        (typedPresentationToSemantic
          (bcTopPresentation data.upperPresentation)))
      (coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcLeftPresentation data.upperPresentation)) ⋙
        coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcLeftPresentation data.lowerPresentation)))
      (coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcRightPresentation data.upperPresentation)) ⋙
        coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcRightPresentation data.lowerPresentation)))
      (coreFiberTransportFunctor
        (typedPresentationToSemantic
          (bcBottomPresentation data.lowerPresentation))) :=
  (TwoSquare.mk _ _ _ _
    (bcCoreTransportSquareIso data.upperPresentation).hom) ≫ᵥ
  (TwoSquare.mk _ _ _ _
    (bcCoreTransportSquareIso data.lowerPresentation).hom)

/-- The vertical component square after aligning both composite side
functors by the generated core compositors. -/
noncomputable def verticalCompositorAlignedComponentSquareForOuterEquality
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    TwoSquare
      (coreFiberTransportFunctor
        (typedPresentationToSemantic
          (bcTopPresentation data.upperPresentation)))
      (coreFiberTransportFunctor
        ((toSemanticBC data.upperPresentation).square.left ≫
          (toSemanticBC data.lowerPresentation).square.left))
      (coreFiberTransportFunctor
        ((toSemanticBC data.upperPresentation).square.right ≫
          (toSemanticBC data.lowerPresentation).square.right))
      (coreFiberTransportFunctor
        (typedPresentationToSemantic
          (bcBottomPresentation data.lowerPresentation))) :=
  ((verticalTypedComponentSquareForOuterEquality data).whiskerRight
    (coreFiberCompositor
      (typedPresentationToSemantic
        (bcRightPresentation data.upperPresentation))
      (typedPresentationToSemantic
        (bcRightPresentation data.lowerPresentation))).hom).whiskerLeft
    (coreFiberCompositor
      (typedPresentationToSemantic
        (bcLeftPresentation data.upperPresentation))
      (typedPresentationToSemantic
        (bcLeftPresentation data.lowerPresentation))).inv

/-- The compositor-aligned vertical component square is the reviewed vertical
component comparison. -/
theorem verticalCompositorAlignedComponentSquareForOuterEquality_eq
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    verticalCompositorAlignedComponentSquareForOuterEquality data =
      TwoSquare.mk _ _ _ _
        (verticalBCPastingComponentComparison data).hom := by
  have hupp :
      bcCoreTransportSquareIso data.upperPresentation =
        bcSemanticCoreTransportSquareIso
          (toSemanticBC data.upperPresentation) := by
    exact bcProvenanceCoreTransportSquareIso_eq_semantic
      (⟨data.upperPresentation, rfl⟩ :
        BCRealizationProvenance (toSemanticBC data.upperPresentation))
  have hlow :
      bcCoreTransportSquareIso data.lowerPresentation =
        bcSemanticCoreTransportSquareIso
          (toSemanticBC data.lowerPresentation) := by
    exact bcProvenanceCoreTransportSquareIso_eq_semantic
      (⟨data.lowerPresentation, rfl⟩ :
        BCRealizationProvenance (toSemanticBC data.lowerPresentation))
  apply NatTrans.ext
  funext X
  simp [verticalCompositorAlignedComponentSquareForOuterEquality,
    verticalTypedComponentSquareForOuterEquality,
    verticalBCPastingComponentComparison, hupp, hlow]
  rfl

/-- The reviewed vertical outer route with each right, top, component, and
left alignment exposed as a named composition. -/
noncomputable def verticalReviewedOuterComparisonNatTrans
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.vertical data)).top ⋙
        coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.vertical data)).right ⟶
      coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.vertical data)).left ⋙
        coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.vertical data)).bottom :=
  Functor.whiskerLeft
      (coreFiberTransportFunctor
        (normalizedNestedPasteSquare (.vertical data)).top)
      (coreFiberTransportEqIso
        (verticalBCPastingNormalizedRight_eq data)).hom ≫
    Functor.whiskerRight
      (verticalBCPastingNormalizedTopCompositor data).hom
      (coreFiberTransportFunctor
        ((toSemanticBC data.upperPresentation).square.right ≫
          (toSemanticBC data.lowerPresentation).square.right)) ≫
    Functor.whiskerLeft
      (coreFiberTransportFunctor
        (bcPastingNorthwestIso (.vertical data)).inv)
      (verticalCompositorAlignedComponentSquareForOuterEquality data) ≫
    Functor.whiskerRight
      (verticalBCPastingNormalizedLeftCompositor data).symm.hom
      (coreFiberTransportFunctor
        (toSemanticBC data.lowerPresentation).square.bottom)

/-- The reviewed vertical route is the independently generated normalized
outer boundary comparison. -/
theorem verticalReviewedOuterComparisonNatTrans_eq_outer
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    verticalReviewedOuterComparisonNatTrans data =
      (verticalBCPastingOuterBoundaryComparison data).hom := by
  unfold verticalReviewedOuterComparisonNatTrans
  unfold verticalBCPastingOuterBoundaryComparison
  unfold verticalBCPastingNormalizedComponentComparison
  rw [verticalCompositorAlignedComponentSquareForOuterEquality_eq]
  simp only [Iso.trans_hom, Functor.isoWhiskerLeft_hom,
    Functor.isoWhiskerRight_hom]

/-- The vertical right compositor carries the normalized top alignment to the
iterated component route. -/
@[reassoc]
theorem verticalTopRightAlignment_app
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U)
    (X : CoreFiber
      (normalizedNestedPasteSquare (.vertical data)).northwest) :
    (verticalNormalizedRightTransportIso data).hom.app
          ((coreFiberTransportFunctor
            (normalizedNestedPasteSquare (.vertical data)).top).obj X) ≫
        (coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcRightPresentation data.lowerPresentation))).map
          ((coreFiberTransportFunctor
            (typedPresentationToSemantic
              (bcRightPresentation data.upperPresentation))).map
            ((verticalBCPastingNormalizedTopCompositor data).hom.app X)) =
      (coreFiberTransportEqIso
          (verticalBCPastingNormalizedRight_eq data)).hom.app
            ((coreFiberTransportFunctor
              (normalizedNestedPasteSquare (.vertical data)).top).obj X) ≫
        (coreFiberTransportFunctor
          ((toSemanticBC data.upperPresentation).square.right ≫
            (toSemanticBC data.lowerPresentation).square.right)).map
            ((verticalBCPastingNormalizedTopCompositor data).hom.app X) ≫
          (coreFiberCompositor
            (typedPresentationToSemantic
              (bcRightPresentation data.upperPresentation))
            (typedPresentationToSemantic
              (bcRightPresentation data.lowerPresentation))).hom.app
              ((coreFiberTransportFunctor
                (typedPresentationToSemantic
                  (bcTopPresentation data.upperPresentation))).obj
                ((coreFiberTransportFunctor
                  (bcPastingNorthwestIso (.vertical data)).inv).obj X)) := by
  unfold verticalNormalizedRightTransportIso
  simp only [Iso.trans_hom, NatTrans.comp_app, Category.assoc]
  have hn := (coreFiberCompositor
      (typedPresentationToSemantic
        (bcRightPresentation data.upperPresentation))
      (typedPresentationToSemantic
        (bcRightPresentation data.lowerPresentation))).hom.naturality
    ((verticalBCPastingNormalizedTopCompositor data).hom.app X)
  simpa only [Functor.comp_map] using congrArg
    (fun k =>
      (coreFiberTransportEqIso
        (verticalBCPastingNormalizedRight_eq data)).hom.app
          ((coreFiberTransportFunctor
            (normalizedNestedPasteSquare (.vertical data)).top).obj X) ≫ k)
    hn.symm

/-- The generated vertical bottom alignment reduces to the left unitor on the
literal lower component bottom edge. -/
theorem verticalTypedComponentsToOuterBottom_eq_leftUnitor
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    verticalTypedComponentsToOuterBottom data =
      (Functor.leftUnitor
        (coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcBottomPresentation data.lowerPresentation)))).hom := by
  rw [verticalTypedComponentsToOuterBottom_eq]
  unfold coreFiberTransportEqIso
  have hproof : verticalNormalizedBottom_eq data = rfl :=
    Subsingleton.elim _ _
  rw [hproof]
  exact Category.comp_id _

/-- The generated vertical typed outer normal form equals the reviewed route.
The larger heartbeat allowance is local to this dependent categorical
normalization. -/
theorem verticalTypedOuterComparisonNormalForm_eq_reviewed
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    verticalTypedOuterComparisonNormalForm data =
      verticalReviewedOuterComparisonNatTrans data := by
  set_option maxHeartbeats 8000000 in
    rw [verticalTypedOuterComparisonNormalForm_eq_staged,
      verticalTypedComponentsToOuterBottom_eq_leftUnitor]
    apply NatTrans.ext
    funext X
    rw [verticalTypedRawComparisonSquare_eq]
    unfold verticalReviewedOuterComparisonNatTrans
    simp only [TwoSquare.whiskerTop, TwoSquare.whiskerRight,
      TwoSquare.whiskerBottom, TwoSquare.hComp, TwoSquare.vComp,
      NatTrans.comp_app, Functor.whiskerLeft_app,
      Functor.whiskerRight_app, Functor.associator_hom_app,
      Functor.associator_inv_app, Functor.comp_obj,
      Category.assoc, Category.id_comp, Category.comp_id,
      Functor.id_obj]
    simp [verticalNormalizedNorthwestLeftTransportSquare,
      verticalCompositorAlignedComponentSquareForOuterEquality,
      verticalTypedComponentSquareForOuterEquality]
    rw [verticalTopRightAlignment_app_assoc]
    rfl

/-- The generated vertical typed outer comparison equals the independently
generated vertical outer boundary comparison. -/
theorem verticalTypedOuterComparisonNormalForm_eq_outer
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    verticalTypedOuterComparisonNormalForm data =
      (verticalBCPastingOuterBoundaryComparison data).hom := by
  rw [verticalTypedOuterComparisonNormalForm_eq_reviewed,
    verticalReviewedOuterComparisonNatTrans_eq_outer]

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
