import ResearchLean.AG.DoctrineFiberProduct.BCSchema

/-!
# Finite-code Beck--Chevalley pasting schema

This module fixes the F0b2 pasting boundary for G-110.  A horizontal or
vertical input consists of three typed finite-code arrows and one shared
pre-base-change diagnostic presentation.  The two adjacent pullback squares,
their common edge, the outer cospan, and the pasted square are generated from
those arrows.  No semantic square, pullback certificate, comparison
isomorphism, or expected equality is an input field.

The northwest object obtained by iterating the finite pullback constructor is
not definitionally the same code as the northwest object obtained by applying
the constructor once to the outer cospan.  Realization compatibility is
therefore stated through the canonical isomorphism generated by the two
pullback universal properties, rather than by a false literal equality of raw
codes.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open CategoryTheory.Limits
open AtomFoundation
open TransportCoherence

/-! ## Canonical BC presentations from typed cospans -/

/-- The compatible-point table generated by a typed finite-code cospan. -/
def compatiblePointCodeOfCospan
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (cospan : CartCospanPresentation U) : CompatiblePointCode where
  sourcePoints
    | 0 => cospan.firstSource.point.down.val
    | 1 => cospan.secondSource.point.down.val
  basePoint := cospan.base.point.down.val
  images
    | 0 => (cospan.first.sourceMap cospan.firstSource.point).down.val
    | 1 => (cospan.second.sourceMap cospan.secondSource.point).down.val

/-- The generated compatible-point table satisfies all seven finite checks. -/
theorem compatiblePointCodeOfCospan_wellFormed
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (cospan : CartCospanPresentation U) :
    (compatiblePointCodeOfCospan cospan).WellFormed cospan := by
  refine ⟨rfl, rfl, rfl, rfl, rfl, ?_, ?_⟩
  · exact congrArg (fun point => point.down.val) cospan.first.source_eq
  · exact congrArg (fun point => point.down.val) cospan.second.source_eq

/--
Generate a validated BC presentation from a typed cospan and one
pre-base-change diagnostic presentation.
-/
def bcPresentationOfCospan
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (cospan : CartCospanPresentation U)
    (diagnostic : FiniteDiagnosticPresentation.{u}) : BCPresentation U :=
  ⟨{ cospan := cospan,
      compatiblePoints := compatiblePointCodeOfCospan cospan,
      diagnostic := diagnostic },
    compatiblePointCodeOfCospan_wellFormed cospan⟩

/--
Every validated BC presentation is propositionally equal to the canonical
point-table presentation generated from its own cospan and diagnostic.  Thus
the canonical point producer does not shrink the existing presentation class.
-/
theorem bcPresentationOfCospan_normalizes
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (presentation : BCPresentation U) :
    bcPresentationOfCospan presentation.1.cospan
        presentation.1.diagnostic = presentation := by
  rcases presentation with ⟨⟨cospan, points, diagnostic⟩, hwellFormed⟩
  rcases hwellFormed with
    ⟨hsourceFirst, hsourceSecond, hbase, himageFirst, himageSecond, _, _⟩
  apply Subtype.ext
  have hpoints : compatiblePointCodeOfCospan cospan = points := by
    cases points with
    | mk sourcePoints basePoint images =>
      change CompatiblePointCode.mk _ _ _ =
        CompatiblePointCode.mk sourcePoints basePoint images
      congr
      · funext index
        fin_cases index
        · exact hsourceFirst.symm
        · exact hsourceSecond.symm
      · exact hbase.symm
      · funext index
        fin_cases index
        · exact himageFirst.symm
        · exact himageSecond.symm
  change
    ({ cospan := cospan
       compatiblePoints := compatiblePointCodeOfCospan cospan
       diagnostic := diagnostic } : BCRawCode U) =
      { cospan := cospan
        compatiblePoints := points
        diagnostic := diagnostic }
  rw [hpoints]

/-! ## Strictly composable horizontal and vertical seeds -/

/--
Three finite-code arrows generating two strictly adjacent horizontal pullback
squares.  The right square is generated first; its first projection is the
right edge of the generated left square.
-/
structure HorizontalBCPastingData (U : AtomCarrier.{u}) [DecidableEq U.Atom] where
  /-- Southwest object of the left square. -/
  southwest : FiniteInstanceCode U
  /-- Shared southeast/southwest object. -/
  middleSouth : FiniteInstanceCode U
  /-- Northeast object of the right square. -/
  northeast : FiniteInstanceCode U
  /-- Southeast object of the outer rectangle. -/
  southeast : FiniteInstanceCode U
  /-- Bottom edge of the left square. -/
  bottomLeft : CartPresentationBetween southwest middleSouth
  /-- Bottom edge of the right square. -/
  bottomRight : CartPresentationBetween middleSouth southeast
  /-- Right edge of the right square. -/
  right : CartPresentationBetween northeast southeast
  /-- Shared pre-base-change diagnostic presentation. -/
  diagnostic : FiniteDiagnosticPresentation.{u}

namespace HorizontalBCPastingData

/-- The generated right-hand pullback square. -/
def rightPullback {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :=
  pullbackPresentation data.bottomRight data.right

/-- The generated left-hand pullback square, sharing the right square's first projection. -/
def leftPullback {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :=
  pullbackPresentation data.bottomLeft
    (pullbackFstPresentation data.bottomRight data.right)

/-- The generated finite presentation of the left component square. -/
def leftPresentation {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) : BCPresentation U :=
  bcPresentationOfCospan
    { firstSource := data.southwest
      secondSource := pullbackInstanceCode data.bottomRight data.right
      base := data.middleSouth
      first := data.bottomLeft
      second := pullbackFstPresentation data.bottomRight data.right }
    data.diagnostic

/-- The generated finite presentation of the right component square. -/
def rightPresentation {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) : BCPresentation U :=
  bcPresentationOfCospan
    { firstSource := data.middleSouth
      secondSource := data.northeast
      base := data.southeast
      first := data.bottomRight
      second := data.right }
    data.diagnostic

/-- The outer cospan obtained by composing the two bottom edges. -/
def outerCospan {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) : CartCospanPresentation U where
  firstSource := data.southwest
  secondSource := data.northeast
  base := data.southeast
  first := compPresentation data.bottomLeft data.bottomRight
  second := data.right

/-- The generated finite presentation of the outer horizontal rectangle. -/
def pastePresentation {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) : BCPresentation U :=
  bcPresentationOfCospan data.outerCospan data.diagnostic

/--
The semantic outer rectangle obtained by literally composing the generated
left and right pullback squares.  Its bottom edge is written through the
finite-code composition constructor, so it has exactly the same outer cospan
as `pastePresentation` after decoding.
-/
noncomputable def nestedSquare
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) : ExtInstSquare U :=
  let left := (toSemanticBC data.leftPresentation).square
  let right := (toSemanticBC data.rightPresentation).square
  have sharedEdge : left.right = right.left := rfl
  { northwest := left.northwest
    northeast := right.northeast
    southwest := left.southwest
    southeast := right.southeast
    top := left.top ≫ right.top
    left := left.left
    right := right.right
    bottom := (toSemanticCart
      (compPresentation data.bottomLeft data.bottomRight).toPresentation).hom
    commutes := by
      rw [toSemanticCart_compPresentation_hom]
      calc
        left.left ≫ (left.bottom ≫ right.bottom) =
            (left.left ≫ left.bottom) ≫ right.bottom := by simp
        _ = (left.top ≫ left.right) ≫ right.bottom := by
          rw [left.commutes]
        _ = left.top ≫ (right.left ≫ right.bottom) := by
          rw [sharedEdge]
          simp
        _ = left.top ≫ (right.top ≫ right.right) := by
          rw [right.commutes]
        _ = (left.top ≫ right.top) ≫ right.right := by simp }

/-- Horizontal pasting of the two generated component squares is a pullback. -/
theorem nestedSquare_isPullback
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    IsPullback data.nestedSquare.left data.nestedSquare.top
      data.nestedSquare.bottom data.nestedSquare.right := by
  have leftPullback := (toSemanticBC_sound data.leftPresentation).1
  have rightPullback := (toSemanticBC_sound data.rightPresentation).1
  have pasted := leftPullback.flip.paste_horiz rightPullback.flip
  simpa [nestedSquare, toSemanticCart_compPresentation_hom] using pasted.flip

end HorizontalBCPastingData

/--
Three finite-code arrows generating two strictly adjacent vertical pullback
squares.  The lower square is generated first; its second projection is the
bottom edge of the generated upper square.
-/
structure VerticalBCPastingData (U : AtomCarrier.{u}) [DecidableEq U.Atom] where
  /-- Northeast object of the upper square. -/
  northeast : FiniteInstanceCode U
  /-- Shared southeast/northeast object. -/
  middleEast : FiniteInstanceCode U
  /-- Southwest object of the lower square. -/
  southwest : FiniteInstanceCode U
  /-- Southeast object of the outer rectangle. -/
  southeast : FiniteInstanceCode U
  /-- Right edge of the upper square. -/
  rightTop : CartPresentationBetween northeast middleEast
  /-- Bottom edge of the lower square. -/
  bottom : CartPresentationBetween southwest southeast
  /-- Right edge of the lower square. -/
  rightBottom : CartPresentationBetween middleEast southeast
  /-- Shared pre-base-change diagnostic presentation. -/
  diagnostic : FiniteDiagnosticPresentation.{u}

namespace VerticalBCPastingData

/-- The generated lower pullback square. -/
def lowerPullback {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :=
  pullbackPresentation data.bottom data.rightBottom

/-- The generated upper pullback square, sharing the lower square's second projection. -/
def upperPullback {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :=
  pullbackPresentation
    (pullbackSndPresentation data.bottom data.rightBottom) data.rightTop

/-- The generated finite presentation of the upper component square. -/
def upperPresentation {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) : BCPresentation U :=
  bcPresentationOfCospan
    { firstSource := pullbackInstanceCode data.bottom data.rightBottom
      secondSource := data.northeast
      base := data.middleEast
      first := pullbackSndPresentation data.bottom data.rightBottom
      second := data.rightTop }
    data.diagnostic

/-- The generated finite presentation of the lower component square. -/
def lowerPresentation {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) : BCPresentation U :=
  bcPresentationOfCospan
    { firstSource := data.southwest
      secondSource := data.middleEast
      base := data.southeast
      first := data.bottom
      second := data.rightBottom }
    data.diagnostic

/-- The outer cospan obtained by composing the two right edges. -/
def outerCospan {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) : CartCospanPresentation U where
  firstSource := data.southwest
  secondSource := data.northeast
  base := data.southeast
  first := data.bottom
  second := compPresentation data.rightTop data.rightBottom

/-- The generated finite presentation of the outer vertical rectangle. -/
def pastePresentation {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) : BCPresentation U :=
  bcPresentationOfCospan data.outerCospan data.diagnostic

/--
The semantic outer rectangle obtained by literally composing the generated
upper and lower pullback squares.  Its right edge is written through the
finite-code composition constructor, matching the outer decoded cospan.
-/
noncomputable def nestedSquare
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) : ExtInstSquare U :=
  let upper := (toSemanticBC data.upperPresentation).square
  let lower := (toSemanticBC data.lowerPresentation).square
  have sharedEdge : upper.bottom = lower.top := rfl
  { northwest := upper.northwest
    northeast := upper.northeast
    southwest := lower.southwest
    southeast := lower.southeast
    top := upper.top
    left := upper.left ≫ lower.left
    right := (toSemanticCart
      (compPresentation data.rightTop data.rightBottom).toPresentation).hom
    bottom := lower.bottom
    commutes := by
      rw [toSemanticCart_compPresentation_hom]
      calc
        (upper.left ≫ lower.left) ≫ lower.bottom =
            upper.left ≫ (lower.left ≫ lower.bottom) := by simp
        _ = upper.left ≫ (lower.top ≫ lower.right) := by
          rw [lower.commutes]
        _ = (upper.left ≫ upper.bottom) ≫ lower.right := by
          rw [sharedEdge]
          simp
        _ = (upper.top ≫ upper.right) ≫ lower.right := by
          rw [upper.commutes]
        _ = upper.top ≫ (upper.right ≫ lower.right) := by simp }

/-- Vertical pasting of the two generated component squares is a pullback. -/
theorem nestedSquare_isPullback
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    IsPullback data.nestedSquare.left data.nestedSquare.top
      data.nestedSquare.bottom data.nestedSquare.right := by
  have upperPullback := (toSemanticBC_sound data.upperPresentation).1
  have lowerPullback := (toSemanticBC_sound data.lowerPresentation).1
  have pasted := upperPullback.flip.paste_vert lowerPullback.flip
  simpa [nestedSquare, toSemanticCart_compPresentation_hom] using pasted.flip

end VerticalBCPastingData

/-- Direction-indexed input for finite-code square pasting. -/
inductive BCPastingInput (U : AtomCarrier.{u}) [DecidableEq U.Atom]
  | horizontal (data : HorizontalBCPastingData U)
  | vertical (data : VerticalBCPastingData U)

/-- Generate the finite presentation of the outer pasted rectangle. -/
def pastePresentation {U : AtomCarrier.{u}} [DecidableEq U.Atom] :
    BCPastingInput U → BCPresentation U
  | .horizontal data => data.pastePresentation
  | .vertical data => data.pastePresentation

/-- The literally pasted semantic outer rectangle. -/
noncomputable def nestedPasteSquare
    {U : AtomCarrier.{u}} [DecidableEq U.Atom] :
    BCPastingInput U → ExtInstSquare U
  | .horizontal data => data.nestedSquare
  | .vertical data => data.nestedSquare

/-- Both directions of finite-code square pasting preserve pullback universality. -/
theorem nestedPasteSquare_isPullback
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : BCPastingInput U) :
    IsPullback (nestedPasteSquare input).left (nestedPasteSquare input).top
      (nestedPasteSquare input).bottom (nestedPasteSquare input).right := by
  cases input with
  | horizontal data => exact data.nestedSquare_isPullback
  | vertical data => exact data.nestedSquare_isPullback

/-!
The canonical output presentation and the literally nested paste have the same
outer cospan.  Their northwest objects can differ as finite codes, so the
realization theorem uses the unique isomorphism between the two generated
pullbacks.
-/

namespace HorizontalBCPastingData

/-- Canonical northwest comparison for a horizontal paste. -/
noncomputable def pasteNorthwestIso
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    data.nestedSquare.northwest ≅
      (toSemanticBC data.pastePresentation).square.northwest :=
  data.nestedSquare_isPullback.isoIsPullback
    data.southwest.toSemantic data.northeast.toSemantic
      (toSemanticBC_sound data.pastePresentation).1

/-- The horizontal northwest isomorphism identifies the left projections. -/
theorem pasteNorthwestIso_hom_left
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    data.pasteNorthwestIso.hom ≫
        (toSemanticBC data.pastePresentation).square.left =
      data.nestedSquare.left := by
  exact data.nestedSquare_isPullback.isoIsPullback_hom_fst
    data.southwest.toSemantic data.northeast.toSemantic
      (toSemanticBC_sound data.pastePresentation).1

/-- The horizontal northwest isomorphism identifies the top projections. -/
theorem pasteNorthwestIso_hom_top
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    data.pasteNorthwestIso.hom ≫
        (toSemanticBC data.pastePresentation).square.top =
      data.nestedSquare.top := by
  exact data.nestedSquare_isPullback.isoIsPullback_hom_snd
    data.southwest.toSemantic data.northeast.toSemantic
      (toSemanticBC_sound data.pastePresentation).1

end HorizontalBCPastingData

namespace VerticalBCPastingData

/-- Canonical northwest comparison for a vertical paste. -/
noncomputable def pasteNorthwestIso
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    data.nestedSquare.northwest ≅
      (toSemanticBC data.pastePresentation).square.northwest :=
  data.nestedSquare_isPullback.isoIsPullback
    data.southwest.toSemantic data.northeast.toSemantic
      (toSemanticBC_sound data.pastePresentation).1

/-- The vertical northwest isomorphism identifies the left projections. -/
theorem pasteNorthwestIso_hom_left
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    data.pasteNorthwestIso.hom ≫
        (toSemanticBC data.pastePresentation).square.left =
      data.nestedSquare.left := by
  exact data.nestedSquare_isPullback.isoIsPullback_hom_fst
    data.southwest.toSemantic data.northeast.toSemantic
      (toSemanticBC_sound data.pastePresentation).1

/-- The vertical northwest isomorphism identifies the top projections. -/
theorem pasteNorthwestIso_hom_top
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    data.pasteNorthwestIso.hom ≫
        (toSemanticBC data.pastePresentation).square.top =
      data.nestedSquare.top := by
  exact data.nestedSquare_isPullback.isoIsPullback_hom_snd
    data.southwest.toSemantic data.northeast.toSemantic
      (toSemanticBC_sound data.pastePresentation).1

end VerticalBCPastingData

/-! ## Authored 2-cell raw table -/

/--
The F0b2 raw schema for an authored comparison on finite 2-cell support.
The support packages are an index generated by the later K2 construction; the
only authored field is the same pointwise `PackageFiberAut` assignment table
as the reviewed G-106 comparator field.  A natural family, canonical mate, and
expected equality are deliberately absent.
-/
structure AuthoredBC2CellPresentation
    {U : AtomCarrier.{u}} {G : FiniteTransportPresentation.{u}}
    (supportPackage : G.TwoCell → AATCorePackage U) where
  /-- Authored endpoint-fiber automorphism on every finite 2-cell. -/
  comparator : (cell : G.TwoCell) →
    PackageFiberAut (supportPackage cell)

namespace AuthoredBC2CellPresentation

/-- Reuse exactly the authored comparator table of reviewed G-106 data. -/
def ofTransportData
    {U : AtomCarrier.{u}} {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U) :
    AuthoredBC2CellPresentation
      (fun cell => data.lift.package (G.twoTarget cell)) where
  comparator := data.comparator

@[simp]
theorem ofTransportData_comparator
    {U : AtomCarrier.{u}} {G : FiniteTransportPresentation.{u}}
    (data : AdmissibleTransportData G U) (cell : G.TwoCell) :
    (ofTransportData data).comparator cell = data.comparator cell := rfl

end AuthoredBC2CellPresentation

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
