import ResearchLean.AG.DoctrineFiberProduct.BCPastingClosure
import ResearchLean.AG.DoctrineFiberProduct.BCPresentationReplacement

/-!
# Beck--Chevalley comparison on the normalized pasted square

The horizontal and vertical finite-code pasting constructors generate an outer
presentation whose semantic input is the canonically northwest-normalized
literal paste.  This module turns that realization equality into the exact
`BCRealizationProvenance` consumed by the canonical covariant square comparison
and identifies the resulting comparison with the semantic comparison on the
normalized pasted square.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation CrossStageCoherence

/-- The G-110(E) comparison-realization predecessor for either pasting
direction.  Its presentation and equality are generated by the finite-code
pasting constructor and its reviewed realization theorem. -/
noncomputable def bcPastingNormalizedProvenance
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : BCPastingInput U) :
    BCRealizationProvenance (normalizedNestedPasteSemanticInput input) where
  presentation := pastePresentation input
  realization_eq := (toSemanticBC_pastePresentation_eq input).symm

/-- The covariant comparison generated from the pasted outer presentation is
the canonical semantic comparison on its normalized literal pasted square. -/
theorem bcPastingCoreTransportSquareIso_eq_semantic
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : BCPastingInput U) :
    bcProvenanceCoreTransportSquareIso
        (bcPastingNormalizedProvenance input) =
      bcSemanticCoreTransportSquareIso
        (normalizedNestedPasteSemanticInput input) :=
  bcProvenanceCoreTransportSquareIso_eq_semantic
    (bcPastingNormalizedProvenance input)

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
