import ResearchLean.AG.DoctrineFiberProduct.BCPastingNorthwestSecondMate
import ResearchLean.AG.DoctrineFiberProduct.BCHorizontalPastingMateComposition
import ResearchLean.AG.DoctrineFiberProduct.BCVerticalPastingComparisonNormalization

/-!
# Normalized-provenance mate alignment for Beck--Chevalley pasting

The canonical outer mates use the selected reindex functors generated by the
normalized realization provenance.  This module derives their northwest
second mates directly and records the exact source and target transformations
needed to compare them with the literal component-mate composites.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation CrossStageCoherence
open CategoryTheory.NatTrans CategoryTheory.TwoSquare

set_option maxHeartbeats 2000000

/-- Covariant northwest alignment from the horizontal normalized-provenance
left adjunction to the left component adjunction. -/
noncomputable def horizontalNormalizedNorthwestLeftTransportSquare
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :=
  TwoSquare.mk _ _ _ _
    ((horizontalBCPastingNormalizedLeftCompositor data).inv ≫
      (coreFiberTransportFunctor
        (normalizedNestedPasteSquare (.horizontal data)).left).rightUnitor.inv)

/-- The horizontal northwest second mate generated directly on the normalized
outer realization provenance. -/
noncomputable def horizontalNormalizedNorthwestReindexAlignment
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    selectedCoreFiberReindexFunctor
          (bcPastingNormalizedProvenance
            (.horizontal data)).leftProvenance.toRealizableHom ⋙
        coreFiberTransportFunctor data.pasteNorthwestIso.inv ⟶
      selectedCoreFiberReindexFunctor
        (typedRealizableHom
          (bcLeftPresentation data.leftPresentation)) :=
  ((mateEquiv
    (coreTransportReindexAdjunction
      (bcPastingNormalizedProvenance
        (.horizontal data)).leftProvenance.toRealizableHom)
    (bcLeftAdjunction data.leftPresentation)
    (horizontalNormalizedNorthwestLeftTransportSquare data)).natTrans) ≫
      (selectedCoreFiberReindexFunctor
        (typedRealizableHom
          (bcLeftPresentation data.leftPresentation))).leftUnitor.hom

/-- Exact source alignment from the horizontal normalized outer mate to the
literal component-mate source. -/
noncomputable def horizontalMateSourceAlignment
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    selectedCoreFiberReindexFunctor
          (bcPastingNormalizedProvenance
            (.horizontal data)).leftProvenance.toRealizableHom ⋙
        coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).top ⟶
      selectedCoreFiberReindexFunctor
          (typedRealizableHom (bcLeftPresentation data.leftPresentation)) ⋙
        (coreFiberTransportFunctor
            (typedPresentationToSemantic
              (bcTopPresentation data.leftPresentation)) ⋙
          coreFiberTransportFunctor
            (typedPresentationToSemantic
              (bcTopPresentation data.rightPresentation))) :=
  Functor.whiskerLeft
      (selectedCoreFiberReindexFunctor
        (bcPastingNormalizedProvenance
          (.horizontal data)).leftProvenance.toRealizableHom)
      (horizontalBCPastingNormalizedTopCompositor data).hom ≫
    (Functor.associator _ _ _).inv ≫
    Functor.whiskerRight
      (horizontalNormalizedNorthwestReindexAlignment data)
      (coreFiberTransportFunctor
        ((toSemanticBC data.leftPresentation).square.top ≫
          (toSemanticBC data.rightPresentation).square.top)) ≫
    Functor.whiskerLeft
      (selectedCoreFiberReindexFunctor
        (typedRealizableHom (bcLeftPresentation data.leftPresentation)))
      (coreFiberCompositor
        (typedPresentationToSemantic
          (bcTopPresentation data.leftPresentation))
        (typedPresentationToSemantic
          (bcTopPresentation data.rightPresentation))).hom

/-- Exact target alignment from the horizontal normalized outer mate to the
literal component-mate target. -/
noncomputable def horizontalMateTargetAlignment
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : HorizontalBCPastingData U) :
    coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.horizontal data)).bottom ⋙
        selectedCoreFiberReindexFunctor
          (typedRealizableHom (bcRightPresentation data.pastePresentation)) ⟶
      (coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcBottomPresentation data.leftPresentation)) ⋙
        coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcBottomPresentation data.rightPresentation))) ⋙
        selectedCoreFiberReindexFunctor
          (typedRealizableHom (bcRightPresentation data.rightPresentation)) :=
  Functor.whiskerRight
    ((coreFiberTransportEqIso
        (horizontalBCPastingNormalizedBottom_eq data)).trans
      (coreFiberCompositor
        (typedPresentationToSemantic
          (bcBottomPresentation data.leftPresentation))
        (typedPresentationToSemantic
          (bcBottomPresentation data.rightPresentation)))).hom
    (selectedCoreFiberReindexFunctor
      (typedRealizableHom (bcRightPresentation data.rightPresentation)))

/-- The normalized vertical bottom edge is the lower component bottom edge. -/
theorem verticalNormalizedBottom_eq
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    (normalizedNestedPasteSquare (.vertical data)).bottom =
      typedPresentationToSemantic
        (bcBottomPresentation data.lowerPresentation) := by
  rfl

/-- Covariant northwest alignment from the vertical normalized-provenance left
adjunction to the composed component left adjunction. -/
noncomputable def verticalNormalizedNorthwestLeftTransportSquare
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :=
  TwoSquare.mk _ _ _ _
    (Functor.whiskerLeft
        (coreFiberTransportFunctor data.pasteNorthwestIso.inv)
        (coreFiberCompositor
          (typedPresentationToSemantic
            (bcLeftPresentation data.upperPresentation))
          (typedPresentationToSemantic
            (bcLeftPresentation data.lowerPresentation))).inv ≫
      (verticalBCPastingNormalizedLeftCompositor data).inv ≫
      (coreFiberTransportFunctor
        (normalizedNestedPasteSquare (.vertical data)).left).rightUnitor.inv)

/-- The vertical northwest second mate generated directly on the normalized
outer realization provenance. -/
noncomputable def verticalNormalizedNorthwestReindexAlignment
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    selectedCoreFiberReindexFunctor
          (bcPastingNormalizedProvenance
            (.vertical data)).leftProvenance.toRealizableHom ⋙
        coreFiberTransportFunctor data.pasteNorthwestIso.inv ⟶
      selectedCoreFiberReindexFunctor
          (typedRealizableHom
            (bcLeftPresentation data.lowerPresentation)) ⋙
        selectedCoreFiberReindexFunctor
          (typedRealizableHom
            (bcLeftPresentation data.upperPresentation)) :=
  ((mateEquiv
    (coreTransportReindexAdjunction
      (bcPastingNormalizedProvenance
        (.vertical data)).leftProvenance.toRealizableHom)
    ((bcLeftAdjunction data.upperPresentation).comp
      (bcLeftAdjunction data.lowerPresentation))
    (verticalNormalizedNorthwestLeftTransportSquare data)).natTrans) ≫
      (Functor.leftUnitor _).hom

/-- Exact source alignment from the vertical normalized outer mate to the
literal component-mate source. -/
noncomputable def verticalMateSourceAlignment
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    selectedCoreFiberReindexFunctor
          (bcPastingNormalizedProvenance
            (.vertical data)).leftProvenance.toRealizableHom ⋙
        coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.vertical data)).top ⟶
      (selectedCoreFiberReindexFunctor
          (typedRealizableHom
            (bcLeftPresentation data.lowerPresentation)) ⋙
        selectedCoreFiberReindexFunctor
          (typedRealizableHom
            (bcLeftPresentation data.upperPresentation))) ⋙
        coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcTopPresentation data.upperPresentation)) :=
  Functor.whiskerLeft
      (selectedCoreFiberReindexFunctor
        (bcPastingNormalizedProvenance
          (.vertical data)).leftProvenance.toRealizableHom)
      (verticalBCPastingNormalizedTopCompositor data).hom ≫
    (Functor.associator _ _ _).inv ≫
    Functor.whiskerRight
      (verticalNormalizedNorthwestReindexAlignment data)
      (coreFiberTransportFunctor data.nestedSquare.top)

/-- Covariant right-edge alignment from the normalized outer route to the
literal upper/lower component route. -/
noncomputable def verticalNormalizedRightTransportIso
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    coreFiberTransportFunctor
        (normalizedNestedPasteSquare (.vertical data)).right ≅
      coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcRightPresentation data.upperPresentation)) ⋙
        coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcRightPresentation data.lowerPresentation)) :=
  (coreFiberTransportEqIso
      (verticalBCPastingNormalizedRight_eq data)).trans
    (coreFiberCompositor
      (typedPresentationToSemantic
        (bcRightPresentation data.upperPresentation))
      (typedPresentationToSemantic
        (bcRightPresentation data.lowerPresentation)))

/-- Contravariant right-edge alignment generated as the conjugate of the
inverse covariant right-edge alignment. -/
noncomputable def verticalNormalizedRightReindexAlignment
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    selectedCoreFiberReindexFunctor
        (bcPastingNormalizedProvenance
          (.vertical data)).rightProvenance.toRealizableHom ⟶
      selectedCoreFiberReindexFunctor
          (typedRealizableHom
            (bcRightPresentation data.lowerPresentation)) ⋙
        selectedCoreFiberReindexFunctor
          (typedRealizableHom
            (bcRightPresentation data.upperPresentation)) :=
  conjugateEquiv
    (coreTransportReindexAdjunction
      (bcPastingNormalizedProvenance
        (.vertical data)).rightProvenance.toRealizableHom)
    ((bcRightAdjunction data.upperPresentation).comp
      (bcRightAdjunction data.lowerPresentation))
    (verticalNormalizedRightTransportIso data).inv

/-- Exact target alignment from the vertical normalized outer mate to the
literal component-mate target. -/
noncomputable def verticalMateTargetAlignment
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (data : VerticalBCPastingData U) :
    coreFiberTransportFunctor
          (normalizedNestedPasteSquare (.vertical data)).bottom ⋙
        selectedCoreFiberReindexFunctor
          (bcPastingNormalizedProvenance
            (.vertical data)).rightProvenance.toRealizableHom ⟶
      coreFiberTransportFunctor
          (typedPresentationToSemantic
            (bcBottomPresentation data.lowerPresentation)) ⋙
        (selectedCoreFiberReindexFunctor
            (typedRealizableHom
              (bcRightPresentation data.lowerPresentation)) ⋙
          selectedCoreFiberReindexFunctor
            (typedRealizableHom
              (bcRightPresentation data.upperPresentation))) :=
  Functor.whiskerRight
      (coreFiberTransportEqIso (verticalNormalizedBottom_eq data)).hom
      (selectedCoreFiberReindexFunctor
        (bcPastingNormalizedProvenance
          (.vertical data)).rightProvenance.toRealizableHom) ≫
    Functor.whiskerLeft
      (coreFiberTransportFunctor
        (typedPresentationToSemantic
          (bcBottomPresentation data.lowerPresentation)))
      (verticalNormalizedRightReindexAlignment data)

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
