import ResearchLean.AG.DoctrineFiberProduct.CartesianRegimeReindexingCleavageWitnesses
import ResearchLean.AG.DoctrineFiberProduct.CartesianRegimeReindexingPresentationCoherence
import ResearchLean.AG.DoctrineFiberProduct.CartesianRegimeReindexingPresentationReplacement

/-!
# Finite witnesses for cartesian-presentation descent

This module supplies raw-distinct finite presentations that decode to the same
semantic cartesian input.  The alternate code pads the identity Atom
permutation with a nonempty authored support; its decoder is still the literal
identity permutation.  Thus the distinction is genuine code data rather than
proof-field noise.  The existing infinite-source semantic identity supplies a
typed negative example showing that finite realization provenance is not
automatically inhabited.

## Implementation notes

The alternate presentation keeps the existing endpoint codes and source table
literal, changing only the authored finite support of an identity-decoding Atom
table.  A separate padded identity presentation is retained because relative
unitor descent requires an identity-decoding representative at the common
support endpoint.  Adding a comparison certificate to either presentation was
rejected: every comparison and coherence law below is generated by the generic
selected-lift APIs.

The comparison observations below reuse the existing selective two-to-support
arrow, whose source table is noninjective, and the existing nonidentity
four-axis vertical map.  Presentation inequality is not used to claim that an
opaque selected comparison component is itself nonidentity.
-/

namespace AAT.AG.DoctrineFiberProduct

open CategoryTheory
open AtomFoundation
open CrossStageCoherence

/-! ## A noncanonical code for the identity Atom permutation -/

/-- Executable Atom equality for the concrete finite presentation witness. -/
local instance finitePresentationDescentAtomDecidableEq :
    DecidableEq FiniteModel.carrier.Atom := by
  change DecidableEq FiniteModel.FiniteAtom
  infer_instance

/--
The identity Atom permutation encoded with a nonempty singleton support.  This
is raw-distinct from `AtomPermutationCode.refl`, whose authored support is
empty, although both codes decode to the same semantic permutation.
-/
def finitePresentationPaddedIdentityAtomCode :
    AtomPermutationCode FiniteModel.carrier :=
  AtomPermutationCode.ofPerm
    {FiniteModel.FiniteAtom.componentA}
    (Equiv.refl FiniteModel.carrier.Atom) (by simp) (by simp)

/-- The padded code retains its authored singleton support. -/
@[simp]
theorem finitePresentationPaddedIdentityAtomCode_support :
    finitePresentationPaddedIdentityAtomCode.support =
      {FiniteModel.FiniteAtom.componentA} :=
  rfl

/-- The noncanonical padded code still decodes to the identity permutation. -/
@[simp]
theorem finitePresentationPaddedIdentityAtomCode_toEquiv :
    finitePresentationPaddedIdentityAtomCode.toEquiv =
      Equiv.refl FiniteModel.carrier.Atom := by
  simp [finitePresentationPaddedIdentityAtomCode]

/-! ## Raw-distinct presentations of the selective two-to-support arrow -/

/--
The existing noninvertible selective two-to-support source table, presented
with the padded identity Atom code.  All validation laws are regenerated from
the actual finite tables.
-/
def finitePaddedSelectiveTwoToSupportPresentation :
    CartPresentationBetween finiteSelectiveTwoInstance
      finitePortfolioSupportInstance where
  sourceMap := fun _ => ULift.up (1 : Fin 2)
  atomEquiv := finitePresentationPaddedIdentityAtomCode
  normalize_eq _ := rfl
  extraction_eq _ := by
    change finiteWithoutComponentCAtomPredicate =
      finiteWithoutComponentCAtomPredicate.transport
        finitePresentationPaddedIdentityAtomCode.toEquiv
    rw [finitePresentationPaddedIdentityAtomCode_toEquiv]
    simp
  source_eq := rfl

/-- The canonical composite presentation has empty authored Atom support. -/
@[simp]
theorem finiteCanonicalSelectiveTwoToSupportPresentation_atomSupport :
    finiteSelectiveTwoToSupportPresentation.atomEquiv.support = ∅ := by
  simp [finiteSelectiveTwoToSupportPresentation,
    finiteSelectiveTwoToOnePresentation,
    finiteSelectiveOneToSupportPresentation, compPresentation,
    AtomPermutationCode.trans, AtomPermutationCode.refl,
    AtomPermutationCode.ofPerm]

/-- The canonical composite presentation decodes the identity Atom map. -/
@[simp]
theorem finiteCanonicalSelectiveTwoToSupportPresentation_atomEquiv :
    finiteSelectiveTwoToSupportPresentation.atomEquiv.toEquiv =
      Equiv.refl FiniteModel.carrier.Atom := by
  simp [finiteSelectiveTwoToSupportPresentation,
    finiteSelectiveTwoToOnePresentation,
    finiteSelectiveOneToSupportPresentation, compPresentation]

/-- The typed finite presentations are unequal as authored code values. -/
theorem finiteSelectiveTwoToSupportPresentation_ne_padded :
    finiteSelectiveTwoToSupportPresentation ≠
      finitePaddedSelectiveTwoToSupportPresentation := by
  intro equality
  have supportEquality := congrArg
    (fun presentation : CartPresentationBetween finiteSelectiveTwoInstance
        finitePortfolioSupportInstance => presentation.atomEquiv.support)
    equality
  have componentAMemPadded :
      FiniteModel.FiniteAtom.componentA ∈
        finitePaddedSelectiveTwoToSupportPresentation.atomEquiv.support := by
    change FiniteModel.FiniteAtom.componentA ∈
      finitePresentationPaddedIdentityAtomCode.support
    rw [finitePresentationPaddedIdentityAtomCode_support]
    simp
  have componentAMem :
      FiniteModel.FiniteAtom.componentA ∈
        finiteSelectiveTwoToSupportPresentation.atomEquiv.support :=
    Eq.mp
      (congrArg (fun support => FiniteModel.FiniteAtom.componentA ∈ support)
        supportEquality.symm)
      componentAMemPadded
  simp at componentAMem

/-- Forgetting endpoint indices preserves the genuine raw-code inequality. -/
theorem finiteSelectiveTwoToSupportRawPresentation_ne_padded :
    finiteSelectiveTwoToSupportPresentation.toPresentation ≠
      finitePaddedSelectiveTwoToSupportPresentation.toPresentation := by
  intro equality
  have supportEquality := congrArg
    (fun presentation : CartPresentation FiniteModel.carrier =>
      presentation.1.atomEquiv.support) equality
  have componentAMemPadded :
      FiniteModel.FiniteAtom.componentA ∈
        (CartPresentationBetween.toPresentation
          finitePaddedSelectiveTwoToSupportPresentation).1.atomEquiv.support := by
    change FiniteModel.FiniteAtom.componentA ∈
      finitePresentationPaddedIdentityAtomCode.support
    rw [finitePresentationPaddedIdentityAtomCode_support]
    simp
  have componentAMem :
      FiniteModel.FiniteAtom.componentA ∈
        (CartPresentationBetween.toPresentation
          finiteSelectiveTwoToSupportPresentation).1.atomEquiv.support :=
    Eq.mp
      (congrArg (fun support => FiniteModel.FiniteAtom.componentA ∈ support)
        supportEquality.symm)
      componentAMemPadded
  change FiniteModel.FiniteAtom.componentA ∈
    finiteSelectiveTwoToSupportPresentation.atomEquiv.support at componentAMem
  simp at componentAMem

/-- The two raw-distinct presentations decode to the same exact pointed hom. -/
theorem finiteSelectiveTwoToSupportPresentation_semanticHom_eq :
    typedPresentationToSemantic finiteSelectiveTwoToSupportPresentation =
      typedPresentationToSemantic
        finitePaddedSelectiveTwoToSupportPresentation := by
  apply ExtInstHom.ext
  apply ExactDoctrineHom.ext
  · rfl
  · change
      finiteSelectiveTwoToSupportPresentation.atomEquiv.toEquiv =
        finitePresentationPaddedIdentityAtomCode.toEquiv
    rw [finiteCanonicalSelectiveTwoToSupportPresentation_atomEquiv,
      finitePresentationPaddedIdentityAtomCode_toEquiv]

/-- The raw-distinct pair has equal full `CartSemanticInput` decodings. -/
theorem finiteSelectiveTwoToSupportPresentation_semanticInput_eq :
    typedCartSemanticInput finiteSelectiveTwoToSupportPresentation =
      typedCartSemanticInput
        finitePaddedSelectiveTwoToSupportPresentation := by
  exact typedCartSemanticInput_eq_of_hom_eq
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq

/-! ## Fixed-input provenance comparison -/

/-- The infinite-source semantic identity admits no finite realization provenance. -/
theorem infiniteIdentityInput_has_no_cartRealizationProvenance :
    ¬ Nonempty (CartRealizationProvenance infiniteIdentityInput) := by
  rintro ⟨provenance⟩
  exact infiniteIdentityInput_not_presented
    ⟨provenance.presentation, provenance.realization_eq⟩

/--
The canonical selective presentation regarded as finite provenance over its
own literal semantic input.
-/
def finiteSelectiveCanonicalCartProvenance :
    CartRealizationProvenance
      (typedCartSemanticInput finiteSelectiveTwoToSupportPresentation) :=
  typedCartRealizationProvenance finiteSelectiveTwoToSupportPresentation

/--
The padded presentation rebased to the canonical presentation's literal
semantic input using the proved decoder equality.
-/
def finiteSelectivePaddedCartProvenance :
    CartRealizationProvenance
      (typedCartSemanticInput finiteSelectiveTwoToSupportPresentation) :=
  typedCartRealizationProvenanceOfSemanticEq
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq

/-- The fixed-input provenance comparison at the finite four-axis target. -/
noncomputable def finiteSelectiveCartProvenanceComparisonApp :=
  cartRealizationProvenanceComparisonApp
    finiteSelectiveCanonicalCartProvenance
    finiteSelectivePaddedCartProvenance finiteReindexFourAxisTarget

/-- The provenance comparison's forward component satisfies its lift triangle. -/
theorem finiteSelectiveCartProvenanceComparisonApp_hom_fac :
    finiteSelectiveCartProvenanceComparisonApp.hom.1 ≫
        (selectedCoreFiberCartesianLift
          finiteSelectivePaddedCartProvenance.toRealizableHom
          finiteReindexFourAxisTarget).hom =
      (selectedCoreFiberCartesianLift
        finiteSelectiveCanonicalCartProvenance.toRealizableHom
        finiteReindexFourAxisTarget).hom :=
  cartRealizationProvenanceComparisonApp_hom_fac
    finiteSelectiveCanonicalCartProvenance
    finiteSelectivePaddedCartProvenance finiteReindexFourAxisTarget

/-- The provenance comparison's inverse component satisfies the reverse triangle. -/
theorem finiteSelectiveCartProvenanceComparisonApp_inv_fac :
    finiteSelectiveCartProvenanceComparisonApp.inv.1 ≫
        (selectedCoreFiberCartesianLift
          finiteSelectiveCanonicalCartProvenance.toRealizableHom
          finiteReindexFourAxisTarget).hom =
      (selectedCoreFiberCartesianLift
        finiteSelectivePaddedCartProvenance.toRealizableHom
        finiteReindexFourAxisTarget).hom :=
  cartRealizationProvenanceComparisonApp_inv_fac
    finiteSelectiveCanonicalCartProvenance
    finiteSelectivePaddedCartProvenance finiteReindexFourAxisTarget

/-- Fixed-input comparison naturality fires on the genuine four-axis swap. -/
theorem finiteSelectiveCartProvenanceComparison_naturality :
    (selectedCoreFiberReindexFunctor
        finiteSelectiveCanonicalCartProvenance.toRealizableHom).map
          finiteReindexAxisSwapHom ≫
        finiteSelectiveCartProvenanceComparisonApp.hom =
      finiteSelectiveCartProvenanceComparisonApp.hom ≫
        (selectedCoreFiberReindexFunctor
          finiteSelectivePaddedCartProvenance.toRealizableHom).map
            finiteReindexAxisSwapHom :=
  cartRealizationProvenanceComparison_naturality
    finiteSelectiveCanonicalCartProvenance
    finiteSelectivePaddedCartProvenance finiteReindexAxisSwapHom

/-- The whole selected-functor comparison generated from the two provenances. -/
noncomputable def finiteSelectiveCartProvenanceComparison :=
  cartRealizationProvenanceComparison
    finiteSelectiveCanonicalCartProvenance
    finiteSelectivePaddedCartProvenance

/-- The concrete provenance comparison API is reflexive. -/
theorem finiteSelectiveCartProvenanceComparison_refl :
    cartRealizationProvenanceComparison
        finiteSelectiveCanonicalCartProvenance
        finiteSelectiveCanonicalCartProvenance =
      Iso.refl (selectedCoreFiberReindexFunctor
        finiteSelectiveCanonicalCartProvenance.toRealizableHom) :=
  cartRealizationProvenanceComparison_refl
    finiteSelectiveCanonicalCartProvenance

/-- Reversing the concrete provenance comparison gives the reverse comparison. -/
theorem finiteSelectiveCartProvenanceComparison_symm :
    (finiteSelectiveCartProvenanceComparison).symm =
      cartRealizationProvenanceComparison
        finiteSelectivePaddedCartProvenance
        finiteSelectiveCanonicalCartProvenance :=
  cartRealizationProvenanceComparison_symm
    finiteSelectiveCanonicalCartProvenance
    finiteSelectivePaddedCartProvenance

/-- The raw-distinct provenance pair fires the whole-comparison cocycle. -/
theorem finiteSelectiveCartProvenanceComparison_cocycle :
    (finiteSelectiveCartProvenanceComparison).trans
        (cartRealizationProvenanceComparison
          finiteSelectivePaddedCartProvenance
          finiteSelectiveCanonicalCartProvenance) =
      cartRealizationProvenanceComparison
        finiteSelectiveCanonicalCartProvenance
        finiteSelectiveCanonicalCartProvenance :=
  cartRealizationProvenanceComparison_cocycle
    finiteSelectiveCanonicalCartProvenance
    finiteSelectivePaddedCartProvenance
    finiteSelectiveCanonicalCartProvenance

/-! ## Exact-endpoint typed comparison -/

/-- The typed presentation comparison at the finite four-axis target. -/
noncomputable def finiteSelectiveTypedPresentationComparisonApp :=
  selectedTypedCoreFiberPresentationComparisonApp
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq
    finiteReindexFourAxisTarget

/-- The forward typed comparison satisfies its selected-lift triangle. -/
theorem finiteSelectiveTypedPresentationComparisonApp_hom_fac :
    finiteSelectiveTypedPresentationComparisonApp.hom.1 ≫
        (selectedTypedCoreFiberCartesianLift
          finitePaddedSelectiveTwoToSupportPresentation
          finiteReindexFourAxisTarget).hom =
      (selectedTypedCoreFiberCartesianLift
        finiteSelectiveTwoToSupportPresentation
        finiteReindexFourAxisTarget).hom :=
  selectedTypedCoreFiberPresentationComparisonApp_hom_fac
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq
    finiteReindexFourAxisTarget

/-- The inverse typed comparison satisfies the reverse selected-lift triangle. -/
theorem finiteSelectiveTypedPresentationComparisonApp_inv_fac :
    finiteSelectiveTypedPresentationComparisonApp.inv.1 ≫
        (selectedTypedCoreFiberCartesianLift
          finiteSelectiveTwoToSupportPresentation
          finiteReindexFourAxisTarget).hom =
      (selectedTypedCoreFiberCartesianLift
        finitePaddedSelectiveTwoToSupportPresentation
        finiteReindexFourAxisTarget).hom :=
  selectedTypedCoreFiberPresentationComparisonApp_inv_fac
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq
    finiteReindexFourAxisTarget

/-- Typed replacement naturality fires on the genuine four-axis swap. -/
theorem finiteSelectiveTypedPresentationComparison_naturality :
    (selectedTypedCoreFiberReindexFunctor
        finiteSelectiveTwoToSupportPresentation).map
          finiteReindexAxisSwapHom ≫
        finiteSelectiveTypedPresentationComparisonApp.hom =
      finiteSelectiveTypedPresentationComparisonApp.hom ≫
        (selectedTypedCoreFiberReindexFunctor
          finitePaddedSelectiveTwoToSupportPresentation).map
            finiteReindexAxisSwapHom :=
  selectedTypedCoreFiberPresentationComparison_naturality
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq
    finiteReindexAxisSwapHom

/-- The whole exact-endpoint comparison for the raw-distinct pair. -/
noncomputable def finiteSelectiveTypedPresentationComparison :=
  selectedTypedCoreFiberPresentationComparison
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq

/-- The typed comparison API is reflexive on the canonical presentation. -/
theorem finiteSelectiveTypedPresentationComparison_refl :
    selectedTypedCoreFiberPresentationComparison
        finiteSelectiveTwoToSupportPresentation
        finiteSelectiveTwoToSupportPresentation rfl =
      Iso.refl (selectedTypedCoreFiberReindexFunctor
        finiteSelectiveTwoToSupportPresentation) :=
  selectedTypedCoreFiberPresentationComparison_refl
    finiteSelectiveTwoToSupportPresentation

/-- Reversing the typed comparison uses the reversed semantic equality. -/
theorem finiteSelectiveTypedPresentationComparison_symm :
    (finiteSelectiveTypedPresentationComparison).symm =
      selectedTypedCoreFiberPresentationComparison
        finitePaddedSelectiveTwoToSupportPresentation
        finiteSelectiveTwoToSupportPresentation
        finiteSelectiveTwoToSupportPresentation_semanticHom_eq.symm :=
  selectedTypedCoreFiberPresentationComparison_symm
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq

/-- The raw-distinct typed pair fires the whole-comparison cocycle. -/
theorem finiteSelectiveTypedPresentationComparison_cocycle :
    (finiteSelectiveTypedPresentationComparison).trans
        (selectedTypedCoreFiberPresentationComparison
          finitePaddedSelectiveTwoToSupportPresentation
          finiteSelectiveTwoToSupportPresentation
          finiteSelectiveTwoToSupportPresentation_semanticHom_eq.symm) =
      selectedTypedCoreFiberPresentationComparison
        finiteSelectiveTwoToSupportPresentation
        finiteSelectiveTwoToSupportPresentation
        (finiteSelectiveTwoToSupportPresentation_semanticHom_eq.trans
          finiteSelectiveTwoToSupportPresentation_semanticHom_eq.symm) :=
  selectedTypedCoreFiberPresentationComparison_cocycle
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq
    finiteSelectiveTwoToSupportPresentation_semanticHom_eq.symm

/-! ## A raw-distinct identity presentation at the support endpoint -/

/--
The identity source table at the finite support endpoint, again carrying the
noncanonical padded identity Atom code.
-/
def finitePaddedSupportIdentityPresentation :
    CartPresentationBetween finitePortfolioSupportInstance
      finitePortfolioSupportInstance where
  sourceMap := id
  atomEquiv := finitePresentationPaddedIdentityAtomCode
  normalize_eq _ := rfl
  extraction_eq input := by
    change finiteModelDoctrineCode.extraction input =
      (finiteModelDoctrineCode.extraction input).transport
        finitePresentationPaddedIdentityAtomCode.toEquiv
    rw [finitePresentationPaddedIdentityAtomCode_toEquiv]
    simp
  source_eq := rfl

/-- The canonical typed identity uses the empty-support Atom code. -/
@[simp]
theorem finiteCanonicalSupportIdentityPresentation_atomSupport :
    (idTypedPresentation finitePortfolioSupportInstance).atomEquiv.support =
      ∅ :=
  rfl

/-- The canonical and padded support identity presentations are raw-distinct. -/
theorem finiteSupportIdentityPresentation_ne_padded :
    idTypedPresentation finitePortfolioSupportInstance ≠
      finitePaddedSupportIdentityPresentation := by
  intro equality
  have supportEquality := congrArg
    (fun presentation : CartPresentationBetween
        finitePortfolioSupportInstance finitePortfolioSupportInstance =>
      presentation.atomEquiv.support) equality
  have componentAMemPadded :
      FiniteModel.FiniteAtom.componentA ∈
        finitePaddedSupportIdentityPresentation.atomEquiv.support := by
    change FiniteModel.FiniteAtom.componentA ∈
      finitePresentationPaddedIdentityAtomCode.support
    rw [finitePresentationPaddedIdentityAtomCode_support]
    simp
  have componentAMem :
      FiniteModel.FiniteAtom.componentA ∈
        (idTypedPresentation
          finitePortfolioSupportInstance).atomEquiv.support :=
    Eq.mp
      (congrArg (fun support => FiniteModel.FiniteAtom.componentA ∈ support)
        supportEquality.symm)
      componentAMemPadded
  simp at componentAMem

/-- The padded identity presentation decodes to the categorical identity. -/
theorem finitePaddedSupportIdentityPresentation_hom :
    typedPresentationToSemantic finitePaddedSupportIdentityPresentation =
      𝟙 finitePortfolioSupportInstance.toSemantic := by
  apply ExtInstHom.ext
  apply ExactDoctrineHom.ext
  · rfl
  · change finitePresentationPaddedIdentityAtomCode.toEquiv =
      Equiv.refl FiniteModel.carrier.Atom
    exact finitePresentationPaddedIdentityAtomCode_toEquiv

/-- The canonical and padded identities have equal decoded semantic homs. -/
theorem finiteSupportIdentityPresentation_semanticHom_eq :
    typedPresentationToSemantic
        (idTypedPresentation finitePortfolioSupportInstance) =
      typedPresentationToSemantic
        finitePaddedSupportIdentityPresentation := by
  calc
    _ = 𝟙 finitePortfolioSupportInstance.toSemantic :=
      typedRealizableHom_id_hom finitePortfolioSupportInstance
    _ = _ := finitePaddedSupportIdentityPresentation_hom.symm

/-- The identity pair also has equal full semantic-input decodings. -/
theorem finiteSupportIdentityPresentation_semanticInput_eq :
    typedCartSemanticInput
        (idTypedPresentation finitePortfolioSupportInstance) =
      typedCartSemanticInput finitePaddedSupportIdentityPresentation := by
  exact typedCartSemanticInput_eq_of_hom_eq
    (idTypedPresentation finitePortfolioSupportInstance)
    finitePaddedSupportIdentityPresentation
    finiteSupportIdentityPresentation_semanticHom_eq

/-! ## Presentation-relative compositor on the selective chain -/

/--
The canonical selective composite decodes to the categorical composite of its
existing two-to-one and one-to-support presentation legs.
-/
theorem finiteCanonicalSelectivePresentationComposition_eq :
    typedPresentationToSemantic finiteSelectiveTwoToSupportPresentation =
      typedPresentationToSemantic finiteSelectiveTwoToOnePresentation ≫
        typedPresentationToSemantic
          finiteSelectiveOneToSupportPresentation := by
  simpa only [finiteSelectiveTwoToSupportPresentation,
    typedCartSemanticInput, typedRealizableHom_hom] using
      typedRealizableHom_comp_hom finiteSelectiveTwoToOnePresentation
        finiteSelectiveOneToSupportPresentation

/--
The raw-distinct padded direct presentation decodes to the same two-leg
semantic composite; this equation is derived from the finite decoder proofs.
-/
theorem finitePaddedSelectivePresentationComposition_eq :
    typedPresentationToSemantic
        finitePaddedSelectiveTwoToSupportPresentation =
      typedPresentationToSemantic finiteSelectiveTwoToOnePresentation ≫
        typedPresentationToSemantic
          finiteSelectiveOneToSupportPresentation := by
  calc
    _ = typedPresentationToSemantic
        finiteSelectiveTwoToSupportPresentation :=
      finiteSelectiveTwoToSupportPresentation_semanticHom_eq.symm
    _ = _ := finiteCanonicalSelectivePresentationComposition_eq

/--
The relative compositor for the padded direct presentation, evaluated at the
finite four-axis target.
-/
noncomputable def finitePaddedSelectivePresentationCompositorApp :=
  selectedTypedCoreFiberPresentationCompositorApp
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToOnePresentation
    finiteSelectiveOneToSupportPresentation
    finitePaddedSelectivePresentationComposition_eq
    finiteReindexFourAxisTarget

/-- The padded relative compositor satisfies its forward two-step triangle. -/
theorem finitePaddedSelectivePresentationCompositorApp_hom_fac :
    finitePaddedSelectivePresentationCompositorApp.hom.1 ≫
        (selectedTypedCoreFiberCartesianLift
          finitePaddedSelectiveTwoToSupportPresentation
          finiteReindexFourAxisTarget).hom =
      (selectedCoreFiberIteratedCartesianLift
        finiteSelectiveTwoToOnePresentation
        finiteSelectiveOneToSupportPresentation
        finiteReindexFourAxisTarget).hom :=
  selectedTypedCoreFiberPresentationCompositorApp_hom_fac
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToOnePresentation
    finiteSelectiveOneToSupportPresentation
    finitePaddedSelectivePresentationComposition_eq
    finiteReindexFourAxisTarget

/-- The padded relative compositor satisfies its inverse two-step triangle. -/
theorem finitePaddedSelectivePresentationCompositorApp_inv_fac :
    finitePaddedSelectivePresentationCompositorApp.inv.1 ≫
        (selectedCoreFiberIteratedCartesianLift
          finiteSelectiveTwoToOnePresentation
          finiteSelectiveOneToSupportPresentation
          finiteReindexFourAxisTarget).hom =
      (selectedTypedCoreFiberCartesianLift
        finitePaddedSelectiveTwoToSupportPresentation
        finiteReindexFourAxisTarget).hom :=
  selectedTypedCoreFiberPresentationCompositorApp_inv_fac
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToOnePresentation
    finiteSelectiveOneToSupportPresentation
    finitePaddedSelectivePresentationComposition_eq
    finiteReindexFourAxisTarget

/-- Relative-compositor naturality fires on the genuine four-axis swap. -/
theorem finitePaddedSelectivePresentationCompositor_naturality :
    (selectedTypedCoreFiberReindexFunctor
          finiteSelectiveOneToSupportPresentation ⋙
        selectedTypedCoreFiberReindexFunctor
          finiteSelectiveTwoToOnePresentation).map
          finiteReindexAxisSwapHom ≫
        finitePaddedSelectivePresentationCompositorApp.hom =
      finitePaddedSelectivePresentationCompositorApp.hom ≫
        (selectedTypedCoreFiberReindexFunctor
          finitePaddedSelectiveTwoToSupportPresentation).map
            finiteReindexAxisSwapHom :=
  selectedTypedCoreFiberPresentationCompositor_naturality
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToOnePresentation
    finiteSelectiveOneToSupportPresentation
    finitePaddedSelectivePresentationComposition_eq
    finiteReindexAxisSwapHom

/-- The whole relative compositor for the padded direct presentation. -/
noncomputable def finitePaddedSelectivePresentationCompositor :=
  selectedTypedCoreFiberPresentationCompositor
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToOnePresentation
    finiteSelectiveOneToSupportPresentation
    finitePaddedSelectivePresentationComposition_eq

/--
Componentwise compositor compatibility compares the canonical and padded
direct presentations while keeping both genuine selective-chain legs fixed.
-/
theorem finiteSelectivePresentationCompositor_compatibility_app :
    (selectedTypedCoreFiberPresentationCompositorApp
      finiteSelectiveTwoToSupportPresentation
      finiteSelectiveTwoToOnePresentation
      finiteSelectiveOneToSupportPresentation
      finiteCanonicalSelectivePresentationComposition_eq
      finiteReindexFourAxisTarget).hom ≫
        (selectedTypedCoreFiberPresentationComparisonApp
          finiteSelectiveTwoToSupportPresentation
          finitePaddedSelectiveTwoToSupportPresentation
          (typedPresentationDirect_congr
            finiteSelectiveTwoToSupportPresentation
            finitePaddedSelectiveTwoToSupportPresentation
            finiteSelectiveTwoToOnePresentation
            finiteSelectiveTwoToOnePresentation
            finiteSelectiveOneToSupportPresentation
            finiteSelectiveOneToSupportPresentation
            finiteCanonicalSelectivePresentationComposition_eq
            finitePaddedSelectivePresentationComposition_eq rfl rfl)
          finiteReindexFourAxisTarget).hom =
      (selectedTypedCoreFiberReindexFunctor
        finiteSelectiveTwoToOnePresentation).map
          (selectedTypedCoreFiberPresentationComparisonApp
            finiteSelectiveOneToSupportPresentation
            finiteSelectiveOneToSupportPresentation rfl
            finiteReindexFourAxisTarget).hom ≫
        (selectedTypedCoreFiberPresentationComparisonApp
          finiteSelectiveTwoToOnePresentation
          finiteSelectiveTwoToOnePresentation rfl
          ((selectedTypedCoreFiberReindexFunctor
            finiteSelectiveOneToSupportPresentation).obj
              finiteReindexFourAxisTarget)).hom ≫
        finitePaddedSelectivePresentationCompositorApp.hom :=
  selectedTypedCoreFiberPresentationCompositor_compatibility_app
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToOnePresentation
    finiteSelectiveTwoToOnePresentation
    finiteSelectiveOneToSupportPresentation
    finiteSelectiveOneToSupportPresentation
    finiteCanonicalSelectivePresentationComposition_eq
    finitePaddedSelectivePresentationComposition_eq rfl rfl
    finiteReindexFourAxisTarget

/--
The whole relative compositor square commutes under replacement of the raw
direct presentation.
-/
theorem finiteSelectivePresentationCompositor_compatibility :
    (selectedTypedCoreFiberPresentationCompositor
      finiteSelectiveTwoToSupportPresentation
      finiteSelectiveTwoToOnePresentation
      finiteSelectiveOneToSupportPresentation
      finiteCanonicalSelectivePresentationComposition_eq).trans
        (selectedTypedCoreFiberPresentationComparison
          finiteSelectiveTwoToSupportPresentation
          finitePaddedSelectiveTwoToSupportPresentation
          (typedPresentationDirect_congr
            finiteSelectiveTwoToSupportPresentation
            finitePaddedSelectiveTwoToSupportPresentation
            finiteSelectiveTwoToOnePresentation
            finiteSelectiveTwoToOnePresentation
            finiteSelectiveOneToSupportPresentation
            finiteSelectiveOneToSupportPresentation
            finiteCanonicalSelectivePresentationComposition_eq
            finitePaddedSelectivePresentationComposition_eq rfl rfl)) =
      (selectedTypedCoreFiberPresentationHorizontalComparison
        finiteSelectiveTwoToOnePresentation
        finiteSelectiveTwoToOnePresentation
        finiteSelectiveOneToSupportPresentation
        finiteSelectiveOneToSupportPresentation rfl rfl).trans
          finitePaddedSelectivePresentationCompositor :=
  selectedTypedCoreFiberPresentationCompositor_compatibility
    finiteSelectiveTwoToSupportPresentation
    finitePaddedSelectiveTwoToSupportPresentation
    finiteSelectiveTwoToOnePresentation
    finiteSelectiveTwoToOnePresentation
    finiteSelectiveOneToSupportPresentation
    finiteSelectiveOneToSupportPresentation
    finiteCanonicalSelectivePresentationComposition_eq
    finitePaddedSelectivePresentationComposition_eq rfl rfl

/-! ## Presentation-relative unitor at the support endpoint -/

/-- The canonical support identity decodes to the categorical identity. -/
theorem finiteCanonicalSupportIdentityPresentation_hom :
    typedPresentationToSemantic
        (idTypedPresentation finitePortfolioSupportInstance) =
      𝟙 finitePortfolioSupportInstance.toSemantic := by
  simpa only [typedCartSemanticInput, typedRealizableHom_hom] using
    typedRealizableHom_id_hom finitePortfolioSupportInstance

/-- The padded relative unitor evaluated at the finite four-axis target. -/
noncomputable def finitePaddedSupportPresentationUnitorApp :=
  selectedTypedCoreFiberPresentationUnitorApp
    finitePortfolioSupportInstance finitePaddedSupportIdentityPresentation
    finitePaddedSupportIdentityPresentation_hom finiteReindexFourAxisTarget

/-- The padded relative unitor satisfies its selected-lift triangle. -/
theorem finitePaddedSupportPresentationUnitorApp_hom_fac :
    finitePaddedSupportPresentationUnitorApp.hom.1 ≫
        (selectedTypedCoreFiberCartesianLift
          finitePaddedSupportIdentityPresentation
          finiteReindexFourAxisTarget).hom =
      𝟙 finiteReindexFourAxisTarget.1 :=
  selectedTypedCoreFiberPresentationUnitorApp_hom_fac
    finitePortfolioSupportInstance finitePaddedSupportIdentityPresentation
    finitePaddedSupportIdentityPresentation_hom finiteReindexFourAxisTarget

/-- The inverse padded unitor component is the selected identity lift. -/
theorem finitePaddedSupportPresentationUnitorApp_inv :
    finitePaddedSupportPresentationUnitorApp.inv.1 =
      (selectedTypedCoreFiberCartesianLift
        finitePaddedSupportIdentityPresentation
        finiteReindexFourAxisTarget).hom :=
  selectedTypedCoreFiberPresentationUnitorApp_inv
    finitePortfolioSupportInstance finitePaddedSupportIdentityPresentation
    finitePaddedSupportIdentityPresentation_hom finiteReindexFourAxisTarget

/-- Relative-unitor naturality fires on the genuine four-axis swap. -/
theorem finitePaddedSupportPresentationUnitor_naturality :
    finiteReindexAxisSwapHom ≫
        finitePaddedSupportPresentationUnitorApp.hom =
      finitePaddedSupportPresentationUnitorApp.hom ≫
        (selectedTypedCoreFiberReindexFunctor
          finitePaddedSupportIdentityPresentation).map
            finiteReindexAxisSwapHom :=
  selectedTypedCoreFiberPresentationUnitor_naturality
    finitePortfolioSupportInstance finitePaddedSupportIdentityPresentation
    finitePaddedSupportIdentityPresentation_hom finiteReindexAxisSwapHom

/-- The whole relative unitor for the padded identity presentation. -/
noncomputable def finitePaddedSupportPresentationUnitor :=
  selectedTypedCoreFiberPresentationUnitor finitePortfolioSupportInstance
    finitePaddedSupportIdentityPresentation
    finitePaddedSupportIdentityPresentation_hom

/--
Componentwise unitor compatibility compares the raw-distinct canonical and
padded identity presentations.
-/
theorem finiteSupportPresentationUnitor_compatibility_app :
    (selectedTypedCoreFiberPresentationUnitorApp
      finitePortfolioSupportInstance
      (idTypedPresentation finitePortfolioSupportInstance)
      finiteCanonicalSupportIdentityPresentation_hom
      finiteReindexFourAxisTarget).hom ≫
        (selectedTypedCoreFiberPresentationComparisonApp
          (idTypedPresentation finitePortfolioSupportInstance)
          finitePaddedSupportIdentityPresentation
          (finiteCanonicalSupportIdentityPresentation_hom.trans
            finitePaddedSupportIdentityPresentation_hom.symm)
          finiteReindexFourAxisTarget).hom =
      finitePaddedSupportPresentationUnitorApp.hom :=
  selectedTypedCoreFiberPresentationUnitor_compatibility_app
    finitePortfolioSupportInstance
    (idTypedPresentation finitePortfolioSupportInstance)
    finitePaddedSupportIdentityPresentation
    finiteCanonicalSupportIdentityPresentation_hom
    finitePaddedSupportIdentityPresentation_hom finiteReindexFourAxisTarget

/-- The whole relative unitor is compatible with identity-presentation replacement. -/
theorem finiteSupportPresentationUnitor_compatibility :
    (selectedTypedCoreFiberPresentationUnitor
      finitePortfolioSupportInstance
      (idTypedPresentation finitePortfolioSupportInstance)
      finiteCanonicalSupportIdentityPresentation_hom).trans
        (selectedTypedCoreFiberPresentationComparison
          (idTypedPresentation finitePortfolioSupportInstance)
          finitePaddedSupportIdentityPresentation
          (finiteCanonicalSupportIdentityPresentation_hom.trans
            finitePaddedSupportIdentityPresentation_hom.symm)) =
      finitePaddedSupportPresentationUnitor :=
  selectedTypedCoreFiberPresentationUnitor_compatibility
    finitePortfolioSupportInstance
    (idTypedPresentation finitePortfolioSupportInstance)
    finitePaddedSupportIdentityPresentation
    finiteCanonicalSupportIdentityPresentation_hom
    finitePaddedSupportIdentityPresentation_hom

/-! ## Independent nondegeneracy controls -/

/-- The first leg of the fired selective compositor is independently noninvertible. -/
theorem finitePresentationDescentCompositorFirstLeg_not_isIso :
    ¬ IsIso
      (typedRealizableHom
        finiteSelectiveTwoToOnePresentation).semantic.hom :=
  finiteSelectiveTwoInput_not_isIso

/-- The selective leg retained by the presentation witness is noninvertible. -/
theorem finitePresentationDescentSelectiveLeg_not_isIso :
    ¬ IsIso
      (typedRealizableHom
        finiteSelectiveTwoToSupportPresentation).semantic.hom :=
  finiteSelectiveTwoToSupportInput_not_isIso

/-- The vertical map used below is a genuine nonidentity four-axis map. -/
theorem finitePresentationDescentAxisSwap_ne_id :
    finiteReindexAxisSwapHom ≠ 𝟙 finiteReindexFourAxisTarget :=
  finiteReindexAxisSwapHom_ne_id

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
