import ResearchLean.AG.DoctrineFiberProduct.FiniteGeneratedContextEquivalenceCompositionDescent

/-!
# Generated observable-equivalence composition descent

This module reflects the observable-family component of the actual normalized
high-factor triangle.  The proof first compares every generated observable in
the lifted target.  It transports the reflected actual value across its
generated context landing, applies the actual high upper factorization, and
then reflects the resulting equality through the canonical target lift.

No low factorization theorem, whole canonical-factor equality, caller context
certificate, or special property of the concrete coefficient ring is used.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory
open AtomFoundation

/-! ## Dependent cast computations -/

/--
An exact observable equivalence commutes with rewriting its source context.
This is the dependent cast used to move the reflected actual value from its
actual high endpoint to the generated-image endpoint.
-/
private theorem equationObservableEquiv_cast_source
    {U : AtomCarrier.{u}}
    {A₀ B₀ : ArchitectureObject U}
    {C : Site.ContextPreorderCategory A₀}
    {D : Site.ContextPreorderCategory B₀}
    {E : ArchitecturalEquationSystem C}
    {F : ArchitecturalEquationSystem D}
    {atomEquiv : U.Atom ≃ U.Atom}
    {objectMap : ArchitectureObject U → ArchitectureObject U}
    (transport : EquationSystemExactTransport E F atomEquiv objectMap)
    {first second : Site.ContextCategoryObject C}
    (context_eq : first = second)
    (value : E.Observable second) :
    transport.observableEquiv first
        (RingEquiv.cast (R := E.Observable) context_eq.symm value) =
      RingEquiv.cast
        (R := F.Observable)
        (congrArg (fun W => transport.contextForward W) context_eq).symm
        (transport.observableEquiv second value) := by
  cases context_eq
  rfl

/--
Successive dependent ring casts agree with the cast along the composite
endpoint equality.
-/
private theorem ringEquiv_cast_apply_trans
    {index : Type*} {R : index → Type*}
    [(i : index) → CommRing (R i)]
    {first middle last : index}
    (first_eq : first = middle) (second_eq : middle = last)
    (value : R first) :
    RingEquiv.cast (R := R) second_eq
        (RingEquiv.cast (R := R) first_eq value) =
      RingEquiv.cast (R := R) (first_eq.trans second_eq) value := by
  cases first_eq
  cases second_eq
  rfl

/--
The canonical finite-model observable lift commutes with simultaneous
rewriting of its low and high context endpoints.
-/
private theorem finiteModelTargetEquationObservableEquiv_cast
    {firstLow secondLow : Site.ContextCategoryObject
      FiniteModel.corePackage.algebra.contextPreorder}
    {firstHigh secondHigh : Site.ContextCategoryObject
      finiteModelLiftCorePackage.{u}.algebra.contextPreorder}
    (low_eq : firstLow = secondLow)
    (high_eq : firstHigh = secondHigh)
    (value : FiniteModel.corePackage.algebra.equationSystem.Observable firstLow) :
    finiteModelTargetEquationObservableEquiv.{u} secondLow secondHigh
        (RingEquiv.cast
          (R := FiniteModel.corePackage.algebra.equationSystem.Observable)
          low_eq value) =
      RingEquiv.cast
        (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
        high_eq
        (finiteModelTargetEquationObservableEquiv.{u}
          firstLow firstHigh value) := by
  cases low_eq
  cases high_eq
  rfl

/--
Equality of complete exact uppers gives the pointwise observable equality with
the target context cast generated by that same equality.  In particular, the
observable field cannot be replaced independently of the supplied upper
equality.
-/
private theorem signedExactCoreReadingHom_observableEquiv_apply_cast_of_eq
    {U : AtomCarrier.{u}} {P Q : AATCorePackage U}
    {first second : SignedExactCoreReadingHom P Q}
    (equality : first = second)
    (W : Site.ContextCategoryObject P.algebra.contextPreorder)
    (value : P.algebra.equationSystem.Observable W) :
    RingEquiv.cast
        (R := Q.algebra.equationSystem.Observable)
        (congrArg
          (fun upper : SignedExactCoreReadingHom P Q =>
            upper.equationTransport.contextForward W)
          equality)
        (first.equationTransport.observableEquiv W value) =
      second.equationTransport.observableEquiv W value := by
  cases equality
  rfl

/--
Pointwise observable equality after rewriting the context equivalence gives
heterogeneous equality of the complete dependent observable families.
-/
private theorem equationObservableEquiv_heq_of_context_eq
    {U : AtomCarrier.{u}}
    {A₀ B₀ : ArchitectureObject U}
    {C : Site.ContextPreorderCategory A₀}
    {D : Site.ContextPreorderCategory B₀}
    {E : ArchitecturalEquationSystem C}
    {F : ArchitecturalEquationSystem D}
    {firstAtomEquiv secondAtomEquiv : U.Atom ≃ U.Atom}
    {firstObjectMap secondObjectMap :
      ArchitectureObject U → ArchitectureObject U}
    (first : EquationSystemExactTransport E F
      firstAtomEquiv firstObjectMap)
    (second : EquationSystemExactTransport E F
      secondAtomEquiv secondObjectMap)
    (context_eq : first.contextEquivalence = second.contextEquivalence)
    (pointwise : ∀ W value,
      RingEquiv.cast
          (R := F.Observable)
          (congrArg
            (fun equivalence => equivalence.functor.obj W)
            context_eq)
          (first.observableEquiv W value) =
        second.observableEquiv W value) :
    HEq first.observableEquiv second.observableEquiv := by
  cases first
  cases second
  cases context_eq
  apply heq_of_eq
  funext W
  apply RingEquiv.ext
  intro value
  simpa using pointwise W value

/-! ## Actual-high observable composition -/

/--
Every reflected observable, followed through the inner generated high upper,
has the outer generated high observable image.  The target cast is generated
by the already-proved high context triangle, while the value equality directly
uses the actual normalized high upper factorization.
-/
theorem finiteGeneratedReflectedUpper_comp_observable_high_image
    (input : FiniteGeneratedLiftInput)
    (lift : StrongCartesianLift
      (FiniteGeneratedLiftInput.highInput.{u} input)
      (FiniteGeneratedLiftInput.highTarget.{u} input))
    {package : AATCorePackage FiniteModel.carrier}
    (base : packagePoint package ⟶ input.source)
    (W : Site.ContextCategoryObject
      ((finiteGeneratedOuterInput input base).lowGeneratedLift.domain.algebra.contextPreorder))
    (value : (finiteGeneratedOuterInput input base).lowGeneratedLift.domain.algebra.equationSystem.Observable W) :
    RingEquiv.cast
        (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
        (finiteGeneratedReflectedUpper_comp_contextForward_high_image
          input lift base W)
        (input.highGeneratedLift.hom.upper.equationTransport.observableEquiv
          ((finiteGeneratedContextImageFunctor.{u} input).obj
            (finiteGeneratedReflectedForwardObject input lift base W))
          (finiteGeneratedEquationObservableEquiv.{u} input
            (finiteGeneratedReflectedForwardObject input lift base W)
            (finiteGeneratedReflectedEquationObservableEquiv
              input lift base W value))) =
      ((finiteGeneratedOuterInput input base).highGeneratedLift.hom.upper).equationTransport.observableEquiv
          ((finiteGeneratedContextImageFunctor.{u}
            (finiteGeneratedOuterInput input base)).obj W)
          (finiteGeneratedEquationObservableEquiv.{u}
            (finiteGeneratedOuterInput input base) W value) := by
  let outer := finiteGeneratedOuterInput input base
  let reflected := finiteGeneratedReflectedForwardObject input lift base W
  let sourceImage := (finiteGeneratedContextImageFunctor.{u} outer).obj W
  let reflectedImage := (finiteGeneratedContextImageFunctor.{u} input).obj reflected
  let actualTarget :=
    (finiteGeneratedActualHighContextEquivalence input lift base).functor.obj
      sourceImage
  let highInput := input.highGeneratedLift.hom.upper.equationTransport
  let highOuter := outer.highGeneratedLift.hom.upper.equationTransport
  let actual :=
    (finiteGeneratedNormalizedHighFactor input lift base).upper.equationTransport
  let sourceLift := finiteGeneratedEquationObservableEquiv.{u} outer W value
  have hLanding : reflectedImage = actualTarget := by
    exact finiteGeneratedReflectedForwardObject_image_eq input lift base W
  have hInner : highInput.contextForward reflectedImage =
      highInput.contextForward actualTarget :=
    congrArg (fun context => highInput.contextForward context) hLanding
  have hHighImage : highInput.contextForward reflectedImage =
      highOuter.contextForward sourceImage := by
    exact finiteGeneratedReflectedUpper_comp_contextForward_high_image
      input lift base W
  have hTriangle : highInput.contextForward actualTarget =
      highOuter.contextForward sourceImage := by
    have equality := congrArg
      (fun equivalence => equivalence.functor.obj sourceImage)
      (finiteGeneratedNormalizedHighFactor_upper_fac_contextEquivalence
        input lift base)
    change highInput.contextForward actualTarget =
      highOuter.contextForward sourceImage at equality
    exact equality
  have hReflected :=
    finiteGeneratedReflectedEquationObservableEquiv_apply_high_image
      input lift base W value
  have hCastSource := equationObservableEquiv_cast_source highInput hLanding
    (actual.observableEquiv sourceImage sourceLift)
  change highInput.observableEquiv reflectedImage
      (finiteGeneratedReflectedEquationObservableTargetCast
        input lift base W
        (actual.observableEquiv sourceImage sourceLift)) =
    RingEquiv.cast
      (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
      hInner.symm
      (highInput.observableEquiv actualTarget
        (actual.observableEquiv sourceImage sourceLift)) at hCastSource
  have hActual :=
    signedExactCoreReadingHom_observableEquiv_apply_cast_of_eq
      (finiteGeneratedNormalizedHighFactor_upper_fac input lift base)
      sourceImage sourceLift
  change RingEquiv.cast
      (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
      hTriangle
      (highInput.observableEquiv actualTarget
        (actual.observableEquiv sourceImage sourceLift)) =
    highOuter.observableEquiv sourceImage sourceLift at hActual
  change RingEquiv.cast
      (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
      hHighImage
      (highInput.observableEquiv reflectedImage
        (finiteGeneratedEquationObservableEquiv.{u} input reflected
          (finiteGeneratedReflectedEquationObservableEquiv
            input lift base W value))) =
    highOuter.observableEquiv sourceImage sourceLift
  calc
    _ = RingEquiv.cast
        (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
        hHighImage
        (highInput.observableEquiv reflectedImage
          (finiteGeneratedReflectedEquationObservableTargetCast
            input lift base W
            (actual.observableEquiv sourceImage sourceLift))) := by
      exact congrArg
        (fun observable => RingEquiv.cast
          (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
          hHighImage
          (highInput.observableEquiv reflectedImage observable))
        hReflected
    _ = RingEquiv.cast
        (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
        hHighImage
        (RingEquiv.cast
          (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
          hInner.symm
          (highInput.observableEquiv actualTarget
            (actual.observableEquiv sourceImage sourceLift))) := by
      exact congrArg
        (fun observable => RingEquiv.cast
          (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
          hHighImage observable)
        hCastSource
    _ = RingEquiv.cast
        (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
        hTriangle
        (highInput.observableEquiv actualTarget
          (actual.observableEquiv sourceImage sourceLift)) := by
      rw [ringEquiv_cast_apply_trans]
    _ = highOuter.observableEquiv sourceImage sourceLift := hActual

/-! ## Low observable-family composition -/

/--
The observable-equivalence family of the reflected low upper followed by the
inner generated low upper is the outer generated low family.  The context
equality and both observable endpoint casts are generated internally, and the
only comparison of observable values is the actual high upper triangle.
-/
theorem finiteGeneratedReflectedUpper_comp_observableEquiv
    (input : FiniteGeneratedLiftInput)
    (lift : StrongCartesianLift
      (FiniteGeneratedLiftInput.highInput.{u} input)
      (FiniteGeneratedLiftInput.highTarget.{u} input))
    {package : AATCorePackage FiniteModel.carrier}
    (base : packagePoint package ⟶ input.source) :
    HEq
      (((finiteGeneratedReflectedSignedExactCoreReadingHom input lift base).comp
        input.lowGeneratedLift.hom.upper).equationTransport.observableEquiv)
      (((finiteGeneratedOuterInput input base).lowGeneratedLift.hom.upper).equationTransport.observableEquiv) := by
  let outer := finiteGeneratedOuterInput input base
  let first :=
    ((finiteGeneratedReflectedSignedExactCoreReadingHom input lift base).comp
      input.lowGeneratedLift.hom.upper).equationTransport
  let second := outer.lowGeneratedLift.hom.upper.equationTransport
  have hContext : first.contextEquivalence = second.contextEquivalence := by
    exact finiteGeneratedReflectedUpper_comp_contextEquivalence
      input lift base
  apply equationObservableEquiv_heq_of_context_eq first second hContext
  intro W value
  let reflected := finiteGeneratedReflectedForwardObject input lift base W
  let firstLowTarget := first.contextForward W
  let secondLowTarget := second.contextForward W
  let firstHighTarget :=
    input.highGeneratedLift.hom.upper.equationTransport.contextForward
      ((finiteGeneratedContextImageFunctor.{u} input).obj reflected)
  let secondHighTarget :=
    outer.highGeneratedLift.hom.upper.equationTransport.contextForward
      ((finiteGeneratedContextImageFunctor.{u} outer).obj W)
  have hLow : firstLowTarget = secondLowTarget := by
    exact congrArg (fun equivalence => equivalence.functor.obj W) hContext
  have hHigh : firstHighTarget = secondHighTarget := by
    exact finiteGeneratedReflectedUpper_comp_contextForward_high_image
      input lift base W
  let targetLift := finiteModelTargetEquationObservableEquiv.{u}
    secondLowTarget secondHighTarget
  apply targetLift.injective
  calc
    targetLift
        (RingEquiv.cast
          (R := FiniteModel.corePackage.algebra.equationSystem.Observable)
          hLow
          (first.observableEquiv W value)) =
      RingEquiv.cast
        (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
        hHigh
        (finiteModelTargetEquationObservableEquiv.{u}
          firstLowTarget firstHighTarget
          (first.observableEquiv W value)) :=
      finiteModelTargetEquationObservableEquiv_cast hLow hHigh _
    _ = RingEquiv.cast
        (R := finiteModelLiftCorePackage.{u}.algebra.equationSystem.Observable)
        hHigh
        (input.highGeneratedLift.hom.upper.equationTransport.observableEquiv
          ((finiteGeneratedContextImageFunctor.{u} input).obj reflected)
          (finiteGeneratedEquationObservableEquiv.{u} input reflected
            (finiteGeneratedReflectedEquationObservableEquiv
              input lift base W value))) := by
      apply congrArg
      simpa only [input.highGeneratedLift_hom_eq_highPackageHomFromLowData] using
        (finiteGeneratedEquationObservableEquiv_forward_image
          input reflected
          (finiteGeneratedReflectedEquationObservableEquiv
            input lift base W value)).symm
    _ = outer.highGeneratedLift.hom.upper.equationTransport.observableEquiv
        ((finiteGeneratedContextImageFunctor.{u} outer).obj W)
        (finiteGeneratedEquationObservableEquiv.{u} outer W value) :=
      finiteGeneratedReflectedUpper_comp_observable_high_image
        input lift base W value
    _ = targetLift (second.observableEquiv W value) := by
      simpa only [outer.highGeneratedLift_hom_eq_highPackageHomFromLowData] using
        (finiteGeneratedEquationObservableEquiv_forward_image
          outer W value)

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
