import ResearchLean.AG.AtomFoundation.Categories
import ResearchLean.AG.DoctrineFiberProduct.DoctrinePullback

/-!
# Pointed pullbacks of exact extraction doctrines

This module lifts the arbitrary doctrine pullback to the pointed category
`ExtInst_U`.  A pointed cospan already contains the compatible point cone: its
three selected sources and the two `ExtInstHom.source_eq` fields generate the
selected source of the pullback.  No pullback object, universal factor, or
`IsPullback` certificate is supplied by the caller.

The universal factor is obtained from the explicit doctrine-level factor of
`DoctrinePullback`.  Its pointed source equation is then generated from the
two source equations of the arbitrary pointed cone.  In particular, the
factor retains the cone's actual Atom equivalence.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u

open CategoryTheory CategoryTheory.Limits
open AtomFoundation

/-- The compatible source pair generated by a pointed exact-doctrine cospan. -/
def pointedPullbackSource
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base) :
    DoctrinePullbackSource sigmaOne.doctrineHom sigmaTwo.doctrineHom :=
  ⟨(DOne.source, DTwo.source),
    sigmaOne.source_eq.trans sigmaTwo.source_eq.symm⟩

/-- The doctrine pullback equipped with the internally generated compatible point. -/
def pointedPullback
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base) :
    ExtractionInstance U where
  doctrine := doctrinePullback sigmaOne.doctrineHom sigmaTwo.doctrineHom
  source := pointedPullbackSource sigmaOne sigmaTwo

/-- First pointed projection from the generated pullback. -/
def pointedPullbackFst
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base) :
    pointedPullback sigmaOne sigmaTwo ⟶ DOne where
  doctrineHom := doctrinePullbackFst sigmaOne.doctrineHom sigmaTwo.doctrineHom
  source_eq := rfl

/-- Second pointed projection from the generated pullback. -/
def pointedPullbackSnd
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base) :
    pointedPullback sigmaOne sigmaTwo ⟶ DTwo where
  doctrineHom := doctrinePullbackSnd sigmaOne.doctrineHom sigmaTwo.doctrineHom
  source_eq := rfl

/-- The two pointed projections commute over the input cospan. -/
theorem pointedPullback_commutes
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base) :
    pointedPullbackFst sigmaOne sigmaTwo ≫ sigmaOne =
      pointedPullbackSnd sigmaOne sigmaTwo ≫ sigmaTwo := by
  apply ExtInstHom.ext
  exact doctrinePullback_commutes sigmaOne.doctrineHom sigmaTwo.doctrineHom

/-- The underlying doctrine cone of an arbitrary pointed pullback cone. -/
private def pointedConeToDoctrineCone
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base)
    (cone : PullbackCone sigmaOne sigmaTwo) :
    PullbackCone (C := ExtractionDoctrine U)
      (sigmaOne.doctrineHom) (sigmaTwo.doctrineHom) :=
  PullbackCone.mk cone.fst.doctrineHom cone.snd.doctrineHom <| by
    exact congrArg (fun hom => hom.doctrineHom) cone.condition

/-- Universal pointed factor from an arbitrary pointed cone. -/
def pointedPullbackLift
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base)
    (cone : PullbackCone sigmaOne sigmaTwo) :
    cone.pt ⟶ pointedPullback sigmaOne sigmaTwo where
  doctrineHom := doctrinePullbackLift sigmaOne.doctrineHom sigmaTwo.doctrineHom
    (pointedConeToDoctrineCone sigmaOne sigmaTwo cone)
  source_eq := by
    apply Subtype.ext
    apply Prod.ext
    · exact cone.fst.source_eq
    · exact cone.snd.source_eq

/-- The pointed universal factor preserves the first cone leg's Atom equivalence. -/
@[simp]
theorem pointedPullbackLift_atomEquiv
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base)
    (cone : PullbackCone sigmaOne sigmaTwo) :
    (pointedPullbackLift sigmaOne sigmaTwo cone).doctrineHom.atomEquiv =
      cone.fst.doctrineHom.atomEquiv :=
  rfl

/-- The pointed universal factor recovers the first cone leg. -/
theorem pointedPullbackLift_fst
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base)
    (cone : PullbackCone sigmaOne sigmaTwo) :
    pointedPullbackLift sigmaOne sigmaTwo cone ≫
        pointedPullbackFst sigmaOne sigmaTwo =
      cone.fst := by
  apply ExtInstHom.ext
  exact doctrinePullbackLift_fst sigmaOne.doctrineHom sigmaTwo.doctrineHom
    (pointedConeToDoctrineCone sigmaOne sigmaTwo cone)

/-- The pointed universal factor recovers the second cone leg. -/
theorem pointedPullbackLift_snd
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base)
    (cone : PullbackCone sigmaOne sigmaTwo) :
    pointedPullbackLift sigmaOne sigmaTwo cone ≫
        pointedPullbackSnd sigmaOne sigmaTwo =
      cone.snd := by
  apply ExtInstHom.ext
  exact doctrinePullbackLift_snd sigmaOne.doctrineHom sigmaTwo.doctrineHom
    (pointedConeToDoctrineCone sigmaOne sigmaTwo cone)

/-- Every pointed factor satisfying both projection equations is the generated factor. -/
theorem pointedPullbackLift_unique
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base)
    (cone : PullbackCone sigmaOne sigmaTwo)
    (candidate : cone.pt ⟶ pointedPullback sigmaOne sigmaTwo)
    (hfst : candidate ≫ pointedPullbackFst sigmaOne sigmaTwo = cone.fst)
    (hsnd : candidate ≫ pointedPullbackSnd sigmaOne sigmaTwo = cone.snd) :
    candidate = pointedPullbackLift sigmaOne sigmaTwo cone := by
  apply ExtInstHom.ext
  apply doctrinePullbackLift_unique sigmaOne.doctrineHom sigmaTwo.doctrineHom
    (pointedConeToDoctrineCone sigmaOne sigmaTwo cone) candidate.doctrineHom
  · exact congrArg (fun hom => hom.doctrineHom) hfst
  · exact congrArg (fun hom => hom.doctrineHom) hsnd

/-- Every pointed exact-doctrine cospan has the generated pullback in `ExtInst_U`. -/
theorem pointedPullback_isPullback
    {U : AtomCarrier.{u}} {DOne DTwo Base : ExtractionInstance U}
    (sigmaOne : DOne ⟶ Base) (sigmaTwo : DTwo ⟶ Base) :
    IsPullback
      (pointedPullbackFst sigmaOne sigmaTwo)
      (pointedPullbackSnd sigmaOne sigmaTwo)
      sigmaOne sigmaTwo := by
  apply IsPullback.of_isLimit'
    ⟨pointedPullback_commutes sigmaOne sigmaTwo⟩
  refine PullbackCone.IsLimit.mk _
    (fun cone => pointedPullbackLift sigmaOne sigmaTwo cone) ?_ ?_ ?_
  · intro cone
    exact pointedPullbackLift_fst sigmaOne sigmaTwo cone
  · intro cone
    exact pointedPullbackLift_snd sigmaOne sigmaTwo cone
  · intro cone candidate hfst hsnd
    exact pointedPullbackLift_unique sigmaOne sigmaTwo cone candidate hfst hsnd

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
