import ResearchLean.AG.DoctrineFiberProduct.UpperGeometryCanonicalAuthoredPairedRestrictedPoint

/-!
# Cochain and paired-suborbit transport for witness-bearing restricted points

Endpoint conjugation is lifted coordinatewise to the full dependent raw
cochain groups.  The cochain square then commutes with the restricted-point
equivalence.  Paired suborbit membership is derived from the transported
shared witness, rather than used as a surrogate for witness correspondence.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u v

open CategoryTheory AtomFoundation GeometryTransport CrossStageCoherence
open TransportCoherence

namespace UpperGeometryCompatibleProblemInputData

/-- Coordinatewise exact endpoint conjugation on base-route raw cochains. -/
noncomputable def canonicalAuthoredGeneratedBaseUpperDefectCochainMulEquiv
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k) :
    UpperDefectCochain input.canonicalAuthoredBaseRouteData ≃*
      UpperDefectCochain input.generatedBaseRouteData :=
  MulEquiv.piCongrRight fun cell =>
    CompositeFiberAut.conjugationMulEquiv
      (input.canonicalAuthoredBaseToGeneratedRouteExactGeometryIsoAt
        (P.twoTarget cell))

/-- Coordinatewise exact endpoint conjugation on pulled-route raw cochains. -/
noncomputable def canonicalAuthoredGeneratedPulledUpperDefectCochainMulEquiv
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k) :
    UpperDefectCochain input.canonicalAuthoredPulledRouteData ≃*
      UpperDefectCochain input.generatedPulledRouteData :=
  MulEquiv.piCongrRight fun cell =>
    CompositeFiberAut.conjugationMulEquiv
      (input.canonicalAuthoredPulledToGeneratedRouteExactGeometryIsoAt
        (P.twoTarget cell))

/-- The base raw-cochain projection commutes with the complete restricted
point transport as an equality of dependent cochain functions. -/
theorem canonicalAuthoredPairedRestrictedPoint_baseCochain_forward_eq
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    (point : CanonicalAuthoredPairedRestrictedPoint input) :
    input.canonicalAuthoredGeneratedBaseUpperDefectCochainMulEquiv
        point.baseCochain =
      (input.canonicalAuthoredPairedRestrictedPointForward point).baseCochain := by
  funext cell
  exact input.canonicalAuthoredPairedRestrictedPoint_baseCochain_forward
    point cell

/-- The pulled raw-cochain projection commutes with the complete restricted
point transport as an equality of dependent cochain functions. -/
theorem canonicalAuthoredPairedRestrictedPoint_pulledCochain_forward_eq
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    (point : CanonicalAuthoredPairedRestrictedPoint input) :
    input.canonicalAuthoredGeneratedPulledUpperDefectCochainMulEquiv
        point.pulledCochain =
      (input.canonicalAuthoredPairedRestrictedPointForward point).pulledCochain := by
  funext cell
  exact input.canonicalAuthoredPairedRestrictedPoint_pulledCochain_forward
    point cell

/-- Every generated restricted point lies in the existing paired actual
suborbit at the two raw cochains generated by its retained witnesses. -/
theorem GeneratedPairedRestrictedPoint.mem_pairedRestrictedOrbit
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    {input : UpperGeometryCompatibleProblemInputData ctx P k}
    (point : GeneratedPairedRestrictedPoint input) :
    InPairedCoefficientTrivialUpperReselectionOrbit point.solution
      point.baseCochain point.pulledCochain := by
  exact point.paired.mem_pairedRestrictedOrbit

/-- Transporting one canonical restricted point carries its two cochains into
the existing paired generated suborbit using that same transported witness. -/
theorem CanonicalAuthoredPairedRestrictedPoint.forward_mem_pairedRestrictedOrbit
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    {input : UpperGeometryCompatibleProblemInputData ctx P k}
    (point : CanonicalAuthoredPairedRestrictedPoint input) :
    InPairedCoefficientTrivialUpperReselectionOrbit
      (input.canonicalAuthoredPairedRestrictedPointForward point).solution
      (input.canonicalAuthoredGeneratedBaseUpperDefectCochainMulEquiv
        point.baseCochain)
      (input.canonicalAuthoredGeneratedPulledUpperDefectCochainMulEquiv
        point.pulledCochain) := by
  rw [input.canonicalAuthoredPairedRestrictedPoint_baseCochain_forward_eq,
    input.canonicalAuthoredPairedRestrictedPoint_pulledCochain_forward_eq]
  exact (input.canonicalAuthoredPairedRestrictedPointForward point).mem_pairedRestrictedOrbit

end UpperGeometryCompatibleProblemInputData

namespace UpperDecisionWitness

/-- The named generated solution and comparator reselections form one actual
witness-bearing restricted point. -/
noncomputable def generatedComparatorPairedRestrictedPoint :
    UpperGeometryCompatibleProblemInputData.GeneratedPairedRestrictedPoint
      problem.data where
  solution := solution
  base := generatedBaseComparatorCoefficientTrivialUpperReselection
  pulled := generatedPulledComparatorCoefficientTrivialUpperReselection
  paired := generatedComparatorUpperReselections_paired_fires

/-- The named canonical companion solution and its two backward-transported
reselections form the corresponding canonical-authored restricted point. -/
noncomputable def canonicalCompanionComparatorPairedRestrictedPoint :
    UpperGeometryCompatibleProblemInputData.CanonicalAuthoredPairedRestrictedPoint
      problem.data where
  solution := problem.data.canonicalCompanionUpperRefinementBCSolution
  base := canonicalCompanionBaseComparatorCoefficientTrivialUpperReselection
  pulled := canonicalCompanionPulledComparatorCoefficientTrivialUpperReselection
  paired := canonicalCompanionComparatorUpperReselections_paired_fires

/-- The complete restricted-point equivalence sends the named canonical
companion point to the named generated point. -/
theorem canonicalCompanionComparatorPairedRestrictedPoint_forward :
    problem.data.canonicalAuthoredPairedRestrictedPointForward
        canonicalCompanionComparatorPairedRestrictedPoint =
      generatedComparatorPairedRestrictedPoint := by
  change
    problem.data.canonicalAuthoredPairedRestrictedPointForward
        (problem.data.canonicalAuthoredPairedRestrictedPointBackward
          generatedComparatorPairedRestrictedPoint) =
      generatedComparatorPairedRestrictedPoint
  exact problem.data.canonicalAuthoredPairedRestrictedPointForward_backward
    generatedComparatorPairedRestrictedPoint

/-- The named base companion raw cochain agrees, coordinatewise under exact
endpoint conjugation, with the named generated base raw cochain. -/
theorem canonicalCompanionComparatorPairedRestrictedPoint_baseCochain_forward
    (cell : presentation.TwoCell) :
    problem.data.canonicalAuthoredBaseCompositeFiberAutForwardAt
        (presentation.twoTarget cell)
        (canonicalCompanionComparatorPairedRestrictedPoint.baseCochain cell) =
      generatedComparatorPairedRestrictedPoint.baseCochain cell := by
  rw [← canonicalCompanionComparatorPairedRestrictedPoint_forward]
  exact problem.data.canonicalAuthoredPairedRestrictedPoint_baseCochain_forward
    canonicalCompanionComparatorPairedRestrictedPoint cell

/-- The named pulled companion raw cochain agrees, coordinatewise under exact
endpoint conjugation, with the named generated pulled raw cochain. -/
theorem canonicalCompanionComparatorPairedRestrictedPoint_pulledCochain_forward
    (cell : presentation.TwoCell) :
    problem.data.canonicalAuthoredPulledCompositeFiberAutForwardAt
        (presentation.twoTarget cell)
        (canonicalCompanionComparatorPairedRestrictedPoint.pulledCochain cell) =
      generatedComparatorPairedRestrictedPoint.pulledCochain cell := by
  rw [← canonicalCompanionComparatorPairedRestrictedPoint_forward]
  exact problem.data.canonicalAuthoredPairedRestrictedPoint_pulledCochain_forward
    canonicalCompanionComparatorPairedRestrictedPoint cell

/-- The named canonical companion cochain pair lands in the existing paired
generated suborbit through the transported same-witness restricted point. -/
theorem canonicalCompanionComparatorPairedRestrictedPoint_forward_mem :
    UpperGeometryCompatibleProblemInputData.InPairedCoefficientTrivialUpperReselectionOrbit
      generatedComparatorPairedRestrictedPoint.solution
      (problem.data.canonicalAuthoredGeneratedBaseUpperDefectCochainMulEquiv
        canonicalCompanionComparatorPairedRestrictedPoint.baseCochain)
      (problem.data.canonicalAuthoredGeneratedPulledUpperDefectCochainMulEquiv
        canonicalCompanionComparatorPairedRestrictedPoint.pulledCochain) := by
  simpa only [canonicalCompanionComparatorPairedRestrictedPoint_forward] using
    canonicalCompanionComparatorPairedRestrictedPoint.forward_mem_pairedRestrictedOrbit

end UpperDecisionWitness

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
