import ResearchLean.AG.DoctrineFiberProduct.UpperGeometryCompatibleRouteCoreEdges

/-!
# Generated complete route geometry edges

The exact core edges from the preceding compatible checkpoint are lifted
through the theorem-generated strongly Cartesian route legs.  Exactification
then recovers complete geometry edges for both routes.  Each edge satisfies
the literal factor graph against the authored source transport edge; no route
edge or Cartesian qualification is accepted from the caller.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u v

open CategoryTheory AtomFoundation GeometryTransport CrossStageCoherence
open TransportCoherence

set_option maxHeartbeats 3000000

namespace UpperGeometryCompatibleProblemInputData

/-- Cartesian factor of an authored source edge through the generated base
route, before exactification. -/
noncomputable def generatedBaseRouteRefinementGeometryEdge
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    RefinementGeometryHom (input.generatedBaseRouteGeometryAt i)
      (input.generatedBaseRouteGeometryAt j) := by
  letI := input.generatedBaseRouteLegAt_isStronglyCartesian j
  let candidate := RefinementGeometryHom.comp
    (input.generatedBaseRouteLegAt i)
    ((exactGeometryToRefinementGeometry U).map
      (input.sourceTransport.edgeLift edge))
  letI := UpperGeometryCleavage.refinementGeometryHom_isHomLift candidate
  exact CategoryTheory.Functor.IsStronglyCartesian.map
    (refinementGeometryProjection U)
    (input.generatedBaseRouteLegAt j).base
    (input.generatedBaseRouteLegAt j)
    (g := (exactPackageToRefinement U).map
      (input.generatedBaseRouteCoreDiagram.map
        (presentedEdgePath edge)).1)
    (f' := candidate.base)
    (input.generatedBaseRouteCoreEdge_fac edge).symm candidate

/-- The base-route Cartesian factor lies over the exact generated core edge. -/
theorem generatedBaseRouteRefinementGeometryEdge_base
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    (input.generatedBaseRouteRefinementGeometryEdge edge).base =
      (exactPackageToRefinement U).map
        (input.generatedBaseRouteCoreDiagram.map
          (presentedEdgePath edge)).1 := by
  letI := input.generatedBaseRouteLegAt_isStronglyCartesian j
  let candidate := RefinementGeometryHom.comp
    (input.generatedBaseRouteLegAt i)
    ((exactGeometryToRefinementGeometry U).map
      (input.sourceTransport.edgeLift edge))
  letI : (refinementGeometryProjection U).IsHomLift
      ((input.generatedBaseRouteLegAt i).base ≫
        (exactPackageToRefinement U).map
          (input.sourceTransport.edgeLift edge).base) candidate := by
    apply CategoryTheory.IsHomLift.of_fac'
      (refinementGeometryProjection U) _ candidate rfl rfl
    rfl
  unfold generatedBaseRouteRefinementGeometryEdge
  exact (CategoryTheory.IsHomLift.eq_of_isHomLift
    (refinementGeometryProjection U)
    ((exactPackageToRefinement U).map
      (input.generatedBaseRouteCoreDiagram.map
        (presentedEdgePath edge)).1)
    (CategoryTheory.Functor.IsStronglyCartesian.map
      (refinementGeometryProjection U)
      (input.generatedBaseRouteLegAt j).base
      (input.generatedBaseRouteLegAt j)
      (input.generatedBaseRouteCoreEdge_fac edge).symm candidate)).symm

/-- Exact complete base-route geometry edge generated by the Cartesian
factorization. -/
noncomputable def generatedBaseRouteGeometryEdge
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    GeometryTotalHom (input.generatedBaseRouteGeometryAt i)
      (input.generatedBaseRouteGeometryAt j) :=
  UpperGeometryCleavage.exactGeometryHomOfRefinement
    (input.generatedBaseRouteCoreDiagram.map
      (presentedEdgePath edge)).1
    (input.generatedBaseRouteRefinementGeometryEdge edge)
    (input.generatedBaseRouteRefinementGeometryEdge_base edge)

/-- The generated complete base-route edge has the exact Cycle 34 lower map. -/
@[simp] theorem generatedBaseRouteGeometryEdge_base
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    (input.generatedBaseRouteGeometryEdge edge).base =
      (input.generatedBaseRouteCoreDiagram.map
        (presentedEdgePath edge)).1 := rfl

/-- Refinement embedding recovers the universal base-route geometry factor. -/
theorem generatedBaseRouteGeometryEdge_toRefinement
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    (exactGeometryToRefinementGeometry U).map
        (input.generatedBaseRouteGeometryEdge edge) =
      input.generatedBaseRouteRefinementGeometryEdge edge := by
  exact UpperGeometryCleavage.exactGeometryHomOfRefinement_toRefinement
    (input.generatedBaseRouteCoreDiagram.map
      (presentedEdgePath edge)).1
    (input.generatedBaseRouteRefinementGeometryEdge edge)
    (input.generatedBaseRouteRefinementGeometryEdge_base edge)

/-- The exact base-route edge satisfies complete geometry naturality against
the authored source edge. -/
theorem generatedBaseRouteGeometryEdge_fac
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    RefinementGeometryHom.comp
        ((exactGeometryToRefinementGeometry U).map
          (input.generatedBaseRouteGeometryEdge edge))
        (input.generatedBaseRouteLegAt j) =
      RefinementGeometryHom.comp
        (input.generatedBaseRouteLegAt i)
        ((exactGeometryToRefinementGeometry U).map
          (input.sourceTransport.edgeLift edge)) := by
  rw [input.generatedBaseRouteGeometryEdge_toRefinement edge]
  unfold generatedBaseRouteRefinementGeometryEdge
  letI := input.generatedBaseRouteLegAt_isStronglyCartesian j
  let candidate := RefinementGeometryHom.comp
    (input.generatedBaseRouteLegAt i)
    ((exactGeometryToRefinementGeometry U).map
      (input.sourceTransport.edgeLift edge))
  letI : (refinementGeometryProjection U).IsHomLift
      ((input.generatedBaseRouteLegAt i).base ≫
        (exactPackageToRefinement U).map
          (input.sourceTransport.edgeLift edge).base) candidate := by
    apply CategoryTheory.IsHomLift.of_fac'
      (refinementGeometryProjection U) _ candidate rfl rfl
    rfl
  exact CategoryTheory.Functor.IsStronglyCartesian.fac
    (refinementGeometryProjection U)
    (input.generatedBaseRouteLegAt j).base
    (input.generatedBaseRouteLegAt j)
    (input.generatedBaseRouteCoreEdge_fac edge).symm
    candidate

/-- Cartesian factor of the same authored source edge through the generated
pulled route, before exactification. -/
noncomputable def generatedPulledRouteRefinementGeometryEdge
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    RefinementGeometryHom (input.generatedPulledRouteGeometryAt i)
      (input.generatedPulledRouteGeometryAt j) := by
  letI := input.generatedPulledRouteLegAt_isStronglyCartesian j
  let candidate := RefinementGeometryHom.comp
    (input.generatedPulledRouteLegAt i)
    ((exactGeometryToRefinementGeometry U).map
      (input.sourceTransport.edgeLift edge))
  letI := UpperGeometryCleavage.refinementGeometryHom_isHomLift candidate
  exact CategoryTheory.Functor.IsStronglyCartesian.map
    (refinementGeometryProjection U)
    (input.generatedPulledRouteLegAt j).base
    (input.generatedPulledRouteLegAt j)
    (g := (exactPackageToRefinement U).map
      (input.generatedPulledRouteCoreDiagram.map
        (presentedEdgePath edge)).1)
    (f' := candidate.base)
    (input.generatedPulledRouteCoreEdge_fac edge).symm candidate

/-- The pulled-route Cartesian factor lies over the exact generated core edge. -/
theorem generatedPulledRouteRefinementGeometryEdge_base
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    (input.generatedPulledRouteRefinementGeometryEdge edge).base =
      (exactPackageToRefinement U).map
        (input.generatedPulledRouteCoreDiagram.map
          (presentedEdgePath edge)).1 := by
  letI := input.generatedPulledRouteLegAt_isStronglyCartesian j
  let candidate := RefinementGeometryHom.comp
    (input.generatedPulledRouteLegAt i)
    ((exactGeometryToRefinementGeometry U).map
      (input.sourceTransport.edgeLift edge))
  letI : (refinementGeometryProjection U).IsHomLift
      ((input.generatedPulledRouteLegAt i).base ≫
        (exactPackageToRefinement U).map
          (input.sourceTransport.edgeLift edge).base) candidate := by
    apply CategoryTheory.IsHomLift.of_fac'
      (refinementGeometryProjection U) _ candidate rfl rfl
    rfl
  unfold generatedPulledRouteRefinementGeometryEdge
  exact (CategoryTheory.IsHomLift.eq_of_isHomLift
    (refinementGeometryProjection U)
    ((exactPackageToRefinement U).map
      (input.generatedPulledRouteCoreDiagram.map
        (presentedEdgePath edge)).1)
    (CategoryTheory.Functor.IsStronglyCartesian.map
      (refinementGeometryProjection U)
      (input.generatedPulledRouteLegAt j).base
      (input.generatedPulledRouteLegAt j)
      (input.generatedPulledRouteCoreEdge_fac edge).symm candidate)).symm

/-- Exact complete pulled-route geometry edge generated by the Cartesian
factorization. -/
noncomputable def generatedPulledRouteGeometryEdge
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    GeometryTotalHom (input.generatedPulledRouteGeometryAt i)
      (input.generatedPulledRouteGeometryAt j) :=
  UpperGeometryCleavage.exactGeometryHomOfRefinement
    (input.generatedPulledRouteCoreDiagram.map
      (presentedEdgePath edge)).1
    (input.generatedPulledRouteRefinementGeometryEdge edge)
    (input.generatedPulledRouteRefinementGeometryEdge_base edge)

/-- The generated complete pulled-route edge has the exact Cycle 34 lower map. -/
@[simp] theorem generatedPulledRouteGeometryEdge_base
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    (input.generatedPulledRouteGeometryEdge edge).base =
      (input.generatedPulledRouteCoreDiagram.map
        (presentedEdgePath edge)).1 := rfl

/-- Refinement embedding recovers the universal pulled-route geometry factor. -/
theorem generatedPulledRouteGeometryEdge_toRefinement
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    (exactGeometryToRefinementGeometry U).map
        (input.generatedPulledRouteGeometryEdge edge) =
      input.generatedPulledRouteRefinementGeometryEdge edge := by
  exact UpperGeometryCleavage.exactGeometryHomOfRefinement_toRefinement
    (input.generatedPulledRouteCoreDiagram.map
      (presentedEdgePath edge)).1
    (input.generatedPulledRouteRefinementGeometryEdge edge)
    (input.generatedPulledRouteRefinementGeometryEdge_base edge)

/-- The exact pulled-route edge satisfies complete geometry naturality against
the same authored source edge. -/
theorem generatedPulledRouteGeometryEdge_fac
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    (input : UpperGeometryCompatibleProblemInputData ctx P k)
    {i j : P.Vertex} (edge : P.Edge i j) :
    RefinementGeometryHom.comp
        ((exactGeometryToRefinementGeometry U).map
          (input.generatedPulledRouteGeometryEdge edge))
        (input.generatedPulledRouteLegAt j) =
      RefinementGeometryHom.comp
        (input.generatedPulledRouteLegAt i)
        ((exactGeometryToRefinementGeometry U).map
          (input.sourceTransport.edgeLift edge)) := by
  rw [input.generatedPulledRouteGeometryEdge_toRefinement edge]
  unfold generatedPulledRouteRefinementGeometryEdge
  letI := input.generatedPulledRouteLegAt_isStronglyCartesian j
  let candidate := RefinementGeometryHom.comp
    (input.generatedPulledRouteLegAt i)
    ((exactGeometryToRefinementGeometry U).map
      (input.sourceTransport.edgeLift edge))
  letI : (refinementGeometryProjection U).IsHomLift
      ((input.generatedPulledRouteLegAt i).base ≫
        (exactPackageToRefinement U).map
          (input.sourceTransport.edgeLift edge).base) candidate := by
    apply CategoryTheory.IsHomLift.of_fac'
      (refinementGeometryProjection U) _ candidate rfl rfl
    rfl
  exact CategoryTheory.Functor.IsStronglyCartesian.fac
    (refinementGeometryProjection U)
    (input.generatedPulledRouteLegAt j).base
    (input.generatedPulledRouteLegAt j)
    (input.generatedPulledRouteCoreEdge_fac edge).symm
    candidate

end UpperGeometryCompatibleProblemInputData

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
