import ResearchLean.AG.DoctrineFiberProduct.UpperGeometryFullPairedReselection

/-!
# Paired coefficient-trivial restricted upper-reselection orbit for G-115

This module defines the paired restricted-suborbit representation required by
G-115 revision 8 clause (c).  Membership retains one base reselection and one
pulled reselection satisfying the full paired relation, together with the
equalities identifying the two requested cochains with the actual
`upperRawDefectCochain`s generated by those same witnesses.

The full paired relation itself does not store a raw-cochain equality.  The
intertwining and coefficient conclusions below are derived by unpacking the
single shared pair; membership is not reconstructed from two independent
one-sided orbit certificates.
-/

namespace AAT.AG.DoctrineFiberProduct

universe u v

open CategoryTheory AtomFoundation GeometryTransport CrossStageCoherence
open TransportCoherence

namespace UpperGeometryCompatibleProblemInputData

/-- Two actual generated raw cochains lie in the paired coefficient-trivial
restricted orbit when one shared full paired reselection generates both. -/
def InPairedCoefficientTrivialUpperReselectionOrbit
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    {input : UpperGeometryCompatibleProblemInputData ctx P k}
    (solution : GeometryCompatibleUpperRefinementBCSolution input)
    (baseCochain : UpperDefectCochain input.generatedBaseRouteData)
    (pulledCochain : UpperDefectCochain input.generatedPulledRouteData) : Prop :=
  ∃ (base : GeneratedBaseCoefficientTrivialUpperEdgeReselection input)
      (pulled : GeneratedPulledCoefficientTrivialUpperEdgeReselection input),
    PairedCoefficientTrivialUpperReselection solution base pulled ∧
    upperRawDefectCochain input.generatedBaseRouteData
        base.toUpperEdgeReselection = baseCochain ∧
    upperRawDefectCochain input.generatedPulledRouteData
        pulled.toUpperEdgeReselection = pulledCochain

/-- Paired restricted-orbit membership yields base restricted-orbit membership
using the base half of the same paired witness. -/
theorem InPairedCoefficientTrivialUpperReselectionOrbit.base_mem
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    {input : UpperGeometryCompatibleProblemInputData ctx P k}
    {solution : GeometryCompatibleUpperRefinementBCSolution input}
    {baseCochain : UpperDefectCochain input.generatedBaseRouteData}
    {pulledCochain : UpperDefectCochain input.generatedPulledRouteData}
    (membership : InPairedCoefficientTrivialUpperReselectionOrbit solution
      baseCochain pulledCochain) :
    InCoefficientTrivialUpperReselectionOrbit
      input.generatedBaseRouteTransport baseCochain := by
  rcases membership with ⟨base, pulled, paired, baseEquality, pulledEquality⟩
  exact ⟨base, baseEquality⟩

/-- Paired restricted-orbit membership yields pulled restricted-orbit
membership using the pulled half of the same paired witness. -/
theorem InPairedCoefficientTrivialUpperReselectionOrbit.pulled_mem
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    {input : UpperGeometryCompatibleProblemInputData ctx P k}
    {solution : GeometryCompatibleUpperRefinementBCSolution input}
    {baseCochain : UpperDefectCochain input.generatedBaseRouteData}
    {pulledCochain : UpperDefectCochain input.generatedPulledRouteData}
    (membership : InPairedCoefficientTrivialUpperReselectionOrbit solution
      baseCochain pulledCochain) :
    InCoefficientTrivialUpperReselectionOrbit
      input.generatedPulledRouteTransport pulledCochain := by
  rcases membership with ⟨base, pulled, paired, baseEquality, pulledEquality⟩
  exact ⟨pulled, pulledEquality⟩

/-- The two cochains represented by one paired restricted-orbit witness
intertwine with the actual solution component at every authored two-cell. -/
theorem InPairedCoefficientTrivialUpperReselectionOrbit.cochain_intertwining
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    {input : UpperGeometryCompatibleProblemInputData ctx P k}
    {solution : GeometryCompatibleUpperRefinementBCSolution input}
    {baseCochain : UpperDefectCochain input.generatedBaseRouteData}
    {pulledCochain : UpperDefectCochain input.generatedPulledRouteData}
    (membership : InPairedCoefficientTrivialUpperReselectionOrbit solution
      baseCochain pulledCochain)
    (cell : P.TwoCell) :
    (CompositeFiberAut.hom (baseCochain cell)).comp
        (solution.component (P.twoTarget cell)) =
      (solution.component (P.twoTarget cell)).comp
        (CompositeFiberAut.hom (pulledCochain cell)) := by
  rcases membership with ⟨base, pulled, paired, baseEquality, pulledEquality⟩
  rw [← baseEquality, ← pulledEquality]
  exact paired.upperRawDefectCochain_intertwining cell

/-- Both composites represented by one paired restricted-orbit witness fix
the common coefficient ring pointwise. -/
theorem InPairedCoefficientTrivialUpperReselectionOrbit.composite_coefficient_id
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    {input : UpperGeometryCompatibleProblemInputData ctx P k}
    {solution : GeometryCompatibleUpperRefinementBCSolution input}
    {baseCochain : UpperDefectCochain input.generatedBaseRouteData}
    {pulledCochain : UpperDefectCochain input.generatedPulledRouteData}
    (membership : InPairedCoefficientTrivialUpperReselectionOrbit solution
      baseCochain pulledCochain)
    (cell : P.TwoCell) :
    (((CompositeFiberAut.hom (baseCochain cell)).comp
      (solution.component (P.twoTarget cell))).geometry.coefficientHom =
        RingHom.id k) ∧
    (((solution.component (P.twoTarget cell)).comp
      (CompositeFiberAut.hom (pulledCochain cell))).geometry.coefficientHom =
        RingHom.id k) := by
  rcases membership with ⟨base, pulled, paired, baseEquality, pulledEquality⟩
  rw [← baseEquality, ← pulledEquality]
  exact paired.2.2.2 cell

/-- A full paired reselection belongs to the paired restricted orbit of the
two actual raw cochains it generates; the generation equalities are reflexive
and are not supplied by the caller. -/
theorem PairedCoefficientTrivialUpperReselection.mem_pairedRestrictedOrbit
    {U : AtomCarrier.{u}} {ctx : ActiveRefinementBCContext U}
    {P : FiniteTransportPresentation.{u}} {k : CommRingCat.{v}}
    {input : UpperGeometryCompatibleProblemInputData ctx P k}
    {solution : GeometryCompatibleUpperRefinementBCSolution input}
    {base : GeneratedBaseCoefficientTrivialUpperEdgeReselection input}
    {pulled : GeneratedPulledCoefficientTrivialUpperEdgeReselection input}
    (paired : PairedCoefficientTrivialUpperReselection solution base pulled) :
    InPairedCoefficientTrivialUpperReselectionOrbit solution
      (upperRawDefectCochain input.generatedBaseRouteData
        base.toUpperEdgeReselection)
      (upperRawDefectCochain input.generatedPulledRouteData
        pulled.toUpperEdgeReselection) := by
  exact ⟨base, pulled, paired, rfl, rfl⟩

end UpperGeometryCompatibleProblemInputData

namespace UpperDecisionWitness

/-- The named generated comparator pair fires paired restricted-orbit
membership for the two actual raw cochains generated by that same pair. -/
theorem generatedComparatorUpperReselections_pairedRestrictedOrbit_fires :
    UpperGeometryCompatibleProblemInputData.InPairedCoefficientTrivialUpperReselectionOrbit
      solution
      (upperRawDefectCochain problem.data.generatedBaseRouteData
        generatedBaseComparatorCoefficientTrivialUpperReselection.toUpperEdgeReselection)
      (upperRawDefectCochain problem.data.generatedPulledRouteData
        generatedPulledComparatorCoefficientTrivialUpperReselection.toUpperEdgeReselection) :=
  UpperGeometryCompatibleProblemInputData.PairedCoefficientTrivialUpperReselection.mem_pairedRestrictedOrbit
    generatedComparatorUpperReselections_paired_fires

end UpperDecisionWitness

end AAT.AG.DoctrineFiberProduct

#assert_standard_axioms_only AAT.AG.DoctrineFiberProduct
