import Formal.AG.LawAlgebra.LawfulLocus

noncomputable section

open BigOperators

namespace AAT.AG
namespace Derived

universe u v

namespace Koszul

variable (A : Type v) [CommRing A]

/--
V.定義2.3: selected finite defect generators for an obstruction ideal.

The generator selection is explicit because PRD-5 treats derived lawful loci as
Koszul complexes only after the selected generators for `I_U` have been fixed.
-/
structure SelectedGeneratorFamily (I : Ideal A) where
  Generator : Type u
  [fintype : Fintype Generator]
  generator : Generator -> A
  spans : Ideal.span (Set.range generator) = I

attribute [instance] SelectedGeneratorFamily.fintype

namespace SelectedGeneratorFamily

variable {A}

/-- V.定義2.3: the ideal generated by the selected defect sections. -/
def generatedIdeal {I : Ideal A} (G : SelectedGeneratorFamily.{u, v} A I) : Ideal A :=
  Ideal.span (Set.range G.generator)

/-- V.定義2.3: selected generators recover the obstruction ideal they present. -/
theorem generatedIdeal_eq {I : Ideal A} (G : SelectedGeneratorFamily.{u, v} A I) :
    G.generatedIdeal = I :=
  G.spans

/-- V.定義2.3: the degree-one free term of the chart-level Koszul surface. -/
abbrev firstTerm {I : Ideal A} (G : SelectedGeneratorFamily.{u, v} A I) :=
  G.Generator -> A

/-- V.定義2.3: first Koszul differential, recording the selected equations. -/
def d1 {I : Ideal A} (G : SelectedGeneratorFamily.{u, v} A I) (c : G.firstTerm) : A :=
  ∑ i, c i * G.generator i

/-- V.定義2.3: the first differential lands in the selected generated ideal. -/
theorem d1_mem_generatedIdeal {I : Ideal A}
    (G : SelectedGeneratorFamily.{u, v} A I) (c : G.firstTerm) :
    G.d1 c ∈ G.generatedIdeal := by
  classical
  refine Ideal.sum_mem G.generatedIdeal ?_
  intro i _hi
  exact Ideal.mul_mem_left G.generatedIdeal (c i)
    (Ideal.subset_span (Set.mem_range_self i))

end SelectedGeneratorFamily

/--
V.定義2.3: chart-level Koszul complex surface for a selected generator family.

This is not a general derived-category object. It records the degree-zero term,
the first differential generated by selected defect sections, and the quotient
that represents the `H_0` truncation used by PRD-5.
-/
structure KoszulComplex (I : Ideal A) where
  generators : SelectedGeneratorFamily.{u, v} A I

namespace KoszulComplex

variable {A}

/-- V.定義2.3: degree-zero term of the selected Koszul surface. -/
abbrev C0 {I : Ideal A} (_K : KoszulComplex.{u, v} A I) :=
  A

/-- V.定義2.3: degree-one term of the selected Koszul surface. -/
abbrev C1 {I : Ideal A} (K : KoszulComplex.{u, v} A I) :=
  K.generators.firstTerm

/-- V.定義2.3: first differential of the selected Koszul surface. -/
def d1 {I : Ideal A} (K : KoszulComplex.{u, v} A I) : K.C1 -> K.C0 :=
  K.generators.d1

/-- V.原則2.4: the ideal cutting out the zero-th Koszul homology quotient. -/
def zeroHomologyIdeal {I : Ideal A} (K : KoszulComplex.{u, v} A I) : Ideal A :=
  K.generators.generatedIdeal

/-- V.原則2.4: selected `H_0(Kosz)` quotient for the chart-level Koszul surface. -/
abbrev zeroHomology {I : Ideal A} (K : KoszulComplex.{u, v} A I) :=
  A ⧸ K.zeroHomologyIdeal

/-- V.原則2.4: the selected `H_0` quotient is cut out by the original ideal `I`. -/
theorem zeroHomologyIdeal_eq {I : Ideal A} (K : KoszulComplex.{u, v} A I) :
    K.zeroHomologyIdeal = I :=
  K.generators.generatedIdeal_eq

/-- V.原則2.4: `H_0(Kosz(O_X; delta_U))` is the classical quotient `O_X / I_U`. -/
theorem zeroHomology_eq_classicalQuotient {I : Ideal A}
    (K : KoszulComplex.{u, v} A I) :
    K.zeroHomology = (A ⧸ I) := by
  simp [zeroHomology, zeroHomologyIdeal_eq]

/-- V.原則2.4: algebra-equivalence form of `H_0(Kosz) ≅ O_X / I`. -/
def zeroHomologyAlgEquivClassicalQuotient {I : Ideal A}
    (K : KoszulComplex.{u, v} A I) :
    K.zeroHomology ≃ₐ[A] (A ⧸ I) :=
  Ideal.quotientEquivAlgOfEq A K.zeroHomologyIdeal_eq

/-- V.原則2.4: ring-equivalence form of `H_0(Kosz) ≅ O_X / I`. -/
def zeroHomologyRingEquivClassicalQuotient {I : Ideal A}
    (K : KoszulComplex.{u, v} A I) :
    K.zeroHomology ≃+* (A ⧸ I) :=
  K.zeroHomologyAlgEquivClassicalQuotient.toRingEquiv

end KoszulComplex

/--
V.定義2.3: derived lawful locus represented by a selected chart-level Koszul
surface. The selected generators are part of the data.
-/
structure DerivedLawfulLocus (I : Ideal A) where
  koszul : KoszulComplex.{u, v} A I

namespace DerivedLawfulLocus

variable {A}

/-- V.定義2.3: structure-sheaf complex representation of the derived locus. -/
def structureSheafComplex {I : Ideal A}
    (D : DerivedLawfulLocus.{u, v} A I) : KoszulComplex.{u, v} A I :=
  D.koszul

/-- V.原則2.4: zero-th truncation quotient of the derived lawful locus. -/
abbrev truncation {I : Ideal A} (D : DerivedLawfulLocus.{u, v} A I) :=
  D.koszul.zeroHomology

/-- V.原則2.4: the truncation quotient is the classical quotient `O_X / I`. -/
theorem truncation_eq_classicalQuotient {I : Ideal A}
    (D : DerivedLawfulLocus.{u, v} A I) :
    D.truncation = (A ⧸ I) :=
  D.koszul.zeroHomology_eq_classicalQuotient

/-- V.原則2.4: algebra-equivalence form of the derived-locus truncation. -/
def truncationAlgEquivClassicalQuotient {I : Ideal A}
    (D : DerivedLawfulLocus.{u, v} A I) :
    D.truncation ≃ₐ[A] (A ⧸ I) :=
  D.koszul.zeroHomologyAlgEquivClassicalQuotient

/-- V.原則2.4: ring-equivalence form of the derived-locus truncation. -/
def truncationRingEquivClassicalQuotient {I : Ideal A}
    (D : DerivedLawfulLocus.{u, v} A I) :
    D.truncation ≃+* (A ⧸ I) :=
  D.koszul.zeroHomologyRingEquivClassicalQuotient

/-- V.原則2.4: the truncation ideal is the original obstruction ideal. -/
theorem truncationIdeal_eq {I : Ideal A}
    (D : DerivedLawfulLocus.{u, v} A I) :
    D.koszul.zeroHomologyIdeal = I :=
  D.koszul.zeroHomologyIdeal_eq

/-- V.原則2.4: the classical truncation of the derived locus is `Flat_U(X)`. -/
theorem truncation_locus_eq_classical {I : Ideal A}
    (D : DerivedLawfulLocus.{u, v} A I) :
    LawAlgebra.LawfulLocus.lawfulLocus A D.koszul.zeroHomologyIdeal =
      LawAlgebra.LawfulLocus.lawfulLocus A I := by
  rw [D.truncationIdeal_eq]

end DerivedLawfulLocus

end Koszul

end Derived
end AAT.AG
