import Formal.AG.Derived.HilbertSeries
import Mathlib.Order.WellFounded

noncomputable section

namespace AAT.AG
namespace Derived

universe u

namespace WellFoundedRepair

/--
V.定義13.1: well-founded repair comparison profile.

The relation `ltRep B A` is the selected repair comparison reading
`B <_{rep} A`.  The profile only says that selected repair steps decrease in
this relation; it does not assert solver completeness or global optimality.
-/
structure RepairComparisonProfile where
  State : Type u
  ltRep : State -> State -> Prop
  wellFounded_ltRep : WellFounded ltRep
  step : State -> State -> Prop
  step_decreases : ∀ {A B : State}, step A B -> ltRep B A
  targetCleared : State -> Prop
  noSolutionCertificate : State -> Prop

namespace RepairComparisonProfile

variable (P : RepairComparisonProfile.{u})

/-- V.定義13.1: every selected repair step decreases in `<_{rep}`. -/
theorem step_decreases_certificate {A B : P.State} (hstep : P.step A B) :
    P.ltRep B A :=
  P.step_decreases hstep

/-- V.定理13.3: a Nat-indexed infinite selected repair sequence. -/
def InfiniteRepairSequence : Prop :=
  ∃ sequence : Nat -> P.State, ∀ n, P.step (sequence n) (sequence (n + 1))

/--
V.定理13.3: repair termination.

If every selected repair step decreases in a well-founded repair comparison
profile, then no infinite selected repair sequence exists.
-/
theorem no_infinite_repair_sequence :
    ¬ P.InfiniteRepairSequence := by
  rintro ⟨sequence, hstep⟩
  have hdescending : ∀ n, P.ltRep (sequence (n + 1)) (sequence n) := by
    intro n
    exact P.step_decreases (hstep n)
  exact
    (wellFounded_iff_isEmpty_descending_chain.mp P.wellFounded_ltRep).false
      ⟨sequence, hdescending⟩

end RepairComparisonProfile

/-- V.定義13.2: selected evidence that a repair step is sound. -/
inductive SoundRepairStepEvidence (P : RepairComparisonProfile.{u})
    (A B : P.State) where
  | targetDecreases (hstep : P.step A B) (hdecreases : P.ltRep B A)
  | cleared (hstep : P.step A B) (hcleared : P.targetCleared B)
  | noSolution (hcertificate : P.noSolutionCertificate A)

namespace SoundRepairStepEvidence

variable {P : RepairComparisonProfile.{u}} {A B : P.State}

/--
V.定義13.2: sound step evidence contains either a selected decreasing or
cleared step, or a selected no-solution certificate.
-/
theorem sound_or_certificate (E : SoundRepairStepEvidence P A B) :
    (P.step A B ∧ (P.ltRep B A ∨ P.targetCleared B)) ∨
      P.noSolutionCertificate A := by
  cases E with
  | targetDecreases hstep hdecreases =>
      exact Or.inl ⟨hstep, Or.inl hdecreases⟩
  | cleared hstep hcleared =>
      exact Or.inl ⟨hstep, Or.inr hcleared⟩
  | noSolution hcertificate =>
      exact Or.inr hcertificate

end SoundRepairStepEvidence

/-- V.定理13.4: selected terminal output of a sound repair synthesis rule. -/
inductive SynthesisOutput (P : RepairComparisonProfile.{u})
    (state : P.State) where
  | cleared (hcleared : P.targetCleared state)
  | noSolution (hcertificate : P.noSolutionCertificate state)

/--
V.定理13.4: one constructor-level decision of a selected synthesis rule.

The rule cannot emit an unverified transition: a `step` constructor contains
the selected step proof, while both terminal constructors contain their
cleared or no-solution evidence.
-/
inductive SynthesisDecision (P : RepairComparisonProfile.{u})
    (state : P.State) where
  | step (next : P.State) (hstep : P.step state next)
  | cleared (hcleared : P.targetCleared state)
  | noSolution (hcertificate : P.noSolutionCertificate state)

/--
V.定理13.4: finite derivation generated by constructor-level synthesis
decisions.  Each recursive constructor consumes a selected repair step.
-/
inductive SynthesisRun (P : RepairComparisonProfile.{u}) : P.State -> Type u where
  | cleared {state : P.State} (hcleared : P.targetCleared state) :
      SynthesisRun P state
  | noSolution {state : P.State} (hcertificate : P.noSolutionCertificate state) :
      SynthesisRun P state
  | step {state next : P.State} (hstep : P.step state next)
      (tail : SynthesisRun P next) : SynthesisRun P state

namespace SynthesisRun

variable {P : RepairComparisonProfile.{u}}

/-- V.定理13.4: the finite state trace carried by a synthesis derivation. -/
def trace : {start : P.State} -> SynthesisRun P start -> List P.State
  | start, .cleared _ => [start]
  | start, .noSolution _ => [start]
  | start, .step _ tail => start :: trace tail

/-- V.定理13.4: number of selected step constructors in a synthesis run. -/
def depth : {start : P.State} -> SynthesisRun P start -> Nat
  | _, .cleared _ => 0
  | _, .noSolution _ => 0
  | _, .step _ tail => depth tail + 1

/-- V.定理13.4: terminal state computed from the synthesis derivation. -/
def outputState : {start : P.State} -> SynthesisRun P start -> P.State
  | state, .cleared _ => state
  | state, .noSolution _ => state
  | _, .step _ tail => outputState tail

/-- V.定理13.4: terminal evidence computed from the synthesis derivation. -/
def output : {start : P.State} -> (run : SynthesisRun P start) ->
    SynthesisOutput P run.outputState
  | _, .cleared hcleared => .cleared hcleared
  | _, .noSolution hcertificate => .noSolution hcertificate
  | _, .step _ tail => output tail

/--
V.定理13.4: every adjacent transition in a trace carries actual sound-step
evidence.  Singleton terminal traces satisfy the predicate directly.
-/
def TraceEmitsOnlySoundSteps (P : RepairComparisonProfile.{u}) :
    List P.State -> Prop
  | [] => True
  | [_] => True
  | state :: next :: rest =>
      P.step state next ∧ P.ltRep next state ∧
        TraceEmitsOnlySoundSteps P (next :: rest)

/-- V.定理13.4: each run constructor produces sound evidence for its trace. -/
theorem trace_emitsOnlySoundSteps {start : P.State} (run : SynthesisRun P start) :
    TraceEmitsOnlySoundSteps P run.trace := by
  induction run with
  | cleared _ => trivial
  | noSolution _ => trivial
  | @step state next hstep tail ih =>
      have hsound : P.step state next ∧ P.ltRep next state :=
        ⟨hstep, P.step_decreases hstep⟩
      cases tail <;> simp_all [trace, TraceEmitsOnlySoundSteps]

/-- V.定理13.4: trace length is exactly the finite constructor depth plus one. -/
theorem trace_length_eq_depth_add_one {start : P.State}
    (run : SynthesisRun P start) : run.trace.length = run.depth + 1 := by
  induction run with
  | cleared _ => rfl
  | noSolution _ => rfl
  | step _ tail ih =>
      simp [trace, depth, ih, Nat.add_comm]

/-- V.定理13.4: a generated run ends only in a cleared or certified state. -/
theorem output_cleared_or_noSolution {start : P.State}
    (run : SynthesisRun P start) :
    P.targetCleared run.outputState ∨ P.noSolutionCertificate run.outputState := by
  induction run with
  | cleared hcleared => exact Or.inl hcleared
  | noSolution hcertificate => exact Or.inr hcertificate
  | step _ _ ih => exact ih

end SynthesisRun

/--
V.定理13.4: run a total constructor-level rule by recursion on the selected
well-founded repair comparison.  A recursive call is available only for the
strictly smaller state certified by a `step` decision.
-/
noncomputable def synthesize (P : RepairComparisonProfile.{u})
    (rule : (state : P.State) -> SynthesisDecision P state)
    (start : P.State) : SynthesisRun P start :=
  P.wellFounded_ltRep.fix (C := fun state => SynthesisRun P state)
    (fun state recurse =>
      match rule state with
      | .step next hstep =>
          .step hstep (recurse next (P.step_decreases hstep))
      | .cleared hcleared => .cleared hcleared
      | .noSolution hcertificate => .noSolution hcertificate)
    start

/-- V.定理13.4 API equation: synthesis follows exactly the selected rule constructor. -/
theorem synthesize_eq (P : RepairComparisonProfile.{u})
    (rule : (state : P.State) -> SynthesisDecision P state)
    (start : P.State) :
    synthesize P rule start =
      match rule start with
      | .step next hstep => .step hstep (synthesize P rule next)
      | .cleared hcleared => .cleared hcleared
      | .noSolution hcertificate => .noSolution hcertificate := by
  rw [synthesize, WellFounded.fix_eq]
  cases h : rule start with
  | step next hstep =>
      congr
  | cleared hcleared => rfl
  | noSolution hcertificate => rfl

/--
Compatibility carrier for a generated finite synthesis result.  Its only data
is a start state paired with the constructor-derived run; no soundness
proposition or terminal conclusion is stored as an independent field.
-/
abbrev SoundRepairSynthesisPackage (P : RepairComparisonProfile.{u}) :=
  Σ start : P.State, SynthesisRun P start

/-- V.定理13.4: generate the compatibility synthesis result from a rule. -/
noncomputable def synthesizePackage (P : RepairComparisonProfile.{u})
    (rule : (state : P.State) -> SynthesisDecision P state)
    (start : P.State) : SoundRepairSynthesisPackage P :=
  ⟨start, synthesize P rule start⟩

namespace SoundRepairSynthesisPackage

variable {P : RepairComparisonProfile.{u}}

/-- V.定理13.4: generated trace of a sound repair synthesis result. -/
def trace (S : SoundRepairSynthesisPackage P) : List P.State :=
  S.2.trace

/-- V.定理13.4: generated terminal state of a sound repair synthesis result. -/
def outputState (S : SoundRepairSynthesisPackage P) : P.State :=
  S.2.outputState

/-- V.定理13.4: generated terminal evidence of a sound repair synthesis result. -/
def output (S : SoundRepairSynthesisPackage P) : SynthesisOutput P S.outputState :=
  S.2.output

/-- V.定理13.4: the generated trace emits only selected sound steps. -/
theorem emitsOnlySoundStepsOrNoSolutionCertificate_certificate
    (S : SoundRepairSynthesisPackage P) :
    SynthesisRun.TraceEmitsOnlySoundSteps P S.trace :=
  S.2.trace_emitsOnlySoundSteps

/-- V.定理13.4: generated trace length is controlled by constructor depth. -/
theorem trace_length_eq_depth_add_one (S : SoundRepairSynthesisPackage P) :
    S.trace.length = S.2.depth + 1 :=
  S.2.trace_length_eq_depth_add_one

/--
V.定理13.4: sound repair synthesis terminates with a cleared target or a
selected no-solution certificate.
-/
theorem output_cleared_or_noSolution (S : SoundRepairSynthesisPackage P) :
    P.targetCleared S.outputState ∨ P.noSolutionCertificate S.outputState := by
  exact S.2.output_cleared_or_noSolution

end SoundRepairSynthesisPackage

/--
V.定理13.4 Sound Repair Synthesis: a total constructor-level synthesis rule
terminates in a finite, sound trace whose output is cleared or certified.
-/
theorem soundRepairSynthesis (P : RepairComparisonProfile.{u})
    (rule : (state : P.State) -> SynthesisDecision P state)
    (start : P.State) :
    let run := synthesize P rule start
    SynthesisRun.TraceEmitsOnlySoundSteps P run.trace ∧
      run.trace.length = run.depth + 1 ∧
        (P.targetCleared run.outputState ∨
          P.noSolutionCertificate run.outputState) := by
  dsimp
  exact ⟨SynthesisRun.trace_emitsOnlySoundSteps _,
    SynthesisRun.trace_length_eq_depth_add_one _,
    SynthesisRun.output_cleared_or_noSolution _⟩

end WellFoundedRepair

end Derived
end AAT.AG
