import ResearchLean.AG.ResolutionInvariance.ComparisonData
import ResearchLean.AG.TwoPhase.CohomologyComparison
import Formal.Util.AssertStandardAxioms

/-!
# A face-lift obstruction to the proposed resolution-invariance condition

This module tests the fixed incidence conditions C0--C3 of
`G-104-aat-resolution-invariance`.  The finite witness has a proper adequate
refinement and a nonconstant law.  Every coefficient coordinate is generated
by the canonical law descent.  The fine nerve is a four-edge cycle with no
face, while the coarse nerve is its three-edge image with a filling face.

The chart fibers are connected trees, every coarse edge has a lift, and fiber
cycles are generated by internal faces vacuously because the only nontrivial
fiber is a single edge.  Nevertheless the canonical pullback on standard
`H^1` is not surjective.  Thus the missing coarse-face lift is a concrete
obstruction to the proposed sufficiency of C0--C3.
-/

noncomputable section

namespace AAT.AG.ResolutionInvariance

open CanonicalResolution Cohomology TwoPhase

namespace FaceLiftObstruction

/-! ## A proper adequate pair with a nonconstant law -/

/-- Four concrete sources; the first two are identified by the coarse reading. -/
abbrev Source := Fin 4

/-- The explicit quotient map underlying the coarse reading. -/
def coarseRead (source : Source) : Fin 3 :=
  if source = 0 then 0 else if source = 1 then 0 else
    if source = 2 then 1 else 2

/-- The fine reading keeps every source distinct. -/
abbrev fineReading : Reading Source where
  Target := Fin 4
  read := id
  surjective := Function.surjective_id

/-- The coarse reading has three targets and identifies sources zero and one. -/
abbrev coarseReading : Reading Source where
  Target := Fin 3
  read := coarseRead
  surjective := by
    intro target
    fin_cases target
    · exact ⟨0, by simp [coarseRead]⟩
    · exact ⟨2, by simp [coarseRead]⟩
    · exact ⟨3, by simp [coarseRead]⟩

/-- One declared law whose value is the coarse reading itself. -/
def laws : FiniteLawFamily Source where
  Law := PUnit
  lawFintype := inferInstance
  Value := fun _ => Fin 3
  valueDecidableEq := fun _ => inferInstance
  eval := fun _ => coarseRead

/-- The coarse reading is adequate for the declared law. -/
theorem coarse_adequate : laws.Adequate coarseReading := by
  intro law
  refine ⟨id, ?_⟩
  intro source
  cases law
  rfl

/-- The fine reading is adequate because the law descends by `coarseRead`. -/
theorem fine_adequate : laws.Adequate fineReading := by
  intro law
  refine ⟨coarseRead, ?_⟩
  intro source
  cases law
  rfl

/-- The coarse reading is coarser than the identity reading. -/
theorem coarse_coarser_fine : coarseReading.CoarserThan fineReading := by
  intro x y hxy
  change x = y at hxy
  subst y
  rfl

/-- The canonical comparison factor is the explicit quotient map. -/
theorem comparisonFactor_eq_coarseRead :
    comparisonFactor coarseReading fineReading coarse_coarser_fine =
      coarseRead := by
  symm
  apply comparisonFactor_unique coarseReading fineReading coarse_coarser_fine
  intro source
  rfl

/-- The adequate comparison is a proper refinement, not an identity map. -/
theorem comparisonFactor_not_injective :
    ¬ Function.Injective
      (comparisonFactor coarseReading fineReading coarse_coarser_fine) := by
  intro hinjective
  have hsame :
      comparisonFactor coarseReading fineReading coarse_coarser_fine 0 =
        comparisonFactor coarseReading fineReading coarse_coarser_fine 1 := by
    rw [comparisonFactor_eq_coarseRead]
    rfl
  have hzeroOne := hinjective hsame
  exact (by decide : (0 : Fin 4) ≠ 1) hzeroOne

/-- The concrete law evaluation is genuinely nonconstant. -/
theorem law_nonconstant :
    ∃ law x y, laws.eval law x ≠ laws.eval law y := by
  refine ⟨PUnit.unit, 0, 2, ?_⟩
  decide

/-! ## Supported nerves and the incidence conditions -/

/-- A finite nerve whose cells carry subsets of one reading target. -/
structure TargetSupportedNerve (q : Reading Source) where
  nerve : CoverNerve
  [chartFintype : Fintype nerve.Chart]
  [edgeFintype : Fintype nerve.EdgeComponent]
  [faceFintype : Fintype nerve.FaceComponent]
  chartSupport : nerve.Chart → Set q.Target
  edgeSupport : nerve.EdgeComponent → Set q.Target
  faceSupport : nerve.FaceComponent → Set q.Target
  chartSupport_nonempty : ∀ chart, (chartSupport chart).Nonempty
  edgeSupport_left : ∀ edge,
    edgeSupport edge ⊆ chartSupport (nerve.edgeLeft edge)
  edgeSupport_right : ∀ edge,
    edgeSupport edge ⊆ chartSupport (nerve.edgeRight edge)
  faceSupport_edge0 : ∀ face,
    faceSupport face ⊆ edgeSupport (nerve.faceEdge0 face)
  faceSupport_edge1 : ∀ face,
    faceSupport face ⊆ edgeSupport (nerve.faceEdge1 face)
  faceSupport_edge2 : ∀ face,
    faceSupport face ⊆ edgeSupport (nerve.faceEdge2 face)

namespace TargetSupportedNerve

attribute [instance] chartFintype edgeFintype faceFintype

end TargetSupportedNerve

/--
An incidence morphism allows precisely the degenerate edges and faces described
by the fixed GOAL: an edge without an image lies inside one chart fiber, and a
face without an image has only such internal boundary edges.
-/
structure NerveMorphism (fine coarse : CoverNerve) where
  chartMap : fine.Chart → coarse.Chart
  edgeMap : fine.EdgeComponent → Option coarse.EdgeComponent
  faceMap : fine.FaceComponent → Option coarse.FaceComponent
  edge_some_left : ∀ fineEdge coarseEdge,
    edgeMap fineEdge = some coarseEdge →
      chartMap (fine.edgeLeft fineEdge) = coarse.edgeLeft coarseEdge
  edge_some_right : ∀ fineEdge coarseEdge,
    edgeMap fineEdge = some coarseEdge →
      chartMap (fine.edgeRight fineEdge) = coarse.edgeRight coarseEdge
  edge_none_fiber : ∀ fineEdge,
    edgeMap fineEdge = none →
      chartMap (fine.edgeLeft fineEdge) = chartMap (fine.edgeRight fineEdge)
  face_some_edge0 : ∀ fineFace coarseFace,
    faceMap fineFace = some coarseFace →
      edgeMap (fine.faceEdge0 fineFace) = some (coarse.faceEdge0 coarseFace)
  face_some_edge1 : ∀ fineFace coarseFace,
    faceMap fineFace = some coarseFace →
      edgeMap (fine.faceEdge1 fineFace) = some (coarse.faceEdge1 coarseFace)
  face_some_edge2 : ∀ fineFace coarseFace,
    faceMap fineFace = some coarseFace →
      edgeMap (fine.faceEdge2 fineFace) = some (coarse.faceEdge2 coarseFace)
  face_none_edge0 : ∀ fineFace,
    faceMap fineFace = none → edgeMap (fine.faceEdge0 fineFace) = none
  face_none_edge1 : ∀ fineFace,
    faceMap fineFace = none → edgeMap (fine.faceEdge1 fineFace) = none
  face_none_edge2 : ∀ fineFace,
    faceMap fineFace = none → edgeMap (fine.faceEdge2 fineFace) = none

/-- Coarse triangle: three charts, three edges, and one filling face. -/
abbrev coarseNerve : CoverNerve where
  Chart := Fin 3
  EdgeComponent := Fin 3
  FaceComponent := PUnit
  edgeLeft edge := if edge = 0 then 0 else if edge = 1 then 0 else 1
  edgeRight edge := if edge = 0 then 1 else 2
  faceEdge0 _ := 0
  faceEdge1 _ := 1
  faceEdge2 _ := 2
  edgeOverlapComponent := fun _ => True
  faceTripleOverlapComponent := fun _ => True
  edgeOverlapComponent_holds := fun _ => trivial
  faceTripleOverlapComponent_holds := fun _ => trivial

/--
Fine four-cycle: edge zero is internal to the split chart fiber; edges one,
two, and three map to the three coarse edges.  There is no fine face.
-/
abbrev fineNerve : CoverNerve where
  Chart := Fin 4
  EdgeComponent := Fin 4
  FaceComponent := Empty
  edgeLeft edge :=
    if edge = 0 then 0 else if edge = 1 then 1 else
      if edge = 2 then 0 else 2
  edgeRight edge :=
    if edge = 0 then 1 else if edge = 1 then 2 else 3
  faceEdge0 := Empty.elim
  faceEdge1 := Empty.elim
  faceEdge2 := Empty.elim
  edgeOverlapComponent := fun _ => True
  faceTripleOverlapComponent := fun _ => True
  edgeOverlapComponent_holds := fun _ => trivial
  faceTripleOverlapComponent_holds := Empty.elim

/-- The coarse nerve with full, nonempty target support on every cell. -/
abbrev coarseSupported : TargetSupportedNerve coarseReading where
  nerve := coarseNerve
  chartFintype := inferInstance
  edgeFintype := inferInstance
  faceFintype := inferInstance
  chartSupport := fun _ => Set.univ
  edgeSupport := fun _ => Set.univ
  faceSupport := fun _ => Set.univ
  chartSupport_nonempty := fun _ => ⟨0, Set.mem_univ _⟩
  edgeSupport_left := by intros; simp
  edgeSupport_right := by intros; simp
  faceSupport_edge0 := by intros; simp
  faceSupport_edge1 := by intros; simp
  faceSupport_edge2 := by intros; simp

/-- The fine nerve with full, nonempty target support on every cell. -/
abbrev fineSupported : TargetSupportedNerve fineReading where
  nerve := fineNerve
  chartFintype := inferInstance
  edgeFintype := inferInstance
  faceFintype := inferInstance
  chartSupport := fun _ => Set.univ
  edgeSupport := fun _ => Set.univ
  faceSupport := Empty.elim
  chartSupport_nonempty := fun _ => ⟨0, Set.mem_univ _⟩
  edgeSupport_left := by intros; simp
  edgeSupport_right := by intros; simp
  faceSupport_edge0 := by intro face; exact isEmptyElim face
  faceSupport_edge1 := by intro face; exact isEmptyElim face
  faceSupport_edge2 := by intro face; exact isEmptyElim face

/-- The chart map identifies fine charts zero and one. -/
def chartMap (chart : fineNerve.Chart) : coarseNerve.Chart :=
  coarseRead chart

/-- The edge map deletes only the internal split-fiber edge. -/
def edgeMap (edge : fineNerve.EdgeComponent) :
    Option coarseNerve.EdgeComponent :=
  if edge = 0 then none else if edge = 1 then some 0 else
    if edge = 2 then some 1 else some 2

/-- The explicit incidence morphism from the fine cycle to the filled triangle. -/
abbrev nerveMorphism : NerveMorphism fineNerve coarseNerve where
  chartMap := chartMap
  edgeMap := edgeMap
  faceMap := Empty.elim
  edge_some_left := by
    intro fineEdge coarseEdge h
    fin_cases fineEdge <;> fin_cases coarseEdge <;>
      simp [edgeMap, chartMap, coarseRead, fineNerve, coarseNerve] at h ⊢
  edge_some_right := by
    intro fineEdge coarseEdge h
    fin_cases fineEdge <;> fin_cases coarseEdge <;>
      simp [edgeMap, chartMap, coarseRead, fineNerve, coarseNerve] at h ⊢
  edge_none_fiber := by
    intro fineEdge h
    fin_cases fineEdge <;>
      simp [edgeMap, chartMap, coarseRead, fineNerve] at h ⊢
  face_some_edge0 := by intro face; exact isEmptyElim face
  face_some_edge1 := by intro face; exact isEmptyElim face
  face_some_edge2 := by intro face; exact isEmptyElim face
  face_none_edge0 := by intro face; exact isEmptyElim face
  face_none_edge1 := by intro face; exact isEmptyElim face
  face_none_edge2 := by intro face; exact isEmptyElim face

/-!
The following predicates are private proof helpers for this one closed finite
witness.  They are not exported as reusable `Prop` APIs: the public theorems
below state the corresponding incidence properties directly.
-/

/-- Fine chart support maps into the corresponding coarse chart support. -/
private def SupportCompatible : Prop :=
  ∀ chart target, target ∈ fineSupported.chartSupport chart →
    comparisonFactor coarseReading fineReading coarse_coarser_fine target ∈
      coarseSupported.chartSupport (nerveMorphism.chartMap chart)

/-- C0: every coarse chart support is exactly the union of mapped fine supports. -/
private def ConditionC0 : Prop :=
  ∀ coarseChart target,
    target ∈ coarseSupported.chartSupport coarseChart ↔
      ∃ fineChart fineTarget,
        nerveMorphism.chartMap fineChart = coarseChart ∧
        fineTarget ∈ fineSupported.chartSupport fineChart ∧
        comparisonFactor coarseReading fineReading coarse_coarser_fine fineTarget =
          target

/-- Fine charts are adjacent inside a coarse-chart fiber along deleted edges. -/
private def FiberAdjacent (left right : fineNerve.Chart) : Prop :=
  ∃ edge, nerveMorphism.edgeMap edge = none ∧
    ((fineNerve.edgeLeft edge = left ∧ fineNerve.edgeRight edge = right) ∨
      (fineNerve.edgeLeft edge = right ∧ fineNerve.edgeRight edge = left))

/-- C1: every chart fiber is nonempty and connected by internal fine edges. -/
private def ConditionC1 : Prop :=
  ∀ coarseChart,
    (∃ fineChart, nerveMorphism.chartMap fineChart = coarseChart) ∧
    ∀ left right,
      nerveMorphism.chartMap left = coarseChart →
      nerveMorphism.chartMap right = coarseChart →
      Relation.ReflTransGen FiberAdjacent left right

/-- C2: every coarse edge has a fine edge lift. -/
private def ConditionC2 : Prop :=
  ∀ coarseEdge, ∃ fineEdge, nerveMorphism.edgeMap fineEdge = some coarseEdge

/-- An edge lies in the internal graph over one coarse chart. -/
private def FiberEdge (coarseChart : coarseNerve.Chart)
    (edge : fineNerve.EdgeComponent) : Prop :=
  nerveMorphism.edgeMap edge = none ∧
    nerveMorphism.chartMap (fineNerve.edgeLeft edge) = coarseChart

/-- Incoming coefficient sum of a finite one-chain at one fine chart. -/
private def incoming (chain : fineNerve.EdgeComponent → ℚ)
    (chart : fineNerve.Chart) : ℚ :=
  ∑ edge, if fineNerve.edgeRight edge = chart then chain edge else 0

/-- Outgoing coefficient sum of a finite one-chain at one fine chart. -/
private def outgoing (chain : fineNerve.EdgeComponent → ℚ)
    (chart : fineNerve.Chart) : ℚ :=
  ∑ edge, if fineNerve.edgeLeft edge = chart then chain edge else 0

/-- A cycle supported inside one chart fiber, stated only with incidence data. -/
private def IsFiberCycle (coarseChart : coarseNerve.Chart)
    (chain : fineNerve.EdgeComponent → ℚ) : Prop :=
  (∀ edge, ¬ FiberEdge coarseChart edge → chain edge = 0) ∧
  ∀ chart, nerveMorphism.chartMap chart = coarseChart →
    incoming chain chart = outgoing chain chart

/-- A fine face is internal to one chart fiber when all boundary edges are. -/
private def InternalFace (coarseChart : coarseNerve.Chart)
    (face : fineNerve.FaceComponent) : Prop :=
  FiberEdge coarseChart (fineNerve.faceEdge0 face) ∧
    FiberEdge coarseChart (fineNerve.faceEdge1 face) ∧
    FiberEdge coarseChart (fineNerve.faceEdge2 face)

/-- Oriented boundary of a finite fine-face chain. -/
private def faceBoundary (faces : fineNerve.FaceComponent → ℚ)
    (edge : fineNerve.EdgeComponent) : ℚ :=
  (∑ face, if fineNerve.faceEdge0 face = edge then faces face else 0) -
    (∑ face, if fineNerve.faceEdge1 face = edge then faces face else 0) +
      (∑ face, if fineNerve.faceEdge2 face = edge then faces face else 0)

/-- C3: every internal fiber cycle is spanned by internal fine faces. -/
private def ConditionC3 : Prop :=
  ∀ coarseChart chain, IsFiberCycle coarseChart chain →
    ∃ faces : fineNerve.FaceComponent → ℚ,
      (∀ face, ¬ InternalFace coarseChart face → faces face = 0) ∧
      ∀ edge, chain edge = faceBoundary faces edge

/-- Full supports are compatible with the canonical comparison factor. -/
theorem support_compatible :
    ∀ chart target, target ∈ fineSupported.chartSupport chart →
      comparisonFactor coarseReading fineReading coarse_coarser_fine target ∈
        coarseSupported.chartSupport (nerveMorphism.chartMap chart) := by
  change SupportCompatible
  intro chart target _
  trivial

/-- A selected fine chart over each coarse chart. -/
def chartLift (chart : coarseNerve.Chart) : fineNerve.Chart :=
  if chart = 0 then 0 else if chart = 1 then 2 else 3

/-- The selected chart lift lies in the requested fiber. -/
theorem chartMap_chartLift (chart : coarseNerve.Chart) :
    nerveMorphism.chartMap (chartLift chart) = chart := by
  fin_cases chart <;> rfl

/-- C0 holds for the concrete full supports. -/
theorem conditionC0 :
    ∀ coarseChart target,
      target ∈ coarseSupported.chartSupport coarseChart ↔
        ∃ fineChart fineTarget,
          nerveMorphism.chartMap fineChart = coarseChart ∧
          fineTarget ∈ fineSupported.chartSupport fineChart ∧
          comparisonFactor coarseReading fineReading coarse_coarser_fine fineTarget =
            target := by
  change ConditionC0
  intro coarseChart target
  constructor
  · intro _
    obtain ⟨fineTarget, htarget⟩ :=
      comparisonFactor_surjective coarseReading fineReading coarse_coarser_fine target
    exact ⟨chartLift coarseChart, fineTarget, chartMap_chartLift coarseChart,
      Set.mem_univ _, htarget⟩
  · intro _
    trivial

/-- The two split charts are connected by the internal edge. -/
private theorem fiberAdjacent_zero_one : FiberAdjacent 0 1 := by
  exact ⟨0, by rfl, Or.inl ⟨rfl, rfl⟩⟩

/-- The split adjacency is symmetric. -/
private theorem fiberAdjacent_one_zero : FiberAdjacent 1 0 := by
  exact ⟨0, by rfl, Or.inr ⟨rfl, rfl⟩⟩

/-- C1 holds: the only nonsingleton fiber is the connected pair zero--one. -/
theorem conditionC1 :
    ∀ coarseChart,
      (∃ fineChart, nerveMorphism.chartMap fineChart = coarseChart) ∧
      ∀ left right,
        nerveMorphism.chartMap left = coarseChart →
        nerveMorphism.chartMap right = coarseChart →
        Relation.ReflTransGen
          (fun left right : fineNerve.Chart =>
            ∃ edge, nerveMorphism.edgeMap edge = none ∧
              ((fineNerve.edgeLeft edge = left ∧
                  fineNerve.edgeRight edge = right) ∨
                (fineNerve.edgeLeft edge = right ∧
                  fineNerve.edgeRight edge = left)))
          left right := by
  change ConditionC1
  intro coarseChart
  refine ⟨⟨chartLift coarseChart, chartMap_chartLift coarseChart⟩, ?_⟩
  intro left right hleft hright
  fin_cases coarseChart
  · have hl : left = 0 ∨ left = 1 := by
      fin_cases left <;> simp_all [chartMap, coarseRead]
    have hr : right = 0 ∨ right = 1 := by
      fin_cases right <;> simp_all [chartMap, coarseRead]
    rcases hl with rfl | rfl <;> rcases hr with rfl | rfl
    · exact Relation.ReflTransGen.refl
    · exact Relation.ReflTransGen.single fiberAdjacent_zero_one
    · exact Relation.ReflTransGen.single fiberAdjacent_one_zero
    · exact Relation.ReflTransGen.refl
  · have hl : left = 2 := by
      fin_cases left <;> simp_all [chartMap, coarseRead]
    have hr : right = 2 := by
      fin_cases right <;> simp_all [chartMap, coarseRead]
    subst left
    subst right
    exact Relation.ReflTransGen.refl
  · have hl : left = 3 := by
      fin_cases left <;> simp_all [chartMap, coarseRead]
    have hr : right = 3 := by
      fin_cases right <;> simp_all [chartMap, coarseRead]
    subst left
    subst right
    exact Relation.ReflTransGen.refl

/-- C2 holds by the three nondegenerate fine edges. -/
theorem conditionC2 :
    ∀ coarseEdge, ∃ fineEdge,
      nerveMorphism.edgeMap fineEdge = some coarseEdge := by
  change ConditionC2
  intro coarseEdge
  fin_cases coarseEdge
  · exact ⟨1, rfl⟩
  · exact ⟨2, rfl⟩
  · exact ⟨3, rfl⟩

/-- Every internal fiber cycle in the concrete fine graph is zero. -/
private theorem fiberCycle_eq_zero (coarseChart : coarseNerve.Chart)
    (chain : fineNerve.EdgeComponent → ℚ)
    (hcycle : IsFiberCycle coarseChart chain) : chain = 0 := by
  rcases hcycle with ⟨hsupport, hbalanced⟩
  funext edge
  fin_cases edge
  · by_cases hchart : coarseChart = 0
    · subst coarseChart
      change chain 0 = 0
      have hedgeTwo : chain 2 = 0 := hsupport 2 (by
        simp [FiberEdge, edgeMap])
      have hbalance := hbalanced 0 (by rfl)
      simp [incoming, outgoing, fineNerve, Fin.sum_univ_succ] at hbalance
      rw [hedgeTwo] at hbalance
      linarith
    · change chain 0 = 0
      apply hsupport 0
      intro hfiber
      exact hchart hfiber.2.symm
  · change chain 1 = 0
    exact hsupport 1 (by simp [FiberEdge, edgeMap])
  · change chain 2 = 0
    exact hsupport 2 (by simp [FiberEdge, edgeMap])
  · change chain 3 = 0
    exact hsupport 3 (by simp [FiberEdge, edgeMap])

/-- C3 holds because every chart fiber graph is a forest. -/
theorem conditionC3 :
    ∀ coarseChart,
      let fiberEdge : fineNerve.EdgeComponent → Prop := fun edge =>
        nerveMorphism.edgeMap edge = none ∧
          nerveMorphism.chartMap (fineNerve.edgeLeft edge) = coarseChart
      let isFiberCycle : (fineNerve.EdgeComponent → ℚ) → Prop := fun chain =>
        (∀ edge, ¬ fiberEdge edge → chain edge = 0) ∧
          ∀ chart, nerveMorphism.chartMap chart = coarseChart →
            (∑ edge, if fineNerve.edgeRight edge = chart then chain edge else 0) =
              ∑ edge, if fineNerve.edgeLeft edge = chart then chain edge else 0
      let internalFace : fineNerve.FaceComponent → Prop := fun face =>
        fiberEdge (fineNerve.faceEdge0 face) ∧
          fiberEdge (fineNerve.faceEdge1 face) ∧
          fiberEdge (fineNerve.faceEdge2 face)
      let boundary : (fineNerve.FaceComponent → ℚ) →
          fineNerve.EdgeComponent → ℚ := fun faces edge =>
        (∑ face, if fineNerve.faceEdge0 face = edge then faces face else 0) -
          (∑ face, if fineNerve.faceEdge1 face = edge then faces face else 0) +
            ∑ face, if fineNerve.faceEdge2 face = edge then faces face else 0
      ∀ chain, isFiberCycle chain →
        ∃ faces : fineNerve.FaceComponent → ℚ,
          (∀ face, ¬ internalFace face → faces face = 0) ∧
            ∀ edge, chain edge = boundary faces edge := by
  change ConditionC3
  intro coarseChart chain hcycle
  refine ⟨Empty.elim, (by intro face; exact isEmptyElim face), ?_⟩
  intro edge
  rw [fiberCycle_eq_zero coarseChart chain hcycle]
  simp [faceBoundary]

/-- The coarse filling face has no fine face lift. -/
theorem coarse_face_has_no_lift :
    ¬ ∃ fineFace : fineNerve.FaceComponent,
      nerveMorphism.faceMap fineFace = some PUnit.unit := by
  rintro ⟨fineFace, _⟩
  exact isEmptyElim fineFace

/-! ## Law-descend-generated coordinates and incidence complexes -/

/--
The coordinate basis is the actual finite value type of the sole declared law.
The generation theorems below prove that every basis element occurs on each
full support for both descents.
-/
abbrev CoarseCoordinate := Fin 3

/-- Fine coordinates use the same actual law-value basis. -/
abbrev FineCoordinate := Fin 3

/-- A source realizing each of the three law values. -/
def sourceOfValue (value : Fin 3) : Source :=
  if value = 0 then 0 else if value = 1 then 2 else 3

/-- The selected source realizes its requested law value. -/
theorem coarseRead_sourceOfValue (value : Fin 3) :
    coarseRead (sourceOfValue value) = value := by
  fin_cases value <;> rfl

/-- Every coarse basis value is generated by the actual coarse descent. -/
theorem coarseCoordinate_generated (value : CoarseCoordinate) :
    ∃ target : coarseReading.Target, target ∈ (Set.univ : Set coarseReading.Target) ∧
      lawDescend laws coarseReading coarse_adequate PUnit.unit target = value := by
  refine ⟨coarseReading.read (sourceOfValue value), Set.mem_univ _, ?_⟩
  simpa [laws, coarseRead_sourceOfValue] using
    lawDescend_commutes laws coarseReading coarse_adequate PUnit.unit
      (sourceOfValue value)

/-- Every fine basis value is generated by the actual fine descent. -/
theorem fineCoordinate_generated (value : FineCoordinate) :
    ∃ target : fineReading.Target, target ∈ (Set.univ : Set fineReading.Target) ∧
      lawDescend laws fineReading fine_adequate PUnit.unit target = value := by
  refine ⟨fineReading.read (sourceOfValue value), Set.mem_univ _, ?_⟩
  simpa [laws, coarseRead_sourceOfValue] using
    lawDescend_commutes laws fineReading fine_adequate PUnit.unit
      (sourceOfValue value)

/-- Fine law values map to the identical generated coarse law value. -/
def coordinateMap (coordinate : FineCoordinate) : CoarseCoordinate := coordinate

/-- The coordinate map preserves the underlying generated law value. -/
@[simp]
theorem coordinateMap_value (coordinate : FineCoordinate) :
    coordinateMap coordinate = coordinate :=
  rfl

/-- The coordinate map is injective because coordinates are actual law values. -/
theorem coordinateMap_injective : Function.Injective coordinateMap := by
  intro left right h
  exact h

/-- The value-coordinate map is the one forced by descend compatibility. -/
theorem coordinateMap_descend_compatible (target : fineReading.Target) :
    lawDescend laws coarseReading coarse_adequate PUnit.unit
        (comparisonFactor coarseReading fineReading coarse_coarser_fine target) =
      coordinateMap
        (lawDescend laws fineReading fine_adequate PUnit.unit target) := by
  simpa [coordinateMap] using
    lawDescend_comparisonFactor laws coarseReading fineReading
      coarse_adequate fine_adequate coarse_coarser_fine PUnit.unit target

/-- The expanded coarse nerve has one generated law coordinate per cell. -/
abbrev coarseLawNerve : CoverNerve where
  Chart := coarseNerve.Chart × CoarseCoordinate
  EdgeComponent := coarseNerve.EdgeComponent × CoarseCoordinate
  FaceComponent := coarseNerve.FaceComponent × CoarseCoordinate
  edgeLeft edge := (coarseNerve.edgeLeft edge.1, edge.2)
  edgeRight edge := (coarseNerve.edgeRight edge.1, edge.2)
  faceEdge0 face := (coarseNerve.faceEdge0 face.1, face.2)
  faceEdge1 face := (coarseNerve.faceEdge1 face.1, face.2)
  faceEdge2 face := (coarseNerve.faceEdge2 face.1, face.2)
  edgeOverlapComponent := fun _ => True
  faceTripleOverlapComponent := fun _ => True
  edgeOverlapComponent_holds := fun _ => trivial
  faceTripleOverlapComponent_holds := fun _ => trivial

/-- The expanded fine nerve has one generated law coordinate per cell. -/
abbrev fineLawNerve : CoverNerve where
  Chart := fineNerve.Chart × FineCoordinate
  EdgeComponent := fineNerve.EdgeComponent × FineCoordinate
  FaceComponent := fineNerve.FaceComponent × FineCoordinate
  edgeLeft edge := (fineNerve.edgeLeft edge.1, edge.2)
  edgeRight edge := (fineNerve.edgeRight edge.1, edge.2)
  faceEdge0 face := (fineNerve.faceEdge0 face.1, face.2)
  faceEdge1 face := (fineNerve.faceEdge1 face.1, face.2)
  faceEdge2 face := (fineNerve.faceEdge2 face.1, face.2)
  edgeOverlapComponent := fun _ => True
  faceTripleOverlapComponent := fun _ => True
  edgeOverlapComponent_holds := fun _ => trivial
  faceTripleOverlapComponent_holds := fun face => isEmptyElim face.1

/-- Endpoint incidence map on a finite nerve. -/
def edgeIncidence (N : CoverNerve) (k : Type) [Field k] :
    (N.Chart → k) →ₗ[k] (N.EdgeComponent → k) where
  toFun cochain edge :=
    cochain (N.edgeRight edge) - cochain (N.edgeLeft edge)
  map_add' left right := by funext edge; simp; abel
  map_smul' scalar cochain := by funext edge; simp [mul_sub]

/-- Face incidence map on a finite nerve. -/
def faceIncidence (N : CoverNerve) (k : Type) [Field k] :
    (N.EdgeComponent → k) →ₗ[k] (N.FaceComponent → k) where
  toFun cochain face :=
    cochain (N.faceEdge0 face) - cochain (N.faceEdge1 face) +
      cochain (N.faceEdge2 face)
  map_add' left right := by funext face; simp; abel
  map_smul' scalar cochain := by funext face; simp [mul_sub, mul_add]

/-- The actual filled-triangle coefficient complex over generated law values. -/
abbrev coarseCoefficientComplex :
    FiniteNerveCochainComplex coarseLawNerve ℚ where
  C0 := coarseLawNerve.Chart → ℚ
  C1 := coarseLawNerve.EdgeComponent → ℚ
  C2 := coarseLawNerve.FaceComponent → ℚ
  d0 := edgeIncidence coarseLawNerve ℚ
  d1 := faceIncidence coarseLawNerve ℚ
  d1_comp_d0 := by
    intro cochain
    funext face
    rcases face with ⟨face, coordinate⟩
    cases face
    simp [edgeIncidence, faceIncidence, coarseLawNerve, coarseNerve]
  zeroCochainCoordinates := LinearEquiv.refl ℚ _
  oneCochainCoordinates := LinearEquiv.refl ℚ _
  twoCochainCoordinates := LinearEquiv.refl ℚ _
  d0_eq_edgeIncidence := by intros; rfl
  d1_eq_faceIncidence := by intros; rfl

/-- The actual face-free coefficient complex over generated law values. -/
abbrev fineCoefficientComplex :
    FiniteNerveCochainComplex fineLawNerve ℚ where
  C0 := fineLawNerve.Chart → ℚ
  C1 := fineLawNerve.EdgeComponent → ℚ
  C2 := fineLawNerve.FaceComponent → ℚ
  d0 := edgeIncidence fineLawNerve ℚ
  d1 := 0
  d1_comp_d0 := by intro; rfl
  zeroCochainCoordinates := LinearEquiv.refl ℚ _
  oneCochainCoordinates := LinearEquiv.refl ℚ _
  twoCochainCoordinates := LinearEquiv.refl ℚ _
  d0_eq_edgeIncidence := by intros; rfl
  d1_eq_faceIncidence := by
    intro _ face
    exact isEmptyElim face.1

/-- Forget only the audited nerve-coordinate presentation. -/
abbrev asThreeComplex {N : CoverNerve}
    (complex : FiniteNerveCochainComplex N ℚ) :
    ThreeCochainComplex ℚ where
  C0 := complex.C0
  C1 := complex.C1
  C2 := complex.C2
  d0 := complex.d0
  d1 := complex.d1
  d1_comp_d0 := complex.d1_comp_d0

/-- Coarse generated coefficient complex in the shared G-102 linear API. -/
abbrev coarseComplex : ThreeCochainComplex ℚ :=
  asThreeComplex coarseCoefficientComplex

/-- Fine generated coefficient complex in the shared G-102 linear API. -/
abbrev fineComplex : ThreeCochainComplex ℚ :=
  asThreeComplex fineCoefficientComplex

/-- Pullback of zero-cochains along the chart and generated-value maps. -/
def pullback0 : coarseComplex.C0 →ₗ[ℚ] fineComplex.C0 where
  toFun cochain chart :=
    cochain (nerveMorphism.chartMap chart.1, coordinateMap chart.2)
  map_add' left right := by funext chart; simp
  map_smul' scalar cochain := by funext chart; simp

/-- Pullback of one-cochains, zero on the declared internal edge. -/
def pullback1 : coarseComplex.C1 →ₗ[ℚ] fineComplex.C1 where
  toFun cochain edge :=
    match nerveMorphism.edgeMap edge.1 with
    | none => 0
    | some coarseEdge => cochain (coarseEdge, coordinateMap edge.2)
  map_add' left right := by
    funext edge
    rcases edge with ⟨edge, coordinate⟩
    fin_cases edge <;> simp [edgeMap]
  map_smul' scalar cochain := by
    funext edge
    rcases edge with ⟨edge, coordinate⟩
    fin_cases edge <;> simp [edgeMap]

/-- Pullback of two-cochains into the empty fine face space. -/
def pullback2 : coarseComplex.C2 →ₗ[ℚ] fineComplex.C2 :=
  0

/-- The canonical cochain map generated by the nerve morphism and law descents. -/
def comparisonCochainMap : ThreeCochainComplex.Hom coarseComplex fineComplex where
  f0 := pullback0
  f1 := pullback1
  f2 := pullback2
  comm0 := by
    intro cochain
    funext edge
    rcases edge with ⟨edge, coordinate⟩
    fin_cases edge <;>
      simp [pullback0, pullback1, edgeIncidence, coarseComplex, fineComplex,
        asThreeComplex, coarseCoefficientComplex, fineCoefficientComplex,
        fineLawNerve, coarseLawNerve, fineNerve, coarseNerve,
        edgeMap, chartMap, coarseRead]
  comm1 := by
    intro cochain
    funext face
    exact isEmptyElim face.1

/-- The induced canonical map from coarse to fine standard `H^1`. -/
def comparisonH1Map : coarseComplex.H1 →ₗ[ℚ] fineComplex.H1 :=
  comparisonCochainMap.h1Map

/-! ## Direct cohomology computation -/

/-- A primitive for every coarse cocycle, constructed coordinatewise. -/
def coarsePrimitive (cycle : LinearMap.ker coarseComplex.d1) :
    coarseComplex.C0 := fun chart =>
  if chart.1 = 0 then 0 else if chart.1 = 1 then
    cycle.1 (0, chart.2) else cycle.1 (1, chart.2)

/-- Every coarse cocycle is the boundary of its coordinatewise primitive. -/
theorem coarse_d0_primitive (cycle : LinearMap.ker coarseComplex.d1) :
    coarseComplex.d0 (coarsePrimitive cycle) = cycle.1 := by
  funext edge
  rcases edge with ⟨edge, coordinate⟩
  fin_cases edge
  · simp [coarseComplex, asThreeComplex, coarseCoefficientComplex,
      edgeIncidence, coarsePrimitive, coarseLawNerve, coarseNerve]
  · simp [coarseComplex, asThreeComplex, coarseCoefficientComplex,
      edgeIncidence, coarsePrimitive, coarseLawNerve, coarseNerve]
  · have hface := congrFun cycle.2 (PUnit.unit, coordinate)
    change cycle.1 (0, coordinate) - cycle.1 (1, coordinate) +
      cycle.1 (2, coordinate) = 0 at hface
    simp [coarseComplex, asThreeComplex, coarseCoefficientComplex,
      edgeIncidence, coarsePrimitive, coarseLawNerve, coarseNerve]
    linarith

/-- The filled coarse triangle has zero standard `H^1` for every law value. -/
theorem coarseH1Zero : coarseComplex.H1Zero := by
  intro cohomologyClass
  obtain ⟨cycle, rfl⟩ :=
    (LinearMap.range coarseComplex.boundaryToCycles).mkQ_surjective
      cohomologyClass
  apply (Submodule.Quotient.mk_eq_zero _).2
  refine ⟨coarsePrimitive cycle, ?_⟩
  apply Subtype.ext
  exact coarse_d0_primitive cycle

/-- One concrete generated fine coordinate used by the nonzero class. -/
def selectedCoordinate : FineCoordinate := 0

/-- Period around the fine four-edge cycle at the selected law coordinate. -/
def finePeriod (cochain : fineComplex.C1) : ℚ :=
  cochain (0, selectedCoordinate) + cochain (1, selectedCoordinate) +
    cochain (3, selectedCoordinate) - cochain (2, selectedCoordinate)

/-- Every actual fine coboundary has zero period. -/
theorem finePeriod_boundary_zero (cochain : fineComplex.C0) :
    finePeriod (fineComplex.d0 cochain) = 0 := by
  simp [finePeriod, fineComplex, asThreeComplex, fineCoefficientComplex,
    edgeIncidence, fineLawNerve, fineNerve]

/-- A generated coordinate vector on the internal fine edge. -/
def fineFiringCochain : fineComplex.C1 :=
  coordinateVector (0, selectedCoordinate)

/-- The firing cochain is a cocycle because the fine nerve has no faces. -/
theorem fineFiringCochain_cocycle :
    fineComplex.d1 fineFiringCochain = 0 :=
  rfl

/-- The concrete fine cocycle. -/
def fineFiringCycle : LinearMap.ker fineComplex.d1 :=
  ⟨fineFiringCochain, fineFiringCochain_cocycle⟩

/-- The standard fine `H^1` class represented by the internal-edge vector. -/
def fineFiringClass : fineComplex.H1 :=
  (LinearMap.range fineComplex.boundaryToCycles).mkQ fineFiringCycle

/-- The firing cycle has unit period. -/
theorem finePeriod_firing : finePeriod fineFiringCycle.1 = 1 := by
  simp [finePeriod, fineFiringCycle, fineFiringCochain, coordinateVector]

/-- The face-free fine cycle has a nonzero standard `H^1` class. -/
theorem fineFiringClass_ne_zero : fineFiringClass ≠ 0 := by
  intro hzero
  have hmem := (Submodule.Quotient.mk_eq_zero
    (LinearMap.range fineComplex.boundaryToCycles)).1 hzero
  rcases hmem with ⟨cochain, hcochain⟩
  have hperiod := congrArg (fun cycle : LinearMap.ker fineComplex.d1 =>
    finePeriod cycle.1) hcochain
  change finePeriod (fineComplex.d0 cochain) =
    finePeriod fineFiringCycle.1 at hperiod
  rw [finePeriod_boundary_zero, finePeriod_firing] at hperiod
  exact zero_ne_one hperiod

/-- The canonical comparison map is not surjective on `H^1`. -/
theorem comparisonH1Map_not_surjective :
    ¬ Function.Surjective comparisonH1Map := by
  intro hsurjective
  obtain ⟨sourceClass, hsource⟩ := hsurjective fineFiringClass
  rw [coarseH1Zero sourceClass, map_zero] at hsource
  exact fineFiringClass_ne_zero hsource.symm

/--
The finite witness satisfies every proposed input and C0--C3 while the
canonical comparison map fails to be an `H^1` isomorphism.
-/
theorem fixedConditionC_not_sufficient :
    let supportCompatible : Prop :=
      ∀ chart target, target ∈ fineSupported.chartSupport chart →
        comparisonFactor coarseReading fineReading coarse_coarser_fine target ∈
          coarseSupported.chartSupport (nerveMorphism.chartMap chart)
    let conditionC0 : Prop :=
      ∀ coarseChart target,
        target ∈ coarseSupported.chartSupport coarseChart ↔
          ∃ fineChart fineTarget,
            nerveMorphism.chartMap fineChart = coarseChart ∧
            fineTarget ∈ fineSupported.chartSupport fineChart ∧
            comparisonFactor coarseReading fineReading coarse_coarser_fine fineTarget =
              target
    let fiberAdjacent : fineNerve.Chart → fineNerve.Chart → Prop := fun left right =>
      ∃ edge, nerveMorphism.edgeMap edge = none ∧
        ((fineNerve.edgeLeft edge = left ∧ fineNerve.edgeRight edge = right) ∨
          (fineNerve.edgeLeft edge = right ∧ fineNerve.edgeRight edge = left))
    let conditionC1 : Prop :=
      ∀ coarseChart,
        (∃ fineChart, nerveMorphism.chartMap fineChart = coarseChart) ∧
        ∀ left right,
          nerveMorphism.chartMap left = coarseChart →
          nerveMorphism.chartMap right = coarseChart →
          Relation.ReflTransGen fiberAdjacent left right
    let conditionC2 : Prop :=
      ∀ coarseEdge, ∃ fineEdge,
        nerveMorphism.edgeMap fineEdge = some coarseEdge
    let fiberEdge : coarseNerve.Chart → fineNerve.EdgeComponent → Prop :=
      fun coarseChart edge =>
        nerveMorphism.edgeMap edge = none ∧
          nerveMorphism.chartMap (fineNerve.edgeLeft edge) = coarseChart
    let incoming : (fineNerve.EdgeComponent → ℚ) → fineNerve.Chart → ℚ :=
      fun chain chart =>
        ∑ edge, if fineNerve.edgeRight edge = chart then chain edge else 0
    let outgoing : (fineNerve.EdgeComponent → ℚ) → fineNerve.Chart → ℚ :=
      fun chain chart =>
        ∑ edge, if fineNerve.edgeLeft edge = chart then chain edge else 0
    let isFiberCycle : coarseNerve.Chart →
        (fineNerve.EdgeComponent → ℚ) → Prop := fun coarseChart chain =>
      (∀ edge, ¬ fiberEdge coarseChart edge → chain edge = 0) ∧
        ∀ chart, nerveMorphism.chartMap chart = coarseChart →
          incoming chain chart = outgoing chain chart
    let internalFace : coarseNerve.Chart → fineNerve.FaceComponent → Prop :=
      fun coarseChart face =>
        fiberEdge coarseChart (fineNerve.faceEdge0 face) ∧
          fiberEdge coarseChart (fineNerve.faceEdge1 face) ∧
          fiberEdge coarseChart (fineNerve.faceEdge2 face)
    let boundary : (fineNerve.FaceComponent → ℚ) →
        fineNerve.EdgeComponent → ℚ := fun faces edge =>
      (∑ face, if fineNerve.faceEdge0 face = edge then faces face else 0) -
        (∑ face, if fineNerve.faceEdge1 face = edge then faces face else 0) +
          ∑ face, if fineNerve.faceEdge2 face = edge then faces face else 0
    let conditionC3 : Prop :=
      ∀ coarseChart chain, isFiberCycle coarseChart chain →
        ∃ faces : fineNerve.FaceComponent → ℚ,
          (∀ face, ¬ internalFace coarseChart face → faces face = 0) ∧
            ∀ edge, chain edge = boundary faces edge
    laws.Adequate coarseReading ∧
      laws.Adequate fineReading ∧
      coarseReading.CoarserThan fineReading ∧
      supportCompatible ∧
      conditionC0 ∧
      conditionC1 ∧
      conditionC2 ∧
      conditionC3 ∧
      (¬ Function.Injective
        (comparisonFactor coarseReading fineReading coarse_coarser_fine)) ∧
      (∃ law x y, laws.eval law x ≠ laws.eval law y) ∧
      (∀ value : CoarseCoordinate,
        ∃ target : coarseReading.Target,
          target ∈ (Set.univ : Set coarseReading.Target) ∧
          lawDescend laws coarseReading coarse_adequate PUnit.unit target = value) ∧
      (∀ value : FineCoordinate,
        ∃ target : fineReading.Target,
          target ∈ (Set.univ : Set fineReading.Target) ∧
          lawDescend laws fineReading fine_adequate PUnit.unit target = value) ∧
      (∀ target : fineReading.Target,
        lawDescend laws coarseReading coarse_adequate PUnit.unit
            (comparisonFactor coarseReading fineReading coarse_coarser_fine target) =
          coordinateMap
            (lawDescend laws fineReading fine_adequate PUnit.unit target)) ∧
      coarseComplex.H1Zero ∧
      fineFiringClass ≠ 0 ∧
      (¬ Function.Surjective comparisonH1Map) := by
  dsimp only
  exact ⟨coarse_adequate, fine_adequate, coarse_coarser_fine,
    support_compatible, conditionC0, conditionC1, conditionC2, conditionC3,
    comparisonFactor_not_injective, law_nonconstant, coarseCoordinate_generated,
    fineCoordinate_generated, coordinateMap_descend_compatible, coarseH1Zero,
    fineFiringClass_ne_zero, comparisonH1Map_not_surjective⟩

end FaceLiftObstruction

end AAT.AG.ResolutionInvariance

#assert_standard_axioms_only AAT.AG.ResolutionInvariance.FaceLiftObstruction
