import ResearchLean.AG.ResolutionInvariance.GeneratedComparisonMap
import Mathlib.LinearAlgebra.DirectSum.Finite
import Formal.Util.AssertStandardAxioms

/-!
# Law-value block decomposition for resolution invariance

This module constructs the finite coordinate blocks required by
`G-104-aat-resolution-invariance`.  The common block index is the image of the
finite source under the finite law family.  It is therefore independent of a
reading and finite even though an ambient law-value type need not be finite.

Every K0 coordinate has a canonical source-generated law-value label.  The
endpoint and face-incidence coordinate maps preserve that label, so each block
inherits a three-term cochain complex.  The original cochain spaces are then
identified canonically with the finite direct sums of the block cochain spaces,
and both generated differentials intertwine these identifications.

No basis, partition certificate, or enumeration of an ambient value type is
supplied.  The quotient-level decomposition of `H^1` is a later obligation.
-/

noncomputable section

namespace AAT.AG.ResolutionInvariance

open CanonicalResolution DirectSum TwoPhase

universe u

variable {Source : Type u}

/-! ## The finite source-generated label type -/

/--
A law-value pair that actually occurs on the finite source.  The generating
source is proof data, so different occurrences of the same value give one
label.
-/
structure LawValueLabel (laws : FiniteLawFamily Source) where
  law : laws.Law
  value : laws.Value law
  generated : ∃ source, laws.eval law source = value

namespace LawValueLabel

/-- Labels are equal when their dependent law and value fields agree. -/
@[ext]
theorem ext (laws : FiniteLawFamily Source)
    {left right : LawValueLabel laws}
    (hlaw : left.law = right.law)
    (hvalue : HEq left.value right.value) : left = right := by
  cases left with
  | mk leftLaw leftValue leftGenerated =>
      cases right with
      | mk rightLaw rightValue rightGenerated =>
          cases hlaw
          cases hvalue
          rfl

/-- The label generated by evaluating one law at one source point. -/
def ofSource (laws : FiniteLawFamily Source) (law : laws.Law)
    (source : Source) : LawValueLabel laws :=
  ⟨law, laws.eval law source, source, rfl⟩

/-- The law field of a source-generated label. -/
@[simp]
theorem ofSource_law (laws : FiniteLawFamily Source) (law : laws.Law)
    (source : Source) : (ofSource laws law source).law = law :=
  rfl

/-- The value field of a source-generated label. -/
@[simp]
theorem ofSource_value (laws : FiniteLawFamily Source) (law : laws.Law)
    (source : Source) :
    (ofSource laws law source).value = laws.eval law source :=
  rfl

/-- The source-generated label type is finite without a finite ambient value type. -/
noncomputable instance instFintype [Fintype Source]
    (laws : FiniteLawFamily Source) : Fintype (LawValueLabel laws) := by
  classical
  let Domain := Σ law : laws.Law, Source
  let toLabel : Domain → LawValueLabel laws :=
    fun input => ofSource laws input.1 input.2
  exact Fintype.ofSurjective toLabel (by
    intro label
    obtain ⟨source, hvalue⟩ := label.generated
    refine ⟨⟨label.law, source⟩, ?_⟩
    apply LawValueLabel.ext
    · rfl
    · exact heq_of_eq hvalue)

end LawValueLabel

/-! ## Coordinate fibers and their canonical direct sum -/

namespace CellCoordinate

/-- The source-generated label carried by one K0 coordinate. -/
def lawValueLabel (laws : FiniteLawFamily Source) (q : Reading Source)
    (hadequate : laws.Adequate q) (Cell : Type u)
    (support : Cell → Set q.Target)
    (coordinate : CellCoordinate laws q hadequate Cell support) :
    LawValueLabel laws := by
  refine ⟨coordinate.law, coordinate.value, ?_⟩
  obtain ⟨target, _htarget, hvalue⟩ := coordinate.generated
  obtain ⟨source, rfl⟩ := q.surjective target
  refine ⟨source, ?_⟩
  exact (lawDescend_commutes laws q hadequate coordinate.law source).symm.trans
    hvalue

/-- Coordinates in the fiber of one source-generated law-value label. -/
abbrev Block (laws : FiniteLawFamily Source) (q : Reading Source)
    (hadequate : laws.Adequate q) (Cell : Type u)
    (support : Cell → Set q.Target) (label : LawValueLabel laws) :=
  {coordinate : CellCoordinate laws q hadequate Cell support //
    coordinate.lawValueLabel laws q hadequate Cell support = label}

/--
The cochain space on all coordinates is canonically the finite direct sum of
the cochain spaces on the label fibers.
-/
def cochainBlockEquiv [Fintype Source]
    (laws : FiniteLawFamily Source) (q : Reading Source)
    (hadequate : laws.Adequate q) (Cell : Type u) [Fintype Cell]
    (support : Cell → Set q.Target) :
    (CellCoordinate laws q hadequate Cell support → ℚ) ≃ₗ[ℚ]
      ⨁ label : LawValueLabel laws,
        Block laws q hadequate Cell support label → ℚ :=
  (LinearEquiv.piCongrLeft ℚ
      (fun _ : CellCoordinate laws q hadequate Cell support => ℚ)
      (Equiv.sigmaFiberEquiv
        (lawValueLabel laws q hadequate Cell support))).symm ≪≫ₗ
    LinearEquiv.piCurry ℚ
      (fun (label : LawValueLabel laws)
        (_ : Block laws q hadequate Cell support label) => ℚ) ≪≫ₗ
    (DirectSum.linearEquivFunOnFintype ℚ (LawValueLabel laws)
      (fun label => Block laws q hadequate Cell support label → ℚ)).symm

/-- Evaluation of the decomposed cochain in one label fiber. -/
@[simp]
theorem cochainBlockEquiv_apply [Fintype Source]
    (laws : FiniteLawFamily Source) (q : Reading Source)
    (hadequate : laws.Adequate q) (Cell : Type u) [Fintype Cell]
    (support : Cell → Set q.Target)
    (cochain : CellCoordinate laws q hadequate Cell support → ℚ)
    (label : LawValueLabel laws)
    (coordinate : Block laws q hadequate Cell support label) :
    (DirectSum.linearEquivFunOnFintype ℚ (LawValueLabel laws)
        (fun current => Block laws q hadequate Cell support current → ℚ)
      (cochainBlockEquiv laws q hadequate Cell support cochain)) label coordinate =
      cochain coordinate.1 := by
  rfl

end CellCoordinate

namespace TargetSupportedNerve

variable {q : Reading Source}

/-- Degree-zero coordinates in one law-value block. -/
abbrev ChartBlockCoordinate (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws) :=
  CellCoordinate.Block laws q hadequate D.nerve.Chart D.chartSupport label

/-- Degree-one coordinates in one law-value block. -/
abbrev EdgeBlockCoordinate (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws) :=
  CellCoordinate.Block laws q hadequate D.nerve.EdgeComponent D.edgeSupport label

/-- Degree-two coordinates in one law-value block. -/
abbrev FaceBlockCoordinate (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws) :=
  CellCoordinate.Block laws q hadequate D.nerve.FaceComponent D.faceSupport label

/-- The left endpoint construction preserves the source-generated label. -/
theorem edgeLeftCoordinate_lawValueLabel (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (coordinate : D.EdgeCoordinate laws hadequate) :
    (D.edgeLeftCoordinate laws hadequate coordinate).lawValueLabel laws q
        hadequate D.nerve.Chart D.chartSupport =
      coordinate.lawValueLabel laws q hadequate D.nerve.EdgeComponent
        D.edgeSupport := by
  apply LawValueLabel.ext
  · rfl
  · rfl

/-- The right endpoint construction preserves the source-generated label. -/
theorem edgeRightCoordinate_lawValueLabel (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (coordinate : D.EdgeCoordinate laws hadequate) :
    (D.edgeRightCoordinate laws hadequate coordinate).lawValueLabel laws q
        hadequate D.nerve.Chart D.chartSupport =
      coordinate.lawValueLabel laws q hadequate D.nerve.EdgeComponent
        D.edgeSupport := by
  apply LawValueLabel.ext
  · rfl
  · rfl

/-- Boundary-edge zero preserves the source-generated label. -/
theorem faceEdge0Coordinate_lawValueLabel (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (coordinate : D.FaceCoordinate laws hadequate) :
    (D.faceEdge0Coordinate laws hadequate coordinate).lawValueLabel laws q
        hadequate D.nerve.EdgeComponent D.edgeSupport =
      coordinate.lawValueLabel laws q hadequate D.nerve.FaceComponent
        D.faceSupport := by
  apply LawValueLabel.ext
  · rfl
  · rfl

/-- Boundary-edge one preserves the source-generated label. -/
theorem faceEdge1Coordinate_lawValueLabel (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (coordinate : D.FaceCoordinate laws hadequate) :
    (D.faceEdge1Coordinate laws hadequate coordinate).lawValueLabel laws q
        hadequate D.nerve.EdgeComponent D.edgeSupport =
      coordinate.lawValueLabel laws q hadequate D.nerve.FaceComponent
        D.faceSupport := by
  apply LawValueLabel.ext
  · rfl
  · rfl

/-- Boundary-edge two preserves the source-generated label. -/
theorem faceEdge2Coordinate_lawValueLabel (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (coordinate : D.FaceCoordinate laws hadequate) :
    (D.faceEdge2Coordinate laws hadequate coordinate).lawValueLabel laws q
        hadequate D.nerve.EdgeComponent D.edgeSupport =
      coordinate.lawValueLabel laws q hadequate D.nerve.FaceComponent
        D.faceSupport := by
  apply LawValueLabel.ext
  · rfl
  · rfl

/-- The left endpoint of a block edge coordinate remains in the same block. -/
def edgeLeftBlockCoordinate (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws)
    (coordinate : D.EdgeBlockCoordinate laws hadequate label) :
    D.ChartBlockCoordinate laws hadequate label :=
  ⟨D.edgeLeftCoordinate laws hadequate coordinate.1,
    (D.edgeLeftCoordinate_lawValueLabel laws hadequate coordinate.1).trans
      coordinate.2⟩

/-- The right endpoint of a block edge coordinate remains in the same block. -/
def edgeRightBlockCoordinate (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws)
    (coordinate : D.EdgeBlockCoordinate laws hadequate label) :
    D.ChartBlockCoordinate laws hadequate label :=
  ⟨D.edgeRightCoordinate laws hadequate coordinate.1,
    (D.edgeRightCoordinate_lawValueLabel laws hadequate coordinate.1).trans
      coordinate.2⟩

/-- Boundary-edge zero of a block face remains in the same block. -/
def faceEdge0BlockCoordinate (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws)
    (coordinate : D.FaceBlockCoordinate laws hadequate label) :
    D.EdgeBlockCoordinate laws hadequate label :=
  ⟨D.faceEdge0Coordinate laws hadequate coordinate.1,
    (D.faceEdge0Coordinate_lawValueLabel laws hadequate coordinate.1).trans
      coordinate.2⟩

/-- Boundary-edge one of a block face remains in the same block. -/
def faceEdge1BlockCoordinate (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws)
    (coordinate : D.FaceBlockCoordinate laws hadequate label) :
    D.EdgeBlockCoordinate laws hadequate label :=
  ⟨D.faceEdge1Coordinate laws hadequate coordinate.1,
    (D.faceEdge1Coordinate_lawValueLabel laws hadequate coordinate.1).trans
      coordinate.2⟩

/-- Boundary-edge two of a block face remains in the same block. -/
def faceEdge2BlockCoordinate (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws)
    (coordinate : D.FaceBlockCoordinate laws hadequate label) :
    D.EdgeBlockCoordinate laws hadequate label :=
  ⟨D.faceEdge2Coordinate laws hadequate coordinate.1,
    (D.faceEdge2Coordinate_lawValueLabel laws hadequate coordinate.1).trans
      coordinate.2⟩

/-! ## The complex on one law-value block -/

/-- Degree-zero differential restricted to one law-value block. -/
def lawValueBlockD0 (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws) :
    (D.ChartBlockCoordinate laws hadequate label → ℚ) →ₗ[ℚ]
      (D.EdgeBlockCoordinate laws hadequate label → ℚ) where
  toFun cochain coordinate :=
    cochain (D.edgeRightBlockCoordinate laws hadequate label coordinate) -
      cochain (D.edgeLeftBlockCoordinate laws hadequate label coordinate)
  map_add' left right := by
    ext coordinate
    simp
    ring
  map_smul' scalar cochain := by
    ext coordinate
    simp
    ring

/-- Degree-one differential restricted to one law-value block. -/
def lawValueBlockD1 (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws) :
    (D.EdgeBlockCoordinate laws hadequate label → ℚ) →ₗ[ℚ]
      (D.FaceBlockCoordinate laws hadequate label → ℚ) where
  toFun cochain coordinate :=
    cochain (D.faceEdge0BlockCoordinate laws hadequate label coordinate) -
      cochain (D.faceEdge1BlockCoordinate laws hadequate label coordinate) +
        cochain (D.faceEdge2BlockCoordinate laws hadequate label coordinate)
  map_add' left right := by
    ext coordinate
    simp
    ring
  map_smul' scalar cochain := by
    ext coordinate
    simp
    ring

private theorem block_left_faceEdge0_eq_left_faceEdge1
    (D : TargetSupportedNerve q) (laws : FiniteLawFamily Source)
    (hadequate : laws.Adequate q) (label : LawValueLabel laws)
    (coordinate : D.FaceBlockCoordinate laws hadequate label) :
    D.edgeLeftBlockCoordinate laws hadequate label
        (D.faceEdge0BlockCoordinate laws hadequate label coordinate) =
      D.edgeLeftBlockCoordinate laws hadequate label
        (D.faceEdge1BlockCoordinate laws hadequate label coordinate) := by
  apply Subtype.ext
  apply CellCoordinate.ext
  · exact D.faceEdge0_left coordinate.1.cell
  · rfl
  · rfl

private theorem block_right_faceEdge0_eq_left_faceEdge2
    (D : TargetSupportedNerve q) (laws : FiniteLawFamily Source)
    (hadequate : laws.Adequate q) (label : LawValueLabel laws)
    (coordinate : D.FaceBlockCoordinate laws hadequate label) :
    D.edgeRightBlockCoordinate laws hadequate label
        (D.faceEdge0BlockCoordinate laws hadequate label coordinate) =
      D.edgeLeftBlockCoordinate laws hadequate label
        (D.faceEdge2BlockCoordinate laws hadequate label coordinate) := by
  apply Subtype.ext
  apply CellCoordinate.ext
  · exact D.faceEdge0_right coordinate.1.cell
  · rfl
  · rfl

private theorem block_right_faceEdge1_eq_right_faceEdge2
    (D : TargetSupportedNerve q) (laws : FiniteLawFamily Source)
    (hadequate : laws.Adequate q) (label : LawValueLabel laws)
    (coordinate : D.FaceBlockCoordinate laws hadequate label) :
    D.edgeRightBlockCoordinate laws hadequate label
        (D.faceEdge1BlockCoordinate laws hadequate label coordinate) =
      D.edgeRightBlockCoordinate laws hadequate label
        (D.faceEdge2BlockCoordinate laws hadequate label coordinate) := by
  apply Subtype.ext
  apply CellCoordinate.ext
  · exact D.faceEdge1_right coordinate.1.cell
  · rfl
  · rfl

/-- The restricted block differentials compose to zero. -/
theorem lawValueBlock_d1_comp_d0 (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws)
    (cochain : D.ChartBlockCoordinate laws hadequate label → ℚ) :
    D.lawValueBlockD1 laws hadequate label
        (D.lawValueBlockD0 laws hadequate label cochain) = 0 := by
  funext coordinate
  change
    (cochain (D.edgeRightBlockCoordinate laws hadequate label
        (D.faceEdge0BlockCoordinate laws hadequate label coordinate)) -
      cochain (D.edgeLeftBlockCoordinate laws hadequate label
        (D.faceEdge0BlockCoordinate laws hadequate label coordinate))) -
    (cochain (D.edgeRightBlockCoordinate laws hadequate label
        (D.faceEdge1BlockCoordinate laws hadequate label coordinate)) -
      cochain (D.edgeLeftBlockCoordinate laws hadequate label
        (D.faceEdge1BlockCoordinate laws hadequate label coordinate))) +
    (cochain (D.edgeRightBlockCoordinate laws hadequate label
        (D.faceEdge2BlockCoordinate laws hadequate label coordinate)) -
      cochain (D.edgeLeftBlockCoordinate laws hadequate label
        (D.faceEdge2BlockCoordinate laws hadequate label coordinate))) = 0
  rw [D.block_left_faceEdge0_eq_left_faceEdge1 laws hadequate label coordinate,
    D.block_right_faceEdge0_eq_left_faceEdge2 laws hadequate label coordinate,
    D.block_right_faceEdge1_eq_right_faceEdge2 laws hadequate label coordinate]
  ring

/-- The finite three-term complex carried by one source-generated label. -/
def lawValueBlockComplex [Fintype Source] (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q)
    (label : LawValueLabel laws) : ThreeCochainComplex ℚ where
  C0 := D.ChartBlockCoordinate laws hadequate label → ℚ
  C1 := D.EdgeBlockCoordinate laws hadequate label → ℚ
  C2 := D.FaceBlockCoordinate laws hadequate label → ℚ
  d0 := D.lawValueBlockD0 laws hadequate label
  d1 := D.lawValueBlockD1 laws hadequate label
  d1_comp_d0 := D.lawValueBlock_d1_comp_d0 laws hadequate label

/-! ## Direct sum of all block complexes -/

/-- Degree-zero direct-sum decomposition. -/
def chartCochainBlockEquiv [Fintype Source] (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q) :
    (D.ChartCoordinate laws hadequate → ℚ) ≃ₗ[ℚ]
      ⨁ label : LawValueLabel laws,
        D.ChartBlockCoordinate laws hadequate label → ℚ :=
  CellCoordinate.cochainBlockEquiv laws q hadequate D.nerve.Chart D.chartSupport

/-- Degree-one direct-sum decomposition. -/
def edgeCochainBlockEquiv [Fintype Source] (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q) :
    (D.EdgeCoordinate laws hadequate → ℚ) ≃ₗ[ℚ]
      ⨁ label : LawValueLabel laws,
        D.EdgeBlockCoordinate laws hadequate label → ℚ :=
  CellCoordinate.cochainBlockEquiv laws q hadequate D.nerve.EdgeComponent
    D.edgeSupport

/-- Degree-two direct-sum decomposition. -/
def faceCochainBlockEquiv [Fintype Source] (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q) :
    (D.FaceCoordinate laws hadequate → ℚ) ≃ₗ[ℚ]
      ⨁ label : LawValueLabel laws,
        D.FaceBlockCoordinate laws hadequate label → ℚ :=
  CellCoordinate.cochainBlockEquiv laws q hadequate D.nerve.FaceComponent
    D.faceSupport

/-- The componentwise degree-zero map on the product of all finite blocks. -/
def lawValueBlockProductD0 [Fintype Source] (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q) :
    ((label : LawValueLabel laws) →
      D.ChartBlockCoordinate laws hadequate label → ℚ) →ₗ[ℚ]
    ((label : LawValueLabel laws) →
      D.EdgeBlockCoordinate laws hadequate label → ℚ) where
  toFun cochain label :=
    D.lawValueBlockD0 laws hadequate label (cochain label)
  map_add' left right := by
    funext label coordinate
    simp
  map_smul' scalar cochain := by
    funext label coordinate
    simp

/-- The componentwise degree-one map on the product of all finite blocks. -/
def lawValueBlockProductD1 [Fintype Source] (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q) :
    ((label : LawValueLabel laws) →
      D.EdgeBlockCoordinate laws hadequate label → ℚ) →ₗ[ℚ]
    ((label : LawValueLabel laws) →
      D.FaceBlockCoordinate laws hadequate label → ℚ) where
  toFun cochain label :=
    D.lawValueBlockD1 laws hadequate label (cochain label)
  map_add' left right := by
    funext label coordinate
    simp
  map_smul' scalar cochain := by
    funext label coordinate
    simp

/-- The componentwise degree-zero map on the finite direct sum of blocks. -/
def lawValueBlockDirectSumD0 [Fintype Source] (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q) :
    (⨁ label : LawValueLabel laws,
      D.ChartBlockCoordinate laws hadequate label → ℚ) →ₗ[ℚ]
    (⨁ label : LawValueLabel laws,
      D.EdgeBlockCoordinate laws hadequate label → ℚ) :=
  (DirectSum.linearEquivFunOnFintype ℚ (LawValueLabel laws)
      (fun label => D.EdgeBlockCoordinate laws hadequate label → ℚ)).symm.toLinearMap.comp
    ((D.lawValueBlockProductD0 laws hadequate).comp
      (DirectSum.linearEquivFunOnFintype ℚ (LawValueLabel laws)
        (fun label =>
          D.ChartBlockCoordinate laws hadequate label → ℚ)).toLinearMap)

/-- The componentwise degree-one map on the finite direct sum of blocks. -/
def lawValueBlockDirectSumD1 [Fintype Source] (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source) (hadequate : laws.Adequate q) :
    (⨁ label : LawValueLabel laws,
      D.EdgeBlockCoordinate laws hadequate label → ℚ) →ₗ[ℚ]
    (⨁ label : LawValueLabel laws,
      D.FaceBlockCoordinate laws hadequate label → ℚ) :=
  (DirectSum.linearEquivFunOnFintype ℚ (LawValueLabel laws)
      (fun label => D.FaceBlockCoordinate laws hadequate label → ℚ)).symm.toLinearMap.comp
    ((D.lawValueBlockProductD1 laws hadequate).comp
      (DirectSum.linearEquivFunOnFintype ℚ (LawValueLabel laws)
        (fun label =>
          D.EdgeBlockCoordinate laws hadequate label → ℚ)).toLinearMap)

/-- The original degree-zero differential is the direct sum of the block maps. -/
theorem lawGeneratedD0_block_intertwining [Fintype Source]
    (D : TargetSupportedNerve q) (laws : FiniteLawFamily Source)
    (hadequate : laws.Adequate q)
    (cochain : D.ChartCoordinate laws hadequate → ℚ) :
    D.lawValueBlockDirectSumD0 laws hadequate
        (D.chartCochainBlockEquiv laws hadequate cochain) =
      D.edgeCochainBlockEquiv laws hadequate
        (D.lawGeneratedD0 laws hadequate cochain) := by
  apply (DirectSum.linearEquivFunOnFintype ℚ (LawValueLabel laws)
    (fun label => D.EdgeBlockCoordinate laws hadequate label → ℚ)).injective
  funext label coordinate
  rfl

/-- The original degree-one differential is the direct sum of the block maps. -/
theorem lawGeneratedD1_block_intertwining [Fintype Source]
    (D : TargetSupportedNerve q) (laws : FiniteLawFamily Source)
    (hadequate : laws.Adequate q)
    (cochain : D.EdgeCoordinate laws hadequate → ℚ) :
    D.lawValueBlockDirectSumD1 laws hadequate
        (D.edgeCochainBlockEquiv laws hadequate cochain) =
      D.faceCochainBlockEquiv laws hadequate
        (D.lawGeneratedD1 laws hadequate cochain) := by
  apply (DirectSum.linearEquivFunOnFintype ℚ (LawValueLabel laws)
    (fun label => D.FaceBlockCoordinate laws hadequate label → ℚ)).injective
  funext label coordinate
  rfl

end TargetSupportedNerve

/-! ## Label preservation by the generated comparison transport -/

namespace TargetSupportedNerveMorphism

variable {coarseReading fineReading : Reading Source}
variable {hcoarser : coarseReading.CoarserThan fineReading}
variable {coarse : TargetSupportedNerve coarseReading}
variable {fine : TargetSupportedNerve fineReading}

/-- Canonical chart-coordinate transport preserves the common label. -/
theorem chartCoordinateMap_lawValueLabel
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine)
    (laws : FiniteLawFamily Source)
    (hcoarse : laws.Adequate coarseReading)
    (hfine : laws.Adequate fineReading)
    (coordinate : fine.ChartCoordinate laws hfine) :
    (M.chartCoordinateMap laws hcoarse hfine coordinate).lawValueLabel laws
        coarseReading hcoarse coarse.nerve.Chart coarse.chartSupport =
      coordinate.lawValueLabel laws fineReading hfine fine.nerve.Chart
        fine.chartSupport := by
  apply LawValueLabel.ext
  · rfl
  · rfl

/-- Canonical mapped-edge coordinate transport preserves the common label. -/
theorem edgeCoordinateMap_lawValueLabel
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine)
    (laws : FiniteLawFamily Source)
    (hcoarse : laws.Adequate coarseReading)
    (hfine : laws.Adequate fineReading)
    (coordinate : fine.EdgeCoordinate laws hfine)
    (coarseEdge : coarse.nerve.EdgeComponent)
    (hmap : M.edgeMap coordinate.cell = some coarseEdge) :
    (M.edgeCoordinateMap laws hcoarse hfine coordinate coarseEdge hmap).lawValueLabel
        laws coarseReading hcoarse coarse.nerve.EdgeComponent coarse.edgeSupport =
      coordinate.lawValueLabel laws fineReading hfine fine.nerve.EdgeComponent
        fine.edgeSupport := by
  apply LawValueLabel.ext
  · rfl
  · rfl

/-- Canonical mapped-face coordinate transport preserves the common label. -/
theorem faceCoordinateMap_lawValueLabel
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine)
    (laws : FiniteLawFamily Source)
    (hcoarse : laws.Adequate coarseReading)
    (hfine : laws.Adequate fineReading)
    (coordinate : fine.FaceCoordinate laws hfine)
    (coarseFace : coarse.nerve.FaceComponent)
    (hmap : M.faceMap coordinate.cell = some coarseFace) :
    (M.faceCoordinateMap laws hcoarse hfine coordinate coarseFace hmap).lawValueLabel
        laws coarseReading hcoarse coarse.nerve.FaceComponent coarse.faceSupport =
      coordinate.lawValueLabel laws fineReading hfine fine.nerve.FaceComponent
        fine.faceSupport := by
  apply LawValueLabel.ext
  · rfl
  · rfl

end TargetSupportedNerveMorphism

end AAT.AG.ResolutionInvariance

#assert_standard_axioms_only AAT.AG.ResolutionInvariance
