import ResearchLean.AG.ResolutionInvariance.ResolutionInvarianceConditions
import Formal.Util.AssertStandardAxioms

/-!
# Fiber periods of exact law-value block cocycles

This module connects the local rational condition C3 to the actual block
differential from the generated K0/K1 complex.  A discrete Stokes calculation
first shows that a genuine block cocycle annihilates every oriented block-face
chain.  Eliminating the C3 filling existential then shows that it annihilates
every rational cycle supported in one coordinate fiber.

The result removes the local period obstruction needed for the later
surjectivity proof.  It does not select or store a filling, primitive, path, or
inverse, and it does not claim that a primitive or an H1 preimage already
exists.
-/

noncomputable section

namespace AAT.AG.ResolutionInvariance

open BigOperators CanonicalResolution TwoPhase

universe u

variable {Source : Type u}

/-- Module-local exact-block edge finiteness, derived from the canonical
coordinate subnerve instance fixed in Cycle 14. -/
noncomputable local instance exactBlockEdgeFintype [Fintype Source]
    {q : Reading Source}
    (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source)
    (hadequate : laws.Adequate q)
    (label : LawValueLabel laws) :
    Fintype (D.EdgeBlockCoordinate laws hadequate label) := by
  change Fintype
    (D.lawValueCoordinateSubnerve laws hadequate label).EdgeComponent
  infer_instance

/-- Module-local exact-block face finiteness, derived from the canonical
coordinate subnerve instance fixed in Cycle 14. -/
noncomputable local instance exactBlockFaceFintype [Fintype Source]
    {q : Reading Source}
    (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source)
    (hadequate : laws.Adequate q)
    (label : LawValueLabel laws) :
    Fintype (D.FaceBlockCoordinate laws hadequate label) := by
  change Fintype
    (D.lawValueCoordinateSubnerve laws hadequate label).FaceComponent
  infer_instance

namespace TargetSupportedNerve

variable {q : Reading Source}

/-- Discrete Stokes on one exact law-value block: an actual block cocycle
annihilates the oriented edge chain generated by every rational face chain. -/
theorem lawValueBlockCycle_annihilates_coordinateFaceBoundary [Fintype Source]
    (D : TargetSupportedNerve q)
    (laws : FiniteLawFamily Source)
    (hadequate : laws.Adequate q)
    (label : LawValueLabel laws)
    (cycle : LinearMap.ker (D.lawValueBlockComplex laws hadequate label).d1)
    (faces : D.FaceBlockCoordinate laws hadequate label → ℚ) :
    ∑ edge,
        TargetSupportedNerveMorphism.coordinateFaceBoundary
            laws hadequate D label faces edge * cycle.1 edge = 0 := by
  classical
  have hcycle (face : D.FaceBlockCoordinate laws hadequate label) :
      cycle.1 (D.faceEdge0BlockCoordinate laws hadequate label face) -
          cycle.1 (D.faceEdge1BlockCoordinate laws hadequate label face) +
        cycle.1 (D.faceEdge2BlockCoordinate laws hadequate label face) = 0 := by
    have hvalue := congrFun cycle.2 face
    exact hvalue
  have hsum0 :
      (∑ edge,
          (∑ face,
              if D.faceEdge0BlockCoordinate laws hadequate label face = edge then
                faces face
              else 0) * cycle.1 edge) =
        ∑ face, faces face *
          cycle.1 (D.faceEdge0BlockCoordinate laws hadequate label face) := by
    calc
      (∑ edge,
          (∑ face,
              if D.faceEdge0BlockCoordinate laws hadequate label face = edge then
                faces face
              else 0) * cycle.1 edge) =
          ∑ edge, ∑ face,
            (if D.faceEdge0BlockCoordinate laws hadequate label face = edge then
              faces face
            else 0) * cycle.1 edge := by
              apply Finset.sum_congr rfl
              intro edge _
              rw [Finset.sum_mul]
      _ = ∑ face, ∑ edge,
          (if D.faceEdge0BlockCoordinate laws hadequate label face = edge then
            faces face
          else 0) * cycle.1 edge := Finset.sum_comm
      _ = ∑ face, faces face *
          cycle.1 (D.faceEdge0BlockCoordinate laws hadequate label face) := by
            apply Finset.sum_congr rfl
            intro face _
            simp
  have hsum1 :
      (∑ edge,
          (∑ face,
              if D.faceEdge1BlockCoordinate laws hadequate label face = edge then
                faces face
              else 0) * cycle.1 edge) =
        ∑ face, faces face *
          cycle.1 (D.faceEdge1BlockCoordinate laws hadequate label face) := by
    calc
      (∑ edge,
          (∑ face,
              if D.faceEdge1BlockCoordinate laws hadequate label face = edge then
                faces face
              else 0) * cycle.1 edge) =
          ∑ edge, ∑ face,
            (if D.faceEdge1BlockCoordinate laws hadequate label face = edge then
              faces face
            else 0) * cycle.1 edge := by
              apply Finset.sum_congr rfl
              intro edge _
              rw [Finset.sum_mul]
      _ = ∑ face, ∑ edge,
          (if D.faceEdge1BlockCoordinate laws hadequate label face = edge then
            faces face
          else 0) * cycle.1 edge := Finset.sum_comm
      _ = ∑ face, faces face *
          cycle.1 (D.faceEdge1BlockCoordinate laws hadequate label face) := by
            apply Finset.sum_congr rfl
            intro face _
            simp
  have hsum2 :
      (∑ edge,
          (∑ face,
              if D.faceEdge2BlockCoordinate laws hadequate label face = edge then
                faces face
              else 0) * cycle.1 edge) =
        ∑ face, faces face *
          cycle.1 (D.faceEdge2BlockCoordinate laws hadequate label face) := by
    calc
      (∑ edge,
          (∑ face,
              if D.faceEdge2BlockCoordinate laws hadequate label face = edge then
                faces face
              else 0) * cycle.1 edge) =
          ∑ edge, ∑ face,
            (if D.faceEdge2BlockCoordinate laws hadequate label face = edge then
              faces face
            else 0) * cycle.1 edge := by
              apply Finset.sum_congr rfl
              intro edge _
              rw [Finset.sum_mul]
      _ = ∑ face, ∑ edge,
          (if D.faceEdge2BlockCoordinate laws hadequate label face = edge then
            faces face
          else 0) * cycle.1 edge := Finset.sum_comm
      _ = ∑ face, faces face *
          cycle.1 (D.faceEdge2BlockCoordinate laws hadequate label face) := by
            apply Finset.sum_congr rfl
            intro face _
            simp
  change
    (∑ edge,
      ((∑ face,
          if D.faceEdge0BlockCoordinate laws hadequate label face = edge then
            faces face
          else 0) -
        (∑ face,
          if D.faceEdge1BlockCoordinate laws hadequate label face = edge then
            faces face
          else 0) +
        ∑ face,
          if D.faceEdge2BlockCoordinate laws hadequate label face = edge then
            faces face
          else 0) * cycle.1 edge) = 0
  simp only [sub_mul, add_mul, Finset.sum_sub_distrib,
    Finset.sum_add_distrib]
  rw [hsum0, hsum1, hsum2]
  calc
    (∑ face, faces face *
          cycle.1 (D.faceEdge0BlockCoordinate laws hadequate label face)) -
        (∑ face, faces face *
          cycle.1 (D.faceEdge1BlockCoordinate laws hadequate label face)) +
      ∑ face, faces face *
        cycle.1 (D.faceEdge2BlockCoordinate laws hadequate label face) =
        ∑ face, faces face *
          (cycle.1 (D.faceEdge0BlockCoordinate laws hadequate label face) -
            cycle.1 (D.faceEdge1BlockCoordinate laws hadequate label face) +
            cycle.1 (D.faceEdge2BlockCoordinate laws hadequate label face)) := by
              simp only [mul_sub, mul_add, Finset.sum_sub_distrib,
                Finset.sum_add_distrib]
    _ = 0 := by
      apply Finset.sum_eq_zero
      intro face _
      rw [hcycle face, mul_zero]

end TargetSupportedNerve

namespace TargetSupportedNerveMorphism

variable {coarseReading fineReading : Reading Source}
variable {hcoarser : coarseReading.CoarserThan fineReading}
variable {coarse : TargetSupportedNerve coarseReading}
variable {fine : TargetSupportedNerve fineReading}

/-- C3 removes every rational period obstruction in one coordinate fiber:
each actual fine block cocycle annihilates every coordinate-fiber cycle. -/
theorem lawValueBlockCycle_annihilates_coordinateFiberCycle [Fintype Source]
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine)
    (laws : FiniteLawFamily Source)
    (hcoarse : laws.Adequate coarseReading)
    (hfine : laws.Adequate fineReading)
    (label : LawValueLabel laws)
    (hC3 : M.ConditionC3At laws hcoarse hfine label)
    (cycle :
      LinearMap.ker (fine.lawValueBlockComplex laws hfine label).d1)
    (coarseChart : coarse.ChartBlockCoordinate laws hcoarse label)
    (chain : fine.EdgeBlockCoordinate laws hfine label → ℚ)
    (hchain :
      M.CoordinateFiberCycle laws hcoarse hfine label coarseChart chain) :
    ∑ edge, chain edge * cycle.1 edge = 0 := by
  obtain ⟨faces, _hfacesSupport, hboundary⟩ :=
    hC3 coarseChart chain hchain
  calc
    (∑ edge, chain edge * cycle.1 edge) =
        ∑ edge,
          coordinateFaceBoundary laws hfine fine label faces edge *
            cycle.1 edge := by
              apply Finset.sum_congr rfl
              intro edge _
              rw [hboundary edge]
    _ = 0 :=
      fine.lawValueBlockCycle_annihilates_coordinateFaceBoundary laws hfine
        label cycle faces

end TargetSupportedNerveMorphism

end AAT.AG.ResolutionInvariance

#assert_standard_axioms_only AAT.AG.ResolutionInvariance
