import ResearchLean.AG.VisibleCycleReflection.FiniteInputTable
import ResearchLean.AG.VisibleCycleReflection.FinitePathSearch
import Formal.Util.AssertStandardAxioms

/-!
# Finite bridge and reflection search on the original raw table

## Implementation notes

The scan orders source-generated labels before every actual ordered intersection
edge. An invisible edge is tested by enumerating a path after its deletion. A
failure contains that computed path and the exact label and edge codes; its cycle
and symbolic primitive transition are deterministic interpretations of these data.
-/

namespace AAT.AG.VisibleCycleReflection.FiniteInputTable
variable (T : FiniteInputTable)

/-- The original ordered raw intersection is an edge of the same raw graph. -/
def rawGraphEdge (e : T.RawEdge) : Graph.Edge T.rawGraph :=
  ⟨e.val,e.property.1,(T.rawGraph_adj _ _).mpr ⟨ne_of_lt e.property.1,e.property.2⟩⟩

/-- Raw graph edge conversion retains both endpoint codes. -/
@[simp] theorem rawGraphEdge_val (e : T.RawEdge) : (T.rawGraphEdge e).val = e.val := rfl

/-- Search the deleted graph using the bounded finite path enumerator. -/
def deletedPath (e : T.RawEdge) :
    Option ((Graph.withoutEdge T.rawGraph (T.rawGraphEdge e)).Path e.val.1 e.val.2) :=
  FinitePathSearch.findPath _ e.val.1 e.val.2

/-- Deletion search fails exactly on bridges of the original graph. -/
theorem deletedPath_none_iff (e : T.RawEdge) :
    T.deletedPath e = none ↔ T.rawGraph.IsBridge (Graph.unoriented T.rawGraph (T.rawGraphEdge e)) := by
  rw [deletedPath,FinitePathSearch.findPath_none_iff,Graph.isBridge_iff_not_reachable]
  rfl

/-- The bridge Boolean computes endpoint disconnection after deletion. -/
def bridgeTest (e : T.RawEdge) : Bool := (T.deletedPath e).isNone

/-- The computed bridge agrees with the required increase in connected-component count. -/
theorem bridgeTest_true_iff (e : T.RawEdge) :
    T.bridgeTest e = true ↔ Nat.card T.rawGraph.ConnectedComponent <
      Nat.card (Graph.withoutEdge T.rawGraph (T.rawGraphEdge e)).ConnectedComponent := by
  rw [bridgeTest,Option.isNone_iff_eq_none,T.deletedPath_none_iff,
    Graph.isBridge_iff_component_count]

/-- A generated raw label stores only its code and a membership proof from the finite list. -/
abbrev GeneratedRawLabel := {r : T.RawLabel // r ∈ T.rawLabels}

/-- The runtime failure data is generated by visibility checking and deleted-path search. -/
structure SearchFailure where
  label : T.GeneratedRawLabel
  edge : T.RawEdge
  invisible : ¬T.EdgeVisible label.val edge.val
  path : (Graph.withoutEdge T.rawGraph (T.rawGraphEdge edge)).Path edge.val.1 edge.val.2

/-- The returned deleted path generates this exact closed raw walk. -/
def SearchFailure.cycle (f : T.SearchFailure) : T.rawGraph.Walk f.edge.val.2 f.edge.val.2 :=
  Graph.cycleOfPath _ (T.rawGraphEdge f.edge) f.path

/-- The failure transition is an explicit integral coordinate table, supported on one edge and label. -/
def SearchFailure.transition (f : T.SearchFailure) (e : T.RawEdge) (r : T.RawLabel) : ℤ :=
  if e = f.edge then if r = f.label.val then 1 else 0 else 0

/-- The failure local-state table is zero at all charts and generated labels. -/
def SearchFailure.localState (_f : T.SearchFailure) (_i : T.Chart) (_r : T.RawLabel) : ℤ := 0

/-- A finite output tuple containing the generated codes, cycle vertices, and full integral local data. -/
structure FailureOutput where
  label : T.RawLabel
  edge : T.Chart × T.Chart
  cycle : List T.Chart
  transition : List (T.RawEdge × T.RawLabel × ℤ)
  localState : List (T.Chart × T.RawLabel × ℤ)

/-- Serialize every edge/label transition and every chart/label state from the generated failure. -/
def SearchFailure.output (f : T.SearchFailure) : T.FailureOutput where
  label := f.label.val
  edge := f.edge.val
  cycle := f.cycle.support
  transition := T.rawEdges.flatMap fun e => T.rawLabels.map fun r => (e,r,SearchFailure.transition T f e r)
  localState := (List.finRange T.chartCount).flatMap fun i =>
    T.rawLabels.map fun r => (i,r,SearchFailure.localState T f i r)

/-- The finite output retains exactly the computed label, edge, and cycle support. -/
theorem SearchFailure.output_codes (f : T.SearchFailure) :
    (SearchFailure.output T f).label = f.label.val ∧
      (SearchFailure.output T f).edge = f.edge.val ∧
      (SearchFailure.output T f).cycle = f.cycle.support := ⟨rfl,rfl,rfl⟩

/-- Every serialized transition row has exactly the computed value, and every actual row is present. -/
theorem SearchFailure.output_transition_iff (f : T.SearchFailure) (e : T.RawEdge)
    (r : T.RawLabel) (z : ℤ) :
    (e,r,z) ∈ (SearchFailure.output T f).transition ↔
      r ∈ T.rawLabels ∧ z = SearchFailure.transition T f e r := by
  simp only [output,List.mem_flatMap,List.mem_map,Prod.mk.injEq]
  constructor
  · rintro ⟨e',_,r',hr,he,hh,hz⟩
    subst e'; subst r'
    exact ⟨hr,hz.symm⟩
  · rintro ⟨hr,rfl⟩
    exact ⟨e,T.mem_rawEdges e,r,hr,rfl,rfl,rfl⟩

/-- Every chart/label state row is present and has the exact serialized zero value. -/
theorem SearchFailure.output_state_iff (f : T.SearchFailure) (i : T.Chart)
    (r : T.RawLabel) (z : ℤ) :
    (i,r,z) ∈ (SearchFailure.output T f).localState ↔ r ∈ T.rawLabels ∧ z = 0 := by
  simp only [output,localState,List.mem_flatMap,List.mem_map,Prod.mk.injEq,List.mem_finRange,true_and]
  constructor
  · rintro ⟨i',r',hr,hi,hh,hz⟩
    subst i'; subst r'
    exact ⟨hr,hz.symm⟩
  · rintro ⟨hr,rfl⟩
    exact ⟨i,r,hr,rfl,rfl,rfl⟩

/-- At one pair, return the generated path precisely when the edge is invisible and not a bridge. -/
def failureAt (r : T.GeneratedRawLabel) (e : T.RawEdge) : Option T.SearchFailure :=
  if hv : T.EdgeVisible r.val e.val then none else
    (T.deletedPath e).map (fun p => ⟨r,e,hv,p⟩)

/-- Failure search at a pair returns none exactly when visibility or bridge status makes it harmless. -/
theorem failureAt_none_iff (r : T.GeneratedRawLabel) (e : T.RawEdge) :
    T.failureAt r e = none ↔ T.EdgeVisible r.val e.val ∨
      T.rawGraph.IsBridge (Graph.unoriented T.rawGraph (T.rawGraphEdge e)) := by
  unfold failureAt
  split_ifs with hv
  · simp [hv]
  · simp only [Option.map_eq_none_iff,T.deletedPath_none_iff,hv,false_or]

/-- Enumerate all generated labels and every actual intersection edge in table order. -/
def searchPairs : List (T.GeneratedRawLabel × T.RawEdge) :=
  T.rawLabels.attach.flatMap fun r => T.rawEdges.map fun e => (r,e)

/-- Every relevant label/edge pair occurs in the finite scan. -/
theorem mem_searchPairs (r : T.GeneratedRawLabel) (e : T.RawEdge) :
    (r,e) ∈ T.searchPairs := by
  simp only [searchPairs,List.mem_flatMap,List.mem_map]
  exact ⟨r,List.mem_attach _ r,e,T.mem_rawEdges e,rfl⟩

/-- Return the first failure generated by the finite table scan. -/
def searchFailure : Option T.SearchFailure :=
  T.searchPairs.findSome? fun pair => T.failureAt pair.1 pair.2

/-- The raw B3 predicate quantifies every generated label and every actual raw edge. -/
def RawNonbridgeVisible : Prop :=
  ∀ r : T.GeneratedRawLabel, ∀ e : T.RawEdge,
    ¬T.rawGraph.IsBridge (Graph.unoriented T.rawGraph (T.rawGraphEdge e)) →
      T.EdgeVisible r.val e.val

/-- Finite scan success is equivalent to the complete raw nonbridge visibility condition. -/
theorem searchFailure_none_iff : T.searchFailure = none ↔ T.RawNonbridgeVisible := by
  rw [searchFailure,List.findSome?_eq_none_iff]
  constructor
  · intro h r e he
    rcases (T.failureAt_none_iff r e).mp (h (r,e) (T.mem_searchPairs r e)) with hv | hb
    · exact hv
    · exact False.elim (he hb)
  · intro h pair _
    apply (T.failureAt_none_iff pair.1 pair.2).mpr
    by_cases hb : T.rawGraph.IsBridge (Graph.unoriented T.rawGraph (T.rawGraphEdge pair.2))
    · exact Or.inr hb
    · exact Or.inl (h pair.1 pair.2 hb)

/-- Boolean reflection success is the absence of a generated failure in the finite scan. -/
def reflectsTest : Bool := T.searchFailure.isNone

/-- The returned failure has this computed cycle's simple-cycle, once-through, and orientation evidence. -/
theorem SearchFailure.cycle_correct (f : T.SearchFailure) :
    f.cycle.IsCycle ∧ f.cycle.edges.count (Graph.unoriented T.rawGraph (T.rawGraphEdge f.edge)) = 1 ∧
      Graph.walkChain T.rawGraph f.cycle (T.rawGraphEdge f.edge) = -1 :=
  ⟨Graph.cycleOfPath_isCycle _ _ _,Graph.cycleOfPath_once _ _ _,Graph.cycleOfPath_coefficient _ _ _⟩

/-- Every returned failure certifies an actual nonbridge edge, without an existentially chosen path. -/
theorem SearchFailure.not_bridge (f : T.SearchFailure) :
    ¬T.rawGraph.IsBridge (Graph.unoriented T.rawGraph (T.rawGraphEdge f.edge)) :=
  Graph.not_bridge_of_deleted_path _ _ f.path


/-- A returned failure retains the very deleted path produced by the finite path search. -/
theorem failureAt_provenance (r : T.GeneratedRawLabel) (e : T.RawEdge) (f : T.SearchFailure)
    (hf : T.failureAt r e = some f) :
    f.label = r ∧ f.edge = e ∧ T.deletedPath f.edge = some f.path := by
  unfold failureAt at hf
  split_ifs at hf with hv
  cases hp : T.deletedPath e with
  | none => simp only [hp,Option.map_none,reduceCtorEq] at hf
  | some p =>
    simp only [hp,Option.map_some,Option.some.injEq] at hf
    cases hf
    exact ⟨rfl,rfl,hp⟩

/-- A search output comes from a listed pair and the computed deleted path, not existential choice. -/
theorem searchFailure_provenance (f : T.SearchFailure) (hf : T.searchFailure = some f) :
    (f.label,f.edge) ∈ T.searchPairs ∧ T.deletedPath f.edge = some f.path := by
  obtain ⟨pair,hpair,hf⟩ := List.exists_of_findSome?_eq_some hf
  obtain ⟨hr,he,hp⟩ := T.failureAt_provenance pair.1 pair.2 f hf
  exact ⟨by simpa only [hr,he] using hpair,hp⟩

/-- The runtime outcome distinguishes invalid T0 tables, reflection success, and generated failure data. -/
inductive SearchResult where
  | invalid
  | success
  | failure (data : T.SearchFailure)

/-- Check raw T0 first, then perform the bounded reflection scan on that same raw table. -/
def checkAndSearch : T.SearchResult :=
  if T.validate then
    match T.searchFailure with
    | none => .success
    | some f => .failure f
  else .invalid

/-- Invalid output is exactly failure of the raw finite T0 validation. -/
theorem checkAndSearch_invalid_iff : T.checkAndSearch = .invalid ↔ ¬T.Valid := by
  unfold checkAndSearch
  cases hv : T.validate
  · simpa using (T.validate_false_iff).mp hv
  · have hvalid := (T.validate_true_iff).mp hv
    cases hf : T.searchFailure <;> simp [hvalid]

/-- A validated table succeeds exactly when the finite reflection scan finds no failure. -/
theorem checkAndSearch_success_iff (h : T.Valid) :
    T.checkAndSearch = .success ↔ T.reflectsTest = true := by
  unfold checkAndSearch
  rw [(T.validate_true_iff).mpr h]
  cases hf : T.searchFailure <;> simp [reflectsTest,hf]

/-- A validated table returns this failure exactly when the finite scan returns this same failure. -/
theorem checkAndSearch_failure_iff (h : T.Valid) (f : T.SearchFailure) :
    T.checkAndSearch = .failure f ↔ T.searchFailure = some f := by
  unfold checkAndSearch
  rw [(T.validate_true_iff).mpr h]
  cases hf : T.searchFailure <;> simp

end AAT.AG.VisibleCycleReflection.FiniteInputTable
#assert_standard_axioms_only AAT.AG.VisibleCycleReflection.FiniteInputTable
