import ResearchLean.AG.VisibleCycleReflection.WitnessInputs
import Formal.Util.AssertStandardAxioms

/-!
# Cycle and support evaluations used by the specified actual witnesses

## Implementation notes

The public cycle coefficient and support evaluations preserve the accepted
owners' definitions. A positive once-through coefficient has plus the original
primitive basis as its period, complementing the negative orientation already
proved for the computed failure cycle.
-/

noncomputable section
namespace AAT.AG.VisibleCycleReflection
open CanonicalResolution ResolutionInvariance ObstructionDiagnosticBridge
universe u
namespace Graph
variable {V : Type u} [LinearOrder V] [Fintype V] (G : SimpleGraph V)
/-- The standard H1 element generated by a closed walk has its original signed chain coefficients. -/
@[simp] theorem closedWalkH1_value {a : V} (p : G.Walk a a) :
    (closedWalkH1 G p).val = walkChain G p := rfl
end Graph
namespace GeometricCover
variable {Source X I : Type u} [Fintype Source] [TopologicalSpace X] [LinearOrder I] [Fintype I]
variable {laws : FiniteLawFamily Source} {q : Reading Source}
variable (K : GeometricCover X I) (target : I → Set q.Target) (hne : ∀ i, (target i).Nonempty)
omit [Fintype Source] in
/-- The target-supported nerve retains exactly the separately supplied chart target column. -/
@[simp] theorem supportedNerve_chartSupport (i : I) :
    (K.supportedNerve target hne).chartSupport i = target i := rfl
variable (P : GeneratorPresentation laws) (hR : P.ReflectionCondition)
/-- A positive once-through cycle has period plus the original primitive basis. -/
theorem singleEdgeData_period_one (label : LawValueLabel laws) (edge : Graph.Edge K.graph)
    {a b : I} (p : K.graph.Walk a b) (hp : Graph.walkChain K.graph p edge = 1) :
    K.actualTransitionPeriod target hne P (K.singleEdgeData target hne P hR label edge) p =
      labelBasis P hR label := by
  classical
  rw [actualTransitionPeriod_apply]
  apply P.coefficientComparison_injective hR
  ext current
  change P.coefficientComparison
    (Graph.walkPeriod K.graph (fun e => P.faceEmptyCechCochain1Equiv
      (K.actualCechCover P target hne)
      (K.singleEdgeData target hne P hR label edge).transition (K.graphEdgeEquiv.symm e)) p) current = _
  have h := Graph.map_walkPeriod K.graph
    ((Pi.evalAddMonoidHom (fun _ : LawValueLabel laws => ℚ) current).comp P.coefficientComparison)
    (fun e => P.faceEmptyCechCochain1Equiv (K.actualCechCover P target hne)
      (K.singleEdgeData target hne P hR label edge).transition (K.graphEdgeEquiv.symm e)) p
  change P.coefficientComparison _ current = _ at h
  rw [h]
  simp_rw [singleEdgeData_transition_value]
  simp only [AddMonoidHom.comp_apply,Pi.evalAddMonoidHom_apply] at *
  change (∑ e, Graph.walkChain K.graph p e *
    P.coefficientComparison (if e = edge then labelBasis P hR label else 0) current) = _
  have hf : ∀ e : Graph.Edge K.graph,
      P.coefficientComparison (if e = edge then labelBasis P hR label else 0) current =
        if e = edge then if current = label then 1 else 0 else 0 := by
    intro e
    by_cases he : e = edge <;> simp [he,coefficientComparison_labelBasis]
  simp_rw [hf]
  by_cases hc : current = label
  · subst current
    simp [coefficientComparison_labelBasis,hp]
  · simp [coefficientComparison_labelBasis,hc]
end GeometricCover
namespace FiniteInputTable
variable (T : FiniteInputTable)
/-- The actual edge constructor is precisely transport of the same finite original edge. -/
theorem actualEdge_transport (h : T.Valid) (e : T.RawEdge) :
    letI : TopologicalSpace T.Point := T.actualTopology h
    T.actualEdge h e = Graph.transportEdge (T.actualGeometry_graph h).symm (T.rawGraphEdge e) := rfl
/-- The actual decoded edge retains the exact original endpoint column. -/
@[simp] theorem actualEdge_val (h : T.Valid) (e : T.RawEdge) :
    (T.actualEdge h e).val = e.val := by
  letI : TopologicalSpace T.Point := T.actualTopology h
  rw [T.actualEdge_transport,Graph.transportEdge_val,T.rawGraphEdge_val]
/-- The retained failure restores the original actual single-edge primitive data. -/
theorem SearchFailure.actualInput_singleEdgeData (f : T.SearchFailure) (h : T.Valid) :
    letI : TopologicalSpace T.Point := T.actualTopology h
    SearchFailure.actualInput T f h = (T.actualGeometry h).singleEdgeData
      (T.actualTarget h) (T.actualTarget_nonempty h) (T.actualPresentation h)
      (T.actualReflectionCondition h) (T.actualLabel f.label) (T.actualEdge h f.edge) := rfl
end FiniteInputTable
end AAT.AG.VisibleCycleReflection
#assert_standard_axioms_only AAT.AG.VisibleCycleReflection
