import Mathlib.Combinatorics.SimpleGraph.Connectivity.WalkCounting
import ResearchLean.AG.UniformInvariance.ConditionCAllA
import ResearchLean.AG.UniformInvariance.PresentationASubnerveDefect
import Formal.Util.AssertStandardAxioms

/-!
# Executable checker for Condition C on every target subnerve

This module discharges the executable-checker obligation in claim (iii) of
`G-107-aat-uniform-invariance-characterization`.  It reads only the finite raw
tables of a `FiniteComparisonPresentation`.  Finite graph reachability decides
C1, while exact rational ranks of the fiber boundary maps decide C3.

The checker does not evaluate the semantic proposition with `Classical.dec`,
and the presentation stores no condition bit, path, filling chain, matrix,
rank, or checker result.  Correctness is proved by transporting the raw cells
to the actual canonical A-subnerves generated by `toGeometry`.
-/

namespace AAT.AG.ResolutionInvariance

open CanonicalResolution BigOperators
open ExecutableRationalLinearAlgebra

universe u

/-! ## A rank criterion for a finite two-step chain complex -/

namespace ExecutableRationalLinearAlgebra

/-- For a finite two-step complex over `ℚ`, exactness in the middle is
equivalent to the sum of the two executable ranks being the number of middle
basis vectors. -/
theorem ker_le_range_iff_finrank_range_add_eq_card
    {F E V : Type*} [Fintype F] [Fintype E] [Fintype V]
    (boundaryTwo : (F → ℚ) →ₗ[ℚ] (E → ℚ))
    (boundaryOne : (E → ℚ) →ₗ[ℚ] (V → ℚ))
    (hcomplex : boundaryOne.comp boundaryTwo = 0) :
    (∀ chain, boundaryOne chain = 0 →
        ∃ faces, boundaryTwo faces = chain) ↔
      Module.finrank ℚ (LinearMap.range boundaryOne) +
          Module.finrank ℚ (LinearMap.range boundaryTwo) =
        Fintype.card E := by
  have hrangeKer : LinearMap.range boundaryTwo ≤ LinearMap.ker boundaryOne := by
    rintro chain ⟨faces, rfl⟩
    change boundaryOne (boundaryTwo faces) = 0
    have happly := LinearMap.congr_fun hcomplex faces
    simpa using happly
  have hrankNullity := LinearMap.finrank_range_add_finrank_ker boundaryOne
  rw [Module.finrank_fintype_fun_eq_card] at hrankNullity
  constructor
  · intro hexact
    have hkerRange : LinearMap.ker boundaryOne ≤ LinearMap.range boundaryTwo := by
      intro chain hchain
      obtain ⟨faces, hfaces⟩ := hexact chain hchain
      exact ⟨faces, hfaces⟩
    have heq : LinearMap.ker boundaryOne = LinearMap.range boundaryTwo :=
      le_antisymm hkerRange hrangeKer
    rw [heq] at hrankNullity
    exact hrankNullity
  · intro hranks chain hchain
    have hfinrank :
        Module.finrank ℚ (LinearMap.range boundaryTwo) =
          Module.finrank ℚ (LinearMap.ker boundaryOne) := by
      omega
    have heq : LinearMap.range boundaryTwo = LinearMap.ker boundaryOne :=
      Submodule.eq_of_le_of_finrank_eq hrangeKer hfinrank
    have : chain ∈ LinearMap.range boundaryTwo := by
      rw [heq]
      exact hchain
    exact this

end ExecutableRationalLinearAlgebra

namespace FiniteComparisonPresentation

/-- Every finite coarse-target subset is the finite set underlying a sublist
of the presentation's explicit target enumeration.  This local coverage API
keeps the Condition C checker independent of the uniformity decider. -/
theorem exists_conditionC_sublists_toFinset_eq
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    ∃ targets ∈ P.coarseTargetEntries.sublists, targets.toFinset = A := by
  let targets := P.coarseTargetEntries.filter fun target => decide (target ∈ A)
  refine ⟨targets, List.mem_sublists.mpr List.filter_sublist, ?_⟩
  ext target
  simp [targets, P.coarseTarget_mem_coarseTargetEntries]

/-! ## Raw endpoint fibers and finite reachability -/

/-- A selected raw fine edge has both endpoint images equal to one selected
coarse chart. -/
def rawFiberEdge (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A)
    (fineEdge : P.FineEdgeIn A) : Prop :=
  P.chartMapIn A (P.fineEdgeLeftIn A fineEdge) = coarseChart ∧
    P.chartMapIn A (P.fineEdgeRightIn A fineEdge) = coarseChart

/-- Raw endpoint-fiber membership is decidable from the finite chart table. -/
instance rawFiberEdgeDecidable (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A)
    (fineEdge : P.FineEdgeIn A) :
    Decidable (P.rawFiberEdge A coarseChart fineEdge) := by
  unfold rawFiberEdge
  infer_instance

/-- A selected raw fine face all of whose three boundary edges lie in one
endpoint fiber. -/
def rawInternalFace (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A)
    (fineFace : P.FineFaceIn A) : Prop :=
  P.rawFiberEdge A coarseChart (P.fineFaceEdge0In A fineFace) ∧
    P.rawFiberEdge A coarseChart (P.fineFaceEdge1In A fineFace) ∧
      P.rawFiberEdge A coarseChart (P.fineFaceEdge2In A fineFace)

/-- Raw internal-face membership is decidable from the three finite incidence
tables and endpoint-fiber membership. -/
instance rawInternalFaceDecidable (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A)
    (fineFace : P.FineFaceIn A) :
    Decidable (P.rawInternalFace A coarseChart fineFace) := by
  unfold rawInternalFace
  infer_instance

/-- Raw undirected adjacency inside one endpoint-defined chart fiber. -/
def rawFiberAdjacent (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A)
    (left right : P.FineChartIn A) : Prop :=
  ∃ fineEdge : P.FineEdgeIn A,
    P.rawFiberEdge A coarseChart fineEdge ∧
      ((P.fineEdgeLeftIn A fineEdge = left ∧
          P.fineEdgeRightIn A fineEdge = right) ∨
        (P.fineEdgeLeftIn A fineEdge = right ∧
          P.fineEdgeRightIn A fineEdge = left))

/-- Raw fiber adjacency has a constructive decision procedure obtained by
finite search through the selected raw edge table. -/
instance rawFiberAdjacentDecidable (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A) :
    DecidableRel (P.rawFiberAdjacent A coarseChart) := by
  intro left right
  unfold rawFiberAdjacent rawFiberEdge
  infer_instance

/-- The executable simple graph underlying one raw endpoint fiber.  Removing
loops does not change reflexive-transitive reachability. -/
def fiberGraph (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A) :
    SimpleGraph (P.FineChartIn A) :=
  SimpleGraph.fromRel (P.rawFiberAdjacent A coarseChart)

/-- Adjacency in the executable fiber graph is exactly unequal raw vertices
joined by raw fiber adjacency in either orientation.  This definition-owner
API lets finite counterexamples reason about the graph without unfolding its
`SimpleGraph.fromRel` representation. -/
theorem fiberGraph_adj_iff (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A)
    (left right : P.FineChartIn A) :
    (P.fiberGraph A coarseChart).Adj left right ↔
      left ≠ right ∧
        (P.rawFiberAdjacent A coarseChart left right ∨
          P.rawFiberAdjacent A coarseChart right left) :=
  SimpleGraph.fromRel_adj _ _ _

/-- Adjacency in the raw fiber graph is constructively decidable. -/
instance fiberGraphAdjDecidable (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A) :
    DecidableRel (P.fiberGraph A coarseChart).Adj := by
  change DecidableRel
    (SimpleGraph.fromRel (P.rawFiberAdjacent A coarseChart)).Adj
  infer_instance

/-- Raw fiber adjacency is symmetric. -/
theorem rawFiberAdjacent_symm (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A)
    {left right : P.FineChartIn A}
    (hadjacent : P.rawFiberAdjacent A coarseChart left right) :
    P.rawFiberAdjacent A coarseChart right left := by
  obtain ⟨fineEdge, hfiber, hendpoints⟩ := hadjacent
  exact ⟨fineEdge, hfiber, hendpoints.elim Or.inr Or.inl⟩

/-- The raw selected chart map commutes with the canonical cell
equivalences and the actual A-subnerve chart map. -/
theorem chartMapIn_equiv_aSubnerveChartMap
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (fineChart : P.FineChartIn A) :
    P.coarseChartEquiv A (P.chartMapIn A fineChart) =
      P.toGeometry.aSubnerveChartMap (A : Set P.CoarseTarget)
        (P.fineChartEquiv A fineChart) := by
  apply Subtype.ext
  rfl

/-- Raw endpoint-fiber membership is exactly actual A-subnerve endpoint-fiber
membership under the canonical raw/semantic cell equivalences. -/
theorem rawFiberEdge_iff_targetSubsetFiberEdge
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (fineEdge : P.FineEdgeIn A) :
    P.rawFiberEdge A coarseChart fineEdge ↔
      P.toGeometry.TargetSubsetFiberEdge (A : Set P.CoarseTarget)
        (P.coarseChartEquiv A coarseChart) (P.fineEdgeEquiv A fineEdge) := by
  rw [P.toGeometry.targetSubsetFiberEdge_iff_endpoint_cells]
  constructor
  · rintro ⟨hleft, hright⟩
    have hleftVal := congrArg Subtype.val hleft
    have hrightVal := congrArg Subtype.val hright
    change P.chartMap (P.fineEdgeLeft fineEdge.1) = coarseChart.1 at hleftVal
    change P.chartMap (P.fineEdgeRight fineEdge.1) = coarseChart.1 at hrightVal
    exact ⟨hleftVal, hrightVal⟩
  · rintro ⟨hleft, hright⟩
    constructor
    · apply Subtype.ext
      exact hleft
    · apply Subtype.ext
      exact hright

/-- Raw fiber adjacency is exactly actual A-subnerve fiber adjacency under
the canonical raw/semantic cell equivalences. -/
theorem rawFiberAdjacent_iff_targetSubsetFiberAdjacent
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (left right : P.FineChartIn A) :
    P.rawFiberAdjacent A coarseChart left right ↔
      P.toGeometry.TargetSubsetFiberAdjacent (A : Set P.CoarseTarget)
        (P.coarseChartEquiv A coarseChart)
        (P.fineChartEquiv A left) (P.fineChartEquiv A right) := by
  constructor
  · rintro ⟨fineEdge, hfiber, hendpoints⟩
    refine ⟨P.fineEdgeEquiv A fineEdge,
      (P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart fineEdge).1
        hfiber, ?_⟩
    rcases hendpoints with hforward | hbackward
    · left
      constructor
      · rw [← P.fineEquiv_edgeLeft A fineEdge]
        exact congrArg (P.fineChartEquiv A) hforward.1
      · rw [← P.fineEquiv_edgeRight A fineEdge]
        exact congrArg (P.fineChartEquiv A) hforward.2
    · right
      constructor
      · rw [← P.fineEquiv_edgeLeft A fineEdge]
        exact congrArg (P.fineChartEquiv A) hbackward.1
      · rw [← P.fineEquiv_edgeRight A fineEdge]
        exact congrArg (P.fineChartEquiv A) hbackward.2
  · rintro ⟨semanticEdge, hfiber, hendpoints⟩
    let fineEdge := (P.fineEdgeEquiv A).symm semanticEdge
    refine ⟨fineEdge,
      (P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart fineEdge).2
        (by simpa [fineEdge] using hfiber), ?_⟩
    rcases hendpoints with hforward | hbackward
    · left
      constructor
      · apply (P.fineChartEquiv A).injective
        rw [P.fineEquiv_edgeLeft A fineEdge]
        simpa [fineEdge] using hforward.1
      · apply (P.fineChartEquiv A).injective
        rw [P.fineEquiv_edgeRight A fineEdge]
        simpa [fineEdge] using hforward.2
    · right
      constructor
      · apply (P.fineChartEquiv A).injective
        rw [P.fineEquiv_edgeLeft A fineEdge]
        simpa [fineEdge] using hbackward.1
      · apply (P.fineChartEquiv A).injective
        rw [P.fineEquiv_edgeRight A fineEdge]
        simpa [fineEdge] using hbackward.2

/-- Bounded reachability in the raw fiber graph is exactly the semantic
reflexive-transitive A-subnerve fiber adjacency relation. -/
theorem fiberGraph_reachable_iff_targetSubsetFiberAdjacent_reflTransGen
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (left right : P.FineChartIn A) :
    (P.fiberGraph A coarseChart).Reachable left right ↔
      Relation.ReflTransGen
        (P.toGeometry.TargetSubsetFiberAdjacent (A : Set P.CoarseTarget)
          (P.coarseChartEquiv A coarseChart))
        (P.fineChartEquiv A left) (P.fineChartEquiv A right) := by
  rw [SimpleGraph.reachable_iff_reflTransGen]
  constructor
  · intro hpath
    apply Relation.ReflTransGen.lift (P.fineChartEquiv A) _ hpath
    intro rawLeft rawRight hadjacent
    have hraw : P.rawFiberAdjacent A coarseChart rawLeft rawRight :=
      hadjacent.2.elim id (P.rawFiberAdjacent_symm A coarseChart)
    exact (P.rawFiberAdjacent_iff_targetSubsetFiberAdjacent
      A coarseChart rawLeft rawRight).1 hraw
  · intro hpath
    apply Relation.ReflTransGen.lift' (P.fineChartEquiv A).symm _ hpath
    intro semanticLeft semanticRight hadjacent
    have hraw : P.rawFiberAdjacent A coarseChart
        ((P.fineChartEquiv A).symm semanticLeft)
        ((P.fineChartEquiv A).symm semanticRight) := by
      apply (P.rawFiberAdjacent_iff_targetSubsetFiberAdjacent A coarseChart
        ((P.fineChartEquiv A).symm semanticLeft)
        ((P.fineChartEquiv A).symm semanticRight)).2
      simpa using hadjacent
    by_cases hequal :
        (P.fineChartEquiv A).symm semanticLeft =
          (P.fineChartEquiv A).symm semanticRight
    · rw [hequal]
    · exact Relation.ReflTransGen.single ⟨hequal, Or.inl hraw⟩

/-- Raw C1 on one finite target subset, using bounded finite-graph
reachability rather than a nonconstructive transitive-closure decision. -/
def RawConditionC1At (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Prop :=
  ∀ coarseChart : P.CoarseChartIn A,
    (∃ fineChart : P.FineChartIn A,
      P.chartMapIn A fineChart = coarseChart) ∧
    ∀ left right : P.FineChartIn A,
      P.chartMapIn A left = coarseChart →
      P.chartMapIn A right = coarseChart →
      (P.fiberGraph A coarseChart).Reachable left right

/-- Raw finite C1 is constructively decidable by finite quantification and
the bounded-walk reachability instance of `fiberGraph`. -/
instance rawConditionC1AtDecidable (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Decidable (P.RawConditionC1At A) := by
  unfold RawConditionC1At
  infer_instance

/-- Executable raw C1 check on one target subset. -/
def conditionC1AtTargetSubsetCheck (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Bool :=
  decide (P.RawConditionC1At A)

/-- Raw bounded C1 is equivalent to C1 on the actual canonical A-subnerve. -/
theorem rawConditionC1At_iff_conditionC1AtTargetSubset
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.RawConditionC1At A ↔
      P.toGeometry.ConditionC1AtTargetSubset (A : Set P.CoarseTarget) := by
  constructor
  · intro hraw semanticCoarseChart
    let coarseChart := (P.coarseChartEquiv A).symm semanticCoarseChart
    obtain ⟨⟨rawFineChart, hrawMap⟩, hrawConnected⟩ := hraw coarseChart
    constructor
    · refine ⟨P.fineChartEquiv A rawFineChart, ?_⟩
      rw [← P.chartMapIn_equiv_aSubnerveChartMap A rawFineChart]
      simpa [coarseChart] using congrArg (P.coarseChartEquiv A) hrawMap
    · intro semanticLeft semanticRight hleftMap hrightMap
      let rawLeft := (P.fineChartEquiv A).symm semanticLeft
      let rawRight := (P.fineChartEquiv A).symm semanticRight
      have hrawLeft : P.chartMapIn A rawLeft = coarseChart := by
        apply (P.coarseChartEquiv A).injective
        rw [P.chartMapIn_equiv_aSubnerveChartMap A rawLeft]
        simpa [rawLeft, coarseChart] using hleftMap
      have hrawRight : P.chartMapIn A rawRight = coarseChart := by
        apply (P.coarseChartEquiv A).injective
        rw [P.chartMapIn_equiv_aSubnerveChartMap A rawRight]
        simpa [rawRight, coarseChart] using hrightMap
      have hreachable := hrawConnected rawLeft rawRight hrawLeft hrawRight
      simpa [rawLeft, rawRight, coarseChart] using
        (P.fiberGraph_reachable_iff_targetSubsetFiberAdjacent_reflTransGen
          A coarseChart rawLeft rawRight).1 hreachable
  · intro hsemantic coarseChart
    obtain ⟨⟨semanticFineChart, hsemanticMap⟩, hsemanticConnected⟩ :=
      hsemantic (P.coarseChartEquiv A coarseChart)
    let fineChart := (P.fineChartEquiv A).symm semanticFineChart
    constructor
    · refine ⟨fineChart, ?_⟩
      apply (P.coarseChartEquiv A).injective
      rw [P.chartMapIn_equiv_aSubnerveChartMap A fineChart]
      simpa [fineChart] using hsemanticMap
    · intro rawLeft rawRight hleftMap hrightMap
      have hsemanticLeft :
          P.toGeometry.aSubnerveChartMap (A : Set P.CoarseTarget)
              (P.fineChartEquiv A rawLeft) =
            P.coarseChartEquiv A coarseChart := by
        rw [← P.chartMapIn_equiv_aSubnerveChartMap A rawLeft]
        exact congrArg (P.coarseChartEquiv A) hleftMap
      have hsemanticRight :
          P.toGeometry.aSubnerveChartMap (A : Set P.CoarseTarget)
              (P.fineChartEquiv A rawRight) =
            P.coarseChartEquiv A coarseChart := by
        rw [← P.chartMapIn_equiv_aSubnerveChartMap A rawRight]
        exact congrArg (P.coarseChartEquiv A) hrightMap
      apply (P.fiberGraph_reachable_iff_targetSubsetFiberAdjacent_reflTransGen
        A coarseChart rawLeft rawRight).2
      exact hsemanticConnected _ _ hsemanticLeft hsemanticRight

/-- The executable finite C1 check is sound and complete for actual
A-subnerve C1. -/
theorem conditionC1AtTargetSubsetCheck_eq_true_iff
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.conditionC1AtTargetSubsetCheck A = true ↔
      P.toGeometry.ConditionC1AtTargetSubset (A : Set P.CoarseTarget) := by
  rw [conditionC1AtTargetSubsetCheck, decide_eq_true_iff]
  exact P.rawConditionC1At_iff_conditionC1AtTargetSubset A

/-! ## Direct finite checks for C0, C2, C4, C5, and C6 -/

/-- Raw finite C0, stated only with the support tables, raw chart map, and
executable comparison factor. -/
def RawConditionC0 (P : FiniteComparisonPresentation) : Prop :=
  ∀ coarseChart coarseTarget,
    coarseTarget ∈ P.coarseChartSupport coarseChart ↔
      ∃ fineChart fineTarget,
        P.chartMap fineChart = coarseChart ∧
        fineTarget ∈ P.fineChartSupport fineChart ∧
        P.computedFactor fineTarget = coarseTarget

/-- Raw finite C2 on one selected target subset. -/
def RawConditionC2At (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Prop :=
  ∀ coarseEdge : P.CoarseEdgeIn A,
    ∃ fineEdge : P.FineEdgeIn A,
      P.edgeMap fineEdge.1 = some coarseEdge.1

/-- Raw finite C4 on one selected target subset. -/
def RawConditionC4At (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Prop :=
  ∀ coarseFace : P.CoarseFaceIn A,
    ∃ fineFace : P.FineFaceIn A,
      P.faceMap fineFace.1 = some coarseFace.1

/-- Raw finite C5, requiring uniqueness of every declared edge lift. -/
def RawConditionC5 (P : FiniteComparisonPresentation) : Prop :=
  ∀ coarseEdge fineLeft fineRight,
    P.edgeMap fineLeft = some coarseEdge →
    P.edgeMap fineRight = some coarseEdge →
    fineLeft = fineRight

/-- Raw finite C6, reflecting every mapped coarse self-loop to a fine
self-loop. -/
def RawConditionC6 (P : FiniteComparisonPresentation) : Prop :=
  ∀ fineEdge coarseEdge,
    P.edgeMap fineEdge = some coarseEdge →
    P.coarseEdgeLeft coarseEdge = P.coarseEdgeRight coarseEdge →
    P.fineEdgeLeft fineEdge = P.fineEdgeRight fineEdge

/-- Raw finite C0 is constructively decidable. -/
instance rawConditionC0Decidable (P : FiniteComparisonPresentation) :
    Decidable P.RawConditionC0 := by
  unfold RawConditionC0
  infer_instance

/-- Raw finite C2 is constructively decidable. -/
instance rawConditionC2AtDecidable (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Decidable (P.RawConditionC2At A) := by
  unfold RawConditionC2At
  infer_instance

/-- Raw finite C4 is constructively decidable. -/
instance rawConditionC4AtDecidable (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Decidable (P.RawConditionC4At A) := by
  unfold RawConditionC4At
  infer_instance

/-- Raw finite C5 is constructively decidable. -/
instance rawConditionC5Decidable (P : FiniteComparisonPresentation) :
    Decidable P.RawConditionC5 := by
  unfold RawConditionC5
  infer_instance

/-- Raw finite C6 is constructively decidable. -/
instance rawConditionC6Decidable (P : FiniteComparisonPresentation) :
    Decidable P.RawConditionC6 := by
  unfold RawConditionC6
  infer_instance

/-- Executable whole-nerve C0 check. -/
def conditionC0Check (P : FiniteComparisonPresentation) : Bool :=
  decide P.RawConditionC0

/-- Executable C2 check on one selected target subset. -/
def conditionC2AtTargetSubsetCheck (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Bool :=
  decide (P.RawConditionC2At A)

/-- Executable C4 check on one selected target subset. -/
def conditionC4AtTargetSubsetCheck (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Bool :=
  decide (P.RawConditionC4At A)

/-- Executable whole-nerve C5 check. -/
def conditionC5Check (P : FiniteComparisonPresentation) : Bool :=
  decide P.RawConditionC5

/-- Executable whole-nerve C6 check. -/
def conditionC6Check (P : FiniteComparisonPresentation) : Bool :=
  decide P.RawConditionC6

/-- Raw finite C0 is exactly semantic whole-nerve C0 on the generated
comparison geometry. -/
theorem rawConditionC0_iff_conditionC0 (P : FiniteComparisonPresentation) :
    P.RawConditionC0 ↔ P.toGeometry.ConditionC0 := by
  unfold RawConditionC0 TargetSupportedNerveMorphism.ConditionC0
  rw [← P.computedFactor_eq_comparisonFactor]
  rfl

/-- Raw finite C2 is exactly semantic C2 on the actual canonical
A-subnerve. -/
theorem rawConditionC2At_iff_conditionC2AtTargetSubset
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.RawConditionC2At A ↔
      P.toGeometry.ConditionC2AtTargetSubset (A : Set P.CoarseTarget) := by
  constructor
  · intro hraw semanticCoarseEdge
    let coarseEdge := (P.coarseEdgeEquiv A).symm semanticCoarseEdge
    obtain ⟨fineEdge, hmap⟩ := hraw coarseEdge
    refine ⟨P.fineEdgeEquiv A fineEdge, ?_⟩
    apply (P.toGeometry.aSubnerveEdgeMapOption_eq_some_iff
      (A : Set P.CoarseTarget) _ _).2
    simpa [coarseEdge] using hmap
  · intro hsemantic coarseEdge
    obtain ⟨semanticFineEdge, hmap⟩ :=
      hsemantic (P.coarseEdgeEquiv A coarseEdge)
    let fineEdge := (P.fineEdgeEquiv A).symm semanticFineEdge
    refine ⟨fineEdge, ?_⟩
    have hwhole := (P.toGeometry.aSubnerveEdgeMapOption_eq_some_iff
      (A : Set P.CoarseTarget) semanticFineEdge
      (P.coarseEdgeEquiv A coarseEdge)).1 hmap
    simpa [fineEdge] using hwhole

/-- Raw finite C4 is exactly semantic C4 on the actual canonical
A-subnerve. -/
theorem rawConditionC4At_iff_conditionC4AtTargetSubset
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.RawConditionC4At A ↔
      P.toGeometry.ConditionC4AtTargetSubset (A : Set P.CoarseTarget) := by
  constructor
  · intro hraw semanticCoarseFace
    let coarseFace := (P.coarseFaceEquiv A).symm semanticCoarseFace
    obtain ⟨fineFace, hmap⟩ := hraw coarseFace
    refine ⟨P.fineFaceEquiv A fineFace, ?_⟩
    apply (P.toGeometry.aSubnerveFaceMapOption_eq_some_iff
      (A : Set P.CoarseTarget) _ _).2
    simpa [coarseFace] using hmap
  · intro hsemantic coarseFace
    obtain ⟨semanticFineFace, hmap⟩ :=
      hsemantic (P.coarseFaceEquiv A coarseFace)
    let fineFace := (P.fineFaceEquiv A).symm semanticFineFace
    refine ⟨fineFace, ?_⟩
    have hwhole := (P.toGeometry.aSubnerveFaceMapOption_eq_some_iff
      (A : Set P.CoarseTarget) semanticFineFace
      (P.coarseFaceEquiv A coarseFace)).1 hmap
    simpa [fineFace] using hwhole

/-- Raw finite C5 is exactly semantic whole-nerve C5. -/
theorem rawConditionC5_iff_conditionC5 (P : FiniteComparisonPresentation) :
    P.RawConditionC5 ↔ P.toGeometry.ConditionC5 := by
  rfl

/-- Raw finite C6 is exactly semantic whole-nerve C6. -/
theorem rawConditionC6_iff_conditionC6 (P : FiniteComparisonPresentation) :
    P.RawConditionC6 ↔ P.toGeometry.ConditionC6 := by
  rfl

/-- The executable C0 check is sound and complete. -/
theorem conditionC0Check_eq_true_iff (P : FiniteComparisonPresentation) :
    P.conditionC0Check = true ↔ P.toGeometry.ConditionC0 := by
  rw [conditionC0Check, decide_eq_true_iff]
  exact P.rawConditionC0_iff_conditionC0

/-- The executable C2 check on one target subset is sound and complete. -/
theorem conditionC2AtTargetSubsetCheck_eq_true_iff
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.conditionC2AtTargetSubsetCheck A = true ↔
      P.toGeometry.ConditionC2AtTargetSubset (A : Set P.CoarseTarget) := by
  rw [conditionC2AtTargetSubsetCheck, decide_eq_true_iff]
  exact P.rawConditionC2At_iff_conditionC2AtTargetSubset A

/-- The executable C4 check on one target subset is sound and complete. -/
theorem conditionC4AtTargetSubsetCheck_eq_true_iff
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.conditionC4AtTargetSubsetCheck A = true ↔
      P.toGeometry.ConditionC4AtTargetSubset (A : Set P.CoarseTarget) := by
  rw [conditionC4AtTargetSubsetCheck, decide_eq_true_iff]
  exact P.rawConditionC4At_iff_conditionC4AtTargetSubset A

/-- The executable C5 check is sound and complete. -/
theorem conditionC5Check_eq_true_iff (P : FiniteComparisonPresentation) :
    P.conditionC5Check = true ↔ P.toGeometry.ConditionC5 := by
  rw [conditionC5Check, decide_eq_true_iff]
  exact P.rawConditionC5_iff_conditionC5

/-- The executable C6 check is sound and complete. -/
theorem conditionC6Check_eq_true_iff (P : FiniteComparisonPresentation) :
    P.conditionC6Check = true ↔ P.toGeometry.ConditionC6 := by
  rw [conditionC6Check, decide_eq_true_iff]
  exact P.rawConditionC6_iff_conditionC6

/-! ## Raw rational fiber constraints and internal boundaries -/

/-- Incoming coefficient sum of a raw selected edge chain at one selected
fine chart. -/
def rawFiberIncoming (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (chain : P.FineEdgeIn A → ℚ)
    (chart : P.FineChartIn A) : ℚ :=
  ∑ edge,
    if P.fineEdgeRightIn A edge = chart then chain edge else 0

/-- Outgoing coefficient sum of a raw selected edge chain at one selected
fine chart. -/
def rawFiberOutgoing (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (chain : P.FineEdgeIn A → ℚ)
    (chart : P.FineChartIn A) : ℚ :=
  ∑ edge,
    if P.fineEdgeLeftIn A edge = chart then chain edge else 0

/-- Normalize a raw incoming coefficient to its defining finite edge sum. -/
@[simp]
theorem rawFiberIncoming_apply (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (chain : P.FineEdgeIn A → ℚ)
    (chart : P.FineChartIn A) :
    P.rawFiberIncoming A chain chart =
      ∑ edge,
        if P.fineEdgeRightIn A edge = chart then chain edge else 0 :=
  rfl

/-- Normalize a raw outgoing coefficient to its defining finite edge sum. -/
@[simp]
theorem rawFiberOutgoing_apply (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (chain : P.FineEdgeIn A → ℚ)
    (chart : P.FineChartIn A) :
    P.rawFiberOutgoing A chain chart =
      ∑ edge,
        if P.fineEdgeLeftIn A edge = chart then chain edge else 0 :=
  rfl

/-- Executable matrix imposing both support in one endpoint fiber and flow
conservation at every chart in that fiber. -/
def fiberCycleConstraintMatrix (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A) :
    Matrix (P.FineEdgeIn A ⊕ P.FineChartIn A) (P.FineEdgeIn A) ℚ :=
  fun row edge =>
    match row with
    | Sum.inl checkedEdge =>
        if P.rawFiberEdge A coarseChart checkedEdge then 0
        else if checkedEdge = edge then 1 else 0
    | Sum.inr checkedChart =>
        if P.chartMapIn A checkedChart = coarseChart then
          (if P.fineEdgeRightIn A edge = checkedChart then 1 else 0) -
            (if P.fineEdgeLeftIn A edge = checkedChart then 1 else 0)
        else 0

/-- The raw linear constraint whose kernel is precisely the full-space
extension of endpoint-fiber cycles. -/
def fiberCycleConstraintLinearMap (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A) :
    (P.FineEdgeIn A → ℚ) →ₗ[ℚ]
      (P.FineEdgeIn A ⊕ P.FineChartIn A → ℚ) :=
  (P.fiberCycleConstraintMatrix A coarseChart).mulVecLin

/-- Executable matrix of the oriented boundary of an internal-face chain.
Columns belonging to noninternal faces are masked to zero. -/
def internalFaceBoundaryMatrix (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A) :
    Matrix (P.FineEdgeIn A) (P.FineFaceIn A) ℚ :=
  fun edge face =>
    if P.rawInternalFace A coarseChart face then
      (if P.fineFaceEdge0In A face = edge then 1 else 0) -
        (if P.fineFaceEdge1In A face = edge then 1 else 0) +
          (if P.fineFaceEdge2In A face = edge then 1 else 0)
    else 0

/-- The raw oriented boundary map generated only by internal fine faces. -/
def internalFaceBoundaryLinearMap (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A) :
    (P.FineFaceIn A → ℚ) →ₗ[ℚ] (P.FineEdgeIn A → ℚ) :=
  (P.internalFaceBoundaryMatrix A coarseChart).mulVecLin

/-- Extend a raw internal-face chain by zero to every selected fine face. -/
def maskedInternalFaceChain (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A)
    (faces : P.FineFaceIn A → ℚ) : P.FineFaceIn A → ℚ :=
  fun face => if P.rawInternalFace A coarseChart face then faces face else 0

/-- Normalize the zero extension of an internal-face chain at one selected
fine face. -/
@[simp]
theorem maskedInternalFaceChain_apply
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (faces : P.FineFaceIn A → ℚ)
    (face : P.FineFaceIn A) :
    P.maskedInternalFaceChain A coarseChart faces face =
      if P.rawInternalFace A coarseChart face then faces face else 0 :=
  rfl

/-- The support row of the raw cycle constraint returns the coefficient of a
nonfiber edge and zero on a fiber edge. -/
@[simp]
theorem fiberCycleConstraintLinearMap_apply_inl
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (chain : P.FineEdgeIn A → ℚ)
    (checkedEdge : P.FineEdgeIn A) :
    P.fiberCycleConstraintLinearMap A coarseChart chain
        (Sum.inl checkedEdge) =
      if P.rawFiberEdge A coarseChart checkedEdge then 0 else chain checkedEdge := by
  classical
  simp [fiberCycleConstraintLinearMap, fiberCycleConstraintMatrix,
    Matrix.mulVec, dotProduct]

/-- The conservation row of the raw cycle constraint is
incoming-minus-outgoing on a fiber chart and zero off the fiber. -/
@[simp]
theorem fiberCycleConstraintLinearMap_apply_inr
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (chain : P.FineEdgeIn A → ℚ)
    (checkedChart : P.FineChartIn A) :
    P.fiberCycleConstraintLinearMap A coarseChart chain
        (Sum.inr checkedChart) =
      if P.chartMapIn A checkedChart = coarseChart then
        P.rawFiberIncoming A chain checkedChart -
          P.rawFiberOutgoing A chain checkedChart
      else 0 := by
  classical
  simp [fiberCycleConstraintLinearMap, fiberCycleConstraintMatrix,
    rawFiberIncoming, rawFiberOutgoing, Matrix.mulVec, dotProduct, sub_mul,
    Finset.sum_sub_distrib]

/-- The raw internal-face matrix computes the oriented boundary of the
zero-extended internal-face chain. -/
@[simp]
theorem internalFaceBoundaryLinearMap_apply
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (faces : P.FineFaceIn A → ℚ)
    (edge : P.FineEdgeIn A) :
    P.internalFaceBoundaryLinearMap A coarseChart faces edge =
      (∑ face,
        if P.fineFaceEdge0In A face = edge then
          P.maskedInternalFaceChain A coarseChart faces face else 0) -
      (∑ face,
        if P.fineFaceEdge1In A face = edge then
          P.maskedInternalFaceChain A coarseChart faces face else 0) +
      ∑ face,
        if P.fineFaceEdge2In A face = edge then
          P.maskedInternalFaceChain A coarseChart faces face else 0 := by
  classical
  simp only [internalFaceBoundaryLinearMap]
  rw [← Finset.sum_sub_distrib, ← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro face _hface
  by_cases hinternal : P.rawInternalFace A coarseChart face <;>
    simp [internalFaceBoundaryMatrix, hinternal, maskedInternalFaceChain,
      sub_mul, add_mul]

/-- The two selected fine boundary edges `0` and `1` of a face have the same
left endpoint. -/
theorem fineFaceEdge0In_left_eq_faceEdge1In_left
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (face : P.FineFaceIn A) :
    P.fineEdgeLeftIn A (P.fineFaceEdge0In A face) =
      P.fineEdgeLeftIn A (P.fineFaceEdge1In A face) := by
  apply Subtype.ext
  exact P.fineFaceEdge0_left face.1

/-- The right endpoint of selected fine face edge `0` is the left endpoint of
selected fine face edge `2`. -/
theorem fineFaceEdge0In_right_eq_faceEdge2In_left
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (face : P.FineFaceIn A) :
    P.fineEdgeRightIn A (P.fineFaceEdge0In A face) =
      P.fineEdgeLeftIn A (P.fineFaceEdge2In A face) := by
  apply Subtype.ext
  exact P.fineFaceEdge0_right face.1

/-- The two selected fine boundary edges `1` and `2` of a face have the same
right endpoint. -/
theorem fineFaceEdge1In_right_eq_faceEdge2In_right
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (face : P.FineFaceIn A) :
    P.fineEdgeRightIn A (P.fineFaceEdge1In A face) =
      P.fineEdgeRightIn A (P.fineFaceEdge2In A face) := by
  apply Subtype.ext
  exact P.fineFaceEdge1_right face.1

/-- Applying the internal-face boundary map to a standard basis face returns
the corresponding matrix column. -/
@[simp]
theorem internalFaceBoundaryLinearMap_basis_apply
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (face : P.FineFaceIn A)
    (edge : P.FineEdgeIn A) :
    P.internalFaceBoundaryLinearMap A coarseChart
        ((Pi.basisFun ℚ (P.FineFaceIn A)) face) edge =
      P.internalFaceBoundaryMatrix A coarseChart edge face := by
  simp [internalFaceBoundaryLinearMap]

/-- A finite endpoint-filtered Kronecker delta sum evaluates at its selected
edge. -/
theorem sum_endpoint_ite_eq
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (endpoint : P.FineEdgeIn A → P.FineChartIn A)
    (chart : P.FineChartIn A) (selected : P.FineEdgeIn A) :
    (∑ edge,
      if endpoint edge = chart then
        (if selected = edge then (1 : ℚ) else 0) else 0) =
      if endpoint selected = chart then 1 else 0 := by
  classical
  calc
    (∑ edge,
        if endpoint edge = chart then
          (if selected = edge then (1 : ℚ) else 0) else 0) =
      ∑ edge,
        if selected = edge then
          (if endpoint edge = chart then (1 : ℚ) else 0) else 0 := by
        apply Finset.sum_congr rfl
        intro edge _hedge
        by_cases hselected : selected = edge <;>
          simp [hselected]
    _ = _ := by
      rw [Finset.sum_ite_eq]
      simp

/-- Summing one internal-face matrix column over the edges incident to a
fixed endpoint evaluates the three Kronecker deltas at that face's edges. -/
theorem sum_endpoint_internalFaceBoundaryMatrix
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (face : P.FineFaceIn A)
    (hinternal : P.rawInternalFace A coarseChart face)
    (endpoint : P.FineEdgeIn A → P.FineChartIn A)
    (chart : P.FineChartIn A) :
    (∑ edge,
      if endpoint edge = chart then
        P.internalFaceBoundaryMatrix A coarseChart edge face else 0) =
      (if endpoint (P.fineFaceEdge0In A face) = chart then 1 else 0) -
      (if endpoint (P.fineFaceEdge1In A face) = chart then 1 else 0) +
      (if endpoint (P.fineFaceEdge2In A face) = chart then 1 else 0) := by
  classical
  simp only [internalFaceBoundaryMatrix, hinternal, if_pos]
  calc
    (∑ edge,
        if endpoint edge = chart then
          ((if P.fineFaceEdge0In A face = edge then (1 : ℚ) else 0) -
            (if P.fineFaceEdge1In A face = edge then (1 : ℚ) else 0) +
            (if P.fineFaceEdge2In A face = edge then (1 : ℚ) else 0)) else 0) =
      ∑ edge,
        ((if endpoint edge = chart then
            (if P.fineFaceEdge0In A face = edge then (1 : ℚ) else 0) else 0) -
          (if endpoint edge = chart then
            (if P.fineFaceEdge1In A face = edge then (1 : ℚ) else 0) else 0) +
          (if endpoint edge = chart then
            (if P.fineFaceEdge2In A face = edge then (1 : ℚ) else 0) else 0)) := by
        apply Finset.sum_congr rfl
        intro edge _hedge
        by_cases hendpoint : endpoint edge = chart <;>
          simp [hendpoint]
    _ = _ := by
      rw [Finset.sum_add_distrib, Finset.sum_sub_distrib]
      rw [P.sum_endpoint_ite_eq A endpoint chart
          (P.fineFaceEdge0In A face),
        P.sum_endpoint_ite_eq A endpoint chart
          (P.fineFaceEdge1In A face),
        P.sum_endpoint_ite_eq A endpoint chart
          (P.fineFaceEdge2In A face)]

/-- Internal-face boundaries satisfy the raw fiber cycle constraints. -/
theorem fiberCycleConstraint_comp_internalFaceBoundary
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) :
    (P.fiberCycleConstraintLinearMap A coarseChart).comp
        (P.internalFaceBoundaryLinearMap A coarseChart) = 0 := by
  apply (Pi.basisFun ℚ (P.FineFaceIn A)).ext
  intro face
  ext row
  simp only [LinearMap.zero_apply, Pi.zero_apply]
  cases row with
  | inl checkedEdge =>
      rw [LinearMap.comp_apply,
        P.fiberCycleConstraintLinearMap_apply_inl]
      by_cases hchecked : P.rawFiberEdge A coarseChart checkedEdge
      · simp [hchecked]
      · rw [if_neg hchecked,
          P.internalFaceBoundaryLinearMap_basis_apply]
        by_cases hinternal : P.rawInternalFace A coarseChart face
        · have hne0 : P.fineFaceEdge0In A face ≠ checkedEdge := by
            intro hequal
            exact hchecked (hequal ▸ hinternal.1)
          have hne1 : P.fineFaceEdge1In A face ≠ checkedEdge := by
            intro hequal
            exact hchecked (hequal ▸ hinternal.2.1)
          have hne2 : P.fineFaceEdge2In A face ≠ checkedEdge := by
            intro hequal
            exact hchecked (hequal ▸ hinternal.2.2)
          simp [internalFaceBoundaryMatrix, hinternal, hne0, hne1, hne2]
        · simp [internalFaceBoundaryMatrix, hinternal]
  | inr checkedChart =>
      rw [LinearMap.comp_apply,
        P.fiberCycleConstraintLinearMap_apply_inr]
      by_cases hchart : P.chartMapIn A checkedChart = coarseChart
      · rw [if_pos hchart]
        unfold rawFiberIncoming rawFiberOutgoing
        simp_rw [P.internalFaceBoundaryLinearMap_basis_apply]
        by_cases hinternal : P.rawInternalFace A coarseChart face
        · rw [P.sum_endpoint_internalFaceBoundaryMatrix A coarseChart face
              hinternal (P.fineEdgeRightIn A) checkedChart,
            P.sum_endpoint_internalFaceBoundaryMatrix A coarseChart face
              hinternal (P.fineEdgeLeftIn A) checkedChart,
            P.fineFaceEdge0In_left_eq_faceEdge1In_left A face,
            P.fineFaceEdge0In_right_eq_faceEdge2In_left A face,
            P.fineFaceEdge1In_right_eq_faceEdge2In_right A face]
          ring
        · simp [internalFaceBoundaryMatrix, hinternal]
      · simp [hchart]

/-- Exact rational rank of a standard coordinate matrix equals the range
dimension of the linear map that generated it. -/
theorem rationalMatrixRank_toMatrix'_eq_finrank_range
    {m n : Type*} [Fintype m] [Fintype n] [DecidableEq n]
    (linearMap : (n → ℚ) →ₗ[ℚ] (m → ℚ)) :
    rationalMatrixRank (LinearMap.toMatrix' linearMap) =
      Module.finrank ℚ (LinearMap.range linearMap) := by
  classical
  rw [rationalMatrixRank_eq_finrank_range]
  have hlinear :
      (LinearMap.toMatrix' linearMap).mulVecLin = linearMap := by
    apply LinearMap.ext
    intro input
    funext index
    simpa only [Matrix.mulVecLin_apply] using
      congrFun (LinearMap.toMatrix'_mulVec linearMap input) index
  rw [hlinear]

/-- A finite rational two-step complex is exact in the middle exactly when
the exact executable ranks add to the number of middle basis vectors. -/
theorem ker_le_range_iff_rationalMatrixRank_add_eq_card
    {F E V : Type*} [Fintype F] [Fintype E] [Fintype V]
    [DecidableEq F] [DecidableEq E]
    (boundaryTwo : (F → ℚ) →ₗ[ℚ] (E → ℚ))
    (boundaryOne : (E → ℚ) →ₗ[ℚ] (V → ℚ))
    (hcomplex : boundaryOne.comp boundaryTwo = 0) :
    LinearMap.ker boundaryOne ≤ LinearMap.range boundaryTwo ↔
      rationalMatrixRank (LinearMap.toMatrix' boundaryOne) +
          rationalMatrixRank (LinearMap.toMatrix' boundaryTwo) =
        Fintype.card E := by
  rw [rationalMatrixRank_toMatrix'_eq_finrank_range,
    rationalMatrixRank_toMatrix'_eq_finrank_range]
  simpa only [LinearMap.mem_ker] using
    ker_le_range_iff_finrank_range_add_eq_card boundaryTwo boundaryOne hcomplex

/-- Raw C3 on one finite target subset, expressed as exactness of the two raw
fiber boundary maps. -/
def RawConditionC3At (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Prop :=
  ∀ coarseChart : P.CoarseChartIn A,
    ∀ chain : P.FineEdgeIn A → ℚ,
      P.fiberCycleConstraintLinearMap A coarseChart chain = 0 →
        ∃ faces : P.FineFaceIn A → ℚ,
          P.internalFaceBoundaryLinearMap A coarseChart faces = chain

/-- Exact rational-rank criterion used by the executable C3 check on one
coarse chart fiber. -/
def conditionC3FiberCheck (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) (coarseChart : P.CoarseChartIn A) : Bool :=
  decide (
    rationalMatrixRank (P.fiberCycleConstraintMatrix A coarseChart) +
        rationalMatrixRank (P.internalFaceBoundaryMatrix A coarseChart) =
      Fintype.card (P.FineEdgeIn A))

/-- Executable raw C3 check on every coarse chart fiber in one target subset. -/
def conditionC3AtTargetSubsetCheck (P : FiniteComparisonPresentation)
    (A : Finset P.CoarseTarget) : Bool :=
  decide (∀ coarseChart : P.CoarseChartIn A,
    P.conditionC3FiberCheck A coarseChart = true)

/-- One raw coarse-chart fiber passes the executable C3 rank check exactly
when every raw constrained edge chain is an internal-face boundary. -/
theorem conditionC3FiberCheck_eq_true_iff
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) :
    P.conditionC3FiberCheck A coarseChart = true ↔
      ∀ chain : P.FineEdgeIn A → ℚ,
        P.fiberCycleConstraintLinearMap A coarseChart chain = 0 →
          ∃ faces : P.FineFaceIn A → ℚ,
            P.internalFaceBoundaryLinearMap A coarseChart faces = chain := by
  rw [conditionC3FiberCheck, decide_eq_true_iff]
  have hexact := ker_le_range_iff_rationalMatrixRank_add_eq_card
    (P.internalFaceBoundaryLinearMap A coarseChart)
    (P.fiberCycleConstraintLinearMap A coarseChart)
    (P.fiberCycleConstraint_comp_internalFaceBoundary A coarseChart)
  have hconstraintMatrix :
      LinearMap.toMatrix' (P.fiberCycleConstraintLinearMap A coarseChart) =
        P.fiberCycleConstraintMatrix A coarseChart := by
    simpa only [fiberCycleConstraintLinearMap] using
      (LinearEquiv.apply_symm_apply LinearMap.toMatrix'
        (P.fiberCycleConstraintMatrix A coarseChart))
  have hboundaryMatrix :
      LinearMap.toMatrix' (P.internalFaceBoundaryLinearMap A coarseChart) =
        P.internalFaceBoundaryMatrix A coarseChart := by
    simpa only [internalFaceBoundaryLinearMap] using
      (LinearEquiv.apply_symm_apply LinearMap.toMatrix'
        (P.internalFaceBoundaryMatrix A coarseChart))
  rw [← hconstraintMatrix, ← hboundaryMatrix]
  rw [← hexact]
  rfl

/-- The all-fiber raw C3 check is true exactly for raw C3 on one target
subset. -/
theorem conditionC3AtTargetSubsetCheck_eq_true_iff_raw
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.conditionC3AtTargetSubsetCheck A = true ↔ P.RawConditionC3At A := by
  rw [conditionC3AtTargetSubsetCheck, decide_eq_true_iff]
  constructor
  · intro hcheck coarseChart
    exact (P.conditionC3FiberCheck_eq_true_iff A coarseChart).1
      (hcheck coarseChart)
  · intro hraw coarseChart
    exact (P.conditionC3FiberCheck_eq_true_iff A coarseChart).2
      (hraw coarseChart)

/-! ## Raw/semantic transport for C3 -/

/-- Raw internal-face membership is exactly actual A-subnerve internal-face
membership under the canonical raw/semantic cell equivalences. -/
theorem rawInternalFace_iff_targetSubsetInternalFace
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (fineFace : P.FineFaceIn A) :
    P.rawInternalFace A coarseChart fineFace ↔
      P.toGeometry.TargetSubsetInternalFace (A : Set P.CoarseTarget)
        (P.coarseChartEquiv A coarseChart) (P.fineFaceEquiv A fineFace) := by
  constructor
  · rintro ⟨hedge0, hedge1, hedge2⟩
    constructor
    · rw [← P.fineEquiv_faceEdge0 A fineFace]
      exact (P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart _).1
        hedge0
    constructor
    · rw [← P.fineEquiv_faceEdge1 A fineFace]
      exact (P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart _).1
        hedge1
    · rw [← P.fineEquiv_faceEdge2 A fineFace]
      exact (P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart _).1
        hedge2
  · rintro ⟨hedge0, hedge1, hedge2⟩
    constructor
    · apply (P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart _).2
      rw [P.fineEquiv_faceEdge0 A fineFace]
      exact hedge0
    constructor
    · apply (P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart _).2
      rw [P.fineEquiv_faceEdge1 A fineFace]
      exact hedge1
    · apply (P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart _).2
      rw [P.fineEquiv_faceEdge2 A fineFace]
      exact hedge2

/-- Raw incoming sums agree with actual A-subnerve incoming sums after
canonical edge and chart reindexing. -/
theorem rawFiberIncoming_eq_targetSubsetFiberIncoming
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (chain : P.FineEdgeIn A → ℚ) (chart : P.FineChartIn A) :
    P.rawFiberIncoming A chain chart =
      TargetSupportedNerveMorphism.targetSubsetFiberIncoming
        P.fineSupportedNerve (P.canonicalFinePreimage A)
        (fun semanticEdge => chain ((P.fineEdgeEquiv A).symm semanticEdge))
        (P.fineChartEquiv A chart) := by
  classical
  unfold rawFiberIncoming
  rw [TargetSupportedNerveMorphism.targetSubsetFiberIncoming_apply]
  rw [← (P.fineEdgeEquiv A).sum_comp]
  simp_rw [← P.fineEquiv_edgeRight A]
  simp

/-- Raw outgoing sums agree with actual A-subnerve outgoing sums after
canonical edge and chart reindexing. -/
theorem rawFiberOutgoing_eq_targetSubsetFiberOutgoing
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (chain : P.FineEdgeIn A → ℚ) (chart : P.FineChartIn A) :
    P.rawFiberOutgoing A chain chart =
      TargetSupportedNerveMorphism.targetSubsetFiberOutgoing
        P.fineSupportedNerve (P.canonicalFinePreimage A)
        (fun semanticEdge => chain ((P.fineEdgeEquiv A).symm semanticEdge))
        (P.fineChartEquiv A chart) := by
  classical
  unfold rawFiberOutgoing
  rw [TargetSupportedNerveMorphism.targetSubsetFiberOutgoing_apply]
  rw [← (P.fineEdgeEquiv A).sum_comp]
  simp_rw [← P.fineEquiv_edgeLeft A]
  simp

/-- The kernel of the raw cycle-constraint map is exactly the actual
A-subnerve endpoint-fiber cycle predicate after canonical edge reindexing. -/
theorem fiberCycleConstraint_eq_zero_iff_targetSubsetFiberCycle
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (chain : P.FineEdgeIn A → ℚ) :
    P.fiberCycleConstraintLinearMap A coarseChart chain = 0 ↔
      P.toGeometry.TargetSubsetFiberCycle (A : Set P.CoarseTarget)
        (P.coarseChartEquiv A coarseChart)
        (fun semanticEdge => chain ((P.fineEdgeEquiv A).symm semanticEdge)) := by
  constructor
  · intro hzero
    apply P.toGeometry.targetSubsetFiberCycle_mk
    · intro semanticEdge houtside
      let rawEdge := (P.fineEdgeEquiv A).symm semanticEdge
      have hrawOutside : ¬ P.rawFiberEdge A coarseChart rawEdge := by
        intro hraw
        apply houtside
        simpa [rawEdge] using
          (P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart rawEdge).1
            hraw
      have hrow := congrFun hzero (Sum.inl rawEdge)
      rw [P.fiberCycleConstraintLinearMap_apply_inl,
        if_neg hrawOutside] at hrow
      simpa [rawEdge] using hrow
    · intro semanticChart hmap
      let rawChart := (P.fineChartEquiv A).symm semanticChart
      have hrawMap : P.chartMapIn A rawChart = coarseChart := by
        apply (P.coarseChartEquiv A).injective
        rw [P.chartMapIn_equiv_aSubnerveChartMap A rawChart]
        simpa [rawChart] using hmap
      have hrow := congrFun hzero (Sum.inr rawChart)
      rw [P.fiberCycleConstraintLinearMap_apply_inr,
        if_pos hrawMap] at hrow
      have hconservation :
          P.rawFiberIncoming A chain rawChart =
            P.rawFiberOutgoing A chain rawChart := by
        apply sub_eq_zero.mp
        simpa using hrow
      rw [P.rawFiberIncoming_eq_targetSubsetFiberIncoming A chain rawChart,
        P.rawFiberOutgoing_eq_targetSubsetFiberOutgoing A chain rawChart]
        at hconservation
      simpa [rawChart] using hconservation
  · intro hcycle
    funext row
    simp only [Pi.zero_apply]
    cases row with
    | inl rawEdge =>
        rw [P.fiberCycleConstraintLinearMap_apply_inl]
        by_cases hfiber : P.rawFiberEdge A coarseChart rawEdge
        · simp [hfiber]
        · rw [if_neg hfiber]
          have hsemanticOutside :
              ¬ P.toGeometry.TargetSubsetFiberEdge (A : Set P.CoarseTarget)
                (P.coarseChartEquiv A coarseChart)
                (P.fineEdgeEquiv A rawEdge) := by
            intro hsemantic
            exact hfiber
              ((P.rawFiberEdge_iff_targetSubsetFiberEdge A coarseChart
                rawEdge).2 hsemantic)
          have hvanish := hcycle.support P.toGeometry
            (P.fineEdgeEquiv A rawEdge) hsemanticOutside
          simpa using hvanish
    | inr rawChart =>
        rw [P.fiberCycleConstraintLinearMap_apply_inr]
        by_cases hmap : P.chartMapIn A rawChart = coarseChart
        · rw [if_pos hmap, sub_eq_zero]
          have hsemanticMap :
              P.toGeometry.aSubnerveChartMap (A : Set P.CoarseTarget)
                  (P.fineChartEquiv A rawChart) =
                P.coarseChartEquiv A coarseChart := by
            rw [← P.chartMapIn_equiv_aSubnerveChartMap A rawChart]
            exact congrArg (P.coarseChartEquiv A) hmap
          have hconservation := hcycle.conservation P.toGeometry
            (P.fineChartEquiv A rawChart) hsemanticMap
          rw [← P.rawFiberIncoming_eq_targetSubsetFiberIncoming A chain
              rawChart,
            ← P.rawFiberOutgoing_eq_targetSubsetFiberOutgoing A chain
              rawChart] at hconservation
          exact hconservation
        · simp [hmap]

/-- The raw internal-face boundary is the actual A-subnerve face boundary
after canonical edge and face reindexing. -/
theorem internalFaceBoundary_eq_targetSubsetFaceBoundary
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget)
    (coarseChart : P.CoarseChartIn A) (faces : P.FineFaceIn A → ℚ)
    (edge : P.FineEdgeIn A) :
    P.internalFaceBoundaryLinearMap A coarseChart faces edge =
      TargetSupportedNerveMorphism.targetSubsetFaceBoundary
        P.fineSupportedNerve
        (P.canonicalFinePreimage A)
        (fun semanticFace =>
          P.maskedInternalFaceChain A coarseChart faces
            ((P.fineFaceEquiv A).symm semanticFace))
        (P.fineEdgeEquiv A edge) := by
  classical
  rw [P.internalFaceBoundaryLinearMap_apply,
    TargetSupportedNerveMorphism.targetSubsetFaceBoundary_apply]
  rw [← (P.fineFaceEquiv A).sum_comp]
  rw [← (P.fineFaceEquiv A).sum_comp]
  rw [← (P.fineFaceEquiv A).sum_comp]
  simp_rw [← P.fineEquiv_faceEdge0 A, ← P.fineEquiv_faceEdge1 A,
    ← P.fineEquiv_faceEdge2 A]
  simp

/-- Raw exactness of the executable fiber chain complex is exactly semantic
C3 on the corresponding actual A-subnerve. -/
theorem rawConditionC3At_iff_conditionC3AtTargetSubset
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.RawConditionC3At A ↔
      P.toGeometry.ConditionC3AtTargetSubset (A : Set P.CoarseTarget) := by
  constructor
  · intro hraw semanticCoarseChart semanticChain hcycle
    let rawCoarseChart := (P.coarseChartEquiv A).symm semanticCoarseChart
    let rawChain : P.FineEdgeIn A → ℚ :=
      fun rawEdge => semanticChain (P.fineEdgeEquiv A rawEdge)
    have hrawCycle :
        P.fiberCycleConstraintLinearMap A rawCoarseChart rawChain = 0 := by
      apply (P.fiberCycleConstraint_eq_zero_iff_targetSubsetFiberCycle A
        rawCoarseChart rawChain).2
      simpa [rawCoarseChart, rawChain] using hcycle
    obtain ⟨rawFaces, hrawBoundary⟩ :=
      hraw rawCoarseChart rawChain hrawCycle
    let semanticFaces :
        P.fineSupportedNerve.FaceInTargetSubset
            (P.canonicalFinePreimage A) → ℚ :=
      fun semanticFace =>
        P.maskedInternalFaceChain A rawCoarseChart rawFaces
          ((P.fineFaceEquiv A).symm semanticFace)
    refine ⟨semanticFaces, ?_, ?_⟩
    · intro semanticFace hnotInternal
      let rawFace := (P.fineFaceEquiv A).symm semanticFace
      have hnotRaw : ¬ P.rawInternalFace A rawCoarseChart rawFace := by
        intro hrawInternal
        apply hnotInternal
        simpa [rawCoarseChart, rawFace] using
          (P.rawInternalFace_iff_targetSubsetInternalFace A rawCoarseChart
            rawFace).1 hrawInternal
      simp [semanticFaces, rawFace,
        FiniteComparisonPresentation.maskedInternalFaceChain, hnotRaw]
    · intro semanticEdge
      let rawEdge := (P.fineEdgeEquiv A).symm semanticEdge
      calc
        semanticChain semanticEdge = rawChain rawEdge := by
          simp [rawChain, rawEdge]
        _ = P.internalFaceBoundaryLinearMap A rawCoarseChart rawFaces
              rawEdge := (congrFun hrawBoundary rawEdge).symm
        _ = TargetSupportedNerveMorphism.targetSubsetFaceBoundary
              P.fineSupportedNerve (P.canonicalFinePreimage A)
              semanticFaces (P.fineEdgeEquiv A rawEdge) := by
          simpa [semanticFaces] using
            P.internalFaceBoundary_eq_targetSubsetFaceBoundary A
              rawCoarseChart rawFaces rawEdge
        _ = TargetSupportedNerveMorphism.targetSubsetFaceBoundary
              P.fineSupportedNerve (P.canonicalFinePreimage A)
              semanticFaces semanticEdge := by
          simp [rawEdge]
  · intro hsemantic rawCoarseChart rawChain hrawCycle
    have hcycle :
        P.toGeometry.TargetSubsetFiberCycle (A : Set P.CoarseTarget)
          (P.coarseChartEquiv A rawCoarseChart)
          (fun semanticEdge =>
            rawChain ((P.fineEdgeEquiv A).symm semanticEdge)) :=
      (P.fiberCycleConstraint_eq_zero_iff_targetSubsetFiberCycle A
        rawCoarseChart rawChain).1 hrawCycle
    obtain ⟨semanticFaces, hsemanticSupport, hsemanticBoundary⟩ :=
      hsemantic (P.coarseChartEquiv A rawCoarseChart)
        (fun semanticEdge =>
          rawChain ((P.fineEdgeEquiv A).symm semanticEdge)) hcycle
    let rawFaces : P.FineFaceIn A → ℚ :=
      fun rawFace => semanticFaces (P.fineFaceEquiv A rawFace)
    have hmaskedRaw (rawFace : P.FineFaceIn A) :
        P.maskedInternalFaceChain A rawCoarseChart rawFaces rawFace =
          semanticFaces (P.fineFaceEquiv A rawFace) := by
      by_cases hinternal : P.rawInternalFace A rawCoarseChart rawFace
      · simp [FiniteComparisonPresentation.maskedInternalFaceChain,
          rawFaces, hinternal]
      · have hsemanticNotInternal :
            ¬ P.toGeometry.TargetSubsetInternalFace
              (A : Set P.CoarseTarget)
              (P.coarseChartEquiv A rawCoarseChart)
              (P.fineFaceEquiv A rawFace) := by
          intro hsemanticInternal
          exact hinternal
            ((P.rawInternalFace_iff_targetSubsetInternalFace A
              rawCoarseChart rawFace).2 hsemanticInternal)
        have hzero := hsemanticSupport
          (P.fineFaceEquiv A rawFace) hsemanticNotInternal
        simp [FiniteComparisonPresentation.maskedInternalFaceChain,
          rawFaces, hinternal, hzero]
    have hfaces :
        (fun semanticFace =>
          P.maskedInternalFaceChain A rawCoarseChart rawFaces
            ((P.fineFaceEquiv A).symm semanticFace)) = semanticFaces := by
      funext semanticFace
      simpa using hmaskedRaw ((P.fineFaceEquiv A).symm semanticFace)
    refine ⟨rawFaces, ?_⟩
    funext rawEdge
    calc
      P.internalFaceBoundaryLinearMap A rawCoarseChart rawFaces rawEdge =
          TargetSupportedNerveMorphism.targetSubsetFaceBoundary
            P.fineSupportedNerve (P.canonicalFinePreimage A)
            semanticFaces (P.fineEdgeEquiv A rawEdge) := by
        rw [← hfaces]
        exact P.internalFaceBoundary_eq_targetSubsetFaceBoundary A
          rawCoarseChart rawFaces rawEdge
      _ = rawChain rawEdge := by
        simpa using
          (hsemanticBoundary (P.fineEdgeEquiv A rawEdge)).symm

/-- The executable C3 rank check is true exactly for semantic C3 on the
actual A-subnerve determined by the finite target subset. -/
theorem conditionC3AtTargetSubsetCheck_eq_true_iff
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.conditionC3AtTargetSubsetCheck A = true ↔
      P.toGeometry.ConditionC3AtTargetSubset (A : Set P.CoarseTarget) := by
  rw [P.conditionC3AtTargetSubsetCheck_eq_true_iff_raw,
    P.rawConditionC3At_iff_conditionC3AtTargetSubset]

/-! ## All-clause executable checker -/

/-- Executably check C1--C4 on one finite target subset. -/
def conditionC1ToC4AtTargetSubsetCheck
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) : Bool :=
  P.conditionC1AtTargetSubsetCheck A &&
    (P.conditionC2AtTargetSubsetCheck A &&
      (P.conditionC3AtTargetSubsetCheck A &&
        P.conditionC4AtTargetSubsetCheck A))

/-- The four-clause subset checker is true exactly for semantic C1--C4 on
the corresponding actual A-subnerve. -/
theorem conditionC1ToC4AtTargetSubsetCheck_eq_true_iff
    (P : FiniteComparisonPresentation) (A : Finset P.CoarseTarget) :
    P.conditionC1ToC4AtTargetSubsetCheck A = true ↔
      P.toGeometry.ConditionC1AtTargetSubset (A : Set P.CoarseTarget) ∧
      P.toGeometry.ConditionC2AtTargetSubset (A : Set P.CoarseTarget) ∧
      P.toGeometry.ConditionC3AtTargetSubset (A : Set P.CoarseTarget) ∧
      P.toGeometry.ConditionC4AtTargetSubset (A : Set P.CoarseTarget) := by
  simp only [conditionC1ToC4AtTargetSubsetCheck, Bool.and_eq_true]
  rw [P.conditionC1AtTargetSubsetCheck_eq_true_iff,
    P.conditionC2AtTargetSubsetCheck_eq_true_iff,
    P.conditionC3AtTargetSubsetCheck_eq_true_iff,
    P.conditionC4AtTargetSubsetCheck_eq_true_iff]

/-- Executably inspect every sublist of the explicit coarse-target
enumeration, skip the empty subset, and run the four subset clauses on every
nonempty finite target subset. -/
def conditionC1ToC4AllNonemptySubsetsCheck
    (P : FiniteComparisonPresentation) : Bool :=
  P.coarseTargetEntries.sublists.all fun targets =>
    match targets with
    | [] => true
    | _ :: _ => P.conditionC1ToC4AtTargetSubsetCheck targets.toFinset

/-- Explicit sublist enumeration checks the four subset clauses exactly on
all nonempty finite target subsets. -/
theorem conditionC1ToC4AllNonemptySubsetsCheck_eq_true_iff
    (P : FiniteComparisonPresentation) :
    P.conditionC1ToC4AllNonemptySubsetsCheck = true ↔
      ∀ A : Finset P.CoarseTarget, A.Nonempty →
        P.toGeometry.ConditionC1AtTargetSubset (A : Set P.CoarseTarget) ∧
        P.toGeometry.ConditionC2AtTargetSubset (A : Set P.CoarseTarget) ∧
        P.toGeometry.ConditionC3AtTargetSubset (A : Set P.CoarseTarget) ∧
        P.toGeometry.ConditionC4AtTargetSubset
          (A : Set P.CoarseTarget) := by
  rw [conditionC1ToC4AllNonemptySubsetsCheck, List.all_eq_true]
  constructor
  · intro hcheck A hA
    obtain ⟨targets, htargets, htargetsA⟩ :=
      P.exists_conditionC_sublists_toFinset_eq A
    cases targets with
    | nil =>
        simp at htargetsA
        subst A
        exact (Finset.not_nonempty_empty hA).elim
    | cons target rest =>
        have hvalue := hcheck (target :: rest) htargets
        rw [P.conditionC1ToC4AtTargetSubsetCheck_eq_true_iff] at hvalue
        simpa [htargetsA] using hvalue
  · intro hclauses targets _htargets
    cases targets with
    | nil => rfl
    | cons target rest =>
        apply (P.conditionC1ToC4AtTargetSubsetCheck_eq_true_iff
          ((target :: rest).toFinset)).2
        apply hclauses
        exact ⟨target, by simp⟩

/-- The finite-subset form of C1--C4 is equivalent to the semantic form on
every nonempty set of coarse targets. -/
theorem allNonemptyFiniteSubsetClauses_iff
    (P : FiniteComparisonPresentation) :
    (∀ A : Finset P.CoarseTarget, A.Nonempty →
      P.toGeometry.ConditionC1AtTargetSubset (A : Set P.CoarseTarget) ∧
      P.toGeometry.ConditionC2AtTargetSubset (A : Set P.CoarseTarget) ∧
      P.toGeometry.ConditionC3AtTargetSubset (A : Set P.CoarseTarget) ∧
      P.toGeometry.ConditionC4AtTargetSubset
        (A : Set P.CoarseTarget)) ↔
    (∀ A : Set P.CoarseTarget, A.Nonempty →
      P.toGeometry.ConditionC1AtTargetSubset A ∧
      P.toGeometry.ConditionC2AtTargetSubset A ∧
      P.toGeometry.ConditionC3AtTargetSubset A ∧
      P.toGeometry.ConditionC4AtTargetSubset A) := by
  constructor
  · intro hfinite A hA
    let AFinset : Finset P.CoarseTarget := A.toFinite.toFinset
    have hAFinset : AFinset.Nonempty := by
      rw [Finset.nonempty_iff_ne_empty]
      intro hempty
      have hsetEmpty : A = ∅ := by
        rw [← A.toFinite.coe_toFinset]
        simp [AFinset, hempty]
      exact hA.ne_empty hsetEmpty
    simpa [AFinset] using hfinite AFinset hAFinset
  · intro hsemantic A hA
    exact hsemantic (A : Set P.CoarseTarget) (by simpa using hA)

/-- Executable checker for the full all-subset Atlas condition.  Its body
uses only raw finite tables, bounded graph reachability, exact rational rank,
and explicit sublist enumeration. -/
def conditionCAllACheck (P : FiniteComparisonPresentation) : Bool :=
  P.conditionC0Check &&
    (P.conditionC1ToC4AllNonemptySubsetsCheck &&
      (P.conditionC5Check && P.conditionC6Check))

/-- Main Cycle 11 correctness theorem: the executable checker is true
exactly when the generated canonical comparison geometry satisfies
`ConditionCAllA`. -/
theorem conditionCAllACheck_eq_true_iff
    (P : FiniteComparisonPresentation) :
    P.conditionCAllACheck = true ↔ P.toGeometry.ConditionCAllA := by
  simp only [conditionCAllACheck, Bool.and_eq_true]
  rw [P.conditionC0Check_eq_true_iff,
    P.conditionC1ToC4AllNonemptySubsetsCheck_eq_true_iff,
    P.allNonemptyFiniteSubsetClauses_iff,
    P.conditionC5Check_eq_true_iff,
    P.conditionC6Check_eq_true_iff]
  constructor
  · rintro ⟨h0, hA, h5, h6⟩
    exact P.toGeometry.conditionCAllA_intro h0 hA h5 h6
  · intro hC
    exact ⟨hC.conditionC0 P.toGeometry,
      fun A hA => hC.subsetClauses P.toGeometry A hA,
      hC.conditionC5 P.toGeometry, hC.conditionC6 P.toGeometry⟩

end FiniteComparisonPresentation

end AAT.AG.ResolutionInvariance

#assert_standard_axioms_only AAT.AG.ResolutionInvariance
