import ResearchLean.AG.UniformInvariance.GlobalBlockBijectivity
import ResearchLean.AG.UniformInvariance.IndicatorLawFamily
import Formal.Util.AssertStandardAxioms

/-!
# Uniform invariance and all nonempty A-subnerve comparisons

This module closes the bijectivity-level part of U0 in
`G-107-aat-uniform-invariance-characterization`.  It first lifts the canonical
cochain equivalences from Cycle 1 to the actual G-102 `H¹` quotients and proves
that the actual block and label-fiber comparison maps are conjugate through
those generated equivalences.  It then combines the Cycle 2 global/blockwise
reduction with the Cycle 3 indicator family to characterize uniform invariance
by all nonempty A-subnerve comparisons.

The `H¹` equivalences and naturality square are constructed here from the
degreewise equivalences and differential compatibility.  They are not supplied
as comparison data or theorem hypotheses.
-/

noncomputable section

namespace AAT.AG.ResolutionInvariance

open CanonicalResolution TwoPhase

universe u

variable {Source : Type u}

/-! ## H¹ functoriality of a generated cochain equivalence -/

namespace ThreeCochainComplex.CochainEquiv

variable {source target : ThreeCochainComplex ℚ}

/-- A cochain equivalence determines the forward cochain Hom. -/
def toHom (equiv : ThreeCochainComplex.CochainEquiv source target) :
    ThreeCochainComplex.Hom source target where
  f0 := equiv.e0.toLinearMap
  f1 := equiv.e1.toLinearMap
  f2 := equiv.e2.toLinearMap
  comm0 := equiv.comm0
  comm1 := equiv.comm1

/-- Reversing all degreewise equivalences produces the inverse cochain
equivalence, with differential compatibility derived from the forward one. -/
def symm (equiv : ThreeCochainComplex.CochainEquiv source target) :
    ThreeCochainComplex.CochainEquiv target source where
  e0 := equiv.e0.symm
  e1 := equiv.e1.symm
  e2 := equiv.e2.symm
  comm0 := by
    intro cochain
    apply equiv.e1.injective
    rw [equiv.e1.apply_symm_apply, equiv.comm0, equiv.e0.apply_symm_apply]
  comm1 := by
    intro cochain
    apply equiv.e2.injective
    rw [equiv.e2.apply_symm_apply, equiv.comm1, equiv.e1.apply_symm_apply]

/-- The inverse induced H¹ map is a left inverse of the forward induced map. -/
theorem symm_h1Map_toHom_h1Map
    (equiv : ThreeCochainComplex.CochainEquiv source target)
    (cohomologyClass : source.H1) :
    equiv.symm.toHom.h1Map (equiv.toHom.h1Map cohomologyClass) =
      cohomologyClass := by
  obtain ⟨cycle, rfl⟩ :=
    (LinearMap.range source.boundaryToCycles).mkQ_surjective cohomologyClass
  rw [ThreeCochainComplex.Hom.h1Map_mk,
    ThreeCochainComplex.Hom.h1Map_mk]
  apply congrArg (LinearMap.range source.boundaryToCycles).mkQ
  apply Subtype.ext
  exact equiv.e1.symm_apply_apply cycle.1

/-- The forward induced H¹ map is a left inverse of the inverse induced map. -/
theorem toHom_h1Map_symm_h1Map
    (equiv : ThreeCochainComplex.CochainEquiv source target)
    (cohomologyClass : target.H1) :
    equiv.toHom.h1Map (equiv.symm.toHom.h1Map cohomologyClass) =
      cohomologyClass := by
  obtain ⟨cycle, rfl⟩ :=
    (LinearMap.range target.boundaryToCycles).mkQ_surjective cohomologyClass
  rw [ThreeCochainComplex.Hom.h1Map_mk,
    ThreeCochainComplex.Hom.h1Map_mk]
  apply congrArg (LinearMap.range target.boundaryToCycles).mkQ
  apply Subtype.ext
  exact equiv.e1.apply_symm_apply cycle.1

/-- The actual H¹ map induced by a cochain equivalence is bijective. -/
theorem toHom_h1Map_bijective
    (equiv : ThreeCochainComplex.CochainEquiv source target) :
    Function.Bijective equiv.toHom.h1Map := by
  constructor
  · intro left right hequal
    have hinverse := congrArg equiv.symm.toHom.h1Map hequal
    rw [equiv.symm_h1Map_toHom_h1Map,
      equiv.symm_h1Map_toHom_h1Map] at hinverse
    exact hinverse
  · intro cohomologyClass
    exact ⟨equiv.symm.toHom.h1Map cohomologyClass,
      equiv.toHom_h1Map_symm_h1Map cohomologyClass⟩

/-- A cochain equivalence induces a canonical linear equivalence on the actual
G-102 H¹ quotients. -/
def h1Equiv (equiv : ThreeCochainComplex.CochainEquiv source target) :
    source.H1 ≃ₗ[ℚ] target.H1 :=
  LinearEquiv.ofBijective equiv.toHom.h1Map equiv.toHom_h1Map_bijective

/-- Applying the generated H¹ equivalence normalizes to the forward Hom's
actual induced H¹ map. -/
@[simp]
theorem h1Equiv_apply
    (equiv : ThreeCochainComplex.CochainEquiv source target)
    (cohomologyClass : source.H1) :
    equiv.h1Equiv cohomologyClass = equiv.toHom.h1Map cohomologyClass :=
  rfl

/-- A degree-one naturality square between cochain Homs descends to the actual
H¹ quotient square generated by the two cochain equivalences. -/
theorem h1Equiv_naturality_apply
    {source' target' : ThreeCochainComplex ℚ}
    (sourceEquiv : ThreeCochainComplex.CochainEquiv source source')
    (targetEquiv : ThreeCochainComplex.CochainEquiv target target')
    (forward : ThreeCochainComplex.Hom source target)
    (transported : ThreeCochainComplex.Hom source' target')
    (hnatural : ∀ cochain,
      targetEquiv.e1 (forward.f1 cochain) =
        transported.f1 (sourceEquiv.e1 cochain))
    (cohomologyClass : source.H1) :
    targetEquiv.h1Equiv (forward.h1Map cohomologyClass) =
      transported.h1Map (sourceEquiv.h1Equiv cohomologyClass) := by
  obtain ⟨cycle, rfl⟩ :=
    (LinearMap.range source.boundaryToCycles).mkQ_surjective cohomologyClass
  rw [h1Equiv_apply, h1Equiv_apply,
    ThreeCochainComplex.Hom.h1Map_mk,
    ThreeCochainComplex.Hom.h1Map_mk,
    ThreeCochainComplex.Hom.h1Map_mk,
    ThreeCochainComplex.Hom.h1Map_mk]
  apply congrArg (LinearMap.range target'.boundaryToCycles).mkQ
  apply Subtype.ext
  exact hnatural cycle.1

end ThreeCochainComplex.CochainEquiv

/-! ## Actual block/A-subnerve H¹ comparison -/

namespace TargetSupportedNerveMorphism

variable {coarseReading fineReading : Reading Source}
variable {hcoarser : coarseReading.CoarserThan fineReading}
variable {coarse : TargetSupportedNerve coarseReading}
variable {fine : TargetSupportedNerve fineReading}

/-- Bijectivity of an actual selected-subset H¹ comparison is invariant under
proved equalities of both selected subsets.  This is dependent transport, not
an additional comparison certificate. -/
theorem targetSubsetComparisonH1Map_bijective_congr
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine)
    (coarseSubset coarseSubset' : Set coarseReading.Target)
    (fineSubset fineSubset' : Set fineReading.Target)
    (hcoarseSubset : coarseSubset = coarseSubset')
    (hfineSubset : fineSubset = fineSubset')
    (hsubset : ∀ target, target ∈ fineSubset →
      comparisonFactor coarseReading fineReading hcoarser target ∈
        coarseSubset)
    (hsubset' : ∀ target, target ∈ fineSubset' →
      comparisonFactor coarseReading fineReading hcoarser target ∈
        coarseSubset') :
    Function.Bijective
        (M.targetSubsetComparisonHom coarseSubset fineSubset hsubset).h1Map ↔
      Function.Bijective
        (M.targetSubsetComparisonHom coarseSubset' fineSubset' hsubset').h1Map := by
  subst coarseSubset'
  subst fineSubset'
  rfl

/-- The actual block H¹ comparison square commutes with the generated
block/label-fiber A-subnerve H¹ equivalences. -/
theorem labelFiberComparison_h1_naturality [Fintype Source]
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine)
    (laws : FiniteLawFamily Source)
    (hcoarse : laws.Adequate coarseReading)
    (hfine : laws.Adequate fineReading)
    (label : LawValueLabel laws)
    (cohomologyClass :
      (coarse.lawValueBlockComplex laws hcoarse label).H1) :
    (fine.lawValueBlockTargetSubsetComplexEquiv laws hfine label).h1Equiv
        (M.generatedBlockComparisonH1Map laws hcoarse hfine label
          cohomologyClass) =
      (M.labelFiberComparisonHom laws hcoarse hfine label).h1Map
        ((coarse.lawValueBlockTargetSubsetComplexEquiv laws hcoarse label).h1Equiv
          cohomologyClass) := by
  exact ThreeCochainComplex.CochainEquiv.h1Equiv_naturality_apply
    (coarse.lawValueBlockTargetSubsetComplexEquiv laws hcoarse label)
    (fine.lawValueBlockTargetSubsetComplexEquiv laws hfine label)
    (M.generatedBlockComparisonHom laws hcoarse hfine label)
    (M.labelFiberComparisonHom laws hcoarse hfine label)
    (M.labelFiberComparison_naturality1 laws hcoarse hfine label)
    cohomologyClass

/-- The actual generated block H¹ map is bijective exactly when the actual
label-fiber A-subnerve H¹ map is bijective. -/
theorem generatedBlockComparisonH1Map_bijective_iff_labelFiber
    [Fintype Source]
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine)
    (laws : FiniteLawFamily Source)
    (hcoarse : laws.Adequate coarseReading)
    (hfine : laws.Adequate fineReading)
    (label : LawValueLabel laws) :
    Function.Bijective
        (M.generatedBlockComparisonH1Map laws hcoarse hfine label) ↔
      Function.Bijective
        (M.labelFiberComparisonHom laws hcoarse hfine label).h1Map := by
  let coarseEquiv :=
    (coarse.lawValueBlockTargetSubsetComplexEquiv laws hcoarse label).h1Equiv
  let fineEquiv :=
    (fine.lawValueBlockTargetSubsetComplexEquiv laws hfine label).h1Equiv
  let blockMap := M.generatedBlockComparisonH1Map laws hcoarse hfine label
  let fiberMap := (M.labelFiberComparisonHom laws hcoarse hfine label).h1Map
  have hnatural (cohomologyClass :
      (coarse.lawValueBlockComplex laws hcoarse label).H1) :
      fineEquiv (blockMap cohomologyClass) =
        fiberMap (coarseEquiv cohomologyClass) :=
    M.labelFiberComparison_h1_naturality laws hcoarse hfine label
      cohomologyClass
  constructor
  · intro hblock
    have hleft : Function.Bijective (fun cohomologyClass =>
        fineEquiv (blockMap cohomologyClass)) :=
      fineEquiv.bijective.comp hblock
    rw [show (fun cohomologyClass => fineEquiv (blockMap cohomologyClass)) =
        (fun cohomologyClass => fiberMap (coarseEquiv cohomologyClass)) from
      funext hnatural] at hleft
    exact (Function.Bijective.of_comp_iff fiberMap coarseEquiv.bijective).1
      (by simpa only [Function.comp_apply] using hleft)
  · intro hfiber
    have hright : Function.Bijective (fun cohomologyClass =>
        fiberMap (coarseEquiv cohomologyClass)) :=
      hfiber.comp coarseEquiv.bijective
    rw [show (fun cohomologyClass => fiberMap (coarseEquiv cohomologyClass)) =
        (fun cohomologyClass => fineEquiv (blockMap cohomologyClass)) from
      (funext hnatural).symm] at hright
    exact (Function.Bijective.of_comp_iff' fineEquiv.bijective blockMap).1
      (by simpa only [Function.comp_apply] using hright)

/-! ## Uniformity and the A-subnerve characterization -/

/-- Uniform invariance internally quantifies every finite law family and both
adequacy domain proofs, and asks for bijectivity of the actual global H¹ map. -/
def UniformInvariance [Fintype Source]
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine) : Prop :=
  ∀ (laws : FiniteLawFamily Source)
    (hcoarse : laws.Adequate coarseReading)
    (hfine : laws.Adequate fineReading),
      Function.Bijective (M.generatedComparisonH1Map laws hcoarse hfine)

/-- Every nonempty coarse target subset has bijective actual H¹ comparison on
its constant-rational A-subnerve and canonical fine preimage. -/
def AllNonemptyASubnerveH1Bijective [Fintype Source]
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine) : Prop :=
  ∀ (A : Set coarseReading.Target), A.Nonempty →
    Function.Bijective (M.aSubnerveComparisonHom A).h1Map

/-- Uniform invariance is equivalent to bijectivity of every nonempty actual
A-subnerve H¹ comparison. -/
theorem uniformInvariance_iff_allNonemptyASubnerveH1Bijective
    [Fintype Source]
    (M : TargetSupportedNerveMorphism coarseReading fineReading hcoarser
      coarse fine) :
    M.UniformInvariance ↔ M.AllNonemptyASubnerveH1Bijective := by
  constructor
  · intro huniform A hA
    let laws := indicatorLawFamily coarseReading A
    let hcoarse := indicatorLawFamily_adequate coarseReading A
    let hfine := indicatorLawFamily_adequate_of_coarserThan
      coarseReading fineReading hcoarser A
    let label := indicatorLawFamilyTrueLabel coarseReading A hA
    have hglobal := huniform laws hcoarse hfine
    have hblocks :=
      (M.generatedComparisonH1Map_bijective_iff_blocks laws hcoarse hfine).1
        hglobal
    have hblock := hblocks label
    have hfiber :=
      (M.generatedBlockComparisonH1Map_bijective_iff_labelFiber
        laws hcoarse hfine label).1 hblock
    have hcoarseFiber :
        labelValueFiber laws coarseReading hcoarse label = A := by
      dsimp [laws, hcoarse, label]
      exact indicatorLawFamily_trueFiber_eq coarseReading A hA
    have hfineFiber :
        labelValueFiber laws fineReading hfine label =
          comparisonFactor coarseReading fineReading hcoarser ⁻¹' A := by
      dsimp [laws, hfine, label]
      exact indicatorLawFamily_trueFineFiber_eq_preimage
        coarseReading fineReading hcoarser A hA
    change Function.Bijective
      (M.targetSubsetComparisonHom
        (labelValueFiber laws coarseReading hcoarse label)
        (labelValueFiber laws fineReading hfine label)
        (labelValueFiber_mapsTo laws coarseReading fineReading hcoarse hfine
          hcoarser label)).h1Map at hfiber
    change Function.Bijective
      (M.targetSubsetComparisonHom A
        (comparisonFactor coarseReading fineReading hcoarser ⁻¹' A)
        (fun _ htarget => htarget)).h1Map
    exact (M.targetSubsetComparisonH1Map_bijective_congr
      (labelValueFiber laws coarseReading hcoarse label) A
      (labelValueFiber laws fineReading hfine label)
      (comparisonFactor coarseReading fineReading hcoarser ⁻¹' A)
      hcoarseFiber hfineFiber
      (labelValueFiber_mapsTo laws coarseReading fineReading hcoarse hfine
        hcoarser label)
      (fun _ htarget => htarget)).1 hfiber
  · intro hsubnerve laws hcoarse hfine
    apply (M.generatedComparisonH1Map_bijective_iff_blocks
      laws hcoarse hfine).2
    intro label
    apply (M.generatedBlockComparisonH1Map_bijective_iff_labelFiber
      laws hcoarse hfine label).2
    have hfiber := labelValueFiber_nonempty laws coarseReading hcoarse label
    have hsub := hsubnerve
      (labelValueFiber laws coarseReading hcoarse label) hfiber
    have hfineFiber :
        labelValueFiber laws fineReading hfine label =
          comparisonFactor coarseReading fineReading hcoarser ⁻¹'
            labelValueFiber laws coarseReading hcoarse label :=
      labelValueFiber_eq_preimage laws coarseReading fineReading hcoarse hfine
        hcoarser label
    change Function.Bijective
      (M.targetSubsetComparisonHom
        (labelValueFiber laws coarseReading hcoarse label)
        (comparisonFactor coarseReading fineReading hcoarser ⁻¹'
          labelValueFiber laws coarseReading hcoarse label)
        (fun _ htarget => htarget)).h1Map at hsub
    change Function.Bijective
      (M.targetSubsetComparisonHom
        (labelValueFiber laws coarseReading hcoarse label)
        (labelValueFiber laws fineReading hfine label)
        (labelValueFiber_mapsTo laws coarseReading fineReading hcoarse hfine
          hcoarser label)).h1Map
    exact (M.targetSubsetComparisonH1Map_bijective_congr
      (labelValueFiber laws coarseReading hcoarse label)
      (labelValueFiber laws coarseReading hcoarse label)
      (comparisonFactor coarseReading fineReading hcoarser ⁻¹'
        labelValueFiber laws coarseReading hcoarse label)
      (labelValueFiber laws fineReading hfine label)
      rfl hfineFiber.symm
      (fun _ htarget => htarget)
      (labelValueFiber_mapsTo laws coarseReading fineReading hcoarse hfine
        hcoarser label)).1 hsub

end TargetSupportedNerveMorphism

end AAT.AG.ResolutionInvariance

#assert_standard_axioms_only AAT.AG.ResolutionInvariance
