import Formal.AG.LawAlgebra.Coordinate
import Formal.AG.LawAlgebra.AmbientAlgebra
import Formal.AG.LawAlgebra.StructuralRelation
import Formal.AG.LawAlgebra.StructureSheaf
import Formal.AG.LawAlgebra.WitnessIdeal
import Formal.AG.LawAlgebra.IdempotentCollapse
import Formal.AG.LawAlgebra.StanleyReisner
import Formal.AG.LawAlgebra.ObstructionIdeal
import Formal.AG.LawAlgebra.LawEquation
import Formal.AG.LawAlgebra.LawfulLocus
import Formal.AG.LawAlgebra.Nullstellensatz
import Formal.AG.LawAlgebra.AffineChart
import Formal.AG.LawAlgebra.StandardScheme
import Formal.AG.LawAlgebra.Correspondence
import Formal.AG.LawAlgebra.FiniteExamples
import Formal.AG.LawAlgebra.RawPresheafFiniteExample
import Formal.AG.LawAlgebra.RingedSiteFiniteExample
import Formal.AG.LawAlgebra.StandardSchemeFiniteExample
import Formal.AG.LawAlgebra.ClosedEquationalGeometry
