import Formal.AG.LawAlgebra.Coordinate
import Formal.AG.LawAlgebra.AmbientAlgebra
import Formal.AG.LawAlgebra.StructuralRelation
import Formal.AG.LawAlgebra.StructureSheaf
import Formal.AG.LawAlgebra.WitnessIdeal
import Formal.AG.LawAlgebra.IdempotentCollapse
import Formal.AG.LawAlgebra.StanleyReisner
import Formal.AG.LawAlgebra.ObstructionIdeal
import Formal.AG.LawAlgebra.LawfulLocus
import Formal.AG.LawAlgebra.Nullstellensatz
