import ResearchLean.AG.FullGeometryNormalization.ExactGeometryPull
import Mathlib.CategoryTheory.Adjunction.Basic

/-!
# Exact complete-geometry transport/pullback adjunction

For a realized exact arrow, this module constructs the hom-set correspondence
between canonical cocartesian transport of complete geometries and the exact
cartesian pullback from `ExactGeometryPull`.  Both transposes are generated by
the corresponding universal property.  Their factorization equations prove
that they are inverse and natural, and hence generate the adjunction, its unit,
counit, and triangle identities.

No geometry morphism, adjunction datum, or cartesian/cocartesian certificate is
accepted from the caller.
-/

namespace AAT.AG.FullGeometryNormalization

universe u v

open CategoryTheory AtomFoundation GeometryTransport CrossStageCoherence
open DoctrineFiberProduct

set_option maxHeartbeats 3000000

/-- Send a vertical map out of complete-geometry transport to its exact
cartesian transpose. -/
noncomputable def exactGeometryTransportToPullHom
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target)
    (hom : (geomFiberTransportFunctor input.semantic.hom).obj sourceGeometry ⟶
      targetGeometry) :
    sourceGeometry ⟶ (exactGeometryPullFunctor input).obj targetGeometry := by
  let cartLift := exactGeometryPullLift input targetGeometry
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      input.semantic.hom cartLift :=
    exactGeometryPullLift_crossStageStronglyCartesian input targetGeometry
  letI : (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      (geomFiberLift input.semantic.hom sourceGeometry) :=
    geomFiberLift_isHomLift input.semantic.hom sourceGeometry
  letI : (crossStageProjection.{u, v} U).IsHomLift
      (𝟙 input.semantic.target) hom.1 := hom.2
  letI : (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      (geomFiberLift input.semantic.hom sourceGeometry ≫ hom.1) := by
    simpa using inferInstanceAs
      ((crossStageProjection.{u, v} U).IsHomLift
        (input.semantic.hom ≫ 𝟙 input.semantic.target)
        (geomFiberLift input.semantic.hom sourceGeometry ≫ hom.1))
  exact ⟨CategoryTheory.Functor.IsStronglyCartesian.map
      (crossStageProjection.{u, v} U) input.semantic.hom cartLift
      (g := 𝟙 input.semantic.source) (f' := input.semantic.hom)
      (Category.id_comp input.semantic.hom).symm
      (geomFiberLift input.semantic.hom sourceGeometry ≫ hom.1), inferInstance⟩

/-- The cartesian transpose satisfies its defining factorization through the
exact complete-geometry lift. -/
theorem exactGeometryTransportToPullHom_fac
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target)
    (hom : (geomFiberTransportFunctor input.semantic.hom).obj sourceGeometry ⟶
      targetGeometry) :
    (exactGeometryTransportToPullHom input sourceGeometry targetGeometry hom).1 ≫
        exactGeometryPullLift input targetGeometry =
      geomFiberLift input.semantic.hom sourceGeometry ≫ hom.1 := by
  let cartLift := exactGeometryPullLift input targetGeometry
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      input.semantic.hom cartLift :=
    exactGeometryPullLift_crossStageStronglyCartesian input targetGeometry
  letI : (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      (geomFiberLift input.semantic.hom sourceGeometry) :=
    geomFiberLift_isHomLift input.semantic.hom sourceGeometry
  letI : (crossStageProjection.{u, v} U).IsHomLift
      (𝟙 input.semantic.target) hom.1 := hom.2
  letI : (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      (geomFiberLift input.semantic.hom sourceGeometry ≫ hom.1) := by
    simpa using inferInstanceAs
      ((crossStageProjection.{u, v} U).IsHomLift
        (input.semantic.hom ≫ 𝟙 input.semantic.target)
        (geomFiberLift input.semantic.hom sourceGeometry ≫ hom.1))
  exact CategoryTheory.Functor.IsStronglyCartesian.fac
    (crossStageProjection.{u, v} U) input.semantic.hom cartLift
    (Category.id_comp input.semantic.hom).symm
    (geomFiberLift input.semantic.hom sourceGeometry ≫ hom.1)

/-- Send a vertical map into exact pullback to its cocartesian transpose out of
complete-geometry transport. -/
noncomputable def exactGeometryPullToTransportHom
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target)
    (hom : sourceGeometry ⟶
      (exactGeometryPullFunctor input).obj targetGeometry) :
    (geomFiberTransportFunctor input.semantic.hom).obj sourceGeometry ⟶
      targetGeometry := by
  let cocartLift := geomFiberLift input.semantic.hom sourceGeometry
  let cartLift := exactGeometryPullLift input targetGeometry
  letI : (crossStageProjection.{u, v} U).IsStronglyCocartesian
      input.semantic.hom cocartLift :=
    geomFiberLift_isStronglyCocartesian input.semantic.hom sourceGeometry
  letI : (crossStageProjection.{u, v} U).IsHomLift
      (𝟙 input.semantic.source) hom.1 := hom.2
  letI : (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      cartLift := exactGeometryPullLift_isHomLift input targetGeometry
  letI : (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      (hom.1 ≫ cartLift) := by
    simpa using inferInstanceAs
      ((crossStageProjection.{u, v} U).IsHomLift
        ((𝟙 input.semantic.source) ≫ input.semantic.hom)
        (hom.1 ≫ cartLift))
  exact ⟨CategoryTheory.Functor.IsStronglyCocartesian.map
      (crossStageProjection.{u, v} U) input.semantic.hom cocartLift
      (g := 𝟙 input.semantic.target) (f' := input.semantic.hom)
      (Category.comp_id input.semantic.hom).symm
      (hom.1 ≫ cartLift), inferInstance⟩

/-- The cocartesian transpose satisfies its defining factorization through the
canonical complete-geometry transport lift. -/
theorem exactGeometryPullToTransportHom_fac
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target)
    (hom : sourceGeometry ⟶
      (exactGeometryPullFunctor input).obj targetGeometry) :
    geomFiberLift input.semantic.hom sourceGeometry ≫
        (exactGeometryPullToTransportHom input sourceGeometry targetGeometry hom).1 =
      hom.1 ≫ exactGeometryPullLift input targetGeometry := by
  let cocartLift := geomFiberLift input.semantic.hom sourceGeometry
  let cartLift := exactGeometryPullLift input targetGeometry
  letI : (crossStageProjection.{u, v} U).IsStronglyCocartesian
      input.semantic.hom cocartLift :=
    geomFiberLift_isStronglyCocartesian input.semantic.hom sourceGeometry
  letI : (crossStageProjection.{u, v} U).IsHomLift
      (𝟙 input.semantic.source) hom.1 := hom.2
  letI : (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      cartLift := exactGeometryPullLift_isHomLift input targetGeometry
  letI : (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      (hom.1 ≫ cartLift) := by
    simpa using inferInstanceAs
      ((crossStageProjection.{u, v} U).IsHomLift
        ((𝟙 input.semantic.source) ≫ input.semantic.hom)
        (hom.1 ≫ cartLift))
  exact CategoryTheory.Functor.IsStronglyCocartesian.fac
    (crossStageProjection.{u, v} U) input.semantic.hom cocartLift
    (Category.comp_id input.semantic.hom).symm (hom.1 ≫ cartLift)

/-- Cartesian then cocartesian transposition is the identity in the target
geometry fiber. -/
theorem exactGeometryPullToTransportHom_toPull
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target)
    (hom : (geomFiberTransportFunctor input.semantic.hom).obj sourceGeometry ⟶
      targetGeometry) :
    exactGeometryPullToTransportHom input sourceGeometry targetGeometry
        (exactGeometryTransportToPullHom input sourceGeometry targetGeometry hom) =
      hom := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let cocartLift := geomFiberLift input.semantic.hom sourceGeometry
  letI : (crossStageProjection.{u, v} U).IsStronglyCocartesian
      input.semantic.hom cocartLift :=
    geomFiberLift_isStronglyCocartesian input.semantic.hom sourceGeometry
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (crossStageProjection.{u, v} U) input.semantic.hom cocartLift
    (𝟙 input.semantic.target)
  change cocartLift ≫
      (exactGeometryPullToTransportHom input sourceGeometry targetGeometry
        (exactGeometryTransportToPullHom input sourceGeometry targetGeometry hom)).1 =
    cocartLift ≫ hom.1
  rw [exactGeometryPullToTransportHom_fac, exactGeometryTransportToPullHom_fac]

/-- Cocartesian then cartesian transposition is the identity in the source
geometry fiber. -/
theorem exactGeometryTransportToPullHom_toTransport
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target)
    (hom : sourceGeometry ⟶
      (exactGeometryPullFunctor input).obj targetGeometry) :
    exactGeometryTransportToPullHom input sourceGeometry targetGeometry
        (exactGeometryPullToTransportHom input sourceGeometry targetGeometry hom) =
      hom := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let cartLift := exactGeometryPullLift input targetGeometry
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      input.semantic.hom cartLift :=
    exactGeometryPullLift_crossStageStronglyCartesian input targetGeometry
  apply CategoryTheory.Functor.IsStronglyCartesian.ext
    (crossStageProjection.{u, v} U) input.semantic.hom cartLift
    (𝟙 input.semantic.source)
  change (exactGeometryTransportToPullHom input sourceGeometry targetGeometry
      (exactGeometryPullToTransportHom input sourceGeometry targetGeometry hom)).1 ≫
      cartLift = hom.1 ≫ cartLift
  rw [exactGeometryTransportToPullHom_fac, exactGeometryPullToTransportHom_fac]

/-- The complete-geometry transport/pullback hom-set equivalence generated by
the two universal properties. -/
noncomputable def exactGeometryTransportPullHomEquiv
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target) :
    ((geomFiberTransportFunctor input.semantic.hom).obj sourceGeometry ⟶
        targetGeometry) ≃
      (sourceGeometry ⟶ (exactGeometryPullFunctor input).obj targetGeometry) where
  toFun := exactGeometryTransportToPullHom input sourceGeometry targetGeometry
  invFun := exactGeometryPullToTransportHom input sourceGeometry targetGeometry
  left_inv := exactGeometryPullToTransportHom_toPull input sourceGeometry targetGeometry
  right_inv := exactGeometryTransportToPullHom_toTransport input sourceGeometry targetGeometry

/-! ## Naturality of the generated correspondence -/

/-- The inverse transpose is natural in the source geometry. -/
theorem exactGeometryPullToTransportHom_comp_left
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    {first second : GeomFiber.{u, v} input.semantic.source}
    (sourceHom : first ⟶ second)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target)
    (hom : second ⟶ (exactGeometryPullFunctor input).obj targetGeometry) :
    exactGeometryPullToTransportHom input first targetGeometry (sourceHom ≫ hom) =
      (geomFiberTransportFunctor input.semantic.hom).map sourceHom ≫
        exactGeometryPullToTransportHom input second targetGeometry hom := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let cocartLift := geomFiberLift input.semantic.hom first
  letI : (crossStageProjection.{u, v} U).IsStronglyCocartesian
      input.semantic.hom cocartLift :=
    geomFiberLift_isStronglyCocartesian input.semantic.hom first
  apply CategoryTheory.Functor.IsStronglyCocartesian.ext
    (crossStageProjection.{u, v} U) input.semantic.hom cocartLift
    (𝟙 input.semantic.target)
  change cocartLift ≫
      (exactGeometryPullToTransportHom input first targetGeometry
        (sourceHom ≫ hom)).1 =
    cocartLift ≫
      ((geomFiberTransportFunctor input.semantic.hom).map sourceHom).1 ≫
      (exactGeometryPullToTransportHom input second targetGeometry hom).1
  rw [exactGeometryPullToTransportHom_fac]
  change (sourceHom.1 ≫ hom.1) ≫ exactGeometryPullLift input targetGeometry = _
  have transportFac :
      geomFiberLift input.semantic.hom first ≫
          ((geomFiberTransportFunctor input.semantic.hom).map sourceHom).1 =
        sourceHom.1 ≫ geomFiberLift input.semantic.hom second := by
    simpa only [geomFiberTransportFunctor] using
      geomFiberTransportMap_fac input.semantic.hom sourceHom
  calc
    _ = sourceHom.1 ≫ (hom.1 ≫ exactGeometryPullLift input targetGeometry) :=
      Category.assoc _ _ _
    _ = sourceHom.1 ≫
        (geomFiberLift input.semantic.hom second ≫
          (exactGeometryPullToTransportHom input second targetGeometry hom).1) := by
      rw [exactGeometryPullToTransportHom_fac]
    _ = (sourceHom.1 ≫ geomFiberLift input.semantic.hom second) ≫
        (exactGeometryPullToTransportHom input second targetGeometry hom).1 :=
      (Category.assoc _ _ _).symm
    _ = (geomFiberLift input.semantic.hom first ≫
        ((geomFiberTransportFunctor input.semantic.hom).map sourceHom).1) ≫
          (exactGeometryPullToTransportHom input second targetGeometry hom).1 := by
      rw [transportFac]
    _ = _ := Category.assoc _ _ _

/-- The forward transpose is natural in the target geometry. -/
theorem exactGeometryTransportToPullHom_comp_right
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source)
    {first second : GeomFiber.{u, v} input.semantic.target}
    (hom : (geomFiberTransportFunctor input.semantic.hom).obj sourceGeometry ⟶ first)
    (targetHom : first ⟶ second) :
    exactGeometryTransportToPullHom input sourceGeometry second (hom ≫ targetHom) =
      exactGeometryTransportToPullHom input sourceGeometry first hom ≫
        (exactGeometryPullFunctor input).map targetHom := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let cartLift := exactGeometryPullLift input second
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      input.semantic.hom cartLift :=
    exactGeometryPullLift_crossStageStronglyCartesian input second
  apply CategoryTheory.Functor.IsStronglyCartesian.ext
    (crossStageProjection.{u, v} U) input.semantic.hom cartLift
    (𝟙 input.semantic.source)
  change (exactGeometryTransportToPullHom input sourceGeometry second
      (hom ≫ targetHom)).1 ≫ cartLift =
    ((exactGeometryTransportToPullHom input sourceGeometry first hom).1 ≫
      ((exactGeometryPullFunctor input).map targetHom).1) ≫ cartLift
  rw [exactGeometryTransportToPullHom_fac]
  change geomFiberLift input.semantic.hom sourceGeometry ≫
      (hom.1 ≫ targetHom.1) =
    ((exactGeometryTransportToPullHom input sourceGeometry first hom).1 ≫
      (exactGeometryPullMap input targetHom).1) ≫ cartLift
  rw [Category.assoc, exactGeometryPullMap_fac]
  simpa only [Category.assoc] using congrArg
    (fun k => k ≫ targetHom.1)
    (exactGeometryTransportToPullHom_fac
      input sourceGeometry first hom).symm

/-- The natural hom-equivalence package for exact complete-geometry transport
and pullback. -/
noncomputable def exactGeometryTransportPullCoreHomEquiv
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U) :
    Adjunction.CoreHomEquiv
      (geomFiberTransportFunctor input.semantic.hom)
      (exactGeometryPullFunctor input) where
  homEquiv := exactGeometryTransportPullHomEquiv input
  homEquiv_naturality_left_symm := by
    intro first second target sourceHom hom
    exact exactGeometryPullToTransportHom_comp_left
      input sourceHom target hom
  homEquiv_naturality_right := by
    intro source first second hom targetHom
    exact exactGeometryTransportToPullHom_comp_right
      input source hom targetHom

/-! ## Adjunction, unit, counit, and component equations -/

/-- Canonical complete-geometry cocartesian transport is left adjoint to exact
complete-geometry cartesian pullback. -/
noncomputable def exactGeometryTransportPullAdjunction
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U) :
    geomFiberTransportFunctor input.semantic.hom ⊣
      exactGeometryPullFunctor input :=
  Adjunction.mkOfHomEquiv (exactGeometryTransportPullCoreHomEquiv input)

/-- The generated unit of exact complete-geometry transport and pullback. -/
noncomputable def exactGeometryTransportPullUnit
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U) :
    𝟭 (GeomFiber.{u, v} input.semantic.source) ⟶
      geomFiberTransportFunctor input.semantic.hom ⋙
        exactGeometryPullFunctor input :=
  (exactGeometryTransportPullAdjunction input).unit

/-- The generated counit of exact complete-geometry transport and pullback. -/
noncomputable def exactGeometryTransportPullCounit
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U) :
    exactGeometryPullFunctor input ⋙
        geomFiberTransportFunctor input.semantic.hom ⟶
      𝟭 (GeomFiber.{u, v} input.semantic.target) :=
  (exactGeometryTransportPullAdjunction input).counit

/-- The unit component is the cartesian transpose of the identity. -/
theorem exactGeometryTransportPullUnit_app
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source) :
    (exactGeometryTransportPullUnit input).app sourceGeometry =
      exactGeometryTransportToPullHom input sourceGeometry
        ((geomFiberTransportFunctor input.semantic.hom).obj sourceGeometry)
        (𝟙 ((geomFiberTransportFunctor input.semantic.hom).obj sourceGeometry)) := by
  rfl

/-- The counit component is the cocartesian transpose of the identity. -/
theorem exactGeometryTransportPullCounit_app
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target) :
    (exactGeometryTransportPullCounit input).app targetGeometry =
      exactGeometryPullToTransportHom input
        ((exactGeometryPullFunctor input).obj targetGeometry)
        targetGeometry
        (𝟙 ((exactGeometryPullFunctor input).obj targetGeometry)) := by
  rfl

/-- The unit component factors the canonical cocartesian lift through the exact
cartesian lift. -/
theorem exactGeometryTransportPullUnit_app_fac
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (sourceGeometry : GeomFiber.{u, v} input.semantic.source) :
    ((exactGeometryTransportPullUnit input).app sourceGeometry).1 ≫
        exactGeometryPullLift input
          ((geomFiberTransportFunctor input.semantic.hom).obj sourceGeometry) =
      geomFiberLift input.semantic.hom sourceGeometry := by
  rw [exactGeometryTransportPullUnit_app, exactGeometryTransportToPullHom_fac]
  change geomFiberLift input.semantic.hom sourceGeometry ≫ 𝟙 _ = _
  exact Category.comp_id _

/-- The counit component factors the exact cartesian lift through the canonical
cocartesian lift. -/
theorem exactGeometryTransportPullCounit_app_fac
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (targetGeometry : GeomFiber.{u, v} input.semantic.target) :
    geomFiberLift input.semantic.hom
        ((exactGeometryPullFunctor input).obj targetGeometry) ≫
      ((exactGeometryTransportPullCounit input).app targetGeometry).1 =
        exactGeometryPullLift input targetGeometry := by
  rw [exactGeometryTransportPullCounit_app, exactGeometryPullToTransportHom_fac]
  change 𝟙 _ ≫ exactGeometryPullLift input targetGeometry = _
  exact Category.id_comp _

/-- Naturality of the generated unit. -/
theorem exactGeometryTransportPullUnit_naturality
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    {first second : GeomFiber.{u, v} input.semantic.source}
    (hom : first ⟶ second) :
    (𝟭 (GeomFiber.{u, v} input.semantic.source)).map hom ≫
        (exactGeometryTransportPullUnit input).app second =
      (exactGeometryTransportPullUnit input).app first ≫
        (geomFiberTransportFunctor input.semantic.hom ⋙
          exactGeometryPullFunctor input).map hom :=
  (exactGeometryTransportPullUnit input).naturality hom

/-- Naturality of the generated counit. -/
theorem exactGeometryTransportPullCounit_naturality
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    {first second : GeomFiber.{u, v} input.semantic.target}
    (hom : first ⟶ second) :
    (exactGeometryPullFunctor input ⋙
        geomFiberTransportFunctor input.semantic.hom).map hom ≫
        (exactGeometryTransportPullCounit input).app second =
      (exactGeometryTransportPullCounit input).app first ≫
        (𝟭 (GeomFiber.{u, v} input.semantic.target)).map hom :=
  (exactGeometryTransportPullCounit input).naturality hom

/-- The left triangle identity of the exact complete-geometry adjunction. -/
theorem exactGeometryTransportPull_left_triangle
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U) :
    Functor.whiskerRight (exactGeometryTransportPullUnit input)
        (geomFiberTransportFunctor input.semantic.hom) ≫
      (Functor.associator
        (geomFiberTransportFunctor input.semantic.hom)
        (exactGeometryPullFunctor input)
        (geomFiberTransportFunctor input.semantic.hom)).hom ≫
      Functor.whiskerLeft (geomFiberTransportFunctor input.semantic.hom)
        (exactGeometryTransportPullCounit input) =
      NatTrans.id
        (𝟭 (GeomFiber.{u, v} input.semantic.source) ⋙
          geomFiberTransportFunctor input.semantic.hom) :=
  (exactGeometryTransportPullAdjunction input).left_triangle

/-- The right triangle identity of the exact complete-geometry adjunction. -/
theorem exactGeometryTransportPull_right_triangle
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U) :
    Functor.whiskerLeft (exactGeometryPullFunctor input)
        (exactGeometryTransportPullUnit input) ≫
      (Functor.associator
        (exactGeometryPullFunctor input)
        (geomFiberTransportFunctor input.semantic.hom)
        (exactGeometryPullFunctor input)).inv ≫
      Functor.whiskerRight (exactGeometryTransportPullCounit input)
        (exactGeometryPullFunctor input) =
      NatTrans.id
        (exactGeometryPullFunctor input ⋙
          𝟭 (GeomFiber.{u, v} input.semantic.source)) :=
  (exactGeometryTransportPullAdjunction input).right_triangle

end AAT.AG.FullGeometryNormalization

#assert_standard_axioms_only AAT.AG.FullGeometryNormalization
