import ResearchLean.AG.FullGeometryNormalization.ExactDerivedRefinementBC

/-!
# Pullback comparisons for the exact-derived refinement square

The generated mixed and exact pullbacks are compared with the northwest and
northeast endpoints of the original realized Beck--Chevalley square. All
endpoint identifications and pullback certificates are reconstructed from the
realization provenance; none is accepted from the caller.
-/

namespace AAT.AG.FullGeometryNormalization

universe u

open CategoryTheory CategoryTheory.Limits AtomFoundation
open DoctrineFiberProduct

set_option maxHeartbeats 3000000

/-- The pointed G-114 configuration generated by the exact-derived data. -/
noncomputable def authoredExactPointedRefinementBCConfiguration
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) : LegacyRefinementBCConfiguration U :=
  (authoredExactRefinementBCConfiguration A).pointedConfigurationAt
    (authoredExactRefinementBCCompatibleSource A)

/-- Its exact horizontal comparison. -/
noncomputable def authoredExactPulledComparison
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).pullbackSourceAt
        (authoredExactRefinementBCCompatibleSource A) ⟶
      (authoredExactRefinementBCConfiguration A).pullbackTargetAt
        (authoredExactRefinementBCCompatibleSource A) :=
  pulledExactComparisonAt
    (authoredExactRefinementBCConfiguration A)
    (authoredExactRefinementBCCompatibleSource A)
    (authoredExactRefinementBC_exactImage A)

/-- G-122(B2a) source-endpoint identification, derived from the realized
square's selected southwest point rather than a caller-supplied cast. -/
theorem authoredExactRefinementBCSourcePoint_eq
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).sourcePointAt
        (authoredExactRefinementBCCompatibleSource A) =
      A.context.square.semantic.square.southwest := by
  rcases A with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  rfl

/-- G-122(B2a) second-endpoint identification, derived from the realized
square's selected northeast point. -/
theorem authoredExactRefinementBCSecondPoint_eq
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).secondPointAt
        (authoredExactRefinementBCCompatibleSource A) =
      A.context.square.semantic.square.northeast := by
  rcases A with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  rfl

/-- G-122(B2a) bottom-endpoint identification.  Its source equality is the
original realized bottom leg's selected-point equation. -/
theorem authoredExactRefinementBCBottomPoint_eq
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).bottomPointAt
        (authoredExactRefinementBCCompatibleSource A) =
      A.context.square.semantic.square.southeast := by
  rcases A with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  rw [ExtractionInstance.mk.injEq]
  constructor
  · rfl
  · apply heq_of_eq
    exact (toSemanticBC presentation).square.bottom.source_eq

/-- First leg of the G-122(B2a) mixed cone, retargeted by the derived
southwest selected-point equality. -/
noncomputable def authoredExactMixedFst
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).pullbackSourceAt
        (authoredExactRefinementBCCompatibleSource A) ⟶
      A.context.square.semantic.square.southwest :=
  (authoredExactPointedRefinementBCConfiguration A).pulledFst ≫
    eqToHom (authoredExactRefinementBCSourcePoint_eq A)

/-- Second leg of the G-122(B2a) mixed cone.  It uses the exact-image
horizontal comparison and the derived northeast selected-point equality. -/
noncomputable def authoredExactMixedSnd
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).pullbackSourceAt
        (authoredExactRefinementBCCompatibleSource A) ⟶
      A.context.square.semantic.square.northeast :=
  authoredExactPulledComparison A ≫
    pointedPullbackSnd
      (authoredExactPointedRefinementBCConfiguration A).sigmaOne
      (authoredExactPointedRefinementBCConfiguration A).sigmaTwo ≫
    eqToHom (authoredExactRefinementBCSecondPoint_eq A)

/-- First leg of the G-122(B2a) exact target cone, retargeted by the derived
southeast selected-point equality. -/
noncomputable def authoredExactTargetFst
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).pullbackTargetAt
        (authoredExactRefinementBCCompatibleSource A) ⟶
      A.context.square.semantic.square.southeast :=
  (authoredExactPointedRefinementBCConfiguration A).pullbackFst ≫
    eqToHom (authoredExactRefinementBCTargetPoint_eq A)

/-- Second leg of the G-122(B2a) exact target cone, retargeted by the derived
northeast selected-point equality. -/
noncomputable def authoredExactTargetSnd
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).pullbackTargetAt
        (authoredExactRefinementBCCompatibleSource A) ⟶
      A.context.square.semantic.square.northeast :=
  pointedPullbackSnd
      (authoredExactPointedRefinementBCConfiguration A).sigmaOne
      (authoredExactPointedRefinementBCConfiguration A).sigmaTwo ≫
    eqToHom (authoredExactRefinementBCSecondPoint_eq A)

/-- The original square's pullback certificate comes from its presentation. -/
theorem authoredExactOriginalSquare_isPullback
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    IsPullback A.context.square.semantic.square.left
      A.context.square.semantic.square.top
      A.context.square.semantic.square.bottom
      A.context.square.semantic.square.right := by
  rcases A with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  exact (toSemanticBC_sound presentation).1

/-- The generated mixed cone is the original bottom/right pullback. -/
theorem authoredExactMixedSource_isPullback
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    IsPullback (authoredExactMixedFst A) (authoredExactMixedSnd A)
      A.context.square.semantic.square.bottom
      A.context.square.semantic.square.right := by
  rcases A with ⟨⟨⟨semantic, presentation, realization_eq⟩,
    lift, endpoint_eq⟩, twoCellBase, authored⟩
  cases realization_eq
  let A' : AuthoredBCDatumSquare U := {
    context := {
      square := {
        semantic := toSemanticBC presentation
        presentation := presentation
        realization_eq := rfl }
      lift := lift
      endpoint_eq := endpoint_eq }
    twoCellBase := twoCellBase
    authored := authored }
  have hfst : authoredExactMixedFst A' =
      pointedPullbackFst (toSemanticBC presentation).square.bottom
        (toSemanticBC presentation).square.right := by
    apply ExtInstHom.ext
    apply ExactDoctrineHom.ext <;> rfl
  have hsnd : authoredExactMixedSnd A' =
      pointedPullbackSnd (toSemanticBC presentation).square.bottom
        (toSemanticBC presentation).square.right := by
    apply ExtInstHom.ext
    apply ExactDoctrineHom.ext
    · rfl
    · apply Equiv.ext
      intro atom
      change
        ((toSemanticBC presentation).square.bottom.doctrineHom.atomEquiv.trans
          (toSemanticBC presentation).square.right.doctrineHom.atomEquiv.symm)
            atom =
        ((toSemanticBC presentation).square.bottom.doctrineHom.atomEquiv.trans
          (toSemanticBC presentation).square.right.doctrineHom.atomEquiv.symm)
            atom
      rfl
  rw [hfst, hsnd]
  exact pointedPullback_isPullback
    (toSemanticBC presentation).square.bottom
    (toSemanticBC presentation).square.right

/-- Inverse to the generated identity first leg of the exact target cospan. -/
noncomputable def authoredExactTargetFirstInv
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactPointedRefinementBCConfiguration A).Base ⟶
      (authoredExactPointedRefinementBCConfiguration A).DOne where
  doctrineHom := ExactDoctrineHom.id _
  source_eq := rfl

/-- The generated first target leg is an isomorphism because it is the
identity exact doctrine map with the same selected source. -/
noncomputable def authoredExactTargetFirstIso
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactPointedRefinementBCConfiguration A).DOne ≅
      (authoredExactPointedRefinementBCConfiguration A).Base where
  hom := (authoredExactPointedRefinementBCConfiguration A).sigmaOne
  inv := authoredExactTargetFirstInv A
  hom_inv_id := by
    apply ExtInstHom.ext
    apply ExactDoctrineHom.ext
    · rfl
    · apply Equiv.ext
      intro atom
      rfl
  inv_hom_id := by
    apply ExtInstHom.ext
    apply ExactDoctrineHom.ext
    · rfl
    · apply Equiv.ext
      intro atom
      rfl

/-- G-122(B2a) source endpoint comparison.  It is generated by uniqueness
between the mixed pointed pullback and the realization-proven original square. -/
noncomputable def authoredExactPullbackSourceIso
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).pullbackSourceAt
        (authoredExactRefinementBCCompatibleSource A) ≅
      A.context.square.semantic.square.northwest :=
  (authoredExactMixedSource_isPullback A).isoIsPullback
    A.context.square.semantic.square.southwest
    A.context.square.semantic.square.northeast
    (authoredExactOriginalSquare_isPullback A)

/-- G-122(B2a) target endpoint comparison.  It comes from the generated
pointed pullback universal property and the identity first target leg. -/
noncomputable def authoredExactPullbackTargetIso
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactRefinementBCConfiguration A).pullbackTargetAt
        (authoredExactRefinementBCCompatibleSource A) ≅
      A.context.square.semantic.square.northeast := by
  let C := authoredExactPointedRefinementBCConfiguration A
  letI : IsIso C.sigmaOne := (authoredExactTargetFirstIso A).isIso_hom
  let hpb := pointedPullback_isPullback C.sigmaOne C.sigmaTwo
  letI : IsIso (pointedPullbackSnd C.sigmaOne C.sigmaTwo) :=
    hpb.isIso_snd_of_isIso
  exact asIso (pointedPullbackSnd C.sigmaOne C.sigmaTwo) ≪≫
    eqToIso (authoredExactRefinementBCSecondPoint_eq A)

/-- Projection law for the G-122(B2a) source comparison, inherited from the
two realization-proven pointed pullback certificates. -/
theorem authoredExactPullbackSourceIso_hom_left
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactPullbackSourceIso A).hom ≫
        A.context.square.semantic.square.left = authoredExactMixedFst A :=
  (authoredExactMixedSource_isPullback A).isoIsPullback_hom_fst
    _ _ (authoredExactOriginalSquare_isPullback A)

/-- Second projection law for the G-122(B2a) source comparison, inherited
from the two realization-proven pointed pullback certificates. -/
theorem authoredExactPullbackSourceIso_hom_top
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactPullbackSourceIso A).hom ≫
        A.context.square.semantic.square.top = authoredExactMixedSnd A :=
  (authoredExactMixedSource_isPullback A).isoIsPullback_hom_snd
    _ _ (authoredExactOriginalSquare_isPullback A)

/-- G-122(B2a) target-comparison computation: its hom is the generated
pointed pullback's second projection after the selected-point retargeting. -/
theorem authoredExactPullbackTargetIso_hom
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactPullbackTargetIso A).hom = authoredExactTargetSnd A := by
  rfl

/-- Under the endpoint comparisons, the generated exact horizontal map is
the original top edge. -/
theorem authoredExactPulledComparison_comparisonSquare
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (A : AuthoredBCDatumSquare U) :
    (authoredExactPullbackSourceIso A).hom ≫
        A.context.square.semantic.square.top =
      authoredExactPulledComparison A ≫
        (authoredExactPullbackTargetIso A).hom := by
  rw [authoredExactPullbackSourceIso_hom_top,
    authoredExactPullbackTargetIso_hom]
  rfl

end AAT.AG.FullGeometryNormalization

#assert_standard_axioms_only AAT.AG.FullGeometryNormalization
