import ResearchLean.AG.CrossStageCoherence.FiberTransport
import ResearchLean.AG.DoctrineFiberProduct.CartesianTransport
import ResearchLean.AG.DoctrineFiberProduct.UpperGeometryCleavage
import ResearchLean.AG.GeometryTransport.Factorization
import ResearchLean.AG.FullGeometryNormalization.ExactGeometryPull

/-!
# Cartesianity of exact complete-geometry push transport

The canonical complete-geometry push morphism is already known to be strongly
cocartesian.  This file proves its dual universal property.  The lower factor
is generated by the G-101 Cartesian factor, while the complete geometry factor
is reconstructed from the incoming hom by cancelling the canonical forward
context and local-carrier equivalences.

No geometry factor or Cartesian certificate is accepted from the caller.
-/

namespace AAT.AG.FullGeometryNormalization

universe u v

open CategoryTheory AtomFoundation GeometryTransport CrossStageCoherence
open DoctrineFiberProduct

set_option maxHeartbeats 3000000

/-- Context equality induced by the G-101 factorization of an incoming core
map through canonical transport. -/
theorem incomingGeometryFactorContext_eq
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    (W : K.site.category) :
    contextForward h.base W =
      contextForward (transportAlongHom G.core sigma)
        (contextForward factorBase W) := by
  rw [hbase]
  rfl

/-- Inverse context transport of the factored composite cancels canonical
forward transport on a raw source context. -/
theorem incomingGeometryFactorBackwardMap_eq
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (W : Site.ArchCtx G.core.object) :
    contextBackwardMap (G := K) (H := geomTransportAlong G sigma)
        (PackageTotalHom.comp factorBase (transportAlongHom G.core sigma))
        (contextMap (G := G) (H := geomTransportAlong G sigma)
          (transportAlongHom G.core sigma) W) =
      contextBackwardMap (G := K) (H := G) factorBase W := by
  change
    (contextBackward
      (PackageTotalHom.comp factorBase (transportAlongHom G.core sigma))
      (contextForward (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma) ⟨W⟩)).ctx = _
  rw [contextBackward_comp]
  exact congrArg (fun X =>
      (contextBackward (G := K) (H := G) factorBase X).ctx)
    (canonicalContextRetraction_eq G sigma ⟨W⟩)

/-- Incoming support comparison after cancellation of canonical forward
transport. -/
noncomputable def incomingGeometryFactorSupportComp
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    (W : K.site.category) :
    W.ctx.Support → (contextForward factorBase W).ctx.Support := fun support =>
  (transportCoreSupportEquiv G.core.reading sigma
      (contextForward factorBase W)).symm
    (supportEquivOfContextEq
      (incomingGeometryFactorContext_eq G K sigma factorBase h hbase W)
      (h.geometry.supportComp W support))

/-- Incoming axis comparison after cancellation of canonical forward
transport. -/
noncomputable def incomingGeometryFactorAxisComp
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    (W : K.site.category) :
    W.ctx.Axis → (contextForward factorBase W).ctx.Axis := fun axis =>
  (transportCoreAxisEquiv G.core.reading sigma
      (contextForward factorBase W)).symm
    (axisEquivOfContextEq
      (incomingGeometryFactorContext_eq G K sigma factorBase h hbase W)
      (h.geometry.axisComp W axis))

/-- Incoming observable comparison after cancellation of canonical forward
transport. -/
noncomputable def incomingGeometryFactorObservableComp
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    (W : K.site.category) :
    W.ctx.Observable → (contextForward factorBase W).ctx.Observable :=
  fun observable =>
    (transportCoreObservableEquiv G.core.reading sigma
        (contextForward factorBase W)).symm
      (observableEquivOfContextEq
        (incomingGeometryFactorContext_eq G K sigma factorBase h hbase W)
        (h.geometry.observableComp W observable))

/-- Incoming coverage preservation reflected through the free canonical push.
The witnesses in the pushed predicates are forced to be the images selected by
the core factor because every canonical index map is injective. -/
def incomingGeometryFactorCoverage
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma)) :
    CoverageTransport K G factorBase where
  requiredSupport atom hrequired := by
    rcases h.geometry.coverage.requiredSupport atom hrequired with
      ⟨source, hsource, hsource_eq⟩
    have hEq : source = factorBase.upper.atomEquiv atom := by
      apply sigma.atomEquiv.injective
      simpa [hbase, PackageTotalHom.comp, transportAlongHom,
        transportAlongUpper, SignedExactCoreReadingHom.comp] using hsource_eq
    simpa [hEq] using hsource
  requiredEquationCoordinate coordinate hrequired := by
    rcases h.geometry.coverage.requiredEquationCoordinate coordinate hrequired with
      ⟨source, hsource, hsource_eq⟩
    have hEq : source = requiredCoordinateMap factorBase coordinate := by
      apply requiredCoordinateMap_injective
        (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma)
      simpa [hbase, requiredCoordinateMap, PackageTotalHom.comp,
        SignedExactCoreReadingHom.comp] using hsource_eq
    simpa [hEq] using hsource
  selectedViolationWitness coordinate hrequired := by
    rcases h.geometry.coverage.selectedViolationWitness coordinate hrequired with
      ⟨source, hsource, hsource_eq⟩
    have hEq : source = equationCoordinateMap factorBase coordinate := by
      apply equationCoordinateMap_injective
        (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma)
      simpa [hbase, equationCoordinateMap, PackageTotalHom.comp,
        SignedExactCoreReadingHom.comp] using hsource_eq
    simpa [hEq] using hsource
  requiredAxis axis hrequired := by
    rcases h.geometry.coverage.requiredAxis axis hrequired with
      ⟨source, hsource, hsource_eq⟩
    have hEq : source = factorBase.upper.axisMap axis := by
      simpa [hbase, PackageTotalHom.comp, transportAlongHom,
        transportAlongUpper] using hsource_eq
    simpa [hEq] using hsource
  supportVisibleOn W atom hvisible := by
    rcases h.geometry.coverage.supportVisibleOn W atom hvisible with
      ⟨sourceW, source, hsource, hW, hAtom⟩
    have hWEq : sourceW = contextMap factorBase W := by
      apply canonicalCoreContextMap_injective G sigma
      simpa [hbase, contextMap] using hW
    have hAtomEq : source = factorBase.upper.atomEquiv atom := by
      apply sigma.atomEquiv.injective
      simpa [hbase, PackageTotalHom.comp, transportAlongHom,
        transportAlongUpper, SignedExactCoreReadingHom.comp] using hAtom
    simpa [hWEq, hAtomEq] using hsource
  equationCoordinateVisibleOn W coordinate hvisible := by
    rcases h.geometry.coverage.equationCoordinateVisibleOn W coordinate hvisible with
      ⟨sourceW, source, hsource, hW, hCoordinate⟩
    have hWEq : sourceW = contextMap factorBase W := by
      apply canonicalCoreContextMap_injective G sigma
      simpa [hbase, contextMap] using hW
    have hCoordinateEq : source = requiredCoordinateMap factorBase coordinate := by
      apply requiredCoordinateMap_injective
        (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma)
      simpa [hbase, requiredCoordinateMap, PackageTotalHom.comp,
        SignedExactCoreReadingHom.comp] using hCoordinate
    simpa [hWEq, hCoordinateEq] using hsource
  violationWitnessVisibleOn W coordinate hvisible := by
    rcases h.geometry.coverage.violationWitnessVisibleOn W coordinate hvisible with
      ⟨sourceW, source, hsource, hW, hCoordinate⟩
    have hWEq : sourceW = contextMap factorBase W := by
      apply canonicalCoreContextMap_injective G sigma
      simpa [hbase, contextMap] using hW
    have hCoordinateEq : source = equationCoordinateMap factorBase coordinate := by
      apply equationCoordinateMap_injective
        (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma)
      simpa [hbase, equationCoordinateMap, PackageTotalHom.comp,
        SignedExactCoreReadingHom.comp] using hCoordinate
    simpa [hWEq, hCoordinateEq] using hsource
  axisReadableOn W axis hreadable := by
    rcases h.geometry.coverage.axisReadableOn W axis hreadable with
      ⟨sourceW, source, hsource, hW, hAxis⟩
    have hWEq : sourceW = contextMap factorBase W := by
      apply canonicalCoreContextMap_injective G sigma
      simpa [hbase, contextMap] using hW
    have hAxisEq : source = factorBase.upper.axisMap axis := by
      simpa [hbase, PackageTotalHom.comp, transportAlongHom,
        transportAlongUpper] using hAxis
    simpa [hWEq, hAxisEq] using hsource
  boundaryVisibleOn W V hvisible := by
    rcases h.geometry.coverage.boundaryVisibleOn W V hvisible with
      ⟨sourceW, sourceV, hsource, hW, hV⟩
    have hWEq : sourceW = contextMap factorBase W := by
      apply canonicalCoreContextMap_injective G sigma
      simpa [hbase, contextMap] using hW
    have hVEq : sourceV = contextMap factorBase V := by
      apply canonicalCoreContextMap_injective G sigma
      simpa [hbase, contextMap] using hV
    simpa [hWEq, hVEq] using hsource

/-- Incoming overlap comparison reflected through the inverse canonical
context equivalence. -/
noncomputable def incomingGeometryFactorOverlap
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma)) :
    OverlapTransport K G factorBase where
  overlapIso base left right := by
    let canonical := transportAlongHom G.core sigma
    let mapped := (contextInverse canonical).mapIso
      (h.geometry.overlap.overlapIso
        (contextMap canonical base)
        (contextMap canonical left)
        (contextMap canonical right))
    refine (eqToIso ?_).trans (mapped.trans (eqToIso ?_))
    · simp only [canonical, hbase, geomTransportAlong,
        pushGeometryPackage, pushSelectedGeometry, pushOverlap,
        contextForward_comp]
      rw [incomingGeometryFactorBackwardMap_eq,
        incomingGeometryFactorBackwardMap_eq,
        incomingGeometryFactorBackwardMap_eq]
      exact (canonicalContextRetraction_eq G sigma _).symm
    · simp only [canonical, geomTransportAlong,
        pushGeometryPackage, pushSelectedGeometry, pushOverlap, contextMap]
      change
        contextBackward (transportAlongHom G.core sigma)
            (contextForward (G := G) (H := geomTransportAlong G sigma)
              (transportAlongHom G.core sigma)
              ⟨G.geometry.overlap.overlap
                (coreContextBackwardMap (transportAlongHom G.core sigma)
                  (coreContextMap (transportAlongHom G.core sigma) base))
                (coreContextBackwardMap (transportAlongHom G.core sigma)
                  (coreContextMap (transportAlongHom G.core sigma) left))
                (coreContextBackwardMap (transportAlongHom G.core sigma)
                  (coreContextMap (transportAlongHom G.core sigma) right))⟩) = _
      rw [canonicalCoreContextBackwardMap_forward,
        canonicalCoreContextBackwardMap_forward,
        canonicalCoreContextBackwardMap_forward,
        canonicalContextRetraction_eq]

/-- Canonical raw reindexing is injective because the generated inverse upper
map cancels the canonical forward upper map. -/
theorem canonicalRawReindex_injective
    {U : AtomCarrier.{u}}
    (G : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    {k : Type v} [CommRing k]
    (first second : LawAlgebra.RawAmbientRestrictionSystem G.site k)
    (hEq : rawReindex
        (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma) first =
      rawReindex
        (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma) second) :
    first = second := by
  have hback := congrArg
    (UpperGeometryCleavage.rawReindexUpper
      (geomTransportAlong G sigma).geometry G.geometry
      (transportAlongUpperInverse G.core sigma)) hEq
  change UpperGeometryCleavage.rawReindexUpper G.geometry
      (geomTransportAlong G sigma).geometry
      (transportAlongHom G.core sigma).upper first =
    UpperGeometryCleavage.rawReindexUpper G.geometry
      (geomTransportAlong G sigma).geometry
      (transportAlongHom G.core sigma).upper second at hEq
  change UpperGeometryCleavage.rawReindexUpper
      (geomTransportAlong G sigma).geometry G.geometry
      (transportAlongUpperInverse G.core sigma)
      (UpperGeometryCleavage.rawReindexUpper G.geometry
        (geomTransportAlong G sigma).geometry
        (transportAlongHom G.core sigma).upper first) =
    UpperGeometryCleavage.rawReindexUpper
      (geomTransportAlong G sigma).geometry G.geometry
      (transportAlongUpperInverse G.core sigma)
      (UpperGeometryCleavage.rawReindexUpper G.geometry
        (geomTransportAlong G sigma).geometry
        (transportAlongHom G.core sigma).upper second) at hback
  rw [← UpperGeometryCleavage.rawReindexUpper_comp,
    ← UpperGeometryCleavage.rawReindexUpper_comp] at hback
  change UpperGeometryCleavage.rawReindexUpper G.geometry G.geometry
      ((transportAlongUpper G.core sigma).comp
        (transportAlongUpperInverse G.core sigma)) first =
    UpperGeometryCleavage.rawReindexUpper G.geometry G.geometry
      ((transportAlongUpper G.core sigma).comp
        (transportAlongUpperInverse G.core sigma)) second at hback
  rw [transportAlongUpper_comp_inverse,
    UpperGeometryCleavage.rawReindexUpper_id] at hback
  exact hback

/-- Raw transport respects equality of its core-package map. -/
theorem rawTransport_eq_of_base_eq
    {U : AtomCarrier.{u}}
    {G H : GeometryPackage.{u, v} U}
    {first second : PackageTotalHom G.core H.core}
    (hbase : first = second)
    (coefficient : G.Coefficient →+* H.Coefficient) :
    rawTransport first coefficient = rawTransport second coefficient := by
  cases hbase
  rfl

/-- The raw-system equality for the incoming geometry factor follows by
cancelling canonical raw reindexing from the incoming hom's raw equality. -/
theorem incomingGeometryFactor_raw_eq
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma)) :
    G.raw = rawTransport factorBase h.geometry.coefficientHom := by
  apply canonicalRawReindex_injective G sigma
  let canonical := transportAlongHom G.core sigma
  calc
    rawReindex (G := G) (H := geomTransportAlong G sigma) canonical G.raw =
        (geomTransportAlong G sigma).raw := by
      change rawReindex (G := G) (H := geomTransportAlong G sigma)
          canonical G.raw =
        rawReindex (G := G) (H := geomTransportAlong G sigma)
          canonical (G.raw.baseChange (RingHom.id G.Coefficient))
      rw [LawAlgebra.RawAmbientRestrictionSystem.baseChange_id]
    _ = rawTransport h.base h.geometry.coefficientHom := h.geometry.raw_eq
    _ = rawTransport (PackageTotalHom.comp factorBase canonical)
        h.geometry.coefficientHom :=
      rawTransport_eq_of_base_eq hbase h.geometry.coefficientHom
    _ = rawReindex (G := G) (H := geomTransportAlong G sigma) canonical
        ((rawTransport factorBase h.geometry.coefficientHom).baseChange
          (RingHom.id G.Coefficient)) := by
      simpa using (rawTransport_comp
        (G := K) (H := G) (K := geomTransportAlong G sigma)
        factorBase canonical
        h.geometry.coefficientHom (RingHom.id G.Coefficient))
    _ = rawReindex (G := G) (H := geomTransportAlong G sigma) canonical
        (rawTransport factorBase h.geometry.coefficientHom) := by
      rw [LawAlgebra.RawAmbientRestrictionSystem.baseChange_id]

/-- The reflected support comparison preserves support readings. -/
theorem incomingGeometryFactor_supportReads
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    (W : K.site.category) (support : W.ctx.Support) (atom : U.Atom)
    (hread : W.ctx.minimal.supportReads support atom) :
    (contextForward factorBase W).ctx.minimal.supportReads
      (incomingGeometryFactorSupportComp G K sigma factorBase h hbase W support)
      (factorBase.upper.atomEquiv atom) := by
  let contextEq := incomingGeometryFactorContext_eq
    G K sigma factorBase h hbase W
  let mapped := h.geometry.supportComp W support
  have hmapped := h.geometry.supportReads W support atom hread
  have hcast :
      (contextForward (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma)
        (contextForward factorBase W)).ctx.minimal.supportReads
        (supportEquivOfContextEq contextEq mapped)
        (sigma.atomEquiv (factorBase.upper.atomEquiv atom)) := by
    apply (supportEquivOfContextEq_reads_iff contextEq mapped _).2
    simpa [hbase, PackageTotalHom.comp, SignedExactCoreReadingHom.comp,
      transportAlongHom, transportAlongUpper] using hmapped
  apply (transportCoreSupportEquiv_reads_iff G.core.reading sigma
    (contextForward factorBase W)
    ((transportCoreSupportEquiv G.core.reading sigma
      (contextForward factorBase W)).symm
      (supportEquivOfContextEq contextEq mapped))
    (factorBase.upper.atomEquiv atom)).mp
  simpa [incomingGeometryFactorSupportComp, contextEq, mapped] using hcast

/-- The reflected axis comparison preserves axis readings. -/
theorem incomingGeometryFactor_axisReads
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    (W : K.site.category) (axis : W.ctx.Axis)
    (hread : W.ctx.minimal.axisReads axis) :
    (contextForward factorBase W).ctx.minimal.axisReads
      (incomingGeometryFactorAxisComp G K sigma factorBase h hbase W axis) := by
  let contextEq := incomingGeometryFactorContext_eq
    G K sigma factorBase h hbase W
  let mapped := h.geometry.axisComp W axis
  have hmapped := h.geometry.axisReads W axis hread
  have hcast :
      (contextForward (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma)
        (contextForward factorBase W)).ctx.minimal.axisReads
        (axisEquivOfContextEq contextEq mapped) := by
    exact (axisEquivOfContextEq_reads_iff contextEq mapped).2 hmapped
  apply (transportCoreAxisEquiv_reads_iff G.core.reading sigma
    (contextForward factorBase W)
    ((transportCoreAxisEquiv G.core.reading sigma
      (contextForward factorBase W)).symm
      (axisEquivOfContextEq contextEq mapped))).mp
  simpa [incomingGeometryFactorAxisComp, contextEq, mapped] using hcast

/-- The reflected observable comparison preserves observable readings. -/
theorem incomingGeometryFactor_observableReads
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    (W : K.site.category) (observable : W.ctx.Observable)
    (hread : W.ctx.minimal.observableReads observable) :
    (contextForward factorBase W).ctx.minimal.observableReads
      (incomingGeometryFactorObservableComp
        G K sigma factorBase h hbase W observable) := by
  let contextEq := incomingGeometryFactorContext_eq
    G K sigma factorBase h hbase W
  let mapped := h.geometry.observableComp W observable
  have hmapped := h.geometry.observableReads W observable hread
  have hcast :
      (contextForward (G := G) (H := geomTransportAlong G sigma)
        (transportAlongHom G.core sigma)
        (contextForward factorBase W)).ctx.minimal.observableReads
        (observableEquivOfContextEq contextEq mapped) := by
    exact (observableEquivOfContextEq_reads_iff contextEq mapped).2 hmapped
  apply (transportCoreObservableEquiv_reads_iff G.core.reading sigma
    (contextForward factorBase W)
    ((transportCoreObservableEquiv G.core.reading sigma
      (contextForward factorBase W)).symm
      (observableEquivOfContextEq contextEq mapped))).mp
  simpa [incomingGeometryFactorObservableComp, contextEq, mapped] using hcast

/-- Naturality of the reflected support comparison. -/
theorem incomingGeometryFactor_support_naturality
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    {W V : K.site.category} (w : W ⟶ V) (support : W.ctx.Support) :
    (targetContextMorphism (f := factorBase) w).supportMap
        (incomingGeometryFactorSupportComp
          G K sigma factorBase h hbase W support) =
      incomingGeometryFactorSupportComp G K sigma factorBase h hbase V
        ((sourceContextMorphism w).supportMap support) := by
  let eqW := incomingGeometryFactorContext_eq
    G K sigma factorBase h hbase W
  let eqV := incomingGeometryFactorContext_eq
    G K sigma factorBase h hbase V
  apply (transportCoreSupportEquiv G.core.reading sigma
    (contextForward factorBase V)).injective
  change (transportCoreSupportEquiv G.core.reading sigma
      (contextForward factorBase V))
      ((targetContextMorphism (f := factorBase) w).supportMap
        ((transportCoreSupportEquiv G.core.reading sigma
          (contextForward factorBase W)).symm
          (supportEquivOfContextEq eqW
            (h.geometry.supportComp W support)))) =
    (transportCoreSupportEquiv G.core.reading sigma
      (contextForward factorBase V))
      ((transportCoreSupportEquiv G.core.reading sigma
        (contextForward factorBase V)).symm
        (supportEquivOfContextEq eqV
          (h.geometry.supportComp V
            ((sourceContextMorphism w).supportMap support))))
  calc
    _ = ((geomTransportAlong G sigma).core.contextPreorder.morphism
          (leOfHom ((contextFunctor (transportAlongHom G.core sigma)).map
            ((contextFunctor factorBase).map w)))).supportMap
        (supportEquivOfContextEq eqW
          (h.geometry.supportComp W support)) := by
      simpa only [Equiv.apply_symm_apply] using
        (transportCoreSupportEquiv_naturality G.core.reading sigma
        ((contextFunctor factorBase).map w)
        ((transportCoreSupportEquiv G.core.reading sigma
          (contextForward factorBase W)).symm
          (supportEquivOfContextEq eqW
            (h.geometry.supportComp W support)))).symm
    _ = supportEquivOfContextEq eqV
        ((targetContextMorphism (f := h.base) w).supportMap
          (h.geometry.supportComp W support)) :=
      supportEquivOfContextEq_naturality eqW eqV
        ((contextFunctor h.base).map w)
        ((contextFunctor (G := G) (H := geomTransportAlong G sigma)
          (transportAlongHom G.core sigma)).map
          ((contextFunctor factorBase).map w))
        (h.geometry.supportComp W support)
    _ = _ := congrArg (supportEquivOfContextEq eqV)
      (h.geometry.support_naturality w support)
    _ = _ := (Equiv.apply_symm_apply
      (transportCoreSupportEquiv G.core.reading sigma
        (contextForward factorBase V)) _).symm

/-- Naturality of the reflected axis comparison. -/
theorem incomingGeometryFactor_axis_naturality
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    {W V : K.site.category} (w : W ⟶ V) (axis : W.ctx.Axis) :
    (targetContextMorphism (f := factorBase) w).axisMap
        (incomingGeometryFactorAxisComp
          G K sigma factorBase h hbase W axis) =
      incomingGeometryFactorAxisComp G K sigma factorBase h hbase V
        ((sourceContextMorphism w).axisMap axis) := by
  let eqW := incomingGeometryFactorContext_eq
    G K sigma factorBase h hbase W
  let eqV := incomingGeometryFactorContext_eq
    G K sigma factorBase h hbase V
  apply (transportCoreAxisEquiv G.core.reading sigma
    (contextForward factorBase V)).injective
  change (transportCoreAxisEquiv G.core.reading sigma
      (contextForward factorBase V))
      ((targetContextMorphism (f := factorBase) w).axisMap
        ((transportCoreAxisEquiv G.core.reading sigma
          (contextForward factorBase W)).symm
          (axisEquivOfContextEq eqW (h.geometry.axisComp W axis)))) =
    (transportCoreAxisEquiv G.core.reading sigma
      (contextForward factorBase V))
      ((transportCoreAxisEquiv G.core.reading sigma
        (contextForward factorBase V)).symm
        (axisEquivOfContextEq eqV
          (h.geometry.axisComp V ((sourceContextMorphism w).axisMap axis))))
  calc
    _ = ((geomTransportAlong G sigma).core.contextPreorder.morphism
          (leOfHom ((contextFunctor (transportAlongHom G.core sigma)).map
            ((contextFunctor factorBase).map w)))).axisMap
        (axisEquivOfContextEq eqW (h.geometry.axisComp W axis)) := by
      simpa only [Equiv.apply_symm_apply] using
        (transportCoreAxisEquiv_naturality G.core.reading sigma
        ((contextFunctor factorBase).map w)
        ((transportCoreAxisEquiv G.core.reading sigma
          (contextForward factorBase W)).symm
          (axisEquivOfContextEq eqW (h.geometry.axisComp W axis)))).symm
    _ = axisEquivOfContextEq eqV
        ((targetContextMorphism (f := h.base) w).axisMap
          (h.geometry.axisComp W axis)) :=
      axisEquivOfContextEq_naturality eqW eqV
        ((contextFunctor h.base).map w)
        ((contextFunctor (G := G) (H := geomTransportAlong G sigma)
          (transportAlongHom G.core sigma)).map
          ((contextFunctor factorBase).map w))
        (h.geometry.axisComp W axis)
    _ = _ := congrArg (axisEquivOfContextEq eqV)
      (h.geometry.axis_naturality w axis)
    _ = _ := (Equiv.apply_symm_apply
      (transportCoreAxisEquiv G.core.reading sigma
        (contextForward factorBase V)) _).symm

/-- Naturality of the reflected observable comparison. -/
theorem incomingGeometryFactor_observable_naturality
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    {W V : K.site.category} (w : W ⟶ V) (observable : V.ctx.Observable) :
    (targetContextMorphism (f := factorBase) w).observableRestrict
        (incomingGeometryFactorObservableComp
          G K sigma factorBase h hbase V observable) =
      incomingGeometryFactorObservableComp G K sigma factorBase h hbase W
        ((sourceContextMorphism w).observableRestrict observable) := by
  let eqW := incomingGeometryFactorContext_eq
    G K sigma factorBase h hbase W
  let eqV := incomingGeometryFactorContext_eq
    G K sigma factorBase h hbase V
  apply (transportCoreObservableEquiv G.core.reading sigma
    (contextForward factorBase W)).injective
  change (transportCoreObservableEquiv G.core.reading sigma
      (contextForward factorBase W))
      ((targetContextMorphism (f := factorBase) w).observableRestrict
        ((transportCoreObservableEquiv G.core.reading sigma
          (contextForward factorBase V)).symm
          (observableEquivOfContextEq eqV
            (h.geometry.observableComp V observable)))) =
    (transportCoreObservableEquiv G.core.reading sigma
      (contextForward factorBase W))
      ((transportCoreObservableEquiv G.core.reading sigma
        (contextForward factorBase W)).symm
        (observableEquivOfContextEq eqW
          (h.geometry.observableComp W
            ((sourceContextMorphism w).observableRestrict observable))))
  calc
    _ = ((geomTransportAlong G sigma).core.contextPreorder.morphism
          (leOfHom ((contextFunctor (transportAlongHom G.core sigma)).map
            ((contextFunctor factorBase).map w)))).observableRestrict
        (observableEquivOfContextEq eqV
          (h.geometry.observableComp V observable)) := by
      simpa only [Equiv.apply_symm_apply] using
        (transportCoreObservableEquiv_naturality G.core.reading sigma
        ((contextFunctor factorBase).map w)
        ((transportCoreObservableEquiv G.core.reading sigma
          (contextForward factorBase V)).symm
          (observableEquivOfContextEq eqV
            (h.geometry.observableComp V observable)))).symm
    _ = observableEquivOfContextEq eqW
        ((targetContextMorphism (f := h.base) w).observableRestrict
          (h.geometry.observableComp V observable)) :=
      observableEquivOfContextEq_naturality eqW eqV
        ((contextFunctor h.base).map w)
        ((contextFunctor (G := G) (H := geomTransportAlong G sigma)
          (transportAlongHom G.core sigma)).map
          ((contextFunctor factorBase).map w))
        (h.geometry.observableComp V observable)
    _ = _ := congrArg (observableEquivOfContextEq eqW)
      (h.geometry.observable_naturality w observable)
    _ = _ := (Equiv.apply_symm_apply
      (transportCoreObservableEquiv G.core.reading sigma
        (contextForward factorBase W)) _).symm

/-- Complete incoming geometry factor generated from the authored incoming
hom and the lower Cartesian factor. -/
noncomputable def incomingGeometryFactorGeometryHom
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma)) :
    GeomReadHom K G factorBase where
  coverage := incomingGeometryFactorCoverage G K sigma factorBase h hbase
  overlap := incomingGeometryFactorOverlap G K sigma factorBase h hbase
  coefficientHom := h.geometry.coefficientHom
  raw_eq := incomingGeometryFactor_raw_eq G K sigma factorBase h hbase
  supportComp := incomingGeometryFactorSupportComp G K sigma factorBase h hbase
  axisComp := incomingGeometryFactorAxisComp G K sigma factorBase h hbase
  observableComp :=
    incomingGeometryFactorObservableComp G K sigma factorBase h hbase
  supportReads :=
    incomingGeometryFactor_supportReads G K sigma factorBase h hbase
  axisReads := incomingGeometryFactor_axisReads G K sigma factorBase h hbase
  observableReads :=
    incomingGeometryFactor_observableReads G K sigma factorBase h hbase
  support_naturality :=
    incomingGeometryFactor_support_naturality G K sigma factorBase h hbase
  axis_naturality :=
    incomingGeometryFactor_axis_naturality G K sigma factorBase h hbase
  observable_naturality :=
    incomingGeometryFactor_observable_naturality G K sigma factorBase h hbase

/-- Total incoming factor over the supplied lower Cartesian factor. -/
noncomputable def incomingGeometryTotalFactor
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma)) :
    GeometryTotalHom K G where
  base := factorBase
  geometry :=
    let normalized : GeometryTotalHom K (geomTransportAlong G sigma) :=
      { base := PackageTotalHom.comp factorBase
          (transportAlongHom G.core sigma)
        geometry := GeomReadHom.castBase hbase h.geometry }
    incomingGeometryFactorGeometryHom G K sigma factorBase normalized rfl

/-- The generated incoming factor lies over the supplied lower factor. -/
@[simp] theorem incomingGeometryTotalFactor_base
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma)) :
    (incomingGeometryTotalFactor G K sigma factorBase h hbase).base =
      factorBase := rfl

/-- Reindexing a geometry hom along base equality changes only its dependent
type. -/
theorem geomReadHom_castBase_heq
    {U : AtomCarrier.{u}}
    {G H : GeometryPackage.{u, v} U}
    {first second : PackageTotalHom G.core H.core}
    (hbase : first = second) (hom : GeomReadHom G H first) :
    HEq (GeomReadHom.castBase hbase hom) hom := by
  cases hbase
  rfl

private theorem incomingGeometryFactorContext_eq_exact
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (hom : GeomReadHom K (geomTransportAlong G sigma)
      (PackageTotalHom.comp factorBase (transportAlongHom G.core sigma)))
    (W : K.site.category) :
    incomingGeometryFactorContext_eq G K sigma factorBase
      { base := PackageTotalHom.comp factorBase
          (transportAlongHom G.core sigma)
        geometry := hom } rfl W = rfl := by
  apply Subsingleton.elim

private theorem incomingGeometryFactorSupportComp_fac_exact
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (hom : GeomReadHom K (geomTransportAlong G sigma)
      (PackageTotalHom.comp factorBase (transportAlongHom G.core sigma)))
    (W : K.site.category) (support : W.ctx.Support) :
    geomTransportSupportComp G sigma (contextForward factorBase W)
        (incomingGeometryFactorSupportComp G K sigma factorBase
          { base := PackageTotalHom.comp factorBase
              (transportAlongHom G.core sigma)
            geometry := hom } rfl W support) =
      hom.supportComp W support := by
  unfold incomingGeometryFactorSupportComp geomTransportSupportComp
  rw [incomingGeometryFactorContext_eq_exact G K sigma factorBase hom W]
  exact Equiv.apply_symm_apply _ _

private theorem incomingGeometryFactorAxisComp_fac_exact
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (hom : GeomReadHom K (geomTransportAlong G sigma)
      (PackageTotalHom.comp factorBase (transportAlongHom G.core sigma)))
    (W : K.site.category) (axis : W.ctx.Axis) :
    geomTransportAxisComp G sigma (contextForward factorBase W)
        (incomingGeometryFactorAxisComp G K sigma factorBase
          { base := PackageTotalHom.comp factorBase
              (transportAlongHom G.core sigma)
            geometry := hom } rfl W axis) =
      hom.axisComp W axis := by
  unfold incomingGeometryFactorAxisComp geomTransportAxisComp
  rw [incomingGeometryFactorContext_eq_exact G K sigma factorBase hom W]
  exact Equiv.apply_symm_apply _ _

private theorem incomingGeometryFactorObservableComp_fac_exact
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (hom : GeomReadHom K (geomTransportAlong G sigma)
      (PackageTotalHom.comp factorBase (transportAlongHom G.core sigma)))
    (W : K.site.category) (observable : W.ctx.Observable) :
    geomTransportObservableComp G sigma (contextForward factorBase W)
        (incomingGeometryFactorObservableComp G K sigma factorBase
          { base := PackageTotalHom.comp factorBase
              (transportAlongHom G.core sigma)
            geometry := hom } rfl W observable) =
      hom.observableComp W observable := by
  unfold incomingGeometryFactorObservableComp geomTransportObservableComp
  rw [incomingGeometryFactorContext_eq_exact G K sigma factorBase hom W]
  exact Equiv.apply_symm_apply _ _

/-- Componentwise cancellation identifies the generated geometry factor
followed by canonical geometry transport with the incoming geometry data. -/
theorem incomingGeometryFactorGeometryHom_fac_exact
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (hom : GeomReadHom K (geomTransportAlong G sigma)
      (PackageTotalHom.comp factorBase (transportAlongHom G.core sigma))) :
    GeomReadHom.comp
        (incomingGeometryFactorGeometryHom G K sigma factorBase
          { base := PackageTotalHom.comp factorBase
              (transportAlongHom G.core sigma)
            geometry := hom } rfl)
        (geomTransportAlongGeometryHom G sigma) = hom := by
  apply GeomReadHom.ext
  · rfl
  · apply heq_of_eq
    funext W support
    exact incomingGeometryFactorSupportComp_fac_exact
      G K sigma factorBase hom W support
  · apply heq_of_eq
    funext W axis
    exact incomingGeometryFactorAxisComp_fac_exact
      G K sigma factorBase hom W axis
  · apply heq_of_eq
    funext W observable
    exact incomingGeometryFactorObservableComp_fac_exact
      G K sigma factorBase hom W observable

/-- Cancelling canonical transport after composing an arbitrary incoming
geometry factor reconstructs that factor. -/
theorem incomingGeometryFactor_of_composite
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (factor : GeomReadHom K G factorBase) :
    incomingGeometryFactorGeometryHom G K sigma factorBase
        { base := PackageTotalHom.comp factorBase
            (transportAlongHom G.core sigma)
          geometry := GeomReadHom.comp factor
            (geomTransportAlongGeometryHom G sigma) } rfl =
      factor := by
  apply GeomReadHom.ext
  · rfl
  · apply heq_of_eq
    funext W support
    unfold incomingGeometryFactorGeometryHom
      incomingGeometryFactorSupportComp
    have hproof :
        incomingGeometryFactorContext_eq G K sigma factorBase
          { base := PackageTotalHom.comp factorBase
              (transportAlongHom G.core sigma)
            geometry := GeomReadHom.comp factor
              (geomTransportAlongGeometryHom G sigma) } rfl W = rfl := by
      apply Subsingleton.elim
    change
      (transportCoreSupportEquiv G.core.reading sigma
          (contextForward factorBase W)).symm
        (supportEquivOfContextEq
          (incomingGeometryFactorContext_eq G K sigma factorBase
            { base := PackageTotalHom.comp factorBase
                (transportAlongHom G.core sigma)
              geometry := GeomReadHom.comp factor
                (geomTransportAlongGeometryHom G sigma) } rfl W)
          (geomTransportSupportComp G sigma (contextForward factorBase W)
            (factor.supportComp W support))) = factor.supportComp W support
    rw [hproof]
    exact Equiv.symm_apply_apply _ _
  · apply heq_of_eq
    funext W axis
    unfold incomingGeometryFactorGeometryHom
      incomingGeometryFactorAxisComp
    have hproof :
        incomingGeometryFactorContext_eq G K sigma factorBase
          { base := PackageTotalHom.comp factorBase
              (transportAlongHom G.core sigma)
            geometry := GeomReadHom.comp factor
              (geomTransportAlongGeometryHom G sigma) } rfl W = rfl := by
      apply Subsingleton.elim
    change
      (transportCoreAxisEquiv G.core.reading sigma
          (contextForward factorBase W)).symm
        (axisEquivOfContextEq
          (incomingGeometryFactorContext_eq G K sigma factorBase
            { base := PackageTotalHom.comp factorBase
                (transportAlongHom G.core sigma)
              geometry := GeomReadHom.comp factor
                (geomTransportAlongGeometryHom G sigma) } rfl W)
          (geomTransportAxisComp G sigma (contextForward factorBase W)
            (factor.axisComp W axis))) = factor.axisComp W axis
    rw [hproof]
    exact Equiv.symm_apply_apply _ _
  · apply heq_of_eq
    funext W observable
    unfold incomingGeometryFactorGeometryHom
      incomingGeometryFactorObservableComp
    have hproof :
        incomingGeometryFactorContext_eq G K sigma factorBase
          { base := PackageTotalHom.comp factorBase
              (transportAlongHom G.core sigma)
            geometry := GeomReadHom.comp factor
              (geomTransportAlongGeometryHom G sigma) } rfl W = rfl := by
      apply Subsingleton.elim
    change
      (transportCoreObservableEquiv G.core.reading sigma
          (contextForward factorBase W)).symm
        (observableEquivOfContextEq
          (incomingGeometryFactorContext_eq G K sigma factorBase
            { base := PackageTotalHom.comp factorBase
                (transportAlongHom G.core sigma)
              geometry := GeomReadHom.comp factor
                (geomTransportAlongGeometryHom G sigma) } rfl W)
          (geomTransportObservableComp G sigma (contextForward factorBase W)
            (factor.observableComp W observable))) =
        factor.observableComp W observable
    rw [hproof]
    exact Equiv.symm_apply_apply _ _

/-- Componentwise cancellation for an incoming total hom after dependent base
normalization. -/
theorem incomingGeometryFactorGeometryHom_fac
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma)) :
    GeomReadHom.comp
        (incomingGeometryTotalFactor G K sigma factorBase h hbase).geometry
        (geomTransportAlongGeometryHom G sigma) =
      GeomReadHom.castBase hbase h.geometry := by
  exact incomingGeometryFactorGeometryHom_fac_exact G K sigma factorBase
    (GeomReadHom.castBase hbase h.geometry)

/-- The generated incoming geometry factor followed by canonical transport is
the authored incoming hom. -/
theorem incomingGeometryTotalFactor_fac
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma)) :
    GeometryTotalHom.comp
        (incomingGeometryTotalFactor G K sigma factorBase h hbase)
        (geomTransportAlongHom G sigma) = h := by
  apply GeometryTotalHom.ext
  · exact hbase.symm
  · exact (heq_of_eq
      (incomingGeometryFactorGeometryHom_fac
        G K sigma factorBase h hbase)).trans
      (geomReadHom_castBase_heq hbase h.geometry)

private theorem geomReadHom_comp_castBase_left_heq
    {U : AtomCarrier.{u}}
    {G H K : GeometryPackage.{u, v} U}
    {first first' : PackageTotalHom G.core H.core}
    {second : PackageTotalHom H.core K.core}
    (hfirst : first = first') (head : GeomReadHom G H first)
    (tail : GeomReadHom H K second) :
    HEq (GeomReadHom.comp (GeomReadHom.castBase hfirst head) tail)
      (GeomReadHom.comp head tail) := by
  cases hfirst
  rfl

private theorem geometry_heq_of_total_eq
    {U : AtomCarrier.{u}}
    {G H : GeometryPackage.{u, v} U}
    {first second : GeometryTotalHom G H}
    (h : first = second) : HEq first.geometry second.geometry := by
  cases h
  rfl

/-- Every incoming total factor over a fixed lower factor is the generated
factor.  The only hypothesis about the candidate is its factor equation. -/
theorem incomingGeometryTotalFactor_unique
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma))
    (candidate : GeometryTotalHom K G)
    (candidateBase : candidate.base = factorBase)
    (candidateFac : GeometryTotalHom.comp candidate
      (geomTransportAlongHom G sigma) = h) :
    candidate = incomingGeometryTotalFactor G K sigma factorBase h hbase := by
  let candidateGeometry := GeomReadHom.castBase candidateBase candidate.geometry
  let normalizedH := GeomReadHom.castBase hbase h.geometry
  have hnormalized : GeomReadHom.comp candidateGeometry
      (geomTransportAlongGeometryHom G sigma) = normalizedH := by
    apply eq_of_heq
    exact ((geomReadHom_comp_castBase_left_heq candidateBase candidate.geometry
      (geomTransportAlongGeometryHom G sigma)).trans
        (geometry_heq_of_total_eq candidateFac)).trans
          (geomReadHom_castBase_heq hbase h.geometry).symm
  have hgeometry : candidateGeometry =
      (incomingGeometryTotalFactor G K sigma factorBase h hbase).geometry := by
    calc
      candidateGeometry = incomingGeometryFactorGeometryHom G K sigma factorBase
          { base := PackageTotalHom.comp factorBase
              (transportAlongHom G.core sigma)
            geometry := GeomReadHom.comp candidateGeometry
              (geomTransportAlongGeometryHom G sigma) } rfl :=
        (incomingGeometryFactor_of_composite G K sigma factorBase
          candidateGeometry).symm
      _ = incomingGeometryFactorGeometryHom G K sigma factorBase
          { base := PackageTotalHom.comp factorBase
              (transportAlongHom G.core sigma)
            geometry := normalizedH } rfl := by
        rw [hnormalized]
      _ = (incomingGeometryTotalFactor G K sigma factorBase h hbase).geometry := rfl
  apply GeometryTotalHom.ext
  · exact candidateBase
  · exact (geomReadHom_castBase_heq candidateBase candidate.geometry).symm.trans
      (heq_of_eq hgeometry)

/-- The generated incoming factor is the unique total factor over the fixed
lower Cartesian factor. -/
theorem geomTransportAlongHom_incomingFactor_existsUnique
    {U : AtomCarrier.{u}}
    (G K : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma))
    (hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma)) :
    ∃! factor : GeometryTotalHom K G,
      factor.base = factorBase ∧
        GeometryTotalHom.comp factor (geomTransportAlongHom G sigma) = h := by
  refine ⟨incomingGeometryTotalFactor G K sigma factorBase h hbase,
    ⟨rfl, incomingGeometryTotalFactor_fac G K sigma factorBase h hbase⟩, ?_⟩
  intro candidate hcandidate
  exact incomingGeometryTotalFactor_unique G K sigma factorBase h hbase
    candidate hcandidate.1 hcandidate.2

/-- Canonical complete-geometry push transport is strongly Cartesian over its
actual core-package morphism.  Its incoming factor is constructed above by
cancelling the canonical local-carrier equivalences. -/
theorem geomTransportAlongHom_isStronglyCartesian
    {U : AtomCarrier.{u}}
    (G : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E) :
    (geometryProjection U).IsStronglyCartesian
      (transportAlongHom G.core sigma)
      (geomTransportAlongHom G sigma) := by
  letI : (geometryProjection U).IsHomLift
      (transportAlongHom G.core sigma) (geomTransportAlongHom G sigma) := by
    change (geometryProjection U).IsHomLift
      ((geometryProjection U).map (geomTransportAlongHom G sigma))
      (geomTransportAlongHom G sigma)
    infer_instance
  apply CategoryTheory.Functor.IsStronglyCartesian.mk
  rintro (K : GeomReadCategory.{u, v} U)
    (factorBase : PackageTotalHom K.core G.core)
    (h : GeometryTotalHom K (geomTransportAlong G sigma)) hLift
  letI : (geometryProjection U).IsHomLift
      (PackageTotalHom.comp factorBase (transportAlongHom G.core sigma)) h := hLift
  have hbase : h.base = PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma) := by
    have hbase' := CategoryTheory.IsHomLift.eq_of_isHomLift
      (p := geometryProjection U)
      (a := K) (b := geomTransportAlong G sigma)
      (f := (show K.core ⟶ (geomTransportAlong G sigma).core from
        PackageTotalHom.comp factorBase
          (transportAlongHom G.core sigma)))
      (φ := h)
    change PackageTotalHom.comp factorBase
      (transportAlongHom G.core sigma) = h.base at hbase'
    exact hbase'.symm
  rcases geomTransportAlongHom_incomingFactor_existsUnique
      G K sigma factorBase h hbase with ⟨factor, hfactor, hunique⟩
  refine ⟨factor, ?_, ?_⟩
  · constructor
    · rw [← hfactor.1]
      change (geometryProjection U).IsHomLift
        ((geometryProjection U).map factor) factor
      infer_instance
    · exact hfactor.2
  · intro candidate hcandidate
    apply hunique candidate
    constructor
    · letI : (geometryProjection U).IsHomLift factorBase candidate :=
        hcandidate.1
      exact (CategoryTheory.IsHomLift.eq_of_isHomLift
        (geometryProjection U) factorBase candidate).symm
    · exact hcandidate.2

/-- Canonical complete-geometry push transport is strongly Cartesian for the
composed projection over its definitionally projected pointed arrow. -/
theorem geomTransportAlongHom_crossStageStronglyCartesian_map
    {U : AtomCarrier.{u}}
    (G : GeometryPackage.{u, v} U)
    {E : ExtractionDoctrine U}
    (sigma : ExactDoctrineHom G.core.reading.doctrine E) :
    (crossStageProjection.{u, v} U).IsStronglyCartesian
      ((crossStageProjection.{u, v} U).map
        (geomTransportAlongHom G sigma))
      (geomTransportAlongHom G sigma) := by
  letI : (geometryProjection U).IsStronglyCartesian
      ((geometryProjection U).map (geomTransportAlongHom G sigma))
      (geomTransportAlongHom G sigma) := by
    simpa using geomTransportAlongHom_isStronglyCartesian G sigma
  letI : (packageProjection U).IsStronglyCartesian
      ((packageProjection U).map
        ((geometryProjection U).map (geomTransportAlongHom G sigma)))
      ((geometryProjection U).map (geomTransportAlongHom G sigma)) := by
    simpa using AAT.AG.DoctrineFiberProduct.transportAlongHom_isStronglyCartesian
      G.core sigma
  exact stronglyCartesian_comp_projection
    (geometryProjection U) (packageProjection U)
    (geomTransportAlongHom G sigma)

/-- G-122 B1: the canonical complete-geometry fiber push is strongly
Cartesian over the authored semantic hom, not merely over its projected map. -/
theorem geomFiberLift_crossStageStronglyCartesian
    {U : AtomCarrier.{u}}
    {X Y : ExtractionInstance U} (sigma : X ⟶ Y)
    (G : GeomFiber.{u, v} X) :
    (crossStageProjection.{u, v} U).IsStronglyCartesian sigma
      (geomFiberLift sigma G) := by
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      ((crossStageProjection.{u, v} U).map (geomFiberLift sigma G))
      (geomFiberLift sigma G) :=
    geomTransportAlongHom_crossStageStronglyCartesian_map
      G.1 (geomFiberBaseHom sigma G).doctrineHom
  letI : (crossStageProjection.{u, v} U).IsHomLift sigma
      (geomFiberLift sigma G) := geomFiberLift_isHomLift sigma G
  exact stronglyCartesian_of_isHomLift
    (crossStageProjection.{u, v} U) sigma (geomFiberLift sigma G)

end AAT.AG.FullGeometryNormalization

#assert_standard_axioms_only AAT.AG.FullGeometryNormalization
