import ResearchLean.AG.DoctrineFiberProduct.UpperGeometryCartesian
import ResearchLean.AG.CrossStageCoherence.FiberTransport

/-!
# Exact complete-geometry pullback over a realized arrow

This module starts G-122(B1) from the existing exact geometry cleavage.  A
`RealizableHom` and a geometry in its target fiber determine the pointed exact
arrow used by `exactSourceGeometry`; the pulled geometry and its complete lift
are therefore generated from the authored arrow and the target geometry.

No complete geometry hom or cartesian certificate is accepted from the caller.
The refinement-level universal property is exactified back to the complete
geometry category, and then composed with the exact core-package cleavage.
This produces the cross-stage cartesian lift and its induced geometry-fiber
reindexing without accepting either a lift or a cartesian certificate.

## Implementation notes

The target object is taken in the existing `GeomFiber`, so its stored fiber
equality supplies exactly the endpoint cast needed to compose the authored
realized arrow with `exactSourceGeometry`.  Introducing a new geometry package
record or accepting a prebuilt lift was rejected: both would bypass the
reviewed G-115 exact cleavage instead of applying it to the G-122 input.
-/

namespace AAT.AG.FullGeometryNormalization

universe u v u₁ u₂ u₃ v₁ v₂ v₃

open CategoryTheory AtomFoundation GeometryTransport CrossStageCoherence
open DoctrineFiberProduct

set_option maxHeartbeats 3000000

/-- The pointed exact arrow obtained from the realized arrow and the target
geometry fiber equality. -/
noncomputable def exactGeometryPullBaseHom
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    input.semantic.source ⟶ packagePoint target.1.core :=
  input.semantic.hom ≫ eqToHom target.2.symm

/-- The canonical complete geometry pulled back along a realized arrow. -/
noncomputable def exactGeometryPullObject
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    GeomReadCategory.{u, v} U :=
  UpperGeometryCleavage.exactSourceGeometry target.1
    (exactGeometryPullBaseHom input target)

/-- The canonical pullback geometry lies over the source of the realized
arrow. -/
theorem exactGeometryPullObject_point
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (crossStageProjection.{u, v} U).obj
        (exactGeometryPullObject input target) = input.semantic.source := by
  change packagePoint
      (UpperGeometryCleavage.exactSourceGeometry target.1
        (exactGeometryPullBaseHom input target)).core = input.semantic.source
  rw [UpperGeometryCleavage.exactSourceGeometry_core]
  exact inverseCorePackage_point target.1.core
    (exactGeometryPullBaseHom input target)

/-- The canonical complete-geometry pullback, placed in the source fiber. -/
noncomputable def exactGeometryPull
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    GeomFiber.{u, v} input.semantic.source :=
  ⟨exactGeometryPullObject input target,
    exactGeometryPullObject_point input target⟩

/-- The exact pullback retains the target coefficient ring definitionally;
the simp normal form points from the generated object to the input target. -/
@[simp] theorem exactGeometryPull_coefficient
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (exactGeometryPull input target).1.Coefficient = target.1.Coefficient :=
  UpperGeometryCleavage.exactSourceGeometry_coefficient_eq target.1
    (exactGeometryPullBaseHom input target)

/-- The core of the complete-geometry pullback is the canonical exact inverse
package over the realized arrow; the simp normal form exposes that predecessor
construction. -/
@[simp] theorem exactGeometryPull_core
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (exactGeometryPull input target).1.core =
      inverseCorePackage target.1.core
        (exactGeometryPullBaseHom input target) :=
  UpperGeometryCleavage.exactSourceGeometry_core target.1
    (exactGeometryPullBaseHom input target)

/-- The complete exact geometry lift generated by the canonical cleavage. -/
noncomputable def exactGeometryPullLift
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (exactGeometryPull input target).1 ⟶ target.1 :=
  UpperGeometryCleavage.generatedExactGeometryHom target.1
    (exactGeometryPullBaseHom input target)

/-- The generated lift has the canonical exact inverse-package map as its
core projection; the simp normal form exposes the core-stage map. -/
@[simp] theorem exactGeometryPullLift_coreProjection
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (geometryProjection U).map (exactGeometryPullLift input target) =
      UpperGeometryCleavage.exactBaseHom target.1
        (exactGeometryPullBaseHom input target) :=
  rfl

/-- The coefficient component of the generated complete lift is the identity
under the definitional coefficient identification; the simp normal form removes
the generated coefficient map. -/
@[simp] theorem exactGeometryPullLift_coefficientHom
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (exactGeometryPullLift input target).geometry.coefficientHom =
      RingHom.id target.1.Coefficient :=
  rfl

/-- The complete lift projects to the exact arrow obtained from the realized
arrow and the target fiber equality; the simp normal form exposes that authored
base composite. -/
@[simp] theorem exactGeometryPullLift_crossStageProjection
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (crossStageProjection.{u, v} U).map
        (exactGeometryPullLift input target) =
      exactGeometryPullBaseHom input target :=
  rfl

/-- After exact-to-refinement embedding, the generated complete lift is the
strongly cartesian geometry cleavage over its exact core projection. -/
theorem exactGeometryPullLift_refinementStronglyCartesian
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (refinementGeometryProjection U).IsStronglyCartesian
      ((exactPackageToRefinement U).map
        (UpperGeometryCleavage.exactBaseHom target.1
          (exactGeometryPullBaseHom input target)))
      ((exactGeometryToRefinementGeometry U).map
        (exactGeometryPullLift input target)) :=
  UpperGeometryCleavage.generatedExactGeometryHom_isStronglyCartesian
    target.1 (exactGeometryPullBaseHom input target)

/-- The exact complete lift is strongly Cartesian over its exact core-package
projection.  Its universal factor is obtained in the refinement category and
then exactified over the original exact package map. -/
theorem exactGeometryPullLift_geometryStronglyCartesian
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (geometryProjection U).IsStronglyCartesian
      (UpperGeometryCleavage.exactBaseHom target.1
        (exactGeometryPullBaseHom input target))
      (exactGeometryPullLift input target) := by
  let lift := exactGeometryPullLift input target
  let refinementLift := (exactGeometryToRefinementGeometry U).map lift
  letI : (refinementGeometryProjection U).IsStronglyCartesian
      ((exactPackageToRefinement U).map
        (UpperGeometryCleavage.exactBaseHom target.1
          (exactGeometryPullBaseHom input target))) refinementLift :=
    exactGeometryPullLift_refinementStronglyCartesian input target
  letI : (geometryProjection U).IsHomLift
      (UpperGeometryCleavage.exactBaseHom target.1
        (exactGeometryPullBaseHom input target)) lift := by
    apply CategoryTheory.IsHomLift.of_fac'
      (geometryProjection U) _ lift rfl rfl
    rfl
  apply CategoryTheory.Functor.IsStronglyCartesian.mk
  intro K g h hLift
  letI : (geometryProjection U).IsHomLift
      (g ≫ UpperGeometryCleavage.exactBaseHom target.1
        (exactGeometryPullBaseHom input target)) h := hLift
  let refinementH := (exactGeometryToRefinementGeometry U).map h
  let refinementG := (exactPackageToRefinement U).map g
  have refinementHBase : refinementH.base = refinementG.comp
      ((exactPackageToRefinement U).map
        (UpperGeometryCleavage.exactBaseHom target.1
          (exactGeometryPullBaseHom input target))) := by
    have hbase : h.base =
        g ≫ UpperGeometryCleavage.exactBaseHom target.1
          (exactGeometryPullBaseHom input target) :=
      (CategoryTheory.IsHomLift.eq_of_isHomLift
        (geometryProjection U)
        (g ≫ UpperGeometryCleavage.exactBaseHom target.1
          (exactGeometryPullBaseHom input target)) h).symm
    change (exactPackageToRefinement U).map h.base = _
    simpa only [Functor.map_comp] using
      congrArg (exactPackageToRefinement U).map hbase
  let refinementFactor :=
    UpperGeometryCleavage.generatedExactCartesianFactor target.1
      (exactGeometryPullBaseHom input target) refinementG refinementH
      refinementHBase
  let factor := UpperGeometryCleavage.exactGeometryHomOfRefinement g
    refinementFactor rfl
  refine ⟨factor, ?_, ?_⟩
  · constructor
    · apply CategoryTheory.IsHomLift.of_fac'
        (geometryProjection U) g factor rfl rfl
      rfl
    · apply (exactGeometryToRefinementGeometry U).map_injective
      rw [(exactGeometryToRefinementGeometry U).map_comp]
      change refinementFactor ≫ refinementLift = refinementH
      exact UpperGeometryCleavage.generatedExactCartesianFactor_fac target.1
        (exactGeometryPullBaseHom input target) refinementG refinementH
        refinementHBase
  · intro factor' hfactor'
    apply (exactGeometryToRefinementGeometry U).map_injective
    apply UpperGeometryCleavage.generatedExactCartesianFactor_unique target.1
      (exactGeometryPullBaseHom input target) refinementG refinementH
      refinementHBase
    · letI : (geometryProjection U).IsHomLift g factor' := hfactor'.1
      have hfactorBase := CategoryTheory.IsHomLift.eq_of_isHomLift
        (geometryProjection U) g factor'
      change (exactPackageToRefinement U).map factor'.base = refinementG
      exact congrArg (exactPackageToRefinement U).map hfactorBase.symm
    · change (exactGeometryToRefinementGeometry U).map
          (factor' ≫ lift) = refinementH
      rw [hfactor'.2]

/-- Strong Cartesian morphisms compose through two successive projections.
The factor is obtained first in the lower projection and then in the upper
projection, dual to the existing cocartesian tower lemma. -/
theorem stronglyCartesian_comp_projection
    {𝒳 : Type u₁} {𝒴 : Type u₂} {𝒵 : Type u₃}
    [Category.{v₁} 𝒳] [Category.{v₂} 𝒴] [Category.{v₃} 𝒵]
    (q : 𝒳 ⥤ 𝒴) (p : 𝒴 ⥤ 𝒵)
    {a b : 𝒳} (φ : a ⟶ b)
    [q.IsStronglyCartesian (q.map φ) φ]
    [p.IsStronglyCartesian (p.map (q.map φ)) (q.map φ)] :
    (q ⋙ p).IsStronglyCartesian ((q ⋙ p).map φ) φ := by
  apply CategoryTheory.Functor.IsStronglyCartesian.mk
  intro c g ψ hψ
  letI : (q ⋙ p).IsHomLift
      (g ≫ (q ⋙ p).map φ) ψ := hψ
  letI : p.IsHomLift
      (g ≫ p.map (q.map φ)) (q.map ψ) := by
    have hmap := CategoryTheory.IsHomLift.eq_of_isHomLift
      (q ⋙ p) (g ≫ (q ⋙ p).map φ) ψ
    change g ≫ p.map (q.map φ) = p.map (q.map ψ) at hmap
    rw [hmap]
    infer_instance
  rcases CategoryTheory.Functor.IsStronglyCartesian.universal_property
      p (p.map (q.map φ)) (q.map φ) g
      (g ≫ p.map (q.map φ)) rfl (q.map ψ) with
    ⟨η, hη, hη_unique⟩
  letI : p.IsHomLift g η := hη.1
  letI : q.IsHomLift (η ≫ q.map φ) ψ := by
    rw [hη.2]
    infer_instance
  rcases CategoryTheory.Functor.IsStronglyCartesian.universal_property
      q (q.map φ) φ η (η ≫ q.map φ) rfl ψ with
    ⟨χ, hχ, hχ_unique⟩
  letI : q.IsHomLift η χ := hχ.1
  have compositeLift : (q ⋙ p).IsHomLift g χ := by
    have hq := CategoryTheory.IsHomLift.eq_of_isHomLift q η χ
    have hp := CategoryTheory.IsHomLift.eq_of_isHomLift p g η
    have hmap : g = (q ⋙ p).map χ := by
      change g = p.map (q.map χ)
      calc
        g = p.map η := hp
        _ = p.map (q.map χ) := congrArg p.map hq
    rw [hmap]
    infer_instance
  refine ⟨χ, ⟨compositeLift, hχ.2⟩, ?_⟩
  intro χ' hχ'
  letI : (q ⋙ p).IsHomLift g χ' := hχ'.1
  letI : p.IsHomLift g (q.map χ') := by
    have hmap := CategoryTheory.IsHomLift.eq_of_isHomLift (q ⋙ p) g χ'
    change g = p.map (q.map χ') at hmap
    subst g
    infer_instance
  have hqfac : q.map χ' ≫ q.map φ = q.map ψ := by
    simpa only [← q.map_comp] using congrArg q.map hχ'.2
  have hqχ' : q.map χ' = η :=
    hη_unique (q.map χ') ⟨inferInstance, hqfac⟩
  letI : q.IsHomLift η χ' := by
    rw [← hqχ']
    infer_instance
  exact hχ_unique χ' ⟨inferInstance, hχ'.2⟩

/-- The generated complete lift is strongly Cartesian for the composed
geometry-to-pointed projection over its actual projected arrow. -/
theorem exactGeometryPullLift_crossStageStronglyCartesian_map
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (crossStageProjection.{u, v} U).IsStronglyCartesian
      ((crossStageProjection.{u, v} U).map
        (exactGeometryPullLift input target))
      (exactGeometryPullLift input target) := by
  letI : (geometryProjection U).IsStronglyCartesian
      ((geometryProjection U).map (exactGeometryPullLift input target))
      (exactGeometryPullLift input target) := by
    simpa only [exactGeometryPullLift_coreProjection] using
      exactGeometryPullLift_geometryStronglyCartesian input target
  letI : (packageProjection U).IsStronglyCartesian
      ((packageProjection U).map
        ((geometryProjection U).map (exactGeometryPullLift input target)))
      ((geometryProjection U).map (exactGeometryPullLift input target)) := by
    simpa only [exactGeometryPullLift_coreProjection] using
      AAT.AG.DoctrineFiberProduct.inverseCorePackageHom_isStronglyCartesian
        target.1.core
        (exactGeometryPullBaseHom input target)
  exact stronglyCartesian_comp_projection
    (geometryProjection U) (packageProjection U)
    (exactGeometryPullLift input target)

/-- The generated complete lift is a genuine lift of the authored semantic
arrow, including both endpoint equalities stored by the source and target
fiber objects. -/
theorem exactGeometryPullLift_isHomLift
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      (exactGeometryPullLift input target) := by
  apply CategoryTheory.IsHomLift.of_commsq
    (crossStageProjection.{u, v} U) input.semantic.hom
    (exactGeometryPullLift input target)
    (exactGeometryPull input target).2 target.2
  change (input.semantic.hom ≫ eqToHom target.2.symm) ≫
      eqToHom target.2 =
    eqToHom (exactGeometryPull input target).2 ≫ input.semantic.hom
  simp

/-- Reindex a strong Cartesian certificate along a genuine hom-lift witness
for the same total morphism. -/
theorem stronglyCartesian_of_isHomLift
    {Base : Type u₁} {Total : Type u₂}
    [Category.{v₁} Base] [Category.{v₂} Total]
    (projection : Total ⥤ Base) {source target : Base}
    {domain codomain : Total} (base : source ⟶ target)
    (hom : domain ⟶ codomain)
    [projection.IsStronglyCartesian (projection.map hom) hom]
    [projection.IsHomLift base hom] :
    projection.IsStronglyCartesian base hom := by
  subst_hom_lift projection base hom
  infer_instance

/-- The exact lift is strongly Cartesian over the authored semantic arrow,
not merely over its definitionally exposed endpoint-cast composite. -/
theorem exactGeometryPullLift_crossStageStronglyCartesian
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    (crossStageProjection.{u, v} U).IsStronglyCartesian input.semantic.hom
      (exactGeometryPullLift input target) := by
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      ((crossStageProjection.{u, v} U).map
        (exactGeometryPullLift input target))
      (exactGeometryPullLift input target) :=
    exactGeometryPullLift_crossStageStronglyCartesian_map input target
  letI : (crossStageProjection.{u, v} U).IsHomLift input.semantic.hom
      (exactGeometryPullLift input target) :=
    exactGeometryPullLift_isHomLift input target
  exact stronglyCartesian_of_isHomLift
    (crossStageProjection.{u, v} U) input.semantic.hom
    (exactGeometryPullLift input target)

/-- A vertical morphism in the target geometry fiber is pulled back by the
strong Cartesian universal property of the exact lift at its codomain. -/
noncomputable def exactGeometryPullMap
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    {first second : GeomFiber.{u, v} input.semantic.target}
    (hom : first ⟶ second) :
    exactGeometryPull input first ⟶ exactGeometryPull input second := by
  let firstLift := exactGeometryPullLift input first
  let secondLift := exactGeometryPullLift input second
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      input.semantic.hom secondLift :=
    exactGeometryPullLift_crossStageStronglyCartesian input second
  letI : (crossStageProjection.{u, v} U).IsHomLift
      input.semantic.hom firstLift :=
    exactGeometryPullLift_isHomLift input first
  letI : (crossStageProjection.{u, v} U).IsHomLift
      (𝟙 input.semantic.target) hom.1 := hom.2
  letI : (crossStageProjection.{u, v} U).IsHomLift
      input.semantic.hom (firstLift ≫ hom.1) := by
    simpa using inferInstanceAs
      ((crossStageProjection.{u, v} U).IsHomLift
        (input.semantic.hom ≫ 𝟙 input.semantic.target)
        (firstLift ≫ hom.1))
  exact ⟨CategoryTheory.Functor.IsStronglyCartesian.map
      (crossStageProjection.{u, v} U) input.semantic.hom secondLift
      (g := 𝟙 input.semantic.source) (f' := input.semantic.hom)
      (Category.id_comp input.semantic.hom).symm
      (firstLift ≫ hom.1), inferInstance⟩

/-- The pulled vertical morphism satisfies its defining factorization through
the exact lift at the target object. -/
theorem exactGeometryPullMap_fac
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    {first second : GeomFiber.{u, v} input.semantic.target}
    (hom : first ⟶ second) :
    (exactGeometryPullMap input hom).1 ≫
        exactGeometryPullLift input second =
      exactGeometryPullLift input first ≫ hom.1 := by
  let firstLift := exactGeometryPullLift input first
  let secondLift := exactGeometryPullLift input second
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      input.semantic.hom secondLift :=
    exactGeometryPullLift_crossStageStronglyCartesian input second
  letI : (crossStageProjection.{u, v} U).IsHomLift
      input.semantic.hom firstLift :=
    exactGeometryPullLift_isHomLift input first
  letI : (crossStageProjection.{u, v} U).IsHomLift
      (𝟙 input.semantic.target) hom.1 := hom.2
  letI : (crossStageProjection.{u, v} U).IsHomLift
      input.semantic.hom (firstLift ≫ hom.1) := by
    simpa using inferInstanceAs
      ((crossStageProjection.{u, v} U).IsHomLift
        (input.semantic.hom ≫ 𝟙 input.semantic.target)
        (firstLift ≫ hom.1))
  exact CategoryTheory.Functor.IsStronglyCartesian.fac
    (crossStageProjection.{u, v} U) input.semantic.hom secondLift
    (Category.id_comp input.semantic.hom).symm (firstLift ≫ hom.1)

/-- Exact geometry pullback preserves vertical identities. -/
theorem exactGeometryPullMap_id
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    (target : GeomFiber.{u, v} input.semantic.target) :
    exactGeometryPullMap input (𝟙 target) =
      𝟙 (exactGeometryPull input target) := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let lift := exactGeometryPullLift input target
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      input.semantic.hom lift :=
    exactGeometryPullLift_crossStageStronglyCartesian input target
  apply CategoryTheory.Functor.IsStronglyCartesian.ext
    (crossStageProjection.{u, v} U) input.semantic.hom lift
    (𝟙 input.semantic.source)
  simpa using exactGeometryPullMap_fac input (𝟙 target)

/-- Exact geometry pullback preserves composition of vertical morphisms. -/
theorem exactGeometryPullMap_comp
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U)
    {first second third : GeomFiber.{u, v} input.semantic.target}
    (f : first ⟶ second) (g : second ⟶ third) :
    exactGeometryPullMap input (f ≫ g) =
      exactGeometryPullMap input f ≫ exactGeometryPullMap input g := by
  apply CategoryTheory.Functor.Fiber.hom_ext
  let thirdLift := exactGeometryPullLift input third
  letI : (crossStageProjection.{u, v} U).IsStronglyCartesian
      input.semantic.hom thirdLift :=
    exactGeometryPullLift_crossStageStronglyCartesian input third
  apply CategoryTheory.Functor.IsStronglyCartesian.ext
    (crossStageProjection.{u, v} U) input.semantic.hom thirdLift
    (𝟙 input.semantic.source)
  change (exactGeometryPullMap input (f ≫ g)).1 ≫
      exactGeometryPullLift input third =
    ((exactGeometryPullMap input f).1 ≫
      (exactGeometryPullMap input g).1) ≫
      exactGeometryPullLift input third
  calc
    _ = exactGeometryPullLift input first ≫ (f ≫ g).1 :=
      exactGeometryPullMap_fac input (f ≫ g)
    _ = (exactGeometryPullLift input first ≫ f.1) ≫ g.1 :=
      (Category.assoc _ _ _).symm
    _ = ((exactGeometryPullMap input f).1 ≫
        exactGeometryPullLift input second) ≫ g.1 :=
      congrArg (fun h => h ≫ g.1)
        (exactGeometryPullMap_fac input f).symm
    _ = (exactGeometryPullMap input f).1 ≫
        (exactGeometryPullLift input second ≫ g.1) :=
      Category.assoc _ _ _
    _ = (exactGeometryPullMap input f).1 ≫
        ((exactGeometryPullMap input g).1 ≫
          exactGeometryPullLift input third) :=
      congrArg (fun h => (exactGeometryPullMap input f).1 ≫ h)
        (exactGeometryPullMap_fac input g).symm
    _ = _ := (Category.assoc _ _ _).symm

/-- Reindexing of complete geometry fibers generated by the exact Cartesian
cleavage over a realized arrow. -/
noncomputable def exactGeometryPullFunctor
    {U : AtomCarrier.{u}} [DecidableEq U.Atom]
    (input : RealizableHom U) :
    GeomFiber.{u, v} input.semantic.target ⥤
      GeomFiber.{u, v} input.semantic.source where
  obj := exactGeometryPull input
  map := exactGeometryPullMap input
  map_id := exactGeometryPullMap_id input
  map_comp := exactGeometryPullMap_comp input

end AAT.AG.FullGeometryNormalization

#assert_standard_axioms_only AAT.AG.FullGeometryNormalization
