import Mathlib.CategoryTheory.Adjunction.Mates
import ResearchLean.AG.DoctrineFiberProduct.BCPresentationReplacement
import ResearchLean.AG.DoctrineFiberProduct.BCHorizontalPastingComparisonFactorization
import ResearchLean.AG.DiagnosticConservativity.TransportAdjunction

/-!
# The core Beck--Chevalley mate of a semantic square

The mate is generated from the core transport square comparison and the
semantic-global transport/reindex adjunctions of the actual left and right
arrows. No finite presentation or caller-supplied mate enters the definition.
-/

namespace AAT.AG.FullGeometryNormalization

universe u

open CategoryTheory AtomFoundation CrossStageCoherence
open DoctrineFiberProduct

set_option maxHeartbeats 3000000

/-- The core mate for an arbitrary semantic Beck--Chevalley square. -/
noncomputable def semanticCoreBeckChevalleyMate
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    exact_bottom_semantic_global_reindex_functor input.square.left ⋙
        coreFiberTransportFunctor input.square.top ⟶
      coreFiberTransportFunctor input.square.bottom ⋙
        exact_bottom_semantic_global_reindex_functor input.square.right :=
  (mateEquiv
    (semanticGlobalTransportReindexAdjunction input.square.left)
    (semanticGlobalTransportReindexAdjunction input.square.right)
    (bcSemanticCoreTransportSquareIso input).hom).natTrans

/-- The semantic core mate is generated by the right unit, the covariant
square comparison, and the left counit. -/
theorem semanticCoreBeckChevalleyMate_app
    {U : AtomCarrier.{u}} (input : BCSemanticInput U)
    (source : CoreFiber input.square.southwest) :
    (semanticCoreBeckChevalleyMate input).app source =
      (semanticGlobalTransportReindexAdjunction input.square.right).unit.app
        ((coreFiberTransportFunctor input.square.top).obj
          ((exact_bottom_semantic_global_reindex_functor
            input.square.left).obj source)) ≫
      (exact_bottom_semantic_global_reindex_functor input.square.right).map
        ((bcSemanticCoreTransportSquareIso input).hom.app
          ((exact_bottom_semantic_global_reindex_functor
            input.square.left).obj source)) ≫
      (exact_bottom_semantic_global_reindex_functor input.square.right).map
        ((coreFiberTransportFunctor input.square.bottom).map
          ((semanticGlobalTransportReindexAdjunction
            input.square.left).counit.app source)) := by
  simp [semanticCoreBeckChevalleyMate, mateEquiv_apply]

/-- After the selected right Cartesian lift, the core mate becomes the
transported covariant square comparison followed by the left counit. -/
theorem semanticCoreBeckChevalleyMate_app_selectedLift_fac
    {U : AtomCarrier.{u}} (input : BCSemanticInput U)
    (source : CoreFiber input.square.southwest) :
    ((semanticCoreBeckChevalleyMate input).app source).1 ≫
      (exact_bottom_semantic_global_selected_lift input.square.right
        ((coreFiberTransportFunctor input.square.bottom).obj source)).hom =
    coreFiberLift input.square.right
      ((coreFiberTransportFunctor input.square.top).obj
        ((exact_bottom_semantic_global_reindex_functor
          input.square.left).obj source)) ≫
      ((bcSemanticCoreTransportSquareIso input).hom.app
        ((exact_bottom_semantic_global_reindex_functor
          input.square.left).obj source)).1 ≫
      ((coreFiberTransportFunctor input.square.bottom).map
        ((semanticGlobalTransportReindexAdjunction
          input.square.left).counit.app source)).1 := by
  rw [semanticCoreBeckChevalleyMate_app]
  change
    (((semanticGlobalTransportReindexAdjunction input.square.right).unit.app
      ((coreFiberTransportFunctor input.square.top).obj
        ((exact_bottom_semantic_global_reindex_functor input.square.left).obj
          source))).1 ≫
      ((exact_bottom_semantic_global_reindex_functor input.square.right).map
        ((bcSemanticCoreTransportSquareIso input).hom.app
          ((exact_bottom_semantic_global_reindex_functor
            input.square.left).obj source))).1 ≫
      ((exact_bottom_semantic_global_reindex_functor input.square.right).map
        ((coreFiberTransportFunctor input.square.bottom).map
          ((semanticGlobalTransportReindexAdjunction
            input.square.left).counit.app source))).1) ≫
      (exact_bottom_semantic_global_selected_lift input.square.right
        ((coreFiberTransportFunctor input.square.bottom).obj source)).hom = _
  have hmapCounit := exact_bottom_semantic_global_reindex_map_fac
    input.square.right
    ((coreFiberTransportFunctor input.square.bottom).map
      ((semanticGlobalTransportReindexAdjunction
        input.square.left).counit.app source))
  simp only [Functor.id_obj] at hmapCounit
  have hmapSquare := exact_bottom_semantic_global_reindex_map_fac
    input.square.right
    ((bcSemanticCoreTransportSquareIso input).hom.app
      ((exact_bottom_semantic_global_reindex_functor
        input.square.left).obj source))
  simp only [Functor.comp_obj] at hmapSquare
  simp only [Category.assoc]
  rw [hmapCounit]
  simp only [Functor.comp_obj]
  let unit := ((semanticGlobalTransportReindexAdjunction
    input.square.right).unit.app
      ((coreFiberTransportFunctor input.square.top).obj
        ((exact_bottom_semantic_global_reindex_functor
          input.square.left).obj source))).1
  let counitMap := ((coreFiberTransportFunctor input.square.bottom).map
    ((semanticGlobalTransportReindexAdjunction
      input.square.left).counit.app source)).1
  have h1 := congrArg (fun h => unit ≫ h ≫ counitMap) hmapSquare
  have hunit := semanticGlobalTransportReindexUnit_app_fac
    input.square.right
    ((coreFiberTransportFunctor input.square.top).obj
      ((exact_bottom_semantic_global_reindex_functor
        input.square.left).obj source))
  have h2 := congrArg (fun h => h ≫
    ((bcSemanticCoreTransportSquareIso input).hom.app
      ((exact_bottom_semantic_global_reindex_functor
        input.square.left).obj source)).1 ≫ counitMap) hunit
  simpa only [unit, counitMap, Category.assoc] using h1.trans h2

/-- The semantic core mate has the Beck--Chevalley iterated-lift square as
its defining factorization at each southwest core package. -/
theorem semanticCoreBeckChevalleyMate_app_iterated_fac
    {U : AtomCarrier.{u}} (input : BCSemanticInput U)
    (source : CoreFiber input.square.southwest) :
    coreFiberLift input.square.top
        ((exact_bottom_semantic_global_reindex_functor
          input.square.left).obj source) ≫
      ((semanticCoreBeckChevalleyMate input).app source).1 ≫
      (exact_bottom_semantic_global_selected_lift input.square.right
        ((coreFiberTransportFunctor input.square.bottom).obj source)).hom =
    (exact_bottom_semantic_global_selected_lift input.square.left
        source).hom ≫
      coreFiberLift input.square.bottom source := by
  let selectedLeft := (exact_bottom_semantic_global_reindex_functor
    input.square.left).obj source
  have mateFac := semanticCoreBeckChevalleyMate_app_selectedLift_fac
    input source
  have squareFac := bcSemanticCoreTransportSquareIso_hom_fac
    input selectedLeft
  have bottomMapFac := coreFiberTransportMap_fac input.square.bottom
    ((semanticGlobalTransportReindexAdjunction
      input.square.left).counit.app source)
  have leftCounitFac := semanticGlobalTransportReindexCounit_app_fac
    input.square.left source
  calc
    _ = coreFiberIteratedLift input.square.top input.square.right
          selectedLeft ≫
        ((bcSemanticCoreTransportSquareIso input).hom.app
          selectedLeft).1 ≫
        ((coreFiberTransportFunctor input.square.bottom).map
          ((semanticGlobalTransportReindexAdjunction
            input.square.left).counit.app source)).1 := by
      simpa only [coreFiberIteratedLift, Category.assoc] using
        congrArg (fun h => coreFiberLift input.square.top selectedLeft ≫ h)
          mateFac
    _ = coreFiberIteratedLift input.square.left input.square.bottom
          selectedLeft ≫
        ((coreFiberTransportFunctor input.square.bottom).map
          ((semanticGlobalTransportReindexAdjunction
            input.square.left).counit.app source)).1 := by
      simpa only [Category.assoc] using
        congrArg (fun h => h ≫
          ((coreFiberTransportFunctor input.square.bottom).map
            ((semanticGlobalTransportReindexAdjunction
              input.square.left).counit.app source)).1) squareFac
    _ = (coreFiberLift input.square.left selectedLeft ≫
          ((semanticGlobalTransportReindexAdjunction
            input.square.left).counit.app source).1) ≫
        coreFiberLift input.square.bottom source := by
      simp only [Functor.comp_obj, Functor.id_obj] at bottomMapFac
      simpa only [coreFiberIteratedLift, Category.assoc] using
        congrArg (fun h => coreFiberLift input.square.left selectedLeft ≫ h)
          bottomMapFac
    _ = _ := by
      simpa only [Category.assoc, semanticGlobalTransportReindexCounit] using
        congrArg (fun h => h ≫ coreFiberLift input.square.bottom source)
          leftCounitFac

end AAT.AG.FullGeometryNormalization

#assert_standard_axioms_only AAT.AG.FullGeometryNormalization
