import ResearchLean.AG.FullGeometryNormalization.SemanticDerivedRefinementBC

/-!
# Pullback comparisons for a semantic exact square

The generated mixed pullback is compared with the northwest endpoint of a
semantic square under the square's stated pullback premise. The generated
exact target pullback is compared with its northeast endpoint. The endpoint
identifications and the generated pullback certificates follow from the
semantic arrows and their selected-source equations.
-/

namespace AAT.AG.FullGeometryNormalization

universe u

open CategoryTheory CategoryTheory.Limits AtomFoundation CrossStageCoherence
open DoctrineFiberProduct

set_option maxHeartbeats 3000000

/-- The pointed refinement configuration generated by the semantic square. -/
noncomputable def semanticDerivedPointedRefinementBCConfiguration
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    LegacyRefinementBCConfiguration U :=
  (semanticDerivedRefinementBCConfiguration input).pointedConfigurationAt
    (semanticDerivedRefinementBCCompatibleSource input)

/-- The generated exact horizontal comparison. -/
noncomputable def semanticDerivedPulledComparison
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedRefinementBCConfiguration input).pullbackSourceAt
        (semanticDerivedRefinementBCCompatibleSource input) ⟶
      (semanticDerivedRefinementBCConfiguration input).pullbackTargetAt
        (semanticDerivedRefinementBCCompatibleSource input) :=
  pulledExactComparisonAt
    (semanticDerivedRefinementBCConfiguration input)
    (semanticDerivedRefinementBCCompatibleSource input)
    (semanticDerivedRefinementBC_exactImage input)

/-- The generated refined source is the southwest endpoint. -/
theorem semanticDerivedRefinementBCSourcePoint_eq
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedRefinementBCConfiguration input).sourcePointAt
        (semanticDerivedRefinementBCCompatibleSource input) =
      input.square.southwest := by
  rfl

/-- The generated second source is the northeast endpoint. -/
theorem semanticDerivedRefinementBCSecondPoint_eq
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedRefinementBCConfiguration input).secondPointAt
        (semanticDerivedRefinementBCCompatibleSource input) =
      input.square.northeast := by
  rfl

/-- The generated common bottom point is the southeast endpoint. -/
theorem semanticDerivedRefinementBCBottomPoint_eq
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedRefinementBCConfiguration input).bottomPointAt
        (semanticDerivedRefinementBCCompatibleSource input) =
      input.square.southeast := by
  apply ExtractionInstance.ext
  · rfl
  · apply heq_of_eq
    change input.square.bottom.doctrineHom.sourceMap
      input.square.southwest.source = input.square.southeast.source
    exact input.square.bottom.source_eq

/-- First projection of the generated mixed cone at the semantic southwest. -/
noncomputable def semanticDerivedMixedFst
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedRefinementBCConfiguration input).pullbackSourceAt
        (semanticDerivedRefinementBCCompatibleSource input) ⟶
      input.square.southwest :=
  (semanticDerivedPointedRefinementBCConfiguration input).pulledFst ≫
    eqToHom (semanticDerivedRefinementBCSourcePoint_eq input)

/-- Second projection of the generated mixed cone at the semantic northeast. -/
noncomputable def semanticDerivedMixedSnd
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedRefinementBCConfiguration input).pullbackSourceAt
        (semanticDerivedRefinementBCCompatibleSource input) ⟶
      input.square.northeast :=
  semanticDerivedPulledComparison input ≫
    pointedPullbackSnd
      (semanticDerivedPointedRefinementBCConfiguration input).sigmaOne
      (semanticDerivedPointedRefinementBCConfiguration input).sigmaTwo ≫
    eqToHom (semanticDerivedRefinementBCSecondPoint_eq input)

/-- First projection of the generated exact target cone. -/
noncomputable def semanticDerivedTargetFst
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedRefinementBCConfiguration input).pullbackTargetAt
        (semanticDerivedRefinementBCCompatibleSource input) ⟶
      input.square.southeast :=
  (semanticDerivedPointedRefinementBCConfiguration input).pullbackFst ≫
    eqToHom (semanticDerivedRefinementBCTargetPoint_eq input)

/-- Second projection of the generated exact target cone. -/
noncomputable def semanticDerivedTargetSnd
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedRefinementBCConfiguration input).pullbackTargetAt
        (semanticDerivedRefinementBCCompatibleSource input) ⟶
      input.square.northeast :=
  pointedPullbackSnd
      (semanticDerivedPointedRefinementBCConfiguration input).sigmaOne
      (semanticDerivedPointedRefinementBCConfiguration input).sigmaTwo ≫
    eqToHom (semanticDerivedRefinementBCSecondPoint_eq input)

/-- The generated mixed cone is a pullback of the semantic bottom/right cospan. -/
theorem semanticDerivedMixedSource_isPullback
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    IsPullback (semanticDerivedMixedFst input) (semanticDerivedMixedSnd input)
      input.square.bottom input.square.right := by
  have hfst : semanticDerivedMixedFst input =
      pointedPullbackFst input.square.bottom input.square.right := by
    apply ExtInstHom.ext
    apply ExactDoctrineHom.ext <;> rfl
  have hsnd : semanticDerivedMixedSnd input =
      pointedPullbackSnd input.square.bottom input.square.right := by
    apply ExtInstHom.ext
    apply ExactDoctrineHom.ext
    · rfl
    · apply Equiv.ext
      intro atom
      change
        (input.square.bottom.doctrineHom.atomEquiv.trans
          input.square.right.doctrineHom.atomEquiv.symm) atom =
        (input.square.bottom.doctrineHom.atomEquiv.trans
          input.square.right.doctrineHom.atomEquiv.symm) atom
      rfl
  rw [hfst, hsnd]
  exact pointedPullback_isPullback input.square.bottom input.square.right

/-- Inverse to the generated identity first target leg. -/
noncomputable def semanticDerivedTargetFirstInv
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedPointedRefinementBCConfiguration input).Base ⟶
      (semanticDerivedPointedRefinementBCConfiguration input).DOne where
  doctrineHom := ExactDoctrineHom.id _
  source_eq := rfl

/-- The first target cospan leg is an isomorphism. -/
noncomputable def semanticDerivedTargetFirstIso
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedPointedRefinementBCConfiguration input).DOne ≅
      (semanticDerivedPointedRefinementBCConfiguration input).Base where
  hom := (semanticDerivedPointedRefinementBCConfiguration input).sigmaOne
  inv := semanticDerivedTargetFirstInv input
  hom_inv_id := by
    apply ExtInstHom.ext
    apply ExactDoctrineHom.ext
    · rfl
    · apply Equiv.ext
      intro atom
      rfl
  inv_hom_id := by
    apply ExtInstHom.ext
    apply ExactDoctrineHom.ext
    · rfl
    · apply Equiv.ext
      intro atom
      rfl

/-- Compare the generated mixed source with the northwest semantic endpoint. -/
noncomputable def semanticDerivedPullbackSourceIso
    {U : AtomCarrier.{u}} (input : BCSemanticInput U)
    (square_isPullback : IsPullback input.square.left input.square.top
      input.square.bottom input.square.right) :
    (semanticDerivedRefinementBCConfiguration input).pullbackSourceAt
        (semanticDerivedRefinementBCCompatibleSource input) ≅
      input.square.northwest :=
  (semanticDerivedMixedSource_isPullback input).isoIsPullback
    input.square.southwest input.square.northeast square_isPullback

/-- Compare the generated exact target with the northeast semantic endpoint. -/
noncomputable def semanticDerivedPullbackTargetIso
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedRefinementBCConfiguration input).pullbackTargetAt
        (semanticDerivedRefinementBCCompatibleSource input) ≅
      input.square.northeast := by
  let C := semanticDerivedPointedRefinementBCConfiguration input
  letI : IsIso C.sigmaOne := (semanticDerivedTargetFirstIso input).isIso_hom
  let hpb := pointedPullback_isPullback C.sigmaOne C.sigmaTwo
  letI : IsIso (pointedPullbackSnd C.sigmaOne C.sigmaTwo) :=
    hpb.isIso_snd_of_isIso
  exact asIso (pointedPullbackSnd C.sigmaOne C.sigmaTwo) ≪≫
    eqToIso (semanticDerivedRefinementBCSecondPoint_eq input)

/-- The source comparison preserves the southwest projection. -/
theorem semanticDerivedPullbackSourceIso_hom_left
    {U : AtomCarrier.{u}} (input : BCSemanticInput U)
    (square_isPullback : IsPullback input.square.left input.square.top
      input.square.bottom input.square.right) :
    (semanticDerivedPullbackSourceIso input square_isPullback).hom ≫
      input.square.left = semanticDerivedMixedFst input :=
  (semanticDerivedMixedSource_isPullback input).isoIsPullback_hom_fst
    _ _ square_isPullback

/-- The source comparison preserves the northeast projection. -/
theorem semanticDerivedPullbackSourceIso_hom_top
    {U : AtomCarrier.{u}} (input : BCSemanticInput U)
    (square_isPullback : IsPullback input.square.left input.square.top
      input.square.bottom input.square.right) :
    (semanticDerivedPullbackSourceIso input square_isPullback).hom ≫
      input.square.top = semanticDerivedMixedSnd input :=
  (semanticDerivedMixedSource_isPullback input).isoIsPullback_hom_snd
    _ _ square_isPullback

/-- The target comparison is the generated second projection. -/
theorem semanticDerivedPullbackTargetIso_hom
    {U : AtomCarrier.{u}} (input : BCSemanticInput U) :
    (semanticDerivedPullbackTargetIso input).hom =
      semanticDerivedTargetSnd input := by
  rfl

/-- The generated horizontal comparison represents the semantic top edge. -/
theorem semanticDerivedPulledComparison_comparisonSquare
    {U : AtomCarrier.{u}} (input : BCSemanticInput U)
    (square_isPullback : IsPullback input.square.left input.square.top
      input.square.bottom input.square.right) :
    (semanticDerivedPullbackSourceIso input square_isPullback).hom ≫
        input.square.top =
      semanticDerivedPulledComparison input ≫
        (semanticDerivedPullbackTargetIso input).hom := by
  rw [semanticDerivedPullbackSourceIso_hom_top,
    semanticDerivedPullbackTargetIso_hom]
  rfl

end AAT.AG.FullGeometryNormalization

#assert_standard_axioms_only AAT.AG.FullGeometryNormalization
