import ResearchLean.AG.LocalSemanticReconstruction.InducedComponentCriteria
import Mathlib.Combinatorics.SimpleGraph.Connectivity.WalkCounting
import Mathlib.Data.Fintype.Sets
import Formal.Util.AssertStandardAxioms

/-!
# Executable enumeration of finite graph components

An explicit finite enumeration of the vertices and named edges of a fixed
directed multigraph makes its generated undirected reachability relation
decidable.  The decision procedure passes through finite simple-graph path
enumeration; no component representative is chosen.

The resulting decidable relation gives both an explicit finite enumeration
and decidable equality for the component quotient.  The same construction is
then applied to a decidable induced vertex subset.  Boolean equality tests
are proved to decide exactly the pre-existing generated reachability
relations, so the computation is tied to the accepted component
classification rather than to a replacement notion of component.
-/

namespace AAT.AG.LocalSemanticReconstruction

open RealizationReconstruction

namespace FiniteComponent

/-- API helper for G-124(D): the loopless undirected simple graph generated by
a directed relation.  The relation is supplied by the finite-table input. -/
def relationGraph {Vertex : Type*} (relation : Vertex → Vertex → Prop) :
    SimpleGraph Vertex :=
  SimpleGraph.fromRel relation

/-- G-124(D) bridge API: equivalence closure of a relation is reachability in
the undirected simple graph generated by that relation.  Dropped loops are
supplied by reflexivity, and the reverse orientation is supplied by symmetry. -/
theorem eqvGen_iff_relationGraph_reachable
    {Vertex : Type*} [DecidableEq Vertex]
    (relation : Vertex → Vertex → Prop) (first second : Vertex) :
    Relation.EqvGen relation first second ↔
      (relationGraph relation).Reachable first second := by
  constructor
  · intro reachable
    induction reachable with
    | rel first second step =>
        by_cases equal : first = second
        · subst second
          exact SimpleGraph.Reachable.refl first
        · exact SimpleGraph.Adj.reachable ⟨equal, Or.inl step⟩
    | refl vertex =>
        exact SimpleGraph.Reachable.refl vertex
    | symm first second relation inductionHypothesis =>
        exact inductionHypothesis.symm
    | trans first second third firstRelation secondRelation
        firstInduction secondInduction =>
        exact firstInduction.trans secondInduction
  · intro reachable
    rw [SimpleGraph.reachable_iff_reflTransGen] at reachable
    induction reachable with
    | refl =>
        exact Relation.EqvGen.refl _
    | tail firstReachable adjacent inductionHypothesis =>
        apply Relation.EqvGen.trans _ _ _ inductionHypothesis
        rcases adjacent.2 with step | step
        · exact Relation.EqvGen.rel _ _ step
        · exact Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ step)

/-- G-124(D) finite-search API: finite path enumeration decides the
equivalence closure of an explicitly decidable relation on an explicitly
enumerable finite type.  Its typeclass premises are the finite-table input. -/
def finiteEqvGenDecidable
    {Vertex : Type*} [Fintype Vertex] [DecidableEq Vertex]
    (relation : Vertex → Vertex → Prop) [DecidableRel relation] :
    DecidableRel (Relation.EqvGen relation) :=
  fun first second => by
    letI : DecidableRel (relationGraph relation).Adj := by
      dsimp [relationGraph]
      infer_instance
    letI : DecidableRel (relationGraph relation).Reachable := inferInstance
    exact decidable_of_iff
      ((relationGraph relation).Reachable first second)
      (eqvGen_iff_relationGraph_reachable relation first second).symm

/-- G-124(D) graph API: a named directed edge step is decidable by finite
search through the supplied edge enumeration and vertex equality decision. -/
def directedEdgeStepDecidable
    (F : FixedFDirectedMultigraph)
    [Fintype F.Edge] [DecidableEq F.Vertex] :
    DecidableRel (fixedFDirectedEdgeStep F) :=
  fun _ _ => by
    unfold fixedFDirectedEdgeStep
    infer_instance

/-- G-124(D) main decision procedure: generated undirected reachability is
decided from the supplied finite vertex/edge tables and vertex equality. -/
def undirectedReachableDecidable
    (F : FixedFDirectedMultigraph)
    [Fintype F.Vertex] [DecidableEq F.Vertex] [Fintype F.Edge] :
    DecidableRel (FixedFUndirectedReachable F) := by
  letI : DecidableRel (fixedFDirectedEdgeStep F) :=
    directedEdgeStepDecidable F
  exact finiteEqvGenDecidable (fixedFDirectedEdgeStep F)

/-- G-124(D) component-enumeration construction: the accepted quotient of an
explicitly finite graph by generated reachability is explicitly finite.  The
`Fintype` and `DecidableEq` premises are the specified finite-table input. -/
def componentFintype
    (F : FixedFDirectedMultigraph)
    [Fintype F.Vertex] [DecidableEq F.Vertex] [Fintype F.Edge] :
    Fintype (FixedFComponent F) := by
  letI : DecidableRel (FixedFUndirectedReachable F) :=
    undirectedReachableDecidable F
  exact @Quotient.fintype _ _ (fixedFComponentSetoid F)
    (inferInstance : DecidableRel (FixedFUndirectedReachable F))

/-- G-124(D) component API: equality in the accepted component quotient is
decidable from the specified finite-table input. -/
def componentDecidableEq
    (F : FixedFDirectedMultigraph)
    [Fintype F.Vertex] [DecidableEq F.Vertex] [Fintype F.Edge] :
    DecidableEq (FixedFComponent F) := by
  letI : DecidableRel (FixedFUndirectedReachable F) :=
    undirectedReachableDecidable F
  exact @Quotient.decidableEq _ (fixedFComponentSetoid F)
    (inferInstance : DecidableRel (FixedFUndirectedReachable F))

/-- G-124(D) executable API test for the generated components of two vertices;
the finite enumerations and vertex equality are the specified input tables. -/
def componentEqualityTest
    (F : FixedFDirectedMultigraph)
    [Fintype F.Vertex] [DecidableEq F.Vertex] [Fintype F.Edge]
    (first second : F.Vertex) : Bool := by
  letI : DecidableEq (FixedFComponent F) := componentDecidableEq F
  exact decide (fixedFComponentMk F first = fixedFComponentMk F second)

/-- G-124(D) correctness theorem: the executable component equality test
agrees exactly with the accepted generated-reachability classification. -/
@[simp]
theorem componentEqualityTest_eq_true_iff
    (F : FixedFDirectedMultigraph)
    [Fintype F.Vertex] [DecidableEq F.Vertex] [Fintype F.Edge]
    (first second : F.Vertex) :
    componentEqualityTest F first second = true ↔
      FixedFUndirectedReachable F first second := by
  letI : DecidableEq (FixedFComponent F) := componentDecidableEq F
  simp [componentEqualityTest, fixedFComponentMk_eq_iff]

/-- G-124(D) induced-component construction: a supplied decidable vertex
predicate and finite graph tables enumerate the component type of the actual
induced graph. -/
def inducedComponentFintype
    (F : FixedFDirectedMultigraph)
    [Fintype F.Vertex] [DecidableEq F.Vertex] [Fintype F.Edge]
    (S : F.Vertex → Prop) [DecidablePred S] :
    Fintype (InducedComponent.Component F S) := by
  letI : Fintype (InducedComponent.graph F S).Vertex :=
    Subtype.fintype S
  letI : DecidableEq (InducedComponent.graph F S).Vertex := by
    change DecidableEq {vertex : F.Vertex // S vertex}
    exact Subtype.instDecidableEq
  letI : Fintype (InducedComponent.graph F S).Edge :=
    Subtype.fintype
      (fun namedEdge : F.Edge => S (F.source namedEdge) ∧ S (F.target namedEdge))
  exact componentFintype (InducedComponent.graph F S)

/-- G-124(D) induced-component API: equality of components in the actual
induced graph is decidable from the same finite tables and predicate decision. -/
def inducedComponentDecidableEq
    (F : FixedFDirectedMultigraph)
    [Fintype F.Vertex] [DecidableEq F.Vertex] [Fintype F.Edge]
    (S : F.Vertex → Prop) [DecidablePred S] :
    DecidableEq (InducedComponent.Component F S) := by
  letI : Fintype (InducedComponent.graph F S).Vertex :=
    Subtype.fintype S
  letI : DecidableEq (InducedComponent.graph F S).Vertex := by
    change DecidableEq {vertex : F.Vertex // S vertex}
    exact Subtype.instDecidableEq
  letI : Fintype (InducedComponent.graph F S).Edge :=
    Subtype.fintype
      (fun namedEdge : F.Edge => S (F.source namedEdge) ∧ S (F.target namedEdge))
  exact componentDecidableEq (InducedComponent.graph F S)

/-- G-124(D) executable API test for two components in the actual induced
graph, using the supplied finite tables and predicate decision. -/
def inducedComponentEqualityTest
    (F : FixedFDirectedMultigraph)
    [Fintype F.Vertex] [DecidableEq F.Vertex] [Fintype F.Edge]
    (S : F.Vertex → Prop) [DecidablePred S]
    (first second : (InducedComponent.graph F S).Vertex) : Bool := by
  letI : DecidableEq (InducedComponent.Component F S) :=
    inducedComponentDecidableEq F S
  exact decide
    (fixedFComponentMk (InducedComponent.graph F S) first =
      fixedFComponentMk (InducedComponent.graph F S) second)

/-- G-124(D) correctness theorem: the induced-component equality test decides
exactly the pre-existing induced reachability relation. -/
@[simp]
theorem inducedComponentEqualityTest_eq_true_iff
    (F : FixedFDirectedMultigraph)
    [Fintype F.Vertex] [DecidableEq F.Vertex] [Fintype F.Edge]
    (S : F.Vertex → Prop) [DecidablePred S]
    (first second : (InducedComponent.graph F S).Vertex) :
    inducedComponentEqualityTest F S first second = true ↔
      InducedComponent.Reachable F S first second := by
  letI : DecidableEq (InducedComponent.Component F S) :=
    inducedComponentDecidableEq F S
  simp [inducedComponentEqualityTest, fixedFComponentMk_eq_iff]

#assert_standard_axioms_only AAT.AG.LocalSemanticReconstruction.FiniteComponent

end FiniteComponent

end AAT.AG.LocalSemanticReconstruction
