import ResearchLean.AG.LocalSemanticReconstruction.G122DisplayedKernelLiftLocalModel
import Formal.Util.AssertStandardAxioms

/-!
# Group reconstruction and torsor law for the displayed G-122 kernel

The displayed two-case kernel syntax is promoted to an independent group
presentation.  Evaluation is a multiplicative equivalence onto the subgroup
it generates inside the full actual comparison restriction kernel.  On every
represented comparison fiber, this subgroup acts freely and transitively on
the canonical/shifted orbit.

The result includes all-elements subgroup readback, both inverse laws,
multiplication preservation, and unique displacement between any two orbit
points.  It remains a presentation of the displayed `C₂`, not of the full
restriction kernel.
-/

namespace AAT.AG.LocalSemanticReconstruction.G122DisplayedKernelGroupTorsor

open CategoryTheory AtomFoundation DoctrineFiberProduct GeometryTransport
open TransportCoherence FullGeometryNormalization
open AAT.AG.RealizationReconstruction MulAction Set Subgroup

noncomputable section

open G122FourComponentComparisonLocalModel
open G122DisplayedKernelLiftLocalModel
open AAT.AG.RealizationReconstruction.FiniteAxisFoldComparisonRestrictionKernel

/-- Source-owned two-element group syntax. -/
inductive GroupCode
  | identity
  | shift
  deriving DecidableEq

namespace GroupCode

/-- Multiplication table of the source `C₂`. -/
def mul : GroupCode → GroupCode → GroupCode
  | .identity, value => value
  | value, .identity => value
  | .shift, .shift => .identity

/-- The explicit table is a group law. -/
instance : Group GroupCode where
  mul := mul
  one := .identity
  inv := fun value => value
  mul_assoc := by intro a b c; cases a <;> cases b <;> cases c <;> rfl
  one_mul := by intro a; cases a <;> rfl
  mul_one := by intro a; cases a <;> rfl
  inv_mul_cancel := by intro a; cases a <;> rfl

end GroupCode

/-- Evaluate the source group syntax in the full actual restriction kernel. -/
noncomputable def evaluate : GroupCode → restrictionHom.kerᵐᵒᵖ
  | .identity => 1
  | .shift => MulOpposite.op element

/-- Source multiplication evaluates to actual kernel multiplication. -/
theorem evaluate_mul (first second : GroupCode) :
    evaluate (first * second) = evaluate first * evaluate second := by
  cases first <;> cases second
  · change evaluate .identity = evaluate .identity * evaluate .identity
    simp [evaluate]
  · change evaluate .shift = evaluate .identity * evaluate .shift
    simp [evaluate]
  · change evaluate .shift = evaluate .shift * evaluate .identity
    simp [evaluate]
  · apply MulOpposite.unop_injective
    change MulOpposite.unop (evaluate .identity) =
      MulOpposite.unop (evaluate .shift * evaluate .shift)
    simp [evaluate, restrictionKernelElement_mul_self]

/-- Multiplicative evaluation of the independent source group. -/
noncomputable def evaluationHom : GroupCode →* restrictionHom.kerᵐᵒᵖ where
  toFun := evaluate
  map_one' := rfl
  map_mul' := evaluate_mul

/-- Actual evaluation separates the two source group elements. -/
theorem evaluate_injective : Function.Injective evaluate := by
  intro first second equality
  cases first <;> cases second
  · rfl
  · exfalso
    apply element_ne_one
    exact MulOpposite.op_injective equality.symm
  · exfalso
    apply element_ne_one
    exact MulOpposite.op_injective equality
  · rfl

/-- The actual subgroup generated by the displayed source group. -/
noncomputable def ActualSubgroup : Subgroup restrictionHom.kerᵐᵒᵖ :=
  MonoidHom.range evaluationHom

/-- Assemble a source code as an element of the actual generated subgroup. -/
noncomputable def assemble (code : GroupCode) : ActualSubgroup :=
  ⟨evaluate code, ⟨code, rfl⟩⟩

/-- Every actual subgroup element has exactly one source code. -/
theorem code_existsUnique (value : ActualSubgroup) :
    ∃! code : GroupCode, evaluate code = value.1 := by
  rcases value with ⟨value, code, rfl⟩
  refine ⟨code, rfl, ?_⟩
  intro candidate equality
  exact evaluate_injective equality

/-- Read the unique source code from an actual subgroup element. -/
noncomputable def read (value : ActualSubgroup) : GroupCode :=
  Classical.choose (code_existsUnique value)

/-- Reading after assembly is identity. -/
@[simp] theorem read_assemble (code : GroupCode) : read (assemble code) = code := by
  exact ((Classical.choose_spec (code_existsUnique (assemble code))).2 code rfl).symm

/-- Assembly after reading is identity. -/
@[simp] theorem assemble_read (value : ActualSubgroup) :
    assemble (read value) = value := by
  apply Subtype.ext
  exact (Classical.choose_spec (code_existsUnique value)).1

/-- The source presentation is the actual generated subgroup as a group. -/
noncomputable def sourceActualMulEquiv : GroupCode ≃* ActualSubgroup where
  toFun := assemble
  invFun := read
  left_inv := read_assemble
  right_inv := assemble_read
  map_mul' first second := by
    apply Subtype.ext
    exact evaluate_mul first second

/-- Evaluate a group code on the canonical lift over one comparison. -/
noncomputable def orbitLift (comparison : LocalComparisonImage)
    (code : GroupCode) : LiftFiber comparison :=
  evaluate code • G122FourComponentComparisonLocalModel.canonicalLift comparison

/-- The group-code orbit is exactly the accepted displayed two-point image. -/
theorem orbitLift_range_eq_displayedLiftImage
    (comparison : LocalComparisonImage) :
    Set.range (orbitLift comparison) = DisplayedLiftImage comparison := by
  ext lift
  constructor
  · rintro ⟨code, rfl⟩
    cases code
    · exact ⟨false, by simp [orbitLift, displayedLift, evaluate]⟩
    · exact ⟨true, rfl⟩
  · rintro ⟨code, rfl⟩
    cases code
    · exact ⟨.identity, by simp [orbitLift, displayedLift, evaluate]⟩
    · exact ⟨.shift, rfl⟩

/-- The actual orbit separates the two source group codes. -/
theorem orbitLift_injective (comparison : LocalComparisonImage) :
    Function.Injective (orbitLift comparison) := by
  intro first second equality
  cases first <;> cases second
  · rfl
  · exfalso
    exact displayedLift_true_ne_false comparison equality.symm
  · exfalso
    exact displayedLift_true_ne_false comparison equality
  · rfl

/-- Any two points of the displayed orbit differ by one unique element of the
actual generated subgroup. -/
theorem orbitLift_existsUnique_subgroup_displacement
    (comparison : LocalComparisonImage) (first second : GroupCode) :
    ∃! value : ActualSubgroup,
      value.1 • orbitLift comparison first = orbitLift comparison second := by
  let displacement := assemble (second * first⁻¹)
  have displacement_action :
      displacement.1 • orbitLift comparison first = orbitLift comparison second := by
    change evaluate (second * first⁻¹) •
        (evaluate first •
          G122FourComponentComparisonLocalModel.canonicalLift comparison) = _
    rw [← mul_smul, ← evaluate_mul]
    simp [orbitLift]
  refine ⟨displacement, displacement_action, ?_⟩
  · rintro ⟨candidateValue, candidateCode, rfl⟩ equality
    apply Subtype.ext
    change evaluate candidateCode = evaluate (second * first⁻¹)
    have orbitEquality :
        orbitLift comparison (candidateCode * first) = orbitLift comparison second := by
      change evaluate (candidateCode * first) •
          G122FourComponentComparisonLocalModel.canonicalLift comparison = _
      rw [evaluate_mul, mul_smul]
      exact equality
    have codeMulEquality : candidateCode * first = second :=
      orbitLift_injective comparison orbitEquality
    congr 1
    calc
      candidateCode = (candidateCode * first) * first⁻¹ := by simp
      _ = second * first⁻¹ := congrArg (fun code => code * first⁻¹) codeMulEquality

/-- The unique subgroup displacement also holds on the accepted displayed
two-point image. -/
theorem displayedOrbit_existsUnique_subgroup_displacement
    (comparison : LocalComparisonImage)
    (first second : DisplayedLiftImage comparison) :
    ∃! value : ActualSubgroup, value.1 • first.1 = second.1 := by
  rcases first with ⟨first, firstCode, rfl⟩
  rcases second with ⟨second, secondCode, rfl⟩
  cases firstCode <;> cases secondCode
  · change ∃! value : ActualSubgroup,
      value.1 • orbitLift comparison .identity = orbitLift comparison .identity
    exact orbitLift_existsUnique_subgroup_displacement comparison .identity .identity
  · change ∃! value : ActualSubgroup,
      value.1 • orbitLift comparison .identity = orbitLift comparison .shift
    exact orbitLift_existsUnique_subgroup_displacement comparison .identity .shift
  · change ∃! value : ActualSubgroup,
      value.1 • orbitLift comparison .shift = orbitLift comparison .identity
    exact orbitLift_existsUnique_subgroup_displacement comparison .shift .identity
  · change ∃! value : ActualSubgroup,
      value.1 • orbitLift comparison .shift = orbitLift comparison .shift
    exact orbitLift_existsUnique_subgroup_displacement comparison .shift .shift

/-- Comparison reconstruction and the actual generated-kernel torsor law hold
together on the same represented fiber. -/
theorem comparisonCode_and_displayedSubgroup_torsor
    (comparison : LocalComparisonImage)
    (first second : DisplayedLiftImage comparison) :
    (∃! code : LocalCode, G122FourComponentComparisonLocalModel.assemble code = comparison) ∧
    (∃! value : ActualSubgroup, value.1 • first.1 = second.1) :=
  ⟨comparisonCode_existsUnique comparison,
    displayedOrbit_existsUnique_subgroup_displacement comparison first second⟩

end
end AAT.AG.LocalSemanticReconstruction.G122DisplayedKernelGroupTorsor

#assert_standard_axioms_only AAT.AG.LocalSemanticReconstruction.G122DisplayedKernelGroupTorsor
