import Formal.AG.Examples.FiniteModel
import Formal.AG.Atom.LawfulnessZeroLegacy

namespace AAT.AG

namespace FiniteModel

/--
Compatibility display of the finite NoCycle equation as a predicate-valued
law. Standard finite consumers use `equationSystem`.
-/
def noCycleLaw : Law carrier where
  holds A := ¬ hasDependencyCycle A

/-- Compatibility singleton universe generated by the NoCycle display. -/
def lawUniverse : LawUniverse carrier where
  Index := PUnit
  law _ := noCycleLaw
  role _ := LawRole.required
  witnessFamily := { Witness := PUnit, badWitness := fun _ _ => True }
  SelectedReading := PUnit
  selectedReading := PUnit.unit

/-- Every compatibility law in the singleton universe is required. -/
theorem lawUniverse_required (index : lawUniverse.Index) :
    lawUniverse.Required index := by
  cases index
  rfl

/-- The one-way legacy law generated from the finite equation is the NoCycle predicate. -/
theorem equationSystem_legacy_law_eq_noCycleLaw
    (C : Site.ContextPreorderCategory object) :
    (equationSystem C).toLegacyLawUniverse.law PUnit.unit = noCycleLaw := by
  apply Law.ext
  funext A
  apply propext
  exact (equationHolds_iff_noCycle C A).trans Iff.rfl

/-- The generated site legacy display is exactly the finite NoCycle equation. -/
@[simp] theorem site_law_holds_iff_noCycleLaw
    (A : ArchitectureObject carrier) :
    (site.equationSystem.toLegacyLawUniverse.law PUnit.unit).holds A ↔
      noCycleLaw.holds A := by
  change site.equationSystem.EquationHolds PUnit.unit A ↔ ¬ hasDependencyCycle A
  exact site_equationHolds_iff_noCycle A

/-- SD2: the finite site retains the generated core law universe. -/
theorem site_lawUniverse_eq_core :
    site.equationSystem.toLegacyLawUniverse =
      siteCorePackage.equationSystem.toLegacyLawUniverse :=
  rfl

/-- Compatibility count-valued obstruction reading for the NoCycle display. -/
noncomputable def noCycleOmega (_law : Law carrier)
    (A : ArchitectureObject carrier) : Nat := by
  classical
  exact if hasCycleWitness A then 1 else 0

/-- Compatibility obstruction valuation for the NoCycle display. -/
noncomputable def noCycleValuation : ObstructionValuation carrier Nat where
  domain := ObstructionValueDomain.nat
  omega := noCycleOmega

/-- Compatibility zero-reflecting aggregation for the singleton universe. -/
def singletonRequiredAggregation :
    ZeroReflectingAggregation Nat noCycleValuation.domain
      lawUniverse.RequiredIndex where
  aggregate values := values ⟨PUnit.unit, rfl⟩
  zero_reflecting values := by
    constructor
    · intro h index
      cases index with
      | mk index hrequired =>
          cases index
          exact h
    · intro h
      exact h ⟨PUnit.unit, rfl⟩

/-- Compatibility soundness theorem for the NoCycle display. -/
theorem noCycleSound :
    ObstructionSound noCycleValuation noCycleLaw := by
  intro A h
  classical
  have hnot : ¬ hasCycleWitness A := by
    simpa [hasCycleWitness, hasDependencyCycle, noCycleLaw] using h
  simp [noCycleValuation, noCycleOmega, ObstructionValueDomain.nat, hnot]

/-- Compatibility completeness theorem for the NoCycle display. -/
theorem noCycleComplete :
    ObstructionComplete noCycleValuation noCycleLaw := by
  intro A hfailure
  classical
  have hcycle : hasCycleWitness A := by
    exact Classical.byContradiction (fun hnot =>
      hfailure (by
        simpa [hasCycleWitness, hasDependencyCycle, noCycleLaw] using hnot))
  simp [noCycleValuation, noCycleOmega, ObstructionValueDomain.nat, hcycle]

end FiniteModel

end AAT.AG
