import Formal.AG.Examples.FiniteModel
import Formal.AG.Cohomology.FiniteExamples
import Formal.AG.SemanticRepair.Boundary
import Formal.AG.SemanticRepair.LawEquationGeneratedPair
import Mathlib.Data.Int.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.LinearAlgebra.Quotient.Basic

noncomputable section

namespace AAT.AG
namespace Examples
namespace SemanticRepairPart10

open CategoryTheory
open Opposite
open SemanticRepair

/-!
Part X R9 / AC16 finite lawful firing instance.

Example 9.1 is the lawful firing witness.  It is separate from the circle-nerve
nonzero witness used by example 9.2: in this lawful instance the generated
degree-zero class vanishes by theorem 8.1, and that zero reading is the intended
end-to-end firing surface rather than a missing obstruction.
-/

/-! ## Concrete quotient-sheaf instance -/

/-- X.例9.1: the selected quotient coefficient presheaf on the finite site. -/
def quotientPresheaf : Site.AATPresheaf FiniteModel.site where
  obj _ := PUnit
  map _ x := x
  map_id _ := rfl
  map_comp _ _ := rfl

/--
X.例9.1: `quotientIsSheaf` is discharged as a theorem for the concrete finite
singleton quotient instance.  General quotient sheaf comparison remains data.
-/
theorem quotientIsSheaf :
    Site.AATSheafCondition FiniteModel.site quotientPresheaf := by
  intro _base _cover _hcover family _compatible
  refine ⟨PUnit.unit, ?_, ?_⟩
  · intro _Y f hf
    cases family f hf
    rfl
  · intro y _hy
    cases y
    rfl

/-- X.例9.1: concrete obstruction coefficient sheaf generated by the quotient. -/
def quotientObstructionSheaf :
    Cohomology.ObstructionSheaf FiniteModel.site where
  carrier := {
    carrier := quotientPresheaf
    isSheaf := quotientIsSheaf
  }
  addCommGroup W := by
    change AddCommGroup PUnit
    infer_instance
  map_zero := by
    intro _source _target _f
    rfl
  map_add := by
    intro _source _target _f x y
    cases x
    cases y
    rfl

/-! ## Concrete semantic additive and cover-relative zero data -/

/-- X.例9.1: singleton semantic atom projection for the lawful firing witness. -/
def semanticProjection : SemanticAtomProjection where
  SemanticAtom := PUnit
  Component := PUnit
  project _ := PUnit.unit

/-- X.例9.1: singleton finite semantic repair cover. -/
def semanticCover : SemanticRepairCover semanticProjection where
  baseCover := {
    Chart := PUnit
    Transition := PUnit
    chartFinite := inferInstance
    transitionFinite := inferInstance
    holonomySupport := fun _ => True
  }
  CoverChart := PUnit
  chart _ := PUnit.unit
  chartFinite := inferInstance
  Overlap := fun _ _ => PUnit
  overlapFinite := fun _ _ => inferInstance
  TripleOverlap := fun _ _ _ => PUnit
  tripleFinite := fun _ _ _ => inferInstance
  tripleEdge01 := fun _ => PUnit.unit
  tripleEdge12 := fun _ => PUnit.unit
  tripleEdge02 := fun _ => PUnit.unit

/-- X.例9.1: zero additive Cech data for the lawful firing witness. -/
def semanticCechData : SemanticRepairCoverCechData semanticCover where
  C0 := PUnit
  C1 := PUnit
  C2 := PUnit
  c0Finite := inferInstance
  c1Finite := inferInstance
  zero1 := PUnit.unit
  zero2 := PUnit.unit
  delta0 _ := PUnit.unit
  delta1 _ := PUnit.unit
  residual := PUnit.unit
  zero1_cocycle := rfl
  delta1_delta0_eq_zero := fun _ => rfl
  residual_cocycle := rfl

/-- X.例9.1: additive law package for the zero Cech surface. -/
def semanticAdditiveData :
    SemanticRepairAdditiveCechH1Data semanticCechData where
  c0AddCommGroup := by
    change AddCommGroup PUnit
    infer_instance
  c1AddCommGroup := by
    change AddCommGroup PUnit
    infer_instance
  zero1_eq_zero := rfl
  delta0_zero := rfl
  delta0_add := fun _ _ => rfl
  delta0_neg := fun _ => rfl

/-- X.例9.1: boundary-relation data for the lawful zero instance. -/
def boundaryRelationData :
    SemanticRepairCoverH1BoundaryRelationAbelianData semanticProjection where
  cover := semanticCover
  cech := semanticCechData
  supportOf _ := fun _ => True
  component_covered_of_boundary := by
    intro _primitive _hboundary residual hresidual
    exact ⟨residual, trivial, rfl⟩
  component_faithful_of_boundary := by
    intro _primitive _hboundary _residual _candidate _hresidual _hcandidate _hprojection
    trivial

/-- X.例9.1: additive boundary-relation data used by theorem 7.5. -/
def boundaryAdditiveData :
    SemanticRepairCoverH1BoundaryRelationAdditiveData semanticProjection where
  boundaryRelation := boundaryRelationData
  additive := semanticAdditiveData

/-- X.例9.1: cover-relative singleton cover for the concrete Cech complex. -/
def coverRelativeCover :
    Cohomology.CoverRelativeCechCover FiniteModel.site where
  base := FiniteModel.siteBase
  Index := PUnit
  chart _ := FiniteModel.siteBase
  inclusion _ := 𝟙 FiniteModel.siteBase
  simplex _ := PUnit
  overlap _ _ := FiniteModel.siteBase
  face _ _ _ := PUnit.unit
  faceRestriction _ _ _ := 𝟙 FiniteModel.siteBase

/-- X.例9.1: singleton cover-relative Cech complex with zero differential. -/
def coverRelativeComplex :
    Cohomology.CoverRelativeCechComplex coverRelativeCover quotientObstructionSheaf where
  cochainAddCommGroup n := by
    change AddCommGroup (PUnit -> PUnit)
    infer_instance
  alternatingFaceCombination _ _ _ := PUnit.unit
  differential _ := by
    change (PUnit -> PUnit) →+ (PUnit -> PUnit)
    exact {
      toFun := fun _ _ => PUnit.unit
      map_zero' := by
        funext σ
        rfl
      map_add' := by
        intro x y
        funext σ
        cases x σ
        cases y σ
        rfl
    }
  differential_eq_alternatingFaceCombination := by
    intro _n c
    funext σ
    cases c σ
    rfl
  differential_comp := by
    intro _n c
    funext σ
    cases c σ
    rfl

/-- X.例9.1: additive equivalence between `PUnit` and singleton cochains. -/
def punitCochainAddEquiv (_n : Nat) :
    PUnit ≃+ (PUnit -> PUnit) where
  toFun _ _ := PUnit.unit
  invFun _ := PUnit.unit
  left_inv := by
    intro x
    cases x
    rfl
  right_inv := by
    intro f
    funext σ
    cases f σ
    rfl
  map_add' := by
    intro x y
    cases x
    cases y
    rfl

/-- X.例9.1: equivalence between `PUnit` and degree-two singleton cochains. -/
def punitCochainEquiv (_n : Nat) :
    PUnit ≃ (PUnit -> PUnit) where
  toFun _ _ := PUnit.unit
  invFun _ := PUnit.unit
  left_inv := by
    intro x
    cases x
    rfl
  right_inv := by
    intro f
    funext σ
    cases f σ
    rfl

/--
X.例9.1: concrete cochain comparison data.  Since both sides are singleton
zero surfaces, all differential compatibility obligations are definitional.
-/
def h1Comparison :
    SemanticRepairCoverRelativeH1Comparison
      boundaryAdditiveData.toAdditiveH1Surface coverRelativeComplex where
  c0Equiv := punitCochainAddEquiv 0
  c1Equiv := punitCochainAddEquiv 1
  c2Equiv := punitCochainEquiv 2
  c2Equiv_zero := rfl
  c2Equiv_symm_zero := rfl
  d0_to := by
    intro primitive
    cases primitive
    funext σ
    cases σ
    rfl
  d0_from := by
    intro primitive
    cases primitive PUnit.unit
    rfl
  d1_to := by
    intro cochain
    cases cochain
    funext σ
    cases σ
    rfl
  d1_from := by
    intro cochain
    cases cochain PUnit.unit
    rfl

/--
X.例9.1: concrete cochain realization data whose theorem-level H1 comparison
is generated by `SemanticRepairCoverRelativeCochainRealization.toH1Comparison`.
-/
def h1Realization :
    SemanticRepairCoverRelativeCochainRealization
      boundaryAdditiveData.toAdditiveH1Surface coverRelativeComplex where
  c0Equiv := punitCochainAddEquiv 0
  c1Equiv := punitCochainAddEquiv 1
  c2Equiv := punitCochainEquiv 2
  c2Equiv_zero := rfl
  c2Equiv_symm_zero := rfl
  d0_to := by
    intro primitive
    cases primitive
    funext σ
    cases σ
    rfl
  d0_from := by
    intro primitive
    cases primitive PUnit.unit
    rfl
  d1_to := by
    intro cochain
    cases cochain
    funext σ
    cases σ
    rfl
  d1_from := by
    intro cochain
    cases cochain PUnit.unit
    rfl

/-! ## Generated `F₂` quotient coefficient for example 9.1 -/

/--
X.例9.1 / #3102: generated quotient coefficient presheaf over `F₂`.

This is the non-singleton coefficient route for the lawful firing instance.
The legacy `quotientPresheaf` above remains the simplest singleton witness,
but the completion theorem below fires theorem 7.5 through this `ZMod 2`
coefficient.
-/
def generatedF2QuotientPresheaf : Site.AATPresheaf FiniteModel.site where
  obj _ := ZMod 2
  map _ x := x
  map_id _ := rfl
  map_comp _ _ := rfl

/-- X.例9.1 / #3102: every finite-site covering sieve is top. -/
theorem finiteSiteTopology_cover_eq_top {base : FiniteModel.site.category}
    {cover : Sieve base} (hcover : cover ∈ FiniteModel.site.topology base) :
    cover = ⊤ := by
  rw [FiniteModel.site_topology_eq_generated] at hcover
  change
    (Site.admissiblePrecoverage FiniteModel.siteCoverageRequirements
      FiniteModel.siteOverlap).Saturate base cover at hcover
  induction hcover with
  | of X S hS =>
      rcases hS with ⟨F, rfl⟩
      rw [← Sieve.id_mem_iff_eq_top]
      rcases F.admissible.atomSupportCoverage
          FiniteModel.FiniteAtom.componentA trivial with ⟨i, _hi⟩
      let hEq :
          X = Site.ContextCategoryObject.of
            FiniteModel.siteContextPreorder (F.patch i) := by
        cases X
        exact congrArg
          (Site.ContextCategoryObject.of FiniteModel.siteContextPreorder)
          (F.inclusion i).symm
      have hmem : F.presieve (𝟙 X) :=
        Presieve.ofArrows.mk'
          (Y := fun i => Site.ContextCategoryObject.of
            FiniteModel.siteContextPreorder (F.patch i))
          (f := fun i => homOfLE (F.inclusion i))
          i hEq
          (Subsingleton.elim (𝟙 X)
            (eqToHom hEq ≫ homOfLE (F.inclusion i)))
      exact Sieve.le_generate F.presieve X hmem
  | top _X =>
      rfl
  | pullback _X _S _hS _Y _f ih =>
      rw [ih, Sieve.pullback_top]
  | transitive X S R _hS hR ihS ihR =>
      rw [← Sieve.id_mem_iff_eq_top]
      have hSid : S (𝟙 X) := by
        rw [Sieve.id_mem_iff_eq_top, ihS]
      have hlocal : R = ⊤ := by
        simpa using ihR hSid
      rw [hlocal]
      trivial

/-- X.例9.1 / #3102: every presheaf on the singleton finite site is a sheaf. -/
theorem finiteSite_allPresheaves_isSheaf
    (F : Site.AATPresheaf FiniteModel.site) :
    Site.AATSheafCondition FiniteModel.site F := by
  intro _base cover hcover
  rw [Site.AATSheafConditionFor, finiteSiteTopology_cover_eq_top hcover]
  exact Presieve.isSheafFor_top F

/-- X.例9.1 / #3102: the generated `F₂` quotient coefficient is a true sheaf. -/
theorem generatedF2QuotientIsSheaf :
    Site.AATSheafCondition FiniteModel.site generatedF2QuotientPresheaf := by
  exact finiteSite_allPresheaves_isSheaf generatedF2QuotientPresheaf

/-- X.例9.1 / #3102: generated non-`PUnit` obstruction coefficient sheaf. -/
def generatedF2QuotientObstructionSheaf :
    Cohomology.ObstructionSheaf FiniteModel.site where
  carrier := {
    carrier := generatedF2QuotientPresheaf
    isSheaf := generatedF2QuotientIsSheaf
  }
  addCommGroup _ := by
    change AddCommGroup (ZMod 2)
    infer_instance
  map_zero := by
    intro _source _target _f
    rfl
  map_add := by
    intro _source _target _f _x _y
    rfl

/-- X.例9.1 / #3102: the generated quotient coefficient is genuinely nontrivial. -/
theorem generatedF2QuotientPresheaf_nontrivial :
    Nontrivial (generatedF2QuotientPresheaf.obj (op FiniteModel.siteBase)) := by
  change Nontrivial (ZMod 2)
  infer_instance

/-- X.例9.1 / #3102: selected zero section of the generated `F₂` quotient. -/
def generatedF2ZeroSection (Y : FiniteModel.site.category) :
    generatedF2QuotientPresheaf.obj (op Y) :=
  (0 : ZMod 2)

/-- X.例9.1 / #3102: zero Cech data over the generated `F₂` coefficient. -/
def generatedF2SemanticCechData :
    SemanticRepairCoverCechData semanticCover where
  C0 := ZMod 2
  C1 := ZMod 2
  C2 := ZMod 2
  c0Finite := inferInstance
  c1Finite := inferInstance
  zero1 := 0
  zero2 := 0
  delta0 _ := 0
  delta1 _ := 0
  residual := 0
  zero1_cocycle := rfl
  delta1_delta0_eq_zero := fun _ => rfl
  residual_cocycle := rfl

/-- X.例9.1 / #3102: additive law package over the generated `F₂` surface. -/
def generatedF2SemanticAdditiveData :
    SemanticRepairAdditiveCechH1Data generatedF2SemanticCechData where
  c0AddCommGroup := by
    change AddCommGroup (ZMod 2)
    infer_instance
  c1AddCommGroup := by
    change AddCommGroup (ZMod 2)
    infer_instance
  zero1_eq_zero := rfl
  delta0_zero := rfl
  delta0_add := fun _ _ => rfl
  delta0_neg := by
    intro x
    simp [generatedF2SemanticCechData]

/-- X.例9.1 / #3102: boundary-relation data over generated `F₂` coefficients. -/
def generatedF2BoundaryRelationData :
    SemanticRepairCoverH1BoundaryRelationAbelianData semanticProjection where
  cover := semanticCover
  cech := generatedF2SemanticCechData
  supportOf _ := fun _ => True
  component_covered_of_boundary := by
    intro _primitive _hboundary residual hresidual
    exact ⟨residual, trivial, rfl⟩
  component_faithful_of_boundary := by
    intro _primitive _hboundary _residual _candidate _hresidual _hcandidate _hprojection
    trivial

/-- X.例9.1 / #3102: additive boundary-relation data over generated `F₂`. -/
def generatedF2BoundaryAdditiveData :
    SemanticRepairCoverH1BoundaryRelationAdditiveData semanticProjection where
  boundaryRelation := generatedF2BoundaryRelationData
  additive := generatedF2SemanticAdditiveData

/-- X.例9.1 / #3102: generated `F₂` cover-relative singleton complex. -/
def generatedF2CoverRelativeComplex :
    Cohomology.CoverRelativeCechComplex
      coverRelativeCover generatedF2QuotientObstructionSheaf where
  cochainAddCommGroup n := by
    change AddCommGroup (PUnit -> ZMod 2)
    infer_instance
  alternatingFaceCombination _ _ _ := 0
  differential _ := by
    change (PUnit -> ZMod 2) →+ (PUnit -> ZMod 2)
    exact {
      toFun := fun _ _ => 0
      map_zero' := by
        funext σ
        rfl
      map_add' := by
        intro _x _y
        funext σ
        rfl
    }
  differential_eq_alternatingFaceCombination := by
    intro _n _c
    funext σ
    cases σ
    rfl
  differential_comp := by
    intro _n _c
    funext σ
    cases σ
    rfl

/-- X.例9.1 / #3102: additive equivalence between `F₂` and singleton cochains. -/
def zmod2SingletonCochainAddEquiv (_n : Nat) :
    ZMod 2 ≃+ (PUnit -> ZMod 2) where
  toFun x := fun _ => x
  invFun f := f PUnit.unit
  left_inv := by
    intro x
    rfl
  right_inv := by
    intro f
    funext σ
    cases σ
    rfl
  map_add' := by
    intro _x _y
    rfl

/-- X.例9.1 / #3102: equivalence between `F₂` and degree-two singleton cochains. -/
def zmod2SingletonCochainEquiv (_n : Nat) :
    ZMod 2 ≃ (PUnit -> ZMod 2) where
  toFun x := fun _ => x
  invFun f := f PUnit.unit
  left_inv := by
    intro x
    rfl
  right_inv := by
    intro f
    funext σ
    cases σ
    rfl

/--
X.例9.1 / #3102: generated `F₂` cochain realization.

The theorem-7.5 comparison is generated from this realization rather than
accepted as a package field.
-/
def generatedF2H1Realization :
    SemanticRepairCoverRelativeCochainRealization
      generatedF2BoundaryAdditiveData.toAdditiveH1Surface
      generatedF2CoverRelativeComplex where
  c0Equiv := by
    change ZMod 2 ≃+ (PUnit -> ZMod 2)
    exact zmod2SingletonCochainAddEquiv 0
  c1Equiv := by
    change ZMod 2 ≃+ (PUnit -> ZMod 2)
    exact zmod2SingletonCochainAddEquiv 1
  c2Equiv := by
    change ZMod 2 ≃ (PUnit -> ZMod 2)
    exact zmod2SingletonCochainEquiv 2
  c2Equiv_zero := by
    funext σ
    cases σ
    rfl
  c2Equiv_symm_zero := rfl
  d0_to := by
    intro _primitive
    funext σ
    cases σ
    rfl
  d0_from := by
    intro _primitive
    rfl
  d1_to := by
    intro _cochain
    funext σ
    cases σ
    rfl
  d1_from := by
    intro _cochain
    rfl

/-! ## Concrete law-equation firing data -/

/-- X.例9.1: lawful finite object with the selected NoCycle relation removed. -/
def lawfulConfiguration : AtomConfiguration FiniteModel.carrier where
  family := FiniteModel.allFamily
  relation _ _ := False
  identification _ _ := False

/-- X.例9.1: lawful local object used by the displayed law source. -/
def lawfulObject : ArchitectureObject FiniteModel.carrier :=
  FiniteModel.objectOfConfiguration lawfulConfiguration

/-- X.例9.1: the selected local object satisfies the required NoCycle law. -/
theorem lawfulObject_noCycleLaw :
    FiniteModel.noCycleLaw.holds lawfulObject := by
  intro hcycle
  exact hcycle.1

/-- X.例9.1: concrete law-equation witness-ideal core over `ZMod 4`. -/
def lawEquationCore :
    LawAlgebra.SemanticLawEquationWitnessIdealCore FiniteModel.site where
  Observable _ := ZMod 4
  observableCommRing _ := inferInstance
  restrict _ := RingHom.id (ZMod 4)
  restrict_id := by
    intro _W x
    rfl
  restrict_comp := by
    intro _W₀ _W₁ _W₂ _f _g x
    rfl
  violationWitness _ _ _ := (2 : ZMod 4)
  violationWitness_restrict := by
    intro _source _target _f _lawIndex _atom
    rfl
  supportAtom := FiniteModel.FiniteAtom.componentA
  supportLawIndex := PUnit.unit
  supportLawIndex_required := rfl

/-! ## Integer law-equation core required by Part X R9(b) -/

/--
X.例9.1 / #3102: production law-equation core with observable ring `ℤ` and
constant violation witness `2`.
-/
def integerLawEquationCore :
    LawAlgebra.SemanticLawEquationWitnessIdealCore FiniteModel.site where
  Observable _ := ℤ
  observableCommRing _ := inferInstance
  restrict _ := RingHom.id ℤ
  restrict_id := by
    intro _W x
    rfl
  restrict_comp := by
    intro _W₀ _W₁ _W₂ _f _g x
    rfl
  violationWitness _ _ _ := (2 : ℤ)
  violationWitness_restrict := by
    intro _source _target _f _lawIndex _atom
    rfl
  supportAtom := FiniteModel.FiniteAtom.componentA
  supportLawIndex := PUnit.unit
  supportLawIndex_required := rfl

/-- Generated quotient presheaf `ℤ / I_Ob` for the integer law core. -/
abbrev integerGeneratedLawQuotientPresheaf : Site.AATPresheaf FiniteModel.site :=
  integerLawEquationCore.obstructionQuotientPresheaf

/-- The integer generated quotient is a sheaf on the singleton finite site. -/
theorem integerGeneratedLawQuotientIsSheaf :
    Site.AATSheafCondition FiniteModel.site integerGeneratedLawQuotientPresheaf :=
  finiteSite_allPresheaves_isSheaf integerGeneratedLawQuotientPresheaf

/-- Every integer witness ideal is contained in `span {2}`. -/
theorem integerLaw_lawWitnessIdeal_le
    (W : FiniteModel.site.category)
    (lawIndex : FiniteModel.site.lawUniverse.Index) :
    integerLawEquationCore.lawWitnessIdeal W lawIndex ≤
      Ideal.span ({(2 : ℤ)} : Set ℤ) := by
  refine Ideal.span_le.mpr ?_
  rintro _x ⟨atom, rfl⟩
  exact Ideal.subset_span rfl

/-- The integer obstruction ideal is contained in `span {2}`. -/
theorem integerLaw_obstructionIdeal_le (W : FiniteModel.site.category) :
    integerLawEquationCore.obstructionIdeal W ≤
      Ideal.span ({(2 : ℤ)} : Set ℤ) := by
  change
    (integerLawEquationCore.selectedLawWitnessIdealFamily W).localObstructionIdeal ≤
      Ideal.span ({(2 : ℤ)} : Set ℤ)
  rw [LawAlgebra.ObstructionIdeal.SelectedLawWitnessIdealFamily.localObstructionIdeal_le_iff]
  intro lawIndex _hselected
  exact integerLaw_lawWitnessIdeal_le W lawIndex

/-- The integer defect `1` is not killed by the generated obstruction ideal. -/
theorem integerLaw_one_notMem_obstructionIdeal (W : FiniteModel.site.category) :
    (1 : ℤ) ∉ integerLawEquationCore.obstructionIdeal W := by
  intro hmem
  have hspan := integerLaw_obstructionIdeal_le W hmem
  rw [Ideal.mem_span_singleton] at hspan
  have hdiv : (2 : ℤ) ∣ (1 : ℤ) := hspan
  obtain ⟨c, hc⟩ := hdiv
  omega

/-- The quotient class of `1` is nonzero for the integer generated coefficient. -/
theorem integerGeneratedLawQuotient_one_ne_zero (W : FiniteModel.site.category) :
    Ideal.Quotient.mk (integerLawEquationCore.obstructionIdeal W) (1 : ℤ) ≠ 0 := by
  intro hzero
  exact integerLaw_one_notMem_obstructionIdeal W
    (Ideal.Quotient.eq_zero_iff_mem.mp hzero)

/-- The integer generated quotient coefficient is nontrivial at every context. -/
theorem integerGeneratedLawQuotient_nontrivial (W : FiniteModel.site.category) :
    ∃ x : integerLawEquationCore.ObstructionQuotient W, x ≠ 0 :=
  ⟨Ideal.Quotient.mk (integerLawEquationCore.obstructionIdeal W) 1,
    integerGeneratedLawQuotient_one_ne_zero W⟩

/-- Every selected integer violation witness has zero quotient class. -/
theorem integerLaw_violationWitness_class_eq_zero
    (W : FiniteModel.site.category)
    (lawIndex : FiniteModel.site.lawUniverse.Index)
    (atom : FiniteModel.carrier.Atom) :
    Ideal.Quotient.mk (integerLawEquationCore.obstructionIdeal W)
        (integerLawEquationCore.violationWitness W lawIndex atom) = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.mpr
    (integerLawEquationCore.lawWitnessIdeal_le_obstructionIdeal W
      (FiniteModel.lawUniverse_required lawIndex)
      (Ideal.subset_span ⟨atom, rfl⟩))

/-- X.例9.1: displayed defect source whose defect lies in the selected witness ideal. -/
def defectSource :
    LawAlgebra.LawEquationDefectSource lawEquationCore where
  Chart := PUnit
  chart _ := FiniteModel.siteBase
  LocalInput _ := PUnit
  input _ := PUnit.unit
  lawSupport _ _ := [PUnit.unit]
  lawSupport_nonempty := by
    intro i
    exact ⟨PUnit.unit, by simp⟩
  lawSupport_required := by
    intro i lawIndex hmem
    cases lawIndex
    rfl
  objectOfLocalInput _ _ := lawfulObject
  defect _ _ := (2 : ZMod 4)
  holds_defect_mem := by
    intro i lawIndex hmem hrequired _hholds
    exact Ideal.subset_span
      ⟨FiniteModel.FiniteAtom.componentA, rfl⟩

/-- X.例9.1: displayed required laws hold on the selected lawful local input. -/
theorem displayedRequiredLawsHoldOn :
    defectSource.DisplayedRequiredLawsHoldOn := by
  intro i lawIndex hmem hrequired
  cases lawIndex
  exact lawfulObject_noCycleLaw

/-!
The following source is a negative witness for the displayed realization
predicate.  Its displayed defect is the nonzero quotient class of `1`, while
the generated base source still starts from the zero section.
-/

/-- A concrete configuration that violates the selected no-cycle law. -/
def nonlawfulConfiguration : AtomConfiguration FiniteModel.carrier where
  family := FiniteModel.allFamily
  relation _ _ := True
  identification _ _ := False

/-- Architecture object induced by `nonlawfulConfiguration`. -/
def nonlawfulObject : ArchitectureObject FiniteModel.carrier :=
  FiniteModel.objectOfConfiguration nonlawfulConfiguration

theorem nonlawfulObject_not_noCycleLaw :
    ¬ FiniteModel.noCycleLaw.holds nonlawfulObject := by
  intro hholds
  apply hholds
  exact ⟨trivial, trivial, trivial⟩

/-- Defect source whose displayed law interpretation is nonzero. -/
def nonlawfulDefectSource :
    LawAlgebra.LawEquationDefectSource lawEquationCore where
  Chart := PUnit
  chart _ := FiniteModel.siteBase
  LocalInput _ := PUnit
  input _ := PUnit.unit
  lawSupport _ _ := [PUnit.unit]
  lawSupport_nonempty := by
    intro _i
    exact ⟨PUnit.unit, by simp⟩
  lawSupport_required := by
    intro _i lawIndex _hmem
    cases lawIndex
    rfl
  objectOfLocalInput _ _ := nonlawfulObject
  defect _ _ := (1 : ZMod 4)
  holds_defect_mem := by
    intro _i lawIndex _hmem _hrequired hholds
    cases lawIndex
    exact False.elim (nonlawfulObject_not_noCycleLaw hholds)

/-! ## Native generated quotient coefficient for example 9.1 -/

/--
X.例9.1 / #3102: the coefficient presheaf generated by `lawEquationCore`
itself, namely the obstruction quotient `O/I_Ob`.
-/
abbrev generatedLawQuotientPresheaf : Site.AATPresheaf FiniteModel.site :=
  lawEquationCore.obstructionQuotientPresheaf

/--
X.例9.1 / #3102: the law-equation-generated quotient coefficient is a true
sheaf on the selected finite-site topology.
-/
theorem generatedLawQuotientIsSheaf :
    Site.AATSheafCondition FiniteModel.site generatedLawQuotientPresheaf := by
  intro _base cover hcover
  rw [Site.AATSheafConditionFor, finiteSiteTopology_cover_eq_top hcover]
  exact Presieve.isSheafFor_top generatedLawQuotientPresheaf

/--
X.例9.1 / #3102: obstruction sheaf whose carrier is exactly the
law-equation-generated quotient presheaf.
-/
def generatedLawQuotientObstructionSheaf :
    Cohomology.ObstructionSheaf FiniteModel.site :=
  Cohomology.ObstructionSheaf.ofAddCommGrpValued
    lawEquationCore.obstructionQuotientCoefficient generatedLawQuotientIsSheaf

/-- X.例9.1 / #3102: selected native quotient value at the singleton base. -/
abbrev GeneratedLawQuotient :=
  lawEquationCore.ObstructionQuotient FiniteModel.siteBase

instance generatedLawQuotientFintype :
    Fintype GeneratedLawQuotient := by
  dsimp [GeneratedLawQuotient,
    LawAlgebra.SemanticLawEquationWitnessIdealCore.ObstructionQuotient,
    lawEquationCore]
  infer_instance

/-- X.例9.1 / #3102: the native generated obstruction ideal is `span {2}`. -/
private theorem generatedLaw_obstructionIdeal_eq_span_two :
    lawEquationCore.obstructionIdeal FiniteModel.siteBase =
      Ideal.span ({(2 : ZMod 4)} : Set (ZMod 4)) := by
  have hwitness :
      lawEquationCore.lawWitnessIdeal FiniteModel.siteBase PUnit.unit =
        Ideal.span ({(2 : ZMod 4)} : Set (ZMod 4)) := by
    dsimp [LawAlgebra.SemanticLawEquationWitnessIdealCore.lawWitnessIdeal,
      lawEquationCore]
    congr
    ext x
    constructor
    · rintro ⟨_atom, rfl⟩
      simp
    · intro hx
      exact ⟨FiniteModel.FiniteAtom.componentA, by simpa using hx.symm⟩
  apply le_antisymm
  · change
      (lawEquationCore.selectedLawWitnessIdealFamily FiniteModel.siteBase).localObstructionIdeal ≤
        Ideal.span ({(2 : ZMod 4)} : Set (ZMod 4))
    rw [LawAlgebra.ObstructionIdeal.SelectedLawWitnessIdealFamily.localObstructionIdeal_le_iff]
    intro lawIndex _hselected
    cases lawIndex
    change lawEquationCore.lawWitnessIdeal FiniteModel.siteBase PUnit.unit ≤
      Ideal.span ({(2 : ZMod 4)} : Set (ZMod 4))
    rw [hwitness]
  · rw [← hwitness]
    exact lawEquationCore.lawWitnessIdeal_le_obstructionIdeal FiniteModel.siteBase rfl

/-- X.例9.1 / #3102: `1` is not killed by the generated ideal `span {2}`. -/
private theorem generatedLaw_one_notMem_span_two :
    (1 : ZMod 4) ∉ Ideal.span ({(2 : ZMod 4)} : Set (ZMod 4)) := by
  intro h
  rw [Ideal.mem_span_singleton'] at h
  rcases h with ⟨a, ha⟩
  exact (by fin_cases a <;> decide : ¬ a * 2 = (1 : ZMod 4)) ha

/-- X.例9.1 / #3102: the native generated quotient has a concrete nonzero class. -/
theorem generatedLawQuotient_one_ne_zero :
    (Ideal.Quotient.mk (lawEquationCore.obstructionIdeal FiniteModel.siteBase)
      (1 : ZMod 4)) ≠ 0 := by
  intro hzero
  rw [Ideal.Quotient.eq_zero_iff_mem] at hzero
  rw [generatedLaw_obstructionIdeal_eq_span_two] at hzero
  exact generatedLaw_one_notMem_span_two hzero

theorem nonlawfulDefectSource_interpret_ne_zero :
    nonlawfulDefectSource.interpret PUnit.unit ≠ 0 := by
  apply
    nonlawfulDefectSource.interpret_ne_zero_of_defect_notMem_obstructionIdeal
  dsimp [nonlawfulDefectSource]
  rw [generatedLaw_obstructionIdeal_eq_span_two]
  exact generatedLaw_one_notMem_span_two

/-- X.例9.1 / #3102: the native law-equation-generated quotient is nontrivial. -/
instance generatedLawQuotientNontrivial :
    Nontrivial GeneratedLawQuotient := by
  refine
    ⟨⟨0,
      Ideal.Quotient.mk (lawEquationCore.obstructionIdeal FiniteModel.siteBase)
        (1 : ZMod 4), ?_⟩⟩
  intro h
  exact generatedLawQuotient_one_ne_zero h.symm

/-- X.例9.1 / #3102: selected nonzero class in the native generated quotient. -/
def generatedLawQuotientOne : GeneratedLawQuotient :=
  Ideal.Quotient.mk (lawEquationCore.obstructionIdeal FiniteModel.siteBase)
    (1 : ZMod 4)

/-- X.例9.1 / #3102: the selected native quotient class is nonzero. -/
theorem generatedLawQuotientOne_ne_zero :
    generatedLawQuotientOne ≠ 0 :=
  generatedLawQuotient_one_ne_zero

/-- X.例9.1 / #3102: the selected quotient class has order two. -/
theorem generatedLawQuotientOne_add_self :
    generatedLawQuotientOne + generatedLawQuotientOne = 0 := by
  dsimp [generatedLawQuotientOne]
  rw [← map_add]
  change
    Ideal.Quotient.mk (lawEquationCore.obstructionIdeal FiniteModel.siteBase)
      (2 : ZMod 4) = 0
  rw [Ideal.Quotient.eq_zero_iff_mem]
  rw [generatedLaw_obstructionIdeal_eq_span_two]
  exact Ideal.subset_span rfl

/-- X.例9.1 / #3102: zero section of the native generated quotient. -/
def generatedLawZeroSection (Y : FiniteModel.site.category) :
    generatedLawQuotientPresheaf.obj (op Y) :=
  by
    change lawEquationCore.ObstructionQuotient Y
    exact 0

/-- X.例9.1 / #3102: Cech data over the native generated quotient coefficient. -/
def generatedLawSemanticCechData :
    SemanticRepairCoverCechData semanticCover where
  C0 := GeneratedLawQuotient
  C1 := GeneratedLawQuotient
  C2 := GeneratedLawQuotient
  c0Finite := generatedLawQuotientFintype
  c1Finite := generatedLawQuotientFintype
  zero1 := 0
  zero2 := 0
  delta0 _ := 0
  delta1 _ := 0
  residual := 0
  zero1_cocycle := rfl
  delta1_delta0_eq_zero := fun _ => rfl
  residual_cocycle := rfl

/-- X.例9.1 / #3102: additive law package over the native quotient surface. -/
def generatedLawSemanticAdditiveData :
    SemanticRepairAdditiveCechH1Data generatedLawSemanticCechData where
  c0AddCommGroup := by
    change AddCommGroup GeneratedLawQuotient
    infer_instance
  c1AddCommGroup := by
    change AddCommGroup GeneratedLawQuotient
    infer_instance
  zero1_eq_zero := rfl
  delta0_zero := rfl
  delta0_add := fun _ _ => rfl
  delta0_neg := by
    intro x
    change (0 : GeneratedLawQuotient) = -0
    simp

/-- X.例9.1 / #3102: boundary-relation data over native generated coefficients. -/
def generatedLawBoundaryRelationData :
    SemanticRepairCoverH1BoundaryRelationAbelianData semanticProjection where
  cover := semanticCover
  cech := generatedLawSemanticCechData
  supportOf _ := fun _ => True
  component_covered_of_boundary := by
    intro _primitive _hboundary residual hresidual
    exact ⟨residual, trivial, rfl⟩
  component_faithful_of_boundary := by
    intro _primitive _hboundary _residual _candidate _hresidual _hcandidate _hprojection
    trivial

/-- X.例9.1 / #3102: additive boundary-relation data over native coefficients. -/
def generatedLawBoundaryAdditiveData :
    SemanticRepairCoverH1BoundaryRelationAdditiveData semanticProjection where
  boundaryRelation := generatedLawBoundaryRelationData
  additive := generatedLawSemanticAdditiveData

/-- X.例9.1 / #3102: native generated cover-relative singleton complex. -/
def generatedLawCoverRelativeComplex :
    Cohomology.CoverRelativeCechComplex
      coverRelativeCover generatedLawQuotientObstructionSheaf where
  cochainAddCommGroup n := by
    change AddCommGroup (PUnit -> GeneratedLawQuotient)
    infer_instance
  alternatingFaceCombination _ _ _ := 0
  differential _ := by
    change (PUnit -> GeneratedLawQuotient) →+ (PUnit -> GeneratedLawQuotient)
    exact {
      toFun := fun _ _ => 0
      map_zero' := by
        funext σ
        rfl
      map_add' := by
        intro _x _y
        funext σ
        rfl
    }
  differential_eq_alternatingFaceCombination := by
    intro _n _c
    funext σ
    cases σ
    rfl
  differential_comp := by
    intro _n _c
    funext σ
    cases σ
    rfl

/-- X.例9.1 / #3102: additive equivalence with singleton cochains. -/
def singletonCochainAddEquiv (α : Type*) [AddCommGroup α] (_n : Nat) :
    α ≃+ (PUnit -> α) where
  toFun x := fun _ => x
  invFun f := f PUnit.unit
  left_inv := by
    intro x
    rfl
  right_inv := by
    intro f
    funext σ
    cases σ
    rfl
  map_add' := by
    intro _x _y
    rfl

/-- X.例9.1 / #3102: equivalence with degree-two singleton cochains. -/
def singletonCochainEquiv (α : Type*) (_n : Nat) :
    α ≃ (PUnit -> α) where
  toFun x := fun _ => x
  invFun f := f PUnit.unit
  left_inv := by
    intro x
    rfl
  right_inv := by
    intro f
    funext σ
    cases σ
    rfl

/--
X.例9.1 / #3102: cochain realization over the native generated quotient.

The theorem-7.5 comparison is obtained from this realization, not supplied as
an independent premise.
-/
def generatedLawH1Realization :
    SemanticRepairCoverRelativeCochainRealization
      generatedLawBoundaryAdditiveData.toAdditiveH1Surface
      generatedLawCoverRelativeComplex where
  c0Equiv := by
    change GeneratedLawQuotient ≃+ (PUnit -> GeneratedLawQuotient)
    exact singletonCochainAddEquiv GeneratedLawQuotient 0
  c1Equiv := by
    change GeneratedLawQuotient ≃+ (PUnit -> GeneratedLawQuotient)
    exact singletonCochainAddEquiv GeneratedLawQuotient 1
  c2Equiv := by
    change GeneratedLawQuotient ≃ (PUnit -> GeneratedLawQuotient)
    exact singletonCochainEquiv GeneratedLawQuotient 2
  c2Equiv_zero := by
    funext σ
    cases σ
    rfl
  c2Equiv_symm_zero := rfl
  d0_to := by
    intro _primitive
    funext σ
    cases σ
    rfl
  d0_from := by
    intro _primitive
    rfl
  d1_to := by
    intro _cochain
    funext σ
    cases σ
    rfl
  d1_from := by
    intro _cochain
    rfl

/-! ## End-to-end firing -/

/-- X.例9.1: top-cover gluing data for the singleton quotient presheaf. -/
def gluingData :
    Site.AATGluingData FiniteModel.site quotientPresheaf
      (⊤ : Sieve FiniteModel.siteBase) where
  localSections := fun _Y _f _hf => PUnit.unit
  overlapAgreement := by
    intro _Y _Z _W _f _g _hf _hg _w h₁ _hcomp
    rfl

/-- X.例9.1: true-sheaf certificate with `quotientIsSheaf` discharged as a theorem. -/
def trueSheafCertificate :
    boundaryAdditiveData.TrueSheafConditionCertificate
      FiniteModel.site quotientPresheaf (⊤ : Sieve FiniteModel.siteBase) where
  cover_mem := FiniteModel.site.top_mem FiniteModel.siteBase
  sheafCondition := quotientIsSheaf

/-- X.例9.1 / #3102: top-cover gluing data for the generated `F₂` quotient. -/
def generatedF2GluingData :
    Site.AATGluingData FiniteModel.site generatedF2QuotientPresheaf
      (⊤ : Sieve FiniteModel.siteBase) where
  localSections := fun Y _f _hf => generatedF2ZeroSection Y
  overlapAgreement := by
    intro _Y _Z _W _f _g _hf _hg _w _h₁ _hcomp
    rfl

/--
X.例9.1 / #3102: true-sheaf certificate for the generated `F₂`
quotient coefficient.
-/
def generatedF2TrueSheafCertificate :
    generatedF2BoundaryAdditiveData.TrueSheafConditionCertificate
      FiniteModel.site generatedF2QuotientPresheaf
      (⊤ : Sieve FiniteModel.siteBase) where
  cover_mem := FiniteModel.site.top_mem FiniteModel.siteBase
  sheafCondition := generatedF2QuotientIsSheaf

/-- X.例9.1 / #3102: gluing data over the native generated quotient. -/
def generatedLawGluingData :
    Site.AATGluingData FiniteModel.site generatedLawQuotientPresheaf
      (⊤ : Sieve FiniteModel.siteBase) where
  localSections := fun Y _f _hf => generatedLawZeroSection Y
  overlapAgreement := by
    intro _Y _Z _W _f _g _hf _hg _w _h₁ _hcomp
    rfl

/--
X.例9.1 / #3102: true-sheaf certificate for the native
law-equation-generated quotient coefficient.
-/
def generatedLawTrueSheafCertificate :
    generatedLawBoundaryAdditiveData.TrueSheafConditionCertificate
      FiniteModel.site generatedLawQuotientPresheaf
      (⊤ : Sieve FiniteModel.siteBase) where
  cover_mem := FiniteModel.site.top_mem FiniteModel.siteBase
  sheafCondition := generatedLawQuotientIsSheaf

/--
X.例9.1 / #3102: native generated theorem-7.5 input surface.

Here the obstruction sheaf carrier is definitionally
`lawEquationCore.obstructionQuotientPresheaf`.
-/
def generatedLawNativeEndToEndInputs :
    SemanticRepairNativeGeneratedEndToEndInputs
      generatedLawBoundaryAdditiveData defectSource
      (⊤ : Sieve FiniteModel.siteBase) generatedLawTrueSheafCertificate
      generatedLawCoverRelativeComplex where
  realization := generatedLawH1Realization

/--
X.例9.1: lawful firing of theorem 7.5 on the concrete finite instance.

The packet is generated from the concrete law-equation source, the theorem-level
quotient sheaf certificate above, and the singleton H1 comparison data.
-/
theorem lawfulFiring_endToEndPacket :
    Nonempty
      (SemanticRepairGeneratedEndToEndSAGAPacket
        boundaryAdditiveData defectSource FiniteModel.site quotientPresheaf
        (⊤ : Sieve FiniteModel.siteBase) gluingData h1Comparison) :=
  lawEquation_constructs_groundedComparisonPacket
    boundaryAdditiveData defectSource displayedRequiredLawsHoldOn
    FiniteModel.site quotientPresheaf (⊤ : Sieve FiniteModel.siteBase)
    trueSheafCertificate gluingData h1Comparison

/--
X.例9.1: lawful firing through the generated-comparison theorem 7.5 route.

The returned pair contains the comparison generated from `h1Realization` and
the corresponding end-to-end SAGA packet.
-/
theorem lawfulFiring_endToEndPacket_fromRealization :
    Nonempty
      (Sigma fun comparison :
        SemanticRepairCoverRelativeH1Comparison
          boundaryAdditiveData.toAdditiveH1Surface coverRelativeComplex =>
          SemanticRepairGeneratedEndToEndSAGAPacket
            boundaryAdditiveData defectSource FiniteModel.site quotientPresheaf
            (⊤ : Sieve FiniteModel.siteBase) gluingData comparison) :=
  lawEquation_constructs_groundedComparisonPacket_fromRealization
    boundaryAdditiveData defectSource displayedRequiredLawsHoldOn
    FiniteModel.site quotientPresheaf (⊤ : Sieve FiniteModel.siteBase)
    trueSheafCertificate gluingData h1Realization

/--
X.例9.1 / #3102: theorem 7.5 fires over the native law-equation-generated
obstruction quotient coefficient.

This is audit-facing compatibility evidence: the coefficient presheaf is
`lawEquationCore.obstructionQuotientPresheaf`, the sheaf condition is proved by
`generatedLawQuotientIsSheaf`, and the comparison is generated from the selected
cochain realization stored in `generatedLawNativeEndToEndInputs`.
-/
theorem lawfulFiring_generatedLawQuotient_endToEndPacket_fromNativeGeneratedInputs :
    Nonempty
      (Sigma fun comparison :
        SemanticRepairCoverRelativeH1Comparison
          generatedLawBoundaryAdditiveData.toAdditiveH1Surface
          generatedLawCoverRelativeComplex =>
          SemanticRepairGeneratedEndToEndSAGAPacket
            generatedLawBoundaryAdditiveData defectSource FiniteModel.site
            generatedLawQuotientPresheaf
            (⊤ : Sieve FiniteModel.siteBase) generatedLawGluingData
            comparison) :=
  lawEquation_constructs_groundedComparisonPacket_fromNativeGeneratedInputs
    generatedLawBoundaryAdditiveData defectSource displayedRequiredLawsHoldOn
    (⊤ : Sieve FiniteModel.siteBase)
    generatedLawTrueSheafCertificate generatedLawGluingData
    generatedLawNativeEndToEndInputs

/--
X.例9.1: theorem 8.1 fires on the same lawful source, producing pointwise zero
and the selected degree-zero Cech-zero reading.
-/
theorem lawfulFiring_generatedSourceC0Zero :
    Nonempty (GeneratedSourceC0ZeroPackage defectSource) :=
  displayedRequiredLawsHoldOn_constructs_generatedSourceC0_zeroPackage
    defectSource displayedRequiredLawsHoldOn

/-! ## Circle-nerve nonzero transfer witness -/

/--
X.例9.2: degenerate witness-site coverage requirements used by the selected
circle nerve.

The selected nerve below is supplied simplicial data, not generated from chart
intersections.  These requirements deliberately have no admissible cover, so
the generated topology is the top-only witness topology used for the concrete
`F₂` coefficient sheaf.
-/
def circleCoverageRequirements :
    Site.CoverageRequirements FiniteModel.object
      FiniteModel.lawUniverse FiniteModel.signature where
  requiredSupport := fun _ => True
  requiredWitness := fun _ => False
  requiredAxis := fun _ => False
  supportVisibleOn := fun _ _ => False
  witnessVisibleOn := fun _ _ => False
  axisReadableOn := fun _ _ => False
  boundaryVisibleOn := fun _ _ => False

/-- X.例9.2: generated-core geometry for the selected circle witness site. -/
noncomputable def circleSelectedGeometryReading :
    Site.SelectedGeometryReading FiniteModel.corePackage where
  contextPreorder := FiniteModel.siteContextPreorder
  requirements := circleCoverageRequirements
  overlap := FiniteModel.siteOverlap

/-- X.例9.2: selected witness site for the circle-nerve nonzero class. -/
noncomputable def circleSite : Site.AATSite FiniteModel.corePackage.object :=
  circleSelectedGeometryReading.toAATSite

/-- X.例9.2: the circle witness topology is generated from its selected coverage. -/
theorem circleSite_topology_eq_generated :
    circleSite.topology =
      Site.AATGrothendieckTopology circleCoverageRequirements
        FiniteModel.siteOverlap :=
  Site.SelectedGeometryReading.topology_eq_generated
    circleSelectedGeometryReading

/-- X.例9.2: base object for the selected circle witness site. -/
def circleSiteBase : circleSite.category :=
  Site.ContextCategoryObject.of FiniteModel.siteContextPreorder
    FiniteModel.siteContext

/-- X.例9.2: no admissible cover exists for the selected witness topology. -/
theorem circleCoverageFamily_impossible {base : circleSite.category}
    (F : Site.AATCoverageFamily circleCoverageRequirements
      FiniteModel.siteOverlap base) :
    False := by
  rcases F.admissible.atomSupportCoverage
      FiniteModel.FiniteAtom.componentA trivial with ⟨i, hi⟩
  exact hi

/-- X.例9.2: every covering sieve in the selected witness topology is top. -/
theorem circleSiteTopology_cover_eq_top {base : circleSite.category}
    {cover : Sieve base} (hcover : cover ∈ circleSite.topology base) :
    cover = ⊤ := by
  rw [circleSite_topology_eq_generated] at hcover
  change
    (Site.admissiblePrecoverage circleCoverageRequirements
      FiniteModel.siteOverlap).Saturate base cover at hcover
  induction hcover with
  | of _X _S hS =>
      rcases hS with ⟨F, rfl⟩
      exact False.elim (circleCoverageFamily_impossible F)
  | top _X =>
      rfl
  | pullback _X _S _hS _Y _f ih =>
      rw [ih, Sieve.pullback_top]
  | transitive X S R _hS hR ihS ihR =>
      rw [← Sieve.id_mem_iff_eq_top]
      have hSid : S (𝟙 X) := by
        rw [Sieve.id_mem_iff_eq_top, ihS]
      have hlocal : R = ⊤ := by
        simpa using ihR hSid
      rw [hlocal]
      trivial

/-- X.例9.2: constant `F₂` coefficient presheaf on the circle witness site. -/
def circleF2Presheaf : Site.AATPresheaf circleSite where
  obj _ := ZMod 2
  map _ x := x
  map_id _ := rfl
  map_comp _ _ := rfl

/-- X.例9.2: the constant `F₂` presheaf is a sheaf on the witness topology. -/
theorem circleF2IsSheaf :
    Site.AATSheafCondition circleSite circleF2Presheaf := by
  intro _base cover hcover
  rw [Site.AATSheafConditionFor, circleSiteTopology_cover_eq_top hcover]
  exact Presieve.isSheafFor_top circleF2Presheaf

/-- X.例9.2: obstruction coefficient sheaf `Q ≅ F₂` for the circle witness. -/
def circleObstructionSheaf :
    Cohomology.ObstructionSheaf circleSite where
  carrier := {
    carrier := circleF2Presheaf
    isSheaf := circleF2IsSheaf
  }
  addCommGroup _ := by
    change AddCommGroup (ZMod 2)
    infer_instance
  map_zero := by
    intro _source _target _f
    rfl
  map_add := by
    intro _source _target _f _x _y
    rfl

/-- X.例9.2: supplied circle-nerve cover data. -/
def circleSimplex : Nat -> Type
  | 0 => Fin 3
  | 1 => Fin 3
  | _ + 2 => Unit

/-- X.例9.2: cyclic successor on the three selected circle vertices. -/
def circleNext (vertex : Fin 3) : Fin 3 :=
  ⟨(vertex.val + 1) % 3, Nat.mod_lt _ (by decide : 0 < 3)⟩

/-- X.例9.2: selected face map for the three-edge circle nerve. -/
def circleFace : ∀ n : Nat, Fin (n + 2) -> circleSimplex (n + 1) ->
    circleSimplex n
  | 0, i, edge => if i.val = 0 then circleNext edge else edge
  | 1, _i, _twoSimplex => (0 : Fin 3)
  | _ + 2, _i, _higherSimplex => ()

/-- X.例9.2: selected circle C0 cochains. -/
abbrev circleC0 : Type := Fin 3 -> ZMod 2

/-- X.例9.2: selected circle C1 cochains. -/
abbrev circleC1 : Type := Fin 3 -> ZMod 2

/-- X.例9.2: selected circle C2 cochains. -/
abbrev circleC2 : Type := Unit -> ZMod 2

/-- X.例9.2: selected circle Cech coboundary `d0`. -/
def circleD0 (cochain : circleC0) : circleC1 :=
  fun edge => cochain (circleNext edge) - cochain edge

/-- X.例9.2: selected residual one-cochain on the circle. -/
def circleResidual : circleC1 :=
  fun _ => (1 : ZMod 2)

/-- X.例9.2: selected zero one-cochain on the circle. -/
def circleZero1 : circleC1 :=
  fun _ => (0 : ZMod 2)

/-- X.例9.2: selected zero two-cochain on the circle. -/
def circleZero2 : circleC2 :=
  fun _ : Unit => (0 : ZMod 2)

/-- X.例9.2: the residual `1` on the three-edge circle is not a coboundary. -/
theorem circleResidual_not_coboundary :
    ¬ ∃ primitive : circleC0, circleResidual - circleZero1 = circleD0 primitive := by
  decide

/-- X.例9.2: supplied circle-nerve cover data. -/
def circleCoverRelativeCover :
    Cohomology.CoverRelativeCechCover circleSite where
  base := circleSiteBase
  Index := Fin 3
  chart _ := circleSiteBase
  inclusion _ := 𝟙 circleSiteBase
  simplex := circleSimplex
  overlap _ _ := circleSiteBase
  face := circleFace
  faceRestriction _ _ _ := 𝟙 circleSiteBase

/-- X.例9.2: selected three-edge circle complex over `F₂`. -/
def circleCoverRelativeComplex :
    Cohomology.CoverRelativeCechComplex
      circleCoverRelativeCover circleObstructionSheaf where
  cochainAddCommGroup n := by
    change AddCommGroup (circleSimplex n -> ZMod 2)
    infer_instance
  alternatingFaceCombination
    | 0, terms => fun edge =>
        (terms edge 0 : ZMod 2) - (terms edge 1 : ZMod 2)
    | _ + 1, _terms => fun _ => (0 : ZMod 2)
  differential
    | 0 => by
        change circleC0 →+ circleC1
        exact {
          toFun := circleD0
          map_zero' := by
            funext edge
            simp [circleD0]
          map_add' := by
            intro left right
            funext edge
            simp [circleD0]
            abel
        }
    | _ + 1 => by
        change (circleSimplex (_ + 1) -> ZMod 2) →+
          (circleSimplex (_ + 2) -> ZMod 2)
        exact {
          toFun := fun _ => fun _ => (0 : ZMod 2)
          map_zero' := by
            funext σ
            rfl
          map_add' := by
            intro _x _y
            funext σ
            rfl
        }
  differential_eq_alternatingFaceCombination := by
    intro n c
    cases n with
    | zero =>
        funext edge
        letI := circleObstructionSheaf.addCommGroup circleSiteBase
        dsimp [circleD0, circleFace, circleCoverRelativeCover,
          circleObstructionSheaf, circleF2Presheaf, Site.AATSheaf.toPresheaf]
        change circleD0 (c : circleC0) edge = _
        rfl
    | succ n =>
        funext σ
        change (0 : ZMod 2) = 0
        rfl
  differential_comp := by
    intro n _c
    cases n with
    | zero =>
        funext σ
        change (0 : ZMod 2) = 0
        rfl
    | succ n =>
        funext σ
        change (0 : ZMod 2) = 0
        rfl

/-- X.例9.2: semantic additive `H¹` surface with residual `1 ∈ F₂`. -/
def circleAdditiveH1Surface :
    SemanticRepairAdditiveH1Surface where
  C0 := circleC0
  C1 := circleC1
  C2 := circleC2
  zero1 := circleZero1
  zero2 := circleZero2
  delta0 := circleD0
  delta1 _ := circleZero2
  residual := circleResidual
  c0AddCommGroup := inferInstance
  c1AddCommGroup := inferInstance
  zero1_eq_zero := by
    funext edge
    rfl
  delta0_zero := by
    funext edge
    simp [circleD0]
  delta0_add := by
    intro left right
    funext edge
    simp [circleD0]
    abel
  delta0_neg := by
    intro primitive
    funext edge
    change
      (-primitive (circleNext edge) - -primitive edge) =
        -(primitive (circleNext edge) - primitive edge)
    abel
  zero1_cocycle := by
    funext σ
    rfl
  delta1_delta0_eq_zero := by
    intro _primitive
    funext σ
    rfl
  residual_cocycle := by
    funext σ
    rfl

/-- X.例9.2: the semantic residual circle cochain is not a semantic coboundary. -/
theorem circleSemantic_residual_not_coboundary :
    ¬ circleAdditiveH1Surface.Cohomologous
      ⟨circleResidual, circleAdditiveH1Surface.residual_cocycle⟩
      ⟨circleZero1, circleAdditiveH1Surface.zero1_cocycle⟩ :=
  circleResidual_not_coboundary

/-- X.例9.2: semantic additive residual class is nonzero in `H¹`. -/
theorem circleSemanticH1_nonzero :
    ¬ circleAdditiveH1Surface.H1Zero := by
  intro hzero
  exact circleSemantic_residual_not_coboundary (Quotient.exact hzero)

/-- X.例9.2: selected cover-relative residual cocycle. -/
def circleCoverRelativeResidualCocycle :
    circleCoverRelativeComplex.CechCocycle 1 where
  val := circleResidual
  property := by
    funext σ
    change (0 : ZMod 2) = 0
    rfl

/-- X.例9.2: selected cover-relative zero cocycle. -/
def circleCoverRelativeZeroCocycle :
    circleCoverRelativeComplex.CechCocycle 1 where
  val := circleZero1
  property := by
    funext σ
    change (0 : ZMod 2) = 0
    rfl

/-- X.例9.2: selected cover-relative residual class. -/
def circleCoverRelativeResidualClass :
    circleCoverRelativeComplex.CechCohomologySucc 0 :=
  circleCoverRelativeComplex.cohomologyClassSucc 0
    circleCoverRelativeResidualCocycle

/-- X.例9.2: selected cover-relative zero class. -/
def circleCoverRelativeZeroClass :
    circleCoverRelativeComplex.CechCohomologySucc 0 :=
  circleCoverRelativeComplex.cohomologyClassSucc 0
    circleCoverRelativeZeroCocycle

/-- X.例9.2: the cover-relative residual `1` is not a coboundary. -/
theorem circleCoverRelative_residual_not_coboundary :
    ¬ (circleCoverRelativeComplex.CechCoboundarySetoidSucc 0).r
      circleCoverRelativeResidualCocycle circleCoverRelativeZeroCocycle := by
  rintro ⟨primitive, hprimitive⟩
  have hzero :
      circleResidual - circleZero1 = circleD0 primitive := hprimitive
  exact circleResidual_not_coboundary ⟨primitive, hzero⟩

/-- X.例9.2: the cover-relative residual class is nonzero in `H¹`. -/
theorem circleCoverRelativeH1_nonzero :
    circleCoverRelativeResidualClass ≠ circleCoverRelativeZeroClass := by
  intro hzero
  exact circleCoverRelative_residual_not_coboundary (Quotient.exact hzero)

/--
X.例9.2: identity cochain comparison between the semantic additive surface and
the selected cover-relative circle complex.
-/
def circleH1Comparison :
    SemanticRepairCoverRelativeH1Comparison
      circleAdditiveH1Surface circleCoverRelativeComplex where
  c0Equiv := by
    change circleC0 ≃+ circleC0
    exact AddEquiv.refl circleC0
  c1Equiv := by
    change circleC1 ≃+ circleC1
    exact AddEquiv.refl circleC1
  c2Equiv := by
    change (Unit -> ZMod 2) ≃ (Unit -> ZMod 2)
    exact Equiv.refl (Unit -> ZMod 2)
  c2Equiv_zero := by
    funext σ
    rfl
  c2Equiv_symm_zero := by
    funext σ
    rfl
  d0_to := by
    intro primitive
    rfl
  d0_from := by
    intro primitive
    rfl
  d1_to := by
    intro _cochain
    funext σ
    change (0 : ZMod 2) = 0
    rfl
  d1_from := by
    intro _cochain
    funext σ
    change (0 : ZMod 2) = 0
    rfl

/-- X.例9.2: nonzero semantic class transfers across theorem 7.2 comparison. -/
theorem circleTransferredCoverRelativeH1_nonzero :
    ¬ circleH1Comparison.CoverRelativeResidualH1Zero := by
  intro hzero
  exact circleSemanticH1_nonzero
    ((SemanticRepairCoverRelativeH1Comparison.semanticRepairAdditiveH1Zero_iff_coverRelativeH1Zero
        circleH1Comparison).2 hzero)

/-- X.例9.2: concrete transfer packet for the circle-nerve nonzero class. -/
structure CircleNerveNonzeroTransferPacket where
  semanticResidualNonzero :
    ¬ circleAdditiveH1Surface.H1Zero
  coverRelativeResidualNonzero :
    circleCoverRelativeResidualClass ≠ circleCoverRelativeZeroClass
  transferredCoverRelativeNonzero :
    ¬ circleH1Comparison.CoverRelativeResidualH1Zero
  comparisonEquiv :
    circleAdditiveH1Surface.H1 ≃ circleCoverRelativeComplex.CechCohomologySucc 0
  zeroPredicateTransfer :
    circleAdditiveH1Surface.H1Zero <->
      circleH1Comparison.CoverRelativeResidualH1Zero

/--
X.例9.2: the selected circle nerve fires: both semantic and cover-relative
degree-one classes are nonzero, and theorem 7.2 transfers the nonzero reading
through the identity comparison.
-/
theorem circleNerve_nonzeroClassTransfer_packet :
    Nonempty CircleNerveNonzeroTransferPacket := by
  refine ⟨{
    semanticResidualNonzero := circleSemanticH1_nonzero
    coverRelativeResidualNonzero := circleCoverRelativeH1_nonzero
    transferredCoverRelativeNonzero :=
      circleTransferredCoverRelativeH1_nonzero
    comparisonEquiv :=
      SemanticRepairCoverRelativeH1Comparison.semanticRepairAdditiveH1_equiv_coverRelativeH1
        circleH1Comparison
    zeroPredicateTransfer :=
      SemanticRepairCoverRelativeH1Comparison.semanticRepairAdditiveH1Zero_iff_coverRelativeH1Zero
        circleH1Comparison
  }⟩

/--
R5 / IV-2: Part X circle-nerve nonzero H1 instance fired as a Part IV
pseudo-circle golden example.
-/
def circlePartIVPseudoCircleFiring :
    Cohomology.FiniteExamples.PseudoCircleGolden.PartIVCircleNonzeroH1Firing
      circleCoverRelativeComplex where
  residualCocycle := circleCoverRelativeResidualCocycle
  zeroCocycle := circleCoverRelativeZeroCocycle
  h0WitnessCountingZero :=
    Cohomology.FiniteExamples.PseudoCircleGolden.h0_witness_counting_sees_no_obstruction
  coverRelativeResidualClass_nonzero := circleCoverRelativeH1_nonzero

/--
R5 / IV-2: the Part X circle instance gives the Part IV reading "H0 sees no
obstruction, H1 is nonzero".
-/
theorem circlePartIV_h0_invisible_coverRelativeH1_nonzero :
    Cohomology.FiniteExamples.PseudoCircleGolden.witnessCountingObstruction = 0 ∧
      circleCoverRelativeComplex.cohomologyClassSucc 0
          circleCoverRelativeResidualCocycle ≠
        circleCoverRelativeComplex.cohomologyClassSucc 0
          circleCoverRelativeZeroCocycle :=
  Cohomology.FiniteExamples.PseudoCircleGolden.PartIVCircleNonzeroH1Firing.h0_invisible_and_coverRelativeH1_nonzero
    circlePartIVPseudoCircleFiring

/--
R5 / IV-2: the same circle instance read through the additive H1 quotient
surface introduced in IV-1.
-/
theorem circlePartIV_h0_invisible_additiveH1_nonzero :
    Cohomology.FiniteExamples.PseudoCircleGolden.witnessCountingObstruction = 0 ∧
      circleCoverRelativeComplex.additiveH1Class
          circleCoverRelativeResidualCocycle ≠
        circleCoverRelativeComplex.additiveH1Class
          circleCoverRelativeZeroCocycle :=
  Cohomology.FiniteExamples.PseudoCircleGolden.PartIVCircleNonzeroH1Firing.h0_invisible_and_additiveH1_nonzero
    circlePartIVPseudoCircleFiring

/-! ## Native generated quotient circle witness -/

/--
X.例9.1 / #3102: the theorem-7.5 witness reuses the circle nerve shape over
the native law-equation-generated quotient coefficient.
-/
def generatedLawCircleCoverRelativeCover :
    Cohomology.CoverRelativeCechCover FiniteModel.site where
  base := FiniteModel.siteBase
  Index := Fin 3
  chart _ := FiniteModel.siteBase
  inclusion _ := 𝟙 FiniteModel.siteBase
  simplex := circleSimplex
  overlap _ _ := FiniteModel.siteBase
  face := circleFace
  faceRestriction _ _ _ := 𝟙 FiniteModel.siteBase

/--
X.例9.1 / #3102: three-component semantic projection used by the native
generated quotient circle witness.
-/
def generatedLawCircleSemanticProjection : SemanticAtomProjection where
  SemanticAtom := Fin 3
  Component := Fin 3
  project atom := atom

/--
X.例9.1 / #3102: semantic repair cover with the same three-chart / three-edge
shape as the native generated quotient circle complex.
-/
def generatedLawCircleSemanticCover :
    SemanticRepairCover generatedLawCircleSemanticProjection where
  baseCover := {
    Chart := Fin 3
    Transition := Fin 3
    chartFinite := inferInstance
    transitionFinite := inferInstance
    holonomySupport := fun _ => True
  }
  CoverChart := Fin 3
  chart chart := chart
  chartFinite := inferInstance
  Overlap := fun _ _ => Fin 3
  overlapFinite := fun _ _ => inferInstance
  TripleOverlap := fun _ _ _ => Unit
  tripleFinite := fun _ _ _ => inferInstance
  tripleEdge01 := fun _ => 0
  tripleEdge12 := fun _ => 0
  tripleEdge02 := fun _ => 0

/-! ## Native generated singleton standard source-C0 route witness -/

/--
X.例9.1 / #3102: PUnit singleton finite-poset cover geometry used by the
finite-free ten-conclusion source-C0 route.  This is not the Fin-3 circle
complex used by the nonzero H1 example.
-/
def generatedLawFinitePosetCoverGeometry :
    Site.FinitePosetCoverGeometry FiniteModel.site where
  ContextIndex := PUnit
  finiteContextIndex := inferInstance
  context := fun _ => FiniteModel.siteContext
  contextLe := fun _ _ => True
  contextLe_refl := fun _ => trivial
  contextLe_trans := fun _ _ => trivial
  contextLe_antisymm := by
    intro i j _ _
    cases i
    cases j
    rfl
  contextLe_sound := fun _ => rfl
  contextMeet := fun _ _ => PUnit.unit
  contextMeet_le_left := fun _ _ => trivial
  contextMeet_le_right := fun _ _ => trivial
  context_le_meet := fun _ _ => trivial
  base := FiniteModel.siteBase
  cover := FiniteModel.siteSingletonCover
  finiteCoverIndex := by
    change Finite PUnit
    infer_instance
  nerveSimplex := fun _ => PUnit
  finiteNerveSimplex := fun _ => inferInstance
  simplexIndices := fun _ _ _ => PUnit.unit
  simplexOverlap := fun _ _ => FiniteModel.siteContext
  simplexOverlap_le_patch := fun _ _ _ => rfl
  adequacyRequirements := FiniteModel.siteAdequacyRequirements
  coverAdequate := FiniteModel.siteSingletonCover_uAdequate

/-- Canonical tuple geometry generated from the singleton finite-poset cover. -/
abbrev generatedLawTupleGeometry :=
  generatedLawFinitePosetCoverGeometry.canonicalTupleCoverGeometryFromOverlap

/-! ## Part X R9(b) integer lawful firing -/

/-- Semantic input for the integer law-equation lawful firing. -/
def integerLawFiniteFreeSemanticInput :
    StandardFinitePosetGeneratedBoundary.LawEquationSemanticAtomInputBody
      FiniteModel.carrier where
  Component := Fin 3
  project _ := 0
  sourceTraceToken _ := true

/-- Three-chart semantic incidence data for the integer lawful firing. -/
def integerLawFiniteFreeSemanticCover :
    SemanticRepairCover integerLawFiniteFreeSemanticInput.toSemanticAtomProjection where
  baseCover := {
    Chart := Fin 3
    Transition := Fin 3
    chartFinite := inferInstance
    transitionFinite := inferInstance
    holonomySupport := fun _ => True
  }
  CoverChart := Fin 3
  chart chart := chart
  chartFinite := inferInstance
  Overlap := fun _ _ => Fin 3
  overlapFinite := fun _ _ => inferInstance
  TripleOverlap := fun _ _ _ => Unit
  tripleFinite := fun _ _ _ => inferInstance
  tripleEdge01 := fun _ => 0
  tripleEdge12 := fun _ => 0
  tripleEdge02 := fun _ => 0

/-- Integer witness geometry with quotient sheaf condition proved on the finite site. -/
def integerLawFiniteFreeWitnessIdealGeometry :
    StandardFinitePosetGeneratedBoundary.LawEquationWitnessIdealGeometryBody
      integerLawFiniteFreeSemanticInput FiniteModel.site where
  toCore := integerLawEquationCore
  supportAtom_traceVisible := rfl
  quotientIsSheaf := integerGeneratedLawQuotientIsSheaf

/-- Geometry-indexed integer defect input with selected defect `2`. -/
def integerLawFiniteFreeDefectSource :
    StandardFinitePosetGeneratedBoundary.FinitePosetLawEquationDefectSourceBody
      integerLawFiniteFreeSemanticInput integerLawFiniteFreeWitnessIdealGeometry
      generatedLawFinitePosetCoverGeometry where
  LocalInput _ := PUnit
  input _ := PUnit.unit
  atomSupport _ _ := [FiniteModel.FiniteAtom.componentA]
  atomSupport_traceVisible := by
    intro _ _
    exact ⟨FiniteModel.FiniteAtom.componentA, by simp, rfl⟩
  lawSupport _ _ := [PUnit.unit]
  lawSupport_nonempty := by
    intro _
    exact ⟨PUnit.unit, by simp⟩
  lawSupport_required := by
    intro _ lawIndex _
    cases lawIndex
    rfl
  objectOfLocalInput _ _ := lawfulObject
  defect _ _ := (2 : ℤ)
  holds_defect_mem := by
    intro _ lawIndex _ _ _
    cases lawIndex
    exact Ideal.subset_span ⟨FiniteModel.FiniteAtom.componentA, rfl⟩

/-- Displayed required laws hold for the integer lawful input. -/
theorem integerLawFiniteFreeDisplayedRequiredLawsHoldOn :
    integerLawFiniteFreeDefectSource.DisplayedRequiredLawsHoldOn := by
  intro _ lawIndex _ _
  cases lawIndex
  exact lawfulObject_noCycleLaw

/--
X.例9.1 / Part X R9(b): the integer observable core, witness `2`, proved quotient
sheaf condition, and geometry-indexed lawful source fire the final ten-conclusion
theorem.
-/
theorem lawfulFiring_integerLawSingletonStandardSourceC0_finiteFreeTenConjunctPacket :
    let K := StandardFinitePosetGeneratedBoundary.lawEquationCechComplex
      (G := integerLawEquationCore) integerGeneratedLawQuotientIsSheaf
      generatedLawTupleGeometry
    let source := integerLawFiniteFreeDefectSource.toLawEquationBodyCechSource
    let surface := lawEquationGeneratedCurrentG06InputSurfaceOfFinitePosetGeometry
      integerLawFiniteFreeSemanticCover generatedLawFinitePosetCoverGeometry K
      (fun _ => fun _ => PUnit.unit)
      (fun _ => fun _ => PUnit.unit)
      (fun _ => fun _ => PUnit.unit)
      integerGeneratedLawQuotientIsSheaf
    Nonempty
      (StandardFinitePosetGeneratedBoundary.LawEquationGroundedComparisonFiniteFreeConjunctsBody
        integerLawFiniteFreeDefectSource surface source) :=
  StandardFinitePosetGeneratedBoundary.lawEquation_constructs_groundedComparisonPacket_finiteFree
    integerLawFiniteFreeSemanticInput integerLawFiniteFreeSemanticCover
    integerLawFiniteFreeWitnessIdealGeometry generatedLawFinitePosetCoverGeometry
    integerLawFiniteFreeDefectSource
    (fun _ => fun _ => PUnit.unit)
    (fun _ => fun _ => PUnit.unit)
    (fun _ => fun _ => PUnit.unit)
    integerLawFiniteFreeDisplayedRequiredLawsHoldOn

/-- Standard generated cover-relative complex used by the singleton source example. -/
abbrev generatedLawStandardSourceC0Complex :=
  StandardFinitePosetGeneratedBoundary.lawEquationCechComplex
    (G := lawEquationCore) generatedLawQuotientIsSheaf
    generatedLawTupleGeometry

/-- Semantic atom input tied definitionally to the finite law carrier. -/
def generatedLawFiniteFreeSemanticInput :
    StandardFinitePosetGeneratedBoundary.LawEquationSemanticAtomInputBody
      FiniteModel.carrier where
  Component := Fin 3
  project _ := 0
  sourceTraceToken _ := true

/-- Three-chart semantic incidence data feeding the singleton standard route. -/
def generatedLawFiniteFreeSemanticCover :
    SemanticRepairCover generatedLawFiniteFreeSemanticInput.toSemanticAtomProjection where
  baseCover := {
    Chart := Fin 3
    Transition := Fin 3
    chartFinite := inferInstance
    transitionFinite := inferInstance
    holonomySupport := fun _ => True
  }
  CoverChart := Fin 3
  chart chart := chart
  chartFinite := inferInstance
  Overlap := fun _ _ => Fin 3
  overlapFinite := fun _ _ => inferInstance
  TripleOverlap := fun _ _ _ => Unit
  tripleFinite := fun _ _ _ => inferInstance
  tripleEdge01 := fun _ => 0
  tripleEdge12 := fun _ => 0
  tripleEdge02 := fun _ => 0

/-- Rich production witness geometry carrying trace and quotient-sheaf inputs. -/
def generatedLawFiniteFreeWitnessIdealGeometry :
    StandardFinitePosetGeneratedBoundary.LawEquationWitnessIdealGeometryBody
      generatedLawFiniteFreeSemanticInput FiniteModel.site where
  toCore := lawEquationCore
  supportAtom_traceVisible := rfl
  quotientIsSheaf := generatedLawQuotientIsSheaf

/-- Geometry-indexed lawful defect input for the singleton standard route. -/
def generatedLawFiniteFreeDefectSource :
    StandardFinitePosetGeneratedBoundary.FinitePosetLawEquationDefectSourceBody
      generatedLawFiniteFreeSemanticInput generatedLawFiniteFreeWitnessIdealGeometry
      generatedLawFinitePosetCoverGeometry where
  LocalInput _ := PUnit
  input _ := PUnit.unit
  atomSupport _ _ := [FiniteModel.FiniteAtom.componentA]
  atomSupport_traceVisible := by
    intro _ _
    exact ⟨FiniteModel.FiniteAtom.componentA, by simp,
      rfl⟩
  lawSupport _ _ := [PUnit.unit]
  lawSupport_nonempty := by
    intro _
    exact ⟨PUnit.unit, by simp⟩
  lawSupport_required := by
    intro _ lawIndex _
    cases lawIndex
    rfl
  objectOfLocalInput _ _ := lawfulObject
  defect _ _ := (2 : ZMod 4)
  holds_defect_mem := by
    intro _ lawIndex _ _ _
    cases lawIndex
    exact Ideal.subset_span ⟨FiniteModel.FiniteAtom.componentA, rfl⟩

/-- Displayed required laws hold on the rich singleton defect input. -/
theorem generatedLawFiniteFreeDisplayedRequiredLawsHoldOn :
    generatedLawFiniteFreeDefectSource.DisplayedRequiredLawsHoldOn := by
  intro _ lawIndex _ _
  cases lawIndex
  exact lawfulObject_noCycleLaw

/--
Concrete R5 final firing on the PUnit singleton standard complex.  The result
is the generated-zero ten-conclusion packet and is separate from the Fin-3
circle nonzero residual route.
-/
theorem lawfulFiring_generatedLawSingletonStandardSourceC0_finiteFreeTenConjunctPacket :
    let K := StandardFinitePosetGeneratedBoundary.lawEquationCechComplex
      (G := lawEquationCore) generatedLawQuotientIsSheaf generatedLawTupleGeometry
    let source := generatedLawFiniteFreeDefectSource.toLawEquationBodyCechSource
    let surface := lawEquationGeneratedCurrentG06InputSurfaceOfFinitePosetGeometry
      generatedLawFiniteFreeSemanticCover generatedLawFinitePosetCoverGeometry K
      (fun _ => fun _ => PUnit.unit)
      (fun _ => fun _ => PUnit.unit)
      (fun _ => fun _ => PUnit.unit)
      generatedLawQuotientIsSheaf
    Nonempty
      (StandardFinitePosetGeneratedBoundary.LawEquationGroundedComparisonFiniteFreeConjunctsBody
        generatedLawFiniteFreeDefectSource surface source) :=
  StandardFinitePosetGeneratedBoundary.lawEquation_constructs_groundedComparisonPacket_finiteFree
    generatedLawFiniteFreeSemanticInput generatedLawFiniteFreeSemanticCover
    generatedLawFiniteFreeWitnessIdealGeometry generatedLawFinitePosetCoverGeometry
    generatedLawFiniteFreeDefectSource
    (fun _ => fun _ => PUnit.unit)
    (fun _ => fun _ => PUnit.unit)
    (fun _ => fun _ => PUnit.unit)
    generatedLawFiniteFreeDisplayedRequiredLawsHoldOn

/-- The singleton standard body source is the restriction of the zero base section. -/
theorem generatedLawSingletonStandardBodySource_toPrimitive_eq_zero :
    forall sigma,
      generatedLawFiniteFreeDefectSource.toLawEquationBodyCechSource.toPrimitive sigma = 0 := by
  intro sigma
  exact
    (lawEquationCore.obstructionQuotientCoefficient.map
      (generatedLawFiniteFreeDefectSource.toLawEquationBodyCechSource.zeroSimplexToBase
        sigma).op).hom.map_zero

/-- The R5 singleton selected residual is zero and is not the circle residual. -/
theorem generatedLawSingletonStandardGeneratedResidual_eq_zero :
    forall sigma,
      (generatedLawStandardSourceC0Complex.d 0
        generatedLawFiniteFreeDefectSource.toLawEquationBodyCechSource.toPrimitive) sigma = 0 := by
  intro sigma
  letI := generatedLawStandardSourceC0Complex.cochainAddCommGroup 0
  letI := generatedLawStandardSourceC0Complex.cochainAddCommGroup 1
  have hprimitive :
      generatedLawFiniteFreeDefectSource.toLawEquationBodyCechSource.toPrimitive = 0 := by
    funext sigma
    exact generatedLawSingletonStandardBodySource_toPrimitive_eq_zero sigma
  have hresidual :
      generatedLawStandardSourceC0Complex.d 0
          generatedLawFiniteFreeDefectSource.toLawEquationBodyCechSource.toPrimitive = 0 := by
    rw [hprimitive]
    exact (generatedLawStandardSourceC0Complex.d 0).map_zero
  exact congrFun hresidual sigma

/-- Finite degree-zero cochain instance for the legacy bounded route. -/
def generatedLawStandardSourceC0Fintype :
    Fintype (generatedLawStandardSourceC0Complex.Cn 0) := by
  change
    Fintype
      ((Site.FinitePosetCechCanonicalTupleSimplex PUnit 0) ->
        GeneratedLawQuotient)
  infer_instance

/-- Finite degree-one cochain instance for the legacy bounded route. -/
def generatedLawStandardSourceC1Fintype :
    Fintype (generatedLawStandardSourceC0Complex.Cn 1) := by
  change
    Fintype
      ((Site.FinitePosetCechCanonicalTupleSimplex PUnit 1) ->
        GeneratedLawQuotient)
  infer_instance

/-- Body Cech source generated by the singleton standard geometry. -/
def generatedLawStandardBodySource :
    LawEquationBodyCechSource defectSource generatedLawStandardSourceC0Complex where
  chartOf _ := PUnit.unit
  chartToBase _ := 𝟙 _
  restriction sigma :=
    homOfLE
      (generatedLawFinitePosetCoverGeometry.canonicalTupleOverlapFromOverlap_le_base
        0 sigma)

/-- Nonlawful body Cech source used to refute automatic realization. -/
def generatedLawStandardNonlawfulBodySource :
    LawEquationBodyCechSource nonlawfulDefectSource
      generatedLawStandardSourceC0Complex where
  chartOf _ := PUnit.unit
  chartToBase _ := 𝟙 _
  restriction sigma :=
    homOfLE
      (generatedLawFinitePosetCoverGeometry.canonicalTupleOverlapFromOverlap_le_base
        0 sigma)

/-- Selected degree-zero simplex exposing the nonlawful interpretation. -/
def generatedLawStandardSourceC0SelectedSimplex :
    Site.FinitePosetCechCanonicalTupleSimplex PUnit 0 :=
  fun _ => PUnit.unit

theorem generatedLawStandardNonlawfulBodySource_not_displayedInterpretationRealization :
    ¬ generatedLawStandardNonlawfulBodySource.DisplayedInterpretationRealization := by
  apply
    generatedLawStandardNonlawfulBodySource.restrictedDisplayedInterpretation_ne_zero_prevents_displayedInterpretationRealization
      generatedLawStandardSourceC0SelectedSimplex
  simpa [LawEquationBodyCechSource.restrictedDisplayedInterpretation,
    generatedLawStandardNonlawfulBodySource,
    nonlawfulDefectSource,
    LawAlgebra.LawEquationDefectSource.interpret,
    LawAlgebra.SemanticLawEquationWitnessIdealCore.obstructionQuotientPresheaf,
    LawAlgebra.SemanticLawEquationWitnessIdealCore.obstructionQuotientCoefficient,
    lawEquationCore] using nonlawfulDefectSource_interpret_ne_zero

/-!
Two-chart negative instance for the chart-level common-source and arrow laws.
The first chart reads zero and the second reads the nonzero quotient class of
`1`; both chart arrows are the identity into the same selected base.
-/

/-- Two-chart defect source with one zero and one nonzero interpretation. -/
def mixedDefectSource :
    LawAlgebra.LawEquationDefectSource lawEquationCore where
  Chart := Bool
  chart _ := FiniteModel.siteBase
  LocalInput _ := PUnit
  input _ := PUnit.unit
  lawSupport _ _ := [PUnit.unit]
  lawSupport_nonempty := by
    intro _i
    exact ⟨PUnit.unit, by simp⟩
  lawSupport_required := by
    intro _i lawIndex _hmem
    cases lawIndex
    rfl
  objectOfLocalInput i _ := if i then nonlawfulObject else lawfulObject
  defect i _ := if i then (1 : ZMod 4) else 0
  holds_defect_mem := by
    intro i lawIndex _hmem _hrequired hholds
    cases i with
    | false =>
        cases lawIndex
        exact Ideal.zero_mem _
    | true =>
        cases lawIndex
        exact False.elim (nonlawfulObject_not_noCycleLaw hholds)

/-- Cover-relative two-chart presentation used by the mixed-source counterexample. -/
def mixedCoverRelativeCover :
    Cohomology.CoverRelativeCechCover FiniteModel.site where
  base := FiniteModel.siteBase
  Index := Bool
  chart _ := FiniteModel.siteBase
  inclusion _ := 𝟙 _
  simplex _ := Bool
  overlap _ _ := FiniteModel.siteBase
  face _ _ sigma := sigma
  faceRestriction _ _ _ := 𝟙 _

/-- Zero-differential Cech complex isolating realization compatibility. -/
def mixedZeroCechComplex :
    Cohomology.CoverRelativeCechComplex mixedCoverRelativeCover
      generatedLawQuotientObstructionSheaf where
  cochainAddCommGroup := by
    intro _n
    change AddCommGroup (Bool -> GeneratedLawQuotient)
    infer_instance
  alternatingFaceCombination := by
    intro _n _terms _sigma
    exact (0 : GeneratedLawQuotient)
  differential := by
    intro _n
    change (Bool -> GeneratedLawQuotient) →+
      (Bool -> GeneratedLawQuotient)
    exact 0
  differential_eq_alternatingFaceCombination := by
    intro _n _cochain
    rfl
  differential_comp := by
    intro _n _cochain
    rfl

/-- Body source whose two restrictions expose incompatible interpretations. -/
def mixedBodySource :
    LawEquationBodyCechSource mixedDefectSource mixedZeroCechComplex where
  chartOf sigma := sigma
  chartToBase _ := 𝟙 _
  restriction _ := 𝟙 _

theorem mixedDefectSource_interpret_false_zero :
    mixedDefectSource.interpret false = 0 := by
  simp [mixedDefectSource, LawAlgebra.LawEquationDefectSource.interpret]

theorem mixedDefectSource_interpret_true_ne_zero :
    mixedDefectSource.interpret true ≠ 0 := by
  simp [mixedDefectSource, LawAlgebra.LawEquationDefectSource.interpret]

theorem mixedBodySource_has_displayedRequiredLawRestrictionEvaluator :
    mixedBodySource.DisplayedRequiredLawRestrictionEvaluator := by
  intro sigma tau Z gSigma gTau hcomm lawIndexSigma lawIndexTau
    hmemSigma hmemTau hrequiredSigma hrequiredTau hholdsSigma hholdsTau
  cases sigma <;> cases tau
  · simp [mixedBodySource, mixedDefectSource,
      LawAlgebra.LawEquationDefectSource.interpret]
  · exact False.elim
      (nonlawfulObject_not_noCycleLaw
        (by simpa [mixedDefectSource] using hholdsTau))
  · exact False.elim
      (nonlawfulObject_not_noCycleLaw
        (by simpa [mixedDefectSource] using hholdsSigma))
  · have heq : gSigma = gTau := Subsingleton.elim _ _
    subst gTau
    rfl

theorem mixedDefectSource_not_generatedInterpretationPointwiseZero :
    ¬ mixedDefectSource.GeneratedInterpretationPointwiseZero := by
  intro hzero
  exact mixedDefectSource_interpret_true_ne_zero (hzero true)

theorem mixedBodySource_not_arrowCompatibilityLaw :
    ¬ mixedBodySource.ArrowCompatibilityLaw := by
  intro hcompatible
  have heq :=
    hcompatible false true FiniteModel.siteBase (𝟙 _) (𝟙 _)
      (by simp [mixedBodySource])
  have hinterpret :
      mixedDefectSource.interpret false =
        mixedDefectSource.interpret true := by
    simpa [mixedBodySource] using heq
  apply mixedDefectSource_interpret_true_ne_zero
  exact hinterpret.symm.trans mixedDefectSource_interpret_false_zero

theorem mixedBodySource_not_commonRestrictionRealization :
    ¬ mixedBodySource.CommonRestrictionRealization :=
  mixedBodySource.no_commonRestrictionRealization_without_arrowCompatibilityLaw
    mixedBodySource_not_arrowCompatibilityLaw

theorem mixedBodySource_zeroBase_not_preservesDisplayedInterpretation :
    ¬ mixedBodySource.BaseRestrictionSourcePreservesDisplayedInterpretation
      mixedBodySource.toBaseRestrictionSource := by
  intro hpreserves
  exact mixedBodySource_not_commonRestrictionRealization
    ⟨mixedBodySource.toBaseRestrictionSource, hpreserves⟩

/-- Additive boundary data generated from the singleton standard source. -/
def generatedLawStandardSourceC0BoundaryAdditiveData :
    SemanticRepairCoverH1BoundaryRelationAdditiveData
      generatedLawCircleSemanticProjection :=
  coverRelativeBoundaryAdditiveDataOfComplex generatedLawCircleSemanticCover
    generatedLawStandardSourceC0Complex generatedLawStandardSourceC0Fintype
    generatedLawStandardSourceC1Fintype
    (0 : generatedLawStandardSourceC0Complex.Cn 1)
    (generatedLawStandardSourceC0Complex.d 0
      generatedLawStandardBodySource.toPrimitive)
    (by
      letI := generatedLawStandardSourceC0Complex.cochainAddCommGroup 1
      letI := generatedLawStandardSourceC0Complex.cochainAddCommGroup 2
      exact (generatedLawStandardSourceC0Complex.d 1).map_zero)
    (generatedLawStandardSourceC0Complex.differential_comp 0
      generatedLawStandardBodySource.toPrimitive)
    rfl
    (fun _ => lawEquationCompleteRepairSupport generatedLawCircleSemanticProjection)
    (fun _ _ =>
      (lawEquationCompleteRepairSupport_componentCoverage_and_faithfulness
        generatedLawCircleSemanticProjection
        generatedLawCircleSemanticCover.baseCover).1)
    (fun _ _ =>
      (lawEquationCompleteRepairSupport_componentCoverage_and_faithfulness
        generatedLawCircleSemanticProjection
        generatedLawCircleSemanticCover.baseCover).2)

/--
Legacy bounded singleton firing retained for comparison only.  It requires
cochain Fintype inputs and is not completion evidence for the R5 final route.
-/
theorem legacyFiring_generatedLawSingletonStandardSourceC0_boundedConjuncts :
    Nonempty
      (Sigma fun surface :
        LawEquationGeneratedCurrentG06InputSurface
          generatedLawCircleSemanticCover FiniteModel.site
          lawEquationCore.obstructionQuotientPresheaf
          generatedLawStandardSourceC0Complex =>
        Sigma fun comparison :
          SemanticRepairCoverRelativeH1Comparison
            generatedLawStandardSourceC0BoundaryAdditiveData.toAdditiveH1Surface
            generatedLawStandardSourceC0Complex =>
          LawEquationGroundedComparisonConjunctsBody
            defectSource surface generatedLawStandardBodySource
            generatedLawStandardSourceC0BoundaryAdditiveData
            comparison) :=
  StandardFinitePosetGeneratedBoundary.lawEquation_constructs_groundedResearchConjuncts_fromStandardFinitePosetSource
    generatedLawCircleSemanticCover defectSource displayedRequiredLawsHoldOn
    generatedLawQuotientIsSheaf
    (StandardFinitePosetGeneratedBoundary.canonicalTupleGeneratedBoundaryLaw
      (G := lawEquationCore) generatedLawQuotientIsSheaf
      generatedLawTupleGeometry)
    (fun _ => fun _ => PUnit.unit)
    (fun _ => fun _ => PUnit.unit)
    (fun _ => fun _ => PUnit.unit)
    generatedLawStandardBodySource generatedLawStandardSourceC0Fintype
    generatedLawStandardSourceC1Fintype

/-- X.例9.1 / #3102: native generated quotient circle C0 cochains. -/
abbrev generatedLawCircleC0 : Type :=
  Fin 3 -> GeneratedLawQuotient

/-- X.例9.1 / #3102: native generated quotient circle C1 cochains. -/
abbrev generatedLawCircleC1 : Type :=
  Fin 3 -> GeneratedLawQuotient

/-- X.例9.1 / #3102: native generated quotient circle C2 cochains. -/
abbrev generatedLawCircleC2 : Type :=
  Unit -> GeneratedLawQuotient

/-- X.例9.1 / #3102: selected circle coboundary over the native quotient. -/
def generatedLawCircleD0 (cochain : generatedLawCircleC0) :
    generatedLawCircleC1 :=
  fun edge => cochain (circleNext edge) - cochain edge

/-- X.例9.1 / #3102: selected nonzero residual over the native quotient. -/
def generatedLawCircleResidual : generatedLawCircleC1 :=
  fun _ => generatedLawQuotientOne

/-- X.例9.1 / #3102: selected zero one-cochain over the native quotient. -/
def generatedLawCircleZero1 : generatedLawCircleC1 :=
  fun _ => 0

/-- X.例9.1 / #3102: selected zero two-cochain over the native quotient. -/
def generatedLawCircleZero2 : generatedLawCircleC2 :=
  fun _ => 0

/--
X.例9.1 / #3102: the native generated quotient residual on the three-edge
circle is not a coboundary.
-/
theorem generatedLawCircleResidual_not_coboundary :
    ¬ ∃ primitive : generatedLawCircleC0,
      generatedLawCircleResidual - generatedLawCircleZero1 =
        generatedLawCircleD0 primitive := by
  rintro ⟨primitive, hprimitive⟩
  have h0 := congrFun hprimitive (0 : Fin 3)
  have h1 := congrFun hprimitive (1 : Fin 3)
  have h2 := congrFun hprimitive (2 : Fin 3)
  simp [generatedLawCircleResidual, generatedLawCircleZero1,
    generatedLawCircleD0, circleNext] at h0 h1 h2
  have hsum :
      generatedLawQuotientOne + generatedLawQuotientOne + generatedLawQuotientOne =
        0 := by
    nth_rw 1 [h0]
    nth_rw 1 [h1]
    nth_rw 1 [h2]
    abel
  have hcollapse :
      generatedLawQuotientOne + generatedLawQuotientOne + generatedLawQuotientOne =
        generatedLawQuotientOne := by
    rw [generatedLawQuotientOne_add_self]
    rfl
  exact generatedLawQuotientOne_ne_zero (hcollapse ▸ hsum)

/-- X.例9.1 / #3102: selected circle complex over the native generated quotient. -/
def generatedLawCircleCoverRelativeComplex :
    Cohomology.CoverRelativeCechComplex
      generatedLawCircleCoverRelativeCover generatedLawQuotientObstructionSheaf where
  cochainAddCommGroup n := by
    change AddCommGroup (circleSimplex n -> GeneratedLawQuotient)
    infer_instance
  alternatingFaceCombination
    | 0, terms => fun edge =>
        (terms edge 0 : GeneratedLawQuotient) - terms edge 1
    | _ + 1, _terms => fun _ => (0 : GeneratedLawQuotient)
  differential
    | 0 => by
        change generatedLawCircleC0 →+ generatedLawCircleC1
        exact {
          toFun := generatedLawCircleD0
          map_zero' := by
            funext edge
            simp [generatedLawCircleD0]
          map_add' := by
            intro left right
            funext edge
            simp [generatedLawCircleD0]
            abel
        }
    | _ + 1 => by
        change (circleSimplex (_ + 1) -> GeneratedLawQuotient) →+
          (circleSimplex (_ + 2) -> GeneratedLawQuotient)
        exact {
          toFun := fun _ => fun _ => (0 : GeneratedLawQuotient)
          map_zero' := by
            funext σ
            rfl
          map_add' := by
            intro _x _y
            funext σ
            rfl
        }
  differential_eq_alternatingFaceCombination := by
    intro n c
    cases n with
    | zero =>
        funext edge
        letI : AddCommGroup (generatedLawQuotientPresheaf.obj (op FiniteModel.siteBase)) := by
          change AddCommGroup GeneratedLawQuotient
          infer_instance
        change generatedLawCircleD0 c edge =
          generatedLawQuotientPresheaf.map (𝟙 (op FiniteModel.siteBase))
              (c (circleNext edge)) -
            generatedLawQuotientPresheaf.map (𝟙 (op FiniteModel.siteBase)) (c edge)
        simp [generatedLawCircleD0]
    | succ n =>
        funext σ
        change (0 : GeneratedLawQuotient) = 0
        rfl
  differential_comp := by
    intro n _c
    cases n with
    | zero =>
        funext σ
        change (0 : GeneratedLawQuotient) = 0
        rfl
    | succ n =>
        funext σ
        change (0 : GeneratedLawQuotient) = 0
        rfl

/--
X.例9.1 / #3102: generated support attached to a circle primitive.  The
support is the nonzero locus of the primitive, not a free `True` slot.
-/
def generatedLawCircleSupportOf (primitive : generatedLawCircleC0) :
    generatedLawCircleSemanticProjection.Support :=
  fun atom => primitive atom ≠ 0

private theorem generatedLawCircleD0_eq_residual_impossible
    (primitive : generatedLawCircleC0)
    (hboundary : generatedLawCircleD0 primitive = generatedLawCircleResidual) :
    False := by
  exact generatedLawCircleResidual_not_coboundary
    ⟨primitive, by
      funext edge
      rw [hboundary]
      simp [generatedLawCircleZero1]⟩

/--
X.例9.1 / #3102: the nonzero-locus support covers residual components for a
boundary primitive.  The premise is impossible by the nonzero circle H1 proof,
so this does not use a freely supplied Prop field.
-/
theorem generatedLawCircle_componentCovered_of_boundary
    (primitive : generatedLawCircleC0)
    (hboundary :
      generatedLawCircleCoverRelativeComplex.differential 0 primitive =
        generatedLawCircleResidual) :
    ResidualComponentCoveredSupport generatedLawCircleSemanticProjection
      generatedLawCircleSemanticCover.baseCover
      (generatedLawCircleSupportOf primitive) := by
  exact False.elim
    (generatedLawCircleD0_eq_residual_impossible primitive hboundary)

/--
X.例9.1 / #3102: the nonzero-locus support is component-faithful for a boundary
primitive, again by the impossibility of such a primitive on the native
generated quotient circle.
-/
theorem generatedLawCircle_componentFaithful_of_boundary
    (primitive : generatedLawCircleC0)
    (hboundary :
      generatedLawCircleCoverRelativeComplex.differential 0 primitive =
        generatedLawCircleResidual) :
    ResidualComponentFaithfulSupport generatedLawCircleSemanticProjection
      generatedLawCircleSemanticCover.baseCover
      (generatedLawCircleSupportOf primitive) := by
  exact False.elim
    (generatedLawCircleD0_eq_residual_impossible primitive hboundary)

instance generatedLawCircleCoverRelativeC0Fintype :
    Fintype (generatedLawCircleCoverRelativeComplex.Cn 0) := by
  change Fintype generatedLawCircleC0
  infer_instance

instance generatedLawCircleCoverRelativeC1Fintype :
    Fintype (generatedLawCircleCoverRelativeComplex.Cn 1) := by
  change Fintype generatedLawCircleC1
  infer_instance

/-- X.例9.1 / #3102: semantic Cech data over the native generated circle. -/
def generatedLawCircleSemanticCechData :
    SemanticRepairCoverCechData generatedLawCircleSemanticCover :=
  AAT.AG.SemanticRepair.coverRelativeCechDataOfComplex generatedLawCircleSemanticCover
    generatedLawCircleCoverRelativeComplex generatedLawCircleCoverRelativeC0Fintype
    generatedLawCircleCoverRelativeC1Fintype generatedLawCircleZero1
    generatedLawCircleResidual
    (by
      funext σ
      rfl)
    (by
      funext σ
      rfl)

/-- X.例9.1 / #3102: additive Cech data over the native generated circle. -/
def generatedLawCircleSemanticAdditiveData :
    SemanticRepairAdditiveCechH1Data generatedLawCircleSemanticCechData :=
  AAT.AG.SemanticRepair.coverRelativeAdditiveCechDataOfComplex generatedLawCircleSemanticCover
    generatedLawCircleCoverRelativeComplex generatedLawCircleCoverRelativeC0Fintype
    generatedLawCircleCoverRelativeC1Fintype generatedLawCircleZero1
    generatedLawCircleResidual
    (by
      funext σ
      rfl)
    (by
      funext σ
      rfl)
    (by
      funext edge
      rfl)

/-- X.例9.1 / #3102: boundary-relation data over native circle coefficients. -/
def generatedLawCircleBoundaryRelationData :
    SemanticRepairCoverH1BoundaryRelationAbelianData generatedLawCircleSemanticProjection :=
  (AAT.AG.SemanticRepair.coverRelativeBoundaryAdditiveDataOfComplex
    generatedLawCircleSemanticCover
    generatedLawCircleCoverRelativeComplex generatedLawCircleCoverRelativeC0Fintype
    generatedLawCircleCoverRelativeC1Fintype generatedLawCircleZero1
    generatedLawCircleResidual
    (by
      funext σ
      rfl)
    (by
      funext σ
      rfl)
    (by
      funext edge
      rfl)
    generatedLawCircleSupportOf
    generatedLawCircle_componentCovered_of_boundary
    generatedLawCircle_componentFaithful_of_boundary).boundaryRelation

/-- X.例9.1 / #3102: additive boundary data over native circle coefficients. -/
def generatedLawCircleBoundaryAdditiveData :
    SemanticRepairCoverH1BoundaryRelationAdditiveData generatedLawCircleSemanticProjection :=
  AAT.AG.SemanticRepair.coverRelativeBoundaryAdditiveDataOfComplex
    generatedLawCircleSemanticCover
    generatedLawCircleCoverRelativeComplex generatedLawCircleCoverRelativeC0Fintype
    generatedLawCircleCoverRelativeC1Fintype generatedLawCircleZero1
    generatedLawCircleResidual
    (by
      funext σ
      rfl)
    (by
      funext σ
      rfl)
    (by
      funext edge
      rfl)
    generatedLawCircleSupportOf
    generatedLawCircle_componentCovered_of_boundary
    generatedLawCircle_componentFaithful_of_boundary

/-- X.例9.1 / #3102: native quotient circle H1 class is nonzero. -/
theorem generatedLawCircleSemanticH1_nonzero :
    ¬ generatedLawCircleBoundaryAdditiveData.toAdditiveH1Surface.H1Zero := by
  intro hzero
  exact generatedLawCircleResidual_not_coboundary
    (by
      simpa [SemanticRepairAdditiveH1Surface.Cohomologous,
        generatedLawCircleBoundaryAdditiveData,
        generatedLawCircleBoundaryRelationData,
        generatedLawCircleSemanticCechData]
        using Quotient.exact hzero)

/--
The concrete Fin-3 circle residual is not generated by a degree-zero
primitive, providing the negative instance paired with the generated-boundary
surface.
-/
theorem generatedLawCircle_not_generatedResidualBoundarySurfaceBody :
    ¬ GeneratedResidualBoundarySurfaceBody
      generatedLawCircleBoundaryAdditiveData.toAdditiveH1Surface := by
  intro hboundary
  apply generatedLawCircleSemanticH1_nonzero
  exact semanticH1ZeroBody_constructs_additiveH1Zero
    (residualBoundaryBody_constructs_semanticH1ZeroBody hboundary)

/-- The same circle witness refutes the generated semantic-zero predicate. -/
theorem generatedLawCircle_not_generatedSemanticH1ZeroBody :
    ¬ GeneratedSemanticH1ZeroBody
      generatedLawCircleBoundaryAdditiveData.toAdditiveH1Surface :=
  no_generatedSemanticH1ZeroBody_without_residualBoundary
    generatedLawCircle_not_generatedResidualBoundarySurfaceBody

/-- X.例9.1 / #3102: identity cochain realization for the constructed native circle. -/
def generatedLawCircleH1Realization :
    SemanticRepairCoverRelativeCochainRealization
      generatedLawCircleBoundaryAdditiveData.toAdditiveH1Surface
      generatedLawCircleCoverRelativeComplex :=
  AAT.AG.SemanticRepair.coverRelativeIdentityCochainRealizationOfComplex
    generatedLawCircleSemanticCover
    generatedLawCircleCoverRelativeComplex generatedLawCircleCoverRelativeC0Fintype
    generatedLawCircleCoverRelativeC1Fintype generatedLawCircleZero1
    generatedLawCircleResidual
    (by
      funext σ
      rfl)
    (by
      funext σ
      rfl)
    (by
      funext edge
      rfl)
    generatedLawCircleSupportOf
    generatedLawCircle_componentCovered_of_boundary
    generatedLawCircle_componentFaithful_of_boundary

/-
X.例9.1 / #3102: zero primitive on the Fin-3 circle complex generates the
zero-boundary packet.  Its residual is not the selected nonzero circle
residual used by `generatedLawCircleSemanticH1_nonzero`.
-/
/-- Additive data generated by the zero primitive on the Fin-3 circle. -/
def generatedLawCircleZeroBoundaryAdditiveData :
    SemanticRepairCoverH1BoundaryRelationAdditiveData
      generatedLawCircleSemanticProjection :=
  coverRelativeBoundaryAdditiveDataOfComplex generatedLawCircleSemanticCover
    generatedLawCircleCoverRelativeComplex
    generatedLawCircleCoverRelativeC0Fintype
    generatedLawCircleCoverRelativeC1Fintype generatedLawCircleZero1
    (generatedLawCircleCoverRelativeComplex.d 0 (0 : generatedLawCircleC0))
    (by
      funext sigma
      rfl)
    (generatedLawCircleCoverRelativeComplex.differential_comp
      0 (0 : generatedLawCircleC0))
    (by
      funext edge
      rfl)
    (fun _ => lawEquationCompleteRepairSupport generatedLawCircleSemanticProjection)
    (fun _ _ =>
      (lawEquationCompleteRepairSupport_componentCoverage_and_faithfulness
        generatedLawCircleSemanticProjection
        generatedLawCircleSemanticCover.baseCover).1)
    (fun _ _ =>
      (lawEquationCompleteRepairSupport_componentCoverage_and_faithfulness
        generatedLawCircleSemanticProjection
        generatedLawCircleSemanticCover.baseCover).2)

/--
The zero primitive generates the zero-boundary packet, separately from the
nonzero circle residual used by `generatedLawCircleSemanticH1_nonzero`.
-/
theorem lawfulFiring_generatedLawCircleComplex_zeroBoundaryPacket_fromZeroPrimitive :
    Nonempty
      (LawEquationGeneratedBoundaryGroundedComparisonPacket
        generatedLawCircleSemanticCover defectSource
        (⊤ : Sieve FiniteModel.siteBase) generatedLawGluingData
        generatedLawCircleCoverRelativeComplex
        generatedLawCircleZeroBoundaryAdditiveData) :=
  lawEquation_constructs_generatedBoundary_groundedComparisonPacket_fromPrimitive
    generatedLawCircleSemanticCover
    defectSource displayedRequiredLawsHoldOn
    (fun chart => chart)
    (fun overlap => overlap.2)
    (fun _triple => ())
    (⊤ : Sieve FiniteModel.siteBase)
    generatedLawQuotientIsSheaf
    generatedLawCircleCoverRelativeComplex
    generatedLawCircleCoverRelativeC0Fintype
    generatedLawCircleCoverRelativeC1Fintype
    generatedLawCircleZero1
    (0 : generatedLawCircleC0)
    (by
      funext σ
      rfl)
    (by
      funext edge
      rfl)
    (fun _ => lawEquationCompleteRepairSupport generatedLawCircleSemanticProjection)
    (fun _ _ =>
      (lawEquationCompleteRepairSupport_componentCoverage_and_faithfulness
        generatedLawCircleSemanticProjection
        generatedLawCircleSemanticCover.baseCover).1)
    (fun _ _ =>
      (lawEquationCompleteRepairSupport_componentCoverage_and_faithfulness
        generatedLawCircleSemanticProjection
        generatedLawCircleSemanticCover.baseCover).2)
    (FiniteModel.site.top_mem FiniteModel.siteBase)
    generatedLawGluingData

/-- X.例9.1 / #3102: true-sheaf certificate for the constructed native circle route. -/
def generatedLawCircleTrueSheafCertificate :
    generatedLawCircleBoundaryAdditiveData.TrueSheafConditionCertificate
      FiniteModel.site generatedLawQuotientPresheaf
      (⊤ : Sieve FiniteModel.siteBase) where
  cover_mem := FiniteModel.site.top_mem FiniteModel.siteBase
  sheafCondition := generatedLawQuotientIsSheaf

/--
X.例9.1 / #3102: the older generated-pair SAGA packet fires on the Fin-3
circle complex.  The H1-class nonzero theorem is bundled separately below;
this declaration itself returns only the generated-pair packet.
-/
theorem lawfulFiring_generatedLawCircle_generatedPairSAGAPacket :
    Nonempty
      (Sigma fun comparison :
        SemanticRepairCoverRelativeH1Comparison
          generatedLawCircleBoundaryAdditiveData.toAdditiveH1Surface
          generatedLawCircleCoverRelativeComplex =>
          SemanticRepairGeneratedEndToEndSAGAPacket
            generatedLawCircleBoundaryAdditiveData defectSource FiniteModel.site
            generatedLawQuotientPresheaf
            (⊤ : Sieve FiniteModel.siteBase) generatedLawGluingData
          comparison) :=
  by
    letI : Fintype (generatedLawCircleCoverRelativeComplex.Cn 0) :=
      generatedLawCircleCoverRelativeC0Fintype
    letI : Fintype (generatedLawCircleCoverRelativeComplex.Cn 1) :=
      generatedLawCircleCoverRelativeC1Fintype
    rcases
      lawEquation_constructs_generatedPair_groundedComparisonPacket_fromCoverRelativeComplex
        generatedLawCircleSemanticCover
        defectSource displayedRequiredLawsHoldOn
        (fun chart => chart)
        (fun overlap => overlap.2)
        (fun _triple => ())
        (⊤ : Sieve FiniteModel.siteBase)
        generatedLawQuotientIsSheaf
        generatedLawCircleCoverRelativeComplex
        generatedLawCircleCoverRelativeC0Fintype
        generatedLawCircleCoverRelativeC1Fintype
        generatedLawCircleZero1
        generatedLawCircleResidual
        (by
          funext σ
          rfl)
        (by
          funext σ
          rfl)
        (by
          funext edge
          rfl)
        generatedLawCircleSupportOf
        generatedLawCircle_componentCovered_of_boundary
        generatedLawCircle_componentFaithful_of_boundary
        (FiniteModel.site.top_mem FiniteModel.siteBase)
        generatedLawGluingData with
      ⟨⟨_bridge, comparison, packet⟩⟩
    exact ⟨⟨comparison, packet⟩⟩

/--
X.例9.1 / #3102: the Fin-3 circle nonzero residual together with the older
generated-pair SAGA packet on that same circle complex.  This is not the R5
finite-free ten-conclusion generated-zero packet.
-/
theorem generatedLawCircle_nonzeroResidual_withGeneratedPairSAGAPacket :
    Nontrivial GeneratedLawQuotient /\
      (¬ generatedLawCircleBoundaryAdditiveData.toAdditiveH1Surface.H1Zero) /\
      Nonempty
        (Sigma fun comparison :
          SemanticRepairCoverRelativeH1Comparison
            generatedLawCircleBoundaryAdditiveData.toAdditiveH1Surface
            generatedLawCircleCoverRelativeComplex =>
            SemanticRepairGeneratedEndToEndSAGAPacket
              generatedLawCircleBoundaryAdditiveData defectSource FiniteModel.site
              generatedLawQuotientPresheaf
              (⊤ : Sieve FiniteModel.siteBase) generatedLawGluingData
              comparison) :=
  ⟨generatedLawQuotientNontrivial,
    generatedLawCircleSemanticH1_nonzero,
    lawfulFiring_generatedLawCircle_generatedPairSAGAPacket⟩

/--
Two distinct Cech witnesses sharing the generated law-equation coefficient:
a Fin-3 circle nonzero H1 class and a PUnit singleton standard generated-zero
packet.  The type does not assert that the coefficient is their only shared
datum.
-/
structure GeneratedLawSharedCoefficientSeparateCechWitnesses where
  coefficientNontrivial : Nontrivial GeneratedLawQuotient
  circleH1ClassNonzero :
    ¬ generatedLawCircleBoundaryAdditiveData.toAdditiveH1Surface.H1Zero
  circleGeneratedPairPacket :
    Nonempty
      (Sigma fun comparison :
        SemanticRepairCoverRelativeH1Comparison
          generatedLawCircleBoundaryAdditiveData.toAdditiveH1Surface
          generatedLawCircleCoverRelativeComplex =>
          SemanticRepairGeneratedEndToEndSAGAPacket
            generatedLawCircleBoundaryAdditiveData defectSource FiniteModel.site
            generatedLawQuotientPresheaf
            (⊤ : Sieve FiniteModel.siteBase) generatedLawGluingData comparison)
  singletonStandardGeneratedZeroPacket :
    let K := StandardFinitePosetGeneratedBoundary.lawEquationCechComplex
      (G := lawEquationCore) generatedLawQuotientIsSheaf generatedLawTupleGeometry
    let source := generatedLawFiniteFreeDefectSource.toLawEquationBodyCechSource
    let surface := lawEquationGeneratedCurrentG06InputSurfaceOfFinitePosetGeometry
      generatedLawFiniteFreeSemanticCover generatedLawFinitePosetCoverGeometry K
      (fun _ => fun _ => PUnit.unit)
      (fun _ => fun _ => PUnit.unit)
      (fun _ => fun _ => PUnit.unit)
      generatedLawQuotientIsSheaf
    Nonempty
      (StandardFinitePosetGeneratedBoundary.LawEquationGroundedComparisonFiniteFreeConjunctsBody
        generatedLawFiniteFreeDefectSource surface source)

/--
The two example routes share the generated coefficient, but their complexes
and selected residuals remain separate in the result type.
-/
theorem generatedLaw_sharedCoefficient_separateCircleNonzero_andSingletonStandardPackets :
    GeneratedLawSharedCoefficientSeparateCechWitnesses where
  coefficientNontrivial := generatedLawQuotientNontrivial
  circleH1ClassNonzero := generatedLawCircleSemanticH1_nonzero
  circleGeneratedPairPacket :=
    lawfulFiring_generatedLawCircle_generatedPairSAGAPacket
  singletonStandardGeneratedZeroPacket :=
    lawfulFiring_generatedLawSingletonStandardSourceC0_finiteFreeTenConjunctPacket

end SemanticRepairPart10
end Examples
end AAT.AG
