import Formal.AG.Examples.FiniteModel
import Formal.AG.Cohomology.FiniteExamples
import Formal.AG.SemanticRepair.Boundary
import Mathlib.Data.Int.Basic
import Mathlib.Data.ZMod.Basic

noncomputable section

namespace AAT.AG
namespace Examples
namespace SemanticRepairPart10

open CategoryTheory
open Opposite
open SemanticRepair

/-!
PRD-10 R9 / AC16 finite lawful firing instance.

Example 9.1 is the lawful firing witness.  It is separate from the circle-nerve
nonzero witness used by example 9.2: in this lawful instance the generated
degree-zero class vanishes by theorem 8.1, and that zero reading is the intended
end-to-end firing surface rather than a missing obstruction.
-/

/-! ## Concrete quotient-sheaf instance -/

/-- X.例9.1: the selected quotient coefficient presheaf on the finite site. -/
def quotientPresheaf : Site.AATPresheaf FiniteModel.site where
  obj _ := PUnit
  map _ x := x
  map_id _ := rfl
  map_comp _ _ := rfl

/--
X.例9.1: `quotientIsSheaf` is discharged as a theorem for the concrete finite
singleton quotient instance.  General quotient sheaf comparison remains data.
-/
theorem quotientIsSheaf :
    Site.AATSheafCondition FiniteModel.site quotientPresheaf := by
  intro _base _cover _hcover family _compatible
  refine ⟨PUnit.unit, ?_, ?_⟩
  · intro _Y f hf
    cases family f hf
    rfl
  · intro y _hy
    cases y
    rfl

/-- X.例9.1: concrete obstruction coefficient sheaf generated by the quotient. -/
def quotientObstructionSheaf :
    Cohomology.ObstructionSheaf FiniteModel.site where
  carrier := {
    carrier := quotientPresheaf
    isSheaf := quotientIsSheaf
  }
  addCommGroup W := by
    change AddCommGroup PUnit
    infer_instance
  map_zero := by
    intro _source _target _f
    rfl
  map_add := by
    intro _source _target _f x y
    cases x
    cases y
    rfl

/-! ## Concrete semantic additive and cover-relative zero data -/

/-- X.例9.1: singleton semantic atom projection for the lawful firing witness. -/
def semanticProjection : SemanticAtomProjection where
  SemanticAtom := PUnit
  Component := PUnit
  project _ := PUnit.unit

/-- X.例9.1: singleton finite semantic repair cover. -/
def semanticCover : SemanticRepairCover semanticProjection where
  baseCover := {
    Chart := PUnit
    Transition := PUnit
    chartFinite := inferInstance
    transitionFinite := inferInstance
    holonomySupport := fun _ => True
  }
  CoverChart := PUnit
  chart _ := PUnit.unit
  chartFinite := inferInstance
  Overlap := fun _ _ => PUnit
  overlapFinite := fun _ _ => inferInstance
  TripleOverlap := fun _ _ _ => PUnit
  tripleFinite := fun _ _ _ => inferInstance
  tripleEdge01 := fun _ => PUnit.unit
  tripleEdge12 := fun _ => PUnit.unit
  tripleEdge02 := fun _ => PUnit.unit

/-- X.例9.1: zero additive Cech data for the lawful firing witness. -/
def semanticCechData : SemanticRepairCoverCechData semanticCover where
  C0 := PUnit
  C1 := PUnit
  C2 := PUnit
  c0Finite := inferInstance
  c1Finite := inferInstance
  zero1 := PUnit.unit
  zero2 := PUnit.unit
  delta0 _ := PUnit.unit
  delta1 _ := PUnit.unit
  residual := PUnit.unit
  zero1_cocycle := rfl
  delta1_delta0_eq_zero := fun _ => rfl
  residual_cocycle := rfl

/-- X.例9.1: additive law package for the zero Cech surface. -/
def semanticAdditiveData :
    SemanticRepairAdditiveCechH1Data semanticCechData where
  c0AddCommGroup := by
    change AddCommGroup PUnit
    infer_instance
  c1AddCommGroup := by
    change AddCommGroup PUnit
    infer_instance
  zero1_eq_zero := rfl
  delta0_zero := rfl
  delta0_add := fun _ _ => rfl
  delta0_neg := fun _ => rfl

/-- X.例9.1: boundary-relation data for the lawful zero instance. -/
def boundaryRelationData :
    SemanticRepairCoverH1BoundaryRelationAbelianData semanticProjection where
  cover := semanticCover
  cech := semanticCechData
  supportOf _ := fun _ => True
  component_covered_of_boundary := by
    intro _primitive _hboundary residual hresidual
    exact ⟨residual, trivial, rfl⟩
  component_faithful_of_boundary := by
    intro _primitive _hboundary _residual _candidate _hresidual _hcandidate _hprojection
    trivial

/-- X.例9.1: additive boundary-relation data used by theorem 7.5. -/
def boundaryAdditiveData :
    SemanticRepairCoverH1BoundaryRelationAdditiveData semanticProjection where
  boundaryRelation := boundaryRelationData
  additive := semanticAdditiveData

/-- X.例9.1: cover-relative singleton cover for the concrete Cech complex. -/
def coverRelativeCover :
    Cohomology.CoverRelativeCechCover FiniteModel.site where
  base := FiniteModel.siteBase
  Index := PUnit
  chart _ := FiniteModel.siteBase
  inclusion _ := 𝟙 FiniteModel.siteBase
  simplex _ := PUnit
  overlap _ _ := FiniteModel.siteBase
  face _ _ _ := PUnit.unit
  faceRestriction _ _ _ := 𝟙 FiniteModel.siteBase

/-- X.例9.1: singleton cover-relative Cech complex with zero differential. -/
def coverRelativeComplex :
    Cohomology.CoverRelativeCechComplex coverRelativeCover quotientObstructionSheaf where
  cochainAddCommGroup n := by
    change AddCommGroup (PUnit -> PUnit)
    infer_instance
  alternatingFaceCombination _ _ _ := PUnit.unit
  differential _ := by
    change (PUnit -> PUnit) →+ (PUnit -> PUnit)
    exact {
      toFun := fun _ _ => PUnit.unit
      map_zero' := by
        funext σ
        rfl
      map_add' := by
        intro x y
        funext σ
        cases x σ
        cases y σ
        rfl
    }
  differential_eq_alternatingFaceCombination := by
    intro _n c
    funext σ
    cases c σ
    rfl
  differential_comp := by
    intro _n c
    funext σ
    cases c σ
    rfl

/-- X.例9.1: additive equivalence between `PUnit` and singleton cochains. -/
def punitCochainAddEquiv (_n : Nat) :
    PUnit ≃+ (PUnit -> PUnit) where
  toFun _ _ := PUnit.unit
  invFun _ := PUnit.unit
  left_inv := by
    intro x
    cases x
    rfl
  right_inv := by
    intro f
    funext σ
    cases f σ
    rfl
  map_add' := by
    intro x y
    cases x
    cases y
    rfl

/-- X.例9.1: equivalence between `PUnit` and degree-two singleton cochains. -/
def punitCochainEquiv (_n : Nat) :
    PUnit ≃ (PUnit -> PUnit) where
  toFun _ _ := PUnit.unit
  invFun _ := PUnit.unit
  left_inv := by
    intro x
    cases x
    rfl
  right_inv := by
    intro f
    funext σ
    cases f σ
    rfl

/--
X.例9.1: concrete cochain comparison data.  Since both sides are singleton
zero surfaces, all differential compatibility obligations are definitional.
-/
def h1Comparison :
    SemanticRepairCoverRelativeH1Comparison
      boundaryAdditiveData.toAdditiveH1Surface coverRelativeComplex where
  c0Equiv := punitCochainAddEquiv 0
  c1Equiv := punitCochainAddEquiv 1
  c2Equiv := punitCochainEquiv 2
  c2Equiv_zero := rfl
  c2Equiv_symm_zero := rfl
  d0_to := by
    intro primitive
    cases primitive
    funext σ
    cases σ
    rfl
  d0_from := by
    intro primitive
    cases primitive PUnit.unit
    rfl
  d1_to := by
    intro cochain
    cases cochain
    funext σ
    cases σ
    rfl
  d1_from := by
    intro cochain
    cases cochain PUnit.unit
    rfl

/--
X.例9.1: concrete cochain realization data whose theorem-level H1 comparison
is generated by `SemanticRepairCoverRelativeCochainRealization.toH1Comparison`.
-/
def h1Realization :
    SemanticRepairCoverRelativeCochainRealization
      boundaryAdditiveData.toAdditiveH1Surface coverRelativeComplex where
  c0Equiv := punitCochainAddEquiv 0
  c1Equiv := punitCochainAddEquiv 1
  c2Equiv := punitCochainEquiv 2
  c2Equiv_zero := rfl
  c2Equiv_symm_zero := rfl
  d0_to := by
    intro primitive
    cases primitive
    funext σ
    cases σ
    rfl
  d0_from := by
    intro primitive
    cases primitive PUnit.unit
    rfl
  d1_to := by
    intro cochain
    cases cochain
    funext σ
    cases σ
    rfl
  d1_from := by
    intro cochain
    cases cochain PUnit.unit
    rfl

/-! ## Concrete law-equation firing data -/

/-- X.例9.1: lawful finite object with the selected NoCycle relation removed. -/
def lawfulConfiguration : AtomConfiguration FiniteModel.carrier where
  family := FiniteModel.allFamily
  relation _ _ := False
  identification _ _ := False

/-- X.例9.1: lawful local object used by the displayed law source. -/
def lawfulObject : ArchitectureObject FiniteModel.carrier :=
  FiniteModel.objectOfConfiguration lawfulConfiguration

/-- X.例9.1: the selected local object satisfies the required NoCycle law. -/
theorem lawfulObject_noCycleLaw :
    FiniteModel.noCycleLaw.holds lawfulObject := by
  intro hcycle
  exact hcycle.1

/-- X.例9.1: concrete law-equation witness-ideal core over `ℤ`. -/
def lawEquationCore :
    LawAlgebra.SemanticLawEquationWitnessIdealCore FiniteModel.site where
  Observable _ := Int
  observableCommRing _ := inferInstance
  restrict _ := RingHom.id Int
  restrict_id := by
    intro _W x
    rfl
  restrict_comp := by
    intro _W₀ _W₁ _W₂ _f _g x
    rfl
  violationWitness _ _ _ := (2 : Int)
  violationWitness_restrict := by
    intro _source _target _f _lawIndex _atom
    rfl
  supportAtom := FiniteModel.FiniteAtom.componentA
  supportLawIndex := PUnit.unit
  supportLawIndex_required := rfl

/-- X.例9.1: displayed defect source whose defect lies in the selected witness ideal. -/
def defectSource :
    LawAlgebra.LawEquationDefectSource lawEquationCore where
  Chart := PUnit
  chart _ := FiniteModel.siteBase
  LocalInput _ := PUnit
  input _ := PUnit.unit
  lawSupport _ _ := [PUnit.unit]
  lawSupport_nonempty := by
    intro i
    exact ⟨PUnit.unit, by simp⟩
  lawSupport_required := by
    intro i lawIndex hmem
    cases lawIndex
    rfl
  objectOfLocalInput _ _ := lawfulObject
  defect _ _ := (2 : Int)
  holds_defect_mem := by
    intro i lawIndex hmem hrequired _hholds
    exact Ideal.subset_span
      ⟨FiniteModel.FiniteAtom.componentA, rfl⟩

/-- X.例9.1: displayed required laws hold on the selected lawful local input. -/
theorem displayedRequiredLawsHoldOn :
    defectSource.DisplayedRequiredLawsHoldOn := by
  intro i lawIndex hmem hrequired
  cases lawIndex
  exact lawfulObject_noCycleLaw

/-! ## End-to-end firing -/

/-- X.例9.1: top-cover gluing data for the singleton quotient presheaf. -/
def gluingData :
    Site.AATGluingData FiniteModel.site quotientPresheaf
      (⊤ : Sieve FiniteModel.siteBase) where
  localSections := fun _Y _f _hf => PUnit.unit
  overlapAgreement := by
    intro _Y _Z _W _f _g _hf _hg _w h₁ _hcomp
    rfl

/-- X.例9.1: true-sheaf certificate with `quotientIsSheaf` discharged as a theorem. -/
def trueSheafCertificate :
    boundaryAdditiveData.TrueSheafConditionCertificate
      FiniteModel.site quotientPresheaf (⊤ : Sieve FiniteModel.siteBase) where
  cover_mem := FiniteModel.site.top_mem FiniteModel.siteBase
  sheafCondition := quotientIsSheaf

/--
X.例9.1: lawful firing of theorem 7.5 on the concrete finite instance.

The packet is generated from the concrete law-equation source, the theorem-level
quotient sheaf certificate above, and the singleton H1 comparison data.
-/
theorem lawfulFiring_endToEndPacket :
    Nonempty
      (SemanticRepairGeneratedEndToEndSAGAPacket
        boundaryAdditiveData defectSource FiniteModel.site quotientPresheaf
        (⊤ : Sieve FiniteModel.siteBase) gluingData h1Comparison) :=
  lawEquation_constructs_groundedComparisonPacket
    boundaryAdditiveData defectSource displayedRequiredLawsHoldOn
    FiniteModel.site quotientPresheaf (⊤ : Sieve FiniteModel.siteBase)
    trueSheafCertificate gluingData h1Comparison

/--
X.例9.1: lawful firing through the generated-comparison theorem 7.5 route.

The returned pair contains the comparison generated from `h1Realization` and
the corresponding end-to-end SAGA packet.
-/
theorem lawfulFiring_endToEndPacket_fromRealization :
    Nonempty
      (Sigma fun comparison :
        SemanticRepairCoverRelativeH1Comparison
          boundaryAdditiveData.toAdditiveH1Surface coverRelativeComplex =>
          SemanticRepairGeneratedEndToEndSAGAPacket
            boundaryAdditiveData defectSource FiniteModel.site quotientPresheaf
            (⊤ : Sieve FiniteModel.siteBase) gluingData comparison) :=
  lawEquation_constructs_groundedComparisonPacket_fromRealization
    boundaryAdditiveData defectSource displayedRequiredLawsHoldOn
    FiniteModel.site quotientPresheaf (⊤ : Sieve FiniteModel.siteBase)
    trueSheafCertificate gluingData h1Realization

/--
X.例9.1: theorem 8.1 fires on the same lawful source, producing pointwise zero
and the selected degree-zero Cech-zero reading.
-/
theorem lawfulFiring_generatedSourceC0Zero :
    Nonempty (GeneratedSourceC0ZeroPackage defectSource) :=
  displayedRequiredLawsHoldOn_constructs_generatedSourceC0_zeroPackage
    defectSource displayedRequiredLawsHoldOn

/-! ## Circle-nerve nonzero transfer witness -/

/--
X.例9.2: degenerate witness-site coverage requirements used by the selected
circle nerve.

The selected nerve below is supplied simplicial data, not generated from chart
intersections.  These requirements deliberately have no admissible cover, so
the generated topology is the top-only witness topology used for the concrete
`F₂` coefficient sheaf.
-/
def circleCoverageRequirements :
    Site.CoverageRequirements FiniteModel.object
      FiniteModel.lawUniverse FiniteModel.signature where
  selectedReading := FiniteModel.lawUniverse.selectedReading
  requiredSupport := fun _ _ => True
  requiredWitness := fun _ _ => False
  requiredAxis := fun _ _ => False
  supportVisibleOn := fun _ _ => False
  witnessVisibleOn := fun _ _ => False
  axisReadableOn := fun _ _ => False
  boundaryVisibleOn := fun _ _ => False

/-- X.例9.2: selected witness site for the circle-nerve nonzero class. -/
def circleSite : Site.AATSite FiniteModel.object where
  contextPreorder := FiniteModel.siteContextPreorder
  lawUniverse := FiniteModel.lawUniverse
  signature := FiniteModel.signature
  requirements := circleCoverageRequirements
  overlap := FiniteModel.siteOverlap

/-- X.例9.2: base object for the selected circle witness site. -/
def circleSiteBase : circleSite.category :=
  Site.ContextCategoryObject.of FiniteModel.siteContextPreorder
    FiniteModel.siteContext

/-- X.例9.2: no admissible cover exists for the selected witness topology. -/
theorem circleCoverageFamily_impossible {base : circleSite.category}
    (F : Site.AATCoverageFamily circleCoverageRequirements
      FiniteModel.siteOverlap base) :
    False := by
  rcases F.admissible.atomSupportCoverage
      FiniteModel.FiniteAtom.componentA trivial with ⟨i, hi⟩
  exact hi

/-- X.例9.2: every covering sieve in the selected witness topology is top. -/
theorem circleSiteTopology_cover_eq_top {base : circleSite.category}
    {cover : Sieve base} (hcover : cover ∈ circleSite.topology base) :
    cover = ⊤ := by
  change
    (Site.admissiblePrecoverage circleCoverageRequirements
      FiniteModel.siteOverlap).Saturate base cover at hcover
  induction hcover with
  | of _X _S hS =>
      rcases hS with ⟨F, rfl⟩
      exact False.elim (circleCoverageFamily_impossible F)
  | top _X =>
      rfl
  | pullback _X _S _hS _Y _f ih =>
      rw [ih, Sieve.pullback_top]
  | transitive X S R _hS hR ihS ihR =>
      rw [← Sieve.id_mem_iff_eq_top]
      have hSid : S (𝟙 X) := by
        rw [Sieve.id_mem_iff_eq_top, ihS]
      have hlocal : R = ⊤ := by
        simpa using ihR hSid
      rw [hlocal]
      trivial

/-- X.例9.2: constant `F₂` coefficient presheaf on the circle witness site. -/
def circleF2Presheaf : Site.AATPresheaf circleSite where
  obj _ := ZMod 2
  map _ x := x
  map_id _ := rfl
  map_comp _ _ := rfl

/-- X.例9.2: the constant `F₂` presheaf is a sheaf on the witness topology. -/
theorem circleF2IsSheaf :
    Site.AATSheafCondition circleSite circleF2Presheaf := by
  intro _base cover hcover
  rw [Site.AATSheafConditionFor, circleSiteTopology_cover_eq_top hcover]
  exact Presieve.isSheafFor_top circleF2Presheaf

/-- X.例9.2: obstruction coefficient sheaf `Q ≅ F₂` for the circle witness. -/
def circleObstructionSheaf :
    Cohomology.ObstructionSheaf circleSite where
  carrier := {
    carrier := circleF2Presheaf
    isSheaf := circleF2IsSheaf
  }
  addCommGroup _ := by
    change AddCommGroup (ZMod 2)
    infer_instance
  map_zero := by
    intro _source _target _f
    rfl
  map_add := by
    intro _source _target _f _x _y
    rfl

/-- X.例9.2: supplied circle-nerve cover data. -/
def circleSimplex : Nat -> Type
  | 0 => Fin 3
  | 1 => Fin 3
  | _ + 2 => Unit

/-- X.例9.2: cyclic successor on the three selected circle vertices. -/
def circleNext (vertex : Fin 3) : Fin 3 :=
  ⟨(vertex.val + 1) % 3, Nat.mod_lt _ (by decide : 0 < 3)⟩

/-- X.例9.2: selected face map for the three-edge circle nerve. -/
def circleFace : ∀ n : Nat, Fin (n + 2) -> circleSimplex (n + 1) ->
    circleSimplex n
  | 0, i, edge => if i.val = 0 then circleNext edge else edge
  | 1, _i, _twoSimplex => (0 : Fin 3)
  | _ + 2, _i, _higherSimplex => ()

/-- X.例9.2: selected circle C0 cochains. -/
abbrev circleC0 : Type := Fin 3 -> ZMod 2

/-- X.例9.2: selected circle C1 cochains. -/
abbrev circleC1 : Type := Fin 3 -> ZMod 2

/-- X.例9.2: selected circle C2 cochains. -/
abbrev circleC2 : Type := Unit -> ZMod 2

/-- X.例9.2: selected circle Cech coboundary `d0`. -/
def circleD0 (cochain : circleC0) : circleC1 :=
  fun edge => cochain (circleNext edge) - cochain edge

/-- X.例9.2: selected residual one-cochain on the circle. -/
def circleResidual : circleC1 :=
  fun _ => (1 : ZMod 2)

/-- X.例9.2: selected zero one-cochain on the circle. -/
def circleZero1 : circleC1 :=
  fun _ => (0 : ZMod 2)

/-- X.例9.2: selected zero two-cochain on the circle. -/
def circleZero2 : circleC2 :=
  fun _ : Unit => (0 : ZMod 2)

/-- X.例9.2: the residual `1` on the three-edge circle is not a coboundary. -/
theorem circleResidual_not_coboundary :
    ¬ ∃ primitive : circleC0, circleResidual - circleZero1 = circleD0 primitive := by
  decide

/-- X.例9.2: supplied circle-nerve cover data. -/
def circleCoverRelativeCover :
    Cohomology.CoverRelativeCechCover circleSite where
  base := circleSiteBase
  Index := Fin 3
  chart _ := circleSiteBase
  inclusion _ := 𝟙 circleSiteBase
  simplex := circleSimplex
  overlap _ _ := circleSiteBase
  face := circleFace
  faceRestriction _ _ _ := 𝟙 circleSiteBase

/-- X.例9.2: selected three-edge circle complex over `F₂`. -/
def circleCoverRelativeComplex :
    Cohomology.CoverRelativeCechComplex
      circleCoverRelativeCover circleObstructionSheaf where
  cochainAddCommGroup n := by
    change AddCommGroup (circleSimplex n -> ZMod 2)
    infer_instance
  alternatingFaceCombination
    | 0, terms => fun edge =>
        (terms edge 0 : ZMod 2) - (terms edge 1 : ZMod 2)
    | _ + 1, _terms => fun _ => (0 : ZMod 2)
  differential
    | 0 => by
        change circleC0 →+ circleC1
        exact {
          toFun := circleD0
          map_zero' := by
            funext edge
            simp [circleD0]
          map_add' := by
            intro left right
            funext edge
            simp [circleD0]
            abel
        }
    | _ + 1 => by
        change (circleSimplex (_ + 1) -> ZMod 2) →+
          (circleSimplex (_ + 2) -> ZMod 2)
        exact {
          toFun := fun _ => fun _ => (0 : ZMod 2)
          map_zero' := by
            funext σ
            rfl
          map_add' := by
            intro _x _y
            funext σ
            rfl
        }
  differential_eq_alternatingFaceCombination := by
    intro n c
    cases n with
    | zero =>
        funext edge
        letI := circleObstructionSheaf.addCommGroup circleSiteBase
        dsimp [circleD0, circleFace, circleCoverRelativeCover,
          circleObstructionSheaf, circleF2Presheaf, Site.AATSheaf.toPresheaf]
        change circleD0 (c : circleC0) edge = _
        rfl
    | succ n =>
        funext σ
        change (0 : ZMod 2) = 0
        rfl
  differential_comp := by
    intro n _c
    cases n with
    | zero =>
        funext σ
        change (0 : ZMod 2) = 0
        rfl
    | succ n =>
        funext σ
        change (0 : ZMod 2) = 0
        rfl

/-- X.例9.2: semantic additive `H¹` surface with residual `1 ∈ F₂`. -/
def circleAdditiveH1Surface :
    SemanticRepairAdditiveH1Surface where
  C0 := circleC0
  C1 := circleC1
  C2 := circleC2
  zero1 := circleZero1
  zero2 := circleZero2
  delta0 := circleD0
  delta1 _ := circleZero2
  residual := circleResidual
  c0AddCommGroup := inferInstance
  c1AddCommGroup := inferInstance
  zero1_eq_zero := by
    funext edge
    rfl
  delta0_zero := by
    funext edge
    simp [circleD0]
  delta0_add := by
    intro left right
    funext edge
    simp [circleD0]
    abel
  delta0_neg := by
    intro primitive
    funext edge
    change
      (-primitive (circleNext edge) - -primitive edge) =
        -(primitive (circleNext edge) - primitive edge)
    abel
  zero1_cocycle := by
    funext σ
    rfl
  delta1_delta0_eq_zero := by
    intro _primitive
    funext σ
    rfl
  residual_cocycle := by
    funext σ
    rfl

/-- X.例9.2: the semantic residual circle cochain is not a semantic coboundary. -/
theorem circleSemantic_residual_not_coboundary :
    ¬ circleAdditiveH1Surface.Cohomologous
      ⟨circleResidual, circleAdditiveH1Surface.residual_cocycle⟩
      ⟨circleZero1, circleAdditiveH1Surface.zero1_cocycle⟩ :=
  circleResidual_not_coboundary

/-- X.例9.2: semantic additive residual class is nonzero in `H¹`. -/
theorem circleSemanticH1_nonzero :
    ¬ circleAdditiveH1Surface.H1Zero := by
  intro hzero
  exact circleSemantic_residual_not_coboundary (Quotient.exact hzero)

/-- X.例9.2: selected cover-relative residual cocycle. -/
def circleCoverRelativeResidualCocycle :
    circleCoverRelativeComplex.CechCocycle 1 where
  val := circleResidual
  property := by
    funext σ
    change (0 : ZMod 2) = 0
    rfl

/-- X.例9.2: selected cover-relative zero cocycle. -/
def circleCoverRelativeZeroCocycle :
    circleCoverRelativeComplex.CechCocycle 1 where
  val := circleZero1
  property := by
    funext σ
    change (0 : ZMod 2) = 0
    rfl

/-- X.例9.2: selected cover-relative residual class. -/
def circleCoverRelativeResidualClass :
    circleCoverRelativeComplex.CechCohomologySucc 0 :=
  circleCoverRelativeComplex.cohomologyClassSucc 0
    circleCoverRelativeResidualCocycle

/-- X.例9.2: selected cover-relative zero class. -/
def circleCoverRelativeZeroClass :
    circleCoverRelativeComplex.CechCohomologySucc 0 :=
  circleCoverRelativeComplex.cohomologyClassSucc 0
    circleCoverRelativeZeroCocycle

/-- X.例9.2: the cover-relative residual `1` is not a coboundary. -/
theorem circleCoverRelative_residual_not_coboundary :
    ¬ (circleCoverRelativeComplex.CechCoboundarySetoidSucc 0).r
      circleCoverRelativeResidualCocycle circleCoverRelativeZeroCocycle := by
  rintro ⟨primitive, hprimitive⟩
  have hzero :
      circleResidual - circleZero1 = circleD0 primitive := hprimitive
  exact circleResidual_not_coboundary ⟨primitive, hzero⟩

/-- X.例9.2: the cover-relative residual class is nonzero in `H¹`. -/
theorem circleCoverRelativeH1_nonzero :
    circleCoverRelativeResidualClass ≠ circleCoverRelativeZeroClass := by
  intro hzero
  exact circleCoverRelative_residual_not_coboundary (Quotient.exact hzero)

/--
X.例9.2: identity cochain comparison between the semantic additive surface and
the selected cover-relative circle complex.
-/
def circleH1Comparison :
    SemanticRepairCoverRelativeH1Comparison
      circleAdditiveH1Surface circleCoverRelativeComplex where
  c0Equiv := by
    change circleC0 ≃+ circleC0
    exact AddEquiv.refl circleC0
  c1Equiv := by
    change circleC1 ≃+ circleC1
    exact AddEquiv.refl circleC1
  c2Equiv := by
    change (Unit -> ZMod 2) ≃ (Unit -> ZMod 2)
    exact Equiv.refl (Unit -> ZMod 2)
  c2Equiv_zero := by
    funext σ
    rfl
  c2Equiv_symm_zero := by
    funext σ
    rfl
  d0_to := by
    intro primitive
    rfl
  d0_from := by
    intro primitive
    rfl
  d1_to := by
    intro _cochain
    funext σ
    change (0 : ZMod 2) = 0
    rfl
  d1_from := by
    intro _cochain
    funext σ
    change (0 : ZMod 2) = 0
    rfl

/-- X.例9.2: nonzero semantic class transfers across theorem 7.2 comparison. -/
theorem circleTransferredCoverRelativeH1_nonzero :
    ¬ circleH1Comparison.CoverRelativeResidualH1Zero := by
  intro hzero
  exact circleSemanticH1_nonzero
    ((SemanticRepairCoverRelativeH1Comparison.semanticRepairAdditiveH1Zero_iff_coverRelativeH1Zero
        circleH1Comparison).2 hzero)

/-- X.例9.2: concrete transfer packet for the circle-nerve nonzero class. -/
structure CircleNerveNonzeroTransferPacket where
  semanticResidualNonzero :
    ¬ circleAdditiveH1Surface.H1Zero
  coverRelativeResidualNonzero :
    circleCoverRelativeResidualClass ≠ circleCoverRelativeZeroClass
  transferredCoverRelativeNonzero :
    ¬ circleH1Comparison.CoverRelativeResidualH1Zero
  comparisonEquiv :
    circleAdditiveH1Surface.H1 ≃ circleCoverRelativeComplex.CechCohomologySucc 0
  zeroPredicateTransfer :
    circleAdditiveH1Surface.H1Zero <->
      circleH1Comparison.CoverRelativeResidualH1Zero

/--
X.例9.2: the selected circle nerve fires: both semantic and cover-relative
degree-one classes are nonzero, and theorem 7.2 transfers the nonzero reading
through the identity comparison.
-/
theorem circleNerve_nonzeroClassTransfer_packet :
    Nonempty CircleNerveNonzeroTransferPacket := by
  refine ⟨{
    semanticResidualNonzero := circleSemanticH1_nonzero
    coverRelativeResidualNonzero := circleCoverRelativeH1_nonzero
    transferredCoverRelativeNonzero :=
      circleTransferredCoverRelativeH1_nonzero
    comparisonEquiv :=
      SemanticRepairCoverRelativeH1Comparison.semanticRepairAdditiveH1_equiv_coverRelativeH1
        circleH1Comparison
    zeroPredicateTransfer :=
      SemanticRepairCoverRelativeH1Comparison.semanticRepairAdditiveH1Zero_iff_coverRelativeH1Zero
        circleH1Comparison
  }⟩

/--
R5 / IV-2: PRD-10 circle-nerve nonzero H1 instance fired as a Part IV
pseudo-circle golden example.
-/
def circlePartIVPseudoCircleFiring :
    Cohomology.FiniteExamples.PseudoCircleGolden.PartIVCircleNonzeroH1Firing
      circleCoverRelativeComplex where
  residualCocycle := circleCoverRelativeResidualCocycle
  zeroCocycle := circleCoverRelativeZeroCocycle
  h0WitnessCountingZero :=
    Cohomology.FiniteExamples.PseudoCircleGolden.h0_witness_counting_sees_no_obstruction
  coverRelativeResidualClass_nonzero := circleCoverRelativeH1_nonzero

/--
R5 / IV-2: the PRD-10 circle instance gives the Part IV reading "H0 sees no
obstruction, H1 is nonzero".
-/
theorem circlePartIV_h0_invisible_coverRelativeH1_nonzero :
    Cohomology.FiniteExamples.PseudoCircleGolden.witnessCountingObstruction = 0 ∧
      circleCoverRelativeComplex.cohomologyClassSucc 0
          circleCoverRelativeResidualCocycle ≠
        circleCoverRelativeComplex.cohomologyClassSucc 0
          circleCoverRelativeZeroCocycle :=
  Cohomology.FiniteExamples.PseudoCircleGolden.PartIVCircleNonzeroH1Firing.h0_invisible_and_coverRelativeH1_nonzero
    circlePartIVPseudoCircleFiring

/--
R5 / IV-2: the same circle instance read through the additive H1 quotient
surface introduced in IV-1.
-/
theorem circlePartIV_h0_invisible_additiveH1_nonzero :
    Cohomology.FiniteExamples.PseudoCircleGolden.witnessCountingObstruction = 0 ∧
      circleCoverRelativeComplex.additiveH1Class
          circleCoverRelativeResidualCocycle ≠
        circleCoverRelativeComplex.additiveH1Class
          circleCoverRelativeZeroCocycle :=
  Cohomology.FiniteExamples.PseudoCircleGolden.PartIVCircleNonzeroH1Firing.h0_invisible_and_additiveH1_nonzero
    circlePartIVPseudoCircleFiring

end SemanticRepairPart10
end Examples
end AAT.AG
